# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSExchFormat:ExchFormatList"
	bean-define = DSBean.AAADSExchFormat.ExchFormatList
	bean-name = ExchFormatList
	id = ExchFormatList_iD__1
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			id = C_51V
			table-column-count = 4 !
			table-columns-width = "25,25,25,25" !
		{
			--- TableColumn ---
				column-name = currencyCode !
				column-type = domain !
				domainAttribute = currencyCode !
				id = currencyCode
				table-column-width = 25
			{
				--- TableColumnItem ---
					item-column = currencyCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = underlyCurrencyCode !
				column-type = domain !
				domainAttribute = underlyCurrencyCode !
				id = underlyCurrencyCode
				table-column-width = 25
			{
				--- TableColumnItem ---
					item-column = underlyCurrencyCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = inverseF !
				column-type = domain !
				domainAttribute = inverseF !
				id = inverseF
				table-column-width = 25
			{
				--- TableColumnItem ---
					item-column = inverseF
					previewValue = value
			}
			--- TableColumn ---
				column-name = multiplyN !
				column-type = domain !
				domainAttribute = multiplyN !
				id = multiplyN
				table-column-width = 25
			{
				--- TableColumnItem ---
					item-column = multiplyN
					format = decimal.detailed
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = currencyCode
				sort-rank = 1
			--- TableSort ---
				sort-column-name = underlyCurrencyCode
				sort-rank = 2
		}
	}
}