# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Data Security Profile Search", fr = "Recherche de profil de sécurité des données", de = "Datensicherheitsprofil Suche"
	containment = container
	search = container
	id = DataSecuProfileSearch_Wl86_
	tid = 877799254452516
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/datasecuprofile/search/DataSecuProfileSearchInput.module
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/datasecuprofile/search/DataSecuProfileList.module
	}
}