# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Search Results", fr = "Résultats de la recherche", de = Suchergebnisse
	domainEntity = "AAADSDataSecuProf:DataSecuProfList"
	search = output
	bean-define = DSBean.AAADSDataSecuProf.DataSecuProfList
	bean-name = DataSecuProfList
	id = DataSecuProfileList_K91e0
	tid = 877838406265334
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			id = uM_38
			table-column-count = 1 !
			table-columns-width = 100 !
		{
			--- TableColumn ---
				column-name = code !
				column-type = domain !
				domainAttribute = code !
				type = text
				column-locked = true
				id = code
				table-column-width = 100
			{
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "com.odcgroup.tsl.wui.search.form.SearchFormHelper.isLookup(objectModel) == false"
						technicalName = NotLookup
						boxType = vertical
						isWidgetSelected = true
					{
						--- TableColumnItem ---
							toolTips en = "Select Business Unit", fr = "Sélectionner l\'unité business", de = "Geschäftseinheit auswählen"
							item-column = code
							previewValue = value
							tid = 377781664971297
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = select ud
								Query.beanValue1 = "<udp:item column=\"code\"/>" ud
								modal = false
								only-changed = false
								prevalidate = false
								searchOrigin = dataSecurityProfile ud
							}
						}
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetVisible = false
					{
						--- TableColumnItem ---
							toolTips en = "Select Business Unit", fr = "Sélectionner l\'unité business", de = "Geschäftseinheit auswählen"
							item-column = code
							previewValue = value
							tid = 377781680698498
						{
							Event OnClick (setWidgetValue)
							{
								widget-group-id = "<xsp:expr>com.odcgroup.tsl.wui.search.form.SearchFormHelper.getParentWidgetValue1Id(objectModel)</xsp:expr>"
								value = "<udp:item column=\"code\"/>"
								target = WUI_main
							}
							Event OnClick (winClose)
							{
								target = self
							}
						}
					}
				}
			}
			--- TableSort ---
				sort-column-name = code
				sort-rank = 1
		}
	}
}