# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "By Asset Class / Currency", de = "Per Anlagekategorie / Währung", fr = "Par catégorie d’actif / devise"
	domainEntity = "AAADSValuation:ValuationSummaryList"
	bean-define = DSBean.AAADSValuation.ValuationSummaryList
	bean-name = ValuationSummaryList
	id = AssetClassCurrencyMatrix_W__7B
	tid = 10515942999459
{
	--- Box ---
	{
		--- Matrix ---
			id = n_z_7
		{
			--- MatrixAxis ---
				domainAttribute = POS_CURRENCY !
				group-sorting-column-name = MKT_VAL
				group-sorting-direction = descending
				matrixAxis = x-axis !
			--- MatrixAxis ---
				domainAttribute = ASSET_CLASS_DENOM !
				group-sorting-column-name = MKT_VAL
				group-sorting-direction = descending
				matrixAxis = y-axis !
			--- MatrixContentCell ---
				matrixCellType = content-cell !
			{
				Snippet CssClass --- MatrixContentCellItem ---
					toolTips en = "Market Value", de = Marktwert, fr = "Valeur de marché"
					column-name = MKT_VAL_REF_CURR
					matrixCellItemType = computed !
					format = amount
					horizontalAlignment = trail
					verticalAlignment = lead
					id = X_8_3
					aggregationItems = "N9_4W,K_Kh7,U2_RX"
					column-computation = make-amount
					column-computation-parameters = "MKT_VAL,REF_CURRENCY"
					tid = 10081382411172
				--- Box ---
					boxType = vertical
					horizontalAlignment = center
				{
					--- MatrixContentCellItem ---
						column-name = MKT_VAL_PERC
						matrixCellItemType = computed !
						format = percent
						id = t14_q
						documentation = "Compute Percentage"
						aggregationItems = "l7__5,V_i_k,v_33_"
						column-computation = compute-percentage
						column-computation-parameters = MKT_VAL
				}
			}
			--- MatrixCell ---
				matrixCellType = last-cell !
			{
				--- MatrixCellItem ---
					column-name = comp_U2_RX
					matrixCellItemType = computed !
					id = U2_RX
				--- MatrixCellItem ---
					column-name = comp_v_33_
					matrixCellItemType = computed !
					id = v_33_
			}
			--- MatrixCell ---
				matrixCellType = last-row !
			{
				--- MatrixCellItem ---
					column-name = comp_K_Kh7
					matrixCellItemType = computed !
					id = K_Kh7 !
				--- MatrixCellItem ---
					column-name = comp_V_i_k
					matrixCellItemType = computed !
					id = V_i_k
			}
			--- MatrixCell ---
				matrixCellType = last-column !
			{
				--- MatrixCellItem ---
					column-name = comp_N9_4W
					matrixCellItemType = computed !
					id = N9_4W
				--- MatrixCellItem ---
					column-name = comp_l7__5
					matrixCellItemType = computed !
					id = l7__5
			}
			--- MatrixExtraColumn ---
				matrixCellType = extra-column !
		}
	}
}