# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSExtOperation:ExtOperationAll"
	cssClass = nodeco
	bean-define = DSBean.AAADSExtOperation.ExtOperationAll
	bean-name = ExtOperationAll
	id = AdditionalDataOther_TT_xy
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			id = S8W81
			indexOfSelectedChild = 0
		{
			--- Tab ---
				labels en = Communication
				id = tab_y___B
				isWidgetSelected = true
				tid = 664799851699028
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/extoperation/order/Communication.fragment
			}
			--- Tab ---
				labels en = Trading
				id = tab_w7s_X
				isWidgetVisible = false
				tid = 664799852710889
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/extoperation/order/TradingOther.fragment
			}
			--- Tab ---
				labels en = Fees
				id = tab_E_73g
				isWidgetVisible = false
				tid = 664799854605822
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/extoperation/order/FeesAndTaxes.fragment
			}
		}
	}
}