# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSExtOperation:ExtOperationAll"
	cssClass = nodeco
	bean-define = DSBean.AAADSExtOperation.ExtOperationAll
	bean-name = ExtOperationAll
	id = AdditionalData_K7__8
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			id = h7sFp
			indexOfSelectedChild = 0
		{
			--- Tab ---
				labels en = Communication, fr = Communication, de = Kommunikation
				id = tab_I5_S_
				isWidgetSelected = true
				tid = 662917209517969
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/extoperation/order/Communication.fragment
			}
			--- Tab ---
				labels de = Handel, fr = Marché, en = Trading
				id = tab_Hl_2o
				isWidgetVisible = false
				tid = 662917210239290
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/extoperation/order/Trading.fragment
			}
			--- Tab ---
				labels en = Booking, fr = Réservation, de = Verbuchung
				id = tab_w_J0_
				isWidgetVisible = false
				tid = 662917212276420
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/extoperation/order/Booking.fragment
			}
			--- Tab ---
				labels en = "Fees & Taxes", fr = "Fees & Taxes", de = "Fees & Taxes"
				id = tab_e4_2E
				isWidgetVisible = false
				tid = 662917214135316
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/extoperation/order/FeesAndTaxes.fragment
			}
		}
	}
}