# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Create Call Amendment Order", de = "Änderungsauftrag Kündigungsgeld erstellen", fr = "Créer un ordre de modification d\'appels"
	containment = container
	domainEntity = "AAADSExtOperation:ExtOperationAll"
	bean-define = DSBean.AAADSExtOperation.ExtOperationAll
	bean-name = ExtOperationAll
	id = CallAmendmentCreate_B6__5
	tid = 68999936733579
{
	--- Box ---
		boxType = vertical
	{
		--- TextArea ---
			domainAttribute = summaryC !
			columns = 200
			horizontalAlignment = "${corporatehalign}"
			rows = 1
			type = text
			bean-property = summaryC
			id = summaryC
		--- Box ---
			labels en = Identification, de = Identifikation, fr = Identification
			boxType = vertical
			tid = 5571900536434
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 4
				gridColumnsWidth = "25,25,25,25" !
				gridRowCount = 2
			{
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- LabelDomain ---
						labels en = Contract, de = Vertrag
						domainAttribute = sourceCode !
						for = sourceCode
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						tid = 161067478353813
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- TextField ---
						domainAttribute = sourceCode !
						horizontalAlignment = "${corporatehalign}"
						type = text
						chars = 20
						editable = false
						bean-property = sourceCode
						id = sourceCode
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- LabelDomain ---
						domainAttribute = valueD !
						for = valueD
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- CaldateField ---
						domainAttribute = valueD !
						format = datetime.date-only
						horizontalAlignment = "${corporatehalign}"
						type = datetime
						required = true
						bean-property = valueD
						id = valueD
					{
						Event OnChange (submit)
						{
							method = post
							call-URI = "<pageflow:continuation/>"
							widget-group-ref = form
							param = "flow-action=reload"
							only-changed = true
							modal = false
							prevalidate = false
						}
					}
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- LabelDomain ---
						domainAttribute = portfolio !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- Include ---
						domainAssociation = portfolio
						includeSrc = "" !
						resource:///default/defaultFragments/PortfolioIdentifierView.fragment
						bean-property-prefix = portfolio.
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- LabelDomain ---
						labels en = "Portfolio Name", de = "Portfolio Name", fr = "Nom du portefeuille"
						domainAttribute = portfolio !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						tid = 3301786532211496
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- Include ---
						domainAssociation = portfolio
						includeSrc = "" !
						resource:///default/extoperation/basicelements/PortfolioNameIdentifier.fragment
						bean-property-prefix = portfolio.
				}
			}
		}
		--- Box ---
			labels en = Instruction, de = Instruktion, fr = Instruction
			boxType = vertical
			tid = 5571900735284
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 4
				gridColumnsWidth = "25,25,25,25" !
				gridRowCount = 2
			{
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- LabelDomain ---
						labels en = Amount, fr = Montant, de = Betrag
						domainAttribute = quantityN !
						for = quantityN
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						tid = 5571914899391
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- Box ---
					{
						--- TextField ---
							domainAttribute = quantityN !
							columns = 21
							format = decimal.detailed
							horizontalAlignment = "${corporatehalign}"
							type = decimal
							allow = "\'0123456789.,\'"
							chars = 23
							required = true
							bean-property = quantityN
							id = quantityN
						{
							Event OnChange (submit)
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								widget-group-ref = form
								param = "flow-action=reload"
								only-changed = true
								modal = false
								prevalidate = false
							}
						}
						--- Include ---
							domainAssociation = account
							includeSrc = "" !
							resource:///default/defaultFragments/InstrumentIdentifierView.fragment
							bean-property-prefix = account.
						--- Include ---
							domainAssociation = accCurrency
							includeSrc = "" !
							resource:///default/defaultFragments/CurrencyIdentifierView.fragment
							bean-property-prefix = accCurrency.
					}
				}
				--- GridCell ---
					gridColumnWidth = 25
				--- GridCell ---
					gridColumnWidth = 25
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- LabelDomain ---
						domainAttribute = rateP !
						for = rateP
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- TextField ---
						domainAttribute = rateP !
						columns = 11
						format = decimal.5-digits
						horizontalAlignment = "${corporatehalign}"
						type = percent
						allow = "\'0123456789.,\'"
						chars = 11
						editable = false
						bean-property = rateP
						id = rateP
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- LabelDomain ---
						domainAttribute = counterpartyThird !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- Include ---
						domainAssociation = counterpartyThird
						includeSrc = "" !
						resource:///default/defaultFragments/ThirdPartyIdentifierView.fragment
						bean-property-prefix = counterpartyThird.
				}
			}
		}
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/extoperation/order/create/SecurityCommunicationCreate.module
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/extoperation/order/create/OrderTradingCreate.module
		--- Grid ---
			cssClass = blank
			gridColumnCount = 4
			gridColumnsWidth = "25,25,25,25" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Button ---
					labels en = Save, de = Speichern, fr = Sauver
					id = btn_il_6_
					tid = 5571925599334
				{
					Event OnClick (submit)
					tid = 279966347425074
					messages en = "Are you sure to submit this order ?", de = "Wollen Sie diesen Auftrag wirklich senden?", fr = "Etes-vous sûr de soumettre cet ordre?"
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						widget-group-ref = form
						param = "flow-action=create"
						only-changed = true
						modal = false
						prevalidate = false
					}
				}
				--- Button ---
					labels en = Cancel, de = Abbrechen, fr = Annuler
					id = btn_ik_16
					tid = 5571925990169
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						flow-action = cancel ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
		}
	}
}