# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSExtOperation:ExtOperationAll"
	cssClass = nodeco
	bean-define = DSBean.AAADSExtOperation.ExtOperationAll
	bean-name = ExtOperationAll
	id = FeesAndTaxesCreate_sU90B
{
	--- Box ---
		labels en = "Fees & Taxes", de = "Fees & Taxes", fr = "Frais & Taxes"
		boxType = vertical
		tid = 22069723747571
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 4
			gridColumnsWidth = "25,25,25,25" !
			gridRowCount = 2
		{
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- LabelDomain ---
					labels en = "Fees 1", fr = "Fees 1", de = "Fees 1"
					domainAttribute = bp1AmountM !
					for = bp1AmountM
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					tid = 23631698034526
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/extoperation/basicelements/Fees1View.fragment
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- LabelDomain ---
					labels en = "Taxes 1", fr = "Taxes 1", de = "Taxes 1"
					domainAttribute = bp6AmountM !
					for = bp6AmountM
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					tid = 23679073106218
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/extoperation/basicelements/Taxes1View.fragment
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- LabelDomain ---
					labels en = "Fees 2", fr = "Fees 2", de = "Fees 2"
					domainAttribute = bp2AmountM !
					for = bp2AmountM
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					tid = 23648004850616
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/extoperation/basicelements/Fees2View.fragment
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- LabelDomain ---
					labels en = "Taxes 2", fr = "Taxes 2", de = "Taxes 2"
					domainAttribute = bp7AmountM !
					for = bp7AmountM
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					tid = 23693696936342
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/extoperation/basicelements/Taxes2View.fragment
			}
		}
	}
}