# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Create Forex Order", de = "Devisenkassa-Auftrag erstellen"
	containment = container
	domainEntity = "AAADSExtOperation:ExtOperationAll"
	cssClass = nodeco
	bean-define = DSBean.AAADSExtOperation.ExtOperationAll
	bean-name = ExtOperationAll
	id = FxSpotNoButtonCreate_OkLS1
	tid = 703599561713011
{
	--- Box ---
		boxType = vertical
	{
		--- TextArea ---
			domainAttribute = summaryC !
			columns = 200
			horizontalAlignment = "${corporatehalign}"
			rows = 1
			type = text
			editable = false
			bean-property = summaryC
			id = summaryC
		--- Box ---
			labels en = Identification, de = Identifikation, fr = Identification
			boxType = vertical
			tid = 703599562490763
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 4
				gridColumnsWidth = "25,25,25,25" !
				gridRowCount = 2
			{
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- LabelDomain ---
						domainAttribute = natureE !
						for = natureE
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- Conditional ---
						indexOfSelectedChild = 1
					{
						--- ConditionalBody ---
							javaCode = "null != <bean:get-property bean=\"ExtOperationAll\" property=\"orderType\"/> &amp;&amp; \r\n(\"PCK_DS_ACCT_SAME_CCY\".equals(<bean:get-property bean=\"ExtOperationAll\" property=\"orderType.code\"/>.toString()))"
							technicalName = Condition
							isWidgetVisible = false
						{
							--- Code ---
								code = "<xgui:combobox id=\"natureE\" required=\"true\" widget-group=\"form\">\r\n  <xgui:selected-value>\r\n\t<bean:get-property bean=\"ExtOperationAll\" property=\"natureE\"/>\r\n  </xgui:selected-value>\r\n  <xgui:item>\r\n\t<xgui:value>1</xgui:value>\r\n\t<xgui:text>\r\n\t  <i18n:text>forex.ACCT_SAME_CCY.buy.text</i18n:text>\r\n\t</xgui:text>\r\n  </xgui:item>\r\n  <xgui:item>\r\n\t<xgui:value>2</xgui:value>\r\n\t<xgui:text>\r\n\t  <i18n:text>forex.ACCT_SAME_CCY.sell.text</i18n:text>\r\n\t</xgui:text>\r\n  </xgui:item>\r\n  <xgui:onevent type=\"change\">\r\n\t<xgui:submit method=\"post\" only-changed=\"true\" param=\"flow-action=newOpNatOrder\" widget-group-ref=\"form\">\r\n\t  <xsp:attribute name=\"call-URI\"><pageflow:continuation/></xsp:attribute>\r\n\t  <xgui:param name=\"orderType.code\"><bean:get-property bean=\"ExtOperationAll\" property=\"orderType.code\"/></xgui:param>\r\n\t</xgui:submit>\r\n  </xgui:onevent>\r\n</xgui:combobox>"
						}
						--- ConditionalBody ---
							javaCode = true
							technicalName = Default
							boxType = vertical
							isWidgetSelected = true
						{
							--- Code ---
								code = "<xgui:combobox id=\"natureE\" required=\"true\" widget-group=\"form\">\r\n  <xgui:selected-value>\r\n\t<bean:get-property bean=\"ExtOperationAll\" property=\"natureE\"/>\r\n  </xgui:selected-value>\r\n  <xgui:item>\r\n\t<xgui:value>1</xgui:value>\r\n\t<xgui:text>\r\n\t  <i18n:text>aaaenumerations.operationnaturee.1.text</i18n:text>\r\n\t</xgui:text>\r\n  </xgui:item>\r\n  <xgui:item>\r\n\t<xgui:value>2</xgui:value>\r\n\t<xgui:text>\r\n\t  <i18n:text>aaaenumerations.operationnaturee.2.text</i18n:text>\r\n\t</xgui:text>\r\n  </xgui:item>\r\n  <xgui:onevent type=\"change\">\r\n\t<xgui:submit method=\"post\" only-changed=\"true\" param=\"flow-action=newOpNatOrder\" widget-group-ref=\"form\">\r\n\t  <xsp:attribute name=\"call-URI\"><pageflow:continuation/></xsp:attribute>\r\n\t  <xgui:param name=\"orderType.code\"><bean:get-property bean=\"ExtOperationAll\" property=\"orderType.code\"/></xgui:param>\r\n\t</xgui:submit>\r\n  </xgui:onevent>\r\n</xgui:combobox>"
						}
					}
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- LabelDomain ---
						labels en = Type
						domainAttribute = orderType !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						tid = 435383098728469
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- Include ---
						domainAssociation = orderType
						includeSrc = "" !
						resource:///default/defaultFragments/TypeIdentifierRequiredReload.fragment
						bean-property-prefix = orderType.
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- LabelDomain ---
						domainAttribute = portfolio !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- Include ---
						domainAssociation = portfolio
						includeSrc = "" !
						resource:///default/extoperation/basicelements/PortfolioSearch.fragment
						bean-property-prefix = portfolio.
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- LabelDomain ---
						labels en = "Portfolio Name", de = "Portfolio Name", fr = "Nom du portefeuille"
						domainAttribute = portfolio !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						tid = 703599564420059
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- Box ---
					{
						--- Include ---
							domainAssociation = portfolio
							includeSrc = "" !
							resource:///default/extoperation/basicelements/PortfolioNameIdentifier.fragment
							bean-property-prefix = portfolio.
						--- Conditional ---
							indexOfSelectedChild = 0
						{
							--- ConditionalBody ---
								javaCode = "null != <bean:get-property bean=\"ExtOperationAll\" property=\"portfolio.code\"/>"
								technicalName = "ptf!=null"
								boxType = vertical
								isWidgetSelected = true
							{
								--- Icon ---
									icon = application_form_magnify
									id = u4952
								{
									Event OnClick (submit) S
									{
										method = post
										call-URI = "resource:///administration/portfolio/PortfolioView.pageflow"
										target = layer
										code = "<bean:get-property bean=\"ExtOperationAll\" property=\"portfolio.code\"/>" ud
										modal = false
										only-changed = false
										prevalidate = false
									}
								}
							}
							--- ConditionalBody ---
								javaCode = true
								technicalName = Default
								boxType = vertical
								isWidgetVisible = false
						}
					}
				}
			}
		}
		--- Conditional ---
			indexOfSelectedChild = 0
		{
			--- ConditionalBody ---
				javaCode = "null != <bean:get-property bean=\"ExtOperationAll\" property=\"portfolio\"/> &amp;&amp; null != <bean:get-property bean=\"ExtOperationAll\" property=\"portfolio.code\"/>"
				technicalName = IsPtfSelected
				boxType = vertical
				isWidgetSelected = true
			{
				--- Conditional ---
					indexOfSelectedChild = 1
				{
					--- ConditionalBody ---
						javaCode = "Integer.toString(com.odcgroup.aaa.OperationNatureE.Sell).equals(<bean:get-property bean=\"ExtOperationAll\" property=\"natureE\"/>.toString()) &amp;&amp; \r\nnull != <bean:get-property bean=\"ExtOperationAll\" property=\"orderType\"/> &amp;&amp; \r\n(\"PCK_DS_FXSPOT_NEGO\".equals(<bean:get-property bean=\"ExtOperationAll\" property=\"orderType.code\"/>.toString()) ||\r\n\"PCK_DS_FXSPOT_CONV\".equals(<bean:get-property bean=\"ExtOperationAll\" property=\"orderType.code\"/>.toString()))"
						technicalName = IsSellFxSpot
						boxType = vertical
						isWidgetVisible = false
					{
						--- Box ---
							labels en = Instruction, de = Instruktion, fr = Instruction
							boxType = vertical
							tid = 703599566383157
						{
							--- Grid ---
								cssClass = blank
								gridColumnCount = 4
								gridColumnsWidth = "25,25,25,25" !
								gridRowCount = 3
							{
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = Sell
										domainAttribute = opCurrency !
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 27498309811721
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- Include ---
											domainAssociation = opCurrency
											includeSrc = "" !
											resource:///default/defaultFragments/CurrencyIdentifier.fragment
											bean-property-prefix = opCurrency.
										--- TextField ---
											domainAttribute = quantityN !
											columns = 21
											format = decimal
											horizontalAlignment = "${corporatehalign}"
											type = decimal
											allow = "\'0123456789.,\'"
											chars = 23
											required = true
											bean-property = quantityN
											id = quantityN
										{
											Event OnChange (submit)
											{
												method = post
												call-URI = "<pageflow:continuation/>"
												widget-group-ref = form
												target = self
												param = "flow-action=reload"
												only-changed = true
												modal = false
												prevalidate = false
											}
										}
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = Buy
										domainAttribute = accCurrency !
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 531510415037665
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- Include ---
											domainAssociation = accCurrency
											includeSrc = "" !
											resource:///default/defaultFragments/CurrencyIdentifier.fragment
											bean-property-prefix = accCurrency.
										--- TextField ---
											domainAttribute = accNetAmountM !
											columns = 21
											format = decimal
											type = amount
											chars = 18
											editable = false
											bean-property = accNetAmountM
											id = accNetAmountM
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = "Debited Account"
										domainAttribute = instr !
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 531020090108100
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- Include ---
											domainAssociation = instr
											includeSrc = "" !
											resource:///default/defaultFragments/InstrumentAccountIdentifier.fragment
											bean-property-prefix = instr.
										--- Include ---
											domainAssociation = opCurrency
											includeSrc = "" !
											resource:///default/defaultFragments/CurrencyIdentifierView.fragment
											bean-property-prefix = opCurrency.
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = "Credited Account"
										domainAttribute = account !
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 531677257317899
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- Include ---
											domainAssociation = account
											includeSrc = "" !
											resource:///default/defaultFragments/InstrumentAccountIdentifier.fragment
											bean-property-prefix = account.
										--- Include ---
											domainAssociation = accCurrency
											includeSrc = "" !
											resource:///default/defaultFragments/CurrencyIdentifierView.fragment
											bean-property-prefix = accCurrency.
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								--- GridCell ---
									gridColumnWidth = 25
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										domainAttribute = valueD !
										for = valueD
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- CaldateField ---
										domainAttribute = valueD !
										format = datetime.date-only
										horizontalAlignment = "${corporatehalign}"
										type = datetime
										bean-property = valueD
										id = valueD
								}
							}
						}
					}
					--- ConditionalBody ---
						javaCode = "Integer.toString(com.odcgroup.aaa.OperationNatureE.Buy).equals(<bean:get-property bean=\"ExtOperationAll\" property=\"natureE\"/>.toString()) &amp;&amp; \r\nnull != <bean:get-property bean=\"ExtOperationAll\" property=\"orderType\"/> &amp;&amp; \r\n(\"PCK_DS_FXSPOT_NEGO\".equals(<bean:get-property bean=\"ExtOperationAll\" property=\"orderType.code\"/>.toString()) ||\r\n\"PCK_DS_FXSPOT_CONV\".equals(<bean:get-property bean=\"ExtOperationAll\" property=\"orderType.code\"/>.toString()))"
						technicalName = IsBuyFxSpot
						boxType = vertical
						isWidgetSelected = true
					{
						--- Box ---
							labels en = Instruction, fr = Instruction, de = Instruktion
							boxType = vertical
							tid = 703599576146689
						{
							--- Grid ---
								cssClass = blank
								gridColumnCount = 4
								gridColumnsWidth = "25,25,25,25" !
								gridRowCount = 3
							{
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = Buy
										domainAttribute = opCurrency !
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 27441343923040
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- Include ---
											domainAssociation = opCurrency
											includeSrc = "" !
											resource:///default/defaultFragments/CurrencyIdentifier.fragment
											bean-property-prefix = opCurrency.
										--- TextField ---
											domainAttribute = quantityN !
											columns = 21
											format = decimal
											horizontalAlignment = "${corporatehalign}"
											type = decimal
											allow = "\'0123456789.,\'"
											chars = 23
											required = true
											bean-property = quantityN
											id = quantityN
										{
											Event OnChange (submit)
											{
												method = post
												call-URI = "<pageflow:continuation/>"
												widget-group-ref = form
												target = self
												param = "flow-action=reload"
												only-changed = true
												prevalidate = false
												modal = false
											}
										}
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = Sell
										domainAttribute = accCurrency !
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 531542837208080
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- Include ---
											domainAssociation = accCurrency
											includeSrc = "" !
											resource:///default/defaultFragments/CurrencyIdentifier.fragment
											bean-property-prefix = accCurrency.
										--- TextField ---
											domainAttribute = accNetAmountM !
											columns = 21
											format = decimal
											type = amount
											chars = 23
											editable = false
											required = true
											bean-property = accNetAmountM
											id = accNetAmountM
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = "Credited Account"
										domainAttribute = instr !
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 531106958479639
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- Include ---
											domainAssociation = instr
											includeSrc = "" !
											resource:///default/defaultFragments/InstrumentAccountIdentifier.fragment
											bean-property-prefix = instr.
										--- Include ---
											domainAssociation = opCurrency
											includeSrc = "" !
											resource:///default/defaultFragments/CurrencyIdentifierView.fragment
											bean-property-prefix = opCurrency.
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = "Debited Account", de = "Belastetes Konto", fr = "Compte débité"
										domainAttribute = account !
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										required = true
										tid = 703599580048861
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- Include ---
											domainAssociation = account
											includeSrc = "" !
											resource:///default/defaultFragments/InstrumentAccountIdentifier.fragment
											bean-property-prefix = account.
										--- Include ---
											domainAssociation = accCurrency
											includeSrc = "" !
											resource:///default/defaultFragments/CurrencyIdentifierView.fragment
											bean-property-prefix = accCurrency.
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								--- GridCell ---
									gridColumnWidth = 25
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										domainAttribute = valueD !
										for = valueD
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- CaldateField ---
										domainAttribute = valueD !
										format = datetime.date-only
										horizontalAlignment = "${corporatehalign}"
										type = datetime
										bean-property = valueD
										id = valueD
								}
							}
						}
					}
					--- ConditionalBody ---
						javaCode = "Integer.toString(com.odcgroup.aaa.OperationNatureE.Buy).equals(<bean:get-property bean=\"ExtOperationAll\" property=\"natureE\"/>.toString()) &amp;&amp; \r\nnull != <bean:get-property bean=\"ExtOperationAll\" property=\"orderType\"/> &amp;&amp; \r\n(\"PCK_DS_FXFWD_NEGO\".equals(<bean:get-property bean=\"ExtOperationAll\" property=\"orderType.code\"/>.toString()) ||\r\n\"PCK_DS_FXFWD_CONV\".equals(<bean:get-property bean=\"ExtOperationAll\" property=\"orderType.code\"/>.toString()))"
						technicalName = IsBuyFxForward
						boxType = vertical
						isWidgetVisible = false
					{
						--- Box ---
							labels en = Instruction, fr = Instruction, de = Instruktion
							boxType = vertical
							tid = 435062721072370
						{
							--- Grid ---
								cssClass = blank
								gridColumnCount = 4
								gridColumnsWidth = "25,25,25,25" !
								gridRowCount = 3
							{
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = Buy
										domainAttribute = acc2Currency !
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 25920274007171
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- Include ---
											domainAssociation = acc2Currency
											includeSrc = "" !
											resource:///default/defaultFragments/CurrencyIdentifier.fragment
											bean-property-prefix = acc2Currency.
										--- TextField ---
											domainAttribute = quantityN !
											columns = 21
											format = decimal
											horizontalAlignment = "${corporatehalign}"
											type = decimal
											allow = "\'0123456789.,\'"
											chars = 23
											required = true
											bean-property = quantityN
											id = quantityN
										{
											Event OnChange (submit)
											{
												method = post
												call-URI = "<pageflow:continuation/>"
												widget-group-ref = form
												param = "flow-action=reload"
												only-changed = true
												modal = false
												prevalidate = false
											}
										}
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = Sell
										domainAttribute = opCurrency !
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 19720832398810
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- Include ---
											domainAssociation = opCurrency
											includeSrc = "" !
											resource:///default/defaultFragments/CurrencyIdentifier.fragment
											bean-property-prefix = opCurrency.
										--- TextField ---
											domainAttribute = accNetAmountM !
											columns = 16
											format = decimal
											horizontalAlignment = "${corporatehalign}"
											type = amount
											chars = 18
											editable = false
											bean-property = accNetAmountM
											id = accNetAmountM
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = "Credited Account"
										domainAttribute = account2 !
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 26000138225947
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- Include ---
											domainAssociation = account2
											includeSrc = "" !
											resource:///default/defaultFragments/InstrumentAccountIdentifier.fragment
											bean-property-prefix = account2.
										--- Include ---
											domainAssociation = acc2Currency
											includeSrc = "" !
											resource:///default/defaultFragments/CurrencyIdentifierView.fragment
											bean-property-prefix = acc2Currency.
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = "Debited Account"
										domainAttribute = account !
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 19747584036797
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- Include ---
											domainAssociation = account
											includeSrc = "" !
											resource:///default/defaultFragments/InstrumentAccountIdentifier.fragment
											bean-property-prefix = account.
										--- Include ---
											domainAssociation = accCurrency
											includeSrc = "" !
											resource:///default/defaultFragments/CurrencyIdentifierView.fragment
											bean-property-prefix = accCurrency.
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = Length
										domainAttribute = contractLengthN !
										for = contractLengthN
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 437437523455076
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- TextField ---
										domainAttribute = contractLengthN !
										columns = 9
										format = integer
										horizontalAlignment = "${corporatehalign}"
										type = integer
										chars = 9
										required = true
										bean-property = contractLengthN
										id = contractLengthN
									{
										Event OnChange (submit)
										{
											method = post
											call-URI = "<pageflow:continuation/>"
											widget-group-ref = form
											target = self
											param = "flow-action=reload"
											only-changed = true
											modal = false
											prevalidate = false
										}
									}
									--- ComboBox ---
										domainAttribute = contractLengthUnitE !
										horizontalAlignment = "${corporatehalign}"
										required = true
										bean-property = contractLengthUnitE
										id = contractLengthUnitE
									{
										Event OnChange (submit)
										{
											method = post
											call-URI = "<pageflow:continuation/>"
											widget-group-ref = form
											target = self
											param = "flow-action=reload"
											only-changed = true
											modal = false
											prevalidate = false
										}
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										domainAttribute = valueD !
										for = valueD
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- CaldateField ---
										domainAttribute = valueD !
										format = datetime.date-only
										horizontalAlignment = "${corporatehalign}"
										type = datetime
										required = true
										bean-property = valueD
										id = valueD
									{
										Event OnChange (submit)
										{
											method = post
											call-URI = "<pageflow:continuation/>"
											widget-group-ref = form
											param = "flow-action=reload"
											only-changed = true
											modal = false
											prevalidate = false
										}
									}
								}
							}
						}
					}
					--- ConditionalBody ---
						javaCode = "Integer.toString(com.odcgroup.aaa.OperationNatureE.Sell).equals(<bean:get-property bean=\"ExtOperationAll\" property=\"natureE\"/>.toString()) &amp;&amp; \r\nnull != <bean:get-property bean=\"ExtOperationAll\" property=\"orderType\"/> &amp;&amp; \r\n(\"PCK_DS_FXFWD_NEGO\".equals(<bean:get-property bean=\"ExtOperationAll\" property=\"orderType.code\"/>.toString()) ||\r\n\"PCK_DS_FXFWD_CONV\".equals(<bean:get-property bean=\"ExtOperationAll\" property=\"orderType.code\"/>.toString()))"
						technicalName = isSellFxForward
						boxType = vertical
						isWidgetVisible = false
					{
						--- Box ---
							labels en = Instruction, de = Instruktion, fr = Instruction
							boxType = vertical
							tid = 435135041466443
						{
							--- Grid ---
								cssClass = blank
								gridColumnCount = 4
								gridColumnsWidth = "25,25,25,25" !
								gridRowCount = 3
							{
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = Sell
										domainAttribute = acc2Currency !
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 26099236303496
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- Include ---
											domainAssociation = acc2Currency
											includeSrc = "" !
											resource:///default/defaultFragments/CurrencyIdentifier.fragment
											bean-property-prefix = acc2Currency.
										--- TextField ---
											domainAttribute = quantityN !
											columns = 21
											format = decimal
											horizontalAlignment = "${corporatehalign}"
											type = decimal
											allow = "\'0123456789.,\'"
											chars = 23
											required = true
											bean-property = quantityN
											id = quantityN
										{
											Event OnChange (submit)
											{
												method = post
												call-URI = "<pageflow:continuation/>"
												widget-group-ref = form
												param = "flow-action=reload"
												only-changed = true
												modal = false
												prevalidate = false
											}
										}
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = Buy
										domainAttribute = opCurrency !
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 21180839360868
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- Include ---
											domainAssociation = opCurrency
											includeSrc = "" !
											resource:///default/defaultFragments/CurrencyIdentifier.fragment
											bean-property-prefix = opCurrency.
										--- TextField ---
											domainAttribute = accNetAmountM !
											columns = 16
											format = decimal
											horizontalAlignment = "${corporatehalign}"
											type = amount
											chars = 18
											editable = false
											bean-property = accNetAmountM
											id = accNetAmountM
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = "Debited Account"
										domainAttribute = account2 !
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 21180841301897
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- Include ---
											domainAssociation = account2
											includeSrc = "" !
											resource:///default/defaultFragments/InstrumentAccountIdentifier.fragment
											bean-property-prefix = account2.
										--- Include ---
											domainAssociation = acc2Currency
											includeSrc = "" !
											resource:///default/defaultFragments/CurrencyIdentifierView.fragment
											bean-property-prefix = acc2Currency.
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = "Credited Account"
										domainAttribute = account !
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 21180843232589
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- Include ---
											domainAssociation = account
											includeSrc = "" !
											resource:///default/defaultFragments/InstrumentAccountIdentifier.fragment
											bean-property-prefix = account.
										--- Include ---
											domainAssociation = accCurrency
											includeSrc = "" !
											resource:///default/defaultFragments/CurrencyIdentifierView.fragment
											bean-property-prefix = accCurrency.
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = Length
										domainAttribute = contractLengthN !
										for = contractLengthN
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 21180845197085
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- TextField ---
										domainAttribute = contractLengthN !
										columns = 9
										format = integer
										horizontalAlignment = "${corporatehalign}"
										type = integer
										chars = 9
										required = true
										bean-property = contractLengthN
										id = contractLengthN
									{
										Event OnChange (submit)
										{
											method = post
											call-URI = "<pageflow:continuation/>"
											widget-group-ref = form
											target = self
											param = "flow-action=reload"
											only-changed = true
											modal = false
											prevalidate = false
										}
									}
									--- ComboBox ---
										domainAttribute = contractLengthUnitE !
										horizontalAlignment = "${corporatehalign}"
										required = true
										bean-property = contractLengthUnitE
										id = contractLengthUnitE
									{
										Event OnChange (submit)
										{
											method = post
											call-URI = "<pageflow:continuation/>"
											widget-group-ref = form
											target = self
											param = "flow-action=reload"
											only-changed = true
											modal = false
											prevalidate = false
										}
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										domainAttribute = valueD !
										for = valueD
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- CaldateField ---
										domainAttribute = valueD !
										format = datetime.date-only
										horizontalAlignment = "${corporatehalign}"
										type = datetime
										required = true
										bean-property = valueD
										id = valueD
									{
										Event OnChange (submit)
										{
											method = post
											call-URI = "<pageflow:continuation/>"
											widget-group-ref = form
											param = "flow-action=reload"
											only-changed = true
											modal = false
											prevalidate = false
										}
									}
								}
							}
						}
					}
					--- ConditionalBody ---
						javaCode = "Integer.toString(com.odcgroup.aaa.OperationNatureE.Sell).equals(<bean:get-property bean=\"ExtOperationAll\" property=\"natureE\"/>.toString()) &amp;&amp; \r\nnull != <bean:get-property bean=\"ExtOperationAll\" property=\"orderType\"/> &amp;&amp; \r\n(\"PCK_DS_ACCT_SAME_CCY\".equals(<bean:get-property bean=\"ExtOperationAll\" property=\"orderType.code\"/>.toString()))"
						technicalName = "Transfer From"
						boxType = vertical
						isWidgetVisible = false
					{
						--- Box ---
							labels en = Instruction, de = Instruktion, fr = Instruction
							boxType = vertical
							tid = 75619782816256
						{
							--- Grid ---
								cssClass = blank
								gridColumnCount = 4
								gridColumnsWidth = "25,25,25,25" !
								gridRowCount = 3
							{
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = "Amount to Debit"
										domainAttribute = opCurrency !
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 75619785025058
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- Include ---
											domainAssociation = opCurrency
											includeSrc = "" !
											resource:///default/defaultFragments/CurrencyIdentifier.fragment
											bean-property-prefix = opCurrency.
										--- TextField ---
											domainAttribute = quantityN !
											columns = 21
											format = decimal
											horizontalAlignment = "${corporatehalign}"
											type = decimal
											allow = "\'0123456789.,\'"
											chars = 23
											required = true
											bean-property = quantityN
											id = quantityN
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = "Received Amount"
										domainAttribute = accCurrency !
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 75619785976331
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- Include ---
											domainAssociation = accCurrency
											includeSrc = "" !
											resource:///default/defaultFragments/CurrencyIdentifierView.fragment
											bean-property-prefix = accCurrency.
										--- TextField ---
											domainAttribute = accNetAmountM !
											columns = 21
											format = decimal
											type = amount
											chars = 18
											editable = false
											bean-property = accNetAmountM
											id = accNetAmountM
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = "Debited Account"
										domainAttribute = instr !
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 75619787025127
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- Include ---
											domainAssociation = instr
											includeSrc = "" !
											resource:///default/defaultFragments/InstrumentAccountIdentifier.fragment
											bean-property-prefix = instr.
										--- Include ---
											domainAssociation = opCurrency
											includeSrc = "" !
											resource:///default/defaultFragments/CurrencyIdentifierView.fragment
											bean-property-prefix = opCurrency.
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = "Credited Account"
										domainAttribute = account !
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 75619787997787
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- Include ---
											domainAssociation = account
											includeSrc = "" !
											resource:///default/defaultFragments/InstrumentAccountIdentifier.fragment
											bean-property-prefix = account.
										--- Include ---
											domainAssociation = accCurrency
											includeSrc = "" !
											resource:///default/defaultFragments/CurrencyIdentifierView.fragment
											bean-property-prefix = accCurrency.
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								--- GridCell ---
									gridColumnWidth = 25
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										domainAttribute = valueD !
										for = valueD
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- CaldateField ---
										domainAttribute = valueD !
										format = datetime.date-only
										horizontalAlignment = "${corporatehalign}"
										type = datetime
										bean-property = valueD
										id = valueD
								}
							}
						}
					}
					--- ConditionalBody ---
						javaCode = "Integer.toString(com.odcgroup.aaa.OperationNatureE.Buy).equals(<bean:get-property bean=\"ExtOperationAll\" property=\"natureE\"/>.toString()) &amp;&amp; \r\nnull != <bean:get-property bean=\"ExtOperationAll\" property=\"orderType\"/> &amp;&amp; \r\n(\"PCK_DS_ACCT_SAME_CCY\".equals(<bean:get-property bean=\"ExtOperationAll\" property=\"orderType.code\"/>.toString()))"
						technicalName = "Transfer To"
						boxType = vertical
						isWidgetVisible = false
					{
						--- Box ---
							labels en = Instruction, fr = Instruction, de = Instruktion
							boxType = vertical
							tid = 75694446353787
						{
							--- Grid ---
								cssClass = blank
								gridColumnCount = 4
								gridColumnsWidth = "25,25,25,25" !
								gridRowCount = 3
							{
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = "Amount to Credit"
										domainAttribute = opCurrency !
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 75694448248207
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- Include ---
											domainAssociation = opCurrency
											includeSrc = "" !
											resource:///default/defaultFragments/CurrencyIdentifier.fragment
											bean-property-prefix = opCurrency.
										--- TextField ---
											domainAttribute = quantityN !
											columns = 21
											format = decimal
											horizontalAlignment = "${corporatehalign}"
											type = decimal
											allow = "\'0123456789.,\'"
											chars = 23
											required = true
											bean-property = quantityN
											id = quantityN
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = "Debited Amount"
										domainAttribute = accCurrency !
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 75694449362018
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- Include ---
											domainAssociation = accCurrency
											includeSrc = "" !
											resource:///default/defaultFragments/CurrencyIdentifierView.fragment
											bean-property-prefix = accCurrency.
										--- TextField ---
											domainAttribute = accNetAmountM !
											columns = 21
											format = decimal
											type = amount
											chars = 23
											editable = false
											required = true
											bean-property = accNetAmountM
											id = accNetAmountM
										{
											Event OnChange (submit)
											{
												method = post
												call-URI = "<pageflow:continuation/>"
												widget-group-ref = form
												param = "flow-action=reload"
												only-changed = true
												modal = false
												prevalidate = false
											}
										}
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = "Credited Account"
										domainAttribute = instr !
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 75694450364619
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- Include ---
											domainAssociation = instr
											includeSrc = "" !
											resource:///default/defaultFragments/InstrumentAccountIdentifier.fragment
											bean-property-prefix = instr.
										--- Include ---
											domainAssociation = opCurrency
											includeSrc = "" !
											resource:///default/defaultFragments/CurrencyIdentifierView.fragment
											bean-property-prefix = opCurrency.
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = "Debited Account", de = "Belastetes Konto", fr = "Compte débité"
										domainAttribute = account !
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										required = true
										tid = 75694451367220
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- Include ---
											domainAssociation = account
											includeSrc = "" !
											resource:///default/defaultFragments/InstrumentAccountIdentifier.fragment
											bean-property-prefix = account.
										--- Include ---
											domainAssociation = accCurrency
											includeSrc = "" !
											resource:///default/defaultFragments/CurrencyIdentifierView.fragment
											bean-property-prefix = accCurrency.
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								--- GridCell ---
									gridColumnWidth = 25
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										domainAttribute = valueD !
										for = valueD
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- CaldateField ---
										domainAttribute = valueD !
										format = datetime.date-only
										horizontalAlignment = "${corporatehalign}"
										type = datetime
										bean-property = valueD
										id = valueD
								}
							}
						}
					}
				}
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "null != <bean:get-property bean=\"ExtOperationAll\" property=\"orderType\"/> &amp;&amp; \r\n(\"PCK_DS_FXSPOT_NEGO\".equals(<bean:get-property bean=\"ExtOperationAll\" property=\"orderType.code\"/>.toString()) || \r\n\"PCK_DS_FXFWD_NEGO\".equals(<bean:get-property bean=\"ExtOperationAll\" property=\"orderType.code\"/>.toString()))"
						technicalName = IsFxNego
						boxType = vertical
						documentation = "It defines the fx rate conditions for Fx Spot order.\r\nIt requires having to buy or sell an amount into a currency against another currency."
						isWidgetSelected = true
					{
						--- Box ---
							labels en = Rate, fr = Taux
							boxType = vertical
							widgetBorder = box
							tid = 703600759884566
						{
							--- Grid ---
								cssClass = blank
								gridColumnCount = 4
								gridColumnsWidth = "25,25,25,25" !
								gridRowCount = 3
							{
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = "Client Rate", de = Kunden-Kurs, fr = "Taux client"
										domainAttribute = fxClientRateN !
										for = fxClientRateN
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 703600806569270
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- TextField ---
											domainAttribute = fxClientRateN !
											columns = 21
											format = decimal.detailed
											type = decimal
											allow = "\'0123456789.,\'"
											chars = 23
											bean-property = fxClientRateN
											id = fxClientRateN
										{
											Event OnChange (submit)
											{
												method = post
												call-URI = "<pageflow:continuation/>"
												widget-group-ref = form
												param = "flow-action=reload"
												only-changed = true
												stabs = "<xsp-request:get-parameter name=\"stabs\"/>" ud
												modal = false
												prevalidate = false
											}
										}
										--- ComboBox ---
											domainAttribute = fxRateDirectionF !
											horizontalAlignment = "${corporatehalign}"
											required = true
											bean-property = fxRateDirectionF
											id = fxRateDirectionF
										{
											Event OnChange (submit)
											{
												method = post
												call-URI = "<pageflow:continuation/>"
												widget-group-ref = form
												param = "flow-action=reload"
												only-changed = true
												stabs = "<xsp-request:get-parameter name=\"stabs\"/>" ud
												modal = false
												prevalidate = false
											}
										}
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = "Margin %"
										domainAttribute = fxMarginP !
										for = fxMarginP
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 200891342325910
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- TextField ---
											domainAttribute = fxMarginP !
											columns = 11
											format = percentTA
											horizontalAlignment = "${corporatehalign}"
											type = percent
											chars = 11
											editable = false
											bean-property = fxMarginP
											id = fxMarginP
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = "Margin pips"
										domainAttribute = fxMarginN !
										for = fxMarginN
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 200772395048532
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- TextField ---
										domainAttribute = fxMarginN !
										columns = 21
										format = decimal.detailed
										horizontalAlignment = "${corporatehalign}"
										type = decimal
										chars = 23
										bean-property = fxMarginN
										id = fxMarginN
									{
										Event OnChange (submit)
										{
											method = post
											call-URI = "<pageflow:continuation/>"
											widget-group-ref = form
											param = "flow-action=reload"
											only-changed = true
											stabs = "<xsp-request:get-parameter name=\"stabs\"/>" ud
											modal = false
											prevalidate = false
										}
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = "Margin Amount"
										domainAttribute = fxMarginM !
										for = fxMarginM
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 703600911099595
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- TextField ---
											domainAttribute = fxMarginM !
											columns = 21
											format = decimal
											horizontalAlignment = trail
											type = amount
											chars = 18
											editable = false
											bean-property = fxMarginM
											id = fxMarginM
										--- Include ---
											domainAssociation = opCurrency
											includeSrc = "" !
											resource:///default/defaultFragments/CurrencyIdentifierView.fragment
											bean-property-prefix = opCurrency.
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = "Market Rate", de = Basis-Kurs, fr = "Taux de base"
										domainAttribute = fxMarketRateN !
										for = fxMarketRateN
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 703600909150185
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- TextField ---
										domainAttribute = fxMarketRateN !
										columns = 21
										format = decimal.detailed
										horizontalAlignment = "${corporatehalign}"
										type = decimal
										chars = 23
										editable = false
										required = true
										bean-property = fxMarketRateN
										id = fxMarketRateN
									{
										Event OnChange (submit)
										{
											method = post
											call-URI = "<pageflow:continuation/>"
											widget-group-ref = form
											param = "flow-action=reload"
											only-changed = true
											stabs = "<xsp-request:get-parameter name=\"stabs\"/>" ud
											modal = false
											prevalidate = false
										}
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								--- GridCell ---
									gridColumnWidth = 25
							}
						}
					}
					--- ConditionalBody ---
						javaCode = "null != <bean:get-property bean=\"ExtOperationAll\" property=\"orderType\"/> &amp;&amp; \r\n(\"PCK_DS_FXSPOT_CONV\".equals(<bean:get-property bean=\"ExtOperationAll\" property=\"orderType.code\"/>.toString()) || \r\n\"PCK_DS_FXFWD_CONV\".equals(<bean:get-property bean=\"ExtOperationAll\" property=\"orderType.code\"/>.toString()))"
						technicalName = IsFxConv
						boxType = vertical
						isWidgetVisible = false
					{
						--- Box ---
							labels en = Rate, fr = Taux
							boxType = vertical
							widgetBorder = box
							tid = 703600913055989
						{
							--- Grid ---
								cssClass = blank
								gridColumnCount = 4
								gridColumnsWidth = "25,25,25,25" !
								gridRowCount = 3
							{
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = "Client Rate"
										domainAttribute = fxClientRateN !
										for = fxClientRateN
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 540101922302974
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- TextField ---
											domainAttribute = fxClientRateN !
											columns = 21
											format = decimal.detailed
											horizontalAlignment = "${corporatehalign}"
											type = decimal
											chars = 23
											editable = false
											bean-property = fxClientRateN
											id = fxClientRateN
										--- ComboBox ---
											domainAttribute = fxRateDirectionF !
											horizontalAlignment = "${corporatehalign}"
											required = true
											bean-property = fxRateDirectionF
											id = fxRateDirectionF
										{
											Event OnChange (submit)
											{
												method = post
												call-URI = "<pageflow:continuation/>"
												widget-group-ref = form
												param = "flow-action=reload"
												only-changed = true
												stabs = "<xsp-request:get-parameter name=\"stabs\"/>" ud
												modal = false
												prevalidate = false
											}
										}
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = "Margin %"
										domainAttribute = fxMarginP !
										for = fxMarginP
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 539910072895577
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- TextField ---
											domainAttribute = fxMarginP !
											columns = 11
											format = percentTA
											horizontalAlignment = "${corporatehalign}"
											type = percent
											chars = 11
											editable = false
											bean-property = fxMarginP
											id = fxMarginP
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = "Margin pips", fr = Marge, de = Marge
										domainAttribute = fxMarginN !
										for = fxMarginN
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 703600916960116
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- TextField ---
										domainAttribute = fxMarginN !
										columns = 21
										format = decimal.detailed
										type = decimal
										chars = 23
										editable = false
										bean-property = fxMarginN
										id = fxMarginN
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = "Margin Amount"
										domainAttribute = fxMarginM !
										for = fxMarginM
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 703600920874580
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- TextField ---
											domainAttribute = fxMarginM !
											columns = 21
											format = decimal
											horizontalAlignment = trail
											type = amount
											chars = 18
											editable = false
											bean-property = fxMarginM
											id = fxMarginM
										--- Include ---
											domainAssociation = opCurrency
											includeSrc = "" !
											resource:///default/defaultFragments/CurrencyIdentifierView.fragment
											bean-property-prefix = opCurrency.
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = "Market Rate", de = Basis-Kurs, fr = "Taux de base"
										domainAttribute = fxMarketRateN !
										for = fxMarketRateN
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 703600918940815
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- TextField ---
										domainAttribute = fxMarketRateN !
										columns = 21
										format = decimal.detailed
										horizontalAlignment = "${corporatehalign}"
										type = decimal
										chars = 23
										editable = false
										bean-property = fxMarketRateN
										id = fxMarketRateN
								}
								--- GridCell ---
									gridColumnWidth = 25
								--- GridCell ---
									gridColumnWidth = 25
							}
						}
					}
				}
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/extoperation/order/create/AdditionalDataOther.module
			}
		}
	}
}