# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Create Deposit Order", de = "Anlage-Auftrag erstellen", fr = "Créer un ordre de dépôt"
	containment = container
	domainEntity = "AAADSExtOperation:ExtOperationAll"
	bean-define = DSBean.AAADSExtOperation.ExtOperationAll
	bean-name = ExtOperationAll
	id = MoneyMarketCreate_K327_
	tid = 21552684670106
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/extoperation/order/create/MMDepositNoButtonCreate.module
		--- Conditional ---
			indexOfSelectedChild = 1
		{
			--- ConditionalBody ---
				javaCode = "Boolean.toString(com.odcgroup.aaa.ExtOperationInSessionF.Yes).equals(<bean:get-property bean=\"ExtOperationAll\" property=\"inSessionF\"/>.toString())"
				technicalName = InSession
				boxType = vertical
				isWidgetVisible = false
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 4
					gridColumnsWidth = "25,25,25,25" !
					gridRowCount = 1
				{
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- Button ---
							labels en = Save, fr = Sauver, de = Speichern
							id = btn_j2__2
							tid = 106296459256134
						{
							Event OnClick (submit)
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								widget-group-ref = form
								param = "flow-action=create"
								only-changed = true
								modal = false
								prevalidate = false
							}
						}
						--- Button ---
							labels en = Cancel, fr = Annuler, de = Abbrechen
							id = btn_F1_IH
							tid = 106323105549727
						{
							Event OnClick (submit) S
							tid = 624781181938207
							messages en = "Are you sure to cancel this order?", fr = "Etes-vous sûr d\'annuler cet ordre?", de = "Wollen Sie diesen Auftrag wirklich streichen?"
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								flow-action = cancel ud
								modal = false
								only-changed = false
								prevalidate = false
								target = self
							}
						}
					}
					--- GridCell ---
						gridColumnWidth = 25
					--- GridCell ---
						gridColumnWidth = 25
					--- GridCell ---
						gridColumnWidth = 25
				}
			}
			--- ConditionalBody ---
				javaCode = true
				technicalName = Default
				boxType = vertical
				isWidgetSelected = true
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 4
					gridColumnsWidth = "25,25,25,25" !
					gridRowCount = 1
				{
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- Button ---
							labels en = Save, de = Speichern, fr = Sauver
							id = btn_il_6_
							tid = 5571925637577
						{
							Event OnClick (submit)
							tid = 280001827897031
							messages en = "Are you sure to submit this order ?", de = "Wollen Sie diesen Auftrag wirklich senden?", fr = "Etes-vous sûr de soumette cet ordre?"
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								widget-group-ref = form
								param = "flow-action=create"
								only-changed = true
								modal = false
								prevalidate = false
							}
						}
						--- Button ---
							labels en = Cancel, de = Abbrechen, fr = Annuler
							id = btn_ik_16
							tid = 5571925952392
						{
							Event OnClick (submit) S
							tid = 624803792342043
							messages en = "Are you sure to cancel this order?", de = "Wollen Sie diesen Auftrag wirklich streichen?", fr = "Etes-vous sûr d\'annuler cet ordre?"
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								flow-action = cancel ud
								modal = false
								only-changed = false
								prevalidate = false
								target = self
							}
						}
					}
					--- GridCell ---
						gridColumnWidth = 25
					--- GridCell ---
						gridColumnWidth = 25
					--- GridCell ---
						gridColumnWidth = 25
				}
			}
		}
	}
}