# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Create Loan Order", de = "Kredit-Auftrag erstellen", fr = "Créer un ordre de prêt"
	containment = container
	domainEntity = "AAADSExtOperation:ExtOperationAll"
	bean-define = DSBean.AAADSExtOperation.ExtOperationAll
	bean-name = ExtOperationAll
	id = MoneyMarketLoanCreate_F68DZ
	tid = 5571925511210
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/extoperation/order/create/MMLoanNoButtonCreate.module
		--- Conditional ---
			indexOfSelectedChild = 1
		{
			--- ConditionalBody ---
				javaCode = "Boolean.toString(com.odcgroup.aaa.ExtOperationInSessionF.Yes).equals(<bean:get-property bean=\"ExtOperationAll\" property=\"inSessionF\"/>.toString())"
				technicalName = InSession
				boxType = vertical
				isWidgetVisible = false
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 4
					gridColumnsWidth = "25,25,25,25" !
					gridRowCount = 1
				{
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- Button ---
							labels en = Save, fr = Sauver, de = Speichern
							id = btn_J_37Q
							tid = 682042266384694
						{
							Event OnClick (submit)
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								widget-group-ref = form
								param = "flow-action=create"
								only-changed = true
								modal = false
								prevalidate = false
							}
						}
						--- Button ---
							labels en = Cancel, fr = Annuler, de = Abbrechen
							id = btn_TS_wr
							tid = 682042267022484
						{
							Event OnClick (submit) S
							tid = 682042268966307
							messages en = "Are you sure to cancel this order?", fr = "Etes-vous sûr d\'annuler cet ordre?", de = "Wollen Sie diesen Auftrag wirklich streichen?"
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								flow-action = cancel ud
								modal = false
								only-changed = false
								prevalidate = false
								target = self
							}
						}
					}
					--- GridCell ---
						gridColumnWidth = 25
					--- GridCell ---
						gridColumnWidth = 25
					--- GridCell ---
						gridColumnWidth = 25
				}
			}
			--- ConditionalBody ---
				javaCode = true
				technicalName = Default
				boxType = vertical
				isWidgetSelected = true
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 4
					gridColumnsWidth = "25,25,25,25" !
					gridRowCount = 1
				{
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- Button ---
							labels en = Save, de = Speichern, fr = Sauver
							id = btn_t1l97
							tid = 682042270916275
						{
							Event OnClick (submit)
							tid = 682042272876580
							messages en = "Are you sure to submit this order ?", de = "Wollen Sie diesen Auftrag wirklich senden?", fr = "Etes-vous sûr de soumette cet ordre?"
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								widget-group-ref = form
								param = "flow-action=create"
								only-changed = true
								modal = false
								prevalidate = false
							}
						}
						--- Button ---
							labels en = Cancel, de = Abbrechen, fr = Annuler
							id = btn_Gx__3
							tid = 682042274822358
						{
							Event OnClick (submit) S
							tid = 682042276778193
							messages en = "Are you sure to cancel this order?", de = "Wollen Sie diesen Auftrag wirklich streichen?", fr = "Etes-vous sûr d\'annuler cet ordre?"
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								flow-action = cancel ud
								modal = false
								only-changed = false
								prevalidate = false
								target = self
							}
						}
					}
					--- GridCell ---
						gridColumnWidth = 25
					--- GridCell ---
						gridColumnWidth = 25
					--- GridCell ---
						gridColumnWidth = 25
				}
			}
		}
	}
}