# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSExtOperation:ExtOperationAll"
	cssClass = nodeco
	bean-define = DSBean.AAADSExtOperation.ExtOperationAll
	bean-name = ExtOperationAll
	id = FxSpotCommunicationCreate_tJ_c4
{
	--- Box ---
		labels en = Trading, de = Handel, fr = Marché
		boxType = vertical
		tid = 22903356312171
	{
		--- Conditional ---
			indexOfSelectedChild = 1
		{
			--- ConditionalBody ---
				javaCode = "null != <bean:get-property bean=\"ExtOperationAll\" property=\"orderModeType\"/> &amp;&amp; \r\n\"PCK_DS_NORMAL\".equals(<bean:get-property bean=\"ExtOperationAll\" property=\"orderModeType.code\"/>.toString())"
				technicalName = PCK_DS_NORMAL
				boxType = vertical
				isWidgetVisible = false
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 4
					gridColumnsWidth = "25,25,25,25" !
					gridRowCount = 2
				{
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- LabelDomain ---
							labels en = "Order Mode", fr = "Modalité de l\'ordre"
							domainAttribute = orderModeType !
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							tid = 298013343796488
					}
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- Include ---
							domainAssociation = orderModeType
							includeSrc = "" !
							resource:///default/defaultFragments/TypeIdentifierRequiredReload.fragment
							bean-property-prefix = orderModeType.
					}
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- LabelDomain ---
							labels en = Trader, fr = "Opérateur boursier"
							domainAttribute = traderManager !
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							tid = 709560992441218
					}
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- Include ---
							domainAssociation = traderManager
							includeSrc = "" !
							resource:///default/defaultFragments/TraderManagerIdentifier.fragment
							bean-property-prefix = traderManager.
					}
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- LabelDomain ---
							labels en = "Trader Instruction", de = Händler-Anweisung, fr = "Instruction de l\'opérateur boursier"
							domainAttribute = remark3C !
							for = remark3C
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							tid = 702648118543837
					}
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- TextArea ---
							domainAttribute = remark3C !
							columns = 50
							horizontalAlignment = "${corporatehalign}"
							rows = 3
							type = text
							bean-property = remark3C
							id = remark3C
					}
					--- GridCell ---
						gridColumnWidth = 25
					--- GridCell ---
						gridColumnWidth = 25
				}
			}
			--- ConditionalBody ---
				javaCode = true
				technicalName = Default
				boxType = vertical
				isWidgetSelected = true
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 4
					gridColumnsWidth = "25,25,25,25" !
					gridRowCount = 3
				{
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- LabelDomain ---
							labels en = "Order Mode", fr = "Modalité de l\'ordre"
							domainAttribute = orderModeType !
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							tid = 714090519508205
					}
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- Include ---
							domainAssociation = orderModeType
							includeSrc = "" !
							resource:///default/defaultFragments/TypeIdentifierRequiredReload.fragment
							bean-property-prefix = orderModeType.
					}
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- LabelDomain ---
							labels en = Trader, fr = "Opérateur boursier"
							domainAttribute = traderManager !
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							tid = 714090522278669
					}
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- Include ---
							domainAssociation = traderManager
							includeSrc = "" !
							resource:///default/defaultFragments/TraderManagerIdentifier.fragment
							bean-property-prefix = traderManager.
					}
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- LabelDomain ---
							labels en = "Trader Instruction", de = Händler-Anweisung, fr = "Instruction de l\'opérateur boursier"
							domainAttribute = remark3C !
							for = remark3C
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							tid = 714090520313056
					}
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- TextArea ---
							domainAttribute = remark3C !
							columns = 50
							horizontalAlignment = "${corporatehalign}"
							rows = 3
							type = text
							bean-property = remark3C
							id = remark3C
					}
					--- GridCell ---
						gridColumnWidth = 25
					--- GridCell ---
						gridColumnWidth = 25
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- LabelDomain ---
							labels fr = "Mode de transmission", de = Übermittlungsart
							domainAttribute = transmissionType !
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							tid = 715046266837545
					}
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- Include ---
							domainAssociation = transmissionType
							includeSrc = "" !
							resource:///default/defaultFragments/TypeIdentifierCombo.fragment
							bean-property-prefix = transmissionType.
					}
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- LabelDomain ---
							labels fr = "Date de transmission", de = Übermittlungsdatum
							domainAttribute = transmissionD !
							for = transmissionD
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							tid = 715067017138211
					}
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- CaldateField ---
							domainAttribute = transmissionD !
							format = datetime
							horizontalAlignment = "${corporatehalign}"
							type = datetime
							bean-property = transmissionD
							id = transmissionD
					}
				}
			}
		}
	}
}