# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSExtOperation:ExtOperationAll"
	cssClass = nodeco
	bean-define = DSBean.AAADSExtOperation.ExtOperationAll
	bean-name = ExtOperationAll
	id = SecurityModeCreate_hQ__a
{
	--- Box ---
		labels en = Mode, de = Modus, fr = Mode
		boxType = vertical
		tid = 2382792702424
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 2
			gridColumnsWidth = "50,50" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 50
			{
				--- Box ---
					boxType = vertical
				{
					--- Grid ---
						cssClass = blank
						gridColumnCount = 2
						gridColumnsWidth = "50,50" !
						gridRowCount = 2
					{
						--- GridCell ---
							gridColumnWidth = 50
						{
							--- LabelDomain ---
								labels en = "Order Type"
								domainAttribute = orderNatE !
								for = orderNatE
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
								tid = 5571968586515
						}
						--- GridCell ---
							gridColumnWidth = 50
						{
							--- ComboBox ---
								domainAttribute = orderNatE !
								horizontalAlignment = "${corporatehalign}"
								required = true
								bean-property = orderNatE
								id = orderNatE
							{
								Event OnChange (submit)
								{
									method = post
									call-URI = "<pageflow:continuation/>"
									widget-group-ref = form
									param = "flow-action=reload"
									only-changed = true
									stabs = "<xsp-request:get-parameter name=\"stabs\"/>" ud
									modal = false
									prevalidate = false
								}
							}
						}
						--- GridCell ---
							gridColumnWidth = 50
						{
							--- LabelDomain ---
								labels en = Validity
								domainAttribute = orderLimitD !
								for = orderLimitD
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
								tid = 5571968768873
						}
						--- GridCell ---
							gridColumnWidth = 50
						{
							--- CaldateField ---
								domainAttribute = orderLimitD !
								format = datetime.date-only
								horizontalAlignment = "${corporatehalign}"
								type = datetime
								required = true
								bean-property = orderLimitD
								id = orderLimitD
						}
					}
				}
			}
			--- GridCell ---
				gridColumnWidth = 50
			{
				--- Box ---
					boxType = vertical
				{
					--- Conditional ---
						indexOfSelectedChild = 2
					{
						--- ConditionalBody ---
							javaCode = "Integer.toString(com.odcgroup.aaa.OperationOrderNatE.StopLimit).equals(<bean:get-property bean=\"ExtOperationAll\" property=\"orderNatE\"/>.toString())"
							technicalName = Limit-Stop
							boxType = vertical
							isWidgetVisible = false
						{
							--- Grid ---
								cssClass = blank
								gridColumnCount = 2
								gridColumnsWidth = "50,50" !
								gridRowCount = 2
							{
								--- GridCell ---
									gridColumnWidth = 50
								{
									--- LabelDomain ---
										labels en = Limit
										domainAttribute = limitQuoteN !
										for = limitQuoteN
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										required = true
										tid = 5571968956362
								}
								--- GridCell ---
									gridColumnWidth = 50
								{
									--- TextField ---
										domainAttribute = limitQuoteN !
										columns = 21
										format = decimal.detailed
										horizontalAlignment = "${corporatehalign}"
										type = decimal
										allow = "\'0123456789.,\'"
										chars = 23
										required = true
										bean-property = limitQuoteN
										id = limitQuoteN
									{
										Event OnChange (submit)
										{
											method = post
											call-URI = "<pageflow:continuation/>"
											widget-group-ref = form
											param = "flow-action=reload"
											only-changed = true
											stabs = "<xsp-request:get-parameter name=\"stabs\"/>" ud
											modal = false
											prevalidate = false
										}
									}
								}
								--- GridCell ---
									gridColumnWidth = 50
								{
									--- LabelDomain ---
										labels en = Stop
										domainAttribute = stopQuoteN !
										for = stopQuoteN
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										required = true
										tid = 5571969180733
								}
								--- GridCell ---
									gridColumnWidth = 50
								{
									--- TextField ---
										domainAttribute = stopQuoteN !
										columns = 21
										format = decimal.detailed
										horizontalAlignment = "${corporatehalign}"
										type = decimal
										allow = "\'0123456789.,\'"
										chars = 23
										required = true
										bean-property = stopQuoteN
										id = stopQuoteN
								}
							}
						}
						--- ConditionalBody ---
							javaCode = "Integer.toString(com.odcgroup.aaa.OperationOrderNatE.Stop).equals(<bean:get-property bean=\"ExtOperationAll\" property=\"orderNatE\"/>.toString())"
							technicalName = Stop
							boxType = vertical
							isWidgetVisible = false
						{
							--- Grid ---
								cssClass = blank
								gridColumnCount = 2
								gridColumnsWidth = "50,50" !
								gridRowCount = 2
							{
								--- GridCell ---
									gridColumnWidth = 50
								--- GridCell ---
									gridColumnWidth = 50
								--- GridCell ---
									gridColumnWidth = 50
								{
									--- LabelDomain ---
										labels en = Stop, fr = Stop
										domainAttribute = stopQuoteN !
										for = stopQuoteN
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 5571976531630
								}
								--- GridCell ---
									gridColumnWidth = 50
								{
									--- TextField ---
										domainAttribute = stopQuoteN !
										columns = 21
										format = decimal.detailed
										horizontalAlignment = "${corporatehalign}"
										type = decimal
										allow = "\'0123456789.,\'"
										chars = 23
										required = true
										bean-property = stopQuoteN
										id = stopQuoteN
								}
							}
						}
						--- ConditionalBody ---
							javaCode = "Integer.toString(com.odcgroup.aaa.OperationOrderNatE.Limit).equals(<bean:get-property bean=\"ExtOperationAll\" property=\"orderNatE\"/>.toString())"
							technicalName = Limit
							boxType = vertical
							isWidgetSelected = true
						{
							--- Grid ---
								cssClass = blank
								gridColumnCount = 2
								gridColumnsWidth = "50,50" !
								gridRowCount = 2
							{
								--- GridCell ---
									gridColumnWidth = 50
								--- GridCell ---
									gridColumnWidth = 50
								--- GridCell ---
									gridColumnWidth = 50
								{
									--- LabelDomain ---
										labels en = Limit
										domainAttribute = limitQuoteN !
										for = limitQuoteN
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										required = true
										tid = 5576567571018
								}
								--- GridCell ---
									gridColumnWidth = 50
								{
									--- TextField ---
										domainAttribute = limitQuoteN !
										columns = 21
										format = decimal.detailed
										horizontalAlignment = "${corporatehalign}"
										type = decimal
										allow = "\'0123456789.,\'"
										chars = 23
										required = true
										bean-property = limitQuoteN
										id = limitQuoteN
									{
										Event OnChange (submit)
										{
											method = post
											call-URI = "<pageflow:continuation/>"
											widget-group-ref = form
											param = "flow-action=reload"
											only-changed = true
											stabs = "<xsp-request:get-parameter name=\"stabs\"/>" ud
											modal = false
											prevalidate = false
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
}