<?xml version="1.0" encoding="ASCII" standalone="no"?><com.odcgroup.page.model:Model xmlns:com.odcgroup.page.model="http://www.odcgroup.com/page/model" xmlns:xmi="http://www.omg.org/XMI" metamodelVersion="2.4.0.20100320" modifiedBy="san" modifiedDate="2009-04-30T21:38:26.077+0200" xmi:id="_yjPdkDWrEd6e7a7zIFhVUA" xmi:version="2.0">
  <widget libraryName="xgui" typeName="Module" xmi:id="_yjPdkTWrEd6e7a7zIFhVUA">
    <properties libraryName="xgui" typeName="id" value="Identification_d20LP" xmi:id="_yjPdkjWrEd6e7a7zIFhVUA"/>
    <properties libraryName="xgui" typeName="icon" value="" xmi:id="_yjPdkzWrEd6e7a7zIFhVUA"/>
    <properties libraryName="xgui" typeName="verticalAlignment" value="center" xmi:id="_yjPdlDWrEd6e7a7zIFhVUA"/>
    <properties libraryName="xgui" typeName="domainEntity" value="AAADSPortfolio:PortfolioAll" xmi:id="_yjPdlTWrEd6e7a7zIFhVUA"/>
    <properties libraryName="xgui" typeName="collapsible" value="false" xmi:id="_yjPdljWrEd6e7a7zIFhVUA"/>
    <properties libraryName="xgui" typeName="name" value="554485939650989.name" xmi:id="_yjPdlzWrEd6e7a7zIFhVUA"/>
    <properties libraryName="xgui" typeName="documentation" value="" xmi:id="_yjPdmDWrEd6e7a7zIFhVUA"/>
    <properties libraryName="xgui" typeName="bean-name" value="PortfolioAll" xmi:id="_yjPdmTWrEd6e7a7zIFhVUA"/>
    <properties libraryName="xgui" typeName="bean-define" value="DSBean.AAADSPortfolio.PortfolioAll" xmi:id="_yjPdmjWrEd6e7a7zIFhVUA"/>
    <properties libraryName="xgui" typeName="pagebreak" value="" xmi:id="_yjPdmzWrEd6e7a7zIFhVUA"/>
    <properties libraryName="xgui" typeName="collapsed" value="false" xmi:id="_yjPdnDWrEd6e7a7zIFhVUA"/>
    <contents libraryName="xgui" typeName="Box" xmi:id="_yjPdnTWrEd6e7a7zIFhVUA">
      <properties libraryName="xgui" typeName="widgetBorder" value="none" xmi:id="_yjPdnjWrEd6e7a7zIFhVUA"/>
      <properties libraryName="xgui" typeName="boxType" value="vertical" xmi:id="_yjPdnzWrEd6e7a7zIFhVUA"/>
      <properties libraryName="xgui" typeName="width" value="0" xmi:id="_yjPdoDWrEd6e7a7zIFhVUA"/>
      <properties libraryName="xgui" typeName="isWidgetSelectable" value="true" xmi:id="_yjPdoTWrEd6e7a7zIFhVUA"/>
      <properties libraryName="xgui" typeName="constraints" value="0" xmi:id="_yjPdojWrEd6e7a7zIFhVUA"/>
      <properties libraryName="xgui" typeName="caption" value="" xmi:id="_yjPdozWrEd6e7a7zIFhVUA"/>
      <properties libraryName="xgui" typeName="isWidgetDeletable" value="true" xmi:id="_yjPdpDWrEd6e7a7zIFhVUA"/>
      <properties libraryName="xgui" typeName="id" value="" xmi:id="_yjPdpTWrEd6e7a7zIFhVUA"/>
      <properties libraryName="xgui" typeName="aggregation" value="false" xmi:id="_yjPdpjWrEd6e7a7zIFhVUA"/>
      <properties libraryName="xgui" typeName="horizontalAlignment" value="lead" xmi:id="_yjPdpzWrEd6e7a7zIFhVUA"/>
      <properties libraryName="xgui" typeName="verticalAlignment" value="center" xmi:id="_yjPdqDWrEd6e7a7zIFhVUA"/>
      <properties libraryName="xgui" typeName="height" value="0" xmi:id="_yjPdqTWrEd6e7a7zIFhVUA"/>
      <properties libraryName="xgui" typeName="indexOfSelectedChild" value="-1" xmi:id="_yjPdqjWrEd6e7a7zIFhVUA"/>
      <properties libraryName="xgui" typeName="documentation" value="" xmi:id="_yjPdqzWrEd6e7a7zIFhVUA"/>
      <properties libraryName="xgui" typeName="cssClass" value="" xmi:id="_yjPdrDWrEd6e7a7zIFhVUA"/>
      <contents libraryName="xgui" typeName="TabbedPane" xmi:id="_znMN4DWrEd6e7a7zIFhVUA">
        <properties libraryName="xgui" typeName="id" value="vtXU_" xmi:id="_znMN4TWrEd6e7a7zIFhVUA"/>
        <properties libraryName="xgui" typeName="indexOfSelectedChild" value="0" xmi:id="_znMN4jWrEd6e7a7zIFhVUA"/>
        <properties libraryName="xgui" typeName="documentation" value="" xmi:id="_znMN4zWrEd6e7a7zIFhVUA"/>
        <properties libraryName="xgui" typeName="cssClass" value="" xmi:id="_znMN5DWrEd6e7a7zIFhVUA"/>
        <contents libraryName="xgui" typeName="Tab" xmi:id="_znMN5TWrEd6e7a7zIFhVUA">
          <properties libraryName="xgui" typeName="id" value="tab_P_6Pn" xmi:id="_znMN5jWrEd6e7a7zIFhVUA"/>
          <properties libraryName="xgui" typeName="boxType" value="horizontal" xmi:id="_znMN5zWrEd6e7a7zIFhVUA"/>
          <properties libraryName="xgui" typeName="documentation" value="" xmi:id="_znMN6DWrEd6e7a7zIFhVUA"/>
          <properties libraryName="xgui" typeName="cssClass" value="" xmi:id="_znMN6TWrEd6e7a7zIFhVUA"/>
          <properties libraryName="xgui" typeName="caption" value="554492572357380.caption" xmi:id="_znMN6jWrEd6e7a7zIFhVUA"/>
          <properties libraryName="xgui" typeName="isWidgetVisible" value="true" xmi:id="_znMN6zWrEd6e7a7zIFhVUA"/>
          <properties libraryName="xgui" typeName="isWidgetSelected" value="true" xmi:id="_znMN7DWrEd6e7a7zIFhVUA"/>
          <properties libraryName="xgui" typeName="tooltip" value="" xmi:id="_znMN7TWrEd6e7a7zIFhVUA"/>
          
        </contents>
        <contents libraryName="xgui" typeName="Tab" xmi:id="_0tE34DWrEd6e7a7zIFhVUA">
          <properties libraryName="xgui" typeName="id" value="tab_J61Q6" xmi:id="_0tE34TWrEd6e7a7zIFhVUA"/>
          <properties libraryName="xgui" typeName="boxType" value="horizontal" xmi:id="_0tE34jWrEd6e7a7zIFhVUA"/>
          <properties libraryName="xgui" typeName="documentation" value="" xmi:id="_0tE34zWrEd6e7a7zIFhVUA"/>
          <properties libraryName="xgui" typeName="cssClass" value="" xmi:id="_0tE35DWrEd6e7a7zIFhVUA"/>
          <properties libraryName="xgui" typeName="caption" value="554499899929181.caption" xmi:id="_0tE35TWrEd6e7a7zIFhVUA"/>
          <properties libraryName="xgui" typeName="isWidgetVisible" value="false" xmi:id="_0tE35jWrEd6e7a7zIFhVUA"/>
          <properties libraryName="xgui" typeName="isWidgetSelected" value="false" xmi:id="_0tE35zWrEd6e7a7zIFhVUA"/>
          <properties libraryName="xgui" typeName="tooltip" value="" xmi:id="_0tE36DWrEd6e7a7zIFhVUA"/>
          
        </contents>
        <contents libraryName="xgui" typeName="Tab" xmi:id="_0PbSkDWrEd6e7a7zIFhVUA">
          <properties libraryName="xgui" typeName="id" value="tab_c9X__" xmi:id="_0PbSkTWrEd6e7a7zIFhVUA"/>
          <properties libraryName="xgui" typeName="boxType" value="horizontal" xmi:id="_0PbSkjWrEd6e7a7zIFhVUA"/>
          <properties libraryName="xgui" typeName="documentation" value="" xmi:id="_0PbSkzWrEd6e7a7zIFhVUA"/>
          <properties libraryName="xgui" typeName="cssClass" value="" xmi:id="_0PbSlDWrEd6e7a7zIFhVUA"/>
          <properties libraryName="xgui" typeName="caption" value="554496782762054.caption" xmi:id="_0PbSlTWrEd6e7a7zIFhVUA"/>
          <properties libraryName="xgui" typeName="isWidgetVisible" value="false" xmi:id="_0PbSljWrEd6e7a7zIFhVUA"/>
          <properties libraryName="xgui" typeName="isWidgetSelected" value="false" xmi:id="_0PbSlzWrEd6e7a7zIFhVUA"/>
          <properties libraryName="xgui" typeName="tooltip" value="" xmi:id="_0PbSmDWrEd6e7a7zIFhVUA"/>
          
        </contents>
      </contents>
    </contents>
  </widget>
</com.odcgroup.page.model:Model>