# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Cash Account", de = Kontokorrent, fr = "Compte de liquidité"
	containment = container
	domainEntity = "AAADSInstrument:InstrumentAll"
	bean-define = DSBean.AAADSInstrument.InstrumentAll
	bean-name = InstrumentAll
	id = CashAccountQuickView_i__72
	tid = 2256763854133416
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/instrument/resume/InstrumentResume.module
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/instrument/view/InstrumentHeaderView.module
		--- Box ---
			labels en = Instrument, de = Instrument, fr = Instrument
			boxType = vertical
			widgetBorder = box
			tid = 2256965507992496
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 6
				gridColumnsWidth = "16,16,16,16,16,16" !
				gridRowCount = 2
			{
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = refCurr !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- Include ---
						domainAssociation = refCurr
						includeSrc = "" !
						resource:///default/defaultFragments/CurrencyIdentifierView.fragment
						bean-property-prefix = refCurr.
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = payFreqN !
						for = payFreqN
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- Box ---
					{
						--- TextField ---
							domainAttribute = payFreqN !
							columns = 4
							format = integer
							horizontalAlignment = "${corporatehalign}"
							type = integer
							editable = false
							bean-property = payFreqN
							id = payFreqN
						--- ComboBox ---
							domainAttribute = payFreqUnitE !
							horizontalAlignment = "${corporatehalign}"
							editable = false
							required = true
							bean-property = payFreqUnitE
							id = payFreqUnitE
					}
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = accrualRuleE !
						for = accrualRuleE
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- ComboBox ---
						domainAttribute = accrualRuleE !
						horizontalAlignment = "${corporatehalign}"
						editable = false
						required = true
						bean-property = accrualRuleE
						id = accrualRuleE
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = beginD !
						for = beginD
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- CaldateField ---
						domainAttribute = beginD !
						format = date
						horizontalAlignment = "${corporatehalign}"
						type = date
						editable = false
						bean-property = beginD
						id = beginD
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = endD !
						for = endD
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- CaldateField ---
						domainAttribute = endD !
						format = date
						horizontalAlignment = "${corporatehalign}"
						type = date
						editable = false
						bean-property = endD
						id = endD
				}
				--- GridCell ---
					gridColumnWidth = 16
				--- GridCell ---
					gridColumnWidth = 16
			}
			--- Grid ---
				cssClass = blank
				gridColumnCount = 4
				gridColumnsWidth = "16,16,16,48" !
				gridRowCount = 3
			{
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = parentInstr !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- Include ---
						domainAssociation = parentInstr
						includeSrc = "" !
						resource:///default/defaultFragments/InstrumentIdentifierView.fragment
						bean-property-prefix = parentInstr.
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						labels en = "Parent Instrument Denom.", fr = "Dénom. Instrument Parent", de = "Übergeordnetes Instrument Denom."
						domainAttribute = parentInstr !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						tid = 442438271582002
				}
				--- GridCell ---
					gridColumnWidth = 48
				{
					--- Include ---
						domainAssociation = parentInstr
						includeSrc = "" !
						resource:///default/defaultFragments/InstrumentIdentifierDenomView.fragment
						bean-property-prefix = parentInstr.
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = ownerThird !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- Include ---
						domainAssociation = ownerThird
						includeSrc = "" !
						resource:///default/defaultFragments/ThirdPartyIdentifierView.fragment
						bean-property-prefix = ownerThird.
				}
				--- GridCell ---
					gridColumnWidth = 16
				--- GridCell ---
					gridColumnWidth = 48
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = portfolio !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- Include ---
						domainAssociation = portfolio
						includeSrc = "" !
						resource:///default/defaultFragments/PortfolioIdentifierNameView.fragment
						bean-property-prefix = portfolio.
				}
				--- GridCell ---
					gridColumnWidth = 16
				--- GridCell ---
					gridColumnWidth = 48
			}
		}
		--- Box ---
			boxType = vertical
			widgetBorder = box
		{
			--- TabbedPane ---
				id = L3G_N
				indexOfSelectedChild = 4
			{
				--- Tab ---
					labels en = Details, fr = Détails, de = Details
					boxType = vertical
					id = tab_g5_8x
					isWidgetVisible = false
					tid = 2257524463205239
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/risklist/RiskList.module
				}
				--- Tab ---
					labels en = Events, de = Ereignisse, fr = Evénements
					boxType = vertical
					id = tab_z_9G_
					isWidgetVisible = false
					tid = 68870191581052
				{
					--- Box ---
					{
						--- Grid ---
							cssClass = blank
							gridColumnCount = 4
							gridColumnsWidth = "25,25,25,25" !
							gridRowCount = 1
						{
							--- GridCell ---
								gridColumnWidth = 25
							{
								--- Box ---
								{
									--- RadioButton ---
										labels en = Income, fr = Revenu, de = Zinszahlung
										selected = true
										group = Events
										id = Income
										tid = 29677676012571
									--- RadioButton ---
										labels en = "Interest Rate Condition", fr = "Condition de taux d\'intérêt", de = Zinskonditionen
										group = Events
										id = InterestRate
										tid = 29677680843282
								}
							}
							--- GridCell ---
								gridColumnWidth = 25
							--- GridCell ---
								gridColumnWidth = 25
							--- GridCell ---
								gridColumnWidth = 25
						}
					}
					--- Box ---
						boxType = vertical
					{
						--- Conditional ---
							indexOfSelectedChild = 1
						{
							--- ConditionalBody ---
								javaCode = "<nav:is-selected  group-id=\"Events\" element-id=\"Income\" default-selected=\"true\"/>"
								technicalName = Income
								boxType = vertical
								isWidgetVisible = false
							{
								--- Box ---
									boxType = vertical
								{
									--- Include ---
										includeSrc = "" !
										resource:///Default/module/aaa/administration/incomeevent/IncomeEventList.module
								}
							}
							--- ConditionalBody ---
								javaCode = "<nav:is-selected  group-id=\"Events\" element-id=\"InterestRate\" default-selected=\"true\"/>"
								technicalName = InterestRate
								boxType = vertical
								isWidgetSelected = true
							{
								--- Box ---
									boxType = vertical
								{
									--- Include ---
										includeSrc = "" !
										resource:///Default/module/aaa/administration/interestcond/InterestConditionList.module
								}
							}
						}
					}
				}
				--- Tab ---
					labels en = Chrono, de = Verlauf, fr = Chronologie
					id = tab_vR5_z
					isWidgetVisible = false
					tid = 29589498128281
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/instrchrono/InstrChronoList.module
				}
				--- Tab ---
					labels en = Identification, fr = Identification, de = Identifizierung
					boxType = vertical
					id = tab_cQf_3
					isWidgetVisible = false
					tid = 2257552589593649
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/synonym/SynonymList.module
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/denomination/DenominationList.module
				}
				--- Tab ---
					labels en = Notepad, fr = Bloc-note, de = Notizen
					boxType = vertical
					id = tab_q6Y_c
					isWidgetSelected = true
					tid = 2257563386753624
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/notepad/search/NotepadList.module
				}
			}
		}
	}
}