# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = Commodity, de = Rohstoff, fr = "Matière première"
	containment = container
	domainEntity = "AAADSInstrument:InstrumentAll"
	bean-define = DSBean.AAADSInstrument.InstrumentAll
	bean-name = InstrumentAll
	id = CommodityQuickView_S3_B_
	tid = 2257732136013376
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/instrument/resume/InstrumentResume.module
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/instrument/view/InstrumentHeaderView.module
		--- Box ---
			labels en = Instrument, fr = Instrument, de = Instrument
			boxType = vertical
			widgetBorder = box
			tid = 2256928854186216
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 6
				gridColumnsWidth = "16,16,16,16,16,16" !
				gridRowCount = 1
			{
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = refCurr !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- Include ---
						domainAssociation = refCurr
						includeSrc = "" !
						resource:///default/defaultFragments/CurrencyIdentifierView.fragment
						bean-property-prefix = refCurr.
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = contractSizeN !
						for = contractSizeN
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- TextField ---
						domainAttribute = contractSizeN !
						columns = 21
						format = decimal.detailed
						horizontalAlignment = "${corporatehalign}"
						type = decimal
						chars = 23
						editable = false
						required = true
						bean-property = contractSizeN
						id = contractSizeN
				}
				--- GridCell ---
					gridColumnWidth = 16
				--- GridCell ---
					gridColumnWidth = 16
			}
		}
		--- Box ---
			boxType = vertical
			widgetBorder = box
		{
			--- TabbedPane ---
				id = q_9Q_
				indexOfSelectedChild = 4
			{
				--- Tab ---
					labels en = Details, fr = Détails, de = Details
					boxType = vertical
					id = tab_Y2__8
					isWidgetVisible = false
					tid = 2256261801948571
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/risklist/RiskList.module
					--- Box ---
						labels en = Advanced, fr = Avancé, de = Erweitert
						boxType = vertical
						widgetBorder = box
						tid = 67776296810628
					{
						--- Grid ---
							cssClass = blank
							gridColumnCount = 6
							gridColumnsWidth = "16,16,16,16,16,16" !
							gridRowCount = 3
						{
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									domainAttribute = marketThird !
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- Include ---
									domainAssociation = marketThird
									includeSrc = "" !
									resource:///default/defaultFragments/ThirdPartyIdentifierView.fragment
									bean-property-prefix = marketThird.
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									labels en = "Round Lot Quantity"
									domainAttribute = oddLotQtyN !
									for = oddLotQtyN
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
									tid = 67776298543529
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- TextField ---
									domainAttribute = oddLotQtyN !
									columns = 21
									format = decimal.detailed
									horizontalAlignment = "${corporatehalign}"
									type = decimal
									chars = 23
									editable = false
									bean-property = oddLotQtyN
									id = oddLotQtyN
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									domainAttribute = minTradeQtyN !
									for = minTradeQtyN
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- TextField ---
									domainAttribute = minTradeQtyN !
									columns = 21
									format = decimal.detailed
									horizontalAlignment = "${corporatehalign}"
									type = decimal
									chars = 23
									editable = false
									bean-property = minTradeQtyN
									id = minTradeQtyN
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									domainAttribute = settleDayN !
									for = settleDayN
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- TextField ---
									domainAttribute = settleDayN !
									columns = 30
									format = integer
									horizontalAlignment = "${corporatehalign}"
									type = integer
									editable = false
									bean-property = settleDayN
									id = settleDayN
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									domainAttribute = costOfCarryN !
									for = costOfCarryN
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- TextField ---
									domainAttribute = costOfCarryN !
									columns = 21
									format = decimal.detailed
									horizontalAlignment = "${corporatehalign}"
									type = decimal
									chars = 23
									editable = false
									bean-property = costOfCarryN
									id = costOfCarryN
							}
							--- GridCell ---
								gridColumnWidth = 16
							--- GridCell ---
								gridColumnWidth = 16
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									domainAttribute = priceCalcRuleE !
									for = priceCalcRuleE
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
									required = true
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- ComboBox ---
									domainAttribute = priceCalcRuleE !
									horizontalAlignment = "${corporatehalign}"
									editable = false
									required = true
									bean-property = priceCalcRuleE
									id = priceCalcRuleE
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									domainAttribute = valRuleE !
									for = valRuleE
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
									required = true
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- ComboBox ---
									domainAttribute = valRuleE !
									horizontalAlignment = "${corporatehalign}"
									editable = false
									required = true
									bean-property = valRuleE
									id = valRuleE
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									domainAttribute = tickSizeN !
									for = tickSizeN
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- TextField ---
									domainAttribute = tickSizeN !
									columns = 21
									format = decimal.detailed
									horizontalAlignment = "${corporatehalign}"
									type = decimal
									chars = 23
									editable = false
									bean-property = tickSizeN
									id = tickSizeN
							}
						}
					}
				}
				--- Tab ---
					labels en = Price, fr = Prix, de = Preise
					boxType = vertical
					id = tab_k5H__
					isWidgetVisible = false
					tid = 2256279322997196
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/instrprice/InstrPriceList.module
				}
				--- Tab ---
					labels en = Chrono, fr = Chronologie, de = "Zeitliche Abfolge"
					boxType = vertical
					id = tab_Z1B_7
					isWidgetVisible = false
					tid = 2256297549070622
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/instrchrono/InstrChronoList.module
				}
				--- Tab ---
					labels en = Identification, fr = Identification, de = Identifizierung
					boxType = vertical
					id = tab_H0_xr
					isWidgetVisible = false
					tid = 2256314636367192
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/synonym/SynonymList.module
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/denomination/DenominationList.module
				}
				--- Tab ---
					labels en = Notepad, fr = Bloc-note, de = Notizen
					boxType = vertical
					id = tab_j6Wf6
					isWidgetSelected = true
					tid = 2256329416695418
				{
					--- Box ---
						boxType = vertical
					{
						--- Include ---
							includeSrc = "" !
							resource:///Default/module/aaa/administration/notepad/search/NotepadList.module
					}
				}
			}
		}
	}
}