# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSExchangeEvent:ExchangeEventList"
	cssClass = nodeco
	bean-define = DSBean.AAADSExchangeEvent.ExchangeEventList
	bean-name = ExchangeEventList
	id = ExchangeList_U3_0_
	documentation = "check if can be deleted"
{
	--- Box ---
		labels en = Exchange, fr = Echange, de = Austausch
		boxType = vertical
		tid = 1142205431963559
	{
		--- TableTree ---
			id = n_3_w
			table-column-count = 10 !
			table-columns-width = "10,10,10,10,10,10,10,10,10,10" !
		{
			--- TableColumn ---
				column-name = validityD !
				column-type = domain !
				domainAttribute = validityD !
				type = text
				id = validityD
				table-column-width = 10
			{
				--- TableColumnItem ---
					item-column = validityD
					format = date
					previewValue = value
			}
			--- TableColumn ---
				column-name = beginD !
				column-type = domain !
				domainAttribute = beginD !
				type = text
				id = beginD
				table-column-width = 10
			{
				--- TableColumnItem ---
					item-column = beginD
					format = date
					previewValue = value
			}
			--- TableColumn ---
				column-name = natureE !
				column-type = domain !
				domainAttribute = natureE !
				type = text
				id = natureE
				table-column-width = 10
			{
				--- TableColumnItem ---
					item-column = natureE
					previewValue = value
			}
			--- TableColumn ---
				column-name = code !
				column-type = domain !
				domainAttribute = code !
				type = text
				id = code
				table-column-width = 10
			{
				--- TableColumnItem ---
					item-column = code
					previewValue = value
			}
			--- TableColumn ---
				column-name = currencyExtDenomination !
				column-type = domain !
				domainAttribute = currencyExtDenomination !
				type = text
				id = currencyExtDenomination
				table-column-width = 10
			{
				--- TableColumnItem ---
					item-column = currencyExtDenomination
					previewValue = value
			}
			--- TableColumn ---
				column-name = refQtyN !
				column-type = domain !
				domainAttribute = refQtyN !
				type = text
				id = refQtyN
				table-column-width = 10
			{
				--- TableColumnItem ---
					item-column = refQtyN
					format = decimal.detailed
					previewValue = value
			}
			--- TableColumn ---
				column-name = newInstrQtyN !
				column-type = domain !
				domainAttribute = newInstrQtyN !
				type = text
				id = newInstrQtyN
				table-column-width = 10
			{
				--- TableColumnItem ---
					item-column = newInstrQtyN
					format = decimal.detailed
					previewValue = value
			}
			--- TableColumn ---
				column-name = endD !
				column-type = domain !
				domainAttribute = endD !
				type = text
				id = endD
				table-column-width = 10
			{
				--- TableColumnItem ---
					item-column = endD
					format = date
					previewValue = value
			}
			--- TableColumn ---
				column-name = quoteN !
				column-type = domain !
				domainAttribute = quoteN !
				type = text
				id = quoteN
				table-column-width = 10
			{
				--- TableColumnItem ---
					item-column = quoteN
					format = decimal.detailed
					previewValue = value
			}
			--- TableColumn ---
				column-name = settleDaysN !
				column-type = domain !
				domainAttribute = settleDaysN !
				type = text
				id = settleDaysN
				table-column-width = 10
			{
				--- TableColumnItem ---
					item-column = settleDaysN
					format = integer
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = validityD
				sort-direction = descending
				sort-rank = 1
		}
	}
}