# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Fixed Income", fr = "Revenu fixe", de = Anleihe
	containment = container
	domainEntity = "AAADSInstrument:InstrumentAll"
	bean-define = DSBean.AAADSInstrument.InstrumentAll
	bean-name = InstrumentAll
	id = FixedIncomeQuickView_fcV_8
	tid = 27005334780484
{
	--- Box ---
		boxType = vertical
		widgetBorder = box
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/instrument/resume/InstrumentResume.module
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/instrument/view/InstrumentHeaderView.module
		--- Box ---
			boxType = vertical
			widgetBorder = box
		{
			--- Box ---
				labels en = Instrument, fr = Instrument, de = Instrument
				boxType = vertical
				widgetBorder = box
				tid = 1826303306460178
			{
				--- Box ---
					boxType = vertical
					widgetBorder = box
				{
					--- Grid ---
						cssClass = blank
						gridColumnCount = 6
						gridColumnsWidth = "16,16,16,16,16,16" !
						gridRowCount = 4
					{
						--- GridCell ---
							gridColumnWidth = 16
							gridColumnCssClass = grey
						{
							--- LabelDomain ---
								domainAttribute = issuerThird !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- Include ---
								domainAssociation = issuerThird
								includeSrc = "" !
								resource:///default/defaultFragments/ThirdPartyIdentifierView.fragment
								bean-property-prefix = issuerThird.
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = faceValueN !
								for = faceValueN
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- TextField ---
								domainAttribute = faceValueN !
								columns = 21
								format = decimal.detailed
								horizontalAlignment = "${corporatehalign}"
								type = decimal
								chars = 23
								editable = false
								bean-property = faceValueN
								id = faceValueN
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = refCurr !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- Include ---
								domainAssociation = refCurr
								includeSrc = "" !
								resource:///default/defaultFragments/CurrencyIdentifierView.fragment
								bean-property-prefix = refCurr.
						}
						--- GridCell ---
							gridColumnWidth = 16
							gridColumnCssClass = grey
						{
							--- LabelDomain ---
								domainAttribute = beginD !
								for = beginD
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- CaldateField ---
								domainAttribute = beginD !
								format = date
								horizontalAlignment = "${corporatehalign}"
								type = date
								editable = false
								bean-property = beginD
								id = beginD
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = endD !
								for = endD
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- CaldateField ---
								domainAttribute = endD !
								format = date
								horizontalAlignment = "${corporatehalign}"
								type = date
								editable = false
								bean-property = endD
								id = endD
						}
						--- GridCell ---
							gridColumnWidth = 16
						--- GridCell ---
							gridColumnWidth = 16
						--- GridCell ---
							gridColumnWidth = 16
							gridColumnCssClass = grey
						{
							--- LabelDomain ---
								domainAttribute = issueQuoteN !
								for = issueQuoteN
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- TextField ---
								domainAttribute = issueQuoteN !
								columns = 21
								format = decimal.detailed
								horizontalAlignment = "${corporatehalign}"
								type = decimal
								chars = 23
								editable = false
								bean-property = issueQuoteN
								id = issueQuoteN
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = redempQuoteN !
								for = redempQuoteN
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- TextField ---
								domainAttribute = redempQuoteN !
								columns = 21
								format = decimal.detailed
								horizontalAlignment = "${corporatehalign}"
								type = decimal
								chars = 23
								editable = false
								bean-property = redempQuoteN
								id = redempQuoteN
						}
						--- GridCell ---
							gridColumnWidth = 16
						--- GridCell ---
							gridColumnWidth = 16
						--- GridCell ---
							gridColumnWidth = 16
							gridColumnCssClass = grey
						{
							--- LabelDomain ---
								domainAttribute = issueQtyN !
								for = issueQtyN
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- TextField ---
								domainAttribute = issueQtyN !
								columns = 23
								format = decimal
								horizontalAlignment = "${corporatehalign}"
								type = amount
								chars = 25
								editable = false
								bean-property = issueQtyN
								id = issueQtyN
						}
						--- GridCell ---
							gridColumnWidth = 16
						--- GridCell ---
							gridColumnWidth = 16
						--- GridCell ---
							gridColumnWidth = 16
						--- GridCell ---
							gridColumnWidth = 16
					}
				}
				--- Box ---
					boxType = vertical
					widgetBorder = box
				{
					--- Grid ---
						cssClass = blank
						gridColumnCount = 4
						gridColumnsWidth = "16,16,16,48" !
						gridRowCount = 2
					{
						--- GridCell ---
							gridColumnWidth = 16
							gridColumnCssClass = grey
						{
							--- LabelDomain ---
								domainAttribute = interestRateP !
								for = interestRateP
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- TextField ---
								domainAttribute = interestRateP !
								columns = 11
								format = percentTA
								horizontalAlignment = "${corporatehalign}"
								type = percent
								chars = 11
								editable = false
								bean-property = interestRateP
								id = interestRateP
						}
						--- GridCell ---
							gridColumnWidth = 16
						--- GridCell ---
							gridColumnWidth = 48
						--- GridCell ---
							gridColumnWidth = 16
							gridColumnCssClass = grey
						{
							--- LabelDomain ---
								labels en = "Floating Rate Instrument Name", fr = "Instrument à taux variable Nom", de = "Instrument mit variablem Zins Nom"
								domainAttribute = floatInstr !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 92176007449829
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- Include ---
								domainAssociation = floatInstr
								includeSrc = "" !
								resource:///default/defaultFragments/InstrumentIdentifierView.fragment
								bean-property-prefix = floatInstr.
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								labels en = "Floating Rate Instrument Denom.", fr = "Flottant Dénom. instrument à taux", de = "Instrument mit variablem Zins Denom. "
								domainAttribute = floatInstr !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 92157591017573
						}
						--- GridCell ---
							gridColumnWidth = 48
						{
							--- Include ---
								domainAssociation = floatInstr
								includeSrc = "" !
								resource:///default/defaultFragments/InstrumentIdentifierDenomView.fragment
								bean-property-prefix = floatInstr.
						}
					}
					--- Grid ---
						cssClass = blank
						gridColumnCount = 6
						gridColumnsWidth = "16,16,16,16,16,16" !
						gridRowCount = 2
					{
						--- GridCell ---
							gridColumnWidth = 16
							gridColumnCssClass = grey
						{
							--- LabelDomain ---
								domainAttribute = payFreqN !
								for = payFreqN
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- Box ---
							{
								--- TextField ---
									domainAttribute = payFreqN !
									columns = 4
									format = integer
									horizontalAlignment = "${corporatehalign}"
									type = integer
									editable = false
									bean-property = payFreqN
									id = payFreqN
								--- ComboBox ---
									domainAttribute = payFreqUnitE !
									horizontalAlignment = "${corporatehalign}"
									editable = false
									required = true
									bean-property = payFreqUnitE
									id = payFreqUnitE
							}
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = accrualRuleE !
								for = accrualRuleE
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- ComboBox ---
								domainAttribute = accrualRuleE !
								horizontalAlignment = "${corporatehalign}"
								editable = false
								required = true
								bean-property = accrualRuleE
								id = accrualRuleE
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = couponConvE !
								for = couponConvE
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- ComboBox ---
								domainAttribute = couponConvE !
								horizontalAlignment = "${corporatehalign}"
								editable = false
								required = true
								bean-property = couponConvE
								id = couponConvE
						}
						--- GridCell ---
							gridColumnWidth = 16
							gridColumnCssClass = grey
						{
							--- LabelDomain ---
								domainAttribute = firstExD !
								for = firstExD
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- CaldateField ---
								domainAttribute = firstExD !
								format = datetime.date-only
								horizontalAlignment = "${corporatehalign}"
								type = datetime
								editable = false
								bean-property = firstExD
								id = firstExD
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = firstCoupD !
								for = firstCoupD
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- CaldateField ---
								domainAttribute = firstCoupD !
								format = datetime.date-only
								horizontalAlignment = "${corporatehalign}"
								type = datetime
								editable = false
								bean-property = firstCoupD
								id = firstCoupD
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = lastCoupD !
								for = lastCoupD
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- CaldateField ---
								domainAttribute = lastCoupD !
								format = datetime.date-only
								horizontalAlignment = "${corporatehalign}"
								type = datetime
								editable = false
								bean-property = lastCoupD
								id = lastCoupD
						}
					}
				}
			}
		}
		--- Box ---
			boxType = vertical
			widgetBorder = box
		{
			--- TabbedPane ---
				id = w__2_
				indexOfSelectedChild = 0
			{
				--- Tab ---
					labels en = Details, de = Details, fr = Détails
					tab-name = Details
					boxType = vertical
					id = tab_nBW_u
					isWidgetSelected = true
					tid = 92999573530408
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/risklist/RiskList.module
					--- Box ---
						labels en = Advanced, de = Erweitert, fr = Avancé
						boxType = vertical
						widgetBorder = box
						tid = 2425382810628725
					{
						--- Grid ---
							cssClass = blank
							gridColumnCount = 6
							gridColumnsWidth = "16,16,16,16,16,16" !
							gridRowCount = 4
						{
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									domainAttribute = marketThird !
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- Include ---
									domainAssociation = marketThird
									includeSrc = "" !
									resource:///default/defaultFragments/ThirdPartyIdentifierView.fragment
									bean-property-prefix = marketThird.
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									labels en = "Round Lot Quantity"
									domainAttribute = oddLotQtyN !
									for = oddLotQtyN
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
									tid = 64443073372174
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- TextField ---
									domainAttribute = oddLotQtyN !
									columns = 21
									format = decimal.detailed
									horizontalAlignment = "${corporatehalign}"
									type = decimal
									chars = 23
									editable = false
									bean-property = oddLotQtyN
									id = oddLotQtyN
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									domainAttribute = minTradeQtyN !
									for = minTradeQtyN
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- TextField ---
									domainAttribute = minTradeQtyN !
									columns = 21
									format = decimal.detailed
									horizontalAlignment = "${corporatehalign}"
									type = decimal
									chars = 23
									editable = false
									bean-property = minTradeQtyN
									id = minTradeQtyN
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									domainAttribute = settleDayN !
									for = settleDayN
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- TextField ---
									domainAttribute = settleDayN !
									columns = 30
									format = integer
									horizontalAlignment = "${corporatehalign}"
									type = integer
									editable = false
									bean-property = settleDayN
									id = settleDayN
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									domainAttribute = contractSizeN !
									for = contractSizeN
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
									required = true
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- TextField ---
									domainAttribute = contractSizeN !
									columns = 21
									format = decimal.detailed
									horizontalAlignment = "${corporatehalign}"
									type = decimal
									chars = 23
									editable = false
									required = true
									bean-property = contractSizeN
									id = contractSizeN
							}
							--- GridCell ---
								gridColumnWidth = 16
							--- GridCell ---
								gridColumnWidth = 16
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									domainAttribute = priceCalcRuleE !
									for = priceCalcRuleE
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
									required = true
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- ComboBox ---
									domainAttribute = priceCalcRuleE !
									horizontalAlignment = "${corporatehalign}"
									editable = false
									required = true
									bean-property = priceCalcRuleE
									id = priceCalcRuleE
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									domainAttribute = valRuleE !
									for = valRuleE
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
									required = true
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- ComboBox ---
									domainAttribute = valRuleE !
									horizontalAlignment = "${corporatehalign}"
									editable = false
									required = true
									bean-property = valRuleE
									id = valRuleE
							}
							--- GridCell ---
								gridColumnWidth = 16
							--- GridCell ---
								gridColumnWidth = 16
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									domainAttribute = taxGeo !
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- Include ---
									domainAssociation = taxGeo
									includeSrc = "" !
									resource:///default/defaultFragments/GeographicIdentifierView.fragment
									bean-property-prefix = taxGeo.
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									domainAttribute = capTaxRateP !
									for = capTaxRateP
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- TextField ---
									domainAttribute = capTaxRateP !
									columns = 11
									format = percentTA
									horizontalAlignment = "${corporatehalign}"
									type = percent
									chars = 11
									editable = false
									bean-property = capTaxRateP
									id = capTaxRateP
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									domainAttribute = taxRateP !
									for = taxRateP
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- TextField ---
									domainAttribute = taxRateP !
									columns = 11
									format = percentTA
									horizontalAlignment = "${corporatehalign}"
									type = percent
									chars = 11
									editable = false
									bean-property = taxRateP
									id = taxRateP
							}
						}
					}
				}
				--- Tab ---
					labels en = "Prices ", de = Preise, fr = "Prix "
					tab-name = Prices
					boxType = vertical
					id = tab_L7i__
					isWidgetVisible = false
					tid = 92999679655884
				{
					--- Box ---
						boxType = vertical
					{
						--- Include ---
							includeSrc = "" !
							resource:///Default/module/aaa/administration/instrprice/InstrPriceList.module
					}
				}
				--- Tab ---
					labels en = Chrono, de = Verlauf, fr = Chronologie
					id = tab_M6ng_
					isWidgetVisible = false
					tid = 29457654051099
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/instrchrono/InstrChronoList.module
				}
				--- Tab ---
					labels en = "Events, Terms & Conditions", fr = "Evénements, termes & conditions", de = "Ereignisse, Bedingungen & Konditionen"
					boxType = vertical
					id = tab_SL0__
					isWidgetVisible = false
					tid = 2932382029744562
				{
					--- Box ---
					{
						--- Grid ---
							cssClass = blank
							gridColumnCount = 4
							gridColumnsWidth = "25,25,25,25" !
							gridRowCount = 1
						{
							--- GridCell ---
								gridColumnWidth = 25
							{
								--- Box ---
								{
									--- RadioButton ---
										labels en = Income, fr = Revenu, de = Zinszahlung
										selected = true
										group = Events
										id = Income
										tid = 2934436044534710
									--- RadioButton ---
										labels en = "Issue and Redemption", de = "Ausgabe / Fälligkeit", fr = "Emission et rachat"
										group = Events
										id = IssueRedemption
										tid = 2934503102479225
									--- RadioButton ---
										labels en = "Corporate Action", fr = "Opération sur titres", de = Kapitalmassnahme
										group = Events
										id = CorporateAction
										tid = 2934527560471792
								}
							}
							--- GridCell ---
								gridColumnWidth = 25
							{
								--- Box ---
								{
									--- RadioButton ---
										labels en = Exchange, fr = Echange, de = Austausch
										group = Events
										id = Exchange
										tid = 2934547236749922
									--- RadioButton ---
										labels en = "Interest Rate Condition", fr = "Condition de taux d\'intérêt", de = Zinskonditionen
										group = Events
										id = InterestRate
										tid = 2934565638543166
								}
							}
							--- GridCell ---
								gridColumnWidth = 25
							--- GridCell ---
								gridColumnWidth = 25
						}
					}
					--- Box ---
						boxType = vertical
					{
						--- Conditional ---
							indexOfSelectedChild = 4
						{
							--- ConditionalBody ---
								javaCode = "<nav:is-selected  group-id=\"Events\" element-id=\"Income\" default-selected=\"true\"/>"
								technicalName = Income
								boxType = vertical
								isWidgetVisible = false
							{
								--- Box ---
									boxType = vertical
								{
									--- Include ---
										includeSrc = "" !
										resource:///Default/module/aaa/administration/incomeevent/IncomeEventList.module
								}
							}
							--- ConditionalBody ---
								javaCode = "<nav:is-selected  group-id=\"Events\" element-id=\"IssueRedemption\" default-selected=\"true\"/>"
								technicalName = IssueRedemption
								boxType = vertical
								isWidgetVisible = false
							{
								--- Box ---
									boxType = vertical
								{
									--- Include ---
										includeSrc = "" !
										resource:///Default/module/aaa/administration/issredmevent/IssueRedemptionEventList.module
								}
							}
							--- ConditionalBody ---
								javaCode = "<nav:is-selected  group-id=\"Events\" element-id=\"CorporateAction\" default-selected=\"true\"/>"
								technicalName = CorporateAction
								boxType = vertical
								isWidgetVisible = false
							{
								--- Box ---
									boxType = vertical
								{
									--- Include ---
										includeSrc = "" !
										resource:///Default/module/aaa/administration/corporateaction/CorporateActionList.module
								}
							}
							--- ConditionalBody ---
								javaCode = "<nav:is-selected  group-id=\"Events\" element-id=\"InterestRate\" default-selected=\"true\"/>"
								technicalName = InterestRate
								boxType = vertical
								isWidgetVisible = false
							{
								--- Box ---
									boxType = vertical
								{
									--- Include ---
										includeSrc = "" !
										resource:///Default/module/aaa/administration/interestcond/InterestConditionList.module
								}
							}
							--- ConditionalBody ---
								javaCode = "<nav:is-selected  group-id=\"Events\" element-id=\"Exchange\" default-selected=\"true\"/>"
								technicalName = Exchange
								boxType = vertical
								isWidgetSelected = true
							{
								--- Box ---
									boxType = vertical
								{
									--- Include ---
										includeSrc = "" !
										resource:///Default/module/aaa/administration/exchangeevent/ExchangeEventList.module
								}
							}
						}
					}
				}
				--- Tab ---
					labels en = Sectors, fr = Secteurs, de = Branchen
					boxType = vertical
					id = tab_qQ30X
					isWidgetVisible = false
					tid = 26269595396004
				{
					--- Box ---
						boxType = vertical
					{
						--- Include ---
							includeSrc = "" !
							resource:///Default/module/aaa/administration/sectorattrib/SectorAttribList.module
					}
				}
				--- Tab ---
					labels en = Rating, de = Bonität, fr = Notation
					boxType = vertical
					id = tab_T3_3_
					isWidgetVisible = false
					tid = 1829898140718443
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/ratingattrib/RatingAttribList.module
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/garantee/GaranteeList.module
				}
				--- Tab ---
					labels en = Trading, de = Börsenplatz, fr = "Conditions de négociations"
					tab-name = "Trading Places"
					boxType = vertical
					id = tab_L6341
					isWidgetVisible = false
					tid = 115380431391825
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/tradingplace/TradingPlaceList.module
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/tradingcurrency/TradingCurrencyList.module
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/instrdeposit/InstrumentDepositList.module
				}
				--- Tab ---
					labels en = Identification, de = Identifizierung, fr = Identification
					boxType = vertical
					id = tab_GAr2_
					isWidgetVisible = false
					tid = 1830152361835652
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/synonym/SynonymList.module
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/denomination/DenominationList.module
				}
				--- Tab ---
					labels en = Notepad, fr = Bloc-note, de = Notizen
					tab-name = Notepad
					boxType = vertical
					id = tab_FQc_x
					isWidgetVisible = false
					tid = 32257881635478
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/notepad/search/NotepadList.module
				}
			}
		}
	}
}