# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Floating Rate", de = "Variabler Zinssatz", fr = "Taux variable"
	containment = container
	domainEntity = "AAADSInstrument:InstrumentAll"
	bean-define = DSBean.AAADSInstrument.InstrumentAll
	bean-name = InstrumentAll
	id = FloatingRateQuickView_x_9_O
	documentation = "to delete"
	tid = 2257822275924174
{
	--- Box ---
		boxType = vertical
	{
		--- Box ---
			boxType = vertical
		{
			--- Include ---
				includeSrc = "" !
				resource:///Default/module/aaa/administration/instrument/resume/InstrumentResume.module
			--- Include ---
				includeSrc = "" !
				resource:///Default/module/aaa/administration/instrument/view/InstrumentHeaderView.module
		}
	}
}