# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = Forex, de = Devisengeschäft, fr = Change
	containment = container
	domainEntity = "AAADSInstrument:InstrumentAll"
	bean-define = DSBean.AAADSInstrument.InstrumentAll
	bean-name = InstrumentAll
	id = ForexQuickView_vGV_i
	tid = 2168182965281341
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/instrument/resume/InstrumentResume.module
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/instrument/view/InstrumentHeaderView.module
		--- Box ---
			labels en = Instrument, de = Instrument, fr = Instrument
			boxType = vertical
			widgetBorder = box
			tid = 2257310369742243
		{
			--- Conditional ---
				indexOfSelectedChild = 0
			{
				--- ConditionalBody ---
					javaCode = "null != <bean:get-property bean=\"InstrumentAll\" property=\"natureE\"/> &amp;&amp; Integer.toString(com.odcgroup.aaa.InstrumentNatureE.Forward).equals(<bean:get-property bean=\"InstrumentAll\" property=\"natureE\"/>.toString())"
					technicalName = IsForward
					boxType = vertical
					isWidgetSelected = true
				{
					--- Grid ---
						cssClass = blank
						gridColumnCount = 6
						gridColumnsWidth = "16,16,16,16,16,16" !
						gridRowCount = 2
					{
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								labels en = "Forex Pair", fr = Pair, de = Währungen
								domainAttribute = refCurr !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
								tid = 21937969908355
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- Box ---
							{
								--- Include ---
									domainAssociation = refCurr
									includeSrc = "" !
									resource:///default/defaultFragments/CurrencyIdentifierView.fragment
									bean-property-prefix = refCurr.
								--- Label ---
									labels en = /, fr = /, de = /
									horizontalAlignment = "${corporatehalign}"
									id = Z678O
									tid = 21784830220645
								--- Include ---
									domainAssociation = underlyInstr
									includeSrc = "" !
									resource:///default/defaultFragments/InstrumentAsCurrencyIdentifierView.fragment
									bean-property-prefix = underlyInstr.
							}
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = contractSizeN !
								for = contractSizeN
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- TextField ---
								domainAttribute = contractSizeN !
								columns = 21
								format = decimal.detailed
								horizontalAlignment = "${corporatehalign}"
								type = decimal
								chars = 23
								editable = false
								required = true
								bean-property = contractSizeN
								id = contractSizeN
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = physicalF !
								for = physicalF
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- ComboBox ---
								domainAttribute = physicalF !
								horizontalAlignment = "${corporatehalign}"
								editable = false
								required = true
								bean-property = physicalF
								id = physicalF
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = beginD !
								for = beginD
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- CaldateField ---
								domainAttribute = beginD !
								format = date
								horizontalAlignment = "${corporatehalign}"
								type = date
								editable = false
								bean-property = beginD
								id = beginD
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = endD !
								for = endD
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- CaldateField ---
								domainAttribute = endD !
								format = date
								horizontalAlignment = "${corporatehalign}"
								type = date
								editable = false
								bean-property = endD
								id = endD
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = redempQuoteN !
								for = redempQuoteN
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- TextField ---
								domainAttribute = redempQuoteN !
								columns = 21
								format = decimal.detailed
								horizontalAlignment = "${corporatehalign}"
								type = decimal
								chars = 23
								editable = false
								bean-property = redempQuoteN
								id = redempQuoteN
						}
					}
				}
				--- ConditionalBody ---
					javaCode = true
					technicalName = IsFxSwap
					boxType = vertical
					isWidgetVisible = false
				{
					--- Grid ---
						cssClass = blank
						gridColumnCount = 6
						gridColumnsWidth = "16,16,16,16,16,16" !
						gridRowCount = 2
					{
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								labels en = "Forex Pair", fr = Pair, de = Währungen
								domainAttribute = refCurr !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
								tid = 23090063354431
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- Box ---
							{
								--- Include ---
									domainAssociation = refCurr
									includeSrc = "" !
									resource:///default/defaultFragments/CurrencyIdentifierView.fragment
									bean-property-prefix = refCurr.
								--- Label ---
									labels en = /, fr = /, de = /
									horizontalAlignment = "${corporatehalign}"
									id = olx_9
									tid = 23090064348461
								--- Include ---
									domainAssociation = swapPaidCurr
									includeSrc = "" !
									resource:///default/defaultFragments/CurrencyIdentifierView.fragment
									bean-property-prefix = swapPaidCurr.
							}
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = contractSizeN !
								for = contractSizeN
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- TextField ---
								domainAttribute = contractSizeN !
								columns = 21
								format = decimal.detailed
								horizontalAlignment = "${corporatehalign}"
								type = decimal
								chars = 23
								editable = false
								required = true
								bean-property = contractSizeN
								id = contractSizeN
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = physicalF !
								for = physicalF
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- ComboBox ---
								domainAttribute = physicalF !
								horizontalAlignment = "${corporatehalign}"
								editable = false
								required = true
								bean-property = physicalF
								id = physicalF
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = beginD !
								for = beginD
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- CaldateField ---
								domainAttribute = beginD !
								format = date
								horizontalAlignment = "${corporatehalign}"
								type = date
								editable = false
								bean-property = beginD
								id = beginD
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = endD !
								for = endD
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- CaldateField ---
								domainAttribute = endD !
								format = date
								horizontalAlignment = "${corporatehalign}"
								type = date
								editable = false
								bean-property = endD
								id = endD
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = redempQuoteN !
								for = redempQuoteN
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- TextField ---
								domainAttribute = redempQuoteN !
								columns = 21
								format = decimal.detailed
								horizontalAlignment = "${corporatehalign}"
								type = decimal
								chars = 23
								editable = false
								bean-property = redempQuoteN
								id = redempQuoteN
						}
					}
				}
			}
		}
		--- Conditional ---
			indexOfSelectedChild = 0
		{
			--- ConditionalBody ---
				javaCode = "Integer.toString(com.odcgroup.aaa.InstrumentValRuleE.Theoretical).equals(<bean:get-property bean=\"InstrumentAll\" property=\"valRuleE\"/>.toString())"
				technicalName = Theorical_Prices
				boxType = vertical
				isWidgetSelected = true
			{
				--- Box ---
					boxType = vertical
					widgetBorder = box
				{
					--- TabbedPane ---
						id = qL__8
						indexOfSelectedChild = 0
					{
						--- Tab ---
							labels en = Details, fr = Détails, de = Details
							boxType = vertical
							id = tab_B9z__
							isWidgetSelected = true
							tid = 115478976066702
						{
							--- Include ---
								includeSrc = "" !
								resource:///Default/module/aaa/administration/risklist/RiskList.module
							--- Box ---
								labels en = Advanced, de = Erweitert, fr = Avancé
								boxType = vertical
								widgetBorder = box
								tid = 115478978020590
							{
								--- Grid ---
									cssClass = blank
									gridColumnCount = 6
									gridColumnsWidth = "16,16,16,16,16,16" !
									gridRowCount = 1
								{
									--- GridCell ---
										gridColumnWidth = 16
									{
										--- LabelDomain ---
											domainAttribute = priceCalcRuleE !
											for = priceCalcRuleE
											cssClass = grey
											horizontalAlignment = "${corporatehalign}"
											required = true
									}
									--- GridCell ---
										gridColumnWidth = 16
									{
										--- ComboBox ---
											domainAttribute = priceCalcRuleE !
											horizontalAlignment = "${corporatehalign}"
											editable = false
											required = true
											bean-property = priceCalcRuleE
											id = priceCalcRuleE
									}
									--- GridCell ---
										gridColumnWidth = 16
									{
										--- LabelDomain ---
											domainAttribute = valRuleE !
											for = valRuleE
											cssClass = grey
											horizontalAlignment = "${corporatehalign}"
											required = true
									}
									--- GridCell ---
										gridColumnWidth = 16
									{
										--- ComboBox ---
											domainAttribute = valRuleE !
											horizontalAlignment = "${corporatehalign}"
											editable = false
											required = true
											bean-property = valRuleE
											id = valRuleE
									}
									--- GridCell ---
										gridColumnWidth = 16
									--- GridCell ---
										gridColumnWidth = 16
								}
							}
						}
						--- Tab ---
							labels en = Identification, fr = Identification, de = Identifizierung
							boxType = vertical
							id = tab_ztr_s
							isWidgetVisible = false
							tid = 115478981918682
						{
							--- Include ---
								includeSrc = "" !
								resource:///Default/module/aaa/administration/synonym/SynonymList.module
							--- Include ---
								includeSrc = "" !
								resource:///Default/module/aaa/administration/denomination/DenominationList.module
						}
						--- Tab ---
							labels en = Notepad, fr = Bloc-note, de = Notizen
							boxType = vertical
							id = tab_o0qa_
							isWidgetVisible = false
							tid = 115478983870378
						{
							--- Include ---
								includeSrc = "" !
								resource:///Default/module/aaa/administration/notepad/search/NotepadList.module
						}
					}
				}
			}
			--- ConditionalBody ---
				javaCode = true
				technicalName = Others
				boxType = vertical
				isWidgetVisible = false
			{
				--- Box ---
					boxType = vertical
					widgetBorder = box
				{
					--- TabbedPane ---
						id = l_yS_
						indexOfSelectedChild = 1
					{
						--- Tab ---
							labels en = Details, fr = Détails, de = Details
							boxType = vertical
							id = tab_O9__S
							isWidgetVisible = false
							tid = 2169712166444617
						{
							--- Include ---
								includeSrc = "" !
								resource:///Default/module/aaa/administration/risklist/RiskList.module
							--- Box ---
								labels en = Advanced, de = Erweitert, fr = Avancé
								boxType = vertical
								widgetBorder = box
								tid = 66905376881978
							{
								--- Grid ---
									cssClass = blank
									gridColumnCount = 6
									gridColumnsWidth = "16,16,16,16,16,16" !
									gridRowCount = 1
								{
									--- GridCell ---
										gridColumnWidth = 16
									{
										--- LabelDomain ---
											domainAttribute = priceCalcRuleE !
											for = priceCalcRuleE
											cssClass = grey
											horizontalAlignment = "${corporatehalign}"
											required = true
									}
									--- GridCell ---
										gridColumnWidth = 16
									{
										--- ComboBox ---
											domainAttribute = priceCalcRuleE !
											horizontalAlignment = "${corporatehalign}"
											editable = false
											required = true
											bean-property = priceCalcRuleE
											id = priceCalcRuleE
									}
									--- GridCell ---
										gridColumnWidth = 16
									{
										--- LabelDomain ---
											domainAttribute = valRuleE !
											for = valRuleE
											cssClass = grey
											horizontalAlignment = "${corporatehalign}"
											required = true
									}
									--- GridCell ---
										gridColumnWidth = 16
									{
										--- ComboBox ---
											domainAttribute = valRuleE !
											horizontalAlignment = "${corporatehalign}"
											editable = false
											required = true
											bean-property = valRuleE
											id = valRuleE
									}
									--- GridCell ---
										gridColumnWidth = 16
									--- GridCell ---
										gridColumnWidth = 16
								}
							}
						}
						--- Tab ---
							labels en = Prices, fr = "Prix ", de = Preise
							boxType = vertical
							id = tab_K7e74
							isWidgetSelected = true
							tid = 2169995449048133
						{
							--- Box ---
								boxType = vertical
							{
								--- Include ---
									includeSrc = "" !
									resource:///Default/module/aaa/administration/instrprice/InstrPriceList.module
							}
						}
						--- Tab ---
							labels en = Identification, fr = Identification, de = Identifizierung
							boxType = vertical
							id = tab_S0_r_
							isWidgetVisible = false
							tid = 2170009668105583
						{
							--- Include ---
								includeSrc = "" !
								resource:///Default/module/aaa/administration/synonym/SynonymList.module
							--- Include ---
								includeSrc = "" !
								resource:///Default/module/aaa/administration/denomination/DenominationList.module
						}
						--- Tab ---
							labels en = Notepad, fr = Bloc-note, de = Notizen
							boxType = vertical
							id = tab_IqQ3_
							isWidgetVisible = false
							tid = 2170026261610902
						{
							--- Include ---
								includeSrc = "" !
								resource:///Default/module/aaa/administration/notepad/search/NotepadList.module
						}
					}
				}
			}
		}
	}
}