# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = Forward, fr = "Informations spécifiques", de = "Spezifische Information"
	containment = container
	domainEntity = "AAADSInstrument:InstrumentAll"
	bean-define = DSBean.AAADSInstrument.InstrumentAll
	bean-name = InstrumentAll
	id = StockQuickView_d_57_
	documentation = "to delete"
	tid = 26978342921249
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			id = s__34
			indexOfSelectedChild = 3
		{
			--- Tab ---
				labels en = Details, de = Details, fr = Détails
				tab-name = Details
				id = tab_O_1sB
				isWidgetVisible = false
				tid = 93136894335479
			{
				--- Box ---
					boxType = vertical
				{
					--- Grid ---
						cssClass = blank
						gridColumnCount = 6
						gridColumnsWidth = "16,16,16,16,16,16" !
						gridRowCount = 4
					{
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = type !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- Include ---
								domainAssociation = type
								includeSrc = "" !
								resource:///default/defaultFragments/TypeIdentifierView.fragment
								bean-property-prefix = type.
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = beginD !
								for = beginD
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- CaldateField ---
								domainAttribute = beginD !
								format = date
								horizontalAlignment = "${corporatehalign}"
								type = date
								editable = false
								bean-property = beginD
								id = beginD
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								labels en = "Quotation Unit", fr = "Règle de quotation"
								domainAttribute = priceCalcRuleE !
								for = priceCalcRuleE
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
								tid = 96221294176951
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- ComboBox ---
								domainAttribute = priceCalcRuleE !
								horizontalAlignment = "${corporatehalign}"
								editable = false
								required = true
								bean-property = priceCalcRuleE
								id = priceCalcRuleE
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = subtype !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- Include ---
								domainAssociation = subtype
								includeSrc = "" !
								resource:///default/defaultFragments/TypeIdentifierView.fragment
								bean-property-prefix = subtype.
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = endD !
								for = endD
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- CaldateField ---
								domainAttribute = endD !
								format = date
								horizontalAlignment = "${corporatehalign}"
								type = date
								editable = false
								bean-property = endD
								id = endD
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = valRuleE !
								for = valRuleE
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- ComboBox ---
								domainAttribute = valRuleE !
								horizontalAlignment = "${corporatehalign}"
								editable = false
								required = true
								bean-property = valRuleE
								id = valRuleE
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = underlyInstr !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- Include ---
								domainAssociation = underlyInstr
								includeSrc = "" !
								resource:///default/defaultFragments/InstrumentIdentifierView.fragment
								bean-property-prefix = underlyInstr.
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = contractSizeN !
								for = contractSizeN
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- TextField ---
								domainAttribute = contractSizeN !
								columns = 21
								format = decimal.detailed
								horizontalAlignment = "${corporatehalign}"
								type = decimal
								chars = 23
								editable = false
								required = true
								bean-property = contractSizeN
								id = contractSizeN
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = accrualRuleE !
								for = accrualRuleE
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- ComboBox ---
								domainAttribute = accrualRuleE !
								horizontalAlignment = "${corporatehalign}"
								editable = false
								required = true
								bean-property = accrualRuleE
								id = accrualRuleE
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = marketThird !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- Include ---
								domainAssociation = marketThird
								includeSrc = "" !
								resource:///default/defaultFragments/ThirdPartyIdentifierView.fragment
								bean-property-prefix = marketThird.
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = oddLotQtyN !
								for = oddLotQtyN
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- TextField ---
								domainAttribute = oddLotQtyN !
								columns = 21
								format = decimal.detailed
								horizontalAlignment = "${corporatehalign}"
								type = decimal
								chars = 23
								editable = false
								bean-property = oddLotQtyN
								id = oddLotQtyN
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = yieldCurveInstr !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- Include ---
								domainAssociation = yieldCurveInstr
								includeSrc = "" !
								resource:///default/defaultFragments/InstrumentIdentifierView.fragment
								bean-property-prefix = yieldCurveInstr.
						}
					}
					--- Grid ---
						cssClass = blank
						gridColumnCount = 2
						gridColumnsWidth = "50,50" !
						gridRowCount = 1
					{
						--- GridCell ---
							gridColumnWidth = 50
						{
							--- Box ---
								boxType = vertical
							{
								--- Include ---
									includeSrc = "" !
									resource:///Default/module/aaa/administration/synonym/SynonymList.module
							}
						}
						--- GridCell ---
							gridColumnWidth = 50
						{
							--- Box ---
								boxType = vertical
							{
								--- Include ---
									includeSrc = "" !
									resource:///Default/module/aaa/administration/denomination/DenominationList.module
							}
						}
					}
				}
			}
			--- Tab ---
				labels en = Prices, de = Preise, fr = Prix
				tab-name = Prices
				id = tab_T__A6
				isWidgetVisible = false
				tid = 93137011233487
			{
				--- Box ---
					boxType = vertical
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/instrprice/InstrPriceList.module
				}
			}
			--- Tab ---
				labels en = "Trading Places", de = Börsenplatz, fr = "Lieux d\'échange"
				tab-name = "Trading Places"
				id = tab_a_2av
				isWidgetVisible = false
				tid = 115421054925064
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/tradingplace/TradingPlaceList.module
			}
			--- Tab ---
				labels en = Notepad, fr = Bloc-note, de = Notizen
				tab-name = Notepad
				id = tab_m_8__
				isWidgetSelected = true
				tid = 32236564621896
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/notepad/search/NotepadList.module
			}
		}
	}
}