# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Forward Rate Agreement", de = Zinstermingeschäft, fr = "Contrat à terme de taux d\'intérêt"
	containment = container
	domainEntity = "AAADSInstrument:InstrumentAll"
	bean-define = DSBean.AAADSInstrument.InstrumentAll
	bean-name = InstrumentAll
	id = FRAQuickView_B4G__
	tid = 1748641778705673
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/instrument/resume/InstrumentResume.module
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/instrument/view/InstrumentHeaderView.module
		--- Box ---
			labels en = Instrument, de = Instrument, fr = Instrument
			boxType = vertical
			widgetBorder = box
			tid = 1745244471145075
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 4
				gridColumnsWidth = "16,16,16,48" !
				gridRowCount = 1
			{
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = floatInstr !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- Include ---
						domainAssociation = underlyInstr
						includeSrc = "" !
						resource:///default/defaultFragments/InstrumentIdentifierView.fragment
						bean-property-prefix = underlyInstr.
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						labels en = "Floating Rate Instrument Denom.", fr = "Instrument Denom. à taux variable", de = "Instrument Denom. mit variablem Zins"
						domainAttribute = floatInstr !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						tid = 506802052602216
				}
				--- GridCell ---
					gridColumnWidth = 48
				{
					--- Include ---
						domainAssociation = underlyInstr
						includeSrc = "" !
						resource:///default/defaultFragments/InstrumentIdentifierDenomView.fragment
						bean-property-prefix = underlyInstr.
				}
			}
			--- Grid ---
				cssClass = blank
				gridColumnCount = 6
				gridColumnsWidth = "16,16,16,16,16,16" !
				gridRowCount = 1
			{
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = refCurr !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- Include ---
						domainAssociation = refCurr
						includeSrc = "" !
						resource:///default/defaultFragments/CurrencyIdentifierView.fragment
						bean-property-prefix = refCurr.
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = accrualRuleE !
						for = accrualRuleE
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- ComboBox ---
						domainAttribute = accrualRuleE !
						horizontalAlignment = "${corporatehalign}"
						editable = false
						required = true
						bean-property = accrualRuleE
						id = accrualRuleE
				}
				--- GridCell ---
					gridColumnWidth = 16
				--- GridCell ---
					gridColumnWidth = 16
			}
		}
		--- Box ---
			boxType = vertical
			widgetBorder = box
		{
			--- TabbedPane ---
				id = C2U1c
				indexOfSelectedChild = 3
			{
				--- Tab ---
					labels en = Detail, de = Details, fr = Détail
					boxType = vertical
					id = tab_C___V
					isWidgetVisible = false
					tid = 1746382629059559
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/risklist/RiskList.module
					--- Box ---
						labels en = Advanced, fr = Avancé, de = Erweitert
						boxType = vertical
						widgetBorder = box
						tid = 67279216764979
					{
						--- Grid ---
							cssClass = blank
							gridColumnCount = 6
							gridColumnsWidth = "16,16,16,16,16,16" !
							gridRowCount = 1
						{
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									domainAttribute = priceCalcRuleE !
									for = priceCalcRuleE
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
									required = true
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- ComboBox ---
									domainAttribute = priceCalcRuleE !
									horizontalAlignment = "${corporatehalign}"
									editable = false
									required = true
									bean-property = priceCalcRuleE
									id = priceCalcRuleE
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									domainAttribute = valRuleE !
									for = valRuleE
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
									required = true
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- ComboBox ---
									domainAttribute = valRuleE !
									horizontalAlignment = "${corporatehalign}"
									editable = false
									required = true
									bean-property = valRuleE
									id = valRuleE
							}
							--- GridCell ---
								gridColumnWidth = 16
							--- GridCell ---
								gridColumnWidth = 16
						}
					}
				}
				--- Tab ---
					labels en = Price, de = Preise, fr = Prix
					boxType = vertical
					id = tab_Q_j_6
					isWidgetVisible = false
					tid = 1746441831908524
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/instrprice/InstrPriceList.module
				}
				--- Tab ---
					labels en = Identification, de = Identifizierung, fr = Identification
					boxType = vertical
					id = tab_v_s6_
					isWidgetVisible = false
					tid = 1746457035375166
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/synonym/SynonymList.module
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/denomination/DenominationList.module
				}
				--- Tab ---
					labels en = Notepad, de = Notizen, fr = Bloc-note
					boxType = vertical
					id = tab_f7Z__
					isWidgetSelected = true
					tid = 1746583957209086
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/notepad/search/NotepadList.module
				}
			}
		}
	}
}