# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Fund Share", fr = Fond, de = Fondsanteil
	containment = container
	domainEntity = "AAADSInstrument:InstrumentAll"
	bean-define = DSBean.AAADSInstrument.InstrumentAll
	bean-name = InstrumentAll
	id = StockQuickView_d_57_
	tid = 184163253955713
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/instrument/resume/InstrumentResume.module
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/instrument/view/InstrumentHeaderView.module
		--- Box ---
			labels en = Instrument, de = Instrument, fr = Instrument
			boxType = vertical
			widgetBorder = box
			tid = 2257248839037084
		{
			--- Box ---
				boxType = vertical
				widgetBorder = box
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 6
					gridColumnsWidth = "16,16,16,16,16,16" !
					gridRowCount = 2
				{
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- LabelDomain ---
							domainAttribute = issuerThird !
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- Include ---
							domainAssociation = issuerThird
							includeSrc = "" !
							resource:///default/defaultFragments/ThirdPartyIdentifierView.fragment
							bean-property-prefix = issuerThird.
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- LabelDomain ---
							domainAttribute = faceValueN !
							for = faceValueN
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- TextField ---
							domainAttribute = faceValueN !
							columns = 21
							format = decimal.detailed
							horizontalAlignment = "${corporatehalign}"
							type = decimal
							chars = 23
							editable = false
							bean-property = faceValueN
							id = faceValueN
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- LabelDomain ---
							domainAttribute = refCurr !
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							required = true
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- Include ---
							domainAssociation = refCurr
							includeSrc = "" !
							resource:///default/defaultFragments/CurrencyIdentifierView.fragment
							bean-property-prefix = refCurr.
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- LabelDomain ---
							domainAttribute = payFreqN !
							for = payFreqN
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- Box ---
						{
							--- TextField ---
								domainAttribute = payFreqN !
								columns = 4
								format = integer
								horizontalAlignment = "${corporatehalign}"
								type = integer
								editable = false
								bean-property = payFreqN
								id = payFreqN
							--- ComboBox ---
								domainAttribute = payFreqUnitE !
								horizontalAlignment = "${corporatehalign}"
								editable = false
								required = true
								bean-property = payFreqUnitE
								id = payFreqUnitE
						}
					}
					--- GridCell ---
						gridColumnWidth = 16
					--- GridCell ---
						gridColumnWidth = 16
					--- GridCell ---
						gridColumnWidth = 16
					--- GridCell ---
						gridColumnWidth = 16
				}
			}
			--- Conditional ---
				indexOfSelectedChild = 1
			{
				--- ConditionalBody ---
					javaCode = "(<bean:get-property bean=\"InstrumentAll\" property=\"indexInstr\"/>)==null"
					technicalName = "No Index"
					boxType = vertical
					isWidgetVisible = false
				--- ConditionalBody ---
					javaCode = true
					technicalName = "With Index"
					boxType = vertical
					isWidgetSelected = true
				{
					--- Box ---
						boxType = vertical
						widgetBorder = box
					{
						--- Grid ---
							cssClass = blank
							gridColumnCount = 6
							gridColumnsWidth = "17,17,17,17,16,16" !
							gridRowCount = 4
						{
							--- GridCell ---
								gridColumnWidth = 17
							{
								--- LabelDomain ---
									labels en = Index, fr = Indice
									domainAttribute = indexInstr !
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
									tid = 1126335997282894
							}
							--- GridCell ---
								gridColumnWidth = 17
							{
								--- Include ---
									domainAssociation = indexInstr
									includeSrc = "" !
									resource:///default/defaultFragments/InstrumentIdentifierView.fragment
									bean-property-prefix = indexInstr.
							}
							--- GridCell ---
								gridColumnWidth = 17
							{
								--- LabelDomain ---
									labels en = "Index Denomination", fr = "Indice Denomimation", de = "Index Bezeichnung"
									domainAttribute = indexInstr !
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
									tid = 1126355331132867
							}
							--- GridCell ---
								gridColumnWidth = 17
							{
								--- Include ---
									includeSrc = "" !
									resource:///default/defaultFragments/InstrumentIdentifierDenomView.fragment
									bean-property-prefix = indexInstr.
							}
							--- GridCell ---
								gridColumnWidth = 16
							--- GridCell ---
								gridColumnWidth = 16
							--- GridCell ---
								gridColumnWidth = 17
							{
								--- LabelDomain ---
									domainAttribute = indexCalcRuleE !
									for = indexCalcRuleE
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
									required = true
							}
							--- GridCell ---
								gridColumnWidth = 17
							{
								--- Include ---
									includeSrc = "" !
									resource:///default/defaultFragments/InstrumentIndexDivN.fragment
									bean-property-prefix = indexInstr.
							}
							--- GridCell ---
								gridColumnWidth = 17
							{
								--- LabelDomain ---
									domainAttribute = indexBaseD !
									for = indexBaseD
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
							}
							--- GridCell ---
								gridColumnWidth = 17
							{
								--- Include ---
									includeSrc = "" !
									resource:///default/defaultFragments/InstrumentIndexBaseD.fragment
									bean-property-prefix = indexInstr.
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									domainAttribute = indexForexF !
									for = indexForexF
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
									required = true
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- Include ---
									includeSrc = "" !
									resource:///default/defaultFragments/InstrumentIndexForexF.fragment
									bean-property-prefix = indexInstr.
							}
							--- GridCell ---
								gridColumnWidth = 17
							{
								--- LabelDomain ---
									domainAttribute = indexDivN !
									for = indexDivN
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
							}
							--- GridCell ---
								gridColumnWidth = 17
							{
								--- Include ---
									includeSrc = "" !
									resource:///default/defaultFragments/InstrumentIndexCalcRuleE.fragment
									bean-property-prefix = indexInstr.
							}
							--- GridCell ---
								gridColumnWidth = 17
							{
								--- LabelDomain ---
									domainAttribute = indexBaseN !
									for = indexBaseN
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
							}
							--- GridCell ---
								gridColumnWidth = 17
							{
								--- Include ---
									includeSrc = "" !
									resource:///default/defaultFragments/InstrumentIndexBaseN.fragment
									bean-property-prefix = indexInstr.
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									labels en = "Index Return Type", fr = "Type de perf. de l\'indice", de = Indexertragstyp
									domainAttribute = indexInstr !
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
									tid = 106856410875849
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- Include ---
									domainAssociation = indexInstr
									includeSrc = "" !
									resource:///default/defaultFragments/InstrumentIndexReturnTypeView.fragment
									bean-property-prefix = indexInstr.
							}
							--- GridCell ---
								gridColumnWidth = 17
							{
								--- LabelDomain ---
									labels en = "Index Time Rule", fr = "Règle temporelle de l\'indice", de = Indexzeitregel
									domainAttribute = indexInstr !
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
									tid = 107022980700313
							}
							--- GridCell ---
								gridColumnWidth = 17
							{
								--- Include ---
									domainAssociation = indexInstr
									includeSrc = "" !
									resource:///default/defaultFragments/InstrumentIndexTimeRuleView.fragment
									bean-property-prefix = indexInstr.
							}
							--- GridCell ---
								gridColumnWidth = 17
							--- GridCell ---
								gridColumnWidth = 17
							--- GridCell ---
								gridColumnWidth = 16
							--- GridCell ---
								gridColumnWidth = 16
						}
					}
				}
			}
		}
		--- TabbedPane ---
			id = s__34
			indexOfSelectedChild = 3
		{
			--- Tab ---
				labels en = Details, fr = Détails, de = Details
				tab-name = Details
				boxType = vertical
				id = tab_O_1sB
				isWidgetVisible = false
				tid = 184163256145673
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/risklist/RiskList.module
				--- Box ---
					labels en = Advanced, fr = Avancé, de = Erweitert
					boxType = vertical
					widgetBorder = box
					tid = 2427704561080249
				{
					--- Grid ---
						cssClass = blank
						gridColumnCount = 6
						gridColumnsWidth = "16,16,16,16,16,16" !
						gridRowCount = 4
					{
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = marketThird !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- Include ---
								domainAssociation = marketThird
								includeSrc = "" !
								resource:///default/defaultFragments/ThirdPartyIdentifierView.fragment
								bean-property-prefix = marketThird.
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								labels en = "Round Lot Quantity"
								domainAttribute = oddLotQtyN !
								for = oddLotQtyN
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 64953929550822
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- TextField ---
								domainAttribute = oddLotQtyN !
								columns = 21
								format = decimal.detailed
								horizontalAlignment = "${corporatehalign}"
								type = decimal
								chars = 23
								editable = false
								bean-property = oddLotQtyN
								id = oddLotQtyN
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = minTradeQtyN !
								for = minTradeQtyN
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- TextField ---
								domainAttribute = minTradeQtyN !
								columns = 21
								format = decimal.detailed
								horizontalAlignment = "${corporatehalign}"
								type = decimal
								chars = 23
								editable = false
								bean-property = minTradeQtyN
								id = minTradeQtyN
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = settleDayN !
								for = settleDayN
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- TextField ---
								domainAttribute = settleDayN !
								columns = 30
								format = integer
								horizontalAlignment = "${corporatehalign}"
								type = integer
								editable = false
								bean-property = settleDayN
								id = settleDayN
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = contractSizeN !
								for = contractSizeN
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- TextField ---
								domainAttribute = contractSizeN !
								columns = 21
								format = decimal.detailed
								horizontalAlignment = "${corporatehalign}"
								type = decimal
								chars = 23
								editable = false
								required = true
								bean-property = contractSizeN
								id = contractSizeN
						}
						--- GridCell ---
							gridColumnWidth = 16
						--- GridCell ---
							gridColumnWidth = 16
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = priceCalcRuleE !
								for = priceCalcRuleE
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- ComboBox ---
								domainAttribute = priceCalcRuleE !
								horizontalAlignment = "${corporatehalign}"
								editable = false
								required = true
								bean-property = priceCalcRuleE
								id = priceCalcRuleE
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = valRuleE !
								for = valRuleE
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- ComboBox ---
								domainAttribute = valRuleE !
								horizontalAlignment = "${corporatehalign}"
								editable = false
								required = true
								bean-property = valRuleE
								id = valRuleE
						}
						--- GridCell ---
							gridColumnWidth = 16
						--- GridCell ---
							gridColumnWidth = 16
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = taxGeo !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- Include ---
								domainAssociation = taxGeo
								includeSrc = "" !
								resource:///default/defaultFragments/GeographicIdentifierView.fragment
								bean-property-prefix = taxGeo.
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = capTaxRateP !
								for = capTaxRateP
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- TextField ---
								domainAttribute = capTaxRateP !
								columns = 11
								format = percentTA
								horizontalAlignment = "${corporatehalign}"
								type = percent
								chars = 11
								editable = false
								bean-property = capTaxRateP
								id = capTaxRateP
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = taxRateP !
								for = taxRateP
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- TextField ---
								domainAttribute = taxRateP !
								columns = 11
								format = percentTA
								horizontalAlignment = "${corporatehalign}"
								type = percent
								chars = 11
								editable = false
								bean-property = taxRateP
								id = taxRateP
						}
					}
				}
			}
			--- Tab ---
				labels en = Prices, de = Preise, fr = Prix
				boxType = vertical
				id = tab_MZ__0
				isWidgetVisible = false
				tid = 1831246728520803
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/instrprice/InstrPriceList.module
			}
			--- Tab ---
				labels en = Chrono, de = Verlauf, fr = Chronologie
				boxType = vertical
				id = tab_IQ_03
				isWidgetVisible = false
				tid = 1831421273302891
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/instrchrono/InstrChronoList.module
			}
			--- Tab ---
				labels en = Income, fr = Revenu, de = Einkommen
				boxType = vertical
				id = tab_Z3y_S
				isWidgetSelected = true
				tid = 101224971889572
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/incomeevent/IncomeEventList.module
			}
			--- Tab ---
				labels en = Composition, de = Zusammensetzung, fr = Composition
				boxType = vertical
				id = tab_U_1i_
				isWidgetVisible = false
				tid = 1831804319774999
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/instrcompo/InstrumentCompositionList.module
			}
			--- Tab ---
				labels en = Sectors, de = Branchen, fr = Secteurs
				boxType = vertical
				id = tab_N8_uD
				isWidgetVisible = false
				tid = 1831871861352210
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/sectorattrib/SectorAttribList.module
			}
			--- Tab ---
				labels en = Rating, de = Bonität, fr = Notation
				boxType = vertical
				id = tab_yh_L_
				isWidgetVisible = false
				tid = 2166567238189490
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/ratingattrib/RatingAttribList.module
			}
			--- Tab ---
				labels en = Identification, de = Identifizierung, fr = Identification
				boxType = vertical
				id = tab_lx2_6
				isWidgetVisible = false
				tid = 1831676913385081
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/synonym/SynonymList.module
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/denomination/DenominationList.module
			}
			--- Tab ---
				labels en = Notepad, fr = Bloc-note, de = Notizen
				tab-name = Notepad
				boxType = vertical
				id = tab_V53RI
				isWidgetVisible = false
				tid = 32159384521847
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/notepad/search/NotepadList.module
			}
		}
	}
}