# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = Future, fr = Future, de = Future
	containment = container
	domainEntity = "AAADSInstrument:InstrumentAll"
	bean-define = DSBean.AAADSInstrument.InstrumentAll
	bean-name = InstrumentAll
	id = StockQuickView_d_57_
	tid = 26947888993931
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/instrument/resume/InstrumentResume.module
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/instrument/view/InstrumentHeaderView.module
		--- Box ---
			labels en = Instrument, de = Instrument, fr = Instrument
			boxType = vertical
			widgetBorder = box
			tid = 1826218088075439
		{
			--- Box ---
				boxType = vertical
				widgetBorder = box
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 6
					gridColumnsWidth = "16,16,16,16,16,16" !
					gridRowCount = 2
				{
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- LabelDomain ---
							domainAttribute = beginD !
							for = beginD
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- CaldateField ---
							domainAttribute = beginD !
							format = date
							horizontalAlignment = "${corporatehalign}"
							type = date
							editable = false
							bean-property = beginD
							id = beginD
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- LabelDomain ---
							domainAttribute = endD !
							for = endD
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- CaldateField ---
							domainAttribute = endD !
							format = date
							horizontalAlignment = "${corporatehalign}"
							type = date
							editable = false
							bean-property = endD
							id = endD
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- LabelDomain ---
							domainAttribute = refCurr !
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							required = true
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- Include ---
							domainAssociation = refCurr
							includeSrc = "" !
							resource:///default/defaultFragments/CurrencyIdentifierView.fragment
							bean-property-prefix = refCurr.
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- LabelDomain ---
							domainAttribute = underlyQtyN !
							for = underlyQtyN
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- TextField ---
							domainAttribute = underlyQtyN !
							columns = 21
							format = decimal.detailed
							horizontalAlignment = "${corporatehalign}"
							type = decimal
							chars = 23
							editable = false
							bean-property = underlyQtyN
							id = underlyQtyN
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- LabelDomain ---
							domainAttribute = contractSizeN !
							for = contractSizeN
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							required = true
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- TextField ---
							domainAttribute = contractSizeN !
							columns = 21
							format = decimal.detailed
							horizontalAlignment = "${corporatehalign}"
							type = decimal
							chars = 23
							editable = false
							required = true
							bean-property = contractSizeN
							id = contractSizeN
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- LabelDomain ---
							domainAttribute = physicalF !
							for = physicalF
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							required = true
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- ComboBox ---
							domainAttribute = physicalF !
							horizontalAlignment = "${corporatehalign}"
							editable = false
							required = true
							bean-property = physicalF
							id = physicalF
					}
				}
			}
			--- Box ---
				boxType = vertical
				widgetBorder = box
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 4
					gridColumnsWidth = "16,16,16,48" !
					gridRowCount = 1
				{
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- LabelDomain ---
							domainAttribute = underlyInstr !
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- Include ---
							domainAssociation = underlyInstr
							includeSrc = "" !
							resource:///default/defaultFragments/InstrumentIdentifierView.fragment
							bean-property-prefix = underlyInstr.
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- LabelDomain ---
							labels en = "Underlying Denom.", fr = "Denom. sous-jacents", de = "Basiswert Denom."
							domainAttribute = underlyInstr !
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							tid = 442195979935438
					}
					--- GridCell ---
						gridColumnWidth = 48
					{
						--- Include ---
							domainAssociation = underlyInstr
							includeSrc = "" !
							resource:///default/defaultFragments/InstrumentIdentifierDenomView.fragment
							bean-property-prefix = underlyInstr.
					}
				}
			}
		}
		--- Box ---
			boxType = vertical
			widgetBorder = box
		{
			--- TabbedPane ---
				id = s__34
				indexOfSelectedChild = 5
			{
				--- Tab ---
					labels en = Details, de = Details, fr = Détails
					tab-name = Details
					boxType = vertical
					id = tab_O_1sB
					isWidgetVisible = false
					tid = 93171719495127
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/risklist/RiskList.module
					--- Box ---
						labels en = Advanced, fr = Avancé, de = Erweitert
						boxType = vertical
						widgetBorder = box
						tid = 2425254718372307
					{
						--- Grid ---
							cssClass = blank
							gridColumnCount = 6
							gridColumnsWidth = "16,16,16,16,16,16" !
							gridRowCount = 2
						{
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									domainAttribute = marketThird !
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- Include ---
									domainAssociation = marketThird
									includeSrc = "" !
									resource:///default/defaultFragments/ThirdPartyIdentifierView.fragment
									bean-property-prefix = marketThird.
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									labels en = "Round Lot Quantity"
									domainAttribute = oddLotQtyN !
									for = oddLotQtyN
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
									tid = 2353222128775584
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- TextField ---
									domainAttribute = oddLotQtyN !
									columns = 21
									format = decimal.detailed
									horizontalAlignment = "${corporatehalign}"
									type = decimal
									chars = 23
									editable = false
									bean-property = oddLotQtyN
									id = oddLotQtyN
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									domainAttribute = minTradeQtyN !
									for = minTradeQtyN
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- TextField ---
									domainAttribute = minTradeQtyN !
									columns = 21
									format = decimal.detailed
									horizontalAlignment = "${corporatehalign}"
									type = decimal
									chars = 23
									editable = false
									bean-property = minTradeQtyN
									id = minTradeQtyN
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									domainAttribute = priceCalcRuleE !
									for = priceCalcRuleE
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
									required = true
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- ComboBox ---
									domainAttribute = priceCalcRuleE !
									horizontalAlignment = "${corporatehalign}"
									editable = false
									required = true
									bean-property = priceCalcRuleE
									id = priceCalcRuleE
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									domainAttribute = valRuleE !
									for = valRuleE
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
									required = true
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- ComboBox ---
									domainAttribute = valRuleE !
									horizontalAlignment = "${corporatehalign}"
									editable = false
									required = true
									bean-property = valRuleE
									id = valRuleE
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									domainAttribute = tickSizeN !
									for = tickSizeN
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- TextField ---
									domainAttribute = tickSizeN !
									columns = 21
									format = decimal.detailed
									horizontalAlignment = "${corporatehalign}"
									type = decimal
									chars = 23
									editable = false
									bean-property = tickSizeN
									id = tickSizeN
							}
						}
					}
				}
				--- Tab ---
					labels en = Prices, de = Preise, fr = Prix
					tab-name = Prices
					id = tab_T__A6
					isWidgetVisible = false
					tid = 93171842824668
				{
					--- Box ---
						boxType = vertical
					{
						--- Include ---
							includeSrc = "" !
							resource:///Default/module/aaa/administration/instrprice/InstrPriceList.module
					}
				}
				--- Tab ---
					labels en = Chrono, de = Verlauf, fr = Chronologie
					id = tab_z8_69
					isWidgetVisible = false
					tid = 101420595985898
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/instrchrono/InstrChronoList.module
				}
				--- Tab ---
					labels en = Events, fr = Evénements, de = Ereignisse
					id = tab_V_Bx6
					isWidgetVisible = false
					tid = 1825705567357583
				{
					--- Box ---
						boxType = vertical
					{
						--- Include ---
							includeSrc = "" !
							resource:///Default/module/aaa/administration/exchangeevent/ExchangeEventList.module
						--- Include ---
							includeSrc = "" !
							resource:///Default/module/aaa/administration/termevent/TermEventList.module
					}
				}
				--- Tab ---
					labels en = Identification, fr = Identification, de = Identifizierung
					id = tab_G5_5k
					isWidgetVisible = false
					tid = 1823789681794753
				{
					--- Box ---
						boxType = vertical
					{
						--- Include ---
							includeSrc = "" !
							resource:///Default/module/aaa/administration/synonym/SynonymList.module
						--- Include ---
							includeSrc = "" !
							resource:///Default/module/aaa/administration/denomination/DenominationList.module
					}
				}
				--- Tab ---
					labels en = Notepad, fr = Bloc-note, de = Notizen
					tab-name = Notepad
					id = tab_F____
					isWidgetSelected = true
					tid = 32141607240921
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/notepad/search/NotepadList.module
				}
			}
		}
	}
}