# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "General information", fr = "Informations générales", de = Basisinformation
	containment = container
	domainEntity = "AAADSInstrument:InstrumentAll"
	bean-define = DSBean.AAADSInstrument.InstrumentAll
	bean-name = InstrumentAll
	id = HeaderModule_Z8_9i
	tid = 25075669095492
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///default/instrument/basicelements/HeaderView.fragment
	}
}