# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	containment = container
	domainEntity = "AAADSInstrument:InstrumentAll"
	cssClass = nodeco
	bean-define = DSBean.AAADSInstrument.InstrumentAll
	bean-name = InstrumentAll
	id = InstrumentDetailsView_w_cj5
{
	--- Box ---
		boxType = vertical
	{
		--- Conditional ---
			technicalName = "Conditions for Instrument Detail Pages"
			indexOfSelectedChild = 1
		{
			--- ConditionalBody ---
				javaCode = "null != <bean:get-property bean=\"InstrumentAll\" property=\"decisionState\"/> &amp;&amp; \r\n\"1\".equals(<bean:get-property bean=\"InstrumentAll\" property=\"decisionState\"/>.toString())"
				technicalName = Stock
				boxType = vertical
				documentation = "Instrument Detail screen for Stock  - Nature IN (stock)"
				isWidgetVisible = false
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/instrument/view/StockQuickView.module
			}
			--- ConditionalBody ---
				javaCode = "null != <bean:get-property bean=\"InstrumentAll\" property=\"decisionState\"/> &amp;&amp; \r\n\"3\".equals(<bean:get-property bean=\"InstrumentAll\" property=\"decisionState\"/>.toString())"
				technicalName = "Money Market"
				boxType = vertical
				documentation = "Instrument Detail screen for Money Market- Nature IN (Money Market)"
				isWidgetSelected = true
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/instrument/view/MoneyMarketQuickView.module
			}
			--- ConditionalBody ---
				javaCode = "null != <bean:get-property bean=\"InstrumentAll\" property=\"decisionState\"/> &amp;&amp; \r\n\"4\".equals(<bean:get-property bean=\"InstrumentAll\" property=\"decisionState\"/>.toString())"
				technicalName = Option
				boxType = vertical
				documentation = "Instrument Detail screen for Option- Nature IN (Options, Exotic Option, Swaptions)"
				isWidgetVisible = false
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/instrument/view/OptionQuickView.module
			}
			--- ConditionalBody ---
				javaCode = "null != <bean:get-property bean=\"InstrumentAll\" property=\"decisionState\"/> &amp;&amp; \r\n\"5\".equals(<bean:get-property bean=\"InstrumentAll\" property=\"decisionState\"/>.toString())"
				technicalName = Future
				boxType = vertical
				documentation = "Instrument Detail screen for Future- Nature IN (Future)"
				isWidgetVisible = false
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/instrument/view/FutureQuickView.module
			}
			--- ConditionalBody ---
				javaCode = "null != <bean:get-property bean=\"InstrumentAll\" property=\"decisionState\"/> &amp;&amp; \r\n\"7\".equals(<bean:get-property bean=\"InstrumentAll\" property=\"decisionState\"/>.toString())"
				technicalName = Fund
				boxType = vertical
				documentation = "Instrument Detail screen for Fund- Nature IN (Fund, Index)"
				isWidgetVisible = false
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/instrument/view/FundQuickView.module
			}
			--- ConditionalBody ---
				javaCode = "null != <bean:get-property bean=\"InstrumentAll\" property=\"decisionState\"/> &amp;&amp; \r\n\"8\".equals(<bean:get-property bean=\"InstrumentAll\" property=\"decisionState\"/>.toString())"
				technicalName = "Fixed Income"
				boxType = vertical
				documentation = "Instrument Detail screen for Fixed Income- Nature IN (fixed Income)"
				isWidgetVisible = false
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/instrument/view/FixedIncomeQuickView.module
			}
			--- ConditionalBody ---
				javaCode = "null != <bean:get-property bean=\"InstrumentAll\" property=\"decisionState\"/> &amp;&amp; \r\n\"90\".equals(<bean:get-property bean=\"InstrumentAll\" property=\"decisionState\"/>.toString())"
				technicalName = "Cash Account"
				boxType = vertical
				documentation = "Instrument Detail screen for Cash Account- Nature IN (cash account)"
				isWidgetVisible = false
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/instrument/view/CashAccountQuickView.module
			}
			--- ConditionalBody ---
				javaCode = "null != <bean:get-property bean=\"InstrumentAll\" property=\"decisionState\"/> &amp;&amp; \r\n\"10\".equals(<bean:get-property bean=\"InstrumentAll\" property=\"decisionState\"/>.toString())"
				technicalName = Forex
				boxType = vertical
				documentation = "Instrument Detail screen for Forex- Nature IN (Forward, Fxswap)"
				isWidgetVisible = false
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/instrument/view/ForexQuickView.module
			}
			--- ConditionalBody ---
				javaCode = "null != <bean:get-property bean=\"InstrumentAll\" property=\"decisionState\"/> &amp;&amp; \r\n\"11\".equals(<bean:get-property bean=\"InstrumentAll\" property=\"decisionState\"/>.toString())"
				technicalName = Commodity
				boxType = vertical
				documentation = "Instrument Detail screen for Commodity- Nature IN (Commodity)"
				isWidgetVisible = false
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/instrument/view/CommodityQuickView.module
			}
			--- ConditionalBody ---
				javaCode = "null != <bean:get-property bean=\"InstrumentAll\" property=\"decisionState\"/> &amp;&amp; \r\n\"12\".equals(<bean:get-property bean=\"InstrumentAll\" property=\"decisionState\"/>.toString())"
				technicalName = "Forward Rate Agreement"
				boxType = vertical
				documentation = "Instrument Detail screen for Forward Rate Agreement- Nature IN (Fra)"
				isWidgetVisible = false
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/instrument/view/FRAQuickView.module
			}
			--- ConditionalBody ---
				javaCode = "null != <bean:get-property bean=\"InstrumentAll\" property=\"decisionState\"/> &amp;&amp; \r\n\"13\".equals(<bean:get-property bean=\"InstrumentAll\" property=\"decisionState\"/>.toString())"
				technicalName = Swap
				boxType = vertical
				documentation = "Instrument Detail screen for Swap- Nature IN (Swap)"
				isWidgetVisible = false
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/instrument/view/SwapQuickView.module
			}
			--- ConditionalBody ---
				javaCode = "null != <bean:get-property bean=\"InstrumentAll\" property=\"decisionState\"/> &amp;&amp; \r\n\"99\".equals(<bean:get-property bean=\"InstrumentAll\" property=\"decisionState\"/>.toString())"
				technicalName = Other
				boxType = vertical
				documentation = "Instrument Detail screen for Others- Nature IN (others)"
				isWidgetVisible = false
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/instrument/view/OtherQuickView.module
			}
		}
	}
}