# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	containment = container
	domainEntity = "AAADSInstrument:InstrumentAll"
	cssClass = nodeco
	bean-define = DSBean.AAADSInstrument.InstrumentAll
	bean-name = InstrumentAll
	id = InstrumentHeaderView_gu_Q1
{
	--- Box ---
		boxType = vertical
	{
		--- Box ---
			labels en = Identification, de = Identifizierung, fr = Identification
			boxType = vertical
			widgetBorder = box
			tid = 1563985383525404
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 2
				gridColumnsWidth = "16,80" !
				gridRowCount = 3
			{
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = code !
						for = code
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
				}
				--- GridCell ---
					gridColumnWidth = 80
				{
					--- TextField ---
						domainAttribute = code !
						horizontalAlignment = "${corporatehalign}"
						type = text
						chars = 20
						editable = false
						required = true
						bean-property = code
						id = code
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = name !
						for = name
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
				}
				--- GridCell ---
					gridColumnWidth = 80
				{
					--- TextField ---
						domainAttribute = name !
						horizontalAlignment = "${corporatehalign}"
						type = text
						chars = 20
						editable = false
						required = true
						bean-property = name
						id = name
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = denom !
						for = denom
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 80
				{
					--- TextArea ---
						domainAttribute = denom
						columns = 30
						rows = 3
						editable = false
						bean-property = denom
						id = denom
				}
			}
		}
		--- Box ---
			labels en = "Nature & Type", de = "Art & Typ", fr = "Nature et type"
			boxType = vertical
			widgetBorder = box
			tid = 1563993493209617
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 6
				gridColumnsWidth = "16,16,16,16,16,16" !
				gridRowCount = 3
			{
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = natureE !
						for = natureE
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- ComboBox ---
						domainAttribute = natureE !
						horizontalAlignment = "${corporatehalign}"
						editable = false
						required = true
						bean-property = natureE
						id = natureE
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = type !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- Include ---
						domainAssociation = type
						includeSrc = "" !
						resource:///default/defaultFragments/TypeIdentifierDenomView.fragment
						bean-property-prefix = type.
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = contractType !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- Include ---
						domainAssociation = contractType
						includeSrc = "" !
						resource:///default/defaultFragments/TypeIdentifierDenomView.fragment
						bean-property-prefix = contractType.
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = subNatE !
						for = subNatE
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- ComboBox ---
						domainAttribute = subNatE !
						horizontalAlignment = "${corporatehalign}"
						editable = false
						required = true
						bean-property = subNatE
						id = subNatE
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = subtype !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- Include ---
						domainAssociation = subtype
						includeSrc = "" !
						resource:///default/defaultFragments/TypeIdentifierDenomView.fragment
						bean-property-prefix = subtype.
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = categE !
						for = categE
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- ComboBox ---
						domainAttribute = categE !
						horizontalAlignment = "${corporatehalign}"
						editable = false
						required = true
						bean-property = categE
						id = categE
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						labels fr = Statut, de = Status
						domainAttribute = statusE !
						for = statusE
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
						tid = 23900465872059
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- ComboBox ---
						domainAttribute = statusE !
						horizontalAlignment = "${corporatehalign}"
						editable = false
						required = true
						bean-property = statusE
						id = statusE
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = activeF !
						for = activeF
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- ComboBox ---
						domainAttribute = activeF !
						horizontalAlignment = "${corporatehalign}"
						editable = false
						required = true
						bean-property = activeF
						id = activeF
				}
				--- GridCell ---
					gridColumnWidth = 16
				--- GridCell ---
					gridColumnWidth = 16
			}
		}
	}
}