# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSInterestCond:InterestCondList"
	cssClass = nodeco
	bean-define = DSBean.AAADSInterestCond.InterestCondList
	bean-name = InterestCondList
	id = InterestRateCondList_PDQ_0
	documentation = "check if can be deleted"
{
	--- Box ---
		labels en = "Interest Rate Condition", de = Zinskonditionen, fr = "Condition de taux d\'intérêt"
		boxType = vertical
		tid = 1142451195512558
	{
		--- TableTree ---
			id = iL_7_
			table-column-count = 24 !
			table-columns-width = "4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4" !
		{
			--- TableColumn ---
				column-name = validityD !
				column-type = domain !
				domainAttribute = validityD !
				type = text
				id = validityD
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = validityD
					format = date
					previewValue = value
			}
			--- TableColumn ---
				column-name = intCalcRuleE !
				column-type = domain !
				domainAttribute = intCalcRuleE !
				type = text
				id = intCalcRuleE
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = intCalcRuleE
					previewValue = value
			}
			--- TableColumn ---
				column-name = beginD !
				column-type = domain !
				domainAttribute = beginD !
				type = text
				id = beginD
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = beginD
					format = date
					previewValue = value
			}
			--- TableColumn ---
				column-name = natureE !
				column-type = domain !
				domainAttribute = natureE !
				type = text
				id = natureE
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = natureE
					previewValue = value
			}
			--- TableColumn ---
				column-name = endD !
				column-type = domain !
				domainAttribute = endD !
				type = text
				id = endD
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = endD
					format = date
					previewValue = value
			}
			--- TableColumn ---
				column-name = interestRateP !
				column-type = domain !
				domainAttribute = interestRateP !
				type = text
				id = interestRateP
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = interestRateP
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = firstBenchD !
				column-type = domain !
				domainAttribute = firstBenchD !
				type = text
				id = firstBenchD
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = firstBenchD
					format = date
					previewValue = value
			}
			--- TableColumn ---
				column-name = minIntP !
				column-type = domain !
				domainAttribute = minIntP !
				type = text
				id = minIntP
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = minIntP
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = maxIntP !
				column-type = domain !
				domainAttribute = maxIntP !
				type = text
				id = maxIntP
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = maxIntP
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = multMarginN !
				column-type = domain !
				domainAttribute = multMarginN !
				type = text
				id = multMarginN
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = multMarginN
					format = decimal.detailed
					previewValue = value
			}
			--- TableColumn ---
				column-name = addMarginP !
				column-type = domain !
				domainAttribute = addMarginP !
				type = text
				id = addMarginP
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = addMarginP
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = code !
				column-type = domain !
				domainAttribute = code !
				type = text
				column-visibility = not-visible
				id = code
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = code
					previewValue = value
			}
			--- TableColumn ---
				column-name = endValidityD !
				column-type = domain !
				domainAttribute = endValidityD !
				type = text
				column-visibility = not-visible
				id = endValidityD
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = endValidityD
					format = date
					previewValue = value
			}
			--- TableColumn ---
				column-name = firstResetD !
				column-type = domain !
				domainAttribute = firstResetD !
				type = text
				column-visibility = not-visible
				id = firstResetD
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = firstResetD
					format = date
					previewValue = value
			}
			--- TableColumn ---
				column-name = resetFreqN !
				column-type = domain !
				domainAttribute = resetFreqN !
				type = text
				column-visibility = not-visible
				id = resetFreqN
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = resetFreqN
					format = integer
					previewValue = value
			}
			--- TableColumn ---
				column-name = resetFreqUnitE !
				column-type = domain !
				domainAttribute = resetFreqUnitE !
				type = text
				column-visibility = not-visible
				id = resetFreqUnitE
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = resetFreqUnitE
					previewValue = value
			}
			--- TableColumn ---
				column-name = compoundFreqN !
				column-type = domain !
				domainAttribute = compoundFreqN !
				type = text
				column-visibility = not-visible
				id = compoundFreqN
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = compoundFreqN
					format = integer
					previewValue = value
			}
			--- TableColumn ---
				column-name = growthP !
				column-type = domain !
				domainAttribute = growthP !
				type = text
				column-visibility = not-visible
				id = growthP
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = growthP
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = compConvE !
				column-type = domain !
				domainAttribute = compConvE !
				type = text
				column-visibility = not-visible
				id = compConvE
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = compConvE
					previewValue = value
			}
			--- TableColumn ---
				column-name = averF !
				column-type = domain !
				domainAttribute = averF !
				type = text
				column-visibility = not-visible
				id = averF
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = averF
					previewValue = value
			}
			--- TableColumn ---
				column-name = averPeriodN !
				column-type = domain !
				domainAttribute = averPeriodN !
				type = text
				column-visibility = not-visible
				id = averPeriodN
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = averPeriodN
					format = integer
					previewValue = value
			}
			--- TableColumn ---
				column-name = averPeriodUnitE !
				column-type = domain !
				domainAttribute = averPeriodUnitE !
				type = text
				column-visibility = not-visible
				id = averPeriodUnitE
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = averPeriodUnitE
					previewValue = value
			}
			--- TableColumn ---
				column-name = backsetF !
				column-type = domain !
				domainAttribute = backsetF !
				type = text
				column-visibility = not-visible
				id = backsetF
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = backsetF
					previewValue = value
			}
			--- TableColumn ---
				column-name = accrualFactorN !
				column-type = domain !
				domainAttribute = accrualFactorN !
				type = text
				column-visibility = not-visible
				id = accrualFactorN
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = accrualFactorN
					format = decimal.detailed
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = validityD
				sort-direction = descending
				sort-rank = 1
			--- TableSort ---
				sort-column-name = beginD
				sort-direction = descending
				sort-rank = 2
			--- TableSort ---
				sort-column-name = natureE
				sort-rank = 3
			--- TableSort ---
				sort-column-name = endValidityD
				sort-direction = descending
				sort-rank = 4
			--- TableSort ---
				sort-column-name = endD
				sort-direction = descending
				sort-rank = 5
		}
	}
}