# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Money Market", fr = "Marché monétaire", de = Geldmarkt
	containment = container
	domainEntity = "AAADSInstrument:InstrumentAll"
	bean-define = DSBean.AAADSInstrument.InstrumentAll
	bean-name = InstrumentAll
	id = StockQuickView_d_57_
	tid = 26916690102330
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/instrument/resume/InstrumentResume.module
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/instrument/view/InstrumentHeaderView.module
		--- Box ---
			labels en = Instrument, de = Instrument, fr = Instrument
			boxType = vertical
			widgetBorder = box
			tid = 2257214519115697
		{
			--- Box ---
				boxType = vertical
				widgetBorder = box
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 6
					gridColumnsWidth = "16,16,16,16,16,16" !
					gridRowCount = 2
				{
					--- GridCell ---
						gridColumnWidth = 16
						gridColumnCssClass = grey
					{
						--- LabelDomain ---
							domainAttribute = issuerThird !
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- Include ---
							domainAssociation = issuerThird
							includeSrc = "" !
							resource:///default/defaultFragments/ThirdPartyIdentifierView.fragment
							bean-property-prefix = issuerThird.
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- LabelDomain ---
							domainAttribute = refCurr !
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							required = true
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- Include ---
							domainAssociation = refCurr
							includeSrc = "" !
							resource:///default/defaultFragments/CurrencyIdentifierView.fragment
							bean-property-prefix = refCurr.
					}
					--- GridCell ---
						gridColumnWidth = 16
					--- GridCell ---
						gridColumnWidth = 16
					--- GridCell ---
						gridColumnWidth = 16
						gridColumnCssClass = grey
					{
						--- LabelDomain ---
							domainAttribute = beginD !
							for = beginD
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- CaldateField ---
							domainAttribute = beginD !
							format = date
							horizontalAlignment = "${corporatehalign}"
							type = date
							editable = false
							bean-property = beginD
							id = beginD
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- LabelDomain ---
							domainAttribute = endD !
							for = endD
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- CaldateField ---
							domainAttribute = endD !
							format = date
							horizontalAlignment = "${corporatehalign}"
							type = date
							editable = false
							bean-property = endD
							id = endD
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- LabelDomain ---
							domainAttribute = noticeDayN !
							for = noticeDayN
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- TextField ---
							domainAttribute = noticeDayN !
							columns = 30
							format = integer
							horizontalAlignment = "${corporatehalign}"
							type = integer
							editable = false
							bean-property = noticeDayN
							id = noticeDayN
					}
				}
			}
			--- Box ---
				boxType = vertical
				widgetBorder = box
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 4
					gridColumnsWidth = "16,16,16,48" !
					gridRowCount = 3
				{
					--- GridCell ---
						gridColumnWidth = 16
						gridColumnCssClass = grey
					{
						--- LabelDomain ---
							domainAttribute = interestRateP !
							for = interestRateP
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- TextField ---
							domainAttribute = interestRateP !
							columns = 11
							format = percentTA
							horizontalAlignment = "${corporatehalign}"
							type = percent
							chars = 11
							editable = false
							bean-property = interestRateP
							id = interestRateP
					}
					--- GridCell ---
						gridColumnWidth = 16
					--- GridCell ---
						gridColumnWidth = 48
					--- GridCell ---
						gridColumnWidth = 16
						gridColumnCssClass = grey
					{
						--- LabelDomain ---
							domainAttribute = floatInstr !
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- Include ---
							domainAssociation = floatInstr
							includeSrc = "" !
							resource:///default/defaultFragments/InstrumentIdentifierView.fragment
							bean-property-prefix = floatInstr.
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- LabelDomain ---
							labels en = "Floating Rate Instrument Denom.", fr = "Flottant Dénom. instrument à taux", de = "Floating Rate Instrument Denom."
							domainAttribute = floatInstr !
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							tid = 506880593098564
					}
					--- GridCell ---
						gridColumnWidth = 48
					{
						--- Include ---
							domainAssociation = floatInstr
							includeSrc = "" !
							resource:///default/defaultFragments/InstrumentIdentifierDenomView.fragment
							bean-property-prefix = floatInstr.
					}
					--- GridCell ---
						gridColumnWidth = 16
						gridColumnCssClass = grey
					{
						--- LabelDomain ---
							domainAttribute = addMarginP !
							for = addMarginP
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- TextField ---
							domainAttribute = addMarginP !
							columns = 11
							format = percentTA
							horizontalAlignment = "${corporatehalign}"
							type = percent
							chars = 11
							editable = false
							bean-property = addMarginP
							id = addMarginP
					}
					--- GridCell ---
						gridColumnWidth = 16
					--- GridCell ---
						gridColumnWidth = 48
				}
			}
			--- Box ---
				boxType = vertical
				widgetBorder = box
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 6
					gridColumnsWidth = "16,16,16,16,16,16" !
					gridRowCount = 1
				{
					--- GridCell ---
						gridColumnWidth = 16
						gridColumnCssClass = grey
					{
						--- LabelDomain ---
							domainAttribute = payFreqN !
							for = payFreqN
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- Box ---
						{
							--- TextField ---
								domainAttribute = payFreqN !
								columns = 4
								format = integer
								horizontalAlignment = "${corporatehalign}"
								type = integer
								editable = false
								bean-property = payFreqN
								id = payFreqN
							--- ComboBox ---
								domainAttribute = payFreqUnitE !
								horizontalAlignment = "${corporatehalign}"
								editable = false
								required = true
								bean-property = payFreqUnitE
								id = payFreqUnitE
						}
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- LabelDomain ---
							domainAttribute = accrualRuleE !
							for = accrualRuleE
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							required = true
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- ComboBox ---
							domainAttribute = accrualRuleE !
							horizontalAlignment = "${corporatehalign}"
							editable = false
							required = true
							bean-property = accrualRuleE
							id = accrualRuleE
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- LabelDomain ---
							domainAttribute = interestRateConvE !
							for = interestRateConvE
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							required = true
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- ComboBox ---
							domainAttribute = interestRateConvE !
							horizontalAlignment = "${corporatehalign}"
							editable = false
							required = true
							bean-property = interestRateConvE
							id = interestRateConvE
					}
				}
			}
		}
		--- Box ---
			boxType = vertical
			widgetBorder = box
		{
			--- TabbedPane ---
				id = s__34
				indexOfSelectedChild = 4
			{
				--- Tab ---
					labels en = Details, de = Details, fr = Détails
					tab-name = Details
					boxType = vertical
					id = tab_O_1sB
					isWidgetVisible = false
					tid = 93209220695839
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/risklist/RiskList.module
					--- Box ---
						labels en = Advanced, fr = Avancé, de = Erweitert
						boxType = vertical
						widgetBorder = box
						tid = 2422545585260417
					{
						--- Grid ---
							cssClass = blank
							gridColumnCount = 6
							gridColumnsWidth = "16,16,16,16,16,16" !
							gridRowCount = 2
						{
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									domainAttribute = contractSizeN !
									for = contractSizeN
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
									required = true
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- TextField ---
									domainAttribute = contractSizeN !
									columns = 21
									format = decimal.detailed
									horizontalAlignment = "${corporatehalign}"
									type = decimal
									chars = 23
									editable = false
									required = true
									bean-property = contractSizeN
									id = contractSizeN
							}
							--- GridCell ---
								gridColumnWidth = 16
							--- GridCell ---
								gridColumnWidth = 16
							--- GridCell ---
								gridColumnWidth = 16
							--- GridCell ---
								gridColumnWidth = 16
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									domainAttribute = taxGeo !
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- Include ---
									domainAssociation = taxGeo
									includeSrc = "" !
									resource:///default/defaultFragments/GeographicIdentifierView.fragment
									bean-property-prefix = taxGeo.
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									domainAttribute = capTaxRateP !
									for = capTaxRateP
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- TextField ---
									domainAttribute = capTaxRateP !
									columns = 11
									format = percentTA
									horizontalAlignment = "${corporatehalign}"
									type = percent
									chars = 11
									editable = false
									bean-property = capTaxRateP
									id = capTaxRateP
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									domainAttribute = taxRateP !
									for = taxRateP
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- TextField ---
									domainAttribute = taxRateP !
									columns = 11
									format = percentTA
									horizontalAlignment = "${corporatehalign}"
									type = percent
									chars = 11
									editable = false
									bean-property = taxRateP
									id = taxRateP
							}
						}
					}
				}
				--- Tab ---
					labels en = Income, de = Zinszahlung, fr = Revenu
					tab-name = "Trading Places"
					boxType = vertical
					id = tab_T7_m3
					isWidgetVisible = false
					tid = 115522901814689
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/interestcond/InterestConditionList.module
				}
				--- Tab ---
					labels en = Rating, fr = Notation, de = Bonität
					boxType = vertical
					id = tab_n_L6_
					isWidgetVisible = false
					tid = 2172406883821547
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/ratingattrib/RatingAttribList.module
				}
				--- Tab ---
					labels en = Identification, fr = Identification, de = Identifizierung
					boxType = vertical
					id = tab_W_599
					isWidgetVisible = false
					tid = 2173276980178766
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/synonym/SynonymList.module
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/denomination/DenominationList.module
				}
				--- Tab ---
					labels en = Notepad, fr = Bloc-note, de = Notizen
					tab-name = Notepad
					boxType = vertical
					id = tab_U_D67
					isWidgetSelected = true
					tid = 31924206751905
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/notepad/search/NotepadList.module
				}
			}
		}
	}
}