# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = Option, fr = Option, de = Option
	containment = container
	domainEntity = "AAADSInstrument:InstrumentAll"
	bean-define = DSBean.AAADSInstrument.InstrumentAll
	bean-name = InstrumentAll
	id = StockQuickView_d_57_
	tid = 22106942642463
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/instrument/resume/InstrumentResume.module
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/instrument/view/InstrumentHeaderView.module
		--- Box ---
			labels en = Instrument, de = Instrument, fr = Instrument
			boxType = vertical
			widgetBorder = box
			tid = 1640649665988275
		{
			--- Box ---
				boxType = vertical
				widgetBorder = box
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 6
					gridColumnsWidth = "16,16,16,16,16,16" !
					gridRowCount = 3
				{
					--- GridCell ---
						gridColumnWidth = 16
						gridColumnCssClass = grey
					{
						--- LabelDomain ---
							domainAttribute = optionClassE !
							for = optionClassE
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							required = true
					}
					--- GridCell ---
						gridColumnWidth = 16
						gridColumnCssClass = grey
					{
						--- ComboBox ---
							domainAttribute = optionClassE !
							horizontalAlignment = "${corporatehalign}"
							editable = false
							required = true
							bean-property = optionClassE
							id = optionClassE
					}
					--- GridCell ---
						gridColumnWidth = 16
						gridColumnCssClass = grey
					{
						--- LabelDomain ---
							domainAttribute = optStyleE !
							for = optStyleE
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							required = true
					}
					--- GridCell ---
						gridColumnWidth = 16
						gridColumnCssClass = grey
					{
						--- ComboBox ---
							domainAttribute = optStyleE !
							horizontalAlignment = "${corporatehalign}"
							editable = false
							required = true
							bean-property = optStyleE
							id = optStyleE
					}
					--- GridCell ---
						gridColumnWidth = 16
						gridColumnCssClass = grey
					{
						--- LabelDomain ---
							domainAttribute = refCurr !
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							required = true
					}
					--- GridCell ---
						gridColumnWidth = 16
						gridColumnCssClass = grey
					{
						--- Include ---
							domainAssociation = refCurr
							includeSrc = "" !
							resource:///default/defaultFragments/CurrencyIdentifierView.fragment
							bean-property-prefix = refCurr.
					}
					--- GridCell ---
						gridColumnWidth = 16
						gridColumnCssClass = grey
					{
						--- LabelDomain ---
							domainAttribute = beginD !
							for = beginD
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
					}
					--- GridCell ---
						gridColumnWidth = 16
						gridColumnCssClass = grey
					{
						--- CaldateField ---
							domainAttribute = beginD !
							format = date
							horizontalAlignment = "${corporatehalign}"
							type = date
							editable = false
							bean-property = beginD
							id = beginD
					}
					--- GridCell ---
						gridColumnWidth = 16
						gridColumnCssClass = grey
					{
						--- LabelDomain ---
							domainAttribute = endD !
							for = endD
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
					}
					--- GridCell ---
						gridColumnWidth = 16
						gridColumnCssClass = grey
					{
						--- CaldateField ---
							domainAttribute = endD !
							format = date
							horizontalAlignment = "${corporatehalign}"
							type = date
							editable = false
							bean-property = endD
							id = endD
					}
					--- GridCell ---
						gridColumnWidth = 16
						gridColumnCssClass = grey
					{
						--- LabelDomain ---
							domainAttribute = redempQuoteN !
							for = redempQuoteN
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
					}
					--- GridCell ---
						gridColumnWidth = 16
						gridColumnCssClass = grey
					{
						--- TextField ---
							domainAttribute = redempQuoteN !
							columns = 21
							format = decimal.detailed
							horizontalAlignment = "${corporatehalign}"
							type = decimal
							chars = 23
							editable = false
							bean-property = redempQuoteN
							id = redempQuoteN
					}
					--- GridCell ---
						gridColumnWidth = 16
						gridColumnCssClass = grey
					{
						--- LabelDomain ---
							domainAttribute = underlyQtyN !
							for = underlyQtyN
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
					}
					--- GridCell ---
						gridColumnWidth = 16
						gridColumnCssClass = grey
					{
						--- TextField ---
							domainAttribute = underlyQtyN !
							columns = 21
							format = decimal.detailed
							horizontalAlignment = "${corporatehalign}"
							type = decimal
							chars = 23
							editable = false
							bean-property = underlyQtyN
							id = underlyQtyN
					}
					--- GridCell ---
						gridColumnWidth = 16
						gridColumnCssClass = grey
					{
						--- LabelDomain ---
							domainAttribute = contractSizeN !
							for = contractSizeN
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							required = true
					}
					--- GridCell ---
						gridColumnWidth = 16
						gridColumnCssClass = grey
					{
						--- TextField ---
							domainAttribute = contractSizeN !
							columns = 21
							format = decimal.detailed
							horizontalAlignment = "${corporatehalign}"
							type = decimal
							chars = 23
							editable = false
							required = true
							bean-property = contractSizeN
							id = contractSizeN
					}
					--- GridCell ---
						gridColumnWidth = 16
						gridColumnCssClass = grey
					{
						--- LabelDomain ---
							domainAttribute = physicalF !
							for = physicalF
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							required = true
					}
					--- GridCell ---
						gridColumnWidth = 16
						gridColumnCssClass = grey
					{
						--- ComboBox ---
							domainAttribute = physicalF !
							horizontalAlignment = "${corporatehalign}"
							editable = false
							required = true
							bean-property = physicalF
							id = physicalF
					}
				}
			}
			--- Box ---
				boxType = vertical
				widgetBorder = box
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 4
					gridColumnsWidth = "16,16,16,48" !
					gridRowCount = 1
				{
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- LabelDomain ---
							domainAttribute = underlyInstr !
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- Include ---
							domainAssociation = underlyInstr
							includeSrc = "" !
							resource:///default/defaultFragments/InstrumentIdentifierView.fragment
							bean-property-prefix = underlyInstr.
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- LabelDomain ---
							labels en = "Underlying Denom.", fr = "Dénom. sous-jacents", de = "Basiswert Denomination"
							domainAttribute = underlyInstr !
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							tid = 26028294842594
					}
					--- GridCell ---
						gridColumnWidth = 48
					{
						--- Include ---
							domainAssociation = underlyInstr
							includeSrc = "" !
							resource:///default/defaultFragments/InstrumentIdentifierDenomView.fragment
							bean-property-prefix = underlyInstr.
					}
				}
			}
		}
		--- Box ---
			boxType = vertical
			widgetBorder = box
		{
			--- TabbedPane ---
				id = s__34
				indexOfSelectedChild = 6
			{
				--- Tab ---
					labels en = Details, de = Details, fr = Détails
					tab-name = Details
					boxType = vertical
					id = tab_Gc_9v
					isWidgetVisible = false
					tid = 92966342870774
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/risklist/RiskList.module
					--- Box ---
						labels en = Advanced, fr = Avancé, de = Erweitert
						boxType = vertical
						widgetBorder = box
						tid = 2426574020414047
					{
						--- Grid ---
							cssClass = blank
							gridColumnCount = 6
							gridColumnsWidth = "16,16,16,16,16,16" !
							gridRowCount = 3
						{
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									domainAttribute = marketThird !
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- Include ---
									domainAssociation = marketThird
									includeSrc = "" !
									resource:///default/defaultFragments/ThirdPartyIdentifierView.fragment
									bean-property-prefix = marketThird.
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									labels en = "Round Lot Quantity"
									domainAttribute = oddLotQtyN !
									for = oddLotQtyN
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
									tid = 2353525956122636
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- TextField ---
									domainAttribute = oddLotQtyN !
									columns = 21
									format = decimal.detailed
									horizontalAlignment = "${corporatehalign}"
									type = decimal
									chars = 23
									editable = false
									bean-property = oddLotQtyN
									id = oddLotQtyN
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									domainAttribute = minTradeQtyN !
									for = minTradeQtyN
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- TextField ---
									domainAttribute = minTradeQtyN !
									columns = 21
									format = decimal.detailed
									horizontalAlignment = "${corporatehalign}"
									type = decimal
									chars = 23
									editable = false
									bean-property = minTradeQtyN
									id = minTradeQtyN
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									domainAttribute = priceCalcRuleE !
									for = priceCalcRuleE
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
									required = true
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- ComboBox ---
									domainAttribute = priceCalcRuleE !
									horizontalAlignment = "${corporatehalign}"
									editable = false
									required = true
									bean-property = priceCalcRuleE
									id = priceCalcRuleE
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									domainAttribute = valRuleE !
									for = valRuleE
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
									required = true
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- ComboBox ---
									domainAttribute = valRuleE !
									horizontalAlignment = "${corporatehalign}"
									editable = false
									required = true
									bean-property = valRuleE
									id = valRuleE
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									domainAttribute = tickSizeN !
									for = tickSizeN
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- TextField ---
									domainAttribute = tickSizeN !
									columns = 21
									format = decimal.detailed
									horizontalAlignment = "${corporatehalign}"
									type = decimal
									chars = 23
									editable = false
									bean-property = tickSizeN
									id = tickSizeN
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									domainAttribute = premiumPmtE !
									for = premiumPmtE
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
									required = true
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- ComboBox ---
									domainAttribute = premiumPmtE !
									horizontalAlignment = "${corporatehalign}"
									editable = false
									required = true
									bean-property = premiumPmtE
									id = premiumPmtE
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									domainAttribute = issuerThird !
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- Include ---
									domainAssociation = issuerThird
									includeSrc = "" !
									resource:///default/defaultFragments/ThirdPartyIdentifierView.fragment
									bean-property-prefix = issuerThird.
							}
							--- GridCell ---
								gridColumnWidth = 16
							--- GridCell ---
								gridColumnWidth = 16
						}
					}
				}
				--- Tab ---
					labels en = Prices, de = Preise, fr = Prix
					tab-name = Prices
					boxType = vertical
					id = tab_eE_s_
					isWidgetVisible = false
					tid = 92966492306471
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/instrprice/InstrPriceList.module
				}
				--- Tab ---
					labels en = Chrono, fr = Chronologie, de = Verlauf
					boxType = vertical
					id = tab_s1___
					isWidgetVisible = false
					tid = 1737779925549476
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/instrchrono/InstrChronoList.module
				}
				--- Tab ---
					labels en = Events, fr = Evénements, de = Ereignisse
					boxType = vertical
					id = tab_b_933
					isWidgetVisible = false
					tid = 1751791339033871
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/exchangeevent/ExchangeEventList.module
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/termevent/TermEventList.module
				}
				--- Tab ---
					labels en = "Trading Places", de = Börsenplatz, fr = "Lieux d\'échange"
					tab-name = "Trading Places"
					boxType = vertical
					id = tab_Fm__L
					isWidgetVisible = false
					tid = 115550845430131
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/tradingplace/TradingPlaceList.module
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/tradingcurrency/TradingCurrencyList.module
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/instrdeposit/InstrumentDepositList.module
				}
				--- Tab ---
					labels en = Identification, fr = Identification, de = Identifizierung
					boxType = vertical
					id = tab_mNQ1_
					isWidgetVisible = false
					tid = 1751968779588746
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/synonym/SynonymList.module
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/denomination/DenominationList.module
				}
				--- Tab ---
					labels en = Notepad, fr = Bloc-note, de = Notizen
					tab-name = Notepad
					boxType = vertical
					id = tab_L___g
					isWidgetSelected = true
					tid = 32100119657548
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/notepad/search/NotepadList.module
				}
			}
		}
	}
}