# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = Stock, fr = Action, de = Aktie
	containment = container
	domainEntity = "AAADSInstrument:InstrumentAll"
	bean-define = DSBean.AAADSInstrument.InstrumentAll
	bean-name = InstrumentAll
	id = StockQuickView_d_57_
	tid = 22024156194431
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/instrument/resume/InstrumentResume.module
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/instrument/view/InstrumentHeaderView.module
		--- Box ---
			labels en = Instrument, de = Instrument, fr = Instrument
			boxType = vertical
			widgetBorder = box
			tid = 1564033090041271
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 6
				gridColumnsWidth = "16,16,16,16,16,16" !
				gridRowCount = 1
			{
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = issuerThird !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- Include ---
						domainAssociation = issuerThird
						includeSrc = "" !
						resource:///default/defaultFragments/ThirdPartyIdentifierView.fragment
						bean-property-prefix = issuerThird.
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = refCurr !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- Include ---
						domainAssociation = refCurr
						includeSrc = "" !
						resource:///default/defaultFragments/CurrencyIdentifierView.fragment
						bean-property-prefix = refCurr.
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = payFreqN !
						for = payFreqN
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- Box ---
					{
						--- TextField ---
							domainAttribute = payFreqN !
							columns = 10
							format = integer
							horizontalAlignment = "${corporatehalign}"
							type = integer
							editable = false
							bean-property = payFreqN
							id = payFreqN
						--- ComboBox ---
							domainAttribute = payFreqUnitE !
							horizontalAlignment = "${corporatehalign}"
							editable = false
							required = true
							bean-property = payFreqUnitE
							id = payFreqUnitE
					}
				}
			}
			--- Grid ---
				cssClass = blank
				gridColumnCount = 4
				gridColumnsWidth = "16,16,16,48" !
				gridRowCount = 1
			{
				--- GridCell ---
					gridColumnWidth = 16
					gridColumnCssClass = grey
				{
					--- LabelDomain ---
						labels en = "Index Name"
						domainAttribute = indexInstr !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						tid = 92101123325171
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- Include ---
						domainAssociation = indexInstr
						includeSrc = "" !
						resource:///default/defaultFragments/InstrumentIdentifierView.fragment
						bean-property-prefix = indexInstr.
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						labels en = "Index denomination ", fr = "Indice denomination ", de = "Index denomination "
						domainAttribute = indexInstr !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						tid = 92108419954770
				}
				--- GridCell ---
					gridColumnWidth = 48
				{
					--- Include ---
						domainAssociation = indexInstr
						includeSrc = "" !
						resource:///default/defaultFragments/InstrumentIdentifierDenomView.fragment
						bean-property-prefix = indexInstr.
				}
			}
		}
		--- Box ---
			boxType = vertical
			widgetBorder = box
		{
			--- TabbedPane ---
				id = s__34
				indexOfSelectedChild = 3
			{
				--- Tab ---
					labels en = Details, fr = Détails, de = Details
					tab-name = Details
					boxType = vertical
					id = tab_O_1sB
					isWidgetVisible = false
					tid = 120894233010551
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/risklist/RiskList.module
					--- Box ---
						labels en = Advanced, fr = Avancé, de = Erweitert
						boxType = vertical
						widgetBorder = box
						tid = 81654817663687
					{
						--- Grid ---
							cssClass = blank
							gridColumnCount = 6
							gridColumnsWidth = "16,16,16,16,16,16" !
							gridRowCount = 4
						{
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									domainAttribute = marketThird !
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- Include ---
									domainAssociation = marketThird
									includeSrc = "" !
									resource:///default/defaultFragments/ThirdPartyIdentifierView.fragment
									bean-property-prefix = marketThird.
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									labels en = "Round Lot Quantity"
									domainAttribute = oddLotQtyN !
									for = oddLotQtyN
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
									tid = 2353161599828749
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- TextField ---
									domainAttribute = oddLotQtyN !
									columns = 21
									format = decimal.detailed
									horizontalAlignment = "${corporatehalign}"
									type = decimal
									chars = 23
									editable = false
									bean-property = oddLotQtyN
									id = oddLotQtyN
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									domainAttribute = minTradeQtyN !
									for = minTradeQtyN
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- TextField ---
									domainAttribute = minTradeQtyN !
									columns = 21
									format = decimal.detailed
									horizontalAlignment = "${corporatehalign}"
									type = decimal
									chars = 23
									editable = false
									bean-property = minTradeQtyN
									id = minTradeQtyN
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									labels en = "Settlement Day "
									domainAttribute = settleDayN !
									for = settleDayN
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
									tid = 2356119766124745
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- TextField ---
									domainAttribute = settleDayN !
									columns = 30
									format = integer
									horizontalAlignment = "${corporatehalign}"
									type = integer
									editable = false
									bean-property = settleDayN
									id = settleDayN
							}
							--- GridCell ---
								gridColumnWidth = 16
							--- GridCell ---
								gridColumnWidth = 16
							--- GridCell ---
								gridColumnWidth = 16
							--- GridCell ---
								gridColumnWidth = 16
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									domainAttribute = priceCalcRuleE !
									for = priceCalcRuleE
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
									required = true
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- ComboBox ---
									domainAttribute = priceCalcRuleE !
									horizontalAlignment = "${corporatehalign}"
									editable = false
									required = true
									bean-property = priceCalcRuleE
									id = priceCalcRuleE
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									domainAttribute = valRuleE !
									for = valRuleE
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
									required = true
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- ComboBox ---
									domainAttribute = valRuleE !
									horizontalAlignment = "${corporatehalign}"
									editable = false
									required = true
									bean-property = valRuleE
									id = valRuleE
							}
							--- GridCell ---
								gridColumnWidth = 16
							--- GridCell ---
								gridColumnWidth = 16
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									domainAttribute = taxGeo !
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- Include ---
									domainAssociation = taxGeo
									includeSrc = "" !
									resource:///default/defaultFragments/GeographicIdentifierView.fragment
									bean-property-prefix = taxGeo.
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									domainAttribute = capTaxRateP !
									for = capTaxRateP
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- TextField ---
									domainAttribute = capTaxRateP !
									columns = 11
									format = percentTA
									horizontalAlignment = "${corporatehalign}"
									type = percent
									chars = 11
									editable = false
									bean-property = capTaxRateP
									id = capTaxRateP
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									domainAttribute = taxRateP !
									for = taxRateP
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- TextField ---
									domainAttribute = taxRateP !
									columns = 11
									format = percentTA
									horizontalAlignment = "${corporatehalign}"
									type = percent
									chars = 11
									editable = false
									bean-property = taxRateP
									id = taxRateP
							}
						}
					}
				}
				--- Tab ---
					labels en = Prices, fr = Prix, de = Preise
					tab-name = Prices
					boxType = vertical
					id = tab_T__A6
					isWidgetVisible = false
					tid = 120894281793343
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/instrprice/InstrPriceList.module
				}
				--- Tab ---
					labels en = Chrono, de = Verlauf, fr = Chronologie
					id = tab_rQ46_
					isWidgetVisible = false
					tid = 101433261250629
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/instrchrono/InstrChronoList.module
				}
				--- Tab ---
					labels en = Events, fr = Evénements, de = Ereignisse
					boxType = vertical
					id = tab_cPE0_
					isWidgetSelected = true
					tid = 2172711917685627
				{
					--- Box ---
					{
						--- Grid ---
							cssClass = blank
							gridColumnCount = 4
							gridColumnsWidth = "25,25,25,25" !
							gridRowCount = 1
						{
							--- GridCell ---
								gridColumnWidth = 25
							{
								--- Box ---
								{
									--- RadioButton ---
										labels en = Dividends, fr = Dividendes, de = Dividenden
										selected = true
										group = Events
										id = Dividends
										tid = 2339228146236183
									--- RadioButton ---
										labels en = "Corporate Action", fr = "Opération sur titres", de = Kapitalmassnahmen
										group = Events
										id = CorporateAction
										tid = 2339245862162928
									--- RadioButton ---
										labels en = Exchange, fr = Echange, de = Austausch
										group = Events
										id = Exchange
										tid = 1381576463064076
								}
							}
							--- GridCell ---
								gridColumnWidth = 25
							--- GridCell ---
								gridColumnWidth = 25
							--- GridCell ---
								gridColumnWidth = 25
						}
					}
					--- Box ---
						boxType = vertical
					{
						--- Conditional ---
							indexOfSelectedChild = 2
						{
							--- ConditionalBody ---
								javaCode = "<nav:is-selected  group-id=\"Events\" element-id=\"Dividends\" default-selected=\"true\"/>"
								technicalName = Dividends
								boxType = vertical
								isWidgetVisible = false
							{
								--- Include ---
									includeSrc = "" !
									resource:///Default/module/aaa/administration/incomeevent/IncomeEventDividendsList.module
							}
							--- ConditionalBody ---
								javaCode = "<nav:is-selected  group-id=\"Events\" element-id=\"CorporateAction\" default-selected=\"true\"/>"
								technicalName = CorporateAction
								boxType = vertical
								isWidgetVisible = false
							{
								--- Include ---
									includeSrc = "" !
									resource:///Default/module/aaa/administration/corporateaction/CorporateActionList.module
							}
							--- ConditionalBody ---
								javaCode = "<nav:is-selected  group-id=\"Events\" element-id=\"Exchange\" default-selected=\"true\"/>"
								technicalName = Exchange
								boxType = vertical
								isWidgetSelected = true
							{
								--- Include ---
									includeSrc = "" !
									resource:///Default/module/aaa/administration/exchangeevent/ExchangeEventList.module
							}
						}
					}
				}
				--- Tab ---
					labels en = Sector, fr = Secteur, de = Branche
					boxType = vertical
					id = tab_f_X2_
					isWidgetVisible = false
					tid = 2172693714676586
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/sectorattrib/SectorAttribList.module
				}
				--- Tab ---
					labels en = Rating, fr = Notation, de = Bonität
					boxType = vertical
					id = tab_w_Kl9
					isWidgetVisible = false
					tid = 2172590543080195
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/ratingattrib/RatingAttribList.module
				}
				--- Tab ---
					labels en = Trading, de = Börsenplatz, fr = "Conditions de négociations"
					tab-name = "Trading Places"
					boxType = vertical
					id = tab_ls1fi
					isWidgetVisible = false
					tid = 115594876869118
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/tradingplace/TradingPlaceList.module
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/tradingcurrency/TradingCurrencyList.module
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/instrdeposit/InstrumentDepositList.module
				}
				--- Tab ---
					labels en = Identification, fr = Identification, de = Identifizierung
					boxType = vertical
					id = tab_l_9L1
					isWidgetVisible = false
					tid = 1311409134222492
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/synonym/SynonymList.module
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/denomination/DenominationList.module
				}
				--- Tab ---
					labels en = Notepad, fr = Bloc-note, de = Notizen
					tab-name = Notepad
					boxType = vertical
					id = tab_t9916
					isWidgetVisible = false
					tid = 27491633417731
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/notepad/search/NotepadList.module
				}
			}
		}
	}
}