# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = Swap, de = Swap, fr = Swap
	containment = container
	domainEntity = "AAADSInstrument:InstrumentAll"
	bean-define = DSBean.AAADSInstrument.InstrumentAll
	bean-name = InstrumentAll
	id = SwapQuickView_t3_4_
	tid = 2240088200759035
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/instrument/resume/InstrumentResume.module
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/instrument/view/InstrumentHeaderView.module
		--- Box ---
			labels en = Instrument, de = Instrument, fr = Instrument
			boxType = vertical
			widgetBorder = box
			tid = 2257173136014214
		{
			--- Box ---
				labels en = Swap, de = Swap, fr = Swap
				boxType = vertical
				verticalAlignment = lead
				widgetBorder = box
				tid = 1735082168601
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 6
					gridColumnsWidth = "16,16,16,16,16,16" !
					gridRowCount = 2
				{
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- LabelDomain ---
							domainAttribute = beginD !
							for = beginD
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- CaldateField ---
							domainAttribute = beginD !
							format = date
							horizontalAlignment = "${corporatehalign}"
							type = date
							editable = false
							bean-property = beginD
							id = beginD
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- LabelDomain ---
							domainAttribute = endD !
							for = endD
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- CaldateField ---
							domainAttribute = endD !
							format = date
							horizontalAlignment = "${corporatehalign}"
							type = date
							editable = false
							bean-property = endD
							id = endD
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- LabelDomain ---
							domainAttribute = tenorFreqN !
							for = tenorFreqN
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- Box ---
						{
							--- TextField ---
								domainAttribute = tenorFreqN !
								columns = 4
								format = integer
								horizontalAlignment = "${corporatehalign}"
								type = integer
								editable = false
								bean-property = tenorFreqN
								id = tenorFreqN
							--- ComboBox ---
								domainAttribute = tenorFreqUnitE !
								horizontalAlignment = "${corporatehalign}"
								editable = false
								required = true
								bean-property = tenorFreqUnitE
								id = tenorFreqUnitE
						}
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- LabelDomain ---
							domainAttribute = principalRuleE !
							for = principalRuleE
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							required = true
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- ComboBox ---
							domainAttribute = principalRuleE !
							horizontalAlignment = "${corporatehalign}"
							editable = false
							required = true
							bean-property = principalRuleE
							id = principalRuleE
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- LabelDomain ---
							domainAttribute = addMarginP !
							for = addMarginP
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- TextField ---
							domainAttribute = addMarginP !
							columns = 11
							format = percentTA
							horizontalAlignment = "${corporatehalign}"
							type = percent
							chars = 11
							editable = false
							bean-property = addMarginP
							id = addMarginP
					}
					--- GridCell ---
						gridColumnWidth = 16
					--- GridCell ---
						gridColumnWidth = 16
				}
			}
			--- Box ---
				labels en = "Receiving Leg", de = "Empfangende Seite", fr = "Jambe receveuse"
				boxType = vertical
				verticalAlignment = lead
				widgetBorder = box
				tid = 1735098799417
			{
				--- Box ---
					boxType = vertical
					widgetBorder = box
				{
					--- Grid ---
						cssClass = blank
						gridColumnCount = 4
						gridColumnsWidth = "16,16,16,48" !
						gridRowCount = 2
					{
						--- GridCell ---
							gridColumnWidth = 16
							gridColumnCssClass = grey
						{
							--- LabelDomain ---
								domainAttribute = interestRateP !
								for = interestRateP
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- TextField ---
								domainAttribute = interestRateP !
								columns = 11
								format = percentTA
								horizontalAlignment = "${corporatehalign}"
								type = percent
								chars = 11
								editable = false
								bean-property = interestRateP
								id = interestRateP
						}
						--- GridCell ---
							gridColumnWidth = 16
						--- GridCell ---
							gridColumnWidth = 48
						--- GridCell ---
							gridColumnWidth = 16
							gridColumnCssClass = grey
						{
							--- LabelDomain ---
								domainAttribute = floatInstr !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- Include ---
								domainAssociation = floatInstr
								includeSrc = "" !
								resource:///default/defaultFragments/InstrumentIdentifierView.fragment
								bean-property-prefix = floatInstr.
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								labels en = "Floating Rate Instrument Denom.", fr = "Denomination de l\'instrument à taux variable", de = "Bez. variable verzinsl. Instrument "
								domainAttribute = floatInstr !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 442373889255757
						}
						--- GridCell ---
							gridColumnWidth = 48
						{
							--- Include ---
								domainAssociation = floatInstr
								includeSrc = "" !
								resource:///default/defaultFragments/InstrumentIdentifierDenomView.fragment
								bean-property-prefix = floatInstr.
						}
					}
				}
				--- Box ---
					boxType = vertical
					widgetBorder = box
				{
					--- Grid ---
						cssClass = blank
						gridColumnCount = 6
						gridColumnsWidth = "16,16,16,16,16,16" !
						gridRowCount = 2
					{
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = refCurr !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- Include ---
								domainAssociation = refCurr
								includeSrc = "" !
								resource:///default/defaultFragments/CurrencyIdentifierView.fragment
								bean-property-prefix = refCurr.
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = calendar !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- Include ---
								domainAssociation = calendar
								includeSrc = "" !
								resource:///default/defaultFragments/CalendarIdentifierView.fragment
								bean-property-prefix = calendar.
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = eomE !
								for = eomE
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- ComboBox ---
								domainAttribute = eomE !
								horizontalAlignment = "${corporatehalign}"
								editable = false
								required = true
								bean-property = eomE
								id = eomE
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = payFreqN !
								for = payFreqN
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- Box ---
							{
								--- TextField ---
									domainAttribute = payFreqN !
									columns = 3
									format = integer
									horizontalAlignment = "${corporatehalign}"
									type = integer
									editable = false
									bean-property = payFreqN
									id = payFreqN
								--- ComboBox ---
									domainAttribute = payFreqUnitE !
									horizontalAlignment = "${corporatehalign}"
									editable = false
									required = true
									bean-property = payFreqUnitE
									id = payFreqUnitE
							}
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = accrualRuleE !
								for = accrualRuleE
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- ComboBox ---
								domainAttribute = accrualRuleE !
								horizontalAlignment = "${corporatehalign}"
								editable = false
								required = true
								bean-property = accrualRuleE
								id = accrualRuleE
						}
						--- GridCell ---
							gridColumnWidth = 16
						--- GridCell ---
							gridColumnWidth = 16
					}
				}
			}
			--- Box ---
				labels en = "Paying Leg", de = "Zahlende Seite", fr = "Jambe payeuse"
				boxType = vertical
				verticalAlignment = lead
				widgetBorder = box
				tid = 1735104793132
			{
				--- Box ---
					boxType = vertical
					widgetBorder = box
				{
					--- Grid ---
						cssClass = blank
						gridColumnCount = 4
						gridColumnsWidth = "16,16,16,48" !
						gridRowCount = 2
					{
						--- GridCell ---
							gridColumnWidth = 16
							gridColumnCssClass = grey
						{
							--- LabelDomain ---
								labels en = "Interest Rate", fr = "Taux d\'intérêts", de = Zinssatz
								domainAttribute = paidInterestRateP !
								for = paidInterestRateP
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 107494556099056
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- TextField ---
								domainAttribute = paidInterestRateP !
								columns = 11
								format = percentTA
								horizontalAlignment = "${corporatehalign}"
								type = percent
								chars = 11
								editable = false
								bean-property = paidInterestRateP
								id = paidInterestRateP
						}
						--- GridCell ---
							gridColumnWidth = 16
						--- GridCell ---
							gridColumnWidth = 48
						--- GridCell ---
							gridColumnWidth = 16
							gridColumnCssClass = grey
						{
							--- LabelDomain ---
								labels de = "Instrument mit variablem Zins", fr = "Instrument à taux variable", en = "Floating Rate Instrument"
								domainAttribute = paidFloatInstr !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 1735106773501
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- Include ---
								domainAssociation = paidFloatInstr
								includeSrc = "" !
								resource:///default/defaultFragments/InstrumentIdentifierView.fragment
								bean-property-prefix = paidFloatInstr.
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								labels en = "Floating Rate Instrument Denom.", de = "Bez. variable verzinsl. Instrument ", fr = "Denomination de l\'instrument à taux variable"
								domainAttribute = paidFloatInstr !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 442389777768962
						}
						--- GridCell ---
							gridColumnWidth = 48
						{
							--- Include ---
								domainAssociation = paidFloatInstr
								includeSrc = "" !
								resource:///default/defaultFragments/InstrumentIdentifierDenomView.fragment
								bean-property-prefix = paidFloatInstr.
						}
					}
				}
				--- Box ---
					boxType = vertical
					widgetBorder = box
				{
					--- Grid ---
						cssClass = blank
						gridColumnCount = 6
						gridColumnsWidth = "16,16,16,16,16,16" !
						gridRowCount = 2
					{
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								labels de = Referenzwährung, en = "Reference Currency", fr = "Devise de référence"
								domainAttribute = swapPaidCurr !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 107669680212205
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- Include ---
								domainAssociation = swapPaidCurr
								includeSrc = "" !
								resource:///default/defaultFragments/CurrencyIdentifierView.fragment
								bean-property-prefix = swapPaidCurr.
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								labels en = Calendar, fr = Calendrier, de = Kalender
								domainAttribute = paidCalendar !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 107793253450443
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- Include ---
								domainAssociation = paidCalendar
								includeSrc = "" !
								resource:///default/defaultFragments/CalendarIdentifierView.fragment
								bean-property-prefix = paidCalendar.
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								labels en = "End of Month Convention", fr = "Convention fin de mois", de = Monatsende-Konvention
								domainAttribute = paidEomE !
								for = paidEomE
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
								tid = 107821932884884
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- ComboBox ---
								domainAttribute = paidEomE !
								horizontalAlignment = "${corporatehalign}"
								editable = false
								required = true
								bean-property = paidEomE
								id = paidEomE
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								labels de = Zahlungsfrequenz, en = " Payment Frequency"
								domainAttribute = paidPayFreqN !
								for = paidPayFreqN
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 1735107767962
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- Box ---
							{
								--- TextField ---
									domainAttribute = paidPayFreqN !
									columns = 3
									format = integer
									horizontalAlignment = "${corporatehalign}"
									type = integer
									editable = false
									bean-property = paidPayFreqN
									id = paidPayFreqN
								--- ComboBox ---
									domainAttribute = paidPayFreqUnitE !
									horizontalAlignment = "${corporatehalign}"
									editable = false
									required = true
									bean-property = paidPayFreqUnitE
									id = paidPayFreqUnitE
							}
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								labels de = Zuwachsregel, en = "Accrual Rule", fr = "Règle de calcul des intérêts"
								domainAttribute = paidAccrualRuleE !
								for = paidAccrualRuleE
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
								tid = 1735109714968
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- ComboBox ---
								domainAttribute = paidAccrualRuleE !
								horizontalAlignment = "${corporatehalign}"
								editable = false
								required = true
								bean-property = paidAccrualRuleE
								id = paidAccrualRuleE
						}
						--- GridCell ---
							gridColumnWidth = 16
						--- GridCell ---
							gridColumnWidth = 16
					}
				}
			}
		}
		--- Box ---
			boxType = vertical
		{
			--- TabbedPane ---
				id = t9y9_
				indexOfSelectedChild = 4
			{
				--- Tab ---
					labels en = Details, fr = Détails, de = Details
					boxType = vertical
					id = tab_K_ry8
					isWidgetVisible = false
					tid = 2173775996306234
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/risklist/RiskList.module
					--- Box ---
						labels en = Advanced, fr = Avancé, de = Erweitert
						boxType = vertical
						widgetBorder = box
						tid = 66712349336018
					{
						--- Grid ---
							cssClass = blank
							gridColumnCount = 6
							gridColumnsWidth = "16,16,16,16,16,16" !
							gridRowCount = 1
						{
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									domainAttribute = priceCalcRuleE !
									for = priceCalcRuleE
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
									required = true
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- ComboBox ---
									domainAttribute = priceCalcRuleE !
									horizontalAlignment = "${corporatehalign}"
									editable = false
									required = true
									bean-property = priceCalcRuleE
									id = priceCalcRuleE
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									domainAttribute = valRuleE !
									for = valRuleE
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
									required = true
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- ComboBox ---
									domainAttribute = valRuleE !
									horizontalAlignment = "${corporatehalign}"
									editable = false
									required = true
									bean-property = valRuleE
									id = valRuleE
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									domainAttribute = contractSizeN !
									for = contractSizeN
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
									required = true
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- TextField ---
									domainAttribute = contractSizeN !
									columns = 21
									format = decimal.detailed
									horizontalAlignment = "${corporatehalign}"
									type = decimal
									chars = 23
									editable = false
									required = true
									bean-property = contractSizeN
									id = contractSizeN
							}
						}
					}
				}
				--- Tab ---
					labels en = Price, fr = Prix, de = Preise
					boxType = vertical
					id = tab_X909_
					isWidgetVisible = false
					tid = 2173794908243645
				{
					--- Box ---
						boxType = vertical
					{
						--- Include ---
							includeSrc = "" !
							resource:///Default/module/aaa/administration/instrprice/InstrPriceList.module
					}
				}
				--- Tab ---
					labels en = Events, fr = Evénements, de = Ereignisse
					boxType = vertical
					id = tab_j4_7_
					isWidgetVisible = false
					tid = 2173806659134331
				{
					--- Box ---
					{
						--- Grid ---
							cssClass = blank
							gridColumnCount = 4
							gridColumnsWidth = "25,25,25,25" !
							gridRowCount = 1
						{
							--- GridCell ---
								gridColumnWidth = 25
							{
								--- Box ---
								{
									--- RadioButton ---
										labels en = Income, fr = Revenu, de = Zinszahlung
										selected = true
										group = Events
										id = Income
										tid = 69413239975192
									--- RadioButton ---
										labels en = "Issue and Redemption", de = "Ausgabe / Fälligkeit", fr = "Emission et rachat"
										group = Events
										id = IssueRedemption
										tid = 69413241730722
									--- RadioButton ---
										labels en = "Interest Rate Condition", fr = "Condition de taux d\'intérêt", de = Zinskonditionen
										group = Events
										id = InterestRate
										tid = 69413247591802
								}
							}
							--- GridCell ---
								gridColumnWidth = 25
							--- GridCell ---
								gridColumnWidth = 25
							--- GridCell ---
								gridColumnWidth = 25
						}
					}
					--- Box ---
						boxType = vertical
					{
						--- Conditional ---
							indexOfSelectedChild = 0
						{
							--- ConditionalBody ---
								javaCode = "<nav:is-selected  group-id=\"Events\" element-id=\"Income\" default-selected=\"true\"/>"
								technicalName = Income
								boxType = vertical
								isWidgetSelected = true
							{
								--- Include ---
									includeSrc = "" !
									resource:///Default/module/aaa/administration/incomeevent/IncomeEventList.module
							}
							--- ConditionalBody ---
								javaCode = "<nav:is-selected  group-id=\"Events\" element-id=\"IssueRedemption\" default-selected=\"true\"/>"
								technicalName = IssueRedemption
								boxType = vertical
								isWidgetVisible = false
							{
								--- Include ---
									includeSrc = "" !
									resource:///Default/module/aaa/administration/issredmevent/IssueRedemptionEventList.module
							}
							--- ConditionalBody ---
								javaCode = "<nav:is-selected  group-id=\"Events\" element-id=\"InterestRate\" default-selected=\"true\"/>"
								technicalName = InterestRate
								boxType = vertical
								isWidgetVisible = false
							{
								--- Include ---
									includeSrc = "" !
									resource:///Default/module/aaa/administration/interestcond/InterestConditionList.module
							}
						}
					}
				}
				--- Tab ---
					labels en = Identification, fr = Identification, de = Identifizierung
					boxType = vertical
					id = tab_Qy6e_
					isWidgetVisible = false
					tid = 2173825360826864
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/synonym/SynonymList.module
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/denomination/DenominationList.module
				}
				--- Tab ---
					labels en = Notepad, de = Notizen, fr = Bloc-note
					boxType = vertical
					id = tab_py_69
					isWidgetSelected = true
					tid = 2173835976949863
				{
					--- Box ---
						boxType = vertical
					{
						--- Include ---
							includeSrc = "" !
							resource:///Default/module/aaa/administration/notepad/search/NotepadList.module
					}
				}
			}
		}
	}
}