# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "List Of Allocation Rules", de = "Liste Verteilungs-Regeln", fr = "Liste des règles d\'allocation"
	domainEntity = "AAADSExtStrategyElement:ExtStrategyElementDomainList"
	bean-define = DSTableModel.AAADSExtStrategyElement.ExtStrategyElementDomainList
	bean-name = ExtStrategyElementDomainList
	id = InstrResultPercentOfPtfEdit_T1__3
	tid = 1270330225564054
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			id = Sc17_
			table-model-reference = DSTableModel.AAADSExtStrategyElement.ExtStrategyElementDomainList
			table-column-count = 16 !
			table-columns-width = "6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6" !
		{
			--- TableColumn ---
				column-name = id !
				column-type = domain !
				domainAttribute = id !
				type = text
				column-visibility = never-visible
				id = id
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = id
					format = integer
					previewValue = value
			}
			--- TableColumn ---
				column-name = UPDATE
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				column-width = 2%
				id = Dq_Kh
				table-column-width = 6
			{
				--- Icon ---
					toolTips en = "Update Allocation Rule", de = "Instruktion aktualisieren", fr = "Mettre à jour les instructions"
					horizontalAlignment = center
					icon = application_form_edit
					id = YDY__
					tid = 1813538353665343
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = edit-instruction ud
						id = "<udp:item column=\"id\"/>" ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- TableColumn ---
				column-name = DELETE
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				column-width = 2%
				id = j8w2s
				table-column-width = 6
			{
				--- Icon ---
					toolTips en = "Delete Allocation Rule", de = "Instruktion löschen", fr = "Supprimer l\'Instruction"
					horizontalAlignment = center
					icon = application_form_delete
					id = D5_B1
					tid = 1813538354638423
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = delete-instruction ud
						id = "<udp:item column=\"id\"/>" ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- TableColumn ---
				column-name = instrCode !
				column-type = domain !
				domainAttribute = instrCode !
				type = text
				id = instrCode
				table-column-width = 6
			{
				--- Icon ---
					toolTips fr = "Voir les détails de l\'instrument", en = "View Instrument Details", de = "Details des Instruments ansehen"
					icon = application_form_magnify
					id = LMC_Q
					tid = 1227864708418200
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "resource:///administration/instrument/InstrumentQuickView.pageflow"
						target = popup
						code = "<udp:item column=\"instrCode\"/>" ud
						only-changed = false
						prevalidate = false
						modal = false
					}
				}
				--- Spacer ---
					height = 4
					width = 10
				--- TableColumnItem ---
					item-column = instrCode
					previewValue = value
			}
			--- TableColumn ---
				labels fr = Objectif, de = Zielgewicht, en = "Weight %"
				column-name = objWeightContN !
				column-type = domain !
				domainAttribute = objWeightContN !
				type = text
				id = objWeightContN
				table-column-width = 6
				tid = 1813538356632059
			{
				--- TableColumnItem ---
					item-column = objWeightContN
					format = decimal.detailed
					previewValue = value
			}
			--- TableColumn ---
				column-name = objWeightContMargN !
				column-type = domain !
				domainAttribute = objWeightContMargN !
				format = decimal.detailed
				type = text
				id = objWeightContMargN
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = objWeightContMargN
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Last Quote", fr = "Cours courant", de = "Aktueller Kurs"
				column-name = Last_Quote
				type = amount
				id = K3OL4
				column-computation = make-amount
				column-computation-parameters = "currentQuoteN,currQuoteCurrCode"
				table-column-width = 6
				tid = 82859830860560
			{
				--- TableColumnItem ---
					item-column = Last_Quote
					previewValue = value
			}
			--- TableColumn ---
				labels fr = "Nature de l\'ordre"
				column-name = actualOrderNatE !
				column-type = domain !
				domainAttribute = actualOrderNatE !
				type = text
				id = actualOrderNatE
				table-column-width = 6
				tid = 1813538357633368
			{
				--- TableColumnItem ---
					item-column = actualOrderNatE
					previewValue = value
			}
			--- TableColumn ---
				labels en = Limit, fr = Limite, de = Limit-Kurs
				column-name = Limit_Quote
				type = amount
				id = b5Lt_
				column-computation = make-amount
				column-computation-parameters = "orderQuoteN,orderQuoteCurrCode"
				table-column-width = 6
				tid = 82920214399581
			{
				--- TableColumnItem ---
					item-column = Limit_Quote
					previewValue = value
			}
			--- TableColumn ---
				labels en = Stop, fr = Stop, de = Stop-Kurs
				column-name = Stop_Quote
				type = amount
				id = q34_1
				column-computation = make-amount
				column-computation-parameters = "stopQuoteN,orderQuoteCurrCode"
				table-column-width = 6
				tid = 82934107839031
			{
				--- TableColumnItem ---
					item-column = Stop_Quote
					previewValue = value
			}
			--- TableColumn ---
				labels en = Validity, fr = "Date de validité", de = Limit-Datum
				column-name = orderLimitD !
				column-type = domain !
				domainAttribute = orderLimitD !
				type = text
				id = orderLimitD
				table-column-width = 6
				tid = 1813538360624036
			{
				--- TableColumnItem ---
					item-column = orderLimitD
					format = date
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Last Quote", fr = "Dernier cours", de = "Aktueller Kurs"
				column-name = currentQuoteN !
				column-type = domain !
				domainAttribute = currentQuoteN !
				type = text
				column-visibility = never-visible
				id = currentQuoteN
				table-column-width = 6
				tid = 1813538355640587
			{
				--- TableColumnItem ---
					item-column = currentQuoteN
					format = decimal.detailed
					previewValue = value
			}
			--- TableColumn ---
				column-name = currQuoteCurrCode !
				column-type = domain !
				domainAttribute = currQuoteCurrCode !
				type = text
				column-visibility = never-visible
				id = currQuoteCurrCode
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = currQuoteCurrCode
					previewValue = value
			}
			--- TableColumn ---
				labels en = Limit, fr = Limite, de = Limit-Kurs
				column-name = orderQuoteN !
				column-type = domain !
				domainAttribute = orderQuoteN !
				type = text
				column-visibility = never-visible
				id = orderQuoteN
				table-column-width = 6
				tid = 1813538358640238
			{
				--- TableColumnItem ---
					item-column = orderQuoteN
					format = decimal.detailed
					previewValue = value
			}
			--- TableColumn ---
				column-name = orderQuoteCurrCode !
				column-type = domain !
				domainAttribute = orderQuoteCurrCode !
				type = text
				column-visibility = never-visible
				id = orderQuoteCurrCode
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = orderQuoteCurrCode
					previewValue = value
			}
			--- TableColumn ---
				labels en = Stop, de = Stop-Kurs
				column-name = stopQuoteN !
				column-type = domain !
				domainAttribute = stopQuoteN !
				type = text
				column-visibility = never-visible
				id = stopQuoteN
				table-column-width = 6
				tid = 1813538359654807
			{
				--- TableColumnItem ---
					item-column = stopQuoteN
					format = decimal.detailed
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = id
				sort-direction = descending
				sort-rank = 1
		}
	}
}