# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSDomain:DomainContext"
	collapsible = true
	cssClass = nodeco
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = ContextBasicNotEdited_o03u5
{
	--- Box ---
		boxType = vertical
		cssClass = nodeco
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 6
			gridColumnsWidth = "33,13,13,15,13,13" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 33
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainPerformancePortfolioDimensionNotEdited.fragment
			}
			--- GridCell ---
				gridColumnWidth = 13
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainFromDateNotEdited.fragment
			}
			--- GridCell ---
				gridColumnWidth = 13
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainPivotDateTillNotEdited.fragment
			}
			--- GridCell ---
				gridColumnWidth = 15
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainRefCurrencyNotEdited.fragment
			}
			--- GridCell ---
				gridColumnWidth = 13
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainHierarchyIdentifierNotEdited.fragment
			}
			--- GridCell ---
				gridColumnWidth = 13
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainConsolidationIdentifierNotEdited.fragment
			}
		}
	}
}