# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = Context, fr = Contexte, de = Kontext
	containment = container
	domainEntity = "AAADSDomain:DomainContext"
	collapsible = true
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = Context_W__H8
	tid = 286995510822202
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TabbedPane ---
			id = U___6
			indexOfSelectedChild = 1
		{
			--- Tab ---
				labels fr = Base, en = Basic, de = Einfach
				id = perf_attrib_basic
				isWidgetVisible = false
				tid = 286995512768082
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/performance/attribution/context/ContextBasic.module
			}
			--- Tab ---
				labels fr = Avancée, en = Advanced, de = Erweitert
				id = perf_attrib_advanced
				isWidgetSelected = true
				tid = 286995514722866
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/performance/attribution/context/ContextAdvanced.module
			}
		}
		--- Grid ---
			cssClass = blank
			gridColumnCount = 4
			gridColumnsWidth = "25,25,25,25" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Button ---
					labels en = Execute, de = Ausführen, fr = Exécuter
					id = btn_a_C0d
					tid = 286995516678814
				{
					Event OnClick (submit)
					{
						method = get
						call-URI = "<pageflow:continuation/>"
						widget-group-ref = form
						param = "flow-action=execute"
						only-changed = true
						prevalidate = false
						modal = false
					}
				}
				--- Button ---
					labels en = Refresh, de = Aktualisieren, fr = Actualiser
					id = btn_I12__
					tid = 286995520627303
				{
					Event OnClick (submit)
					{
						method = get
						call-URI = "<pageflow:continuation/>"
						widget-group-ref = form
						param = "flow-action=execute,DSAction=refresh"
						only-changed = true
						prevalidate = false
						modal = false
					}
				}
				--- Button ---
					labels en = "Default Settings", de = Standardeinstellung, fr = "Valeurs par défaut"
					id = btn_ll_LU
					tid = 286995524141582
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = reset ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
		}
	}
}