# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSDomain:DomainContext"
	collapsible = true
	cssClass = nodeco
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = ContextAdvancedNotEdited_ORV_K
{
	--- Box ---
		boxType = vertical
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 5
			gridColumnsWidth = "10,12,15,20,20" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 10
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainPLMethodNotEdited.fragment
			}
			--- GridCell ---
				gridColumnWidth = 12
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainDynamicWeightNotEdited.fragment
			}
			--- GridCell ---
				gridColumnWidth = 15
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainRiskExposureNotEdited.fragment
			}
			--- GridCell ---
				gridColumnWidth = 20
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainPerformanceFrequency1NotEditedWithNotEditableUnit.fragment
			}
			--- GridCell ---
				gridColumnWidth = 20
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainPerformanceDetailLevelNotEdited.fragment
			}
		}
		--- Grid ---
			cssClass = blank
			gridColumnCount = 1
			gridColumnsWidth = 100 !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 100
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainStrategyLinkNotEdited.fragment
			}
		}
	}
}