# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Portfolio Details", fr = "Détails du portefeuille", de = "Details des Portfolios"
	domainEntity = "AAADSDomain:DomainContextDetail"
	collapsed = true
	bean-define = DSActivityBean.AAADSDomain.DomainContextDetail
	bean-name = DomainContextDetail
	id = PortfolioCodeDetailHead_ey_5l
	tid = 287084830768023
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			id = s_1_r
			indexOfSelectedChild = 0
		{
			--- Tab ---
				labels en = Basic, fr = Base, de = Einfach
				id = perf_attrib_basic_details
				isWidgetSelected = true
				tid = 287084832724771
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 6
					gridColumnsWidth = "20,16,16,16,16,16" !
					gridRowCount = 1
					verticalAlignment = lead
				{
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainPortfolioCodeView.fragment
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainFromDateView.fragment
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainPivotDateTillView.fragment
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainRefCurrencyView.fragment
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainHierarchyIdentifierView.fragment
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainConsolidationIdentifierView.fragment
					}
				}
			}
			--- Tab ---
				labels en = Advanced, fr = Avancé, de = Erweitert
				id = perf_attrib_advanced_details
				isWidgetVisible = false
				tid = 287084834673438
			{
				--- Box ---
					boxType = vertical
				{
					--- Grid ---
						cssClass = blank
						gridColumnCount = 6
						gridColumnsWidth = "10,12,15,20,20,23" !
						gridRowCount = 1
					{
						--- GridCell ---
							gridColumnWidth = 10
						{
							--- Include ---
								includeSrc = "" !
								resource:///default/domain/basicelements/DomainPLMethodView.fragment
						}
						--- GridCell ---
							gridColumnWidth = 12
						{
							--- Include ---
								includeSrc = "" !
								resource:///default/domain/basicelements/DomainDynamicWeightView.fragment
						}
						--- GridCell ---
							gridColumnWidth = 15
						{
							--- Include ---
								includeSrc = "" !
								resource:///default/domain/basicelements/DomainRiskExposureView.fragment
						}
						--- GridCell ---
							gridColumnWidth = 20
						{
							--- Include ---
								includeSrc = "" !
								resource:///default/domain/basicelements/DomainPerformanceFrequency1View.fragment
						}
						--- GridCell ---
							gridColumnWidth = 20
						{
							--- Include ---
								includeSrc = "" !
								resource:///default/domain/basicelements/DomainPerformanceAttribFreqView.fragment
						}
						--- GridCell ---
							gridColumnWidth = 23
						{
							--- Include ---
								includeSrc = "" !
								resource:///default/domain/basicelements/DomainPerformanceAttribMethodView.fragment
						}
					}
					--- Grid ---
						cssClass = blank
						gridColumnCount = 2
						gridColumnsWidth = "5,40" !
						gridRowCount = 1
					{
						--- GridCell ---
							gridColumnWidth = 5
						{
							--- Include ---
								includeSrc = "" !
								resource:///default/domain/basicelements/DomainPerformanceDetailLevelView.fragment
						}
						--- GridCell ---
							gridColumnWidth = 40
						{
							--- Include ---
								includeSrc = "" !
								resource:///default/domain/basicelements/DomainPortfolioDetailsStrategyLinkView.fragment
						}
					}
				}
			}
		}
	}
}