/*
* generated by Xtext
*/
package com.odcgroup.service.model;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ComponentUiInjectorProvider implements IInjectorProvider {

	public Injector getInjector() {
		return com.odcgroup.service.model.ui.internal.ComponentActivator.getInstance().getInjector("com.odcgroup.service.model.Component");
	}

}
