# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Cash Summary View", de = "Geldfluss Zusammenfassung", fr = "Vue sommaire de liquidité"
	domainEntity = "AAADSFutureCashFlow:FutureCashFlowSummaryList"
	bean-define = DSBean.AAADSFutureCashFlow.FutureCashFlowSummaryList
	bean-name = FutureCashFlowSummaryList
	id = FutureCashFlowBalanceNoEvent_HG6B0
	documentation = "Using as reference the From date of the context (domain), this module displays all cumulated futur cash flows (balances) for the following periods:\r\n\r\n- today\r\n- next year\r\n- in 2 years\r\n- in 3 years\r\n- in 4 years\r\n- in 5 years\r\n- in 6 years and more"
	tid = 658512903979137
{
	--- Box ---
		boxType = vertical
	{
		--- Box ---
			boxType = vertical
		{
			--- Label ---
				labels en = "Flow per Dates", de = "Geldfluss per  Datum", fr = "Flux par dates"
				id = b288v
				tid = 658512904932610
			--- Label ---
				labels en = "Balance per Dates", de = "Saldo per Datum", fr = "Balance par dates"
				cssClass = "blue bold italic fs12"
				id = O2216
				tid = 658512907249385
		}
		--- TableTree ---
			table-rendering-mode = summary-delegated
			id = g7__F
			documentation = "This table displays the cumulated futur cash flows (balances) from today, splitted in period of one year. The reference date used to define today is the From date of the context (domain)."
			table-column-count = 18 !
			table-columns-width = "5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5" !
		{
			--- TableColumn ---
				labels en = Portfolio, fr = Portefeuille, de = Portfolio
				column-display-grouping = true
				column-name = GROUPING
				column-type = placeholder !
				type = text
				column-locked = true
				column-sortable = false !
				column-width = 200
				column-wrapped = false
				id = P_W7_
				table-column-width = 5
				tid = 658512908811594
			{
				--- TableGroup ---
					group-column-name = CURR_CLASS_CODE
					group-sorting-column-name = CURR_CLASS_RANK
					group-sorting-direction = ascending
					group-rank = 4
				--- TableGroup ---
					group-column-name = PTF_HIER_STR
					group-sorting-column-name = PTF_HIER_STR
					group-sorting-direction = ascending
					hierarchy = true
					group-rank = 1
			}
			--- TableColumn ---
				column-name = THIRD_COMP_RULE !
				column-type = domain !
				domainAttribute = THIRD_COMP_RULE !
				type = text
				column-visibility = not-visible
				id = THIRD_COMP_RULE
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = THIRD_COMP_RULE
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Start Date", de = Anfangsdatum, fr = "Date de début"
				column-name = StartDate
				type = amount
				id = Gx__3
				column-computation = make-amount
				column-computation-parameters = "DEBIT_CREDIT_PER_0,POS_CURRENCY"
				table-column-width = 5
				tid = 658512910773296
			{
				--- TableColumnItem ---
					toolTips en = Flow, fr = Flux, de = Flüsse
					item-column = StartDate
					item-halign = trail
					item-width = 100
					previewValue = value
					tid = 658512912738350
				--- TableColumnItem ---
					toolTips en = Balance, fr = Solde, de = Saldo
					item-column = Balance_per_0
					item-css = "blue bold italic fs12"
					item-halign = trail
					item-width = 100
					newLine = true
					previewValue = value
					tid = 658512914687760
			}
			--- TableColumn ---
				column-name = Balance_per_0
				type = amount
				column-visibility = never-visible
				id = B_309
				column-computation = make-amount
				column-computation-parameters = "BALANCE_PER_0,POS_CURRENCY"
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = Balance_per_0
					previewValue = value
			}
			--- TableColumn ---
				labels en = "One Week", de = "Eine Woche", fr = "Une semaine"
				column-name = NextWeek
				type = amount
				id = w_0YO
				column-computation = make-amount
				column-computation-parameters = "DEBIT_CREDIT_PER_1,POS_CURRENCY"
				table-column-width = 5
				tid = 658512916622643
			{
				--- TableColumnItem ---
					toolTips en = Flow, fr = Flux, de = Flüsse
					item-column = NextWeek
					item-halign = trail
					item-width = 100
					previewValue = value
					tid = 658512918578199
				--- TableColumnItem ---
					toolTips en = Balance, fr = Solde, de = Saldo
					item-column = Balance_per_1
					item-css = "blue bold italic fs12"
					item-halign = trail
					item-width = 100
					newLine = true
					previewValue = value
					tid = 658512920533755
			}
			--- TableColumn ---
				column-name = Balance_per_1
				type = amount
				column-visibility = never-visible
				id = o9v_1
				column-computation = make-amount
				column-computation-parameters = "BALANCE_PER_1,POS_CURRENCY"
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = Balance_per_1
					previewValue = value
			}
			--- TableColumn ---
				labels en = "One Month", de = "Ein Monat", fr = "Un mois"
				column-name = OneMonth
				type = amount
				id = b6__8
				column-computation = make-amount
				column-computation-parameters = "DEBIT_CREDIT_PER_2,POS_CURRENCY"
				table-column-width = 5
				tid = 658512922487355
			{
				--- TableColumnItem ---
					toolTips en = Flow, fr = Flux, de = Flüsse
					item-column = OneMonth
					item-halign = trail
					item-width = 100
					previewValue = value
					tid = 658512924437044
				--- TableColumnItem ---
					toolTips en = Balance, fr = Solde, de = Saldo
					item-column = Balancer_per_2
					item-css = "blue bold italic fs12"
					item-halign = trail
					item-width = 100
					newLine = true
					previewValue = value
					tid = 658512926393997
			}
			--- TableColumn ---
				column-name = Balancer_per_2
				type = amount
				column-visibility = never-visible
				id = G9256
				column-computation = make-amount
				column-computation-parameters = "BALANCE_PER_2,POS_CURRENCY"
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = Balancer_per_2
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Three Months", de = "Drei Monate", fr = "Trois mois"
				column-name = ThreeMonths
				type = amount
				id = Y8ap6
				column-computation = make-amount
				column-computation-parameters = "DEBIT_CREDIT_PER_3,POS_CURRENCY"
				table-column-width = 5
				tid = 658512928355978
			{
				--- TableColumnItem ---
					toolTips en = Flow, fr = Flux, de = Flüsse
					item-column = ThreeMonths
					item-halign = trail
					item-width = 100
					previewValue = value
					tid = 658512930313768
				--- TableColumnItem ---
					toolTips en = Balance, fr = Solde, de = Saldo
					item-column = Balance_per_3
					item-css = "blue bold italic fs12"
					item-halign = trail
					item-width = 100
					newLine = true
					previewValue = value
					tid = 658512932265972
			}
			--- TableColumn ---
				column-name = Balance_per_3
				type = amount
				column-visibility = never-visible
				id = W0__2
				column-computation = make-amount
				column-computation-parameters = "BALANCE_PER_3,POS_CURRENCY"
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = Balance_per_3
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Six Months", de = "Sechs Monate", fr = "Six mois"
				column-name = SixMonths
				type = amount
				id = Cb79_
				column-computation = make-amount
				column-computation-parameters = "DEBIT_CREDIT_PER_4,POS_CURRENCY"
				table-column-width = 5
				tid = 658512934216499
			{
				--- TableColumnItem ---
					toolTips en = Flow, fr = Flux, de = Flüsse
					item-column = SixMonths
					item-halign = trail
					item-width = 100
					previewValue = value
					tid = 658512936156131
				--- TableColumnItem ---
					toolTips en = Balance, fr = Solde, de = Saldo
					item-column = Balance_per_4
					item-css = "blue bold italic fs12"
					item-halign = trail
					item-width = 100
					newLine = true
					previewValue = value
					tid = 658512938122582
			}
			--- TableColumn ---
				column-name = Balance_per_4
				type = amount
				column-visibility = never-visible
				id = o89_3
				column-computation = make-amount
				column-computation-parameters = "BALANCE_PER_4,POS_CURRENCY"
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = Balance_per_4
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Nine Months", de = "Neun Monate", fr = "Neuf mois"
				column-name = NineMonths
				type = amount
				id = P___s
				column-computation = make-amount
				column-computation-parameters = "DEBIT_CREDIT_PER_5,POS_CURRENCY"
				table-column-width = 5
				tid = 658512940063052
			{
				--- TableColumnItem ---
					toolTips en = Flow, fr = Flux, de = Flüsse
					item-column = NineMonths
					item-halign = trail
					item-width = 100
					previewValue = value
					tid = 658512942014418
				--- TableColumnItem ---
					toolTips en = Balance, fr = Solde, de = Saldo
					item-column = Balance_per_5
					item-css = "blue bold italic fs12"
					item-halign = trail
					item-width = 100
					newLine = true
					previewValue = value
					tid = 658512943971929
			}
			--- TableColumn ---
				column-name = Balance_per_5
				type = amount
				column-visibility = never-visible
				id = Y_uap
				column-computation = make-amount
				column-computation-parameters = "BALANCE_PER_5,POS_CURRENCY"
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = Balance_per_5
					previewValue = value
			}
			--- TableColumn ---
				labels en = "One Year", de = "Ein Jahr", fr = "Un an"
				column-name = OneYear
				type = amount
				id = P_V_7
				column-computation = make-amount
				column-computation-parameters = "DEBIT_CREDIT_PER_6,POS_CURRENCY"
				table-column-width = 5
				tid = 658512945919942
			{
				--- TableColumnItem ---
					toolTips en = Flow, fr = Flux, de = Flüsse
					item-column = OneYear
					item-halign = trail
					item-width = 100
					previewValue = value
					tid = 658512947877453
				--- TableColumnItem ---
					toolTips en = Balance, fr = Solde, de = Saldo
					item-column = Balance_per_6
					item-css = "blue bold italic fs12"
					item-halign = trail
					item-width = 100
					newLine = true
					previewValue = value
					tid = 658512949827422
			}
			--- TableColumn ---
				column-name = Balance_per_6
				type = amount
				column-visibility = never-visible
				id = f41Pj
				column-computation = make-amount
				column-computation-parameters = "BALANCE_PER_6,POS_CURRENCY"
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = Balance_per_6
					previewValue = value
			}
			--- TableColumn ---
				column-name = THIRD_PARTY_OWNERSHIP_RULE !
				column-type = domain !
				domainAttribute = THIRD_PARTY_OWNERSHIP_RULE !
				type = text
				column-visibility = not-visible
				id = THIRD_PARTY_OWNERSHIP_RULE
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = THIRD_PARTY_OWNERSHIP_RULE
					previewValue = value
			}
			--- TableColumn ---
				column-name = THIRD_PARTY_PERCT_OWNERSHIP !
				column-type = domain !
				domainAttribute = THIRD_PARTY_PERCT_OWNERSHIP !
				type = text
				column-visibility = not-visible
				id = THIRD_PARTY_PERCT_OWNERSHIP
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = THIRD_PARTY_PERCT_OWNERSHIP
					format = percentTA
					previewValue = value
			}
			--- TableExtra ---
				domainAttribute = portfolio_id
			--- TableAggregate ---
				aggregate-column-name = PORTFOLIO_CODE
				aggregate-computation = max
				aggregate-group-names = PTF_HIER_STR
			--- TableAggregate ---
				aggregate-column-name = POS_CURRENCY
				aggregate-computation = max
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = portfolio_id
				aggregate-computation = max
				aggregate-group-names = PTF_HIER_STR
			--- TableAggregate ---
				aggregate-column-name = CURR_CLASS_RANK
				aggregate-computation = max
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = CURR_CLASS_CODE
				aggregate-computation = max
				aggregate-group-names = CURR_CLASS_CODE
			--- TableExtra ---
				domainAttribute = PORTFOLIO_CODE
			--- TableAggregate ---
				aggregate-column-name = DEBIT_CREDIT_PER_0
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = DEBIT_CREDIT_PER_1
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = DEBIT_CREDIT_PER_2
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = DEBIT_CREDIT_PER_3
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = DEBIT_CREDIT_PER_4
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = DEBIT_CREDIT_PER_5
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = DEBIT_CREDIT_PER_6
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = NextWeek
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = OneMonth
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = ThreeMonths
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = SixMonths
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = NineMonths
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = OneYear
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = THIRD_COMP_RULE
				aggregate-computation = max
				aggregate-group-names = PTF_HIER_STR
			--- TableAggregate ---
				aggregate-column-name = THIRD_PARTY_OWNERSHIP_RULE
				aggregate-computation = max
				aggregate-group-names = PTF_HIER_STR
			--- TableAggregate ---
				aggregate-column-name = THIRD_PARTY_PERCT_OWNERSHIP
				aggregate-computation = max
				aggregate-group-names = PTF_HIER_STR
			--- TableAggregate ---
				aggregate-column-name = StartDate
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = PTF_HIER_STR
				aggregate-computation = max
			--- TableKeepFilter ---
				keep-filter-column-name = SERVER_FILTER
				keep-filter-operand = 1
			--- TableAggregate ---
				aggregate-column-name = DEBIT_CREDIT_CUM_PER_0
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = Balance_per_0
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = BALANCE_PER_0
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = Balance_per_1
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = BALANCE_PER_1
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = DEBIT_CREDIT_CUM_PER_2
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = Balancer_per_2
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = BALANCE_PER_2
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = DEBIT_CREDIT_CUM_PER_3
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = DEBIT_CREDIT_CUM_PER_1
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = Balance_per_3
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = BALANCE_PER_3
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = DEBIT_CREDIT_CUM_PER_4
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = Balance_per_4
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = BALANCE_PER_4
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = DEBIT_CREDIT_CUM_PER_5
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = Balance_per_5
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = BALANCE_PER_5
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = DEBIT_CREDIT_CUM_PER_6
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = Balance_per_6
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = BALANCE_PER_6
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
		}
	}
}