# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Cash Summary View", de = "Geldfluss Zusammenfassung", fr = "Vue sommaire de liquidité"
	domainEntity = "AAADSFutureCashFlow:FutureCashFlowSummaryList"
	bean-define = DSBean.AAADSFutureCashFlow.FutureCashFlowSummaryList
	bean-name = FutureCashFlowSummaryList
	id = FutureCashFlowE_ps__U
	documentation = "Using as reference the From date of the context (domain), this module displays all cumulated futur cash flows (balances) for the following periods:\r\n\r\n- today\r\n- next year\r\n- in 2 years\r\n- in 3 years\r\n- in 4 years\r\n- in 5 years\r\n- in 6 years and more"
	tid = 659919429213768
{
	--- Box ---
		boxType = vertical
	{
		--- Box ---
			boxType = vertical
		{
			--- Label ---
				labels en = "Flow per Dates", de = "Geldfluss per  Datum", fr = "Flux par dates"
				id = J32__
				tid = 659919430180372
			--- Label ---
				labels en = "Warning: Balance is not calculated when scope is reduced by context parameters (Instrument, Statuses)", fr = "Avertissement: La balance n’est pas calculée lorsque les paramètres du contexte réduisent le champ d’action (instrument, statut)", de = "Warnung: Der Saldo wird nicht berechnet, wenn der Analyse-Umfang durch Kontext-Parameter beschränkt wird (Instrument, Status)"
				tid = 90670943679080
		}
		--- TableTree ---
			table-rendering-mode = summary-delegated
			id = IyJIy
			documentation = "This table displays the cumulated futur cash flows (balances) from today, splitted in period of one year. The reference date used to define today is the From date of the context (domain)."
			table-column-count = 11 !
			table-columns-width = "9,9,9,9,9,9,9,9,9,9,9" !
		{
			--- TableColumn ---
				labels en = Portfolio, fr = Portefeuille, de = Portfolio
				column-display-grouping = true
				column-name = GROUPING
				column-type = placeholder !
				type = text
				column-locked = true
				column-sortable = false !
				column-width = 200
				column-wrapped = false
				id = t217h
				table-column-width = 9
				tid = 659919434065782
			{
				--- TableGroup ---
					group-column-name = CURR_CLASS_CODE
					group-sorting-column-name = CURR_CLASS_RANK
					group-sorting-direction = ascending
					group-rank = 4
				--- TableGroup ---
					group-column-name = PTF_HIER_STR
					group-sorting-column-name = PTF_HIER_STR
					group-sorting-direction = ascending
					hierarchy = true
					group-rank = 1
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = selectPortfolio ud
						portfolioDimPortfolio.code = "<udp:item column=\"_nodeCode\"/>" ud
						portfolioDimensionE = 1 ud
						modal = false
						only-changed = false
						prevalidate = false
						code = "<udp:item column=\"_nodeCode\"/>" ud
						Snippet FilterSet
						id = fs_5be
						level = 0
						targetDataset = "AAADSFutureCashFlow:FutureCashFlowSummaryList"
						{
							Snippet Filter
							attribute = PTF_HIER_STR
							filterValue = "<udp:item column=\"PTF_HIER_STR\"/>"
							operator = BEGINS_WITH
						}
					}
				}
			}
			--- TableColumn ---
				column-name = THIRD_COMP_RULE !
				column-type = domain !
				domainAttribute = THIRD_COMP_RULE !
				type = text
				column-visibility = not-visible
				id = THIRD_COMP_RULE
				table-column-width = 9
			{
				--- TableColumnItem ---
					item-column = THIRD_COMP_RULE
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Start Date", de = Anfangsdatum, fr = "Date de début"
				column-name = StartDate
				type = amount
				id = A_0au
				column-computation = make-amount
				column-computation-parameters = "DEBIT_CREDIT_PER_0,POS_CURRENCY"
				table-column-width = 9
				tid = 659919436044804
			{
				--- TableColumnItem ---
					toolTips en = Flow, fr = Flux, de = Flüsse
					item-column = StartDate
					item-halign = trail
					item-width = 100
					previewValue = value
					tid = 659919438002595
			}
			--- TableColumn ---
				labels en = "One Week", de = "Eine Woche", fr = "Une semaine"
				column-name = NextWeek
				type = amount
				id = b____
				column-computation = make-amount
				column-computation-parameters = "DEBIT_CREDIT_PER_1,POS_CURRENCY"
				table-column-width = 9
				tid = 659919441894989
			{
				--- TableColumnItem ---
					toolTips en = Flow, fr = Flux, de = Flüsse
					item-column = NextWeek
					item-halign = trail
					item-width = 100
					previewValue = value
					tid = 659919443838812
			}
			--- TableColumn ---
				labels en = "One Month", de = "Ein Monat", fr = "Un mois"
				column-name = OneMonth
				type = amount
				id = C__9_
				column-computation = make-amount
				column-computation-parameters = "DEBIT_CREDIT_PER_2,POS_CURRENCY"
				table-column-width = 9
				tid = 659919447755510
			{
				--- TableColumnItem ---
					toolTips en = Flow, fr = Flux, de = Flüsse
					item-column = OneMonth
					item-halign = trail
					item-width = 100
					previewValue = value
					tid = 659919449706038
			}
			--- TableColumn ---
				labels en = "Three Months", de = "Drei Monate", fr = "Trois mois"
				column-name = ThreeMonths
				type = amount
				id = F__E_
				column-computation = make-amount
				column-computation-parameters = "DEBIT_CREDIT_PER_3,POS_CURRENCY"
				table-column-width = 9
				tid = 659919453614635
			{
				--- TableColumnItem ---
					toolTips en = Flow, fr = Flux, de = Flüsse
					item-column = ThreeMonths
					item-halign = trail
					item-width = 100
					previewValue = value
					tid = 659919455570191
			}
			--- TableColumn ---
				labels en = "Six Months", de = "Sechs Monate", fr = "Six mois"
				column-name = SixMonths
				type = amount
				id = t_145
				column-computation = make-amount
				column-computation-parameters = "DEBIT_CREDIT_PER_4,POS_CURRENCY"
				table-column-width = 9
				tid = 659919459474039
			{
				--- TableColumnItem ---
					toolTips en = Flow, fr = Flux, de = Flüsse
					item-column = SixMonths
					item-halign = trail
					item-width = 100
					previewValue = value
					tid = 659919461433785
			}
			--- TableColumn ---
				labels en = "Nine Months", de = "Neun Monate", fr = "Neuf mois"
				column-name = NineMonths
				type = amount
				id = v2U_d
				column-computation = make-amount
				column-computation-parameters = "DEBIT_CREDIT_PER_5,POS_CURRENCY"
				table-column-width = 9
				tid = 659919465334560
			{
				--- TableColumnItem ---
					toolTips en = Flow, fr = Flux, de = Flüsse
					item-column = NineMonths
					item-halign = trail
					item-width = 100
					previewValue = value
					tid = 659919467286764
			}
			--- TableColumn ---
				labels en = "One Year", de = "Ein Jahr", fr = "Un an"
				column-name = OneYear
				type = amount
				id = Ho_78
				column-computation = make-amount
				column-computation-parameters = "DEBIT_CREDIT_PER_6,POS_CURRENCY"
				table-column-width = 9
				tid = 659919471175805
			{
				--- TableColumnItem ---
					toolTips en = Flow, fr = Flux, de = Flüsse
					item-column = OneYear
					item-halign = trail
					item-width = 100
					previewValue = value
					tid = 659919473130803
			}
			--- TableColumn ---
				column-name = THIRD_PARTY_OWNERSHIP_RULE !
				column-type = domain !
				domainAttribute = THIRD_PARTY_OWNERSHIP_RULE !
				type = text
				column-visibility = not-visible
				id = THIRD_PARTY_OWNERSHIP_RULE
				table-column-width = 9
			{
				--- TableColumnItem ---
					item-column = THIRD_PARTY_OWNERSHIP_RULE
					previewValue = value
			}
			--- TableColumn ---
				column-name = THIRD_PARTY_PERCT_OWNERSHIP !
				column-type = domain !
				domainAttribute = THIRD_PARTY_PERCT_OWNERSHIP !
				type = text
				column-visibility = not-visible
				id = THIRD_PARTY_PERCT_OWNERSHIP
				table-column-width = 9
			{
				--- TableColumnItem ---
					item-column = THIRD_PARTY_PERCT_OWNERSHIP
					format = percentTA
					previewValue = value
			}
			--- TableExtra ---
				domainAttribute = portfolio_id
			--- TableAggregate ---
				aggregate-column-name = PORTFOLIO_CODE
				aggregate-computation = max
				aggregate-group-names = PTF_HIER_STR
			--- TableAggregate ---
				aggregate-column-name = POS_CURRENCY
				aggregate-computation = max
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = portfolio_id
				aggregate-computation = max
				aggregate-group-names = PTF_HIER_STR
			--- TableAggregate ---
				aggregate-column-name = CURR_CLASS_RANK
				aggregate-computation = max
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = CURR_CLASS_CODE
				aggregate-computation = max
				aggregate-group-names = CURR_CLASS_CODE
			--- TableExtra ---
				domainAttribute = PORTFOLIO_CODE
			--- TableAggregate ---
				aggregate-column-name = DEBIT_CREDIT_PER_0
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = DEBIT_CREDIT_PER_1
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = DEBIT_CREDIT_PER_2
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = DEBIT_CREDIT_PER_3
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = DEBIT_CREDIT_PER_4
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = DEBIT_CREDIT_PER_5
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = DEBIT_CREDIT_PER_6
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = NextWeek
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = OneMonth
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = ThreeMonths
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = SixMonths
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = NineMonths
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = OneYear
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = THIRD_COMP_RULE
				aggregate-computation = max
				aggregate-group-names = PTF_HIER_STR
			--- TableAggregate ---
				aggregate-column-name = THIRD_PARTY_OWNERSHIP_RULE
				aggregate-computation = max
				aggregate-group-names = PTF_HIER_STR
			--- TableAggregate ---
				aggregate-column-name = THIRD_PARTY_PERCT_OWNERSHIP
				aggregate-computation = max
				aggregate-group-names = PTF_HIER_STR
			--- TableAggregate ---
				aggregate-column-name = StartDate
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = PTF_HIER_STR
				aggregate-computation = max
			--- TableKeepFilter ---
				keep-filter-column-name = SERVER_FILTER
				keep-filter-operand = 1
			--- TableAggregate ---
				aggregate-column-name = DEBIT_CREDIT_CUM_PER_0
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = BALANCE_PER_0
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = BALANCE_PER_1
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = DEBIT_CREDIT_CUM_PER_2
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = BALANCE_PER_2
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = DEBIT_CREDIT_CUM_PER_3
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = DEBIT_CREDIT_CUM_PER_1
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = BALANCE_PER_3
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = DEBIT_CREDIT_CUM_PER_4
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = BALANCE_PER_4
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = DEBIT_CREDIT_CUM_PER_5
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = BALANCE_PER_5
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = DEBIT_CREDIT_CUM_PER_6
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = BALANCE_PER_6
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
		}
	}
}