# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Cash Summary View", de = "Geldfluss Zusammenfassung", fr = "Vue sommaire de liquidité"
	domainEntity = "AAADSFutureCashFlow:FutureCashFlowSummaryList"
	bean-define = DSBean.AAADSFutureCashFlow.FutureCashFlowSummaryList
	bean-name = FutureCashFlowSummaryList
	id = FutureCashFlowNoEvent_NFT5_
	documentation = "Using as reference the From date of the context (domain), this module displays all cumulated futur cash flows (balances) for the following periods:\r\n\r\n- today\r\n- next year\r\n- in 2 years\r\n- in 3 years\r\n- in 4 years\r\n- in 5 years\r\n- in 6 years and more"
	tid = 658187654075867
{
	--- Box ---
		boxType = vertical
	{
		--- Box ---
			boxType = vertical
		{
			--- Label ---
				labels en = "Flow per Dates", de = "Geldfluss per  Datum", fr = "Flux par dates"
				id = GH_9_
				tid = 658187654993581
			--- Label ---
				labels en = "Warning: Balance is not calculated when scope is reduced by context parameters (Instrument, Statuses)", fr = "Avertissement: La balance n’est pas calculée lorsque les paramètres du contexte réduisent le champ d’action (instrument, statut)", de = "Warnung: Der Saldo wird nicht berechnet, wenn der Analyse-Umfang durch Kontext-Parameter beschränkt wird (Instrument, Status)"
				verticalTextPosition = lead
				tid = 91830061353841
		}
		--- TableTree ---
			table-rendering-mode = summary-delegated
			id = g_z3U
			documentation = "This table displays the cumulated futur cash flows (balances) from today, splitted in period of one year. The reference date used to define today is the From date of the context (domain)."
			table-column-count = 11 !
			table-columns-width = "9,9,9,9,9,9,9,9,9,9,9" !
		{
			--- TableColumn ---
				labels en = Portfolio, fr = Portefeuille, de = Portfolio
				column-display-grouping = true
				column-name = GROUPING
				column-type = placeholder !
				type = text
				column-locked = true
				column-sortable = false !
				column-width = 200
				column-wrapped = false
				id = gF_X_
				table-column-width = 9
				tid = 658187656905277
			{
				--- TableGroup ---
					group-column-name = CURR_CLASS_CODE
					group-sorting-column-name = CURR_CLASS_RANK
					group-sorting-direction = ascending
					group-rank = 4
				--- TableGroup ---
					group-column-name = PTF_HIER_STR
					group-sorting-column-name = PTF_HIER_STR
					group-sorting-direction = ascending
					hierarchy = true
					group-rank = 1
			}
			--- TableColumn ---
				column-name = THIRD_COMP_RULE !
				column-type = domain !
				domainAttribute = THIRD_COMP_RULE !
				type = text
				column-visibility = not-visible
				id = THIRD_COMP_RULE
				table-column-width = 9
			{
				--- TableColumnItem ---
					item-column = THIRD_COMP_RULE
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Start Date", de = Anfangsdatum, fr = "Date de début"
				column-name = StartDate
				type = amount
				id = N6r__
				column-computation = make-amount
				column-computation-parameters = "DEBIT_CREDIT_PER_0,POS_CURRENCY"
				table-column-width = 9
				tid = 658187658844909
			{
				--- TableColumnItem ---
					toolTips en = Flow, fr = Flux, de = Flüsse
					item-column = StartDate
					item-halign = trail
					item-width = 100
					previewValue = value
					tid = 658187660813874
			}
			--- TableColumn ---
				labels en = "One Week", de = "Eine Woche", fr = "Une semaine"
				column-name = NextWeek
				type = amount
				id = b_Mx_
				column-computation = make-amount
				column-computation-parameters = "DEBIT_CREDIT_PER_1,POS_CURRENCY"
				table-column-width = 9
				tid = 658187662765798
			{
				--- TableColumnItem ---
					toolTips en = Flow, fr = Flux, de = Flüsse
					item-column = NextWeek
					item-halign = trail
					item-width = 100
					previewValue = value
					tid = 658187664711297
			}
			--- TableColumn ---
				labels en = "One Month", de = "Ein Monat", fr = "Un mois"
				column-name = OneMonth
				type = amount
				id = o276_
				column-computation = make-amount
				column-computation-parameters = "DEBIT_CREDIT_PER_2,POS_CURRENCY"
				table-column-width = 9
				tid = 658187666674954
			{
				--- TableColumnItem ---
					toolTips en = Flow, fr = Flux, de = Flüsse
					item-column = OneMonth
					item-halign = trail
					item-width = 100
					previewValue = value
					tid = 658187668639450
			}
			--- TableColumn ---
				labels en = "Three Months", de = "Drei Monate", fr = "Trois mois"
				column-name = ThreeMonths
				type = amount
				id = e__x5
				column-computation = make-amount
				column-computation-parameters = "DEBIT_CREDIT_PER_3,POS_CURRENCY"
				table-column-width = 9
				tid = 658187670612047
			{
				--- TableColumnItem ---
					toolTips en = Flow, fr = Flux, de = Flüsse
					item-column = ThreeMonths
					item-halign = trail
					item-width = 100
					previewValue = value
					tid = 658187672516199
			}
			--- TableColumn ---
				labels en = "Six Months", de = "Sechs Monate", fr = "Six mois"
				column-name = SixMonths
				type = amount
				id = JU2__
				column-computation = make-amount
				column-computation-parameters = "DEBIT_CREDIT_PER_4,POS_CURRENCY"
				table-column-width = 9
				tid = 658187674485165
			{
				--- TableColumnItem ---
					toolTips en = Flow, fr = Flux, de = Flüsse
					item-column = SixMonths
					item-halign = trail
					item-width = 100
					previewValue = value
					tid = 658187676444631
			}
			--- TableColumn ---
				labels en = "Nine Months", de = "Neun Monate", fr = "Neuf mois"
				column-name = NineMonths
				type = amount
				id = H662_
				column-computation = make-amount
				column-computation-parameters = "DEBIT_CREDIT_PER_5,POS_CURRENCY"
				table-column-width = 9
				tid = 658187678392086
			{
				--- TableColumnItem ---
					toolTips en = Flow, fr = Flux, de = Flüsse
					item-column = NineMonths
					item-halign = trail
					item-width = 100
					previewValue = value
					tid = 658187680325851
			}
			--- TableColumn ---
				labels en = "One Year", de = "Ein Jahr", fr = "Un an"
				column-name = OneYear
				type = amount
				id = d1C2U
				column-computation = make-amount
				column-computation-parameters = "DEBIT_CREDIT_PER_6,POS_CURRENCY"
				table-column-width = 9
				tid = 658187682298169
			{
				--- TableColumnItem ---
					toolTips en = Flow, fr = Flux, de = Flüsse
					item-column = OneYear
					item-halign = trail
					item-width = 100
					previewValue = value
					tid = 658187684252328
			}
			--- TableColumn ---
				column-name = THIRD_PARTY_OWNERSHIP_RULE !
				column-type = domain !
				domainAttribute = THIRD_PARTY_OWNERSHIP_RULE !
				type = text
				column-visibility = not-visible
				id = THIRD_PARTY_OWNERSHIP_RULE
				table-column-width = 9
			{
				--- TableColumnItem ---
					item-column = THIRD_PARTY_OWNERSHIP_RULE
					previewValue = value
			}
			--- TableColumn ---
				column-name = THIRD_PARTY_PERCT_OWNERSHIP !
				column-type = domain !
				domainAttribute = THIRD_PARTY_PERCT_OWNERSHIP !
				type = text
				column-visibility = not-visible
				id = THIRD_PARTY_PERCT_OWNERSHIP
				table-column-width = 9
			{
				--- TableColumnItem ---
					item-column = THIRD_PARTY_PERCT_OWNERSHIP
					format = percentTA
					previewValue = value
			}
			--- TableExtra ---
				domainAttribute = portfolio_id
			--- TableAggregate ---
				aggregate-column-name = PORTFOLIO_CODE
				aggregate-computation = max
				aggregate-group-names = PTF_HIER_STR
			--- TableAggregate ---
				aggregate-column-name = POS_CURRENCY
				aggregate-computation = max
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = portfolio_id
				aggregate-computation = max
				aggregate-group-names = PTF_HIER_STR
			--- TableAggregate ---
				aggregate-column-name = CURR_CLASS_RANK
				aggregate-computation = max
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = CURR_CLASS_CODE
				aggregate-computation = max
				aggregate-group-names = CURR_CLASS_CODE
			--- TableExtra ---
				domainAttribute = PORTFOLIO_CODE
			--- TableAggregate ---
				aggregate-column-name = DEBIT_CREDIT_PER_0
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = DEBIT_CREDIT_PER_1
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = DEBIT_CREDIT_PER_2
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = DEBIT_CREDIT_PER_3
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = DEBIT_CREDIT_PER_4
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = DEBIT_CREDIT_PER_5
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = DEBIT_CREDIT_PER_6
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = NextWeek
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = OneMonth
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = ThreeMonths
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = SixMonths
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = NineMonths
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = OneYear
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = THIRD_COMP_RULE
				aggregate-computation = max
				aggregate-group-names = PTF_HIER_STR
			--- TableAggregate ---
				aggregate-column-name = THIRD_PARTY_OWNERSHIP_RULE
				aggregate-computation = max
				aggregate-group-names = PTF_HIER_STR
			--- TableAggregate ---
				aggregate-column-name = THIRD_PARTY_PERCT_OWNERSHIP
				aggregate-computation = max
				aggregate-group-names = PTF_HIER_STR
			--- TableAggregate ---
				aggregate-column-name = StartDate
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = PTF_HIER_STR
				aggregate-computation = max
			--- TableKeepFilter ---
				keep-filter-column-name = SERVER_FILTER
				keep-filter-operand = 1
			--- TableAggregate ---
				aggregate-column-name = DEBIT_CREDIT_CUM_PER_0
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = BALANCE_PER_0
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = BALANCE_PER_1
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = DEBIT_CREDIT_CUM_PER_2
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = BALANCE_PER_2
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = DEBIT_CREDIT_CUM_PER_3
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = DEBIT_CREDIT_CUM_PER_1
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = BALANCE_PER_3
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = DEBIT_CREDIT_CUM_PER_4
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = BALANCE_PER_4
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = DEBIT_CREDIT_CUM_PER_5
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = BALANCE_PER_5
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = DEBIT_CREDIT_CUM_PER_6
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
			--- TableAggregate ---
				aggregate-column-name = BALANCE_PER_6
				aggregate-computation = sum
				aggregate-group-names = CURR_CLASS_CODE
		}
	}
}