# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Rule List", fr = "Liste des règles", de = "Liste der Regeln"
	domainEntity = "AAADSApplRule:ApplRuleList"
	bean-define = DSBean.AAADSApplRule.ApplRuleList
	bean-name = ApplRuleList
	id = ApplRuleList_K3u_5
	tid = 27321784879642
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			id = n0NC7
			table-column-count = 3 !
			table-columns-width = "33,33,33" !
		{
			--- TableColumn ---
				column-name = dictEntityName !
				column-type = domain !
				domainAttribute = dictEntityName !
				id = dictEntityName
				table-column-width = 33
			{
				--- TableColumnItem ---
					item-column = dictEntityName
					previewValue = value
			}
			--- TableColumn ---
				column-name = code !
				column-type = domain !
				domainAttribute = code !
				id = code
				table-column-width = 33
			{
				--- TableColumnItem ---
					item-column = code
					previewValue = value
			}
			--- TableColumn ---
				column-name = denom !
				column-type = domain !
				domainAttribute = denom !
				id = denom
				table-column-width = 33
			{
				--- TableColumnItem ---
					item-column = denom
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = dictEntityName
				sort-rank = 1
			--- TableSort ---
				sort-column-name = code
				sort-rank = 2
		}
	}
}