# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSDictEntitiy:DictEntityList"
	bean-define = DSBean.AAADSDictEntitiy.DictEntityList
	bean-name = DictEntityList
	id = DictEntityList_o__5c
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			id = Dl_5_
			table-column-count = 1 !
			table-columns-width = 100 !
		{
			--- TableColumn ---
				column-name = name !
				column-type = domain !
				domainAttribute = name !
				id = name
				table-column-width = 100
			{
				--- TableColumnItem ---
					item-column = name
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = name
				sort-rank = 1
		}
	}
}