# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSExchangeEvent:ExchangeEventList"
	cssClass = nodeco
	bean-define = DSBean.AAADSExchangeEvent.ExchangeEventList
	bean-name = ExchangeEventList
	id = ExchangeEventList_Lc_dr
{
	--- Box ---
		labels en = "Exchange Events", de = Austausch, fr = "Evénement sur le bourse"
		boxType = vertical
		widgetBorder = box
		width = 0
		tid = 715832808334020
	{
		--- TableTree ---
			table-filter-layer = true
			id = e0JlD
			table-model-reference = DSTableModel.AAADSExchangeEvent.ExchangeEventList
			table-column-count = 17 !
			table-columns-width = "5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5" !
		{
			--- TableColumn ---
				column-name = validityD !
				column-type = domain !
				domainAttribute = validityD !
				column-locked = true
				id = validityD
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = validityD
					format = date
					previewValue = value
			}
			--- TableColumn ---
				column-name = beginD !
				column-type = domain !
				domainAttribute = beginD !
				id = beginD
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = beginD
					format = date
					previewValue = value
			}
			--- TableColumn ---
				column-name = natureE !
				column-type = domain !
				domainAttribute = natureE !
				id = natureE
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = natureE
					previewValue = value
			}
			--- TableColumn ---
				column-name = code !
				column-type = domain !
				domainAttribute = code !
				type = text
				id = code
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = code
					previewValue = value
			}
			--- TableColumn ---
				column-name = endValidityD !
				column-type = domain !
				domainAttribute = endValidityD !
				type = text
				id = endValidityD
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = endValidityD
					format = date
					previewValue = value
			}
			--- TableColumn ---
				column-name = endD !
				column-type = domain !
				domainAttribute = endD !
				type = text
				id = endD
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = endD
					format = date
					previewValue = value
			}
			--- TableColumn ---
				column-name = newInstrCode !
				column-type = domain !
				domainAttribute = newInstrCode !
				type = text
				id = newInstrCode
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = newInstrCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = currencyCode !
				column-type = domain !
				domainAttribute = currencyCode !
				type = text
				id = currencyCode
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = currencyCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = refQtyN !
				column-type = domain !
				domainAttribute = refQtyN !
				type = text
				id = refQtyN
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = refQtyN
					format = decimal.detailed
					previewValue = value
			}
			--- TableColumn ---
				column-name = newInstrQtyN !
				column-type = domain !
				domainAttribute = newInstrQtyN !
				type = text
				id = newInstrQtyN
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = newInstrQtyN
					format = decimal.detailed
					previewValue = value
			}
			--- TableColumn ---
				column-name = instrPhysicalF !
				column-type = domain !
				domainAttribute = instrPhysicalF !
				type = text
				id = instrPhysicalF
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = instrPhysicalF
					previewValue = value
			}
			--- TableColumn ---
				column-name = quoteN !
				column-type = domain !
				domainAttribute = quoteN !
				type = text
				id = quoteN
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = quoteN
					format = decimal.detailed
					previewValue = value
			}
			--- TableColumn ---
				column-name = settleDaysN !
				column-type = domain !
				domainAttribute = settleDaysN !
				type = text
				column-visibility = not-visible
				id = settleDaysN
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = settleDaysN
					format = integer
					previewValue = value
			}
			--- TableColumn ---
				column-name = roundRuleE !
				column-type = domain !
				domainAttribute = roundRuleE !
				type = text
				column-visibility = not-visible
				id = roundRuleE
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = roundRuleE
					previewValue = value
			}
			--- TableColumn ---
				column-name = oddLotCompE !
				column-type = domain !
				domainAttribute = oddLotCompE !
				type = text
				column-visibility = not-visible
				id = oddLotCompE
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = oddLotCompE
					previewValue = value
			}
			--- TableColumn ---
				column-name = roundLevelE !
				column-type = domain !
				domainAttribute = roundLevelE !
				type = text
				column-visibility = not-visible
				id = roundLevelE
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = roundLevelE
					previewValue = value
			}
			--- TableColumn ---
				column-name = fixedExchRate !
				column-type = domain !
				domainAttribute = fixedExchRate !
				type = text
				column-visibility = not-visible
				id = fixedExchRate
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = fixedExchRate
					format = decimal.detailed
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = beginD
				sort-direction = descending
				sort-rank = 5
			--- TableSort ---
				sort-column-name = validityD
				sort-direction = descending
				sort-rank = 1
			--- TableSort ---
				sort-column-name = natureE
				sort-direction = descending
				sort-rank = 7
			--- TableSort ---
				sort-column-name = endD
				sort-direction = descending
				sort-rank = 6
			--- TableSort ---
				sort-column-name = endValidityD
				sort-direction = descending
				sort-rank = 2
			--- TableSort ---
				sort-column-name = newInstrId
				sort-direction = descending
				sort-rank = 8
		}
	}
}