<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="transformmodel"
    nsURI="http://www.odcgroup.com/page/transformmodel" nsPrefix="com.odcgroup.page.transformmodel">
  <eClassifiers xsi:type="ecore:EClass" name="TransformModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="namespaces" upperBound="-1"
        eType="#//Namespace" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="widgetTransformers" upperBound="-1"
        eType="#//AbstractWidgetTransformer" containment="true" eOpposite="#//AbstractWidgetTransformer/model"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultNamespace" eType="#//Namespace"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertyTransformers" upperBound="-1"
        eType="#//AbstractPropertyTransformer" containment="true" eOpposite="#//AbstractPropertyTransformer/model"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultWidgetLibrary" eType="ecore:EClass ../../page-metamodel/model/PageMetaModel.ecore#//WidgetLibrary"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventTransformations" eType="#//EventTransformations"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Namespace">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prefix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="origin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="metaModel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractWidgetTransformer" abstract="true"
      eSuperTypes="#//WidgetTransformer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" eType="#//TransformModel"
        eOpposite="#//TransformModel/widgetTransformers"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleWidgetTransformer" abstract="true"
      eSuperTypes="#//AbstractWidgetTransformer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="widgetType" eType="ecore:EClass ../../page-metamodel/model/PageMetaModel.ecore#//WidgetType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="namespace" eType="#//Namespace"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElementNameWidgetTransformer" eSuperTypes="#//SimpleWidgetTransformer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractPropertyTransformer" abstract="true"
      eSuperTypes="#//PropertyTransformer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" eType="#//TransformModel"
        eOpposite="#//TransformModel/propertyTransformers"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimplePropertyTransformer" abstract="true"
      eSuperTypes="#//AbstractPropertyTransformer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertyType" eType="ecore:EClass ../../page-metamodel/model/PageMetaModel.ecore#//PropertyType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeNamePropertyTransformer" eSuperTypes="#//SimplePropertyTransformer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attributeName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElementPropertyTransformer" eSuperTypes="#//SimplePropertyTransformer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="namespace" eType="#//Namespace"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExtraParentWidgetTransformer" eSuperTypes="#//ElementNameWidgetTransformer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parentElementName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="onlyAddIfRoot" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentNamespace" eType="#//Namespace"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WidgetTransformer" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyTransformer" abstract="true"
      interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="GenericPropertyTransformer" eSuperTypes="#//SimplePropertyTransformer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="implementationClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenericWidgetTransformer" eSuperTypes="#//SimpleWidgetTransformer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="implementationClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NullWidgetTransformer" eSuperTypes="#//SimpleWidgetTransformer"/>
  <eClassifiers xsi:type="ecore:EClass" name="NullPropertyTransformer" eSuperTypes="#//SimplePropertyTransformer"/>
  <eClassifiers xsi:type="ecore:EClass" name="EventTransformations">
    <eStructuralFeatures xsi:type="ecore:EReference" name="transformations" upperBound="-1"
        eType="#//EventTransformation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventTransformation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventType" eType="ecore:EClass ../../page-metamodel/model/PageMetaModel.ecore#//EventType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChildrenWidgetTransformer" eSuperTypes="#//SimpleWidgetTransformer"/>
  <eClassifiers xsi:type="ecore:EClass" name="SnippetTransformation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="snippetType" eType="ecore:EClass ../../page-metamodel/model/PageMetaModel.ecore#//SnippetType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SnippetTransformations">
    <eStructuralFeatures xsi:type="ecore:EReference" name="transformations" upperBound="-1"
        eType="#//SnippetTransformation" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
