# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels fr = Contexte, en = Context, de = Kontext
	containment = container
	domainEntity = "AAADSDomain:DomainContext"
	collapsible = true
	cssClass = nodeco
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = Context_EW_f_
	documentation = "Domain Context"
	tid = 6230607011198
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- Conditional ---
			indexOfSelectedChild = 0
		{
			--- ConditionalBody ---
				javaCode = "null!=<bean:get-property bean=\"DomainContext\" property=\"simulationF\"/>\r\n&amp;&amp;\r\nBoolean.toString(com.odcgroup.aaa.DomainAAASimulationF.Yes).equals(<bean:get-property bean=\"DomainContext\" property=\"simulationF\"/>.toString())"
				technicalName = Simulation
				boxType = vertical
				isWidgetSelected = true
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/valuation/context/SimulationContextNotEditedHead.module
			}
			--- ConditionalBody ---
				javaCode = true
				technicalName = Default
				boxType = vertical
				isWidgetVisible = false
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/valuation/context/ContextNotEditedHead.module
			}
		}
		--- Conditional ---
			indexOfSelectedChild = 1
		{
			--- ConditionalBody ---
				javaCode = "Integer.toString(com.odcgroup.aaa.DomainAAAPortfolioDimensionE.Portfolio).equals(<bean:get-property bean=\"DomainContext\" property=\"portfolioDimensionE\"/>.toString())"
				technicalName = Portfolio
				boxType = vertical
				isWidgetVisible = false
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/identification/identification/PortfolioBanner.module
			}
			--- ConditionalBody ---
				javaCode = "Integer.toString(com.odcgroup.aaa.DomainAAAPortfolioDimensionE.PortfolioThirdParty).equals(<bean:get-property bean=\"DomainContext\" property=\"portfolioDimensionE\"/>.toString())"
				technicalName = Client
				boxType = vertical
				isWidgetSelected = true
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/identification/identification/ClientBanner.module
			}
			--- ConditionalBody ---
				javaCode = true
				technicalName = Default
				boxType = vertical
				isWidgetVisible = false
		}
	}
}