# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels fr = Contexte, en = Context, de = Kontext
	domainEntity = "AAADSDomain:DomainContext"
	collapsible = true
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = Context_EW_f_
	documentation = "Domain Context"
	tid = 6230607118499
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TabbedPane ---
			id = U_60C
			indexOfSelectedChild = 0
		{
			--- Tab ---
				labels fr = Base, en = Basic, de = Einfach
				id = tab_N0E_N
				isWidgetSelected = true
				tid = 6230606539821
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 6
					gridColumnsWidth = "27,16,13,16,14,14" !
					gridRowCount = 1
					verticalAlignment = lead
				{
					--- GridCell ---
						gridColumnWidth = 27
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainPortfolioDimension.fragment
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainInstrumentDimension.fragment
					}
					--- GridCell ---
						gridColumnWidth = 13
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainPivotDate.fragment
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainRefCurrency.fragment
					}
					--- GridCell ---
						gridColumnWidth = 14
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainHierarchyIdentifier.fragment
					}
					--- GridCell ---
						gridColumnWidth = 14
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainConsolidationIdentifier.fragment
					}
				}
			}
			--- Tab ---
				labels fr = Avancé, en = Advanced, de = Erweitert
				id = tab_N9D21
				isWidgetVisible = false
				tid = 6230608873899
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 7
					gridColumnsWidth = "14,14,14,14,14,14,14" !
					gridRowCount = 1
				{
					--- GridCell ---
						gridColumnWidth = 14
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainMinStatus.fragment
					}
					--- GridCell ---
						gridColumnWidth = 14
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainMaxStatus.fragment
					}
					--- GridCell ---
						gridColumnWidth = 14
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainZeroQtyF.fragment
					}
					--- GridCell ---
						gridColumnWidth = 14
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainStatusFus.fragment
					}
					--- GridCell ---
						gridColumnWidth = 14
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainPosLogicalE.fragment
					}
					--- GridCell ---
						gridColumnWidth = 14
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainClosePosF.fragment
					}
					--- GridCell ---
						gridColumnWidth = 14
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainFundSplit.fragment
					}
				}
			}
		}
		--- Grid ---
			cssClass = blank
			gridColumnCount = 4
			gridColumnsWidth = "25,25,25,25" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Button ---
					labels en = Execute, de = Ausführen, fr = Exécuter
					id = btn_execute_in_domaincontext
					tid = 6230607934201
				{
					Event OnClick (submit)
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						widget-group-ref = form
						param = "flow-action=execute"
						only-changed = true
						prevalidate = false
						modal = false
					}
				}
				--- Button ---
					labels en = Refresh, de = Aktualisieren, fr = Actualiser
					id = btn_refresh_in_domaincontext
					tid = 6230608487504
				{
					Event OnClick (submit)
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						widget-group-ref = form
						param = "flow-action=execute,DSAction=refresh"
						only-changed = true
						prevalidate = false
						modal = false
					}
				}
				--- Button ---
					labels en = "Default Settings", de = Standardeinstellung, fr = "Valeurs par défaut"
					id = btn_t9_E_
					tid = 474061737839306
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = reset ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
		}
	}
}