# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Instrument Details", fr = "Détails de l\'instrument", de = "Details des Instruments"
	domainEntity = "AAADSDomain:DomainContext"
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = InstrumentDetail_T_gRm
	tid = 6229753975936
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TabbedPane ---
			id = EF108
			indexOfSelectedChild = 0
		{
			--- Tab ---
				labels en = Basic, fr = Base, de = Einfach
				id = tab_Y_A_1
				isWidgetSelected = true
				tid = 100408134639408
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 6
					gridColumnsWidth = "20,20,8,8,8,8" !
					gridRowCount = 1
					verticalAlignment = lead
				{
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainPortfolioDimensionView.fragment
					}
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainInstrumentCodeView.fragment
					}
					--- GridCell ---
						gridColumnWidth = 8
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainReferenceDateView.fragment
					}
					--- GridCell ---
						gridColumnWidth = 8
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainRefCurrencyView.fragment
					}
					--- GridCell ---
						gridColumnWidth = 8
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainHierarchyIdentifierView.fragment
					}
					--- GridCell ---
						gridColumnWidth = 8
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainConsolidationIdentifierView.fragment
					}
				}
			}
			--- Tab ---
				labels en = Advanced, fr = Avancée, de = Erweitert
				id = tab_y965g
				isWidgetVisible = false
				tid = 100408136585050
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 7
					gridColumnsWidth = "14,14,14,14,14,14,14" !
					gridRowCount = 1
				{
					--- GridCell ---
						gridColumnWidth = 14
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainMinStatusView.fragment
					}
					--- GridCell ---
						gridColumnWidth = 14
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainMaxStatusView.fragment
					}
					--- GridCell ---
						gridColumnWidth = 14
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainZeroQtyFView.fragment
					}
					--- GridCell ---
						gridColumnWidth = 14
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainStatusFusView.fragment
					}
					--- GridCell ---
						gridColumnWidth = 14
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainPosLogicalEView.fragment
					}
					--- GridCell ---
						gridColumnWidth = 14
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainClosePosFView.fragment
					}
					--- GridCell ---
						gridColumnWidth = 14
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainFundSplitView.fragment
					}
				}
			}
		}
		--- Grid ---
			cssClass = blank
			gridColumnCount = 4
			gridColumnsWidth = "25,25,25,25" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Button ---
					labels en = "Back to Summary", fr = "Retour au résumé", de = "Zurück zur Ansicht"
					id = btn_y0kG4
					tid = 6229753615525
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = back ud
						modal = false
						only-changed = false
						prevalidate = false
						Query.fs_1.TargetDS = "AAADSValuation:ValuationSummaryList" ud
						Query.fs_1.cancel = true ud
						Query.fs_1.level = 0 ud
						Query.fs_2.TargetDS = "AAADSValuation:ValuationDetailledList" ud
						Query.fs_2.cancel = true ud
						Query.fs_2.level = 0 ud
					}
				}
			}
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
		}
	}
}