# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Portfolio Details", fr = "Détails du portefeuille", de = "Details des Portfolios"
	domainEntity = "AAADSDomain:DomainContext"
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = PortfolioCodeDetailCHead_k_m_0
	tid = 9046665364997
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			id = W6lBo
			indexOfSelectedChild = 0
		{
			--- Tab ---
				labels en = Basic, fr = Base, de = Einfach
				id = tab_PvQ97
				isWidgetSelected = true
				tid = 173371651333195
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 6
					gridColumnsWidth = "20,20,8,8,8,8" !
					gridRowCount = 1
					verticalAlignment = lead
				{
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainPortfolioCodeView.fragment
					}
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainInstrumentDimensionView.fragment
					}
					--- GridCell ---
						gridColumnWidth = 8
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainReferenceDateView.fragment
					}
					--- GridCell ---
						gridColumnWidth = 8
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainRefCurrencyView.fragment
					}
					--- GridCell ---
						gridColumnWidth = 8
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainHierarchyIdentifierView.fragment
					}
					--- GridCell ---
						gridColumnWidth = 8
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainConsolidationIdentifierView.fragment
					}
				}
			}
			--- Tab ---
				labels en = Advanced, fr = Avancée, de = Erweitert
				id = tab_pR_G_
				isWidgetVisible = false
				tid = 173425472665311
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 7
					gridColumnsWidth = "14,14,14,14,14,14,14" !
					gridRowCount = 1
				{
					--- GridCell ---
						gridColumnWidth = 14
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainMinStatusView.fragment
					}
					--- GridCell ---
						gridColumnWidth = 14
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainMaxStatusView.fragment
					}
					--- GridCell ---
						gridColumnWidth = 14
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainZeroQtyFView.fragment
					}
					--- GridCell ---
						gridColumnWidth = 14
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainStatusFusView.fragment
					}
					--- GridCell ---
						gridColumnWidth = 14
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainPosLogicalEView.fragment
					}
					--- GridCell ---
						gridColumnWidth = 14
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainClosePosFView.fragment
					}
					--- GridCell ---
						gridColumnWidth = 14
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainFundSplitView.fragment
					}
				}
			}
		}
	}
}