# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Simulation Context", de = Simulationskontext, fr = "Simulation du contexte"
	domainEntity = "AAADSDomain:DomainContext"
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = SimulationContextNotEditedHead_z__N6
	tid = 6633370414283
{
	--- Box ---
		boxType = vertical
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 5
			gridColumnsWidth = "20,20,20,20,20" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 20
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainPortfolioCodeView.fragment
			}
			--- GridCell ---
				gridColumnWidth = 20
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainPivotDateView.fragment
			}
			--- GridCell ---
				gridColumnWidth = 20
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainRefCurrencyNotEdited.fragment
			}
			--- GridCell ---
				gridColumnWidth = 20
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainFundSplitNotEdited.fragment
			}
			--- GridCell ---
				gridColumnWidth = 20
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainProposalSessionOrdersNotEdited.fragment
			}
		}
		--- Grid ---
			cssClass = blank
			gridColumnCount = 4
			gridColumnsWidth = "25,25,25,25" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Button ---
					labels en = Refresh, de = Aktualisieren, fr = Actualiser
					id = btn_N_U_d
					tid = 6814837711334
				{
					Event OnClick (submit)
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						widget-group-ref = form
						param = "flow-action=executeSimulation,DSAction=refresh"
						only-changed = true
						prevalidate = false
						modal = false
					}
				}
				--- Button ---
					labels en = "Default Settings", de = Standardeinstellung, fr = "Valeurs par défaut"
					id = btn_a4d2c
					tid = 6822507601353
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = reset ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
				--- Button ---
					labels en = Back, de = Zurück, fr = Retour
					id = btn_yqpTA
					tid = 6826539636406
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = back ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
		}
	}
}