# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Simulation Context", de = Simulationskontext, fr = "Simulation du contexte"
	domainEntity = "AAADSDomain:DomainContext"
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = SimulationContext_aR516
	tid = 8065628079688
{
	--- Box ---
		boxType = vertical
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 5
			gridColumnsWidth = "20,20,20,20,20" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 20
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainPortfolioCodeView.fragment
			}
			--- GridCell ---
				gridColumnWidth = 20
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainPivotDateView.fragment
			}
			--- GridCell ---
				gridColumnWidth = 20
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainRefCurrency.fragment
			}
			--- GridCell ---
				gridColumnWidth = 20
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainFundSplit.fragment
			}
			--- GridCell ---
				gridColumnWidth = 20
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainProposalSessionOrders.fragment
			}
		}
		--- Grid ---
			cssClass = blank
			gridColumnCount = 4
			gridColumnsWidth = "25,25,25,25" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Button ---
					labels en = Execute, de = Ausführen, fr = Exécuter
					id = btn_Y_KND
					tid = 8109000059881
				{
					Event OnClick (submit)
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						widget-group-ref = form
						param = "flow-action=executeSimulation"
						only-changed = true
						prevalidate = false
						modal = false
					}
				}
				--- Button ---
					labels en = Refresh, de = Aktualisieren, fr = Actualiser
					id = btn_f__cb
					tid = 8111767495644
				{
					Event OnClick (submit)
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						widget-group-ref = form
						param = "flow-action=executeSimulation,DSAction=refresh"
						only-changed = true
						prevalidate = false
						modal = false
					}
				}
				--- Button ---
					labels en = "Default Settings", de = Standardeinstellung, fr = "Valeurs par défaut"
					id = btn_T4_a_
					tid = 8114410350312
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = reset ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
				--- Button ---
					labels en = Back, de = Zurück, fr = Retour
					id = btn_I5J1_
					tid = 8117709565134
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = back ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
		}
	}
}