# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	containment = container
	domainEntity = "AAADSDomain:DomainContext"
	cssClass = nodeco
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = ValuationContext_KX__6
{
	--- Box ---
		boxType = vertical
	{
		--- Conditional ---
			indexOfSelectedChild = 0
		{
			--- ConditionalBody ---
				javaCode = "null!=<bean:get-property bean=\"DomainContext\" property=\"simulationF\"/>\r\n&amp;&amp;\r\nBoolean.toString(com.odcgroup.aaa.DomainAAASimulationF.Yes).equals(<bean:get-property bean=\"DomainContext\" property=\"simulationF\"/>.toString())"
				technicalName = Simulation
				boxType = vertical
				isWidgetSelected = true
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/valuation/context/SimulationContext.module
			}
			--- ConditionalBody ---
				javaCode = true
				technicalName = Default
				boxType = vertical
				isWidgetVisible = false
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/valuation/context/Context.module
			}
		}
	}
}