# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels fr = "Liste des secteurs", de = "Liste der Branchenzuordnung"
	domainEntity = "AAADSSectorAttrib:SectorAttribList"
	cssClass = nodeco
	bean-define = DSBean.AAADSSectorAttrib.SectorAttribList
	bean-name = SectorAttribList
	id = SectorAttribList_H_OV_
	tid = 19654472917088
{
	--- Box ---
		labels en = "Sector Attribution", de = Branchen-Zuordnung, fr = "Attribution de secteur"
		boxType = vertical
		widgetBorder = box
		width = 0
		tid = 713136551822368
	{
		--- TableTree ---
			table-filter-layer = true
			id = Ob_0w
			table-column-count = 3 !
			table-columns-width = "33,33,33" !
		{
			--- TableColumn ---
				column-name = validityDate !
				column-type = domain !
				domainAttribute = validityDate !
				format = datetime.date-only
				type = text
				id = validityDate
				table-column-width = 33
			{
				--- TableColumnItem ---
					item-column = validityDate
					format = datetime.date-only
					previewValue = value
			}
			--- TableColumn ---
				column-name = codificationCode !
				column-type = domain !
				domainAttribute = codificationCode !
				type = text
				id = codificationCode
				table-column-width = 33
			{
				--- TableColumnItem ---
					item-column = codificationCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = sectorExtDenomination !
				column-type = domain !
				domainAttribute = sectorExtDenomination !
				type = text
				id = sectorExtDenomination
				table-column-width = 33
			{
				--- TableColumnItem ---
					item-column = sectorExtDenomination
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = codificationCode
				sort-direction = descending
				sort-rank = 2
			--- TableSort ---
				sort-column-name = validityDate
				sort-direction = descending
				sort-rank = 1
		}
	}
}