/*
* generated by Xtext
*/
package com.odcgroup.page.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import com.odcgroup.workbench.dsl.services.CommonGrammarAccess;

@Singleton
public class PageGrammarAccess extends AbstractGrammarElementFinder {


	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Model");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cModelAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cMetamodelVersionKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cEqualsSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cMetamodelVersionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cMetamodelVersionString_ValueParserRuleCall_3_0 = (RuleCall)cMetamodelVersionAssignment_3.eContents().get(0);
		private final Assignment cWidgetAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cWidgetWidgetParserRuleCall_4_0 = (RuleCall)cWidgetAssignment_4.eContents().get(0);

		//Model:
		//	{Model} "metamodelVersion" "=" metamodelVersion=String_Value widget=Widget;
		public ParserRule getRule() { return rule; }

		//{Model} "metamodelVersion" "=" metamodelVersion=String_Value widget=Widget
		public Group getGroup() { return cGroup; }

		//{Model}
		public Action getModelAction_0() { return cModelAction_0; }

		//"metamodelVersion"
		public Keyword getMetamodelVersionKeyword_1() { return cMetamodelVersionKeyword_1; }

		//"="
		public Keyword getEqualsSignKeyword_2() { return cEqualsSignKeyword_2; }

		//metamodelVersion=String_Value
		public Assignment getMetamodelVersionAssignment_3() { return cMetamodelVersionAssignment_3; }

		//String_Value
		public RuleCall getMetamodelVersionString_ValueParserRuleCall_3_0() { return cMetamodelVersionString_ValueParserRuleCall_3_0; }

		//widget=Widget
		public Assignment getWidgetAssignment_4() { return cWidgetAssignment_4; }

		//Widget
		public RuleCall getWidgetWidgetParserRuleCall_4_0() { return cWidgetWidgetParserRuleCall_4_0; }
	}

	public class WidgetElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Widget");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cWidgetAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cHyphenMinusHyphenMinusHyphenMinusKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Assignment cLibraryNameAssignment_2_0 = (Assignment)cGroup_2.eContents().get(0);
		private final RuleCall cLibraryNameLibraryNameParserRuleCall_2_0_0 = (RuleCall)cLibraryNameAssignment_2_0.eContents().get(0);
		private final Keyword cColonKeyword_2_1 = (Keyword)cGroup_2.eContents().get(1);
		private final Assignment cTypeNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cTypeNameIDTerminalRuleCall_3_0 = (RuleCall)cTypeNameAssignment_3.eContents().get(0);
		private final Keyword cHyphenMinusHyphenMinusHyphenMinusKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cLabelsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cLabelsAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cLabelsTranslationParserRuleCall_5_1_0 = (RuleCall)cLabelsAssignment_5_1.eContents().get(0);
		private final Group cGroup_5_2 = (Group)cGroup_5.eContents().get(2);
		private final Keyword cCommaKeyword_5_2_0 = (Keyword)cGroup_5_2.eContents().get(0);
		private final Assignment cLabelsAssignment_5_2_1 = (Assignment)cGroup_5_2.eContents().get(1);
		private final RuleCall cLabelsTranslationParserRuleCall_5_2_1_0 = (RuleCall)cLabelsAssignment_5_2_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cToolTipsKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cToolTipsAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cToolTipsTranslationParserRuleCall_6_1_0 = (RuleCall)cToolTipsAssignment_6_1.eContents().get(0);
		private final Group cGroup_6_2 = (Group)cGroup_6.eContents().get(2);
		private final Keyword cCommaKeyword_6_2_0 = (Keyword)cGroup_6_2.eContents().get(0);
		private final Assignment cToolTipsAssignment_6_2_1 = (Assignment)cGroup_6_2.eContents().get(1);
		private final RuleCall cToolTipsTranslationParserRuleCall_6_2_1_0 = (RuleCall)cToolTipsAssignment_6_2_1.eContents().get(0);
		private final Assignment cPropertiesAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cPropertiesPropertyParserRuleCall_7_0 = (RuleCall)cPropertiesAssignment_7.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cLeftCurlyBracketKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Group cGroup_8_1 = (Group)cGroup_8.eContents().get(1);
		private final Assignment cEventsAssignment_8_1_0 = (Assignment)cGroup_8_1.eContents().get(0);
		private final RuleCall cEventsEventParserRuleCall_8_1_0_0 = (RuleCall)cEventsAssignment_8_1_0.eContents().get(0);
		private final Assignment cEventsAssignment_8_1_1 = (Assignment)cGroup_8_1.eContents().get(1);
		private final RuleCall cEventsEventParserRuleCall_8_1_1_0 = (RuleCall)cEventsAssignment_8_1_1.eContents().get(0);
		private final Group cGroup_8_2 = (Group)cGroup_8.eContents().get(2);
		private final Assignment cSnippetsAssignment_8_2_0 = (Assignment)cGroup_8_2.eContents().get(0);
		private final RuleCall cSnippetsSnippetParserRuleCall_8_2_0_0 = (RuleCall)cSnippetsAssignment_8_2_0.eContents().get(0);
		private final Assignment cSnippetsAssignment_8_2_1 = (Assignment)cGroup_8_2.eContents().get(1);
		private final RuleCall cSnippetsSnippetParserRuleCall_8_2_1_0 = (RuleCall)cSnippetsAssignment_8_2_1.eContents().get(0);
		private final Group cGroup_8_3 = (Group)cGroup_8.eContents().get(3);
		private final Assignment cContentsAssignment_8_3_0 = (Assignment)cGroup_8_3.eContents().get(0);
		private final RuleCall cContentsWidgetParserRuleCall_8_3_0_0 = (RuleCall)cContentsAssignment_8_3_0.eContents().get(0);
		private final Assignment cContentsAssignment_8_3_1 = (Assignment)cGroup_8_3.eContents().get(1);
		private final RuleCall cContentsWidgetParserRuleCall_8_3_1_0 = (RuleCall)cContentsAssignment_8_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8_4 = (Keyword)cGroup_8.eContents().get(4);

		//Widget:
		//	{Widget} "---" (libraryName=LibraryName ":")? typeName=ID "---" ("labels" labels+=Translation (","
		//	labels+=Translation)*)? ("toolTips" toolTips+=Translation ("," toolTips+=Translation)*)? properties+=Property* ("{"
		//	(events+=Event events+=Event*)? (snippets+=Snippet snippets+=Snippet*)? (contents+=Widget contents+=Widget*)? "}")?;
		public ParserRule getRule() { return rule; }

		//{Widget} "---" (libraryName=LibraryName ":")? typeName=ID "---" ("labels" labels+=Translation (","
		//labels+=Translation)*)? ("toolTips" toolTips+=Translation ("," toolTips+=Translation)*)? properties+=Property* ("{"
		//(events+=Event events+=Event*)? (snippets+=Snippet snippets+=Snippet*)? (contents+=Widget contents+=Widget*)? "}")?
		public Group getGroup() { return cGroup; }

		//{Widget}
		public Action getWidgetAction_0() { return cWidgetAction_0; }

		//"---"
		public Keyword getHyphenMinusHyphenMinusHyphenMinusKeyword_1() { return cHyphenMinusHyphenMinusHyphenMinusKeyword_1; }

		//(libraryName=LibraryName ":")?
		public Group getGroup_2() { return cGroup_2; }

		//libraryName=LibraryName
		public Assignment getLibraryNameAssignment_2_0() { return cLibraryNameAssignment_2_0; }

		//LibraryName
		public RuleCall getLibraryNameLibraryNameParserRuleCall_2_0_0() { return cLibraryNameLibraryNameParserRuleCall_2_0_0; }

		//":"
		public Keyword getColonKeyword_2_1() { return cColonKeyword_2_1; }

		//typeName=ID
		public Assignment getTypeNameAssignment_3() { return cTypeNameAssignment_3; }

		//ID
		public RuleCall getTypeNameIDTerminalRuleCall_3_0() { return cTypeNameIDTerminalRuleCall_3_0; }

		//"---"
		public Keyword getHyphenMinusHyphenMinusHyphenMinusKeyword_4() { return cHyphenMinusHyphenMinusHyphenMinusKeyword_4; }

		//("labels" labels+=Translation ("," labels+=Translation)*)?
		public Group getGroup_5() { return cGroup_5; }

		//"labels"
		public Keyword getLabelsKeyword_5_0() { return cLabelsKeyword_5_0; }

		//labels+=Translation
		public Assignment getLabelsAssignment_5_1() { return cLabelsAssignment_5_1; }

		//Translation
		public RuleCall getLabelsTranslationParserRuleCall_5_1_0() { return cLabelsTranslationParserRuleCall_5_1_0; }

		//("," labels+=Translation)*
		public Group getGroup_5_2() { return cGroup_5_2; }

		//","
		public Keyword getCommaKeyword_5_2_0() { return cCommaKeyword_5_2_0; }

		//labels+=Translation
		public Assignment getLabelsAssignment_5_2_1() { return cLabelsAssignment_5_2_1; }

		//Translation
		public RuleCall getLabelsTranslationParserRuleCall_5_2_1_0() { return cLabelsTranslationParserRuleCall_5_2_1_0; }

		//("toolTips" toolTips+=Translation ("," toolTips+=Translation)*)?
		public Group getGroup_6() { return cGroup_6; }

		//"toolTips"
		public Keyword getToolTipsKeyword_6_0() { return cToolTipsKeyword_6_0; }

		//toolTips+=Translation
		public Assignment getToolTipsAssignment_6_1() { return cToolTipsAssignment_6_1; }

		//Translation
		public RuleCall getToolTipsTranslationParserRuleCall_6_1_0() { return cToolTipsTranslationParserRuleCall_6_1_0; }

		//("," toolTips+=Translation)*
		public Group getGroup_6_2() { return cGroup_6_2; }

		//","
		public Keyword getCommaKeyword_6_2_0() { return cCommaKeyword_6_2_0; }

		//toolTips+=Translation
		public Assignment getToolTipsAssignment_6_2_1() { return cToolTipsAssignment_6_2_1; }

		//Translation
		public RuleCall getToolTipsTranslationParserRuleCall_6_2_1_0() { return cToolTipsTranslationParserRuleCall_6_2_1_0; }

		//properties+=Property*
		public Assignment getPropertiesAssignment_7() { return cPropertiesAssignment_7; }

		//Property
		public RuleCall getPropertiesPropertyParserRuleCall_7_0() { return cPropertiesPropertyParserRuleCall_7_0; }

		//("{" (events+=Event events+=Event*)? (snippets+=Snippet snippets+=Snippet*)? (contents+=Widget contents+=Widget*)? "}")?
		public Group getGroup_8() { return cGroup_8; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_8_0() { return cLeftCurlyBracketKeyword_8_0; }

		//(events+=Event events+=Event*)?
		public Group getGroup_8_1() { return cGroup_8_1; }

		//events+=Event
		public Assignment getEventsAssignment_8_1_0() { return cEventsAssignment_8_1_0; }

		//Event
		public RuleCall getEventsEventParserRuleCall_8_1_0_0() { return cEventsEventParserRuleCall_8_1_0_0; }

		//events+=Event*
		public Assignment getEventsAssignment_8_1_1() { return cEventsAssignment_8_1_1; }

		//Event
		public RuleCall getEventsEventParserRuleCall_8_1_1_0() { return cEventsEventParserRuleCall_8_1_1_0; }

		//(snippets+=Snippet snippets+=Snippet*)?
		public Group getGroup_8_2() { return cGroup_8_2; }

		//snippets+=Snippet
		public Assignment getSnippetsAssignment_8_2_0() { return cSnippetsAssignment_8_2_0; }

		//Snippet
		public RuleCall getSnippetsSnippetParserRuleCall_8_2_0_0() { return cSnippetsSnippetParserRuleCall_8_2_0_0; }

		//snippets+=Snippet*
		public Assignment getSnippetsAssignment_8_2_1() { return cSnippetsAssignment_8_2_1; }

		//Snippet
		public RuleCall getSnippetsSnippetParserRuleCall_8_2_1_0() { return cSnippetsSnippetParserRuleCall_8_2_1_0; }

		//(contents+=Widget contents+=Widget*)?
		public Group getGroup_8_3() { return cGroup_8_3; }

		//contents+=Widget
		public Assignment getContentsAssignment_8_3_0() { return cContentsAssignment_8_3_0; }

		//Widget
		public RuleCall getContentsWidgetParserRuleCall_8_3_0_0() { return cContentsWidgetParserRuleCall_8_3_0_0; }

		//contents+=Widget*
		public Assignment getContentsAssignment_8_3_1() { return cContentsAssignment_8_3_1; }

		//Widget
		public RuleCall getContentsWidgetParserRuleCall_8_3_1_0() { return cContentsWidgetParserRuleCall_8_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_8_4() { return cRightCurlyBracketKeyword_8_4; }
	}

	public class TimestampElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Timestamp");
		private final RuleCall cString_ValueParserRuleCall = (RuleCall)rule.eContents().get(1);

		//Timestamp returns ecore::EDate:
		//	String_Value;
		public ParserRule getRule() { return rule; }

		//String_Value
		public RuleCall getString_ValueParserRuleCall() { return cString_ValueParserRuleCall; }
	}

	public class PropertyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Property");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cPropertyAction_0 = (Action)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Assignment cLibraryNameAssignment_1_0 = (Assignment)cGroup_1.eContents().get(0);
		private final RuleCall cLibraryNameIDTerminalRuleCall_1_0_0 = (RuleCall)cLibraryNameAssignment_1_0.eContents().get(0);
		private final Keyword cColonKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cTypeNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTypeNameIDTerminalRuleCall_2_0 = (RuleCall)cTypeNameAssignment_2.eContents().get(0);
		private final Keyword cEqualsSignKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cValueAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cValueString_ValueParserRuleCall_4_0 = (RuleCall)cValueAssignment_4.eContents().get(0);
		private final Assignment cReadonlyAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final Keyword cReadonlyExclamationMarkKeyword_5_0 = (Keyword)cReadonlyAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cExclamationMarkKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cModelAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final CrossReference cModelModelCrossReference_6_1_0 = (CrossReference)cModelAssignment_6_1.eContents().get(0);
		private final RuleCall cModelModelURITerminalRuleCall_6_1_0_1 = (RuleCall)cModelModelCrossReference_6_1_0.eContents().get(1);

		//Property:
		//	{Property} (libraryName=ID ":")? typeName=ID "=" value=String_Value readonly?="!"? ("!" model=[Model|URI])?;
		public ParserRule getRule() { return rule; }

		//{Property} (libraryName=ID ":")? typeName=ID "=" value=String_Value readonly?="!"? ("!" model=[Model|URI])?
		public Group getGroup() { return cGroup; }

		//{Property}
		public Action getPropertyAction_0() { return cPropertyAction_0; }

		//(libraryName=ID ":")?
		public Group getGroup_1() { return cGroup_1; }

		//libraryName=ID
		public Assignment getLibraryNameAssignment_1_0() { return cLibraryNameAssignment_1_0; }

		//ID
		public RuleCall getLibraryNameIDTerminalRuleCall_1_0_0() { return cLibraryNameIDTerminalRuleCall_1_0_0; }

		//":"
		public Keyword getColonKeyword_1_1() { return cColonKeyword_1_1; }

		//typeName=ID
		public Assignment getTypeNameAssignment_2() { return cTypeNameAssignment_2; }

		//ID
		public RuleCall getTypeNameIDTerminalRuleCall_2_0() { return cTypeNameIDTerminalRuleCall_2_0; }

		//"="
		public Keyword getEqualsSignKeyword_3() { return cEqualsSignKeyword_3; }

		//value=String_Value
		public Assignment getValueAssignment_4() { return cValueAssignment_4; }

		//String_Value
		public RuleCall getValueString_ValueParserRuleCall_4_0() { return cValueString_ValueParserRuleCall_4_0; }

		//readonly?="!"?
		public Assignment getReadonlyAssignment_5() { return cReadonlyAssignment_5; }

		//"!"
		public Keyword getReadonlyExclamationMarkKeyword_5_0() { return cReadonlyExclamationMarkKeyword_5_0; }

		//("!" model=[Model|URI])?
		public Group getGroup_6() { return cGroup_6; }

		//"!"
		public Keyword getExclamationMarkKeyword_6_0() { return cExclamationMarkKeyword_6_0; }

		//model=[Model|URI]
		public Assignment getModelAssignment_6_1() { return cModelAssignment_6_1; }

		//[Model|URI]
		public CrossReference getModelModelCrossReference_6_1_0() { return cModelModelCrossReference_6_1_0; }

		//URI
		public RuleCall getModelModelURITerminalRuleCall_6_1_0_1() { return cModelModelURITerminalRuleCall_6_1_0_1; }
	}

	public class EventElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Event");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEventKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cEventNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cEventNameString_ValueParserRuleCall_1_0 = (RuleCall)cEventNameAssignment_1.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cFunctionNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cFunctionNameString_ValueParserRuleCall_3_0 = (RuleCall)cFunctionNameAssignment_3.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cNatureAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cNatureEventNatureEnumRuleCall_5_0 = (RuleCall)cNatureAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cSolidusSolidusKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cDescriptionAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cDescriptionString_ValueParserRuleCall_6_1_0 = (RuleCall)cDescriptionAssignment_6_1.eContents().get(0);
		private final Assignment cPropertiesAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cPropertiesPropertyParserRuleCall_7_0 = (RuleCall)cPropertiesAssignment_7.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cMessagesKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cMessagesAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cMessagesTranslationParserRuleCall_8_1_0 = (RuleCall)cMessagesAssignment_8_1.eContents().get(0);
		private final Group cGroup_8_2 = (Group)cGroup_8.eContents().get(2);
		private final Keyword cCommaKeyword_8_2_0 = (Keyword)cGroup_8_2.eContents().get(0);
		private final Assignment cMessagesAssignment_8_2_1 = (Assignment)cGroup_8_2.eContents().get(1);
		private final RuleCall cMessagesTranslationParserRuleCall_8_2_1_0 = (RuleCall)cMessagesAssignment_8_2_1.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cLeftCurlyBracketKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Group cGroup_9_1 = (Group)cGroup_9.eContents().get(1);
		private final Assignment cParametersAssignment_9_1_0 = (Assignment)cGroup_9_1.eContents().get(0);
		private final RuleCall cParametersParameterParserRuleCall_9_1_0_0 = (RuleCall)cParametersAssignment_9_1_0.eContents().get(0);
		private final Assignment cParametersAssignment_9_1_1 = (Assignment)cGroup_9_1.eContents().get(1);
		private final RuleCall cParametersParameterParserRuleCall_9_1_1_0 = (RuleCall)cParametersAssignment_9_1_1.eContents().get(0);
		private final Group cGroup_9_2 = (Group)cGroup_9.eContents().get(2);
		private final Assignment cSnippetsAssignment_9_2_0 = (Assignment)cGroup_9_2.eContents().get(0);
		private final RuleCall cSnippetsSnippetParserRuleCall_9_2_0_0 = (RuleCall)cSnippetsAssignment_9_2_0.eContents().get(0);
		private final Assignment cSnippetsAssignment_9_2_1 = (Assignment)cGroup_9_2.eContents().get(1);
		private final RuleCall cSnippetsSnippetParserRuleCall_9_2_1_0 = (RuleCall)cSnippetsAssignment_9_2_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9_3 = (Keyword)cGroup_9.eContents().get(3);

		//Event:
		//	"Event" eventName=String_Value "(" functionName=String_Value ")" nature=EventNature? ("//" description=String_Value)?
		//	properties+=Property* ("messages" messages+=Translation ("," messages+=Translation)*)? ("{" (parameters+=Parameter
		//	parameters+=Parameter*)? (snippets+=Snippet snippets+=Snippet*)? "}")?;
		public ParserRule getRule() { return rule; }

		//"Event" eventName=String_Value "(" functionName=String_Value ")" nature=EventNature? ("//" description=String_Value)?
		//properties+=Property* ("messages" messages+=Translation ("," messages+=Translation)*)? ("{" (parameters+=Parameter
		//parameters+=Parameter*)? (snippets+=Snippet snippets+=Snippet*)? "}")?
		public Group getGroup() { return cGroup; }

		//"Event"
		public Keyword getEventKeyword_0() { return cEventKeyword_0; }

		//eventName=String_Value
		public Assignment getEventNameAssignment_1() { return cEventNameAssignment_1; }

		//String_Value
		public RuleCall getEventNameString_ValueParserRuleCall_1_0() { return cEventNameString_ValueParserRuleCall_1_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_2() { return cLeftParenthesisKeyword_2; }

		//functionName=String_Value
		public Assignment getFunctionNameAssignment_3() { return cFunctionNameAssignment_3; }

		//String_Value
		public RuleCall getFunctionNameString_ValueParserRuleCall_3_0() { return cFunctionNameString_ValueParserRuleCall_3_0; }

		//")"
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }

		//nature=EventNature?
		public Assignment getNatureAssignment_5() { return cNatureAssignment_5; }

		//EventNature
		public RuleCall getNatureEventNatureEnumRuleCall_5_0() { return cNatureEventNatureEnumRuleCall_5_0; }

		//("//" description=String_Value)?
		public Group getGroup_6() { return cGroup_6; }

		//"//"
		public Keyword getSolidusSolidusKeyword_6_0() { return cSolidusSolidusKeyword_6_0; }

		//description=String_Value
		public Assignment getDescriptionAssignment_6_1() { return cDescriptionAssignment_6_1; }

		//String_Value
		public RuleCall getDescriptionString_ValueParserRuleCall_6_1_0() { return cDescriptionString_ValueParserRuleCall_6_1_0; }

		//properties+=Property*
		public Assignment getPropertiesAssignment_7() { return cPropertiesAssignment_7; }

		//Property
		public RuleCall getPropertiesPropertyParserRuleCall_7_0() { return cPropertiesPropertyParserRuleCall_7_0; }

		//("messages" messages+=Translation ("," messages+=Translation)*)?
		public Group getGroup_8() { return cGroup_8; }

		//"messages"
		public Keyword getMessagesKeyword_8_0() { return cMessagesKeyword_8_0; }

		//messages+=Translation
		public Assignment getMessagesAssignment_8_1() { return cMessagesAssignment_8_1; }

		//Translation
		public RuleCall getMessagesTranslationParserRuleCall_8_1_0() { return cMessagesTranslationParserRuleCall_8_1_0; }

		//("," messages+=Translation)*
		public Group getGroup_8_2() { return cGroup_8_2; }

		//","
		public Keyword getCommaKeyword_8_2_0() { return cCommaKeyword_8_2_0; }

		//messages+=Translation
		public Assignment getMessagesAssignment_8_2_1() { return cMessagesAssignment_8_2_1; }

		//Translation
		public RuleCall getMessagesTranslationParserRuleCall_8_2_1_0() { return cMessagesTranslationParserRuleCall_8_2_1_0; }

		//("{" (parameters+=Parameter parameters+=Parameter*)? (snippets+=Snippet snippets+=Snippet*)? "}")?
		public Group getGroup_9() { return cGroup_9; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_9_0() { return cLeftCurlyBracketKeyword_9_0; }

		//(parameters+=Parameter parameters+=Parameter*)?
		public Group getGroup_9_1() { return cGroup_9_1; }

		//parameters+=Parameter
		public Assignment getParametersAssignment_9_1_0() { return cParametersAssignment_9_1_0; }

		//Parameter
		public RuleCall getParametersParameterParserRuleCall_9_1_0_0() { return cParametersParameterParserRuleCall_9_1_0_0; }

		//parameters+=Parameter*
		public Assignment getParametersAssignment_9_1_1() { return cParametersAssignment_9_1_1; }

		//Parameter
		public RuleCall getParametersParameterParserRuleCall_9_1_1_0() { return cParametersParameterParserRuleCall_9_1_1_0; }

		//(snippets+=Snippet snippets+=Snippet*)?
		public Group getGroup_9_2() { return cGroup_9_2; }

		//snippets+=Snippet
		public Assignment getSnippetsAssignment_9_2_0() { return cSnippetsAssignment_9_2_0; }

		//Snippet
		public RuleCall getSnippetsSnippetParserRuleCall_9_2_0_0() { return cSnippetsSnippetParserRuleCall_9_2_0_0; }

		//snippets+=Snippet*
		public Assignment getSnippetsAssignment_9_2_1() { return cSnippetsAssignment_9_2_1; }

		//Snippet
		public RuleCall getSnippetsSnippetParserRuleCall_9_2_1_0() { return cSnippetsSnippetParserRuleCall_9_2_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_9_3() { return cRightCurlyBracketKeyword_9_3; }
	}

	public class SnippetElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Snippet");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSnippetAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cSnippetKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTypeNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTypeNameString_ValueParserRuleCall_2_0 = (RuleCall)cTypeNameAssignment_2.eContents().get(0);
		private final Assignment cPropertiesAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cPropertiesPropertyParserRuleCall_3_0 = (RuleCall)cPropertiesAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cLeftCurlyBracketKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Group cGroup_4_1 = (Group)cGroup_4.eContents().get(1);
		private final Assignment cContentsAssignment_4_1_0 = (Assignment)cGroup_4_1.eContents().get(0);
		private final RuleCall cContentsSnippetParserRuleCall_4_1_0_0 = (RuleCall)cContentsAssignment_4_1_0.eContents().get(0);
		private final Assignment cContentsAssignment_4_1_1 = (Assignment)cGroup_4_1.eContents().get(1);
		private final RuleCall cContentsSnippetParserRuleCall_4_1_1_0 = (RuleCall)cContentsAssignment_4_1_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_2 = (Keyword)cGroup_4.eContents().get(2);

		//Snippet:
		//	{Snippet} "Snippet" typeName=String_Value? properties+=Property* ("{" (contents+=Snippet contents+=Snippet*)? "}")?;
		public ParserRule getRule() { return rule; }

		//{Snippet} "Snippet" typeName=String_Value? properties+=Property* ("{" (contents+=Snippet contents+=Snippet*)? "}")?
		public Group getGroup() { return cGroup; }

		//{Snippet}
		public Action getSnippetAction_0() { return cSnippetAction_0; }

		//"Snippet"
		public Keyword getSnippetKeyword_1() { return cSnippetKeyword_1; }

		//typeName=String_Value?
		public Assignment getTypeNameAssignment_2() { return cTypeNameAssignment_2; }

		//String_Value
		public RuleCall getTypeNameString_ValueParserRuleCall_2_0() { return cTypeNameString_ValueParserRuleCall_2_0; }

		//properties+=Property*
		public Assignment getPropertiesAssignment_3() { return cPropertiesAssignment_3; }

		//Property
		public RuleCall getPropertiesPropertyParserRuleCall_3_0() { return cPropertiesPropertyParserRuleCall_3_0; }

		//("{" (contents+=Snippet contents+=Snippet*)? "}")?
		public Group getGroup_4() { return cGroup_4; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_4_0() { return cLeftCurlyBracketKeyword_4_0; }

		//(contents+=Snippet contents+=Snippet*)?
		public Group getGroup_4_1() { return cGroup_4_1; }

		//contents+=Snippet
		public Assignment getContentsAssignment_4_1_0() { return cContentsAssignment_4_1_0; }

		//Snippet
		public RuleCall getContentsSnippetParserRuleCall_4_1_0_0() { return cContentsSnippetParserRuleCall_4_1_0_0; }

		//contents+=Snippet*
		public Assignment getContentsAssignment_4_1_1() { return cContentsAssignment_4_1_1; }

		//Snippet
		public RuleCall getContentsSnippetParserRuleCall_4_1_1_0() { return cContentsSnippetParserRuleCall_4_1_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4_2() { return cRightCurlyBracketKeyword_4_2; }
	}

	public class TranslationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Translation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cLanguageAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cLanguageIDTerminalRuleCall_0_0 = (RuleCall)cLanguageAssignment_0.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cMessageAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cMessageString_ValueParserRuleCall_2_0 = (RuleCall)cMessageAssignment_2.eContents().get(0);

		//Translation:
		//	language=ID "=" message=String_Value;
		public ParserRule getRule() { return rule; }

		//language=ID "=" message=String_Value
		public Group getGroup() { return cGroup; }

		//language=ID
		public Assignment getLanguageAssignment_0() { return cLanguageAssignment_0; }

		//ID
		public RuleCall getLanguageIDTerminalRuleCall_0_0() { return cLanguageIDTerminalRuleCall_0_0; }

		//"="
		public Keyword getEqualsSignKeyword_1() { return cEqualsSignKeyword_1; }

		//message=String_Value
		public Assignment getMessageAssignment_2() { return cMessageAssignment_2; }

		//String_Value
		public RuleCall getMessageString_ValueParserRuleCall_2_0() { return cMessageString_ValueParserRuleCall_2_0; }
	}

	public class ParameterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Parameter");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cValueAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cValueString_ValueParserRuleCall_2_0 = (RuleCall)cValueAssignment_2.eContents().get(0);
		private final Assignment cUserDefinedAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final Keyword cUserDefinedUdKeyword_3_0 = (Keyword)cUserDefinedAssignment_3.eContents().get(0);

		//Parameter:
		//	name=ID "=" value=String_Value userDefined?="ud"?;
		public ParserRule getRule() { return rule; }

		//name=ID "=" value=String_Value userDefined?="ud"?
		public Group getGroup() { return cGroup; }

		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }

		//"="
		public Keyword getEqualsSignKeyword_1() { return cEqualsSignKeyword_1; }

		//value=String_Value
		public Assignment getValueAssignment_2() { return cValueAssignment_2; }

		//String_Value
		public RuleCall getValueString_ValueParserRuleCall_2_0() { return cValueString_ValueParserRuleCall_2_0; }

		//userDefined?="ud"?
		public Assignment getUserDefinedAssignment_3() { return cUserDefinedAssignment_3; }

		//"ud"
		public Keyword getUserDefinedUdKeyword_3_0() { return cUserDefinedUdKeyword_3_0; }
	}

	public class LibraryNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "LibraryName");
		private final RuleCall cIDTerminalRuleCall = (RuleCall)rule.eContents().get(1);

		//// Data type rules
		// LibraryName:
		//	ID;
		public ParserRule getRule() { return rule; }

		//ID
		public RuleCall getIDTerminalRuleCall() { return cIDTerminalRuleCall; }
	}


	public class EventNatureElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "EventNature");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cADVANCEDEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cADVANCEDAKeyword_0_0 = (Keyword)cADVANCEDEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cSIMPLIFIEDEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cSIMPLIFIEDSKeyword_1_0 = (Keyword)cSIMPLIFIEDEnumLiteralDeclaration_1.eContents().get(0);

		//enum EventNature:
		//	ADVANCED="A" | SIMPLIFIED="S";
		public EnumRule getRule() { return rule; }

		//ADVANCED="A" | SIMPLIFIED="S"
		public Alternatives getAlternatives() { return cAlternatives; }

		//ADVANCED="A"
		public EnumLiteralDeclaration getADVANCEDEnumLiteralDeclaration_0() { return cADVANCEDEnumLiteralDeclaration_0; }

		//"A"
		public Keyword getADVANCEDAKeyword_0_0() { return cADVANCEDAKeyword_0_0; }

		//SIMPLIFIED="S"
		public EnumLiteralDeclaration getSIMPLIFIEDEnumLiteralDeclaration_1() { return cSIMPLIFIEDEnumLiteralDeclaration_1; }

		//"S"
		public Keyword getSIMPLIFIEDSKeyword_1_0() { return cSIMPLIFIEDSKeyword_1_0; }
	}

	private final ModelElements pModel;
	private final WidgetElements pWidget;
	private final TimestampElements pTimestamp;
	private final PropertyElements pProperty;
	private final EventElements pEvent;
	private final SnippetElements pSnippet;
	private final TranslationElements pTranslation;
	private final EventNatureElements unknownRuleEventNature;
	private final ParameterElements pParameter;
	private final LibraryNameElements pLibraryName;
	private final TerminalRule tML_COMMENT;
	private final TerminalRule tSL_COMMENT;
	private final TerminalRule tWS;

	private final Grammar grammar;

	private final CommonGrammarAccess gaCommon;

	@Inject
	public PageGrammarAccess(GrammarProvider grammarProvider,
		CommonGrammarAccess gaCommon) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaCommon = gaCommon;
		this.pModel = new ModelElements();
		this.pWidget = new WidgetElements();
		this.pTimestamp = new TimestampElements();
		this.pProperty = new PropertyElements();
		this.pEvent = new EventElements();
		this.pSnippet = new SnippetElements();
		this.pTranslation = new TranslationElements();
		this.unknownRuleEventNature = new EventNatureElements();
		this.pParameter = new ParameterElements();
		this.pLibraryName = new LibraryNameElements();
		this.tML_COMMENT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "ML_COMMENT");
		this.tSL_COMMENT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "SL_COMMENT");
		this.tWS = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "WS");
	}

	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("com.odcgroup.page.Page".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}


	public Grammar getGrammar() {
		return grammar;
	}


	public CommonGrammarAccess getCommonGrammarAccess() {
		return gaCommon;
	}


	//Model:
	//	{Model} "metamodelVersion" "=" metamodelVersion=String_Value widget=Widget;
	public ModelElements getModelAccess() {
		return pModel;
	}

	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}

	//Widget:
	//	{Widget} "---" (libraryName=LibraryName ":")? typeName=ID "---" ("labels" labels+=Translation (","
	//	labels+=Translation)*)? ("toolTips" toolTips+=Translation ("," toolTips+=Translation)*)? properties+=Property* ("{"
	//	(events+=Event events+=Event*)? (snippets+=Snippet snippets+=Snippet*)? (contents+=Widget contents+=Widget*)? "}")?;
	public WidgetElements getWidgetAccess() {
		return pWidget;
	}

	public ParserRule getWidgetRule() {
		return getWidgetAccess().getRule();
	}

	//Timestamp returns ecore::EDate:
	//	String_Value;
	public TimestampElements getTimestampAccess() {
		return pTimestamp;
	}

	public ParserRule getTimestampRule() {
		return getTimestampAccess().getRule();
	}

	//Property:
	//	{Property} (libraryName=ID ":")? typeName=ID "=" value=String_Value readonly?="!"? ("!" model=[Model|URI])?;
	public PropertyElements getPropertyAccess() {
		return pProperty;
	}

	public ParserRule getPropertyRule() {
		return getPropertyAccess().getRule();
	}

	//Event:
	//	"Event" eventName=String_Value "(" functionName=String_Value ")" nature=EventNature? ("//" description=String_Value)?
	//	properties+=Property* ("messages" messages+=Translation ("," messages+=Translation)*)? ("{" (parameters+=Parameter
	//	parameters+=Parameter*)? (snippets+=Snippet snippets+=Snippet*)? "}")?;
	public EventElements getEventAccess() {
		return pEvent;
	}

	public ParserRule getEventRule() {
		return getEventAccess().getRule();
	}

	//Snippet:
	//	{Snippet} "Snippet" typeName=String_Value? properties+=Property* ("{" (contents+=Snippet contents+=Snippet*)? "}")?;
	public SnippetElements getSnippetAccess() {
		return pSnippet;
	}

	public ParserRule getSnippetRule() {
		return getSnippetAccess().getRule();
	}

	//Translation:
	//	language=ID "=" message=String_Value;
	public TranslationElements getTranslationAccess() {
		return pTranslation;
	}

	public ParserRule getTranslationRule() {
		return getTranslationAccess().getRule();
	}

	//enum EventNature:
	//	ADVANCED="A" | SIMPLIFIED="S";
	public EventNatureElements getEventNatureAccess() {
		return unknownRuleEventNature;
	}

	public EnumRule getEventNatureRule() {
		return getEventNatureAccess().getRule();
	}

	//Parameter:
	//	name=ID "=" value=String_Value userDefined?="ud"?;
	public ParameterElements getParameterAccess() {
		return pParameter;
	}

	public ParserRule getParameterRule() {
		return getParameterAccess().getRule();
	}

	//// Data type rules
	// LibraryName:
	//	ID;
	public LibraryNameElements getLibraryNameAccess() {
		return pLibraryName;
	}

	public ParserRule getLibraryNameRule() {
		return getLibraryNameAccess().getRule();
	}

	//// Terminal rules
	// terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return tML_COMMENT;
	}

	//terminal SL_COMMENT:
	//	"#" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return tSL_COMMENT;
	}

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return tWS;
	}

	//String_Value:
	//	STRING | ID | VALUE;
	public CommonGrammarAccess.String_ValueElements getString_ValueAccess() {
		return gaCommon.getString_ValueAccess();
	}

	public ParserRule getString_ValueRule() {
		return getString_ValueAccess().getRule();
	}

	//// Terminal rules
	// terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "-" | "." | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaCommon.getIDRule();
	}

	//terminal VALUE:
	//	("a".."z" | "A".."Z" | "_" | "0".."9" | "&" | "/" | "%" | "." | "-" | "é" | "è" | "à" | "ä" | "ö" | "ü" | "Ä" | "Ö" |
	//	"Ü" | "É" | "È" | "À" | "ç" | "ß")+;
	public TerminalRule getVALUERule() {
		return gaCommon.getVALUERule();
	}

	//terminal URI:
	//	("resource:///" | "platform:/") ("a".."z" | "A".."Z" | "_" | "0".."9" | "&" | "/" | "%" | "." | "-")+;
	public TerminalRule getURIRule() {
		return gaCommon.getURIRule();
	}

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"";
	public TerminalRule getSTRINGRule() {
		return gaCommon.getSTRINGRule();
	}
}
