# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Activity Summary", fr = "Résumé de l\'activité", de = "Zusammenfassung der Aktivität"
	containment = container
	domainEntity = "AAADSOperationHistory:OperationHistorySummaryList"
	bean-define = DSBean.AAADSOperationHistory.OperationHistorySummaryList
	bean-name = OperationHistorySummaryList
	id = SummaryList_ug_Rj
	documentation = "This module is used to display tabs allowing to see the summary of Portfolio Activity per portfolio or per instrument (defined in opening operation)."
	tid = 606913059981547
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TabbedPane ---
			id = X2_V_
			indexOfSelectedChild = 0
		{
			--- Tab ---
				labels en = "By Portfolio", fr = "Par portefeuille", de = "Per Portfolio"
				id = tab_d3_R_
				documentation = "This tab shows a module displaying the summary of Portfolio Activity per portfolio."
				isWidgetSelected = true
				tid = 606913060954635
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/operationhistory/summary/ByPortfolioList.module
			}
			--- Tab ---
				labels en = "By Instrument", fr = "Par instrument", de = "Per Instrument"
				id = tab_H__y1
				documentation = "This tab shows a module displaying the summary of Portfolio Activity per instrument defined in opening operation."
				isWidgetVisible = false
				tid = 606913061943976
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/operationhistory/summary/ByInstrumentList.module
			}
		}
	}
}