# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Activity Summary", fr = "Résumé de l\'activité", de = "Zusammenfassung der Aktivität"
	containment = container
	domainEntity = "AAADSOperationHistory:OperationHistorySummaryList"
	bean-define = DSBean.AAADSOperationHistory.OperationHistorySummaryList
	bean-name = OperationHistorySummaryList
	id = Summary_s__18
	documentation = "This module is used to display tabs allowing to see the summary of Portfolio Activity per portfolio or per instrument (defined in opening operation)."
	tid = 116853125146631
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TabbedPane ---
			id = HhU71
			indexOfSelectedChild = 1
		{
			--- Tab ---
				labels en = "By Portfolio", fr = "Par portefeuille", de = "Per Portfolio"
				id = tab_Y_1__
				documentation = "This tab shows a module displaying the summary of Portfolio Activity per portfolio."
				isWidgetVisible = false
				tid = 81518789428544
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/operationhistory/summary/ByPortfolio.module
			}
			--- Tab ---
				labels en = "By Instrument", fr = "Par instrument", de = "Per Instrument"
				id = tab_U69_s
				documentation = "This tab shows a module displaying the summary of Portfolio Activity per instrument defined in opening operation."
				isWidgetSelected = true
				tid = 81852108859366
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/operationhistory/summary/ByInstrument.module
			}
		}
	}
}