package com.temenos.t24.tools.eclipse.basic.views.inlineDocs.listener;

import org.dom4j.Document;
import org.dom4j.Node;

import com.temenos.t24.tools.eclipse.basic.document.xml.XmlUtil;
import com.temenos.t24.tools.eclipse.basic.help.AbstractT24FileHelper;
import com.temenos.t24.tools.eclipse.basic.wizards.docgeneration.file.GenerateDocConstants;

/**
 * helper class which helps to produce the help text about the item of in line
 * doc tree viewer, using xml file generated by comments strip out operation.
 * 
 * @author sbharathraja
 * 
 */
public class InLineDocsHelpCache {

    /** instance of {@link AbstractT24FileHelper} */
    private AbstractT24FileHelper xmlFileHelper;
    /** xml document corresponding to currently accessed subroutine */
    private Document xmlDocument;

    /**
     * get the help text about given subroutine name from comments xml file.
     * 
     * @param routineName - name of the subroutine
     * @param commentType - type of the comment (info/more info)
     * @return help text if found, empty otherwise
     */
    public String getRoutineHelpText(String routineName, String commentType) {
        startUpProcess(routineName);
        if (xmlDocument == null)
            return "";
        String xPath = "//SubRoutine[contains(@name ,'" + routineName + "')]";
        Node node = XmlUtil.getSingleNode(xmlDocument, xPath);
        if (node == null)
            return "";
        return XmlUtil.getAttributeValue(node, commentType);
    }

    /**
     * get help text about the given label which lies in given subroutine name,
     * from comments xml file.
     * 
     * @param routineName - name of the subroutine
     * @param labelName - name of the label/gosub
     * @return help text if found, empty otherwise
     */
    public String getLabelHelpText(String routineName, String labelName) {
        startUpProcess(routineName);
        if (xmlDocument == null)
            return "";
        String xPath = "//SubRoutine/GoSub[@" + GenerateDocConstants.IDENTIFIER_OF__ELEMENT + " ='" + labelName + "']";
        Node node = XmlUtil.getSingleNode(xmlDocument, xPath);
        if (node == null)
            return "";
        return XmlUtil.getAttributeValue(node, GenerateDocConstants.NAME_OF_SMALL_COMMENT);
    }

    /**
     * loading the xml document using given path
     * 
     * @param documentPath
     */
    private void loadDocument(String documentPath) {
        xmlDocument = XmlUtil.loadDocument(documentPath);
    }

    /**
     * initial process for getting help text. Here only the xml file path is
     * retrieved.
     * 
     * @param routineName - name of the subroutine
     */
    private void startUpProcess(String routineName) {
        xmlFileHelper = new T24CommentsFileExplorer();
        String xmlFilePath = xmlFileHelper.getCommentsXMLPath(routineName);
        loadDocument(xmlFilePath);
    }
}
