# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Held Assets", fr = "Actifs détenus", de = "Enthaltene Instrumente"
	domainEntity = "AAADSValuation:ValuationSummaryList"
	bean-define = DSBean.AAADSValuation.ValuationSummaryList
	bean-name = ValuationSummaryList
	id = ToptenHoldings_sko_9
	tid = 6875225978205
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			table-fixed-size = true
			table-page-size = 20
			table-preview-size = 1
			id = iE9_V
			table-column-count = 6 !
			table-columns-width = "16,16,16,16,16,16" !
		{
			--- TableColumn ---
				column-name = PORTFOLIO_NAME !
				column-type = domain !
				domainAttribute = PORTFOLIO_NAME !
				type = text
				column-visibility = not-visible
				id = PORTFOLIO_NAME
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = PORTFOLIO_NAME
					previewValue = value
			}
			--- TableColumn ---
				column-name = INSTR_DENOM !
				column-type = domain !
				domainAttribute = INSTR_DENOM !
				type = text
				id = INSTR_DENOM
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = INSTR_DENOM
					previewValue = value
			}
			--- TableColumn ---
				column-name = ASSET_CLASS_DENOM !
				column-type = domain !
				domainAttribute = ASSET_CLASS_DENOM !
				type = text
				id = ASSET_CLASS_DENOM
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = ASSET_CLASS_DENOM
					previewValue = value
			}
			--- TableColumn ---
				column-name = QUANTITY !
				column-type = domain !
				domainAttribute = QUANTITY !
				format = decimal.detailed
				type = text
				id = QUANTITY
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = QUANTITY
					format = decimal.2-digits
					previewValue = value
				--- Spacer ---
					height = 4
					width = 4
				--- TableColumnItem ---
					item-column = QUANTITY_CURR
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Market Value"
				column-name = comp_gcZd0
				type = amount
				id = gcZd0
				column-computation = make-amount
				column-computation-parameters = "MKT_VAL,REF_CURRENCY"
				table-column-width = 16
				tid = 21961261661068
			{
				--- TableColumnItem ---
					item-column = comp_gcZd0
					previewValue = value
			}
			--- TableColumn ---
				column-name = MKT_VAL_PERC !
				column-type = domain !
				domainAttribute = MKT_VAL_PERC !
				format = percentTA
				type = text
				id = MKT_VAL_PERC
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = MKT_VAL_PERC
					previewValue = value
				--- Label ---
					labels en = %, fr = %, de = %
					horizontalAlignment = "${corporatehalign}"
					id = c76_7
					tid = 24570554807695
			}
			--- TableSort ---
				sort-column-name = MKT_VAL_PERC
				sort-direction = descending
				sort-rank = 1
		}
	}
}