# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Instrument Details", fr = "Détails de l\'instrument", de = "Details des Instruments"
	domainEntity = "AAADSDomain:DomainContext"
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = InstrumentDetail_T_gRm
	tid = 6229753953618
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 5
			gridColumnsWidth = "20,20,8,8,8" !
			gridRowCount = 1
			verticalAlignment = lead
		{
			--- GridCell ---
				gridColumnWidth = 20
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainPortfolioDimensionView.fragment
			}
			--- GridCell ---
				gridColumnWidth = 20
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainInstrumentCodeView.fragment
			}
			--- GridCell ---
				gridColumnWidth = 8
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainFromDate.fragment
			}
			--- GridCell ---
				gridColumnWidth = 8
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainTillDate.fragment
			}
			--- GridCell ---
				gridColumnWidth = 8
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainHierarchyIdentifierView.fragment
			}
		}
		--- Grid ---
			cssClass = blank
			gridColumnCount = 4
			gridColumnsWidth = "25,25,25,25" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Button ---
					labels en = "Back to Summary", fr = "Retour au résumé", de = "Zurück zur Ansicht"
					id = btn_t_ntW
					tid = 6229753683098
				{
					Event OnClick (submit)
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						param = "flow-action=back"
						Query.fs_1.TargetDS = "AAADSOperationHistory:OperationHistoryDetailedList" ud
						Query.fs_1.cancel = true ud
						Query.fs_1.level = 0 ud
						Query.fs_2.TargetDS = "AAADSOperationHistory:OperationHistorySummaryList" ud
						Query.fs_2.cancel = true ud
						Query.fs_2.level = 0 ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
		}
	}
}