# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Portfolio Details", fr = "Détails du portefeuille", de = "Details des Portfolios"
	domainEntity = "AAADSDomain:DomainContext"
	collapsed = true
	collapsible = true
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = PortfolioCodeDetailHead_I___V
	tid = 6229744219916
{
	--- Box ---
		boxType = vertical
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 5
			gridColumnsWidth = "20,20,8,8,8" !
			gridRowCount = 1
			verticalAlignment = lead
		{
			--- GridCell ---
				gridColumnWidth = 20
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainPortfolioCodeView.fragment
			}
			--- GridCell ---
				gridColumnWidth = 20
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainInstrumentDimensionView.fragment
			}
			--- GridCell ---
				gridColumnWidth = 8
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainFromDateView.fragment
			}
			--- GridCell ---
				gridColumnWidth = 8
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainPivotDateTillView.fragment
			}
			--- GridCell ---
				gridColumnWidth = 8
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainHierarchyIdentifierView.fragment
			}
		}
	}
}