# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	containment = container
	domainEntity = "AAADSReturn:ReturnAnalysis"
	cssClass = nodeco
	bean-define = DSBean.AAADSReturn.ReturnAnalysis
	bean-name = ReturnAnalysis
	id = GlobalOverview_KvGeS
	documentation = "This view presents a synthesis of the main return indicators for the portfolio selected in the summary.\r\nThe values are computed for the global period of analysis, between from date and till date."
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/returnanalysis/detailedlist/OverviewMarketValue.module
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/returnanalysis/detailedlist/OverviewInPercent.module
	}
}