# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Return Detailed Views", fr = "Vue détaillée des rendements", de = "Rendite Detailansicht"
	containment = container
	domainEntity = "AAADSReturn:ReturnAnalysis"
	bean-define = DSBean.AAADSReturn.ReturnAnalysis
	bean-name = ReturnAnalysis
	id = OverviewByPortfolio_s_4_5
	documentation = "This view groups several detailled sub-views per portfolio."
	tid = 64750571800605
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			id = U___8
			indexOfSelectedChild = 2
		{
			--- Tab ---
				labels en = "Global Overview", fr = "Vue générale", de = Übersicht
				id = tab_T5K0_
				isWidgetVisible = false
				tid = 541556659149417
			{
				--- Box ---
					boxType = vertical
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/returnanalysis/detailedlist/GlobalOverview.module
				}
			}
			--- Tab ---
				labels en = "Return Monthly and Cumulated View", de = "Rendite - monatl. & kumul. Ansicht", fr = "Vue des rendements mensuels et cumulés "
				id = tab_cr9__
				isWidgetVisible = false
				tid = 541559162412261
			{
				--- Box ---
					boxType = vertical
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/returnanalysis/detailedlist/ReturnMonthlyAnalysis.module
					--- Code ---
						code = "<cinclude:include src=\"cocoon://module/aaa/corda/return/returnMonthly/Graph\" />"
				}
			}
			--- Tab ---
				labels en = "P&L Monthly and Cumulated View", de = "Gewinn/Verlust - monatl. & kumul. Ansicht", fr = "Vue G&P mensuel et cumulés"
				id = tab_z6J__
				isWidgetSelected = true
				tid = 312455350257923
			{
				--- Box ---
					boxType = vertical
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/returnanalysis/detailedlist/PLMonthlyAnalysis.module
					--- Code ---
						code = "<cinclude:include src=\"cocoon://module/aaa/corda/return/pandlMonthly/Graph\" />"
				}
			}
		}
	}
}