# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSReturn:ReturnAnalysis_2"
	cssClass = nodeco
	bean-define = DSBean.AAADSReturn.ReturnAnalysis_2
	bean-name = ReturnAnalysis_2
	id = OverviewInPercent_sG_X4
	documentation = "This view presents the compounding per effect of the return per portfolio for the period between from date and till date."
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			id = w_9_T
			indexOfSelectedChild = 0
		{
			--- Tab ---
				labels en = "Return & Effects", fr = "Rendement & effets", de = "Rendite & Effekte"
				id = tab_Z_76f
				isWidgetSelected = true
				tid = 517205392762568
			{
				--- TableTree ---
					table-filter-layer = true
					id = iL3j0
					table-column-count = 8 !
					table-columns-width = "12,12,12,12,12,12,12,12" !
				{
					--- TableColumn ---
						column-name = PORTFOLIO_NAME !
						column-type = domain !
						domainAttribute = PORTFOLIO_NAME !
						type = text
						column-locked = true
						column-width = 180
						id = PORTFOLIO_NAME
						table-column-width = 12
					{
						--- TableColumnItem ---
							item-column = PORTFOLIO_NAME
							previewValue = value
					}
					--- TableColumn ---
						labels en = "Portfolio Return", fr = "Rendement du portefeuille", de = "Rendite Portfolio"
						column-name = CUMUL_TOT_RET !
						column-type = domain !
						domainAttribute = CUMUL_TOT_RET !
						type = text
						id = CUMUL_TOT_RET
						table-column-width = 12
						tid = 21173906634033
					{
						--- TableColumnItem ---
							item-column = CUMUL_TOT_RET
							format = percentTA
							previewValue = value
					}
					--- TableColumn ---
						labels en = "Benchmark Return", fr = "Rendement de l\'Indice", de = "Rendite Benchmark"
						column-name = CUMUL_TOT_RET_BENCH !
						column-type = domain !
						domainAttribute = CUMUL_TOT_RET_BENCH !
						type = text
						id = CUMUL_TOT_RET_BENCH
						table-column-width = 12
						tid = 21189438363611
					{
						--- TableColumnItem ---
							item-column = CUMUL_TOT_RET_BENCH
							format = percentTA
							previewValue = value
					}
					--- TableColumn ---
						labels en = "Capital Effect", fr = "Effet sur capital", de = Kapitaleffekt
						column-name = CUMUL_CAP_EFFECT !
						column-type = domain !
						domainAttribute = CUMUL_CAP_EFFECT !
						type = text
						id = CUMUL_CAP_EFFECT
						table-column-width = 12
						tid = 21199622126677
					{
						--- TableColumnItem ---
							item-column = CUMUL_CAP_EFFECT
							format = percentTA
							previewValue = value
					}
					--- TableColumn ---
						labels en = "Currency Effect", fr = "Effet sur devise", de = Währungseffekt
						column-name = CUMUL_CURR_EFFECT !
						column-type = domain !
						domainAttribute = CUMUL_CURR_EFFECT !
						type = text
						id = CUMUL_CURR_EFFECT
						table-column-width = 12
						tid = 21213317886043
					{
						--- TableColumnItem ---
							item-column = CUMUL_CURR_EFFECT
							format = percentTA
							previewValue = value
					}
					--- TableColumn ---
						labels en = "Income Effect", fr = "Effet sur revenu", de = Einkommenseffekt
						column-name = CUMUL_INCOME_EFFECT !
						column-type = domain !
						domainAttribute = CUMUL_INCOME_EFFECT !
						type = text
						id = CUMUL_INCOME_EFFECT
						table-column-width = 12
						tid = 21226461646611
					{
						--- TableColumnItem ---
							item-column = CUMUL_INCOME_EFFECT
							format = percentTA
							previewValue = value
					}
					--- TableColumn ---
						labels en = "Fees & Taxes Effect", fr = "Effet sur frais & taxes", de = "Steuern-& Gebühren-Effekt"
						column-name = CUMUL_F_T_EFFECT !
						column-type = domain !
						domainAttribute = CUMUL_F_T_EFFECT !
						type = text
						id = CUMUL_F_T_EFFECT
						table-column-width = 12
						tid = 21236533475567
					{
						--- TableColumnItem ---
							item-column = CUMUL_F_T_EFFECT
							format = percentTA
							previewValue = value
					}
					--- TableColumn ---
						labels en = "Cross Effect", fr = "Effet croisé", de = Kreuzeffekt
						column-name = CUMUL_CROSS_EFFECT !
						column-type = domain !
						domainAttribute = CUMUL_CROSS_EFFECT !
						type = text
						id = CUMUL_CROSS_EFFECT
						table-column-width = 12
						tid = 21247245258517
					{
						--- TableColumnItem ---
							item-column = CUMUL_CROSS_EFFECT
							format = percentTA
							previewValue = value
					}
					--- TableKeepFilter ---
						keep-filter-column-name = FILTER_2
						keep-filter-operand = 1
					--- TableSort ---
						sort-column-name = PTF_HIER_STR
						sort-rank = 2
					--- TableSort ---
						sort-column-name = CUMUL_TOT_RET
						sort-direction = descending
						sort-rank = 1
				}
			}
		}
	}
}