# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSReturn:ReturnAnalysis"
	cssClass = nodeco
	bean-define = DSBean.AAADSReturn.ReturnAnalysis
	bean-name = ReturnAnalysis
	id = OverviewMarketValue_x6_52
	documentation = "This view presents the compounding of the final market value at till date from the initial market value at from date according to the different effects explaining this variation of market value for the period between from date and till date."
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			id = Ri_9E
			indexOfSelectedChild = 0
		{
			--- Tab ---
				labels en = "Market Value & PL", fr = "Valeur de marché & Gains et Pertes", de = "Marktwert mit Gewinn/Verlust"
				id = tab_s05__
				isWidgetSelected = true
				tid = 517026948170795
			{
				--- TableTree ---
					table-filter-layer = true
					id = zD___
					table-column-count = 21 !
					table-columns-width = "4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4" !
				{
					--- TableColumn ---
						column-name = PORTFOLIO_NAME !
						column-type = domain !
						domainAttribute = PORTFOLIO_NAME !
						type = text
						column-locked = true
						column-width = 180
						id = PORTFOLIO_NAME
						table-column-width = 4
					{
						--- TableColumnItem ---
							item-column = PORTFOLIO_NAME
							previewValue = value
					}
					--- TableColumn ---
						labels en = "Initial Market Value", fr = "Valeur d\'inventaire initiale", de = Anfangs-Marktwert
						column-name = InitMktVal
						type = amount
						id = df_1Z
						column-computation = make-amount
						column-computation-parameters = "FROM_DATE_IN_MKT_VAL,REF_CURRENCY"
						table-column-width = 4
						tid = 204181154492260
					{
						--- TableColumnItem ---
							item-column = InitMktVal
							previewValue = value
					}
					--- TableColumn ---
						labels de = Anfangswert, fr = "Valeur d\'inventaire initiale"
						column-name = FROM_DATE_IN_MKT_VAL !
						column-type = domain !
						domainAttribute = FROM_DATE_IN_MKT_VAL !
						type = text
						column-is-part-of-filter = false
						column-visibility = never-visible
						id = FROM_DATE_IN_MKT_VAL
						table-column-width = 4
						tid = 1604015512196478
					{
						--- TableColumnItem ---
							item-column = FROM_DATE_IN_MKT_VAL
							format = decimal
							previewValue = value
					}
					--- TableColumn ---
						labels en = "Profits & Losses", fr = "Gains & pertes", de = Gewinn/Verlust
						column-name = PL
						type = amount
						id = o_CB0
						column-computation = make-amount
						column-computation-parameters = "CUMUL_GAIN_LOSS,REF_CURRENCY"
						table-column-width = 4
						tid = 204181154833924
					{
						--- TableColumnItem ---
							item-column = PL
							previewValue = value
					}
					--- TableColumn ---
						labels de = "Gewinn/Verlust kumul.", fr = "Gains & pertes cumulés"
						column-name = CUMUL_GAIN_LOSS !
						column-type = domain !
						domainAttribute = CUMUL_GAIN_LOSS !
						type = text
						column-visibility = never-visible
						id = CUMUL_GAIN_LOSS
						table-column-width = 4
						tid = 1604015512562186
					{
						--- TableColumnItem ---
							item-column = CUMUL_GAIN_LOSS
							format = decimal
							previewValue = value
					}
					--- TableColumn ---
						labels en = "Realized Capital P&L", fr = "Gains & Pertes sur capital réalisés", de = "Realisierter Kaptial-G/V"
						column-name = RealCapPL
						type = amount
						id = v1_iY
						column-computation = make-amount
						column-computation-parameters = "TOT_REAL_CAP_PL,REF_CURRENCY"
						table-column-width = 4
						tid = 204181155161899
					{
						--- TableColumnItem ---
							item-column = RealCapPL
							previewValue = value
					}
					--- TableColumn ---
						labels de = "Realisierter Kaptial-G/V", fr = "Gains & Pertes sur capital réalisés"
						column-name = TOT_REAL_CAP_PL !
						column-type = domain !
						domainAttribute = TOT_REAL_CAP_PL !
						type = text
						column-visibility = never-visible
						id = TOT_REAL_CAP_PL
						table-column-width = 4
						tid = 1604015512953130
					{
						--- TableColumnItem ---
							item-column = TOT_REAL_CAP_PL
							format = decimal
							previewValue = value
					}
					--- TableColumn ---
						labels en = "Unrealized Capital P&L", fr = "G&P sur capital non réalisés", de = "Nicht realisierter Kapital-G/V"
						column-name = UnRealCapPL
						type = amount
						id = Y48V8
						column-computation = make-amount
						column-computation-parameters = "TOT_UNREAL_CAP_PL,REF_CURRENCY"
						table-column-width = 4
						tid = 204181155482330
					{
						--- TableColumnItem ---
							item-column = UnRealCapPL
							previewValue = value
					}
					--- TableColumn ---
						labels de = "Nicht realisierter Kapital-G/V", fr = "G&P sur capital non réalisés"
						column-name = TOT_UNREAL_CAP_PL !
						column-type = domain !
						domainAttribute = TOT_UNREAL_CAP_PL !
						type = text
						column-visibility = never-visible
						id = TOT_UNREAL_CAP_PL
						table-column-width = 4
						tid = 1604015513343647
					{
						--- TableColumnItem ---
							item-column = TOT_UNREAL_CAP_PL
							format = decimal
							previewValue = value
					}
					--- TableColumn ---
						labels en = "Realized Ccy P&L", fr = "G&P sur devise réalisés", de = "Realisierter Devisen-G/V"
						column-name = RealCurPL
						type = amount
						id = Tr_X_
						column-computation = make-amount
						column-computation-parameters = "TOT_REAL_CURR_PL,REF_CURRENCY"
						table-column-width = 4
						tid = 204181155800248
					{
						--- TableColumnItem ---
							item-column = RealCurPL
							previewValue = value
					}
					--- TableColumn ---
						labels de = "Realisierter Devisen-G/V", fr = "G&P sur devise réalisés"
						column-name = TOT_REAL_CURR_PL !
						column-type = domain !
						domainAttribute = TOT_REAL_CURR_PL !
						type = text
						column-visibility = never-visible
						id = TOT_REAL_CURR_PL
						table-column-width = 4
						tid = 1604015513715771
					{
						--- TableColumnItem ---
							item-column = TOT_REAL_CURR_PL
							format = decimal
							previewValue = value
					}
					--- TableColumn ---
						labels en = "Unrealized Ccy P&L", fr = "G&P sur devise non réalisés", de = "Nicht realisierter Devisen-G/V"
						column-name = UnrealCurPL
						type = amount
						id = B___6
						column-computation = make-amount
						column-computation-parameters = "TOT_UNREAL_CURR_PL,REF_CURRENCY"
						table-column-width = 4
						tid = 205687818569399
					{
						--- TableColumnItem ---
							item-column = UnrealCurPL
							previewValue = value
					}
					--- TableColumn ---
						labels de = "Nicht realisierter Devisen-G/V", fr = "G&P sur devise non réalisés"
						column-name = TOT_UNREAL_CURR_PL !
						column-type = domain !
						domainAttribute = TOT_UNREAL_CURR_PL !
						type = text
						column-visibility = never-visible
						id = TOT_UNREAL_CURR_PL
						table-column-width = 4
						tid = 1604015514102010
					{
						--- TableColumnItem ---
							item-column = TOT_UNREAL_CURR_PL
							format = decimal
							previewValue = value
					}
					--- TableColumn ---
						labels en = "Income Effect", fr = "Effet sur revenu", de = Einkommenseffekt
						column-name = IncomeEffect
						type = amount
						id = iS___
						column-computation = make-amount
						column-computation-parameters = "CUMUL_INCOME_EFFECT_AMOUNT,REF_CURRENCY"
						table-column-width = 4
						tid = 204181156124591
					{
						--- TableColumnItem ---
							item-column = IncomeEffect
							previewValue = value
					}
					--- TableColumn ---
						labels de = "Einkommenseffekt kumul.", fr = "Effet sur revenu cumulé"
						column-name = CUMUL_INCOME_EFFECT_AMOUNT !
						column-type = domain !
						domainAttribute = CUMUL_INCOME_EFFECT_AMOUNT !
						type = text
						column-visibility = never-visible
						id = CUMUL_INCOME_EFFECT_AMOUNT
						table-column-width = 4
						tid = 1604015514628972
					{
						--- TableColumnItem ---
							item-column = CUMUL_INCOME_EFFECT_AMOUNT
							format = decimal
							previewValue = value
					}
					--- TableColumn ---
						labels en = "Fees & Taxes Effect", fr = "Effet sur frais & taxes", de = "Steuern-& Gebühren-Effekt"
						column-name = FtEffect
						type = amount
						id = Od49P
						column-computation = make-amount
						column-computation-parameters = "CUMUL_F_T_EFFECT_AMOUNT,REF_CURRENCY"
						table-column-width = 4
						tid = 204289682156810
					{
						--- TableColumnItem ---
							item-column = FtEffect
							previewValue = value
					}
					--- TableColumn ---
						labels de = "Gebühren-/Steuerneffekt kumul.", fr = "Effet sur frais & taxes cumulé"
						column-name = CUMUL_F_T_EFFECT_AMOUNT !
						column-type = domain !
						domainAttribute = CUMUL_F_T_EFFECT_AMOUNT !
						type = text
						column-visibility = never-visible
						id = CUMUL_F_T_EFFECT_AMOUNT
						table-column-width = 4
						tid = 1604015515032749
					{
						--- TableColumnItem ---
							item-column = CUMUL_F_T_EFFECT_AMOUNT
							format = decimal
							previewValue = value
					}
					--- TableColumn ---
						labels en = Investment/Withdrawal, fr = Apport/retrait, de = Zugänge/Abgänge
						column-name = InvestWithdraw
						type = amount
						id = zw74_
						column-computation = make-amount
						column-computation-parameters = "TOT_INVEST_WITHDRAW,REF_CURRENCY"
						table-column-width = 4
						tid = 204363690433560
					{
						--- TableColumnItem ---
							item-column = InvestWithdraw
							previewValue = value
					}
					--- TableColumn ---
						labels de = Zugänge/Abgänge, fr = Apports/retraits
						column-name = TOT_INVEST_WITHDRAW !
						column-type = domain !
						domainAttribute = TOT_INVEST_WITHDRAW !
						type = text
						column-visibility = never-visible
						id = TOT_INVEST_WITHDRAW
						table-column-width = 4
						tid = 1604015515506672
					{
						--- TableColumnItem ---
							item-column = TOT_INVEST_WITHDRAW
							format = decimal
							previewValue = value
					}
					--- TableColumn ---
						labels en = "Final Market Value", fr = "Valeur d\'inventaire finale", de = End-Marktwert
						column-name = FinalMktVal
						type = amount
						id = f9t5Z
						column-computation = make-amount
						column-computation-parameters = "TILL_DATE_FI_MKT_VAL,REF_CURRENCY"
						table-column-width = 4
						tid = 204443858618343
					{
						--- TableColumnItem ---
							item-column = FinalMktVal
							previewValue = value
					}
					--- TableColumn ---
						labels de = Endwert, fr = "Valeur d\'inventaire finale"
						column-name = TILL_DATE_FI_MKT_VAL !
						column-type = domain !
						domainAttribute = TILL_DATE_FI_MKT_VAL !
						type = text
						column-visibility = never-visible
						id = TILL_DATE_FI_MKT_VAL
						table-column-width = 4
						tid = 1604015515914298
					{
						--- TableColumnItem ---
							item-column = TILL_DATE_FI_MKT_VAL
							format = decimal
							previewValue = value
					}
					--- TableKeepFilter ---
						keep-filter-column-name = FILTER_2
						keep-filter-operand = 1
					--- TableSort ---
						sort-column-name = PTF_HIER_STR
						sort-rank = 3
					--- TableSort ---
						sort-column-name = TILL_DATE_FI_MKT_VAL
						sort-direction = descending
						sort-rank = 2
					--- TableSort ---
						sort-column-name = CUMUL_GAIN_LOSS
						sort-direction = descending
						sort-rank = 1
				}
			}
		}
	}
}