# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSReturn:ReturnAnalysis"
	cssClass = nodeco
	bean-define = DSBean.AAADSReturn.ReturnAnalysis
	bean-name = ReturnAnalysis
	id = PLMonthlyCumul_y_WT0
	documentation = "This view presents by monthly sub-periods between from date and till date, the cumulated indicators values associated to the return, with a special focused on effects in amount compounding the return of the portfolio."
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			table-filter-layer = true
			id = oO1uB
			table-column-count = 9 !
			table-columns-width = "11,11,11,11,11,11,11,11,11" !
		{
			--- TableColumn ---
				labels en = Portfolio, fr = Portefeuille, de = Portfolio
				column-display-grouping = true
				column-name = placeholder_N__1_
				column-type = placeholder !
				type = text
				column-locked = true
				column-sortable = false !
				id = N__1_
				table-column-width = 11
				tid = 987356091360773
			{
				--- TableGroup ---
					group-column-name = PORTFOLIO_CODE
					group-sorting-column-name = PTF_HIER_STR
					group-sorting-direction = ascending
					group-rank = 1
			}
			--- TableColumn ---
				labels de = Hierarchiestruktur, fr = "Structure de la hiérarchie"
				column-name = PTF_HIER_STR !
				column-type = domain !
				domainAttribute = PTF_HIER_STR !
				type = text
				column-visibility = never-visible
				id = PTF_HIER_STR
				table-column-width = 11
				tid = 1604016369882490
			{
				--- TableColumnItem ---
					item-column = PTF_HIER_STR
					previewValue = value
			}
			--- TableColumn ---
				column-name = PERIOD_DENOM !
				column-type = domain !
				domainAttribute = PERIOD_DENOM !
				type = text
				id = PERIOD_DENOM
				table-column-width = 11
			{
				--- TableColumnItem ---
					item-column = PERIOD_DENOM
					previewValue = value
			}
			--- TableColumn ---
				labels de = "Kumul. Rendite per Portfolio", fr = "Rendement cumulé du portefeuille"
				column-name = CUMUL_TOT_RET !
				column-type = domain !
				domainAttribute = CUMUL_TOT_RET !
				type = text
				id = CUMUL_TOT_RET
				table-column-width = 11
				tid = 1604016370468051
			{
				--- TableColumnItem ---
					item-column = CUMUL_TOT_RET
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				labels de = "Akkumul. Rendite Bench.", fr = "Rendement cumulé de l\'Indice"
				column-name = CUMUL_TOT_RET_BENCH !
				column-type = domain !
				domainAttribute = CUMUL_TOT_RET_BENCH !
				type = text
				id = CUMUL_TOT_RET_BENCH
				table-column-width = 11
				tid = 1604016370764467
			{
				--- TableColumnItem ---
					item-column = CUMUL_TOT_RET_BENCH
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Capital Effect", fr = "Effet sur capital", de = Kapitaleffekt
				column-name = CapEffect
				type = amount
				id = TN_L_
				column-computation = make-amount
				column-computation-parameters = "CUMUL_CAP_EFFECT_AMOUNT,REF_CURRENCY"
				table-column-width = 11
				tid = 23199940552500
			{
				--- TableColumnItem ---
					item-column = CapEffect
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Currency Effect", fr = "Effet sur devise", de = Währungseffekt
				column-name = CurEffect
				type = amount
				id = d82nl
				column-computation = make-amount
				column-computation-parameters = "CUMUL_CURR_EFFECT_AMOUNT,REF_CURRENCY"
				table-column-width = 11
				tid = 23199940953109
			{
				--- TableColumnItem ---
					item-column = CurEffect
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Income Effect", fr = "Effet sur revenu", de = Einkommenseffekt
				column-name = IncomeEffect
				type = amount
				id = p48i5
				column-computation = make-amount
				column-computation-parameters = "CUMUL_INCOME_EFFECT_AMOUNT,REF_CURRENCY"
				table-column-width = 11
				tid = 23199941338354
			{
				--- TableColumnItem ---
					item-column = IncomeEffect
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Fees & Taxes Effect", fr = "Effet sur frais & taxes", de = "Steuern-& Gebühren-Effekt"
				column-name = FtEffect
				type = amount
				id = f3F_1
				column-computation = make-amount
				column-computation-parameters = "CUMUL_F_T_EFFECT_AMOUNT,REF_CURRENCY"
				table-column-width = 11
				tid = 23199941723040
			{
				--- TableColumnItem ---
					item-column = FtEffect
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = PERIOD_END_OF
				sort-rank = 1
			--- TableKeepFilter ---
				keep-filter-column-name = FILTER_1
				keep-filter-operand = 1
		}
	}
}