# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSReturn:ReturnAnalysis"
	cssClass = nodeco
	bean-define = DSBean.AAADSReturn.ReturnAnalysis
	bean-name = ReturnAnalysis
	id = PLMonthlyAnalysis_A_D20
	documentation = "This view details for each monthly sub-period between from date and till date the details of PL compounding by effects."
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			table-filter-layer = true
			id = S__78
			table-column-count = 23 !
			table-columns-width = "4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4" !
		{
			--- TableColumn ---
				labels en = Period, fr = Période
				column-display-grouping = true
				column-name = PERIOD_DENOM !
				column-type = domain !
				domainAttribute = PERIOD_DENOM !
				type = text
				column-locked = true
				column-width = 200
				id = PERIOD_DENOM
				table-column-width = 4
				tid = 189138338885528
			{
				--- TableColumnItem ---
					item-column = PERIOD_DENOM
					previewValue = value
				--- TableGroup ---
					group-column-name = PORTFOLIO_NAME
					group-sorting-column-name = PERIOD_FINAL_DATE
					group-sorting-direction = ascending
					group-rank = 2
				{
					Event OnClick (pullModule)
					{
						ref-id = PandLMonthlyGraph
						uri = "<pageflow:continuation/>"
						flow-action = filterGraph ud
						dynamicview = /pmodule/aaa/corda/return/pandlMonthly/Graph ud
						variant = replace ud
						Snippet FilterSet
						id = fs_0bu
						level = 100
						targetDataset = "AAADSReturn:ReturnAnalysisGraph"
						{
							Snippet Filter
							attribute = PORTFOLIO_CODE
							filterValue = "<udp:item column=\"PORTFOLIO_CODE\"/>"
							operator = EQUAL
						}
					}
				}
			}
			--- TableColumn ---
				column-name = PTF_HIER_STR !
				column-type = domain !
				domainAttribute = PTF_HIER_STR !
				type = text
				column-visibility = never-visible
				id = PTF_HIER_STR
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = PTF_HIER_STR
					previewValue = value
			}
			--- TableColumn ---
				labels en = P&L, fr = G&P, de = G/V
				column-name = PL
				type = amount
				id = Y_Sd_
				column-computation = make-amount
				column-computation-parameters = "PERIOD_GAIN_LOSS,REF_CURRENCY"
				table-column-width = 4
				tid = 22547250016133
			{
				--- TableColumnItem ---
					item-column = PL
					previewValue = value
			}
			--- TableColumn ---
				column-name = PERIOD_GAIN_LOSS !
				column-type = domain !
				domainAttribute = PERIOD_GAIN_LOSS !
				type = text
				column-visibility = never-visible
				id = PERIOD_GAIN_LOSS
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = PERIOD_GAIN_LOSS
					format = decimal
					previewValue = value
			}
			--- TableColumn ---
				labels en = "P&L Cumul", de = "G/V Kumul.", fr = "G & P cumulés"
				column-name = PLCumul
				type = amount
				id = z5_8_
				column-computation = make-amount
				column-computation-parameters = "CUMUL_GAIN_LOSS,REF_CURRENCY"
				table-column-width = 4
				tid = 324682204004978
			{
				--- TableColumnItem ---
					item-column = PLCumul
					previewValue = value
			}
			--- TableColumn ---
				labels de = "Gewinn & Verlust kumuliert", fr = "Gains & pertes cumulés"
				column-name = CUMUL_GAIN_LOSS !
				column-type = domain !
				domainAttribute = CUMUL_GAIN_LOSS !
				type = text
				column-visibility = never-visible
				id = CUMUL_GAIN_LOSS
				table-column-width = 4
				tid = 23366588252696
			{
				--- TableColumnItem ---
					item-column = CUMUL_GAIN_LOSS
					format = decimal
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Capital Effect", fr = "Effet sur capital", de = Kapitaleffekt
				column-name = CapEffect
				type = amount
				id = r19a4
				column-computation = make-amount
				column-computation-parameters = "PERIOD_CAP_EFFECT_AMOUNT,REF_CURRENCY"
				table-column-width = 4
				tid = 22547250391879
			{
				--- TableColumnItem ---
					item-column = CapEffect
					previewValue = value
			}
			--- TableColumn ---
				column-name = PERIOD_CAP_EFFECT_AMOUNT !
				column-type = domain !
				domainAttribute = PERIOD_CAP_EFFECT_AMOUNT !
				type = text
				column-visibility = never-visible
				id = PERIOD_CAP_EFFECT_AMOUNT
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = PERIOD_CAP_EFFECT_AMOUNT
					format = decimal
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Capital Effect Cumul", de = "Kapitaleffekt kumul.", fr = "Effet sur capital cumulé"
				column-name = CapEffectCumul
				type = amount
				id = zR8_2
				column-computation = make-amount
				column-computation-parameters = "CUMUL_CAP_EFFECT_AMOUNT,REF_CURRENCY"
				table-column-width = 4
				tid = 189516375648022
			{
				--- TableColumnItem ---
					item-column = CapEffectCumul
					previewValue = value
			}
			--- TableColumn ---
				labels de = "Kapitaleffekt kumuliert", fr = "Effet sur capital cumulé"
				column-name = CUMUL_CAP_EFFECT_AMOUNT !
				column-type = domain !
				domainAttribute = CUMUL_CAP_EFFECT_AMOUNT !
				type = text
				column-visibility = never-visible
				id = CUMUL_CAP_EFFECT_AMOUNT
				table-column-width = 4
				tid = 26229028492448
			{
				--- TableColumnItem ---
					item-column = CUMUL_CAP_EFFECT_AMOUNT
					format = decimal
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Currency Effect", fr = "Effet sur devise", de = Währungseffekt
				column-name = CurEffect
				type = amount
				id = G__8t
				column-computation = make-amount
				column-computation-parameters = "PERIOD_CURR_EFFECT_AMOUNT,REF_CURRENCY"
				table-column-width = 4
				tid = 22547250743879
			{
				--- TableColumnItem ---
					item-column = CurEffect
					previewValue = value
			}
			--- TableColumn ---
				column-name = PERIOD_CURR_EFFECT_AMOUNT !
				column-type = domain !
				domainAttribute = PERIOD_CURR_EFFECT_AMOUNT !
				type = text
				column-visibility = never-visible
				id = PERIOD_CURR_EFFECT_AMOUNT
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = PERIOD_CURR_EFFECT_AMOUNT
					format = decimal.detailed
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Currency Effect Cumul", de = "Währungseffekt kumul.", fr = "Effet sur devise cumulé"
				column-name = CurEffectCumul
				type = amount
				id = B_tJ_
				column-computation = make-amount
				column-computation-parameters = "CUMUL_CURR_EFFECT_AMOUNT,REF_CURRENCY"
				table-column-width = 4
				tid = 189609742491573
			{
				--- TableColumnItem ---
					item-column = CurEffectCumul
					previewValue = value
			}
			--- TableColumn ---
				column-name = CUMUL_CURR_EFFECT_AMOUNT !
				column-type = domain !
				domainAttribute = CUMUL_CURR_EFFECT_AMOUNT !
				type = text
				column-visibility = never-visible
				id = CUMUL_CURR_EFFECT_AMOUNT
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = CUMUL_CURR_EFFECT_AMOUNT
					format = decimal.detailed
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Income Effect", fr = "Effet sur revenu", de = Einkommenseffekt
				column-name = IncomeEffect
				type = amount
				id = yP_ec
				column-computation = make-amount
				column-computation-parameters = "PERIOD_INCOME_EFFECT_AMOUNT,REF_CURRENCY"
				table-column-width = 4
				tid = 22547251167676
			{
				--- TableColumnItem ---
					item-column = IncomeEffect
					previewValue = value
			}
			--- TableColumn ---
				column-name = PERIOD_INCOME_EFFECT_AMOUNT !
				column-type = domain !
				domainAttribute = PERIOD_INCOME_EFFECT_AMOUNT !
				type = text
				column-visibility = never-visible
				id = PERIOD_INCOME_EFFECT_AMOUNT
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = PERIOD_INCOME_EFFECT_AMOUNT
					format = decimal
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Income Effect Cumul", de = "Einkommenseffekt kumul.", fr = "Effet sur revenu cumulé"
				column-name = IncomeEffectCumul
				type = amount
				id = t__UD
				column-computation = make-amount
				column-computation-parameters = "CUMUL_INCOME_EFFECT_AMOUNT,REF_CURRENCY"
				table-column-width = 4
				tid = 189674724347368
			{
				--- TableColumnItem ---
					item-column = IncomeEffectCumul
					previewValue = value
			}
			--- TableColumn ---
				column-name = CUMUL_INCOME_EFFECT_AMOUNT !
				column-type = domain !
				domainAttribute = CUMUL_INCOME_EFFECT_AMOUNT !
				type = text
				column-visibility = never-visible
				id = CUMUL_INCOME_EFFECT_AMOUNT
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = CUMUL_INCOME_EFFECT_AMOUNT
					format = decimal
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Fees & Taxes Effect", fr = "Effet sur frais & taxes", de = "Steuern-& Gebühren-Effekt"
				column-name = FtEffect
				type = amount
				id = k72__
				column-computation = make-amount
				column-computation-parameters = "PERIOD_F_T_EFFECT_AMOUNT,REF_CURRENCY"
				table-column-width = 4
				tid = 22547251753225
			{
				--- TableColumnItem ---
					item-column = FtEffect
					previewValue = value
			}
			--- TableColumn ---
				column-name = PERIOD_F_T_EFFECT_AMOUNT !
				column-type = domain !
				domainAttribute = PERIOD_F_T_EFFECT_AMOUNT !
				type = text
				column-visibility = never-visible
				id = PERIOD_F_T_EFFECT_AMOUNT
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = PERIOD_F_T_EFFECT_AMOUNT
					format = decimal
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Fees & Taxes Effect Cumul", de = "Gebühren-/Steuereffekt kumul.", fr = "Effet sur frais & taxes cumulé"
				column-name = FtEffectCumul
				type = amount
				id = x38F2
				column-computation = make-amount
				column-computation-parameters = "CUMUL_F_T_EFFECT_AMOUNT,REF_CURRENCY"
				table-column-width = 4
				tid = 189733070957062
			{
				--- TableColumnItem ---
					item-column = FtEffectCumul
					previewValue = value
			}
			--- TableColumn ---
				column-name = CUMUL_F_T_EFFECT_AMOUNT !
				column-type = domain !
				domainAttribute = CUMUL_F_T_EFFECT_AMOUNT !
				type = text
				column-visibility = never-visible
				id = CUMUL_F_T_EFFECT_AMOUNT
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = CUMUL_F_T_EFFECT_AMOUNT
					format = decimal
					previewValue = value
			}
			--- TableColumn ---
				column-name = PORTFOLIO_CODE !
				column-type = domain !
				domainAttribute = PORTFOLIO_CODE !
				type = text
				column-is-part-of-filter = false
				column-sortable = false
				column-visibility = never-visible
				id = PORTFOLIO_CODE
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = PORTFOLIO_CODE
					previewValue = value
			}
			--- TableKeepFilter ---
				keep-filter-column-name = FILTER_1
				keep-filter-operand = 1
			--- TableAggregate ---
				aggregate-column-name = PL
				aggregate-computation = sum
				aggregate-group-names = PORTFOLIO_NAME
			--- TableAggregate ---
				aggregate-column-name = PERIOD_GAIN_LOSS
				aggregate-computation = sum
				aggregate-group-names = PORTFOLIO_NAME
			--- TableAggregate ---
				aggregate-column-name = PERIOD_CAP_EFFECT_AMOUNT
				aggregate-computation = sum
				aggregate-group-names = PORTFOLIO_NAME
			--- TableAggregate ---
				aggregate-column-name = CapEffect
				aggregate-computation = sum
				aggregate-group-names = PORTFOLIO_NAME
			--- TableAggregate ---
				aggregate-column-name = PERIOD_CURR_EFFECT_AMOUNT
				aggregate-computation = sum
				aggregate-group-names = PORTFOLIO_NAME
			--- TableAggregate ---
				aggregate-column-name = CurEffect
				aggregate-computation = sum
				aggregate-group-names = PORTFOLIO_NAME
			--- TableAggregate ---
				aggregate-column-name = PERIOD_INCOME_EFFECT_AMOUNT
				aggregate-computation = sum
				aggregate-group-names = PORTFOLIO_NAME
			--- TableAggregate ---
				aggregate-column-name = IncomeEffect
				aggregate-computation = sum
				aggregate-group-names = PORTFOLIO_NAME
			--- TableAggregate ---
				aggregate-column-name = PERIOD_F_T_EFFECT_AMOUNT
				aggregate-computation = sum
				aggregate-group-names = PORTFOLIO_NAME
			--- TableAggregate ---
				aggregate-column-name = FtEffect
				aggregate-computation = sum
				aggregate-group-names = PORTFOLIO_NAME
			--- TableExtra ---
				domainAttribute = PERIOD_FINAL_DATE
			--- TableAggregate ---
				aggregate-column-name = PORTFOLIO_CODE
				aggregate-computation = max
				aggregate-group-names = PORTFOLIO_NAME
			--- TableSort ---
				sort-column-name = PTF_HIER_STR
				sort-rank = 2
			--- TableExtra ---
				domainAttribute = PTF_HIER_STR
		}
	}
}