# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSReturn:ReturnAnalysis"
	cssClass = nodeco
	bean-define = DSBean.AAADSReturn.ReturnAnalysis
	bean-name = ReturnAnalysis
	id = ReturnMonthlyAnalysis_H__6_
	documentation = "This view details per monthly sub-periods between from date and till date the main financial indicators associated to return calculation per portfolio and for each month."
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			table-filter-layer = true
			id = j4_6k
			documentation = "This view details per monthly sub-periods between from date and till date the"
			table-column-count = 28 !
			table-columns-width = "3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3" !
			table-filterset-id = fs_S8l
		{
			--- TableColumn ---
				column-display-grouping = true
				column-name = PERIOD_DENOM !
				column-type = domain !
				domainAttribute = PERIOD_DENOM !
				type = text
				column-locked = true
				column-width = 200
				id = PERIOD_DENOM
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = PERIOD_DENOM
					previewValue = value
				--- TableGroup ---
					group-column-name = PORTFOLIO_NAME
					group-sorting-column-name = PERIOD_FINAL_DATE
					group-sorting-direction = ascending
					group-rank = 2
				{
					Event OnClick (pullModule)
					{
						ref-id = ReturnMonthlyGraph
						uri = "<pageflow:continuation/>"
						flow-action = filterGraph ud
						dynamicview = /pmodule/aaa/corda/return/returnMonthly/Graph ud
						variant = replace ud
						Snippet FilterSet
						id = fs_9c6
						level = 100
						targetDataset = "AAADSReturn:ReturnAnalysisGraph"
						{
							Snippet Filter
							attribute = PORTFOLIO_CODE
							filterValue = "<udp:item column=\"PORTFOLIO_CODE\"/>"
							operator = EQUAL
						}
					}
				}
			}
			--- TableColumn ---
				labels de = Hierarchiestruktur, fr = "Structure de la hiérarchie"
				column-name = PTF_HIER_STR !
				column-type = domain !
				domainAttribute = PTF_HIER_STR !
				type = text
				column-visibility = never-visible
				id = PTF_HIER_STR
				table-column-width = 3
				tid = 1604016130823049
			{
				--- TableColumnItem ---
					item-column = PTF_HIER_STR
					previewValue = value
			}
			--- TableColumn ---
				labels de = "Rendite Portfolio", fr = "Rendement du portefeuille"
				column-name = PERIOD_TOT_RET !
				column-type = domain !
				domainAttribute = PERIOD_TOT_RET !
				type = text
				column-width = 80
				id = PERIOD_TOT_RET
				table-column-width = 3
				tid = 1604016131160955
			{
				--- TableColumnItem ---
					item-column = PERIOD_TOT_RET
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				labels de = Kapitaleffekt, fr = "Effet sur capital"
				column-name = PERIOD_CAP_EFFECT !
				column-type = domain !
				domainAttribute = PERIOD_CAP_EFFECT !
				type = text
				column-visibility = not-visible
				id = PERIOD_CAP_EFFECT
				table-column-width = 3
				tid = 1604016131470203
			{
				--- TableColumnItem ---
					item-column = PERIOD_CAP_EFFECT
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = PERIOD_CURR_EFFECT !
				column-type = domain !
				domainAttribute = PERIOD_CURR_EFFECT !
				type = text
				column-visibility = not-visible
				id = PERIOD_CURR_EFFECT
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = PERIOD_CURR_EFFECT
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = PERIOD_INCOME_EFFECT !
				column-type = domain !
				domainAttribute = PERIOD_INCOME_EFFECT !
				type = text
				column-visibility = not-visible
				id = PERIOD_INCOME_EFFECT
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = PERIOD_INCOME_EFFECT
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				labels de = "Steuern-& Gebühren-Effekt", fr = "Effet sur frais & taxes"
				column-name = PERIOD_F_T_EFFECT !
				column-type = domain !
				domainAttribute = PERIOD_F_T_EFFECT !
				type = text
				column-visibility = not-visible
				id = PERIOD_F_T_EFFECT
				table-column-width = 3
				tid = 1604016132408640
			{
				--- TableColumnItem ---
					item-column = PERIOD_F_T_EFFECT
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				labels de = Kreuzeffekt, fr = "Effet croisé"
				column-name = PERIOD_CROSS_EFFECT !
				column-type = domain !
				domainAttribute = PERIOD_CROSS_EFFECT !
				type = text
				column-visibility = not-visible
				id = PERIOD_CROSS_EFFECT
				table-column-width = 3
				tid = 1604016132715749
			{
				--- TableColumnItem ---
					item-column = PERIOD_CROSS_EFFECT
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Portfolio Return Cumul", de = "Kumul. Rendite per Portfolio", fr = "Rendement cumulé du portefeuille"
				column-name = CUMUL_TOT_RET !
				column-type = domain !
				domainAttribute = CUMUL_TOT_RET !
				type = text
				column-width = 80
				id = CUMUL_TOT_RET
				table-column-width = 3
				tid = 189027864420198
			{
				--- TableColumnItem ---
					item-column = CUMUL_TOT_RET
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				labels de = "Kapitaleffekt kumul.", fr = "Effet sur capital cumulé"
				column-name = CUMUL_CAP_EFFECT !
				column-type = domain !
				domainAttribute = CUMUL_CAP_EFFECT !
				type = text
				column-visibility = not-visible
				id = CUMUL_CAP_EFFECT
				table-column-width = 3
				tid = 1604016133225174
			{
				--- TableColumnItem ---
					item-column = CUMUL_CAP_EFFECT
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				labels de = "Deviseneffekt kumul.", fr = "Effet sur devise cumulé"
				column-name = CUMUL_CURR_EFFECT !
				column-type = domain !
				domainAttribute = CUMUL_CURR_EFFECT !
				type = text
				column-visibility = not-visible
				id = CUMUL_CURR_EFFECT
				table-column-width = 3
				tid = 1604016133513464
			{
				--- TableColumnItem ---
					item-column = CUMUL_CURR_EFFECT
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				labels de = "Einkommenseffekt kumul.", fr = "Effet sur revenu cumulé"
				column-name = CUMUL_INCOME_EFFECT !
				column-type = domain !
				domainAttribute = CUMUL_INCOME_EFFECT !
				type = text
				column-visibility = not-visible
				id = CUMUL_INCOME_EFFECT
				table-column-width = 3
				tid = 1604016133800470
			{
				--- TableColumnItem ---
					item-column = CUMUL_INCOME_EFFECT
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				labels de = "Gebühren-/Steuereffekt kumul.", fr = "Effet sur frais & taxes cumulé"
				column-name = CUMUL_F_T_EFFECT !
				column-type = domain !
				domainAttribute = CUMUL_F_T_EFFECT !
				type = text
				column-visibility = not-visible
				id = CUMUL_F_T_EFFECT
				table-column-width = 3
				tid = 1604016134086193
			{
				--- TableColumnItem ---
					item-column = CUMUL_F_T_EFFECT
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				labels de = "Kreuzeffekt kumul.", fr = "Effet croisé cumulé"
				column-name = CUMUL_CROSS_EFFECT !
				column-type = domain !
				domainAttribute = CUMUL_CROSS_EFFECT !
				type = text
				column-visibility = not-visible
				id = CUMUL_CROSS_EFFECT
				table-column-width = 3
				tid = 1604016134394158
			{
				--- TableColumnItem ---
					item-column = CUMUL_CROSS_EFFECT
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				labels de = "Rendite Benchmark"
				column-name = PERIOD_TOT_RET_BENCH !
				column-type = domain !
				domainAttribute = PERIOD_TOT_RET_BENCH !
				type = text
				column-width = 80
				id = PERIOD_TOT_RET_BENCH
				table-column-width = 3
				tid = 1604016134701695
			{
				--- TableColumnItem ---
					item-column = PERIOD_TOT_RET_BENCH
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Benchmark Return Cumul", de = "Akkumul. Rendite Bench.", fr = "Rendement cumulé de l\'Indice"
				column-name = CUMUL_TOT_RET_BENCH !
				column-type = domain !
				domainAttribute = CUMUL_TOT_RET_BENCH !
				type = text
				column-width = 80
				id = CUMUL_TOT_RET_BENCH
				table-column-width = 3
				tid = 189038036999953
			{
				--- TableColumnItem ---
					item-column = CUMUL_TOT_RET_BENCH
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Initial Market Value", fr = "Valeur d\'inventaire initiale", de = Anfangs-Marktwert
				column-name = InitialMktValue
				type = amount
				id = L____
				column-computation = make-amount
				column-computation-parameters = "PERIOD_INITIAL_MKT_VAL,REF_CURRENCY"
				table-column-width = 3
				tid = 23336616366046
			{
				--- TableColumnItem ---
					item-column = InitialMktValue
					previewValue = value
			}
			--- TableColumn ---
				labels de = Anfangswert, fr = "Valeur d\'inventaire initiale"
				column-name = PERIOD_INITIAL_MKT_VAL !
				column-type = domain !
				domainAttribute = PERIOD_INITIAL_MKT_VAL !
				type = text
				column-visibility = never-visible
				id = PERIOD_INITIAL_MKT_VAL
				table-column-width = 3
				tid = 1604016135217108
			{
				--- TableColumnItem ---
					item-column = PERIOD_INITIAL_MKT_VAL
					format = decimal
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Final Market Value", fr = "Valeur d\'inventaire finale", de = End-Marktwert
				column-name = FinalMktValue
				type = amount
				id = a_JzR
				column-computation = make-amount
				column-computation-parameters = "PERIOD_FINAL_MKT_VAL,REF_CURRENCY"
				table-column-width = 3
				tid = 23336625969222
			{
				--- TableColumnItem ---
					item-column = FinalMktValue
					previewValue = value
			}
			--- TableColumn ---
				labels de = Endwert, fr = "Valeur d\'inventaire finale"
				column-name = PERIOD_FINAL_MKT_VAL !
				column-type = domain !
				domainAttribute = PERIOD_FINAL_MKT_VAL !
				type = text
				column-visibility = never-visible
				id = PERIOD_FINAL_MKT_VAL
				table-column-width = 3
				tid = 1604016135572551
			{
				--- TableColumnItem ---
					item-column = PERIOD_FINAL_MKT_VAL
					format = decimal
					previewValue = value
			}
			--- TableColumn ---
				labels en = Investment/Withdrawal, fr = Apport/retrait, de = Zugänge/Abgänge
				column-name = InvestWithdraw
				type = amount
				id = M942_
				column-computation = make-amount
				column-computation-parameters = "PERIOD_INVEST_WITHDRAWAL,REF_CURRENCY"
				table-column-width = 3
				tid = 23336634413032
			{
				--- TableColumnItem ---
					item-column = InvestWithdraw
					previewValue = value
			}
			--- TableColumn ---
				labels de = Zugänge/Abgänge, fr = Apports/retraits
				column-name = PERIOD_INVEST_WITHDRAWAL !
				column-type = domain !
				domainAttribute = PERIOD_INVEST_WITHDRAWAL !
				type = text
				column-visibility = never-visible
				id = PERIOD_INVEST_WITHDRAWAL
				table-column-width = 3
				tid = 1604016135913451
			{
				--- TableColumnItem ---
					item-column = PERIOD_INVEST_WITHDRAWAL
					format = decimal
					previewValue = value
			}
			--- TableColumn ---
				labels en = P&L, fr = G&P, de = G/V
				column-name = PL
				type = amount
				id = K52_4
				column-computation = make-amount
				column-computation-parameters = "PERIOD_GAIN_LOSS,REF_CURRENCY"
				table-column-width = 3
				tid = 23336643460551
			{
				--- TableColumnItem ---
					item-column = PL
					previewValue = value
			}
			--- TableColumn ---
				labels en = "P&L Cumul", fr = "G & P cumulés", de = "G/V Kumul."
				column-name = PLCumul
				type = amount
				id = PqGxk
				column-computation = make-amount
				column-computation-parameters = "CUMUL_GAIN_LOSS,REF_CURRENCY"
				table-column-width = 3
				tid = 404089299847326
			{
				--- TableColumnItem ---
					item-column = PLCumul
					previewValue = value
			}
			--- TableColumn ---
				labels de = Gewinn/Verlust, fr = "Gains & pertes"
				column-name = PERIOD_GAIN_LOSS !
				column-type = domain !
				domainAttribute = PERIOD_GAIN_LOSS !
				type = text
				column-visibility = never-visible
				id = PERIOD_GAIN_LOSS
				table-column-width = 3
				tid = 1604016136357862
			{
				--- TableColumnItem ---
					item-column = PERIOD_GAIN_LOSS
					format = decimal
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Mean Cap", fr = "Capital moyen", de = "Durchschn. Investitionskapital"
				column-name = MeanCap
				type = amount
				id = S4__w
				column-computation = make-amount
				column-computation-parameters = "MEAN_CAP,REF_CURRENCY"
				table-column-width = 3
				tid = 23336652017225
			{
				--- TableColumnItem ---
					item-column = MeanCap
					previewValue = value
			}
			--- TableColumn ---
				labels de = "Durchschn. Kapital", fr = "Capital moyen"
				column-name = MEAN_CAP !
				column-type = domain !
				domainAttribute = MEAN_CAP !
				type = text
				column-visibility = never-visible
				id = MEAN_CAP
				table-column-width = 3
				tid = 1604016136726992
			{
				--- TableColumnItem ---
					item-column = MEAN_CAP
					format = decimal
					previewValue = value
			}
			--- TableColumn ---
				column-name = PORTFOLIO_CODE !
				column-type = domain !
				domainAttribute = PORTFOLIO_CODE !
				type = text
				column-is-part-of-filter = false
				column-sortable = false
				column-visibility = never-visible
				id = PORTFOLIO_CODE
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = PORTFOLIO_CODE
					previewValue = value
			}
			--- TableKeepFilter ---
				keep-filter-column-name = FILTER_1
				keep-filter-operand = 1
			--- TableAggregate ---
				aggregate-column-name = PL
				aggregate-computation = sum
				aggregate-group-names = PORTFOLIO_NAME
			--- TableAggregate ---
				aggregate-column-name = PERIOD_GAIN_LOSS
				aggregate-computation = sum
				aggregate-group-names = PORTFOLIO_NAME
			--- TableAggregate ---
				aggregate-column-name = InvestWithdraw
				aggregate-computation = sum
				aggregate-group-names = PORTFOLIO_NAME
			--- TableAggregate ---
				aggregate-column-name = PERIOD_INVEST_WITHDRAWAL
				aggregate-computation = sum
				aggregate-group-names = PORTFOLIO_NAME
			--- TableAggregate ---
				aggregate-column-name = PORTFOLIO_CODE
				aggregate-computation = max
				aggregate-group-names = PORTFOLIO_NAME
			--- TableSort ---
				sort-column-name = PTF_HIER_STR
				sort-rank = 3
			--- TableExtra ---
				domainAttribute = PERIOD_FINAL_DATE
			--- TableExtra ---
				domainAttribute = PTF_HIER_STR
		}
	}
}