# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSReturn:ReturnAnalysis"
	cssClass = nodeco
	bean-define = DSBean.AAADSReturn.ReturnAnalysis
	bean-name = ReturnAnalysis
	id = ReturnMonthlyCumul_GTMVU
	documentation = "This details per monthly sub-periods between from date and till date the cumulated return value and the financial amount associated to each sub-period."
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			id = G15__
			table-column-count = 13 !
			table-columns-width = "7,7,7,7,7,7,7,7,7,7,7,7,7" !
		{
			--- TableColumn ---
				labels en = Portfolio, fr = Portefeuille, de = Portfolio
				column-display-grouping = true
				column-name = placeholder_t_Rt_
				column-type = placeholder !
				type = text
				column-locked = true
				column-sortable = false !
				id = t_Rt_
				table-column-width = 7
				tid = 987330131213604
			{
				--- TableGroup ---
					group-column-name = PORTFOLIO_CODE
					group-sorting-column-name = PTF_HIER_STR
					group-sorting-direction = ascending
					group-rank = 1
			}
			--- TableColumn ---
				labels de = Hierarchiestruktur, fr = "Structure de la hiérarchie"
				column-name = PTF_HIER_STR !
				column-type = domain !
				domainAttribute = PTF_HIER_STR !
				type = text
				column-visibility = never-visible
				id = PTF_HIER_STR
				table-column-width = 7
				tid = 1604014934916329
			{
				--- TableColumnItem ---
					item-column = PTF_HIER_STR
					previewValue = value
			}
			--- TableColumn ---
				column-name = PERIOD_DENOM !
				column-type = domain !
				domainAttribute = PERIOD_DENOM !
				type = text
				id = PERIOD_DENOM
				table-column-width = 7
			{
				--- TableColumnItem ---
					item-column = PERIOD_DENOM
					previewValue = value
			}
			--- TableColumn ---
				labels de = "Kumul. Rendite per Portfolio", fr = "Rendement cumulé du portefeuille"
				column-name = CUMUL_TOT_RET !
				column-type = domain !
				domainAttribute = CUMUL_TOT_RET !
				type = text
				id = CUMUL_TOT_RET
				table-column-width = 7
				tid = 1604014935652023
			{
				--- TableColumnItem ---
					item-column = CUMUL_TOT_RET
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				labels de = "Akkumul. Rendite Bench.", fr = "Rendement cumulé de l\'Indice"
				column-name = CUMUL_TOT_RET_BENCH !
				column-type = domain !
				domainAttribute = CUMUL_TOT_RET_BENCH !
				type = text
				id = CUMUL_TOT_RET_BENCH
				table-column-width = 7
				tid = 1604014935959560
			{
				--- TableColumnItem ---
					item-column = CUMUL_TOT_RET_BENCH
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Initial Market Value", fr = "Valeur d\'inventaire initiale", de = Anfangs-Marktwert
				column-name = InitialMktValue
				type = amount
				id = w_i__
				column-computation = make-amount
				column-computation-parameters = "PERIOD_INITIAL_MKT_VAL,REF_CURRENCY"
				table-column-width = 7
				tid = 22538409296153
			{
				--- TableColumnItem ---
					item-column = InitialMktValue
					previewValue = value
			}
			--- TableColumn ---
				labels de = Anfangswert, fr = "Valeur d\'inventaire initiale"
				column-name = PERIOD_INITIAL_MKT_VAL !
				column-type = domain !
				domainAttribute = PERIOD_INITIAL_MKT_VAL !
				type = text
				column-visibility = never-visible
				id = PERIOD_INITIAL_MKT_VAL
				table-column-width = 7
				tid = 1604014936341522
			{
				--- TableColumnItem ---
					item-column = PERIOD_INITIAL_MKT_VAL
					format = decimal
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Final Market Value", fr = "Valeur d\'inventaire finale", de = End-Marktwert
				column-name = FinalMktValue
				type = amount
				id = hm_Ve
				column-computation = make-amount
				column-computation-parameters = "PERIOD_FINAL_MKT_VAL,REF_CURRENCY"
				table-column-width = 7
				tid = 22538417991951
			{
				--- TableColumnItem ---
					item-column = FinalMktValue
					previewValue = value
			}
			--- TableColumn ---
				labels de = Endwert, fr = "Valeur d\'inventaire finale"
				column-name = PERIOD_FINAL_MKT_VAL !
				column-type = domain !
				domainAttribute = PERIOD_FINAL_MKT_VAL !
				type = text
				column-visibility = never-visible
				id = PERIOD_FINAL_MKT_VAL
				table-column-width = 7
				tid = 1604014936714502
			{
				--- TableColumnItem ---
					item-column = PERIOD_FINAL_MKT_VAL
					format = decimal
					previewValue = value
			}
			--- TableColumn ---
				labels en = Investment/Withdrawal, fr = Apport/retrait, de = Zugänge/Abgänge
				column-name = InvestWithdraw
				type = amount
				id = s3a90
				column-computation = make-amount
				column-computation-parameters = "PERIOD_INVEST_WITHDRAWAL,REF_CURRENCY"
				table-column-width = 7
				tid = 22538431230784
			{
				--- TableColumnItem ---
					item-column = InvestWithdraw
					previewValue = value
			}
			--- TableColumn ---
				labels de = Zugänge/Abgänge, fr = Apports/retraits
				column-name = PERIOD_INVEST_WITHDRAWAL !
				column-type = domain !
				domainAttribute = PERIOD_INVEST_WITHDRAWAL !
				type = text
				column-visibility = never-visible
				id = PERIOD_INVEST_WITHDRAWAL
				table-column-width = 7
				tid = 1604014937148219
			{
				--- TableColumnItem ---
					item-column = PERIOD_INVEST_WITHDRAWAL
					format = decimal
					previewValue = value
			}
			--- TableColumn ---
				labels en = P&L, fr = G&P, de = G/V
				column-name = PL
				type = amount
				id = H_u_8
				column-computation = make-amount
				column-computation-parameters = "PERIOD_GAIN_LOSS,REF_CURRENCY"
				table-column-width = 7
				tid = 22538439780195
			{
				--- TableColumnItem ---
					item-column = PL
					previewValue = value
			}
			--- TableColumn ---
				labels de = Gewinn/Verlust, fr = "Gains & pertes"
				column-name = PERIOD_GAIN_LOSS !
				column-type = domain !
				domainAttribute = PERIOD_GAIN_LOSS !
				type = text
				column-visibility = never-visible
				id = PERIOD_GAIN_LOSS
				table-column-width = 7
				tid = 1604014937549857
			{
				--- TableColumnItem ---
					item-column = PERIOD_GAIN_LOSS
					format = decimal
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = PERIOD_END_OF
				sort-rank = 1
			--- TableKeepFilter ---
				keep-filter-column-name = FILTER_1
				keep-filter-operand = 1
			--- TableAggregate ---
				aggregate-column-name = PERIOD_GAIN_LOSS
				aggregate-computation = sum
				aggregate-group-names = PORTFOLIO_CODE
			--- TableAggregate ---
				aggregate-column-name = PL
				aggregate-computation = sum
				aggregate-group-names = PORTFOLIO_CODE
			--- TableAggregate ---
				aggregate-column-name = PERIOD_INVEST_WITHDRAWAL
				aggregate-computation = sum
				aggregate-group-names = PORTFOLIO_CODE
			--- TableAggregate ---
				aggregate-column-name = InvestWithdraw
				aggregate-computation = sum
				aggregate-group-names = PORTFOLIO_CODE
		}
	}
}