# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels fr = Contexte, en = Context, de = Kontext
	domainEntity = "AAADSDomain:DomainContext"
	collapsible = true
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = CopyOfContext_v_23Y
	documentation = "Domain Context"
	tid = 88174416030142
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TabbedPane ---
			id = I_N_0
			indexOfSelectedChild = 0
		{
			--- Tab ---
				labels fr = Base, en = Basic, de = Einfach
				id = tab_me1c2
				isWidgetSelected = true
				tid = 88174431674136
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 6
					gridColumnsWidth = "27,16,13,16,14,14" !
					gridRowCount = 1
					verticalAlignment = lead
				{
					--- GridCell ---
						gridColumnWidth = 27
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainPortfolioDimension.fragment
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainInstrumentDimension.fragment
					}
					--- GridCell ---
						gridColumnWidth = 13
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainPivotDate.fragment
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainRefCurrency.fragment
					}
					--- GridCell ---
						gridColumnWidth = 14
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainHierarchyIdentifier.fragment
					}
					--- GridCell ---
						gridColumnWidth = 14
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainConsolidationIdentifier.fragment
					}
				}
			}
			--- Tab ---
				labels fr = Avancé, en = Advanced, de = Erweitert
				id = tab_eR_GS
				isWidgetVisible = false
				tid = 88174432568934
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 7
					gridColumnsWidth = "14,14,14,14,14,14,14" !
					gridRowCount = 1
				{
					--- GridCell ---
						gridColumnWidth = 14
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainMinStatus.fragment
					}
					--- GridCell ---
						gridColumnWidth = 14
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainMaxStatus.fragment
					}
					--- GridCell ---
						gridColumnWidth = 14
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainZeroQtyF.fragment
					}
					--- GridCell ---
						gridColumnWidth = 14
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainStatusFus.fragment
					}
					--- GridCell ---
						gridColumnWidth = 14
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainPosLogicalE.fragment
					}
					--- GridCell ---
						gridColumnWidth = 14
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainClosePosF.fragment
					}
					--- GridCell ---
						gridColumnWidth = 14
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainFundSplit.fragment
					}
				}
			}
		}
		--- Grid ---
			cssClass = blank
			gridColumnCount = 4
			gridColumnsWidth = "25,25,25,25" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Button ---
					labels en = Execute, de = Ausführen, fr = Exécuter
					id = btn_w_6j7
					tid = 88174435548457
				{
					Event OnClick (submit)
					{
						method = get
						call-URI = "<pageflow:continuation/>"
						widget-group-ref = form
						param = "flow-action=execute"
						only-changed = true
						prevalidate = false
						modal = false
					}
				}
				--- Button ---
					labels en = Refresh, de = Aktualisieren, fr = Acutaliser
					id = btn_ut8_8
					tid = 88174438587434
				{
					Event OnClick (submit)
					{
						method = get
						call-URI = "<pageflow:continuation/>"
						widget-group-ref = form
						param = "flow-action=execute,DSAction=refresh"
						only-changed = true
						prevalidate = false
						modal = false
					}
				}
				--- Button ---
					labels en = Default, de = Standard, fr = Défaut
					id = btn_OB_1A
					tid = 88174453131322
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = reset ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
		}
	}
}