# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = Context, fr = Contexte, de = Kontext
	domainEntity = "AAADSDomain:DomainContext"
	collapsible = true
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = Context_K_710
	tid = 65417448073987
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 7
			gridColumnsWidth = "20,20,12,12,12,12,12" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 20
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainPortfolioDimension.fragment
			}
			--- GridCell ---
				gridColumnWidth = 20
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainInstrumentDimension.fragment
			}
			--- GridCell ---
				gridColumnWidth = 12
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainFromDate.fragment
			}
			--- GridCell ---
				gridColumnWidth = 12
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainPivotDateTill.fragment
			}
			--- GridCell ---
				gridColumnWidth = 12
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainHierarchyIdentifier.fragment
			}
			--- GridCell ---
				gridColumnWidth = 12
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainMinStatus.fragment
			}
			--- GridCell ---
				gridColumnWidth = 12
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainMaxStatus.fragment
			}
		}
		--- Grid ---
			cssClass = blank
			gridColumnCount = 4
			gridColumnsWidth = "25,25,25,25" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Button ---
					labels en = Refresh, de = Aktualisieren, fr = Actualiser
					id = btn_Us168
					tid = 612368203777801
				{
					Event OnClick (submit)
					{
						method = get
						call-URI = "<pageflow:continuation/>"
						widget-group-ref = form
						param = "flow-action=refresh"
						only-changed = true
						prevalidate = false
						modal = false
					}
				}
				--- Button ---
					labels en = "Default Settings", de = Standardeinstellung, fr = "Valeurs par défaut"
					id = btn_P2b_1
					tid = 473799567922459
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = reset ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
		}
	}
}