# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Search Strategy", fr = "Recherche de stratégie", de = "Strategie Suche"
	containment = container
	search = container !
	cssClass = nodeco
	id = InvestProfileSearch_L_RhI
	tid = 1888966473591755
{
	--- Box ---
		boxType = vertical
	{
		--- Box ---
			boxType = vertical
		{
			--- Include ---
				includeSrc = "" !
				resource:///Default/module/aaa/administration/strategy/search/StrategySearchInput.module
			--- Include ---
				includeSrc = "" !
				resource:///Default/module/aaa/administration/strategy/search/StrategyListAllocation.module
		}
	}
}