# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Search Recommendation List", fr = "Recherche de liste de recommendation", de = "Empfehlungsliste Suche"
	containment = container
	search = container !
	cssClass = nodeco
	id = ListRecomSearch_MW5_L
	tid = 89788996577355
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/strategy/search/StrategySearchInput.module
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/strategy/search/StrategyListRecomList.module
	}
}