# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Search Strategy", fr = "Recherche de stratégie", de = "Strategie Suche"
	containment = container
	search = container !
	cssClass = nodeco
	id = StrategySearchForStrategyLink_AA_C9
	tid = 122909734209444
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			id = Y8h__
			indexOfSelectedChild = 4
		{
			--- Tab ---
				labels en = All, fr = Tous, de = Alle
				id = tab_D_g_0
				isWidgetVisible = false
				tid = 122909736629193
			{
				Event OnClick (setTabActive) Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = changeTab ud
					modal = false
					only-changed = false
					prevalidate = false
					Snippet Query
					queryAttributes = "currencySearchCode,extDenomination,gridSearchCode,searchCode,marketSegmentName,name,typeCode,code,natureE"
					queryOutputModule = "" !
					resource:///Default/module/aaa/administration/strategy/search/StrategySearch.module
					Snippet FilterSet
					id = fs_387
					level = 2
					targetDataset = "AAADSStrategy:StrategySearchCriteria"
					{
						Snippet Filter
						attribute = natureE
						editMode = editable
						filterValue = "RecommendationList,InvestmentProfile,ModelPortfolio,AssetAllocation"
						operator = IN
					}
				}
				--- Box ---
					boxType = vertical
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/strategy/search/StrategySearchInput.module
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/strategy/search/StrategyListAll.module
				}
			}
			--- Tab ---
				labels en = "Asset Allocation", fr = "Allocation d\'actif", de = Allokation
				id = tab_h6_zk
				isWidgetVisible = false
				tid = 122909738590220
			{
				Event OnClick (setTabActive) Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = changeTab ud
					modal = false
					only-changed = false
					prevalidate = false
					Snippet Query
					queryAttributes = "currencySearchCode,extDenomination,gridSearchCode,searchCode,marketSegmentName,name,code"
					queryOutputModule = "" !
					resource:///Default/module/aaa/administration/strategy/search/StrategySearch.module
					Snippet FilterSet
					id = fs_387
					level = 2
					targetDataset = "AAADSStrategy:StrategySearchCriteria"
					{
						Snippet Filter
						attribute = natureE
						filterValue = AssetAllocation
						operator = EQUAL
					}
				}
				--- Box ---
					boxType = vertical
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/strategy/search/StrategySearchInput.module
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/strategy/search/StrategyListAllocation.module
				}
			}
			--- Tab ---
				labels en = "Model Portfolio", fr = "Portefeuille modèle", de = Modellportfolio
				id = tab_r741_
				isWidgetVisible = false
				tid = 122909740548658
			{
				Event OnClick (setTabActive) Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = changeTab ud
					modal = false
					only-changed = false
					prevalidate = false
					Snippet Query
					queryAttributes = "currencySearchCode,extDenomination,gridSearchCode,searchCode,marketSegmentName,name,typeCode,code"
					queryOutputModule = "" !
					resource:///Default/module/aaa/administration/strategy/search/StrategySearch.module
					Snippet FilterSet
					id = fs_387
					level = 2
					targetDataset = "AAADSStrategy:StrategySearchCriteria"
					{
						Snippet Filter
						attribute = natureE
						filterValue = ModelPortfolio
						operator = EQUAL
					}
				}
				--- Box ---
					boxType = vertical
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/strategy/search/StrategySearchInput.module
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/strategy/search/StrategyListModelPtf.module
				}
			}
			--- Tab ---
				labels en = "Recommendation List", fr = "Liste de recommandation", de = Empfehlungsliste
				id = tab_H_K2U
				isWidgetVisible = false
				tid = 122909742489797
			{
				Event OnClick (setTabActive) Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = changeTab ud
					modal = false
					only-changed = false
					prevalidate = false
					Snippet Query
					queryAttributes = "currencySearchCode,extDenomination,gridSearchCode,marketSegmentName,searchCode,name,typeCode,code"
					queryOutputModule = "" !
					resource:///Default/module/aaa/administration/strategy/search/StrategySearch.module
					Snippet FilterSet
					id = fs_387
					level = 2
					targetDataset = "AAADSStrategy:StrategySearchCriteria"
					{
						Snippet Filter
						attribute = natureE
						filterValue = RecommendationList
						operator = EQUAL
					}
				}
				--- Box ---
					boxType = vertical
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/strategy/search/StrategySearchInput.module
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/strategy/search/StrategyListRecomList.module
				}
			}
			--- Tab ---
				labels en = "Investment Profile", fr = "Profil d\'investissement", de = Investitionsprofil
				id = tab_T5_8P
				isWidgetSelected = true
				tid = 122909744439077
			{
				Event OnClick (setTabActive) Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = changeTab ud
					modal = false
					only-changed = false
					prevalidate = false
					Snippet Query
					queryAttributes = "extDenomination,searchCode,name,code"
					queryOutputModule = "" !
					resource:///Default/module/aaa/administration/strategy/search/StrategySearch.module
					Snippet FilterSet
					id = fs_387
					level = 2
					targetDataset = "AAADSStrategy:StrategySearchCriteria"
					{
						Snippet Filter
						attribute = natureE
						filterValue = InvestmentProfile
						operator = EQUAL
					}
				}
				--- Box ---
					boxType = vertical
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/strategy/search/StrategySearchInput.module
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/strategy/search/StrategyListInvestProfile.module
				}
			}
		}
	}
}