# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Search Results", fr = "Résultats de la recherche", de = Suchergebnisse
	domainEntity = "AAADSStrategy:StrategyList"
	search = output !
	bean-define = DSBean.AAADSStrategy.StrategyList
	bean-name = StrategyList
	id = StrategyListAll_qb9_7
	tid = 352209942677744
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			id = S_I_9
			table-column-count = 9 !
			table-columns-width = "11,11,11,11,11,11,11,11,11" !
		{
			--- TableColumn ---
				labels de = Code
				column-name = code !
				column-type = domain !
				domainAttribute = code !
				type = text
				column-locked = true
				id = code
				table-column-width = 11
				tid = 19980369179323
			{
				--- Conditional ---
					indexOfSelectedChild = 1
				{
					--- ConditionalBody ---
						javaCode = "com.odcgroup.tsl.wui.search.form.SearchFormHelper.isLookup(objectModel) == false"
						technicalName = NotLookup
						boxType = vertical
						isWidgetVisible = false
					{
						--- TableColumnItem ---
							toolTips en = "Select Strategy", fr = "Sélectionner la stratégie", de = "Strategie auswählen"
							item-column = code
							previewValue = value
							tid = 352498196260001
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = select ud
								Query.beanValue1 = "<udp:item column=\"code\"/>" ud
								modal = false
								only-changed = false
								prevalidate = false
							}
						}
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetSelected = true
					{
						--- TableColumnItem ---
							toolTips en = "Select Strategy", fr = "Sélectionner la stratégie", de = "Strategie auswählen"
							item-column = code
							previewValue = value
							tid = 352531379650240
						{
							Event OnClick (setWidgetValue)
							{
								widget-group-id = "<xsp:expr>com.odcgroup.tsl.wui.search.form.SearchFormHelper.getParentWidgetValue1Id(objectModel)</xsp:expr>"
								value = "<udp:item column=\"code\"/>"
								target = WUI_main
							}
							Event OnClick (winClose)
							{
								target = self
							}
						}
					}
				}
			}
			--- TableColumn ---
				column-name = name !
				column-type = domain !
				domainAttribute = name !
				type = text
				id = name
				table-column-width = 11
			{
				--- Icon ---
					toolTips en = "View Strategy Details", fr = "Voir les détails de la stratégie", de = "Details der Strategie ansehen"
					icon = application_form_magnify
					id = k1_1_
					tid = 14353792011189
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "resource:///administration/strategy/StrategyView.pageflow"
						target = popup
						code = "<udp:item column=\"code\"/>" ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
				--- Spacer ---
					height = 4
					width = 4
				--- TableColumnItem ---
					item-column = name
					previewValue = value
			}
			--- TableColumn ---
				column-name = extDenomination !
				column-type = domain !
				domainAttribute = extDenomination !
				type = text
				id = extDenomination
				table-column-width = 11
			{
				--- TableColumnItem ---
					item-column = extDenomination
					previewValue = value
			}
			--- TableColumn ---
				column-name = natureE !
				column-type = domain !
				domainAttribute = natureE !
				type = text
				id = natureE
				table-column-width = 11
			{
				--- TableColumnItem ---
					item-column = natureE
					previewValue = value
			}
			--- TableColumn ---
				column-name = subNatureE !
				column-type = domain !
				domainAttribute = subNatureE !
				type = text
				id = subNatureE
				table-column-width = 11
			{
				--- TableColumnItem ---
					item-column = subNatureE
					previewValue = value
			}
			--- TableColumn ---
				column-name = typeExtDenomination !
				column-type = domain !
				domainAttribute = typeExtDenomination !
				type = text
				id = typeExtDenomination
				table-column-width = 11
			{
				--- TableColumnItem ---
					item-column = typeExtDenomination
					previewValue = value
			}
			--- TableColumn ---
				column-name = currencyExtDenomination !
				column-type = domain !
				domainAttribute = currencyExtDenomination !
				type = text
				id = currencyExtDenomination
				table-column-width = 11
			{
				--- TableColumnItem ---
					item-column = currencyExtDenomination
					previewValue = value
			}
			--- TableColumn ---
				column-name = marketSegmentExtDenomination !
				column-type = domain !
				domainAttribute = marketSegmentExtDenomination !
				type = text
				column-visibility = not-visible
				id = marketSegmentExtDenomination
				table-column-width = 11
			{
				--- TableColumnItem ---
					item-column = marketSegmentExtDenomination
					previewValue = value
			}
			--- TableColumn ---
				column-name = gridExtDenomination !
				column-type = domain !
				domainAttribute = gridExtDenomination !
				type = text
				column-visibility = not-visible
				id = gridExtDenomination
				table-column-width = 11
			{
				--- TableColumnItem ---
					item-column = gridExtDenomination
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = name
				sort-rank = 1
		}
	}
}