# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Search Strategy", fr = "Recherche de stratégie", de = "Strategie Suche"
	containment = container
	search = container !
	cssClass = nodeco
	id = StrategySearch_oe687
	tid = 116526108397893
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			id = ou7_9
			indexOfSelectedChild = 2
		{
			--- Tab ---
				labels en = All, fr = Tous, de = Alle
				id = tab_oz__2
				isWidgetVisible = false
				tid = 116592947147000
			{
				Event OnClick (setTabActive) Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = changeTab ud
					modal = false
					only-changed = false
					prevalidate = false
					Snippet Query
					queryAttributes = "currencySearchCode,extDenomination,gridSearchCode,searchCode,marketSegmentName,name,typeCode,code,natureE"
					queryOutputModule = "" !
					resource:///Default/module/aaa/administration/strategy/search/StrategySearch.module
					Snippet FilterSet
					id = fs_387
					level = 2
					targetDataset = "AAADSStrategy:StrategySearchCriteria"
					{
						Snippet Filter
						attribute = natureE
						editMode = editable
						filterValue = "Index,Benchmark,ModelPortfolio,AssetAllocation"
						operator = IN
					}
				}
				--- Box ---
					boxType = vertical
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/strategy/search/StrategySearchInput.module
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/strategy/search/StrategyListAll.module
				}
			}
			--- Tab ---
				labels en = "Asset Allocation", fr = "Allocation d\'actif", de = Allokation
				id = tab_e1CQ1
				isWidgetVisible = false
				tid = 116615418662434
			{
				Event OnClick (setTabActive) Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = changeTab ud
					modal = false
					only-changed = false
					prevalidate = false
					Snippet Query
					queryAttributes = "currencySearchCode,extDenomination,gridSearchCode,searchCode,marketSegmentName,name,code"
					queryOutputModule = "" !
					resource:///Default/module/aaa/administration/strategy/search/StrategySearch.module
					Snippet FilterSet
					id = fs_387
					level = 2
					targetDataset = "AAADSStrategy:StrategySearchCriteria"
					{
						Snippet Filter
						attribute = natureE
						filterValue = AssetAllocation
						operator = EQUAL
					}
				}
				--- Box ---
					boxType = vertical
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/strategy/search/StrategySearchInput.module
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/strategy/search/StrategyListAllocation.module
				}
			}
			--- Tab ---
				labels en = "Model Portfolio", fr = "Portefeuille modèle", de = Modellportfolio
				id = tab_O0_6h
				isWidgetSelected = true
				tid = 116625810426307
			{
				Event OnClick (setTabActive) Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = changeTab ud
					modal = false
					only-changed = false
					prevalidate = false
					Snippet Query
					queryAttributes = "currencySearchCode,extDenomination,gridSearchCode,searchCode,marketSegmentName,name,typeCode,code"
					queryOutputModule = "" !
					resource:///Default/module/aaa/administration/strategy/search/StrategySearch.module
					Snippet FilterSet
					id = fs_387
					level = 2
					targetDataset = "AAADSStrategy:StrategySearchCriteria"
					{
						Snippet Filter
						attribute = natureE
						filterValue = ModelPortfolio
						operator = EQUAL
					}
				}
				--- Box ---
					boxType = vertical
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/strategy/search/StrategySearchInput.module
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/strategy/search/StrategyListModelPtf.module
				}
			}
			--- Tab ---
				labels en = Benchmark, fr = Benchmark, de = Benchmark
				id = tab_H_Z0_
				isWidgetVisible = false
				tid = 116634610007999
			{
				Event OnClick (setTabActive) Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = changeTab ud
					modal = false
					only-changed = false
					prevalidate = false
					Snippet Query
					queryAttributes = "currencySearchCode,extDenomination,searchCode,marketSegmentName,name,code"
					queryOutputModule = "" !
					resource:///Default/module/aaa/administration/strategy/search/StrategySearch.module
					Snippet FilterSet
					id = fs_387
					level = 2
					targetDataset = "AAADSStrategy:StrategySearchCriteria"
					{
						Snippet Filter
						attribute = natureE
						filterValue = Benchmark
						operator = EQUAL
					}
				}
				--- Box ---
					boxType = vertical
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/strategy/search/StrategySearchInput.module
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/strategy/search/StrategyListBenchmark.module
				}
			}
			--- Tab ---
				labels en = Index, fr = Indice, de = Index
				id = tab_V67__
				isWidgetVisible = false
				tid = 116640746627954
			{
				Event OnClick (setTabActive) Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = changeTab ud
					modal = false
					only-changed = false
					prevalidate = false
					Snippet Query
					queryAttributes = "extDenomination,searchCode,name,code"
					queryOutputModule = "" !
					resource:///Default/module/aaa/administration/strategy/search/StrategySearch.module
					Snippet FilterSet
					id = fs_387
					level = 2
					targetDataset = "AAADSStrategy:StrategySearchCriteria"
					{
						Snippet Filter
						attribute = natureE
						filterValue = Index
						operator = EQUAL
					}
				}
				--- Box ---
					boxType = vertical
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/strategy/search/StrategySearchInput.module
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/strategy/search/StrategyListIndex.module
				}
			}
		}
	}
}