# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Strategy Search Criteria", fr = "Critères de recherche sur stratégie", de = "Strategie Suchbegriffe"
	containment = container
	domainEntity = "AAADSStrategy:StrategySearchCriteria"
	search = input !
	bean-define = DSBean.AAADSStrategy.StrategySearchCriteria
	bean-name = StrategySearchCriteria
	id = StrategySearchInput_G6eD8
	tid = 116972267676458
{
	--- Box ---
		boxType = vertical
	{
		--- FilterCriteria ---
			includedFile = "resource:/com/module/search/QueryBuilder.xsp"
		--- Include ---
			includeSrc = "" !
			resource:///default/search/NavigationSearch.fragment
	}
}