# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Search Results", fr = "Résultats de la recherche", de = Suchergebnisse
	domainEntity = "AAADSStrategy:StrategyList"
	search = output !
	bean-define = DSBean.AAADSStrategy.StrategyList
	bean-name = StrategyList
	id = StrategyListInvestProfile_rXt2_
	tid = 121792478227035
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			id = H78_Z
			table-column-count = 3 !
			table-columns-width = "33,33,33" !
		{
			--- TableColumn ---
				labels de = Code
				column-name = code !
				column-type = domain !
				domainAttribute = code !
				type = text
				column-locked = true
				id = code
				table-column-width = 33
				tid = 121792484033844
			{
				--- Conditional ---
					indexOfSelectedChild = 1
				{
					--- ConditionalBody ---
						javaCode = "com.odcgroup.tsl.wui.search.form.SearchFormHelper.isLookup(objectModel) == false"
						technicalName = NotLookup
						boxType = vertical
						isWidgetVisible = false
					{
						--- TableColumnItem ---
							toolTips en = "Select Strategy", fr = "Sélectionner la stratégie", de = "Strategie auswählen"
							item-column = code
							previewValue = value
							tid = 122045925749619
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = select ud
								Query.beanValue1 = "<udp:item column=\"code\"/>" ud
								modal = false
								only-changed = false
								prevalidate = false
							}
						}
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetSelected = true
					{
						--- TableColumnItem ---
							toolTips en = "Select Strategy", fr = "Sélectionner la stratégie", de = "Strategie auswählen"
							item-column = code
							previewValue = value
							tid = 122045927693687
						{
							Event OnClick (setWidgetValue)
							{
								widget-group-id = "<xsp:expr>com.odcgroup.tsl.wui.search.form.SearchFormHelper.getParentWidgetValue1Id(objectModel)</xsp:expr>"
								value = "<udp:item column=\"code\"/>"
								target = WUI_main
							}
							Event OnClick (winClose)
							{
								target = self
							}
						}
					}
				}
			}
			--- TableColumn ---
				column-name = name !
				column-type = domain !
				domainAttribute = name !
				type = text
				id = name
				table-column-width = 33
			{
				--- Icon ---
					toolTips en = "View Strategy Details", fr = "Voir les détails de la stratégie", de = "Details der Strategie ansehen"
					icon = application_form_magnify
					id = i378_
					tid = 16138927606870
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "resource:///administration/strategy/StrategyView.pageflow"
						target = popup
						code = "<udp:item column=\"code\"/>" ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
				--- Spacer ---
					height = 4
					width = 4
				--- TableColumnItem ---
					item-column = name
					previewValue = value
			}
			--- TableColumn ---
				column-name = extDenomination !
				column-type = domain !
				domainAttribute = extDenomination !
				type = text
				id = extDenomination
				table-column-width = 33
			{
				--- TableColumnItem ---
					item-column = extDenomination
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = name
				sort-rank = 1
		}
	}
}