/*
* generated by Xtext
*/
package com.odcgroup.t24.version.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class VersionDSLProposalProvider extends AbstractVersionDSLProposalProvider {
	
}
