# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Update Third Chrono", de = "Zeitl. Ablauf Drittpartei ändern", fr = "Mettre à jour la chronologie de tierce partie"
	domainEntity = "AAADSThirdChrono:ThirdChronoAll"
	bean-define = DSBean.AAADSThirdChrono.ThirdChronoAll
	bean-name = ThirdChronoAll
	id = ThirdChronoUpdate_Ov_Z_
	tid = 41259122157983
{
	--- Box ---
		boxType = vertical
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 6
			gridColumnsWidth = "16,16,16,16,16,16" !
			gridRowCount = 2
		{
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- LabelDomain ---
					domainAttribute = third !
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					required = true
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- Include ---
					domainAssociation = third
					includeSrc = "" !
					resource:///default/defaultFragments/ThirdPartyIdentifierView.fragment
					bean-property-prefix = third.
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- LabelDomain ---
					domainAttribute = natureE !
					for = natureE
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					required = true
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- ComboBox ---
					domainAttribute = natureE !
					horizontalAlignment = "${corporatehalign}"
					editable = false
					required = true
					bean-property = natureE
					id = natureE
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- LabelDomain ---
					domainAttribute = validityD !
					for = validityD
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					required = true
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- CaldateField ---
					domainAttribute = validityD !
					format = datetime.date-only
					horizontalAlignment = "${corporatehalign}"
					type = datetime
					editable = false
					required = true
					bean-property = validityD
					id = validityD
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- LabelDomain ---
					domainAttribute = currency !
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- Include ---
					domainAssociation = currency
					includeSrc = "" !
					resource:///default/defaultFragments/CurrencyIdentifier.fragment
					bean-property-prefix = currency.
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- LabelDomain ---
					domainAttribute = valueN !
					for = valueN
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					required = true
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- TextField ---
					domainAttribute = valueN !
					columns = 21
					format = decimal.detailed
					horizontalAlignment = "${corporatehalign}"
					type = decimal
					chars = 23
					editable = false
					required = true
					bean-property = valueN
					id = valueN
			}
			--- GridCell ---
				gridColumnWidth = 16
			--- GridCell ---
				gridColumnWidth = 16
		}
	}
}