# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSInstrDeposit:InstrDepositList"
	cssClass = nodeco
	bean-define = DSBean.AAADSInstrDeposit.InstrDepositList
	bean-name = InstrDepositList
	id = InstrumentDepositList_Y90O8
{
	--- Box ---
		labels en = Deposit, de = Lagerstelle, fr = Dépositaire
		boxType = vertical
		widgetBorder = box
		width = 0
		tid = 8535444817986
	{
		--- TableTree ---
			table-filter-layer = true
			id = M__8_
			table-column-count = 3 !
			table-columns-width = "33,33,33" !
		{
			--- TableColumn ---
				column-name = depositCode !
				column-type = domain !
				domainAttribute = depositCode !
				id = depositCode
				table-column-width = 33
			{
				--- TableColumnItem ---
					item-column = depositCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = mainDepositF !
				column-type = domain !
				domainAttribute = mainDepositF !
				id = mainDepositF
				table-column-width = 33
			{
				--- TableColumnItem ---
					item-column = mainDepositF
					previewValue = value
			}
			--- TableColumn ---
				column-name = rankN !
				column-type = domain !
				domainAttribute = rankN !
				id = rankN
				table-column-width = 33
			{
				--- TableColumnItem ---
					item-column = rankN
					format = decimal.detailed
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = depositCode
				sort-rank = 1
			--- TableSort ---
				sort-column-name = mainDepositF
				sort-direction = descending
				sort-rank = 3
			--- TableSort ---
				sort-column-name = rankN
				sort-direction = descending
				sort-rank = 2
		}
	}
}