# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Calendar Date List", fr = "Liste des dates du calendrier", de = "Liste der Kalenderdaten"
	domainEntity = "AAADSCalendarDate:CalendarDateList"
	bean-define = DSBean.AAADSCalendarDate.CalendarDateList
	bean-name = CalendarDateList
	id = CalendarDateList_Mr6m_
	tid = 130367104996026
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			id = j058q
			table-column-count = 4 !
			table-columns-width = "25,25,25,25" !
		{
			--- TableColumn ---
				column-name = calendarCode !
				column-type = domain !
				domainAttribute = calendarCode !
				id = calendarCode
				table-column-width = 25
			{
				--- TableColumnItem ---
					item-column = calendarCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = dateD !
				column-type = domain !
				domainAttribute = dateD !
				id = dateD
				table-column-width = 25
			{
				--- TableColumnItem ---
					item-column = dateD
					format = datetime.date-only
					previewValue = value
			}
			--- TableColumn ---
				column-name = natureE !
				column-type = domain !
				domainAttribute = natureE !
				id = natureE
				table-column-width = 25
			{
				--- TableColumnItem ---
					item-column = natureE
					previewValue = value
			}
			--- TableColumn ---
				column-name = denom !
				column-type = domain !
				domainAttribute = denom !
				id = denom
				table-column-width = 25
			{
				--- TableColumnItem ---
					item-column = denom
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = calendarCode
				sort-rank = 1
			--- TableSort ---
				sort-column-name = dateD
				sort-rank = 2
		}
	}
}