# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels fr = "Liste des synonymes", de = "Liste der Synonyme"
	domainEntity = "AAADSSynonym:SynonymList"
	cssClass = nodeco
	bean-define = DSBean.AAADSSynonym.SynonymList
	bean-name = SynonymList
	id = SynonymList_D__4s
	tid = 24548776791463
{
	--- Box ---
		labels en = Synonym, de = Synonym, fr = Synonyme
		boxType = vertical
		widgetBorder = box
		width = 0
		tid = 713442363315169
	{
		--- TableTree ---
			table-filter-layer = true
			id = Fd6H2
			table-model-reference = DSTableModel.AAADSSynonym.SynonymList
			table-column-count = 2 !
			table-columns-width = "50,50" !
		{
			--- TableColumn ---
				labels de = Kodifizierung
				column-name = codificationCode !
				column-type = domain !
				domainAttribute = codificationCode !
				id = codificationCode
				table-column-width = 50
				tid = 20588225242314
			{
				--- TableColumnItem ---
					item-column = codificationCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = code !
				column-type = domain !
				domainAttribute = code !
				id = code
				table-column-width = 50
			{
				--- TableColumnItem ---
					item-column = code
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = codificationCode
				sort-rank = 1
		}
	}
}