# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSInstrument:InstrumentAll"
	bean-define = DSBean.AAADSInstrument.InstrumentAll
	bean-name = InstrumentAll
	id = RiskView_f__B_
{
	--- Box ---
		labels en = Risk, fr = Risque, de = Risiko
		boxType = vertical
		widgetBorder = box
		tid = 2337214722767558
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 4
			gridColumnsWidth = "25,25,25,25" !
			gridRowCount = 2
		{
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- LabelDomain ---
					domainAttribute = riskNatureE !
					for = riskNatureE
					horizontalAlignment = "${corporatehalign}"
					required = true
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- ComboBox ---
					domainAttribute = riskNatureE !
					horizontalAlignment = "${corporatehalign}"
					editable = false
					required = true
					bean-property = riskNatureE
					id = riskNatureE
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- LabelDomain ---
					domainAttribute = riskGeo !
					horizontalAlignment = "${corporatehalign}"
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Include ---
					domainAssociation = riskGeo
					includeSrc = "" !
					resource:///default/defaultFragments/GeographicIdentifierView.fragment
					bean-property-prefix = riskGeo.
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- LabelDomain ---
					domainAttribute = riskCurr !
					horizontalAlignment = "${corporatehalign}"
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Include ---
					domainAssociation = riskCurr
					includeSrc = "" !
					resource:///default/defaultFragments/CurrencyIdentifierView.fragment
					bean-property-prefix = riskCurr.
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- LabelDomain ---
					labels de = Risiko-Niveau
					domainAttribute = riskLevelN !
					for = riskLevelN
					horizontalAlignment = "${corporatehalign}"
					tid = 2337214724689031
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- TextField ---
					domainAttribute = riskLevelN !
					columns = 21
					format = decimal.detailed
					horizontalAlignment = "${corporatehalign}"
					type = decimal
					chars = 23
					editable = false
					bean-property = riskLevelN
					id = riskLevelN
			}
		}
	}
}