# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSInstrument:InstrumentAll"
	cssClass = nodeco
	bean-define = DSBean.AAADSInstrument.InstrumentAll
	bean-name = InstrumentAll
	id = RiskList_Es9c5
{
	--- Box ---
		labels en = Risk, de = Risiko, fr = Risque
		boxType = vertical
		widgetBorder = box
		tid = 2337198860841810
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 6
			gridColumnsWidth = "16,16,16,16,16,16" !
			gridRowCount = 2
		{
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- LabelDomain ---
					domainAttribute = riskNatureE !
					for = riskNatureE
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					required = true
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- ComboBox ---
					domainAttribute = riskNatureE !
					horizontalAlignment = "${corporatehalign}"
					editable = false
					required = true
					bean-property = riskNatureE
					id = riskNatureE
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- LabelDomain ---
					domainAttribute = riskCurr !
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- Include ---
					domainAssociation = riskCurr
					includeSrc = "" !
					resource:///default/defaultFragments/CurrencyIdentifierView.fragment
					bean-property-prefix = riskCurr.
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- LabelDomain ---
					domainAttribute = riskGeo !
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- Include ---
					domainAssociation = riskGeo
					includeSrc = "" !
					resource:///default/defaultFragments/GeographicIdentifierView.fragment
					bean-property-prefix = riskGeo.
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- LabelDomain ---
					labels de = Risiko-Niveau
					domainAttribute = riskLevelN !
					for = riskLevelN
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					tid = 2337198862384744
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- TextField ---
					domainAttribute = riskLevelN !
					columns = 21
					format = decimal.detailed
					horizontalAlignment = "${corporatehalign}"
					type = decimal
					chars = 23
					editable = false
					bean-property = riskLevelN
					id = riskLevelN
			}
			--- GridCell ---
				gridColumnWidth = 16
			--- GridCell ---
				gridColumnWidth = 16
			--- GridCell ---
				gridColumnWidth = 16
			--- GridCell ---
				gridColumnWidth = 16
		}
	}
}