# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Events & Stats"
	containment = container
	id = EventsAndStats_u_0__
	tid = 1012970052956730
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			id = kp_53
			indexOfSelectedChild = 0
		{
			--- Tab ---
				labels en = "Today\'s events"
				id = tab_d_Eg_
				isWidgetSelected = true
				tid = 1013023267981265
			{
				--- Box ---
					boxType = vertical
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/monitoring/notification/NotificationList.module
					--- Conditional ---
						indexOfSelectedChild = 0
					{
						--- ConditionalBody ---
							javaCode = "com.odcgroup.wui.block.manager.BlockHelper.isWired(\"http://www.odcgroup.com/wui-cims-module\")"
							technicalName = IsTCMPresent
							boxType = vertical
							isWidgetSelected = true
						{
							--- Code ---
								code = "<cinclude:include src=\"cocoon://module/collaboration/task/party/NewTasks\"/>"
						}
						--- ConditionalBody ---
							javaCode = true
							technicalName = Default
							boxType = vertical
							isWidgetVisible = false
					}
				}
			}
		}
	}
}