# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSPortChrono:PortChronoList"
	bean-define = DSBean.AAADSPortChrono.PortChronoList
	bean-name = PortChronoList
	id = PorttChronoList_l_7__
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			id = Z5_p0
			table-column-count = 5 !
			table-columns-width = "20,20,20,20,20" !
		{
			--- TableColumn ---
				column-name = portfolioCode !
				column-type = domain !
				domainAttribute = portfolioCode !
				id = portfolioCode
				table-column-width = 20
			{
				--- TableColumnItem ---
					item-column = portfolioCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = validityD !
				column-type = domain !
				domainAttribute = validityD !
				id = validityD
				table-column-width = 20
			{
				--- TableColumnItem ---
					item-column = validityD
					format = datetime.date-only
					previewValue = value
			}
			--- TableColumn ---
				column-name = natureE !
				column-type = domain !
				domainAttribute = natureE !
				id = natureE
				table-column-width = 20
			{
				--- TableColumnItem ---
					item-column = natureE
					previewValue = value
			}
			--- TableColumn ---
				column-name = valueN !
				column-type = domain !
				domainAttribute = valueN !
				id = valueN
				table-column-width = 20
			{
				--- TableColumnItem ---
					item-column = valueN
					format = decimal.detailed
					previewValue = value
			}
			--- TableColumn ---
				column-name = currencyCode !
				column-type = domain !
				domainAttribute = currencyCode !
				id = currencyCode
				table-column-width = 20
			{
				--- TableColumnItem ---
					item-column = currencyCode
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = portfolioCode
				sort-rank = 1
			--- TableSort ---
				sort-column-name = validityD
				sort-direction = descending
				sort-rank = 2
			--- TableSort ---
				sort-column-name = natureE
				sort-rank = 3
		}
	}
}