/*
* generated by Xtext
*/
package com.odcgroup.t24.version.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class VersionDSLOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
