# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSValuation:ValuationSummaryList"
	cssClass = nodeco
	bean-define = DSBean.AAADSValuation.ValuationSummaryList
	bean-name = ValuationSummaryList
	id = InstrumentAccounting_r66_I
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			table-rendering-mode = summary-delegated
			id = c_o_1
			table-column-count = 6 !
			table-columns-width = "16,16,16,16,16,16" !
		{
			--- TableColumn ---
				labels en = "Asset Class/Instrument Code", de = Anlagekategorie/Instrument, fr = "Classe d\'actif/code de l\'instrument"
				column-display-grouping = true
				column-name = Grouping
				column-type = placeholder !
				type = text
				column-sortable = false !
				id = AFp9_
				table-column-width = 16
				tid = 6036026498339
			{
				--- TableGroup ---
					aggregateData = false
					group-column-name = ASSET_CLASS_DENOM
					group-sorting-column-name = ASSET_CLASS_RANK
					group-sorting-direction = ascending
					group-rank = 1
				--- TableGroup ---
					group-column-name = POS_CURRENCY
					group-dynamic-column = true
					group-sorting-column-name = CURR_CLASS_RANK
					group-sorting-direction = ascending
					group-rank = 5
				--- TableGroup ---
					group-column-name = Sub_Asset_Class
					group-sorting-column-name = Sub_Asset_Class_Rank
					group-sorting-direction = ascending
					group-rank = 2
				--- TableGroup ---
					group-column-name = PORTFOLIO_NAME
					group-sorting-column-name = PORTFOLIO_CODE
					group-sorting-direction = ascending
					group-rank = 4
				--- TableGroup ---
					group-column-name = INSTR_CODE
					group-sorting-column-name = INSTR_CODE
					group-sorting-direction = ascending
					collapsed = true
					group-rank = 3
			}
			--- TableColumn ---
				column-name = INSTR_DENOM !
				column-type = domain !
				domainAttribute = INSTR_DENOM !
				type = text
				id = INSTR_DENOM
				table-column-width = 16
			{
				--- Icon ---
					toolTips en = "View Instrument Details", fr = "Voir les détails de l\'instrument", de = "Details des Instruments ansehen"
					icon = application_form_magnify
					id = h1Y00
					tid = 6036027247038
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "resource:///administration/instrument/InstrumentQuickView.pageflow?2"
						target = popup
						code = "<udp:item column=\"INSTR_CODE\"/>" ud
						instrId = "<udp:item column=\"instr_id\"/>" ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
				--- Spacer ---
					height = 4
					width = 10
				--- TableColumnItem ---
					item-column = INSTR_DENOM
					previewValue = value
			}
			--- TableColumn ---
				column-name = QUANTITY !
				column-type = domain !
				domainAttribute = QUANTITY !
				type = text
				id = QUANTITY
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = QUANTITY
					format = decimal.2-digits
					previewValue = value
				--- Spacer ---
					height = 4
					width = 4
				--- TableColumnItem ---
					item-column = QUANTITY_CURR
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Market Value", de = Marktwert, fr = "Valeur de marché"
				column-name = MarketValue
				type = amount
				id = qST_3
				column-computation = make-amount
				column-computation-parameters = "MKT_VAL,REF_CURRENCY"
				table-column-width = 16
				tid = 6036029215444
			{
				--- TableColumnItem ---
					item-column = MarketValue
					previewValue = value
			}
			--- TableColumn ---
				column-name = MKT_VAL_PERC !
				column-type = domain !
				domainAttribute = MKT_VAL_PERC !
				type = text
				id = MKT_VAL_PERC
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = MKT_VAL_PERC
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = dynamic_MV
				column-type = dynamic !
				type = text
				id = t3_1q
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = MarketValue
					previewValue = value
				--- Spacer ---
					height = 4
					width = 4
				--- TableColumnItem ---
					item-column = MKT_VAL_PERC
					previewValue = value
			}
			--- TableAggregate ---
				aggregate-column-name = MKT_VAL_PERC
				aggregate-computation = sum
				aggregate-group-names = "ASSET_CLASS_DENOM,Sub_Asset_Class,INSTR_CODE,PORTFOLIO_NAME"
			--- TableAggregate ---
				aggregate-column-name = MKT_VAL
				aggregate-computation = sum
				aggregate-group-names = "ASSET_CLASS_DENOM,Sub_Asset_Class,INSTR_CODE,PORTFOLIO_NAME"
			--- TableAggregate ---
				aggregate-column-name = REF_CURRENCY
				aggregate-computation = max
				aggregate-group-names = "ASSET_CLASS_DENOM,Sub_Asset_Class,INSTR_CODE,PORTFOLIO_NAME"
			--- TableAggregate ---
				aggregate-column-name = instr_id
				aggregate-computation = max
				aggregate-group-names = "ASSET_CLASS_DENOM,Sub_Asset_Class,INSTR_CODE,PORTFOLIO_NAME"
			--- TableKeepFilter ---
				keep-filter-column-name = ACCT_FILTER
				keep-filter-operand = 1
			--- TableAggregate ---
				aggregate-column-name = MarketValue
				aggregate-computation = sum
				aggregate-group-names = "ASSET_CLASS_DENOM,Sub_Asset_Class,INSTR_CODE,PORTFOLIO_NAME,POS_CURRENCY"
			--- TableAggregate ---
				aggregate-column-name = dynamic_MV
				aggregate-computation = sum
				aggregate-group-names = "ASSET_CLASS_DENOM,Sub_Asset_Class,INSTR_CODE,PORTFOLIO_NAME"
			--- TableAggregate ---
				aggregate-column-name = ASSET_CLASS_RANK
				aggregate-computation = max
			--- TableAggregate ---
				aggregate-column-name = INSTR_CODE
				aggregate-computation = max
			--- TableAggregate ---
				aggregate-column-name = PORTFOLIO_CODE
				aggregate-computation = max
			--- TableAggregate ---
				aggregate-column-name = CURR_CLASS_RANK
				aggregate-computation = max
			--- TableAggregate ---
				aggregate-column-name = Sub_Asset_Class_Rank
				aggregate-computation = max
			--- TableExtra ---
				domainAttribute = QUANTITY_CURR
			--- TableAggregate ---
				aggregate-column-name = QUANTITY
				aggregate-computation = sum
				aggregate-group-names = "INSTR_CODE,PORTFOLIO_NAME"
			--- TableAggregate ---
				aggregate-column-name = QUANTITY_CURR
				aggregate-computation = max
				aggregate-group-names = "INSTR_CODE,PORTFOLIO_NAME"
			--- TableAggregate ---
				aggregate-column-name = INSTR_DENOM
				aggregate-computation = max
				aggregate-group-names = INSTR_CODE
		}
	}
}