# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels fr = Notation, de = Klassifizierung
	domainEntity = "AAADSRatingAttrib:RatingAttribList"
	cssClass = nodeco
	bean-define = DSBean.AAADSRatingAttrib.RatingAttribList
	bean-name = RatingAttribList
	id = RatingAttribList_ed57_
	tid = 18890227522771
{
	--- Box ---
		labels en = Rating, de = Bonität, fr = Notation
		boxType = vertical
		widgetBorder = box
		width = 0
		tid = 713161295629193
	{
		--- TableTree ---
			table-filter-layer = true
			id = t7w_5
			table-model-reference = DSTableModel.AAADSRatingAttrib.RatingAttribList
			table-column-count = 3 !
			table-columns-width = "33,33,33" !
		{
			--- TableColumn ---
				column-name = beginD !
				column-type = domain !
				domainAttribute = beginD !
				id = beginD
				table-column-width = 33
			{
				--- TableColumnItem ---
					item-column = beginD
					format = date
					previewValue = value
			}
			--- TableColumn ---
				column-name = codificationCode !
				column-type = domain !
				domainAttribute = codificationCode !
				type = text
				id = codificationCode
				table-column-width = 33
			{
				--- TableColumnItem ---
					item-column = codificationCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = ratingCode !
				column-type = domain !
				domainAttribute = ratingCode !
				id = ratingCode
				table-column-width = 33
			{
				--- TableColumnItem ---
					item-column = ratingCode
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = codificationCode
				sort-direction = descending
				sort-rank = 2
			--- TableSort ---
				sort-column-name = beginD
				sort-direction = descending
				sort-rank = 1
			--- TableSort ---
				sort-column-name = ratingCode
				sort-direction = descending
				sort-rank = 3
			--- TableAggregate ---
				aggregate-column-name = beginD
				aggregate-computation = max
			--- TableAggregate ---
				aggregate-column-name = ratingCode
				aggregate-computation = max
		}
	}
}