# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Cash Summary View", fr = "Vue sommaire de liquidité", de = "Geldfluss Zusammenfassung"
	containment = container
	domainEntity = "AAADSDomain:DomainContext"
	cssClass = nodeco
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = FutureCashFlowSummaryList_f2_L_
	tid = 659602007367416
{
	--- Box ---
		boxType = vertical
	{
		--- Conditional ---
			indexOfSelectedChild = 1
		{
			--- ConditionalBody ---
				javaCode = "(Integer.toString(com.odcgroup.aaa.DomainAAAInstrumentDimensionE.All).equals(<bean:get-property bean=\"DomainContext\" property=\"instrumentDimensionE\"/>.toString()))\r\n &amp;&amp;\r\n(Integer.toString(com.odcgroup.aaa.OperationStatusE.Accounted).equals(<bean:get-property bean=\"DomainContext\" property=\"minStatusE\"/>.toString()))\r\n &amp;&amp;\r\n(Integer.toString(com.odcgroup.aaa.OperationStatusE.Accounted).equals(<bean:get-property bean=\"DomainContext\" property=\"maxStatusE\"/>.toString()))"
				technicalName = "With Balance"
				boxType = vertical
				isWidgetVisible = false
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/futurecashflow/summary/FutureCashFlowBalanceE.module
			}
			--- ConditionalBody ---
				javaCode = true
				technicalName = "Without Balance"
				boxType = vertical
				isWidgetSelected = true
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/futurecashflow/summary/FutureCashFlowE.module
			}
		}
	}
}