# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels fr = Contexte, en = Context, de = Kontext
	domainEntity = "AAADSPortfolio:PortfolioAll"
	collapsible = true
	cssClass = nodeco
	bean-define = DSBean.AAADSPortfolio.PortfolioAll
	bean-name = PortfolioAll
	id = SelectPortfolioCode_vUtH_
	documentation = "Domain Context"
	tid = 1190410911556636
{
	--- Box ---
		labels en = Portfolio, de = Portfolio, fr = Portfeuille
		boxType = vertical
		width = 0
		tid = 1190539721009234
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 1
			gridColumnsWidth = 25 !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/defaultFragments/PortfolioIdentifierView.fragment
			}
		}
	}
}