<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="metamodel"
    nsURI="http://www.odcgroup.com/page/metamodel" nsPrefix="com.odcgroup.page.metamodel">
  <eClassifiers xsi:type="ecore:EClass" name="WidgetType" eSuperTypes="#//NamedType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//WidgetType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertyTypes" upperBound="-1"
        eType="#//PropertyType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="library" eType="#//WidgetLibrary"
        eOpposite="#//WidgetLibrary/widgetTypes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="excludedPropertyTypes"
        upperBound="-1" eType="#//PropertyType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="propertyFilterClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="derivable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="strictAccountability" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="domainWidget" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="canDropDomainElement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="richtext" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyType" eSuperTypes="#//NamedType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataType" lowerBound="1"
        eType="#//DataType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="library" eType="#//WidgetLibrary"
        eOpposite="#//WidgetLibrary/propertyTypes"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="category" eType="#//PropertyCategory"
        defaultValueLiteral="None"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceAdapter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subCategory" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibleInDomain" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MetaModel" eSuperTypes="#//NamedType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="widgetLibraries" upperBound="-1"
        eType="#//WidgetLibrary"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containability" eType="#//Accountability"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="includeability" eType="#//Accountability"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataTypes" eType="#//DataTypes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventModel" eType="#//EventModel"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="snippetModel" eType="#//SnippetModel"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WidgetTemplate" eSuperTypes="#//NamedType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//WidgetType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1"
        eType="#//WidgetTemplate" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertyTemplates" upperBound="-1"
        eType="#//PropertyTemplate" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventTemplates" upperBound="-1"
        eType="#//EventTemplate" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AccountabilityRule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="child" lowerBound="1" eType="#//WidgetType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//WidgetType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minOccurs" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxOccurs" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WidgetLibrary" eSuperTypes="#//NamedType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="widgetTypes" upperBound="-1"
        eType="#//WidgetType" containment="true" eOpposite="#//WidgetType/library"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertyTypes" upperBound="-1"
        eType="#//PropertyType" containment="true" eOpposite="#//PropertyType/library"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="widgetTemplates" upperBound="-1"
        eType="#//WidgetTemplate" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Accountability">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" upperBound="-1"
        eType="#//AccountabilityRule" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyValueConverter" abstract="true"
      interface="true">
    <eOperations name="getName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="toObject" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject">
      <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="toString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataType" eSuperTypes="#//NamedType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
        eType="#//DataValue" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="editorName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="com.odcgroup.page.ui.properties.PropertyTextEditor"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="validatorName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="converterName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="com.odcgroup.page.model.converter.StringValueConverter"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="editable" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedType" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="translationSupport" lowerBound="1"
        eType="#//TranslationSupport" defaultValueLiteral="NONE"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="propertiesHelpID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ConceptHelpID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ordinal" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyTemplate">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="readonly" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//PropertyType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataTypes">
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
        eType="#//DataType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IncludeabilityRule" eSuperTypes="#//AccountabilityRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inclusionType" eType="#//InclusionType"
        defaultValueLiteral="XINCLUDE"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="limitedAccountability"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="functions" upperBound="-1"
        eType="#//FunctionType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="events" upperBound="-1"
        eType="#//WidgetEvent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventTypes" upperBound="-1"
        eType="#//EventType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WidgetEvent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="widgetType" lowerBound="1"
        eType="#//WidgetType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventTypes" upperBound="-1"
        eType="#//EventType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionType" eSuperTypes="#//NamedType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//ParameterType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventTypes" upperBound="-1"
        eType="#//EventType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="allowUserParameters" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterType" eSuperTypes="#//NamedType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//DataType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventTemplate">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameterTemplates" upperBound="-1"
        eType="#//ParameterTemplate" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="functionType" eType="#//FunctionType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eventType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterTemplate">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//ParameterType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userDefined" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertyTypes" upperBound="-1"
        eType="#//PropertyType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SnippetType" eSuperTypes="#//NamedType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//SnippetType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertyTypes" upperBound="-1"
        eType="#//PropertyType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SnippetModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="snippets" upperBound="-1"
        eType="#//SnippetType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertyTypes" upperBound="-1"
        eType="#//PropertyType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="widgets" upperBound="-1"
        eType="#//WidgetSnippet" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="events" upperBound="-1"
        eType="#//EventSnippet" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WidgetSnippet">
    <eStructuralFeatures xsi:type="ecore:EReference" name="widgetType" lowerBound="1"
        eType="#//WidgetType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="snippets" upperBound="-1"
        eType="#//SnippetType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventSnippet">
    <eStructuralFeatures xsi:type="ecore:EReference" name="snippets" upperBound="-1"
        eType="#//SnippetType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="InclusionType">
    <eLiterals name="CINCLUDE" value="1"/>
    <eLiterals name="XINCLUDE"/>
    <eLiterals name="SOURCE_INCLUDE" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PropertyCategory">
    <eLiterals name="None"/>
    <eLiterals name="General" value="1"/>
    <eLiterals name="Presentation" value="3" literal="Presentation"/>
    <eLiterals name="Event" value="6"/>
    <eLiterals name="Description" value="2" literal="Description"/>
    <eLiterals name="Limitation" value="4" literal="Limitation"/>
    <eLiterals name="Technical" value="5" literal="Technical"/>
    <eLiterals name="Localization" value="7"/>
    <eLiterals name="Autocomplete" value="8" literal="Autocomplete"/>
    <eLiterals name="Xtooltip" value="9"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TranslationSupport">
    <eLiterals name="NONE"/>
    <eLiterals name="NAME" value="1"/>
    <eLiterals name="TEXT" value="2"/>
    <eLiterals name="NAME_AND_TEXT" value="3" literal="NAME_AND_TEXT"/>
  </eClassifiers>
</ecore:EPackage>
