# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	containment = container
	domainEntity = "AAADSValuation:ValuationSummaryList"
	cssClass = nodeco
	bean-define = DSBean.AAADSValuation.ValuationSummaryList
	bean-name = ValuationSummaryList
	id = AssetClass_FTn_5
{
	--- Box ---
		boxType = vertical
	{
		--- Code ---
			code = "<cinclude:include src=\"cocoon://module/aaa/corda/valuation/ByAssetClassCurrencyGraph\" />"
	}
}