# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Cumulated Returns (Portfolio vs. Benchmark)"
	containment = container
	domainEntity = "AAADSReturn:ReturnAnalysis"
	bean-define = DSBean.AAADSReturn.ReturnAnalysis
	bean-name = ReturnAnalysis
	id = CumulatedReturn_S1x_p
	tid = 2851266038164
{
	--- Box ---
		boxType = vertical
	{
		--- Code ---
			code = "<cinclude:include src=\"cocoon://module/aaa/corda/overview/CumulatedReturns\" />"
	}
}