# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Valued Portfolio"
	domainEntity = "AAADSPortfolio:PortfolioAll"
	bean-define = DSBean.AAADSPortfolio.PortfolioAll
	bean-name = PortfolioAll
	id = ValuedPortfolio_KW8e_
	tid = 7153192612527
{
	--- Box ---
		boxType = vertical
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 6
			gridColumnsWidth = "17,16,17,17,16,17" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 17
			{
				--- LabelDomain ---
					labels en = "Final Market Value", fr = "Valeur d\'inventaire ", de = Marktwert
					domainAttribute = extTdMktValM !
					for = extTdMktValM
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					required = true
					tid = 22805233432337
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- TextField ---
					domainAttribute = extTdMktValM !
					columns = 16
					format = decimal
					horizontalAlignment = "${corporatehalign}"
					type = amount
					chars = 18
					editable = false
					required = true
					bean-property = extTdMktValM
					id = extTdMktValM
				--- Spacer ---
					height = 4
					width = 4
				--- TextField ---
					domainAttribute = extPtfCur !
					columns = 5
					horizontalAlignment = "${corporatehalign}"
					type = text
					chars = 60
					editable = false
					required = true
					bean-property = extPtfCur
					id = extPtfCur
			}
			--- GridCell ---
				gridColumnWidth = 17
			{
				--- LabelDomain ---
					domainAttribute = extYtdPtfReturn !
					for = extYtdPtfReturn
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					required = true
			}
			--- GridCell ---
				gridColumnWidth = 17
			{
				--- TextField ---
					domainAttribute = extYtdPtfReturn !
					columns = 11
					format = percentTA
					horizontalAlignment = "${corporatehalign}"
					type = percent
					chars = 11
					editable = false
					required = true
					bean-property = extYtdPtfReturn
					id = extYtdPtfReturn
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- LabelDomain ---
					domainAttribute = extYtdBenchRet !
					for = extYtdBenchRet
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					required = true
			}
			--- GridCell ---
				gridColumnWidth = 17
			{
				--- TextField ---
					domainAttribute = extYtdBenchRet !
					columns = 11
					format = percentTA
					horizontalAlignment = "${corporatehalign}"
					type = percent
					chars = 11
					editable = false
					required = true
					bean-property = extYtdBenchRet
					id = extYtdBenchRet
			}
		}
	}
}