# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Update Type", de = "Typ ändern", fr = "Mettre à jour le type"
	containment = container
	id = TypeUpdate_QNFW_
	tid = 4126341110951
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			id = J0_37
			indexOfSelectedChild = 2
		{
			--- Tab ---
				labels en = Detail, de = Detail, fr = Détail
				id = tab_vg_a3
				isWidgetVisible = false
				tid = 5571960902924
			--- Tab ---
				labels en = Denomination, de = Beschreibung, fr = Dénomination
				id = tab_oV_L4
				isWidgetVisible = false
				tid = 4974375593546
			--- Tab ---
				labels en = Synonym, de = Synonym, fr = Synonyme
				id = tab_zsp7_
				isWidgetSelected = true
				tid = 5004569625748
		}
	}
}