# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Update Operation Type", de = "Transaktionsart ändern", fr = "Mettre à jour le type de l\'opération"
	containment = container
	id = TypeOperationUpdate_J9UXn
	tid = 4242624772422
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			id = u_Yp8
			indexOfSelectedChild = 1
		{
			--- Tab ---
				labels en = Detail, de = Detail, fr = Détail
				id = tab_V_1_y
				isWidgetVisible = false
				tid = 4288311240953
			--- Tab ---
				labels en = Denomination, de = Beschreibung, fr = Dénomination
				id = tab_O_914
				isWidgetSelected = true
				tid = 4309541040271
			{
				--- TabbedPane ---
					id = n_Q3C
					indexOfSelectedChild = 2
				{
					--- Tab ---
						labels en = Detail, de = Detail, fr = Détail
						id = tab_B_3H_
						isWidgetVisible = false
						tid = 5571960865426
					--- Tab ---
						labels en = Denomination, de = Beschreibung, fr = Dénomination
						id = tab_N_P42
						isWidgetVisible = false
						tid = 5571961052061
					--- Tab ---
						labels en = Synonym, de = Synonym, fr = Synonyme
						id = tab_z_00Y
						isWidgetSelected = true
						tid = 5571962143566
				}
			}
		}
	}
}