# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Update Instrument Type", de = "Instrumenttyp ändern", fr = "Mettre à jour le type d\'instrument"
	containment = container
	id = TypeInstrumentUpdate_c__oV
	tid = 4193441223395
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			id = X69_R
			indexOfSelectedChild = 2
		{
			--- Tab ---
				labels en = Detail, de = Detail, fr = Détail
				id = tab_P_9__
				isWidgetVisible = false
				tid = 5571960939735
			--- Tab ---
				labels en = Denomination, de = Beschreibung, fr = Dénomination
				id = tab_DyCM0
				isWidgetVisible = false
				tid = 5571961016931
			--- Tab ---
				labels en = Synonym, de = Synonym, fr = Synonyme
				id = tab_zA76w
				isWidgetSelected = true
				tid = 5571962072215
		}
	}
}