# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSDomain:DomainContext"
	cssClass = nodeco
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = ReportExistingPortfolio_Kz__G
{
	--- Box ---
		boxType = vertical
	{
		--- Box ---
			labels en = Valuation, fr = Valorisation, de = Bewertung
			boxType = vertical
			tid = 27242451168534
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 5
				gridColumnsWidth = "15,15,15,15,40" !
				gridRowCount = 2
			{
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						labels en = "Display Type", fr = "Type d\'affichage", de = Darstellungs-Art
						domainAttribute = repValuationE !
						for = repValuationE
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
						tid = 27242452165570
				}
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- ComboBox ---
						domainAttribute = repValuationE !
						horizontalAlignment = "${corporatehalign}"
						bean-property = repValuationE
						id = repValuationE
					{
						Event OnChange (submit)
						{
							method = post
							call-URI = "<pageflow:continuation/>"
							widget-group-ref = form
							target = self
							param = "flow-action=reload"
							only-changed = true
							modal = false
							prevalidate = false
						}
					}
				}
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						labels de = "Grafik Aktien"
						domainAttribute = repStockChartE !
						for = repStockChartE
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
						tid = 2023530519540501
				}
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- CheckBox ---
						domainAttribute = repStockChartE
						displayLabel = false
						horizontalTextPosition = trail
						enabled = conditional
						enabledIsBasedOn = advanced
						bean-property = repStockChartE
						id = repStockChartE
						enabledIsBasedOn-advanced = "conditionVal = (Integer.valueOf(<bean:get-property bean=\"DomainContext\" property=\"repValuationE\"/>.toString()) > 0);"
				}
				--- GridCell ---
					gridColumnWidth = 40
				--- GridCell ---
					gridColumnWidth = 15
				--- GridCell ---
					gridColumnWidth = 15
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						labels fr = "Graphiques titres à revenu fixe", de = "Grafik Anleihen", en = "Additionnal Fixed Income Charts"
						domainAttribute = repBondChartE !
						for = repBondChartE
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
						tid = 2021040609998379
				}
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- CheckBox ---
						domainAttribute = repBondChartE
						displayLabel = false
						horizontalTextPosition = trail
						enabled = conditional
						enabledIsBasedOn = advanced
						bean-property = repBondChartE
						id = repBondChartE
						enabledIsBasedOn-advanced = "conditionVal = (Integer.valueOf(<bean:get-property bean=\"DomainContext\" property=\"repValuationE\"/>.toString()) > 0);"
				}
				--- GridCell ---
					gridColumnWidth = 40
			}
		}
		--- Box ---
			labels en = "Cash Flow", fr = "Cash flow", de = Geldfluss
			boxType = vertical
			tid = 27274442464249
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 5
				gridColumnsWidth = "15,15,15,15,40" !
				gridRowCount = 2
			{
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						labels en = "Display Type", fr = "Type d\'affichage", de = Darstellungs-Art
						domainAttribute = repCashflowE !
						for = repCashflowE
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
						tid = 27274443480961
				}
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- ComboBox ---
						domainAttribute = repCashflowE !
						horizontalAlignment = "${corporatehalign}"
						bean-property = repCashflowE
						id = repCashflowE
					{
						Event OnChange (submit)
						{
							method = post
							call-URI = "<pageflow:continuation/>"
							widget-group-ref = form
							target = self
							param = "flow-action=reload"
							only-changed = true
							modal = false
							prevalidate = false
						}
					}
				}
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						labels de = "Grafik Fälligkeiten"
						domainAttribute = repMaturityChartE !
						for = repMaturityChartE
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
						tid = 2023497128228324
				}
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- CheckBox ---
						domainAttribute = repMaturityChartE
						displayLabel = false
						horizontalTextPosition = trail
						enabled = conditional
						enabledIsBasedOn = advanced
						bean-property = repMaturityChartE
						id = repMaturityChartE
						enabledIsBasedOn-advanced = "conditionVal = (Integer.valueOf(<bean:get-property bean=\"DomainContext\" property=\"repCashflowE\"/>.toString()) > 0);"
				}
				--- GridCell ---
					gridColumnWidth = 40
				--- GridCell ---
					gridColumnWidth = 15
				--- GridCell ---
					gridColumnWidth = 15
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						labels de = "Grafik Währungen"
						domainAttribute = repCurrencyChartE !
						for = repCurrencyChartE
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
						tid = 2023504751759135
				}
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- CheckBox ---
						domainAttribute = repCurrencyChartE
						displayLabel = false
						horizontalTextPosition = trail
						enabled = conditional
						enabledIsBasedOn = advanced
						bean-property = repCurrencyChartE
						id = repCurrencyChartE
						enabledIsBasedOn-advanced = "conditionVal = (Integer.valueOf(<bean:get-property bean=\"DomainContext\" property=\"repCashflowE\"/>.toString()) > 0);"
				}
				--- GridCell ---
					gridColumnWidth = 40
			}
		}
	}
}