# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSDomain:DomainContext"
	cssClass = nodeco
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = ContactDetails_uT4ot
{
	--- Box ---
		labels en = "Contact Details", de = Kontakt-Details, fr = "Détails de contact"
		boxType = vertical
		tid = 366299927567902
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 2
			gridColumnsWidth = "15,85" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 15
			{
				--- LabelDomain ---
					domainAttribute = repAdditionalInfoC !
					for = repAdditionalInfoC
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					required = true
			}
			--- GridCell ---
				gridColumnWidth = 85
			{
				--- TextArea ---
					domainAttribute = repAdditionalInfoC !
					columns = 100
					horizontalAlignment = "${corporatehalign}"
					rows = 3
					type = text
					chars = 255
					bean-property = repAdditionalInfoC
					id = repAdditionalInfoC
			}
		}
	}
}