# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSDomain:DomainContext"
	cssClass = nodeco
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = ReportFinancialParameters_Nf_3m
{
	--- Box ---
		labels en = "Financial Parameters", fr = "Paramètres financiers", de = Finanz-Parameter
		boxType = vertical
		width = 0
		tid = 32753531589710
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 3
			gridColumnsWidth = "20,15,65" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 20
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainLanguagePGReport.fragment
			}
			--- GridCell ---
				gridColumnWidth = 15
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainFundSplit.fragment
			}
			--- GridCell ---
				gridColumnWidth = 65
		}
	}
}