# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = Comments, de = Kommentare, fr = Commentaires
	domainEntity = "AAADSDomain:DomainReportComments"
	bean-define = DSActivityBean.AAADSDomain.DomainReportComments
	bean-name = DomainReportComments
	id = ReportCommentsView_b__2V
	tid = 1908724612206734
{
	--- Box ---
		boxType = vertical
	{
		--- Box ---
			labels en = "Language Selection", fr = "Sélection de la langue", de = "Sprache Wahl"
			boxType = vertical
			tid = 34553040586602
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 3
				gridColumnsWidth = "15,35,50" !
				gridRowCount = 1
			{
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						domainAttribute = language !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 35
				{
					--- Include ---
						domainAssociation = language
						includeSrc = "" !
						resource:///default/defaultFragments/DictLanguageIdentifierView.fragment
						bean-property-prefix = language.
				}
				--- GridCell ---
					gridColumnWidth = 50
			}
		}
		--- Button ---
			labels en = Back, de = Zurück, fr = Retour
			id = btn_H60__
			tid = 1910943201474888
		{
			Event OnClick (submit) S
			{
				method = post
				call-URI = "<pageflow:continuation/>"
				target = self
				flow-action = back ud
				modal = false
				only-changed = false
				prevalidate = false
			}
		}
		--- Box ---
			labels en = "Market Segment Comments - Stocks", de = "Marktsegment-Kommentare - Aktien", fr = "Commentaire du segment de marché - Actions"
			boxType = vertical
			tid = 1908195519857874
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 3
				gridColumnsWidth = "15,35,50" !
				gridRowCount = 2
			{
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						domainAttribute = stockMktOutlook !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 35
				{
					--- Include ---
						domainAssociation = stockMktOutlook
						includeSrc = "" !
						resource:///default/extoperation/orderproposal/ReportCommentView.fragment
						bean-property-prefix = stockMktOutlook.
				}
				--- GridCell ---
					gridColumnWidth = 50
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						domainAttribute = stockAdvice !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 35
				{
					--- Include ---
						domainAssociation = stockAdvice
						includeSrc = "" !
						resource:///default/extoperation/orderproposal/ReportCommentView.fragment
						bean-property-prefix = stockAdvice.
				}
				--- GridCell ---
					gridColumnWidth = 50
			}
		}
		--- Box ---
			labels en = "Market Segment Comments - Fixed Income", de = "Marktsegment-Kommentare - Anleihen", fr = "Commentaire du segment de marché - Titres à revenu fixe"
			boxType = vertical
			tid = 1908212739101833
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 3
				gridColumnsWidth = "15,35,50" !
				gridRowCount = 2
			{
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						domainAttribute = bondMktOutlook !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 35
				{
					--- Include ---
						domainAssociation = bondMktOutlook
						includeSrc = "" !
						resource:///default/extoperation/orderproposal/ReportCommentView.fragment
						bean-property-prefix = bondMktOutlook.
				}
				--- GridCell ---
					gridColumnWidth = 50
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						domainAttribute = bondAdvice !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 35
				{
					--- Include ---
						domainAssociation = bondAdvice
						includeSrc = "" !
						resource:///default/extoperation/orderproposal/ReportCommentView.fragment
						bean-property-prefix = bondAdvice.
				}
				--- GridCell ---
					gridColumnWidth = 50
			}
		}
		--- Box ---
			labels en = "Market Segment Comments - Funds", de = "Marktsegment-Kommentare - Fondsanteile", fr = "Commentaire du segment de marché - Fonds"
			boxType = vertical
			tid = 125892571562388
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 3
				gridColumnsWidth = "15,35,50" !
				gridRowCount = 2
			{
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						domainAttribute = cashMktOutlook !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 35
				{
					--- Include ---
						domainAssociation = fundMktOutlook
						includeSrc = "" !
						resource:///default/extoperation/orderproposal/ReportCommentView.fragment
						bean-property-prefix = fundMktOutlook.
				}
				--- GridCell ---
					gridColumnWidth = 50
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						domainAttribute = cashAdvice !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 35
				{
					--- Include ---
						domainAssociation = fundAdvice
						includeSrc = "" !
						resource:///default/extoperation/orderproposal/ReportCommentView.fragment
						bean-property-prefix = fundAdvice.
				}
				--- GridCell ---
					gridColumnWidth = 50
			}
		}
		--- Box ---
			labels en = "Market Segment Comments - Derivatives", de = "Marktsegment-Kommentare - Derivate", fr = "Commentaire du segment de marché - Dérivés"
			boxType = vertical
			tid = 125895579707597
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 3
				gridColumnsWidth = "15,35,50" !
				gridRowCount = 2
			{
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						domainAttribute = cashMktOutlook !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 35
				{
					--- Include ---
						domainAssociation = derivativeMktOutlook
						includeSrc = "" !
						resource:///default/extoperation/orderproposal/ReportCommentView.fragment
						bean-property-prefix = derivativeMktOutlook.
				}
				--- GridCell ---
					gridColumnWidth = 50
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						domainAttribute = cashAdvice !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 35
				{
					--- Include ---
						domainAssociation = derivativeAdvice
						includeSrc = "" !
						resource:///default/extoperation/orderproposal/ReportCommentView.fragment
						bean-property-prefix = derivativeAdvice.
				}
				--- GridCell ---
					gridColumnWidth = 50
			}
		}
		--- Box ---
			labels en = "Market Segment Comments - Liquidity", de = "Marktsegment-Kommentare - Liquidität", fr = "Commentaire du segment de marché - Liquidités"
			boxType = vertical
			tid = 125909547185790
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 3
				gridColumnsWidth = "15,35,50" !
				gridRowCount = 2
			{
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						domainAttribute = cashMktOutlook !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 35
				{
					--- Include ---
						domainAssociation = cashMktOutlook
						includeSrc = "" !
						resource:///default/extoperation/orderproposal/ReportCommentView.fragment
						bean-property-prefix = cashMktOutlook.
				}
				--- GridCell ---
					gridColumnWidth = 50
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						domainAttribute = cashAdvice !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 35
				{
					--- Include ---
						domainAssociation = cashAdvice
						includeSrc = "" !
						resource:///default/extoperation/orderproposal/ReportCommentView.fragment
						bean-property-prefix = cashAdvice.
				}
				--- GridCell ---
					gridColumnWidth = 50
			}
		}
		--- Box ---
			labels en = "Market Segment Comments - Money Market", de = "Marktsegment-Kommentare - Geldmarkt", fr = "Commentaire du segment de marché - Marché monétaire"
			boxType = vertical
			tid = 125887613953571
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 3
				gridColumnsWidth = "15,35,50" !
				gridRowCount = 2
			{
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						domainAttribute = cashMktOutlook !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 35
				{
					--- Include ---
						domainAssociation = moneyMarketMktOutlook
						includeSrc = "" !
						resource:///default/extoperation/orderproposal/ReportCommentView.fragment
						bean-property-prefix = moneyMarketMktOutlook.
				}
				--- GridCell ---
					gridColumnWidth = 50
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						domainAttribute = cashAdvice !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 35
				{
					--- Include ---
						domainAssociation = moneyMarketAdvice
						includeSrc = "" !
						resource:///default/extoperation/orderproposal/ReportCommentView.fragment
						bean-property-prefix = moneyMarketAdvice.
				}
				--- GridCell ---
					gridColumnWidth = 50
			}
		}
		--- Box ---
			labels en = "Market Segment Comments - Forwards", de = "Marktsegment-Kommentare - Devisentermin", fr = "Commentaire du segment de marché - Contrats à terme"
			boxType = vertical
			tid = 1908180589302800
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 3
				gridColumnsWidth = "15,35,50" !
				gridRowCount = 2
			{
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						domainAttribute = cashMktOutlook !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 35
				{
					--- Include ---
						domainAssociation = forwardMktOutlook
						includeSrc = "" !
						resource:///default/extoperation/orderproposal/ReportCommentView.fragment
						bean-property-prefix = forwardMktOutlook.
				}
				--- GridCell ---
					gridColumnWidth = 50
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						domainAttribute = cashAdvice !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 35
				{
					--- Include ---
						domainAssociation = forwardAdvice
						includeSrc = "" !
						resource:///default/extoperation/orderproposal/ReportCommentView.fragment
						bean-property-prefix = forwardAdvice.
				}
				--- GridCell ---
					gridColumnWidth = 50
			}
		}
		--- Box ---
			labels en = "Market Segment Comments - Other", de = "Marktsegment-Kommentare - Sonstige", fr = "Commentaire du segment de marché - Autres"
			boxType = vertical
			tid = 1908232592000903
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 3
				gridColumnsWidth = "15,35,50" !
				gridRowCount = 2
			{
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						domainAttribute = otherMktOutlook !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 35
				{
					--- Include ---
						domainAssociation = otherMktOutlook
						includeSrc = "" !
						resource:///default/extoperation/orderproposal/ReportCommentView.fragment
						bean-property-prefix = otherMktOutlook.
				}
				--- GridCell ---
					gridColumnWidth = 50
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						domainAttribute = otherAdvice !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 35
				{
					--- Include ---
						domainAssociation = otherAdvice
						includeSrc = "" !
						resource:///default/extoperation/orderproposal/ReportCommentView.fragment
						bean-property-prefix = otherAdvice.
				}
				--- GridCell ---
					gridColumnWidth = 50
			}
		}
		--- Box ---
			labels en = "Additional Comments", de = "Zusätzliche Kommentare ", fr = "Commentaires additionnels"
			boxType = vertical
			tid = 1908251434049391
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 3
				gridColumnsWidth = "15,35,50" !
				gridRowCount = 2
			{
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						domainAttribute = openingComments !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 35
				{
					--- Include ---
						domainAssociation = openingComments
						includeSrc = "" !
						resource:///default/extoperation/orderproposal/ReportCommentView.fragment
						bean-property-prefix = openingComments.
				}
				--- GridCell ---
					gridColumnWidth = 50
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						domainAttribute = closingComments !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 35
				{
					--- Include ---
						domainAssociation = closingComments
						includeSrc = "" !
						resource:///default/extoperation/orderproposal/ReportCommentView.fragment
						bean-property-prefix = closingComments.
				}
				--- GridCell ---
					gridColumnWidth = 50
			}
		}
	}
}