# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Report Content", fr = "Contenu de rapport", de = "Inhalt des Berichts"
	containment = container
	id = ReportContent_m2wD_
	tid = 1820616142117908
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/orderproposal/reportconfiguration/ReportFinancialParameters.module
		--- Box ---
			boxType = vertical
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/reporting/context/ReportOptions.module
		--- Box ---
			boxType = vertical
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/orderproposal/reportconfiguration/ReportContactDetails.module
		--- Box ---
			boxType = vertical
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/orderproposal/reportconfiguration/ReportBlocksSelection.module
	}
}