# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSDomain:DomainContext"
	cssClass = nodeco
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = ReportFinalPortfolio_U_25_
{
	--- Box ---
		boxType = vertical
	{
		--- Box ---
			labels en = Valuation, fr = Valorisation, de = Bewertung
			boxType = vertical
			tid = 27477349735599
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 5
				gridColumnsWidth = "15,15,15,15,40" !
				gridRowCount = 2
			{
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						labels de = Darstellungs-Art, en = "Display Type", fr = "Type d\'affichage"
						domainAttribute = repValuation2E !
						for = repValuation2E
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
						tid = 27736603259551
				}
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- ComboBox ---
						domainAttribute = repValuation2E !
						horizontalAlignment = "${corporatehalign}"
						bean-property = repValuation2E
						id = repValuation2E
					{
						Event OnChange (submit)
						{
							method = post
							call-URI = "<pageflow:continuation/>"
							widget-group-ref = form
							target = self
							param = "flow-action=reload"
							only-changed = true
							modal = false
							prevalidate = false
						}
					}
				}
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						labels fr = "Graphiques actions", de = "Grafik Aktien", en = "Additionnal Stock Charts"
						domainAttribute = repStockChart2E !
						for = repStockChart2E
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
						tid = 27918045535600
				}
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- CheckBox ---
						domainAttribute = repStockChart2E
						displayLabel = false
						horizontalTextPosition = trail
						enabled = conditional
						enabledIsBasedOn = advanced
						bean-property = repStockChart2E
						id = repStockChart2E
						enabledIsBasedOn-advanced = "conditionVal = (Integer.valueOf(<bean:get-property bean=\"DomainContext\" property=\"repValuation2E\"/>.toString()) > 0);"
				}
				--- GridCell ---
					gridColumnWidth = 40
				--- GridCell ---
					gridColumnWidth = 15
				--- GridCell ---
					gridColumnWidth = 15
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						labels fr = "Graphiques titres à revenu fixe", de = "Grafik Anleihen", en = "Additionnal Fixed Income Charts"
						domainAttribute = repBondChart2E !
						for = repBondChart2E
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
						tid = 27874351153093
				}
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- CheckBox ---
						domainAttribute = repBondChart2E
						displayLabel = false
						horizontalTextPosition = trail
						enabled = conditional
						enabledIsBasedOn = advanced
						bean-property = repBondChart2E
						id = repBondChart2E
						enabledIsBasedOn-advanced = "conditionVal = (Integer.valueOf(<bean:get-property bean=\"DomainContext\" property=\"repValuation2E\"/>.toString()) > 0);"
				}
				--- GridCell ---
					gridColumnWidth = 40
			}
		}
		--- Box ---
			labels en = "Cash Flow", fr = "Cash flow", de = Geldfluss
			boxType = vertical
			tid = 27500213634374
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 5
				gridColumnsWidth = "15,15,15,15,40" !
				gridRowCount = 2
			{
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						labels de = Darstellungs-Art, en = "Display Type", fr = "Type d\'affichage"
						domainAttribute = repCashflow2E !
						for = repCashflow2E
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
						tid = 28181919900476
				}
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- ComboBox ---
						domainAttribute = repCashflow2E !
						horizontalAlignment = "${corporatehalign}"
						bean-property = repCashflow2E
						id = repCashflow2E
					{
						Event OnChange (submit)
						{
							method = post
							call-URI = "<pageflow:continuation/>"
							widget-group-ref = form
							target = self
							param = "flow-action=reload"
							only-changed = true
							modal = false
							prevalidate = false
						}
					}
				}
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						labels fr = "Graphiques d\'échéance", de = "Grafik Fälligkeiten", en = "Additional Maturity Charts"
						domainAttribute = repMaturityChart2E !
						for = repMaturityChart2E
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
						tid = 28252680626742
				}
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- CheckBox ---
						domainAttribute = repMaturityChart2E
						displayLabel = false
						horizontalTextPosition = trail
						enabled = conditional
						enabledIsBasedOn = advanced
						bean-property = repMaturityChart2E
						id = repMaturityChart2E
						enabledIsBasedOn-advanced = "conditionVal = (Integer.valueOf(<bean:get-property bean=\"DomainContext\" property=\"repCashflow2E\"/>.toString()) > 0);"
				}
				--- GridCell ---
					gridColumnWidth = 40
				--- GridCell ---
					gridColumnWidth = 15
				--- GridCell ---
					gridColumnWidth = 15
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						labels fr = "Graphiques de devise", de = "Grafik Währungen", en = "Additional Currency Charts"
						domainAttribute = repCurrencyChart2E !
						for = repCurrencyChart2E
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
						tid = 28256384847444
				}
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- CheckBox ---
						column-checkbox-action = ""
						domainAttribute = repCurrencyChart2E
						displayLabel = false
						horizontalTextPosition = trail
						enabled = conditional
						enabledIsBasedOn = advanced
						bean-property = repCurrencyChart2E
						id = repCurrencyChart2E
						enabledIsBasedOn-advanced = "conditionVal = (Integer.valueOf(<bean:get-property bean=\"DomainContext\" property=\"repCashflow2E\"/>.toString()) > 0);"
				}
				--- GridCell ---
					gridColumnWidth = 40
			}
		}
	}
}