# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Report Configuration", fr = "Configuration de rapport", de = "Konfiguration des Berichts"
	containment = container
	domainEntity = "AAADSDomain:DomainContext"
	cssClass = nodeco
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = ReportSummary_B_KYI
	tid = 23535609115445
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/orderproposal/reportconfiguration/ReportContent.module
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/orderproposal/reportconfiguration/ReportComments.module
		--- Box ---
		{
			--- Button ---
				labels en = "View Draft Report", de = "Berichts-Entwurf ansehen", fr = "Voir l\'ébauche du rapport"
				id = btn_zO1_9
				tid = 10810870580757
			{
				Event OnClick (submit)
				{
					method = post
					call-URI = "resource:///orderproposal/PGReportPreviewExecution.pageflow"
					target = popup
					only-changed = false
					prevalidate = false
					modal = false
					widget-group-ref = form
				}
			}
			--- Button ---
				labels en = "Send Report to Repository", de = "Bericht an Speicher senden", fr = "Envoyer rapport dans le répertoire"
				id = btn_r_i__
				tid = 6229748994609
			{
				Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					widget-group-ref = form
					target = self
					flow-action = sendreport ud
					modal = false
					only-changed = false
					prevalidate = false
				}
			}
			--- Button ---
				labels en = Back, de = Zurück, fr = Retour
				id = btn_hGr__
				tid = 18536356926151
			{
				Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					widget-group-ref = form
					target = self
					flow-action = back ud
					modal = false
					only-changed = false
					prevalidate = false
				}
			}
			--- Glue ---
		}
	}
}