# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	containment = container
	domainEntity = "AAADSDomain:DomainContext"
	cssClass = nodeco
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = ReportBlocksSelection_f553_
{
	--- Box ---
		labels en = "Report Blocks Selection", fr = "Sélection des sections de rapport", de = "Auswahl Berichts-Abschnitte"
		boxType = vertical
		tid = 366038877678258
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 2
			gridColumnsWidth = "15,85" !
			gridRowCount = 4
		{
			--- GridCell ---
				gridColumnWidth = 15
			{
				--- LabelDomain ---
					domainAttribute = repConfigNatureE !
					for = repConfigNatureE
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					required = true
			}
			--- GridCell ---
				gridColumnWidth = 85
			{
				--- ComboBox ---
					domainAttribute = repConfigNatureE !
					horizontalAlignment = "${corporatehalign}"
					bean-property = repConfigNatureE
					id = repConfigNatureE
				{
					Event OnChange (submit)
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						widget-group-ref = form
						target = self
						param = "flow-action=reload"
						only-changed = true
						modal = false
						prevalidate = false
					}
				}
			}
			--- GridCell ---
				gridColumnWidth = 15
			{
				--- Label ---
					labels en = "Initial Portfolio", de = Ausgangs-Portfolio, fr = "Portefeuille initial"
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					verticalAlignment = lead
					id = W_Q_3
					tid = 939890214916421
			}
			--- GridCell ---
				gridColumnWidth = 85
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/orderproposal/reportconfiguration/ReportExistingPortfolio.module
			}
			--- GridCell ---
				gridColumnWidth = 15
			{
				--- Label ---
					labels en = "Final Portfolio", de = "Portfolio inkl. Aufträge", fr = "Portefeuille final"
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					verticalAlignment = lead
					id = R50_i
					tid = 939940726189781
			}
			--- GridCell ---
				gridColumnWidth = 85
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/orderproposal/reportconfiguration/ReportFinalPortfolio.module
			}
			--- GridCell ---
				gridColumnWidth = 15
			{
				--- LabelDomain ---
					domainAttribute = repOrdersE !
					for = repOrdersE
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
			}
			--- GridCell ---
				gridColumnWidth = 85
			{
				--- Box ---
					widgetBorder = box
				{
					--- Grid ---
						cssClass = blank
						gridColumnCount = 3
						gridColumnsWidth = "15,15,70" !
						gridRowCount = 1
					{
						--- GridCell ---
							gridColumnWidth = 15
						{
							--- LabelDomain ---
								labels en = "Display Type", fr = "Type d\'affichage", de = Darstellungs-Art
								domainAttribute = repOrdersE !
								for = repOrdersE
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
								tid = 1561922772235907
						}
						--- GridCell ---
							gridColumnWidth = 15
						{
							--- ComboBox ---
								domainAttribute = repOrdersE !
								horizontalAlignment = "${corporatehalign}"
								bean-property = repOrdersE
								id = repOrdersE
						}
						--- GridCell ---
							gridColumnWidth = 70
					}
					--- Spacer ---
						height = 4
						width = 4
				}
			}
		}
	}
}