# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = Comments, de = Kommentare, fr = Commentaires
	containment = container
	domainEntity = "AAADSDomain:DomainReportComments"
	bean-define = DSActivityBean.AAADSDomain.DomainReportComments
	bean-name = DomainReportComments
	id = ReportComments_yLe61
	tid = 1819320291111958
{
	--- Box ---
		boxType = vertical
	{
		--- Box ---
			labels en = "Market Segment Comments - Stocks", de = "Marktsegment-Kommentare - Aktien", fr = "Commentaire du segment de marché - Actions"
			boxType = vertical
			tid = 465453785071445
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 2
				gridColumnsWidth = "15,85" !
				gridRowCount = 2
			{
				--- GridCell ---
					gridColumnWidth = 15
					gridColumnCssClass = grey
				{
					--- LabelDomain ---
						domainAttribute = stockMktOutlook !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 85
				{
					--- Include ---
						domainAssociation = stockMktOutlook
						includeSrc = "" !
						resource:///default/extoperation/orderproposal/ReportCommentEdit.fragment
						bean-property-prefix = stockMktOutlook.
				}
				--- GridCell ---
					gridColumnWidth = 15
					gridColumnCssClass = grey
				{
					--- LabelDomain ---
						domainAttribute = stockAdvice !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 85
				{
					--- Include ---
						domainAssociation = stockAdvice
						includeSrc = "" !
						resource:///default/extoperation/orderproposal/ReportCommentEdit.fragment
						bean-property-prefix = stockAdvice.
				}
			}
		}
		--- Box ---
			labels en = "Market Segment Comments - Fixed Income", de = "Marktsegment-Kommentare - Anleihen", fr = "Commentaire du segment de marché - Titres à revenu fixe"
			boxType = vertical
			tid = 31568513108768
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 2
				gridColumnsWidth = "15,85" !
				gridRowCount = 2
			{
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						domainAttribute = bondMktOutlook !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 85
				{
					--- Include ---
						domainAssociation = bondMktOutlook
						includeSrc = "" !
						resource:///default/extoperation/orderproposal/ReportCommentEdit.fragment
						bean-property-prefix = bondMktOutlook.
				}
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						domainAttribute = bondAdvice !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 85
				{
					--- Include ---
						domainAssociation = bondAdvice
						includeSrc = "" !
						resource:///default/extoperation/orderproposal/ReportCommentEdit.fragment
						bean-property-prefix = bondAdvice.
				}
			}
		}
		--- Box ---
			labels en = "Market Segment Comments - Funds", de = "Marktsegment-Kommentare - Fondsanteile", fr = "Commentaire du segment de marché - Fonds"
			boxType = vertical
			tid = 464728768679727
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 2
				gridColumnsWidth = "15,85" !
				gridRowCount = 2
			{
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						domainAttribute = otherMktOutlook !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 85
				{
					--- Include ---
						domainAssociation = fundMktOutlook
						includeSrc = "" !
						resource:///default/extoperation/orderproposal/ReportCommentEdit.fragment
						bean-property-prefix = fundMktOutlook.
				}
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						domainAttribute = otherAdvice !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 85
				{
					--- Include ---
						domainAssociation = fundAdvice
						includeSrc = "" !
						resource:///default/extoperation/orderproposal/ReportCommentEdit.fragment
						bean-property-prefix = fundAdvice.
				}
			}
		}
		--- Box ---
			labels en = "Market Segment Comments - Derivatives", de = "Marktsegment-Kommentare - Derivate", fr = "Commentaire du segment de marché - Dérivés"
			boxType = vertical
			tid = 31552067139048
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 2
				gridColumnsWidth = "15,85" !
				gridRowCount = 2
			{
				--- GridCell ---
					gridColumnWidth = 15
					gridColumnCssClass = grey
				{
					--- LabelDomain ---
						domainAttribute = stockMktOutlook !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 85
				{
					--- Include ---
						domainAssociation = derivativeMktOutlook
						includeSrc = "" !
						resource:///default/extoperation/orderproposal/ReportCommentEdit.fragment
						bean-property-prefix = derivativeMktOutlook.
				}
				--- GridCell ---
					gridColumnWidth = 15
					gridColumnCssClass = grey
				{
					--- LabelDomain ---
						domainAttribute = stockAdvice !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 85
				{
					--- Include ---
						domainAssociation = derivativeAdvice
						includeSrc = "" !
						resource:///default/extoperation/orderproposal/ReportCommentEdit.fragment
						bean-property-prefix = derivativeAdvice.
				}
			}
		}
		--- Box ---
			labels en = "Market Segment Comments - Liquidity", de = "Marktsegment-Kommentare - Liquidität", fr = "Commentaire du segment de marché - Liquidités"
			boxType = vertical
			tid = 1813003580246961
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 2
				gridColumnsWidth = "15,85" !
				gridRowCount = 2
			{
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						domainAttribute = cashMktOutlook !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 85
				{
					--- Include ---
						domainAssociation = cashMktOutlook
						includeSrc = "" !
						resource:///default/extoperation/orderproposal/ReportCommentEdit.fragment
						bean-property-prefix = cashMktOutlook.
				}
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						domainAttribute = cashAdvice !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 85
				{
					--- Include ---
						domainAssociation = cashAdvice
						includeSrc = "" !
						resource:///default/extoperation/orderproposal/ReportCommentEdit.fragment
						bean-property-prefix = cashAdvice.
				}
			}
		}
		--- Box ---
			labels en = "Market Segment Comments - Money Market", de = "Marktsegment-Kommentare - Geldmarkt", fr = "Commentaire du segment de marché - Marché monétaire"
			boxType = vertical
			tid = 465860487058956
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 2
				gridColumnsWidth = "15,85" !
				gridRowCount = 2
			{
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						domainAttribute = bondMktOutlook !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 85
				{
					--- Include ---
						domainAssociation = moneyMarketMktOutlook
						includeSrc = "" !
						resource:///default/extoperation/orderproposal/ReportCommentEdit.fragment
						bean-property-prefix = moneyMarketMktOutlook.
				}
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						domainAttribute = bondAdvice !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 85
				{
					--- Include ---
						domainAssociation = moneyMarketAdvice
						includeSrc = "" !
						resource:///default/extoperation/orderproposal/ReportCommentEdit.fragment
						bean-property-prefix = moneyMarketAdvice.
				}
			}
		}
		--- Box ---
			labels en = "Market Segment Comments - Forwards", de = "Marktsegment-Kommentare - Devisentermin", fr = "Commentaire du segment de marché - Contrats à terme"
			boxType = vertical
			tid = 465851478806423
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 2
				gridColumnsWidth = "15,85" !
				gridRowCount = 2
			{
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						domainAttribute = otherMktOutlook !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 85
				{
					--- Include ---
						domainAssociation = forwardMktOutlook
						includeSrc = "" !
						resource:///default/extoperation/orderproposal/ReportCommentEdit.fragment
						bean-property-prefix = forwardMktOutlook.
				}
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						domainAttribute = otherAdvice !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 85
				{
					--- Include ---
						domainAssociation = forwardAdvice
						includeSrc = "" !
						resource:///default/extoperation/orderproposal/ReportCommentEdit.fragment
						bean-property-prefix = forwardAdvice.
				}
			}
		}
		--- Box ---
			labels en = "Market Segment Comments - Other", de = "Marktsegment-Kommentare - Sonstige", fr = "Commentaire du segment de marché - Autres"
			boxType = vertical
			tid = 1891323534157649
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 2
				gridColumnsWidth = "15,85" !
				gridRowCount = 2
			{
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						domainAttribute = otherMktOutlook !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 85
				{
					--- Include ---
						domainAssociation = otherMktOutlook
						includeSrc = "" !
						resource:///default/extoperation/orderproposal/ReportCommentEdit.fragment
						bean-property-prefix = otherMktOutlook.
				}
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						domainAttribute = otherAdvice !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 85
				{
					--- Include ---
						domainAssociation = otherAdvice
						includeSrc = "" !
						resource:///default/extoperation/orderproposal/ReportCommentEdit.fragment
						bean-property-prefix = otherAdvice.
				}
			}
		}
		--- Box ---
			labels en = "Additional Comments", de = "Zusätzliche Kommentare ", fr = "Commentaires additionnels"
			boxType = vertical
			tid = 1891132297425211
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 2
				gridColumnsWidth = "15,85" !
				gridRowCount = 2
			{
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						domainAttribute = openingComments !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 85
				{
					--- Include ---
						domainAssociation = openingComments
						includeSrc = "" !
						resource:///default/extoperation/orderproposal/ReportCommentEdit.fragment
						bean-property-prefix = openingComments.
				}
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						domainAttribute = closingComments !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 85
				{
					--- Include ---
						domainAssociation = closingComments
						includeSrc = "" !
						resource:///default/extoperation/orderproposal/ReportCommentEdit.fragment
						bean-property-prefix = closingComments.
				}
			}
		}
	}
}