# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = Summary, fr = Résumé, de = Zusammenfassung
	domainEntity = "AAADSOrderList:OrderListSummaryList"
	bean-define = DSBean.AAADSOrderList.OrderListSummaryList
	bean-name = OrderListSummaryList
	id = OrderListSummary_cyC_u
	tid = 456936897469074
{
	--- Box ---
		boxType = vertical
	{
		--- Matrix ---
			id = wV02u
		{
			--- MatrixAxis ---
				domainAttribute = CATEGORY_LABEL !
				matrixAxis = x-axis !
			--- MatrixAxis ---
				domainAttribute = STATUS !
				matrixAxis = y-axis !
			--- MatrixContentCell ---
				matrixCellType = content-cell !
			{
				Snippet CssClass --- Box ---
					boxType = vertical
					horizontalAlignment = trail
				{
					--- MatrixContentCellItem ---
						domainAttribute = COUNT_STATUS_ALL !
						matrixCellItemType = domain !
						horizontalAlignment = trail
						id = XV61_
						aggregationItems = "N001u,T830m,q_0_3"
				}
			}
			--- MatrixCell ---
				matrixCellType = last-cell !
			{
				--- MatrixCellItem ---
					domainAttribute = COUNT_STATUS_ALL !
					matrixCellItemType = domain !
					id = q_0_3
			}
			--- MatrixCell ---
				matrixCellType = last-row !
			{
				--- MatrixCellItem ---
					domainAttribute = COUNT_STATUS_ALL !
					matrixCellItemType = domain !
					id = T830m
				{
					Snippet CssClass
				}
			}
			--- MatrixCell ---
				matrixCellType = last-column !
			{
				--- MatrixCellItem ---
					domainAttribute = COUNT_STATUS_ALL !
					matrixCellItemType = domain !
					id = N001u
			}
			--- MatrixExtraColumn ---
				matrixCellType = extra-column !
		}
	}
}