# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = Exchange, fr = Echange, de = Austausch
	containment = container
	domainEntity = "AAADSExtOperation:ExtOperationDetail"
	bean-define = DSBean.AAADSExtOperation.ExtOperationDetail
	bean-name = ExtOperationDetail
	id = AdjExchangeView_EKjN2
	tid = 86703270104994
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/extoperation/operation/view/OperationHeaderView.module
		--- Box ---
			labels en = Identification, de = Identifikation, fr = Identification
			boxType = vertical
			widgetBorder = box
			tid = 83034058180303
		{
			--- Include ---
				includeSrc = "" !
				resource:///Default/module/aaa/administration/extoperation/operation/view/OperationTypologyView.module
			--- Include ---
				includeSrc = "" !
				resource:///default/extoperation/basicelements/PortfolioView.fragment
		}
		--- Box ---
			labels en = Operation, fr = Opération, de = Transaktion
			boxType = vertical
			widgetBorder = box
			tid = 83051742742646
		{
			--- Box ---
				labels en = Instrument, de = Instrument, fr = Instrument
				boxType = vertical
				verticalAlignment = lead
				widgetBorder = box
				tid = 82029495202398
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 4
					gridColumnsWidth = "16,16,16,48" !
					gridRowCount = 1
				{
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- LabelDomain ---
							labels en = "Instrument Name", de = "Instrument Name", fr = "Nom d’instrument"
							domainAttribute = instr !
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							tid = 175688032119724
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- Include ---
							domainAssociation = instr
							includeSrc = "" !
							resource:///default/defaultFragments/InstrumentIdentifierView.fragment
							bean-property-prefix = instr.
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- LabelDomain ---
							labels en = "Instrument Denomination", fr = "Dénomination  d’instrument", de = "Instrument Bezeichnung"
							domainAttribute = instr !
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							tid = 175699041464487
					}
					--- GridCell ---
						gridColumnWidth = 48
					{
						--- Include ---
							domainAssociation = instr
							includeSrc = "" !
							resource:///default/defaultFragments/InstrumentIdentifierDenomView.fragment
							bean-property-prefix = instr.
					}
				}
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "null != <bean:get-property bean=\"ExtOperationDetail\" property=\"instr.natureE\"/> &amp;&amp; (Integer.toString(com.odcgroup.aaa.InstrumentNatureE.FixedIncome).equals(<bean:get-property bean=\"ExtOperationDetail\" property=\"instr.natureE\"/>.toString()) || Integer.toString(com.odcgroup.aaa.InstrumentNatureE.DiscountInstrument).equals(<bean:get-property bean=\"ExtOperationDetail\" property=\"instr.natureE\"/>.toString()) || Integer.toString(com.odcgroup.aaa.InstrumentNatureE.OptionBond).equals(<bean:get-property bean=\"ExtOperationDetail\" property=\"instr.natureE\"/>.toString()) || Integer.toString(com.odcgroup.aaa.InstrumentNatureE.ConvertibleBond).equals(<bean:get-property bean=\"ExtOperationDetail\" property=\"instr.natureE\"/>.toString()))"
						technicalName = IsFixedIncome
						boxType = vertical
						isWidgetSelected = true
					{
						--- Grid ---
							cssClass = blank
							gridColumnCount = 6
							gridColumnsWidth = "16,16,16,16,16,16" !
							gridRowCount = 2
						{
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									domainAttribute = quantityN !
									for = quantityN
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- TextField ---
									domainAttribute = quantityN !
									columns = 21
									format = decimal.detailed
									horizontalAlignment = trail
									type = decimal
									chars = 21
									editable = false
									bean-property = quantityN
									id = quantityN
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									domainAttribute = quoteN !
									for = quoteN
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- Box ---
								{
									--- TextField ---
										domainAttribute = quoteN !
										columns = 21
										format = decimal.detailed
										horizontalAlignment = trail
										type = decimal
										chars = 21
										editable = false
										bean-property = quoteN
										id = quoteN
									--- Include ---
										domainAssociation = opCurrency
										includeSrc = "" !
										resource:///default/defaultFragments/CurrencyIdentifierView.fragment
										bean-property-prefix = opCurrency.
								}
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									domainAttribute = opGrossAmountM !
									for = opGrossAmountM
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- Box ---
								{
									--- TextField ---
										domainAttribute = opGrossAmountM !
										columns = 21
										format = decimal
										horizontalAlignment = trail
										type = amount
										chars = 18
										editable = false
										bean-property = opGrossAmountM
										id = opGrossAmountM
									--- Include ---
										domainAssociation = opCurrency
										includeSrc = "" !
										resource:///default/defaultFragments/CurrencyIdentifierView.fragment
										bean-property-prefix = opCurrency.
								}
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									domainAttribute = deposit !
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- Include ---
									domainAssociation = deposit
									includeSrc = "" !
									resource:///default/defaultFragments/DepositIdentifierView.fragment
									bean-property-prefix = deposit.
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									domainAttribute = accrAmountM !
									for = accrAmountM
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- Box ---
								{
									--- TextField ---
										domainAttribute = accrAmountM !
										columns = 21
										format = decimal
										horizontalAlignment = trail
										type = amount
										chars = 18
										editable = false
										bean-property = accrAmountM
										id = accrAmountM
									--- Include ---
										domainAssociation = opCurrency
										includeSrc = "" !
										resource:///default/defaultFragments/CurrencyIdentifierView.fragment
										bean-property-prefix = opCurrency.
								}
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									domainAttribute = opNetAmountM !
									for = opNetAmountM
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- Box ---
								{
									--- TextField ---
										domainAttribute = opNetAmountM !
										columns = 21
										format = decimal
										horizontalAlignment = trail
										type = amount
										chars = 21
										editable = false
										bean-property = opNetAmountM
										id = opNetAmountM
									--- Include ---
										domainAssociation = opCurrency
										includeSrc = "" !
										resource:///default/defaultFragments/CurrencyIdentifierView.fragment
										bean-property-prefix = opCurrency.
								}
							}
						}
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = IsNotFixedIncome
						boxType = vertical
						isWidgetVisible = false
					{
						--- Grid ---
							cssClass = blank
							gridColumnCount = 6
							gridColumnsWidth = "16,16,16,16,16,16" !
							gridRowCount = 2
						{
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									domainAttribute = quantityN !
									for = quantityN
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- TextField ---
									domainAttribute = quantityN !
									columns = 21
									format = decimal.detailed
									horizontalAlignment = trail
									type = decimal
									chars = 21
									editable = false
									bean-property = quantityN
									id = quantityN
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									domainAttribute = quoteN !
									for = quoteN
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- Box ---
								{
									--- TextField ---
										domainAttribute = quoteN !
										columns = 21
										format = decimal.detailed
										horizontalAlignment = trail
										type = decimal
										chars = 21
										editable = false
										bean-property = quoteN
										id = quoteN
									--- Include ---
										domainAssociation = opCurrency
										includeSrc = "" !
										resource:///default/defaultFragments/CurrencyIdentifierView.fragment
										bean-property-prefix = opCurrency.
								}
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									domainAttribute = opGrossAmountM !
									for = opGrossAmountM
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- Box ---
								{
									--- TextField ---
										domainAttribute = opGrossAmountM !
										columns = 21
										format = decimal
										horizontalAlignment = trail
										type = amount
										chars = 18
										editable = false
										bean-property = opGrossAmountM
										id = opGrossAmountM
									--- Include ---
										domainAssociation = opCurrency
										includeSrc = "" !
										resource:///default/defaultFragments/CurrencyIdentifierView.fragment
										bean-property-prefix = opCurrency.
								}
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									domainAttribute = deposit !
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- Include ---
									domainAssociation = deposit
									includeSrc = "" !
									resource:///default/defaultFragments/DepositIdentifierView.fragment
									bean-property-prefix = deposit.
							}
							--- GridCell ---
								gridColumnWidth = 16
							--- GridCell ---
								gridColumnWidth = 16
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									domainAttribute = opNetAmountM !
									for = opNetAmountM
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- Box ---
								{
									--- TextField ---
										domainAttribute = opNetAmountM !
										columns = 21
										format = decimal
										horizontalAlignment = trail
										type = amount
										chars = 21
										editable = false
										bean-property = opNetAmountM
										id = opNetAmountM
									--- Include ---
										domainAssociation = opCurrency
										includeSrc = "" !
										resource:///default/defaultFragments/CurrencyIdentifierView.fragment
										bean-property-prefix = opCurrency.
								}
							}
						}
					}
				}
			}
			--- Box ---
				labels en = "Adjusted Instrument", de = "Angepasstes Instrument", fr = "Instrument ajusté"
				boxType = vertical
				verticalAlignment = lead
				widgetBorder = box
				tid = 82039998727511
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 4
					gridColumnsWidth = "16,16,16,48" !
					gridRowCount = 1
				{
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- LabelDomain ---
							labels en = "Adjusted Instrument Name", fr = "Nom d\'instrument (ajustement)", de = "Angepasstes Instrument Name"
							domainAttribute = adjInstr !
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							tid = 175652730508486
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- Include ---
							domainAssociation = adjInstr
							includeSrc = "" !
							resource:///default/defaultFragments/InstrumentIdentifierView.fragment
							bean-property-prefix = adjInstr.
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- LabelDomain ---
							labels en = "Adjusted Instrument Denomination", fr = "Dénomination  d’instrument (ajustement)", de = "Angepasstes Instrument Bezeichnung"
							domainAttribute = adjInstr !
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							tid = 175663407069334
					}
					--- GridCell ---
						gridColumnWidth = 48
					{
						--- Include ---
							domainAssociation = adjInstr
							includeSrc = "" !
							resource:///default/defaultFragments/InstrumentIdentifierDenomView.fragment
							bean-property-prefix = adjInstr.
					}
				}
				--- Grid ---
					cssClass = blank
					gridColumnCount = 6
					gridColumnsWidth = "16,16,16,16,16,16" !
					gridRowCount = 1
				{
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- LabelDomain ---
							domainAttribute = adjQuantityN !
							for = adjQuantityN
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- TextField ---
							domainAttribute = adjQuantityN !
							columns = 21
							format = decimal.detailed
							horizontalAlignment = "${corporatehalign}"
							type = decimal
							chars = 23
							editable = false
							bean-property = adjQuantityN
							id = adjQuantityN
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- LabelDomain ---
							domainAttribute = adjDeposit !
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- Include ---
							domainAssociation = adjDeposit
							includeSrc = "" !
							resource:///default/defaultFragments/DepositIdentifierView.fragment
							bean-property-prefix = adjDeposit.
					}
					--- GridCell ---
						gridColumnWidth = 16
					--- GridCell ---
						gridColumnWidth = 16
				}
			}
		}
		--- TabbedPane ---
			id = h_6__
			indexOfSelectedChild = 2
		{
			--- Tab ---
				labels en = Details, de = Details, fr = Détails
				boxType = vertical
				id = tab_lEY7B
				isWidgetVisible = false
				tid = 83086343583814
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/extoperation/operation/view/PaymentView.module
				--- Include ---
					includeSrc = "" !
					resource:///default/extoperation/basicelements/CashPortfolioView.fragment
			}
			--- Tab ---
				labels en = Fees, de = Gebühren, fr = Frais
				id = tab_D_F_4
				isWidgetVisible = false
				tid = 83086344577852
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/extoperation/basicelements/FeesTaxesView.fragment
			}
			--- Tab ---
				labels en = Notepad, de = Notizen, fr = Bloc-note
				id = tab_f9___
				isWidgetSelected = true
				tid = 83086345571462
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/notepad/search/NotepadList.module
			}
			--- Tab ---
				labels en = Audit, de = Audit, fr = Audit
				id = tab_Dtfu6
				isWidgetVisible = false
				tid = 83086346567639
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/extoperation/basicelements/AuditView.fragment
			}
		}
	}
}