# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Margin Call", fr = "Appel de marge", de = "Margin Call"
	containment = container
	domainEntity = "AAADSExtOperation:ExtOperationDetail"
	bean-define = DSBean.AAADSExtOperation.ExtOperationDetail
	bean-name = ExtOperationDetail
	id = AdjMarginCallView_D10UJ
	tid = 81415873821772
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/extoperation/operation/view/SecuritiesIdentificationView.module
		--- Box ---
			labels en = Operation, fr = Opération, de = "Transaktion    "
			boxType = vertical
			widgetBorder = box
			tid = 31310390536955
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 6
				gridColumnsWidth = "16,16,16,16,16,16" !
				gridRowCount = 2
			{
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = quantityN !
						for = quantityN
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- TextField ---
						domainAttribute = quantityN !
						columns = 21
						format = decimal.detailed
						horizontalAlignment = trail
						type = decimal
						chars = 21
						editable = false
						bean-property = quantityN
						id = quantityN
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = quoteN !
						for = quoteN
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- Box ---
					{
						--- TextField ---
							domainAttribute = quoteN !
							columns = 21
							format = decimal.detailed
							horizontalAlignment = trail
							type = decimal
							chars = 21
							editable = false
							bean-property = quoteN
							id = quoteN
						--- Include ---
							domainAssociation = opCurrency
							includeSrc = "" !
							resource:///default/defaultFragments/CurrencyIdentifierView.fragment
							bean-property-prefix = opCurrency.
					}
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = opGrossAmountM !
						for = opGrossAmountM
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- Box ---
					{
						--- TextField ---
							domainAttribute = opGrossAmountM !
							columns = 21
							format = decimal
							horizontalAlignment = trail
							type = amount
							chars = 18
							editable = false
							bean-property = opGrossAmountM
							id = opGrossAmountM
						--- Include ---
							domainAssociation = opCurrency
							includeSrc = "" !
							resource:///default/defaultFragments/CurrencyIdentifierView.fragment
							bean-property-prefix = opCurrency.
					}
				}
				--- GridCell ---
					gridColumnWidth = 16
				--- GridCell ---
					gridColumnWidth = 16
				--- GridCell ---
					gridColumnWidth = 16
				--- GridCell ---
					gridColumnWidth = 16
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = opNetAmountM !
						for = opNetAmountM
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- Box ---
					{
						--- TextField ---
							domainAttribute = opNetAmountM !
							columns = 21
							format = decimal
							horizontalAlignment = trail
							type = amount
							chars = 21
							editable = false
							bean-property = opNetAmountM
							id = opNetAmountM
						--- Include ---
							domainAssociation = opCurrency
							includeSrc = "" !
							resource:///default/defaultFragments/CurrencyIdentifierView.fragment
							bean-property-prefix = opCurrency.
					}
				}
			}
		}
		--- Spacer ---
			height = 10
			width = 4
		--- TabbedPane ---
			id = rQ5g5
			indexOfSelectedChild = 0
		{
			--- Tab ---
				labels en = Details, fr = Détails, de = Details
				boxType = vertical
				id = tab_l4y_6
				isWidgetSelected = true
				tid = 81445968743838
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/extoperation/operation/view/PaymentView.module
				--- Include ---
					includeSrc = "" !
					resource:///default/extoperation/basicelements/CashPortfolioView.fragment
				--- Box ---
					labels en = Intermediaries, de = Vermittler, fr = Intermédiaires
					boxType = vertical
					widgetBorder = box
					tid = 622552257193243
				{
					--- Grid ---
						cssClass = blank
						gridColumnCount = 6
						gridColumnsWidth = "16,16,16,16,16,16" !
						gridRowCount = 1
					{
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = deposit !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- Include ---
								domainAssociation = deposit
								includeSrc = "" !
								resource:///default/defaultFragments/DepositIdentifierView.fragment
								bean-property-prefix = deposit.
						}
						--- GridCell ---
							gridColumnWidth = 16
						--- GridCell ---
							gridColumnWidth = 16
						--- GridCell ---
							gridColumnWidth = 16
						--- GridCell ---
							gridColumnWidth = 16
					}
				}
			}
			--- Tab ---
				labels en = Fees, fr = Frais, de = Gebühren
				id = tab_qL9EB
				isWidgetVisible = false
				tid = 81445970641663
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/extoperation/basicelements/FeesTaxesView.fragment
			}
			--- Tab ---
				labels en = Notepad, fr = Bloc-note, de = Notizen
				id = tab_W_5_4
				isWidgetVisible = false
				tid = 81445971713975
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/notepad/search/NotepadList.module
			}
			--- Tab ---
				labels en = Audit, fr = Audit, de = Audit
				id = tab_y1___
				isWidgetVisible = false
				tid = 81445972723411
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/extoperation/basicelements/AuditView.fragment
			}
		}
	}
}