# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSExtOperation:ExtOperationDetail"
	cssClass = nodeco
	bean-define = DSBean.AAADSExtOperation.ExtOperationDetail
	bean-name = ExtOperationDetail
	id = ContactView_wsQ_s
	documentation = "This sub-block is used to show the way to manage the contact between the bank and the client."
{
	--- Box ---
		labels en = Communication, de = Kommunikation, fr = Communication
		boxType = vertical
		widgetBorder = box
		tid = 1657518604406274
	{
		--- Conditional ---
			indexOfSelectedChild = 1
		{
			--- ConditionalBody ---
				javaCode = "null != <bean:get-property bean=\"ExtOperationDetail\" property=\"clientInitE\"/> &amp;&amp; \r\nInteger.toString(com.odcgroup.aaa.OperationClientInitE.Mandate).equals(<bean:get-property bean=\"ExtOperationDetail\" property=\"clientInitE\"/>.toString())"
				technicalName = UNSOLICITED
				boxType = vertical
				isWidgetVisible = false
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 6
					gridColumnsWidth = "16,16,16,16,16,16" !
					gridRowCount = 1
				{
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- LabelDomain ---
							labels en = Initiation
							domainAttribute = clientInitE !
							for = clientInitE
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							required = true
							tid = 430244022125470
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- ComboBox ---
							domainAttribute = clientInitE !
							horizontalAlignment = "${corporatehalign}"
							editable = false
							required = true
							bean-property = clientInitE
							id = clientInitE
						{
							Event OnChange (submit)
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								widget-group-ref = form
								param = "flow-action=reload"
								only-changed = true
								stabs = "<xsp-request:get-parameter name=\"stabs\"/>" ud
								modal = false
								prevalidate = false
							}
						}
					}
					--- GridCell ---
						gridColumnWidth = 16
					--- GridCell ---
						gridColumnWidth = 16
					--- GridCell ---
						gridColumnWidth = 16
					--- GridCell ---
						gridColumnWidth = 16
				}
			}
			--- ConditionalBody ---
				javaCode = true
				technicalName = Default
				boxType = vertical
				isWidgetSelected = true
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 6
					gridColumnsWidth = "16,16,16,16,16,16" !
					gridRowCount = 3
				{
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- Label ---
							labels en = Initiation, de = Initiierung, fr = Initiation
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							id = d_055
							tid = 430244023065614
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- ComboBox ---
							domainAttribute = clientInitE !
							horizontalAlignment = "${corporatehalign}"
							editable = false
							required = true
							bean-property = clientInitE
							id = clientInitE
						{
							Event OnChange (submit)
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								widget-group-ref = form
								param = "flow-action=reload"
								only-changed = true
								stabs = "<xsp-request:get-parameter name=\"stabs\"/>" ud
								modal = false
								prevalidate = false
							}
						}
					}
					--- GridCell ---
						gridColumnWidth = 16
					--- GridCell ---
						gridColumnWidth = 16
					--- GridCell ---
						gridColumnWidth = 16
					--- GridCell ---
						gridColumnWidth = 16
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- LabelDomain ---
							labels de = "Kontaktiert durch", fr = "Contacté par"
							domainAttribute = commPartyType !
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							tid = 11899970496808
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- Include ---
							domainAssociation = commPartyType
							includeSrc = "" !
							resource:///default/defaultFragments/TypeIdentifierNameView.fragment
							bean-property-prefix = commPartyType.
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- LabelDomain ---
							labels de = Kontakt-Art, fr = "Mode de contact"
							domainAttribute = communicationType !
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							tid = 11910154503156
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- Include ---
							domainAssociation = communicationType
							includeSrc = "" !
							resource:///default/defaultFragments/TypeIdentifierNameView.fragment
							bean-property-prefix = communicationType.
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- LabelDomain ---
							labels de = Kontakt-Datum, fr = "Date de contact"
							domainAttribute = communicationD !
							for = communicationD
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							tid = 11918642469084
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- CaldateField ---
							domainAttribute = communicationD !
							format = datetime.date-only
							horizontalAlignment = "${corporatehalign}"
							type = datetime
							editable = false
							bean-property = communicationD
							id = communicationD
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- LabelDomain ---
							labels en = "Client Instruction", de = Kundenanweisung, fr = "Instruction client"
							domainAttribute = remark1C !
							for = remark1C
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							tid = 430244024084888
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- TextArea ---
							domainAttribute = remark1C !
							columns = 30
							horizontalAlignment = "${corporatehalign}"
							rows = 3
							type = text
							editable = false
							bean-property = remark1C
							id = remark1C
					}
					--- GridCell ---
						gridColumnWidth = 16
					--- GridCell ---
						gridColumnWidth = 16
					--- GridCell ---
						gridColumnWidth = 16
					--- GridCell ---
						gridColumnWidth = 16
				}
			}
		}
	}
}