# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = Derivatives, fr = Dérivés, de = Derivate
	containment = container
	domainEntity = "AAADSExtOperation:ExtOperationDetail"
	bean-define = DSBean.AAADSExtOperation.ExtOperationDetail
	bean-name = ExtOperationDetail
	id = DerivativesView_y7___
	tid = 89770491976942
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/extoperation/operation/view/SecuritiesIdentificationView.module
		--- Conditional ---
			indexOfSelectedChild = 0
		{
			--- ConditionalBody ---
				javaCode = "null != <bean:get-property bean=\"ExtOperationDetail\" property=\"instr.natureE\"/> &amp;&amp; (Integer.toString(com.odcgroup.aaa.InstrumentNatureE.Option).equals(<bean:get-property bean=\"ExtOperationDetail\" property=\"instr.natureE\"/>.toString()) || Integer.toString(com.odcgroup.aaa.InstrumentNatureE.ExoticOption).equals(<bean:get-property bean=\"ExtOperationDetail\" property=\"instr.natureE\"/>.toString())|| Integer.toString(com.odcgroup.aaa.InstrumentNatureE.Swaption).equals(<bean:get-property bean=\"ExtOperationDetail\" property=\"instr.natureE\"/>.toString()))"
				technicalName = IsOption
				boxType = vertical
				isWidgetSelected = true
			{
				--- Box ---
					labels en = "Operation - Option", fr = "Opération - Option", de = "Transaktion - Option"
					boxType = vertical
					widgetBorder = box
					tid = 90213971472431
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/extoperation/operation/view/StockView.module
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/extoperation/operation/view/InstrumentOpOption.module
				}
			}
			--- ConditionalBody ---
				javaCode = "null != <bean:get-property bean=\"ExtOperationDetail\" property=\"instr.natureE\"/> &amp;&amp; Integer.toString(com.odcgroup.aaa.InstrumentNatureE.Future).equals(<bean:get-property bean=\"ExtOperationDetail\" property=\"instr.natureE\"/>.toString())"
				technicalName = IsFuture
				boxType = vertical
				isWidgetVisible = false
			{
				--- Box ---
					labels en = "Operation - Future", fr = "Opération - Future", de = "Transkation - Future"
					boxType = vertical
					widgetBorder = box
					tid = 90225067338509
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/extoperation/operation/view/FutureView.module
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/extoperation/operation/view/InstrumentOpFuture.module
				}
			}
		}
		--- Spacer ---
			height = 10
			width = 4
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/extoperation/operation/view/SecuritiesTabView.module
	}
}