# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSExtOperation:ExtOperationDetail"
	cssClass = nodeco
	bean-define = DSBean.AAADSExtOperation.ExtOperationDetail
	bean-name = ExtOperationDetail
	id = FeesTaxesView_a_s6Y
	documentation = "This sub-block provides a focus about the fees and taes associated to an operation."
{
	--- Box ---
		labels en = "Fees & Taxes", fr = "Frais & Taxes", de = "Gebühren & Steuern"
		boxType = vertical
		widgetBorder = box
		tid = 621850472680860
	{
		--- Include ---
			includeSrc = "" !
			resource:///default/extoperation/basicelements/FeesTaxesView.fragment
	}
}