# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Forex Forward/Swap", de = Devisentermingeschäft, fr = "Change à terme"
	containment = container
	domainEntity = "AAADSExtOperation:ExtOperationDetail"
	bean-define = DSBean.AAADSExtOperation.ExtOperationDetail
	bean-name = ExtOperationDetail
	id = FxForwardView_Qa5_0
	documentation = "Operation screen for Fx Forward and Fx Swap opration.\r\nIt covers any tye of operation such as instrument has nature Forward or fx Swap. It is applied for Buy/Sell, opening, closing, rollover purposes."
	tid = 122521280707743
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/extoperation/operation/view/SecuritiesIdentificationView.module
		--- Box ---
			labels en = Operation, fr = Opération, de = Transaktion
			boxType = vertical
			widgetBorder = box
			tid = 334153280535548
		{
			--- Conditional ---
				indexOfSelectedChild = 0
			{
				--- ConditionalBody ---
					javaCode = "null != <bean:get-property bean=\"ExtOperationDetail\" property=\"instr.natureE\"/> &amp;&amp; Integer.toString(com.odcgroup.aaa.InstrumentNatureE.Forward).equals(<bean:get-property bean=\"ExtOperationDetail\" property=\"instr.natureE\"/>.toString())"
					technicalName = IsForward
					boxType = vertical
					isWidgetSelected = true
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/extoperation/operation/view/FxFwdView.module
				}
				--- ConditionalBody ---
					javaCode = "null != <bean:get-property bean=\"ExtOperationDetail\" property=\"instr.natureE\"/> &amp;&amp; Integer.toString(com.odcgroup.aaa.InstrumentNatureE.ForexSwap).equals(<bean:get-property bean=\"ExtOperationDetail\" property=\"instr.natureE\"/>.toString())"
					technicalName = IsFxSwap
					boxType = vertical
					isWidgetVisible = false
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/extoperation/operation/view/FxSwapView.module
				}
			}
		}
		--- TabbedPane ---
			id = h_066
			indexOfSelectedChild = 2
		{
			--- Tab ---
				labels en = Details, de = Details, fr = Détails
				boxType = vertical
				id = tab_N5242
				isWidgetVisible = false
				tid = 122534472265609
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/extoperation/operation/view/PaymentView.module
				--- Include ---
					includeSrc = "" !
					resource:///default/extoperation/basicelements/CashPortfolioView.fragment
			}
			--- Tab ---
				labels en = Fees, de = Gebühren, fr = Frais
				boxType = vertical
				id = tab_s0_8_
				isWidgetVisible = false
				tid = 122879675975019
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/extoperation/operation/view/FeesTaxesView.module
			}
			--- Tab ---
				labels en = Ordering, fr = Ordre, de = Auftrag
				boxType = vertical
				id = tab_C_rs_
				isWidgetSelected = true
				tid = 519477880477826
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/extoperation/operation/view/OrderingView.module
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/extoperation/operation/view/ContactView.module
			}
			--- Tab ---
				labels en = Notepad, de = Notizen, fr = Bloc-note
				id = tab_r0ElK
				isWidgetVisible = false
				tid = 122566555297391
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/notepad/search/NotepadList.module
			}
			--- Tab ---
				labels en = Audit, de = Audit, fr = Audit
				id = tab_WS_9_
				isWidgetVisible = false
				tid = 410400511431480
			{
				--- Box ---
					boxType = vertical
					widgetBorder = box
				{
					--- Include ---
						includeSrc = "" !
						resource:///default/extoperation/basicelements/AuditView.fragment
				}
			}
		}
	}
}