# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	containment = container
	domainEntity = "AAADSExtOperation:ExtOperationDetail"
	cssClass = nodeco
	bean-define = DSBean.AAADSExtOperation.ExtOperationDetail
	bean-name = ExtOperationDetail
	id = FxFwdView_q5H6d
	documentation = "Operation description for buy/sell of instrument with nature forward."
{
	--- Box ---
		boxType = vertical
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 3
			gridColumnsWidth = "32,32,32" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 32
			{
				--- Box ---
					boxType = vertical
					verticalAlignment = lead
					widgetBorder = box
				{
					--- Label ---
						labels en = "Traded Currency", de = "Gehandelte Währung", fr = "Devise négociée"
						cssClass = grey
						horizontalAlignment = center
						id = F_8_3
						tid = 197606774699973
					--- Grid ---
						cssClass = blank
						gridColumnCount = 2
						gridColumnsWidth = "16,16" !
						gridRowCount = 1
					{
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- Conditional ---
								indexOfSelectedChild = 0
							{
								--- ConditionalBody ---
									javaCode = "Integer.toString(com.odcgroup.aaa.OperationNatureE.Sell).equals(<bean:get-property bean=\"ExtOperationDetail\" property=\"natureE\"/>.toString())"
									technicalName = IsSell
									boxType = vertical
									isWidgetSelected = true
								{
									--- Label ---
										labels en = Sell, fr = Vente, de = Verkauf
										cssClass = "bold red"
										horizontalAlignment = center
										id = T39_B
										tid = 1805633766111092
								}
								--- ConditionalBody ---
									javaCode = "Integer.toString(com.odcgroup.aaa.OperationNatureE.Buy).equals(<bean:get-property bean=\"ExtOperationDetail\" property=\"natureE\"/>.toString())"
									technicalName = IsBuy
									boxType = vertical
									isWidgetVisible = false
								{
									--- Label ---
										labels en = Buy, fr = Achat, de = Kauf
										cssClass = "bold green"
										horizontalAlignment = center
										id = Sc40_
										tid = 1805633781765050
								}
							}
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- Box ---
							{
								--- TextField ---
									domainAttribute = quantityN !
									columns = 21
									format = decimal.2-digits
									horizontalAlignment = "${corporatehalign}"
									type = amount
									chars = 23
									editable = false
									bean-property = quantityN
									id = quantityN
								--- Include ---
									domainAssociation = instr
									includeSrc = "" !
									resource:///default/instrument/InstrumentUnderlyingCcyView.fragment
									bean-property-prefix = instr.
							}
						}
					}
				}
			}
			--- GridCell ---
				gridColumnWidth = 32
			{
				--- Box ---
					boxType = vertical
					verticalAlignment = lead
					widgetBorder = box
				{
					--- Label ---
						labels en = "Fx Rates", de = Währungskurse, fr = "Taux de change"
						cssClass = grey
						horizontalAlignment = center
						id = k__6S
						tid = 1805900615457032
					--- Grid ---
						cssClass = blank
						gridColumnCount = 2
						gridColumnsWidth = "16,16" !
						gridRowCount = 2
					{
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								labels en = "Fx Forward Rate", fr = "Cours de change à terme"
								domainAttribute = quoteN !
								for = quoteN
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 1806598161113271
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- Box ---
							{
								--- TextField ---
									domainAttribute = quoteN !
									columns = 21
									format = decimal.6-digits
									horizontalAlignment = "${corporatehalign}"
									type = decimal
									chars = 23
									editable = false
									bean-property = quoteN
									id = quoteN
								--- Box ---
								{
									--- Include ---
										domainAssociation = instr
										includeSrc = "" !
										resource:///default/instrument/InstrumentUnderlyingCcyView.fragment
										bean-property-prefix = instr.
									--- Label ---
										labels en = /, fr = /, de = /
										horizontalAlignment = "${corporatehalign}"
										id = O2_mY
										tid = 1392710075412
									--- Include ---
										domainAssociation = fiCurrency
										includeSrc = "" !
										resource:///default/defaultFragments/CurrencyIdentifierView.fragment
										bean-property-prefix = fiCurrency.
								}
							}
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								labels en = "Fx Spot Rate", fr = "Cours de change comptant"
								domainAttribute = stopQuoteN !
								for = stopQuoteN
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 1806580345465814
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- Box ---
							{
								--- TextField ---
									domainAttribute = spotQuoteN !
									columns = 21
									format = decimal.detailed
									horizontalAlignment = "${corporatehalign}"
									type = decimal
									chars = 23
									editable = false
									bean-property = spotQuoteN
									id = spotQuoteN
								--- Box ---
								{
									--- Include ---
										domainAssociation = instr
										includeSrc = "" !
										resource:///default/instrument/InstrumentUnderlyingCcyView.fragment
										bean-property-prefix = instr.
									--- Label ---
										labels en = /, fr = /, de = /
										horizontalAlignment = "${corporatehalign}"
										id = xiO_m
										tid = 1344496675062
									--- Include ---
										domainAssociation = fiCurrency
										includeSrc = "" !
										resource:///default/defaultFragments/CurrencyIdentifierView.fragment
										bean-property-prefix = fiCurrency.
								}
							}
						}
					}
				}
			}
			--- GridCell ---
				gridColumnWidth = 32
			{
				--- Box ---
					boxType = vertical
					verticalAlignment = lead
					widgetBorder = box
				{
					--- Label ---
						labels en = "Exchanged Currency", de = Gegenwährung, fr = "Devise échangée"
						cssClass = grey
						horizontalAlignment = center
						id = Q7_JG
						tid = 197620221803385
					--- Grid ---
						cssClass = blank
						gridColumnCount = 2
						gridColumnsWidth = "16,16" !
						gridRowCount = 1
					{
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- Conditional ---
								indexOfSelectedChild = 1
							{
								--- ConditionalBody ---
									javaCode = "Integer.toString(com.odcgroup.aaa.OperationNatureE.Sell).equals(<bean:get-property bean=\"ExtOperationDetail\" property=\"natureE\"/>.toString())"
									technicalName = IsSell
									boxType = vertical
									isWidgetVisible = false
								{
									--- Label ---
										labels en = Buy, de = Kauf, fr = Achat
										cssClass = "bold green"
										horizontalAlignment = center
										id = UH_22
										tid = 1805642941778207
								}
								--- ConditionalBody ---
									javaCode = "Integer.toString(com.odcgroup.aaa.OperationNatureE.Buy).equals(<bean:get-property bean=\"ExtOperationDetail\" property=\"natureE\"/>.toString())"
									technicalName = IsBuy
									boxType = vertical
									isWidgetSelected = true
								{
									--- Label ---
										labels en = Sell, de = Verkauf, fr = Vente
										cssClass = "bold red"
										horizontalAlignment = center
										id = Rv4_0
										tid = 1805642957379983
								}
							}
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- Box ---
							{
								--- TextField ---
									domainAttribute = opGrossAmountM !
									columns = 21
									format = decimal
									horizontalAlignment = "${corporatehalign}"
									type = amount
									chars = 23
									editable = false
									bean-property = opGrossAmountM
									id = opGrossAmountM
								--- Include ---
									domainAssociation = fiCurrency
									includeSrc = "" !
									resource:///default/defaultFragments/CurrencyIdentifierView.fragment
									bean-property-prefix = fiCurrency.
							}
						}
					}
				}
			}
		}
	}
}