# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Fx Spot", de = Devisenkassa, fr = "Taux de change spot"
	containment = container
	domainEntity = "AAADSExtOperation:ExtOperationDetail"
	bean-define = DSBean.AAADSExtOperation.ExtOperationDetail
	bean-name = ExtOperationDetail
	id = FxSpotView_c_X0_
	documentation = "Operation screen for Fx Spot operation."
	tid = 335699397272982
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/extoperation/operation/view/OperationHeaderView.module
		--- Box ---
			labels en = Identification, de = Identifikation, fr = Identification
			boxType = vertical
			widgetBorder = box
			tid = 334829894769281
		{
			--- Include ---
				includeSrc = "" !
				resource:///Default/module/aaa/administration/extoperation/operation/view/OperationTypologyView.module
			--- Include ---
				includeSrc = "" !
				resource:///default/extoperation/basicelements/PortfolioView.fragment
		}
		--- Box ---
			labels en = Operation, fr = Opération, de = Transaktion
			boxType = vertical
			widgetBorder = box
			tid = 334848393783156
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 3
				gridColumnsWidth = "32,32,32" !
				gridRowCount = 1
			{
				--- GridCell ---
					gridColumnWidth = 32
				{
					--- Box ---
						boxType = vertical
						verticalAlignment = lead
						widgetBorder = box
					{
						--- Box ---
							boxType = vertical
						{
							--- Conditional ---
								indexOfSelectedChild = 0
							{
								--- ConditionalBody ---
									javaCode = "Integer.toString(com.odcgroup.aaa.OperationNatureE.Sell).equals(<bean:get-property bean=\"ExtOperationDetail\" property=\"natureE\"/>.toString())"
									technicalName = IsSell
									boxType = vertical
									isWidgetSelected = true
								{
									--- Grid ---
										cssClass = blank
										gridColumnCount = 1
										gridColumnsWidth = 25 !
										gridRowCount = 1
									{
										--- GridCell ---
											gridColumnWidth = 25
										{
											--- Label ---
												labels en = Sell, fr = Vente, de = Verkauf
												cssClass = grey
												horizontalAlignment = center
												id = wws6_
												tid = 2464125169647
										}
									}
								}
								--- ConditionalBody ---
									javaCode = "Integer.toString(com.odcgroup.aaa.OperationNatureE.Buy).equals(<bean:get-property bean=\"ExtOperationDetail\" property=\"natureE\"/>.toString())"
									technicalName = IsBuy
									boxType = vertical
									isWidgetVisible = false
								{
									--- Grid ---
										cssClass = blank
										gridColumnCount = 1
										gridColumnsWidth = 25 !
										gridRowCount = 1
									{
										--- GridCell ---
											gridColumnWidth = 25
										{
											--- Label ---
												labels en = Buy, fr = Achat, de = Kauf
												cssClass = grey
												horizontalAlignment = center
												id = b7569
												tid = 2488284492024
										}
									}
								}
							}
						}
						--- Grid ---
							cssClass = blank
							gridColumnCount = 2
							gridColumnsWidth = "16,16" !
							gridRowCount = 2
						{
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									labels en = Amount, de = Betrag, fr = Montant
									domainAttribute = quantityN !
									for = quantityN
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
									tid = 336998733738562
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- Box ---
								{
									--- TextField ---
										domainAttribute = quantityN !
										columns = 21
										format = decimal
										horizontalAlignment = "${corporatehalign}"
										type = decimal
										allow = "\'0123456789.,\'"
										chars = 23
										editable = false
										required = true
										bean-property = quantityN
										id = quantityN
									{
										Event OnChange (submit)
										{
											method = post
											call-URI = "<pageflow:continuation/>"
											widget-group-ref = form
											param = "flow-action=reload"
											only-changed = true
											modal = false
											prevalidate = false
										}
									}
									--- Include ---
										domainAssociation = opCurrency
										includeSrc = "" !
										resource:///default/defaultFragments/CurrencyIdentifierView.fragment
										bean-property-prefix = opCurrency.
								}
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									labels en = Account, de = Konto, fr = Compte
									domainAttribute = instr !
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
									tid = 336730632730794
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- Include ---
									domainAssociation = instr
									includeSrc = "" !
									resource:///default/defaultFragments/InstrumentIdentifierView.fragment
									bean-property-prefix = instr.
							}
						}
					}
				}
				--- GridCell ---
					gridColumnWidth = 32
				{
					--- Box ---
						boxType = vertical
						verticalAlignment = lead
						widgetBorder = box
					{
						--- Label ---
							labels en = "Fx Rates", de = Wechselkurs, fr = "Taux de change"
							cssClass = grey
							horizontalAlignment = center
							id = RYS__
							tid = 336955160150885
						--- Grid ---
							cssClass = blank
							gridColumnCount = 2
							gridColumnsWidth = "16,16" !
							gridRowCount = 2
						{
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									labels en = "Client Rate", de = Kunden-Kurs
									domainAttribute = accExchRate !
									for = accExchRate
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
									tid = 1648495894888
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- TextField ---
									domainAttribute = accExchRate !
									columns = 18
									format = decimal.detailed
									horizontalAlignment = "${corporatehalign}"
									type = decimal
									chars = 20
									editable = false
									required = true
									bean-property = accExchRate
									id = accExchRate
								{
									Event OnChange (submit)
									{
										method = post
										call-URI = "<pageflow:continuation/>"
										widget-group-ref = form
										param = "flow-action=reload"
										only-changed = true
										stabs = "<xsp-request:get-parameter name=\"stabs\"/>" ud
										modal = false
										prevalidate = false
									}
								}
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									labels en = "Base Rate", de = Basis-Kurs, fr = "Taux de base"
									domainAttribute = fxMarketRateN !
									for = fxMarketRateN
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
									tid = 1648496795682
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- TextField ---
									domainAttribute = fxMarketRateN !
									columns = 18
									format = decimal.detailed
									horizontalAlignment = "${corporatehalign}"
									type = decimal
									chars = 23
									editable = false
									required = true
									bean-property = fxMarketRateN
									id = fxMarketRateN
								{
									Event OnChange (submit)
									{
										method = post
										call-URI = "<pageflow:continuation/>"
										widget-group-ref = form
										param = "flow-action=reload"
										only-changed = true
										stabs = "<xsp-request:get-parameter name=\"stabs\"/>" ud
										modal = false
										prevalidate = false
									}
								}
							}
						}
					}
				}
				--- GridCell ---
					gridColumnWidth = 32
				{
					--- Box ---
						boxType = vertical
						verticalAlignment = lead
						widgetBorder = box
					{
						--- Box ---
							boxType = vertical
						{
							--- Conditional ---
								indexOfSelectedChild = 0
							{
								--- ConditionalBody ---
									javaCode = "Integer.toString(com.odcgroup.aaa.OperationNatureE.Sell).equals(<bean:get-property bean=\"ExtOperationDetail\" property=\"natureE\"/>.toString())"
									technicalName = IsSell
									boxType = vertical
									isWidgetSelected = true
								{
									--- Grid ---
										cssClass = blank
										gridColumnCount = 1
										gridColumnsWidth = 25 !
										gridRowCount = 1
									{
										--- GridCell ---
											gridColumnWidth = 25
										{
											--- Label ---
												labels en = Buy, fr = Achat, de = Kauf
												cssClass = grey
												horizontalAlignment = center
												id = p4MZI
												tid = 2474884841306
										}
									}
								}
								--- ConditionalBody ---
									javaCode = "Integer.toString(com.odcgroup.aaa.OperationNatureE.Buy).equals(<bean:get-property bean=\"ExtOperationDetail\" property=\"natureE\"/>.toString())"
									technicalName = IsBuy
									boxType = vertical
									isWidgetVisible = false
								{
									--- Grid ---
										cssClass = blank
										gridColumnCount = 1
										gridColumnsWidth = 25 !
										gridRowCount = 1
									{
										--- GridCell ---
											gridColumnWidth = 25
										{
											--- Label ---
												labels en = Sell, fr = Vente, de = Verkauf
												cssClass = grey
												horizontalAlignment = center
												id = i_CDS
												tid = 2495316391060
										}
									}
								}
							}
						}
						--- Grid ---
							cssClass = blank
							gridColumnCount = 2
							gridColumnsWidth = "16,16" !
							gridRowCount = 2
						{
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									labels en = Amount, fr = Montant, de = Betrag
									domainAttribute = accNetAmountM !
									for = accNetAmountM
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
									tid = 337005392259165
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- Box ---
								{
									--- TextField ---
										domainAttribute = accNetAmountM !
										columns = 21
										format = decimal
										horizontalAlignment = "${corporatehalign}"
										type = amount
										chars = 18
										editable = false
										bean-property = accNetAmountM
										id = accNetAmountM
									--- Include ---
										domainAssociation = accCurrency
										includeSrc = "" !
										resource:///default/defaultFragments/CurrencyIdentifierView.fragment
										bean-property-prefix = accCurrency.
								}
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- LabelDomain ---
									domainAttribute = account !
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
							}
							--- GridCell ---
								gridColumnWidth = 16
							{
								--- Include ---
									domainAssociation = account
									includeSrc = "" !
									resource:///default/defaultFragments/InstrumentIdentifierView.fragment
									bean-property-prefix = account.
							}
						}
					}
				}
			}
		}
		--- TabbedPane ---
			id = pM1E3
			indexOfSelectedChild = 0
		{
			--- Tab ---
				labels en = Details, de = Details, fr = Détails
				boxType = vertical
				id = tab_u35H_
				isWidgetSelected = true
				tid = 1803825164730131
			{
				--- Box ---
					labels en = "Cash Payment", de = Zahlung, fr = Paiement
					boxType = vertical
					widgetBorder = box
					tid = 1803825180343456
				{
					--- Grid ---
						cssClass = blank
						gridColumnCount = 6
						gridColumnsWidth = "16,16,16,16,16,16" !
						gridRowCount = 1
					{
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = account2 !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								verticalAlignment = lead
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- Box ---
								boxType = vertical
							{
								--- Include ---
									domainAssociation = account2
									includeSrc = "" !
									resource:///default/defaultFragments/InstrumentIdentifierView.fragment
									bean-property-prefix = account2.
								--- Box ---
								{
									--- TextField ---
										domainAttribute = acc2NetAmountM !
										columns = 16
										format = decimal
										horizontalAlignment = "${corporatehalign}"
										type = amount
										chars = 18
										editable = false
										bean-property = acc2NetAmountM
										id = acc2NetAmountM
									--- Include ---
										domainAssociation = acc2Currency
										includeSrc = "" !
										resource:///default/defaultFragments/CurrencyIdentifierView.fragment
										bean-property-prefix = acc2Currency.
								}
							}
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = account3 !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								verticalAlignment = lead
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- Box ---
								boxType = vertical
							{
								--- Include ---
									domainAssociation = account3
									includeSrc = "" !
									resource:///default/defaultFragments/InstrumentIdentifierView.fragment
									bean-property-prefix = account3.
								--- Box ---
								{
									--- TextField ---
										domainAttribute = acc3NetAmountM !
										columns = 16
										format = decimal
										horizontalAlignment = "${corporatehalign}"
										type = amount
										chars = 18
										editable = false
										bean-property = acc3NetAmountM
										id = acc3NetAmountM
									--- Include ---
										domainAssociation = acc3Currency
										includeSrc = "" !
										resource:///default/defaultFragments/CurrencyIdentifierView.fragment
										bean-property-prefix = acc3Currency.
								}
							}
						}
						--- GridCell ---
							gridColumnWidth = 16
						--- GridCell ---
							gridColumnWidth = 16
					}
				}
			}
			--- Tab ---
				labels en = Fees, de = Gebühren, fr = Frais
				id = tab_Wgx_3
				isWidgetVisible = false
				tid = 1803825181326801
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/extoperation/basicelements/FeesTaxesView.fragment
			}
			--- Tab ---
				labels en = Ordering, fr = Ordre, de = Auftrag
				boxType = vertical
				id = tab_E_1l9
				isWidgetVisible = false
				tid = 1803958479843571
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/extoperation/operation/view/OrderingView.module
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/extoperation/operation/view/ContactView.module
			}
			--- Tab ---
				labels en = Notepad, de = Notizen, fr = Bloc-note
				boxType = vertical
				id = tab_h5HS_
				isWidgetVisible = false
				tid = 1803825183325997
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/notepad/search/NotepadList.module
			}
			--- Tab ---
				labels en = Audit, de = Audit, fr = Audit
				id = tab_Ad9_0
				isWidgetVisible = false
				tid = 1803825182331104
			{
				--- Box ---
					boxType = vertical
					widgetBorder = box
				{
					--- Include ---
						includeSrc = "" !
						resource:///default/extoperation/basicelements/AuditView.fragment
				}
			}
		}
	}
}