# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	containment = container
	domainEntity = "AAADSExtOperation:ExtOperationDetail"
	cssClass = nodeco
	bean-define = DSBean.AAADSExtOperation.ExtOperationDetail
	bean-name = ExtOperationDetail
	id = FxSwapView_M_9j_
	documentation = "Operation description for operation about FxSwap instrument."
{
	--- Box ---
		boxType = vertical
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 3
			gridColumnsWidth = "32,32,32" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 32
			{
				--- Box ---
					boxType = vertical
					verticalAlignment = lead
					widgetBorder = box
				{
					--- Label ---
						labels en = "Traded Currency", de = "Gehandelte Währung", fr = "Devise négociée"
						cssClass = grey
						horizontalAlignment = center
						id = s__b_
						tid = 69239904020164
					--- Grid ---
						cssClass = blank
						gridColumnCount = 2
						gridColumnsWidth = "16,16" !
						gridRowCount = 2
					{
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- Conditional ---
								indexOfSelectedChild = 0
							{
								--- ConditionalBody ---
									javaCode = "Integer.toString(com.odcgroup.aaa.OperationNatureE.Sell).equals(<bean:get-property bean=\"ExtOperationDetail\" property=\"natureE\"/>.toString())"
									technicalName = IsSell
									boxType = vertical
									isWidgetSelected = true
								{
									--- Label ---
										labels en = "Sell Forward", fr = "Vente à terme", de = "Verkauf auf Termin"
										cssClass = "bold red"
										horizontalAlignment = center
										id = M7__S
										tid = 1807670652255683
								}
								--- ConditionalBody ---
									javaCode = "Integer.toString(com.odcgroup.aaa.OperationNatureE.Buy).equals(<bean:get-property bean=\"ExtOperationDetail\" property=\"natureE\"/>.toString())"
									technicalName = IsBuy
									boxType = vertical
									isWidgetVisible = false
								{
									--- Label ---
										labels en = "Buy Forward", fr = "Achat à Terme", de = "Kauf auf Termin"
										cssClass = "bold green"
										horizontalAlignment = center
										id = lim_0
										tid = 1807670667890821
								}
							}
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- Box ---
							{
								--- TextField ---
									domainAttribute = quantityN !
									columns = 21
									format = decimal.2-digits
									horizontalAlignment = "${corporatehalign}"
									type = amount
									chars = 23
									editable = false
									bean-property = quantityN
									id = quantityN
								--- Include ---
									domainAssociation = fiCurrency
									includeSrc = "" !
									resource:///default/defaultFragments/CurrencyIdentifierView.fragment
									bean-property-prefix = fiCurrency.
							}
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- Conditional ---
								indexOfSelectedChild = 0
							{
								--- ConditionalBody ---
									javaCode = "Integer.toString(com.odcgroup.aaa.OperationNatureE.Sell).equals(<bean:get-property bean=\"ExtOperationDetail\" property=\"natureE\"/>.toString())"
									technicalName = IsSell
									boxType = vertical
									isWidgetSelected = true
								{
									--- Label ---
										labels en = "Buy Spot", fr = "Achat au comptant", de = "Kauf Kassa "
										cssClass = "bold green"
										horizontalAlignment = center
										id = w56n_
										tid = 68878793809419
								}
								--- ConditionalBody ---
									javaCode = "Integer.toString(com.odcgroup.aaa.OperationNatureE.Buy).equals(<bean:get-property bean=\"ExtOperationDetail\" property=\"natureE\"/>.toString())"
									technicalName = IsBuy
									boxType = vertical
									isWidgetVisible = false
								{
									--- Label ---
										labels en = "Sell Spot", fr = "Vente au comptant", de = "Verkauf Kassa "
										cssClass = "bold red"
										horizontalAlignment = center
										id = U_8A_
										tid = 68872677703738
								}
							}
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- Box ---
							{
								--- TextField ---
									domainAttribute = quantityN !
									columns = 21
									format = decimal.2-digits
									horizontalAlignment = "${corporatehalign}"
									type = amount
									chars = 23
									editable = false
									bean-property = quantityN
									id = quantityN
								--- Include ---
									domainAssociation = fiCurrency
									includeSrc = "" !
									resource:///default/defaultFragments/CurrencyIdentifierView.fragment
									bean-property-prefix = fiCurrency.
							}
						}
					}
				}
			}
			--- GridCell ---
				gridColumnWidth = 32
			{
				--- Box ---
					boxType = vertical
					verticalAlignment = lead
					widgetBorder = box
				{
					--- Label ---
						labels en = "Fx Rates & End Date", fr = "Taux de change & maturité", de = "Devisenkurse & Fälligkeit"
						cssClass = grey
						horizontalAlignment = center
						id = J__25
						tid = 1807670668855346
					--- Grid ---
						cssClass = blank
						gridColumnCount = 2
						gridColumnsWidth = "16,16" !
						gridRowCount = 3
					{
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								labels en = "Basis Points", fr = "Point de base"
								domainAttribute = quoteN !
								for = quoteN
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 1807670669851095
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- Box ---
							{
								--- TextField ---
									domainAttribute = quoteN !
									columns = 21
									format = decimal.6-digits
									horizontalAlignment = "${corporatehalign}"
									type = decimal
									chars = 23
									editable = false
									bean-property = quoteN
									id = quoteN
								--- Box ---
								{
									--- Include ---
										domainAssociation = fiCurrency
										includeSrc = "" !
										resource:///default/defaultFragments/CurrencyIdentifierView.fragment
										bean-property-prefix = fiCurrency.
									--- Label ---
										labels en = /, fr = /, de = /
										horizontalAlignment = "${corporatehalign}"
										id = z5_x8
										tid = 1807670670851976
									--- Include ---
										domainAssociation = acc2Currency
										includeSrc = "" !
										resource:///default/defaultFragments/CurrencyIdentifierView.fragment
										bean-property-prefix = acc2Currency.
								}
							}
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								labels en = "Fx Spot Rate", fr = "Cours de change comptant"
								domainAttribute = stopQuoteN !
								for = stopQuoteN
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 1807670672788297
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- Box ---
							{
								--- TextField ---
									domainAttribute = spotQuoteN !
									columns = 21
									format = decimal.detailed
									horizontalAlignment = "${corporatehalign}"
									type = decimal
									chars = 23
									editable = false
									bean-property = spotQuoteN
									id = spotQuoteN
								--- Box ---
								{
									--- Include ---
										domainAssociation = fiCurrency
										includeSrc = "" !
										resource:///default/defaultFragments/CurrencyIdentifierView.fragment
										bean-property-prefix = fiCurrency.
									--- Label ---
										labels en = /, fr = /, de = /
										horizontalAlignment = "${corporatehalign}"
										id = d27_U
										tid = 1807670672840480
									--- Include ---
										domainAssociation = acc2Currency
										includeSrc = "" !
										resource:///default/defaultFragments/CurrencyIdentifierView.fragment
										bean-property-prefix = acc2Currency.
								}
							}
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = expirationD !
								for = expirationD
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- CaldateField ---
								domainAttribute = expirationD !
								format = datetime.date-only
								horizontalAlignment = "${corporatehalign}"
								type = datetime
								editable = false
								bean-property = expirationD
								id = expirationD
						}
					}
				}
			}
			--- GridCell ---
				gridColumnWidth = 32
			{
				--- Box ---
					boxType = vertical
					verticalAlignment = lead
					widgetBorder = box
				{
					--- Label ---
						labels en = "Exchanged Currency", de = Gegenwährung, fr = "Devise échangée"
						cssClass = grey
						horizontalAlignment = center
						id = d1j39
						tid = 69249103104058
					--- Grid ---
						cssClass = blank
						gridColumnCount = 2
						gridColumnsWidth = "16,16" !
						gridRowCount = 2
					{
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- Conditional ---
								indexOfSelectedChild = 0
							{
								--- ConditionalBody ---
									javaCode = "Integer.toString(com.odcgroup.aaa.OperationNatureE.Sell).equals(<bean:get-property bean=\"ExtOperationDetail\" property=\"natureE\"/>.toString())"
									technicalName = IsSell
									boxType = vertical
									isWidgetSelected = true
								{
									--- Label ---
										labels en = "Buy Forward", fr = "Achat à Terme", de = "Kauf auf Termin"
										cssClass = "bold green"
										horizontalAlignment = center
										id = BC8_E
										tid = 69385962918621
								}
								--- ConditionalBody ---
									javaCode = "Integer.toString(com.odcgroup.aaa.OperationNatureE.Buy).equals(<bean:get-property bean=\"ExtOperationDetail\" property=\"natureE\"/>.toString())"
									technicalName = IsBuy
									boxType = vertical
									isWidgetVisible = false
								{
									--- Label ---
										labels en = "Sell Forward", fr = "Vente à terme", de = "Verkauf auf Termin"
										cssClass = "bold red"
										horizontalAlignment = center
										id = a47_z
										tid = 69385978378392
								}
							}
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- Box ---
							{
								--- TextField ---
									domainAttribute = fxSwapFarLegAmnt !
									columns = 16
									format = decimal
									horizontalAlignment = "${corporatehalign}"
									type = amount
									chars = 18
									editable = false
									bean-property = fxSwapFarLegAmnt
									id = fxSwapFarLegAmnt
								--- Include ---
									domainAssociation = acc2Currency
									includeSrc = "" !
									resource:///default/defaultFragments/CurrencyIdentifierView.fragment
									bean-property-prefix = acc2Currency.
							}
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- Conditional ---
								indexOfSelectedChild = 1
							{
								--- ConditionalBody ---
									javaCode = "Integer.toString(com.odcgroup.aaa.OperationNatureE.Sell).equals(<bean:get-property bean=\"ExtOperationDetail\" property=\"natureE\"/>.toString())"
									technicalName = IsSell
									boxType = vertical
									isWidgetVisible = false
								{
									--- Label ---
										labels en = "Sell Spot", fr = "Vente au comptant", de = "Verkauf Kassa "
										cssClass = "bold red"
										horizontalAlignment = center
										id = n_24_
										tid = 69390115310108
								}
								--- ConditionalBody ---
									javaCode = "Integer.toString(com.odcgroup.aaa.OperationNatureE.Buy).equals(<bean:get-property bean=\"ExtOperationDetail\" property=\"natureE\"/>.toString())"
									technicalName = IsBuy
									boxType = vertical
									isWidgetSelected = true
								{
									--- Label ---
										labels en = "Buy Spot", fr = "Achat au comptant", de = "Kauf Kassa"
										cssClass = "bold green"
										horizontalAlignment = center
										id = Y_Y9_
										tid = 69390130898197
								}
							}
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- Box ---
							{
								--- TextField ---
									domainAttribute = fxSwapSpotLegAmnt !
									columns = 16
									format = decimal
									horizontalAlignment = "${corporatehalign}"
									type = amount
									chars = 18
									editable = false
									bean-property = fxSwapSpotLegAmnt
									id = fxSwapSpotLegAmnt
								--- Include ---
									domainAssociation = acc2Currency
									includeSrc = "" !
									resource:///default/defaultFragments/CurrencyIdentifierView.fragment
									bean-property-prefix = acc2Currency.
							}
						}
					}
				}
			}
		}
	}
}