# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Management Fees", de = Verwaltungsgebühr, fr = "Gestion des frais"
	containment = container
	domainEntity = "AAADSExtOperation:ExtOperationDetail"
	bean-define = DSBean.AAADSExtOperation.ExtOperationDetail
	bean-name = ExtOperationDetail
	id = GlobalFeesView_Cn50_
	documentation = "It is the operation detail view for Global Fees (aka Management Fees) operation."
	tid = 534014208360559
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///default/extoperation/operation/OperationHeaderView.fragment
		--- Box ---
			labels en = Identification, fr = Identification, de = Identifikation
			boxType = vertical
			widgetBorder = box
			tid = 592497437228687
		{
			--- Include ---
				includeSrc = "" !
				resource:///Default/module/aaa/administration/extoperation/operation/view/OperationTypologyView.module
			--- Include ---
				includeSrc = "" !
				resource:///default/extoperation/basicelements/PortfolioView.fragment
		}
		--- Box ---
			labels en = Operation, fr = Opération, de = Transaktion
			boxType = vertical
			widgetBorder = box
			tid = 592572017742550
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 6
				gridColumnsWidth = "16,16,16,16,16,16" !
				gridRowCount = 1
			{
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = account !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- Include ---
						domainAssociation = account
						includeSrc = "" !
						resource:///default/defaultFragments/InstrumentIdentifierView.fragment
						bean-property-prefix = account.
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = accNetAmountM !
						for = accNetAmountM
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- Box ---
					{
						--- TextField ---
							domainAttribute = accNetAmountM !
							columns = 16
							format = decimal
							horizontalAlignment = "${corporatehalign}"
							type = amount
							chars = 18
							editable = false
							bean-property = accNetAmountM
							id = accNetAmountM
						--- Include ---
							domainAssociation = accCurrency
							includeSrc = "" !
							resource:///default/defaultFragments/CurrencyIdentifierView.fragment
							bean-property-prefix = accCurrency.
					}
				}
				--- GridCell ---
					gridColumnWidth = 16
				--- GridCell ---
					gridColumnWidth = 16
			}
		}
		--- Spacer ---
			height = 10
			width = 4
		--- TabbedPane ---
			id = A__2_
			indexOfSelectedChild = 0
		{
			--- Tab ---
				labels en = Notepad, de = Notizen, fr = Bloc-note
				boxType = vertical
				id = tab_x2n_7
				isWidgetSelected = true
				tid = 10617414783443
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/notepad/search/NotepadList.module
			}
			--- Tab ---
				labels en = Audit, de = Audit, fr = Audit
				id = tab_pL75_
				isWidgetVisible = false
				tid = 410483334696169
			{
				--- Box ---
					boxType = vertical
					widgetBorder = box
				{
					--- Include ---
						includeSrc = "" !
						resource:///default/extoperation/basicelements/AuditView.fragment
				}
			}
		}
	}
}