# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = Income, de = Ertrag, fr = Revenu
	containment = container
	domainEntity = "AAADSExtOperation:ExtOperationDetail"
	bean-define = DSBean.AAADSExtOperation.ExtOperationDetail
	bean-name = ExtOperationDetail
	id = IncomeView_J7___
	tid = 440367843157999
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/extoperation/operation/view/SecuritiesIdentificationView.module
		--- Box ---
			labels en = Operation, fr = Opération, de = Transaktion
			boxType = vertical
			widgetBorder = box
			tid = 1712037324168423
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 6
				gridColumnsWidth = "16,16,16,16,16,16" !
				gridRowCount = 1
			{
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = quantityN !
						for = quantityN
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- TextField ---
						domainAttribute = quantityN !
						columns = 21
						format = decimal.detailed
						horizontalAlignment = "${corporatehalign}"
						type = decimal
						chars = 23
						editable = false
						bean-property = quantityN
						id = quantityN
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = opGrossAmountM !
						for = opGrossAmountM
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- Box ---
					{
						--- TextField ---
							domainAttribute = opGrossAmountM !
							columns = 21
							format = decimal
							horizontalAlignment = trail
							type = amount
							chars = 18
							editable = false
							bean-property = opGrossAmountM
							id = opGrossAmountM
						--- Include ---
							domainAssociation = opCurrency
							includeSrc = "" !
							resource:///default/defaultFragments/CurrencyIdentifierView.fragment
							bean-property-prefix = opCurrency.
					}
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = opNetAmountM !
						for = opNetAmountM
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- Box ---
					{
						--- TextField ---
							domainAttribute = opNetAmountM !
							columns = 16
							format = decimal
							horizontalAlignment = "${corporatehalign}"
							type = amount
							chars = 18
							editable = false
							bean-property = opNetAmountM
							id = opNetAmountM
						--- Include ---
							domainAssociation = opCurrency
							includeSrc = "" !
							resource:///default/defaultFragments/CurrencyIdentifierView.fragment
							bean-property-prefix = opCurrency.
					}
				}
			}
		}
		--- Spacer ---
			height = 10
			width = 4
		--- TabbedPane ---
			id = U____
			indexOfSelectedChild = 0
		{
			--- Tab ---
				labels en = Details, de = Details, fr = Détails
				boxType = vertical
				id = tab_r8F3d
				isWidgetSelected = true
				tid = 440367844233554
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/extoperation/operation/view/PaymentView.module
			}
			--- Tab ---
				labels en = Fees, de = Gebühren, fr = Frais
				id = tab_A_3p8
				isWidgetVisible = false
				tid = 440367928465768
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/extoperation/operation/view/FeesTaxesView.module
			}
			--- Tab ---
				labels en = Notepad, de = Notizen, fr = Bloc-note
				boxType = vertical
				id = tab_N_f__
				isWidgetVisible = false
				tid = 440367927248854
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/notepad/search/NotepadList.module
			}
			--- Tab ---
				labels en = Audit, de = Audit, fr = Audit
				id = tab_Qn3__
				isWidgetVisible = false
				tid = 410519039736614
			{
				--- Box ---
					boxType = vertical
					widgetBorder = box
				{
					--- Include ---
						includeSrc = "" !
						resource:///default/extoperation/basicelements/AuditView.fragment
				}
			}
		}
	}
}