# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSInstrument:InstrumentOperation"
	cssClass = nodeco
	bean-define = DSBean.AAADSInstrument.InstrumentOperation
	bean-name = InstrumentOperation
	id = InstrumentOpFra_lws1_
{
	--- Box ---
		labels en = FRA, fr = FRA, de = FRA
		boxType = vertical
		widgetBorder = box
		tid = 180746420102927
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 6
			gridColumnsWidth = "16,16,16,16,16,16" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- LabelDomain ---
					domainAttribute = underlyInstr !
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- Include ---
					domainAssociation = underlyInstr
					includeSrc = "" !
					resource:///default/defaultFragments/InstrumentIdentifierView.fragment
					bean-property-prefix = underlyInstr.
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- LabelDomain ---
					domainAttribute = accrualRuleE !
					for = accrualRuleE
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					required = true
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- ComboBox ---
					domainAttribute = accrualRuleE !
					horizontalAlignment = "${corporatehalign}"
					editable = false
					required = true
					bean-property = accrualRuleE
					id = accrualRuleE
			}
			--- GridCell ---
				gridColumnWidth = 16
			--- GridCell ---
				gridColumnWidth = 16
		}
	}
}