# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSInstrument:InstrumentOperation"
	cssClass = nodeco
	bean-define = DSBean.AAADSInstrument.InstrumentOperation
	bean-name = InstrumentOperation
	id = InstrumentOpSwap_ER___
{
	--- Box ---
		labels en = Swap, fr = Swap, de = Swap
		boxType = vertical
		widgetBorder = box
		tid = 285368535199315
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 3
			gridColumnsWidth = "32,32,32" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 32
			{
				--- Box ---
					labels en = Definition, fr = Définition, de = Definition
					boxType = vertical
					verticalAlignment = lead
					widgetBorder = box
					tid = 285061788333606
				{
					--- Grid ---
						cssClass = blank
						gridColumnCount = 2
						gridColumnsWidth = "16,16" !
						gridRowCount = 5
					{
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = subNatE !
								for = subNatE
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- ComboBox ---
								domainAttribute = subNatE !
								horizontalAlignment = "${corporatehalign}"
								editable = false
								required = true
								bean-property = subNatE
								id = subNatE
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = principalRuleE !
								for = principalRuleE
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- ComboBox ---
								domainAttribute = principalRuleE !
								horizontalAlignment = "${corporatehalign}"
								editable = false
								required = true
								bean-property = principalRuleE
								id = principalRuleE
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = beginD !
								for = beginD
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- CaldateField ---
								domainAttribute = beginD !
								format = date
								horizontalAlignment = "${corporatehalign}"
								type = date
								editable = false
								bean-property = beginD
								id = beginD
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = endD !
								for = endD
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- CaldateField ---
								domainAttribute = endD !
								format = date
								horizontalAlignment = "${corporatehalign}"
								type = date
								editable = false
								bean-property = endD
								id = endD
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = genericF !
								for = genericF
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- ComboBox ---
								domainAttribute = genericF !
								horizontalAlignment = "${corporatehalign}"
								editable = false
								required = true
								bean-property = genericF
								id = genericF
						}
					}
				}
			}
			--- GridCell ---
				gridColumnWidth = 32
			{
				--- Box ---
					labels en = "Receiving Leg", fr = "Patte receveuse", de = "Empfangende Seite"
					boxType = vertical
					verticalAlignment = lead
					widgetBorder = box
					tid = 285077955919961
				{
					--- Grid ---
						cssClass = blank
						gridColumnCount = 2
						gridColumnsWidth = "16,16" !
						gridRowCount = 5
					{
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								labels en = Currency, fr = Devise, de = Währung
								domainAttribute = refCurr !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
								tid = 32533643912005
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- Include ---
								domainAssociation = refCurr
								includeSrc = "" !
								resource:///default/defaultFragments/CurrencyIdentifierView.fragment
								bean-property-prefix = refCurr.
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = interestRateP !
								for = interestRateP
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- TextField ---
								domainAttribute = interestRateP !
								columns = 11
								format = percentTA
								horizontalAlignment = "${corporatehalign}"
								type = percent
								chars = 11
								editable = false
								bean-property = interestRateP
								id = interestRateP
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = floatInstr !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- Include ---
								domainAssociation = floatInstr
								includeSrc = "" !
								resource:///default/defaultFragments/InstrumentIdentifierView.fragment
								bean-property-prefix = floatInstr.
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = accrualRuleE !
								for = accrualRuleE
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- ComboBox ---
								domainAttribute = accrualRuleE !
								horizontalAlignment = "${corporatehalign}"
								editable = false
								required = true
								bean-property = accrualRuleE
								id = accrualRuleE
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = payFreqN !
								for = payFreqN
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- Box ---
							{
								--- TextField ---
									domainAttribute = payFreqN !
									columns = 4
									format = integer
									horizontalAlignment = "${corporatehalign}"
									type = integer
									editable = false
									bean-property = payFreqN
									id = payFreqN
								--- ComboBox ---
									domainAttribute = payFreqUnitE !
									horizontalAlignment = "${corporatehalign}"
									editable = false
									required = true
									bean-property = payFreqUnitE
									id = payFreqUnitE
							}
						}
					}
				}
			}
			--- GridCell ---
				gridColumnWidth = 32
			{
				--- Box ---
					labels en = "Paying Leg", fr = "Patte payeuse", de = "Zahlende Seite"
					boxType = vertical
					verticalAlignment = lead
					widgetBorder = box
					tid = 285087308004220
				{
					--- Grid ---
						cssClass = blank
						gridColumnCount = 2
						gridColumnsWidth = "16,16" !
						gridRowCount = 5
					{
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								labels en = Currency, fr = Devise, de = Währung
								domainAttribute = swapPaidCurr !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 32548723885298
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- Include ---
								domainAssociation = swapPaidCurr
								includeSrc = "" !
								resource:///default/defaultFragments/CurrencyIdentifierView.fragment
								bean-property-prefix = swapPaidCurr.
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								labels en = "Interest Rate", fr = "Taux d\'intérêts", de = Zinssatz
								domainAttribute = paidInterestRateP !
								for = paidInterestRateP
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 32567435733033
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- TextField ---
								domainAttribute = paidInterestRateP !
								columns = 11
								format = percentTA
								horizontalAlignment = "${corporatehalign}"
								type = percent
								chars = 11
								editable = false
								bean-property = paidInterestRateP
								id = paidInterestRateP
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								labels en = "Floating Rate Instrument", de = "Instrument mit variablem Zins"
								domainAttribute = paidFloatInstr !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 32618019825424
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- Include ---
								domainAssociation = paidFloatInstr
								includeSrc = "" !
								resource:///default/defaultFragments/InstrumentIdentifierView.fragment
								bean-property-prefix = paidFloatInstr.
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								labels de = Zuwachsregel
								domainAttribute = paidAccrualRuleE !
								for = paidAccrualRuleE
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
								tid = 32661491931795
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- ComboBox ---
								domainAttribute = paidAccrualRuleE !
								horizontalAlignment = "${corporatehalign}"
								editable = false
								required = true
								bean-property = paidAccrualRuleE
								id = paidAccrualRuleE
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								labels de = Zahlungsfrequenz
								domainAttribute = paidPayFreqN !
								for = paidPayFreqN
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 32673427837057
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- Box ---
							{
								--- TextField ---
									domainAttribute = paidPayFreqN !
									columns = 4
									format = integer
									horizontalAlignment = "${corporatehalign}"
									type = integer
									editable = false
									bean-property = paidPayFreqN
									id = paidPayFreqN
								--- ComboBox ---
									domainAttribute = paidPayFreqUnitE !
									horizontalAlignment = "${corporatehalign}"
									editable = false
									required = true
									bean-property = paidPayFreqUnitE
									id = paidPayFreqUnitE
							}
						}
					}
				}
			}
		}
	}
}