# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = Locking/Unlocking, de = Sperren/Entsperren, fr = "Verrouillage / déverrouillage"
	containment = container
	domainEntity = "AAADSExtOperation:ExtOperationDetail"
	bean-define = DSBean.AAADSExtOperation.ExtOperationDetail
	bean-name = ExtOperationDetail
	id = LockingView_Nr57_
	documentation = "This operation detail screen is applied for operation with nature locking, and it allows showing the diffrent locking nature applied."
	tid = 626841956445753
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/extoperation/operation/view/OperationHeaderView.module
		--- Box ---
			labels en = Identification, de = Identifikation, fr = Identification
			boxType = vertical
			widgetBorder = box
			tid = 330152149483369
		{
			--- Include ---
				includeSrc = "" !
				resource:///Default/module/aaa/administration/extoperation/operation/view/OperationTypologyView.module
			--- Include ---
				includeSrc = "" !
				resource:///default/extoperation/basicelements/PortfolioView.fragment
			--- Include ---
				includeSrc = "" !
				resource:///default/extoperation/basicelements/InstrumentView.fragment
		}
		--- Box ---
			labels en = Operation, fr = Opération, de = Transaktion
			boxType = vertical
			widgetBorder = box
			tid = 330158569881848
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 6
				gridColumnsWidth = "16,16,16,16,16,16" !
				gridRowCount = 1
			{
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = quantityN !
						for = quantityN
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- TextField ---
						domainAttribute = quantityN !
						columns = 21
						format = decimal.detailed
						horizontalAlignment = "${corporatehalign}"
						type = decimal
						chars = 23
						editable = false
						bean-property = quantityN
						id = quantityN
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = lockLimitD !
						for = lockLimitD
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- CaldateField ---
						domainAttribute = lockLimitD !
						format = datetime.date-only
						horizontalAlignment = "${corporatehalign}"
						type = datetime
						editable = false
						bean-property = lockLimitD
						id = lockLimitD
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = deposit !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- Include ---
						domainAssociation = deposit
						includeSrc = "" !
						resource:///default/defaultFragments/DepositIdentifierView.fragment
						bean-property-prefix = deposit.
				}
			}
		}
		--- Spacer ---
			height = 10
			width = 4
		--- TabbedPane ---
			id = x6m2N
			indexOfSelectedChild = 2
		{
			--- Tab ---
				labels en = Details, fr = Détails, de = Details
				boxType = vertical
				id = tab_d_5Xw
				isWidgetVisible = false
				tid = 330568830160239
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/extoperation/operation/view/PaymentView.module
			}
			--- Tab ---
				labels en = Fees, fr = Frais, de = Gebühren
				id = tab_T2_8O
				isWidgetVisible = false
				tid = 330597774223365
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/extoperation/operation/view/FeesTaxesView.module
			}
			--- Tab ---
				labels en = Notepad, fr = Bloc-note, de = Notizen
				id = tab_CT_tj
				isWidgetSelected = true
				tid = 330630020742628
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/notepad/search/NotepadList.module
			}
			--- Tab ---
				labels en = Audit, fr = Audit, de = Audit
				id = tab_Q__QF
				isWidgetVisible = false
				tid = 330613082722859
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/extoperation/basicelements/AuditView.fragment
			}
		}
	}
}