# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	containment = container
	domainEntity = "AAADSExtOperation:ExtOperationDetail"
	cssClass = nodeco
	bean-define = DSBean.AAADSExtOperation.ExtOperationDetail
	bean-name = ExtOperationDetail
	id = MMDepositView_g__f3
	documentation = "It is a sub-block for monye market focused on te detail of the operation done."
{
	--- Box ---
		labels en = Operation, de = Transaktion, fr = Opération
		boxType = vertical
		widgetBorder = box
		tid = 1148380492818
	{
		--- Box ---
			boxType = vertical
			widgetBorder = box
		{
			--- Grid ---
				boxType = vertical
				cssClass = blank
				gridColumnCount = 6
				gridColumnsWidth = "16,16,16,16,16,16" !
				gridRowCount = 2
			{
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						labels en = Amount, fr = Montant, de = Betrag
						domainAttribute = quantityN !
						for = quantityN
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						tid = 5571913945265
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- Box ---
					{
						--- TextField ---
							domainAttribute = quantityN !
							columns = 21
							format = decimal.detailed
							horizontalAlignment = trail
							type = decimal
							chars = 23
							editable = false
							bean-property = quantityN
							id = quantityN
						{
							Event OnChange (submit)
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								widget-group-ref = form
								param = "flow-action=reload"
								only-changed = true
								modal = false
								prevalidate = false
							}
						}
						--- Include ---
							domainAssociation = account
							includeSrc = "" !
							resource:///default/defaultFragments/InstrumentIdentifierView.fragment
							bean-property-prefix = account.
					}
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = expirationD !
						for = expirationD
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- CaldateField ---
						domainAttribute = expirationD !
						format = datetime.date-only
						horizontalAlignment = "${corporatehalign}"
						type = datetime
						editable = false
						bean-property = expirationD
						id = expirationD
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = rateP !
						for = rateP
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- TextField ---
						domainAttribute = rateP !
						columns = 11
						format = percentTA
						horizontalAlignment = "${corporatehalign}"
						type = percent
						chars = 11
						editable = false
						bean-property = rateP
						id = rateP
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = counterpartyThird !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- Include ---
						domainAssociation = counterpartyThird
						includeSrc = "" !
						resource:///default/defaultFragments/ThirdPartyIdentifierView.fragment
						bean-property-prefix = counterpartyThird.
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						labels de = Laufzeit, fr = "Durée du contrat"
						domainAttribute = contractLengthN !
						for = contractLengthN
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						tid = 12311280188124
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- Box ---
					{
						--- TextField ---
							domainAttribute = contractLengthN !
							columns = 9
							format = integer
							horizontalAlignment = "${corporatehalign}"
							type = integer
							chars = 9
							editable = false
							bean-property = contractLengthN
							id = contractLengthN
						--- ComboBox ---
							domainAttribute = contractLengthUnitE !
							horizontalAlignment = "${corporatehalign}"
							editable = false
							required = true
							bean-property = contractLengthUnitE
							id = lH32_
					}
				}
				--- GridCell ---
					gridColumnWidth = 16
				--- GridCell ---
					gridColumnWidth = 16
			}
		}
		--- Box ---
			boxType = vertical
			widgetBorder = box
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 6
				gridColumnsWidth = "16,16,16,16,16,16" !
				gridRowCount = 1
			{
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = autoRenewalE !
						for = autoRenewalE
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- ComboBox ---
						domainAttribute = autoRenewalE !
						horizontalAlignment = "${corporatehalign}"
						editable = false
						required = true
						bean-property = autoRenewalE
						id = autoRenewalE
					{
						Event OnChange (submit)
						{
							method = post
							call-URI = "<pageflow:continuation/>"
							widget-group-ref = form
							param = "flow-action=reload"
							only-changed = true
							modal = false
							prevalidate = false
						}
					}
				}
				--- GridCell ---
					gridColumnWidth = 16
				--- GridCell ---
					gridColumnWidth = 16
				--- GridCell ---
					gridColumnWidth = 16
				--- GridCell ---
					gridColumnWidth = 16
			}
			--- Grid ---
				cssClass = blank
				gridColumnCount = 6
				gridColumnsWidth = "16,16,16,16,16,16" !
				gridRowCount = 1
			{
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = renewalTreatmentE !
						for = renewalTreatmentE
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- ComboBox ---
						domainAttribute = renewalTreatmentE !
						horizontalAlignment = "${corporatehalign}"
						editable = false
						required = true
						bean-property = renewalTreatmentE
						id = renewalTreatmentE
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = renewalLengthN !
						for = renewalLengthN
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- Box ---
					{
						--- TextField ---
							domainAttribute = renewalLengthN !
							columns = 9
							format = decimal.detailed
							horizontalAlignment = "${corporatehalign}"
							type = decimal
							chars = 23
							editable = false
							bean-property = renewalLengthN
							id = renewalLengthN
						--- ComboBox ---
							domainAttribute = renewalLengthUnitE !
							horizontalAlignment = "${corporatehalign}"
							editable = false
							required = true
							bean-property = renewalLengthUnitE
							id = renewalLengthUnitE
					}
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = renewalEndValD !
						for = renewalEndValD
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- CaldateField ---
						domainAttribute = renewalEndValD !
						format = datetime.date-only
						horizontalAlignment = "${corporatehalign}"
						type = datetime
						editable = false
						bean-property = renewalEndValD
						id = renewalEndValD
				}
			}
		}
	}
}