# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Money Market", de = Geldmarkt, fr = "Marché monétaire"
	containment = container
	domainEntity = "AAADSExtOperation:ExtOperationDetail"
	bean-define = DSBean.AAADSExtOperation.ExtOperationDetail
	bean-name = ExtOperationDetail
	id = DepositView_e877_
	tid = 440037069206561
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/extoperation/operation/view/OperationHeaderView.module
		--- Box ---
			labels en = Identification, fr = Identification, de = Identifikation
			boxType = vertical
			widgetBorder = box
			tid = 1113521016587
		{
			--- Include ---
				includeSrc = "" !
				resource:///Default/module/aaa/administration/extoperation/operation/view/OperationTypologyShortView.module
			--- Include ---
				includeSrc = "" !
				resource:///default/extoperation/basicelements/PortfolioView.fragment
			--- Include ---
				includeSrc = "" !
				resource:///default/extoperation/basicelements/InstrumentView.fragment
		}
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/extoperation/operation/view/MMView.module
		--- TabbedPane ---
			id = i3_K_
			indexOfSelectedChild = 2
		{
			--- Tab ---
				labels en = Details, de = Details, fr = Détails
				boxType = vertical
				id = tab_oF_P_
				isWidgetVisible = false
				tid = 5571886729919
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/extoperation/operation/view/PaymentView.module
				--- Include ---
					includeSrc = "" !
					resource:///default/extoperation/basicelements/CashPortfolioView.fragment
			}
			--- Tab ---
				labels en = Fees, de = Gebühren, fr = Frais
				id = tab_e6fNx
				isWidgetVisible = false
				tid = 440037072534079
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/extoperation/operation/view/FeesTaxesView.module
			}
			--- Tab ---
				labels en = Ordering, fr = Ordre, de = Auftrag
				boxType = vertical
				id = tab_V9_E7
				isWidgetSelected = true
				tid = 172940192978716
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/extoperation/operation/view/OrderingView.module
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/extoperation/operation/view/TransmissionView.module
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/extoperation/operation/view/ContactView.module
			}
			--- Tab ---
				labels en = Notepad, de = Notizen, fr = Bloc-note
				id = tab_F8U_9
				isWidgetVisible = false
				tid = 440037071249278
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/notepad/search/NotepadList.module
			}
			--- Tab ---
				labels en = Audit, de = Audit, fr = Audit
				id = tab_hk_AL
				isWidgetVisible = false
				tid = 410575404057778
			{
				--- Box ---
					boxType = vertical
					widgetBorder = box
				{
					--- Include ---
						includeSrc = "" !
						resource:///default/extoperation/basicelements/AuditView.fragment
				}
			}
		}
	}
}