# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Other Operation", fr = "Autre Opération", de = "Andere Transkation"
	containment = container
	domainEntity = "AAADSExtOperation:ExtOperationDetail"
	bean-define = DSBean.AAADSExtOperation.ExtOperationDetail
	bean-name = ExtOperationDetail
	id = OthersView_l9fAo
	tid = 6671041705197
{
	--- Box ---
		boxType = vertical
		widgetBorder = box
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/extoperation/operation/view/SecuritiesIdentificationView.module
		--- Box ---
			labels en = Operation, fr = Opération, de = Transkation
			boxType = vertical
			widgetBorder = box
			tid = 1653644258669281
		{
			--- Conditional ---
				indexOfSelectedChild = 1
			{
				--- ConditionalBody ---
					javaCode = "null != <bean:get-property bean=\"ExtOperationDetail\" property=\"natureE\"/> &amp;&amp; Integer.toString(com.odcgroup.aaa.OperationNatureE.BpTransfer).equals(<bean:get-property bean=\"ExtOperationDetail\" property=\"natureE\"/>.toString())"
					technicalName = Condition
					boxType = vertical
					isWidgetVisible = false
				{
					--- Box ---
						boxType = vertical
						widgetBorder = box
					{
						--- Box ---
							boxType = vertical
						{
							--- Grid ---
								cssClass = blank
								gridColumnCount = 6
								gridColumnsWidth = "16,16,16,16,16,16" !
								gridRowCount = 1
							{
								--- GridCell ---
									gridColumnWidth = 16
								{
									--- LabelDomain ---
										domainAttribute = fromBpType !
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
								}
								--- GridCell ---
									gridColumnWidth = 16
								{
									--- Include ---
										domainAssociation = fromBpType
										includeSrc = "" !
										resource:///default/defaultFragments/BalancePositionTypeIdentifierViewNB.fragment
										bean-property-prefix = fromBpType.
								}
								--- GridCell ---
									gridColumnWidth = 16
								{
									--- LabelDomain ---
										domainAttribute = pfNetAmountM !
										for = pfNetAmountM
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
								}
								--- GridCell ---
									gridColumnWidth = 16
								{
									--- Box ---
									{
										--- TextField ---
											domainAttribute = pfNetAmountM !
											columns = 16
											format = decimal
											horizontalAlignment = "${corporatehalign}"
											type = amount
											chars = 18
											editable = false
											bean-property = pfNetAmountM
											id = pfNetAmountM
										--- Include ---
											domainAssociation = pfCurrency
											includeSrc = "" !
											resource:///default/defaultFragments/CurrencyIdentifierView.fragment
											bean-property-prefix = pfCurrency.
									}
								}
								--- GridCell ---
									gridColumnWidth = 16
								--- GridCell ---
									gridColumnWidth = 16
							}
						}
						--- Box ---
							boxType = vertical
						{
							--- Grid ---
								cssClass = blank
								gridColumnCount = 6
								gridColumnsWidth = "16,16,16,16,16,16" !
								gridRowCount = 1
							{
								--- GridCell ---
									gridColumnWidth = 16
								{
									--- LabelDomain ---
										domainAttribute = toBpType !
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
								}
								--- GridCell ---
									gridColumnWidth = 16
								{
									--- Include ---
										domainAssociation = toBpType
										includeSrc = "" !
										resource:///default/defaultFragments/BalancePositionTypeIdentifierViewNB.fragment
										bean-property-prefix = toBpType.
								}
								--- GridCell ---
									gridColumnWidth = 16
								--- GridCell ---
									gridColumnWidth = 16
								--- GridCell ---
									gridColumnWidth = 16
								--- GridCell ---
									gridColumnWidth = 16
							}
							--- Grid ---
								cssClass = blank
								gridColumnCount = 4
								gridColumnsWidth = "16,16,16,48" !
								gridRowCount = 1
							{
								--- GridCell ---
									gridColumnWidth = 16
								{
									--- LabelDomain ---
										domainAttribute = toInstr !
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
								}
								--- GridCell ---
									gridColumnWidth = 16
								{
									--- Include ---
										domainAssociation = toInstr
										includeSrc = "" !
										resource:///default/defaultFragments/InstrumentIdentifierView.fragment
										bean-property-prefix = toInstr.
								}
								--- GridCell ---
									gridColumnWidth = 16
								{
									--- LabelDomain ---
										labels en = "To Instrument Denomination", fr = "Instrument Dénomination", de = "An Instrument Bezeichnung"
										domainAttribute = toInstr !
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 1647769400293164
								}
								--- GridCell ---
									gridColumnWidth = 48
								{
									--- Include ---
										domainAssociation = toInstr
										includeSrc = "" !
										resource:///default/defaultFragments/InstrumentIdentifierDenomView.fragment
										bean-property-prefix = toInstr.
								}
							}
						}
					}
				}
				--- ConditionalBody ---
					javaCode = true
					technicalName = Default
					boxType = vertical
					isWidgetSelected = true
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/extoperation/operation/view/FixedIncomeView.module
				}
			}
		}
		--- Spacer ---
			height = 10
			width = 4
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/extoperation/operation/view/SecuritiesTabView.module
	}
}