# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSExtOperation:ExtOperationDetail"
	cssClass = nodeco
	bean-define = DSBean.AAADSExtOperation.ExtOperationDetail
	bean-name = ExtOperationDetail
	id = PaymentView_r_52_
	documentation = "This sub-block is focused on cash payment associated with an operation. It details the cash"
{
	--- Box ---
		labels en = "Cash Payment", fr = Paiement, de = Zahlung
		boxType = vertical
		widgetBorder = box
		tid = 1713812528611311
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 6
			gridColumnsWidth = "16,16,16,16,16,16" !
			gridRowCount = 2
		{
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- LabelDomain ---
					domainAttribute = account !
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					verticalAlignment = lead
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- Box ---
					boxType = vertical
				{
					--- Include ---
						domainAssociation = account
						includeSrc = "" !
						resource:///default/defaultFragments/InstrumentIdentifierView.fragment
						bean-property-prefix = account.
					--- Box ---
					{
						--- TextField ---
							domainAttribute = accNetAmountM !
							columns = 16
							format = decimal
							horizontalAlignment = "${corporatehalign}"
							type = amount
							chars = 18
							editable = false
							bean-property = accNetAmountM
							id = accNetAmountM
						--- Include ---
							domainAssociation = accCurrency
							includeSrc = "" !
							resource:///default/defaultFragments/CurrencyIdentifierView.fragment
							bean-property-prefix = accCurrency.
					}
				}
			}
			--- GridCell ---
				gridColumnWidth = 16
				gridColumnCssClass = grey
			{
				--- LabelDomain ---
					domainAttribute = account2 !
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					verticalAlignment = lead
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- Box ---
					boxType = vertical
				{
					--- Include ---
						domainAssociation = account2
						includeSrc = "" !
						resource:///default/defaultFragments/InstrumentIdentifierView.fragment
						bean-property-prefix = account2.
					--- Box ---
					{
						--- TextField ---
							domainAttribute = acc2NetAmountM !
							columns = 16
							format = decimal
							horizontalAlignment = "${corporatehalign}"
							type = amount
							chars = 18
							editable = false
							bean-property = acc2NetAmountM
							id = acc2NetAmountM
						--- Include ---
							domainAssociation = acc2Currency
							includeSrc = "" !
							resource:///default/defaultFragments/CurrencyIdentifierView.fragment
							bean-property-prefix = acc2Currency.
					}
				}
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- LabelDomain ---
					domainAttribute = account3 !
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					verticalAlignment = lead
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- Box ---
					boxType = vertical
				{
					--- Include ---
						domainAssociation = account3
						includeSrc = "" !
						resource:///default/defaultFragments/InstrumentIdentifierView.fragment
						bean-property-prefix = account3.
					--- Box ---
					{
						--- TextField ---
							domainAttribute = acc3NetAmountM !
							columns = 16
							format = decimal
							horizontalAlignment = "${corporatehalign}"
							type = amount
							chars = 18
							editable = false
							bean-property = acc3NetAmountM
							id = acc3NetAmountM
						--- Include ---
							domainAssociation = acc3Currency
							includeSrc = "" !
							resource:///default/defaultFragments/CurrencyIdentifierView.fragment
							bean-property-prefix = acc3Currency.
					}
				}
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- LabelDomain ---
					labels en = "Cash Portfolio Code", fr = "Code du portefeuille cash / port", de = "Kode des Barportfolios"
					domainAttribute = cashPortfolio !
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					verticalAlignment = lead
					tid = 17127635045236
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- Include ---
					domainAssociation = cashPortfolio
					includeSrc = "" !
					resource:///default/defaultFragments/PortfolioIdentifierView.fragment
					bean-property-prefix = cashPortfolio.
			}
			--- GridCell ---
				gridColumnWidth = 16
				gridColumnCssClass = grey
			{
				--- LabelDomain ---
					labels en = "Cash Portfolio Name", fr = "Nom du portefeuille cash / port", de = "Name des Barportfolios"
					domainAttribute = cashPortfolio !
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					verticalAlignment = lead
					tid = 17179797591872
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- Include ---
					domainAssociation = cashPortfolio
					includeSrc = "" !
					resource:///default/defaultFragments/PortfolioIdentifierNameView.fragment
					bean-property-prefix = cashPortfolio.
			}
			--- GridCell ---
				gridColumnWidth = 16
			--- GridCell ---
				gridColumnWidth = 16
		}
	}
}