# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = Redemption, de = Rückzahlung, fr = Remboursement
	containment = container
	domainEntity = "AAADSExtOperation:ExtOperationDetail"
	bean-define = DSBean.AAADSExtOperation.ExtOperationDetail
	bean-name = ExtOperationDetail
	id = RedemptionView_v7W_V
	tid = 359487606401651
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			id = Y__I_
			indexOfSelectedChild = 1
		{
			--- Tab ---
				labels en = Operation, de = Transaktion, fr = Opération
				boxType = vertical
				id = tab_a_4_Y
				isWidgetVisible = false
				tid = 359487607507378
			{
				--- Box ---
					boxType = vertical
					widgetBorder = box
				{
					--- Include ---
						includeSrc = "" !
						resource:///default/extoperation/operation/OperationHeaderView.fragment
				}
				--- Box ---
					boxType = vertical
					widgetBorder = box
				{
					--- Include ---
						includeSrc = "" !
						resource:///default/extoperation/operation/SecurityView.fragment
				}
				--- Box ---
					boxType = vertical
					widgetBorder = box
				{
					--- Grid ---
						cssClass = blank
						gridColumnCount = 4
						gridColumnsWidth = "25,25,25,25" !
						gridRowCount = 2
					{
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								domainAttribute = quantityN !
								for = quantityN
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- TextField ---
								domainAttribute = quantityN !
								columns = 21
								format = decimal.detailed
								horizontalAlignment = "${corporatehalign}"
								type = decimal
								chars = 23
								bean-property = quantityN
								id = quantityN
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								domainAttribute = quoteN !
								for = quoteN
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- TextField ---
								domainAttribute = quoteN !
								columns = 21
								format = decimal.detailed
								horizontalAlignment = "${corporatehalign}"
								type = decimal
								chars = 23
								bean-property = quoteN
								id = quoteN
						}
						--- GridCell ---
							gridColumnWidth = 25
						--- GridCell ---
							gridColumnWidth = 25
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								domainAttribute = opNetAmountM !
								for = opNetAmountM
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- TextField ---
								domainAttribute = opNetAmountM !
								columns = 16
								format = decimal
								horizontalAlignment = "${corporatehalign}"
								type = amount
								chars = 18
								bean-property = opNetAmountM
								id = opNetAmountM
						}
					}
					--- Include ---
						includeSrc = "" !
						resource:///default/extoperation/operation/MainAccountView.fragment
				}
			}
			--- Tab ---
				labels en = Notepad, de = Notiz, fr = Bloc-note
				boxType = vertical
				id = tab_b_S5C
				isWidgetSelected = true
				tid = 359487684340328
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/notepad/search/NotepadList.module
			}
		}
		--- Grid ---
			cssClass = blank
			gridColumnCount = 4
			gridColumnsWidth = "25,25,25,25" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
		}
	}
}