# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = Security, de = Wertpapier, fr = Titre
	containment = container
	domainEntity = "AAADSExtOperation:ExtOperationDetail"
	bean-define = DSBean.AAADSExtOperation.ExtOperationDetail
	bean-name = ExtOperationDetail
	id = SecurityView_X2_X_
	documentation = "This operation etail screen is mainly applicable for buy/sell operation about securities intrument. It allows supporting opening and closing."
	tid = 439983227712460
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/extoperation/operation/view/SecuritiesIdentificationView.module
		--- Conditional ---
			indexOfSelectedChild = 0
		{
			--- ConditionalBody ---
				javaCode = "null != <bean:get-property bean=\"ExtOperationDetail\" property=\"instr.natureE\"/> &amp;&amp; Integer.toString(com.odcgroup.aaa.InstrumentNatureE.Stock).equals(<bean:get-property bean=\"ExtOperationDetail\" property=\"instr.natureE\"/>.toString())"
				technicalName = IsStockEtfOption
				boxType = vertical
				isWidgetSelected = true
			{
				--- Box ---
					labels en = "Operation - Stock", fr = "Opération sur action", de = "Transaktion - Aktie"
					boxType = vertical
					widgetBorder = box
					tid = 94718150979341
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/extoperation/operation/view/StockView.module
				}
			}
			--- ConditionalBody ---
				javaCode = "null != <bean:get-property bean=\"ExtOperationDetail\" property=\"instr.natureE\"/> &amp;&amp; (Integer.toString(com.odcgroup.aaa.InstrumentNatureE.FixedIncome).equals(<bean:get-property bean=\"ExtOperationDetail\" property=\"instr.natureE\"/>.toString()) || Integer.toString(com.odcgroup.aaa.InstrumentNatureE.DiscountInstrument).equals(<bean:get-property bean=\"ExtOperationDetail\" property=\"instr.natureE\"/>.toString()) || Integer.toString(com.odcgroup.aaa.InstrumentNatureE.OptionBond).equals(<bean:get-property bean=\"ExtOperationDetail\" property=\"instr.natureE\"/>.toString()) || Integer.toString(com.odcgroup.aaa.InstrumentNatureE.ConvertibleBond).equals(<bean:get-property bean=\"ExtOperationDetail\" property=\"instr.natureE\"/>.toString()))"
				technicalName = IsFixedIncome
				boxType = vertical
				isWidgetVisible = false
			{
				--- Box ---
					labels en = "Operation - Fixed Income", fr = "Opération - Obligataire", de = "Transaktion - Anleihe"
					boxType = vertical
					widgetBorder = box
					tid = 94913618156769
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/extoperation/operation/view/FixedIncomeView.module
				}
			}
			--- ConditionalBody ---
				javaCode = "null != <bean:get-property bean=\"ExtOperationDetail\" property=\"instr.natureE\"/> &amp;&amp; Integer.toString(com.odcgroup.aaa.InstrumentNatureE.FundShare).equals(<bean:get-property bean=\"ExtOperationDetail\" property=\"instr.natureE\"/>.toString())"
				technicalName = IsFund
				boxType = vertical
				isWidgetVisible = false
			{
				--- Box ---
					labels en = "Operation - Fund Share", fr = "Opération - Fonds d\'investissement", de = "Transaktion - Fondsanteil"
					boxType = vertical
					widgetBorder = box
					tid = 94859931486529
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/extoperation/operation/view/FundView.module
				}
			}
		}
		--- Spacer ---
			height = 10
			width = 4
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/extoperation/operation/view/SecuritiesTabView.module
	}
}