# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	containment = container
	domainEntity = "AAADSExtOperation:ExtOperationDetail"
	collapsed = true
	cssClass = nodeco
	bean-define = DSBean.AAADSExtOperation.ExtOperationDetail
	bean-name = ExtOperationDetail
	id = SecuritiesTabView_A1_6_
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			id = L_O_j
			indexOfSelectedChild = 0
		{
			--- Tab ---
				labels en = Details, fr = Détails, de = Details
				boxType = vertical
				id = tab_cx_53
				documentation = "This sub-block is common to several busines caegory of operation, and it groups the tabs contains that are similar for many types of operation."
				isWidgetSelected = true
				tid = 263288124526878
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/extoperation/operation/view/PaymentView.module
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/extoperation/operation/view/IntermediariesView.module
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/extoperation/operation/view/LockInstrumentView.module
			}
			--- Tab ---
				labels en = Fees, fr = Frais, de = Gebühren
				id = tab_Z0_S_
				isWidgetVisible = false
				tid = 263288125525197
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/extoperation/basicelements/FeesTaxesView.fragment
			}
			--- Tab ---
				labels en = Ordering, fr = Ordre, de = Auftrag
				boxType = vertical
				id = tab_u8Nn_
				isWidgetVisible = false
				tid = 263288126541054
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/extoperation/operation/view/OrderingView.module
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/extoperation/operation/view/TransmissionView.module
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/extoperation/operation/view/ContactView.module
			}
			--- Tab ---
				labels en = Notepad, de = Notizen, fr = Bloc-note
				id = tab_S_552
				isWidgetVisible = false
				tid = 263288127522264
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/notepad/search/NotepadList.module
			}
			--- Tab ---
				labels en = Audit, fr = Audit, de = Audit
				id = tab_y1___
				isWidgetVisible = false
				tid = 263288128521866
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/extoperation/basicelements/AuditView.fragment
			}
		}
	}
}