# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSExtOperation:ExtOperationDetail"
	cssClass = nodeco
	bean-define = DSBean.AAADSExtOperation.ExtOperationDetail
	bean-name = ExtOperationDetail
	id = StockView_S08_v
	documentation = "This sub-block of securities operation screen is specialized or instrument with nature stock, options, exotic option."
{
	--- Box ---
		boxType = vertical
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 6
			gridColumnsWidth = "16,16,16,16,16,16" !
			gridRowCount = 2
		{
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- LabelDomain ---
					domainAttribute = quantityN !
					for = quantityN
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- TextField ---
					domainAttribute = quantityN !
					columns = 21
					format = decimal.detailed
					horizontalAlignment = trail
					type = decimal
					chars = 21
					editable = false
					bean-property = quantityN
					id = quantityN
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- LabelDomain ---
					domainAttribute = quoteN !
					for = quoteN
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- Box ---
				{
					--- TextField ---
						domainAttribute = quoteN !
						columns = 21
						format = decimal.detailed
						horizontalAlignment = trail
						type = decimal
						chars = 21
						editable = false
						bean-property = quoteN
						id = quoteN
					--- Include ---
						domainAssociation = opCurrency
						includeSrc = "" !
						resource:///default/defaultFragments/CurrencyIdentifierView.fragment
						bean-property-prefix = opCurrency.
				}
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- LabelDomain ---
					domainAttribute = opGrossAmountM !
					for = opGrossAmountM
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- Box ---
				{
					--- TextField ---
						domainAttribute = opGrossAmountM !
						columns = 21
						format = decimal
						horizontalAlignment = trail
						type = amount
						chars = 18
						editable = false
						bean-property = opGrossAmountM
						id = opGrossAmountM
					--- Include ---
						domainAssociation = opCurrency
						includeSrc = "" !
						resource:///default/defaultFragments/CurrencyIdentifierView.fragment
						bean-property-prefix = opCurrency.
				}
			}
			--- GridCell ---
				gridColumnWidth = 16
			--- GridCell ---
				gridColumnWidth = 16
			--- GridCell ---
				gridColumnWidth = 16
			--- GridCell ---
				gridColumnWidth = 16
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- LabelDomain ---
					domainAttribute = opNetAmountM !
					for = opNetAmountM
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- Box ---
				{
					--- TextField ---
						domainAttribute = opNetAmountM !
						columns = 21
						format = decimal
						horizontalAlignment = trail
						type = amount
						chars = 21
						editable = false
						bean-property = opNetAmountM
						id = opNetAmountM
					--- Include ---
						domainAssociation = opCurrency
						includeSrc = "" !
						resource:///default/defaultFragments/CurrencyIdentifierView.fragment
						bean-property-prefix = opCurrency.
				}
			}
		}
	}
}