# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSExtOperation:ExtOperationDetail"
	cssClass = nodeco
	bean-define = DSBean.AAADSExtOperation.ExtOperationDetail
	bean-name = ExtOperationDetail
	id = TransmissionView_e04__
{
	--- Box ---
		labels en = Transmission, fr = Transmission, de = Übermittlung
		boxType = vertical
		widgetBorder = box
		tid = 102172812772085
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 6
			gridColumnsWidth = "16,16,16,16,16,16" !
			gridRowCount = 3
		{
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- LabelDomain ---
					domainAttribute = orderModeType !
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- Include ---
					domainAssociation = orderModeType
					includeSrc = "" !
					resource:///default/defaultFragments/TypeIdentifierNameView.fragment
					bean-property-prefix = orderModeType.
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- LabelDomain ---
					labels de = Übermittlungsart, fr = "Mode de transmission"
					domainAttribute = transmissionType !
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					tid = 18387216999925
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- Include ---
					domainAssociation = transmissionType
					includeSrc = "" !
					resource:///default/defaultFragments/TypeIdentifierNameView.fragment
					bean-property-prefix = transmissionType.
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- LabelDomain ---
					labels de = Übermittlungsdatum, fr = "Date de transmission"
					domainAttribute = transmissionD !
					for = transmissionD
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					tid = 18409457770191
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- CaldateField ---
					domainAttribute = transmissionD !
					format = datetime.date-only
					horizontalAlignment = "${corporatehalign}"
					type = datetime
					editable = false
					bean-property = transmissionD
					id = transmissionD
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- LabelDomain ---
					domainAttribute = traderManager !
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- Include ---
					domainAssociation = traderManager
					includeSrc = "" !
					resource:///default/defaultFragments/ManagerIdentifierView.fragment
					bean-property-prefix = traderManager.
			}
			--- GridCell ---
				gridColumnWidth = 16
			--- GridCell ---
				gridColumnWidth = 16
			--- GridCell ---
				gridColumnWidth = 16
			--- GridCell ---
				gridColumnWidth = 16
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- LabelDomain ---
					labels en = "Trader Instruction", fr = "Instruction de l\'opérateur boursier", de = Handlungsanweisungen
					domainAttribute = remarkC !
					for = remarkC
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					tid = 102245218417097
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- TextField ---
					domainAttribute = remarkC !
					columns = 30
					horizontalAlignment = "${corporatehalign}"
					type = text
					chars = 80
					editable = false
					bean-property = remarkC
					id = remarkC
			}
			--- GridCell ---
				gridColumnWidth = 16
			--- GridCell ---
				gridColumnWidth = 16
			--- GridCell ---
				gridColumnWidth = 16
			--- GridCell ---
				gridColumnWidth = 16
		}
	}
}