<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="t24ui" nsURI="http://www.temenos.com/DS/t24ui" nsPrefix="t24ui">
  <eClassifiers xsi:type="ecore:EClass" name="AvailableCOSPatterns">
    <eStructuralFeatures xsi:type="ecore:EReference" name="patterns" upperBound="-1"
        eType="#//cos/pattern/COSPattern" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeScreen" eSuperTypes="#//cos/pattern/AbstractCOS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="domain" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="menuDslName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="topLevelCOS" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BespokeCompositeScreen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sections" upperBound="-1"
        eType="#//cos/bespoke/Section" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AvailableTranslationLanguages">
    <eStructuralFeatures xsi:type="ecore:EReference" name="languages" upperBound="-1"
        eType="#//common/Language" containment="true"/>
  </eClassifiers>
  <eSubpackages name="common" nsURI="http://www.temenos.com/DS/t24ui/common" nsPrefix="common">
    <eClassifiers xsi:type="ecore:EClass" name="Language">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Translation">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="language" eType="#//common/Language"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="contextEnquiry" nsURI="http://www.temenos.com/DS/t24ui/contextEnquiry"
      nsPrefix="contextEnquiry">
    <eClassifiers xsi:type="ecore:EClass" name="ContextEnquiry" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="descriptions" upperBound="-1"
          eType="#//contextEnquiry/Description" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="enquiries" upperBound="-1"
          eType="#//contextEnquiry/AppliedEnquiry" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Description">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lang" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SelectionCriteria">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="appField" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operand" eType="#//contextEnquiry/Operand"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="sortOrder" eType="#//contextEnquiry/SortOrder"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="SortOrder">
      <eLiterals name="Ascending"/>
      <eLiterals name="Descending" value="1"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="Operand">
      <eLiterals name="None"/>
      <eLiterals name="Equals" value="1"/>
      <eLiterals name="NotEquals" value="2"/>
      <eLiterals name="Greater" value="3"/>
      <eLiterals name="GreaterOrEquals" value="4"/>
      <eLiterals name="LessThan" value="5" literal=""/>
      <eLiterals name="LessOrEquals" value="6"/>
      <eLiterals name="Matches" value="7"/>
      <eLiterals name="NotMatches" value="8"/>
      <eLiterals name="Between" value="9"/>
      <eLiterals name="NotBetween" value="10"/>
      <eLiterals name="Contains" value="11"/>
      <eLiterals name="DoesNotContain" value="12"/>
      <eLiterals name="BeginsWith" value="13"/>
      <eLiterals name="DoesNotBeginWith" value="14"/>
      <eLiterals name="EndsWith" value="15"/>
      <eLiterals name="DoesNotEndWith" value="16"/>
      <eLiterals name="SoundsLike" value="17"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AutoLaunch" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="AppliedEnquiry">
      <eStructuralFeatures xsi:type="ecore:EReference" name="enquiry" eType="ecore:EClass ../../com.odcgroup.t24.enquiry.model/model/generated/Enquiry.ecore#//Enquiry"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="selectionFields" upperBound="-1"
          eType="#//contextEnquiry/SelectionCriteria" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="descriptions" upperBound="-1"
          eType="#//contextEnquiry/Description" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="autoLaunch" eType="#//contextEnquiry/AutoLaunch"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ApplicationContextEnquiry" eSuperTypes="#//contextEnquiry/ContextEnquiry">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="appliesToField" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="appliesTo" eType="ecore:EClass ../../com.odcgroup.mdf.ecore/src/main/model/mdf.ecore#//MdfClass"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VersionContextEnquiry" eSuperTypes="#//contextEnquiry/ContextEnquiry">
      <eStructuralFeatures xsi:type="ecore:EReference" name="appliesTo" eType="ecore:EClass ../../com.odcgroup.t24.version.model/model/generated/VersionDSL.ecore#//Version"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="appliesToField" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="FunctionEnum">
      <eLiterals name="Authorise" literal="Authorise"/>
      <eLiterals name="SecondLevelAuthorise" value="1"/>
      <eLiterals name="Copy" value="2"/>
      <eLiterals name="Delete" value="3"/>
      <eLiterals name="Exception" value="4"/>
      <eLiterals name="HistoryRestore" value="5" literal="HistoryRestore"/>
      <eLiterals name="Input" value="6"/>
      <eLiterals name="List" value="7"/>
      <eLiterals name="Print" value="8"/>
      <eLiterals name="Audit" value="9"/>
      <eLiterals name="Reverse" value="10"/>
      <eLiterals name="See" value="11"/>
      <eLiterals name="Verify" value="12"/>
      <eLiterals name="OnHold" value="13"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Function">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="function" eType="#//contextEnquiry/FunctionEnum"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FunctionAutoLaunch" eSuperTypes="#//contextEnquiry/AutoLaunch">
      <eStructuralFeatures xsi:type="ecore:EReference" name="functions" upperBound="-1"
          eType="#//contextEnquiry/Function" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OnChangeAutoLaunch" eSuperTypes="#//contextEnquiry/AutoLaunch"/>
  </eSubpackages>
  <eSubpackages name="cos" nsURI="http://www.temenos.com/DS/t24ui/cos" nsPrefix="cos">
    <eSubpackages name="pattern" nsURI="http://www.temenos.com/DS/t24ui/cos/pattern"
        nsPrefix="pattern">
      <eClassifiers xsi:type="ecore:EClass" name="COSPanel" abstract="true">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="hostableContentAll"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="hostableBespokeCOSContentAll"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="hostableBespokeCOSContent"
            upperBound="-1" eType="#//BespokeCompositeScreen"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="hostableCOSContentAll"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="hostableCOSContent"
            upperBound="-1" eType="#//CompositeScreen"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="hostableEnquiryContentAll"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="hostableEnquiryContent"
            upperBound="-1" eType="ecore:EClass ../../com.odcgroup.t24.enquiry.model/model/generated/Enquiry.ecore#//Enquiry"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="hostableScreenContentAll"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="hostableScreenContent"
            upperBound="-1" eType="ecore:EClass ../../com.odcgroup.t24.version.model/model/generated/VersionDSL.ecore#//Version"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="title" upperBound="-1"
            eType="#//common/Translation" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="backgroundColor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
            defaultValueLiteral="auto"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
            defaultValueLiteral="auto"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="horizontalOverflowOption"
            eType="#//cos/pattern/PanelOverflowOption"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="verticalOverflowOption"
            eType="#//cos/pattern/PanelOverflowOption"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SingleComponentPanel" eSuperTypes="#//cos/pattern/COSPanel">
        <eStructuralFeatures xsi:type="ecore:EReference" name="initialContent" eType="#//cos/pattern/InitialPanelContentSpec"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="MultiComponentPanel" eSuperTypes="#//cos/pattern/ChildResourceSpec #//cos/pattern/COSPanel #//cos/pattern/COSPatternContainer">
        <eStructuralFeatures xsi:type="ecore:EReference" name="childPanels" lowerBound="1"
            upperBound="-1" eType="#//cos/pattern/COSPanel" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="InitialPanelContentSpec" abstract="true"/>
      <eClassifiers xsi:type="ecore:EClass" name="InitialCOS" eSuperTypes="#//cos/pattern/ChildResourceSpec">
        <eStructuralFeatures xsi:type="ecore:EReference" name="compositeScreen" eType="#//CompositeScreen"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="InlineInitialCOS" eSuperTypes="#//cos/pattern/AbstractCOS #//cos/pattern/ChildResourceSpec"/>
      <eClassifiers xsi:type="ecore:EClass" name="InitialBespokeCOS" eSuperTypes="#//cos/pattern/ChildResourceSpec">
        <eStructuralFeatures xsi:type="ecore:EReference" name="compositeScreen" eType="#//BespokeCompositeScreen"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="InitialEnquiry" eSuperTypes="#//cos/pattern/ChildResourceSpec">
        <eStructuralFeatures xsi:type="ecore:EReference" name="enquiry" eType="ecore:EClass ../../com.odcgroup.t24.enquiry.model/model/generated/Enquiry.ecore#//Enquiry"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="InitialScreen" eSuperTypes="#//cos/pattern/ChildResourceSpec">
        <eStructuralFeatures xsi:type="ecore:EReference" name="screen" eType="ecore:EClass ../../com.odcgroup.t24.version.model/model/generated/VersionDSL.ecore#//Version"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="AbstractCOS" abstract="true" eSuperTypes="#//cos/pattern/COSPatternContainer">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="panels" lowerBound="1"
            upperBound="-1" eType="#//cos/pattern/COSPanel" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="title" upperBound="-1"
            eType="#//common/Translation" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="COSPatternContainer" abstract="true">
        <eStructuralFeatures xsi:type="ecore:EReference" name="pattern" lowerBound="1"
            eType="#//cos/pattern/COSPattern"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="panelSeparatorOption"
            eType="#//cos/pattern/PanelSeparatorOption"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="accordionPatternMultiExpandable"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="COSPattern">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="patternSpecificAttributeNames"
            upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="PanelSeparatorOption">
        <eLiterals name="NO_SEPARATORS"/>
        <eLiterals name="FIXED_POSITION_SEPARATORS" value="1"/>
        <eLiterals name="PANEL_RESIZE_BAR_SEPARATORS" value="2"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="PanelOverflowOption">
        <eLiterals name="HIDE_OVERFLOW"/>
        <eLiterals name="SHOW_SCROLLBAR_ALWAYS"/>
        <eLiterals name="SHOW_SCROLLBAR_IF_NEEDED"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ChildResourceSpec" abstract="true"
          eSuperTypes="#//cos/pattern/InitialPanelContentSpec">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameters" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="InitialURL" eSuperTypes="#//cos/pattern/InitialPanelContentSpec">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="bespoke" nsURI="http://www.temenos.com/DS/t24ui/cos/bespoke"
        nsPrefix="bespoke">
      <eClassifiers xsi:type="ecore:EClass" name="Section">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="resources" upperBound="-1"
            eType="#//cos/bespoke/Panel" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Panel" abstract="true"/>
      <eClassifiers xsi:type="ecore:EClass" name="VersionPanel" eSuperTypes="#//cos/bespoke/Panel">
        <eStructuralFeatures xsi:type="ecore:EReference" name="version" eType="ecore:EClass ../../com.odcgroup.t24.version.model/model/generated/VersionDSL.ecore#//Version"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="EnquiryPanel" eSuperTypes="#//cos/bespoke/Panel">
        <eStructuralFeatures xsi:type="ecore:EReference" name="enquiry" eType="ecore:EClass ../../com.odcgroup.t24.enquiry.model/model/generated/Enquiry.ecore#//Enquiry"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ApplicationPanel" eSuperTypes="#//cos/bespoke/Panel">
        <eStructuralFeatures xsi:type="ecore:EReference" name="application" eType="ecore:EClass ../../com.odcgroup.mdf.ecore/src/main/model/mdf.ecore#//MdfClass"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
