# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Client Summary Views", fr = "Vues résumées client", de = "Kunde Zusammenfassung"
	domainEntity = "AAADSPerformance:PerformanceIBPASummary"
	bean-define = DSBean.AAADSPerformance.PerformanceIBPASummary
	bean-name = PerformanceIBPASummary
	id = PerformanceIBPAClientSummaryForDetails_pE6_y
	tid = 203051923879858
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			id = yh_jX
			table-column-count = 17 !
			table-columns-width = "5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5" !
		{
			--- TableColumn ---
				column-name = CLIENT_NAME !
				column-type = domain !
				domainAttribute = CLIENT_NAME !
				type = text
				id = CLIENT_NAME
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = CLIENT_NAME
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Initial Market Value", fr = "Valeur d\'inventaire initiale", de = Anfangs-Marktwert
				column-name = InitialMarketValue
				type = amount
				column-visibility = not-visible
				id = R8q3_
				column-computation = make-amount
				column-computation-parameters = "INITIAL_MARKET_VALUE,REF_CURRENCY"
				table-column-width = 5
				tid = 203051939456053
			{
				--- TableColumnItem ---
					item-column = InitialMarketValue
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Final Market Value", fr = "Valeur d\'inventaire finale", de = End-Marktwert
				column-name = FinalMarketValue
				type = amount
				column-visibility = not-visible
				id = K_s26
				column-computation = make-amount
				column-computation-parameters = "FINAL_MARKET_VALUE,REF_CURRENCY"
				table-column-width = 5
				tid = 203051941398646
			{
				--- TableColumnItem ---
					item-column = FinalMarketValue
					previewValue = value
			}
			--- TableColumn ---
				column-name = PTF_RETURN !
				column-type = domain !
				domainAttribute = PTF_RETURN !
				type = text
				id = PTF_RETURN
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = PTF_RETURN
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = BENCHMARK1_FULL_NAME !
				column-type = domain !
				domainAttribute = BENCHMARK1_FULL_NAME !
				type = text
				id = BENCHMARK1_FULL_NAME
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = BENCHMARK1_FULL_NAME
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_RETURN !
				column-type = domain !
				domainAttribute = B1_RETURN !
				type = text
				id = B1_RETURN
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = B1_RETURN
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_BENCHMARK_FACTOR !
				column-type = domain !
				domainAttribute = B1_BENCHMARK_FACTOR !
				type = text
				id = B1_BENCHMARK_FACTOR
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = B1_BENCHMARK_FACTOR
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = IB1_EFFECT_DENOM !
				column-type = domain !
				domainAttribute = IB1_EFFECT_DENOM !
				type = text
				id = IB1_EFFECT_DENOM
				table-column-width = 5
			{
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "<udp:item column=\"IB1_EFFECT_DENOM\"/>!=null"
						technicalName = "Effect 1"
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips en = "View Effect 1 Details", fr = "Voir les détails de l\'effet 1", de = "Details des Effekts 1 ansehen"
							icon = application_form_magnify
							id = x35_W
							tid = 203051943349940
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = popup
								flow-action = getEffect1 ud
								only-changed = false
								prevalidate = false
								modal = false
								Snippet FilterSet
								id = fs_5NL
								level = 1
								targetDataset = "AAADSPerformance:PerformanceIBPAEffectFocusDetails"
								{
									Snippet Filter
									attribute = IB1_EFFECT_CODE
									filterValue = "<udp:item column=\"IB1_EFFECT_CODE\"/>"
									operator = EQUAL
								}
							}
						}
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetVisible = false
				}
				--- Spacer ---
					height = 4
					width = 10
				--- TableColumnItem ---
					item-column = IB1_EFFECT_DENOM
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_IB1_EFFECT !
				column-type = domain !
				domainAttribute = B1_IB1_EFFECT !
				type = text
				id = B1_IB1_EFFECT
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = B1_IB1_EFFECT
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = IB2_EFFECT_DENOM !
				column-type = domain !
				domainAttribute = IB2_EFFECT_DENOM !
				type = text
				id = IB2_EFFECT_DENOM
				table-column-width = 5
			{
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "<udp:item column=\"IB2_EFFECT_DENOM\"/>!=null"
						technicalName = "Effect 2"
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips en = "View Effect 2 Details", fr = "Voir les détails de l\'effet 2", de = "Details des Effekts 2 ansehen"
							icon = application_form_magnify
							id = dK709
							tid = 203051945399333
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = popup
								flow-action = getEffect2 ud
								only-changed = false
								prevalidate = false
								modal = false
								Snippet FilterSet
								id = fs_5NL
								level = 1
								targetDataset = "AAADSPerformance:PerformanceIBPAEffectFocusDetails"
								{
									Snippet Filter
									attribute = IB2_EFFECT_CODE
									filterValue = "<udp:item column=\"IB2_EFFECT_CODE\"/>"
									operator = EQUAL
								}
							}
						}
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetVisible = false
				}
				--- Spacer ---
					height = 4
					width = 10
				--- TableColumnItem ---
					item-column = IB2_EFFECT_DENOM
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_IB2_EFFECT !
				column-type = domain !
				domainAttribute = B1_IB2_EFFECT !
				type = text
				id = B1_IB2_EFFECT
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = B1_IB2_EFFECT
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = IB3_EFFECT_DENOM !
				column-type = domain !
				domainAttribute = IB3_EFFECT_DENOM !
				type = text
				id = IB3_EFFECT_DENOM
				table-column-width = 5
			{
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "<udp:item column=\"IB3_EFFECT_DENOM\"/>!=null"
						technicalName = "Effect 3"
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips de = "Details des Effekts 3 ansehen", fr = "Voir les détails de l\'effet 3", en = "View Effect 3 Details"
							icon = application_form_magnify
							id = GBt_I
							tid = 203051947256368
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = popup
								flow-action = getEffect3 ud
								only-changed = false
								prevalidate = false
								modal = false
								Snippet FilterSet
								id = fs_5NL
								level = 1
								targetDataset = "AAADSPerformance:PerformanceIBPAEffectFocusDetails"
								{
									Snippet Filter
									attribute = IB3_EFFECT_CODE
									filterValue = "<udp:item column=\"IB3_EFFECT_CODE\"/>"
									operator = EQUAL
								}
							}
						}
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetVisible = false
				}
				--- Spacer ---
					height = 4
					width = 10
				--- TableColumnItem ---
					item-column = IB3_EFFECT_DENOM
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_IB3_EFFECT !
				column-type = domain !
				domainAttribute = B1_IB3_EFFECT !
				type = text
				id = B1_IB3_EFFECT
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = B1_IB3_EFFECT
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = IB4_EFFECT_DENOM !
				column-type = domain !
				domainAttribute = IB4_EFFECT_DENOM !
				type = text
				column-visibility = not-visible
				id = IB4_EFFECT_DENOM
				table-column-width = 5
			{
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "<udp:item column=\"IB4_EFFECT_DENOM\"/>!=null"
						technicalName = "Effect 4"
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips en = "View Effect 4 Details", fr = "Voir les détails de l\'effet 4", de = "Details des Effekts 4 ansehen"
							icon = application_form_magnify
							id = ay_z5
							tid = 203051949209819
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = popup
								flow-action = getEffect4 ud
								only-changed = false
								prevalidate = false
								modal = false
								Snippet FilterSet
								id = fs_5NL
								level = 1
								targetDataset = "AAADSPerformance:PerformanceIBPAEffectFocusDetails"
								{
									Snippet Filter
									attribute = IB4_EFFECT_CODE
									filterValue = "<udp:item column=\"IB4_EFFECT_CODE\"/>"
									operator = EQUAL
								}
							}
						}
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetVisible = false
				}
				--- Spacer ---
					height = 4
					width = 10
				--- TableColumnItem ---
					item-column = IB4_EFFECT_DENOM
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_IB4_EFFECT !
				column-type = domain !
				domainAttribute = B1_IB4_EFFECT !
				type = text
				column-visibility = not-visible
				id = B1_IB4_EFFECT
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = B1_IB4_EFFECT
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = IB5_EFFECT_DENOM !
				column-type = domain !
				domainAttribute = IB5_EFFECT_DENOM !
				type = text
				column-visibility = not-visible
				id = IB5_EFFECT_DENOM
				table-column-width = 5
			{
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "<udp:item column=\"IB5_EFFECT_DENOM\"/>!=null"
						technicalName = "Effect 5"
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips de = "Details des Effekts 5 ansehen", en = "View Effect 5 Details", fr = "Voir les détails de l\'effet 5"
							icon = application_form_magnify
							id = L_M1s
							tid = 203051951160682
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = popup
								flow-action = getEffect5 ud
								only-changed = false
								prevalidate = false
								modal = false
								Snippet FilterSet
								id = fs_5NL
								level = 1
								targetDataset = "AAADSPerformance:PerformanceIBPAEffectFocusDetails"
								{
									Snippet Filter
									attribute = IB5_EFFECT_CODE
									filterValue = "<udp:item column=\"IB5_EFFECT_CODE\"/>"
									operator = EQUAL
								}
							}
						}
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetVisible = false
				}
				--- Spacer ---
					height = 4
					width = 10
				--- TableColumnItem ---
					item-column = IB5_EFFECT_DENOM
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_IB5_EFFECT !
				column-type = domain !
				domainAttribute = B1_IB5_EFFECT !
				type = text
				column-visibility = not-visible
				id = B1_IB5_EFFECT
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = B1_IB5_EFFECT
					format = percentTA
					previewValue = value
			}
			--- TableKeepFilter ---
				keep-filter-column-name = GLOBAL_PERIOD_FILTER
				keep-filter-operand = 1
			--- TableKeepFilter ---
				keep-filter-column-name = PORTFOLIO_LEVEL_FILTER
				keep-filter-operand = 1
			--- TableExtra ---
				domainAttribute = IB1_EFFECT_CODE
			--- TableExtra ---
				domainAttribute = IB2_EFFECT_CODE
			--- TableExtra ---
				domainAttribute = IB3_EFFECT_CODE
			--- TableExtra ---
				domainAttribute = IB4_EFFECT_CODE
			--- TableExtra ---
				domainAttribute = IB5_EFFECT_CODE
			--- TableSort ---
				sort-column-name = CLIENT_NAME
				sort-rank = 1
		}
	}
}