# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Portfolio List Summary Views", fr = "Vues résumées sur liste de portefeuille", de = "Portfolioliste Zusammenfassung"
	domainEntity = "AAADSPerformance:PerformanceIBPASummary"
	bean-define = DSBean.AAADSPerformance.PerformanceIBPASummary
	bean-name = PerformanceIBPASummary
	id = PerformanceIBPAPortfolioListSummary_D07Jh
	tid = 2109591658995
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			id = R__Q3
			table-column-count = 21 !
			table-columns-width = "4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4" !
		{
			--- TableColumn ---
				labels en = Portfolio, fr = Portefeuille, de = Portfolio
				column-display-grouping = true
				column-name = GROUPING
				column-type = placeholder !
				type = text
				column-locked = true
				column-sortable = false !
				id = M__n_
				table-column-width = 4
				tid = 114506593427344
			{
				--- TableGroup ---
					aggregateData = false
					eventLevel = onlyNodes
					group-column-name = PTF_HIER_STR
					group-sorting-column-name = PTF_HIER_STR
					group-sorting-direction = ascending
					hierarchy = true
					group-rank = 1
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = selectPortfolio ud
						portfolioDimPortfolio.code = "<udp:item column=\"_nodeCode\"/>" ud
						portfolioDimensionE = 1 ud
						only-changed = false
						prevalidate = false
						modal = false
						Snippet FilterSet
						id = fs_VzA
						level = 1
						targetDataset = "AAADSPerformance:PerformanceIBPASummary"
						{
							Snippet Filter
							attribute = PTF_HIER_STR
							filterValue = "<udp:item column=\"PTF_HIER_STR\"/>"
							operator = BEGINS_WITH
						}
					}
				}
			}
			--- TableColumn ---
				column-name = CLIENT_NAME !
				column-type = domain !
				domainAttribute = CLIENT_NAME !
				type = text
				column-visibility = not-visible
				id = CLIENT_NAME
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = CLIENT_NAME
					previewValue = value
			}
			--- TableColumn ---
				column-name = PORTFOLIO_INVEST_SERVICE !
				column-type = domain !
				domainAttribute = PORTFOLIO_INVEST_SERVICE !
				type = text
				column-visibility = not-visible
				id = PORTFOLIO_INVEST_SERVICE
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = PORTFOLIO_INVEST_SERVICE
					previewValue = value
			}
			--- TableColumn ---
				column-name = ADMIN_MGR_NAME !
				column-type = domain !
				domainAttribute = ADMIN_MGR_NAME !
				type = text
				column-visibility = not-visible
				id = ADMIN_MGR_NAME
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = ADMIN_MGR_NAME
					previewValue = value
			}
			--- TableColumn ---
				column-name = COM_MGR_NAME !
				column-type = domain !
				domainAttribute = COM_MGR_NAME !
				type = text
				column-visibility = not-visible
				id = COM_MGR_NAME
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = COM_MGR_NAME
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Initial Market Value", fr = "Valeur d\'inventaire initiale", de = Anfangs-Marktwert
				column-name = InitialMarketValue
				type = amount
				column-visibility = not-visible
				id = Qm7a2
				column-computation = make-amount
				column-computation-parameters = "INITIAL_MARKET_VALUE,REF_CURRENCY"
				table-column-width = 4
				tid = 4778877232317
			{
				--- TableColumnItem ---
					item-column = InitialMarketValue
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Final Market Value", fr = "Valeur d\'inventaire finale", de = End-Marktwert
				column-name = FinalMarketValue
				type = amount
				column-visibility = not-visible
				id = z_iT5
				column-computation = make-amount
				column-computation-parameters = "FINAL_MARKET_VALUE,REF_CURRENCY"
				table-column-width = 4
				tid = 4778877717966
			{
				--- TableColumnItem ---
					item-column = FinalMarketValue
					previewValue = value
			}
			--- TableColumn ---
				column-name = PTF_RETURN !
				column-type = domain !
				domainAttribute = PTF_RETURN !
				type = text
				id = PTF_RETURN
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = PTF_RETURN
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = BENCHMARK1_FULL_NAME !
				column-type = domain !
				domainAttribute = BENCHMARK1_FULL_NAME !
				type = text
				id = BENCHMARK1_FULL_NAME
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = BENCHMARK1_FULL_NAME
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_RETURN !
				column-type = domain !
				domainAttribute = B1_RETURN !
				type = text
				id = B1_RETURN
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = B1_RETURN
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_BENCHMARK_FACTOR !
				column-type = domain !
				domainAttribute = B1_BENCHMARK_FACTOR !
				type = text
				id = B1_BENCHMARK_FACTOR
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = B1_BENCHMARK_FACTOR
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = IB1_EFFECT_DENOM !
				column-type = domain !
				domainAttribute = IB1_EFFECT_DENOM !
				type = text
				id = IB1_EFFECT_DENOM
				table-column-width = 4
			{
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "<udp:item column=\"IB1_EFFECT_DENOM\"/>!=null"
						technicalName = "Effect 1"
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips en = "View Effect 1 Details", fr = "Voir les détails de l\'effet 1", de = "Details des Effekts 1 ansehen"
							icon = application_form_magnify
							id = NQQ86
							tid = 4778879661609
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = popup
								flow-action = getEffect1 ud
								only-changed = false
								prevalidate = false
								modal = false
								Snippet FilterSet
								id = fs_5NL
								level = 1
								targetDataset = "AAADSPerformance:PerformanceIBPAEffectFocusDetails"
								{
									Snippet Filter
									attribute = IB1_EFFECT_CODE
									filterValue = "<udp:item column=\"IB1_EFFECT_CODE\"/>"
									operator = EQUAL
									Snippet Filter
									attribute = PORTFOLIO_CODE
									filterValue = "<udp:item column=\"PORTFOLIO_CODE\"/>"
									operator = EQUAL
								}
							}
						}
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetVisible = false
				}
				--- Spacer ---
					height = 4
					width = 10
				--- TableColumnItem ---
					item-column = IB1_EFFECT_DENOM
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_IB1_EFFECT !
				column-type = domain !
				domainAttribute = B1_IB1_EFFECT !
				type = text
				id = B1_IB1_EFFECT
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = B1_IB1_EFFECT
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = IB2_EFFECT_DENOM !
				column-type = domain !
				domainAttribute = IB2_EFFECT_DENOM !
				type = text
				id = IB2_EFFECT_DENOM
				table-column-width = 4
			{
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "<udp:item column=\"IB2_EFFECT_DENOM\"/>!=null"
						technicalName = "Effect 2"
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips en = "View Effect 2 Details", fr = "Voir les détails de l\'effet 2", de = "Details des Effekts 2 ansehen"
							icon = application_form_magnify
							id = ev623
							tid = 4778881611146
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = popup
								flow-action = getEffect2 ud
								only-changed = false
								prevalidate = false
								modal = false
								Snippet FilterSet
								id = fs_5NL
								level = 1
								targetDataset = "AAADSPerformance:PerformanceIBPAEffectFocusDetails"
								{
									Snippet Filter
									attribute = IB2_EFFECT_CODE
									filterValue = "<udp:item column=\"IB2_EFFECT_CODE\"/>"
									operator = EQUAL
									Snippet Filter
									attribute = PORTFOLIO_CODE
									filterValue = "<udp:item column=\"PORTFOLIO_CODE\"/>"
									operator = EQUAL
								}
							}
						}
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetVisible = false
				}
				--- Spacer ---
					height = 4
					width = 10
				--- TableColumnItem ---
					item-column = IB2_EFFECT_DENOM
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_IB2_EFFECT !
				column-type = domain !
				domainAttribute = B1_IB2_EFFECT !
				type = text
				id = B1_IB2_EFFECT
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = B1_IB2_EFFECT
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = IB3_EFFECT_DENOM !
				column-type = domain !
				domainAttribute = IB3_EFFECT_DENOM !
				type = text
				id = IB3_EFFECT_DENOM
				table-column-width = 4
			{
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "<udp:item column=\"IB3_EFFECT_DENOM\"/>!=null"
						technicalName = "Effect 3"
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips de = "Details des Effekts 3 ansehen", fr = "Voir les détails de l\'effet 3", en = "View Effect 3 Details"
							icon = application_form_magnify
							id = W___F
							tid = 4778883563613
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = popup
								flow-action = getEffect3 ud
								only-changed = false
								prevalidate = false
								modal = false
								Snippet FilterSet
								id = fs_5NL
								level = 1
								targetDataset = "AAADSPerformance:PerformanceIBPAEffectFocusDetails"
								{
									Snippet Filter
									attribute = IB3_EFFECT_CODE
									filterValue = "<udp:item column=\"IB3_EFFECT_CODE\"/>"
									operator = EQUAL
									Snippet Filter
									attribute = PORTFOLIO_CODE
									filterValue = "<udp:item column=\"PORTFOLIO_CODE\"/>"
									operator = EQUAL
								}
							}
						}
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetVisible = false
				}
				--- Spacer ---
					height = 4
					width = 10
				--- TableColumnItem ---
					item-column = IB3_EFFECT_DENOM
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_IB3_EFFECT !
				column-type = domain !
				domainAttribute = B1_IB3_EFFECT !
				type = text
				id = B1_IB3_EFFECT
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = B1_IB3_EFFECT
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = IB4_EFFECT_DENOM !
				column-type = domain !
				domainAttribute = IB4_EFFECT_DENOM !
				type = text
				column-visibility = not-visible
				id = IB4_EFFECT_DENOM
				table-column-width = 4
			{
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "<udp:item column=\"IB4_EFFECT_DENOM\"/>!=null"
						technicalName = "Effect 4"
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips en = "View Effect 4 Details", fr = "Voir les détails de l\'effet 4", de = "Details des Effekts 4 ansehen"
							icon = application_form_magnify
							id = MM_9H
							tid = 4778885518011
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = popup
								flow-action = getEffect4 ud
								only-changed = false
								prevalidate = false
								modal = false
								Snippet FilterSet
								id = fs_5NL
								level = 1
								targetDataset = "AAADSPerformance:PerformanceIBPAEffectFocusDetails"
								{
									Snippet Filter
									attribute = IB4_EFFECT_CODE
									filterValue = "<udp:item column=\"IB4_EFFECT_CODE\"/>"
									operator = EQUAL
									Snippet Filter
									attribute = PORTFOLIO_CODE
									filterValue = "<udp:item column=\"PORTFOLIO_CODE\"/>"
									operator = EQUAL
								}
							}
						}
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetVisible = false
				}
				--- Spacer ---
					height = 4
					width = 10
				--- TableColumnItem ---
					item-column = IB4_EFFECT_DENOM
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_IB4_EFFECT !
				column-type = domain !
				domainAttribute = B1_IB4_EFFECT !
				type = text
				column-visibility = not-visible
				id = B1_IB4_EFFECT
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = B1_IB4_EFFECT
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = IB5_EFFECT_DENOM !
				column-type = domain !
				domainAttribute = IB5_EFFECT_DENOM !
				type = text
				column-visibility = not-visible
				id = IB5_EFFECT_DENOM
				table-column-width = 4
			{
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "<udp:item column=\"IB5_EFFECT_DENOM\"/>!=null"
						technicalName = "Effect 5"
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips de = "Details des Effekts 5 ansehen", en = "View Effect 5 Details", fr = "Voir les détails de l\'effet 5"
							icon = application_form_magnify
							id = Q_56_
							tid = 4778887469301
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = popup
								flow-action = getEffect5 ud
								only-changed = false
								prevalidate = false
								modal = false
								Snippet FilterSet
								id = fs_5NL
								level = 1
								targetDataset = "AAADSPerformance:PerformanceIBPAEffectFocusDetails"
								{
									Snippet Filter
									attribute = IB5_EFFECT_CODE
									filterValue = "<udp:item column=\"IB5_EFFECT_CODE\"/>"
									operator = EQUAL
									Snippet Filter
									attribute = PORTFOLIO_CODE
									filterValue = "<udp:item column=\"PORTFOLIO_CODE\"/>"
									operator = EQUAL
								}
							}
						}
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetVisible = false
				}
				--- Spacer ---
					height = 4
					width = 10
				--- TableColumnItem ---
					item-column = IB5_EFFECT_DENOM
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_IB5_EFFECT !
				column-type = domain !
				domainAttribute = B1_IB5_EFFECT !
				type = text
				column-visibility = not-visible
				id = B1_IB5_EFFECT
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = B1_IB5_EFFECT
					format = percentTA
					previewValue = value
			}
			--- TableKeepFilter ---
				keep-filter-column-name = GLOBAL_PERIOD_FILTER
				keep-filter-operand = 1
			--- TableKeepFilter ---
				keep-filter-column-name = PORTFOLIO_LEVEL_FILTER
				keep-filter-operand = 1
			--- TableExtra ---
				domainAttribute = IB1_EFFECT_CODE
			--- TableExtra ---
				domainAttribute = IB2_EFFECT_CODE
			--- TableExtra ---
				domainAttribute = IB3_EFFECT_CODE
			--- TableExtra ---
				domainAttribute = IB4_EFFECT_CODE
			--- TableExtra ---
				domainAttribute = IB5_EFFECT_CODE
			--- TableExtra ---
				domainAttribute = PORTFOLIO_CODE
			--- TableSort ---
				sort-column-name = PTF_HIER_STR
				sort-rank = 1
		}
	}
}