# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSStrategyLink:StrategyLinkList"
	cssClass = nodeco
	bean-define = DSBean.AAADSStrategyLink.StrategyLinkList
	bean-name = StrategyLinkList
	id = AllStrategyLinkList_m_9__
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			table-filter-layer = true
			id = Y34_4
			table-model-reference = DSTableModel.AAADSStrategyLink.StrategyLinkList.All
			table-column-count = 8 !
			table-columns-width = "12,12,12,12,12,12,12,12" !
		{
			--- TableColumn ---
				labels en = Modify, fr = Modifier, de = Aktualisieren
				column-name = updateRightF !
				column-type = domain !
				domainAttribute = updateRightF !
				type = text
				column-is-part-of-filter = false
				column-locked = true
				column-sortable = false
				id = updateRightF
				table-column-width = 12
				tid = 100331933424176
			{
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "\"true\".equals(<udp:item column=\"updateRightF\"/>) &amp;&amp; <udp:item column=\"strategyCode\"/>!=null"
						technicalName = RightsToUpdate
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips en = "Click here to start modifying the strategy link", de = "Klicken Sie hier um die Strategieverknüpfung Aktualisierung anzufangen", fr = "Cliquer ici pour commencer à modifier le lien de stratégie"
							horizontalAlignment = center
							icon = application_form_edit
							id = tI___
							tid = 100331935375363
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = updateStrategyLink ud
								id = "<udp:item column=\"id\"/>" ud
								modal = false
								only-changed = false
								prevalidate = false
								widget-group-ref = "form*"
							}
						}
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetVisible = false
				}
			}
			--- TableColumn ---
				labels en = Delete, fr = Supprimer, de = Löschen
				column-name = deleteRightF !
				column-type = domain !
				domainAttribute = deleteRightF !
				type = text
				column-is-part-of-filter = false
				column-locked = true
				column-sortable = false
				id = deleteRightF
				table-column-width = 12
				tid = 100331937340988
			{
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "\"true\".equals(<udp:item column=\"deleteRightF\"/>)"
						technicalName = RightsToDelete
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips en = "Click here to delete the strategy link", fr = "Cliquer ici pour supprimer le lien de stratégie", de = "Klicken Sie hier um die Strategieverknüpfung zu löschen"
							horizontalAlignment = center
							icon = application_form_delete
							id = Q58dC
							tid = 100331939283523
						{
							Event OnClick (submit)
							tid = 100331941239528
							messages en = "Are you sure to delete this strategy link ?", de = "Wollen Sie diese Strategieverknüpfung wirklich löschen ?", fr = "Etes-vous sûr de vouloir supprimer ce lien de stratégie ?"
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								param = "flow-action=deleteStrategyLink"
								id = "<udp:item column=\"id\"/>" ud
								modal = false
								only-changed = false
								prevalidate = false
							}
						}
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetVisible = false
				}
			}
			--- TableColumn ---
				labels en = View, fr = Voir, de = Ansehen
				column-name = View
				column-type = placeholder !
				type = boolean
				column-locked = true
				column-sortable = false !
				id = M_i__
				table-column-width = 12
				tid = 100331943187172
			{
				--- Icon ---
					toolTips en = "View Strategy Link Details", de = "Strategieverknüpfung Details ansehen", fr = "Voir les détails du lien de stratégie"
					horizontalAlignment = center
					icon = application_form_magnify
					id = Z_807
					tid = 100331967822758
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "resource:///administration/strategylink/StrategyLinkDetails.pageflow"
						target = popup
						id = "<udp:item column=\"id\"/>" ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- TableColumn ---
				column-name = strategyExtDenomination !
				column-type = domain !
				domainAttribute = strategyExtDenomination !
				type = text
				id = strategyExtDenomination
				table-column-width = 12
			{
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						conditionLang = DSEL
						javaCode = "StrategyLinkList.strategyCode!=null"
						technicalName = "Access Right on Strategy"
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips en = "View Strategy Details", fr = "Voir les détails de la stratégie", de = "Details der Strategie ansehen"
							icon = application_form_magnify
							id = Zp_W_
							tid = 100331969553764
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "resource:///administration/strategy/StrategyView.pageflow"
								target = popup
								code = "<udp:item column=\"strategyCode\"/>" ud
								modal = false
								only-changed = false
								prevalidate = false
							}
						}
						--- TableColumnItem ---
							item-column = strategyExtDenomination
							previewValue = D_AI_Asset_Allocation1
						--- Glue ---
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = "No Access Rights on Strategy"
						boxType = vertical
						isWidgetVisible = false
					{
						--- Label ---
							labels en = "No access rights on the associated strategy", fr = "Pas de droit d\'accès sur la stratégie associée", de = "Kein Zugriffsrecht auf der verknüpften Strategie"
							tid = 100331971526364
					}
				}
			}
			--- TableColumn ---
				labels en = "Begin on", fr = "Commence le", de = "Anfängt am"
				column-name = beginD !
				column-type = domain !
				domainAttribute = beginD !
				format = date
				type = text
				id = beginD
				table-column-width = 12
				tid = 100331973462745
			{
				--- TableColumnItem ---
					item-column = beginD
					format = date
					previewValue = "Feb 11, 2013"
			}
			--- TableColumn ---
				labels en = "End on", fr = "Finit le", de = "Endet am"
				column-name = endD !
				column-type = domain !
				domainAttribute = endD !
				format = date
				type = text
				id = endD
				table-column-width = 12
				tid = 100331975433102
			{
				--- TableColumnItem ---
					item-column = endD
					format = date
			}
			--- TableColumn ---
				labels en = Nature, fr = Nature, de = Art
				column-name = linkNatE !
				column-type = domain !
				domainAttribute = linkNatE !
				type = text
				id = linkNatE
				table-column-width = 12
				tid = 100331977366133
			{
				--- TableColumnItem ---
					item-column = linkNatE
					previewValue = Strategy
			}
			--- TableColumn ---
				column-name = priorityN !
				column-type = domain !
				domainAttribute = priorityN !
				format = integer
				type = text
				id = priorityN
				table-column-width = 12
			{
				--- TableColumnItem ---
					item-column = priorityN
					format = integer
			}
			--- TableSort ---
				sort-column-name = beginD
				sort-direction = descending
				sort-rank = 1
			--- TableExtra ---
				domainAttribute = id
			--- TableExtra ---
				domainAttribute = strategyCode
		}
	}
}