# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Order Proposal", de = "Order Proposal", fr = "Proposition d\'ordre"
	domainEntity = "AAADSDomain:DomainContext"
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = ContextView_F____
	tid = 323350144129381
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///default/domain/SessionViewOnly.fragment
		--- Grid ---
			cssClass = blank
			gridColumnCount = 1
			gridColumnsWidth = 25 !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Box ---
				{
					--- Button ---
						labels en = "Show IP", de = "IP anzeigen", fr = "Voir le profile d\'investissement" toolTips en = "Show Investment Profile", de = "Investment Profil anzeigen", fr = "Voir le profile d\'investissement"
						id = btn_V5__7
						tid = 194213258011662
					{
						Event OnClick (submit) S
						{
							method = post
							call-URI = "<pageflow:continuation/>"
							target = self
							flow-action = showIP ud
							modal = false
							only-changed = false
							prevalidate = false
						}
					}
					--- Button ---
						labels en = "External Positions", de = "Externe Positionen", fr = "Positions externes"
						id = btn_r1_e7
						tid = 27019259518573
					{
						Event OnClick (submit) S
						{
							method = post
							call-URI = "<pageflow:continuation/>"
							target = self
							flow-action = viewExtPosition ud
							modal = false
							only-changed = false
							prevalidate = false
						}
					}
					--- Button ---
						labels en = "View Report Comments", de = "Reportkommentar anzeigen", fr = "Voir les commentaires du rapport"
						id = btn_P8__Z
						tid = 1907339528016342
					{
						Event OnClick (submit) S
						{
							method = post
							call-URI = "<pageflow:continuation/>"
							target = self
							flow-action = viewComments ud
							modal = false
							only-changed = false
							prevalidate = false
						}
					}
					--- Glue ---
				}
			}
		}
	}
}