# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = Context, de = Kontext, fr = Contexte
	domainEntity = "AAADSDomain:DomainContext"
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = ProposalCreate_H_5vp
	tid = 26660899750490
{
	--- Box ---
		boxType = vertical
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 3
			gridColumnsWidth = "25,25,25" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainPortfolioCodeView.fragment
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainDefaultInvestmentProfile.fragment
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainForceLink.fragment
			}
		}
	}
}