# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Proposal Creation", de = "Vorschlag erstellen", fr = "Création de proposition"
	domainEntity = "AAADSDomain:DomainContext"
	cssClass = nodeco
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = ProposalCreate_H_5vp
	tid = 202401312745206
{
	--- Box ---
		boxType = vertical
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 3
			gridColumnsWidth = "25,25,25" !
			gridRowCount = 3
		{
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainPortfolioNameView.fragment
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainDefaultInvestmentProfile.fragment
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainForceLink.fragment
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainMinStatusEdit.fragment
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainMaxStatusEdit.fragment
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainMinOrderAmount.fragment
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainSessionDescription.fragment
			}
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
		}
	}
}