# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Edit List Notepad", de = "Notiz der Liste ändern", fr = "Editer la liste de bloc-note"
	containment = container
	domainEntity = "AAADSList:ListAll"
	cssClass = nodeco
	bean-define = DSBean.AAADSList.ListAll
	bean-name = ListAll
	id = ListNotepadEdit_B9aA0
	tid = 115283057075969
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///default/list/listidentifier/ListIdentifierView.fragment
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/notepad/search/NotepadListEdit.module
	}
}