# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Edit List Composition", de = "Zusammensetzung der Liste ändern", fr = "Editer la composition de la liste"
	containment = container
	domainEntity = "AAADSList:ListAll"
	bean-define = DSBean.AAADSList.ListAll
	bean-name = ListAll
	id = ListCompoEdit_fP_8_
	tid = 110500011081296
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///default/list/listidentifier/ListIdentifierView.fragment
	}
}