# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Update List", de = "Liste ändern", fr = "Mettre à jour la liste"
	containment = container
	domainEntity = "AAADSList:ListAll"
	bean-define = DSBean.AAADSList.ListAll
	bean-name = ListAll
	id = ListUpdate_YZ_66
	tid = 108866724445984
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			id = Jq43V
			indexOfSelectedChild = 2
		{
			--- Tab ---
				labels en = Detail, de = Detail, fr = Détail
				boxType = vertical
				id = tab_YQpC_
				isWidgetVisible = false
				tid = 113595940737998
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/list/listall/ListIdentifierUpdate.fragment
				--- Include ---
					includeSrc = "" !
					resource:///default/list/listall/ListDetailUpdate.fragment
			}
			--- Tab ---
				labels en = Composition, de = Zusammensetzung, fr = Composition
				id = tab_r3Ad0
				isWidgetVisible = false
				tid = 113608920470059
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/list/update/ListCompoEdit.module
			}
			--- Tab ---
				labels en = Notepad, de = Notiz, fr = Bloc-note
				id = tab_e9__H
				isWidgetSelected = true
				tid = 113620052312235
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/list/update/ListNotepadEdit.module
			}
		}
	}
}