# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSCurrency:CurrencyList"
	search = autoComplete !
	bean-define = DSBean.AAADSCurrency.CurrencyList
	bean-name = CurrencyList
	id = Currency_y_V__
{
	--- Box ---
		boxType = vertical
	{
		--- AutoCompleteDesign ---
			max-returned = 20
			sortAttribute = code
			titleAttribute = extIsoSynC
		{
			Snippet Line
			{
				Snippet LineItem
				cssClass = css1
				lineAttribute = code
				translation = true
				Snippet LineItem
				cssClass = css2
				lineAttribute = extDenomination
				translation = true
			}
		}
	}
}