# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAAIdentifierDatasets:DataSecuProfIdentifier"
	search = autoComplete !
	bean-define = DSBean.AAAIdentifierDatasets.DataSecuProfIdentifier
	bean-name = DataSecuProfIdentifier
	id = DataSecurityProfile_J3E29
{
	--- Box ---
		boxType = vertical
	{
		--- AutoCompleteDesign ---
			max-returned = 20
			sortAttribute = code
			titleAttribute = code
	}
}