# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSGeographic:GeographicList"
	search = autoComplete !
	bean-define = DSBean.AAADSGeographic.GeographicList
	bean-name = GeographicList
	id = Geographic_T___L
{
	--- Box ---
		boxType = vertical
	{
		--- AutoCompleteDesign ---
			max-returned = 15
			sortAttribute = name
			titleAttribute = extDenomination
		{
			Snippet Line
			{
				Snippet LineItem
				cssClass = css1
				lineAttribute = code
				translation = true
				Snippet LineItem
				cssClass = css2
				lineAttribute = name
				translation = true
			}
		}
	}
}