# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSGrid:GridList"
	search = autoComplete !
	bean-define = DSBean.AAADSGrid.GridList
	bean-name = GridList
	id = Grid_MX048
{
	--- Box ---
		boxType = vertical
	{
		--- AutoCompleteDesign ---
			max-returned = 15
			sortAttribute = name
			titleAttribute = name
		{
			Snippet Line
			{
				Snippet LineItem
				cssClass = css1
				lineAttribute = extDenomination
				translation = true
			}
		}
	}
}