# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSInstrument:InstrumentList"
	search = autoComplete !
	bean-define = DSBean.AAADSInstrument.InstrumentList
	bean-name = InstrumentList
	id = Instrument_ZN_1u
{
	--- Box ---
		boxType = vertical
	{
		--- AutoCompleteDesign ---
			max-returned = 15
			sortAttribute = name
			titleAttribute = extDenomination
		{
			Snippet Line
			{
				Snippet LineItem
				cssClass = css1
				lineAttribute = code
				translation = true
				Snippet LineItem
				cssClass = css2
				lineAttribute = name
				translation = true
			}
			Snippet Line
			{
				Snippet LineItem
				cssClass = css3
				lineAttribute = extIsinSynC
				translation = true
			}
			Snippet Line
			{
				Snippet LineItem
				cssClass = css3
				lineAttribute = extTelekursSynC
				translation = true
			}
		}
	}
}