# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSDictLanguage:DictLanguageList"
	search = autoComplete !
	bean-define = DSBean.AAADSDictLanguage.DictLanguageList
	bean-name = DictLanguageList
	id = Language_X99k_
{
	--- Box ---
		boxType = vertical
	{
		--- AutoCompleteDesign ---
			max-returned = 20
			sortAttribute = code
			titleAttribute = code
		{
			Snippet Line
			{
				Snippet LineItem
				cssClass = css1
				lineAttribute = name
				translation = true
			}
		}
	}
}