# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSManager:ManagerList"
	search = autoComplete !
	bean-define = DSBean.AAADSManager.ManagerList
	bean-name = ManagerList
	id = Manager_d_Bj_
{
	--- Box ---
		boxType = vertical
	{
		--- AutoCompleteDesign ---
			max-returned = 10
			sortAttribute = name
			titleAttribute = extDenomination
		{
			Snippet Line
			{
				Snippet LineItem
				cssClass = css1
				lineAttribute = name
				translation = true
				Snippet LineItem
				cssClass = css1
				lineAttribute = code
			}
		}
	}
}