# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSMarketSegment:MarketSegmentList"
	search = autoComplete !
	bean-define = DSBean.AAADSMarketSegment.MarketSegmentList
	bean-name = MarketSegmentList
	id = MarketSegment_bf_54
{
	--- Box ---
		boxType = vertical
	{
		--- AutoCompleteDesign ---
			max-returned = 15
			sortAttribute = name
			titleAttribute = name
		{
			Snippet Line
			{
				Snippet LineItem
				cssClass = css1
				lineAttribute = gridCode
				translation = true
				Snippet LineItem
				cssClass = css1
				lineAttribute = mktStructParentMktSgtExtDenomination
				translation = true
				Snippet LineItem
				cssClass = css2
				lineAttribute = extDenomination
				translation = true
			}
		}
	}
}