# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSThirdParty:ThirdPartyList"
	search = autoComplete !
	bean-define = DSBean.AAADSThirdParty.ThirdPartyList
	bean-name = ThirdPartyList
	id = Market_eA709
{
	--- Box ---
		boxType = vertical
	{
		--- AutoCompleteDesign ---
			max-returned = 15
			sortAttribute = name
			titleAttribute = extDenomination
		{
			Snippet Line
			{
				Snippet LineItem
				cssClass = css1
				lineAttribute = code
				translation = true
				Snippet LineItem
				cssClass = css2
				lineAttribute = name
				translation = true
			}
		}
	}
}