# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSPortfolio:PortfolioList"
	search = autoComplete !
	bean-define = DSBean.AAADSPortfolio.PortfolioList
	bean-name = PortfolioList
	id = Portfolio_E644e
{
	--- Box ---
		boxType = vertical
	{
		--- AutoCompleteDesign ---
			max-returned = 10
			sortAttribute = code
			titleAttribute = code
		{
			Snippet Line
			{
				Snippet LineItem
				cssClass = css1
				lineAttribute = name
				translation = true
				Snippet LineItem
				cssClass = css2
				lineAttribute = extDenomination
				translation = true
			}
		}
	}
}