# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSStrategy:StrategyList"
	search = autoComplete !
	bean-define = DSBean.AAADSStrategy.StrategyList
	bean-name = StrategyList
	id = Strategy_w__43
{
	--- Box ---
		boxType = vertical
	{
		--- AutoCompleteDesign ---
			max-returned = 10
			sortAttribute = code
			titleAttribute = code
		{
			Snippet Line
			{
				Snippet LineItem
				cssClass = css1
				lineAttribute = name
				translation = true
				Snippet LineItem
				cssClass = css2
				lineAttribute = extDenomination
				translation = true
			}
		}
	}
}