# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSType:TypeList"
	search = autoComplete !
	bean-define = DSBean.AAADSType.TypeList
	bean-name = TypeList
	id = Type_UP84t
{
	--- Box ---
		boxType = vertical
	{
		--- AutoCompleteDesign ---
			sortAttribute = name
			titleAttribute = name
		{
			Snippet Line
			{
				Snippet LineItem
				cssClass = css1
				lineAttribute = extDenomination
				translation = true
			}
		}
	}
}