# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSApplUser:ApplUserList"
	search = autoComplete !
	bean-define = DSBean.AAADSApplUser.ApplUserList
	bean-name = ApplUserList
	id = User_rx1C5
{
	--- Box ---
		boxType = vertical
	{
		--- AutoCompleteDesign ---
			max-returned = 10
			sortAttribute = name
			titleAttribute = extDenomination
		{
			Snippet Line
			{
				Snippet LineItem
				cssClass = css1
				lineAttribute = name
				translation = true
				Snippet LineItem
				cssClass = css1
				lineAttribute = code
			}
		}
	}
}