# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels fr = "Liste des dénominations", de = "Beschreibung der Liste"
	domainEntity = "AAADSDenomination:DenominationList"
	cssClass = nodeco
	bean-define = DSBean.AAADSDenomination.DenominationList
	bean-name = DenominationList
	id = DenominationList_t7K85
	tid = 34842566082840
{
	--- Box ---
		labels en = Denomination, de = Bezeichnung, fr = Dénomination
		boxType = vertical
		widgetBorder = box
		width = 0
		tid = 713414303345536
	{
		--- TableTree ---
			table-filter-layer = true
			id = f_7G2
			table-model-reference = DSTableModel.AAADSDenomination.DenominationList
			table-column-count = 2 !
			table-columns-width = "50,50" !
		{
			--- TableColumn ---
				column-name = languageCode !
				column-type = domain !
				domainAttribute = languageCode !
				type = text
				column-locked = true
				id = languageCode
				table-column-width = 50
			{
				--- TableColumnItem ---
					item-column = languageCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = denom !
				column-type = domain !
				domainAttribute = denom !
				column-locked = true
				id = denom
				table-column-width = 50
			{
				--- TableColumnItem ---
					item-column = denom
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = denom
				sort-direction = descending
				sort-rank = 3
			--- TableSort ---
				sort-column-name = languageExtDenomination
				sort-direction = descending
				sort-rank = 2
		}
	}
}