# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Calendar Convention List", fr = "Liste des conventions du calendrier", de = "Liste der Kalender-Konventionen"
	domainEntity = "AAADSCalendarConv:CalendarConvList"
	bean-define = DSBean.AAADSCalendarConv.CalendarConvList
	bean-name = CalendarConvList
	id = CalendarConvList_w___9
	tid = 129387212156293
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			id = A7_AD
			table-column-count = 6 !
			table-columns-width = "16,16,16,16,16,16" !
		{
			--- TableColumn ---
				column-name = calendarCode !
				column-type = domain !
				domainAttribute = calendarCode !
				id = calendarCode
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = calendarCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = natureE !
				column-type = domain !
				domainAttribute = natureE !
				id = natureE
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = natureE
					previewValue = value
			}
			--- TableColumn ---
				column-name = termN !
				column-type = domain !
				domainAttribute = termN !
				id = termN
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = termN
					format = integer
					previewValue = value
			}
			--- TableColumn ---
				column-name = dayN !
				column-type = domain !
				domainAttribute = dayN !
				id = dayN
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = dayN
					format = integer
					previewValue = value
			}
			--- TableColumn ---
				column-name = weekdayE !
				column-type = domain !
				domainAttribute = weekdayE !
				id = weekdayE
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = weekdayE
					previewValue = value
			}
			--- TableColumn ---
				column-name = anchorDayE !
				column-type = domain !
				domainAttribute = anchorDayE !
				id = anchorDayE
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = anchorDayE
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = calendarCode
				sort-rank = 1
			--- TableSort ---
				sort-column-name = natureE
				sort-rank = 2
			--- TableSort ---
				sort-column-name = termN
				sort-rank = 3
			--- TableSort ---
				sort-column-name = dayN
				sort-rank = 4
			--- TableSort ---
				sort-column-name = weekdayE
				sort-rank = 5
			--- TableSort ---
				sort-column-name = anchorDayE
				sort-rank = 6
		}
	}
}