<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="rulesbinding"
    nsURI="http://www.odcgroup.com/rules/binding" nsPrefix="rule">
  <eClassifiers xsi:type="ecore:EClass" name="MdfBinding">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" lowerBound="1"
        eType="ecore:EClass platform:/plugin/com.odcgroup.mdf.ecore/src/main/model/mdf.ecore#//MdfEntity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" upperBound="-1"
        eType="#//Rule"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rule" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValidationRule" eSuperTypes="#//Rule"/>
  <eClassifiers xsi:type="ecore:EClass" name="CompletionRule" eSuperTypes="#//Rule"/>
</ecore:EPackage>
