# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Exchange Rates", fr = "Cours monétaires", de = Währungskurse
	domainEntity = "AAADSValuation:ValuationSummaryList"
	bean-define = DSBean.AAADSValuation.ValuationSummaryList
	bean-name = ValuationSummaryList
	id = ExchangeRate_H__0Q
	tid = 901687305986
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			table-expand-all = false
			table-rendering-mode = summary-delegated
			table-fixed-size = true
			table-width = 300
			id = T_2_h
			table-column-count = 2 !
			table-columns-width = "50,50" !
		{
			--- TableColumn ---
				labels en = "Position Currency / Reference Currency", fr = "Devise de la position / Devise de référence", de = "Bestandswährung / Referenzwährung"
				column-display-grouping = true
				column-name = GROUPING
				column-type = placeholder !
				type = text
				column-locked = true
				column-sortable = false !
				id = Z8_84
				table-column-width = 50
				tid = 46376062293671
			{
				--- TableGroup ---
					group-column-name = POSCURR_REFCURR
					group-sorting-column-name = POSCURR_REFCURR
					group-sorting-direction = ascending
					group-rank = 1
			}
			--- TableColumn ---
				column-name = EXCH_RATE !
				column-type = domain !
				domainAttribute = EXCH_RATE !
				type = text
				id = EXCH_RATE
				table-column-width = 50
			{
				--- TableColumnItem ---
					item-column = EXCH_RATE
					format = decimal.detailed
					previewValue = value
			}
			--- TableAggregate ---
				aggregate-column-name = EXCH_RATE
				aggregate-computation = max
				aggregate-group-names = POSCURR_REFCURR
			--- TableKeepFilter ---
				keep-filter-column-name = EXCH_RATE
				keep-filter-operand = 1
				keep-filter-operator = not-equal
			--- TableAggregate ---
				aggregate-column-name = POSCURR_REFCURR
				aggregate-computation = max
				aggregate-group-names = POSCURR_REFCURR
		}
	}
}