# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSDomain:DomainContext"
	collapsible = true
	cssClass = nodeco
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = ContextAdvancedNotEdited_A2LM9
{
	--- Box ---
		boxType = vertical
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 4
			gridColumnsWidth = "10,12,20,20" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 10
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainPLMethodNotEdited.fragment
			}
			--- GridCell ---
				gridColumnWidth = 12
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainDynamicWeightNotEdited.fragment
			}
			--- GridCell ---
				gridColumnWidth = 20
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainRiskFreeInstrumentNotEdited.fragment
			}
			--- GridCell ---
				gridColumnWidth = 20
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainStrategyLinkNotEdited.fragment
			}
		}
	}
}