# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = Context, fr = Contexte, de = Kontext
	containment = container
	domainEntity = "AAADSDomain:DomainContext"
	collapsible = true
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = Context_V__S_
	tid = 2931693676454
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TabbedPane ---
			id = eX_31
			indexOfSelectedChild = 1
		{
			--- Tab ---
				labels fr = Base, en = Basic, de = Einfach
				id = perf_risk_measures_basic
				isWidgetVisible = false
				tid = 2931709303716
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/performance/riskmeasures/context/ContextBasic.module
			}
			--- Tab ---
				labels fr = Avancée, en = Advanced, de = Erweitert
				id = perf_risk_measures_advanced
				isWidgetSelected = true
				tid = 2931740047175
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/performance/riskmeasures/context/ContextAdvanced.module
			}
		}
		--- Grid ---
			cssClass = blank
			gridColumnCount = 4
			gridColumnsWidth = "25,25,25,25" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Button ---
					labels en = Execute, de = Ausführen, fr = Exécuter
					id = btn_j_o52
					tid = 2931740515227
				{
					Event OnClick (submit)
					{
						method = get
						call-URI = "<pageflow:continuation/>"
						widget-group-ref = form
						param = "flow-action=execute"
						only-changed = true
						prevalidate = false
						modal = false
					}
				}
				--- Button ---
					labels en = Refresh, de = Aktualisieren, fr = Actualiser
					id = btn_gING_
					tid = 2931742459827
				{
					Event OnClick (submit)
					{
						method = get
						call-URI = "<pageflow:continuation/>"
						widget-group-ref = form
						param = "flow-action=execute,DSAction=refresh"
						only-changed = true
						prevalidate = false
						modal = false
					}
				}
				--- Button ---
					labels en = "Default Settings", de = Standardeinstellung, fr = "Valeurs par défaut"
					id = btn_n0___
					tid = 2931744416242
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = reset ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
		}
	}
}