# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Instrument Details", fr = "Détails de l\'instrument", de = "Details des Instruments"
	domainEntity = "AAADSDomain:DomainContext"
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = InstrumentCodeDetail_W_Y_4
	tid = 3102938871083
{
	--- Box ---
		boxType = vertical
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 4
			gridColumnsWidth = "25,25,25,25" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Button ---
					labels en = "Back to Summary", fr = "Retour au résumé", de = "Zurück zur Ansicht"
					id = btn_jb_73
					tid = 3102939345039
				{
					Event OnClick (submit)
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						param = "flow-action=back"
						Query.fs_1.TargetDS = "AAADSPerformance:PerformanceRiskMeasuresDetails" ud
						Query.fs_1.cancel = true ud
						Query.fs_1.level = 0 ud
						Query.fs_2.TargetDS = "AAADSPerformance:PerformanceRiskMeasuresSummary" ud
						Query.fs_2.cancel = true ud
						Query.fs_2.level = 0 ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
		}
	}
}