# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Portfolio Details", fr = "Détails du portefeuille", de = "Details des Portfolios"
	containment = container
	domainEntity = "AAADSDomain:DomainContextDetail"
	cssClass = nodeco
	bean-define = DSActivityBean.AAADSDomain.DomainContextDetail
	bean-name = DomainContextDetail
	id = PortfolioCodeDetail_f__bY
	tid = 3114001093335
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/performance/riskmeasures/context/PortfolioCodeDetailHead.module
		--- Grid ---
			cssClass = blank
			gridColumnCount = 4
			gridColumnsWidth = "25,25,25,25" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Button ---
					labels en = "Back to Summary", fr = "Retour au résumé", de = "Zurück zur Ansicht"
					id = btn_x_D45
					tid = 3114002500917
				{
					Event OnClick (submit)
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						param = "flow-action=back"
						Query.fs_1.TargetDS = "AAADSPerformance:PerformanceRiskMeasuresDetails" ud
						Query.fs_1.cancel = true ud
						Query.fs_1.level = 0 ud
						Query.fs_2.TargetDS = "AAADSPerformance:PerformanceRiskMeasuresSummary" ud
						Query.fs_2.cancel = true ud
						Query.fs_2.level = 0 ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
				--- Button ---
					labels en = Refresh, fr = Actualiser, de = Aktualisieren
					id = btn_stO3_
					tid = 3857685388216938
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = refresh ud
						only-changed = false
						prevalidate = false
						modal = false
					}
				}
			}
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
		}
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/identification/identification/PortfolioBanner.module
	}
}