# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Portfolio Details", fr = "Détails du portefeuille", de = "Details des Portfolios"
	domainEntity = "AAADSDomain:DomainContextDetail"
	collapsed = true
	bean-define = DSActivityBean.AAADSDomain.DomainContextDetail
	bean-name = DomainContextDetail
	id = PortfolioCodeDetailHead_K_e00
	tid = 3123157124177
{
	--- Box ---
		boxType = vertical
		cssClass = nodeco
	{
		--- TabbedPane ---
			id = K30Jp
			indexOfSelectedChild = 0
		{
			--- Tab ---
				labels en = Basic, fr = Base, de = Einfach
				id = perf_risk_measures_basic_details
				isWidgetSelected = true
				tid = 3123157595751
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 7
					gridColumnsWidth = "20,13,13,13,13,14,14" !
					gridRowCount = 1
					verticalAlignment = lead
				{
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainPortfolioCodeView.fragment
					}
					--- GridCell ---
						gridColumnWidth = 13
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainReferenceDateView.fragment
					}
					--- GridCell ---
						gridColumnWidth = 13
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainFromDateView.fragment
					}
					--- GridCell ---
						gridColumnWidth = 13
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainPivotDateTillView.fragment
					}
					--- GridCell ---
						gridColumnWidth = 13
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainRefCurrencyView.fragment
					}
					--- GridCell ---
						gridColumnWidth = 14
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainHierarchyIdentifierView.fragment
					}
					--- GridCell ---
						gridColumnWidth = 14
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainConsolidationIdentifierView.fragment
					}
				}
			}
			--- Tab ---
				labels en = Advanced, fr = Avancé, de = Erweitert
				id = perf_risk_measures_advanced_details
				isWidgetVisible = false
				tid = 3123163983065
			{
				--- Box ---
					boxType = vertical
				{
					--- Grid ---
						cssClass = blank
						gridColumnCount = 4
						gridColumnsWidth = "10,12,20,23" !
						gridRowCount = 1
					{
						--- GridCell ---
							gridColumnWidth = 10
						{
							--- Include ---
								includeSrc = "" !
								resource:///default/domain/basicelements/DomainPLMethodView.fragment
						}
						--- GridCell ---
							gridColumnWidth = 12
						{
							--- Include ---
								includeSrc = "" !
								resource:///default/domain/basicelements/DomainDynamicWeightView.fragment
						}
						--- GridCell ---
							gridColumnWidth = 23
						{
							--- Include ---
								includeSrc = "" !
								resource:///default/domain/basicelements/DomainRiskFreeInstrumentView.fragment
						}
						--- GridCell ---
							gridColumnWidth = 20
						{
							--- Include ---
								includeSrc = "" !
								resource:///default/domain/basicelements/DomainPortfolioDetailsStrategyLinkView.fragment
						}
					}
				}
			}
		}
	}
}