# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Subscribe to a public alert"
	domainEntity = "AlertDef:AlertSubscriberAll"
	bean-define = DSBean.AlertDef.AlertSubscriberAll
	bean-name = AlertSubscriberAll
	id = AlertSubscribe_DZl54
	tid = 785264435454168
{
	--- Box ---
		boxType = vertical
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 2
			gridColumnsWidth = "50,50" !
			gridRowCount = 2
		{
			--- GridCell ---
				gridColumnWidth = 50
			{
				--- LabelDomain ---
					domainAttribute = fromD !
					for = fromD
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					required = true
					id = fromD
			}
			--- GridCell ---
				gridColumnWidth = 50
			{
				--- CaldateField ---
					domainAttribute = fromD !
					format = datetime.date-only
					horizontalAlignment = "${corporatehalign}"
					type = datetime
					required = true
					bean-property = fromD
					id = fromD
			}
			--- GridCell ---
				gridColumnWidth = 50
			{
				--- LabelDomain ---
					domainAttribute = tillD !
					for = tillD
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					id = tillD
			}
			--- GridCell ---
				gridColumnWidth = 50
			{
				--- CaldateField ---
					domainAttribute = tillD !
					format = datetime.date-only
					horizontalAlignment = "${corporatehalign}"
					type = datetime
					bean-property = tillD
					id = tillD
			}
		}
		--- Box ---
		{
			--- Button ---
				labels en = Subscribe
				id = btn_O3_9_
				tid = 785323304391603
			{
				Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					widget-group-ref = "*"
					target = self
					flow-action = ok ud
					only-changed = false
					prevalidate = false
					modal = false
				}
			}
			--- Button ---
				labels en = Cancel
				id = btn_z1O_6
				tid = 785345084836503
			{
				Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = cancel ud
					only-changed = false
					prevalidate = false
					modal = false
				}
			}
			--- Glue ---
		}
	}
}