# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Query Definition"
	containment = container
	domainEntity = "AlertDef:AlertDefAll"
	bean-define = DSBean.AlertDef.AlertDefAll
	bean-name = AlertDefAll
	id = AlertQueryEdit_h_7b4
	tid = 330783747066888
{
	--- Box ---
		boxType = vertical
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 2
			gridColumnsWidth = "50,50" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 50
			{
				--- Label ---
					labels en = "Target Entity"
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					tid = 94313585528887
			}
			--- GridCell ---
				gridColumnWidth = 50
			{
				--- Include ---
					domainAssociation = entity
					includeSrc = "" !
					resource:///default/defaultFragments/DictEntityIdentifier.fragment
					bean-property-prefix = entity.
			}
		}
		--- Conditional ---
			indexOfSelectedChild = 2
		{
			--- ConditionalBody ---
				javaCode = "\"portfolio\".equals(<bean:get-property bean=\"AlertDefAll\" property=\"entity.sqlnameC\"/>)"
				technicalName = Portfolio
				boxType = vertical
				isWidgetVisible = false
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/alerts/update/AlertPortfolioQueryEdit.module
			}
			--- ConditionalBody ---
				javaCode = "\"third_party\".equals(<bean:get-property bean=\"AlertDefAll\" property=\"entity.sqlnameC\"/>)"
				technicalName = Client
				boxType = vertical
				isWidgetVisible = false
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/alerts/update/AlertClientQueryEdit.module
			}
			--- ConditionalBody ---
				javaCode = "\"instrument\".equals(<bean:get-property bean=\"AlertDefAll\" property=\"entity.sqlnameC\"/>)"
				technicalName = Instrument
				boxType = vertical
				isWidgetSelected = true
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/alerts/update/AlertInstrumentQueryEdit.module
			}
		}
		--- Box ---
		{
			--- Button ---
				labels en = Back
				id = btn_H_o2_
				tid = 331814942611825
			{
				Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = back ud
					only-changed = false
					prevalidate = false
					modal = false
				}
			}
			--- Button ---
				labels en = Next
				id = btn_g211_
				tid = 252228457849534
			{
				Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					widget-group-ref = "*"
					target = self
					flow-action = next ud
					only-changed = false
					prevalidate = false
					modal = false
				}
			}
			--- Button ---
				labels en = Cancel, fr = Annuler, de = Abbrechen
				id = btn_U_O_2
				tid = 875878342891624
			{
				Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = cancel ud
					only-changed = false
					prevalidate = false
					modal = false
				}
			}
			--- Glue ---
		}
	}
}