# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	containment = container
	search = container !
	cssClass = nodeco
	id = AlertInstrumentQueryEdit_t_000
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/alerts/update/AlertSearchCriteriaEdit.module
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/alerts/update/AlertSearchInstrumentOutput.module
	}
}