# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Alert Notifications"
	containment = container
	domainEntity = "AAADSNotification:NotifDefinitionForAlert"
	bean-define = DSBean.AAADSNotification.NotifDefinitionForAlert
	bean-name = NotifDefinitionForAlert
	id = AlertNotificationEdit_A__w_
	tid = 8398694971288
{
	--- Box ---
		boxType = vertical
	{
		--- Code ---
			code = "<bean:define key=\"DSBean.AlertDef.AlertDefAll\" name=\"AlertDefAll\"/>"
		--- Grid ---
			cssClass = blank
			gridColumnCount = 2
			gridColumnsWidth = "50,50" !
			gridRowCount = 2
		{
			--- GridCell ---
				gridColumnWidth = 50
			{
				--- LabelDomain ---
					domainAttribute = notifPriorityE !
					for = notifPriorityE
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					required = true
					id = notifPriorityE
			}
			--- GridCell ---
				gridColumnWidth = 50
			{
				--- ComboBox ---
					domainAttribute = notifPriorityE !
					horizontalAlignment = "${corporatehalign}"
					required = true
					bean-property = notifPriorityE
					id = notifPriorityE
			}
			--- GridCell ---
				gridColumnWidth = 50
			{
				--- LabelDomain ---
					domainAttribute = notifImportanceE !
					for = notifImportanceE
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					required = true
					id = notifImportanceE
			}
			--- GridCell ---
				gridColumnWidth = 50
			{
				--- ComboBox ---
					domainAttribute = notifImportanceE !
					horizontalAlignment = "${corporatehalign}"
					required = true
					bean-property = notifImportanceE
					id = notifImportanceE
			}
		}
		--- Box ---
			labels en = "English Notification Text"
			boxType = vertical
			tid = 321677691516228
		{
			--- Include ---
				domainAssociation = notifSubjectBodyDefEnglish
				includeSrc = "" !
				resource:///default/alert/AlertDefinitionSubjectAndBody.fragment
				bean-property-prefix = notifSubjectBodyDefEnglish.
		}
		--- Box ---
			labels en = "French Notification Text"
			boxType = vertical
			tid = 321703870231294
		{
			--- Include ---
				domainAssociation = notifSubjectBodyDefFrench
				includeSrc = "" !
				resource:///default/alert/AlertDefinitionSubjectAndBody.fragment
				bean-property-prefix = notifSubjectBodyDefFrench.
		}
		--- Box ---
			labels en = "German Notification Text"
			boxType = vertical
			tid = 8475020070707
		{
			--- Include ---
				domainAssociation = notifSubjectBodyDefGerman
				includeSrc = "" !
				resource:///default/alert/AlertDefinitionSubjectAndBody.fragment
				bean-property-prefix = notifSubjectBodyDefGerman.
		}
		--- Conditional ---
			indexOfSelectedChild = 1
		{
			--- ConditionalBody ---
				javaCode = "Integer.valueOf(0).equals(<bean:get-property bean=\"AlertDefAll\" property=\"visibilityE\"/>)"
				technicalName = Public
				isWidgetVisible = false
			{
				--- Button ---
					labels en = Back
					id = btn_W_2_0
					tid = 349188734630722
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = back ud
						only-changed = false
						prevalidate = false
						modal = false
					}
				}
				--- Button ---
					labels en = Next
					id = btn_v_q3v
					tid = 348870746720889
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						widget-group-ref = "*"
						target = self
						flow-action = next ud
						only-changed = false
						prevalidate = false
						modal = false
					}
				}
				--- Button ---
					labels en = Cancel, fr = Annuler, de = Abbrechen
					id = btn_VFG__
					tid = 876005644598126
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = cancel ud
						only-changed = false
						prevalidate = false
						modal = false
					}
				}
				--- Glue ---
			}
			--- ConditionalBody ---
				javaCode = true
				technicalName = Private
				isWidgetSelected = true
			{
				--- Button ---
					labels en = Back
					id = btn_zen_L
					tid = 270586234910432
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = back ud
						only-changed = false
						prevalidate = false
						modal = false
					}
				}
				--- Button ---
					labels en = End
					id = btn_O416N
					tid = 270628821293422
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						widget-group-ref = "*"
						target = self
						flow-action = next ud
						only-changed = false
						prevalidate = false
						modal = false
					}
				}
				--- Button ---
					labels en = Cancel, fr = Annuler, de = Abbrechen
					id = btn_f94Ef
					tid = 876021309632648
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = cancel ud
						only-changed = false
						prevalidate = false
						modal = false
					}
				}
				--- Glue ---
			}
		}
	}
}