# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Run Alert Query"
	containment = container
	domainEntity = "AlertDef:AlertDefAll"
	bean-define = DSBean.AlertDef.AlertDefAll
	bean-name = AlertDefAll
	id = CopyOfAlertQueryRun_d0773
	tid = 441273544896907
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/alerts/view/AlertDefView.module
		--- Box ---
			labels en = Query
			boxType = vertical
			tid = 441273546760272
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 2
				gridColumnsWidth = "50,50" !
				gridRowCount = 2
			{
				--- GridCell ---
					gridColumnWidth = 50
				{
					--- LabelDomain ---
						domainAttribute = entity !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
				}
				--- GridCell ---
					gridColumnWidth = 50
				{
					--- Include ---
						domainAssociation = entity
						includeSrc = "" !
						resource:///default/defaultFragments/DictEntityIdentifierView.fragment
						bean-property-prefix = entity.
				}
				--- GridCell ---
					gridColumnWidth = 50
				--- GridCell ---
					gridColumnWidth = 50
			}
			--- Conditional ---
				indexOfSelectedChild = 1
			{
				--- ConditionalBody ---
					javaCode = "\"portfolio\".equals(<bean:get-property bean=\"AlertDefAll\" property=\"entity.sqlnameC\"/>)"
					technicalName = Portfolio
					boxType = vertical
					isWidgetVisible = false
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/alerts/view/AlertPortfolioQueryView.module
				}
				--- ConditionalBody ---
					javaCode = "\"third_party\".equals(<bean:get-property bean=\"AlertDefAll\" property=\"entity.sqlnameC\"/>)"
					technicalName = ThirdParty
					boxType = vertical
					isWidgetSelected = true
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/alerts/view/AlertClientQueryView.module
				}
			}
		}
		--- Box ---
		{
			--- Button ---
				labels en = Back
				id = btn_E2__A
				tid = 441273548714152
			{
				Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = back ud
					only-changed = false
					prevalidate = false
					modal = false
				}
			}
			--- Glue ---
		}
	}
}