# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Search Instrument Output"
	domainEntity = "AAADSInstrument:InstrumentList"
	search = output
	bean-define = DSBean.AAADSInstrument.InstrumentList
	bean-name = InstrumentList
	id = AlertSearchInstrumentOutput_X4R02
	tid = 860709788642411
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			table-page-size = 15
			id = f_8N6
			table-model-reference = DSTableModel.AAADSInstrument.InstrumentList
			table-column-count = 16 !
			table-columns-width = "6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6" !
		{
			--- TableColumn ---
				column-name = code !
				column-type = domain !
				domainAttribute = code !
				type = text
				id = code
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = code
					previewValue = value
			}
			--- TableColumn ---
				column-name = name !
				column-type = domain !
				domainAttribute = name !
				id = name
				table-column-width = 6
			{
				--- Icon ---
					toolTips en = "View Instrument Details", fr = "Voir les détails de l\'instrument", de = "Details des Instruments ansehen"
					icon = application_form_magnify
					id = s_3__
					tid = 731448082342867
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "resource:///administration/instrument/InstrumentQuickView.pageflow"
						target = popup
						code = "<udp:item column=\"code\"/>" ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
				--- Spacer ---
					height = 4
					width = 10
				--- TableColumnItem ---
					item-column = name
					previewValue = value
			}
			--- TableColumn ---
				column-name = extDenomination !
				column-type = domain !
				domainAttribute = extDenomination !
				type = text
				id = extDenomination
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = extDenomination
					previewValue = value
			}
			--- TableColumn ---
				column-name = refCurrExtDenomination !
				column-type = domain !
				domainAttribute = refCurrExtDenomination !
				type = text
				id = refCurrExtDenomination
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = refCurrExtDenomination
					previewValue = value
			}
			--- TableColumn ---
				column-name = extIsinSynC !
				column-type = domain !
				domainAttribute = extIsinSynC !
				type = text
				id = extIsinSynC
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = extIsinSynC
					previewValue = value
			}
			--- TableColumn ---
				column-name = extTelekursSynC !
				column-type = domain !
				domainAttribute = extTelekursSynC !
				type = text
				id = extTelekursSynC
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = extTelekursSynC
					previewValue = value
			}
			--- TableColumn ---
				column-name = endD !
				column-type = domain !
				domainAttribute = endD !
				type = text
				id = endD
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = endD
					format = date
					previewValue = value
			}
			--- TableColumn ---
				column-name = interestRateP !
				column-type = domain !
				domainAttribute = interestRateP !
				type = text
				id = interestRateP
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = interestRateP
					format = percentTA.4-digits
					previewValue = value
			}
			--- TableColumn ---
				column-name = issuerThirdExtDenomination !
				column-type = domain !
				domainAttribute = issuerThirdExtDenomination !
				type = text
				id = issuerThirdExtDenomination
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = issuerThirdExtDenomination
					previewValue = value
			}
			--- TableColumn ---
				column-name = natureE !
				column-type = domain !
				domainAttribute = natureE !
				type = text
				id = natureE
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = natureE
					item-halign = lead
					previewValue = value
			}
			--- TableColumn ---
				column-name = marketThirdExtDenomination !
				column-type = domain !
				domainAttribute = marketThirdExtDenomination !
				type = text
				id = marketThirdExtDenomination
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = marketThirdExtDenomination
					previewValue = value
			}
			--- TableColumn ---
				column-name = riskGeoExtDenomination !
				column-type = domain !
				domainAttribute = riskGeoExtDenomination !
				type = text
				id = riskGeoExtDenomination
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = riskGeoExtDenomination
					previewValue = value
			}
			--- TableColumn ---
				column-name = extUnderlyingInstrDenom !
				column-type = domain !
				domainAttribute = extUnderlyingInstrDenom !
				type = text
				id = extUnderlyingInstrDenom
				table-column-width = 6
			{
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "<udp:item column=\"underlyingInstrCode\"/>!=null"
						technicalName = Underlying
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips de = "Details des Instruments ansehen", en = "View Instrument Details", fr = "Voir les détails de l\'instrument"
							icon = application_form_magnify
							id = L_60B
							tid = 731448084281940
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "resource:///administration/instrument/InstrumentQuickView.pageflow"
								target = popup
								code = "<udp:item column=\"underlyingInstrCode\"/>" ud
								modal = false
								only-changed = false
								prevalidate = false
							}
						}
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetVisible = false
				}
				--- Spacer ---
					height = 4
					width = 10
				--- TableColumnItem ---
					item-column = extUnderlyingInstrDenom
					previewValue = value
			}
			--- TableColumn ---
				column-name = activeF !
				column-type = domain !
				domainAttribute = activeF !
				type = text
				column-visibility = not-visible
				id = activeF
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = activeF
					previewValue = value
			}
			--- TableColumn ---
				labels de = Status, fr = Statut
				column-name = statusE !
				column-type = domain !
				domainAttribute = statusE !
				type = text
				column-visibility = not-visible
				id = statusE
				table-column-width = 6
				tid = 731448086258169
			{
				--- TableColumnItem ---
					item-column = statusE
					previewValue = value
			}
			--- TableColumn ---
				column-name = extBestDispCode !
				column-type = domain !
				domainAttribute = extBestDispCode !
				type = text
				column-visibility = not-visible
				id = extBestDispCode
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = extBestDispCode
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = endD
				sort-rank = 5
			--- TableSort ---
				sort-column-name = name
				sort-rank = 2
			--- TableExtra ---
				domainAttribute = underlyingInstrCode
		}
	}
}