# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = Criterias
	containment = container
	domainEntity = "AlertDef:AlertDefAll"
	search = input
	bean-define = DSBean.AlertDef.AlertDefAll
	bean-name = AlertDefAll
	id = AlertSearchPortfolioCriteria_md50D
	tid = 242372605276326
{
	--- Box ---
		boxType = vertical
	{
		--- FilterCriteria ---
			includedFile = "resource:/com/module/search/QueryBuilder.xsp"
		--- Include ---
			includeSrc = "" !
			resource:///default/alert/AlertNavigationQueryEdit.fragment
	}
}