# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	containment = container
	search = container
	cssClass = nodeco
	id = AlertPortfolioQuery_X_Lxp
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/alerts/update/AlertSearchCriteriaEdit.module
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/alerts/update/AlertSearchPortfolioOutput.module
	}
}