# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Alert Notification Recipients"
	domainEntity = "AlertDef:AlertRecipientList"
	bean-define = DSBean.AlertDef.AlertRecipientList
	bean-name = AlertRecipientList
	id = AlertRecipient_w_p01
	tid = 260234164881968
{
	--- Box ---
		boxType = vertical
	{
		--- Button ---
			labels en = Delete
			id = btn_xZy7_
			tid = 264975567970657
		{
			Event OnClick (submit) S
			{
				method = post
				call-URI = "<pageflow:continuation/>"
				target = self
				flow-action = delete ud
				only-changed = false
				prevalidate = false
				modal = false
			}
		}
		--- TableTree ---
			id = F_09Z
			table-column-count = 5 !
			table-columns-width = "20,20,20,20,20" !
		{
			--- TableColumn ---
				column-name = SELECT
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				id = Z__3_
				table-column-width = 20
			{
				--- CheckBox ---
					column-checkbox-identifier = id
					horizontalTextPosition = trail
					id = btn_Tr_5D
			}
			--- TableColumn ---
				column-name = managerCode !
				column-type = domain !
				domainAttribute = managerCode !
				type = text
				id = managerCode
				table-column-width = 20
			{
				--- TableColumnItem ---
					item-column = managerCode
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Client Code", fr = "Code client", de = Kundennummer
				column-name = thirdPartyCode !
				column-type = domain !
				domainAttribute = thirdPartyCode !
				type = text
				id = thirdPartyCode
				table-column-width = 20
				tid = 941676424981387
			{
				--- TableColumnItem ---
					item-column = thirdPartyCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = listCode !
				column-type = domain !
				domainAttribute = listCode !
				type = text
				id = listCode
				table-column-width = 20
			{
				--- TableColumnItem ---
					item-column = listCode
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Entity List Name"
				column-name = listEntityName !
				column-type = domain !
				domainAttribute = listEntityName !
				type = text
				id = listEntityName
				table-column-width = 20
				tid = 264521927624319
			{
				--- TableColumnItem ---
					item-column = listEntityName
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = managerCode
				sort-rank = 1
		}
		--- Box ---
		{
			--- Button ---
				labels en = "Add Manager"
				id = btn_F3_76
				tid = 259378556128672
			{
				Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = search ud
					only-changed = false
					prevalidate = false
					modal = false
					Query.beanProperty1 = manager.code ud
					Snippet Query
					queryAttributes = "extDenomination,searchCode,name,dataProfileSearchCode,code,languageSearchCode"
					queryOutputModule = "" !
					resource:///Default/module/aaa/administration/manager/search/ManagerSearch.module
					Snippet FilterSet
					id = fs_iti
					level = 1
					targetDataset = "AAADSManager:ManagerSearchCriteria"
				}
			}
			--- Button ---
				labels en = "Add Client"
				id = btn_z3L43
				tid = 259388897893850
			{
				Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = search ud
					only-changed = false
					prevalidate = false
					modal = false
					Query.beanProperty1 = thirdParty.code ud
					Snippet Query
					queryAttributes = "extDenomination,extCstCompliance,extAdvisoryMandate,extObjCompliance,extTdMktValM,name,extDaysProposal,extDateProposal,extDaysOperation,searchCode,statusE,typeCode,code,extDateOperation,SearchManagerCode"
					queryOutputModule = "" !
					resource:///Default/module/aaa/administration/thirdparty/search/ClientSearch.module
					Snippet FilterSet
					id = fs_cQD
					level = 1
					targetDataset = "AAADSThirdParty:ThirdPartySearchCriteria"
					{
						Snippet Filter
						attribute = clientF
						filterValue = Yes
						operator = EQUAL
					}
				}
			}
			--- Button ---
				labels en = "Add Client List"
				id = btn_F0x5_
				tid = 260159891684862
			{
				Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = search ud
					only-changed = false
					prevalidate = false
					modal = false
					Query.beanProperty0 = list.id ud
					Snippet Query
					queryAttributes = "currencySearchCode,extDenomination,searchCode,name,typeCode,code"
					queryOutputModule = "" !
					resource:///Default/module/aaa/administration/list/search/ListSearch.module
					Snippet FilterSet
					id = fs_z45
					level = 1
					targetDataset = "AAADSList:ListSearchCriteria"
					{
						Snippet Filter
						attribute = entityDict
						filterValue = 600
						operator = EQUAL
					}
				}
			}
			--- Button ---
				labels en = "Add Manager List"
				id = btn_w__0c
				tid = 260174040800422
			{
				Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = search ud
					only-changed = false
					prevalidate = false
					modal = false
					Query.beanProperty0 = list.id ud
					Snippet Query
					queryAttributes = "currencySearchCode,extDenomination,searchCode,name,typeCode,code"
					queryOutputModule = "" !
					resource:///Default/module/aaa/administration/list/search/ListSearch.module
					Snippet FilterSet
					id = fs_z45
					level = 1
					targetDataset = "AAADSList:ListSearchCriteria"
					{
						Snippet Filter
						attribute = entityDict
						filterValue = 803
						operator = EQUAL
					}
				}
			}
			--- Glue ---
		}
		--- Spacer ---
			height = 20
			width = 4
		--- Box ---
		{
			--- Button ---
				labels en = Back
				id = btn_L_wu7
				tid = 272203442077870
			{
				Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = back ud
					only-changed = false
					prevalidate = false
					modal = false
				}
			}
			--- Button ---
				labels en = End
				id = btn_T____
				tid = 272177947844255
			{
				Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = end ud
					only-changed = false
					prevalidate = false
					modal = false
				}
			}
			--- Glue ---
		}
	}
}