# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Alert Definition"
	containment = container
	domainEntity = "AlertDef:AlertDefAll"
	bean-define = DSBean.AlertDef.AlertDefAll
	bean-name = AlertDefAll
	id = AlertDef_hXGlf
	tid = 327242351809260
{
	--- Box ---
		boxType = vertical
	{
		--- Box ---
			labels en = Identification
			boxType = vertical
			tid = 2312357738743890
		{
			--- Conditional ---
				indexOfSelectedChild = 1
			{
				--- ConditionalBody ---
					javaCode = "Integer.valueOf(0).equals(<bean:get-property bean=\"AlertDefAll\" property=\"visibilityE\"/>)"
					technicalName = Public
					boxType = vertical
					isWidgetVisible = false
				{
					--- Grid ---
						cssClass = blank
						gridColumnCount = 2
						gridColumnsWidth = "10,90" !
						gridRowCount = 6
					{
						--- GridCell ---
							gridColumnWidth = 10
						{
							--- LabelDomain ---
								domainAttribute = name !
								for = name
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								id = name
						}
						--- GridCell ---
							gridColumnWidth = 90
						{
							--- TextField ---
								domainAttribute = name !
								columns = 30
								horizontalAlignment = "${corporatehalign}"
								type = text
								chars = 60
								bean-property = name
								id = name
						}
						--- GridCell ---
							gridColumnWidth = 10
						{
							--- LabelDomain ---
								domainAttribute = descriptionC !
								for = descriptionC
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								id = descriptionC
						}
						--- GridCell ---
							gridColumnWidth = 90
						{
							--- TextArea ---
								domainAttribute = descriptionC !
								columns = 80
								horizontalAlignment = "${corporatehalign}"
								rows = 3
								type = text
								bean-property = descriptionC
								id = descriptionC
						}
						--- GridCell ---
							gridColumnWidth = 10
						{
							--- LabelDomain ---
								domainAttribute = activeE !
								for = activeE
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
								id = activeE
						}
						--- GridCell ---
							gridColumnWidth = 90
						{
							--- ComboBox ---
								domainAttribute = activeE !
								horizontalAlignment = "${corporatehalign}"
								required = true
								bean-property = activeE
								id = activeE
						}
						--- GridCell ---
							gridColumnWidth = 10
						{
							--- LabelDomain ---
								domainAttribute = severityE !
								for = severityE
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
								id = severityE
						}
						--- GridCell ---
							gridColumnWidth = 90
						{
							--- ComboBox ---
								domainAttribute = severityE !
								horizontalAlignment = "${corporatehalign}"
								required = true
								bean-property = severityE
								id = severityE
						}
						--- GridCell ---
							gridColumnWidth = 10
						{
							--- LabelDomain ---
								domainAttribute = notifPatternE !
								for = notifPatternE
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
								id = notifPatternE
						}
						--- GridCell ---
							gridColumnWidth = 90
						{
							--- ComboBox ---
								domainAttribute = notifPatternE !
								horizontalAlignment = "${corporatehalign}"
								required = true
								bean-property = notifPatternE
								id = notifPatternE
						}
						--- GridCell ---
							gridColumnWidth = 10
						{
							--- LabelDomain ---
								domainAttribute = dataSecuProf !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
						}
						--- GridCell ---
							gridColumnWidth = 90
						{
							--- Include ---
								domainAssociation = dataSecuProf
								includeSrc = "" !
								resource:///default/defaultFragments/DataSecuProfIdentifierRequired.fragment
								bean-property-prefix = dataSecuProf.
						}
					}
				}
				--- ConditionalBody ---
					javaCode = true
					technicalName = Private
					boxType = vertical
					isWidgetSelected = true
				{
					--- Grid ---
						cssClass = blank
						gridColumnCount = 2
						gridColumnsWidth = "10,90" !
						gridRowCount = 5
					{
						--- GridCell ---
							gridColumnWidth = 10
						{
							--- LabelDomain ---
								domainAttribute = name !
								for = name
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								id = name
						}
						--- GridCell ---
							gridColumnWidth = 90
						{
							--- TextField ---
								domainAttribute = name !
								columns = 30
								horizontalAlignment = "${corporatehalign}"
								type = text
								chars = 60
								bean-property = name
								id = name
						}
						--- GridCell ---
							gridColumnWidth = 10
						{
							--- LabelDomain ---
								domainAttribute = descriptionC !
								for = descriptionC
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								id = descriptionC
						}
						--- GridCell ---
							gridColumnWidth = 90
						{
							--- TextArea ---
								domainAttribute = descriptionC !
								columns = 80
								horizontalAlignment = "${corporatehalign}"
								rows = 3
								type = text
								bean-property = descriptionC
								id = descriptionC
						}
						--- GridCell ---
							gridColumnWidth = 10
						{
							--- LabelDomain ---
								domainAttribute = activeE !
								for = activeE
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
								id = activeE
						}
						--- GridCell ---
							gridColumnWidth = 90
						{
							--- ComboBox ---
								domainAttribute = activeE !
								horizontalAlignment = "${corporatehalign}"
								required = true
								bean-property = activeE
								id = activeE
						}
						--- GridCell ---
							gridColumnWidth = 10
						{
							--- LabelDomain ---
								domainAttribute = severityE !
								for = severityE
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
								id = severityE
						}
						--- GridCell ---
							gridColumnWidth = 90
						{
							--- ComboBox ---
								domainAttribute = severityE !
								horizontalAlignment = "${corporatehalign}"
								required = true
								bean-property = severityE
								id = severityE
						}
						--- GridCell ---
							gridColumnWidth = 10
						{
							--- LabelDomain ---
								domainAttribute = notifPatternE !
								for = notifPatternE
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
								id = notifPatternE
						}
						--- GridCell ---
							gridColumnWidth = 90
						{
							--- ComboBox ---
								domainAttribute = notifPatternE !
								horizontalAlignment = "${corporatehalign}"
								required = true
								bean-property = notifPatternE
								id = notifPatternE
						}
					}
				}
			}
		}
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/alerts/update/AlertScheduleEdit.module
		--- Box ---
		{
			--- Button ---
				labels en = Next
				id = btn_dK___
				tid = 2737352664654
			{
				Event OnClick (submit)
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					widget-group-ref = form
					target = self
					only-changed = false
					prevalidate = true
					modal = false
					param = "flow-action=next"
				}
			}
			--- Button ---
				labels en = Cancel, fr = Annuler, de = Abbrechen
				id = btn_NP9__
				tid = 875748111240395
			{
				Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = cancel ud
					only-changed = false
					prevalidate = false
					modal = false
				}
			}
			--- Glue ---
		}
	}
}