# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = Schedule
	domainEntity = "AlertDef:ScheduleDefAll"
	cssClass = nodeco
	bean-define = DSBean.AlertDef.ScheduleDefAll
	bean-name = ScheduleDefAll
	id = AlertScheduleEdit_ZUf76
	tid = 237277865927726
{
	--- Box ---
		labels en = "Schedule Definition"
		boxType = vertical
		tid = 2710039575700
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 2
			gridColumnsWidth = "50,50" !
			gridRowCount = 2
		{
			--- GridCell ---
				gridColumnWidth = 50
			{
				--- LabelDomain ---
					domainAttribute = frequencyE !
					for = frequencyE
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					required = true
					id = frequencyE
			}
			--- GridCell ---
				gridColumnWidth = 50
			{
				--- ComboBox ---
					domainAttribute = frequencyE !
					horizontalAlignment = "${corporatehalign}"
					required = true
					bean-property = frequencyE
					id = frequencyE
				{
					Event OnChange (submit)
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						widget-group-ref = form
						target = self
						param = "flow-action=changeFrequency"
						only-changed = true
						prevalidate = false
						modal = false
					}
				}
			}
			--- GridCell ---
				gridColumnWidth = 50
			--- GridCell ---
				gridColumnWidth = 50
		}
		--- Conditional ---
			indexOfSelectedChild = 1
		{
			--- ConditionalBody ---
				javaCode = "Integer.valueOf(com.odcgroup.aaa.ScheduleDefFrequencyE.OneTime).equals(<bean:get-property bean=\"ScheduleDefAll\" property=\"frequencyE\"/>)"
				technicalName = OneTime
				boxType = vertical
				isWidgetVisible = false
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 4
					gridColumnsWidth = "25,25,25,25" !
					gridRowCount = 2
				{
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- LabelDomain ---
							labels en = "Date Of Execution"
							domainAttribute = startD !
							for = startD
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							id = startD
							tid = 213723725862644
					}
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- CaldateField ---
							domainAttribute = startD !
							format = datetime.date-only
							horizontalAlignment = "${corporatehalign}"
							type = datetime
							required = true
							bean-property = startD
							id = startD
					}
					--- GridCell ---
						gridColumnWidth = 25
					--- GridCell ---
						gridColumnWidth = 25
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- LabelDomain ---
							labels en = "Time Of Execution"
							domainAttribute = startTimeD !
							for = startTimeD
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							id = startTimeD
							tid = 213730201597409
					}
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- CaldateField ---
							domainAttribute = startTimeD !
							format = datetime.time-only-edit
							horizontalAlignment = "${corporatehalign}"
							type = datetime
							required = true
							bean-property = startTimeD
							id = startTimeD
					}
					--- GridCell ---
						gridColumnWidth = 25
					--- GridCell ---
						gridColumnWidth = 25
				}
			}
			--- ConditionalBody ---
				javaCode = "Integer.valueOf(com.odcgroup.aaa.ScheduleDefFrequencyE.Daily).equals(<bean:get-property bean=\"ScheduleDefAll\" property=\"frequencyE\"/>)"
				technicalName = Daily
				boxType = vertical
				isWidgetSelected = true
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 2
					gridColumnsWidth = "50,50" !
					gridRowCount = 1
				{
					--- GridCell ---
						gridColumnWidth = 50
					{
						--- LabelDomain ---
							domainAttribute = runOnce !
							for = runOnce
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							id = runOnce
					}
					--- GridCell ---
						gridColumnWidth = 50
					{
						--- CheckBox ---
							column-checkbox-action = ""
							domainAttribute = runOnce !
							displayLabel = false
							horizontalAlignment = "${corporatehalign}"
							horizontalTextPosition = trail
							bean-property = runOnce
							id = runOnce
						{
							Event OnClick (submit)
							{
								method = get
								call-URI = "<pageflow:continuation/>"
								widget-group-ref = "*"
								target = self
								param = "flow-action=changeRunOnce"
								only-changed = false
								prevalidate = false
								modal = false
							}
						}
					}
				}
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "(<bean:get-property bean=\"ScheduleDefAll\" property=\"runOnce\"/> != null) &amp;&amp; \r\n(((Boolean)<bean:get-property bean=\"ScheduleDefAll\" property=\"runOnce\"/>).booleanValue())"
						technicalName = "Run Once Per Day"
						boxType = vertical
						isWidgetSelected = true
					{
						--- Grid ---
							cssClass = blank
							gridColumnCount = 2
							gridColumnsWidth = "50,50" !
							gridRowCount = 2
						{
							--- GridCell ---
								gridColumnWidth = 50
							{
								--- LabelDomain ---
									labels en = "Time Of Execution"
									domainAttribute = startTimeD !
									for = startTimeD
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
									id = startTimeD
									tid = 39414895434196
							}
							--- GridCell ---
								gridColumnWidth = 50
							{
								--- CaldateField ---
									domainAttribute = startTimeD !
									format = datetime.time-only
									horizontalAlignment = "${corporatehalign}"
									type = datetime
									bean-property = startTimeD
									id = startTimeD
							}
							--- GridCell ---
								gridColumnWidth = 50
							{
								--- LabelDomain ---
									domainAttribute = expirationD !
									for = expirationD
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
									id = expirationD
							}
							--- GridCell ---
								gridColumnWidth = 50
							{
								--- CaldateField ---
									domainAttribute = expirationD !
									format = datetime.date-only
									horizontalAlignment = "${corporatehalign}"
									type = datetime
									bean-property = expirationD
									id = expirationD
							}
						}
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetVisible = false
					{
						--- Grid ---
							cssClass = blank
							gridColumnCount = 4
							gridColumnsWidth = "25,25,25,25" !
							gridRowCount = 3
						{
							--- GridCell ---
								gridColumnWidth = 25
							{
								--- LabelDomain ---
									domainAttribute = startTimeD !
									for = startTimeD
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
									id = startTimeD
							}
							--- GridCell ---
								gridColumnWidth = 25
							{
								--- CaldateField ---
									domainAttribute = startTimeD !
									format = datetime.time-only
									horizontalAlignment = "${corporatehalign}"
									type = datetime
									bean-property = startTimeD
									id = startTimeD
							}
							--- GridCell ---
								gridColumnWidth = 25
							{
								--- LabelDomain ---
									domainAttribute = endTimeD !
									for = endTimeD
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
									id = endTimeD
							}
							--- GridCell ---
								gridColumnWidth = 25
							{
								--- CaldateField ---
									domainAttribute = endTimeD !
									format = datetime.time-only-edit
									horizontalAlignment = "${corporatehalign}"
									type = datetime
									bean-property = endTimeD
									id = endTimeD
							}
							--- GridCell ---
								gridColumnWidth = 25
							{
								--- LabelDomain ---
									domainAttribute = expirationD !
									for = expirationD
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
									id = expirationD
							}
							--- GridCell ---
								gridColumnWidth = 25
							{
								--- CaldateField ---
									domainAttribute = expirationD !
									format = datetime.date-only
									horizontalAlignment = "${corporatehalign}"
									type = datetime
									bean-property = expirationD
									id = expirationD
							}
							--- GridCell ---
								gridColumnWidth = 25
							{
								--- LabelDomain ---
									labels en = "Every <n> minutes"
									domainAttribute = recurMinutesN !
									for = recurMinutesN
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
									id = recurMinutesN
									tid = 3141469020783
							}
							--- GridCell ---
								gridColumnWidth = 25
							{
								--- TextField ---
									domainAttribute = recurMinutesN !
									columns = 3
									format = integer
									horizontalAlignment = "${corporatehalign}"
									type = integer
									chars = 3
									bean-property = recurMinutesN
									id = recurMinutesN
							}
							--- GridCell ---
								gridColumnWidth = 25
							--- GridCell ---
								gridColumnWidth = 25
							--- GridCell ---
								gridColumnWidth = 25
							--- GridCell ---
								gridColumnWidth = 25
						}
					}
				}
			}
			--- ConditionalBody ---
				javaCode = "Integer.valueOf(com.odcgroup.aaa.ScheduleDefFrequencyE.Weekly).equals(<bean:get-property bean=\"ScheduleDefAll\" property=\"frequencyE\"/>)"
				technicalName = Weekly
				boxType = vertical
				isWidgetVisible = false
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 2
					gridColumnsWidth = "50,50" !
					gridRowCount = 1
				{
					--- GridCell ---
						gridColumnWidth = 50
					{
						--- LabelDomain ---
							domainAttribute = runOnce !
							for = runOnce
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							id = runOnce
					}
					--- GridCell ---
						gridColumnWidth = 50
					{
						--- CheckBox ---
							column-checkbox-action = ""
							domainAttribute = runOnce !
							displayLabel = false
							horizontalAlignment = "${corporatehalign}"
							horizontalTextPosition = trail
							bean-property = runOnce
							id = runOnce
						{
							Event OnClick (submit)
							{
								method = get
								call-URI = "<pageflow:continuation/>"
								widget-group-ref = "*"
								target = self
								param = "flow-action=changeRunOnce"
								only-changed = false
								prevalidate = false
								modal = false
							}
						}
					}
				}
				--- Conditional ---
					indexOfSelectedChild = 1
				{
					--- ConditionalBody ---
						javaCode = "(<bean:get-property bean=\"ScheduleDefAll\" property=\"runOnce\"/> != null) &amp;&amp; \r\n(((Boolean)<bean:get-property bean=\"ScheduleDefAll\" property=\"runOnce\"/>).booleanValue())"
						technicalName = "Run Once Per Day"
						boxType = vertical
						isWidgetVisible = false
					{
						--- Grid ---
							cssClass = blank
							gridColumnCount = 2
							gridColumnsWidth = "50,50" !
							gridRowCount = 2
						{
							--- GridCell ---
								gridColumnWidth = 50
							{
								--- LabelDomain ---
									labels en = "Time Of Execution"
									domainAttribute = startTimeD !
									for = startTimeD
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
									id = startTimeD
									tid = 125501616308497
							}
							--- GridCell ---
								gridColumnWidth = 50
							{
								--- CaldateField ---
									domainAttribute = startTimeD !
									format = datetime.time-only
									horizontalAlignment = "${corporatehalign}"
									type = datetime
									bean-property = startTimeD
									id = startTimeD
							}
							--- GridCell ---
								gridColumnWidth = 50
							{
								--- LabelDomain ---
									domainAttribute = expirationD !
									for = expirationD
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
									id = expirationD
							}
							--- GridCell ---
								gridColumnWidth = 50
							{
								--- CaldateField ---
									domainAttribute = expirationD !
									format = datetime.date-only
									horizontalAlignment = "${corporatehalign}"
									type = datetime
									bean-property = expirationD
									id = expirationD
							}
						}
						--- Grid ---
							cssClass = blank
							gridColumnCount = 4
							gridColumnsWidth = "25,25,25,25" !
							gridRowCount = 5
						{
							--- GridCell ---
								gridColumnWidth = 25
								gridColumnCssClass = grey
							--- GridCell ---
								gridColumnWidth = 25
							--- GridCell ---
								gridColumnWidth = 25
							--- GridCell ---
								gridColumnWidth = 25
							--- GridCell ---
								gridColumnWidth = 25
								gridColumnCssClass = grey
							{
								--- Label ---
									labels en = Weekdays
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
									tid = 123588015817932
							}
							--- GridCell ---
								gridColumnWidth = 25
							{
								--- CheckBox ---
									column-checkbox-action = ""
									domainAttribute = mondayF
									horizontalTextPosition = trail
									bean-property = mondayF
									id = mondayF
							}
							--- GridCell ---
								gridColumnWidth = 25
							{
								--- CheckBox ---
									column-checkbox-action = ""
									domainAttribute = tuesdayF
									horizontalTextPosition = trail
									bean-property = tuesdayF
									id = tuesdayF
							}
							--- GridCell ---
								gridColumnWidth = 25
							{
								--- CheckBox ---
									column-checkbox-action = ""
									domainAttribute = wednesdayF
									horizontalTextPosition = trail
									bean-property = wednesdayF
									id = wednesdayF
							}
							--- GridCell ---
								gridColumnWidth = 25
								gridColumnCssClass = grey
							--- GridCell ---
								gridColumnWidth = 25
							{
								--- CheckBox ---
									column-checkbox-action = ""
									domainAttribute = thursdayF
									horizontalTextPosition = trail
									bean-property = thursdayF
									id = thursdayF
							}
							--- GridCell ---
								gridColumnWidth = 25
							{
								--- CheckBox ---
									column-checkbox-action = ""
									domainAttribute = fridayF
									horizontalTextPosition = trail
									bean-property = fridayF
									id = fridayF
							}
							--- GridCell ---
								gridColumnWidth = 25
							{
								--- CheckBox ---
									column-checkbox-action = ""
									domainAttribute = saturdayF
									horizontalTextPosition = trail
									bean-property = saturdayF
									id = saturdayF
							}
							--- GridCell ---
								gridColumnWidth = 25
								gridColumnCssClass = grey
							--- GridCell ---
								gridColumnWidth = 25
							{
								--- CheckBox ---
									column-checkbox-action = ""
									domainAttribute = sundayF
									horizontalTextPosition = trail
									bean-property = sundayF
									id = sundayF
							}
							--- GridCell ---
								gridColumnWidth = 25
							--- GridCell ---
								gridColumnWidth = 25
							--- GridCell ---
								gridColumnWidth = 25
								gridColumnCssClass = grey
							--- GridCell ---
								gridColumnWidth = 25
							--- GridCell ---
								gridColumnWidth = 25
							--- GridCell ---
								gridColumnWidth = 25
						}
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetSelected = true
					{
						--- Grid ---
							cssClass = blank
							gridColumnCount = 4
							gridColumnsWidth = "25,25,25,25" !
							gridRowCount = 7
						{
							--- GridCell ---
								gridColumnWidth = 25
							{
								--- LabelDomain ---
									domainAttribute = startTimeD !
									for = startTimeD
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
									id = startTimeD
							}
							--- GridCell ---
								gridColumnWidth = 25
							{
								--- CaldateField ---
									domainAttribute = startTimeD !
									format = datetime.time-only-edit
									horizontalAlignment = "${corporatehalign}"
									type = datetime
									bean-property = startTimeD
									id = startTimeD
							}
							--- GridCell ---
								gridColumnWidth = 25
							{
								--- LabelDomain ---
									domainAttribute = endTimeD !
									for = endTimeD
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
									id = endTimeD
							}
							--- GridCell ---
								gridColumnWidth = 25
							{
								--- CaldateField ---
									domainAttribute = endTimeD !
									format = datetime.time-only-edit
									horizontalAlignment = "${corporatehalign}"
									type = datetime
									bean-property = endTimeD
									id = endTimeD
							}
							--- GridCell ---
								gridColumnWidth = 25
							{
								--- LabelDomain ---
									domainAttribute = expirationD !
									for = expirationD
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
									id = expirationD
							}
							--- GridCell ---
								gridColumnWidth = 25
							{
								--- CaldateField ---
									domainAttribute = expirationD !
									format = datetime.date-only
									horizontalAlignment = "${corporatehalign}"
									type = datetime
									bean-property = expirationD
									id = expirationD
							}
							--- GridCell ---
								gridColumnWidth = 25
							{
								--- LabelDomain ---
									labels en = "Every <n> minutes"
									domainAttribute = recurMinutesN !
									for = recurMinutesN
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
									id = recurMinutesN
									tid = 123570430946111
							}
							--- GridCell ---
								gridColumnWidth = 25
							{
								--- TextField ---
									domainAttribute = recurMinutesN !
									columns = 3
									format = integer
									horizontalAlignment = "${corporatehalign}"
									type = integer
									chars = 3
									bean-property = recurMinutesN
									id = recurMinutesN
							}
							--- GridCell ---
								gridColumnWidth = 25
							--- GridCell ---
								gridColumnWidth = 25
							--- GridCell ---
								gridColumnWidth = 25
							--- GridCell ---
								gridColumnWidth = 25
							--- GridCell ---
								gridColumnWidth = 25
							{
								--- Label ---
									labels en = Weekdays
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
									tid = 123570432802493
							}
							--- GridCell ---
								gridColumnWidth = 25
							{
								--- CheckBox ---
									column-checkbox-action = ""
									domainAttribute = mondayF
									horizontalTextPosition = trail
									bean-property = mondayF
									id = mondayF
							}
							--- GridCell ---
								gridColumnWidth = 25
							{
								--- CheckBox ---
									column-checkbox-action = ""
									domainAttribute = tuesdayF
									horizontalTextPosition = trail
									bean-property = tuesdayF
									id = tuesdayF
							}
							--- GridCell ---
								gridColumnWidth = 25
							{
								--- CheckBox ---
									column-checkbox-action = ""
									domainAttribute = wednesdayF
									horizontalTextPosition = trail
									bean-property = wednesdayF
									id = wednesdayF
							}
							--- GridCell ---
								gridColumnWidth = 25
							--- GridCell ---
								gridColumnWidth = 25
							{
								--- CheckBox ---
									column-checkbox-action = ""
									domainAttribute = thursdayF
									horizontalTextPosition = trail
									bean-property = thursdayF
									id = thursdayF
							}
							--- GridCell ---
								gridColumnWidth = 25
							{
								--- CheckBox ---
									column-checkbox-action = ""
									domainAttribute = fridayF
									horizontalTextPosition = trail
									bean-property = fridayF
									id = fridayF
							}
							--- GridCell ---
								gridColumnWidth = 25
							{
								--- CheckBox ---
									column-checkbox-action = ""
									domainAttribute = saturdayF
									horizontalTextPosition = trail
									bean-property = saturdayF
									id = saturdayF
							}
							--- GridCell ---
								gridColumnWidth = 25
							--- GridCell ---
								gridColumnWidth = 25
							{
								--- CheckBox ---
									column-checkbox-action = ""
									domainAttribute = sundayF
									horizontalTextPosition = trail
									bean-property = sundayF
									id = sundayF
							}
							--- GridCell ---
								gridColumnWidth = 25
							--- GridCell ---
								gridColumnWidth = 25
							--- GridCell ---
								gridColumnWidth = 25
							--- GridCell ---
								gridColumnWidth = 25
							--- GridCell ---
								gridColumnWidth = 25
							--- GridCell ---
								gridColumnWidth = 25
						}
					}
				}
			}
			--- ConditionalBody ---
				javaCode = "Integer.valueOf(com.odcgroup.aaa.ScheduleDefFrequencyE.Monthly).equals(<bean:get-property bean=\"ScheduleDefAll\" property=\"frequencyE\"/>)"
				technicalName = Monthly
				boxType = vertical
				isWidgetVisible = false
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 2
					gridColumnsWidth = "50,50" !
					gridRowCount = 1
				{
					--- GridCell ---
						gridColumnWidth = 50
					{
						--- LabelDomain ---
							domainAttribute = runOnce !
							for = runOnce
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							id = runOnce
					}
					--- GridCell ---
						gridColumnWidth = 50
					{
						--- CheckBox ---
							column-checkbox-action = ""
							domainAttribute = runOnce !
							displayLabel = false
							horizontalAlignment = "${corporatehalign}"
							horizontalTextPosition = trail
							bean-property = runOnce
							id = runOnce
						{
							Event OnClick (submit)
							{
								method = get
								call-URI = "<pageflow:continuation/>"
								widget-group-ref = "*"
								target = self
								param = "flow-action=changeRunOnce"
								only-changed = false
								prevalidate = false
								modal = false
							}
						}
					}
				}
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "(<bean:get-property bean=\"ScheduleDefAll\" property=\"runOnce\"/> != null) &amp;&amp; \r\n(((Boolean)<bean:get-property bean=\"ScheduleDefAll\" property=\"runOnce\"/>).booleanValue())"
						technicalName = "Run Once Per Day"
						boxType = vertical
						isWidgetSelected = true
					{
						--- Grid ---
							cssClass = blank
							gridColumnCount = 2
							gridColumnsWidth = "50,50" !
							gridRowCount = 2
						{
							--- GridCell ---
								gridColumnWidth = 50
							{
								--- LabelDomain ---
									labels en = "Time Of Execution"
									domainAttribute = startTimeD !
									for = startTimeD
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
									id = startTimeD
									tid = 125507726597374
							}
							--- GridCell ---
								gridColumnWidth = 50
							{
								--- CaldateField ---
									domainAttribute = startTimeD !
									format = datetime.time-only
									horizontalAlignment = "${corporatehalign}"
									type = datetime
									bean-property = startTimeD
									id = startTimeD
							}
							--- GridCell ---
								gridColumnWidth = 50
							{
								--- LabelDomain ---
									domainAttribute = expirationD !
									for = expirationD
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
									id = expirationD
							}
							--- GridCell ---
								gridColumnWidth = 50
							{
								--- CaldateField ---
									domainAttribute = expirationD !
									format = datetime.date-only
									horizontalAlignment = "${corporatehalign}"
									type = datetime
									bean-property = expirationD
									id = expirationD
							}
						}
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetVisible = false
					{
						--- Grid ---
							cssClass = blank
							gridColumnCount = 5
							gridColumnsWidth = "20,20,20,20,20" !
							gridRowCount = 2
						{
							--- GridCell ---
								gridColumnWidth = 20
							{
								--- LabelDomain ---
									domainAttribute = startTimeD !
									for = startTimeD
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
									id = startTimeD
							}
							--- GridCell ---
								gridColumnWidth = 20
							{
								--- CaldateField ---
									domainAttribute = startTimeD !
									format = datetime.time-only-edit
									horizontalAlignment = "${corporatehalign}"
									type = datetime
									bean-property = startTimeD
									id = startTimeD
							}
							--- GridCell ---
								gridColumnWidth = 20
							{
								--- LabelDomain ---
									domainAttribute = endTimeD !
									for = endTimeD
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
									id = endTimeD
							}
							--- GridCell ---
								gridColumnWidth = 20
							{
								--- CaldateField ---
									domainAttribute = endTimeD !
									format = datetime.time-only-edit
									horizontalAlignment = "${corporatehalign}"
									type = datetime
									bean-property = endTimeD
									id = endTimeD
							}
							--- GridCell ---
								gridColumnWidth = 20
							--- GridCell ---
								gridColumnWidth = 20
							{
								--- LabelDomain ---
									domainAttribute = expirationD !
									for = expirationD
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
									id = expirationD
							}
							--- GridCell ---
								gridColumnWidth = 20
							{
								--- CaldateField ---
									domainAttribute = expirationD !
									format = datetime.date-only
									horizontalAlignment = "${corporatehalign}"
									type = datetime
									bean-property = expirationD
									id = expirationD
							}
							--- GridCell ---
								gridColumnWidth = 20
							{
								--- LabelDomain ---
									labels en = "Every <n> minutes"
									domainAttribute = recurMinutesN !
									for = recurMinutesN
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
									id = recurMinutesN
									tid = 123785919207608
							}
							--- GridCell ---
								gridColumnWidth = 20
							{
								--- TextField ---
									domainAttribute = recurMinutesN !
									columns = 3
									format = integer
									horizontalAlignment = "${corporatehalign}"
									type = integer
									chars = 3
									bean-property = recurMinutesN
									id = recurMinutesN
							}
							--- GridCell ---
								gridColumnWidth = 20
						}
					}
				}
				--- Grid ---
					cssClass = blank
					gridColumnCount = 5
					gridColumnsWidth = "20,20,20,20,20" !
					gridRowCount = 5
				{
					--- GridCell ---
						gridColumnWidth = 20
					--- GridCell ---
						gridColumnWidth = 20
					--- GridCell ---
						gridColumnWidth = 20
					--- GridCell ---
						gridColumnWidth = 20
					--- GridCell ---
						gridColumnWidth = 20
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- Label ---
							labels en = Months
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							tid = 127032601431187
					}
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- CheckBox ---
							column-checkbox-action = ""
							domainAttribute = januaryF
							horizontalTextPosition = trail
							bean-property = januaryF
							id = januaryF
					}
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- CheckBox ---
							column-checkbox-action = ""
							domainAttribute = aprilF
							horizontalTextPosition = trail
							bean-property = aprilF
							id = aprilF
					}
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- CheckBox ---
							column-checkbox-action = ""
							domainAttribute = julyF
							horizontalTextPosition = trail
							bean-property = julyF
							id = julyF
					}
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- CheckBox ---
							column-checkbox-action = ""
							domainAttribute = octoberF
							horizontalTextPosition = trail
							bean-property = octoberF
							id = octoberF
					}
					--- GridCell ---
						gridColumnWidth = 20
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- CheckBox ---
							column-checkbox-action = ""
							domainAttribute = februaryF
							horizontalTextPosition = trail
							bean-property = februaryF
							id = februaryF
					}
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- CheckBox ---
							column-checkbox-action = ""
							domainAttribute = mayF
							horizontalTextPosition = trail
							bean-property = mayF
							id = mayF
					}
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- CheckBox ---
							column-checkbox-action = ""
							domainAttribute = augustF
							horizontalTextPosition = trail
							bean-property = augustF
							id = augustF
					}
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- CheckBox ---
							column-checkbox-action = ""
							domainAttribute = novemberF
							horizontalTextPosition = trail
							bean-property = novemberF
							id = novemberF
					}
					--- GridCell ---
						gridColumnWidth = 20
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- CheckBox ---
							column-checkbox-action = ""
							domainAttribute = marchF
							horizontalTextPosition = trail
							bean-property = marchF
							id = marchF
					}
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- CheckBox ---
							column-checkbox-action = ""
							domainAttribute = juneF
							horizontalTextPosition = trail
							bean-property = juneF
							id = juneF
					}
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- CheckBox ---
							column-checkbox-action = ""
							domainAttribute = septemberF
							horizontalTextPosition = trail
							bean-property = septemberF
							id = septemberF
					}
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- CheckBox ---
							column-checkbox-action = ""
							domainAttribute = decemberF
							horizontalTextPosition = trail
							bean-property = decemberF
							id = decemberF
					}
					--- GridCell ---
						gridColumnWidth = 20
					--- GridCell ---
						gridColumnWidth = 20
					--- GridCell ---
						gridColumnWidth = 20
					--- GridCell ---
						gridColumnWidth = 20
					--- GridCell ---
						gridColumnWidth = 20
				}
				--- Grid ---
					cssClass = blank
					gridColumnCount = 2
					gridColumnsWidth = "50,50" !
					gridRowCount = 2
				{
					--- GridCell ---
						gridColumnWidth = 50
					{
						--- LabelDomain ---
							domainAttribute = monthlyRunMode !
							for = monthlyRunMode
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							id = monthlyRunMode
					}
					--- GridCell ---
						gridColumnWidth = 50
					{
						--- ComboBox ---
							domainAttribute = monthlyRunMode !
							horizontalAlignment = "${corporatehalign}"
							bean-property = monthlyRunMode
							id = monthlyRunMode
						{
							Event OnChange (submit)
							{
								method = get
								call-URI = "<pageflow:continuation/>"
								widget-group-ref = "*"
								target = self
								param = "flow-action=changeRunOnce"
								only-changed = false
								prevalidate = false
								modal = false
							}
						}
					}
					--- GridCell ---
						gridColumnWidth = 50
					--- GridCell ---
						gridColumnWidth = 50
				}
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "(<bean:get-property bean=\"ScheduleDefAll\" property=\"monthlyRunMode\"/> != null) &amp;&amp; \r\n(((Integer)<bean:get-property bean=\"ScheduleDefAll\" property=\"monthlyRunMode\"/>).intValue() == 0)"
						technicalName = "Run Given Month Day"
						boxType = vertical
						isWidgetSelected = true
					{
						--- Grid ---
							cssClass = blank
							gridColumnCount = 2
							gridColumnsWidth = "50,50" !
							gridRowCount = 1
						{
							--- GridCell ---
								gridColumnWidth = 50
							{
								--- LabelDomain ---
									domainAttribute = dayOfMonth !
									for = dayOfMonth
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
									width = 2
									id = dayOfMonth
							}
							--- GridCell ---
								gridColumnWidth = 50
							{
								--- TextField ---
									domainAttribute = dayOfMonth !
									columns = 2
									format = integer
									horizontalAlignment = "${corporatehalign}"
									type = integer
									chars = 2
									bean-property = dayOfMonth
									id = dayOfMonth
							}
						}
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = "Default, Run given weekday"
						boxType = vertical
						isWidgetVisible = false
					{
						--- Grid ---
							cssClass = blank
							gridColumnCount = 5
							gridColumnsWidth = "20,20,20,20,20" !
							gridRowCount = 2
						{
							--- GridCell ---
								gridColumnWidth = 20
							{
								--- Label ---
									labels en = Weekdays
									cssClass = grey
									horizontalAlignment = "${corporatehalign}"
									tid = 128251392323046
							}
							--- GridCell ---
								gridColumnWidth = 20
							{
								--- CheckBox ---
									column-checkbox-action = ""
									domainAttribute = mondayF
									horizontalTextPosition = trail
									bean-property = mondayF
									id = mondayF
							}
							--- GridCell ---
								gridColumnWidth = 20
							{
								--- CheckBox ---
									column-checkbox-action = ""
									domainAttribute = tuesdayF
									horizontalTextPosition = trail
									bean-property = tuesdayF
									id = tuesdayF
							}
							--- GridCell ---
								gridColumnWidth = 20
							{
								--- CheckBox ---
									column-checkbox-action = ""
									domainAttribute = wednesdayF
									horizontalTextPosition = trail
									bean-property = wednesdayF
									id = wednesdayF
							}
							--- GridCell ---
								gridColumnWidth = 20
							{
								--- CheckBox ---
									column-checkbox-action = ""
									domainAttribute = thursdayF
									horizontalTextPosition = trail
									bean-property = thursdayF
									id = thursdayF
							}
							--- GridCell ---
								gridColumnWidth = 20
							--- GridCell ---
								gridColumnWidth = 20
							{
								--- CheckBox ---
									column-checkbox-action = ""
									domainAttribute = fridayF
									horizontalTextPosition = trail
									bean-property = fridayF
									id = fridayF
							}
							--- GridCell ---
								gridColumnWidth = 20
							{
								--- CheckBox ---
									column-checkbox-action = ""
									domainAttribute = saturdayF
									horizontalTextPosition = trail
									bean-property = saturdayF
									id = saturdayF
							}
							--- GridCell ---
								gridColumnWidth = 20
							{
								--- CheckBox ---
									column-checkbox-action = ""
									domainAttribute = sundayF
									horizontalTextPosition = trail
									bean-property = sundayF
									id = sundayF
							}
							--- GridCell ---
								gridColumnWidth = 20
						}
					}
				}
			}
		}
	}
}