# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Confirm Alert Deletion"
	domainEntity = "AlertDef:AlertDefAll"
	bean-define = DSBean.AlertDef.AlertDefAll
	bean-name = AlertDefAll
	id = AlertConfirmDelete_e_6__
	tid = 438635881626575
{
	--- Box ---
		boxType = vertical
	{
		--- Box ---
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 3
				gridColumnsWidth = "25,50,25" !
				gridRowCount = 2
			{
				--- GridCell ---
					gridColumnWidth = 25
				--- GridCell ---
					gridColumnWidth = 50
				{
					--- Label ---
						labels en = "Are you sure you want to delete the alert "
						horizontalAlignment = center
						tid = 438689406657270
					--- Spacer ---
						height = 4
						width = 4
					--- Code ---
						code = "<xgui:label class=\"bold\"><xgui:text>\r\n <bean:get-property bean=\"AlertDefAll\" property=\"name\" />\r\n</xgui:text></xgui:label>"
					--- Label ---
						labels en = "?"
						horizontalAlignment = "${corporatehalign}"
						tid = 443449635993960
				}
				--- GridCell ---
					gridColumnWidth = 25
				--- GridCell ---
					gridColumnWidth = 25
				--- GridCell ---
					gridColumnWidth = 50
				--- GridCell ---
					gridColumnWidth = 25
			}
		}
		--- Box ---
		{
			--- Button ---
				labels en = Yes
				horizontalAlignment = center
				id = btn_C___q
				tid = 438877465209125
			{
				Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = WUI_main
					flow-action = confirmDelete ud
					only-changed = false
					prevalidate = false
					modal = false
				}
			}
			--- Button ---
				labels en = No
				horizontalAlignment = center
				id = btn_q6_xF
				tid = 438881695632545
			{
				Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = WUI_main
					flow-action = cancelDelete ud
					only-changed = false
					prevalidate = false
					modal = false
				}
			}
		}
	}
}