# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Search Client Output"
	domainEntity = "AAADSThirdParty:ThirdPartyList"
	search = output
	bean-define = DSBean.AAADSThirdParty.ThirdPartyList
	bean-name = ThirdPartyList
	id = AlertSearchClientOutput_P0j__
	tid = 984170884513462
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			id = A6l__
			table-model-reference = DSTableModel.AAADSThirdParty.ThirdPartyList
			table-column-count = 14 !
			table-columns-width = "7,7,7,7,7,7,7,7,7,7,7,7,7,7" !
		{
			--- TableColumn ---
				column-name = code !
				column-type = domain !
				domainAttribute = code !
				type = text
				id = code
				table-column-width = 7
			{
				--- TableColumnItem ---
					item-column = code
					previewValue = value
			}
			--- TableColumn ---
				column-name = name !
				column-type = domain !
				domainAttribute = name !
				id = name
				table-column-width = 7
			{
				--- Icon ---
					toolTips en = "View Client Details", fr = "Voir les détails du client", de = "Details der Kunde ansehen"
					icon = application_form_magnify
					id = bK2_5
					tid = 730539469185329
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "resource:///administration/client/ClientDetailsSimplifiedView.pageflow"
						target = layer
						code = "<udp:item column=\"code\"/>" ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
				--- Spacer ---
					height = 4
					width = 10
				--- TableColumnItem ---
					item-column = name
					previewValue = value
			}
			--- TableColumn ---
				column-name = extDenomination !
				column-type = domain !
				domainAttribute = extDenomination !
				type = text
				id = extDenomination
				table-column-width = 7
			{
				--- TableColumnItem ---
					item-column = extDenomination
					previewValue = value
			}
			--- TableColumn ---
				column-name = typeExtDenomination !
				column-type = domain !
				domainAttribute = typeExtDenomination !
				type = text
				id = typeExtDenomination
				table-column-width = 7
			{
				--- TableColumnItem ---
					item-column = typeExtDenomination
					previewValue = value
			}
			--- TableColumn ---
				column-name = currencyExtDenomination !
				column-type = domain !
				domainAttribute = currencyExtDenomination !
				type = text
				id = currencyExtDenomination
				table-column-width = 7
			{
				--- TableColumnItem ---
					item-column = currencyExtDenomination
					previewValue = value
			}
			--- TableColumn ---
				column-name = residGeoExtDenomination !
				column-type = domain !
				domainAttribute = residGeoExtDenomination !
				type = text
				id = residGeoExtDenomination
				table-column-width = 7
			{
				--- TableColumnItem ---
					item-column = residGeoExtDenomination
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Market Value (Sys. Ccy.)", fr = "Valeur de marché (devise sys.)", de = "Marktwert (Sys. Währung)"
				column-name = MarketValue
				type = amount
				column-visibility = not-visible
				id = CKi2_
				column-computation = make-amount
				column-computation-parameters = "extTdMktValM,extRefCur"
				table-column-width = 7
				tid = 730539471101215
			{
				--- TableColumnItem ---
					item-column = MarketValue
					previewValue = value
			}
			--- TableColumn ---
				column-name = extAdvisoryMandate !
				column-type = domain !
				domainAttribute = extAdvisoryMandate !
				type = text
				column-visibility = not-visible
				id = extAdvisoryMandate
				table-column-width = 7
			{
				--- TableColumnItem ---
					item-column = extAdvisoryMandate
					previewValue = value
			}
			--- TableColumn ---
				column-name = extObjCompliance !
				column-type = domain !
				domainAttribute = extObjCompliance !
				type = text
				column-visibility = not-visible
				id = extObjCompliance
				table-column-width = 7
			{
				--- TableColumnItem ---
					item-column = extObjCompliance
					previewValue = value
			}
			--- TableColumn ---
				column-name = extCstCompliance !
				column-type = domain !
				domainAttribute = extCstCompliance !
				type = text
				column-visibility = not-visible
				id = extCstCompliance
				table-column-width = 7
			{
				--- TableColumnItem ---
					item-column = extCstCompliance
					previewValue = value
			}
			--- TableColumn ---
				column-name = extDaysProposal !
				column-type = domain !
				domainAttribute = extDaysProposal !
				format = integer
				type = text
				column-visibility = not-visible
				id = extDaysProposal
				table-column-width = 7
			{
				--- TableColumnItem ---
					item-column = extDaysProposal
					previewValue = value
			}
			--- TableColumn ---
				column-name = extDateProposal !
				column-type = domain !
				domainAttribute = extDateProposal !
				format = date
				type = text
				column-visibility = not-visible
				id = extDateProposal
				table-column-width = 7
			{
				--- TableColumnItem ---
					item-column = extDateProposal
					previewValue = value
			}
			--- TableColumn ---
				column-name = activeF !
				column-type = domain !
				domainAttribute = activeF !
				type = text
				id = activeF
				table-column-width = 7
			{
				--- TableColumnItem ---
					item-column = activeF
					previewValue = value
			}
			--- TableColumn ---
				labels de = Status
				column-name = statusE !
				column-type = domain !
				domainAttribute = statusE !
				type = text
				id = statusE
				table-column-width = 7
				tid = 730539473041964
			{
				--- TableColumnItem ---
					item-column = statusE
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = code
				sort-rank = 1
			--- TableSort ---
				sort-column-name = name
				sort-rank = 2
		}
	}
}