# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Portfolio Summary Views", fr = "Vues résumées du portefeuille", de = "Portfolio Zusammenfassung"
	domainEntity = "AAADSPerformance:PerformanceGlobalSummary"
	bean-define = DSBean.AAADSPerformance.PerformanceGlobalSummary
	bean-name = PerformanceGlobalSummary
	id = PerformanceGlobalPortfolioSummary_tc136
	tid = 12815919358642
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			id = e7x9y
			table-column-count = 27 !
			table-columns-width = "3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3" !
		{
			--- TableColumn ---
				labels en = Portfolio, fr = Portefeuille, de = Portfolio
				column-display-grouping = true
				column-name = GROUPING
				column-type = placeholder !
				type = text
				column-locked = true
				column-sortable = false !
				id = F__8_
				table-column-width = 3
				tid = 90252278969553
			{
				--- TableGroup ---
					aggregateData = false
					group-column-name = PTF_HIER_STR
					group-sorting-column-name = PTF_HIER_STR
					group-sorting-direction = ascending
					hierarchy = true
					group-rank = 1
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = selectPortfolio ud
						portfolioDimPortfolio.code = "<udp:item column=\"_nodeCode\"/>" ud
						portfolioDimensionE = 1 ud
						only-changed = false
						prevalidate = false
						modal = false
						Snippet FilterSet
						id = fs_cka
						level = 1
						targetDataset = "AAADSPerformance:PerformanceGlobalSummary"
						{
							Snippet Filter
							attribute = PORTFOLIO_CODE
							filterValue = "<udp:item column=\"PORTFOLIO_CODE\"/>"
							operator = EQUAL
						}
						Snippet FilterSet
						id = fs_K21
						level = 1
						targetDataset = "AAADSPerformance:PerformanceGlobalDetails"
						{
							Snippet Filter
							attribute = PORTFOLIO_CODE
							filterValue = "<udp:item column=\"PORTFOLIO_CODE\"/>"
							operator = EQUAL
						}
					}
				}
			}
			--- TableColumn ---
				column-name = CLIENT_NAME !
				column-type = domain !
				domainAttribute = CLIENT_NAME !
				type = text
				column-visibility = not-visible
				id = CLIENT_NAME
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = CLIENT_NAME
					previewValue = value
			}
			--- TableColumn ---
				column-name = PORTFOLIO_INVEST_SERVICE !
				column-type = domain !
				domainAttribute = PORTFOLIO_INVEST_SERVICE !
				type = text
				column-visibility = not-visible
				id = PORTFOLIO_INVEST_SERVICE
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = PORTFOLIO_INVEST_SERVICE
					previewValue = value
			}
			--- TableColumn ---
				column-name = ADMIN_MGR_NAME !
				column-type = domain !
				domainAttribute = ADMIN_MGR_NAME !
				type = text
				column-visibility = not-visible
				id = ADMIN_MGR_NAME
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = ADMIN_MGR_NAME
					previewValue = value
			}
			--- TableColumn ---
				column-name = COM_MGR_NAME !
				column-type = domain !
				domainAttribute = COM_MGR_NAME !
				type = text
				column-visibility = not-visible
				id = COM_MGR_NAME
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = COM_MGR_NAME
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Initial Market Value", fr = "Valeur d\'inventaire initiale", de = Anfangs-Marktwert
				column-name = InitialMarketValue
				type = amount
				id = G__42
				column-computation = make-amount
				column-computation-parameters = "PERIOD_INITIAL_MKT_VAL,REF_CURRENCY"
				table-column-width = 3
				tid = 12815919737296
			{
				--- TableColumnItem ---
					item-column = InitialMarketValue
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Final Market Value", fr = "Valeur d\'inventaire finale", de = End-Marktwert
				column-name = FinalMarketValue
				type = amount
				id = q_m25
				column-computation = make-amount
				column-computation-parameters = "PERIOD_FINAL_MKT_VAL,REF_CURRENCY"
				table-column-width = 3
				tid = 12815922092946
			{
				--- TableColumnItem ---
					item-column = FinalMarketValue
					previewValue = value
			}
			--- TableColumn ---
				labels en = Investment/Withdrawal, fr = Apport/retrait, de = "Zuflüsse / Abflüsse"
				column-name = InvestmentandWithdrawal
				type = amount
				id = M_7tY
				column-computation = make-amount
				column-computation-parameters = "PERIOD_INVEST_WITHDRAWAL,REF_CURRENCY"
				table-column-width = 3
				tid = 12815923763592
			{
				--- TableColumnItem ---
					item-column = InvestmentandWithdrawal
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Profit & Loss", fr = "Gains & pertes", de = "Gewinn & Verlust"
				column-name = ProfitLoss
				type = amount
				id = V__r3
				column-computation = make-amount
				column-computation-parameters = "PERIOD_GAIN_LOSS,REF_CURRENCY"
				table-column-width = 3
				tid = 12815927640297
			{
				--- TableColumnItem ---
					item-column = ProfitLoss
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Capital P&L", fr = "G&P sur capital", de = Kapital-G/V toolTips en = "Capital Profit & Loss", fr = "Gains & pertes en capital", de = "Kapital Gewinn & Verlust"
				column-name = CapitalProfitLoss
				type = amount
				id = TC__6
				column-computation = make-amount
				column-computation-parameters = "PERIOD_CAP_PL,REF_CURRENCY"
				table-column-width = 3
				tid = 12815929506993
			{
				--- TableColumnItem ---
					item-column = CapitalProfitLoss
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Currency P&L", fr = "G&P sur devise", de = Währungs-G/V toolTips en = "Currency Profit & Loss", fr = "Gains & pertes sur devise", de = "Währungs- Gewinn & Verlust"
				column-name = CurrencyProfitLoss
				type = amount
				id = p1_U5
				column-computation = make-amount
				column-computation-parameters = "PERIOD_CURR_PL,REF_CURRENCY"
				table-column-width = 3
				tid = 12815935349671
			{
				--- TableColumnItem ---
					item-column = CurrencyProfitLoss
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Real. Capital P&L", fr = "G&P sur capital réalisés", de = "Real. Kapital G/V" toolTips en = "Realized Capital Profit & Loss", fr = "Gains & Pertes sur capital réalisés", de = "Realisierter Kapital Gewinn & Verlust"
				column-name = RealizedCapitalProfitLoss
				type = amount
				id = q9yb2
				column-computation = make-amount
				column-computation-parameters = "PERIOD_REAL_CAP_PL,REF_CURRENCY"
				table-column-width = 3
				tid = 12815932339681
			{
				--- TableColumnItem ---
					item-column = RealizedCapitalProfitLoss
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Unreal. Capital P&L", fr = "G&P sur capital non réalisés", de = "Unreal. Kapital-G/V" toolTips en = "Unrealized Capital Profit & Loss", fr = "Gains & pertes sur capital non réalisés", de = "Unrealisierter Kapital Gewinn & Verlust"
				column-name = UnrealizedCapitalProfitLoss
				type = amount
				id = GI__7
				column-computation = make-amount
				column-computation-parameters = "PERIOD_UNREAL_CAP_PL,REF_CURRENCY"
				table-column-width = 3
				tid = 12815933392805
			{
				--- TableColumnItem ---
					item-column = UnrealizedCapitalProfitLoss
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Real. Currency P&L", fr = "G&P sur devise réalisés", de = "Real. Währungs-G/V" toolTips en = "Realized Currency Profit & Loss", fr = "Gains & pertes sur devise réalisés", de = "Realisierter Währungs- Gewinn & Verlust"
				column-name = RealizedCurrencyProfitLoss
				type = amount
				id = lgiB5
				column-computation = make-amount
				column-computation-parameters = "PERIOD_REAL_CURR_PL,REF_CURRENCY"
				table-column-width = 3
				tid = 12815937298842
			{
				--- TableColumnItem ---
					item-column = RealizedCurrencyProfitLoss
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Unreal. Currency P&L", fr = "G&P sur devise non réalisés", de = "Unreal. Währungs-G/V" toolTips en = "Unrealized Currency Profit & Loss", fr = "Gains & pertes sur devise non réalisés", de = "Unrealisierter Währungs- Gewinn & Verlust"
				column-name = UnrealizedCurrencyProfitLoss
				type = amount
				id = gI_8j
				column-computation = make-amount
				column-computation-parameters = "PERIOD_UNREAL_CURR_PL,REF_CURRENCY"
				table-column-width = 3
				tid = 12815939250752
			{
				--- TableColumnItem ---
					item-column = UnrealizedCurrencyProfitLoss
					previewValue = value
			}
			--- TableColumn ---
				labels en = Income, fr = Revenu, de = Ertrag toolTips en = Income, fr = Revenu, de = Ertrag
				column-name = Income
				type = amount
				id = PIL_k
				column-computation = make-amount
				column-computation-parameters = "PERIOD_INCOME,REF_CURRENCY"
				table-column-width = 3
				tid = 12815941206082
			{
				--- TableColumnItem ---
					item-column = Income
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Fees & Taxes", fr = "Frais & taxes", de = Gebühren/Steuern
				column-name = FeesTaxes
				type = amount
				id = Fnq_F
				column-computation = make-amount
				column-computation-parameters = "PERIOD_FEE_TAX,REF_CURRENCY"
				table-column-width = 3
				tid = 12815943170982
			{
				--- TableColumnItem ---
					item-column = FeesTaxes
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Mean Capital", fr = "Capital moyen", de = "Durchschnittl. Kapital"
				column-name = MeanCapital
				type = amount
				column-visibility = not-visible
				id = Nr_p7
				column-computation = make-amount
				column-computation-parameters = "MEAN_CAP,REF_CURRENCY"
				table-column-width = 3
				tid = 12815926093365
			{
				--- TableColumnItem ---
					item-column = MeanCapital
					previewValue = value
			}
			--- TableColumn ---
				column-name = PERIOD_RET_TWR !
				column-type = domain !
				domainAttribute = PERIOD_RET_TWR !
				type = text
				column-visibility = not-visible
				id = PERIOD_RET_TWR
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = PERIOD_RET_TWR
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = BENCHMARK_FULL_NAME !
				column-type = domain !
				domainAttribute = BENCHMARK_FULL_NAME !
				type = text
				column-visibility = not-visible
				id = BENCHMARK_FULL_NAME
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = BENCHMARK_FULL_NAME
					previewValue = value
			}
			--- TableColumn ---
				column-name = BENCHMARK_RETURN !
				column-type = domain !
				domainAttribute = BENCHMARK_RETURN !
				type = text
				column-visibility = not-visible
				id = BENCHMARK_RETURN
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = BENCHMARK_RETURN
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = CAPITAL_EFFECT !
				column-type = domain !
				domainAttribute = CAPITAL_EFFECT !
				type = text
				column-visibility = not-visible
				id = CAPITAL_EFFECT
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = CAPITAL_EFFECT
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = CURRENCY_EFFECT !
				column-type = domain !
				domainAttribute = CURRENCY_EFFECT !
				type = text
				column-visibility = not-visible
				id = CURRENCY_EFFECT
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = CURRENCY_EFFECT
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = INCOME_EFFECT !
				column-type = domain !
				domainAttribute = INCOME_EFFECT !
				type = text
				column-visibility = not-visible
				id = INCOME_EFFECT
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = INCOME_EFFECT
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = FEES_AND_TAXES_EFFECT !
				column-type = domain !
				domainAttribute = FEES_AND_TAXES_EFFECT !
				type = text
				column-visibility = not-visible
				id = FEES_AND_TAXES_EFFECT
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = FEES_AND_TAXES_EFFECT
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = CROSS_EFFECT !
				column-type = domain !
				domainAttribute = CROSS_EFFECT !
				format = percentTA
				type = text
				column-visibility = not-visible
				id = CROSS_EFFECT
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = CROSS_EFFECT
					previewValue = value
			}
			--- TableColumn ---
				column-name = PORTFOLIO_CODE !
				column-type = domain !
				domainAttribute = PORTFOLIO_CODE !
				type = text
				column-visibility = never-visible
				id = PORTFOLIO_CODE
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = PORTFOLIO_CODE
					previewValue = value
			}
			--- TableKeepFilter ---
				keep-filter-column-name = GLOBAL_PERIOD_FILTER
				keep-filter-operand = 1
			--- TableKeepFilter ---
				keep-filter-column-name = PORTFOLIO_LEVEL_FILTER
				keep-filter-operand = 1
			--- TableSort ---
				sort-column-name = PTF_HIER_STR
				sort-rank = 2
		}
	}
}