# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSTradingCurrency:TradingCurrencyList"
	cssClass = nodeco
	bean-define = DSBean.AAADSTradingCurrency.TradingCurrencyList
	bean-name = TradingCurrencyList
	id = TradingCurrencyList_i_d5_
{
	--- Box ---
		labels en = "Trading Currency", de = Handelswährung, fr = "Devise de négoce"
		boxType = vertical
		widgetBorder = box
		width = 0
		tid = 713229032742708
	{
		--- TableTree ---
			table-filter-layer = true
			id = cHT9_
			table-column-count = 2 !
			table-columns-width = "50,50" !
		{
			--- TableColumn ---
				column-name = currencyCode !
				column-type = domain !
				domainAttribute = currencyCode !
				id = currencyCode
				table-column-width = 50
			{
				--- TableColumnItem ---
					item-column = currencyCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = mainCurrencyF !
				column-type = domain !
				domainAttribute = mainCurrencyF !
				type = text
				id = mainCurrencyF
				table-column-width = 50
			{
				--- TableColumnItem ---
					item-column = mainCurrencyF
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = currencyCode
				sort-direction = descending
				sort-rank = 3
			--- TableSort ---
				sort-column-name = mainCurrencyF
				sort-direction = descending
				sort-rank = 2
		}
	}
}