# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	containment = container
	domainEntity = "AAADSDomain:DomainContext"
	cssClass = nodeco
	bean-define = DSBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = Connectivity_d___W
{
	--- Box ---
		boxType = vertical
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 4
			gridColumnsWidth = "25,25,25,25" !
			gridRowCount = 2
		{
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- LabelDomain ---
					labels fr = Portefeuille, de = Portfolio
					domainAttribute = portfolioDimPortfolio !
					horizontalAlignment = "${corporatehalign}"
					tid = 23217169637481
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Include ---
					domainAssociation = portfolioDimPortfolio
					includeSrc = "" !
					resource:///default/defaultFragments/PortfolioIdentifierView.fragment
					bean-property-prefix = portfolioDimPortfolio.
			}
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Label ---
					horizontalAlignment = "${corporatehalign}"
					id = du_YB
			}
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
		}
	}
}