# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "What elements of the proposal do you want to copy ?", de = "Was möchten Sie kopieren?", fr = "Quels éléments de la proposition voulez-vous copier ?"
	domainEntity = "AAADSDomain:DomainContext"
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = CopyOptionPG_Bl2__
	tid = 56196128521011
{
	--- Box ---
		boxType = vertical
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 2
			gridColumnsWidth = "50,50" !
			gridRowCount = 3
		{
			--- GridCell ---
				gridColumnWidth = 50
			--- GridCell ---
				gridColumnWidth = 50
			--- GridCell ---
				gridColumnWidth = 50
			{
				--- CheckBox ---
					labels en = "Keep Remarks", de = "Bemerkungen behalten", fr = "Garder les remarques"
					domainAttribute = keepRemark !
					horizontalAlignment = "${corporatehalign}"
					horizontalTextPosition = trail
					bean-property = keepRemark
					id = keepRemark
					tid = 1631390394883428
			}
			--- GridCell ---
				gridColumnWidth = 50
			{
				--- HiddenField ---
					domainAttribute = funcResultCode
					bean-property = funcResultCode
					id = funcResultCode
			}
			--- GridCell ---
				gridColumnWidth = 50
			--- GridCell ---
				gridColumnWidth = 50
		}
		--- Grid ---
			cssClass = blank
			gridColumnCount = 1
			gridColumnsWidth = 50 !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 50
			{
				--- Button ---
					labels en = "Copy All", de = "Alle kopieren", fr = "Tout copier"
					id = btn_dB5__
					tid = 1618129624399469
				{
					Event OnClick (submit)
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						widget-group-ref = form
						target = WUI_main
						param = "flow-action=copyall"
						only-changed = true
						DSSessionCode = "valueOf(form.funcResultCode)" ud
						modal = false
						prevalidate = false
					}
				}
				--- Button ---
					labels en = "Copy Orders", de = "Aufträge kopieren", fr = "Copier les ordres"
					id = btn_yQY0g
					tid = 1618138642566303
				{
					Event OnClick (submit)
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						widget-group-ref = form
						target = WUI_main
						param = "flow-action=copyorders"
						only-changed = true
						DSSessionCode = "valueOf(form.funcResultCode)" ud
						modal = false
						prevalidate = false
					}
				}
				--- Button ---
					labels en = "Copy External Positions", de = "Externe Positionen kopieren", fr = "Copier les positions externes"
					id = btn_o8_dU
					tid = 1618152983772518
				{
					Event OnClick (submit)
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						widget-group-ref = form
						target = WUI_main
						param = "flow-action=copyextpos"
						only-changed = true
						DSSessionCode = "valueOf(form.funcResultCode)" ud
						modal = false
						prevalidate = false
					}
				}
			}
		}
	}
}