# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Context Title", de = Titel, fr = "Titre du contexte"
	domainEntity = "AAADSDomain:DomainContext"
	cssClass = nodeco
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = DomainTitle_Y2g__
	tid = 531479392798526
{
	--- Box ---
		boxType = vertical
		cssClass = toolbar
	{
		--- TextArea ---
			domainAttribute = summaryC !
			columns = 80
			horizontalAlignment = "${corporatehalign}"
			rows = 1
			type = text
			editable = false
			bean-property = summaryC
			id = summaryC
	}
}