# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = Context, fr = Contexte, de = Kontext
	domainEntity = "AAADSDomain:DomainContext"
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = DomainContext_xK022
	documentation = "Domain Context"
	tid = 586055818790218
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 4
			gridColumnsWidth = "27,16,16,14" !
			gridRowCount = 1
			verticalAlignment = lead
		{
			--- GridCell ---
				gridColumnWidth = 27
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainPortfolioDimension.fragment
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainInstrumentDimension.fragment
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainRefCurrency.fragment
			}
			--- GridCell ---
				gridColumnWidth = 14
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainHierarchyIdentifier.fragment
			}
		}
		--- Grid ---
			cssClass = blank
			gridColumnCount = 4
			gridColumnsWidth = "25,25,25,25" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Button ---
					labels en = Execute, fr = Exécuter, de = Ausführen
					id = btn_execute_in_domaincontext
					tid = 11440928193585
				{
					Event OnClick (submit)
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						widget-group-ref = form
						param = "flow-action=execute"
						only-changed = true
						prevalidate = false
						modal = false
					}
				}
				--- Button ---
					labels en = "Default Settings", fr = "Valeurs par défaut", de = Standardeinstellung
					id = btn_BJ9i_
					tid = 474817690293878
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = reset ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
		}
	}
}