# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Search Result", de = Suchergebnis, fr = "Résultat de recherche"
	domainEntity = "AAADSList:ListList"
	search = output !
	cssClass = nodeco
	bean-define = DSBean.AAADSList.ListList
	bean-name = ListList
	id = ListListMy_P__S4
	tid = 1320959769068135
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			id = yAQ_k
			table-model-reference = aaa-search.preferred1-output
			table-column-count = 8 !
			table-columns-width = "12,12,12,12,12,12,12,12" !
		{
			--- TableColumn ---
				column-name = natureE !
				column-type = domain !
				domainAttribute = natureE !
				type = text
				id = natureE
				table-column-width = 12
			{
				--- TableColumnItem ---
					item-column = natureE
					previewValue = value
			}
			--- TableColumn ---
				labels de = Code
				column-name = code !
				column-type = domain !
				domainAttribute = code !
				type = text
				id = code
				table-column-width = 12
				tid = 19933177174752
			{
				--- TableColumnItem ---
					item-column = code
					previewValue = value
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = preDefinedSearch ud
						Query.dbId = "<udp:item column=\"id\"/>" ud
						code = "<udp:item column=\"code\"/>" ud
						entity.dict = "<udp:item column=\"entityDict\"/>" ud
						Query.beanProperty1 = queryDefinition ud
						Query.beanName = "AAADSDomain:DomainContext" ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- TableColumn ---
				column-name = name !
				column-type = domain !
				domainAttribute = name !
				type = text
				id = name
				table-column-width = 12
			{
				--- TableColumnItem ---
					item-column = name
					previewValue = value
			}
			--- TableColumn ---
				column-name = denom !
				column-type = domain !
				domainAttribute = denom !
				type = text
				id = denom
				table-column-width = 12
			{
				--- TableColumnItem ---
					item-column = denom
					previewValue = value
			}
			--- TableColumn ---
				column-name = currencyName !
				column-type = domain !
				domainAttribute = currencyName !
				type = text
				id = currencyName
				table-column-width = 12
			{
				--- TableColumnItem ---
					item-column = currencyName
					previewValue = value
			}
			--- TableColumn ---
				column-name = typeName !
				column-type = domain !
				domainAttribute = typeName !
				type = text
				id = typeName
				table-column-width = 12
			{
				--- TableColumnItem ---
					item-column = typeName
					previewValue = value
			}
			--- TableColumn ---
				column-name = entityDict !
				column-type = domain !
				domainAttribute = entityDict !
				type = text
				column-visibility = never-visible
				id = entityDict
				table-column-width = 12
			{
				--- TableColumnItem ---
					item-column = entityDict
					format = integer
					previewValue = value
			}
			--- TableColumn ---
				column-name = id !
				column-type = domain !
				domainAttribute = id !
				type = text
				column-visibility = never-visible
				id = id
				table-column-width = 12
			{
				--- TableColumnItem ---
					item-column = id
					format = integer
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = code
				sort-rank = 1
		}
	}
}