# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = Context, fr = Contexte, de = Kontext
	containment = container
	domainEntity = "AAADSDomain:DomainContext"
	collapsible = true
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = Context_v_E_3
	documentation = "Domain Context"
	tid = 419726638582773
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TabbedPane ---
			id = TT_Qk
			indexOfSelectedChild = 0
		{
			--- Tab ---
				labels fr = Base, en = Basic, de = Basis
				id = tab_JyG2I
				isWidgetSelected = true
				tid = 113083031695648
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 5
					gridColumnsWidth = "15,15,15,15,40" !
					gridRowCount = 1
					verticalAlignment = lead
				{
					--- GridCell ---
						gridColumnWidth = 15
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainPortfolioWithUpdateRightDimension.fragment
					}
					--- GridCell ---
						gridColumnWidth = 15
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainInstrumentDimension.fragment
					}
					--- GridCell ---
						gridColumnWidth = 15
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainMinOrderAmount.fragment
					}
					--- GridCell ---
						gridColumnWidth = 15
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainMinOrderPercent.fragment
					}
					--- GridCell ---
						gridColumnWidth = 40
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainSessionDescription.fragment
					}
				}
			}
			--- Tab ---
				labels fr = Avancé, en = Advanced, de = Erweitert
				id = tab_d___8
				isWidgetVisible = false
				tid = 113126141506252
			{
				--- Box ---
				{
					--- Grid ---
						cssClass = blank
						gridColumnCount = 2
						gridColumnsWidth = "50,50" !
						gridRowCount = 1
					{
						--- GridCell ---
							gridColumnWidth = 50
						{
							--- Include ---
								includeSrc = "" !
								resource:///default/domain/basicelements/DomainMinStatus.fragment
						}
						--- GridCell ---
							gridColumnWidth = 50
						{
							--- Include ---
								includeSrc = "" !
								resource:///default/domain/basicelements/DomainMaxStatus.fragment
						}
					}
					--- Glue ---
				}
			}
		}
		--- Grid ---
			cssClass = blank
			gridColumnCount = 4
			gridColumnsWidth = "25,25,25,25" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Button ---
					labels en = Execute, de = Ausführen, fr = Exécuter
					id = btn_r0___
					tid = 419726640469513
				{
					Event OnClick (submit)
					{
						method = get
						call-URI = "<pageflow:continuation/>"
						widget-group-ref = form
						param = "flow-action=execute"
						only-changed = true
						prevalidate = false
						stabs = tab_order ud
						modal = false
					}
				}
				--- Button ---
					labels en = "Default Settings", de = Standardeinstellung, fr = "Valeurs par défaut"
					id = btn_Bj__b
					tid = 419726641041823
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = reset ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
		}
	}
}