# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Search Results", fr = "Résultats de la recherche", de = Suchergebnisse
	domainEntity = "AAADSDictLanguage:DictLanguageList"
	search = output !
	bean-define = DSBean.AAADSDictLanguage.DictLanguageList
	bean-name = DictLanguageList
	id = DictLanguageList_o39tN
	tid = 30656040931342
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			id = z2hq9
			table-column-count = 3 !
			table-columns-width = "33,33,33" !
		{
			--- TableColumn ---
				labels de = Code
				column-name = code !
				column-type = domain !
				domainAttribute = code !
				column-locked = true
				id = code
				table-column-width = 33
				tid = 20395113307976
			{
				--- Conditional ---
					indexOfSelectedChild = 1
				{
					--- ConditionalBody ---
						javaCode = "com.odcgroup.tsl.wui.search.form.SearchFormHelper.isLookup(objectModel) == false"
						technicalName = NotLookup
						boxType = vertical
						isWidgetVisible = false
					{
						--- TableColumnItem ---
							toolTips en = "Select Language", fr = "Sélectionner la langue", de = "Sprache auswählen"
							item-column = code
							previewValue = value
							tid = 30656042884983
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = select ud
								Query.beanValue1 = "<udp:item column=\"code\"/>" ud
								modal = false
								only-changed = false
								prevalidate = false
								Snippet FilterSet
								id = fs_PYk
							}
						}
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetSelected = true
					{
						--- TableColumnItem ---
							toolTips en = "Select Language", fr = "Sélectionner la langue", de = "Sprache auswählen"
							item-column = code
							previewValue = value
							tid = 30656044836874
						{
							Event OnClick (setWidgetValue)
							{
								widget-group-id = "<xsp:expr>com.odcgroup.tsl.wui.search.form.SearchFormHelper.getParentWidgetValue1Id(objectModel)</xsp:expr>"
								value = "<udp:item column=\"code\"/>"
								target = WUI_main
							}
							Event OnClick (winClose)
							{
								target = self
							}
						}
					}
				}
			}
			--- TableColumn ---
				column-name = name !
				column-type = domain !
				domainAttribute = name !
				id = name
				table-column-width = 33
			{
				--- TableColumnItem ---
					item-column = name
					previewValue = value
			}
			--- TableColumn ---
				column-name = extDenomination !
				column-type = domain !
				domainAttribute = extDenomination !
				type = text
				id = extDenomination
				table-column-width = 33
			{
				--- TableColumnItem ---
					item-column = extDenomination
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = code
				sort-rank = 1
		}
	}
}