# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Language Search Criteria", fr = "Critères de recherche sur langue", de = "Sprache Suchbegriffe"
	containment = container
	domainEntity = "AAADSDictLanguage:DictLanguageSearchCriteria"
	search = input !
	bean-define = DSBean.AAADSDictLanguage.DictLanguageSearchCriteria
	bean-name = DictLanguageSearchCriteria
	id = DictLanguageSearchInput_jM_20
	tid = 30675724856979
{
	--- Box ---
		boxType = vertical
	{
		--- FilterCriteria ---
			includedFile = "resource:/com/module/search/QueryBuilder.xsp"
		--- Include ---
			includeSrc = "" !
			resource:///default/search/NavigationSearchWithoutQueries.fragment
	}
}