# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Search Language", fr = "Recherche de langue", de = "Sprache Suche"
	containment = container
	search = container !
	cssClass = nodeco
	id = DictLanguageSearch_N__9_
	tid = 30664885177255
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/dictlanguage/search/DictLanguageSearchInput.module
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/dictlanguage/search/DictLanguageList.module
	}
}