# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSValuation:ValuationDetailledList"
	cssClass = nodeco
	bean-define = DSBean.AAADSValuation.ValuationDetailledList
	bean-name = ValuationDetailledList
	id = AssetClassAllAccounting_I___C
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			make-checkbox-exclusive = true
			table-filter-layer = true
			table-fixed-size = true
			table-height = 700
			id = Z79_E
			table-column-count = 47 !
			table-columns-width = "2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2" !
		{
			--- TableColumn ---
				column-name = IO_BUY_RIGHT !
				column-type = domain !
				domainAttribute = IO_BUY_RIGHT !
				type = text
				column-visibility = never-visible
				id = IO_BUY_RIGHT
				table-column-width = 2
			{
				--- TableColumnItem ---
					item-column = IO_BUY_RIGHT
					previewValue = value
			}
			--- TableColumn ---
				column-name = IO_SELL_RIGHT !
				column-type = domain !
				domainAttribute = IO_SELL_RIGHT !
				type = text
				column-visibility = never-visible
				id = IO_SELL_RIGHT
				table-column-width = 2
			{
				--- TableColumnItem ---
					item-column = IO_SELL_RIGHT
					previewValue = value
			}
			--- TableColumn ---
				labels en = Buy, fr = Achat, de = Kauf
				column-name = BUY
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				id = R__nw
				table-column-width = 2
				tid = 607313426505253
			{
				--- CheckBox ---
					column-checkbox-action = PCK_DS_IO_buy
					column-checkbox-identifier = seqno
					column-checkbox-security = IO_BUY_RIGHT
					horizontalAlignment = center
					horizontalTextPosition = trail
					id = btn_w3_n_
			}
			--- TableColumn ---
				labels en = Sell, fr = Vente, de = Verkauf
				column-name = SELL
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				id = hd_3_
				table-column-width = 2
				tid = 607317512170386
			{
				--- CheckBox ---
					column-checkbox-action = PCK_DS_IO_sell
					column-checkbox-identifier = seqno
					column-checkbox-security = IO_SELL_RIGHT
					horizontalAlignment = center
					horizontalTextPosition = trail
					id = btn_y__3r
			}
			--- TableColumn ---
				column-display-grouping = true
				column-name = INSTR_DENOM !
				column-type = domain !
				domainAttribute = INSTR_DENOM !
				type = text
				column-locked = true
				id = INSTR_DENOM
				table-column-width = 2
			{
				--- TableColumnItem ---
					item-column = INSTR_DENOM
					previewValue = value
				--- TableGroup ---
					group-column-name = PTF_HIER_STR
					group-sorting-column-name = PTF_HIER_STR
					group-sorting-direction = ascending
					hierarchy = true
					group-rank = 1
				--- TableGroup ---
					group-column-name = ASSET_CLASS_DENOM
					group-sorting-column-name = ASSET_CLASS_RANK
					group-sorting-direction = ascending
					group-rank = 2
				--- TableGroup ---
					group-column-name = Sub_Asset_Class
					group-sorting-column-name = Sub_Asset_Class_Rank
					group-sorting-direction = ascending
					group-rank = 3
				--- TableGroup ---
					group-column-name = POS_CURRENCY
					group-sorting-column-name = CURR_CLASS_RANK
					group-sorting-direction = ascending
					group-rank = 4
			}
			--- TableColumn ---
				labels en = "Instr. Details", fr = "Détails instr.", de = "Instr. Details"
				column-name = InstrumentDetails
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				id = xkd46
				table-column-width = 2
				tid = 95455318994304
			{
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "<udp:item column=\"INSTR_CODE\"/>!=null"
						technicalName = Instrument
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips en = "View Instrument Details", fr = "Voir les détails de l\'instrument", de = "Details des Instruments ansehen"
							horizontalAlignment = center
							icon = application_form_magnify
							id = bJb_I
							tid = 96983483939836
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "resource:///administration/instrument/InstrumentQuickView.pageflow"
								target = popup
								code = "<udp:item column=\"INSTR_CODE\"/>" ud
								modal = false
								only-changed = false
								prevalidate = false
							}
						}
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetVisible = false
				}
			}
			--- TableColumn ---
				column-name = DEPOSIT_NAME !
				column-type = domain !
				domainAttribute = DEPOSIT_NAME !
				type = text
				column-visibility = not-visible
				id = DEPOSIT_NAME
				table-column-width = 2
			{
				--- TableColumnItem ---
					item-column = DEPOSIT_NAME
					previewValue = value
			}
			--- TableColumn ---
				column-name = QUANTITY !
				column-type = domain !
				domainAttribute = QUANTITY !
				id = QUANTITY
				table-column-width = 2
			{
				--- TableColumnItem ---
					item-column = QUANTITY
					format = decimal.2-digits
					previewValue = value
				--- Spacer ---
					height = 4
					width = 4
				--- TableColumnItem ---
					item-column = QUANTITY_CURR
					previewValue = value
				--- Spacer ---
					height = 4
					width = 10
				--- Icon ---
					toolTips en = "View Position Details", fr = "Voir les détails de la position", de = "Details der Position ansehen"
					horizontalAlignment = trail
					icon = application_form_magnify
					id = Y_8_U
					tid = 26575577207438
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "resource:///positiondetails/PositionDetails.pageflow"
						target = popup
						modal = false
						only-changed = false
						prevalidate = false
						pos_instrumentDimInstrument.code = "<udp:item column=\"INSTR_CODE\"/>" ud
						pos_instrumentDimensionE = 1 ud
						pos_portfolioDimPortfolio.code = "<udp:item column=\"PORTFOLIO_CODE\"/>" ud
						pos_portfolioDimensionE = 1 ud
					}
				}
			}
			--- TableColumn ---
				column-name = POS_CURRENCY_COL !
				column-type = domain !
				domainAttribute = POS_CURRENCY_COL !
				type = text
				id = POS_CURRENCY_COL
				table-column-width = 2
			{
				--- TableColumnItem ---
					item-column = POS_CURRENCY_COL
					previewValue = value
			}
			--- TableColumn ---
				column-name = ISIN !
				column-type = domain !
				domainAttribute = ISIN !
				type = text
				column-visibility = not-visible
				id = ISIN
				table-column-width = 2
			{
				--- TableColumnItem ---
					item-column = ISIN
					previewValue = value
			}
			--- TableColumn ---
				column-name = INSTR_PRICE !
				column-type = domain !
				domainAttribute = INSTR_PRICE !
				type = text
				id = INSTR_PRICE
				table-column-width = 2
			{
				--- TableColumnItem ---
					item-column = INSTR_PRICE
					format = decimal.4-digits
					previewValue = value
				--- TableColumnItem ---
					item-column = INSTR_PRICE_PERCENTAGE
					previewValue = %
				--- Spacer ---
					height = 4
					width = 3
				--- TableColumnItem ---
					item-column = INSTR_PRICE_CURRENCY
					previewValue = value
			}
			--- TableColumn ---
				column-name = DATE_MARKET_PRICE !
				column-type = domain !
				domainAttribute = DATE_MARKET_PRICE !
				type = text
				column-visibility = not-visible
				id = DATE_MARKET_PRICE
				table-column-width = 2
			{
				--- TableColumnItem ---
					item-column = DATE_MARKET_PRICE
					format = datetime.date-only
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Market Value", fr = "Valeur de marché", de = Marktwert
				column-name = MarketValue
				type = amount
				id = l4I_0
				documentation = "Market Value in Reference Currency by position."
				column-computation = make-amount
				column-computation-parameters = "MKT_VAL,REF_CURRENCY"
				table-column-width = 2
				tid = 24768539055368
			{
				--- TableColumnItem ---
					item-column = MarketValue
					previewValue = value
			}
			--- TableColumn ---
				column-name = MKT_VAL_PERC !
				column-type = domain !
				domainAttribute = MKT_VAL_PERC !
				type = text
				id = MKT_VAL_PERC
				table-column-width = 2
			{
				--- TableColumnItem ---
					item-column = MKT_VAL_PERC
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = COST_PRICE !
				column-type = domain !
				domainAttribute = COST_PRICE !
				type = text
				id = COST_PRICE
				table-column-width = 2
			{
				--- TableColumnItem ---
					item-column = COST_PRICE
					format = decimal.4-digits
					previewValue = value
				--- TableColumnItem ---
					item-column = COST_PRICE_PERCENTAGE
					previewValue = %
				--- Spacer ---
					height = 4
					width = 3
				--- TableColumnItem ---
					item-column = COST_PRICE_CURRENCY
					previewValue = value
			}
			--- TableColumn ---
				column-name = COST_EXCH_RATE !
				column-type = domain !
				domainAttribute = COST_EXCH_RATE !
				type = text
				id = COST_EXCH_RATE
				table-column-width = 2
			{
				--- TableColumnItem ---
					item-column = COST_EXCH_RATE
					format = decimal.detailed
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Net Cost Value", fr = "Coût d\'achat", de = "Einstandswert Netto"
				column-name = NetCostVal
				type = amount
				id = Q___7
				documentation = "Net Cost Value in Reference Currency by position."
				column-computation = make-amount
				column-computation-parameters = "NET_COST_VAL,REF_CURRENCY"
				table-column-width = 2
				tid = 6229765026006
			{
				--- TableColumnItem ---
					item-column = NetCostVal
					previewValue = value
			}
			--- TableColumn ---
				column-name = PL_PERC !
				column-type = domain !
				domainAttribute = PL_PERC !
				type = text
				id = PL_PERC
				table-column-width = 2
			{
				--- TableColumnItem ---
					item-column = PL_PERC
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				labels en = P&L, de = G/V, fr = G&P
				column-name = Pl
				type = amount
				column-visibility = not-visible
				id = x_u_K
				column-computation = make-amount
				column-computation-parameters = "PL,REF_CURRENCY"
				table-column-width = 2
				tid = 73703535152439
			{
				--- TableColumnItem ---
					item-column = Pl
					previewValue = value
			}
			--- TableColumn ---
				column-name = CAP_PL_PERC !
				column-type = domain !
				domainAttribute = CAP_PL_PERC !
				type = text
				column-visibility = not-visible
				id = CAP_PL_PERC
				table-column-width = 2
			{
				--- TableColumnItem ---
					item-column = CAP_PL_PERC
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Cap P&L", de = "Kap G/V", fr = "G&P sur capital"
				column-name = CapPl
				type = amount
				column-visibility = not-visible
				id = hna6G
				column-computation = make-amount
				column-computation-parameters = "CAP_PL,REF_CURRENCY"
				table-column-width = 2
				tid = 73827099036403
			{
				--- TableColumnItem ---
					item-column = CapPl
					previewValue = value
			}
			--- TableColumn ---
				column-name = CURR_PL_PERC !
				column-type = domain !
				domainAttribute = CURR_PL_PERC !
				type = text
				column-visibility = not-visible
				id = CURR_PL_PERC
				table-column-width = 2
			{
				--- TableColumnItem ---
					item-column = CURR_PL_PERC
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Cur P&L", de = "Dev G/V", fr = "G&P sur devise"
				column-name = CurrPl
				type = amount
				column-visibility = not-visible
				id = Dnr_1
				column-computation = make-amount
				column-computation-parameters = "CURR_PL,REF_CURRENCY"
				table-column-width = 2
				tid = 73883209693293
			{
				--- TableColumnItem ---
					item-column = CurrPl
					previewValue = value
			}
			--- TableColumn ---
				column-name = EXPIRATION !
				column-type = domain !
				domainAttribute = EXPIRATION !
				type = text
				column-visibility = not-visible
				id = EXPIRATION
				table-column-width = 2
			{
				--- TableColumnItem ---
					item-column = EXPIRATION
					format = date
					previewValue = value
			}
			--- TableColumn ---
				column-name = RATE !
				column-type = domain !
				domainAttribute = RATE !
				type = text
				column-visibility = not-visible
				id = RATE
				table-column-width = 2
			{
				--- TableColumnItem ---
					item-column = RATE
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = ACCRUED_INTEREST !
				column-type = domain !
				domainAttribute = ACCRUED_INTEREST !
				type = text
				column-visibility = not-visible
				id = ACCRUED_INTEREST
				table-column-width = 2
			{
				--- TableColumnItem ---
					item-column = ACCRUED_INTEREST
					format = decimal
					previewValue = value
			}
			--- TableColumn ---
				column-name = YTM !
				column-type = domain !
				domainAttribute = YTM !
				type = text
				column-visibility = not-visible
				id = YTM
				table-column-width = 2
			{
				--- TableColumnItem ---
					item-column = YTM
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = MODIFIED_DURATION !
				column-type = domain !
				domainAttribute = MODIFIED_DURATION !
				type = text
				column-visibility = not-visible
				id = MODIFIED_DURATION
				table-column-width = 2
			{
				--- TableColumnItem ---
					item-column = MODIFIED_DURATION
					format = decimal
					previewValue = value
			}
			--- TableColumn ---
				column-name = RATING_DENOM !
				column-type = domain !
				domainAttribute = RATING_DENOM !
				type = text
				column-visibility = not-visible
				id = RATING_DENOM
				table-column-width = 2
			{
				--- TableColumnItem ---
					item-column = RATING_DENOM
					previewValue = value
			}
			--- TableColumn ---
				column-name = REGION_DENOM !
				column-type = domain !
				domainAttribute = REGION_DENOM !
				type = text
				column-visibility = not-visible
				id = REGION_DENOM
				table-column-width = 2
			{
				--- TableColumnItem ---
					item-column = REGION_DENOM
					previewValue = value
			}
			--- TableColumn ---
				column-name = RISK_GEO_DENOM !
				column-type = domain !
				domainAttribute = RISK_GEO_DENOM !
				type = text
				column-visibility = not-visible
				id = RISK_GEO_DENOM
				table-column-width = 2
			{
				--- TableColumnItem ---
					item-column = RISK_GEO_DENOM
					previewValue = value
			}
			--- TableColumn ---
				column-name = OPT_STYLE !
				column-type = domain !
				domainAttribute = OPT_STYLE !
				type = text
				column-visibility = not-visible
				id = OPT_STYLE
				table-column-width = 2
			{
				--- TableColumnItem ---
					item-column = OPT_STYLE
					previewValue = value
			}
			--- TableColumn ---
				column-name = OPT_TYPE !
				column-type = domain !
				domainAttribute = OPT_TYPE !
				type = text
				column-visibility = not-visible
				id = OPT_TYPE
				table-column-width = 2
			{
				--- TableColumnItem ---
					item-column = OPT_TYPE
					previewValue = value
			}
			--- TableColumn ---
				column-name = UNDERLYING_INSTR !
				column-type = domain !
				domainAttribute = UNDERLYING_INSTR !
				type = text
				column-visibility = not-visible
				id = UNDERLYING_INSTR
				table-column-width = 2
			{
				--- TableColumnItem ---
					item-column = UNDERLYING_INSTR
					previewValue = value
			}
			--- TableColumn ---
				column-name = UNDERLYING_NATURE !
				column-type = domain !
				domainAttribute = UNDERLYING_NATURE !
				type = text
				column-visibility = not-visible
				id = UNDERLYING_NATURE
				table-column-width = 2
			{
				--- TableColumnItem ---
					item-column = UNDERLYING_NATURE
					previewValue = value
			}
			--- TableColumn ---
				labels fr = "Prix d\'exercice", de = Ausübungspreis, en = "Strike Price"
				column-name = strikeprice
				type = amount
				column-visibility = not-visible
				id = strikeprice
				column-computation = make-amount
				column-computation-parameters = "STRIKE_PRICE,STRIKE_PRICE_CURR"
				table-column-width = 2
				tid = 11571015974935
			{
				--- TableColumnItem ---
					item-column = strikeprice
					previewValue = value
			}
			--- TableColumn ---
				column-name = RECOMMENDATION !
				column-type = domain !
				domainAttribute = RECOMMENDATION !
				type = text
				column-visibility = not-visible
				id = RECOMMENDATION
				table-column-width = 2
			{
				--- TableColumnItem ---
					item-column = RECOMMENDATION
					previewValue = value
			}
			--- TableColumn ---
				column-name = FUND_SPLIT !
				column-type = domain !
				domainAttribute = FUND_SPLIT !
				type = text
				column-visibility = not-visible
				id = FUND_SPLIT
				table-column-width = 2
			{
				--- TableColumnItem ---
					item-column = FUND_SPLIT
					previewValue = value
			}
			--- TableColumn ---
				column-name = RISK_INSTR_NAME !
				column-type = domain !
				domainAttribute = RISK_INSTR_NAME !
				type = text
				column-visibility = not-visible
				id = RISK_INSTR_NAME
				table-column-width = 2
			{
				--- TableColumnItem ---
					item-column = RISK_INSTR_NAME
					previewValue = value
			}
			--- TableColumn ---
				column-name = STATUS !
				column-type = domain !
				domainAttribute = STATUS !
				id = STATUS
				table-column-width = 2
			{
				--- TableColumnItem ---
					item-column = STATUS
					previewValue = value
			}
			--- TableColumn ---
				column-name = INSTR_CODE !
				column-type = domain !
				domainAttribute = INSTR_CODE !
				type = text
				column-sortable = false
				column-visibility = never-visible
				id = INSTR_CODE
				table-column-width = 2
			{
				--- TableColumnItem ---
					item-column = INSTR_CODE
					previewValue = value
			}
			--- TableColumn ---
				column-name = PORTFOLIO_CODE !
				column-type = domain !
				domainAttribute = PORTFOLIO_CODE !
				type = text
				column-sortable = false
				column-visibility = never-visible
				id = PORTFOLIO_CODE
				table-column-width = 2
			{
				--- TableColumnItem ---
					item-column = PORTFOLIO_CODE
					previewValue = value
			}
			--- TableColumn ---
				column-name = MKT_VAL !
				column-type = domain !
				domainAttribute = MKT_VAL !
				type = text
				column-sortable = false
				column-visibility = never-visible
				id = MKT_VAL
				table-column-width = 2
			{
				--- TableColumnItem ---
					item-column = MKT_VAL
					format = decimal
					previewValue = value
			}
			--- TableColumn ---
				labels de = "Einstandswert Netto"
				column-name = NET_COST_VAL !
				column-type = domain !
				domainAttribute = NET_COST_VAL !
				type = text
				column-sortable = false
				column-visibility = never-visible
				id = NET_COST_VAL
				table-column-width = 2
				tid = 1604013469703742
			{
				--- TableColumnItem ---
					item-column = NET_COST_VAL
					format = decimal
					previewValue = value
			}
			--- TableColumn ---
				column-name = PL !
				column-type = domain !
				domainAttribute = PL !
				type = text
				column-sortable = false
				column-visibility = never-visible
				id = PL
				table-column-width = 2
			{
				--- TableColumnItem ---
					item-column = PL
					format = decimal
					previewValue = value
			}
			--- TableColumn ---
				column-name = CAP_PL !
				column-type = domain !
				domainAttribute = CAP_PL !
				type = text
				column-sortable = false
				column-visibility = never-visible
				id = CAP_PL
				table-column-width = 2
			{
				--- TableColumnItem ---
					item-column = CAP_PL
					format = decimal
					previewValue = value
			}
			--- TableColumn ---
				column-name = CURR_PL !
				column-type = domain !
				domainAttribute = CURR_PL !
				type = text
				column-sortable = false
				column-visibility = never-visible
				id = CURR_PL
				table-column-width = 2
			{
				--- TableColumnItem ---
					item-column = CURR_PL
					format = decimal
					previewValue = value
			}
			--- TableExtra ---
				domainAttribute = INSTR_PRICE_CURRENCY
			--- TableExtra ---
				domainAttribute = INSTR_PRICE_PERCENTAGE
			--- TableExtra ---
				domainAttribute = COST_PRICE_CURRENCY
			--- TableExtra ---
				domainAttribute = COST_PRICE_PERCENTAGE
			--- TableExtra ---
				domainAttribute = QUANTITY_CURR
			--- TableSort ---
				sort-column-name = MKT_VAL
				sort-direction = descending
				sort-rank = 5
			--- TableExtra ---
				domainAttribute = HIERARCHY_SORT
			--- TableExtra ---
				domainAttribute = seqno
			--- TableExtra ---
				domainAttribute = ASSET_CLASS_RANK
			--- TableKeepFilter ---
				keep-filter-column-name = FD_SPLIT_FILTER
				keep-filter-operand = 1
			--- TableAggregate ---
				aggregate-column-name = PTF_HIER_STR
				aggregate-computation = max
				aggregate-group-names = PTF_HIER_STR
			--- TableAggregate ---
				aggregate-column-name = ASSET_CLASS_RANK
				aggregate-computation = max
				aggregate-group-names = ASSET_CLASS_DENOM
			--- TableAggregate ---
				aggregate-column-name = Sub_Asset_Class_Rank
				aggregate-computation = max
				aggregate-group-names = Sub_Asset_Class
			--- TableAggregate ---
				aggregate-column-name = MKT_VAL
				aggregate-computation = sum
				aggregate-group-names = "PTF_HIER_STR,ASSET_CLASS_DENOM,Sub_Asset_Class,POS_CURRENCY"
			--- TableAggregate ---
				aggregate-column-name = REF_CURRENCY
				aggregate-computation = max
				aggregate-group-names = "PTF_HIER_STR,ASSET_CLASS_DENOM,Sub_Asset_Class,POS_CURRENCY"
			--- TableAggregate ---
				aggregate-column-name = MKT_VAL_PERC
				aggregate-computation = sum
				aggregate-group-names = "PTF_HIER_STR,ASSET_CLASS_DENOM,Sub_Asset_Class,POS_CURRENCY"
			--- TableAggregate ---
				aggregate-column-name = NET_COST_VAL
				aggregate-computation = sum
				aggregate-group-names = "PTF_HIER_STR,ASSET_CLASS_DENOM,Sub_Asset_Class,POS_CURRENCY"
			--- TableAggregate ---
				aggregate-column-name = MarketValue
				aggregate-computation = sum
				aggregate-group-names = "PTF_HIER_STR,ASSET_CLASS_DENOM,Sub_Asset_Class,POS_CURRENCY"
			--- TableAggregate ---
				aggregate-column-name = NetCostVal
				aggregate-computation = sum
				aggregate-group-names = "PTF_HIER_STR,ASSET_CLASS_DENOM,Sub_Asset_Class,POS_CURRENCY"
			--- TableAggregate ---
				aggregate-column-name = Pl
				aggregate-computation = sum
				aggregate-group-names = "PTF_HIER_STR,ASSET_CLASS_DENOM,Sub_Asset_Class,POS_CURRENCY"
			--- TableAggregate ---
				aggregate-column-name = CapPl
				aggregate-computation = sum
				aggregate-group-names = "PTF_HIER_STR,ASSET_CLASS_DENOM,Sub_Asset_Class,POS_CURRENCY"
			--- TableAggregate ---
				aggregate-column-name = CurrPl
				aggregate-computation = sum
				aggregate-group-names = "PTF_HIER_STR,ASSET_CLASS_DENOM,Sub_Asset_Class,POS_CURRENCY"
			--- TableAggregate ---
				aggregate-column-name = PL
				aggregate-computation = sum
				aggregate-group-names = "PTF_HIER_STR,ASSET_CLASS_DENOM,Sub_Asset_Class,POS_CURRENCY"
			--- TableAggregate ---
				aggregate-column-name = CAP_PL
				aggregate-computation = sum
				aggregate-group-names = "PTF_HIER_STR,ASSET_CLASS_DENOM,Sub_Asset_Class,POS_CURRENCY"
			--- TableAggregate ---
				aggregate-column-name = CURR_PL
				aggregate-computation = sum
				aggregate-group-names = "PTF_HIER_STR,ASSET_CLASS_DENOM,Sub_Asset_Class,POS_CURRENCY"
			--- TableAggregate ---
				aggregate-column-name = MODIFIED_DURATION
				aggregate-computation = weighted-mean
				aggregate-group-names = "PTF_HIER_STR,ASSET_CLASS_DENOM,Sub_Asset_Class,POS_CURRENCY"
				aggregate-other-column-name = MKT_VAL
			--- TableAggregate ---
				aggregate-column-name = CURR_CLASS_RANK
				aggregate-computation = max
				aggregate-group-names = POS_CURRENCY
			--- TableExtra ---
				domainAttribute = id
		}
	}
}