# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSValuation:ValuationDetailledList"
	cssClass = nodeco
	bean-define = DSBean.AAADSValuation.ValuationDetailledList
	bean-name = ValuationDetailledList
	id = AssetClassCashAccounting_v6T_O
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			table-filter-layer = true
			id = b__f_
			table-column-count = 11 !
			table-columns-width = "9,9,9,9,9,9,9,9,9,9,9" !
		{
			--- TableColumn ---
				column-name = POS_CURRENCY_COL !
				column-type = domain !
				domainAttribute = POS_CURRENCY_COL !
				type = text
				id = POS_CURRENCY_COL
				table-column-width = 9
			{
				--- TableColumnItem ---
					item-column = POS_CURRENCY_COL
					previewValue = value
			}
			--- TableColumn ---
				column-name = INSTR_DENOM !
				column-type = domain !
				domainAttribute = INSTR_DENOM !
				id = INSTR_DENOM
				table-column-width = 9
			{
				--- TableColumnItem ---
					item-column = INSTR_DENOM
					previewValue = value
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = popup
						flow-action = quickViewInstrument ud
						code = "<udp:item column=\"INSTR_CODE\"/>" ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- TableColumn ---
				column-name = PORTFOLIO_NAME !
				column-type = domain !
				domainAttribute = PORTFOLIO_NAME !
				id = PORTFOLIO_NAME
				table-column-width = 9
			{
				--- TableColumnItem ---
					item-column = PORTFOLIO_NAME
					previewValue = value
			}
			--- TableColumn ---
				labels fr = Montant
				column-name = QUANTITY !
				column-type = domain !
				domainAttribute = QUANTITY !
				id = QUANTITY
				table-column-width = 9
				tid = 65114434875661
			{
				--- TableColumnItem ---
					item-column = QUANTITY
					format = decimal.2-digits
					previewValue = value
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = popup
						modal = false
						only-changed = false
						prevalidate = false
						flow-action = positiondetails ud
						pos_instrumentDimInstrument.code = "<udp:item column=\"INSTR_CODE\"/>" ud
						pos_instrumentDimensionE = 1 ud
						pos_portfolioDimPortfolio.code = "<udp:item column=\"PORTFOLIO_CODE\"/>" ud
						pos_portfolioDimensionE = 1 ud
						inputFieldPrefix = pos_ ud
						Snippet FilterSet
						id = fs_HX2
						level = 1
						targetDataset = "AAADSPositionDetails:PositionDetailsFromValuation"
						{
							Snippet Filter
							attribute = id
							filterValue = "<udp:item column=\"id\"/>"
							operator = EQUAL
						}
					}
				}
			}
			--- TableColumn ---
				labels en = "Market Value", fr = "Valeur de marché", de = Marktwert
				column-name = MktVal
				type = amount
				id = GaYZ_
				documentation = "Market Value in Reference Currency by Cash\'s position."
				column-computation = make-amount
				column-computation-parameters = "MKT_VAL,REF_CURRENCY"
				table-column-width = 9
				tid = 1736470996244
			{
				--- TableColumnItem ---
					item-column = MktVal
					previewValue = value
			}
			--- TableColumn ---
				column-name = MKT_VAL_PERC !
				column-type = domain !
				domainAttribute = MKT_VAL_PERC !
				id = MKT_VAL_PERC
				table-column-width = 9
			{
				--- TableColumnItem ---
					item-column = MKT_VAL_PERC
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = PL_PERC !
				column-type = domain !
				domainAttribute = PL_PERC !
				id = PL_PERC
				table-column-width = 9
			{
				--- TableColumnItem ---
					item-column = PL_PERC
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Net Cost Value", fr = "Coût d\'achat", de = "Einstandswert Netto"
				column-name = NetCostVal
				type = amount
				id = z_3V3
				documentation = "Net Cost Value in Reference Currency by Cash\'s position."
				column-computation = make-amount
				column-computation-parameters = "NET_COST_VAL,REF_CURRENCY"
				table-column-width = 9
				tid = 1833884312085
			{
				--- TableColumnItem ---
					item-column = NetCostVal
					previewValue = value
			}
			--- TableColumn ---
				column-name = STATUS !
				column-type = domain !
				domainAttribute = STATUS !
				column-visibility = not-visible
				id = STATUS
				table-column-width = 9
			{
				--- TableColumnItem ---
					item-column = STATUS
					previewValue = value
			}
			--- TableColumn ---
				column-name = INSTR_CODE !
				column-type = domain !
				domainAttribute = INSTR_CODE !
				type = text
				column-is-part-of-filter = false
				column-visibility = never-visible
				id = INSTR_CODE
				table-column-width = 9
			{
				--- TableColumnItem ---
					item-column = INSTR_CODE
					previewValue = value
			}
			--- TableColumn ---
				column-name = PORTFOLIO_CODE !
				column-type = domain !
				domainAttribute = PORTFOLIO_CODE !
				type = text
				column-is-part-of-filter = false
				column-visibility = never-visible
				id = PORTFOLIO_CODE
				table-column-width = 9
			{
				--- TableColumnItem ---
					item-column = PORTFOLIO_CODE
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = INSTR_NAME
				sort-rank = 4
			--- TableSort ---
				sort-column-name = PORTFOLIO_NAME
				sort-rank = 3
			--- TableKeepFilter ---
				keep-filter-column-name = ASSET_CLASS_RANK
				keep-filter-operand = 1
			--- TableKeepFilter ---
				keep-filter-column-name = ACCT_FILTER
				keep-filter-operand = 1
			--- TableSort ---
				sort-column-name = POS_CURRENCY_COL
				sort-rank = 2
			--- TableExtra ---
				domainAttribute = id
		}
	}
}