# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSValuation:ValuationDetailledList"
	cssClass = nodeco
	bean-define = DSBean.AAADSValuation.ValuationDetailledList
	bean-name = ValuationDetailledList
	id = LiquidityAccounting_a2O_2
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			table-filter-layer = true
			table-fixed-size = true
			table-height = 700
			id = U_9_p
			table-column-count = 20 !
			table-columns-width = "5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5" !
		{
			--- TableColumn ---
				column-display-grouping = true
				column-name = INSTR_DENOM !
				column-type = domain !
				domainAttribute = INSTR_DENOM !
				column-locked = true
				id = INSTR_DENOM
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = INSTR_DENOM
					previewValue = value
				--- TableGroup ---
					group-column-name = PTF_HIER_STR
					group-sorting-column-name = PTF_HIER_STR
					group-sorting-direction = ascending
					hierarchy = true
					group-rank = 1
				--- TableGroup ---
					group-column-name = INSTR_TYPE_DENOM
					group-sorting-column-name = INSTR_TYPE_DENOM
					group-sorting-direction = ascending
					group-rank = 2
				--- TableGroup ---
					group-column-name = POS_CURRENCY
					group-sorting-column-name = CURR_CLASS_RANK
					group-sorting-direction = ascending
					group-rank = 3
			}
			--- TableColumn ---
				labels en = "Instr. Details", fr = "Détails instr.", de = "Instr. Details"
				column-name = InstrumentDetails
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				id = tAuU_
				table-column-width = 5
				tid = 27175813030706
			{
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "<udp:item column=\"INSTR_CODE\"/>!=null"
						technicalName = Instrument
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips en = "View Instrument Details", fr = "Voir les détails de l\'instrument", de = "Details des Instruments ansehen"
							horizontalAlignment = center
							icon = application_form_magnify
							id = b___u
							tid = 27175815047163
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "resource:///administration/instrument/InstrumentQuickView.pageflow"
								target = popup
								code = "<udp:item column=\"INSTR_CODE\"/>" ud
								modal = false
								only-changed = false
								prevalidate = false
							}
						}
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetVisible = false
				}
			}
			--- TableColumn ---
				column-name = DEPOSIT_NAME !
				column-type = domain !
				domainAttribute = DEPOSIT_NAME !
				type = text
				column-visibility = not-visible
				id = DEPOSIT_NAME
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = DEPOSIT_NAME
					previewValue = value
			}
			--- TableColumn ---
				labels en = Quantity
				column-name = QUANTITY !
				column-type = domain !
				domainAttribute = QUANTITY !
				id = QUANTITY
				table-column-width = 5
				tid = 27175824735825
			{
				--- TableColumnItem ---
					item-column = QUANTITY
					format = decimal.2-digits
					previewValue = value
				--- Spacer ---
					height = 4
					width = 4
				--- TableColumnItem ---
					item-column = QUANTITY_CURR
					previewValue = value
				--- Spacer ---
					height = 4
					width = 10
				--- Icon ---
					toolTips en = "View Position Details", fr = "Voir les détails de la position", de = "Details der Position ansehen"
					horizontalAlignment = trail
					icon = application_form_magnify
					id = o74UQ
					tid = 30557443867865
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = popup
						modal = false
						only-changed = false
						prevalidate = false
						flow-action = positiondetails ud
						pos_instrumentDimInstrument.code = "<udp:item column=\"INSTR_CODE\"/>" ud
						pos_instrumentDimensionE = 1 ud
						pos_portfolioDimPortfolio.code = "<udp:item column=\"PORTFOLIO_CODE\"/>" ud
						pos_portfolioDimensionE = 1 ud
						inputFieldPrefix = pos_ ud
						Snippet FilterSet
						id = fs_HX2
						level = 1
						targetDataset = "AAADSPositionDetails:PositionDetailsFromValuation"
						{
							Snippet Filter
							attribute = id
							filterValue = "<udp:item column=\"id\"/>"
							operator = EQUAL
						}
					}
				}
			}
			--- TableColumn ---
				column-name = POS_CURRENCY_COL !
				column-type = domain !
				domainAttribute = POS_CURRENCY_COL !
				type = text
				id = POS_CURRENCY_COL
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = POS_CURRENCY_COL
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Market Value", fr = "Valeur de marché", de = Marktwert
				column-name = MktVal
				type = amount
				id = v_E__
				documentation = "Market Value in Reference Currency by Money Markets\'s position."
				column-computation = make-amount
				column-computation-parameters = "MKT_VAL,REF_CURRENCY"
				table-column-width = 5
				tid = 27176060834268
			{
				--- TableColumnItem ---
					item-column = MktVal
					previewValue = value
			}
			--- TableColumn ---
				column-name = MKT_VAL_PERC_REL !
				column-type = domain !
				domainAttribute = MKT_VAL_PERC_REL !
				type = text
				id = MKT_VAL_PERC_REL
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = MKT_VAL_PERC_REL
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = MKT_VAL_PERC !
				column-type = domain !
				domainAttribute = MKT_VAL_PERC !
				type = text
				column-visibility = not-visible
				id = MKT_VAL_PERC
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = MKT_VAL_PERC
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Net Cost Value", de = "Einstandswert Netto", fr = "Coût d\'achat"
				column-name = NetCostVal
				type = amount
				id = my8__
				documentation = "Net Cost Value in Reference Currency by Money Markets\'s position."
				column-computation = make-amount
				column-computation-parameters = "NET_COST_VAL,REF_CURRENCY"
				table-column-width = 5
				tid = 27176062045874
			{
				--- TableColumnItem ---
					item-column = NetCostVal
					previewValue = value
			}
			--- TableColumn ---
				column-name = CURR_PL_PERC !
				column-type = domain !
				domainAttribute = CURR_PL_PERC !
				type = text
				id = CURR_PL_PERC
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = CURR_PL_PERC
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Cur P&L", de = "Dev G/V", fr = "G&P sur devise"
				column-name = CurrPl
				type = amount
				column-visibility = not-visible
				id = W_3_4
				column-computation = make-amount
				column-computation-parameters = "CURR_PL,REF_CURRENCY"
				table-column-width = 5
				tid = 27176067901646
			{
				--- TableColumnItem ---
					item-column = CurrPl
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Interest Rate", de = Zinssatz
				column-name = RATE !
				column-type = domain !
				domainAttribute = RATE !
				type = text
				column-visibility = not-visible
				id = RATE
				table-column-width = 5
				tid = 27176069856085
			{
				--- TableColumnItem ---
					item-column = RATE
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Accrued Interest", fr = "Intérêts courus", de = Stückzinsen
				column-name = AccruedInterest
				type = amount
				column-visibility = not-visible
				id = qX4__
				documentation = "Accrued Interest Value in Reference Currency by Money Market\'s position."
				column-computation = make-amount
				column-computation-parameters = "ACCRUED_INTEREST,REF_CURRENCY"
				table-column-width = 5
				tid = 27176071811361
			{
				--- TableColumnItem ---
					item-column = AccruedInterest
					previewValue = value
			}
			--- TableColumn ---
				column-name = STATUS !
				column-type = domain !
				domainAttribute = STATUS !
				id = STATUS
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = STATUS
					previewValue = value
			}
			--- TableColumn ---
				column-name = INSTR_CODE !
				column-type = domain !
				domainAttribute = INSTR_CODE !
				type = text
				column-is-part-of-filter = false
				column-visibility = never-visible
				id = INSTR_CODE
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = INSTR_CODE
					previewValue = value
			}
			--- TableColumn ---
				column-name = PORTFOLIO_CODE !
				column-type = domain !
				domainAttribute = PORTFOLIO_CODE !
				type = text
				column-is-part-of-filter = false
				column-visibility = never-visible
				id = PORTFOLIO_CODE
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = PORTFOLIO_CODE
					previewValue = value
			}
			--- TableColumn ---
				column-name = MKT_VAL !
				column-type = domain !
				domainAttribute = MKT_VAL !
				type = text
				column-sortable = false
				column-visibility = never-visible
				id = MKT_VAL
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = MKT_VAL
					format = decimal
					previewValue = value
			}
			--- TableColumn ---
				column-name = NET_COST_VAL !
				column-type = domain !
				domainAttribute = NET_COST_VAL !
				type = text
				column-sortable = false
				column-visibility = never-visible
				id = NET_COST_VAL
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = NET_COST_VAL
					format = decimal
					previewValue = value
			}
			--- TableColumn ---
				column-name = CURR_PL !
				column-type = domain !
				domainAttribute = CURR_PL !
				type = text
				column-sortable = false
				column-visibility = never-visible
				id = CURR_PL
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = CURR_PL
					format = decimal
					previewValue = value
			}
			--- TableColumn ---
				column-name = ACCRUED_INTEREST !
				column-type = domain !
				domainAttribute = ACCRUED_INTEREST !
				type = text
				column-sortable = false
				column-visibility = never-visible
				id = ACCRUED_INTEREST
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = ACCRUED_INTEREST
					format = decimal
					previewValue = value
			}
			--- TableExtra ---
				domainAttribute = INSTR_PRICE_CURRENCY
			--- TableExtra ---
				domainAttribute = INSTR_PRICE_PERCENTAGE
			--- TableExtra ---
				domainAttribute = COST_PRICE_CURRENCY
			--- TableExtra ---
				domainAttribute = COST_PRICE_PERCENTAGE
			--- TableExtra ---
				domainAttribute = QUANTITY_CURR
			--- TableSort ---
				sort-column-name = MKT_VAL
				sort-direction = descending
				sort-rank = 1
			--- TableExtra ---
				domainAttribute = CURR_CLASS_RANK
			--- TableExtra ---
				domainAttribute = seqno
			--- TableAggregate ---
				aggregate-column-name = NET_COST_VAL
				aggregate-computation = sum
				aggregate-group-names = "PTF_HIER_STR,INSTR_TYPE_DENOM,POS_CURRENCY"
			--- TableAggregate ---
				aggregate-column-name = NetCostVal
				aggregate-computation = sum
				aggregate-group-names = "PTF_HIER_STR,INSTR_TYPE_DENOM,POS_CURRENCY"
			--- TableAggregate ---
				aggregate-column-name = MKT_VAL_PERC_REL
				aggregate-computation = sum
				aggregate-group-names = "PTF_HIER_STR,INSTR_TYPE_DENOM,POS_CURRENCY"
			--- TableAggregate ---
				aggregate-column-name = MKT_VAL_PERC
				aggregate-computation = sum
				aggregate-group-names = "PTF_HIER_STR,INSTR_TYPE_DENOM,POS_CURRENCY"
			--- TableAggregate ---
				aggregate-column-name = CAP_PL
				aggregate-computation = sum
				aggregate-group-names = "PTF_HIER_STR,INSTR_TYPE_DENOM,POS_CURRENCY"
			--- TableAggregate ---
				aggregate-column-name = CURR_PL
				aggregate-computation = sum
				aggregate-group-names = "PTF_HIER_STR,INSTR_TYPE_DENOM,POS_CURRENCY"
			--- TableAggregate ---
				aggregate-column-name = PL
				aggregate-computation = sum
				aggregate-group-names = "PTF_HIER_STR,INSTR_TYPE_DENOM,POS_CURRENCY"
			--- TableAggregate ---
				aggregate-column-name = CurrPl
				aggregate-computation = sum
				aggregate-group-names = "PTF_HIER_STR,INSTR_TYPE_DENOM,POS_CURRENCY"
			--- TableAggregate ---
				aggregate-column-name = AccruedInterest
				aggregate-computation = sum
				aggregate-group-names = "PTF_HIER_STR,INSTR_TYPE_DENOM,POS_CURRENCY"
			--- TableAggregate ---
				aggregate-column-name = ACCRUED_INTEREST
				aggregate-computation = sum
				aggregate-group-names = "PTF_HIER_STR,INSTR_TYPE_DENOM,POS_CURRENCY"
			--- TableAggregate ---
				aggregate-column-name = MKT_VAL
				aggregate-computation = sum
				aggregate-group-names = "PTF_HIER_STR,INSTR_TYPE_DENOM,POS_CURRENCY"
			--- TableAggregate ---
				aggregate-column-name = MktVal
				aggregate-computation = sum
				aggregate-group-names = "PTF_HIER_STR,INSTR_TYPE_DENOM,POS_CURRENCY"
			--- TableAggregate ---
				aggregate-column-name = REF_CURRENCY
				aggregate-computation = max
				aggregate-group-names = "PTF_HIER_STR,INSTR_TYPE_DENOM,POS_CURRENCY"
			--- TableAggregate ---
				aggregate-column-name = PTF_HIER_STR
				aggregate-computation = max
				aggregate-group-names = PTF_HIER_STR
			--- TableAggregate ---
				aggregate-column-name = INSTR_TYPE_DENOM
				aggregate-computation = max
				aggregate-group-names = INSTR_TYPE_DENOM
			--- TableAggregate ---
				aggregate-column-name = CURR_CLASS_RANK
				aggregate-computation = max
				aggregate-group-names = POS_CURRENCY
			--- TableExtra ---
				domainAttribute = id
		}
	}
}