# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels fr = "Conformité détaillée par portefeuille", de = "Detaillierte Konformität per Portfolio", en = "Compliance Details per Portfolio"
	containment = container
	domainEntity = "AAADSComplianceChecking:ComplianceCheckingDetailledStrategyCheck"
	bean-define = DSBean.AAADSComplianceChecking.ComplianceCheckingDetailledStrategyCheck
	bean-name = ComplianceCheckingDetailledStrategyCheck
	id = DetailedList_rb69z
	documentation = "This module displays compliance details on the selected Portfolio. The compliance details are based on objectives and constraints."
	tid = 6229663113525
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TabbedPane ---
			id = u___7
			indexOfSelectedChild = 0
		{
			--- Tab ---
				labels fr = "Conformité des objectifs", de = "Überprüfung Anlagestrategie", en = "Objectives Compliance"
				boxType = vertical
				id = tab_R___Y
				documentation = "This tab displays the objectives compliance details of the selected Portfolio"
				isWidgetSelected = true
				tid = 6229663292278
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/compliancechecking/detailedlist/ObjectivesCompliance.module
				--- Include ---
					includeSrc = "" !
					resource:///default/initiateorder/NavigationInitiateOrderFromValuation.fragment
			}
			--- Tab ---
				labels fr = "Conformité des contraintes", de = "Überprüfung Beschränkungen", en = "Constraints Compliance"
				id = tab_F_90_
				documentation = "This tab displays the constraints compliance details of the selected Portfolio"
				isWidgetVisible = false
				tid = 6229663468478
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/compliancechecking/detailedlist/ConstraintCompliance.module
			}
		}
	}
}