# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSCalendar:CalendarAll"
	bean-define = DSBean.AAADSCalendar.CalendarAll
	bean-name = CalendarAll
	id = CalendarDetail_C_b_y
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 6
			gridColumnsWidth = "16,16,16,16,16,16" !
			gridRowCount = 2
		{
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- LabelDomain ---
					domainAttribute = code !
					for = code
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					width = 0
					required = true
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- TextField ---
					domainAttribute = code !
					horizontalAlignment = "${corporatehalign}"
					type = text
					required = true
					bean-property = code
					id = code
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- LabelDomain ---
					domainAttribute = name !
					for = name
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					width = 0
					required = true
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- TextField ---
					domainAttribute = name !
					horizontalAlignment = "${corporatehalign}"
					type = text
					required = true
					bean-property = name
					id = name
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- LabelDomain ---
					domainAttribute = denom !
					for = denom
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					width = 0
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- TextField ---
					domainAttribute = denom !
					horizontalAlignment = "${corporatehalign}"
					type = text
					bean-property = denom
					id = denom
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- LabelDomain ---
					domainAttribute = nextBusDateRuleE !
					for = nextBusDateRuleE
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					width = 0
					required = true
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- ComboBox ---
					domainAttribute = nextBusDateRuleE !
					horizontalAlignment = "${corporatehalign}"
					required = true
					bean-property = nextBusDateRuleE
					id = nextBusDateRuleE
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- LabelDomain ---
					domainAttribute = busDateRuleE !
					for = busDateRuleE
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					width = 0
					required = true
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- ComboBox ---
					domainAttribute = busDateRuleE !
					horizontalAlignment = "${corporatehalign}"
					required = true
					bean-property = busDateRuleE
					id = busDateRuleE
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- LabelDomain ---
					domainAttribute = addDaysNumN !
					for = addDaysNumN
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					width = 0
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- TextField ---
					domainAttribute = addDaysNumN !
					horizontalAlignment = "${corporatehalign}"
					type = integer
					bean-property = addDaysNumN
					id = addDaysNumN
			}
		}
	}
}