# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Calendar List", fr = "Liste de calendrier", de = "Liste der Kalender"
	domainEntity = "AAADSCalendar:CalendarList"
	bean-define = DSBean.AAADSCalendar.CalendarList
	bean-name = CalendarList
	id = CalendarList_n360_
	tid = 446870202908470
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			id = V_2N_
			table-column-count = 3 !
			table-columns-width = "33,33,33" !
		{
			--- TableColumn ---
				column-name = code !
				column-type = domain !
				domainAttribute = code !
				id = code
				table-column-width = 33
			{
				--- TableColumnItem ---
					item-column = code
					previewValue = value
			}
			--- TableColumn ---
				column-name = name !
				column-type = domain !
				domainAttribute = name !
				id = name
				table-column-width = 33
			{
				--- TableColumnItem ---
					item-column = name
					previewValue = value
			}
			--- TableColumn ---
				column-name = denom !
				column-type = domain !
				domainAttribute = denom !
				id = denom
				table-column-width = 33
			{
				--- TableColumnItem ---
					item-column = denom
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = code
				sort-rank = 1
		}
	}
}