# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels de = Garantie, fr = Garantie, en = Garantee
	domainEntity = "AAADSGuarantie:GuaranteeList"
	cssClass = nodeco
	bean-define = DSBean.AAADSGuarantie.GuaranteeList
	bean-name = GuaranteeList
	id = GaranteeList_J2BJ9
	tid = 1907284700955009
{
	--- Box ---
		labels en = "Guarantee ", de = Garantie, fr = Garantie
		boxType = vertical
		width = 0
		tid = 1146682413927747
	{
		--- TableTree ---
			table-filter-layer = true
			id = e_2__
			table-column-count = 3 !
			table-columns-width = "33,33,33" !
		{
			--- TableColumn ---
				labels de = Drittpartei, fr = "Tierce partie"
				column-name = thirdCode !
				column-type = domain !
				domainAttribute = thirdCode !
				id = thirdCode
				table-column-width = 33
				tid = 22093081528238
			{
				--- TableColumnItem ---
					item-column = thirdCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = typeExtDenomination !
				column-type = domain !
				domainAttribute = typeExtDenomination !
				type = text
				id = typeExtDenomination
				table-column-width = 33
			{
				--- TableColumnItem ---
					item-column = typeExtDenomination
					previewValue = value
			}
			--- TableColumn ---
				column-name = guaranteeP !
				column-type = domain !
				domainAttribute = guaranteeP !
				id = guaranteeP
				table-column-width = 33
			{
				--- TableColumnItem ---
					item-column = guaranteeP
					format = percentTA
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = thirdCode
				sort-rank = 1
			--- TableSort ---
				sort-column-name = typeCode
				sort-rank = 2
		}
	}
}