# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Create Notepad", de = "Notizblock erstellen", fr = "Créer un bloc-note"
	domainEntity = "AAADSNotepad:NotepadAll"
	bean-define = DSBean.AAADSNotepad.NotepadAll
	bean-name = NotepadAll
	id = NotepadCreate_pp0n1
	tid = 21039049430515
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 6
			gridColumnsWidth = "16,16,16,16,16,16" !
			gridRowCount = 2
		{
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- LabelDomain ---
					domainAttribute = noteD !
					for = noteD
					horizontalAlignment = "${corporatehalign}"
					required = true
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- CaldateField ---
					domainAttribute = noteD !
					format = datetime.date-only
					horizontalAlignment = "${corporatehalign}"
					type = datetime
					required = true
					bean-property = noteD
					id = noteD
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- LabelDomain ---
					domainAttribute = user !
					horizontalAlignment = "${corporatehalign}"
					required = true
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- Include ---
					domainAssociation = user
					includeSrc = "" !
					resource:///default/defaultFragments/ApplUserIdentifier.fragment
					bean-property-prefix = user.
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- LabelDomain ---
					domainAttribute = type !
					horizontalAlignment = "${corporatehalign}"
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- Include ---
					domainAssociation = type
					includeSrc = "" !
					resource:///default/defaultFragments/TypeIdentifier.fragment
					bean-property-prefix = type.
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- LabelDomain ---
					domainAttribute = titleC !
					for = titleC
					horizontalAlignment = "${corporatehalign}"
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- TextField ---
					domainAttribute = titleC !
					horizontalAlignment = "${corporatehalign}"
					type = text
					chars = 20
					bean-property = titleC
					id = titleC
			}
			--- GridCell ---
				gridColumnWidth = 16
			--- GridCell ---
				gridColumnWidth = 16
			--- GridCell ---
				gridColumnWidth = 16
			--- GridCell ---
				gridColumnWidth = 16
		}
		--- Grid ---
			cssClass = blank
			gridColumnCount = 2
			gridColumnsWidth = "10,70" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 10
			{
				--- LabelDomain ---
					domainAttribute = noteC !
					for = noteC
					horizontalAlignment = "${corporatehalign}"
			}
			--- GridCell ---
				gridColumnWidth = 70
			{
				--- TextArea ---
					domainAttribute = noteC !
					columns = 170
					horizontalAlignment = "${corporatehalign}"
					rows = 3
					type = text
					bean-property = noteC
					id = noteC
			}
		}
		--- Grid ---
			cssClass = blank
			gridColumnCount = 4
			gridColumnsWidth = "25,25,25,25" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Button ---
					labels en = Save, de = Speichern, fr = Sauver
					id = btn_i1d6_
					tid = 21136978251188
				{
					Event OnClick (submit)
					{
						method = get
						call-URI = "<pageflow:continuation/>"
						widget-group-ref = form
						param = "flow-action=insert"
						only-changed = true
						modal = false
						prevalidate = false
					}
				}
				--- Button ---
					labels en = Cancel, de = Abbrechen, fr = Annuler
					id = btn_W0__B
					tid = 21146754127897
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						flow-action = create ud
						editionState = CREATE ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
				--- Button ---
					labels en = Search, de = Suchen, fr = Rechercher
					id = btn_a3__6
					tid = 21149785990842
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						flow-action = search ud
						editionState = NONE ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
		}
	}
}