# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels fr = Composition, de = Zusammensetzung, en = Composition
	domainEntity = "AAADSInstrCompo:InstrCompoList"
	cssClass = nodeco
	bean-define = DSBean.AAADSInstrCompo.InstrCompoList
	bean-name = InstrCompoList
	id = InstrumentCompositionList_X070_
	tid = 1895129374219908
{
	--- Box ---
		labels en = Composition, de = Zusammensetzung, fr = Composition
		boxType = vertical
		width = 0
		tid = 715811373204695
	{
		--- TableTree ---
			table-filter-layer = true
			id = l1_13
			table-column-count = 9 !
			table-columns-width = "11,11,11,11,11,11,11,11,11" !
		{
			--- TableColumn ---
				labels en = Instrument, fr = Instrument, de = Instrument
				column-name = instrExtDenomination !
				column-type = domain !
				domainAttribute = instrExtDenomination !
				type = text
				id = instrExtDenomination
				table-column-width = 11
				tid = 110026004934170
			{
				--- TableColumnItem ---
					item-column = instrExtDenomination
					previewValue = value
			}
			--- TableColumn ---
				column-name = beginD !
				column-type = domain !
				domainAttribute = beginD !
				id = beginD
				table-column-width = 11
			{
				--- TableColumnItem ---
					item-column = beginD
					format = date
					previewValue = value
			}
			--- TableColumn ---
				column-name = endD !
				column-type = domain !
				domainAttribute = endD !
				type = text
				id = endD
				table-column-width = 11
			{
				--- TableColumnItem ---
					item-column = endD
					format = date
					previewValue = value
			}
			--- TableColumn ---
				column-name = rankN !
				column-type = domain !
				domainAttribute = rankN !
				type = text
				id = rankN
				table-column-width = 11
			{
				--- TableColumnItem ---
					item-column = rankN
					format = integer
					previewValue = value
			}
			--- TableColumn ---
				column-name = quantityN !
				column-type = domain !
				domainAttribute = quantityN !
				id = quantityN
				table-column-width = 11
			{
				--- TableColumnItem ---
					item-column = quantityN
					format = decimal.detailed
					previewValue = value
			}
			--- TableColumn ---
				column-name = convFactN !
				column-type = domain !
				domainAttribute = convFactN !
				type = text
				column-visibility = not-visible
				id = convFactN
				table-column-width = 11
			{
				--- TableColumnItem ---
					item-column = convFactN
					format = decimal.detailed
					previewValue = value
			}
			--- TableColumn ---
				column-name = convRatioN !
				column-type = domain !
				domainAttribute = convRatioN !
				type = text
				column-visibility = not-visible
				id = convRatioN
				table-column-width = 11
			{
				--- TableColumnItem ---
					item-column = convRatioN
					format = decimal.detailed
					previewValue = value
			}
			--- TableColumn ---
				column-name = cheapestF !
				column-type = domain !
				domainAttribute = cheapestF !
				type = text
				column-visibility = not-visible
				id = cheapestF
				table-column-width = 11
			{
				--- TableColumnItem ---
					item-column = cheapestF
					previewValue = value
			}
			--- TableColumn ---
				column-name = divisorN !
				column-type = domain !
				domainAttribute = divisorN !
				type = text
				column-visibility = not-visible
				id = divisorN
				table-column-width = 11
			{
				--- TableColumnItem ---
					item-column = divisorN
					format = decimal.detailed
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = beginD
				sort-rank = 2
			--- TableSort ---
				sort-column-name = endD
				sort-direction = descending
				sort-rank = 3
			--- TableSort ---
				sort-column-name = rankN
				sort-direction = descending
				sort-rank = 4
		}
	}
}