# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Search Portfolio", fr = "Recherche de portefeuille", de = "Portfolio Suche"
	containment = container
	search = container !
	cssClass = nodeco
	id = PortfolioSearch_eHy1_
	tid = 269140729542801
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/portfolio/search/PortfolioSearchInput.module
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/portfolio/search/PortfolioList.module
	}
}