# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Search Portfolio", de = "Portfolio suchen", fr = "Recherche de portefeuille"
	containment = container
	search = container !
	cssClass = nodeco
	id = PortfolioSearch_eHy1_
	tid = 5571932091793
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/portfolio/search/PortfolioSearchInput.module
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/portfolio/search/PortfolioListOrder.module
	}
}