# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Portfolio Search Criteria", fr = "Critères de recherche sur portefeuille", de = "Portfolio Suchbegriffe"
	containment = container
	domainEntity = "AAADSPortfolio:PortfolioSearchCriteria"
	search = input !
	bean-define = DSBean.AAADSPortfolio.PortfolioSearchCriteria
	bean-name = PortfolioSearchCriteria
	id = PortfolioSearchInput_i09a_
	tid = 69919319213475
{
	--- Box ---
		boxType = vertical
	{
		--- Box ---
		{
			--- FilterCriteria ---
				includedFile = "resource:/com/module/search/QueryBuilder.xsp"
		}
		--- Include ---
			includeSrc = "" !
			resource:///default/search/NavigationSearch.fragment
	}
}