# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Search Results", fr = "Résultats de la recherche", de = Suchergebnisse
	domainEntity = "AAADSPortfolio:PortfolioList"
	search = output !
	bean-define = DSBean.AAADSPortfolio.PortfolioList
	bean-name = PortfolioList
	id = PortfolioList_Z_l42
	tid = 5571912884147
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			id = R87_a
			table-model-reference = DSTableModel.AAADSPortfolio.PortfolioList
			table-column-count = 9 !
			table-columns-width = "11,11,11,11,11,11,11,11,11" !
		{
			--- TableColumn ---
				labels de = Code
				column-name = code !
				column-type = domain !
				domainAttribute = code !
				id = code
				table-column-width = 11
				tid = 20023921198643
			{
				--- TableColumnItem ---
					toolTips en = "Select Portfolio", fr = "Sélectionner le portefeuille", de = "Portfolio auswählen"
					item-column = code
					previewValue = value
					tid = 261275389859907
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = select ud
						Query.beanValue1 = "<udp:item column=\"code\"/>" ud
						modal = false
						only-changed = false
						prevalidate = false
						Snippet FilterSet
						id = fs_PYk
					}
				}
			}
			--- TableColumn ---
				column-name = extDenomination !
				column-type = domain !
				domainAttribute = extDenomination !
				type = text
				id = extDenomination
				table-column-width = 11
			{
				--- TableColumnItem ---
					item-column = extDenomination
					previewValue = value
			}
			--- TableColumn ---
				column-name = currencyExtDenomination !
				column-type = domain !
				domainAttribute = currencyExtDenomination !
				type = text
				id = currencyExtDenomination
				table-column-width = 11
			{
				--- TableColumnItem ---
					item-column = currencyExtDenomination
					previewValue = value
			}
			--- TableColumn ---
				labels de = Kundencode
				column-name = thirdCode !
				column-type = domain !
				domainAttribute = thirdCode !
				type = text
				id = thirdCode
				table-column-width = 11
				tid = 1603686296017971
			{
				--- TableColumnItem ---
					item-column = thirdCode
					previewValue = value
			}
			--- TableColumn ---
				labels de = Kunde
				column-name = thirdName !
				column-type = domain !
				domainAttribute = thirdName !
				type = text
				id = thirdName
				table-column-width = 11
				tid = 1603686296262632
			{
				--- TableColumnItem ---
					item-column = thirdName
					previewValue = value
			}
			--- TableColumn ---
				column-name = commMgrName !
				column-type = domain !
				domainAttribute = commMgrName !
				type = text
				id = commMgrName
				table-column-width = 11
			{
				--- TableColumnItem ---
					item-column = commMgrName
					previewValue = value
			}
			--- TableColumn ---
				column-name = adminMgrName !
				column-type = domain !
				domainAttribute = adminMgrName !
				type = text
				id = adminMgrName
				table-column-width = 11
			{
				--- TableColumnItem ---
					item-column = adminMgrName
					previewValue = value
			}
			--- TableColumn ---
				column-name = serviceTypeE !
				column-type = domain !
				domainAttribute = serviceTypeE !
				type = text
				id = serviceTypeE
				table-column-width = 11
			{
				--- TableColumnItem ---
					item-column = serviceTypeE
					previewValue = value
			}
			--- TableColumn ---
				column-name = managTypeExtDenomination !
				column-type = domain !
				domainAttribute = managTypeExtDenomination !
				type = text
				id = managTypeExtDenomination
				table-column-width = 11
			{
				--- TableColumnItem ---
					item-column = managTypeExtDenomination
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = commMgrName
				sort-rank = 3
			--- TableSort ---
				sort-column-name = serviceTypeE
				sort-rank = 4
			--- TableSort ---
				sort-column-name = code
				sort-rank = 2
		}
	}
}