# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels fr = "Recherche de portefeuille", en = "Search Portfolio", de = "Portfolio Suche"
	containment = container
	search = container !
	cssClass = nodeco
	id = PortfolioSearchMultiple_xm__5
	tid = 161627323739305
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/portfolio/search/PortfolioSearchInput.module
		--- Box ---
			boxType = vertical
		{
			--- Box ---
				boxType = vertical
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/search/NavigationUseInContext.fragment
			}
		}
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/portfolio/search/PortfolioListMultiple.module
	}
}