# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Query Results", fr = "Résultats de la recherche", de = Suchergebnisse
	domainEntity = "AAADSPortfolio:PortfolioList"
	search = output !
	bean-define = DSBean.AAADSPortfolio.PortfolioList
	bean-name = PortfolioList
	id = PortfolioList_Z_l42
	tid = 166147178880835
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			table-select-all = true
			id = OM2_0
			table-model-reference = DSTableModel.AAADSPortfolio.PortfolioList
			table-column-count = 17 !
			table-columns-width = "5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5" !
		{
			--- TableColumn ---
				column-name = SELECT
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				id = x___x
				table-column-width = 5
			{
				--- CheckBox ---
					column-checkbox-identifier = id
					horizontalTextPosition = trail
					id = btn_E1_iC
			}
			--- TableColumn ---
				labels de = Code
				column-name = code !
				column-type = domain !
				domainAttribute = code !
				column-locked = true
				id = code
				table-column-width = 5
				tid = 26522668814053
			{
				--- TableColumnItem ---
					item-column = code
					previewValue = value
			}
			--- TableColumn ---
				column-name = name !
				column-type = domain !
				domainAttribute = name !
				id = name
				table-column-width = 5
			{
				--- Icon ---
					toolTips en = "View Portfolio Details", fr = "Voir les détails du portefeuille", de = "Details des Portfolios ansehen"
					icon = application_form_magnify
					id = N3hJ9
					tid = 543866688328019
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "resource:///administration/portfolio/PortfolioView.pageflow"
						target = popup
						code = "<udp:item column=\"code\"/>" ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
				--- Spacer ---
					height = 10
					width = 4
				--- TableColumnItem ---
					item-column = name
					previewValue = value
			}
			--- TableColumn ---
				column-name = extDenomination !
				column-type = domain !
				domainAttribute = extDenomination !
				type = text
				id = extDenomination
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = extDenomination
					previewValue = value
			}
			--- TableColumn ---
				column-name = currencyExtDenomination !
				column-type = domain !
				domainAttribute = currencyExtDenomination !
				type = text
				id = currencyExtDenomination
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = currencyExtDenomination
					previewValue = value
			}
			--- TableColumn ---
				labels de = Kundencode
				column-name = thirdCode !
				column-type = domain !
				domainAttribute = thirdCode !
				type = text
				id = thirdCode
				table-column-width = 5
				tid = 1603685243190447
			{
				--- TableColumnItem ---
					item-column = thirdCode
					previewValue = value
			}
			--- TableColumn ---
				labels de = Kunde
				column-name = thirdName !
				column-type = domain !
				domainAttribute = thirdName !
				type = text
				id = thirdName
				table-column-width = 5
				tid = 1603685243499695
			{
				--- TableColumnItem ---
					item-column = thirdName
					previewValue = value
			}
			--- TableColumn ---
				column-name = commMgrName !
				column-type = domain !
				domainAttribute = commMgrName !
				type = text
				id = commMgrName
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = commMgrName
					previewValue = value
			}
			--- TableColumn ---
				column-name = adminMgrName !
				column-type = domain !
				domainAttribute = adminMgrName !
				type = text
				id = adminMgrName
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = adminMgrName
					previewValue = value
			}
			--- TableColumn ---
				column-name = activeF !
				column-type = domain !
				domainAttribute = activeF !
				type = text
				column-visibility = not-visible
				id = activeF
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = activeF
					previewValue = value
			}
			--- TableColumn ---
				labels de = Status, fr = Statut
				column-name = statusE !
				column-type = domain !
				domainAttribute = statusE !
				type = text
				column-visibility = not-visible
				id = statusE
				table-column-width = 5
				tid = 1603685244825228
			{
				--- TableColumnItem ---
					item-column = statusE
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Market Value (Sys. Ccy.)", fr = "Valeur de marché (devise sys.)", de = "Marktwert (Sys. Währung)"
				column-name = MarketValue
				type = amount
				id = l_861
				column-computation = make-amount
				column-computation-parameters = "extTdMktValM,extRefCur"
				table-column-width = 5
				tid = 810857065760033
			{
				--- TableColumnItem ---
					item-column = MarketValue
					previewValue = value
			}
			--- TableColumn ---
				column-name = extChangeMktValP !
				column-type = domain !
				domainAttribute = extChangeMktValP !
				type = text
				id = extChangeMktValP
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = extChangeMktValP
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = extBenchDenom !
				column-type = domain !
				domainAttribute = extBenchDenom !
				type = text
				id = extBenchDenom
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = extBenchDenom
					previewValue = value
			}
			--- TableColumn ---
				column-name = extYtdBenchRet !
				column-type = domain !
				domainAttribute = extYtdBenchRet !
				type = text
				id = extYtdBenchRet
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = extYtdBenchRet
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = extYtdPtfReturn !
				column-type = domain !
				domainAttribute = extYtdPtfReturn !
				type = text
				id = extYtdPtfReturn
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = extYtdPtfReturn
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = extOverUnderPerf !
				column-type = domain !
				domainAttribute = extOverUnderPerf !
				type = text
				id = extOverUnderPerf
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = extOverUnderPerf
					format = percentTA
					previewValue = value
			}
			--- TableExtra ---
				domainAttribute = id
			--- TableSort ---
				sort-column-name = code
				sort-rank = 1
			--- TableSort ---
				sort-column-name = commMgrName
				sort-rank = 2
		}
	}
}