# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Search Results", fr = "Résultats de la recherche", de = Suchergebnisse
	domainEntity = "AAADSPortfolio:PortfolioList"
	search = output !
	bean-define = DSBean.AAADSPortfolio.PortfolioList
	bean-name = PortfolioList
	id = PortfolioList_Z_l42
	tid = 173523348484317
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			table-select-all = true
			id = OM2_0
			table-model-reference = DSTableModel.AAADSPortfolio.PortfolioList
			table-column-count = 31 !
			table-columns-width = "3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3" !
		{
			--- TableColumn ---
				column-name = SELECT
				column-type = placeholder !
				type = boolean
				column-locked = true
				column-sortable = false !
				id = x___x
				table-column-width = 3
			{
				--- CheckBox ---
					column-checkbox-identifier = id
					horizontalTextPosition = trail
					id = btn_y1k_U
			}
			--- TableColumn ---
				labels de = Code
				column-name = code !
				column-type = domain !
				domainAttribute = code !
				column-locked = true
				id = code
				table-column-width = 3
				tid = 19770889234525
			{
				--- TableColumnItem ---
					item-column = code
					previewValue = value
			}
			--- TableColumn ---
				column-name = name !
				column-type = domain !
				domainAttribute = name !
				type = text
				id = name
				table-column-width = 3
			{
				--- Icon ---
					toolTips en = "View Portfolio Details", fr = "Voir les détails du portefeuille", de = "Details des Portfolios ansehen"
					icon = application_form_magnify
					id = Bf_7n
					tid = 543812740950008
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "resource:///administration/portfolio/PortfolioView.pageflow"
						target = popup
						code = "<udp:item column=\"code\"/>" ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
				--- Spacer ---
					height = 10
					width = 4
				--- TableColumnItem ---
					item-column = name
					previewValue = value
			}
			--- TableColumn ---
				column-name = extDenomination !
				column-type = domain !
				domainAttribute = extDenomination !
				type = text
				id = extDenomination
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = extDenomination
					previewValue = value
			}
			--- TableColumn ---
				column-name = currencyExtDenomination !
				column-type = domain !
				domainAttribute = currencyExtDenomination !
				type = text
				id = currencyExtDenomination
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = currencyExtDenomination
					previewValue = value
			}
			--- TableColumn ---
				column-name = thirdCode !
				column-type = domain !
				domainAttribute = thirdCode !
				type = text
				id = thirdCode
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = thirdCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = thirdName !
				column-type = domain !
				domainAttribute = thirdName !
				type = text
				id = thirdName
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = thirdName
					previewValue = value
			}
			--- TableColumn ---
				column-name = commMgrName !
				column-type = domain !
				domainAttribute = commMgrName !
				type = text
				id = commMgrName
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = commMgrName
					previewValue = value
			}
			--- TableColumn ---
				column-name = adminMgrName !
				column-type = domain !
				domainAttribute = adminMgrName !
				type = text
				id = adminMgrName
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = adminMgrName
					previewValue = value
			}
			--- TableColumn ---
				column-name = serviceTypeE !
				column-type = domain !
				domainAttribute = serviceTypeE !
				type = text
				id = serviceTypeE
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = serviceTypeE
					previewValue = value
			}
			--- TableColumn ---
				column-name = managTypeExtDenomination !
				column-type = domain !
				domainAttribute = managTypeExtDenomination !
				type = text
				id = managTypeExtDenomination
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = managTypeExtDenomination
					previewValue = value
			}
			--- TableColumn ---
				column-name = activeF !
				column-type = domain !
				domainAttribute = activeF !
				type = text
				column-visibility = not-visible
				id = activeF
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = activeF
					previewValue = value
			}
			--- TableColumn ---
				column-name = statusE !
				column-type = domain !
				domainAttribute = statusE !
				type = text
				column-visibility = not-visible
				id = statusE
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = statusE
					previewValue = value
			}
			--- TableColumn ---
				column-name = extCashPercent !
				column-type = domain !
				domainAttribute = extCashPercent !
				type = text
				column-visibility = not-visible
				id = extCashPercent
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = extCashPercent
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = extChangeMktValP !
				column-type = domain !
				domainAttribute = extChangeMktValP !
				type = text
				column-visibility = not-visible
				id = extChangeMktValP
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = extChangeMktValP
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = extCstCompliance !
				column-type = domain !
				domainAttribute = extCstCompliance !
				type = text
				column-visibility = not-visible
				id = extCstCompliance
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = extCstCompliance
					previewValue = value
			}
			--- TableColumn ---
				column-name = extDateOperation !
				column-type = domain !
				domainAttribute = extDateOperation !
				type = text
				column-visibility = not-visible
				id = extDateOperation
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = extDateOperation
					format = date
					previewValue = value
			}
			--- TableColumn ---
				column-name = extDaysOperation !
				column-type = domain !
				domainAttribute = extDaysOperation !
				type = text
				column-visibility = not-visible
				id = extDaysOperation
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = extDaysOperation
					format = integer
					previewValue = value
			}
			--- TableColumn ---
				column-name = extDaysToRedemp !
				column-type = domain !
				domainAttribute = extDaysToRedemp !
				format = integer
				type = text
				column-visibility = not-visible
				id = extDaysToRedemp
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = extDaysToRedemp
					previewValue = value
			}
			--- TableColumn ---
				column-name = extDaysToRedemp2 !
				column-type = domain !
				domainAttribute = extDaysToRedemp2 !
				format = integer
				type = text
				column-visibility = not-visible
				id = extDaysToRedemp2
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = extDaysToRedemp2
					previewValue = value
			}
			--- TableColumn ---
				column-name = extNextExpLimitOrder !
				column-type = domain !
				domainAttribute = extNextExpLimitOrder !
				format = integer
				type = text
				column-visibility = not-visible
				id = extNextExpLimitOrder
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = extNextExpLimitOrder
					previewValue = value
			}
			--- TableColumn ---
				column-name = extExpLimitOrder !
				column-type = domain !
				domainAttribute = extExpLimitOrder !
				type = text
				column-visibility = not-visible
				id = extExpLimitOrder
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = extExpLimitOrder
					format = integer
					previewValue = value
			}
			--- TableColumn ---
				column-name = extExecLimitOrder !
				column-type = domain !
				domainAttribute = extExecLimitOrder !
				type = text
				column-visibility = not-visible
				id = extExecLimitOrder
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = extExecLimitOrder
					format = integer
					previewValue = value
			}
			--- TableColumn ---
				column-name = extMinBondRating !
				column-type = domain !
				domainAttribute = extMinBondRating !
				type = text
				column-visibility = not-visible
				id = extMinBondRating
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = extMinBondRating
					previewValue = value
			}
			--- TableColumn ---
				column-name = extObjCompliance !
				column-type = domain !
				domainAttribute = extObjCompliance !
				type = text
				column-visibility = not-visible
				id = extObjCompliance
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = extObjCompliance
					previewValue = value
			}
			--- TableColumn ---
				column-name = extOverUnderPerf !
				column-type = domain !
				domainAttribute = extOverUnderPerf !
				type = text
				column-visibility = not-visible
				id = extOverUnderPerf
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = extOverUnderPerf
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = extPlPercent !
				column-type = domain !
				domainAttribute = extPlPercent !
				type = text
				column-visibility = not-visible
				id = extPlPercent
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = extPlPercent
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Cost Value (Sys. Ccy.)", fr = "Coût d\'achat (devise sys.)", de = "Kaufskosten (Sys. Währung)"
				column-name = CostValue
				type = amount
				column-visibility = not-visible
				id = Pf18_
				column-computation = make-amount
				column-computation-parameters = "extTdCostValM,extRefCur"
				table-column-width = 3
				tid = 30942029456483
			{
				--- TableColumnItem ---
					item-column = CostValue
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Market Value (Sys. Ccy.)", fr = "Valeur de marché (devise sys.)", de = "Markwert (Sys. Währung)"
				column-name = MarketValue
				type = amount
				column-visibility = not-visible
				id = z__0A
				column-computation = make-amount
				column-computation-parameters = "extTdMktValM,extRefCur"
				table-column-width = 3
				tid = 30961517271756
			{
				--- TableColumnItem ---
					item-column = MarketValue
					previewValue = value
			}
			--- TableColumn ---
				column-name = extYtdBenchRet !
				column-type = domain !
				domainAttribute = extYtdBenchRet !
				type = text
				column-visibility = not-visible
				id = extYtdBenchRet
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = extYtdBenchRet
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = extYtdPtfReturn !
				column-type = domain !
				domainAttribute = extYtdPtfReturn !
				type = text
				column-visibility = not-visible
				id = extYtdPtfReturn
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = extYtdPtfReturn
					format = percentTA
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = code
				sort-rank = 1
			--- TableExtra ---
				domainAttribute = id
			--- TableSort ---
				sort-column-name = serviceTypeE
				sort-rank = 2
			--- TableSort ---
				sort-column-name = commMgrName
				sort-rank = 3
		}
	}
}