# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Query Results", fr = "Résultats de la recherche", de = Suchergebnisse
	domainEntity = "AAADSPortfolio:PortfolioList"
	search = output !
	bean-define = DSBean.AAADSPortfolio.PortfolioList
	bean-name = PortfolioList
	id = PortfolioList_Z_l42
	tid = 166255981729242
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			table-select-all = true
			id = OM2_0
			table-model-reference = DSTableModel.AAADSPortfolio.PortfolioList
			table-column-count = 21 !
			table-columns-width = "4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4" !
		{
			--- TableColumn ---
				column-name = SELECT
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				id = x___x
				table-column-width = 4
			{
				--- CheckBox ---
					column-checkbox-identifier = id
					horizontalTextPosition = trail
					id = btn_R_9qd
			}
			--- TableColumn ---
				labels de = Code
				column-name = code !
				column-type = domain !
				domainAttribute = code !
				column-locked = true
				id = code
				table-column-width = 4
				tid = 19908073173545
			{
				--- TableColumnItem ---
					item-column = code
					previewValue = value
			}
			--- TableColumn ---
				column-name = name !
				column-type = domain !
				domainAttribute = name !
				id = name
				table-column-width = 4
			{
				--- Icon ---
					toolTips en = "View Portfolio Details", fr = "Voir les détails du portefeuille", de = "Details des Portfolios ansehen"
					icon = application_form_magnify
					id = hK_X_
					tid = 543839277822356
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "resource:///administration/portfolio/PortfolioView.pageflow"
						target = popup
						code = "<udp:item column=\"code\"/>" ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
				--- Spacer ---
					height = 10
					width = 4
				--- TableColumnItem ---
					item-column = name
					previewValue = value
			}
			--- TableColumn ---
				column-name = extDenomination !
				column-type = domain !
				domainAttribute = extDenomination !
				type = text
				id = extDenomination
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = extDenomination
					previewValue = value
			}
			--- TableColumn ---
				column-name = currencyExtDenomination !
				column-type = domain !
				domainAttribute = currencyExtDenomination !
				type = text
				id = currencyExtDenomination
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = currencyExtDenomination
					previewValue = value
			}
			--- TableColumn ---
				labels de = Kundencode
				column-name = thirdCode !
				column-type = domain !
				domainAttribute = thirdCode !
				type = text
				id = thirdCode
				table-column-width = 4
				tid = 1603685888673266
			{
				--- TableColumnItem ---
					item-column = thirdCode
					previewValue = value
			}
			--- TableColumn ---
				labels de = Kunde
				column-name = thirdName !
				column-type = domain !
				domainAttribute = thirdName !
				type = text
				id = thirdName
				table-column-width = 4
				tid = 1603685888930758
			{
				--- TableColumnItem ---
					item-column = thirdName
					previewValue = value
			}
			--- TableColumn ---
				column-name = commMgrName !
				column-type = domain !
				domainAttribute = commMgrName !
				type = text
				id = commMgrName
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = commMgrName
					previewValue = value
			}
			--- TableColumn ---
				column-name = adminMgrName !
				column-type = domain !
				domainAttribute = adminMgrName !
				type = text
				id = adminMgrName
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = adminMgrName
					previewValue = value
			}
			--- TableColumn ---
				column-name = serviceTypeE !
				column-type = domain !
				domainAttribute = serviceTypeE !
				type = text
				id = serviceTypeE
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = serviceTypeE
					previewValue = value
			}
			--- TableColumn ---
				column-name = managTypeExtDenomination !
				column-type = domain !
				domainAttribute = managTypeExtDenomination !
				type = text
				id = managTypeExtDenomination
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = managTypeExtDenomination
					previewValue = value
			}
			--- TableColumn ---
				column-name = activeF !
				column-type = domain !
				domainAttribute = activeF !
				type = text
				column-visibility = not-visible
				id = activeF
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = activeF
					previewValue = value
			}
			--- TableColumn ---
				labels de = Status, fr = Statut
				column-name = statusE !
				column-type = domain !
				domainAttribute = statusE !
				type = text
				column-visibility = not-visible
				id = statusE
				table-column-width = 4
				tid = 1603685890500096
			{
				--- TableColumnItem ---
					item-column = statusE
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Market Value (Sys. Ccy.)", fr = "Valeur d\'inventaire (devise sys.)", de = "Marktwert (Sys. Währung)"
				column-name = MarketValue
				type = amount
				id = FH19u
				column-computation = make-amount
				column-computation-parameters = "extTdMktValM,extRefCur"
				table-column-width = 4
				tid = 863361226020066
			{
				--- TableColumnItem ---
					item-column = MarketValue
					previewValue = value
			}
			--- TableColumn ---
				column-name = extDateOperation !
				column-type = domain !
				domainAttribute = extDateOperation !
				type = text
				id = extDateOperation
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = extDateOperation
					format = date
					previewValue = value
			}
			--- TableColumn ---
				column-name = extDaysOperation !
				column-type = domain !
				domainAttribute = extDaysOperation !
				type = text
				id = extDaysOperation
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = extDaysOperation
					format = integer
					previewValue = value
			}
			--- TableColumn ---
				column-name = extDateFxOperat !
				column-type = domain !
				domainAttribute = extDateFxOperat !
				type = text
				id = extDateFxOperat
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = extDateFxOperat
					format = date
					previewValue = value
			}
			--- TableColumn ---
				column-name = extDaysFxOperat !
				column-type = domain !
				domainAttribute = extDaysFxOperat !
				type = text
				id = extDaysFxOperat
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = extDaysFxOperat
					format = integer
					previewValue = value
			}
			--- TableColumn ---
				column-name = extNextExpLimitOrder !
				column-type = domain !
				domainAttribute = extNextExpLimitOrder !
				format = integer
				type = text
				id = extNextExpLimitOrder
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = extNextExpLimitOrder
					previewValue = value
			}
			--- TableColumn ---
				column-name = extExpLimitOrder !
				column-type = domain !
				domainAttribute = extExpLimitOrder !
				type = text
				id = extExpLimitOrder
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = extExpLimitOrder
					format = integer
					previewValue = value
			}
			--- TableColumn ---
				column-name = extExecLimitOrder !
				column-type = domain !
				domainAttribute = extExecLimitOrder !
				type = text
				id = extExecLimitOrder
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = extExecLimitOrder
					format = integer
					previewValue = value
			}
			--- TableExtra ---
				domainAttribute = id
			--- TableSort ---
				sort-column-name = code
				sort-rank = 1
			--- TableSort ---
				sort-column-name = commMgrName
				sort-rank = 2
		}
	}
}