# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Return Summary Views", fr = "Vues résumées des rendements", de = "Rendite Zusammenfassung"
	domainEntity = "AAADSReturn:SummaryReturnAnalysis"
	bean-define = DSBean.AAADSReturn.SummaryReturnAnalysis
	bean-name = SummaryReturnAnalysis
	id = ByPortfolio_R0gJ_
	tid = 16968381187832
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			table-filter-layer = true
			id = ARK_1
			table-column-count = 16 !
			table-columns-width = "6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6" !
		{
			--- TableColumn ---
				labels en = Portfolio, de = Portfolio, fr = Portefeuille
				column-display-grouping = true
				column-name = GROUPING
				column-type = placeholder !
				type = text
				column-locked = true
				column-sortable = false !
				column-width = 180
				id = Z1_fJ
				table-column-width = 6
				tid = 359109528644841
			{
				--- TableGroup ---
					aggregateData = false
					group-column-name = PTF_HIER_STR
					group-sorting-column-name = PTF_HIER_STR
					group-sorting-direction = ascending
					hierarchy = true
					group-rank = 1
			}
			--- TableColumn ---
				labels de = "Typ des Portfolios", fr = "Type de portefeuille"
				column-name = PORTFOLIO_TYPE_DENOM !
				column-type = domain !
				domainAttribute = PORTFOLIO_TYPE_DENOM !
				type = text
				id = g__f4
				table-column-width = 6
				tid = 1604015611588718
			{
				--- TableColumnItem ---
					item-column = PORTFOLIO_TYPE_DENOM
					previewValue = "Standard Portfolio"
			}
			--- TableColumn ---
				column-name = THIRD_COMP_RULE !
				column-type = domain !
				domainAttribute = THIRD_COMP_RULE !
				type = text
				column-visibility = not-visible
				id = THIRD_COMP_RULE
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = THIRD_COMP_RULE
					previewValue = value
			}
			--- TableColumn ---
				column-name = CLIENT_NAME !
				column-type = domain !
				domainAttribute = CLIENT_NAME !
				type = text
				column-visibility = not-visible
				id = CLIENT_NAME
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = CLIENT_NAME
					previewValue = value
			}
			--- TableColumn ---
				column-name = PORTFOLIO_INVEST_SERVICE !
				column-type = domain !
				domainAttribute = PORTFOLIO_INVEST_SERVICE !
				type = text
				column-visibility = not-visible
				id = PORTFOLIO_INVEST_SERVICE
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = PORTFOLIO_INVEST_SERVICE
					previewValue = value
			}
			--- TableColumn ---
				column-name = ADMIN_MGR_NAME !
				column-type = domain !
				domainAttribute = ADMIN_MGR_NAME !
				type = text
				column-visibility = not-visible
				id = ADMIN_MGR_NAME
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = ADMIN_MGR_NAME
					previewValue = value
			}
			--- TableColumn ---
				column-name = COM_MGR_NAME !
				column-type = domain !
				domainAttribute = COM_MGR_NAME !
				type = text
				column-visibility = not-visible
				id = COM_MGR_NAME
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = COM_MGR_NAME
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Final Market Value", de = End-Marktwert, fr = "Valeur d\'inventaire finale"
				column-name = FinalMktVal
				type = amount
				id = fIa__
				column-computation = make-amount
				column-computation-parameters = "PERIOD_FINAL_MKT_VAL,REF_CURRENCY"
				table-column-width = 6
				tid = 326143552831994
			{
				--- TableColumnItem ---
					item-column = FinalMktVal
					previewValue = "121 456.55 EUR"
			}
			--- TableColumn ---
				labels de = Endwert, fr = "Valeur d\'inventaire finale"
				column-name = PERIOD_FINAL_MKT_VAL !
				column-type = domain !
				domainAttribute = PERIOD_FINAL_MKT_VAL !
				type = text
				column-visibility = never-visible
				id = PERIOD_FINAL_MKT_VAL
				table-column-width = 6
				tid = 1604015611956992
			{
				--- TableColumnItem ---
					item-column = PERIOD_FINAL_MKT_VAL
					format = decimal
					previewValue = value
			}
			--- TableColumn ---
				labels en = P&L, de = G/V, fr = G&P
				column-name = PL
				type = amount
				id = m558Y
				column-computation = make-amount
				column-computation-parameters = "CUMUL_GAIN_LOSS,REF_CURRENCY"
				table-column-width = 6
				tid = 326143553846648
			{
				--- TableColumnItem ---
					item-column = PL
					previewValue = "12 345.43 EUR"
			}
			--- TableColumn ---
				labels de = Gewinn/Verlust, fr = "Gains & pertes"
				column-name = CUMUL_GAIN_LOSS !
				column-type = domain !
				domainAttribute = CUMUL_GAIN_LOSS !
				type = text
				column-visibility = never-visible
				id = CUMUL_GAIN_LOSS
				table-column-width = 6
				tid = 1604015612315429
			{
				--- TableColumnItem ---
					item-column = CUMUL_GAIN_LOSS
					format = decimal
					previewValue = value
			}
			--- TableColumn ---
				labels de = "Rendite Portfolio", fr = "Rendement du portefeuille"
				column-name = CUMUL_TOT_RET !
				column-type = domain !
				domainAttribute = CUMUL_TOT_RET !
				type = text
				id = J2_84
				table-column-width = 6
				tid = 1604015612628527
			{
				--- TableColumnItem ---
					item-column = CUMUL_TOT_RET
					format = percentTA
					previewValue = 5.25%
			}
			--- TableColumn ---
				column-name = BENCH_DENOM !
				column-type = domain !
				domainAttribute = BENCH_DENOM !
				type = text
				id = e__06
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = BENCH_DENOM
					previewValue = "CHF Stock Bench"
			}
			--- TableColumn ---
				labels de = "Rendite Benchmark"
				column-name = CUMUL_TOT_RET_BENCH !
				column-type = domain !
				domainAttribute = CUMUL_TOT_RET_BENCH !
				type = text
				id = Fd83Z
				table-column-width = 6
				tid = 1604015613232908
			{
				--- TableColumnItem ---
					item-column = CUMUL_TOT_RET_BENCH
					format = percentTA
					previewValue = 4.55%
			}
			--- TableColumn ---
				column-name = THIRD_PARTY_OWNERSHIP_RULE !
				column-type = domain !
				domainAttribute = THIRD_PARTY_OWNERSHIP_RULE !
				type = text
				column-visibility = not-visible
				id = THIRD_PARTY_OWNERSHIP_RULE
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = THIRD_PARTY_OWNERSHIP_RULE
					previewValue = value
			}
			--- TableColumn ---
				column-name = THIRD_PARTY_PERCT_OWNERSHIP !
				column-type = domain !
				domainAttribute = THIRD_PARTY_PERCT_OWNERSHIP !
				type = text
				column-visibility = not-visible
				id = THIRD_PARTY_PERCT_OWNERSHIP
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = THIRD_PARTY_PERCT_OWNERSHIP
					format = percentTA
					previewValue = value
			}
			--- TableKeepFilter ---
				keep-filter-column-name = FILTER_2
				keep-filter-operand = 1
			--- TableSort ---
				sort-column-name = PTF_HIER_STR
				sort-direction = descending
				sort-rank = 4
			--- TableExtra ---
				domainAttribute = PORTFOLIO_CODE
			--- TableSort ---
				sort-column-name = PERIOD_FINAL_MKT_VAL
				sort-direction = descending
				sort-rank = 3
			--- TableSort ---
				sort-column-name = CUMUL_GAIN_LOSS
				sort-direction = descending
				sort-rank = 2
		}
	}
}