# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSFtRate:FtRateList"
	bean-define = DSBean.AAADSFtRate.FtRateList
	bean-name = FtRateList
	id = FtRateList_q__v7
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			id = e88__
			table-column-count = 5 !
			table-columns-width = "20,20,20,20,20" !
		{
			--- TableColumn ---
				column-name = ftRateHistoryFtConventionCode !
				column-type = domain !
				domainAttribute = ftRateHistoryFtConventionCode !
				id = ftRateHistoryFtConventionCode
				table-column-width = 20
			{
				--- TableColumnItem ---
					item-column = ftRateHistoryFtConventionCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = ftRateHistoryBeginD !
				column-type = domain !
				domainAttribute = ftRateHistoryBeginD !
				id = ftRateHistoryBeginD
				table-column-width = 20
			{
				--- TableColumnItem ---
					item-column = ftRateHistoryBeginD
					format = datetime.date-only
					previewValue = value
			}
			--- TableColumn ---
				column-name = rankN !
				column-type = domain !
				domainAttribute = rankN !
				id = rankN
				table-column-width = 20
			{
				--- TableColumnItem ---
					item-column = rankN
					format = integer
					previewValue = value
			}
			--- TableColumn ---
				column-name = taxGeoCode !
				column-type = domain !
				domainAttribute = taxGeoCode !
				id = taxGeoCode
				table-column-width = 20
			{
				--- TableColumnItem ---
					item-column = taxGeoCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = instrListCode !
				column-type = domain !
				domainAttribute = instrListCode !
				id = instrListCode
				table-column-width = 20
			{
				--- TableColumnItem ---
					item-column = instrListCode
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = ftRateHistoryFtConventionCode
				sort-rank = 1
			--- TableSort ---
				sort-column-name = ftRateHistoryBeginD
				sort-rank = 2
			--- TableSort ---
				sort-column-name = rankN
				sort-rank = 3
			--- TableSort ---
				sort-column-name = taxGeoCode
				sort-rank = 4
			--- TableSort ---
				sort-column-name = instrListCode
				sort-rank = 5
		}
	}
}