# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Search Results", fr = "Résultats de la recherche", de = Suchergebnisse
	domainEntity = "AAADSInstrument:InstrumentList"
	search = output !
	bean-define = DSBean.AAADSInstrument.InstrumentList
	bean-name = InstrumentList
	id = InstrumentListOption_t9wLZ
	tid = 449190940339903
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			table-page-size = 15
			id = V5oZK
			table-model-reference = DSTableModel.AAADSInstrument.InstrumentList
			table-column-count = 15 !
			table-columns-width = "6,6,6,6,6,6,6,6,6,6,6,6,6,6,6" !
		{
			--- TableColumn ---
				labels de = Code
				column-name = code !
				column-type = domain !
				domainAttribute = code !
				column-locked = true
				id = code
				table-column-width = 6
				tid = 19956361997684
			{
				--- Conditional ---
					indexOfSelectedChild = 1
				{
					--- ConditionalBody ---
						javaCode = "com.odcgroup.tsl.wui.search.form.SearchFormHelper.isLookup(objectModel) == false"
						technicalName = NotLookup
						boxType = vertical
						isWidgetVisible = false
					{
						--- TableColumnItem ---
							toolTips en = "Select Instrument", fr = "Sélectionner l\'instrument", de = "Instrument auswählen"
							item-column = code
							previewValue = value
							tid = 121556476492523
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = select ud
								Query.beanValue1 = "<udp:item column=\"code\"/>" ud
								modal = false
								only-changed = false
								prevalidate = false
								Snippet FilterSet
								id = fs_PYk
							}
						}
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetSelected = true
					{
						--- TableColumnItem ---
							toolTips en = "Select Instrument", fr = "Sélectionner l\'instrument", de = "Instrument auswählen"
							item-column = code
							previewValue = value
							tid = 34225645651460
						{
							Event OnClick (setWidgetValue)
							{
								widget-group-id = "<xsp:expr>com.odcgroup.tsl.wui.search.form.SearchFormHelper.getParentWidgetValue1Id(objectModel)</xsp:expr>"
								value = "<udp:item column=\"code\"/>"
								target = WUI_main
							}
							Event OnClick (winClose)
							{
								target = self
							}
						}
					}
				}
			}
			--- TableColumn ---
				column-name = name !
				column-type = domain !
				domainAttribute = name !
				id = name
				table-column-width = 6
			{
				--- Icon ---
					toolTips en = "View Instrument Details", fr = "Voir les détails de l\'instrument", de = "Details des Instruments ansehen"
					icon = application_form_magnify
					id = g_5_i
					tid = 35248474850294
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "resource:///administration/instrument/InstrumentQuickView.pageflow"
						target = popup
						code = "<udp:item column=\"code\"/>" ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
				--- Spacer ---
					height = 4
					width = 10
				--- TableColumnItem ---
					item-column = name
					previewValue = value
			}
			--- TableColumn ---
				column-name = extDenomination !
				column-type = domain !
				domainAttribute = extDenomination !
				type = text
				id = extDenomination
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = extDenomination
					previewValue = value
			}
			--- TableColumn ---
				column-name = refCurrExtDenomination !
				column-type = domain !
				domainAttribute = refCurrExtDenomination !
				type = text
				id = refCurrExtDenomination
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = refCurrExtDenomination
					previewValue = value
			}
			--- TableColumn ---
				column-name = extIsinSynC !
				column-type = domain !
				domainAttribute = extIsinSynC !
				type = text
				id = extIsinSynC
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = extIsinSynC
					previewValue = value
			}
			--- TableColumn ---
				column-name = extTelekursSynC !
				column-type = domain !
				domainAttribute = extTelekursSynC !
				type = text
				id = extTelekursSynC
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = extTelekursSynC
					previewValue = value
			}
			--- TableColumn ---
				column-name = endD !
				column-type = domain !
				domainAttribute = endD !
				id = endD
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = endD
					format = date
					previewValue = value
			}
			--- TableColumn ---
				column-name = redempQuoteN !
				column-type = domain !
				domainAttribute = redempQuoteN !
				type = text
				id = redempQuoteN
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = redempQuoteN
					format = decimal.detailed
					previewValue = value
			}
			--- TableColumn ---
				column-name = optionStyleE !
				column-type = domain !
				domainAttribute = optionStyleE !
				type = text
				id = optionStyleE
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = optionStyleE
					item-halign = lead
					previewValue = value
			}
			--- TableColumn ---
				column-name = optionClassE !
				column-type = domain !
				domainAttribute = optionClassE !
				type = text
				id = optionClassE
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = optionClassE
					item-halign = lead
					previewValue = value
			}
			--- TableColumn ---
				column-name = marketThirdExtDenomination !
				column-type = domain !
				domainAttribute = marketThirdExtDenomination !
				type = text
				id = marketThirdExtDenomination
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = marketThirdExtDenomination
					previewValue = value
			}
			--- TableColumn ---
				column-name = extUnderlyingInstrDenom !
				column-type = domain !
				domainAttribute = extUnderlyingInstrDenom !
				type = text
				id = extUnderlyingInstrDenom
				table-column-width = 6
			{
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "<udp:item column=\"underlyingInstrCode\"/>!=null"
						technicalName = Underlying
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips en = "View Instrument Details", fr = "Voir les détails de l\'instrument", de = "Details des Instruments ansehen"
							icon = application_form_magnify
							id = a_2Wm
							tid = 119210574158737
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "resource:///administration/instrument/InstrumentQuickView.pageflow"
								target = popup
								code = "<udp:item column=\"underlyingInstrCode\"/>" ud
								modal = false
								only-changed = false
								prevalidate = false
							}
						}
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetVisible = false
				}
				--- Spacer ---
					height = 4
					width = 10
				--- TableColumnItem ---
					item-column = extUnderlyingInstrDenom
					previewValue = value
			}
			--- TableColumn ---
				column-name = activeF !
				column-type = domain !
				domainAttribute = activeF !
				type = text
				column-visibility = not-visible
				id = activeF
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = activeF
					previewValue = value
			}
			--- TableColumn ---
				labels de = Status, fr = Statut
				column-name = statusE !
				column-type = domain !
				domainAttribute = statusE !
				type = text
				column-visibility = not-visible
				id = statusE
				table-column-width = 6
				tid = 1603685074442380
			{
				--- TableColumnItem ---
					item-column = statusE
					previewValue = value
			}
			--- TableColumn ---
				column-name = extBestDispCode !
				column-type = domain !
				domainAttribute = extBestDispCode !
				type = text
				column-visibility = not-visible
				id = extBestDispCode
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = extBestDispCode
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = name
				sort-rank = 1
			--- TableSort ---
				sort-column-name = optionClassE
				sort-rank = 2
			--- TableSort ---
				sort-column-name = redempQuoteN
				sort-rank = 8
			--- TableSort ---
				sort-column-name = endD
				sort-rank = 10
			--- TableExtra ---
				domainAttribute = underlyingInstrCode
			--- TableSort ---
				sort-column-name = extUnderlyingInstrDenom
				sort-rank = 7
		}
	}
}