# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Search Results", fr = "Résultats de la recherche", de = Suchergebnisse
	domainEntity = "AAADSInstrument:InstrumentList"
	search = output !
	bean-define = DSBean.AAADSInstrument.InstrumentList
	bean-name = InstrumentList
	id = InstrumentListRate_B_L_e
	tid = 117187023840375
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			table-page-size = 15
			id = pe79_
			table-model-reference = DSTableModel.AAADSInstrument.InstrumentList
			table-column-count = 10 !
			table-columns-width = "10,10,10,10,10,10,10,10,10,10" !
		{
			--- TableColumn ---
				labels de = Code
				column-name = code !
				column-type = domain !
				domainAttribute = code !
				column-locked = true
				id = code
				table-column-width = 10
				tid = 19724297268228
			{
				--- Conditional ---
					indexOfSelectedChild = 1
				{
					--- ConditionalBody ---
						javaCode = "com.odcgroup.tsl.wui.search.form.SearchFormHelper.isLookup(objectModel) == false"
						technicalName = NotLookup
						boxType = vertical
						isWidgetVisible = false
					{
						--- TableColumnItem ---
							toolTips en = "Select Instrument", fr = "Sélectionner l\'instrument", de = "Instrument auswählen"
							item-column = code
							previewValue = value
							tid = 117187024324366
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = select ud
								Query.beanValue1 = "<udp:item column=\"code\"/>" ud
								modal = false
								only-changed = false
								prevalidate = false
								Snippet FilterSet
								id = fs_PYk
							}
						}
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetSelected = true
					{
						--- TableColumnItem ---
							toolTips en = "Select Instrument", fr = "Sélectionner l\'instrument", de = "Instrument auswählen"
							item-column = code
							previewValue = value
							tid = 117187026260407
						{
							Event OnClick (setWidgetValue)
							{
								widget-group-id = "<xsp:expr>com.odcgroup.tsl.wui.search.form.SearchFormHelper.getParentWidgetValue1Id(objectModel)</xsp:expr>"
								value = "<udp:item column=\"code\"/>"
								target = WUI_main
							}
							Event OnClick (winClose)
							{
								target = self
							}
						}
					}
				}
			}
			--- TableColumn ---
				column-name = name !
				column-type = domain !
				domainAttribute = name !
				id = name
				table-column-width = 10
			{
				--- Icon ---
					toolTips en = "View Instrument Details", fr = "Voir les détails de l\'instrument", de = "Details des Instruments ansehen"
					icon = application_form_magnify
					id = z1_8w
					tid = 117187028222309
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "resource:///administration/instrument/InstrumentQuickView.pageflow"
						target = popup
						code = "<udp:item column=\"code\"/>" ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
				--- Spacer ---
					height = 4
					width = 10
				--- TableColumnItem ---
					item-column = name
					previewValue = value
			}
			--- TableColumn ---
				column-name = extDenomination !
				column-type = domain !
				domainAttribute = extDenomination !
				type = text
				id = extDenomination
				table-column-width = 10
			{
				--- TableColumnItem ---
					item-column = extDenomination
					previewValue = value
			}
			--- TableColumn ---
				column-name = refCurrExtDenomination !
				column-type = domain !
				domainAttribute = refCurrExtDenomination !
				type = text
				id = refCurrExtDenomination
				table-column-width = 10
			{
				--- TableColumnItem ---
					item-column = refCurrExtDenomination
					previewValue = value
			}
			--- TableColumn ---
				column-name = extIsinSynC !
				column-type = domain !
				domainAttribute = extIsinSynC !
				type = text
				id = extIsinSynC
				table-column-width = 10
			{
				--- TableColumnItem ---
					item-column = extIsinSynC
					previewValue = value
			}
			--- TableColumn ---
				column-name = extTelekursSynC !
				column-type = domain !
				domainAttribute = extTelekursSynC !
				type = text
				id = extTelekursSynC
				table-column-width = 10
			{
				--- TableColumnItem ---
					item-column = extTelekursSynC
					previewValue = value
			}
			--- TableColumn ---
				column-name = interestRateP !
				column-type = domain !
				domainAttribute = interestRateP !
				type = text
				id = interestRateP
				table-column-width = 10
			{
				--- TableColumnItem ---
					item-column = interestRateP
					format = percentTA.4-digits
					previewValue = value
			}
			--- TableColumn ---
				column-name = activeF !
				column-type = domain !
				domainAttribute = activeF !
				type = text
				column-visibility = not-visible
				id = activeF
				table-column-width = 10
			{
				--- TableColumnItem ---
					item-column = activeF
					previewValue = value
			}
			--- TableColumn ---
				labels de = Status, fr = Statut
				column-name = statusE !
				column-type = domain !
				domainAttribute = statusE !
				type = text
				column-visibility = not-visible
				id = statusE
				table-column-width = 10
				tid = 117187037974963
			{
				--- TableColumnItem ---
					item-column = statusE
					previewValue = value
			}
			--- TableColumn ---
				column-name = extBestDispCode !
				column-type = domain !
				domainAttribute = extBestDispCode !
				type = text
				column-visibility = not-visible
				id = extBestDispCode
				table-column-width = 10
			{
				--- TableColumnItem ---
					item-column = extBestDispCode
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = name
				sort-rank = 2
			--- TableExtra ---
				domainAttribute = underlyingInstrCode
		}
	}
}