# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Search Instrument", fr = "Recherche d\'instrument", de = "Instrument Suche"
	containment = container
	search = container !
	cssClass = nodeco
	id = InstrumentSearch_z_h01
	documentation = "This module is used to search instruments for a general usage. For example, it can be used as context (domain) parameter."
	tid = 272232199126959
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TabbedPane ---
			id = instrumentTabView
			indexOfSelectedChild = 0
		{
			--- Tab ---
				labels en = All, fr = Tous, de = Alle
				tab-name = all
				id = tab_all
				documentation = "This tab is used to search active and inactive instruments of all natures:"
				isWidgetSelected = true
				tid = 5571933532641
			{
				Event OnClick (setTabActive) Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = changeTab ud
					modal = false
					only-changed = false
					prevalidate = false
					Snippet Query
					queryAttributes = "marketThirdSearchCode,issuerThirdSearchCode,extDenomination,searchCode,statusE,extSectorC,riskGeoSearchCode,maturityDate,code,underlyingInstrSearchCode,refCurrSearchCode,natureE,extTelekursSynC,extIsinSynC,name,interestRateP"
					queryOutputModule = "" !
					resource:///Default/module/aaa/administration/instrument/search/InstrumentSearch.module
					Snippet FilterSet
					id = fs_tKT
					level = 2
					targetDataset = "AAADSInstrument:InstrumentSearchCriteriaAll"
					{
						Snippet Filter
						attribute = natureE
						editMode = editable
						filterValue = "Future,CashAccount,Commodity,Option,MoneyMarket,Stock,Forward,ConvertibleBond,ExoticOption,FixedIncome,FundShare,OptionBond,DiscountInstrument"
						operator = IN
					}
				}
				--- Box ---
					boxType = vertical
					width = 0
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/instrument/search/InstrumentSearchInput.module
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/instrument/search/InstrumentListAll.module
				}
			}
			--- Tab ---
				labels en = Stock, fr = Action, de = Aktie
				tab-name = stock
				id = tab_p___7
				documentation = "This tab is used to search the instruments with the following natures:\r\n\r\n- Stock == 1\r\n\r\nBy default, a critierion to search active instrument is defined. But the user has the possibility to remove it or change its value."
				isWidgetVisible = false
				tid = 5571933727671
			{
				Event OnClick (setTabActive) Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = changeTab ud
					modal = false
					only-changed = false
					prevalidate = false
					Snippet Query
					queryAttributes = "marketThirdSearchCode,issuerThirdSearchCode,extDenomination,searchCode,extSectorC,extTelekursSynC,statusE,extIsinSynC,name,riskGeoSearchCode,code,refCurrSearchCode"
					queryOutputModule = "" !
					resource:///Default/module/aaa/administration/instrument/search/InstrumentSearch.module
					Snippet FilterSet
					id = fs_Maz
					level = 2
					targetDataset = "AAADSInstrument:InstrumentSearchCriteriaAll"
					{
						Snippet Filter
						attribute = natureE
						filterValue = Stock
						operator = EQUAL
					}
				}
				--- Box ---
					boxType = vertical
					width = 0
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/instrument/search/InstrumentSearchInput.module
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/instrument/search/InstrumentListStock.module
				}
			}
			--- Tab ---
				labels en = "Fixed Income", fr = "Revenu fixe", de = Anleihe
				tab-name = bond
				id = tab_U__49
				documentation = "This tab is used to search the instruments with the following natures:\r\n\r\n- Fixed income == 2\r\n- Discount instrument == 11\r\n- Option bond == 18\r\n- Convertible bond == 19\r\n\r\nBy default, a critierion to search active instrument is defined. But the user has the possibility to remove it or change its value."
				isWidgetVisible = false
				tid = 5571957637893
			{
				Event OnClick (setTabActive) Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = changeTab ud
					Query.fs_KvE.f3.attribute = maturityDate ud
					Query.fs_KvE.f3.op = GREATER_THAN ud
					Query.fs_KvE.f3.value1 = "$TODAY" ud
					modal = false
					only-changed = false
					prevalidate = false
					Snippet Query
					queryAttributes = "marketThirdSearchCode,issuerThirdSearchCode,extDenomination,searchCode,statusE,extSectorC,riskGeoSearchCode,maturityDate,code,refCurrSearchCode,extRatingC,extTelekursSynC,extIsinSynC,name,interestRateP"
					queryOutputModule = "" !
					resource:///Default/module/aaa/administration/instrument/search/InstrumentSearch.module
					Snippet FilterSet
					id = fs_KvE
					level = 2
					targetDataset = "AAADSInstrument:InstrumentSearchCriteriaAll"
					{
						Snippet Filter
						attribute = natureE
						filterValue = "ConvertibleBond,FixedIncome,DiscountInstrument,OptionBond"
						operator = IN
					}
				}
				--- Box ---
					boxType = vertical
					width = 0
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/instrument/search/InstrumentSearchInput.module
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/instrument/search/InstrumentListBond.module
				}
			}
			--- Tab ---
				labels en = Fund, fr = Fond, de = Fondsanteil
				tab-name = Fund
				id = tab_P3__8
				documentation = "This tab is used to search the instruments with the following natures:\r\n\r\n- Fund share == 13\r\n\r\nBy default, a critierion to search active instrument is defined. But the user has the possibility to remove it or change its value."
				isWidgetVisible = false
				tid = 32887111648268
			{
				Event OnClick (setTabActive) Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = changeTab ud
					Query.fs_Maz.f2.attribute = maturityDate ud
					Query.fs_Maz.f2.op = GREATER_THAN ud
					Query.fs_Maz.f2.value1 = "$TODAY" ud
					modal = false
					only-changed = false
					prevalidate = false
					Snippet Query
					queryAttributes = "marketThirdSearchCode,issuerThirdSearchCode,extDenomination,searchCode,extTelekursSynC,statusE,extIsinSynC,name,maturityDate,code,refCurrSearchCode"
					queryOutputModule = "" !
					resource:///Default/module/aaa/administration/instrument/search/InstrumentSearch.module
					Snippet FilterSet
					id = fs_Maz
					level = 2
					targetDataset = "AAADSInstrument:InstrumentSearchCriteriaAll"
					{
						Snippet Filter
						attribute = natureE
						filterValue = FundShare
						operator = EQUAL
					}
				}
				--- Box ---
					boxType = vertical
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/instrument/search/InstrumentSearchInput.module
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/instrument/search/InstrumentListFundShare.module
				}
			}
			--- Tab ---
				labels en = Future, fr = Future, de = Future
				tab-name = futures
				id = tab_Z28X0
				documentation = "This tab is used to search the instruments with the following natures:\r\n\r\n- Future == 6\r\n\r\nBy default, a critierion to search active instrument is defined. But the user has the possibility to remove it or change its value."
				isWidgetVisible = false
				tid = 5571958010007
			{
				Event OnClick (setTabActive) Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = changeTab ud
					Query.fs_9q6.f2.attribute = maturityDate ud
					Query.fs_9q6.f2.op = GREATER_THAN ud
					Query.fs_9q6.f2.value1 = "$TODAY" ud
					modal = false
					only-changed = false
					prevalidate = false
					Snippet Query
					queryAttributes = "marketThirdSearchCode,issuerThirdSearchCode,extDenomination,searchCode,statusE,extSectorC,riskGeoSearchCode,redempQuoteN,maturityDate,code,underlyingInstrSearchCode,refCurrSearchCode,extTelekursSynC,extIsinSynC,name"
					queryOutputModule = "" !
					resource:///Default/module/aaa/administration/instrument/search/InstrumentSearch.module
					Snippet FilterSet
					id = fs_9q6
					level = 2
					targetDataset = "AAADSInstrument:InstrumentSearchCriteriaAll"
					{
						Snippet Filter
						attribute = natureE
						filterValue = Future
						operator = EQUAL
					}
				}
				--- Box ---
					boxType = vertical
					width = 0
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/instrument/search/InstrumentSearchInput.module
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/instrument/search/InstrumentListFuture.module
				}
			}
			--- Tab ---
				labels en = Option, fr = Option, de = Option
				tab-name = option
				id = tab_eGb_o
				documentation = "This tab is used to search the instruments with the following natures:\r\n\r\n- Option == 3\r\n- Exotic option == 22\r\n\r\nBy default, a critierion to search active instrument is defined. But the user has the possibility to remove it or change its value."
				isWidgetVisible = false
				tid = 5571957823980
			{
				Event OnClick (setTabActive) Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = changeTab ud
					Query.fs_2fc.f2.attribute = maturityDate ud
					Query.fs_2fc.f2.op = GREATER_THAN ud
					Query.fs_2fc.f2.value1 = "$TODAY" ud
					modal = false
					only-changed = false
					prevalidate = false
					Snippet Query
					queryAttributes = "marketThirdSearchCode,optionClassE,issuerThirdSearchCode,extDenomination,searchCode,statusE,extSectorC,riskGeoSearchCode,redempQuoteN,maturityDate,code,underlyingInstrSearchCode,refCurrSearchCode,optionStyleE,extTelekursSynC,extIsinSynC,name"
					queryOutputModule = "" !
					resource:///Default/module/aaa/administration/instrument/search/InstrumentSearch.module
					Snippet FilterSet
					id = fs_2fc
					level = 2
					targetDataset = "AAADSInstrument:InstrumentSearchCriteriaAll"
					{
						Snippet Filter
						attribute = natureE
						filterValue = "ExoticOption,Option"
						operator = IN
					}
				}
				--- Box ---
					boxType = vertical
					width = 0
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/instrument/search/InstrumentSearchInput.module
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/instrument/search/InstrumentListOption.module
				}
			}
			--- Tab ---
				labels en = "Money Market", fr = "Marché monétaire", de = Geldmarkt
				id = tab_F2eQd
				documentation = "This tab is used to search the instruments with the following natures:\r\n\r\n- Money market == 5\r\n\r\nBy default, a critierion to search active instrument is defined. But the user has the possibility to remove it or change its value."
				isWidgetVisible = false
				tid = 195422002646200
			{
				Event OnClick (setTabActive) Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = changeTab ud
					modal = false
					only-changed = false
					prevalidate = false
					Snippet Query
					queryAttributes = "extDenomination,searchCode,statusE,genericF,name,typeCode,code,refCurrSearchCode"
					queryOutputModule = "" !
					resource:///Default/module/aaa/administration/instrument/search/InstrumentSearch.module
					Snippet FilterSet
					id = fs_hXR
					level = 2
					targetDataset = "AAADSInstrument:InstrumentSearchCriteriaAll"
					{
						Snippet Filter
						attribute = natureE
						filterValue = MoneyMarket
						operator = EQUAL
						Snippet Filter
						attribute = genericF
						editMode = editable
						filterValue = Yes
						operator = EQUAL
					}
				}
				--- Box ---
					boxType = vertical
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/instrument/search/InstrumentSearchInput.module
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/instrument/search/InstrumentListMoneyMarket.module
				}
			}
			--- Tab ---
				labels en = "Cash Account", fr = "Compte de liquidité", de = Kontokorrent
				id = tab_Y3__z
				documentation = "This tab is used to search the instruments with the following natures:\r\n\r\n- Cash account == 4\r\n\r\nBy default, a critierion to search active instrument is defined. But the user has the possibility to remove it or change its value."
				isWidgetVisible = false
				tid = 195429489972974
			{
				Event OnClick (setTabActive) Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = changeTab ud
					modal = false
					only-changed = false
					prevalidate = false
					Snippet Query
					queryAttributes = "extDenomination,searchCode,statusE,name,genericF,code,refCurrSearchCode"
					queryOutputModule = "" !
					resource:///Default/module/aaa/administration/instrument/search/InstrumentSearch.module
					Snippet FilterSet
					id = fs_FTj
					level = 2
					targetDataset = "AAADSInstrument:InstrumentSearchCriteriaAll"
					{
						Snippet Filter
						attribute = natureE
						filterValue = CashAccount
						operator = EQUAL
						Snippet Filter
						attribute = genericF
						editMode = editable
						filterValue = No
						operator = EQUAL
					}
				}
				--- Box ---
					boxType = vertical
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/instrument/search/InstrumentSearchInput.module
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/instrument/search/InstrumentListCashAccount.module
				}
			}
			--- Tab ---
				labels en = Forward, de = Devisenermingeschäft, fr = "Contrat à terme"
				id = tab_Ka67_
				documentation = "This tab is used to search the instruments with the following natures:\r\n\r\n- Forward == 7\r\n\r\nBy default, a critierion to search active instrument is defined. But the user has the possibility to remove it or change its value."
				isWidgetVisible = false
				tid = 195424650203656
			{
				Event OnClick (setTabActive) Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = changeTab ud
					modal = false
					only-changed = false
					prevalidate = false
					Snippet Query
					queryAttributes = "extDenomination,underlyingInstrRefCurrSearchCode,searchCode,statusE,genericF,name,code,refCurrSearchCode"
					queryOutputModule = "" !
					resource:///Default/module/aaa/administration/instrument/search/InstrumentSearch.module
					Snippet FilterSet
					id = fs_GdW
					level = 2
					targetDataset = "AAADSInstrument:InstrumentSearchCriteriaAll"
					{
						Snippet Filter
						attribute = natureE
						filterValue = Forward
						operator = EQUAL
						Snippet Filter
						attribute = genericF
						editMode = editable
						filterValue = Yes
						operator = EQUAL
					}
				}
				--- Box ---
					boxType = vertical
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/instrument/search/InstrumentSearchInput.module
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/instrument/search/InstrumentListForward.module
				}
			}
		}
	}
}