# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Instrument Search Criteria", fr = "Critères de recherche sur instrument", de = "Instrument Suchbegriffe"
	containment = container
	domainEntity = "AAADSInstrument:InstrumentSearchCriteriaAll"
	search = input !
	bean-define = DSBean.AAADSInstrument.InstrumentSearchCriteriaAll
	bean-name = InstrumentSearchCriteriaAll
	id = InstrumentSearchInput_T_h_U
	tid = 9163400823288
{
	--- Box ---
		boxType = vertical
	{
		--- FilterCriteria ---
			includedFile = "resource:/com/module/search/QueryBuilder.xsp"
		--- Include ---
			includeSrc = "" !
			resource:///default/search/NavigationSearch.fragment
	}
}