# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Search Instrument", fr = "Recherche d\'instrument", de = "Instrument Suche"
	containment = container
	search = container !
	cssClass = nodeco
	id = InstrSearch_yfp__
	tid = 115286849161926
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			id = j__w7
			indexOfSelectedChild = 4
		{
			--- Tab ---
				labels en = All, fr = Tous, de = Alle
				id = tab_at683
				isWidgetVisible = false
				tid = 115368751057439
			{
				Event OnClick (setTabActive) Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = changeTab ud
					modal = false
					only-changed = false
					prevalidate = false
					Snippet Query
					queryAttributes = "marketThirdSearchCode,issuerThirdSearchCode,extDenomination,searchCode,statusE,extSectorC,riskGeoSearchCode,maturityDate,code,underlyingInstrSearchCode,refCurrSearchCode,natureE,extTelekursSynC,extIsinSynC,name,interestRateP"
					queryOutputModule = "" !
					resource:///Default/module/aaa/administration/instrument/search/InstrumentSearch.module
					Snippet FilterSet
					id = fs_tKT
					level = 2
					targetDataset = "AAADSInstrument:InstrumentSearchCriteriaAll"
					{
						Snippet Filter
						attribute = natureE
						editMode = editable
						filterValue = "Commodity,Index,FundShare,Rate"
						operator = IN
					}
				}
				--- Box ---
					boxType = vertical
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/instrument/search/InstrumentSearchInput.module
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/instrument/search/InstrumentListAll.module
				}
			}
			--- Tab ---
				labels en = Commodity, fr = "Matière première", de = Rohstoffe
				id = tab_v7T_2
				isWidgetVisible = false
				tid = 115401945477671
			{
				Event OnClick (setTabActive) Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = changeTab ud
					Query.fs_Maz.f2.attribute = maturityDate ud
					Query.fs_Maz.f2.op = GREATER_THAN ud
					Query.fs_Maz.f2.value1 = "$TODAY" ud
					modal = false
					only-changed = false
					prevalidate = false
					Snippet Query
					queryAttributes = "extDenomination,searchCode,extTelekursSynC,statusE,extIsinSynC,name,code"
					queryOutputModule = "" !
					resource:///Default/module/aaa/administration/instrument/search/InstrumentSearch.module
					Snippet FilterSet
					id = fs_Maz
					level = 2
					targetDataset = "AAADSInstrument:InstrumentSearchCriteriaAll"
					{
						Snippet Filter
						attribute = natureE
						filterValue = Commodity
						operator = EQUAL
					}
				}
				--- Box ---
					boxType = vertical
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/instrument/search/InstrumentSearchInput.module
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/instrument/search/InstrumentListCommodity.module
				}
			}
			--- Tab ---
				labels en = Fund, fr = Fond, de = Fondsanteil
				id = tab_Km3t_
				isWidgetVisible = false
				tid = 115418782136744
			{
				Event OnClick (setTabActive) Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = changeTab ud
					Query.fs_Maz.f2.attribute = maturityDate ud
					Query.fs_Maz.f2.op = GREATER_THAN ud
					Query.fs_Maz.f2.value1 = "$TODAY" ud
					modal = false
					only-changed = false
					prevalidate = false
					Snippet Query
					queryAttributes = "marketThirdSearchCode,issuerThirdSearchCode,extDenomination,searchCode,extTelekursSynC,statusE,extIsinSynC,name,maturityDate,code,refCurrSearchCode"
					queryOutputModule = "" !
					resource:///Default/module/aaa/administration/instrument/search/InstrumentSearch.module
					Snippet FilterSet
					id = fs_Maz
					level = 2
					targetDataset = "AAADSInstrument:InstrumentSearchCriteriaAll"
					{
						Snippet Filter
						attribute = natureE
						filterValue = FundShare
						operator = EQUAL
					}
				}
				--- Box ---
					boxType = vertical
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/instrument/search/InstrumentSearchInput.module
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/instrument/search/InstrumentListFundShare.module
				}
			}
			--- Tab ---
				labels en = Index, fr = Indice, de = Index
				id = tab_Vj65i
				isWidgetVisible = false
				tid = 115438968886757
			{
				Event OnClick (setTabActive) Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = changeTab ud
					Query.fs_Maz.f2.attribute = maturityDate ud
					Query.fs_Maz.f2.op = GREATER_THAN ud
					Query.fs_Maz.f2.value1 = "$TODAY" ud
					modal = false
					only-changed = false
					prevalidate = false
					Snippet Query
					queryAttributes = "marketThirdSearchCode,extDenomination,searchCode,extTelekursSynC,statusE,extIsinSynC,name,code,refCurrSearchCode"
					queryOutputModule = "" !
					resource:///Default/module/aaa/administration/instrument/search/InstrumentSearch.module
					Snippet FilterSet
					id = fs_Maz
					level = 2
					targetDataset = "AAADSInstrument:InstrumentSearchCriteriaAll"
					{
						Snippet Filter
						attribute = natureE
						filterValue = Index
						operator = EQUAL
					}
				}
				--- Box ---
					boxType = vertical
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/instrument/search/InstrumentSearchInput.module
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/instrument/search/InstrumentListIndex.module
				}
			}
			--- Tab ---
				labels en = Rate, fr = Taux, de = Zinsinstrument
				id = tab_b_k__
				isWidgetSelected = true
				tid = 115447960631882
			{
				Event OnClick (setTabActive) Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = changeTab ud
					modal = false
					only-changed = false
					prevalidate = false
					Snippet Query
					queryAttributes = "extDenomination,searchCode,extTelekursSynC,statusE,extIsinSynC,name,interestRateP,code,refCurrSearchCode"
					queryOutputModule = "" !
					resource:///Default/module/aaa/administration/instrument/search/InstrumentSearch.module
					Snippet FilterSet
					id = fs_Maz
					level = 2
					targetDataset = "AAADSInstrument:InstrumentSearchCriteriaAll"
					{
						Snippet Filter
						attribute = natureE
						filterValue = Rate
						operator = EQUAL
					}
				}
				--- Box ---
					boxType = vertical
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/instrument/search/InstrumentSearchInput.module
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/instrument/search/InstrumentListRate.module
				}
			}
		}
	}
}