# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Search Results", fr = "Résultats de la recherche", de = Suchergebnisse
	domainEntity = "AAADSInstrument:InstrumentList"
	search = output !
	bean-define = DSBean.AAADSInstrument.InstrumentList
	bean-name = InstrumentList
	id = InstrumentListFuture_R7z74
	tid = 375999100813727
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			table-page-size = 15
			id = cA3Dy
			table-model-reference = DSTableModel.AAADSInstrument.InstrumentList
			table-column-count = 13 !
			table-columns-width = "7,7,7,7,7,7,7,7,7,7,7,7,7" !
		{
			--- TableColumn ---
				labels de = Code
				column-name = code !
				column-type = domain !
				domainAttribute = code !
				column-locked = true
				id = n4gQm
				table-column-width = 7
				tid = 20001105281816
			{
				--- Conditional ---
					indexOfSelectedChild = 1
				{
					--- ConditionalBody ---
						javaCode = "com.odcgroup.tsl.wui.search.form.SearchFormHelper.isLookup(objectModel) == false"
						technicalName = NotLookup
						boxType = vertical
						isWidgetVisible = false
					{
						--- TableColumnItem ---
							toolTips en = "Select Instrument", fr = "Sélectionner l\'instrument", de = "Instrument auswählen"
							item-column = code
							previewValue = value
							tid = 34137894424295
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = select ud
								Query.beanValue1 = "<udp:item column=\"code\"/>" ud
								modal = false
								only-changed = false
								prevalidate = false
								Snippet FilterSet
								id = fs_PYk
							}
						}
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetSelected = true
					{
						--- TableColumnItem ---
							toolTips en = "Select Instrument", fr = "Sélectionner l\'instrument", de = "Instrument auswählen"
							item-column = code
							previewValue = value
							tid = 121219084102570
						{
							Event OnClick (setWidgetValue)
							{
								widget-group-id = "<xsp:expr>com.odcgroup.tsl.wui.search.form.SearchFormHelper.getParentWidgetValue1Id(objectModel)</xsp:expr>"
								value = "<udp:item column=\"code\"/>"
								target = WUI_main
							}
							Event OnClick (winClose)
							{
								target = self
							}
						}
					}
				}
			}
			--- TableColumn ---
				column-name = name !
				column-type = domain !
				domainAttribute = name !
				id = Q93VK
				table-column-width = 7
			{
				--- Icon ---
					toolTips en = "View Instrument Details", fr = "Voir les détails de l\'instrument", de = "Details des Instruments ansehen"
					icon = application_form_magnify
					id = O__76
					tid = 34991013619704
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "resource:///administration/instrument/InstrumentQuickView.pageflow"
						target = popup
						code = "<udp:item column=\"code\"/>" ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
				--- Spacer ---
					height = 4
					width = 10
				--- TableColumnItem ---
					item-column = name
					previewValue = value
			}
			--- TableColumn ---
				column-name = extDenomination !
				column-type = domain !
				domainAttribute = extDenomination !
				type = text
				id = extDenomination
				table-column-width = 7
			{
				--- TableColumnItem ---
					item-column = extDenomination
					previewValue = value
			}
			--- TableColumn ---
				column-name = refCurrExtDenomination !
				column-type = domain !
				domainAttribute = refCurrExtDenomination !
				type = text
				id = refCurrExtDenomination
				table-column-width = 7
			{
				--- TableColumnItem ---
					item-column = refCurrExtDenomination
					previewValue = value
			}
			--- TableColumn ---
				column-name = extIsinSynC !
				column-type = domain !
				domainAttribute = extIsinSynC !
				type = text
				id = G7_3_
				table-column-width = 7
			{
				--- TableColumnItem ---
					item-column = extIsinSynC
					previewValue = value
			}
			--- TableColumn ---
				column-name = extTelekursSynC !
				column-type = domain !
				domainAttribute = extTelekursSynC !
				type = text
				id = ffD1U
				table-column-width = 7
			{
				--- TableColumnItem ---
					item-column = extTelekursSynC
					previewValue = value
			}
			--- TableColumn ---
				column-name = endD !
				column-type = domain !
				domainAttribute = endD !
				type = text
				id = t39N_
				table-column-width = 7
			{
				--- TableColumnItem ---
					item-column = endD
					format = date
					previewValue = value
			}
			--- TableColumn ---
				column-name = redempQuoteN !
				column-type = domain !
				domainAttribute = redempQuoteN !
				type = text
				id = O_370
				table-column-width = 7
			{
				--- TableColumnItem ---
					item-column = redempQuoteN
					format = decimal.detailed
					previewValue = value
			}
			--- TableColumn ---
				column-name = marketThirdExtDenomination !
				column-type = domain !
				domainAttribute = marketThirdExtDenomination !
				type = text
				id = marketThirdExtDenomination
				table-column-width = 7
			{
				--- TableColumnItem ---
					item-column = marketThirdExtDenomination
					previewValue = value
			}
			--- TableColumn ---
				column-name = extUnderlyingInstrDenom !
				column-type = domain !
				domainAttribute = extUnderlyingInstrDenom !
				type = text
				id = extUnderlyingInstrDenom
				table-column-width = 7
			{
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "<udp:item column=\"underlyingInstrCode\"/>!=null"
						technicalName = Underlying
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips en = "View Instrument Details", fr = "Voir les détails de l\'instrument", de = "Details des Instruments ansehen"
							icon = application_form_magnify
							id = k__EG
							tid = 119044994157282
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "resource:///administration/instrument/InstrumentQuickView.pageflow"
								target = popup
								code = "<udp:item column=\"underlyingInstrCode\"/>" ud
								modal = false
								only-changed = false
								prevalidate = false
							}
						}
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetVisible = false
				}
				--- Spacer ---
					height = 4
					width = 10
				--- TableColumnItem ---
					item-column = extUnderlyingInstrDenom
					previewValue = value
			}
			--- TableColumn ---
				column-name = activeF !
				column-type = domain !
				domainAttribute = activeF !
				type = text
				column-visibility = not-visible
				id = activeF
				table-column-width = 7
			{
				--- TableColumnItem ---
					item-column = activeF
					previewValue = value
			}
			--- TableColumn ---
				column-name = statusE !
				column-type = domain !
				domainAttribute = statusE !
				type = text
				column-visibility = not-visible
				id = statusE
				table-column-width = 7
			{
				--- TableColumnItem ---
					item-column = statusE
					previewValue = value
			}
			--- TableColumn ---
				column-name = extBestDispCode !
				column-type = domain !
				domainAttribute = extBestDispCode !
				type = text
				column-visibility = not-visible
				id = UX3k8
				table-column-width = 7
			{
				--- TableColumnItem ---
					item-column = extBestDispCode
					previewValue = value
			}
			--- TableExtra ---
				domainAttribute = underlyingInstrCode
			--- TableSort ---
				sort-column-name = name
				sort-rank = 2
		}
	}
}