# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Search Instrument", fr = "Recherche d\'instrument", de = "Instrument Suche"
	containment = container
	search = container !
	cssClass = nodeco
	id = InstrumentSearch_z_h01
	documentation = "This module is used to search instruments for ordering"
	tid = 5571933336442
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TabbedPane ---
			id = instrumentTabView
			indexOfSelectedChild = 5
		{
			--- Tab ---
				labels en = All, fr = Tous, de = Alle
				tab-name = all
				id = tab_xD___
				documentation = "This tab is used to search active and inactive instruments with the following natures:\r\n\r\n- Stock == 1\r\n- Fixed income == 2\r\n- Option == 3\r\n- Future == 6\r\n- Discount instrument == 11\r\n- Fund share == 13\r\n- Option bond == 18\r\n- Convertible bond == 19\r\n- Exotic option == 22"
				isWidgetVisible = false
				tid = 272250098514681
			{
				Event OnClick (setTabActive) Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = changeTab ud
					modal = false
					only-changed = false
					prevalidate = false
					Snippet Query
					queryAttributes = "marketThirdSearchCode,issuerThirdSearchCode,extDenomination,searchCode,statusE,extSectorC,riskGeoSearchCode,maturityDate,code,underlyingInstrSearchCode,refCurrSearchCode,natureE,extTelekursSynC,extIsinSynC,name,interestRateP"
					queryOutputModule = "" !
					resource:///Default/module/aaa/administration/instrument/search/SecuritySearch.module
					{
						Snippet QueryTabDisplay
						selectedTab = tab_xD___
					}
					Snippet FilterSet
					id = fs_r0z
					level = 2
					targetDataset = "AAADSInstrument:InstrumentSearchCriteriaAll"
					{
						Snippet Filter
						attribute = natureE
						filterValue = "Future,ConvertibleBond,ExoticOption,Option,FixedIncome,FundShare,OptionBond,DiscountInstrument,Stock"
						operator = IN
					}
				}
				--- Box ---
					boxType = vertical
					width = 0
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/instrument/search/InstrumentSearchInput.module
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/instrument/search/InstrumentListAll.module
				}
			}
			--- Tab ---
				labels en = Stock, fr = Action, de = Aktie
				tab-name = stock
				id = tab_p___7
				documentation = "This tab is used to search the instruments with the following natures:\r\n\r\n- Stock == 1\r\n\r\nBy default, a critierion to search active instrument is defined. But the user has the possibility to remove it or change its value."
				isWidgetVisible = false
				tid = 272264347451809
			{
				Event OnClick (setTabActive) Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = changeTab ud
					modal = false
					only-changed = false
					prevalidate = false
					Snippet Query
					queryAttributes = "marketThirdSearchCode,issuerThirdSearchCode,extDenomination,searchCode,statusE,extSectorC,riskGeoSearchCode,code,refCurrSearchCode,extTelekursSynC,extIsinSynC,name"
					queryOutputModule = "" !
					resource:///Default/module/aaa/administration/instrument/search/SecuritySearch.module
					Snippet FilterSet
					id = fs_a61
					level = 2
					targetDataset = "AAADSInstrument:InstrumentSearchCriteriaAll"
					{
						Snippet Filter
						attribute = natureE
						filterValue = Stock
						operator = EQUAL
					}
				}
				--- Box ---
					boxType = vertical
					width = 0
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/instrument/search/InstrumentSearchInput.module
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/instrument/search/InstrumentListStock.module
				}
			}
			--- Tab ---
				labels en = "Fixed Income", fr = "Revenu fixe", de = Anleihe
				tab-name = bond
				id = tab_U__49
				documentation = "This tab is used to search the instruments with the following natures:\r\n\r\n- Fixed income == 2\r\n- Discount instrument == 11\r\n- Option bond == 18\r\n- Convertible bond == 19\r\n\r\nBy default, a critierion to search active instrument is defined. But the user has the possibility to remove it or change its value."
				isWidgetVisible = false
				tid = 447708793444138
			{
				Event OnClick (setTabActive) Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = changeTab ud
					Query.fs_IOX.f10.attribute = endD ud
					Query.fs_IOX.f10.op = GREATER_THAN ud
					Query.fs_IOX.f10.value1 = "$TODAY" ud
					Query.fs_IOX.f10.mode = READONLY ud
					modal = false
					only-changed = false
					prevalidate = false
					Snippet Query
					queryAttributes = "marketThirdSearchCode,issuerThirdSearchCode,extDenomination,searchCode,statusE,extSectorC,riskGeoSearchCode,code,refCurrSearchCode,extTelekursSynC,extRatingC,extIsinSynC,name,interestRateP"
					queryOutputModule = "" !
					resource:///Default/module/aaa/administration/instrument/search/SecuritySearch.module
					Snippet FilterSet
					id = fs_IOX
					level = 2
					targetDataset = "AAADSInstrument:InstrumentSearchCriteriaAll"
					{
						Snippet Filter
						attribute = natureE
						filterValue = "ConvertibleBond,FixedIncome,OptionBond,DiscountInstrument"
						operator = IN
					}
				}
				--- Box ---
					boxType = vertical
					width = 0
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/instrument/search/InstrumentSearchInput.module
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/instrument/search/InstrumentListBond.module
				}
			}
			--- Tab ---
				labels en = Fund, fr = Fond, de = Fondsanteil
				tab-name = FundShare
				id = tab_c12pl
				documentation = "This tab is used to search the instruments with the following natures:\r\n\r\n- Fund share == 13\r\n\r\nBy default, a critierion to search active instrument is defined. But the user has the possibility to remove it or change its value."
				isWidgetVisible = false
				tid = 97802021793218
			{
				Event OnClick (setTabActive) Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = changeTab ud
					Query.fs_cSn.f2.attribute = endD ud
					Query.fs_cSn.f2.op = GREATER_THAN ud
					Query.fs_cSn.f2.value1 = "$TODAY" ud
					Query.fs_cSn.f2.mode = READONLY ud
					modal = false
					only-changed = false
					prevalidate = false
					Snippet Query
					queryAttributes = "marketThirdSearchCode,issuerThirdSearchCode,extDenomination,searchCode,extTelekursSynC,statusE,extIsinSynC,name,code,refCurrSearchCode"
					queryOutputModule = "" !
					resource:///Default/module/aaa/administration/instrument/search/SecuritySearch.module
					Snippet FilterSet
					id = fs_cSn
					level = 2
					targetDataset = "AAADSInstrument:InstrumentSearchCriteriaAll"
					{
						Snippet Filter
						attribute = natureE
						filterValue = FundShare
						operator = EQUAL
					}
				}
				--- Box ---
					boxType = vertical
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/instrument/search/InstrumentSearchInput.module
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/instrument/search/InstrumentListFundShare.module
				}
			}
			--- Tab ---
				labels en = Future, fr = Future, de = Future
				tab-name = future
				id = tab_Z28X0
				documentation = "This tab is used to search the instruments with the following natures:\r\n\r\n- Future == 6\r\n\r\nBy default, a critierion to search active instrument is defined. But the user has the possibility to remove it or change its value."
				isWidgetVisible = false
				tid = 447746983571655
			{
				Event OnClick (setTabActive) Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = changeTab ud
					Query.fs_cSn.f10.attribute = endD ud
					Query.fs_cSn.f10.op = GREATER_THAN ud
					Query.fs_cSn.f10.value1 = "$TODAY" ud
					Query.fs_cSn.f10.mode = READONLY ud
					modal = false
					only-changed = false
					prevalidate = false
					Snippet Query
					queryAttributes = "marketThirdSearchCode,issuerThirdSearchCode,extDenomination,searchCode,statusE,extSectorC,riskGeoSearchCode,redempQuoteN,code,underlyingInstrSearchCode,refCurrSearchCode,extTelekursSynC,extIsinSynC,name"
					queryOutputModule = "" !
					resource:///Default/module/aaa/administration/instrument/search/SecuritySearch.module
					Snippet FilterSet
					id = fs_cSn
					level = 2
					targetDataset = "AAADSInstrument:InstrumentSearchCriteriaAll"
					{
						Snippet Filter
						attribute = natureE
						filterValue = Future
						operator = EQUAL
					}
				}
				--- Box ---
					boxType = vertical
					width = 0
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/instrument/search/InstrumentSearchInput.module
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/instrument/search/InstrumentListFuture.module
				}
			}
			--- Tab ---
				labels en = Option, fr = Option, de = Option
				tab-name = option
				id = tab_eGb_o
				documentation = "This tab is used to search the instruments with the following natures:\r\n\r\n- Option == 3\r\n- Exotic option == 22\r\n\r\nBy default, a critierion to search active instrument is defined. But the user has the possibility to remove it or change its value."
				isWidgetSelected = true
				tid = 447732779309660
			{
				Event OnClick (setTabActive) Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = changeTab ud
					Query.fs_pEq.fs10.attribute = endD ud
					Query.fs_pEq.fs10.op = GREATER_THAN ud
					Query.fs_pEq.fs10.value1 = "$TODAY" ud
					Query.fs_pEq.fs10.mode = READONLY ud
					modal = false
					only-changed = false
					prevalidate = false
					Snippet Query
					queryAttributes = "marketThirdSearchCode,optionClassE,issuerThirdSearchCode,extDenomination,searchCode,statusE,extSectorC,riskGeoSearchCode,redempQuoteN,code,underlyingInstrSearchCode,refCurrSearchCode,optionStyleE,extTelekursSynC,extIsinSynC,name"
					queryOutputModule = "" !
					resource:///Default/module/aaa/administration/instrument/search/SecuritySearch.module
					Snippet FilterSet
					id = fs_pEq
					level = 2
					targetDataset = "AAADSInstrument:InstrumentSearchCriteriaAll"
					{
						Snippet Filter
						attribute = natureE
						filterValue = "ExoticOption,Option"
						operator = IN
					}
				}
				--- Box ---
					boxType = vertical
					width = 0
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/instrument/search/InstrumentSearchInput.module
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/instrument/search/InstrumentListOption.module
				}
			}
		}
	}
}