/*
* generated by Xtext
*/
package com.odcgroup.page.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import com.odcgroup.page.services.PageGrammarAccess;

public class PageParser extends AbstractContentAssistParser {
	
	@Inject
	private PageGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected com.odcgroup.page.ui.contentassist.antlr.internal.InternalPageParser createParser() {
		com.odcgroup.page.ui.contentassist.antlr.internal.InternalPageParser result = new com.odcgroup.page.ui.contentassist.antlr.internal.InternalPageParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getString_ValueAccess().getAlternatives(), "rule__String_Value__Alternatives");
					put(grammarAccess.getEventNatureAccess().getAlternatives(), "rule__EventNature__Alternatives");
					put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
					put(grammarAccess.getWidgetAccess().getGroup(), "rule__Widget__Group__0");
					put(grammarAccess.getWidgetAccess().getGroup_2(), "rule__Widget__Group_2__0");
					put(grammarAccess.getWidgetAccess().getGroup_5(), "rule__Widget__Group_5__0");
					put(grammarAccess.getWidgetAccess().getGroup_5_2(), "rule__Widget__Group_5_2__0");
					put(grammarAccess.getWidgetAccess().getGroup_6(), "rule__Widget__Group_6__0");
					put(grammarAccess.getWidgetAccess().getGroup_6_2(), "rule__Widget__Group_6_2__0");
					put(grammarAccess.getWidgetAccess().getGroup_8(), "rule__Widget__Group_8__0");
					put(grammarAccess.getWidgetAccess().getGroup_8_1(), "rule__Widget__Group_8_1__0");
					put(grammarAccess.getWidgetAccess().getGroup_8_2(), "rule__Widget__Group_8_2__0");
					put(grammarAccess.getWidgetAccess().getGroup_8_3(), "rule__Widget__Group_8_3__0");
					put(grammarAccess.getPropertyAccess().getGroup(), "rule__Property__Group__0");
					put(grammarAccess.getPropertyAccess().getGroup_1(), "rule__Property__Group_1__0");
					put(grammarAccess.getPropertyAccess().getGroup_6(), "rule__Property__Group_6__0");
					put(grammarAccess.getEventAccess().getGroup(), "rule__Event__Group__0");
					put(grammarAccess.getEventAccess().getGroup_6(), "rule__Event__Group_6__0");
					put(grammarAccess.getEventAccess().getGroup_8(), "rule__Event__Group_8__0");
					put(grammarAccess.getEventAccess().getGroup_8_2(), "rule__Event__Group_8_2__0");
					put(grammarAccess.getEventAccess().getGroup_9(), "rule__Event__Group_9__0");
					put(grammarAccess.getEventAccess().getGroup_9_1(), "rule__Event__Group_9_1__0");
					put(grammarAccess.getEventAccess().getGroup_9_2(), "rule__Event__Group_9_2__0");
					put(grammarAccess.getSnippetAccess().getGroup(), "rule__Snippet__Group__0");
					put(grammarAccess.getSnippetAccess().getGroup_4(), "rule__Snippet__Group_4__0");
					put(grammarAccess.getSnippetAccess().getGroup_4_1(), "rule__Snippet__Group_4_1__0");
					put(grammarAccess.getTranslationAccess().getGroup(), "rule__Translation__Group__0");
					put(grammarAccess.getParameterAccess().getGroup(), "rule__Parameter__Group__0");
					put(grammarAccess.getModelAccess().getMetamodelVersionAssignment_3(), "rule__Model__MetamodelVersionAssignment_3");
					put(grammarAccess.getModelAccess().getWidgetAssignment_4(), "rule__Model__WidgetAssignment_4");
					put(grammarAccess.getWidgetAccess().getLibraryNameAssignment_2_0(), "rule__Widget__LibraryNameAssignment_2_0");
					put(grammarAccess.getWidgetAccess().getTypeNameAssignment_3(), "rule__Widget__TypeNameAssignment_3");
					put(grammarAccess.getWidgetAccess().getLabelsAssignment_5_1(), "rule__Widget__LabelsAssignment_5_1");
					put(grammarAccess.getWidgetAccess().getLabelsAssignment_5_2_1(), "rule__Widget__LabelsAssignment_5_2_1");
					put(grammarAccess.getWidgetAccess().getToolTipsAssignment_6_1(), "rule__Widget__ToolTipsAssignment_6_1");
					put(grammarAccess.getWidgetAccess().getToolTipsAssignment_6_2_1(), "rule__Widget__ToolTipsAssignment_6_2_1");
					put(grammarAccess.getWidgetAccess().getPropertiesAssignment_7(), "rule__Widget__PropertiesAssignment_7");
					put(grammarAccess.getWidgetAccess().getEventsAssignment_8_1_0(), "rule__Widget__EventsAssignment_8_1_0");
					put(grammarAccess.getWidgetAccess().getEventsAssignment_8_1_1(), "rule__Widget__EventsAssignment_8_1_1");
					put(grammarAccess.getWidgetAccess().getSnippetsAssignment_8_2_0(), "rule__Widget__SnippetsAssignment_8_2_0");
					put(grammarAccess.getWidgetAccess().getSnippetsAssignment_8_2_1(), "rule__Widget__SnippetsAssignment_8_2_1");
					put(grammarAccess.getWidgetAccess().getContentsAssignment_8_3_0(), "rule__Widget__ContentsAssignment_8_3_0");
					put(grammarAccess.getWidgetAccess().getContentsAssignment_8_3_1(), "rule__Widget__ContentsAssignment_8_3_1");
					put(grammarAccess.getPropertyAccess().getLibraryNameAssignment_1_0(), "rule__Property__LibraryNameAssignment_1_0");
					put(grammarAccess.getPropertyAccess().getTypeNameAssignment_2(), "rule__Property__TypeNameAssignment_2");
					put(grammarAccess.getPropertyAccess().getValueAssignment_4(), "rule__Property__ValueAssignment_4");
					put(grammarAccess.getPropertyAccess().getReadonlyAssignment_5(), "rule__Property__ReadonlyAssignment_5");
					put(grammarAccess.getPropertyAccess().getModelAssignment_6_1(), "rule__Property__ModelAssignment_6_1");
					put(grammarAccess.getEventAccess().getEventNameAssignment_1(), "rule__Event__EventNameAssignment_1");
					put(grammarAccess.getEventAccess().getFunctionNameAssignment_3(), "rule__Event__FunctionNameAssignment_3");
					put(grammarAccess.getEventAccess().getNatureAssignment_5(), "rule__Event__NatureAssignment_5");
					put(grammarAccess.getEventAccess().getDescriptionAssignment_6_1(), "rule__Event__DescriptionAssignment_6_1");
					put(grammarAccess.getEventAccess().getPropertiesAssignment_7(), "rule__Event__PropertiesAssignment_7");
					put(grammarAccess.getEventAccess().getMessagesAssignment_8_1(), "rule__Event__MessagesAssignment_8_1");
					put(grammarAccess.getEventAccess().getMessagesAssignment_8_2_1(), "rule__Event__MessagesAssignment_8_2_1");
					put(grammarAccess.getEventAccess().getParametersAssignment_9_1_0(), "rule__Event__ParametersAssignment_9_1_0");
					put(grammarAccess.getEventAccess().getParametersAssignment_9_1_1(), "rule__Event__ParametersAssignment_9_1_1");
					put(grammarAccess.getEventAccess().getSnippetsAssignment_9_2_0(), "rule__Event__SnippetsAssignment_9_2_0");
					put(grammarAccess.getEventAccess().getSnippetsAssignment_9_2_1(), "rule__Event__SnippetsAssignment_9_2_1");
					put(grammarAccess.getSnippetAccess().getTypeNameAssignment_2(), "rule__Snippet__TypeNameAssignment_2");
					put(grammarAccess.getSnippetAccess().getPropertiesAssignment_3(), "rule__Snippet__PropertiesAssignment_3");
					put(grammarAccess.getSnippetAccess().getContentsAssignment_4_1_0(), "rule__Snippet__ContentsAssignment_4_1_0");
					put(grammarAccess.getSnippetAccess().getContentsAssignment_4_1_1(), "rule__Snippet__ContentsAssignment_4_1_1");
					put(grammarAccess.getTranslationAccess().getLanguageAssignment_0(), "rule__Translation__LanguageAssignment_0");
					put(grammarAccess.getTranslationAccess().getMessageAssignment_2(), "rule__Translation__MessageAssignment_2");
					put(grammarAccess.getParameterAccess().getNameAssignment_0(), "rule__Parameter__NameAssignment_0");
					put(grammarAccess.getParameterAccess().getValueAssignment_2(), "rule__Parameter__ValueAssignment_2");
					put(grammarAccess.getParameterAccess().getUserDefinedAssignment_3(), "rule__Parameter__UserDefinedAssignment_3");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			com.odcgroup.page.ui.contentassist.antlr.internal.InternalPageParser typedParser = (com.odcgroup.page.ui.contentassist.antlr.internal.InternalPageParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public PageGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(PageGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
