# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels fr = "Résumé du portefeuille", en = "Portfolio Summary", de = Portfoliozusammenfassung
	domainEntity = "AAADSValuation:ValuationSummaryPerPortfolio"
	bean-define = DSBean.AAADSValuation.ValuationSummaryPerPortfolio
	bean-name = ValuationSummaryPerPortfolio
	id = ByPortfolio_OFC3_
	tid = 2217576490587
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			id = m8__2
			table-column-count = 12 !
			table-columns-width = "8,8,8,8,8,8,8,8,8,8,8,8" !
		{
			--- TableColumn ---
				labels en = Portfolio, de = Portfolio, fr = Portefeuille
				column-display-grouping = true
				column-name = GROUPING
				column-type = placeholder !
				type = text
				column-locked = true
				column-sortable = false !
				id = D879x
				table-column-width = 8
				tid = 73566021908645
			{
				--- TableGroup ---
					aggregateData = false
					group-column-name = PTF_HIER_STR
					group-sorting-column-name = PTF_HIER_STR
					group-sorting-direction = ascending
					hierarchy = true
					group-rank = 1
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = selectPortfolio ud
						code = "<udp:item column=\"_nodeCode\"/>" ud
						ini_portfolioDimensionE = 1 ud
						ini_portfolioDimPortfolio.code = "<udp:item column=\"_nodeCode\"/>" ud
						modal = false
						only-changed = false
						prevalidate = false
						portfolioId = "<udp:item column=\"portfolio_id\"/>" ud
						Snippet FilterSet
						id = fs_yo1
						level = 1
						targetDataset = "AAADSValuation:ValuationSummaryPerPortfolio"
						{
							Snippet Filter
							attribute = PTF_HIER_STR
							filterValue = "<udp:item column=\"PTF_HIER_STR\"/>"
							operator = BEGINS_WITH
						}
					}
				}
			}
			--- TableColumn ---
				column-name = THIRD_COMP_RULE !
				column-type = domain !
				domainAttribute = THIRD_COMP_RULE !
				type = text
				column-visibility = not-visible
				id = THIRD_COMP_RULE
				table-column-width = 8
			{
				--- TableColumnItem ---
					item-column = THIRD_COMP_RULE
					previewValue = value
			}
			--- TableColumn ---
				column-name = PORTFOLIO_CODE !
				column-type = domain !
				domainAttribute = PORTFOLIO_CODE !
				type = text
				column-visibility = not-visible
				id = PORTFOLIO_CODE
				table-column-width = 8
			{
				--- TableColumnItem ---
					item-column = PORTFOLIO_CODE
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Market Value", de = Marktwert, fr = "Valeur de marché"
				column-name = TotMktVal
				type = amount
				id = p8K_2
				documentation = "Sum of the Total Market Value in Reference Currency by Portfolio."
				column-computation = make-amount
				column-computation-parameters = "TOT_MKT_VAL,REF_CURRENCY"
				table-column-width = 8
				tid = 29630331385846
			{
				--- TableColumnItem ---
					item-column = TotMktVal
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Net Cost Value", de = Netto-Einstandswert, fr = "Coût d\'achat"
				column-name = TotNetCostVal
				type = amount
				id = eaT27
				documentation = "Sum of the Total Net Cost Value in Reference Currency by Portfolio."
				column-computation = make-amount
				column-computation-parameters = "TOT_NET_COST_VAL,REF_CURRENCY"
				table-column-width = 8
				tid = 29634369020814
			{
				--- TableColumnItem ---
					item-column = TotNetCostVal
					previewValue = value
			}
			--- TableColumn ---
				column-name = TOT_PTF_PL_PERC !
				column-type = domain !
				domainAttribute = TOT_PTF_PL_PERC !
				type = text
				id = TOT_PTF_PL_PERC
				table-column-width = 8
			{
				--- TableColumnItem ---
					item-column = TOT_PTF_PL_PERC
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				labels de = Kunde
				column-name = CLIENT_NAME !
				column-type = domain !
				domainAttribute = CLIENT_NAME !
				column-width = 12%
				id = CLIENT_NAME
				table-column-width = 8
				tid = 1604011951104161
			{
				--- TableColumnItem ---
					item-column = CLIENT_NAME
					previewValue = value
			}
			--- TableColumn ---
				column-name = SERVICE_TYPE !
				column-type = domain !
				domainAttribute = SERVICE_TYPE !
				type = text
				id = SERVICE_TYPE
				table-column-width = 8
			{
				--- TableColumnItem ---
					item-column = SERVICE_TYPE
					previewValue = value
			}
			--- TableColumn ---
				labels de = Berater
				column-name = COM_MGR_NAME !
				column-type = domain !
				domainAttribute = COM_MGR_NAME !
				type = text
				id = COM_MGR_NAME
				table-column-width = 8
				tid = 1604011951480562
			{
				--- TableColumnItem ---
					item-column = COM_MGR_NAME
					previewValue = value
			}
			--- TableColumn ---
				labels de = Verwalter
				column-name = ADMIN_MGR_NAME !
				column-type = domain !
				domainAttribute = ADMIN_MGR_NAME !
				type = text
				id = ADMIN_MGR_NAME
				table-column-width = 8
				tid = 1604011951671757
			{
				--- TableColumnItem ---
					item-column = ADMIN_MGR_NAME
					previewValue = value
			}
			--- TableColumn ---
				column-name = THIRD_PARTY_OWNERSHIP_RULE !
				column-type = domain !
				domainAttribute = THIRD_PARTY_OWNERSHIP_RULE !
				type = text
				column-visibility = not-visible
				id = THIRD_PARTY_OWNERSHIP_RULE
				table-column-width = 8
			{
				--- TableColumnItem ---
					item-column = THIRD_PARTY_OWNERSHIP_RULE
					previewValue = value
			}
			--- TableColumn ---
				column-name = THIRD_PARTY_PERCT_OWNERSHIP !
				column-type = domain !
				domainAttribute = THIRD_PARTY_PERCT_OWNERSHIP !
				type = text
				column-visibility = not-visible
				id = THIRD_PARTY_PERCT_OWNERSHIP
				table-column-width = 8
			{
				--- TableColumnItem ---
					item-column = THIRD_PARTY_PERCT_OWNERSHIP
					format = percentTA
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = PTF_HIER_STR
				sort-rank = 1
			--- TableKeepFilter ---
				keep-filter-column-name = ONE_PTF_OCCUR
				keep-filter-operand = 1
			--- TableExtra ---
				domainAttribute = portfolio_id
		}
		--- Grid ---
			cssClass = blank
			gridColumnCount = 4
			gridColumnsWidth = "25,25,25,25" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Button ---
					labels en = "Valuation Details", fr = "Détails de la valorisation", de = Vermögensdetails
					id = btn_jy__P
					tid = 167298923991978
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						flow-action = valuation ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
				--- Button ---
					labels de = Devisenkurs, fr = "Taux de change", en = "Exchange rates"
					id = btn_M62__
					tid = 3785649256499359
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "resource:///valuation/ValuationExchangeRate.pageflow"
						target = popup
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
		}
	}
}