# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels fr = "Résumé du portefeuille", en = "Portfolio Summary", de = Portfoliozusammenfassung
	domainEntity = "AAADSValuation:ValuationSummaryPerPortfolio"
	bean-define = DSBean.AAADSValuation.ValuationSummaryPerPortfolio
	bean-name = ValuationSummaryPerPortfolio
	id = ValuationSummaryByPortfolioNoButton_U_v_8
	tid = 1555983348037809
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			id = G08JQ
			table-column-count = 12 !
			table-columns-width = "8,8,8,8,8,8,8,8,8,8,8,8" !
		{
			--- TableColumn ---
				labels en = Portfolio, de = Portfolio, fr = Portefeuille
				column-display-grouping = true
				column-name = GROUPING
				column-type = placeholder !
				type = text
				column-locked = true
				column-sortable = false !
				id = gPw74
				table-column-width = 8
				tid = 1555983350168527
			{
				--- TableGroup ---
					aggregateData = false
					group-column-name = PTF_HIER_STR
					group-sorting-column-name = PTF_HIER_STR
					group-sorting-direction = ascending
					hierarchy = true
					group-rank = 1
			}
			--- TableColumn ---
				column-name = THIRD_COMP_RULE !
				column-type = domain !
				domainAttribute = THIRD_COMP_RULE !
				type = text
				column-visibility = not-visible
				id = THIRD_COMP_RULE
				table-column-width = 8
			{
				--- TableColumnItem ---
					item-column = THIRD_COMP_RULE
					previewValue = value
			}
			--- TableColumn ---
				column-name = PORTFOLIO_CODE !
				column-type = domain !
				domainAttribute = PORTFOLIO_CODE !
				type = text
				column-visibility = not-visible
				id = PORTFOLIO_CODE
				table-column-width = 8
			{
				--- TableColumnItem ---
					item-column = PORTFOLIO_CODE
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Market Value", de = Marktwert, fr = "Valeur de marché"
				column-name = TotMktVal
				type = amount
				id = tO0__
				documentation = "Sum of the Total Market Value in Reference Currency by Portfolio."
				column-computation = make-amount
				column-computation-parameters = "TOT_MKT_VAL,REF_CURRENCY"
				table-column-width = 8
				tid = 1555983351937187
			{
				--- TableColumnItem ---
					item-column = TotMktVal
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Net Cost Value", de = Netto-Einstandswert, fr = "Coût d\'achat"
				column-name = TotNetCostVal
				type = amount
				id = AS_P8
				documentation = "Sum of the Total Net Cost Value in Reference Currency by Portfolio."
				column-computation = make-amount
				column-computation-parameters = "TOT_NET_COST_VAL,REF_CURRENCY"
				table-column-width = 8
				tid = 1555983353882406
			{
				--- TableColumnItem ---
					item-column = TotNetCostVal
					previewValue = value
			}
			--- TableColumn ---
				column-name = TOT_PTF_PL_PERC !
				column-type = domain !
				domainAttribute = TOT_PTF_PL_PERC !
				type = text
				id = TOT_PTF_PL_PERC
				table-column-width = 8
			{
				--- TableColumnItem ---
					item-column = TOT_PTF_PL_PERC
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				labels de = Kunde
				column-name = CLIENT_NAME !
				column-type = domain !
				domainAttribute = CLIENT_NAME !
				column-width = 12%
				id = CLIENT_NAME
				table-column-width = 8
				tid = 1555983355972896
			{
				--- TableColumnItem ---
					item-column = CLIENT_NAME
					previewValue = value
			}
			--- TableColumn ---
				column-name = SERVICE_TYPE !
				column-type = domain !
				domainAttribute = SERVICE_TYPE !
				type = text
				id = SERVICE_TYPE
				table-column-width = 8
			{
				--- TableColumnItem ---
					item-column = SERVICE_TYPE
					previewValue = value
			}
			--- TableColumn ---
				labels de = Berater
				column-name = COM_MGR_NAME !
				column-type = domain !
				domainAttribute = COM_MGR_NAME !
				type = text
				id = COM_MGR_NAME
				table-column-width = 8
				tid = 1555983357792401
			{
				--- TableColumnItem ---
					item-column = COM_MGR_NAME
					previewValue = value
			}
			--- TableColumn ---
				labels de = Verwalter
				column-name = ADMIN_MGR_NAME !
				column-type = domain !
				domainAttribute = ADMIN_MGR_NAME !
				type = text
				id = ADMIN_MGR_NAME
				table-column-width = 8
				tid = 1555983359749353
			{
				--- TableColumnItem ---
					item-column = ADMIN_MGR_NAME
					previewValue = value
			}
			--- TableColumn ---
				column-name = THIRD_PARTY_OWNERSHIP_RULE !
				column-type = domain !
				domainAttribute = THIRD_PARTY_OWNERSHIP_RULE !
				type = text
				column-visibility = not-visible
				id = THIRD_PARTY_OWNERSHIP_RULE
				table-column-width = 8
			{
				--- TableColumnItem ---
					item-column = THIRD_PARTY_OWNERSHIP_RULE
					previewValue = value
			}
			--- TableColumn ---
				column-name = THIRD_PARTY_PERCT_OWNERSHIP !
				column-type = domain !
				domainAttribute = THIRD_PARTY_PERCT_OWNERSHIP !
				type = text
				column-visibility = not-visible
				id = THIRD_PARTY_PERCT_OWNERSHIP
				table-column-width = 8
			{
				--- TableColumnItem ---
					item-column = THIRD_PARTY_PERCT_OWNERSHIP
					format = percentTA
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = PTF_HIER_STR
				sort-rank = 1
			--- TableKeepFilter ---
				keep-filter-column-name = ONE_PTF_OCCUR
				keep-filter-operand = 1
		}
		--- Button ---
			labels en = "Exchange rates", fr = "Taux de change", de = Devisenkurs
			id = btn_aw02M
			tid = 3786487555449086
		{
			Event OnClick (submit) S
			{
				method = post
				call-URI = "resource:///valuation/ValuationExchangeRate.pageflow"
				target = popup
				modal = false
				only-changed = false
				prevalidate = false
			}
		}
	}
}