# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSListCompo:ListCompoList"
	bean-define = DSBean.AAADSListCompo.ListCompoList
	bean-name = ListCompoList
	id = ListCompoSectorList_im644
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			id = tM_l0
			table-column-count = 7 !
			table-columns-width = "14,14,14,14,14,14,14" !
		{
			--- TableColumn ---
				column-name = listCode !
				column-type = domain !
				domainAttribute = listCode !
				id = listCode
				table-column-width = 14
			{
				--- TableColumnItem ---
					item-column = listCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = listExtDenomination !
				column-type = domain !
				domainAttribute = listExtDenomination !
				type = text
				id = listExtDenomination
				table-column-width = 14
			{
				--- TableColumnItem ---
					item-column = listExtDenomination
					previewValue = value
			}
			--- TableColumn ---
				column-name = validityD !
				column-type = domain !
				domainAttribute = validityD !
				id = validityD
				table-column-width = 14
			{
				--- TableColumnItem ---
					item-column = validityD
					format = datetime.date-only
					previewValue = value
			}
			--- TableColumn ---
				column-name = rankN !
				column-type = domain !
				domainAttribute = rankN !
				id = rankN
				table-column-width = 14
			{
				--- TableColumnItem ---
					item-column = rankN
					format = integer
					previewValue = value
			}
			--- TableColumn ---
				column-name = sectorCodificationCode !
				column-type = domain !
				domainAttribute = sectorCodificationCode !
				id = sectorCodificationCode
				table-column-width = 14
			{
				--- TableColumnItem ---
					item-column = sectorCodificationCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = sectorCode !
				column-type = domain !
				domainAttribute = sectorCode !
				id = sectorCode
				table-column-width = 14
			{
				--- TableColumnItem ---
					item-column = sectorCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = sectorExtDenomination !
				column-type = domain !
				domainAttribute = sectorExtDenomination !
				type = text
				id = sectorExtDenomination
				table-column-width = 14
			{
				--- TableColumnItem ---
					item-column = sectorExtDenomination
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = listCode
				sort-rank = 1
			--- TableSort ---
				sort-column-name = validityD
				sort-direction = descending
				sort-rank = 2
			--- TableSort ---
				sort-column-name = rankN
				sort-rank = 3
			--- TableSort ---
				sort-column-name = sectorCodificationCode
				sort-rank = 4
			--- TableSort ---
				sort-column-name = sectorCode
				sort-rank = 5
		}
	}
}