# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSListCompo:ListCompoList"
	bean-define = DSBean.AAADSListCompo.ListCompoList
	bean-name = ListCompoList
	id = ListCompoManagerList_HD2X_
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			id = z_1c_
			table-column-count = 6 !
			table-columns-width = "16,16,16,16,16,16" !
		{
			--- TableColumn ---
				column-name = listCode !
				column-type = domain !
				domainAttribute = listCode !
				id = listCode
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = listCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = listExtDenomination !
				column-type = domain !
				domainAttribute = listExtDenomination !
				type = text
				id = listExtDenomination
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = listExtDenomination
					previewValue = value
			}
			--- TableColumn ---
				column-name = validityD !
				column-type = domain !
				domainAttribute = validityD !
				id = validityD
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = validityD
					format = datetime.date-only
					previewValue = value
			}
			--- TableColumn ---
				column-name = rankN !
				column-type = domain !
				domainAttribute = rankN !
				id = rankN
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = rankN
					format = integer
					previewValue = value
			}
			--- TableColumn ---
				labels fr = Gestionnaire, de = Verwalter
				column-name = managerCode !
				column-type = domain !
				domainAttribute = managerCode !
				id = managerCode
				table-column-width = 16
				tid = 34873684733394
			{
				--- TableColumnItem ---
					item-column = managerCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = managerName !
				column-type = domain !
				domainAttribute = managerName !
				type = text
				id = managerName
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = managerName
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = listCode
				sort-rank = 1
			--- TableSort ---
				sort-column-name = validityD
				sort-direction = descending
				sort-rank = 2
			--- TableSort ---
				sort-column-name = rankN
				sort-rank = 3
			--- TableSort ---
				sort-column-name = managerCode
				sort-rank = 4
		}
	}
}