# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSListCompo:ListCompoList"
	bean-define = DSBean.AAADSListCompo.ListCompoList
	bean-name = ListCompoList
	id = ListCompoGridList_m51fZ
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			id = cjgQX
			table-column-count = 6 !
			table-columns-width = "16,16,16,16,16,16" !
		{
			--- TableColumn ---
				column-name = listCode !
				column-type = domain !
				domainAttribute = listCode !
				id = listCode
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = listCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = listExtDenomination !
				column-type = domain !
				domainAttribute = listExtDenomination !
				type = text
				id = listExtDenomination
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = listExtDenomination
					previewValue = value
			}
			--- TableColumn ---
				column-name = validityD !
				column-type = domain !
				domainAttribute = validityD !
				id = validityD
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = validityD
					format = datetime.date-only
					previewValue = value
			}
			--- TableColumn ---
				column-name = rankN !
				column-type = domain !
				domainAttribute = rankN !
				id = rankN
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = rankN
					format = integer
					previewValue = value
			}
			--- TableColumn ---
				labels de = Raster
				column-name = gridCode !
				column-type = domain !
				domainAttribute = gridCode !
				id = gridCode
				table-column-width = 16
				tid = 32197876811997
			{
				--- TableColumnItem ---
					item-column = gridCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = gridExtDenomination !
				column-type = domain !
				domainAttribute = gridExtDenomination !
				type = text
				id = gridExtDenomination
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = gridExtDenomination
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = listCode
				sort-rank = 1
			--- TableSort ---
				sort-column-name = validityD
				sort-rank = 2
			--- TableSort ---
				sort-column-name = rankN
				sort-rank = 3
			--- TableSort ---
				sort-column-name = gridCode
				sort-rank = 4
		}
	}
}