# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSListCompo:ListCompoList"
	bean-define = DSBean.AAADSListCompo.ListCompoList
	bean-name = ListCompoList
	id = ListCompoThirdPartyList_BTwj9
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			id = q___4
			table-column-count = 6 !
			table-columns-width = "16,16,16,16,16,16" !
		{
			--- TableColumn ---
				column-name = listCode !
				column-type = domain !
				domainAttribute = listCode !
				id = listCode
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = listCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = listExtDenomination !
				column-type = domain !
				domainAttribute = listExtDenomination !
				type = text
				id = listExtDenomination
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = listExtDenomination
					previewValue = value
			}
			--- TableColumn ---
				column-name = validityD !
				column-type = domain !
				domainAttribute = validityD !
				id = validityD
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = validityD
					format = datetime.date-only
					previewValue = value
			}
			--- TableColumn ---
				column-name = rankN !
				column-type = domain !
				domainAttribute = rankN !
				id = rankN
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = rankN
					format = integer
					previewValue = value
			}
			--- TableColumn ---
				column-name = thirdPartyCode !
				column-type = domain !
				domainAttribute = thirdPartyCode !
				id = thirdPartyCode
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = thirdPartyCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = thirdPartyExtDenomination !
				column-type = domain !
				domainAttribute = thirdPartyExtDenomination !
				type = text
				id = thirdPartyExtDenomination
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = thirdPartyExtDenomination
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = listCode
				sort-rank = 1
			--- TableSort ---
				sort-column-name = validityD
				sort-direction = descending
				sort-rank = 2
			--- TableSort ---
				sort-column-name = rankN
				sort-rank = 3
		}
	}
}