# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = Notepad, fr = Bloc-note, de = Notizblock
	domainEntity = "AAADSNotepad:NotepadList"
	bean-define = DSBean.AAADSNotepad.NotepadList
	bean-name = NotepadList
	id = NotepadList_cM_xv
	tid = 5571969700838
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			table-page-size = 5
			id = d_H_5
			table-model-reference = DSTableModel.AAADSNotepad.NotepadList
			table-column-count = 9 !
			table-columns-width = "11,11,11,11,11,11,11,11,11" !
		{
			--- TableColumn ---
				column-name = noteD !
				column-type = domain !
				domainAttribute = noteD !
				id = noteD
				table-column-width = 11
			{
				--- TableColumnItem ---
					toolTips en = "View Notepad", de = "Notiz ansehen", fr = "Voir bloc-note"
					item-column = noteD
					format = datetime.with-seconds
					previewValue = value
					tid = 5571944292368
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "resource:///administration/notepad/NotepadView.pageflow"
						target = popup
						entity.dict = "<udp:item column=\"entityDict\"/>" ud
						object = "<udp:item column=\"object\"/>" ud
						user.code = "<udp:item column=\"userCode\"/>" ud
						type.id = "<udp:item column=\"typeId\"/>" ud
						noteD = "<udp:item column=\"noteD\"/>" ud
						noteD.date-format = "<udp:datetime-pattern option=\"with-seconds\"/>" ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- TableColumn ---
				column-name = userName !
				column-type = domain !
				domainAttribute = userName !
				type = text
				id = userName
				table-column-width = 11
			{
				--- TableColumnItem ---
					item-column = userName
					previewValue = value
			}
			--- TableColumn ---
				column-name = typeExtDenomination !
				column-type = domain !
				domainAttribute = typeExtDenomination !
				type = text
				id = typeExtDenomination
				table-column-width = 11
			{
				--- TableColumnItem ---
					item-column = typeExtDenomination
					previewValue = value
			}
			--- TableColumn ---
				column-name = titleC !
				column-type = domain !
				domainAttribute = titleC !
				id = titleC
				table-column-width = 11
			{
				--- TableColumnItem ---
					item-column = titleC
					previewValue = value
			}
			--- TableColumn ---
				column-name = userCode !
				column-type = domain !
				domainAttribute = userCode !
				type = text
				column-visibility = never-visible
				id = userCode
				table-column-width = 11
			{
				--- TableColumnItem ---
					item-column = userCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = entityDict !
				column-type = domain !
				domainAttribute = entityDict !
				type = text
				column-visibility = never-visible
				id = entityDict
				table-column-width = 11
			{
				--- TableColumnItem ---
					item-column = entityDict
					format = integer
					previewValue = value
			}
			--- TableColumn ---
				column-name = object !
				column-type = domain !
				domainAttribute = object !
				type = text
				column-visibility = never-visible
				id = object
				table-column-width = 11
			{
				--- TableColumnItem ---
					item-column = object
					format = integer
					previewValue = value
			}
			--- TableColumn ---
				column-name = typeId !
				column-type = domain !
				domainAttribute = typeId !
				type = text
				column-visibility = never-visible
				id = typeId
				table-column-width = 11
			{
				--- TableColumnItem ---
					item-column = typeId
					format = integer
					previewValue = value
			}
			--- TableColumn ---
				column-name = userId !
				column-type = domain !
				domainAttribute = userId !
				type = text
				column-visibility = never-visible
				id = userId
				table-column-width = 11
			{
				--- TableColumnItem ---
					item-column = userId
					format = integer
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = noteD
				sort-direction = descending
				sort-rank = 1
			--- TableSort ---
				sort-column-name = typeExtDenomination
				sort-rank = 3
			--- TableSort ---
				sort-column-name = userName
				sort-rank = 5
		}
	}
}