# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = Notepad, fr = Bloc-note, de = Notizblock
	domainEntity = "AAADSNotepad:NotepadList"
	bean-define = DSBean.AAADSNotepad.NotepadList
	bean-name = NotepadList
	id = NotepadListEdit_bz9__
	tid = 5571969675354
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 4
			gridColumnsWidth = "25,25,25,25" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Button ---
					labels en = "Create Notepad", fr = "Créer un Bloc-notes", de = "Notizblock erstellen"
					id = btn_k8_8_
					tid = 56569950448450
			}
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
		}
		--- TableTree ---
			table-page-size = 5
			id = d7k1D
			table-column-count = 9 !
			table-columns-width = "11,11,11,11,11,11,11,11,11" !
		{
			--- TableColumn ---
				column-name = UPDATE
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				id = cG639
				table-column-width = 11
			{
				--- Icon ---
					toolTips en = "Update Notepad", de = "Notiz ändern", fr = "Mettre à jour le bloc-note"
					horizontalAlignment = center
					icon = application_edit
					id = Qa_4_
					tid = 2711506084432
			}
			--- TableColumn ---
				column-name = COPY
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				id = V___u
				table-column-width = 11
			{
				--- Icon ---
					toolTips en = "Copy Notepad", de = "Notiz kopieren", fr = "Copier bloc-note"
					horizontalAlignment = center
					icon = application_double
					id = id401
					tid = 2772903299162
			}
			--- TableColumn ---
				column-name = DELETE
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				id = KQ16_
				table-column-width = 11
			{
				--- Icon ---
					toolTips en = "Delete Notepad", de = "Notiz löschen", fr = "Supprimer "
					horizontalAlignment = center
					icon = application_form_delete
					id = G9Eq_
					tid = 35409347597529
			}
			--- TableColumn ---
				column-name = noteD !
				column-type = domain !
				domainAttribute = noteD !
				id = noteD
				table-column-width = 11
			{
				--- TableColumnItem ---
					toolTips en = "View Notepad", de = "Notiz ansehen", fr = "Voir bloc-note"
					item-column = noteD
					previewValue = value
					tid = 36690186303007
			}
			--- TableColumn ---
				column-name = userName !
				column-type = domain !
				domainAttribute = userName !
				type = text
				id = userName
				table-column-width = 11
			{
				--- TableColumnItem ---
					item-column = userName
					previewValue = value
			}
			--- TableColumn ---
				column-name = typeExtDenomination !
				column-type = domain !
				domainAttribute = typeExtDenomination !
				type = text
				id = typeExtDenomination
				table-column-width = 11
			{
				--- TableColumnItem ---
					item-column = typeExtDenomination
					previewValue = value
			}
			--- TableColumn ---
				column-name = titleC !
				column-type = domain !
				domainAttribute = titleC !
				id = titleC
				table-column-width = 11
			{
				--- TableColumnItem ---
					item-column = titleC
					previewValue = value
			}
			--- TableColumn ---
				column-name = entityDict !
				column-type = domain !
				domainAttribute = entityDict !
				type = text
				column-visibility = never-visible
				id = entityDict
				table-column-width = 11
			{
				--- TableColumnItem ---
					item-column = entityDict
					format = integer
					previewValue = value
			}
			--- TableColumn ---
				column-name = object !
				column-type = domain !
				domainAttribute = object !
				type = text
				column-visibility = never-visible
				id = object
				table-column-width = 11
			{
				--- TableColumnItem ---
					item-column = object
					format = integer
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = noteD
				sort-direction = descending
				sort-rank = 1
			--- TableSort ---
				sort-column-name = userName
				sort-rank = 3
			--- TableSort ---
				sort-column-name = typeExtDenomination
				sort-rank = 5
		}
	}
}