# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSCurrChrono:CurrChronoList"
	bean-define = DSBean.AAADSCurrChrono.CurrChronoList
	bean-name = CurrChronoList
	id = CurrChronoList_n_586
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			table-filter-layer = true
			id = k991j
			table-column-count = 5 !
			table-columns-width = "20,20,20,20,20" !
		{
			--- TableColumn ---
				column-name = currencyCode !
				column-type = domain !
				domainAttribute = currencyCode !
				id = currencyCode
				table-column-width = 20
			{
				--- TableColumnItem ---
					item-column = currencyCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = dateD !
				column-type = domain !
				domainAttribute = dateD !
				id = dateD
				table-column-width = 20
			{
				--- TableColumnItem ---
					item-column = dateD
					format = datetime.date-only
					previewValue = value
			}
			--- TableColumn ---
				column-name = natureE !
				column-type = domain !
				domainAttribute = natureE !
				id = natureE
				table-column-width = 20
			{
				--- TableColumnItem ---
					item-column = natureE
					previewValue = value
			}
			--- TableColumn ---
				column-name = underlyCurrencyCode !
				column-type = domain !
				domainAttribute = underlyCurrencyCode !
				id = underlyCurrencyCode
				table-column-width = 20
			{
				--- TableColumnItem ---
					item-column = underlyCurrencyCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = valueN !
				column-type = domain !
				domainAttribute = valueN !
				id = valueN
				table-column-width = 20
			{
				--- TableColumnItem ---
					item-column = valueN
					format = decimal.detailed
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = currencyCode
				sort-rank = 1
			--- TableSort ---
				sort-column-name = dateD
				sort-direction = descending
				sort-rank = 2
			--- TableSort ---
				sort-column-name = natureE
				sort-rank = 3
			--- TableSort ---
				sort-column-name = underlyCurrencyCode
				sort-rank = 4
		}
	}
}