# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "View Type", de = "Typ ansehen", fr = "Voir le type"
	containment = container
	id = TypeView_Tml_8
	tid = 4378820478301
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			id = rh2_s
			indexOfSelectedChild = 0
		{
			--- Tab ---
				labels en = Detail, de = Detail, fr = Détail
				id = tab_n_O__
				isWidgetSelected = true
				tid = 4923790096227
			--- Tab ---
				labels en = Denomination, de = Beschreibung, fr = Dénomination
				id = tab_y_9c_
				isWidgetVisible = false
				tid = 5571960003778
			--- Tab ---
				labels en = Synonym, de = Synonym, fr = Synonyme
				id = tab_w1_5_
				isWidgetVisible = false
				tid = 4886372727818
		}
	}
}