# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "View Instrument Type", de = "Instrumentart ansehen", fr = "Voir le type de l\'instrument"
	containment = container
	id = TypeInstrumentView_YB_72
	tid = 4427665106319
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			id = w86__
			indexOfSelectedChild = 2
		{
			--- Tab ---
				labels en = Detail, de = Detail, fr = Détail
				id = tab_y1aL8
				isWidgetVisible = false
				tid = 4964903769333
			--- Tab ---
				labels en = Denomination, de = Beschreibung, fr = Dénomination
				id = tab_I___3
				isWidgetVisible = false
				tid = 5571961096770
			--- Tab ---
				labels en = Synonym, de = Synonym, fr = Synonyme
				id = tab_pk0__
				isWidgetSelected = true
				tid = 5571962108413
		}
	}
}