# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "View Operation Type", de = "Transaktionsart ansehen", fr = "Voir le type de l\'opération"
	containment = container
	id = TypeOperationView_M27k0
	tid = 4497457659562
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			id = Vn6__
			indexOfSelectedChild = 0
		{
			--- Tab ---
				labels en = Detail, de = Detail, fr = Détail
				id = tab_syI6k
				isWidgetSelected = true
				tid = 4942063439068
			--- Tab ---
				labels en = Denomination, de = Beschreibung, fr = Dénomination
				id = tab_an6_p
				isWidgetVisible = false
				tid = 4872492471529
			--- Tab ---
				labels en = Synonym, de = Synonym, fr = Synonyme
				id = tab_v_9Y1
				isWidgetVisible = false
				tid = 5571960508638
		}
	}
}