# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSDomain:DomainContext"
	collapsible = true
	cssClass = nodeco
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = ContextAdvanced_v__2_
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 5
			gridColumnsWidth = "10,12,15,20,20" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 10
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainPLMethod.fragment
			}
			--- GridCell ---
				gridColumnWidth = 12
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainDynamicWeight.fragment
			}
			--- GridCell ---
				gridColumnWidth = 15
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainRiskExposure.fragment
			}
			--- GridCell ---
				gridColumnWidth = 20
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainPerformanceFrequency1.fragment
			}
			--- GridCell ---
				gridColumnWidth = 20
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainPerformanceDetailLevel.fragment
			}
		}
		--- Grid ---
			cssClass = blank
			gridColumnCount = 1
			gridColumnsWidth = 100 !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 100
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainStrategyLink.fragment
			}
		}
	}
}