# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = Context, fr = Contexte, de = Kontext
	containment = container
	domainEntity = "AAADSDomain:DomainContext"
	collapsed = true
	collapsible = true
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = ContextNotEditedHead_A_7G_
	tid = 11156115688510
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TabbedPane ---
			id = ee_nG
			indexOfSelectedChild = 1
		{
			--- Tab ---
				labels fr = Base, en = Basic, de = Einfach
				id = perf_contrib_basic
				isWidgetVisible = false
				tid = 11156131423513
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/performance/contribution/context/ContextBasicNotEdited.module
			}
			--- Tab ---
				labels fr = Avancée, en = Advanced, de = Erweitert
				id = perf_contrib_advanced
				isWidgetSelected = true
				tid = 11156131769052
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/performance/contribution/context/ContextAdvancedNotEdited.module
			}
		}
		--- Grid ---
			cssClass = blank
			gridColumnCount = 4
			gridColumnsWidth = "25,25,25,25" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Button ---
					labels en = Execute, de = Ausführen, fr = Exécuter
					id = btn_B__4i
					tid = 11156147150065
				{
					Event OnClick (submit)
					{
						method = get
						call-URI = "<pageflow:continuation/>"
						widget-group-ref = form
						param = "flow-action=execute"
						only-changed = true
						prevalidate = false
						modal = false
					}
				}
				--- Button ---
					labels en = Refresh, de = Aktualisieren, fr = Actualiser
					id = btn_j3e_8
					tid = 11156152012180
				{
					Event OnClick (submit)
					{
						method = get
						call-URI = "<pageflow:continuation/>"
						widget-group-ref = form
						param = "flow-action=execute,DSAction=refresh"
						only-changed = true
						prevalidate = false
						modal = false
					}
				}
				--- Button ---
					labels en = "Default Settings", de = Standardeinstellung, fr = "Valeurs par défaut"
					id = btn_RszNx
					tid = 11156163049883
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = reset ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
		}
	}
}