# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSDomain:DomainContext"
	collapsible = true
	cssClass = nodeco
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = ContextBasicNotEdited_lX5_U
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 6
			gridColumnsWidth = "25,15,15,15,12,12" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainPortfolioDimensionNotEdited.fragment
			}
			--- GridCell ---
				gridColumnWidth = 15
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainFromDateNotEdited.fragment
			}
			--- GridCell ---
				gridColumnWidth = 15
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainPivotDateTillNotEdited.fragment
			}
			--- GridCell ---
				gridColumnWidth = 15
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainRefCurrencyNotEdited.fragment
			}
			--- GridCell ---
				gridColumnWidth = 12
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainHierarchyIdentifierNotEdited.fragment
			}
			--- GridCell ---
				gridColumnWidth = 12
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainConsolidationIdentifierNotEdited.fragment
			}
		}
	}
}