# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = Context, fr = Contexte, de = Kontext
	containment = container
	domainEntity = "AAADSDomain:DomainContext"
	collapsible = true
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = Context_x84__
	tid = 11025134457927
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TabbedPane ---
			id = n_6_B
			indexOfSelectedChild = 1
		{
			--- Tab ---
				labels fr = Base, en = Basic, de = Einfach
				id = perf_contrib_basic
				isWidgetVisible = false
				tid = 11025134950848
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/performance/contribution/context/ContextBasic.module
			}
			--- Tab ---
				labels fr = Avancée, en = Advanced, de = Erweitert
				id = perf_contrib_advanced
				isWidgetSelected = true
				tid = 11025136888554
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/performance/contribution/context/ContextAdvanced.module
			}
		}
		--- Grid ---
			cssClass = blank
			gridColumnCount = 4
			gridColumnsWidth = "25,25,25,25" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Button ---
					labels en = Execute, de = Ausführen, fr = Exécuter
					id = btn_g__2_
					tid = 11025143467061
				{
					Event OnClick (submit)
					{
						method = get
						call-URI = "<pageflow:continuation/>"
						widget-group-ref = form
						param = "flow-action=execute"
						only-changed = true
						prevalidate = false
						modal = false
					}
				}
				--- Button ---
					labels en = Refresh, de = Aktualisieren, fr = Actualiser
					id = btn_bt7_7
					tid = 11025144697979
				{
					Event OnClick (submit)
					{
						method = get
						call-URI = "<pageflow:continuation/>"
						widget-group-ref = form
						param = "flow-action=execute,DSAction=refresh"
						only-changed = true
						prevalidate = false
						modal = false
					}
				}
				--- Button ---
					labels en = "Default Settings", de = Standardeinstellung, fr = "Valeurs par défaut"
					id = btn_Hz2EH
					tid = 11025146667860
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = reset ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
		}
	}
}