# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Portfolio Details", fr = "Détails du portefeuille", de = "Details des Portfolios"
	domainEntity = "AAADSDomain:DomainContextDetail"
	collapsed = true
	bean-define = DSActivityBean.AAADSDomain.DomainContextDetail
	bean-name = DomainContextDetail
	id = PortfolioCodeDetailHead_I1j_i
	tid = 11125069544242
{
	--- Box ---
		boxType = vertical
		cssClass = nodeco
	{
		--- TabbedPane ---
			id = RX_31
			indexOfSelectedChild = 0
		{
			--- Tab ---
				labels en = Basic, fr = Base, de = Einfach
				id = perf_contrib_basic_details
				isWidgetSelected = true
				tid = 11125070015241
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 6
					gridColumnsWidth = "20,8,8,8,8,8" !
					gridRowCount = 1
					verticalAlignment = lead
				{
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainPortfolioCodeView.fragment
					}
					--- GridCell ---
						gridColumnWidth = 8
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainFromDateView.fragment
					}
					--- GridCell ---
						gridColumnWidth = 8
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainPivotDateTillView.fragment
					}
					--- GridCell ---
						gridColumnWidth = 8
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainRefCurrencyView.fragment
					}
					--- GridCell ---
						gridColumnWidth = 8
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainHierarchyIdentifierView.fragment
					}
					--- GridCell ---
						gridColumnWidth = 8
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainConsolidationIdentifierView.fragment
					}
				}
			}
			--- Tab ---
				labels en = Advanced, fr = Avancé, de = Erweitert
				id = perf_contrib_advanced_details
				isWidgetVisible = false
				tid = 11125114940001
			{
				--- Box ---
					boxType = vertical
				{
					--- Grid ---
						cssClass = blank
						gridColumnCount = 5
						gridColumnsWidth = "10,12,15,20,20" !
						gridRowCount = 1
					{
						--- GridCell ---
							gridColumnWidth = 10
						{
							--- Include ---
								includeSrc = "" !
								resource:///default/domain/basicelements/DomainPLMethodView.fragment
						}
						--- GridCell ---
							gridColumnWidth = 12
						{
							--- Include ---
								includeSrc = "" !
								resource:///default/domain/basicelements/DomainDynamicWeightView.fragment
						}
						--- GridCell ---
							gridColumnWidth = 15
						{
							--- Include ---
								includeSrc = "" !
								resource:///default/domain/basicelements/DomainRiskExposureView.fragment
						}
						--- GridCell ---
							gridColumnWidth = 20
						{
							--- Include ---
								includeSrc = "" !
								resource:///default/domain/basicelements/DomainPerformanceFrequency1View.fragment
						}
						--- GridCell ---
							gridColumnWidth = 20
						{
							--- Include ---
								includeSrc = "" !
								resource:///default/domain/basicelements/DomainPerformanceDetailLevelView.fragment
						}
					}
					--- Grid ---
						cssClass = blank
						gridColumnCount = 1
						gridColumnsWidth = 100 !
						gridRowCount = 1
					{
						--- GridCell ---
							gridColumnWidth = 100
						{
							--- Include ---
								includeSrc = "" !
								resource:///default/domain/basicelements/DomainPortfolioDetailsStrategyLinkView.fragment
						}
					}
				}
			}
		}
	}
}