# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	containment = container
	domainEntity = "AAADSStrategy:StrategyAdmin"
	collapsible = true
	cssClass = nodeco
	pagebreak = true
	bean-define = DSBean.AAADSStrategy.StrategyAdmin
	bean-name = StrategyAdmin
	id = DefinitionCommon_E_S__
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/strategy/common/definition/IdentificationView.module
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/strategy/common/definition/NatureTypeView.module
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/strategy/common/definition/StrategyView.module
	}
}