# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	containment = container
	domainEntity = "AAADSStrategy:StrategyAdmin"
	collapsible = true
	cssClass = nodeco
	pagebreak = true
	bean-define = DSBean.AAADSStrategy.StrategyAdmin
	bean-name = StrategyAdmin
	id = Definition_HA_X_
{
	--- Box ---
		boxType = vertical
	{
		--- Conditional ---
			indexOfSelectedChild = 3
		{
			--- ConditionalBody ---
				conditionLang = DSEL
				javaCode = "StrategyAdmin.natureE==AAAEnumerations::StrategyNatureE::AssetAllocation"
				technicalName = Allocation
				boxType = vertical
				isWidgetVisible = false
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/strategy/common/definition/DefinitionAllocation.module
			}
			--- ConditionalBody ---
				conditionLang = DSEL
				javaCode = "StrategyAdmin.natureE==AAAEnumerations::StrategyNatureE::ModelPortfolio"
				technicalName = "Model Portfolio"
				boxType = vertical
				isWidgetVisible = false
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/strategy/common/definition/DefinitionModelPortfolio.module
			}
			--- ConditionalBody ---
				conditionLang = DSEL
				javaCode = "StrategyAdmin.natureE==AAAEnumerations::StrategyNatureE::RecommendationList"
				technicalName = "Recommendation List"
				boxType = vertical
				isWidgetVisible = false
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/strategy/common/definition/DefinitionRecomList.module
			}
			--- ConditionalBody ---
				conditionLang = DSEL
				javaCode = "StrategyAdmin.natureE==AAAEnumerations::StrategyNatureE::InvestmentProfile"
				technicalName = "Investment Profile"
				boxType = vertical
				isWidgetSelected = true
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/strategy/common/definition/DefinitionInvestProfile.module
			}
			--- ConditionalBody ---
				javaCode = true
				technicalName = Default
				boxType = vertical
				isWidgetVisible = false
		}
	}
}