# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSStrategy:StrategyAdmin"
	cssClass = nodeco
	bean-define = DSBean.AAADSStrategy.StrategyAdmin
	bean-name = StrategyAdmin
	id = IdentificationView_p_K_8
{
	--- Box ---
		boxType = vertical
	{
		--- Box ---
			labels en = Identification, fr = Identification, de = Identifizierung
			boxType = vertical
			widgetBorder = box
			tid = 272203738117964
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 2
				gridColumnsWidth = "15,85" !
				gridRowCount = 3
			{
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						domainAttribute = code !
						for = code
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
						id = code
				}
				--- GridCell ---
					gridColumnWidth = 85
				{
					--- TextField ---
						domainAttribute = code !
						horizontalAlignment = "${corporatehalign}"
						type = text
						chars = 20
						editable = false
						required = true
						bean-property = code
						id = code
				}
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						domainAttribute = name !
						for = name
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
						id = name
				}
				--- GridCell ---
					gridColumnWidth = 85
				{
					--- TextField ---
						domainAttribute = name !
						columns = 30
						horizontalAlignment = "${corporatehalign}"
						type = text
						chars = 20
						editable = false
						required = true
						bean-property = name
						id = name
				}
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						domainAttribute = extDenomination !
						for = extDenomination
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
						id = extDenomination
				}
				--- GridCell ---
					gridColumnWidth = 85
				{
					--- TextField ---
						domainAttribute = extDenomination !
						columns = 30
						horizontalAlignment = "${corporatehalign}"
						type = text
						chars = 80
						editable = false
						required = true
						bean-property = extDenomination
						id = extDenomination
				}
			}
		}
	}
}