# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSStrategy:StrategyAdmin"
	cssClass = nodeco
	bean-define = DSBean.AAADSStrategy.StrategyAdmin
	bean-name = StrategyAdmin
	id = NatureTypeView_R4392
{
	--- Box ---
		boxType = vertical
	{
		--- Box ---
			labels en = "Nature & Type", de = "Art & Typ", fr = "Nature et Type"
			boxType = vertical
			widgetBorder = box
			tid = 272207547643944
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 4
				gridColumnsWidth = "15,35,15,35" !
				gridRowCount = 2
			{
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						domainAttribute = natureE !
						for = natureE
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
						id = natureE
				}
				--- GridCell ---
					gridColumnWidth = 35
				{
					--- ComboBox ---
						domainAttribute = natureE !
						horizontalAlignment = "${corporatehalign}"
						editable = false
						required = true
						bean-property = natureE
						id = natureE
				}
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						domainAttribute = subNatureE !
						for = subNatureE
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
						id = subNatureE
				}
				--- GridCell ---
					gridColumnWidth = 35
				{
					--- ComboBox ---
						domainAttribute = subNatureE !
						horizontalAlignment = "${corporatehalign}"
						editable = false
						required = true
						bean-property = subNatureE
						id = subNatureE
				}
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						domainAttribute = typeExtDenomination !
						for = typeExtDenomination
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
						id = typeExtDenomination
				}
				--- GridCell ---
					gridColumnWidth = 35
				{
					--- Include ---
						domainAssociation = type
						includeSrc = "" !
						resource:///default/strategy/administration/StrategyTypeIdentifierView.fragment
						bean-property-prefix = type.
				}
				--- GridCell ---
					gridColumnWidth = 15
				--- GridCell ---
					gridColumnWidth = 35
			}
		}
	}
}