# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSStrategy:StrategyAdmin"
	cssClass = nodeco
	bean-define = DSBean.AAADSStrategy.StrategyAdmin
	bean-name = StrategyAdmin
	id = StrategyView_y_7FF
{
	--- Box ---
		boxType = vertical
	{
		--- Conditional ---
			indexOfSelectedChild = 3
		{
			--- ConditionalBody ---
				conditionLang = DSEL
				javaCode = "StrategyAdmin.natureE==AAAEnumerations::StrategyNatureE::AssetAllocation"
				technicalName = Allocation
				boxType = vertical
				isWidgetVisible = false
			{
				--- Box ---
					labels en = Strategy, fr = Stratégie, de = Strategie
					boxType = vertical
					widgetBorder = box
					tid = 272271879377914
				{
					--- Grid ---
						cssClass = blank
						gridColumnCount = 4
						gridColumnsWidth = "15,35,15,35" !
						gridRowCount = 6
					{
						--- GridCell ---
							gridColumnWidth = 15
						{
							--- Conditional ---
								indexOfSelectedChild = 1
							{
								--- ConditionalBody ---
									conditionLang = DSEL
									javaCode = "StrategyAdmin.grid!=null"
									technicalName = Grid
									boxType = vertical
									isWidgetVisible = false
								{
									--- Label ---
										labels en = Grid, fr = Grille, de = Raster
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 353380935874892
								}
								--- ConditionalBody ---
									conditionLang = DSEL
									javaCode = "StrategyAdmin.list!=null"
									technicalName = "Grid List"
									boxType = vertical
									isWidgetSelected = true
								{
									--- Label ---
										labels en = "Grid List", fr = "Liste de grille", de = RasterList
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 280797527841026
								}
								--- ConditionalBody ---
									javaCode = true
									technicalName = Default
									boxType = vertical
									isWidgetVisible = false
								{
									--- Label ---
										labels en = Grid, fr = Grille, de = Raster
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 280740755529830
								}
							}
						}
						--- GridCell ---
							gridColumnWidth = 35
						{
							--- Conditional ---
								indexOfSelectedChild = 2
							{
								--- ConditionalBody ---
									conditionLang = DSEL
									javaCode = "StrategyAdmin.grid!=null"
									technicalName = Grid
									boxType = vertical
									isWidgetVisible = false
								{
									--- Include ---
										domainAssociation = grid
										includeSrc = "" !
										resource:///default/strategy/administration/GridIdentifierView.fragment
										bean-property-prefix = grid.
								}
								--- ConditionalBody ---
									conditionLang = DSEL
									javaCode = "StrategyAdmin.list!=null"
									technicalName = "Grid List"
									boxType = vertical
									isWidgetVisible = false
								{
									--- Include ---
										domainAssociation = list
										includeSrc = "" !
										resource:///default/strategy/administration/ListIdentifierView.fragment
										bean-property-prefix = list.
								}
								--- ConditionalBody ---
									javaCode = true
									technicalName = Default
									boxType = vertical
									isWidgetSelected = true
								{
									--- Label ---
										labels en = "No access rights on the associated grid", fr = "Pas de droit d\'accès sur la grille associée", de = "Kein Zugriffsrecht auf dem verknüpften Raster"
										tid = 282915947261010
								}
							}
						}
						--- GridCell ---
							gridColumnWidth = 15
						{
							--- LabelDomain ---
								domainAttribute = parentStrategyExtDenomination !
								for = parentStrategyExtDenomination
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
								id = parentStrategyExtDenomination
						}
						--- GridCell ---
							gridColumnWidth = 35
						{
							--- Include ---
								domainAssociation = parentStrategy
								includeSrc = "" !
								resource:///default/strategy/administration/ParentStrategyIdentifierView.fragment
						}
						--- GridCell ---
							gridColumnWidth = 15
						{
							--- LabelDomain ---
								domainAttribute = marketSegmentExtDenomination !
								for = marketSegmentExtDenomination
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
								id = marketSegmentExtDenomination
						}
						--- GridCell ---
							gridColumnWidth = 35
						{
							--- Include ---
								domainAssociation = marketSegment
								includeSrc = "" !
								resource:///default/strategy/administration/ParentMarketSegmentIdentifierView.fragment
						}
						--- GridCell ---
							gridColumnWidth = 15
						{
							--- LabelDomain ---
								domainAttribute = riskF !
								for = riskF
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
								id = riskF
						}
						--- GridCell ---
							gridColumnWidth = 35
						{
							--- ComboBox ---
								domainAttribute = riskF !
								horizontalAlignment = "${corporatehalign}"
								editable = false
								required = true
								bean-property = riskF
								id = riskF
						}
						--- GridCell ---
							gridColumnWidth = 15
						{
							--- LabelDomain ---
								domainAttribute = relativeMarginF !
								for = relativeMarginF
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
								id = relativeMarginF
						}
						--- GridCell ---
							gridColumnWidth = 35
						{
							--- ComboBox ---
								domainAttribute = relativeMarginF !
								horizontalAlignment = "${corporatehalign}"
								editable = false
								required = true
								bean-property = relativeMarginF
								id = relativeMarginF
						}
						--- GridCell ---
							gridColumnWidth = 15
						{
							--- LabelDomain ---
								domainAttribute = fluctMarginN !
								for = fluctMarginN
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								id = fluctMarginN
						}
						--- GridCell ---
							gridColumnWidth = 35
						{
							--- TextField ---
								domainAttribute = fluctMarginN !
								columns = 10
								format = percentTA
								horizontalAlignment = "${corporatehalign}"
								type = percent
								chars = 10
								editable = false
								bean-property = fluctMarginN
								id = fluctMarginN
						}
						--- GridCell ---
							gridColumnWidth = 15
						{
							--- LabelDomain ---
								domainAttribute = criticalnessE !
								for = criticalnessE
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
								id = criticalnessE
						}
						--- GridCell ---
							gridColumnWidth = 35
						{
							--- ComboBox ---
								domainAttribute = criticalnessE !
								horizontalAlignment = "${corporatehalign}"
								editable = false
								required = true
								bean-property = criticalnessE
								id = criticalnessE
						}
						--- GridCell ---
							gridColumnWidth = 15
						{
							--- LabelDomain ---
								domainAttribute = irregularF !
								for = irregularF
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
								id = irregularF
						}
						--- GridCell ---
							gridColumnWidth = 35
						{
							--- ComboBox ---
								domainAttribute = irregularF !
								horizontalAlignment = "${corporatehalign}"
								editable = false
								required = true
								bean-property = irregularF
								id = irregularF
						}
						--- GridCell ---
							gridColumnWidth = 15
						{
							--- LabelDomain ---
								domainAttribute = benchFreqN !
								for = benchFreqN
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								id = benchFreqN
						}
						--- GridCell ---
							gridColumnWidth = 35
						{
							--- Box ---
							{
								--- TextField ---
									domainAttribute = benchFreqN !
									columns = 5
									format = integer
									horizontalAlignment = "${corporatehalign}"
									type = integer
									chars = 5
									editable = false
									bean-property = benchFreqN
									id = benchFreqN
								--- ComboBox ---
									domainAttribute = benchFreqUnitE !
									horizontalAlignment = "${corporatehalign}"
									editable = false
									required = true
									bean-property = benchFreqUnitE
									id = benchFreqUnitE
							}
						}
						--- GridCell ---
							gridColumnWidth = 15
						{
							--- LabelDomain ---
								domainAttribute = stratRebalD !
								for = stratRebalD
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								id = stratRebalD
						}
						--- GridCell ---
							gridColumnWidth = 35
						{
							--- CaldateField ---
								domainAttribute = stratRebalD !
								format = datetime.date-only
								horizontalAlignment = "${corporatehalign}"
								type = datetime
								editable = false
								bean-property = stratRebalD
								id = stratRebalD
						}
						--- GridCell ---
							gridColumnWidth = 15
						{
							--- LabelDomain ---
								domainAttribute = dataSecuProfCode !
								for = dataSecuProfCode
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
								id = dataSecuProfCode
						}
						--- GridCell ---
							gridColumnWidth = 35
						{
							--- Include ---
								domainAssociation = dataSecuProf
								includeSrc = "" !
								resource:///default/strategy/administration/DataSecuProfIdentifierView.fragment
								bean-property-prefix = dataSecuProf.
						}
						--- GridCell ---
							gridColumnWidth = 15
						{
							--- LabelDomain ---
								domainAttribute = currencyCode !
								for = currencyCode
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
								id = currencyCode
						}
						--- GridCell ---
							gridColumnWidth = 35
						{
							--- Include ---
								domainAssociation = currency
								includeSrc = "" !
								resource:///default/strategy/administration/CurrencyIdentifierView.fragment
								bean-property-prefix = currency.
						}
					}
				}
			}
			--- ConditionalBody ---
				conditionLang = DSEL
				javaCode = "StrategyAdmin.natureE==AAAEnumerations::StrategyNatureE::ModelPortfolio"
				technicalName = "Model Portfolio"
				boxType = vertical
				isWidgetVisible = false
			{
				--- Box ---
					labels en = Strategy, fr = Stratégie, de = Strategie
					boxType = vertical
					widgetBorder = box
					tid = 272271880858964
				{
					--- Grid ---
						cssClass = blank
						gridColumnCount = 4
						gridColumnsWidth = "15,35,15,35" !
						gridRowCount = 6
					{
						--- GridCell ---
							gridColumnWidth = 15
						{
							--- Conditional ---
								indexOfSelectedChild = 2
							{
								--- ConditionalBody ---
									conditionLang = DSEL
									javaCode = "StrategyAdmin.grid!=null"
									technicalName = Grid
									boxType = vertical
									isWidgetVisible = false
								{
									--- Label ---
										labels en = Grid, fr = Grille, de = Raster
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 354724509764346
								}
								--- ConditionalBody ---
									conditionLang = DSEL
									javaCode = "StrategyAdmin.list!=null"
									technicalName = "Grid List"
									boxType = vertical
									isWidgetVisible = false
								{
									--- Label ---
										labels en = "Grid List", fr = "Liste de grille", de = RasterList
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 354724511322926
								}
								--- ConditionalBody ---
									javaCode = true
									technicalName = Default
									boxType = vertical
									isWidgetSelected = true
								{
									--- Label ---
										labels en = Grid, fr = Grille, de = Raster
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 354724513002731
								}
							}
						}
						--- GridCell ---
							gridColumnWidth = 35
						{
							--- Conditional ---
								indexOfSelectedChild = 2
							{
								--- ConditionalBody ---
									conditionLang = DSEL
									javaCode = "StrategyAdmin.grid!=null"
									technicalName = Grid
									boxType = vertical
									isWidgetVisible = false
								{
									--- Include ---
										domainAssociation = grid
										includeSrc = "" !
										resource:///default/strategy/administration/GridIdentifierView.fragment
										bean-property-prefix = grid.
								}
								--- ConditionalBody ---
									conditionLang = DSEL
									javaCode = "StrategyAdmin.list!=null"
									technicalName = "Grid List"
									boxType = vertical
									isWidgetVisible = false
								{
									--- Include ---
										domainAssociation = list
										includeSrc = "" !
										resource:///default/strategy/administration/ListIdentifierView.fragment
										bean-property-prefix = list.
								}
								--- ConditionalBody ---
									javaCode = true
									technicalName = Default
									boxType = vertical
									isWidgetSelected = true
								{
									--- Label ---
										labels en = "No grid or no access rights on the associated grid", fr = "Aucune grille ou pas de droit d\'accès sur la grille associée", de = "Kein Raster oder kein Zugriffsrecht auf dem verknüpften Raster"
										tid = 354738322212057
								}
							}
						}
						--- GridCell ---
							gridColumnWidth = 15
						{
							--- LabelDomain ---
								domainAttribute = parentStrategyExtDenomination !
								for = parentStrategyExtDenomination
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
								id = parentStrategyExtDenomination
						}
						--- GridCell ---
							gridColumnWidth = 35
						{
							--- Include ---
								domainAssociation = parentStrategy
								includeSrc = "" !
								resource:///default/strategy/administration/ParentStrategyIdentifierView.fragment
						}
						--- GridCell ---
							gridColumnWidth = 15
						{
							--- LabelDomain ---
								domainAttribute = marketSegmentExtDenomination !
								for = marketSegmentExtDenomination
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
								id = marketSegmentExtDenomination
						}
						--- GridCell ---
							gridColumnWidth = 35
						{
							--- Include ---
								domainAssociation = marketSegment
								includeSrc = "" !
								resource:///default/strategy/administration/ParentMarketSegmentIdentifierView.fragment
						}
						--- GridCell ---
							gridColumnWidth = 15
						{
							--- LabelDomain ---
								domainAttribute = riskF !
								for = riskF
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
								id = riskF
						}
						--- GridCell ---
							gridColumnWidth = 35
						{
							--- ComboBox ---
								domainAttribute = riskF !
								horizontalAlignment = "${corporatehalign}"
								editable = false
								required = true
								bean-property = riskF
								id = riskF
						}
						--- GridCell ---
							gridColumnWidth = 15
						{
							--- LabelDomain ---
								domainAttribute = relativeMarginF !
								for = relativeMarginF
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
								id = relativeMarginF
						}
						--- GridCell ---
							gridColumnWidth = 35
						{
							--- ComboBox ---
								domainAttribute = relativeMarginF !
								horizontalAlignment = "${corporatehalign}"
								editable = false
								required = true
								bean-property = relativeMarginF
								id = relativeMarginF
						}
						--- GridCell ---
							gridColumnWidth = 15
						{
							--- LabelDomain ---
								domainAttribute = fluctMarginN !
								for = fluctMarginN
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								id = fluctMarginN
						}
						--- GridCell ---
							gridColumnWidth = 35
						{
							--- TextField ---
								domainAttribute = fluctMarginN !
								columns = 10
								format = percentTA
								horizontalAlignment = "${corporatehalign}"
								type = percent
								chars = 10
								editable = false
								bean-property = fluctMarginN
								id = fluctMarginN
						}
						--- GridCell ---
							gridColumnWidth = 15
						{
							--- LabelDomain ---
								domainAttribute = criticalnessE !
								for = criticalnessE
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
								id = criticalnessE
						}
						--- GridCell ---
							gridColumnWidth = 35
						{
							--- ComboBox ---
								domainAttribute = criticalnessE !
								horizontalAlignment = "${corporatehalign}"
								editable = false
								required = true
								bean-property = criticalnessE
								id = criticalnessE
						}
						--- GridCell ---
							gridColumnWidth = 15
						{
							--- LabelDomain ---
								domainAttribute = irregularF !
								for = irregularF
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
								id = irregularF
						}
						--- GridCell ---
							gridColumnWidth = 35
						{
							--- ComboBox ---
								domainAttribute = irregularF !
								horizontalAlignment = "${corporatehalign}"
								editable = false
								required = true
								bean-property = irregularF
								id = irregularF
						}
						--- GridCell ---
							gridColumnWidth = 15
						{
							--- LabelDomain ---
								domainAttribute = benchFreqN !
								for = benchFreqN
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								id = benchFreqN
						}
						--- GridCell ---
							gridColumnWidth = 35
						{
							--- Box ---
							{
								--- TextField ---
									domainAttribute = benchFreqN !
									columns = 5
									format = integer
									horizontalAlignment = "${corporatehalign}"
									type = integer
									chars = 5
									editable = false
									bean-property = benchFreqN
									id = benchFreqN
								--- ComboBox ---
									domainAttribute = benchFreqUnitE !
									horizontalAlignment = "${corporatehalign}"
									editable = false
									required = true
									bean-property = benchFreqUnitE
									id = benchFreqUnitE
							}
						}
						--- GridCell ---
							gridColumnWidth = 15
						{
							--- LabelDomain ---
								domainAttribute = stratRebalD !
								for = stratRebalD
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								id = stratRebalD
						}
						--- GridCell ---
							gridColumnWidth = 35
						{
							--- CaldateField ---
								domainAttribute = stratRebalD !
								format = datetime.date-only
								horizontalAlignment = "${corporatehalign}"
								type = datetime
								editable = false
								bean-property = stratRebalD
								id = stratRebalD
						}
						--- GridCell ---
							gridColumnWidth = 15
						{
							--- LabelDomain ---
								domainAttribute = dataSecuProfCode !
								for = dataSecuProfCode
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
								id = dataSecuProfCode
						}
						--- GridCell ---
							gridColumnWidth = 35
						{
							--- Include ---
								domainAssociation = dataSecuProf
								includeSrc = "" !
								resource:///default/strategy/administration/DataSecuProfIdentifierView.fragment
								bean-property-prefix = dataSecuProf.
						}
						--- GridCell ---
							gridColumnWidth = 15
						{
							--- LabelDomain ---
								domainAttribute = currencyCode !
								for = currencyCode
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
								id = currencyCode
						}
						--- GridCell ---
							gridColumnWidth = 35
						{
							--- Include ---
								domainAssociation = currency
								includeSrc = "" !
								resource:///default/strategy/administration/CurrencyIdentifierView.fragment
								bean-property-prefix = currency.
						}
					}
				}
			}
			--- ConditionalBody ---
				conditionLang = DSEL
				javaCode = "StrategyAdmin.natureE==AAAEnumerations::StrategyNatureE::RecommendationList"
				technicalName = "Recommendation List"
				boxType = vertical
				isWidgetVisible = false
			{
				--- Box ---
					labels en = Strategy, fr = Stratégie, de = Strategie
					boxType = vertical
					widgetBorder = box
					tid = 272271882826079
				{
					--- Grid ---
						cssClass = blank
						gridColumnCount = 4
						gridColumnsWidth = "15,35,15,35" !
						gridRowCount = 3
					{
						--- GridCell ---
							gridColumnWidth = 15
						{
							--- Conditional ---
								indexOfSelectedChild = 2
							{
								--- ConditionalBody ---
									conditionLang = DSEL
									javaCode = "StrategyAdmin.grid!=null"
									technicalName = Grid
									boxType = vertical
									isWidgetVisible = false
								{
									--- Label ---
										labels en = Grid, fr = Grille, de = Raster
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 354726869039350
								}
								--- ConditionalBody ---
									conditionLang = DSEL
									javaCode = "StrategyAdmin.list!=null"
									technicalName = "Grid List"
									boxType = vertical
									isWidgetVisible = false
								{
									--- Label ---
										labels en = "Grid List", fr = "Liste de grille", de = RasterList
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 354726869527646
								}
								--- ConditionalBody ---
									javaCode = true
									technicalName = Default
									boxType = vertical
									isWidgetSelected = true
								{
									--- Label ---
										labels en = Grid, fr = Grille, de = Raster
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 354726876121653
								}
							}
						}
						--- GridCell ---
							gridColumnWidth = 35
						{
							--- Conditional ---
								indexOfSelectedChild = 2
							{
								--- ConditionalBody ---
									conditionLang = DSEL
									javaCode = "StrategyAdmin.grid!=null"
									technicalName = Grid
									boxType = vertical
									isWidgetVisible = false
								{
									--- Include ---
										domainAssociation = grid
										includeSrc = "" !
										resource:///default/strategy/administration/GridIdentifierView.fragment
										bean-property-prefix = grid.
								}
								--- ConditionalBody ---
									conditionLang = DSEL
									javaCode = "StrategyAdmin.list!=null"
									technicalName = "Grid List"
									boxType = vertical
									isWidgetVisible = false
								{
									--- Include ---
										domainAssociation = list
										includeSrc = "" !
										resource:///default/strategy/administration/ListIdentifierView.fragment
										bean-property-prefix = list.
								}
								--- ConditionalBody ---
									javaCode = true
									technicalName = Default
									boxType = vertical
									isWidgetSelected = true
								{
									--- Label ---
										labels en = "No grid or no access rights on the associated grid", fr = "Aucune grille ou pas de droit d\'accès sur la grille associée", de = "Kein Raster oder kein Zugriffsrecht auf dem verknüpften Raster"
										tid = 3268176549454
								}
							}
						}
						--- GridCell ---
							gridColumnWidth = 15
						{
							--- LabelDomain ---
								domainAttribute = riskF !
								for = riskF
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
								id = riskF
						}
						--- GridCell ---
							gridColumnWidth = 35
						{
							--- ComboBox ---
								domainAttribute = riskF !
								horizontalAlignment = "${corporatehalign}"
								editable = false
								required = true
								bean-property = riskF
								id = riskF
						}
						--- GridCell ---
							gridColumnWidth = 15
						{
							--- LabelDomain ---
								domainAttribute = marketSegmentExtDenomination !
								for = marketSegmentExtDenomination
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
								id = marketSegmentExtDenomination
						}
						--- GridCell ---
							gridColumnWidth = 35
						{
							--- Include ---
								domainAssociation = marketSegment
								includeSrc = "" !
								resource:///default/strategy/administration/ParentMarketSegmentIdentifierView.fragment
						}
						--- GridCell ---
							gridColumnWidth = 15
						{
							--- LabelDomain ---
								domainAttribute = criticalnessE !
								for = criticalnessE
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
								id = criticalnessE
						}
						--- GridCell ---
							gridColumnWidth = 35
						{
							--- ComboBox ---
								domainAttribute = criticalnessE !
								horizontalAlignment = "${corporatehalign}"
								editable = false
								required = true
								bean-property = criticalnessE
								id = criticalnessE
						}
						--- GridCell ---
							gridColumnWidth = 15
						{
							--- LabelDomain ---
								domainAttribute = dataSecuProfCode !
								for = dataSecuProfCode
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
								id = dataSecuProfCode
						}
						--- GridCell ---
							gridColumnWidth = 35
						{
							--- Include ---
								domainAssociation = dataSecuProf
								includeSrc = "" !
								resource:///default/strategy/administration/DataSecuProfIdentifierView.fragment
								bean-property-prefix = dataSecuProf.
						}
						--- GridCell ---
							gridColumnWidth = 15
						{
							--- LabelDomain ---
								domainAttribute = currencyCode !
								for = currencyCode
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
								id = currencyCode
						}
						--- GridCell ---
							gridColumnWidth = 35
						{
							--- Include ---
								domainAssociation = currency
								includeSrc = "" !
								resource:///default/strategy/administration/CurrencyIdentifierView.fragment
								bean-property-prefix = currency.
						}
					}
				}
			}
			--- ConditionalBody ---
				conditionLang = DSEL
				javaCode = "StrategyAdmin.natureE==AAAEnumerations::StrategyNatureE::InvestmentProfile"
				technicalName = "Investment Profile"
				boxType = vertical
				isWidgetSelected = true
			{
				--- Box ---
					labels en = Strategy, fr = Stratégie, de = Strategie
					boxType = vertical
					widgetBorder = box
					tid = 272271884775285
				{
					--- Grid ---
						cssClass = blank
						gridColumnCount = 4
						gridColumnsWidth = "15,35,15,35" !
						gridRowCount = 2
					{
						--- GridCell ---
							gridColumnWidth = 15
						{
							--- Conditional ---
								indexOfSelectedChild = 2
							{
								--- ConditionalBody ---
									conditionLang = DSEL
									javaCode = "StrategyAdmin.grid!=null"
									technicalName = Grid
									boxType = vertical
									isWidgetVisible = false
								{
									--- Label ---
										labels en = Grid, fr = Grille, de = Raster
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 354729525314203
								}
								--- ConditionalBody ---
									conditionLang = DSEL
									javaCode = "StrategyAdmin.list!=null"
									technicalName = "Grid List"
									boxType = vertical
									isWidgetVisible = false
								{
									--- Label ---
										labels en = "Grid List", fr = "Liste de grille", de = RasterList
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 354729525762738
								}
								--- ConditionalBody ---
									javaCode = true
									technicalName = Default
									boxType = vertical
									isWidgetSelected = true
								{
									--- Label ---
										labels en = Grid, fr = Grille, de = Raster
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 354729527688358
								}
							}
						}
						--- GridCell ---
							gridColumnWidth = 35
						{
							--- Conditional ---
								indexOfSelectedChild = 2
							{
								--- ConditionalBody ---
									conditionLang = DSEL
									javaCode = "StrategyAdmin.grid!=null"
									technicalName = Grid
									boxType = vertical
									isWidgetVisible = false
								{
									--- Include ---
										domainAssociation = grid
										includeSrc = "" !
										resource:///default/strategy/administration/GridIdentifierView.fragment
										bean-property-prefix = grid.
								}
								--- ConditionalBody ---
									conditionLang = DSEL
									javaCode = "StrategyAdmin.list!=null"
									technicalName = "Grid List"
									boxType = vertical
									isWidgetVisible = false
								{
									--- Include ---
										domainAssociation = list
										includeSrc = "" !
										resource:///default/strategy/administration/ListIdentifierView.fragment
										bean-property-prefix = list.
								}
								--- ConditionalBody ---
									javaCode = true
									technicalName = Default
									boxType = vertical
									isWidgetSelected = true
								{
									--- Label ---
										labels en = "No grid or no access rights on the associated grid", fr = "Aucune grille ou pas de droit d\'accès sur la grille associée", de = "Kein Raster oder kein Zugriffsrecht auf dem verknüpften Raster"
										tid = 3276770230020
								}
							}
						}
						--- GridCell ---
							gridColumnWidth = 15
						{
							--- LabelDomain ---
								domainAttribute = criticalnessE !
								for = criticalnessE
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
								id = criticalnessE
						}
						--- GridCell ---
							gridColumnWidth = 35
						{
							--- ComboBox ---
								domainAttribute = criticalnessE !
								horizontalAlignment = "${corporatehalign}"
								editable = false
								required = true
								bean-property = criticalnessE
								id = criticalnessE
						}
						--- GridCell ---
							gridColumnWidth = 15
						{
							--- LabelDomain ---
								domainAttribute = dataSecuProfCode !
								for = dataSecuProfCode
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
								id = dataSecuProfCode
						}
						--- GridCell ---
							gridColumnWidth = 35
						{
							--- Include ---
								domainAssociation = dataSecuProf
								includeSrc = "" !
								resource:///default/strategy/administration/DataSecuProfIdentifierView.fragment
								bean-property-prefix = dataSecuProf.
						}
						--- GridCell ---
							gridColumnWidth = 15
						{
							--- LabelDomain ---
								domainAttribute = currencyCode !
								for = currencyCode
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
								id = currencyCode
						}
						--- GridCell ---
							gridColumnWidth = 35
						{
							--- Include ---
								domainAssociation = currency
								includeSrc = "" !
								resource:///default/strategy/administration/CurrencyIdentifierView.fragment
								bean-property-prefix = currency.
						}
					}
				}
			}
			--- ConditionalBody ---
				javaCode = true
				technicalName = Default
				boxType = vertical
				isWidgetVisible = false
		}
	}
}