# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSFormat:FormatList"
	bean-define = DSBean.AAADSFormat.FormatList
	bean-name = FormatList
	id = FormatList_u6___
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			id = fWVA_
			table-column-count = 6 !
			table-columns-width = "16,16,16,16,16,16" !
		{
			--- TableColumn ---
				column-name = functionName !
				column-type = domain !
				domainAttribute = functionName !
				id = functionName
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = functionName
					previewValue = value
			}
			--- TableColumn ---
				column-name = code !
				column-type = domain !
				domainAttribute = code !
				id = code
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = code
					previewValue = value
			}
			--- TableColumn ---
				column-name = natureE !
				column-type = domain !
				domainAttribute = natureE !
				id = natureE
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = natureE
					previewValue = value
			}
			--- TableColumn ---
				column-name = name !
				column-type = domain !
				domainAttribute = name !
				id = name
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = name
					previewValue = value
			}
			--- TableColumn ---
				column-name = denom !
				column-type = domain !
				domainAttribute = denom !
				id = denom
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = denom
					previewValue = value
			}
			--- TableColumn ---
				column-name = dictEntityName !
				column-type = domain !
				domainAttribute = dictEntityName !
				id = dictEntityName
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = dictEntityName
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = functionName
				sort-rank = 1
			--- TableSort ---
				sort-column-name = code
				sort-rank = 2
		}
	}
}