# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	containment = container
	domainEntity = "AAADSDomain:DomainContext"
	cssClass = nodeco
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = PerformanceIBPASummaryConditions_BU4_H
{
	--- Box ---
		boxType = vertical
	{
		--- Conditional ---
			indexOfSelectedChild = 5
		{
			--- ConditionalBody ---
				javaCode = "Integer.toString(com.odcgroup.aaa.DomainAAAPortfolioDimensionE.Portfolio).equals(<bean:get-property bean=\"DomainContext\" property=\"portfolioDimensionE\"/>.toString())"
				technicalName = Portfolio
				boxType = vertical
				isWidgetVisible = false
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/summary/PerformanceIBPAPortfolioSummary.module
			}
			--- ConditionalBody ---
				javaCode = "Integer.toString(com.odcgroup.aaa.DomainAAAPortfolioDimensionE.PortfolioThirdParty).equals(<bean:get-property bean=\"DomainContext\" property=\"portfolioDimensionE\"/>.toString())"
				technicalName = Client
				boxType = vertical
				isWidgetVisible = false
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/summary/PerformanceIBPAClientSummary.module
			}
			--- ConditionalBody ---
				javaCode = "Integer.toString(com.odcgroup.aaa.DomainAAAPortfolioDimensionE.PortfolioList).equals(<bean:get-property bean=\"DomainContext\" property=\"portfolioDimensionE\"/>.toString())"
				technicalName = "Portfolio List"
				boxType = vertical
				isWidgetVisible = false
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/summary/PerformanceIBPAPortfolioListSummary.module
			}
			--- ConditionalBody ---
				javaCode = "Integer.toString(com.odcgroup.aaa.DomainAAAPortfolioDimensionE.PortfolioAdminManager).equals(<bean:get-property bean=\"DomainContext\" property=\"portfolioDimensionE\"/>.toString())"
				technicalName = Manager
				boxType = vertical
				isWidgetVisible = false
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/summary/PerformanceIBPAManagerSummary.module
			}
			--- ConditionalBody ---
				javaCode = "Integer.toString(com.odcgroup.aaa.DomainAAAPortfolioDimensionE.PortfolioCommManager).equals(<bean:get-property bean=\"DomainContext\" property=\"portfolioDimensionE\"/>.toString())"
				technicalName = Advisor
				boxType = vertical
				isWidgetVisible = false
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/summary/PerformanceIBPAAdvisorSummary.module
			}
			--- ConditionalBody ---
				javaCode = true
				technicalName = Query
				boxType = vertical
				isWidgetSelected = true
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/summary/PerformanceIBPAQuerySummary.module
			}
		}
	}
}