# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	containment = container
	domainEntity = "AAADSDomain:DomainContext"
	cssClass = nodeco
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = PerformanceIBPADetailsConditions_z___3
{
	--- Box ---
		boxType = vertical
	{
		--- Conditional ---
			indexOfSelectedChild = 6
		{
			--- ConditionalBody ---
				javaCode = "Integer.toString(com.odcgroup.aaa.DomainAAAPortfolioDimensionE.Portfolio).equals(<bean:get-property bean=\"DomainContext\" property=\"portfolioDimensionE\"/>.toString())"
				technicalName = Portfolio
				boxType = vertical
				isWidgetVisible = false
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/summary/PerformanceIBPAPortfolioSummaryForDetails.module
				--- Include ---
					includeSrc = "" !
					resource:///Default/detailedlist/PerformanceIBPAPortfolioDetails.module
			}
			--- ConditionalBody ---
				javaCode = "Integer.toString(com.odcgroup.aaa.DomainAAAPortfolioDimensionE.PortfolioThirdParty).equals(<bean:get-property bean=\"DomainContext\" property=\"portfolioDimensionE\"/>.toString())"
				technicalName = Client
				boxType = vertical
				isWidgetVisible = false
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/summary/PerformanceIBPAClientSummaryForDetails.module
				--- Include ---
					includeSrc = "" !
					resource:///Default/detailedlist/PerformanceIBPAClientDetails.module
			}
			--- ConditionalBody ---
				javaCode = "Integer.toString(com.odcgroup.aaa.DomainAAAPortfolioDimensionE.PortfolioList).equals(<bean:get-property bean=\"DomainContext\" property=\"portfolioDimensionE\"/>.toString())"
				technicalName = "Portfolio List"
				boxType = vertical
				isWidgetVisible = false
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/summary/PerformanceIBPAPortfolioListSummaryForDetails.module
				--- Include ---
					includeSrc = "" !
					resource:///Default/detailedlist/PerformanceIBPAPortfolioListDetails.module
			}
			--- ConditionalBody ---
				javaCode = "Integer.toString(com.odcgroup.aaa.DomainAAAPortfolioDimensionE.PortfolioAdminManager).equals(<bean:get-property bean=\"DomainContext\" property=\"portfolioDimensionE\"/>.toString())"
				technicalName = Manager
				boxType = vertical
				isWidgetVisible = false
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/summary/PerformanceIBPAManagerSummaryForDetails.module
				--- Include ---
					includeSrc = "" !
					resource:///Default/detailedlist/PerformanceIBPAManagerDetails.module
			}
			--- ConditionalBody ---
				javaCode = "Integer.toString(com.odcgroup.aaa.DomainAAAPortfolioDimensionE.PortfolioCommManager).equals(<bean:get-property bean=\"DomainContext\" property=\"portfolioDimensionE\"/>.toString())"
				technicalName = Advisor
				boxType = vertical
				isWidgetVisible = false
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/summary/PerformanceIBPAAdvisorSummaryForDetails.module
				--- Include ---
					includeSrc = "" !
					resource:///Default/detailedlist/PerformanceIBPAAdvisorDetails.module
			}
			--- ConditionalBody ---
				javaCode = "Integer.toString(com.odcgroup.aaa.DomainAAAPortfolioDimensionE.Strategy).equals(<bean:get-property bean=\"DomainContext\" property=\"portfolioDimensionE\"/>.toString())"
				technicalName = Strategy
				boxType = vertical
				isWidgetVisible = false
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/summary/PerformanceIBPAStrategySummaryForDetails.module
				--- Include ---
					includeSrc = "" !
					resource:///Default/detailedlist/PerformanceIBPAStrategyDetails.module
			}
			--- ConditionalBody ---
				javaCode = true
				technicalName = Query
				boxType = vertical
				isWidgetSelected = true
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/summary/PerformanceIBPAQuerySummaryForDetails.module
				--- Include ---
					includeSrc = "" !
					resource:///Default/detailedlist/PerformanceIBPAQueryDetails.module
			}
		}
	}
}