/*
* generated by Xtext
*/
package com.odcgroup.t24.menu.validation;
 
import java.util.ArrayList;
import java.util.List;

import org.eclipse.emf.ecore.EPackage;

public class AbstractMenuJavaValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(com.odcgroup.t24.menu.menu.MenuPackage.eINSTANCE);
		return result;
	}

}
