# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSFundWeight:FundWeightList"
	bean-define = DSBean.AAADSFundWeight.FundWeightList
	bean-name = FundWeightList
	id = FundWeightList_O__0X
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			id = D8_7k
			table-column-count = 5 !
			table-columns-width = "20,20,20,20,20" !
		{
			--- TableColumn ---
				column-name = portfolioCode !
				column-type = domain !
				domainAttribute = portfolioCode !
				id = portfolioCode
				table-column-width = 20
			{
				--- TableColumnItem ---
					item-column = portfolioCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = beginD !
				column-type = domain !
				domainAttribute = beginD !
				id = beginD
				table-column-width = 20
			{
				--- TableColumnItem ---
					item-column = beginD
					format = datetime.date-only
					previewValue = value
			}
			--- TableColumn ---
				column-name = instrCode !
				column-type = domain !
				domainAttribute = instrCode !
				id = instrCode
				table-column-width = 20
			{
				--- TableColumnItem ---
					item-column = instrCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = weightP !
				column-type = domain !
				domainAttribute = weightP !
				id = weightP
				table-column-width = 20
			{
				--- TableColumnItem ---
					item-column = weightP
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = shareNumN !
				column-type = domain !
				domainAttribute = shareNumN !
				id = shareNumN
				table-column-width = 20
			{
				--- TableColumnItem ---
					item-column = shareNumN
					format = decimal.detailed
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = portfolioCode
				sort-rank = 1
			--- TableSort ---
				sort-column-name = beginD
				sort-direction = descending
				sort-rank = 2
			--- TableSort ---
				sort-column-name = instrCode
				sort-rank = 3
		}
	}
}