# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Search Results", fr = "Résultats de la recherche", de = Suchergebnisse
	domainEntity = "AAADSReport:ReportSearchResult"
	search = output !
	bean-define = DSBean.AAADSReport.ReportSearchResult
	bean-name = ReportSearchResult
	id = ReportSearchResult1_x03F_
	tid = 97543886515744
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			id = t4o8i
			table-column-count = 24 !
			table-columns-width = "4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4" !
		{
			--- TableColumn ---
				labels en = Status, fr = Statut, de = Status
				column-name = repExecutionStatusE !
				column-type = domain !
				domainAttribute = repExecutionStatusE !
				type = text
				id = repExecutionStatusE
				table-column-width = 4
				tid = 608645893984570
			{
				--- Conditional ---
					indexOfSelectedChild = 2
				{
					--- ConditionalBody ---
						javaCode = "Integer.toString(com.odcgroup.aaa.DomainAAARepExecutionStatusE.Pending).equals(<udp:item column=\"repExecutionStatusE\"/>.toString())"
						technicalName = "In progress"
						boxType = vertical
						isWidgetVisible = false
					{
						--- Icon ---
							toolTips de = "Im Gange", en = "In progress", fr = "En cours"
							horizontalAlignment = center
							icon = hourglass
							id = M_089
							tid = 608290727064473
					}
					--- ConditionalBody ---
						javaCode = "Integer.toString(com.odcgroup.aaa.DomainAAARepExecutionStatusE.Completed).equals(<udp:item column=\"repExecutionStatusE\"/>.toString())"
						technicalName = success
						boxType = vertical
						isWidgetVisible = false
					{
						--- Icon ---
							toolTips en = Ready, fr = "Prêt", de = Bereit
							horizontalAlignment = center
							icon = tick
							id = Ipd__
							tid = 608290728937895
					}
					--- ConditionalBody ---
						javaCode = "Integer.toString(com.odcgroup.aaa.DomainAAARepExecutionStatusE.Failed).equals(<udp:item column=\"repExecutionStatusE\"/>.toString())"
						technicalName = Failure
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips de = "Report-Generierung ist fehlgeschlagen", en = "Report Generation Failed", fr = "Echec de la génération du rapport"
							horizontalAlignment = center
							icon = cross
							id = E4256
							tid = 608290730899038
					}
				}
			}
			--- TableColumn ---
				labels en = Document, fr = Document, de = Dokument
				column-name = reportView
				column-type = placeholder !
				type = text
				column-sortable = false !
				id = A6_V1
				table-column-width = 4
				tid = 572476310705410
			{
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "Integer.toString(com.odcgroup.aaa.DomainAAARepExecutionStatusE.Completed).equals(<udp:item column=\"repExecutionStatusE\"/>.toString())"
						technicalName = success
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips en = "Open Report", de = "Bericht öffnen", fr = "Ouvrir le rapport"
							horizontalAlignment = center
							icon = attach
							id = L3___
							tid = 701208011544976
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "resource:///reporting/ReportView.pageflow"
								target = popup
								only-changed = false
								prevalidate = false
								modal = false
								funcResultCode = "<udp:item column=\"funcResultCode\"/>" ud
								repFileOutputNatureE = "<udp:item column=\"repFileOutputNatureE\"/>" ud
							}
						}
					}
				}
			}
			--- TableColumn ---
				labels en = Id, fr = Id
				column-name = id !
				column-type = domain !
				domainAttribute = id !
				format = integer
				type = text
				column-visibility = not-visible
				id = id
				table-column-width = 4
				tid = 914377602418743
			{
				--- TableColumnItem ---
					item-column = id
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Report Name", fr = "Nom du rapport", de = "Betrag Name"
				column-name = reportName !
				column-type = domain !
				domainAttribute = reportName !
				type = text
				id = reportName
				table-column-width = 4
				tid = 2923947977674816
			{
				--- TableColumnItem ---
					item-column = reportName
					item-halign = lead
					previewValue = value
			}
			--- TableColumn ---
				column-name = fileOutputName !
				column-type = domain !
				domainAttribute = fileOutputName !
				type = text
				id = fileOutputName
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = fileOutputName
					previewValue = value
			}
			--- TableColumn ---
				column-name = repFileOutputNatureE !
				column-type = domain !
				domainAttribute = repFileOutputNatureE !
				type = text
				column-sortable = false
				id = repFileOutputNatureE
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = repFileOutputNatureE
					previewValue = value
			}
			--- TableColumn ---
				column-name = analysisScope !
				column-type = domain !
				domainAttribute = analysisScope !
				type = text
				column-sortable = false
				id = analysisScope
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = analysisScope
					item-halign = lead
					previewValue = value
			}
			--- TableColumn ---
				column-name = analysisScopeObject !
				column-type = domain !
				domainAttribute = analysisScopeObject !
				type = text
				id = analysisScopeObject
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = analysisScopeObject
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Launch Date", de = Erstellungs-Datum, fr = "Date de lancement"
				column-name = launchDate !
				column-type = domain !
				domainAttribute = launchDate !
				type = text
				id = launchDate
				table-column-width = 4
				tid = 2924092274922930
			{
				--- TableColumnItem ---
					item-column = launchDate
					format = datetime.with-seconds
					item-halign = lead
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Created by", fr = "Créé par", de = "Erstellt durch"
				column-name = sessionCreationUserCode !
				column-type = domain !
				domainAttribute = sessionCreationUserCode !
				type = text
				id = sessionCreationUserCode
				table-column-width = 4
				tid = 3009409001718654
			{
				--- TableColumnItem ---
					item-column = sessionCreationUserCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = fromDate !
				column-type = domain !
				domainAttribute = fromDate !
				type = text
				id = fromDate
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = fromDate
					format = datetime.date-only
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Till Date"
				column-name = tillDate !
				column-type = domain !
				domainAttribute = tillDate !
				type = text
				id = tillDate
				table-column-width = 4
				tid = 284437867635843
			{
				--- TableColumnItem ---
					item-column = tillDate
					format = datetime.date-only
					previewValue = value
			}
			--- TableColumn ---
				column-name = loadHierarchyF !
				column-type = domain !
				domainAttribute = loadHierarchyF !
				type = text
				column-visibility = not-visible
				id = loadHierarchyF
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = loadHierarchyF
					previewValue = value
			}
			--- TableColumn ---
				column-name = currencyCode !
				column-type = domain !
				domainAttribute = currencyCode !
				type = text
				column-visibility = not-visible
				id = currencyCode
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = currencyCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = languageDenom !
				column-type = domain !
				domainAttribute = languageDenom !
				type = text
				column-visibility = not-visible
				id = languageDenom
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = languageDenom
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Max Status", fr = "Statut max.", de = "Max Status"
				column-name = maxStatus !
				column-type = domain !
				domainAttribute = maxStatus !
				type = text
				column-visibility = not-visible
				id = maxStatus
				table-column-width = 4
				tid = 284451604612030
			{
				--- TableColumnItem ---
					item-column = maxStatus
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Min Status", fr = "Statut min.", de = "Min Status"
				column-name = minStatus !
				column-type = domain !
				domainAttribute = minStatus !
				type = text
				column-visibility = not-visible
				id = minStatus
				table-column-width = 4
				tid = 284471458070369
			{
				--- TableColumnItem ---
					item-column = minStatus
					previewValue = value
			}
			--- TableColumn ---
				column-name = portConsRuleE !
				column-type = domain !
				domainAttribute = portConsRuleE !
				type = text
				column-sortable = false
				id = portConsRuleE
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = portConsRuleE
					previewValue = value
			}
			--- TableColumn ---
				column-name = funcResultCode !
				column-type = domain !
				domainAttribute = funcResultCode !
				type = text
				column-visibility = never-visible
				id = funcResultCode
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = funcResultCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = entityCode !
				column-type = domain !
				domainAttribute = entityCode !
				format = integer
				type = text
				column-visibility = never-visible
				id = entityCode
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = entityCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = portfolioListCode !
				column-type = domain !
				domainAttribute = portfolioListCode !
				type = text
				column-visibility = never-visible
				id = portfolioListCode
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = portfolioListCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = portfolioCode !
				column-type = domain !
				domainAttribute = portfolioCode !
				type = text
				column-visibility = never-visible
				id = portfolioCode
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = portfolioCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = portfolioThirdPartyCode !
				column-type = domain !
				domainAttribute = portfolioThirdPartyCode !
				type = text
				column-visibility = never-visible
				id = portfolioThirdPartyCode
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = portfolioThirdPartyCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = portfolioAdminMgrCode !
				column-type = domain !
				domainAttribute = portfolioAdminMgrCode !
				type = text
				column-visibility = never-visible
				id = portfolioAdminMgrCode
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = portfolioAdminMgrCode
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = launchDate
				sort-direction = descending
				sort-rank = 1
		}
	}
}