# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels de = "Report Suchbegriffe", en = "Report Search Criteria", fr = "Critères de recherche sur rapports"
	containment = container
	search = container
	cssClass = nodeco
	id = ReportSearch_nfq_q
	tid = 2833597991319008
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			id = Hr_Q_
			indexOfSelectedChild = 1
		{
			--- Tab ---
				labels en = Today, fr = "Aujourd\'hui", de = Heute
				boxType = vertical
				id = tab_rep_searchToday
				isWidgetVisible = false
				tid = 2833866071572225
			{
				Event OnClick (setTabActive) Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = changeTab ud
					only-changed = false
					prevalidate = false
					modal = false
					Snippet Query
					queryAttributes = "currencySearchCode,loadHierarchyF,analysisScopeObject,repFileOutputNatureE,calcTillD,fileOutputName,analysisScope,calcFromD,reportName,portConsRuleE,languageSearchCode,repExecutionStatusE"
					queryOutputModule = "" !
					resource:///Default/module/aaa/reporting/search/ReportSearch.module
					Snippet FilterSet
					id = fs_cI1
					level = 3
					targetDataset = "AAADSReport:ReportSearchCriteria"
					{
						Snippet Filter
						attribute = sessionCreationUserCode
						editMode = readOnly
						filterValue = "$CURRENT_USER_CODE"
						operator = EQUAL
						Snippet Filter
						attribute = sessionCreationD
						editMode = readOnly
						filterValue = "$TODAY"
						operator = GREATER_THAN_OR_EQUAL
					}
				}
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/reporting/search/ReportSearchInput.module
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/reporting/search/TodayReportSearchResult.module
			}
			--- Tab ---
				labels en = All, fr = Tous, de = Alle
				boxType = vertical
				id = tab_rep_searchAll
				isWidgetSelected = true
				tid = 2833805658767245
			{
				Event OnClick (setTabActive) Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = changeTab ud
					only-changed = false
					prevalidate = false
					modal = false
					Snippet Query
					queryAttributes = "currencySearchCode,loadHierarchyF,fileOutputName,analysisScope,calcFromD,sessionCreationUserSearchCode,portConsRuleE,repExecutionStatusE,analysisScopeObject,repFileOutputNatureE,calcTillD,sessionCreationD,reportName,languageSearchCode"
					queryOutputModule = "" !
					resource:///Default/module/aaa/reporting/search/ReportSearch.module
					runAtStart = false
					Snippet FilterSet
					id = fs_St4
					level = 3
					targetDataset = "AAADSReport:ReportSearchCriteria"
					{
						Snippet Filter
						attribute = sessionStatusE
						filterValue = None
						operator = DIFFERENT
						Snippet Filter
						attribute = reportName
						editMode = editable
						filterValue = "*"
						operator = LIKE
					}
				}
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/reporting/search/ReportSearchInput.module
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/reporting/search/ReportSearchResult.module
			}
		}
	}
}