# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Report Search Criteria", fr = "Critères de recherche sur rapports", de = "Report Suchbegriffe"
	containment = container
	domainEntity = "AAADSReport:ReportSearchCriteria"
	search = input !
	bean-define = DSBean.AAADSReport.ReportSearchCriteria
	bean-name = ReportSearchCriteria
	id = ReportSearchInput_Y_5_7
	tid = 96463493329459
{
	--- Box ---
		boxType = vertical
	{
		--- FilterCriteria ---
			includedFile = "resource:/com/module/search/QueryBuilder.xsp"
		--- Include ---
			includeSrc = "" !
			resource:///default/search/NavigationReportingSearch.fragment
	}
}