# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Search Results", fr = "Résultats de la recherche", de = Suchergebnisse
	domainEntity = "AAADSReport:ReportSearchResult"
	search = output !
	bean-define = DSBean.AAADSReport.ReportSearchResult
	bean-name = ReportSearchResult
	id = TodayReportSearchResult_k__Y8
	tid = 238164543506786
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			id = c_12n
			table-column-count = 25 !
			table-columns-width = "4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4" !
		{
			--- TableColumn ---
				labels en = Status, fr = Statut, de = Status
				column-name = repExecutionStatusE !
				column-type = domain !
				domainAttribute = repExecutionStatusE !
				type = text
				id = repExecutionStatusE
				table-column-width = 4
				tid = 608686484344518
			{
				--- Conditional ---
					indexOfSelectedChild = 2
				{
					--- ConditionalBody ---
						javaCode = "Integer.toString(com.odcgroup.aaa.DomainAAARepExecutionStatusE.Pending).equals(<udp:item column=\"repExecutionStatusE\"/>.toString())"
						technicalName = "In progress"
						boxType = vertical
						isWidgetVisible = false
					{
						--- Icon ---
							toolTips en = "In progress", fr = "En cours", de = "Im Gange"
							horizontalAlignment = center
							icon = hourglass
							id = z9WoD
							tid = 606711490834449
					}
					--- ConditionalBody ---
						javaCode = "Integer.toString(com.odcgroup.aaa.DomainAAARepExecutionStatusE.Completed).equals(<udp:item column=\"repExecutionStatusE\"/>.toString())"
						technicalName = success
						boxType = vertical
						isWidgetVisible = false
					{
						--- Icon ---
							toolTips en = Ready, fr = "Prêt", de = Bereit
							horizontalAlignment = center
							icon = tick
							id = FL520
							tid = 606711493750462
					}
					--- ConditionalBody ---
						javaCode = "Integer.toString(com.odcgroup.aaa.DomainAAARepExecutionStatusE.Failed).equals(<udp:item column=\"repExecutionStatusE\"/>.toString())"
						technicalName = Failure
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips en = "Report Generation Failed", fr = "Echec de la génération du rapport", de = "Report-Generierung ist fehlgeschlagen"
							horizontalAlignment = center
							icon = cross
							id = gZ_C8
							tid = 606711495689815
					}
				}
			}
			--- TableColumn ---
				labels en = Document, fr = Document, de = Dokument
				column-name = reportView
				column-type = placeholder !
				type = text
				column-sortable = false !
				id = wQTr_
				table-column-width = 4
				tid = 573823324306860
			{
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "Integer.toString(com.odcgroup.aaa.DomainAAARepExecutionStatusE.Completed).equals(<udp:item column=\"repExecutionStatusE\"/>.toString())"
						technicalName = success
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips en = "Open Report", fr = "Ouvrir le rapport", de = "Bericht öffnen"
							horizontalAlignment = center
							icon = attach
							id = Uw6__
							tid = 700475514743145
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "resource:///reporting/ReportView.pageflow"
								target = popup
								only-changed = false
								prevalidate = false
								modal = false
								funcResultCode = "<udp:item column=\"funcResultCode\"/>" ud
								repFileOutputNatureE = "<udp:item column=\"repFileOutputNatureE\"/>" ud
							}
						}
					}
				}
			}
			--- TableColumn ---
				column-name = funcResultCode !
				column-type = domain !
				domainAttribute = funcResultCode !
				type = text
				column-visibility = never-visible
				id = funcResultCode
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = funcResultCode
					previewValue = value
			}
			--- TableColumn ---
				labels en = Id, fr = Id
				column-name = id !
				column-type = domain !
				domainAttribute = id !
				format = integer
				type = text
				column-visibility = not-visible
				id = id
				table-column-width = 4
				tid = 914326100692406
			{
				--- TableColumnItem ---
					item-column = id
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Report Name", fr = "Nom du rapport", de = "Betrag Name"
				column-name = reportName !
				column-type = domain !
				domainAttribute = reportName !
				type = text
				id = reportName
				table-column-width = 4
				tid = 268371085089046
			{
				--- TableColumnItem ---
					item-column = reportName
					previewValue = value
			}
			--- TableColumn ---
				column-name = fileOutputName !
				column-type = domain !
				domainAttribute = fileOutputName !
				type = text
				id = fileOutputName
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = fileOutputName
					previewValue = value
			}
			--- TableColumn ---
				column-name = repFileOutputNatureE !
				column-type = domain !
				domainAttribute = repFileOutputNatureE !
				type = text
				column-sortable = false
				id = repFileOutputNatureE
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = repFileOutputNatureE
					previewValue = value
			}
			--- TableColumn ---
				column-name = analysisScope !
				column-type = domain !
				domainAttribute = analysisScope !
				type = text
				column-sortable = false
				id = analysisScope
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = analysisScope
					previewValue = value
			}
			--- TableColumn ---
				column-name = analysisScopeObject !
				column-type = domain !
				domainAttribute = analysisScopeObject !
				type = text
				id = analysisScopeObject
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = analysisScopeObject
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Launch Date", fr = "Date de lancement", de = Starttermin
				column-name = launchDate !
				column-type = domain !
				domainAttribute = launchDate !
				type = text
				id = launchDate
				table-column-width = 4
				tid = 255459620155913
			{
				--- TableColumnItem ---
					item-column = launchDate
					format = datetime.with-seconds
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Created by", fr = "Créé par", de = "Erstellt durch"
				column-name = sessionCreationUserCode !
				column-type = domain !
				domainAttribute = sessionCreationUserCode !
				type = text
				column-visibility = not-visible
				id = sessionCreationUserCode
				table-column-width = 4
				tid = 920276010821487
			{
				--- TableColumnItem ---
					item-column = sessionCreationUserCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = fromDate !
				column-type = domain !
				domainAttribute = fromDate !
				type = text
				id = fromDate
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = fromDate
					format = datetime.date-only
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Till Date"
				column-name = tillDate !
				column-type = domain !
				domainAttribute = tillDate !
				type = text
				id = tillDate
				table-column-width = 4
				tid = 284029695512566
			{
				--- TableColumnItem ---
					item-column = tillDate
					format = datetime.date-only
					previewValue = value
			}
			--- TableColumn ---
				column-name = loadHierarchyF !
				column-type = domain !
				domainAttribute = loadHierarchyF !
				type = text
				column-visibility = not-visible
				id = loadHierarchyF
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = loadHierarchyF
					previewValue = value
			}
			--- TableColumn ---
				column-name = currencyCode !
				column-type = domain !
				domainAttribute = currencyCode !
				type = text
				column-visibility = not-visible
				id = currencyCode
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = currencyCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = languageDenom !
				column-type = domain !
				domainAttribute = languageDenom !
				type = text
				column-visibility = not-visible
				id = languageDenom
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = languageDenom
					previewValue = value
			}
			--- TableColumn ---
				column-name = portConsRuleE !
				column-type = domain !
				domainAttribute = portConsRuleE !
				type = text
				column-sortable = false
				id = portConsRuleE
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = portConsRuleE
					previewValue = value
			}
			--- TableColumn ---
				column-name = parentSessionId !
				column-type = domain !
				domainAttribute = parentSessionId !
				type = text
				column-visibility = never-visible
				id = parentSessionId
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = parentSessionId
					format = integer
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Min Status", fr = "Statut min.", de = "Min Status"
				column-name = minStatus !
				column-type = domain !
				domainAttribute = minStatus !
				type = text
				column-visibility = not-visible
				id = minStatus
				table-column-width = 4
				tid = 284356478540622
			{
				--- TableColumnItem ---
					item-column = minStatus
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Max Status", fr = "Statut max.", de = "Max Status"
				column-name = maxStatus !
				column-type = domain !
				domainAttribute = maxStatus !
				type = text
				column-visibility = not-visible
				id = maxStatus
				table-column-width = 4
				tid = 284387107461774
			{
				--- TableColumnItem ---
					item-column = maxStatus
					previewValue = value
			}
			--- TableColumn ---
				column-name = entityCode !
				column-type = domain !
				domainAttribute = entityCode !
				format = integer
				type = text
				column-visibility = never-visible
				id = entityCode
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = entityCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = portfolioCode !
				column-type = domain !
				domainAttribute = portfolioCode !
				type = text
				column-visibility = never-visible
				id = portfolioCode
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = portfolioCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = portfolioListCode !
				column-type = domain !
				domainAttribute = portfolioListCode !
				type = text
				column-visibility = never-visible
				id = portfolioListCode
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = portfolioListCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = portfolioThirdPartyCode !
				column-type = domain !
				domainAttribute = portfolioThirdPartyCode !
				type = text
				column-visibility = never-visible
				id = portfolioThirdPartyCode
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = portfolioThirdPartyCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = portfolioAdminMgrCode !
				column-type = domain !
				domainAttribute = portfolioAdminMgrCode !
				type = text
				column-visibility = never-visible
				id = portfolioAdminMgrCode
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = portfolioAdminMgrCode
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = launchDate
				sort-direction = descending
				sort-rank = 1
		}
	}
}