# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSPerformance:PerformanceIBPADetails"
	cssClass = nodeco
	bean-define = DSBean.AAADSPerformance.PerformanceIBPADetails
	bean-name = PerformanceIBPADetails
	id = PerformanceIBPADetailsPerMktSeg_kum__
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			table-page-size = 250
			id = q_Y9e
			table-column-count = 52 !
			table-columns-width = "1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1" !
		{
			--- TableColumn ---
				labels en = "Market Segment / Period", fr = "Segment de marché / période", de = "Marktsegment / Periode"
				column-display-grouping = true
				column-name = GROUPING
				column-type = placeholder !
				type = text
				column-locked = true
				column-sortable = false !
				id = s7_M_
				table-column-width = 1
				tid = 278593948607751
			{
				--- TableGroup ---
					aggregateData = false
					group-column-name = PERIOD
					group-sorting-column-name = PERIOD_SORT
					group-sorting-direction = ascending
					hierarchy = true
					group-rank = 1
			}
			--- TableColumn ---
				labels en = "Initial Market Value", fr = "Valeur d\'inventaire initiale", de = Anfangs-Marktwert
				column-name = IntialMarketValue
				type = amount
				column-sortable = false
				column-visibility = not-visible
				id = LZ_d_
				column-computation = make-amount
				column-computation-parameters = "INITIAL_MARKET_VALUE,REF_CURRENCY"
				table-column-width = 1
				tid = 278593950607163
			{
				--- TableColumnItem ---
					item-column = IntialMarketValue
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Final Market Value", fr = "Valeur d\'inventaire finale", de = End-Marktwert
				column-name = FinalMarketValue
				type = amount
				column-sortable = false
				column-visibility = not-visible
				id = Q_N6X
				column-computation = make-amount
				column-computation-parameters = "FINAL_MARKET_VALUE,REF_CURRENCY"
				table-column-width = 1
				tid = 278593952514224
			{
				--- TableColumnItem ---
					item-column = FinalMarketValue
					previewValue = value
			}
			--- TableColumn ---
				column-name = WEIGHT !
				column-type = domain !
				domainAttribute = WEIGHT !
				type = text
				column-sortable = false
				id = WEIGHT
				table-column-width = 1
			{
				--- TableColumnItem ---
					item-column = WEIGHT
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = PTF_RETURN !
				column-type = domain !
				domainAttribute = PTF_RETURN !
				type = text
				column-sortable = false
				id = PTF_RETURN
				table-column-width = 1
			{
				--- TableColumnItem ---
					item-column = PTF_RETURN
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = PTF_RETURN_CONTRIBUTION !
				column-type = domain !
				domainAttribute = PTF_RETURN_CONTRIBUTION !
				type = text
				column-sortable = false
				id = PTF_RETURN_CONTRIBUTION
				table-column-width = 1
			{
				--- TableColumnItem ---
					item-column = PTF_RETURN_CONTRIBUTION
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = PTF_DURATION !
				column-type = domain !
				domainAttribute = PTF_DURATION !
				type = text
				column-sortable = false
				column-visibility = not-visible
				id = PTF_DURATION
				table-column-width = 1
			{
				--- TableColumnItem ---
					item-column = PTF_DURATION
					previewValue = value
			}
			--- TableColumn ---
				column-name = PTF_DURATION_CONTRIBUTION !
				column-type = domain !
				domainAttribute = PTF_DURATION_CONTRIBUTION !
				type = text
				column-sortable = false
				column-visibility = not-visible
				id = PTF_DURATION_CONTRIBUTION
				table-column-width = 1
			{
				--- TableColumnItem ---
					item-column = PTF_DURATION_CONTRIBUTION
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_WEIGHT !
				column-type = domain !
				domainAttribute = B1_WEIGHT !
				type = text
				column-sortable = false
				id = B1_WEIGHT
				table-column-width = 1
			{
				--- TableColumnItem ---
					item-column = B1_WEIGHT
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_RETURN !
				column-type = domain !
				domainAttribute = B1_RETURN !
				type = text
				column-sortable = false
				id = B1_RETURN
				table-column-width = 1
			{
				--- TableColumnItem ---
					item-column = B1_RETURN
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_RETURN_CONTRIBUTION !
				column-type = domain !
				domainAttribute = B1_RETURN_CONTRIBUTION !
				type = text
				column-sortable = false
				id = B1_RETURN_CONTRIBUTION
				table-column-width = 1
			{
				--- TableColumnItem ---
					item-column = B1_RETURN_CONTRIBUTION
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_DURATION !
				column-type = domain !
				domainAttribute = B1_DURATION !
				format = percentTA
				type = text
				column-sortable = false
				column-visibility = not-visible
				id = B1_DURATION
				table-column-width = 1
			{
				--- TableColumnItem ---
					item-column = B1_DURATION
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_DURATION_CONTRIBUTION !
				column-type = domain !
				domainAttribute = B1_DURATION_CONTRIBUTION !
				format = percentTA
				type = text
				column-sortable = false
				column-visibility = not-visible
				id = B1_DURATION_CONTRIBUTION
				table-column-width = 1
			{
				--- TableColumnItem ---
					item-column = B1_DURATION_CONTRIBUTION
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_BENCHMARK_FACTOR !
				column-type = domain !
				domainAttribute = B1_BENCHMARK_FACTOR !
				type = text
				column-sortable = false
				id = B1_BENCHMARK_FACTOR
				table-column-width = 1
			{
				--- TableColumnItem ---
					item-column = B1_BENCHMARK_FACTOR
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = IB1_EFFECT_DENOM !
				column-type = domain !
				domainAttribute = IB1_EFFECT_DENOM !
				type = text
				column-sortable = false
				id = IB1_EFFECT_DENOM
				table-column-width = 1
			{
				--- TableColumnItem ---
					item-column = IB1_EFFECT_DENOM
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_IB1_WEIGHT !
				column-type = domain !
				domainAttribute = B1_IB1_WEIGHT !
				type = text
				column-sortable = false
				column-visibility = not-visible
				id = B1_IB1_WEIGHT
				table-column-width = 1
			{
				--- TableColumnItem ---
					item-column = B1_IB1_WEIGHT
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_IB1_RETURN !
				column-type = domain !
				domainAttribute = B1_IB1_RETURN !
				type = text
				column-sortable = false
				column-visibility = not-visible
				id = B1_IB1_RETURN
				table-column-width = 1
			{
				--- TableColumnItem ---
					item-column = B1_IB1_RETURN
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_IB1_CONTRIBUTION !
				column-type = domain !
				domainAttribute = B1_IB1_CONTRIBUTION !
				type = text
				column-sortable = false
				column-visibility = not-visible
				id = B1_IB1_CONTRIBUTION
				table-column-width = 1
			{
				--- TableColumnItem ---
					item-column = B1_IB1_CONTRIBUTION
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_IB1_DURATION !
				column-type = domain !
				domainAttribute = B1_IB1_DURATION !
				type = text
				column-sortable = false
				column-visibility = not-visible
				id = B1_IB1_DURATION
				table-column-width = 1
			{
				--- TableColumnItem ---
					item-column = B1_IB1_DURATION
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_IB1_DURATION_CONTRIBUTION !
				column-type = domain !
				domainAttribute = B1_IB1_DURATION_CONTRIBUTION !
				type = text
				column-sortable = false
				column-visibility = not-visible
				id = B1_IB1_DURATION_CONTRIBUTION
				table-column-width = 1
			{
				--- TableColumnItem ---
					item-column = B1_IB1_DURATION_CONTRIBUTION
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_IB1_EFFECT !
				column-type = domain !
				domainAttribute = B1_IB1_EFFECT !
				type = text
				column-sortable = false
				id = B1_IB1_EFFECT
				table-column-width = 1
			{
				--- TableColumnItem ---
					item-column = B1_IB1_EFFECT
					format = percentTA
					previewValue = value
				--- Spacer ---
					height = 4
					width = 10
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "<udp:item column=\"B1_IB1_EFFECT\"/>!=null"
						technicalName = "Effect 1"
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips en = "View Effect 1 Details", fr = "Voir les détails de l\'effet 1", de = "Details des Effekts 1 ansehen"
							horizontalAlignment = trail
							icon = application_form_magnify
							id = i5g__
							tid = 112579368086403
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = popup
								flow-action = getEffect1MktSeg ud
								only-changed = false
								prevalidate = false
								modal = false
								Snippet FilterSet
								id = fs_5NL
								level = 1
								targetDataset = "AAADSPerformance:PerformanceIBPAEffectFocusDetails"
								{
									Snippet Filter
									attribute = PERIOD
									filterValue = "<udp:item column=\"PERIOD\"/>"
									operator = EQUAL
								}
							}
						}
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetVisible = false
				}
			}
			--- TableColumn ---
				column-name = IB2_EFFECT_DENOM !
				column-type = domain !
				domainAttribute = IB2_EFFECT_DENOM !
				type = text
				column-sortable = false
				id = IB2_EFFECT_DENOM
				table-column-width = 1
			{
				--- TableColumnItem ---
					item-column = IB2_EFFECT_DENOM
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_IB2_WEIGHT !
				column-type = domain !
				domainAttribute = B1_IB2_WEIGHT !
				type = text
				column-sortable = false
				column-visibility = not-visible
				id = B1_IB2_WEIGHT
				table-column-width = 1
			{
				--- TableColumnItem ---
					item-column = B1_IB2_WEIGHT
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_IB2_RETURN !
				column-type = domain !
				domainAttribute = B1_IB2_RETURN !
				type = text
				column-sortable = false
				column-visibility = not-visible
				id = B1_IB2_RETURN
				table-column-width = 1
			{
				--- TableColumnItem ---
					item-column = B1_IB2_RETURN
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_IB2_CONTRIBUTION !
				column-type = domain !
				domainAttribute = B1_IB2_CONTRIBUTION !
				type = text
				column-sortable = false
				column-visibility = not-visible
				id = B1_IB2_CONTRIBUTION
				table-column-width = 1
			{
				--- TableColumnItem ---
					item-column = B1_IB2_CONTRIBUTION
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_IB2_DURATION !
				column-type = domain !
				domainAttribute = B1_IB2_DURATION !
				type = text
				column-sortable = false
				column-visibility = not-visible
				id = B1_IB2_DURATION
				table-column-width = 1
			{
				--- TableColumnItem ---
					item-column = B1_IB2_DURATION
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_IB2_DURATION_CONTRIBUTION !
				column-type = domain !
				domainAttribute = B1_IB2_DURATION_CONTRIBUTION !
				type = text
				column-sortable = false
				column-visibility = not-visible
				id = B1_IB2_DURATION_CONTRIBUTION
				table-column-width = 1
			{
				--- TableColumnItem ---
					item-column = B1_IB2_DURATION_CONTRIBUTION
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_IB2_EFFECT !
				column-type = domain !
				domainAttribute = B1_IB2_EFFECT !
				type = text
				column-sortable = false
				id = B1_IB2_EFFECT
				table-column-width = 1
			{
				--- TableColumnItem ---
					item-column = B1_IB2_EFFECT
					format = percentTA
					previewValue = value
				--- Spacer ---
					height = 4
					width = 10
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "<udp:item column=\"B1_IB2_EFFECT\"/>!=null"
						technicalName = "Effect 2"
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips de = "Details des Effekts 2 ansehen", fr = "Voir les détails de l\'effet 2", en = "View Effect 2 Details"
							horizontalAlignment = trail
							icon = application_form_magnify
							id = Q1_i_
							tid = 112596829255656
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = popup
								flow-action = getEffect2MktSeg ud
								only-changed = false
								prevalidate = false
								modal = false
								Snippet FilterSet
								id = fs_5NL
								level = 1
								targetDataset = "AAADSPerformance:PerformanceIBPAEffectFocusDetails"
								{
									Snippet Filter
									attribute = PERIOD
									filterValue = "<udp:item column=\"PERIOD\"/>"
									operator = EQUAL
								}
							}
						}
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetVisible = false
				}
			}
			--- TableColumn ---
				column-name = IB3_EFFECT_DENOM !
				column-type = domain !
				domainAttribute = IB3_EFFECT_DENOM !
				type = text
				column-sortable = false
				id = IB3_EFFECT_DENOM
				table-column-width = 1
			{
				--- TableColumnItem ---
					item-column = IB3_EFFECT_DENOM
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_IB3_WEIGHT !
				column-type = domain !
				domainAttribute = B1_IB3_WEIGHT !
				type = text
				column-sortable = false
				column-visibility = not-visible
				id = B1_IB3_WEIGHT
				table-column-width = 1
			{
				--- TableColumnItem ---
					item-column = B1_IB3_WEIGHT
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_IB3_RETURN !
				column-type = domain !
				domainAttribute = B1_IB3_RETURN !
				type = text
				column-sortable = false
				column-visibility = not-visible
				id = B1_IB3_RETURN
				table-column-width = 1
			{
				--- TableColumnItem ---
					item-column = B1_IB3_RETURN
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_IB3_CONTRIBUTION !
				column-type = domain !
				domainAttribute = B1_IB3_CONTRIBUTION !
				type = text
				column-sortable = false
				column-visibility = not-visible
				id = B1_IB3_CONTRIBUTION
				table-column-width = 1
			{
				--- TableColumnItem ---
					item-column = B1_IB3_CONTRIBUTION
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_IB3_DURATION !
				column-type = domain !
				domainAttribute = B1_IB3_DURATION !
				type = text
				column-sortable = false
				column-visibility = not-visible
				id = B1_IB3_DURATION
				table-column-width = 1
			{
				--- TableColumnItem ---
					item-column = B1_IB3_DURATION
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_IB3_DURATION_CONTRIBUTION !
				column-type = domain !
				domainAttribute = B1_IB3_DURATION_CONTRIBUTION !
				type = text
				column-sortable = false
				column-visibility = not-visible
				id = B1_IB3_DURATION_CONTRIBUTION
				table-column-width = 1
			{
				--- TableColumnItem ---
					item-column = B1_IB3_DURATION_CONTRIBUTION
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_IB3_EFFECT !
				column-type = domain !
				domainAttribute = B1_IB3_EFFECT !
				type = text
				column-sortable = false
				id = B1_IB3_EFFECT
				table-column-width = 1
			{
				--- TableColumnItem ---
					item-column = B1_IB3_EFFECT
					format = percentTA
					previewValue = value
				--- Spacer ---
					height = 4
					width = 10
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "<udp:item column=\"B1_IB3_EFFECT\"/>!=null"
						technicalName = "Effect 3"
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips de = "Details des Effekts 3 ansehen", fr = "Voir les détails de l\'effet 3", en = "View Effect 3 Details"
							horizontalAlignment = trail
							icon = application_form_magnify
							id = O___f
							tid = 112699374345500
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = popup
								flow-action = getEffect3MktSeg ud
								only-changed = false
								prevalidate = false
								modal = false
								Snippet FilterSet
								id = fs_5NL
								level = 1
								targetDataset = "AAADSPerformance:PerformanceIBPAEffectFocusDetails"
								{
									Snippet Filter
									attribute = PERIOD
									filterValue = "<udp:item column=\"PERIOD\"/>"
									operator = EQUAL
								}
							}
						}
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetVisible = false
				}
			}
			--- TableColumn ---
				column-name = IB4_EFFECT_DENOM !
				column-type = domain !
				domainAttribute = IB4_EFFECT_DENOM !
				type = text
				column-sortable = false
				column-visibility = not-visible
				id = IB4_EFFECT_DENOM
				table-column-width = 1
			{
				--- TableColumnItem ---
					item-column = IB4_EFFECT_DENOM
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_IB4_WEIGHT !
				column-type = domain !
				domainAttribute = B1_IB4_WEIGHT !
				type = text
				column-sortable = false
				column-visibility = not-visible
				id = B1_IB4_WEIGHT
				table-column-width = 1
			{
				--- TableColumnItem ---
					item-column = B1_IB4_WEIGHT
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_IB4_RETURN !
				column-type = domain !
				domainAttribute = B1_IB4_RETURN !
				type = text
				column-sortable = false
				column-visibility = not-visible
				id = B1_IB4_RETURN
				table-column-width = 1
			{
				--- TableColumnItem ---
					item-column = B1_IB4_RETURN
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_IB4_CONTRIBUTION !
				column-type = domain !
				domainAttribute = B1_IB4_CONTRIBUTION !
				type = text
				column-sortable = false
				column-visibility = not-visible
				id = B1_IB4_CONTRIBUTION
				table-column-width = 1
			{
				--- TableColumnItem ---
					item-column = B1_IB4_CONTRIBUTION
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_IB4_DURATION !
				column-type = domain !
				domainAttribute = B1_IB4_DURATION !
				type = text
				column-sortable = false
				column-visibility = not-visible
				id = B1_IB4_DURATION
				table-column-width = 1
			{
				--- TableColumnItem ---
					item-column = B1_IB4_DURATION
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_IB4_DURATION_CONTRIBUTION !
				column-type = domain !
				domainAttribute = B1_IB4_DURATION_CONTRIBUTION !
				type = text
				column-sortable = false
				column-visibility = not-visible
				id = B1_IB4_DURATION_CONTRIBUTION
				table-column-width = 1
			{
				--- TableColumnItem ---
					item-column = B1_IB4_DURATION_CONTRIBUTION
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_IB4_EFFECT !
				column-type = domain !
				domainAttribute = B1_IB4_EFFECT !
				type = text
				column-sortable = false
				column-visibility = not-visible
				id = B1_IB4_EFFECT
				table-column-width = 1
			{
				--- TableColumnItem ---
					item-column = B1_IB4_EFFECT
					format = percentTA
					previewValue = value
				--- Spacer ---
					height = 4
					width = 10
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "<udp:item column=\"B1_IB4_EFFECT\"/>!=null"
						technicalName = "Effect 4"
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips de = "Details des Effekts 4 ansehen", fr = "Voir les détails de l\'effet 4", en = "View Effect 4 Details"
							horizontalAlignment = trail
							icon = application_form_magnify
							id = T__8_
							tid = 112753866139222
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = popup
								flow-action = getEffect4MktSeg ud
								only-changed = false
								prevalidate = false
								modal = false
								Snippet FilterSet
								id = fs_5NL
								level = 1
								targetDataset = "AAADSPerformance:PerformanceIBPAEffectFocusDetails"
								{
									Snippet Filter
									attribute = PERIOD
									filterValue = "<udp:item column=\"PERIOD\"/>"
									operator = EQUAL
								}
							}
						}
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetVisible = false
				}
			}
			--- TableColumn ---
				column-name = IB5_EFFECT_DENOM !
				column-type = domain !
				domainAttribute = IB5_EFFECT_DENOM !
				type = text
				column-sortable = false
				column-visibility = not-visible
				id = IB5_EFFECT_DENOM
				table-column-width = 1
			{
				--- TableColumnItem ---
					item-column = IB5_EFFECT_DENOM
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_IB5_WEIGHT !
				column-type = domain !
				domainAttribute = B1_IB5_WEIGHT !
				type = text
				column-sortable = false
				column-visibility = not-visible
				id = B1_IB5_WEIGHT
				table-column-width = 1
			{
				--- TableColumnItem ---
					item-column = B1_IB5_WEIGHT
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_IB5_RETURN !
				column-type = domain !
				domainAttribute = B1_IB5_RETURN !
				type = text
				column-sortable = false
				column-visibility = not-visible
				id = B1_IB5_RETURN
				table-column-width = 1
			{
				--- TableColumnItem ---
					item-column = B1_IB5_RETURN
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_IB5_CONTRIBUTION !
				column-type = domain !
				domainAttribute = B1_IB5_CONTRIBUTION !
				type = text
				column-sortable = false
				column-visibility = not-visible
				id = B1_IB5_CONTRIBUTION
				table-column-width = 1
			{
				--- TableColumnItem ---
					item-column = B1_IB5_CONTRIBUTION
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_IB5_DURATION !
				column-type = domain !
				domainAttribute = B1_IB5_DURATION !
				type = text
				column-sortable = false
				column-visibility = not-visible
				id = B1_IB5_DURATION
				table-column-width = 1
			{
				--- TableColumnItem ---
					item-column = B1_IB5_DURATION
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_IB5_DURATION_CONTRIBUTION !
				column-type = domain !
				domainAttribute = B1_IB5_DURATION_CONTRIBUTION !
				type = text
				column-sortable = false
				column-visibility = not-visible
				id = B1_IB5_DURATION_CONTRIBUTION
				table-column-width = 1
			{
				--- TableColumnItem ---
					item-column = B1_IB5_DURATION_CONTRIBUTION
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_IB5_EFFECT !
				column-type = domain !
				domainAttribute = B1_IB5_EFFECT !
				type = text
				column-sortable = false
				column-visibility = not-visible
				id = B1_IB5_EFFECT
				table-column-width = 1
			{
				--- TableColumnItem ---
					item-column = B1_IB5_EFFECT
					format = percentTA
					previewValue = value
				--- Spacer ---
					height = 4
					width = 10
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "<udp:item column=\"B1_IB5_EFFECT\"/>!=null"
						technicalName = "Effect 5"
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips de = "Details des Effekts 5 ansehen", fr = "Voir les détails de l\'effet 5", en = "View Effect 5 Details"
							horizontalAlignment = trail
							icon = application_form_magnify
							id = iq3_2
							tid = 112841818041316
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = popup
								flow-action = getEffect5MktSeg ud
								only-changed = false
								prevalidate = false
								modal = false
								Snippet FilterSet
								id = fs_5NL
								level = 1
								targetDataset = "AAADSPerformance:PerformanceIBPAEffectFocusDetails"
								{
									Snippet Filter
									attribute = PERIOD
									filterValue = "<udp:item column=\"PERIOD\"/>"
									operator = EQUAL
								}
							}
						}
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetVisible = false
				}
			}
			--- TableColumn ---
				column-name = B1_MARKET_SELECTION !
				column-type = domain !
				domainAttribute = B1_MARKET_SELECTION !
				format = percentTA
				type = text
				column-sortable = false
				column-visibility = not-visible
				id = B1_MARKET_SELECTION
				table-column-width = 1
			{
				--- TableColumnItem ---
					item-column = B1_MARKET_SELECTION
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_STOCK_PICKING !
				column-type = domain !
				domainAttribute = B1_STOCK_PICKING !
				format = percentTA
				type = text
				column-sortable = false
				id = B1_STOCK_PICKING
				table-column-width = 1
			{
				--- TableColumnItem ---
					item-column = B1_STOCK_PICKING
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_INTERACTION !
				column-type = domain !
				domainAttribute = B1_INTERACTION !
				format = percentTA
				type = text
				column-sortable = false
				id = B1_INTERACTION
				table-column-width = 1
			{
				--- TableColumnItem ---
					item-column = B1_INTERACTION
					format = percentTA
					previewValue = value
			}
			--- TableKeepFilter ---
				keep-filter-column-name = PERIOD_FILTER
				keep-filter-operand = 1
			--- TableSort ---
				sort-column-name = PERIOD_SORT
				sort-rank = 2
			--- TableSort ---
				sort-column-name = INITIAL_DATE
				sort-rank = 3
			--- TableExtra ---
				domainAttribute = BENCHMARK1_FULL_NAME
		}
	}
}