# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Intermediate Benchmark Performance Attribution Details per Advisor", fr = "Détails de l\'attribution de performance (benchmarks intermédiaires) par conseiller", de = "Mehrstufige Performance Attribution mit Details per Berater"
	containment = container
	domainEntity = "AAADSPerformance:PerformanceIBPADetails"
	bean-define = DSBean.AAADSPerformance.PerformanceIBPADetails
	bean-name = PerformanceIBPADetails
	id = PerformanceIBPAAdvisorDetails_gj3Wi
	tid = 278311546316899
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			id = b590_
			indexOfSelectedChild = 0
		{
			--- Tab ---
				labels en = "By Period", fr = "Par période", de = "Per Periode"
				id = tab_Rj3_5
				isWidgetSelected = true
				tid = 278491468749524
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/detailedlist/PerformanceIBPADetailsPerPeriode.module
			}
			--- Tab ---
				labels en = "By Market Segment", fr = "Par segment de marché", de = "Per Marktsegment"
				id = tab_g3___
				isWidgetVisible = false
				tid = 278511383877489
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/detailedlist/PerformanceIBPADetailsPerMktSeg.module
			}
		}
	}
}