# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Intermediate Benchmark Performance Attribution Details per Portfolio List", fr = "Détails de l\'attribution de performance (benchmarks intermédiaires) par liste de portefeuille", de = "Mehrstufige Performance Attribution mit Details per Portfolioliste"
	containment = container
	domainEntity = "AAADSPerformance:PerformanceIBPADetails"
	bean-define = DSBean.AAADSPerformance.PerformanceIBPADetails
	bean-name = PerformanceIBPADetails
	id = PerformanceIBPAPortfolioListDetails_S5_59
	tid = 278373484560590
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			id = c_1_R
			indexOfSelectedChild = 0
		{
			--- Tab ---
				labels en = "By Period", fr = "Par période", de = "Per Periode"
				id = tab_S6_0z
				isWidgetSelected = true
				tid = 279033124822543
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/detailedlist/PerformanceIBPADetailsPerPeriode.module
			}
			--- Tab ---
				labels en = "By Market Segment", fr = "Par segment de marché", de = "Per Marktsegment"
				id = tab_R9h9P
				isWidgetVisible = false
				tid = 279033126773318
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/detailedlist/PerformanceIBPADetailsPerMktSeg.module
			}
		}
	}
}