# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Intermediate Benchmark Performance Attribution Details per Strategy", fr = "Détails de l\'attribution de performance (benchmarks intermédiaires) par stratégie", de = "Mehrstufige Performance Attribution mit Details per Strategie"
	containment = container
	domainEntity = "AAADSPerformance:PerformanceIBPADetails"
	bean-define = DSBean.AAADSPerformance.PerformanceIBPADetails
	bean-name = PerformanceIBPADetails
	id = PerformanceIBPAStrategyDetails_PgB8_
	tid = 278412370909343
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			id = oQ6gS
			indexOfSelectedChild = 0
		{
			--- Tab ---
				labels en = "By Period", fr = "Par période", de = "Per Periode"
				id = tab_U0mtI
				isWidgetSelected = true
				tid = 279054617243667
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/detailedlist/PerformanceIBPADetailsPerPeriodeForStrategy.module
			}
			--- Tab ---
				labels en = "By Market Segment", fr = "Par segment de marché", de = "Per Marktsegment"
				id = tab_Y73__
				isWidgetVisible = false
				tid = 279054619193870
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/detailedlist/PerformanceIBPADetailsPerMktSegForStrategy.module
			}
		}
	}
}