# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Intermediate Benchmark Performance Attribution Details per Client", fr = "Détails de l\'attribution de performance (benchmarks intermédiaires) par client", de = "Mehrstufige Performance Attribution mit Details per Kunde"
	containment = container
	domainEntity = "AAADSPerformance:PerformanceIBPADetails"
	bean-define = DSBean.AAADSPerformance.PerformanceIBPADetails
	bean-name = PerformanceIBPADetails
	id = PerformanceIBPAClientDetails_Wo_v_
	tid = 278327301619688
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			id = J_n_0
			indexOfSelectedChild = 0
		{
			--- Tab ---
				labels en = "By Period", fr = "Par période", de = "Per Periode"
				id = tab_C0M_8
				isWidgetSelected = true
				tid = 278995041184160
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/detailedlist/PerformanceIBPADetailsPerPeriode.module
			}
			--- Tab ---
				labels en = "By Market Segment", fr = "Par segment de marché", de = "Per Marktsegment"
				id = tab_gW_gZ
				isWidgetVisible = false
				tid = 278995043130433
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/detailedlist/PerformanceIBPADetailsPerMktSeg.module
			}
		}
	}
}