# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Intermediate Benchmark Performance Attribution Details per Manager", fr = "Détails de l\'attribution de performance (benchmarks intermédiaires) par gestionnaire", de = "Mehrstufige Performance Attribution mit Details per Verwalter"
	containment = container
	domainEntity = "AAADSPerformance:PerformanceIBPADetails"
	bean-define = DSBean.AAADSPerformance.PerformanceIBPADetails
	bean-name = PerformanceIBPADetails
	id = PerformanceIBPAManagerDetails_a_T_3
	tid = 278341215171376
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			id = A8__X
			indexOfSelectedChild = 0
		{
			--- Tab ---
				labels en = "By Period", fr = "Par période", de = "Per Periode"
				id = tab_i____
				isWidgetSelected = true
				tid = 279009120770512
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/detailedlist/PerformanceIBPADetailsPerPeriode.module
			}
			--- Tab ---
				labels en = "By Market Segment", fr = "Par segment de marché", de = "Per Marktsegment"
				id = tab_ExPj9
				isWidgetVisible = false
				tid = 279009122721187
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/detailedlist/PerformanceIBPADetailsPerMktSeg.module
			}
		}
	}
}