# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Intermediate Benchmark Performance Attribution Details", fr = "Détails de l\'attribution de performance (benchmarks intermédiaires)", de = "Mehrstufige Performance Attribution mit Details"
	containment = container
	domainEntity = "AAADSPerformance:PerformanceIBPADetails"
	bean-define = DSBean.AAADSPerformance.PerformanceIBPADetails
	bean-name = PerformanceIBPADetails
	id = PerformanceIBPAQueryDetails_T_kjm
	tid = 278388202799432
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			id = U3919
			indexOfSelectedChild = 0
		{
			--- Tab ---
				labels en = "By Period", fr = "Par période", de = "Per Periode"
				id = tab_RZ586
				isWidgetSelected = true
				tid = 279043369585782
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/detailedlist/PerformanceIBPADetailsPerPeriode.module
			}
			--- Tab ---
				labels en = "By Market Segment", fr = "Par segment de marché", de = "Per Marktsegment"
				id = tab_P3b_H
				isWidgetVisible = false
				tid = 279043371536527
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/detailedlist/PerformanceIBPADetailsPerMktSeg.module
			}
		}
	}
}