# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Intermediate Benchmark Performance Attribution Details per Portfolio", fr = "Détails de l\'attribution de performance (benchmarks intermédiaires) par portefeuille", de = "Mehrstufige Performance Attribution mit Details per Portfolio"
	containment = container
	domainEntity = "AAADSPerformance:PerformanceIBPADetails"
	bean-define = DSBean.AAADSPerformance.PerformanceIBPADetails
	bean-name = PerformanceIBPADetails
	id = PerformanceIBPAPortfolioDetails_sn7C6
	tid = 278358599416288
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			id = P_e_4
			indexOfSelectedChild = 0
		{
			--- Tab ---
				labels en = "By Period", fr = "Par période", de = "Per Periode"
				id = tab_c39__
				isWidgetSelected = true
				tid = 279021143792216
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/detailedlist/PerformanceIBPADetailsPerPeriode.module
			}
			--- Tab ---
				labels en = "By Market Segment", fr = "Par segment de marché", de = "Per Marktsegment"
				id = tab_j__23
				isWidgetVisible = false
				tid = 279021145742832
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/detailedlist/PerformanceIBPADetailsPerMktSeg.module
			}
		}
	}
}