<?xml version="1.0" encoding="ASCII"?>
<com.odcgroup.page.model:Model xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:com.odcgroup.page.model="http://www.odcgroup.com/page/model" xmi:id="_rhWlgPTjEdygXKvxE3BNuQ">
  <widget xmi:id="_rhWlgfTjEdygXKvxE3BNuQ" typeName="Module" libraryName="xgui">
    <properties xmi:id="_rhWlgvTjEdygXKvxE3BNuQ" value="" typeName="id" libraryName="xgui"/>
    <properties xmi:id="_rhWlg_TjEdygXKvxE3BNuQ" value="" typeName="icon" libraryName="xgui"/>
    <properties xmi:id="_rhWlhPTjEdygXKvxE3BNuQ" value="center" typeName="verticalAlignment" libraryName="xgui"/>
    <properties xmi:id="_rhWlhfTjEdygXKvxE3BNuQ" value="1205998374682.name" typeName="name" libraryName="xgui" i18n="true"/>
    <properties xmi:id="_rhWlh_TjEdygXKvxE3BNuQ" value="" typeName="documentation" libraryName="xgui"/>
    <properties xmi:id="_rhWliPTjEdygXKvxE3BNuQ" value="" typeName="pagebreak" libraryName="xgui"/>
    <properties xmi:id="_BlAJgAfVEd28uYGZv5kXLA" value="" typeName="domainEntity" libraryName="xgui"/>
    <properties xmi:id="_BlAJgQfVEd28uYGZv5kXLA" value="" typeName="bean-name" libraryName="xgui"/>
    <contents xmi:id="_4jELYPZvEdylt7xqFozWvg" typeName="Box" libraryName="xgui">
      <properties xmi:id="_4jELYfZvEdylt7xqFozWvg" value="none" typeName="widgetBorder" libraryName="xgui"/>
      <properties xmi:id="_4jELYvZvEdylt7xqFozWvg" value="vertical" typeName="boxType" libraryName="xgui"/>
      <properties xmi:id="_4jELY_ZvEdylt7xqFozWvg" value="0" typeName="width" libraryName="xgui"/>
      <properties xmi:id="_4jELZPZvEdylt7xqFozWvg" value="true" typeName="isWidgetSelectable" libraryName="xgui"/>
      <properties xmi:id="_4jELZfZvEdylt7xqFozWvg" value="0" typeName="constraints" libraryName="xgui"/>
      <properties xmi:id="_4jELZvZvEdylt7xqFozWvg" value="1206012131156.caption" typeName="caption" libraryName="xgui" i18n="true"/>
      <properties xmi:id="_4jELZ_ZvEdylt7xqFozWvg" value="true" typeName="isWidgetDeletable" libraryName="xgui"/>
      <properties xmi:id="_4jELaPZvEdylt7xqFozWvg" value="" typeName="id" libraryName="xgui"/>
      <properties xmi:id="_4jELafZvEdylt7xqFozWvg" value="false" typeName="aggregation" libraryName="xgui"/>
      <properties xmi:id="_4jELavZvEdylt7xqFozWvg" value="left" typeName="horizontalAlignment" libraryName="xgui"/>
      <properties xmi:id="_4jELa_ZvEdylt7xqFozWvg" value="center" typeName="verticalAlignment" libraryName="xgui"/>
      <properties xmi:id="_4jELbPZvEdylt7xqFozWvg" value="0" typeName="height" libraryName="xgui"/>
      <properties xmi:id="_4jELbfZvEdylt7xqFozWvg" value="-1" typeName="indexOfSelectedChild" libraryName="xgui"/>
      <properties xmi:id="_4jELb_ZvEdylt7xqFozWvg" value="" typeName="documentation" libraryName="xgui"/>
      <properties xmi:id="_4jELcPZvEdylt7xqFozWvg" value="" typeName="cssClass" libraryName="xgui"/>
      <contents xmi:id="_6QvOIPZvEdylt7xqFozWvg" typeName="Conditional" libraryName="xgui">
        <properties xmi:id="_6QvOIfZvEdylt7xqFozWvg" value="conditionalFigure1" typeName="technicalName" libraryName="xgui"/>
        <properties xmi:id="_6QvOIvZvEdylt7xqFozWvg" value="1" typeName="indexOfSelectedChild" libraryName="xgui"/>
        <properties xmi:id="_6QvOI_ZvEdylt7xqFozWvg" value="" typeName="documentation" libraryName="xgui"/>
        <contents xmi:id="_6QvOJPZvEdylt7xqFozWvg" typeName="ConditionalBody" libraryName="xgui">
          <properties xmi:id="_6QvOJfZvEdylt7xqFozWvg" value="first condition" typeName="technicalName" libraryName="xgui"/>
          <properties xmi:id="_6QvOJvZvEdylt7xqFozWvg" value="vertical" typeName="boxType" libraryName="xgui"/>
          <properties xmi:id="_6QvOJ_ZvEdylt7xqFozWvg" value="" typeName="javaCode" libraryName="xgui"/>
          <properties xmi:id="_6QvOKPZvEdylt7xqFozWvg" value="" typeName="documentation" libraryName="xgui"/>
          <properties xmi:id="_6QvOKfZvEdylt7xqFozWvg" value="false" typeName="isWidgetDeletable" libraryName="xgui"/>
          <properties xmi:id="_6QvOKvZvEdylt7xqFozWvg" value="false" typeName="isWidgetVisible" libraryName="xgui"/>
          <contents xmi:id="_DthLQPtKEdyS3_NuO9qOHg" typeName="Box" libraryName="xgui">
            <properties xmi:id="_DthLQftKEdyS3_NuO9qOHg" value="none" typeName="widgetBorder" libraryName="xgui"/>
            <properties xmi:id="_DthLQvtKEdyS3_NuO9qOHg" value="horizontal" typeName="boxType" libraryName="xgui"/>
            <properties xmi:id="_DthLQ_tKEdyS3_NuO9qOHg" value="0" typeName="width" libraryName="xgui"/>
            <properties xmi:id="_DthLRPtKEdyS3_NuO9qOHg" value="true" typeName="isWidgetSelectable" libraryName="xgui"/>
            <properties xmi:id="_DthLRftKEdyS3_NuO9qOHg" value="0" typeName="constraints" libraryName="xgui"/>
            <properties xmi:id="_DthLRvtKEdyS3_NuO9qOHg" value="1206541913409.caption" typeName="caption" libraryName="xgui" i18n="true"/>
            <properties xmi:id="_DthLR_tKEdyS3_NuO9qOHg" value="true" typeName="isWidgetDeletable" libraryName="xgui"/>
            <properties xmi:id="_DthLSPtKEdyS3_NuO9qOHg" value="" typeName="id" libraryName="xgui"/>
            <properties xmi:id="_DthLSftKEdyS3_NuO9qOHg" value="false" typeName="aggregation" libraryName="xgui"/>
            <properties xmi:id="_DthLSvtKEdyS3_NuO9qOHg" value="left" typeName="horizontalAlignment" libraryName="xgui"/>
            <properties xmi:id="_DthLS_tKEdyS3_NuO9qOHg" value="center" typeName="verticalAlignment" libraryName="xgui"/>
            <properties xmi:id="_DthLTPtKEdyS3_NuO9qOHg" value="0" typeName="height" libraryName="xgui"/>
            <properties xmi:id="_DthLTftKEdyS3_NuO9qOHg" value="-1" typeName="indexOfSelectedChild" libraryName="xgui"/>
            <properties xmi:id="_DthLT_tKEdyS3_NuO9qOHg" value="" typeName="documentation" libraryName="xgui"/>
            <properties xmi:id="_DthLUPtKEdyS3_NuO9qOHg" value="" typeName="cssClass" libraryName="xgui"/>
          </contents>
          <contents xmi:id="_G4qIwPvSEdyKJ-UJgPvNfA" typeName="Label" libraryName="xgui">
            <properties xmi:id="_G4qIwfvSEdyKJ-UJgPvNfA" value="" typeName="icon" libraryName="xgui"/>
            <properties xmi:id="_G4qIwvvSEdyKJ-UJgPvNfA" value="true" typeName="enabled" libraryName="xgui"/>
            <properties xmi:id="_G4qIw_vSEdyKJ-UJgPvNfA" value="Default Text" typeName="text" libraryName="xgui"/>
            <properties xmi:id="_G4qIxPvSEdyKJ-UJgPvNfA" value="" typeName="disabledIcon" libraryName="xgui"/>
            <properties xmi:id="_G4qIxfvSEdyKJ-UJgPvNfA" value="95" typeName="posY" libraryName="xgui"/>
            <properties xmi:id="_G4qIxvvSEdyKJ-UJgPvNfA" value="19" typeName="posX" libraryName="xgui"/>
            <properties xmi:id="_G4qIx_vSEdyKJ-UJgPvNfA" value="" typeName="for" libraryName="xgui"/>
            <properties xmi:id="_G4qIyPvSEdyKJ-UJgPvNfA" value="0" typeName="maxCharacters" libraryName="xgui"/>
            <properties xmi:id="_G4qIyfvSEdyKJ-UJgPvNfA" value="false" typeName="mandatory" libraryName="xgui"/>
            <properties xmi:id="_G4qIyvvSEdyKJ-UJgPvNfA" value="" typeName="verticalTextPosition" libraryName="xgui"/>
            <properties xmi:id="_G4qIy_vSEdyKJ-UJgPvNfA" value="0" typeName="width" libraryName="xgui"/>
            <properties xmi:id="_G4qIzPvSEdyKJ-UJgPvNfA" value="left" typeName="horizontalAlignment" libraryName="xgui"/>
            <properties xmi:id="_G4qIzfvSEdyKJ-UJgPvNfA" value="center" typeName="verticalAlignment" libraryName="xgui"/>
            <properties xmi:id="_G4qIzvvSEdyKJ-UJgPvNfA" value="" typeName="horizontalTextPosition" libraryName="xgui"/>
            <properties xmi:id="_G4qI0PvSEdyKJ-UJgPvNfA" value="" typeName="documentation" libraryName="xgui"/>
            <properties xmi:id="_G4qI0fvSEdyKJ-UJgPvNfA" value="" typeName="action" libraryName="xgui"/>
            <properties xmi:id="_G4qI0vvSEdyKJ-UJgPvNfA" value="" typeName="cssClass" libraryName="xgui"/>
            <properties xmi:id="_G4qI0_vSEdyKJ-UJgPvNfA" value="true" typeName="nowrap" libraryName="xgui"/>
            <properties xmi:id="_G4qI1PvSEdyKJ-UJgPvNfA" value="" typeName="tooltip" libraryName="xgui"/>
          </contents>
          <contents xmi:id="_Sj3qUPvgEdyKJ-UJgPvNfA" typeName="Label" libraryName="xgui">
            <properties xmi:id="_Sj3qUfvgEdyKJ-UJgPvNfA" value="" typeName="icon" libraryName="xgui"/>
            <properties xmi:id="_Sj3qUvvgEdyKJ-UJgPvNfA" value="true" typeName="enabled" libraryName="xgui"/>
            <properties xmi:id="_Sj3qU_vgEdyKJ-UJgPvNfA" value="Default Text" typeName="text" libraryName="xgui"/>
            <properties xmi:id="_Sj3qVPvgEdyKJ-UJgPvNfA" value="" typeName="disabledIcon" libraryName="xgui"/>
            <properties xmi:id="_Sj3qVfvgEdyKJ-UJgPvNfA" value="133" typeName="posY" libraryName="xgui"/>
            <properties xmi:id="_Sj3qVvvgEdyKJ-UJgPvNfA" value="404" typeName="posX" libraryName="xgui"/>
            <properties xmi:id="_Sj3qV_vgEdyKJ-UJgPvNfA" value="" typeName="for" libraryName="xgui"/>
            <properties xmi:id="_Sj3qWPvgEdyKJ-UJgPvNfA" value="0" typeName="maxCharacters" libraryName="xgui"/>
            <properties xmi:id="_Sj3qWfvgEdyKJ-UJgPvNfA" value="false" typeName="mandatory" libraryName="xgui"/>
            <properties xmi:id="_Sj3qWvvgEdyKJ-UJgPvNfA" value="" typeName="verticalTextPosition" libraryName="xgui"/>
            <properties xmi:id="_Sj3qW_vgEdyKJ-UJgPvNfA" value="0" typeName="width" libraryName="xgui"/>
            <properties xmi:id="_Sj3qXPvgEdyKJ-UJgPvNfA" value="left" typeName="horizontalAlignment" libraryName="xgui"/>
            <properties xmi:id="_Sj3qXfvgEdyKJ-UJgPvNfA" value="center" typeName="verticalAlignment" libraryName="xgui"/>
            <properties xmi:id="_Sj3qXvvgEdyKJ-UJgPvNfA" value="" typeName="horizontalTextPosition" libraryName="xgui"/>
            <properties xmi:id="_Sj3qYPvgEdyKJ-UJgPvNfA" value="" typeName="documentation" libraryName="xgui"/>
            <properties xmi:id="_Sj3qYfvgEdyKJ-UJgPvNfA" value="" typeName="action" libraryName="xgui"/>
            <properties xmi:id="_Sj3qYvvgEdyKJ-UJgPvNfA" value="" typeName="cssClass" libraryName="xgui"/>
            <properties xmi:id="_Sj3qY_vgEdyKJ-UJgPvNfA" value="true" typeName="nowrap" libraryName="xgui"/>
            <properties xmi:id="_Sj3qZPvgEdyKJ-UJgPvNfA" value="" typeName="tooltip" libraryName="xgui"/>
          </contents>
          <contents xmi:id="_S5oe8PvgEdyKJ-UJgPvNfA" typeName="Label" libraryName="xgui">
            <properties xmi:id="_S5oe8fvgEdyKJ-UJgPvNfA" value="" typeName="icon" libraryName="xgui"/>
            <properties xmi:id="_S5oe8vvgEdyKJ-UJgPvNfA" value="true" typeName="enabled" libraryName="xgui"/>
            <properties xmi:id="_S5oe8_vgEdyKJ-UJgPvNfA" value="Default Text" typeName="text" libraryName="xgui"/>
            <properties xmi:id="_S5oe9PvgEdyKJ-UJgPvNfA" value="" typeName="disabledIcon" libraryName="xgui"/>
            <properties xmi:id="_S5oe9fvgEdyKJ-UJgPvNfA" value="153" typeName="posY" libraryName="xgui"/>
            <properties xmi:id="_S5oe9vvgEdyKJ-UJgPvNfA" value="427" typeName="posX" libraryName="xgui"/>
            <properties xmi:id="_S5oe9_vgEdyKJ-UJgPvNfA" value="" typeName="for" libraryName="xgui"/>
            <properties xmi:id="_S5oe-PvgEdyKJ-UJgPvNfA" value="0" typeName="maxCharacters" libraryName="xgui"/>
            <properties xmi:id="_S5oe-fvgEdyKJ-UJgPvNfA" value="false" typeName="mandatory" libraryName="xgui"/>
            <properties xmi:id="_S5oe-vvgEdyKJ-UJgPvNfA" value="" typeName="verticalTextPosition" libraryName="xgui"/>
            <properties xmi:id="_S5oe-_vgEdyKJ-UJgPvNfA" value="0" typeName="width" libraryName="xgui"/>
            <properties xmi:id="_S5oe_PvgEdyKJ-UJgPvNfA" value="left" typeName="horizontalAlignment" libraryName="xgui"/>
            <properties xmi:id="_S5oe_fvgEdyKJ-UJgPvNfA" value="center" typeName="verticalAlignment" libraryName="xgui"/>
            <properties xmi:id="_S5oe_vvgEdyKJ-UJgPvNfA" value="" typeName="horizontalTextPosition" libraryName="xgui"/>
            <properties xmi:id="_S5ofAPvgEdyKJ-UJgPvNfA" value="" typeName="documentation" libraryName="xgui"/>
            <properties xmi:id="_S5ofAfvgEdyKJ-UJgPvNfA" value="" typeName="action" libraryName="xgui"/>
            <properties xmi:id="_S5ofAvvgEdyKJ-UJgPvNfA" value="" typeName="cssClass" libraryName="xgui"/>
            <properties xmi:id="_S5ofA_vgEdyKJ-UJgPvNfA" value="true" typeName="nowrap" libraryName="xgui"/>
            <properties xmi:id="_S5ofBPvgEdyKJ-UJgPvNfA" value="" typeName="tooltip" libraryName="xgui"/>
          </contents>
          <contents xmi:id="_Tcy2YPvgEdyKJ-UJgPvNfA" typeName="Label" libraryName="xgui">
            <properties xmi:id="_Tcy2YfvgEdyKJ-UJgPvNfA" value="" typeName="icon" libraryName="xgui"/>
            <properties xmi:id="_Tcy2YvvgEdyKJ-UJgPvNfA" value="true" typeName="enabled" libraryName="xgui"/>
            <properties xmi:id="_Tcy2Y_vgEdyKJ-UJgPvNfA" value="Default Text" typeName="text" libraryName="xgui"/>
            <properties xmi:id="_Tcy2ZPvgEdyKJ-UJgPvNfA" value="" typeName="disabledIcon" libraryName="xgui"/>
            <properties xmi:id="_Tcy2ZfvgEdyKJ-UJgPvNfA" value="172" typeName="posY" libraryName="xgui"/>
            <properties xmi:id="_Tcy2ZvvgEdyKJ-UJgPvNfA" value="440" typeName="posX" libraryName="xgui"/>
            <properties xmi:id="_Tcy2Z_vgEdyKJ-UJgPvNfA" value="" typeName="for" libraryName="xgui"/>
            <properties xmi:id="_Tcy2aPvgEdyKJ-UJgPvNfA" value="0" typeName="maxCharacters" libraryName="xgui"/>
            <properties xmi:id="_Tcy2afvgEdyKJ-UJgPvNfA" value="false" typeName="mandatory" libraryName="xgui"/>
            <properties xmi:id="_Tcy2avvgEdyKJ-UJgPvNfA" value="" typeName="verticalTextPosition" libraryName="xgui"/>
            <properties xmi:id="_Tcy2a_vgEdyKJ-UJgPvNfA" value="0" typeName="width" libraryName="xgui"/>
            <properties xmi:id="_Tcy2bPvgEdyKJ-UJgPvNfA" value="left" typeName="horizontalAlignment" libraryName="xgui"/>
            <properties xmi:id="_Tcy2bfvgEdyKJ-UJgPvNfA" value="center" typeName="verticalAlignment" libraryName="xgui"/>
            <properties xmi:id="_Tcy2bvvgEdyKJ-UJgPvNfA" value="" typeName="horizontalTextPosition" libraryName="xgui"/>
            <properties xmi:id="_Tcy2cPvgEdyKJ-UJgPvNfA" value="" typeName="documentation" libraryName="xgui"/>
            <properties xmi:id="_Tcy2cfvgEdyKJ-UJgPvNfA" value="" typeName="action" libraryName="xgui"/>
            <properties xmi:id="_Tcy2cvvgEdyKJ-UJgPvNfA" value="" typeName="cssClass" libraryName="xgui"/>
            <properties xmi:id="_Tcy2c_vgEdyKJ-UJgPvNfA" value="true" typeName="nowrap" libraryName="xgui"/>
            <properties xmi:id="_Tcy2dPvgEdyKJ-UJgPvNfA" value="" typeName="tooltip" libraryName="xgui"/>
          </contents>
          <contents xmi:id="_TKT_QPvgEdyKJ-UJgPvNfA" typeName="Label" libraryName="xgui">
            <properties xmi:id="_TKT_QfvgEdyKJ-UJgPvNfA" value="" typeName="icon" libraryName="xgui"/>
            <properties xmi:id="_TKT_QvvgEdyKJ-UJgPvNfA" value="true" typeName="enabled" libraryName="xgui"/>
            <properties xmi:id="_TKT_Q_vgEdyKJ-UJgPvNfA" value="Default Text" typeName="text" libraryName="xgui"/>
            <properties xmi:id="_TKT_RPvgEdyKJ-UJgPvNfA" value="" typeName="disabledIcon" libraryName="xgui"/>
            <properties xmi:id="_TKT_RfvgEdyKJ-UJgPvNfA" value="164" typeName="posY" libraryName="xgui"/>
            <properties xmi:id="_TKT_RvvgEdyKJ-UJgPvNfA" value="441" typeName="posX" libraryName="xgui"/>
            <properties xmi:id="_TKT_R_vgEdyKJ-UJgPvNfA" value="" typeName="for" libraryName="xgui"/>
            <properties xmi:id="_TKT_SPvgEdyKJ-UJgPvNfA" value="0" typeName="maxCharacters" libraryName="xgui"/>
            <properties xmi:id="_TKT_SfvgEdyKJ-UJgPvNfA" value="false" typeName="mandatory" libraryName="xgui"/>
            <properties xmi:id="_TKT_SvvgEdyKJ-UJgPvNfA" value="" typeName="verticalTextPosition" libraryName="xgui"/>
            <properties xmi:id="_TKT_S_vgEdyKJ-UJgPvNfA" value="0" typeName="width" libraryName="xgui"/>
            <properties xmi:id="_TKT_TPvgEdyKJ-UJgPvNfA" value="left" typeName="horizontalAlignment" libraryName="xgui"/>
            <properties xmi:id="_TKT_TfvgEdyKJ-UJgPvNfA" value="center" typeName="verticalAlignment" libraryName="xgui"/>
            <properties xmi:id="_TKT_TvvgEdyKJ-UJgPvNfA" value="" typeName="horizontalTextPosition" libraryName="xgui"/>
            <properties xmi:id="_TKT_UPvgEdyKJ-UJgPvNfA" value="" typeName="documentation" libraryName="xgui"/>
            <properties xmi:id="_TKT_UfvgEdyKJ-UJgPvNfA" value="" typeName="action" libraryName="xgui"/>
            <properties xmi:id="_TKT_UvvgEdyKJ-UJgPvNfA" value="" typeName="cssClass" libraryName="xgui"/>
            <properties xmi:id="_TKT_U_vgEdyKJ-UJgPvNfA" value="true" typeName="nowrap" libraryName="xgui"/>
            <properties xmi:id="_TKT_VPvgEdyKJ-UJgPvNfA" value="" typeName="tooltip" libraryName="xgui"/>
          </contents>
          <contents xmi:id="_T4D2EPvgEdyKJ-UJgPvNfA" typeName="Label" libraryName="xgui">
            <properties xmi:id="_T4D2EfvgEdyKJ-UJgPvNfA" value="" typeName="icon" libraryName="xgui"/>
            <properties xmi:id="_T4D2EvvgEdyKJ-UJgPvNfA" value="true" typeName="enabled" libraryName="xgui"/>
            <properties xmi:id="_T4D2E_vgEdyKJ-UJgPvNfA" value="Default Text" typeName="text" libraryName="xgui"/>
            <properties xmi:id="_T4D2FPvgEdyKJ-UJgPvNfA" value="" typeName="disabledIcon" libraryName="xgui"/>
            <properties xmi:id="_T4D2FfvgEdyKJ-UJgPvNfA" value="232" typeName="posY" libraryName="xgui"/>
            <properties xmi:id="_T4D2FvvgEdyKJ-UJgPvNfA" value="336" typeName="posX" libraryName="xgui"/>
            <properties xmi:id="_T4D2F_vgEdyKJ-UJgPvNfA" value="" typeName="for" libraryName="xgui"/>
            <properties xmi:id="_T4D2GPvgEdyKJ-UJgPvNfA" value="0" typeName="maxCharacters" libraryName="xgui"/>
            <properties xmi:id="_T4D2GfvgEdyKJ-UJgPvNfA" value="false" typeName="mandatory" libraryName="xgui"/>
            <properties xmi:id="_T4D2GvvgEdyKJ-UJgPvNfA" value="" typeName="verticalTextPosition" libraryName="xgui"/>
            <properties xmi:id="_T4D2G_vgEdyKJ-UJgPvNfA" value="0" typeName="width" libraryName="xgui"/>
            <properties xmi:id="_T4D2HPvgEdyKJ-UJgPvNfA" value="left" typeName="horizontalAlignment" libraryName="xgui"/>
            <properties xmi:id="_T4D2HfvgEdyKJ-UJgPvNfA" value="center" typeName="verticalAlignment" libraryName="xgui"/>
            <properties xmi:id="_T4D2HvvgEdyKJ-UJgPvNfA" value="" typeName="horizontalTextPosition" libraryName="xgui"/>
            <properties xmi:id="_T4D2IPvgEdyKJ-UJgPvNfA" value="" typeName="documentation" libraryName="xgui"/>
            <properties xmi:id="_T4D2IfvgEdyKJ-UJgPvNfA" value="" typeName="action" libraryName="xgui"/>
            <properties xmi:id="_T4D2IvvgEdyKJ-UJgPvNfA" value="" typeName="cssClass" libraryName="xgui"/>
            <properties xmi:id="_T4D2I_vgEdyKJ-UJgPvNfA" value="true" typeName="nowrap" libraryName="xgui"/>
            <properties xmi:id="_T4D2JPvgEdyKJ-UJgPvNfA" value="" typeName="tooltip" libraryName="xgui"/>
          </contents>
        </contents>
        <contents xmi:id="_AS0sYPZwEdylt7xqFozWvg" typeName="ConditionalBody" libraryName="xgui">
          <properties xmi:id="_AS0sYfZwEdylt7xqFozWvg" value="second condition" typeName="technicalName" libraryName="xgui"/>
          <properties xmi:id="_AS0sYvZwEdylt7xqFozWvg" value="vertical" typeName="boxType" libraryName="xgui"/>
          <properties xmi:id="_AS0sY_ZwEdylt7xqFozWvg" value="" typeName="javaCode" libraryName="xgui"/>
          <properties xmi:id="_AS0sZPZwEdylt7xqFozWvg" value="" typeName="documentation" libraryName="xgui"/>
          <properties xmi:id="_AS0sZfZwEdylt7xqFozWvg" value="false" typeName="isWidgetDeletable" libraryName="xgui"/>
          <properties xmi:id="_AS0sZvZwEdylt7xqFozWvg" value="true" typeName="isWidgetVisible" libraryName="xgui"/>
          <contents xmi:id="_BM-ssPtAEdyS3_NuO9qOHg" typeName="PasswordField" libraryName="xgui">
            <properties xmi:id="_BM-ssftAEdyS3_NuO9qOHg" value="" typeName="widgetGroup" libraryName="xgui"/>
            <properties xmi:id="_BM-ssvtAEdyS3_NuO9qOHg" value="true" typeName="enabled" libraryName="xgui"/>
            <properties xmi:id="_BM-ss_tAEdyS3_NuO9qOHg" value="true" typeName="readable" libraryName="xgui"/>
            <properties xmi:id="_BM-stPtAEdyS3_NuO9qOHg" value="" typeName="accessKey" libraryName="xgui"/>
            <properties xmi:id="_BM-stftAEdyS3_NuO9qOHg" value="70" typeName="posY" libraryName="xgui"/>
            <properties xmi:id="_BM-stvtAEdyS3_NuO9qOHg" value="false" typeName="allow" libraryName="xgui"/>
            <properties xmi:id="_BM-st_tAEdyS3_NuO9qOHg" value="428" typeName="posX" libraryName="xgui"/>
            <properties xmi:id="_BM-suPtAEdyS3_NuO9qOHg" value="0" typeName="tabIndex" libraryName="xgui"/>
            <properties xmi:id="_BM-suftAEdyS3_NuO9qOHg" value="20" typeName="columns" libraryName="xgui"/>
            <properties xmi:id="_BM-suvtAEdyS3_NuO9qOHg" value="****************" typeName="previewValue" libraryName="xgui"/>
            <properties xmi:id="_BM-su_tAEdyS3_NuO9qOHg" value="" typeName="type" libraryName="xgui"/>
            <properties xmi:id="_BM-svPtAEdyS3_NuO9qOHg" value="" typeName="editable" libraryName="xgui"/>
            <properties xmi:id="_BM-svftAEdyS3_NuO9qOHg" value="" typeName="id" libraryName="xgui"/>
            <properties xmi:id="_BM-svvtAEdyS3_NuO9qOHg" value="left" typeName="horizontalAlignment" libraryName="xgui"/>
            <properties xmi:id="_BM-sv_tAEdyS3_NuO9qOHg" value="center" typeName="verticalAlignment" libraryName="xgui"/>
            <properties xmi:id="_BM-swftAEdyS3_NuO9qOHg" value="" typeName="documentation" libraryName="xgui"/>
            <properties xmi:id="_BM-swvtAEdyS3_NuO9qOHg" value="" typeName="bean-name" libraryName="xgui"/>
            <properties xmi:id="_BM-sw_tAEdyS3_NuO9qOHg" value="" typeName="action" libraryName="xgui"/>
            <properties xmi:id="_BM-sxPtAEdyS3_NuO9qOHg" value="" typeName="cssClass" libraryName="xgui"/>
            <properties xmi:id="_BM-sxftAEdyS3_NuO9qOHg" value="0" typeName="chars" libraryName="xgui"/>
            <properties xmi:id="_BM-sxvtAEdyS3_NuO9qOHg" value="false" typeName="required" libraryName="xgui"/>
            <properties xmi:id="_BM-sx_tAEdyS3_NuO9qOHg" value="" typeName="bean-property" libraryName="xgui"/>
            <properties xmi:id="_BM-syPtAEdyS3_NuO9qOHg" value="" typeName="tooltip" libraryName="xgui"/>
            <properties xmi:id="_BlTEcAfVEd28uYGZv5kXLA" value="" typeName="domainAttribute" libraryName="xgui"/>
          </contents>
          <contents xmi:id="_FpEJIPvSEdyKJ-UJgPvNfA" typeName="FileChooser" libraryName="xgui">
            <properties xmi:id="_FpEJIfvSEdyKJ-UJgPvNfA" value="" typeName="widgetGroup" libraryName="xgui"/>
            <properties xmi:id="_FpEJIvvSEdyKJ-UJgPvNfA" value="true" typeName="enabled" libraryName="xgui"/>
            <properties xmi:id="_FpEJI_vSEdyKJ-UJgPvNfA" value="" typeName="accessKey" libraryName="xgui"/>
            <properties xmi:id="_FpEJJPvSEdyKJ-UJgPvNfA" value="83" typeName="posY" libraryName="xgui"/>
            <properties xmi:id="_FpEJJfvSEdyKJ-UJgPvNfA" value="false" typeName="allow" libraryName="xgui"/>
            <properties xmi:id="_FpEJJvvSEdyKJ-UJgPvNfA" value="237" typeName="posX" libraryName="xgui"/>
            <properties xmi:id="_FpEJJ_vSEdyKJ-UJgPvNfA" value="0" typeName="tabIndex" libraryName="xgui"/>
            <properties xmi:id="_FpEJKPvSEdyKJ-UJgPvNfA" value="20" typeName="columns" libraryName="xgui"/>
            <properties xmi:id="_FpEJKfvSEdyKJ-UJgPvNfA" value="" typeName="previewValue" libraryName="xgui"/>
            <properties xmi:id="_FpEJKvvSEdyKJ-UJgPvNfA" value="" typeName="type" libraryName="xgui"/>
            <properties xmi:id="_FpEJK_vSEdyKJ-UJgPvNfA" value="" typeName="editable" libraryName="xgui"/>
            <properties xmi:id="_FpEJLPvSEdyKJ-UJgPvNfA" value="" typeName="id" libraryName="xgui"/>
            <properties xmi:id="_FpEJLfvSEdyKJ-UJgPvNfA" value="left" typeName="horizontalAlignment" libraryName="xgui"/>
            <properties xmi:id="_FpEJLvvSEdyKJ-UJgPvNfA" value="center" typeName="verticalAlignment" libraryName="xgui"/>
            <properties xmi:id="_FpEJMPvSEdyKJ-UJgPvNfA" value="" typeName="documentation" libraryName="xgui"/>
            <properties xmi:id="_FpEJMfvSEdyKJ-UJgPvNfA" value="" typeName="bean-name" libraryName="xgui"/>
            <properties xmi:id="_FpEJMvvSEdyKJ-UJgPvNfA" value="" typeName="action" libraryName="xgui"/>
            <properties xmi:id="_FpEJM_vSEdyKJ-UJgPvNfA" value="" typeName="cssClass" libraryName="xgui"/>
            <properties xmi:id="_FpEJNPvSEdyKJ-UJgPvNfA" value="0" typeName="chars" libraryName="xgui"/>
            <properties xmi:id="_FpEJNfvSEdyKJ-UJgPvNfA" value="false" typeName="required" libraryName="xgui"/>
            <properties xmi:id="_FpEJNvvSEdyKJ-UJgPvNfA" value="" typeName="bean-property" libraryName="xgui"/>
            <properties xmi:id="_FpEJN_vSEdyKJ-UJgPvNfA" value="" typeName="tooltip" libraryName="xgui"/>
            <properties xmi:id="_BlTEcQfVEd28uYGZv5kXLA" value="" typeName="domainAttribute" libraryName="xgui"/>
          </contents>
          <contents xmi:id="_CWw9oAfVEd28uYGZv5kXLA" typeName="CaldateField" libraryName="xgui">
            <properties xmi:id="_CWw9oQfVEd28uYGZv5kXLA" value="" typeName="accessKey" libraryName="xgui"/>
            <properties xmi:id="_CWw9ogfVEd28uYGZv5kXLA" value="117" typeName="posY" libraryName="xgui"/>
            <properties xmi:id="_CWw9owfVEd28uYGZv5kXLA" value="274" typeName="posX" libraryName="xgui"/>
            <properties xmi:id="_CWw9pAfVEd28uYGZv5kXLA" value="0" typeName="tabIndex" libraryName="xgui"/>
            <properties xmi:id="_CWw9pQfVEd28uYGZv5kXLA" value="20" typeName="columns" libraryName="xgui"/>
            <properties xmi:id="_CWw9pgfVEd28uYGZv5kXLA" value="" typeName="previewValue" libraryName="xgui"/>
            <properties xmi:id="_CWw9pwfVEd28uYGZv5kXLA" value="" typeName="type" libraryName="xgui"/>
            <properties xmi:id="_CWw9qAfVEd28uYGZv5kXLA" value="" typeName="id" libraryName="xgui"/>
            <properties xmi:id="_CWw9qQfVEd28uYGZv5kXLA" value="left" typeName="horizontalAlignment" libraryName="xgui"/>
            <properties xmi:id="_CWw9qgfVEd28uYGZv5kXLA" value="" typeName="action" libraryName="xgui"/>
            <properties xmi:id="_CWw9qwfVEd28uYGZv5kXLA" value="" typeName="dateFormat" libraryName="xgui"/>
            <properties xmi:id="_CWw9rAfVEd28uYGZv5kXLA" value="false" typeName="required" libraryName="xgui"/>
            <properties xmi:id="_CWw9rQfVEd28uYGZv5kXLA" value="" typeName="defaultValue" libraryName="xgui"/>
            <properties xmi:id="_CWw9rgfVEd28uYGZv5kXLA" value="" typeName="bean-property" libraryName="xgui"/>
            <properties xmi:id="_CWw9rwfVEd28uYGZv5kXLA" value="" typeName="widgetGroup" libraryName="xgui"/>
            <properties xmi:id="_CWw9sAfVEd28uYGZv5kXLA" value="true" typeName="readable" libraryName="xgui"/>
            <properties xmi:id="_CWw9sQfVEd28uYGZv5kXLA" value="true" typeName="enabled" libraryName="xgui"/>
            <properties xmi:id="_CWw9sgfVEd28uYGZv5kXLA" value="" typeName="caldateYPos" libraryName="xgui"/>
            <properties xmi:id="_CWw9swfVEd28uYGZv5kXLA" value="center" typeName="verticalAlignment" libraryName="xgui"/>
            <properties xmi:id="_CWw9tAfVEd28uYGZv5kXLA" value="" typeName="documentation" libraryName="xgui"/>
            <properties xmi:id="_CWw9tQfVEd28uYGZv5kXLA" value="" typeName="bean-name" libraryName="xgui"/>
            <properties xmi:id="_CWw9tgfVEd28uYGZv5kXLA" value="0" typeName="chars" libraryName="xgui"/>
            <properties xmi:id="_CWw9twfVEd28uYGZv5kXLA" value="" typeName="domainAttribute" libraryName="xgui"/>
            <properties xmi:id="_CWw9uAfVEd28uYGZv5kXLA" value="" typeName="cssClass" libraryName="xgui"/>
            <properties xmi:id="_CWw9uQfVEd28uYGZv5kXLA" value="" typeName="caldateXPos" libraryName="xgui"/>
            <properties xmi:id="_CWw9ugfVEd28uYGZv5kXLA" value="" typeName="tooltip" libraryName="xgui"/>
          </contents>
          <contents xmi:id="_Cj4MkAfVEd28uYGZv5kXLA" typeName="CaldateField" libraryName="xgui">
            <properties xmi:id="_Cj4MkQfVEd28uYGZv5kXLA" value="" typeName="accessKey" libraryName="xgui"/>
            <properties xmi:id="_Cj4MkgfVEd28uYGZv5kXLA" value="139" typeName="posY" libraryName="xgui"/>
            <properties xmi:id="_Cj4MkwfVEd28uYGZv5kXLA" value="318" typeName="posX" libraryName="xgui"/>
            <properties xmi:id="_Cj4MlAfVEd28uYGZv5kXLA" value="0" typeName="tabIndex" libraryName="xgui"/>
            <properties xmi:id="_Cj4MlQfVEd28uYGZv5kXLA" value="20" typeName="columns" libraryName="xgui"/>
            <properties xmi:id="_Cj4MlgfVEd28uYGZv5kXLA" value="" typeName="previewValue" libraryName="xgui"/>
            <properties xmi:id="_Cj4MlwfVEd28uYGZv5kXLA" value="" typeName="type" libraryName="xgui"/>
            <properties xmi:id="_Cj4MmAfVEd28uYGZv5kXLA" value="" typeName="id" libraryName="xgui"/>
            <properties xmi:id="_Cj4MmQfVEd28uYGZv5kXLA" value="left" typeName="horizontalAlignment" libraryName="xgui"/>
            <properties xmi:id="_Cj4MmgfVEd28uYGZv5kXLA" value="" typeName="action" libraryName="xgui"/>
            <properties xmi:id="_Cj4MmwfVEd28uYGZv5kXLA" value="" typeName="dateFormat" libraryName="xgui"/>
            <properties xmi:id="_Cj4MnAfVEd28uYGZv5kXLA" value="false" typeName="required" libraryName="xgui"/>
            <properties xmi:id="_Cj4MnQfVEd28uYGZv5kXLA" value="" typeName="defaultValue" libraryName="xgui"/>
            <properties xmi:id="_Cj4MngfVEd28uYGZv5kXLA" value="" typeName="bean-property" libraryName="xgui"/>
            <properties xmi:id="_Cj4MnwfVEd28uYGZv5kXLA" value="" typeName="widgetGroup" libraryName="xgui"/>
            <properties xmi:id="_Cj4MoAfVEd28uYGZv5kXLA" value="true" typeName="readable" libraryName="xgui"/>
            <properties xmi:id="_Cj4MoQfVEd28uYGZv5kXLA" value="true" typeName="enabled" libraryName="xgui"/>
            <properties xmi:id="_Cj4MogfVEd28uYGZv5kXLA" value="" typeName="caldateYPos" libraryName="xgui"/>
            <properties xmi:id="_Cj4MowfVEd28uYGZv5kXLA" value="center" typeName="verticalAlignment" libraryName="xgui"/>
            <properties xmi:id="_Cj4MpAfVEd28uYGZv5kXLA" value="" typeName="documentation" libraryName="xgui"/>
            <properties xmi:id="_Cj4MpQfVEd28uYGZv5kXLA" value="" typeName="bean-name" libraryName="xgui"/>
            <properties xmi:id="_Cj4MpgfVEd28uYGZv5kXLA" value="0" typeName="chars" libraryName="xgui"/>
            <properties xmi:id="_Cj4MpwfVEd28uYGZv5kXLA" value="" typeName="domainAttribute" libraryName="xgui"/>
            <properties xmi:id="_Cj4MqAfVEd28uYGZv5kXLA" value="" typeName="cssClass" libraryName="xgui"/>
            <properties xmi:id="_Cj4MqQfVEd28uYGZv5kXLA" value="" typeName="caldateXPos" libraryName="xgui"/>
            <properties xmi:id="_Cj4MqgfVEd28uYGZv5kXLA" value="" typeName="tooltip" libraryName="xgui"/>
          </contents>
          <contents xmi:id="_CH3mAAfVEd28uYGZv5kXLA" typeName="FileChooser" libraryName="xgui">
            <properties xmi:id="_CH3mAQfVEd28uYGZv5kXLA" value="" typeName="widgetGroup" libraryName="xgui"/>
            <properties xmi:id="_CH3mAgfVEd28uYGZv5kXLA" value="true" typeName="enabled" libraryName="xgui"/>
            <properties xmi:id="_CH3mAwfVEd28uYGZv5kXLA" value="" typeName="accessKey" libraryName="xgui"/>
            <properties xmi:id="_CH3mBAfVEd28uYGZv5kXLA" value="113" typeName="posY" libraryName="xgui"/>
            <properties xmi:id="_CH3mBQfVEd28uYGZv5kXLA" value="" typeName="allow" libraryName="xgui"/>
            <properties xmi:id="_CH3mBgfVEd28uYGZv5kXLA" value="302" typeName="posX" libraryName="xgui"/>
            <properties xmi:id="_CH3mBwfVEd28uYGZv5kXLA" value="0" typeName="tabIndex" libraryName="xgui"/>
            <properties xmi:id="_CH3mCAfVEd28uYGZv5kXLA" value="20" typeName="columns" libraryName="xgui"/>
            <properties xmi:id="_CH3mCQfVEd28uYGZv5kXLA" value="" typeName="previewValue" libraryName="xgui"/>
            <properties xmi:id="_CH3mCgfVEd28uYGZv5kXLA" value="" typeName="type" libraryName="xgui"/>
            <properties xmi:id="_CH3mCwfVEd28uYGZv5kXLA" value="" typeName="editable" libraryName="xgui"/>
            <properties xmi:id="_CH3mDAfVEd28uYGZv5kXLA" value="" typeName="id" libraryName="xgui"/>
            <properties xmi:id="_CH3mDQfVEd28uYGZv5kXLA" value="left" typeName="horizontalAlignment" libraryName="xgui"/>
            <properties xmi:id="_CH3mDgfVEd28uYGZv5kXLA" value="center" typeName="verticalAlignment" libraryName="xgui"/>
            <properties xmi:id="_CH3mDwfVEd28uYGZv5kXLA" value="" typeName="documentation" libraryName="xgui"/>
            <properties xmi:id="_CH3mEAfVEd28uYGZv5kXLA" value="" typeName="bean-name" libraryName="xgui"/>
            <properties xmi:id="_CH3mEQfVEd28uYGZv5kXLA" value="" typeName="action" libraryName="xgui"/>
            <properties xmi:id="_CH3mEgfVEd28uYGZv5kXLA" value="" typeName="cssClass" libraryName="xgui"/>
            <properties xmi:id="_CH3mEwfVEd28uYGZv5kXLA" value="0" typeName="chars" libraryName="xgui"/>
            <properties xmi:id="_CH3mFAfVEd28uYGZv5kXLA" value="" typeName="domainAttribute" libraryName="xgui"/>
            <properties xmi:id="_CH3mFQfVEd28uYGZv5kXLA" value="false" typeName="required" libraryName="xgui"/>
            <properties xmi:id="_CH3mFgfVEd28uYGZv5kXLA" value="" typeName="bean-property" libraryName="xgui"/>
            <properties xmi:id="_CH3mFwfVEd28uYGZv5kXLA" value="" typeName="tooltip" libraryName="xgui"/>
          </contents>
        </contents>
        <contents xmi:id="_O-h7kPtBEdyS3_NuO9qOHg" typeName="ConditionalBody" libraryName="xgui">
          <properties xmi:id="_O-h7kftBEdyS3_NuO9qOHg" value="third condition" typeName="technicalName" libraryName="xgui"/>
          <properties xmi:id="_O-h7kvtBEdyS3_NuO9qOHg" value="vertical" typeName="boxType" libraryName="xgui"/>
          <properties xmi:id="_O-h7k_tBEdyS3_NuO9qOHg" value="" typeName="javaCode" libraryName="xgui"/>
          <properties xmi:id="_O-h7lPtBEdyS3_NuO9qOHg" value="" typeName="documentation" libraryName="xgui"/>
          <properties xmi:id="_O-h7lftBEdyS3_NuO9qOHg" value="false" typeName="isWidgetDeletable" libraryName="xgui"/>
          <properties xmi:id="_O-h7lvtBEdyS3_NuO9qOHg" value="false" typeName="isWidgetVisible" libraryName="xgui"/>
          <contents xmi:id="__HRQEPvREdyKJ-UJgPvNfA" typeName="Table" libraryName="xgui">
            <properties xmi:id="__HRQEfvREdyKJ-UJgPvNfA" value="false" typeName="dumpModel" libraryName="xgui"/>
            <properties xmi:id="__HRQEvvREdyKJ-UJgPvNfA" value="" typeName="pageSize" libraryName="xgui"/>
            <properties xmi:id="__HRQE_vREdyKJ-UJgPvNfA" value="true" typeName="showColumnHeader" libraryName="xgui"/>
            <properties xmi:id="__HRQFPvREdyKJ-UJgPvNfA" value="" typeName="model-ref" libraryName="xgui"/>
            <properties xmi:id="__HRQFfvREdyKJ-UJgPvNfA" value="" typeName="view-ref" libraryName="xgui"/>
            <properties xmi:id="__HRQFvvREdyKJ-UJgPvNfA" value="" typeName="id" libraryName="xgui"/>
            <properties xmi:id="__HRQF_vREdyKJ-UJgPvNfA" value="center" typeName="verticalAlignment" libraryName="xgui"/>
            <properties xmi:id="__HRQGPvREdyKJ-UJgPvNfA" value="false" typeName="sticky" libraryName="xgui"/>
            <properties xmi:id="__HRQGfvREdyKJ-UJgPvNfA" value="" typeName="keepFilter" libraryName="xgui"/>
            <properties xmi:id="__HRQGvvREdyKJ-UJgPvNfA" value="0" typeName="indexOfSelectedChild" libraryName="xgui"/>
            <properties xmi:id="__HRQHPvREdyKJ-UJgPvNfA" value="" typeName="documentation" libraryName="xgui"/>
            <properties xmi:id="__HRQHfvREdyKJ-UJgPvNfA" value="" typeName="cssClass" libraryName="xgui"/>
            <properties xmi:id="__HRQHvvREdyKJ-UJgPvNfA" value="5" typeName="previewSize" libraryName="xgui"/>
            <properties xmi:id="__HRQH_vREdyKJ-UJgPvNfA" value="" typeName="filter" libraryName="xgui"/>
            <contents xmi:id="__HRQIPvREdyKJ-UJgPvNfA" typeName="Column" libraryName="xgui">
              <properties xmi:id="__HRQIfvREdyKJ-UJgPvNfA" value="" typeName="id" libraryName="xgui"/>
              <properties xmi:id="__HRQIvvREdyKJ-UJgPvNfA" value="false" typeName="isWidgetSelectable" libraryName="xgui"/>
              <properties xmi:id="__HRQJPvREdyKJ-UJgPvNfA" value="" typeName="documentation" libraryName="xgui"/>
              <properties xmi:id="__HRQJfvREdyKJ-UJgPvNfA" value="" typeName="cssClass" libraryName="xgui"/>
              <properties xmi:id="__HRQJvvREdyKJ-UJgPvNfA" value="false" typeName="isWidgetDeletable" libraryName="xgui"/>
              <properties xmi:id="_Blc1cAfVEd28uYGZv5kXLA" value="" typeName="domainAttribute" libraryName="xgui"/>
              <contents xmi:id="__HRQJ_vREdyKJ-UJgPvNfA" typeName="ColumnHeader" libraryName="xgui">
                <properties xmi:id="__HRQKPvREdyKJ-UJgPvNfA" value="true" typeName="visible" libraryName="xgui"/>
                <properties xmi:id="__HRQKfvREdyKJ-UJgPvNfA" value="" typeName="groupSortColumn" libraryName="xgui"/>
                <properties xmi:id="__HRQKvvREdyKJ-UJgPvNfA" value="0" typeName="maxCharacters" libraryName="xgui"/>
                <properties xmi:id="__HRQK_vREdyKJ-UJgPvNfA" value="" typeName="type" libraryName="xgui"/>
                <properties xmi:id="__HRQLPvREdyKJ-UJgPvNfA" value="" typeName="id" libraryName="xgui"/>
                <properties xmi:id="__HRQLfvREdyKJ-UJgPvNfA" value="" typeName="action" libraryName="xgui"/>
                <properties xmi:id="__HRQLvvREdyKJ-UJgPvNfA" value="true" typeName="isSortable" libraryName="xgui"/>
                <properties xmi:id="__HRQL_vREdyKJ-UJgPvNfA" value="1ere colonne" typeName="columnName" libraryName="xgui"/>
                <properties xmi:id="__HRQMPvREdyKJ-UJgPvNfA" value="" typeName="compute" libraryName="xgui"/>
                <properties xmi:id="__HRQMfvREdyKJ-UJgPvNfA" value="true" typeName="nowrap" libraryName="xgui"/>
                <properties xmi:id="__HRQMvvREdyKJ-UJgPvNfA" value="" typeName="option" libraryName="xgui"/>
                <properties xmi:id="__HRQM_vREdyKJ-UJgPvNfA" value="" typeName="defaultSortRank" libraryName="xgui"/>
                <properties xmi:id="__HRQNPvREdyKJ-UJgPvNfA" value="" typeName="xWidth" libraryName="xgui"/>
                <properties xmi:id="__HRQNfvREdyKJ-UJgPvNfA" value="true" typeName="enabled" libraryName="xgui"/>
                <properties xmi:id="__HRQNvvREdyKJ-UJgPvNfA" value="" typeName="icon" libraryName="xgui"/>
                <properties xmi:id="__HRQN_vREdyKJ-UJgPvNfA" value="0" typeName="width" libraryName="xgui"/>
                <properties xmi:id="__HRQOPvREdyKJ-UJgPvNfA" value="Caption" typeName="caption" libraryName="xgui"/>
                <properties xmi:id="__HRQOfvREdyKJ-UJgPvNfA" value="" typeName="format" libraryName="xgui"/>
                <properties xmi:id="__HRQOvvREdyKJ-UJgPvNfA" value="false" typeName="isWidgetDeletable" libraryName="xgui"/>
                <properties xmi:id="__HRQO_vREdyKJ-UJgPvNfA" value="" typeName="groupSortRank" libraryName="xgui"/>
                <properties xmi:id="__HRQPPvREdyKJ-UJgPvNfA" value="ascending" typeName="defaultSortDirection" libraryName="xgui"/>
                <properties xmi:id="__HRQPfvREdyKJ-UJgPvNfA" value="-1" typeName="indexOfSelectedChild" libraryName="xgui"/>
                <properties xmi:id="__HRQP_vREdyKJ-UJgPvNfA" value="" typeName="documentation" libraryName="xgui"/>
                <properties xmi:id="__HRQQfvREdyKJ-UJgPvNfA" value="" typeName="computation" libraryName="xgui"/>
                <properties xmi:id="__HRQQvvREdyKJ-UJgPvNfA" value="" typeName="cssClass" libraryName="xgui"/>
                <properties xmi:id="__HRQQ_vREdyKJ-UJgPvNfA" value="false" typeName="locked" libraryName="xgui"/>
                <properties xmi:id="_Blc1cQfVEd28uYGZv5kXLA" value="" typeName="domainAttribute" libraryName="xgui"/>
              </contents>
              <contents xmi:id="__HRQRPvREdyKJ-UJgPvNfA" typeName="ColumnBody" libraryName="xgui">
                <properties xmi:id="__HRQRfvREdyKJ-UJgPvNfA" value="" typeName="id" libraryName="xgui"/>
                <properties xmi:id="__HRQRvvREdyKJ-UJgPvNfA" value="left" typeName="horizontalAlignment" libraryName="xgui"/>
                <properties xmi:id="__HRQR_vREdyKJ-UJgPvNfA" value="center" typeName="verticalAlignment" libraryName="xgui"/>
                <properties xmi:id="__HRQSPvREdyKJ-UJgPvNfA" value="" typeName="horizontalTextPosition" libraryName="xgui"/>
                <properties xmi:id="__HRQSfvREdyKJ-UJgPvNfA" value="" typeName="verticalTextPosition" libraryName="xgui"/>
                <properties xmi:id="__HRQSvvREdyKJ-UJgPvNfA" value="" typeName="documentation" libraryName="xgui"/>
                <properties xmi:id="__HRQS_vREdyKJ-UJgPvNfA" value="" typeName="cssClass" libraryName="xgui"/>
                <properties xmi:id="__HRQTPvREdyKJ-UJgPvNfA" value="false" typeName="isWidgetDeletable" libraryName="xgui"/>
                <contents xmi:id="__HRQTfvREdyKJ-UJgPvNfA" typeName="Item" libraryName="xgui">
                  <properties xmi:id="__HRQTvvREdyKJ-UJgPvNfA" value="" typeName="documentation" libraryName="xgui"/>
                  <properties xmi:id="__HRQUPvREdyKJ-UJgPvNfA" value="Value" typeName="previewValue" libraryName="xgui"/>
                  <properties xmi:id="__HRQUfvREdyKJ-UJgPvNfA" value="" typeName="columnName" libraryName="xgui"/>
                  <properties xmi:id="_Bll_YAfVEd28uYGZv5kXLA" value="" typeName="domainAttribute" libraryName="xgui"/>
                </contents>
              </contents>
            </contents>
            <contents xmi:id="_CA-BEPvSEdyKJ-UJgPvNfA" typeName="Column" libraryName="xgui">
              <properties xmi:id="_CA-BEfvSEdyKJ-UJgPvNfA" value="" typeName="id" libraryName="xgui"/>
              <properties xmi:id="_CA-BEvvSEdyKJ-UJgPvNfA" value="false" typeName="isWidgetSelectable" libraryName="xgui"/>
              <properties xmi:id="_CA-BFPvSEdyKJ-UJgPvNfA" value="" typeName="documentation" libraryName="xgui"/>
              <properties xmi:id="_CA-BFfvSEdyKJ-UJgPvNfA" value="" typeName="cssClass" libraryName="xgui"/>
              <properties xmi:id="_CA-BFvvSEdyKJ-UJgPvNfA" value="false" typeName="isWidgetDeletable" libraryName="xgui"/>
              <properties xmi:id="_Bll_YQfVEd28uYGZv5kXLA" value="" typeName="domainAttribute" libraryName="xgui"/>
              <contents xmi:id="_CA-BF_vSEdyKJ-UJgPvNfA" typeName="ColumnHeader" libraryName="xgui">
                <properties xmi:id="_CA-BGPvSEdyKJ-UJgPvNfA" value="true" typeName="visible" libraryName="xgui"/>
                <properties xmi:id="_CA-BGfvSEdyKJ-UJgPvNfA" value="" typeName="groupSortColumn" libraryName="xgui"/>
                <properties xmi:id="_CA-BGvvSEdyKJ-UJgPvNfA" value="0" typeName="maxCharacters" libraryName="xgui"/>
                <properties xmi:id="_CA-BG_vSEdyKJ-UJgPvNfA" value="" typeName="type" libraryName="xgui"/>
                <properties xmi:id="_CA-BHPvSEdyKJ-UJgPvNfA" value="" typeName="id" libraryName="xgui"/>
                <properties xmi:id="_CA-BHfvSEdyKJ-UJgPvNfA" value="" typeName="action" libraryName="xgui"/>
                <properties xmi:id="_CA-BHvvSEdyKJ-UJgPvNfA" value="true" typeName="isSortable" libraryName="xgui"/>
                <properties xmi:id="_CA-BH_vSEdyKJ-UJgPvNfA" value="2 eme colonnne" typeName="columnName" libraryName="xgui"/>
                <properties xmi:id="_CA-BIPvSEdyKJ-UJgPvNfA" value="" typeName="compute" libraryName="xgui"/>
                <properties xmi:id="_CA-BIfvSEdyKJ-UJgPvNfA" value="true" typeName="nowrap" libraryName="xgui"/>
                <properties xmi:id="_CA-BIvvSEdyKJ-UJgPvNfA" value="" typeName="option" libraryName="xgui"/>
                <properties xmi:id="_CA-BI_vSEdyKJ-UJgPvNfA" value="" typeName="defaultSortRank" libraryName="xgui"/>
                <properties xmi:id="_CA-BJPvSEdyKJ-UJgPvNfA" value="" typeName="xWidth" libraryName="xgui"/>
                <properties xmi:id="_CA-BJfvSEdyKJ-UJgPvNfA" value="true" typeName="enabled" libraryName="xgui"/>
                <properties xmi:id="_CA-BJvvSEdyKJ-UJgPvNfA" value="" typeName="icon" libraryName="xgui"/>
                <properties xmi:id="_CA-BJ_vSEdyKJ-UJgPvNfA" value="0" typeName="width" libraryName="xgui"/>
                <properties xmi:id="_CA-BKPvSEdyKJ-UJgPvNfA" value="Caption" typeName="caption" libraryName="xgui"/>
                <properties xmi:id="_CA-BKfvSEdyKJ-UJgPvNfA" value="" typeName="format" libraryName="xgui"/>
                <properties xmi:id="_CA-BKvvSEdyKJ-UJgPvNfA" value="false" typeName="isWidgetDeletable" libraryName="xgui"/>
                <properties xmi:id="_CA-BK_vSEdyKJ-UJgPvNfA" value="" typeName="groupSortRank" libraryName="xgui"/>
                <properties xmi:id="_CA-BLPvSEdyKJ-UJgPvNfA" value="ascending" typeName="defaultSortDirection" libraryName="xgui"/>
                <properties xmi:id="_CA-BLfvSEdyKJ-UJgPvNfA" value="-1" typeName="indexOfSelectedChild" libraryName="xgui"/>
                <properties xmi:id="_CA-BL_vSEdyKJ-UJgPvNfA" value="" typeName="documentation" libraryName="xgui"/>
                <properties xmi:id="_CA-BMfvSEdyKJ-UJgPvNfA" value="" typeName="computation" libraryName="xgui"/>
                <properties xmi:id="_CA-BMvvSEdyKJ-UJgPvNfA" value="" typeName="cssClass" libraryName="xgui"/>
                <properties xmi:id="_CA-BM_vSEdyKJ-UJgPvNfA" value="false" typeName="locked" libraryName="xgui"/>
                <properties xmi:id="_BlvwYAfVEd28uYGZv5kXLA" value="" typeName="domainAttribute" libraryName="xgui"/>
              </contents>
              <contents xmi:id="_CA-BNPvSEdyKJ-UJgPvNfA" typeName="ColumnBody" libraryName="xgui">
                <properties xmi:id="_CA-BNfvSEdyKJ-UJgPvNfA" value="" typeName="id" libraryName="xgui"/>
                <properties xmi:id="_CA-BNvvSEdyKJ-UJgPvNfA" value="left" typeName="horizontalAlignment" libraryName="xgui"/>
                <properties xmi:id="_CA-BN_vSEdyKJ-UJgPvNfA" value="center" typeName="verticalAlignment" libraryName="xgui"/>
                <properties xmi:id="_CA-BOPvSEdyKJ-UJgPvNfA" value="" typeName="horizontalTextPosition" libraryName="xgui"/>
                <properties xmi:id="_CA-BOfvSEdyKJ-UJgPvNfA" value="" typeName="verticalTextPosition" libraryName="xgui"/>
                <properties xmi:id="_CA-BOvvSEdyKJ-UJgPvNfA" value="" typeName="documentation" libraryName="xgui"/>
                <properties xmi:id="_CA-BO_vSEdyKJ-UJgPvNfA" value="" typeName="cssClass" libraryName="xgui"/>
                <properties xmi:id="_CA-BPPvSEdyKJ-UJgPvNfA" value="false" typeName="isWidgetDeletable" libraryName="xgui"/>
                <contents xmi:id="_CA-BPfvSEdyKJ-UJgPvNfA" typeName="Item" libraryName="xgui">
                  <properties xmi:id="_CA-BPvvSEdyKJ-UJgPvNfA" value="" typeName="documentation" libraryName="xgui"/>
                  <properties xmi:id="_CA-BQPvSEdyKJ-UJgPvNfA" value="Value" typeName="previewValue" libraryName="xgui"/>
                  <properties xmi:id="_CA-BQfvSEdyKJ-UJgPvNfA" value="" typeName="columnName" libraryName="xgui"/>
                  <properties xmi:id="_BlvwYQfVEd28uYGZv5kXLA" value="" typeName="domainAttribute" libraryName="xgui"/>
                </contents>
              </contents>
            </contents>
          </contents>
        </contents>
      </contents>
    </contents>
  </widget>
</com.odcgroup.page.model:Model>
