# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSValuation:ValuationSummaryList"
	cssClass = nodeco
	bean-define = DSBean.AAADSValuation.ValuationSummaryList
	bean-name = ValuationSummaryList
	id = ByPortfolioD_Y46WA
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			id = RRJL12
			table-column-count = 11 !
			table-columns-width = "9,9,9,9,9,9,9,9,9,9,9" !
		{
			--- TableColumn ---
				labels en = Portfolio, de = Portfolio, fr = Portefeuille
				column-display-grouping = true
				column-name = GROUPING
				column-type = placeholder !
				type = text
				column-locked = true
				column-sortable = false !
				id = ZEed_
				table-column-width = 9
				tid = 608671622043620
			{
				--- TableGroup ---
					aggregateData = false
					group-column-name = PTF_HIER_STR
					group-sorting-column-name = PTF_HIER_STR
					group-sorting-direction = ascending
					hierarchy = true
					group-rank = 1
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = selectPortfolio ud
						portfolioDimPortfolio.code = "<udp:item column=\"_nodeCode\"/>" ud
						portfolioDimensionE = 1 ud
						modal = false
						only-changed = false
						prevalidate = false
						code = "<udp:item column=\"_nodeCode\"/>" ud
						Snippet FilterSet
						id = fs_n7Y
						level = 1
						targetDataset = "AAADSValuation:ValuationSummaryList"
						{
							Snippet Filter
							attribute = PTF_HIER_STR
							filterValue = "<udp:item column=\"PTF_HIER_STR\"/>"
							operator = BEGINS_WITH
						}
					}
				}
			}
			--- TableColumn ---
				column-name = THIRD_COMP_RULE !
				column-type = domain !
				domainAttribute = THIRD_COMP_RULE !
				type = text
				column-visibility = not-visible
				id = THIRD_COMP_RULE
				table-column-width = 9
			{
				--- TableColumnItem ---
					item-column = THIRD_COMP_RULE
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Market Value", de = Marktwert, fr = "Valeur de marché"
				column-name = TotMktVal
				type = amount
				id = g_Z__
				documentation = "Sum of the Total Market Value in Reference Currency by Portfolio."
				column-computation = make-amount
				column-computation-parameters = "TOT_MKT_VAL,REF_CURRENCY"
				table-column-width = 9
				tid = 608671622799533
			{
				--- TableColumnItem ---
					item-column = TotMktVal
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Net Cost Value", de = Netto-Einstandswert, fr = "Coût d\'achat"
				column-name = TotNetCostVal
				type = amount
				id = l212_
				documentation = "Sum of the Total Net Cost Value in Reference Currency by Portfolio."
				column-computation = make-amount
				column-computation-parameters = "TOT_NET_COST_VAL,REF_CURRENCY"
				table-column-width = 9
				tid = 608671623484719
			{
				--- TableColumnItem ---
					item-column = TotNetCostVal
					previewValue = value
			}
			--- TableColumn ---
				column-name = TOT_PTF_PL_PERC !
				column-type = domain !
				domainAttribute = TOT_PTF_PL_PERC !
				type = text
				id = TOT_PTF_PL_PERC
				table-column-width = 9
			{
				--- TableColumnItem ---
					item-column = TOT_PTF_PL_PERC
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = CLIENT_NAME !
				column-type = domain !
				domainAttribute = CLIENT_NAME !
				type = text
				id = CLIENT_NAME
				table-column-width = 9
			{
				--- TableColumnItem ---
					item-column = CLIENT_NAME
					previewValue = value
			}
			--- TableColumn ---
				column-name = PORTFOLIO_INVEST_SERVICE !
				column-type = domain !
				domainAttribute = PORTFOLIO_INVEST_SERVICE !
				type = text
				id = PORTFOLIO_INVEST_SERVICE
				table-column-width = 9
			{
				--- TableColumnItem ---
					item-column = PORTFOLIO_INVEST_SERVICE
					previewValue = value
			}
			--- TableColumn ---
				column-name = ADMIN_MGR_NAME !
				column-type = domain !
				domainAttribute = ADMIN_MGR_NAME !
				type = text
				id = ADMIN_MGR_NAME
				table-column-width = 9
			{
				--- TableColumnItem ---
					item-column = ADMIN_MGR_NAME
					previewValue = value
			}
			--- TableColumn ---
				column-name = COM_MGR_NAME !
				column-type = domain !
				domainAttribute = COM_MGR_NAME !
				type = text
				id = COM_MGR_NAME
				table-column-width = 9
			{
				--- TableColumnItem ---
					item-column = COM_MGR_NAME
					previewValue = value
			}
			--- TableColumn ---
				column-name = THIRD_PARTY_OWNERSHIP_RULE !
				column-type = domain !
				domainAttribute = THIRD_PARTY_OWNERSHIP_RULE !
				type = text
				column-visibility = not-visible
				id = THIRD_PARTY_OWNERSHIP_RULE
				table-column-width = 9
			{
				--- TableColumnItem ---
					item-column = THIRD_PARTY_OWNERSHIP_RULE
					previewValue = value
			}
			--- TableColumn ---
				column-name = THIRD_PARTY_PERCT_OWNERSHIP !
				column-type = domain !
				domainAttribute = THIRD_PARTY_PERCT_OWNERSHIP !
				type = text
				column-visibility = not-visible
				id = THIRD_PARTY_PERCT_OWNERSHIP
				table-column-width = 9
			{
				--- TableColumnItem ---
					item-column = THIRD_PARTY_PERCT_OWNERSHIP
					format = percentTA
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = PTF_HIER_STR
				sort-rank = 1
			--- TableKeepFilter ---
				keep-filter-column-name = ONE_PTF_OCCUR
				keep-filter-operand = 1
		}
	}
}