# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSType:TypeAll"
	bean-define = DSBean.AAADSType.TypeAll
	bean-name = TypeAll
	id = TypeDetail_P_5zt
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 6
			gridColumnsWidth = "16,16,16,16,16,16" !
			gridRowCount = 2
		{
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- LabelDomain ---
					domainAttribute = code !
					for = code
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					width = 0
					required = true
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- TextField ---
					domainAttribute = code !
					horizontalAlignment = "${corporatehalign}"
					type = text
					required = true
					bean-property = code
					id = code
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- LabelDomain ---
					domainAttribute = name !
					for = name
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					width = 0
					required = true
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- TextField ---
					domainAttribute = name !
					horizontalAlignment = "${corporatehalign}"
					type = text
					required = true
					bean-property = name
					id = name
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- LabelDomain ---
					domainAttribute = extDenomination !
					for = extDenomination
					horizontalAlignment = "${corporatehalign}"
					required = true
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- TextField ---
					domainAttribute = extDenomination !
					columns = 30
					horizontalAlignment = "${corporatehalign}"
					type = text
					chars = 80
					required = true
					bean-property = extDenomination
					id = extDenomination
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- LabelDomain ---
					domainAttribute = rankN !
					for = rankN
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					width = 0
					required = true
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- TextField ---
					domainAttribute = rankN !
					horizontalAlignment = "${corporatehalign}"
					type = integer
					required = true
					bean-property = rankN
					id = rankN
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- LabelDomain ---
					domainAttribute = autocreatedF !
					for = autocreatedF
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					width = 0
					required = true
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- ComboBox ---
					domainAttribute = autocreatedF !
					horizontalAlignment = "${corporatehalign}"
					required = true
					bean-property = autocreatedF
					id = autocreatedF
			}
			--- GridCell ---
				gridColumnWidth = 16
			--- GridCell ---
				gridColumnWidth = 16
		}
	}
}