# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSValRule:ValRuleList"
	bean-define = DSBean.AAADSValRule.ValRuleList
	bean-name = ValRuleList
	id = ValRuleList_c03z_
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			id = yI_3_
			table-column-count = 5 !
			table-columns-width = "20,20,20,20,20" !
		{
			--- TableColumn ---
				column-name = natureE !
				column-type = domain !
				domainAttribute = natureE !
				id = natureE
				table-column-width = 20
			{
				--- TableColumnItem ---
					item-column = natureE
					previewValue = value
			}
			--- TableColumn ---
				column-name = code !
				column-type = domain !
				domainAttribute = code !
				id = code
				table-column-width = 20
			{
				--- TableColumnItem ---
					item-column = code
					previewValue = value
			}
			--- TableColumn ---
				column-name = name !
				column-type = domain !
				domainAttribute = name !
				id = name
				table-column-width = 20
			{
				--- TableColumnItem ---
					item-column = name
					previewValue = value
			}
			--- TableColumn ---
				column-name = denom !
				column-type = domain !
				domainAttribute = denom !
				id = denom
				table-column-width = 20
			{
				--- TableColumnItem ---
					item-column = denom
					previewValue = value
			}
			--- TableColumn ---
				column-name = crossCurrCode !
				column-type = domain !
				domainAttribute = crossCurrCode !
				id = crossCurrCode
				table-column-width = 20
			{
				--- TableColumnItem ---
					item-column = crossCurrCode
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = natureE
				sort-rank = 1
			--- TableSort ---
				sort-column-name = code
				sort-rank = 2
		}
	}
}