# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels de = Börsenplatzliste, en = "Trading Place", fr = "Lieu d\'échange"
	domainEntity = "AAADSTradingPlace:TradingPlaceList"
	cssClass = nodeco
	bean-define = DSBean.AAADSTradingPlace.TradingPlaceList
	bean-name = TradingPlaceList
	id = TradingPlaceList_qkUH6
	tid = 29789171648910
{
	--- Box ---
		labels en = "Trading Place", de = Börsenplatz, fr = "Lieu d\'échange"
		boxType = vertical
		widgetBorder = box
		width = 0
		tid = 713206254623702
	{
		--- TableTree ---
			table-filter-layer = true
			id = pdQ9_
			table-model-reference = DSTableModel.AAADSTradingPlace.TradingPlaceList
			table-column-count = 3 !
			table-columns-width = "33,33,33" !
		{
			--- TableColumn ---
				column-name = marketPlaceExtDenomination !
				column-type = domain !
				domainAttribute = marketPlaceExtDenomination !
				type = text
				id = marketPlaceExtDenomination
				table-column-width = 33
			{
				--- TableColumnItem ---
					item-column = marketPlaceExtDenomination
					previewValue = value
			}
			--- TableColumn ---
				column-name = currencyExtDenomination !
				column-type = domain !
				domainAttribute = currencyExtDenomination !
				type = text
				id = currencyExtDenomination
				table-column-width = 33
			{
				--- TableColumnItem ---
					item-column = currencyExtDenomination
					previewValue = value
			}
			--- TableColumn ---
				column-name = mainPlaceF !
				column-type = domain !
				domainAttribute = mainPlaceF !
				type = text
				id = mainPlaceF
				table-column-width = 33
			{
				--- TableColumnItem ---
					item-column = mainPlaceF
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = mainPlaceF
				sort-direction = descending
				sort-rank = 2
			--- TableSort ---
				sort-column-name = marketPlaceExtDenomination
				sort-direction = descending
				sort-rank = 4
			--- TableSort ---
				sort-column-name = currencyExtDenomination
				sort-direction = descending
				sort-rank = 6
		}
	}
}