# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Address List", fr = "Liste d\'adresse", de = Adressliste
	domainEntity = "AAADSAddress:AddressList"
	bean-define = DSBean.AAADSAddress.AddressList
	bean-name = AddressList
	id = AddressList_D993R
	tid = 445510394426945
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			id = WA89_
			table-model-reference = AddressList
			table-column-count = 3 !
			table-columns-width = "33,33,33" !
		{
			--- TableColumn ---
				column-name = thirdCode !
				column-type = domain !
				domainAttribute = thirdCode !
				id = thirdCode
				table-column-width = 33
			{
				--- TableColumnItem ---
					item-column = thirdCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = typeCode !
				column-type = domain !
				domainAttribute = typeCode !
				id = typeCode
				table-column-width = 33
			{
				--- TableColumnItem ---
					item-column = typeCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = geographicCode !
				column-type = domain !
				domainAttribute = geographicCode !
				id = geographicCode
				table-column-width = 33
			{
				--- TableColumnItem ---
					item-column = geographicCode
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = thirdCode
				sort-rank = 1
			--- TableSort ---
				sort-column-name = typeCode
				sort-rank = 2
			--- TableSort ---
				sort-column-name = geographicCode
				sort-rank = 3
		}
	}
}