# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = Query
	containment = container
	domainEntity = "AlertDef:AlertDefAll"
	bean-define = DSBean.AlertDef.AlertDefAll
	bean-name = AlertDefAll
	id = AlertQueryCriteriaView_k_t__
	tid = 503292455213721
{
	--- Box ---
		boxType = vertical
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 2
			gridColumnsWidth = "50,50" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 50
			{
				--- Label ---
					labels en = "Target Entity"
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					tid = 442493638475839
			}
			--- GridCell ---
				gridColumnWidth = 50
			{
				--- Include ---
					domainAssociation = entity
					includeSrc = "" !
					resource:///default/defaultFragments/DictEntityIdentifierView.fragment
			}
		}
		--- Conditional ---
			indexOfSelectedChild = 2
		{
			--- ConditionalBody ---
				conditionLang = DSEL
				javaCode = "\"portfolio\".equals(AlertDefAll.entity.sqlnameC)"
				technicalName = Portfolio
				boxType = vertical
				isWidgetVisible = false
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/alerts/view/AlertPortfolioQueryCriteriaView.module
			}
			--- ConditionalBody ---
				conditionLang = DSEL
				javaCode = "\"third_party\".equals(AlertDefAll.entity.sqlnameC)"
				technicalName = "Third Party"
				boxType = vertical
				isWidgetVisible = false
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/alerts/view/AlertClientQueryCriteriaView.module
			}
			--- ConditionalBody ---
				conditionLang = DSEL
				javaCode = "\"instrument\".equals(AlertDefAll.entity.sqlnameC)"
				technicalName = Instrument
				boxType = vertical
				isWidgetSelected = true
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/alerts/view/AlertInstrumentQueryCriteriaView.module
			}
		}
	}
}