# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = Identification
	domainEntity = "AlertDef:AlertDefAll"
	bean-define = DSBean.AlertDef.AlertDefAll
	bean-name = AlertDefAll
	id = AlertDefView_B_84_
	tid = 503273448109187
{
	--- Box ---
		boxType = vertical
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 2
			gridColumnsWidth = "40,60" !
			gridRowCount = 4
		{
			--- GridCell ---
				gridColumnWidth = 40
			{
				--- LabelDomain ---
					domainAttribute = code !
					for = code
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					required = true
					id = code
			}
			--- GridCell ---
				gridColumnWidth = 60
			{
				--- TextField ---
					domainAttribute = code !
					horizontalAlignment = "${corporatehalign}"
					type = text
					chars = 60
					editable = false
					required = true
					bean-property = code
					id = code
			}
			--- GridCell ---
				gridColumnWidth = 40
			{
				--- LabelDomain ---
					domainAttribute = name !
					for = name
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					id = name
			}
			--- GridCell ---
				gridColumnWidth = 60
			{
				--- TextField ---
					domainAttribute = name !
					columns = 30
					horizontalAlignment = "${corporatehalign}"
					type = text
					chars = 60
					editable = false
					bean-property = name
					id = name
			}
			--- GridCell ---
				gridColumnWidth = 40
			{
				--- LabelDomain ---
					domainAttribute = activeE !
					for = activeE
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					required = true
					id = activeE
			}
			--- GridCell ---
				gridColumnWidth = 60
			{
				--- ComboBox ---
					domainAttribute = activeE !
					horizontalAlignment = "${corporatehalign}"
					editable = false
					required = true
					bean-property = activeE
					id = activeE
			}
			--- GridCell ---
				gridColumnWidth = 40
			{
				--- LabelDomain ---
					domainAttribute = severityE !
					for = severityE
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					required = true
					id = severityE
			}
			--- GridCell ---
				gridColumnWidth = 60
			{
				--- ComboBox ---
					domainAttribute = severityE !
					horizontalAlignment = "${corporatehalign}"
					editable = false
					required = true
					bean-property = severityE
					id = severityE
			}
		}
		--- Conditional ---
			indexOfSelectedChild = 1
		{
			--- ConditionalBody ---
				javaCode = "Integer.valueOf(0).equals(<bean:get-property bean=\"AlertDefAll\" property=\"visibilityE\"/>)"
				technicalName = Public
				boxType = vertical
				isWidgetVisible = false
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 2
					gridColumnsWidth = "40,60" !
					gridRowCount = 1
				{
					--- GridCell ---
						gridColumnWidth = 40
					{
						--- LabelDomain ---
							domainAttribute = dataSecuProf !
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							required = true
					}
					--- GridCell ---
						gridColumnWidth = 60
					{
						--- Include ---
							domainAssociation = dataSecuProf
							includeSrc = "" !
							resource:///default/defaultFragments/DataSecuProfIdentifierView.fragment
							bean-property-prefix = dataSecuProf.
					}
				}
			}
			--- ConditionalBody ---
				javaCode = true
				technicalName = Private
				boxType = vertical
				isWidgetSelected = true
		}
	}
}