# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Alert Query"
	containment = container
	domainEntity = "AlertDef:AlertDefAll"
	bean-define = DSBean.AlertDef.AlertDefAll
	bean-name = AlertDefAll
	id = AlertQueryResult_J228_
	tid = 96695276658625
{
	--- Box ---
		boxType = vertical
	{
		--- Box ---
			boxType = vertical
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 2
				gridColumnsWidth = "50,50" !
				gridRowCount = 2
			{
				--- GridCell ---
					gridColumnWidth = 50
				{
					--- LabelDomain ---
						domainAttribute = entity !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
				}
				--- GridCell ---
					gridColumnWidth = 50
				{
					--- Include ---
						domainAssociation = entity
						includeSrc = "" !
						resource:///default/defaultFragments/DictEntityIdentifierView.fragment
				}
				--- GridCell ---
					gridColumnWidth = 50
				--- GridCell ---
					gridColumnWidth = 50
			}
			--- Conditional ---
				indexOfSelectedChild = 1
			{
				--- ConditionalBody ---
					javaCode = "\"portfolio\".equals(<bean:get-property bean=\"AlertDefAll\" property=\"entity.sqlnameC\"/>)"
					technicalName = Portfolio
					boxType = vertical
					isWidgetVisible = false
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/alerts/view/AlertPortfolioQueryView.module
				}
				--- ConditionalBody ---
					javaCode = "\"third_party\".equals(<bean:get-property bean=\"AlertDefAll\" property=\"entity.sqlnameC\"/>)"
					technicalName = ThirdParty
					boxType = vertical
					isWidgetSelected = true
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/alerts/view/AlertClientQueryView.module
				}
			}
		}
	}
}