# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Notification Messages"
	domainEntity = "AAADSNotification:NotifDefinitionForAlert"
	bean-define = DSBean.AAADSNotification.NotifDefinitionForAlert
	bean-name = NotifDefinitionForAlert
	id = AlertNotificationView_b8r6A
	tid = 503321006143797
{
	--- Box ---
		boxType = vertical
	{
		--- Box ---
			labels en = "English Notification Text"
			boxType = vertical
			tid = 866841362359407
		{
			--- Include ---
				domainAssociation = notifSubjectBodyDefEnglish
				includeSrc = "" !
				resource:///default/alert/AlertDefinitionSubjectAndBodyView.fragment
				bean-property-prefix = notifSubjectBodyDefEnglish.
		}
		--- Box ---
			labels en = "French Notification Text"
			boxType = vertical
			tid = 866892828114377
		{
			--- Include ---
				domainAssociation = notifSubjectBodyDefFrench
				includeSrc = "" !
				resource:///default/alert/AlertDefinitionSubjectAndBodyView.fragment
				bean-property-prefix = notifSubjectBodyDefFrench.
		}
		--- Box ---
			labels en = "German Notification Text"
			tid = 504916095687859
		{
			--- Include ---
				domainAssociation = notifSubjectBodyDefGerman
				includeSrc = "" !
				resource:///default/alert/AlertDefinitionSubjectAndBodyView.fragment
				bean-property-prefix = notifSubjectBodyDefFrench.
		}
	}
}