# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = Schedule
	domainEntity = "AlertDef:ScheduleDefAll"
	bean-define = DSBean.AlertDef.ScheduleDefAll
	bean-name = ScheduleDefAll
	id = AlertScheduleView_vVG46
	tid = 808144889091889
{
	--- Box ---
		boxType = vertical
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 2
			gridColumnsWidth = "50,50" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 50
			{
				--- LabelDomain ---
					domainAttribute = frequencyE !
					for = frequencyE
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					required = true
					id = frequencyE
			}
			--- GridCell ---
				gridColumnWidth = 50
			{
				--- ComboBox ---
					domainAttribute = frequencyE !
					horizontalAlignment = "${corporatehalign}"
					editable = false
					required = true
					bean-property = frequencyE
					id = frequencyE
				{
					Event OnChange (submit)
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						widget-group-ref = form
						target = self
						param = "flow-action=changeFrequency"
						only-changed = true
						prevalidate = false
						modal = false
					}
				}
			}
		}
		--- Conditional ---
			indexOfSelectedChild = 2
		{
			--- ConditionalBody ---
				javaCode = "Integer.valueOf(com.odcgroup.aaa.ScheduleDefFrequencyE.OneTime).equals(<bean:get-property bean=\"ScheduleDefAll\" property=\"frequencyE\"/>)"
				technicalName = OneTime
				boxType = vertical
				isWidgetVisible = false
			{
				--- Box ---
				{
					--- Grid ---
						cssClass = blank
						gridColumnCount = 2
						gridColumnsWidth = "25,25" !
						gridRowCount = 2
					{
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								domainAttribute = startD !
								for = startD
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								id = startD
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- CaldateField ---
								domainAttribute = startD !
								format = datetime.date-only
								horizontalAlignment = "${corporatehalign}"
								type = datetime
								editable = false
								required = true
								bean-property = startD
								id = startD
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								domainAttribute = startTimeD !
								for = startTimeD
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								id = startTimeD
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- CaldateField ---
								domainAttribute = startTimeD !
								format = datetime.time-only-edit
								horizontalAlignment = "${corporatehalign}"
								type = datetime
								editable = false
								required = true
								bean-property = startTimeD
								id = startTimeD
						}
					}
				}
			}
			--- ConditionalBody ---
				javaCode = "Integer.valueOf(com.odcgroup.aaa.ScheduleDefFrequencyE.Daily).equals(<bean:get-property bean=\"ScheduleDefAll\" property=\"frequencyE\"/>)"
				technicalName = Daily
				boxType = vertical
				isWidgetVisible = false
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 4
					gridColumnsWidth = "25,25,25,25" !
					gridRowCount = 3
				{
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- LabelDomain ---
							domainAttribute = startTimeD !
							for = startTimeD
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							id = startTimeD
					}
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- CaldateField ---
							domainAttribute = startTimeD !
							format = datetime.time-only
							horizontalAlignment = "${corporatehalign}"
							type = datetime
							editable = false
							bean-property = startTimeD
							id = startTimeD
					}
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- LabelDomain ---
							domainAttribute = endTimeD !
							for = endTimeD
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							id = endTimeD
					}
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- CaldateField ---
							domainAttribute = endTimeD !
							format = datetime.time-only-edit
							horizontalAlignment = "${corporatehalign}"
							type = datetime
							editable = false
							bean-property = endTimeD
							id = endTimeD
					}
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- LabelDomain ---
							domainAttribute = expirationD !
							for = expirationD
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							id = expirationD
					}
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- CaldateField ---
							domainAttribute = expirationD !
							format = datetime.date-only
							horizontalAlignment = "${corporatehalign}"
							type = datetime
							editable = false
							bean-property = expirationD
							id = expirationD
					}
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- LabelDomain ---
							labels en = "Recurrency Frequency"
							domainAttribute = recurMinutesN !
							for = recurMinutesN
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							id = recurMinutesN
							tid = 504218469426142
					}
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- TextField ---
							domainAttribute = recurMinutesN !
							columns = 2
							format = integer
							horizontalAlignment = "${corporatehalign}"
							type = integer
							chars = 9
							editable = false
							bean-property = recurMinutesN
							id = recurMinutesN
					}
					--- GridCell ---
						gridColumnWidth = 25
					--- GridCell ---
						gridColumnWidth = 25
					--- GridCell ---
						gridColumnWidth = 25
					--- GridCell ---
						gridColumnWidth = 25
				}
			}
			--- ConditionalBody ---
				javaCode = "Integer.valueOf(com.odcgroup.aaa.ScheduleDefFrequencyE.Weekly).equals(<bean:get-property bean=\"ScheduleDefAll\" property=\"frequencyE\"/>)"
				technicalName = Weekly
				boxType = vertical
				isWidgetSelected = true
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 4
					gridColumnsWidth = "25,25,25,25" !
					gridRowCount = 7
				{
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- LabelDomain ---
							domainAttribute = startTimeD !
							for = startTimeD
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							id = startTimeD
					}
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- CaldateField ---
							domainAttribute = startTimeD !
							format = datetime.time-only-edit
							horizontalAlignment = "${corporatehalign}"
							type = datetime
							editable = false
							bean-property = startTimeD
							id = startTimeD
					}
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- LabelDomain ---
							domainAttribute = endTimeD !
							for = endTimeD
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							id = endTimeD
					}
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- CaldateField ---
							domainAttribute = endTimeD !
							format = datetime.time-only-edit
							horizontalAlignment = "${corporatehalign}"
							type = datetime
							editable = false
							bean-property = endTimeD
							id = endTimeD
					}
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- LabelDomain ---
							domainAttribute = expirationD !
							for = expirationD
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							id = expirationD
					}
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- CaldateField ---
							domainAttribute = expirationD !
							format = datetime.date-only
							horizontalAlignment = "${corporatehalign}"
							type = datetime
							editable = false
							bean-property = expirationD
							id = expirationD
					}
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- LabelDomain ---
							labels en = "Recurrency Frequency"
							domainAttribute = recurMinutesN !
							for = recurMinutesN
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							id = recurMinutesN
							tid = 504264595505574
					}
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- TextField ---
							domainAttribute = recurMinutesN !
							columns = 9
							format = integer
							horizontalAlignment = "${corporatehalign}"
							type = integer
							chars = 9
							editable = false
							bean-property = recurMinutesN
							id = recurMinutesN
					}
					--- GridCell ---
						gridColumnWidth = 25
					--- GridCell ---
						gridColumnWidth = 25
					--- GridCell ---
						gridColumnWidth = 25
					--- GridCell ---
						gridColumnWidth = 25
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- Label ---
							labels en = Weekdays
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							tid = 504264597351618
					}
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- CheckBox ---
							column-checkbox-action = ""
							domainAttribute = mondayF
							horizontalTextPosition = trail
							enabled = false
							bean-property = mondayF
							id = mondayF
					}
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- CheckBox ---
							column-checkbox-action = ""
							domainAttribute = tuesdayF
							horizontalTextPosition = trail
							enabled = false
							bean-property = tuesdayF
							id = tuesdayF
					}
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- CheckBox ---
							column-checkbox-action = ""
							domainAttribute = wednesdayF
							horizontalTextPosition = trail
							enabled = false
							bean-property = wednesdayF
							id = wednesdayF
					}
					--- GridCell ---
						gridColumnWidth = 25
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- CheckBox ---
							column-checkbox-action = ""
							domainAttribute = thursdayF
							horizontalTextPosition = trail
							enabled = false
							bean-property = thursdayF
							id = thursdayF
					}
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- CheckBox ---
							column-checkbox-action = ""
							domainAttribute = fridayF
							horizontalTextPosition = trail
							enabled = false
							bean-property = fridayF
							id = fridayF
					}
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- CheckBox ---
							column-checkbox-action = ""
							domainAttribute = saturdayF
							horizontalTextPosition = trail
							enabled = false
							bean-property = saturdayF
							id = saturdayF
					}
					--- GridCell ---
						gridColumnWidth = 25
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- CheckBox ---
							column-checkbox-action = ""
							domainAttribute = sundayF
							horizontalTextPosition = trail
							enabled = false
							bean-property = sundayF
							id = sundayF
					}
					--- GridCell ---
						gridColumnWidth = 25
					--- GridCell ---
						gridColumnWidth = 25
					--- GridCell ---
						gridColumnWidth = 25
					--- GridCell ---
						gridColumnWidth = 25
					--- GridCell ---
						gridColumnWidth = 25
					--- GridCell ---
						gridColumnWidth = 25
				}
			}
			--- ConditionalBody ---
				javaCode = "Integer.valueOf(com.odcgroup.aaa.ScheduleDefFrequencyE.Monthly).equals(<bean:get-property bean=\"ScheduleDefAll\" property=\"frequencyE\"/>)"
				technicalName = Monthly
				boxType = vertical
				isWidgetVisible = false
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 5
					gridColumnsWidth = "20,20,20,20,20" !
					gridRowCount = 14
				{
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- LabelDomain ---
							domainAttribute = startTimeD !
							for = startTimeD
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							id = startTimeD
					}
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- CaldateField ---
							domainAttribute = startTimeD !
							format = datetime.time-only-edit
							horizontalAlignment = "${corporatehalign}"
							type = datetime
							editable = false
							bean-property = startTimeD
							id = startTimeD
					}
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- LabelDomain ---
							domainAttribute = endTimeD !
							for = endTimeD
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							id = endTimeD
					}
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- CaldateField ---
							domainAttribute = endTimeD !
							format = datetime.time-only-edit
							horizontalAlignment = "${corporatehalign}"
							type = datetime
							editable = false
							bean-property = endTimeD
							id = endTimeD
					}
					--- GridCell ---
						gridColumnWidth = 20
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- LabelDomain ---
							domainAttribute = expirationD !
							for = expirationD
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							id = expirationD
					}
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- CaldateField ---
							domainAttribute = expirationD !
							format = datetime.date-only
							horizontalAlignment = "${corporatehalign}"
							type = datetime
							editable = false
							bean-property = expirationD
							id = expirationD
					}
					--- GridCell ---
						gridColumnWidth = 20
					--- GridCell ---
						gridColumnWidth = 20
					--- GridCell ---
						gridColumnWidth = 20
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- LabelDomain ---
							labels en = "Recurrency Frequency"
							domainAttribute = recurMinutesN !
							for = recurMinutesN
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							id = recurMinutesN
							tid = 504369098438768
					}
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- TextField ---
							domainAttribute = recurMinutesN !
							columns = 2
							format = integer
							horizontalAlignment = "${corporatehalign}"
							type = integer
							chars = 9
							editable = false
							bean-property = recurMinutesN
							id = recurMinutesN
					}
					--- GridCell ---
						gridColumnWidth = 20
					--- GridCell ---
						gridColumnWidth = 20
					--- GridCell ---
						gridColumnWidth = 20
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- Label ---
							labels en = Months
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							tid = 504369100281181
					}
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- CheckBox ---
							column-checkbox-action = ""
							domainAttribute = januaryF
							horizontalTextPosition = trail
							enabled = false
							bean-property = januaryF
							id = januaryF
					}
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- CheckBox ---
							column-checkbox-action = ""
							domainAttribute = aprilF
							horizontalTextPosition = trail
							enabled = false
							bean-property = aprilF
							id = aprilF
					}
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- CheckBox ---
							column-checkbox-action = ""
							domainAttribute = julyF
							horizontalTextPosition = trail
							enabled = false
							bean-property = julyF
							id = julyF
					}
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- CheckBox ---
							column-checkbox-action = ""
							domainAttribute = octoberF
							horizontalTextPosition = trail
							enabled = false
							bean-property = octoberF
							id = octoberF
					}
					--- GridCell ---
						gridColumnWidth = 20
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- CheckBox ---
							column-checkbox-action = ""
							domainAttribute = februaryF
							horizontalTextPosition = trail
							enabled = false
							bean-property = februaryF
							id = februaryF
					}
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- CheckBox ---
							column-checkbox-action = ""
							domainAttribute = mayF
							horizontalTextPosition = trail
							enabled = false
							bean-property = mayF
							id = mayF
					}
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- CheckBox ---
							column-checkbox-action = ""
							domainAttribute = augustF
							horizontalTextPosition = trail
							enabled = false
							bean-property = augustF
							id = augustF
					}
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- CheckBox ---
							column-checkbox-action = ""
							domainAttribute = novemberF
							horizontalTextPosition = trail
							enabled = false
							bean-property = novemberF
							id = novemberF
					}
					--- GridCell ---
						gridColumnWidth = 20
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- CheckBox ---
							column-checkbox-action = ""
							domainAttribute = marchF
							horizontalTextPosition = trail
							enabled = false
							bean-property = marchF
							id = marchF
					}
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- CheckBox ---
							column-checkbox-action = ""
							domainAttribute = juneF
							horizontalTextPosition = trail
							enabled = false
							bean-property = juneF
							id = juneF
					}
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- CheckBox ---
							column-checkbox-action = ""
							domainAttribute = septemberF
							horizontalTextPosition = trail
							enabled = false
							bean-property = septemberF
							id = septemberF
					}
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- CheckBox ---
							column-checkbox-action = ""
							domainAttribute = decemberF
							horizontalTextPosition = trail
							enabled = false
							bean-property = decemberF
							id = decemberF
					}
					--- GridCell ---
						gridColumnWidth = 20
					--- GridCell ---
						gridColumnWidth = 20
					--- GridCell ---
						gridColumnWidth = 20
					--- GridCell ---
						gridColumnWidth = 20
					--- GridCell ---
						gridColumnWidth = 20
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- Label ---
							labels en = Weekdays
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							tid = 504369102223047
					}
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- CheckBox ---
							column-checkbox-action = ""
							domainAttribute = mondayF
							horizontalTextPosition = trail
							enabled = false
							bean-property = mondayF
							id = mondayF
					}
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- CheckBox ---
							column-checkbox-action = ""
							domainAttribute = tuesdayF
							horizontalTextPosition = trail
							enabled = false
							bean-property = tuesdayF
							id = tuesdayF
					}
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- CheckBox ---
							column-checkbox-action = ""
							domainAttribute = wednesdayF
							horizontalTextPosition = trail
							enabled = false
							bean-property = wednesdayF
							id = wednesdayF
					}
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- CheckBox ---
							column-checkbox-action = ""
							domainAttribute = thursdayF
							horizontalTextPosition = trail
							enabled = false
							bean-property = thursdayF
							id = thursdayF
					}
					--- GridCell ---
						gridColumnWidth = 20
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- CheckBox ---
							column-checkbox-action = ""
							domainAttribute = fridayF
							horizontalTextPosition = trail
							enabled = false
							bean-property = fridayF
							id = fridayF
					}
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- CheckBox ---
							column-checkbox-action = ""
							domainAttribute = saturdayF
							horizontalTextPosition = trail
							enabled = false
							bean-property = saturdayF
							id = saturdayF
					}
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- CheckBox ---
							column-checkbox-action = ""
							domainAttribute = sundayF
							horizontalTextPosition = trail
							enabled = false
							bean-property = sundayF
							id = sundayF
					}
					--- GridCell ---
						gridColumnWidth = 20
					--- GridCell ---
						gridColumnWidth = 20
					--- GridCell ---
						gridColumnWidth = 20
					--- GridCell ---
						gridColumnWidth = 20
					--- GridCell ---
						gridColumnWidth = 20
					--- GridCell ---
						gridColumnWidth = 20
					--- GridCell ---
						gridColumnWidth = 20
					--- GridCell ---
						gridColumnWidth = 20
					--- GridCell ---
						gridColumnWidth = 20
					--- GridCell ---
						gridColumnWidth = 20
					--- GridCell ---
						gridColumnWidth = 20
					--- GridCell ---
						gridColumnWidth = 20
					--- GridCell ---
						gridColumnWidth = 20
					--- GridCell ---
						gridColumnWidth = 20
					--- GridCell ---
						gridColumnWidth = 20
					--- GridCell ---
						gridColumnWidth = 20
					--- GridCell ---
						gridColumnWidth = 20
					--- GridCell ---
						gridColumnWidth = 20
					--- GridCell ---
						gridColumnWidth = 20
					--- GridCell ---
						gridColumnWidth = 20
					--- GridCell ---
						gridColumnWidth = 20
					--- GridCell ---
						gridColumnWidth = 20
					--- GridCell ---
						gridColumnWidth = 20
					--- GridCell ---
						gridColumnWidth = 20
					--- GridCell ---
						gridColumnWidth = 20
					--- GridCell ---
						gridColumnWidth = 20
				}
			}
		}
	}
}