# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	containment = container
	domainEntity = "AlertDef:AlertDefAll"
	bean-define = DSBean.AlertDef.AlertDefAll
	bean-name = AlertDefAll
	id = AlertQueryDetailsView_i62YB
{
	--- Box ---
		boxType = vertical
	{
		--- Box ---
		{
			--- LabelDomain ---
				domainAttribute = entity !
				horizontalAlignment = "${corporatehalign}"
				required = true
			--- Include ---
				domainAssociation = entity
				includeSrc = "" !
				resource:///default/defaultFragments/DictEntityIdentifierView.fragment
				bean-property-prefix = entityDict.
			--- Glue ---
		}
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/alerts/view/AlertDefView.module
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/alerts/view/AlertScheduleView.module
	}
}