# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSList:ListPreDefQuery"
	cssClass = nodeco
	bean-define = DSBean.AAADSList.ListPreDefQuery
	bean-name = ListPreDefQuery
	id = ListOfPredefinedClientQueriesAll_A_k9_
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			id = S3_y4
			table-column-count = 2 !
			table-columns-width = "50,50" !
		{
			--- TableColumn ---
				column-name = name !
				column-type = domain !
				domainAttribute = name !
				type = text
				column-locked = true
				id = name
				table-column-width = 50
			{
				--- TableColumnItem ---
					item-column = name
					previewValue = value
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = preDefinedSearch ud
						Query.dbId = "<udp:item column=\"id\"/>" ud
						code = "<udp:item column=\"code\"/>" ud
						entity.dict = "<udp:item column=\"entityDict\"/>" ud
						Query.beanProperty1 = portfolioDimThirdParty.code ud
						modal = false
						only-changed = false
						prevalidate = false
						Snippet Query
						queryAttributes = "extDaysOperation,extDenomination,searchCode,statusE,typeCode,code,extCstCompliance,extAdvisoryMandate,extDateOperation,extObjCompliance,extTdMktValM,name,extDaysProposal,extDateProposal"
						queryOutputModule = "" !
						resource:///Default/module/aaa/administration/queries/ClientQueryResultsUncontacted.module
						Snippet FilterSet
						id = fs_I94
						level = 2
						targetDataset = "AAADSThirdParty:ThirdPartySearchCriteria"
						{
							Snippet Filter
							attribute = activeF
							filterValue = Yes
							operator = EQUAL
							Snippet Filter
							attribute = statusE
							editMode = editable
							filterValue = "Active,Prospect,None"
							operator = IN
							Snippet Filter
							attribute = clientF
							filterValue = Yes
							operator = EQUAL
						}
					}
				}
			}
			--- TableColumn ---
				column-name = extDenomination !
				column-type = domain !
				domainAttribute = extDenomination !
				type = text
				id = extDenomination
				table-column-width = 50
			{
				--- TableColumnItem ---
					item-column = extDenomination
					previewValue = value
			}
			--- TableExtra ---
				domainAttribute = entityDict
			--- TableExtra ---
				domainAttribute = id
			--- TableSort ---
				sort-column-name = name
				sort-rank = 2
			--- TableExtra ---
				domainAttribute = code
		}
		--- Include ---
			includeSrc = "" !
			resource:///default/alert/AlertNavigationCancel.fragment
	}
}