# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "View Alert Details"
	containment = container
	domainEntity = "AlertDef:AlertDefAll"
	bean-define = DSBean.AlertDef.AlertDefAll
	bean-name = AlertDefAll
	id = AlertView_e___2
	tid = 502914157872858
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/alerts/view/AlertDefView.module
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/alerts/view/AlertScheduleView.module
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/alerts/view/AlertQueryCriteriaView.module
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/alerts/view/AlertNotificationView.module
		--- Conditional ---
			indexOfSelectedChild = 0
		{
			--- ConditionalBody ---
				javaCode = "(<bean:get-property bean=\"AlertDefAll\" property=\"visibilityE\"/>) != null &amp;&amp;\r\n((Integer)(<bean:get-property bean=\"AlertDefAll\" property=\"visibilityE\"/>)).intValue() == 0"
				technicalName = "Is a Public Alert"
				boxType = vertical
				isWidgetSelected = true
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/alerts/AlertRecipientsList.module
			}
			--- ConditionalBody ---
				javaCode = true
				technicalName = Default
				boxType = vertical
				isWidgetVisible = false
		}
	}
}