# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	containment = container
	search = container
	cssClass = nodeco
	id = AlertPortfolioQueryView_m_954
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/alerts/view/AlertSearchCriteriaView.module
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/alerts/view/AlertSearchPortfolioOutput.module
	}
}