# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSComplianceChecking:ComplianceCheckingPG"
	cssClass = nodeco
	bean-define = DSBean.AAADSComplianceChecking.ComplianceCheckingPG
	bean-name = ComplianceCheckingPG
	id = AssetAllocation_t69vX
	documentation = "This module displays compliance details on the selected Portfolio. The compliance details are based only on objectives.\r\n\r\nThis module is used in the module <DetailedList> for the tab \"Objectives Compliance\""
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			table-fixed-size = true
			table-height = 600
			id = v_J_S
			table-column-count = 2 !
			table-columns-width = "50,50" !
		{
			--- TableColumn ---
				labels en = "Investment Strategy", de = Anlagestrategie, fr = "Stratégie d\'investissement"
				column-display-grouping = true
				column-name = placeholder_yK3X_
				column-type = placeholder !
				type = text
				column-locked = true
				column-sortable = false !
				id = yK3X_
				table-column-width = 50
				tid = 47066854623860
			{
				--- TableGroup ---
					aggregateData = false
					group-column-name = MKT_STRUCTURE
					group-sorting-column-name = MKT_STRUCTURE_SORT
					group-sorting-direction = ascending
					hierarchy = true
					group-rank = 1
			}
			--- TableColumn ---
				labels de = "Optimales Gewicht des Ziels"
				column-name = OBJECTIVE_WEIGHT_WITH_MARGIN !
				column-type = domain !
				domainAttribute = OBJECTIVE_WEIGHT_WITH_MARGIN !
				type = text
				id = OBJECTIVE_WEIGHT_WITH_MARGIN
				table-column-width = 50
				tid = 1604012253060293
			{
				--- TableColumnItem ---
					item-column = OBJECTIVE_WEIGHT_WITH_MARGIN
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = MKT_STRUCTURE_SORT
				sort-rank = 1
			--- TableExtra ---
				domainAttribute = MKT_STRUCTURE_SORT
		}
	}
}