# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Asset Allocation", de = Allokation, fr = "Allocation d’actifs"
	containment = container
	id = InvestmentStrategy_E_F8_
	tid = 803550081620528
{
	--- Box ---
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/orderproposal/compliance/AssetAllocation.module
		--- Spacer ---
			height = 4
			width = 10
		--- Box ---
			boxType = vertical
		{
			--- Code ---
				code = "<cinclude:include src=\"cocoon://module/aaa/corda/orderproposal/assetAllocation/Graph\" />"
		}
	}
}