# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSIssRedmEvent:IssRedmEventList"
	cssClass = nodeco
	bean-define = DSBean.AAADSIssRedmEvent.IssRedmEventList
	bean-name = IssRedmEventList
	id = IssueRedemptionEventList_hv_6_
{
	--- Box ---
		labels en = "Issue Redemption Events", de = Ausgabe/Rücknahme-Ereignisse, fr = "Evénements de rachat d\'émission"
		boxType = vertical
		widgetBorder = box
		width = 0
		tid = 1142642460997696
	{
		--- TableTree ---
			table-filter-layer = true
			id = q3L1I
			table-column-count = 16 !
			table-columns-width = "6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6" !
			table-filterset-id = fs_W1Y
		{
			--- TableColumn ---
				column-name = validityD !
				column-type = domain !
				domainAttribute = validityD !
				column-locked = true
				id = validityD
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = validityD
					format = date
					previewValue = value
			}
			--- TableColumn ---
				column-name = beginD !
				column-type = domain !
				domainAttribute = beginD !
				id = beginD
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = beginD
					format = date
					previewValue = value
			}
			--- TableColumn ---
				column-name = natureE !
				column-type = domain !
				domainAttribute = natureE !
				type = text
				id = natureE
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = natureE
					previewValue = value
			}
			--- TableColumn ---
				column-name = code !
				column-type = domain !
				domainAttribute = code !
				type = text
				column-visibility = not-visible
				id = code
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = code
					previewValue = value
			}
			--- TableColumn ---
				column-name = endD !
				column-type = domain !
				domainAttribute = endD !
				type = text
				id = endD
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = endD
					format = date
					previewValue = value
			}
			--- TableColumn ---
				column-name = endValidityD !
				column-type = domain !
				domainAttribute = endValidityD !
				type = text
				column-visibility = not-visible
				id = endValidityD
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = endValidityD
					format = date
					previewValue = value
			}
			--- TableColumn ---
				column-name = announceD !
				column-type = domain !
				domainAttribute = announceD !
				type = text
				id = announceD
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = announceD
					format = date
					previewValue = value
			}
			--- TableColumn ---
				labels en = Currency, fr = Currency, de = Currency
				column-name = currencyCode !
				column-type = domain !
				domainAttribute = currencyCode !
				type = text
				id = currencyCode
				table-column-width = 6
				tid = 24236365771627
			{
				--- TableColumnItem ---
					item-column = currencyCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = quoteN !
				column-type = domain !
				domainAttribute = quoteN !
				type = text
				id = quoteN
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = quoteN
					format = decimal.detailed
					previewValue = value
			}
			--- TableColumn ---
				column-name = freqN !
				column-type = domain !
				domainAttribute = freqN !
				type = text
				column-visibility = not-visible
				id = freqN
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = freqN
					format = integer
					previewValue = value
			}
			--- TableColumn ---
				column-name = freqUnitE !
				column-type = domain !
				domainAttribute = freqUnitE !
				type = text
				column-visibility = not-visible
				id = freqUnitE
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = freqUnitE
					previewValue = value
			}
			--- TableColumn ---
				column-name = fixedExchRate !
				column-type = domain !
				domainAttribute = fixedExchRate !
				type = text
				column-visibility = not-visible
				id = fixedExchRate
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = fixedExchRate
					format = decimal.detailed
					previewValue = value
			}
			--- TableColumn ---
				column-name = proportionP !
				column-type = domain !
				domainAttribute = proportionP !
				type = text
				column-visibility = not-visible
				id = proportionP
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = proportionP
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = settleDaysN !
				column-type = domain !
				domainAttribute = settleDaysN !
				type = text
				column-visibility = not-visible
				id = settleDaysN
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = settleDaysN
					format = integer
					previewValue = value
			}
			--- TableColumn ---
				column-name = effectiveD !
				column-type = domain !
				domainAttribute = effectiveD !
				type = text
				id = effectiveD
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = effectiveD
					format = datetime.date-only
					previewValue = value
			}
			--- TableColumn ---
				column-name = noticeDayN !
				column-type = domain !
				domainAttribute = noticeDayN !
				type = text
				id = noticeDayN
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = noticeDayN
					format = integer
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = validityD
				sort-direction = descending
				sort-rank = 2
			--- TableSort ---
				sort-column-name = beginD
				sort-direction = descending
				sort-rank = 3
			--- TableSort ---
				sort-column-name = natureE
				sort-direction = descending
				sort-rank = 5
			--- TableSort ---
				sort-column-name = endD
				sort-direction = descending
				sort-rank = 4
			--- TableSort ---
				sort-column-name = endValidityD
				sort-direction = descending
				sort-rank = 6
		}
	}
}