# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Search Currency", de = "Währung Suche", fr = "Recherche de devise"
	containment = container
	search = container !
	cssClass = nodeco
	id = CurrencySearch_g6__9
	tid = 1255846168242058
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/currency/search/CurrencySearchInput.module
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/currency/search/CurrencyList.module
	}
}