# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Currency Search Criteria", de = "Währung Suchbegriffe", fr = "Critères de recherche sur devise"
	containment = container
	domainEntity = "AAADSCurrency:CurrencySearchCriteria"
	search = input !
	bean-define = DSBean.AAADSCurrency.CurrencySearchCriteria
	bean-name = CurrencySearchCriteria
	id = CurrencySearchInput_CtX00
	tid = 1256577304552393
{
	--- Box ---
		boxType = vertical
	{
		--- FilterCriteria ---
			includedFile = "resource:/com/module/search/QueryBuilder.xsp"
		--- Include ---
			includeSrc = "" !
			resource:///default/search/NavigationSearch.fragment
	}
}