# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Search Results", de = Suchergebnisse, fr = "Résultats de la recherche"
	domainEntity = "AAADSCurrency:CurrencyList"
	search = output !
	bean-define = DSBean.AAADSCurrency.CurrencyList
	bean-name = CurrencyList
	id = CurrencyList_CA1__
	tid = 12122766560554
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			id = a2___
			table-model-reference = DSTableModel.AAADSCurrency.CurrencyList
			table-column-count = 6 !
			table-columns-width = "16,16,16,16,16,16" !
		{
			--- TableColumn ---
				labels de = Code
				column-name = code !
				column-type = domain !
				domainAttribute = code !
				column-locked = true
				id = code
				table-column-width = 16
				tid = 24171076228962
			{
				--- Conditional ---
					indexOfSelectedChild = 1
				{
					--- ConditionalBody ---
						javaCode = "com.odcgroup.tsl.wui.search.form.SearchFormHelper.isLookup(objectModel) == false"
						technicalName = NotLookup
						boxType = vertical
						isWidgetVisible = false
					{
						--- TableColumnItem ---
							toolTips en = "Select Currency", fr = "Sélectionner la devise", de = "Währung auswählen"
							item-column = code
							previewValue = value
							tid = 366017521826799
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = select ud
								Query.beanValue1 = "<udp:item column=\"code\"/>" ud
								Query.beanValue2 = "<udp:item column=\"name\"/>" ud
								modal = false
								only-changed = false
								prevalidate = false
							}
						}
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetSelected = true
					{
						--- TableColumnItem ---
							toolTips en = "Select Currency", fr = "Sélectionner la devise", de = "Währung auswählen"
							item-column = code
							previewValue = value
							tid = 366017523776401
						{
							Event OnClick (setWidgetValue)
							{
								widget-group-id = "<xsp:expr>com.odcgroup.tsl.wui.search.form.SearchFormHelper.getParentWidgetValue1Id(objectModel)</xsp:expr>"
								value = "<udp:item column=\"code\"/>"
								target = WUI_main
							}
							Event OnClick (winClose)
							{
								target = self
							}
						}
					}
				}
			}
			--- TableColumn ---
				column-name = name !
				column-type = domain !
				domainAttribute = name !
				id = name
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = name
					previewValue = value
			}
			--- TableColumn ---
				column-name = extDenomination !
				column-type = domain !
				domainAttribute = extDenomination !
				type = text
				id = extDenomination
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = extDenomination
					previewValue = value
			}
			--- TableColumn ---
				column-name = geographicExtDenomination !
				column-type = domain !
				domainAttribute = geographicExtDenomination !
				type = text
				id = geographicExtDenomination
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = geographicExtDenomination
					previewValue = value
			}
			--- TableColumn ---
				column-name = extBestDispCode !
				column-type = domain !
				domainAttribute = extBestDispCode !
				type = text
				column-visibility = not-visible
				id = extBestDispCode
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = extBestDispCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = rankN !
				column-type = domain !
				domainAttribute = rankN !
				column-visibility = not-visible
				id = rankN
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = rankN
					format = integer
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = code
				sort-rank = 1
		}
	}
}