# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSValRuleHistory:ValRuleHistoryList"
	bean-define = DSBean.AAADSValRuleHistory.ValRuleHistoryList
	bean-name = ValRuleHistoryList
	id = VlaRuleHistoryList_I7_k1
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			id = S6Z9_
			table-column-count = 2 !
			table-columns-width = "50,50" !
		{
			--- TableColumn ---
				column-name = valRuleCode !
				column-type = domain !
				domainAttribute = valRuleCode !
				id = valRuleCode
				table-column-width = 50
			{
				--- TableColumnItem ---
					item-column = valRuleCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = beginD !
				column-type = domain !
				domainAttribute = beginD !
				id = beginD
				table-column-width = 50
			{
				--- TableColumnItem ---
					item-column = beginD
					format = datetime.date-only
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = valRuleCode
				sort-rank = 1
			--- TableSort ---
				sort-column-name = beginD
				sort-direction = descending
				sort-rank = 2
		}
	}
}