# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSOrderList:OrderListDetailedList"
	cssClass = nodeco
	bean-define = DSBean.AAADSOrderList.OrderListDetailedList
	bean-name = OrderListDetailedList
	id = SecurityDetailedListViewOnly_E22Jg
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			id = E05__
			table-column-count = 28 !
			table-columns-width = "3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3" !
		{
			--- TableColumn ---
				column-name = ORDER_CODE !
				column-type = domain !
				domainAttribute = ORDER_CODE !
				type = text
				id = WN_ts
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = ORDER_CODE
					previewValue = value
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = view ud
						code = "<udp:item column=\"ORDER_CODE\"/>" ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- TableColumn ---
				column-name = CREATION_DATE !
				column-type = domain !
				domainAttribute = CREATION_DATE !
				type = text
				id = Y8t__
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = CREATION_DATE
					format = datetime.date-only
					previewValue = value
			}
			--- TableColumn ---
				column-name = ORDER_DATE !
				column-type = domain !
				domainAttribute = ORDER_DATE !
				type = text
				id = rG2eT
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = ORDER_DATE
					format = datetime.date-only
					previewValue = value
			}
			--- TableColumn ---
				column-name = PORTFOLIO_NAME !
				column-type = domain !
				domainAttribute = PORTFOLIO_NAME !
				type = text
				id = xLar_
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = PORTFOLIO_NAME
					previewValue = value
			}
			--- TableColumn ---
				column-name = INSTR_NAME !
				column-type = domain !
				domainAttribute = INSTR_NAME !
				type = text
				id = A0___
				table-column-width = 3
			{
				--- Icon ---
					icon = application_form_magnify
					id = E1_8_
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "resource:///administration/instrument/InstrumentQuickView.pageflow"
						target = popup
						code = "<udp:item column=\"INSTR_CODE\"/>" ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
				--- Spacer ---
					height = 4
					width = 10
				--- TableColumnItem ---
					item-column = INSTR_NAME
					previewValue = value
			}
			--- TableColumn ---
				column-name = INSTR_ISIN !
				column-type = domain !
				domainAttribute = INSTR_ISIN !
				type = text
				id = nv_E_
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = INSTR_ISIN
					previewValue = value
			}
			--- TableColumn ---
				column-name = ORDER_NATURE !
				column-type = domain !
				domainAttribute = ORDER_NATURE !
				type = text
				id = O1__v
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = ORDER_NATURE
					previewValue = value
			}
			--- TableColumn ---
				column-name = QUANTITY !
				column-type = domain !
				domainAttribute = QUANTITY !
				type = text
				id = b_Ty_
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = QUANTITY
					format = decimal
					previewValue = value
			}
			--- TableColumn ---
				column-name = PRICE !
				column-type = domain !
				domainAttribute = PRICE !
				type = text
				id = M7_X3
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = PRICE
					format = decimal.detailed
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Order Net Amount", fr = "Montant net de l\'ordre", de = Auftrags-Nettobetrag
				column-name = ORDER_NET_AMT
				type = amount
				id = Z_48_
				column-computation = make-amount
				column-computation-parameters = "ORDER_NET_AMOUNT,ORDER_CURRENCY"
				table-column-width = 3
				tid = 6364156479807070
			{
				--- TableColumnItem ---
					item-column = ORDER_NET_AMT
					previewValue = value
			}
			--- TableColumn ---
				column-name = MARKET !
				column-type = domain !
				domainAttribute = MARKET !
				type = text
				id = U_sgQ
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = MARKET
					previewValue = value
			}
			--- TableColumn ---
				column-name = ORDER_MODE_TYPE !
				column-type = domain !
				domainAttribute = ORDER_MODE_TYPE !
				type = text
				id = d_H__
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = ORDER_MODE_TYPE
					previewValue = value
			}
			--- TableColumn ---
				column-name = VALIDITY_DATE !
				column-type = domain !
				domainAttribute = VALIDITY_DATE !
				type = text
				id = K1Tc_
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = VALIDITY_DATE
					format = date
					previewValue = value
			}
			--- TableColumn ---
				column-name = LIMIT !
				column-type = domain !
				domainAttribute = LIMIT !
				type = text
				id = g__18
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = LIMIT
					format = decimal
					previewValue = value
			}
			--- TableColumn ---
				column-name = STOP !
				column-type = domain !
				domainAttribute = STOP !
				type = text
				id = F__if
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = STOP
					format = decimal.detailed
					previewValue = value
			}
			--- TableColumn ---
				column-name = VALUE_DATE !
				column-type = domain !
				domainAttribute = VALUE_DATE !
				type = text
				id = VALUE_DATE
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = VALUE_DATE
					format = date
					previewValue = value
			}
			--- TableColumn ---
				column-name = STATUS !
				column-type = domain !
				domainAttribute = STATUS !
				type = text
				id = oS1__
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = STATUS
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Order Gross Amount", fr = "Montant brut de l\'ordre", de = Auftrags-Bruttobetrag
				column-name = ORDER_GROSS_AMT
				type = amount
				column-visibility = not-visible
				id = e1_b_
				column-computation = make-amount
				column-computation-parameters = "ORDER_GROSS_AMOUNT,ORDER_CURRENCY"
				table-column-width = 3
				tid = 6364156481946449
			{
				--- TableColumnItem ---
					item-column = ORDER_GROSS_AMT
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Accrued Interest", fr = "Intérêt couru", de = Stückzins
				column-name = ACC_INT
				type = amount
				column-visibility = not-visible
				id = T_44_
				column-computation = make-amount
				column-computation-parameters = "ACCRUED_INTEREST,ORDER_CURRENCY"
				table-column-width = 3
				tid = 6364156498688800
			{
				--- TableColumnItem ---
					item-column = ACC_INT
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Fees & Taxes", fr = "Intérêt couru", de = Stückzins
				column-name = FEES_TAX
				type = amount
				column-visibility = not-visible
				id = S_186
				column-computation = make-amount
				column-computation-parameters = "FEES_TAXES,ORDER_CURRENCY"
				table-column-width = 3
				tid = 6364156500544064
			{
				--- TableColumnItem ---
					item-column = FEES_TAX
					previewValue = value
			}
			--- TableColumn ---
				column-name = TRANSMISSION_DATE !
				column-type = domain !
				domainAttribute = TRANSMISSION_DATE !
				type = text
				column-visibility = not-visible
				id = DA_92
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = TRANSMISSION_DATE
					format = datetime.date-only
					previewValue = value
			}
			--- TableColumn ---
				column-name = order_id !
				column-type = domain !
				domainAttribute = order_id !
				type = text
				column-is-part-of-filter = false
				column-visibility = never-visible
				id = hk__5
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = order_id
					format = integer
					previewValue = value
			}
			--- TableColumn ---
				column-name = INSTR_CODE !
				column-type = domain !
				domainAttribute = INSTR_CODE !
				type = text
				column-is-part-of-filter = false
				column-visibility = never-visible
				id = YCwe_
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = INSTR_CODE
					previewValue = value
			}
			--- TableColumn ---
				column-name = ORDER_CURRENCY !
				column-type = domain !
				domainAttribute = ORDER_CURRENCY !
				type = text
				column-visibility = never-visible
				id = C2_9_
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = ORDER_CURRENCY
					previewValue = value
			}
			--- TableColumn ---
				column-name = ORDER_NET_AMOUNT !
				column-type = domain !
				domainAttribute = ORDER_NET_AMOUNT !
				type = text
				column-visibility = never-visible
				id = ig81_
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = ORDER_NET_AMOUNT
					format = decimal
					previewValue = value
			}
			--- TableColumn ---
				column-name = ORDER_GROSS_AMOUNT !
				column-type = domain !
				domainAttribute = ORDER_GROSS_AMOUNT !
				type = text
				column-visibility = never-visible
				id = c2f6_
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = ORDER_GROSS_AMOUNT
					format = decimal
					previewValue = value
			}
			--- TableColumn ---
				column-name = ACCRUED_INTEREST !
				column-type = domain !
				domainAttribute = ACCRUED_INTEREST !
				type = text
				column-visibility = never-visible
				id = qMXC_
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = ACCRUED_INTEREST
					format = decimal
					previewValue = value
			}
			--- TableColumn ---
				column-name = FEES_TAXES !
				column-type = domain !
				domainAttribute = FEES_TAXES !
				type = text
				column-visibility = never-visible
				id = DX4fo
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = FEES_TAXES
					format = decimal
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = CREATION_DATE
				sort-direction = descending
				sort-rank = 1
			--- TableSort ---
				sort-column-name = PORTFOLIO_NAME
				sort-rank = 2
			--- TableSort ---
				sort-column-name = INSTR_NAME
				sort-rank = 3
		}
	}
}