# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Cash Detailed Views", de = "Detaillierter Geldfluss", fr = "Liste des cash-flow"
	containment = container
	domainEntity = "AAADSFutureCashFlow:FutureCashFlowDetailedList"
	bean-define = DSBean.AAADSFutureCashFlow.FutureCashFlowDetailedList
	bean-name = FutureCashFlowDetailedList
	id = DetailedListCashFlow_R_P__
	documentation = "This module displays the description of the flows on which the summary is based.\r\n\r\nThe display is only available for short term flows (until 12 months from the From date defined in the context) and it is splitted into the following periods:\r\n\r\n- current month\r\n- next month\r\n- in 2 months\r\n- in 3 months\r\n- in 4 months\r\n- in 5 months\r\n- in 6 months\r\n- in 7 months\r\n- in 8 months\r\n- in 9 months\r\n- in 10 months\r\n- in 11 months\r\n- in 12 months"
	tid = 432254188735160
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			hide-empty-tabs = true
			tabs-filtered-attribute = PERIOD_CLASS_RANK
			id = PERIOD_CLASS_RANK
			indexOfSelectedChild = 0
		{
			--- Tab ---
				labels en = All, fr = Tous, de = Alle
				id = tab_h__5t
				isWidgetSelected = true
				tid = 1658095775980466
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/futurecashflow/detailedlist/detailsbyperiods/DetailedCashFlowAll.module
			}
			--- Tab ---
				labels en = "Start Date", de = Anfangsdatum, fr = "Date de début"
				hide-empty-tab = true
				tab-filter = 0
				id = tab_j0W01
				isWidgetVisible = false
				tid = 1044782024041323
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/futurecashflow/detailedlist/detailsbyperiods/DetailedCashFlowStartDate.module
			}
			--- Tab ---
				labels en = "One Week", fr = "Une semaine", de = "Eine Woche"
				hide-empty-tab = true
				tab-filter = 1
				id = tab_U__F_
				isWidgetVisible = false
				tid = 4946640568843
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/futurecashflow/detailedlist/detailsbyperiods/DetailedCashFlowOneWeek.module
			}
			--- Tab ---
				labels en = "One Month", de = "Ein Monat", fr = "Un mois"
				hide-empty-tab = true
				tab-filter = 2
				id = tab_n8M__
				isWidgetVisible = false
				tid = 1044782066031856
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/futurecashflow/detailedlist/detailsbyperiods/DetailedCashFlowOneMonth.module
			}
			--- Tab ---
				labels en = "Three Months", de = "Drei Monate", fr = "Trois mois"
				hide-empty-tab = true
				tab-filter = 3
				id = tab_cp_02
				isWidgetVisible = false
				tid = 1044782067982383
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/futurecashflow/detailedlist/detailsbyperiods/DetailedCashFlowThreeMonths.module
			}
			--- Tab ---
				labels en = "Six Months", de = "Sechs Monate", fr = "Six mois"
				hide-empty-tab = true
				tab-filter = 4
				id = tab_Q__ni
				isWidgetVisible = false
				tid = 1044782069937380
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/futurecashflow/detailedlist/detailsbyperiods/DetailedCashFlowSixMonths.module
			}
			--- Tab ---
				labels en = "Nine Months", de = "Neun Monate", fr = "Neuf mois"
				hide-empty-tab = true
				tab-filter = 5
				id = tab_l_f5_
				isWidgetVisible = false
				tid = 1044782071890701
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/futurecashflow/detailedlist/detailsbyperiods/DetailedCashFlowNineMonths.module
			}
			--- Tab ---
				labels en = "One Year", de = "Ein Jahr", fr = "Un an"
				hide-empty-tab = true
				tab-filter = 6
				id = tab_v52Ok
				isWidgetVisible = false
				tid = 1044782073843183
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/futurecashflow/detailedlist/detailsbyperiods/DetailedCashFlowOneYear.module
			}
		}
	}
}