# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "List of Orders", fr = "Liste des ordres", de = Auftragsliste
	containment = container
	domainEntity = "AAADSOrderList:OrderListDetailedList"
	bean-define = DSBean.AAADSOrderList.OrderListDetailedList
	bean-name = OrderListDetailedList
	id = AllOrderListDetailedListViewOnly_Su__j
	tid = 6364377005430858
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			hide-empty-tabs = true
			tabs-filtered-attribute = CATEGORY
			id = JO_P5
			indexOfSelectedChild = 3
		{
			--- Tab ---
				labels en = All, fr = Tous, de = Alle
				tab-name = All
				id = tab_d__95
				isWidgetVisible = false
				tid = 6364377008670655
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/orderlist/detailedlist/all/AllDetailedListViewOnly.module
			}
			--- Tab ---
				labels en = "Security, Derivative & Other", fr = "Titre, dérivé et autre", de = "Wertpapiere, Derivate u. Andere"
				hide-empty-tab = true
				tab-filter = SEC
				id = tab_W0_58
				isWidgetVisible = false
				tid = 6364377012987126
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/orderlist/detailedlist/security/SecurityDetailedListViewOnly.module
			}
			--- Tab ---
				labels en = Forex, fr = "Change au comptant", de = Devisenkassa
				hide-empty-tab = true
				tab-filter = FX
				id = tab_v_7jm
				isWidgetVisible = false
				tid = 6364377014175265
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/orderlist/detailedlist/fxSpot/FxSpotDetailedListViewOnly.module
			}
			--- Tab ---
				labels en = "Deposit & Loan", fr = "Dépôt et prêt", de = "Anlage & Kredit"
				hide-empty-tab = true
				tab-filter = MM
				id = tab_iy3oB
				isWidgetSelected = true
				tid = 6364377016131659
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/orderlist/detailedlist/deposit/DepositDetailedListViewOnly.module
			}
		}
	}
}