# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "List of Orders", fr = "Liste des ordres", de = Auftragsliste
	containment = container
	domainEntity = "AAADSOrderList:OrderListDetailedList"
	bean-define = DSBean.AAADSOrderList.OrderListDetailedList
	bean-name = OrderListDetailedList
	id = AllOrderListDetailedList_lK21W
	tid = 4747008731696
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/orderlist/detailedlist/OrderListAllManagementButton.module
		--- TabbedPane ---
			hide-empty-tabs = true
			tabs-filtered-attribute = CATEGORY
			id = CATEGORY
			indexOfSelectedChild = 0
		{
			--- Tab ---
				labels en = All, fr = Tous, de = Alle
				tab-name = All
				id = tab_z2_4j
				isWidgetSelected = true
				tid = 105233651756304
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/orderlist/detailedlist/all/AllDetailedList.module
			}
			--- Tab ---
				labels en = "Security, Derivative & Other", fr = "Titre, dérivé et autre", de = "Wertpapiere, Derivate u. Andere"
				hide-empty-tab = true
				tab-filter = SEC
				id = tab_ghRT_
				isWidgetVisible = false
				tid = 105233652705854
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/orderlist/detailedlist/security/SecurityDetailedList.module
			}
			--- Tab ---
				labels en = Forex, fr = "Change au comptant", de = Devisenkassa
				hide-empty-tab = true
				tab-filter = FX
				id = tab_r_716
				isWidgetVisible = false
				tid = 105233653731112
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/orderlist/detailedlist/fxSpot/FxSpotDetailedList.module
			}
			--- Tab ---
				labels en = "Deposit & Loan", fr = "Dépôt et prêt", de = "Anlage & Kredit"
				hide-empty-tab = true
				tab-filter = MM
				id = tab_Sgc2_
				isWidgetVisible = false
				tid = 105233655089140
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/orderlist/detailedlist/deposit/DepositDetailedList.module
			}
		}
	}
}