# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "List of Orders", fr = "Liste des ordres", de = Auftragsliste
	containment = container
	domainEntity = "AAADSOrderList:OrderListDetailedList"
	bean-define = DSBean.AAADSOrderList.OrderListDetailedList
	bean-name = OrderListDetailedList
	id = CancellableOrderListDetailedList_w_f5n
	tid = 105278069850967
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			hide-empty-tabs = true
			tabs-filtered-attribute = CATEGORY
			id = CATEGORY
			indexOfSelectedChild = 0
		{
			--- Tab ---
				labels en = All, fr = Tous, de = Alle
				id = tab_Q3___
				isWidgetSelected = true
				tid = 105278085845328
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/orderlist/detailedlist/all/AllDetailedListSelectable.module
			}
			--- Tab ---
				labels en = "Security, Derivative & Other", fr = "Titre, dérivé et autre", de = "Wertpapiere, Derivate u. Andere"
				hide-empty-tab = true
				tab-filter = SEC
				id = tab_xM19_
				isWidgetVisible = false
				tid = 105278086516429
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/orderlist/detailedlist/security/SecurityDetailedListSelectable.module
			}
			--- Tab ---
				labels en = Forex, fr = "Change au comptant", de = Devisenkassa
				hide-empty-tab = true
				tab-filter = FX
				id = tab_AsN8_
				isWidgetVisible = false
				tid = 105278087489932
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/orderlist/detailedlist/fxSpot/FxSpotDetailedListSelectable.module
			}
			--- Tab ---
				labels en = "Deposit & Loan", fr = "Dépôt et prêt", de = "Anlage & Kredit"
				hide-empty-tab = true
				tab-filter = MM
				id = tab_s0_4_
				isWidgetVisible = false
				tid = 105278088489098
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/orderlist/detailedlist/deposit/DepositDetailedListSelectable.module
			}
		}
		--- Button ---
			labels en = "Cancel Orders", fr = "Annuler les ordres", de = "Aufträge Streichen"
			id = btn_wW3_9
			tid = 111201609162133
		{
			Event OnClick (submit) S
			// "Execute selected Update Field TA Function"
			{
				method = post
				call-URI = "<pageflow:continuation/>"
				target = self
				flow-action = cancel ud
				modal = false
				only-changed = false
				prevalidate = false
			}
		}
	}
}