# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSExtOperation:ExtOperationAll"
	cssClass = nodeco
	bean-define = DSBean.AAADSExtOperation.ExtOperationAll
	bean-name = ExtOperationAll
	id = OrderManagementButton_y_wT_
{
	--- Box ---
	{
		--- Box ---
			labels en = "Table Edition"
			width = 150
			tid = 969532784489090
		{
			--- Button ---
				labels en = Edit
				enabled = conditional
				enabledIsBasedOn = advanced
				id = btn_A_0Av
				enabledIsBasedOn-advanced = "conditionVal=!<bean:is-true key=\"DSBean.AAADSOrderSession.OrderSessionDetailedList.updateMode\"/>;"
				tid = 969532786029509
			{
				Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = edittable ud
					only-changed = false
					prevalidate = false
					modal = false
				}
			}
			--- Button ---
				labels en = Cancel
				enabled = conditional
				enabledIsBasedOn = advanced
				id = btn_V7_d_
				enabledIsBasedOn-advanced = "conditionVal=<bean:is-true key=\"DSBean.AAADSOrderSession.OrderSessionDetailedList.updateMode\"/>;"
				tid = 969532787981992
			{
				Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = cancelTable ud
					only-changed = false
					prevalidate = false
					modal = false
				}
			}
			--- Button ---
				labels en = Update
				enabled = conditional
				enabledIsBasedOn = advanced
				id = btn_a__02
				enabledIsBasedOn-advanced = "conditionVal=<bean:is-true key=\"DSBean.AAADSOrderSession.OrderSessionDetailedList.updateMode\"/>;"
				tid = 969532789933357
			{
				Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					widget-group-ref = "form*"
					target = self
					flow-action = updatetable ud
					only-changed = false
					prevalidate = false
					modal = false
				}
			}
		}
		--- Box ---
			labels en = "Order Grouping"
			width = 150
			tid = 969532792185319
		{
			--- Button ---
				labels en = "Group Order"
				enabled = conditional
				enabledIsBasedOn = advanced
				id = btn_R_8__
				enabledIsBasedOn-advanced = "conditionVal=!<bean:is-true key=\"DSBean.AAADSOrderSession.OrderSessionDetailedList.updateMode\"/>;"
				tid = 969532793896431
			{
				Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = groupOrder ud
					only-changed = false
					prevalidate = false
					modal = false
				}
			}
			--- Button ---
				labels en = "Detach Order"
				enabled = conditional
				enabledIsBasedOn = advanced
				id = btn_qK__x
				enabledIsBasedOn-advanced = "conditionVal=!<bean:is-true key=\"DSBean.AAADSOrderSession.OrderSessionDetailedList.updateMode\"/>;"
				tid = 969532795819859
			{
				Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = detachOrder ud
					only-changed = false
					prevalidate = false
					modal = false
				}
			}
		}
	}
}