# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSExtOperation:ExtOperationAll"
	cssClass = nodeco
	bean-define = DSBean.AAADSExtOperation.ExtOperationAll
	bean-name = ExtOperationAll
	id = OrderListAllManagementButton_r_m8D
{
	--- Box ---
	{
		--- Box ---
			labels en = "Order Grouping"
			width = 150
			tid = 978481727558111
		{
			--- Button ---
				labels en = "Group Order"
				enabled = conditional
				enabledIsBasedOn = advanced
				id = btn_mEN__
				enabledIsBasedOn-advanced = "conditionVal=!<bean:is-true key=\"DSBean.AAADSOrderSession.OrderSessionDetailedList.updateMode\"/>;"
				tid = 978481729508638
			{
				Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = orderGrouping ud
					only-changed = false
					prevalidate = false
					modal = false
				}
			}
			--- Button ---
				labels en = "Detach Order"
				enabled = conditional
				enabledIsBasedOn = advanced
				id = btn_hx8_4
				enabledIsBasedOn-advanced = "conditionVal=!<bean:is-true key=\"DSBean.AAADSOrderSession.OrderSessionDetailedList.updateMode\"/>;"
				tid = 978481731461959
			{
				Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = orderDetach ud
					only-changed = false
					prevalidate = false
					modal = false
				}
			}
		}
	}
}