# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "List of Orders", fr = "Liste des ordres", de = Auftragsliste
	containment = container
	domainEntity = "AAADSOrderList:OrderListDetailedList"
	bean-define = DSBean.AAADSOrderList.OrderListDetailedList
	bean-name = OrderListDetailedList
	id = ToValidateOrderListDetailedList_rf_3X
	tid = 105290940831044
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			hide-empty-tabs = true
			tabs-filtered-attribute = CATEGORY
			id = CATEGORY
			indexOfSelectedChild = 0
		{
			--- Tab ---
				labels en = All, fr = Tous, de = Alle
				id = tab_v__M_
				isWidgetSelected = true
				tid = 105290945633544
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/orderlist/detailedlist/all/AllDetailedListSelectable.module
			}
			--- Tab ---
				labels en = "Security, Derivative & Other", fr = "Titre, dérivé et autre", de = "Wertpapiere, Derivate u. Andere"
				hide-empty-tab = true
				tab-filter = SEC
				id = tab_T4_6_
				isWidgetVisible = false
				tid = 105290946590793
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/orderlist/detailedlist/security/SecurityDetailedListSelectable.module
			}
			--- Tab ---
				labels en = Forex, fr = "Change au comptant", de = Devisenkassa
				hide-empty-tab = true
				tab-filter = FX
				id = tab_te77m
				isWidgetVisible = false
				tid = 105290947586538
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/orderlist/detailedlist/fxSpot/FxSpotDetailedListSelectable.module
			}
			--- Tab ---
				labels en = "Deposit & Loan", fr = "Dépôt et prêt", de = "Anlage & Kredit"
				hide-empty-tab = true
				tab-filter = MM
				id = tab_A8___
				isWidgetVisible = false
				tid = 105290948588698
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/orderlist/detailedlist/deposit/DepositDetailedListSelectable.module
			}
		}
		--- Box ---
		{
			--- Button ---
				labels en = "Validate Orders", fr = "Valider les ordres", de = "Aufträge bestäligen"
				id = btn_z_x0_
				tid = 111219048768814
			{
				Event OnClick (submit) S
				// "Execute selected Update Field TA Function"
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = validate ud
					modal = false
					only-changed = false
					prevalidate = false
				}
			}
			--- Button ---
				labels en = "Reject Orders", fr = "Rejeter les ordres", de = "Aufträge ablehnen"
				id = btn_r_58X
				tid = 111243696026731
			{
				Event OnClick (submit) S
				// "Execute selected Update Field TA Function"
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = reject ud
					modal = false
					only-changed = false
					prevalidate = false
				}
			}
			--- Glue ---
		}
	}
}