# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	containment = container
	search = container !
	cssClass = nodeco
	id = ClientQueryResultsNoActivities_P13_1
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/queries/ClientQueryInput.module
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/thirdparty/search/ThirdPartyListNoActivities.module
	}
}