# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Query Criteria", fr = "Critères de recherche", de = "Schnellsuche Suchbegriffe"
	containment = container
	domainEntity = "AAADSThirdParty:ThirdPartySearchCriteria"
	search = input !
	bean-define = DSBean.AAADSThirdParty.ThirdPartySearchCriteria
	bean-name = ThirdPartySearchCriteria
	id = ClientQueryInput_p9_7_
	tid = 184543051426647
{
	--- Box ---
		boxType = vertical
	{
		--- Box ---
		{
			--- FilterCriteria ---
				includedFile = "resource:/com/module/search/QueryBuilder.xsp"
		}
		--- Include ---
			includeSrc = "" !
			resource:///default/search/NavigationSearch.fragment
	}
}