# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	containment = container
	search = container !
	cssClass = nodeco
	id = PortfolioQueryValuation_a49__
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/queries/PortfolioQueryInput.module
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/portfolio/search/PortfolioListMultipleValuation.module
	}
}