# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Query Definition", fr = "Définition de la recherche", de = "Bestimmung der Schnellsuche"
	domainEntity = "AAADSList:ListAll"
	bean-define = DSBean.AAADSList.ListAll
	bean-name = ListAll
	id = ListIdentifierView_nx731
	documentation = "Presents the pre-defined query denomination and possibel navigation from the query results.\r\n\r\nThe Use in context button is available only for portfolios.\r\nMultiple portoflios can be selected and used in context.\r\nThis is the only entity supporting multiple selection to be pushed in domain.\r\nClient can be selected one by one.\r\nClient selection is made from the output table. \r\n\r\ncondition for displying button is based on property OutputModule, of the query definition. The query definition is stored in the Triple\'A list entity."
	tid = 2252870276250
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///default/queries/QueryDefinitionHeader.fragment
	}
}