# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Pre-Defined Queries", fr = "Recherches prédéfinies", de = "Vorher bestimmte Schnellsuchen"
	containment = container
	domainEntity = "AAADSDomain:DomainContext"
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = PreferredQueries_H_85W
	tid = 179506853295321
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			id = J8rC_
			indexOfSelectedChild = 2
		{
			--- Tab ---
				labels en = Portfolios, de = Portfolios, fr = Portefeuilles
				id = querytab_portfolio
				isWidgetVisible = false
				tid = 179506855556222
			{
				Event OnClick (setTabActive) Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = changeTab ud
					modal = false
					only-changed = false
					prevalidate = false
					Snippet FilterSet
					id = fs_830
					level = 1
					targetDataset = "AAADSList:ListPreDefQuery"
					{
						Snippet Filter
						attribute = natureE
						filterValue = Query
						operator = EQUAL
						Snippet Filter
						attribute = entityDict
						filterValue = 800
						operator = EQUAL
						Snippet Filter
						attribute = typeCode
						filterValue = PCK_DS_PORTFOLIO
						operator = EQUAL
					}
				}
				--- Box ---
					boxType = vertical
				{
					--- Include ---
						includeSrc = "" !
						resource:///default/queries/QueryHeaderManagerChoice.fragment
					--- Conditional ---
						indexOfSelectedChild = 0
					{
						--- ConditionalBody ---
							javaCode = "<nav:is-selected  group-id=\"queriesapplyto\" element-id=\"queriesapplyto_all\" default-selected=\"true\" />"
							technicalName = All
							boxType = vertical
							isWidgetSelected = true
						{
							--- Include ---
								includeSrc = "" !
								resource:///Default/module/aaa/administration/list/queries/ListOfPredefinedPortfolioQueriesAll.module
						}
						--- ConditionalBody ---
							javaCode = "<nav:is-selected  group-id=\"queriesapplyto\" element-id=\"queriesapplyto_me\"/>"
							technicalName = Me
							boxType = vertical
							isWidgetVisible = false
						{
							--- Include ---
								includeSrc = "" !
								resource:///Default/module/aaa/administration/list/queries/ListOfPredefinedPortfolioQueriesMe.module
						}
						--- ConditionalBody ---
							javaCode = "<nav:is-selected  group-id=\"queriesapplyto\" element-id=\"queriesapplyto_manager\"/>"
							technicalName = Manager
							boxType = vertical
							isWidgetVisible = false
						{
							--- Include ---
								includeSrc = "" !
								resource:///Default/module/aaa/administration/list/queries/ListOfPredefinedPortfolioQueriesManager.module
						}
					}
				}
			}
			--- Tab ---
				labels en = Clients, de = Kunden, fr = Clients
				id = querytab_client
				isWidgetVisible = false
				tid = 179506855928337
			{
				Event OnClick (setTabActive) Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = changeTab ud
					entity = portfolio ud
					modal = false
					only-changed = false
					prevalidate = false
					Snippet FilterSet
					id = fs_830
					level = 1
					targetDataset = "AAADSList:ListPreDefQuery"
					{
						Snippet Filter
						attribute = natureE
						filterValue = Query
						operator = EQUAL
						Snippet Filter
						attribute = entityDict
						filterValue = 600
						operator = EQUAL
						Snippet Filter
						attribute = typeCode
						filterValue = PCK_DS_CLIENT
						operator = EQUAL
					}
				}
				--- Box ---
					boxType = vertical
				{
					--- Include ---
						includeSrc = "" !
						resource:///default/queries/QueryHeaderManagerChoice.fragment
					--- Conditional ---
						indexOfSelectedChild = 2
					{
						--- ConditionalBody ---
							javaCode = "<nav:is-selected  group-id=\"queriesapplyto\" element-id=\"queriesapplyto_all\" default-selected=\"true\" />"
							technicalName = All
							boxType = vertical
							isWidgetVisible = false
						{
							--- Include ---
								includeSrc = "" !
								resource:///Default/module/aaa/administration/list/queries/ListOfPredefinedClientQueriesAll.module
						}
						--- ConditionalBody ---
							javaCode = "<nav:is-selected  group-id=\"queriesapplyto\" element-id=\"queriesapplyto_me\"/>"
							technicalName = Me
							boxType = vertical
							isWidgetVisible = false
						{
							--- Include ---
								includeSrc = "" !
								resource:///Default/module/aaa/administration/list/queries/ListOfPredefinedClientQueriesMe.module
						}
						--- ConditionalBody ---
							javaCode = "<nav:is-selected  group-id=\"queriesapplyto\" element-id=\"queriesapplyto_manager\"/>"
							technicalName = Manager
							boxType = vertical
							isWidgetSelected = true
						{
							--- Include ---
								includeSrc = "" !
								resource:///Default/module/aaa/administration/list/queries/ListOfPredefinedClientQueriesManager.module
						}
					}
				}
			}
			--- Tab ---
				labels en = Prospects, de = Prospekte, fr = Prospects
				enabled = false
				id = querytab_prospect
				isWidgetSelected = true
				tid = 179506856215245
			{
				Event OnClick (setTabActive) Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = changeTab ud
					modal = false
					only-changed = false
					prevalidate = false
					Snippet FilterSet
					id = fs_830
					level = 1
					targetDataset = "AAADSList:ListPreDefQuery"
					{
						Snippet Filter
						attribute = natureE
						filterValue = Query
						operator = EQUAL
						Snippet Filter
						attribute = entityDict
						filterValue = 600
						operator = EQUAL
						Snippet Filter
						attribute = typeCode
						filterValue = PCK_DS_PROSPECT
						operator = EQUAL
					}
				}
			}
		}
	}
}