# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Pre-Defined Query", fr = "Recherche prédéfinie", de = "Vordefinierte Schnellabfragen"
	containment = container
	domainEntity = "AAADSPortfolio:PortfolioList"
	cssClass = nodeco
	bean-define = DSBean.AAADSPortfolio.PortfolioList
	bean-name = PortfolioList
	id = PortfolioPreDefinedQuery_S_3x2
	documentation = "Presents the pre-defined query results.\r\nThe output is one of the properties, called OutputModule, of the query definition. The query definition is stored in the Triple\'A list entity.\r\n\r\nThe first level of conditions is based on OutputModule preffix.\r\nThe second  level of condition is based on OutputModule suffix."
	tid = 99914790286195
{
	--- Box ---
		boxType = vertical
	{
		--- Conditional ---
			technicalName = "Based on query (in Triple\'A DB) property OutputModule preffix"
			indexOfSelectedChild = 0
		{
			--- ConditionalBody ---
				javaCode = "((String)<bean:value-of key=\"aaa-search.outputModule\"/>).toLowerCase().startsWith(\"portfolio\")"
				technicalName = Portfolio
				boxType = vertical
				isWidgetSelected = true
			{
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "((String)<bean:value-of key=\"aaa-search.outputModule\"/>).toLowerCase().endsWith(\"valuation\")"
						technicalName = Valuation
						boxType = vertical
						isWidgetSelected = true
					{
						--- Include ---
							includeSrc = "" !
							resource:///Default/module/aaa/administration/queries/PortfolioQueryResultsValuation.module
					}
					--- ConditionalBody ---
						javaCode = "((String)<bean:value-of key=\"aaa-search.outputModule\"/>).toLowerCase().endsWith(\"return\")"
						technicalName = Return
						boxType = vertical
						isWidgetVisible = false
					{
						--- Include ---
							includeSrc = "" !
							resource:///Default/module/aaa/administration/queries/PortfolioQueryResultsReturn.module
					}
					--- ConditionalBody ---
						javaCode = "((String)<bean:value-of key=\"aaa-search.outputModule\"/>).toLowerCase().endsWith(\"compliance\")"
						technicalName = Compliance
						boxType = vertical
						isWidgetVisible = false
					{
						--- Include ---
							includeSrc = "" !
							resource:///Default/module/aaa/administration/queries/PortfolioQueryResultsCompliance.module
					}
					--- ConditionalBody ---
						javaCode = "((String)<bean:value-of key=\"aaa-search.outputModule\"/>).toLowerCase().endsWith(\"crm\")"
						technicalName = CRM
						boxType = vertical
						isWidgetVisible = false
					{
						--- Include ---
							includeSrc = "" !
							resource:///Default/module/aaa/administration/queries/PortfolioQueryResultsCRM.module
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetVisible = false
					{
						--- Include ---
							includeSrc = "" !
							resource:///Default/module/aaa/administration/queries/PortfolioQueryResultsDefault.module
					}
				}
			}
			--- ConditionalBody ---
				javaCode = "((String)<bean:value-of key=\"aaa-search.outputModule\"/>).toLowerCase().startsWith(\"client\")"
				technicalName = Client
				boxType = vertical
				isWidgetVisible = false
			{
				--- Conditional ---
					technicalName = "Based on query (in Triple\'A DB) property OutputModule suffix"
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "((String)<bean:value-of key=\"aaa-search.outputModule\"/>).toLowerCase().endsWith(\"uncontacted\")"
						technicalName = Uncontacted
						boxType = vertical
						isWidgetSelected = true
					{
						--- Include ---
							includeSrc = "" !
							resource:///Default/module/aaa/administration/queries/ClientQueryResultsUncontacted.module
					}
					--- ConditionalBody ---
						javaCode = "((String)<bean:value-of key=\"aaa-search.outputModule\"/>).toLowerCase().endsWith(\"noactivities\")"
						technicalName = "No Activities"
						boxType = vertical
						isWidgetVisible = false
					{
						--- Include ---
							includeSrc = "" !
							resource:///Default/module/aaa/administration/queries/ClientQueryResultsNoActivities.module
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetVisible = false
					{
						--- Include ---
							includeSrc = "" !
							resource:///Default/module/aaa/administration/queries/ClientQueryResultsDefault.module
					}
				}
			}
			--- ConditionalBody ---
				javaCode = "((String)<bean:value-of key=\"aaa-search.outputModule\"/>).toLowerCase().startsWith(\"prospect\")"
				technicalName = Prospect
				boxType = vertical
				isWidgetVisible = false
		}
	}
}