# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Grid Search Criteria", fr = "Critères de recherche sur grille", de = "Raster Suchbegriffe"
	containment = container
	domainEntity = "AAADSGrid:GridSearchCriteria"
	search = input !
	bean-define = DSBean.AAADSGrid.GridSearchCriteria
	bean-name = GridSearchCriteria
	id = GridSearchInput_o5f7_
	tid = 113551660676510
{
	--- Box ---
		boxType = vertical
	{
		--- FilterCriteria ---
			includedFile = "resource:/com/module/search/QueryBuilder.xsp"
		--- Include ---
			includeSrc = "" !
			resource:///default/search/NavigationSearch.fragment
	}
}