# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Search Grid", fr = "Recherche de grille", de = "Raster Suche"
	containment = container
	search = container !
	cssClass = nodeco
	id = GridSearch_szyg3
	tid = 113220898030613
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/grid/search/GridSearchInput.module
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/grid/search/GridList.module
	}
}