/*
* generated by Xtext
*/
package com.odcgroup.service.model.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ComponentProposalProvider extends AbstractComponentProposalProvider {

}
