# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Strategy Link Update", fr = "Mise à jour du lien de stratégie", de = "Strategieverknüpfung Aktualisierung"
	containment = container
	domainEntity = "AAADSStrategyLink:StrategyLinkDetails"
	bean-define = DSBean.AAADSStrategyLink.StrategyLinkDetails
	bean-name = StrategyLinkDetails
	id = StrategyLinkUpdate_Q9_3E
	tid = 100342170386372
{
	--- Box ---
		boxType = vertical
	{
		--- Box ---
			labels en = Definition, fr = Définition, de = Bestimmung
			tid = 100342172339746
		{
			--- Include ---
				includeSrc = "" !
				resource:///Default/module/aaa/administration/strategylink/StrategyLinkDefinition.module
		}
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/strategylink/AssociatedStrategyDetails.module
		--- Include ---
			includeSrc = "" !
			resource:///default/portfolio/administration/ButtonUpdateStrategyLink.fragment
	}
}