# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSPortfolioThirdChrono:PortfolioThirdCompoList"
	cssClass = nodeco
	bean-define = DSBean.AAADSPortfolioThirdChrono.PortfolioThirdCompoList
	bean-name = PortfolioThirdCompoList
	id = PortfolioThirdCompoList_p4_z_
{
	--- Box ---
		labels en = "Portfolio Ownership", fr = "Portefeuille contrôlés", de = "Zugehörige Portfolios"
		boxType = vertical
		widgetBorder = box
		width = 0
		tid = 262006126256186
	{
		--- TableTree ---
			id = e__n4
			table-column-count = 5 !
			table-columns-width = "20,20,20,20,20" !
		{
			--- TableColumn ---
				column-name = portfolioName !
				column-type = domain !
				domainAttribute = portfolioName !
				type = text
				column-locked = true
				id = portfolioName
				table-column-width = 20
			{
				--- TableColumnItem ---
					item-column = portfolioName
					previewValue = value
			}
			--- TableColumn ---
				column-name = validityD !
				column-type = domain !
				domainAttribute = validityD !
				id = validityD
				table-column-width = 20
			{
				--- TableColumnItem ---
					item-column = validityD
					format = datetime.date-only
					previewValue = value
			}
			--- TableColumn ---
				column-name = portfolioThirdName !
				column-type = domain !
				domainAttribute = portfolioThirdName !
				type = text
				id = portfolioThirdName
				table-column-width = 20
			{
				--- TableColumnItem ---
					item-column = portfolioThirdName
					previewValue = value
			}
			--- TableColumn ---
				column-name = ownershipRuleE !
				column-type = domain !
				domainAttribute = ownershipRuleE !
				id = ownershipRuleE
				table-column-width = 20
			{
				--- TableColumnItem ---
					item-column = ownershipRuleE
					previewValue = value
			}
			--- TableColumn ---
				column-name = weightN !
				column-type = domain !
				domainAttribute = weightN !
				id = weightN
				table-column-width = 20
			{
				--- TableColumnItem ---
					item-column = weightN
					format = decimal.detailed
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = validityD
				sort-rank = 3
			--- TableSort ---
				sort-column-name = portfolioName
				sort-rank = 2
			--- TableSort ---
				sort-column-name = portfolioThirdName
				sort-rank = 4
		}
	}
}