# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "List Of Allocation Rules", fr = "Liste des règles d\'allocation", de = "Liste der Verteilungs-Regeln"
	domainEntity = "AAADSExtStrategyElement:ExtStrategyElementDomainList"
	bean-define = DSBean.AAADSExtStrategyElement.ExtStrategyElementDomainList
	bean-name = ExtStrategyElementDomainList
	id = MktSegResultOfPtf_Q_V_5
	tid = 83366728505869
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			id = AK__8
			table-column-count = 16 !
			table-columns-width = "6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6" !
		{
			--- TableColumn ---
				column-name = UPDATE
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				column-width = 2%
				id = tD_6_
				table-column-width = 6
			{
				--- Icon ---
					toolTips en = "Update Instruction", de = "Instruktion aktualisieren", fr = "Mettre à jour les instructions"
					horizontalAlignment = center
					icon = application_form_edit
					id = Q0L_0
					tid = 71619413571156
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = edit-instruction ud
						id = "<udp:item column=\"id\"/>" ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- TableColumn ---
				column-name = DELETE
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				column-width = 2%
				id = Cp4__
				table-column-width = 6
			{
				--- Icon ---
					toolTips en = "Delete Instruction", de = "Instruktion löschen", fr = "Supprimer l\'Instruction"
					horizontalAlignment = center
					icon = application_form_delete
					id = A55_v
					tid = 71619429136214
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = edit-instruction ud
						id = "<udp:item column=\"id\"/>" ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- TableColumn ---
				column-name = instrCode !
				column-type = domain !
				domainAttribute = instrCode !
				type = text
				id = instrCode
				table-column-width = 6
			{
				--- Icon ---
					toolTips en = "View Instrument Details", de = "Details des Instruments ansehen", fr = "Voir les détails de l\'instrument"
					icon = application_form_magnify
					id = jL8__
					tid = 1228240976795990
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "resource:///administration/instrument/InstrumentQuickView.pageflow"
						target = popup
						code = "<udp:item column=\"instrCode\"/>" ud
						only-changed = false
						prevalidate = false
						modal = false
					}
				}
				--- Spacer ---
					height = 4
					width = 10
				--- TableColumnItem ---
					item-column = instrCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = recomNatE !
				column-type = domain !
				domainAttribute = recomNatE !
				type = text
				id = recomNatE
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = recomNatE
					previewValue = value
			}
			--- TableColumn ---
				column-name = objWeightN !
				column-type = domain !
				domainAttribute = objWeightN !
				format = decimal.detailed
				type = text
				id = objWeightN
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = objWeightN
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Last Quote", fr = "Cours courant", de = "Aktueller Kurs"
				column-name = Last_Quote
				type = amount
				id = JF_91
				column-computation = make-amount
				column-computation-parameters = "currentQuoteN,currQuoteCurrCode"
				table-column-width = 6
				tid = 83257391661594
			{
				--- TableColumnItem ---
					item-column = Last_Quote
					previewValue = value
			}
			--- TableColumn ---
				column-name = actualOrderNatE !
				column-type = domain !
				domainAttribute = actualOrderNatE !
				type = text
				id = actualOrderNatE
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = actualOrderNatE
					previewValue = value
			}
			--- TableColumn ---
				labels en = Limit, fr = Limite, de = Limit-Kurs
				column-name = Limit_Quote
				type = amount
				id = KH_6_
				column-computation = make-amount
				column-computation-parameters = "orderQuoteN,orderQuoteCurrCode"
				table-column-width = 6
				tid = 83276422154821
			{
				--- TableColumnItem ---
					item-column = Limit_Quote
					previewValue = value
			}
			--- TableColumn ---
				labels en = Stop, fr = Stop, de = Stop-Kurs
				column-name = Stop_Quote
				type = amount
				id = w_m__
				column-computation = make-amount
				column-computation-parameters = "stopQuoteN,orderQuoteCurrCode"
				table-column-width = 6
				tid = 83286717825477
			{
				--- TableColumnItem ---
					item-column = Stop_Quote
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Limit Date"
				column-name = orderLimitD !
				column-type = domain !
				domainAttribute = orderLimitD !
				type = text
				id = orderLimitD
				table-column-width = 6
				tid = 71619447794180
			{
				--- TableColumnItem ---
					item-column = orderLimitD
					format = date
					previewValue = value
			}
			--- TableColumn ---
				column-name = id !
				column-type = domain !
				domainAttribute = id !
				type = text
				column-visibility = never-visible
				id = id
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = id
					format = integer
					previewValue = value
			}
			--- TableColumn ---
				column-name = currentQuoteN !
				column-type = domain !
				domainAttribute = currentQuoteN !
				format = decimal.detailed
				type = text
				column-visibility = never-visible
				id = currentQuoteN
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = currentQuoteN
					previewValue = value
			}
			--- TableColumn ---
				column-name = currQuoteCurrCode !
				column-type = domain !
				domainAttribute = currQuoteCurrCode !
				type = text
				column-visibility = never-visible
				id = currQuoteCurrCode
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = currQuoteCurrCode
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Limit Price"
				column-name = orderQuoteN !
				column-type = domain !
				domainAttribute = orderQuoteN !
				type = text
				column-visibility = never-visible
				id = orderQuoteN
				table-column-width = 6
				tid = 71619430193132
			{
				--- TableColumnItem ---
					item-column = orderQuoteN
					format = decimal.detailed
					previewValue = value
			}
			--- TableColumn ---
				column-name = orderQuoteCurrCode !
				column-type = domain !
				domainAttribute = orderQuoteCurrCode !
				type = text
				column-visibility = never-visible
				id = orderQuoteCurrCode
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = orderQuoteCurrCode
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Stop Price"
				column-name = stopQuoteN !
				column-type = domain !
				domainAttribute = stopQuoteN !
				type = text
				column-visibility = never-visible
				id = stopQuoteN
				table-column-width = 6
				tid = 71619446815964
			{
				--- TableColumnItem ---
					item-column = stopQuoteN
					format = decimal.detailed
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = id
				sort-direction = descending
				sort-rank = 1
		}
	}
}