# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Allocation Rule Definition", fr = "Définition des règles d\'allocation", de = "Definition Verteilungsregel "
	domainEntity = "AAADSExtStrategyElement:ExtStrategyElementDomainAll"
	bean-define = DSBean.AAADSExtStrategyElement.ExtStrategyElementDomainAll
	bean-name = ExtStrategyElementDomainAll
	id = MktSegResultPercentOfPtfCreate_E1__p
	tid = 2406809926583627
{
	--- Box ---
		boxType = vertical
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 4
			gridColumnsWidth = "25,25,25,25" !
			gridRowCount = 5
		{
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- LabelDomain ---
					domainAttribute = instr !
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Include ---
					domainAssociation = instr
					includeSrc = "" !
					resource:///default/extoperation/basicelements/SecurityInstrumentEdit.fragment
					bean-property-prefix = instr.
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- LabelDomain ---
					labels en = "Instrument Denomination", de = "Beschreibung des Instruments", fr = "Dénomination de l\'instrument"
					domainAttribute = instr !
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					tid = 2406809927578949
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Include ---
					domainAssociation = instr
					includeSrc = "" !
					resource:///default/defaultFragments/InstrumentIdentifierDenomIconView.fragment
					bean-property-prefix = instr.
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- LabelDomain ---
					domainAttribute = recomNatE !
					for = recomNatE
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					required = true
					id = recomNatE
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- ComboBox ---
					domainAttribute = recomNatE !
					horizontalAlignment = "${corporatehalign}"
					required = true
					bean-property = recomNatE
					id = recomNatE
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- LabelDomain ---
					labels en = "Last Quote", fr = "Dernier Cours", de = "Aktueller Kurs"
					domainAttribute = currentQuoteN !
					for = currentQuoteN
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					tid = 2406809929484901
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "(<bean:get-property bean=\"ExtStrategyElementDomainAll\" property=\"currentQuoteN\"/> != null &amp;&amp; <bean:get-property bean=\"ExtStrategyElementDomainAll\" property=\"currQuoteCurr\"/> != null)"
						technicalName = currency
						isWidgetSelected = true
					{
						--- TextField ---
							domainAttribute = currentQuoteN !
							columns = 21
							format = decimal.detailed
							horizontalAlignment = "${corporatehalign}"
							type = decimal
							chars = 23
							editable = false
							bean-property = currentQuoteN
							id = currentQuoteN
						--- Include ---
							domainAssociation = currQuoteCurr
							includeSrc = "" !
							resource:///default/defaultFragments/CurrencyIdentifierView.fragment
							bean-property-prefix = currQuoteCurr.
						--- Glue ---
					}
					--- ConditionalBody ---
						javaCode = "(<bean:get-property bean=\"ExtStrategyElementDomainAll\" property=\"currentQuoteN\"/> != null &amp;&amp; <bean:get-property bean=\"ExtStrategyElementDomainAll\" property=\"currQuoteCurr\"/> == null)"
						technicalName = %
						isWidgetVisible = false
					{
						--- TextField ---
							domainAttribute = currentQuoteN !
							columns = 21
							format = decimal.detailed
							horizontalAlignment = "${corporatehalign}"
							type = decimal
							chars = 23
							editable = false
							bean-property = currentQuoteN
							id = currentQuoteN
						--- Label ---
							labels en = %, fr = %, de = %
							tid = 2406809929590977
					}
				}
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- LabelDomain ---
					domainAttribute = objWeightN !
					for = objWeightN
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					id = objWeightN
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- TextField ---
					domainAttribute = objWeightN !
					columns = 22
					format = decimal.detailed
					horizontalAlignment = "${corporatehalign}"
					type = decimal
					chars = 22
					bean-property = objWeightN
					id = objWeightN
			}
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- LabelDomain ---
					labels en = "Order Type", de = Auftragsart, fr = "Nature de l\'ordre"
					domainAttribute = actualOrderNatE !
					for = actualOrderNatE
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					required = true
					tid = 2406809930582449
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- ComboBox ---
					domainAttribute = actualOrderNatE !
					horizontalAlignment = "${corporatehalign}"
					required = true
					bean-property = actualOrderNatE
					id = actualOrderNatE
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- LabelDomain ---
					labels en = Limit, de = Limit-Kurs, fr = Limite
					domainAttribute = orderQuoteN !
					for = orderQuoteN
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					tid = 2406809931626531
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- TextField ---
					domainAttribute = orderQuoteN !
					columns = 21
					format = decimal.detailed
					horizontalAlignment = "${corporatehalign}"
					type = decimal
					allow = "\'1234567890,.\'"
					chars = 23
					bean-property = orderQuoteN
					id = orderQuoteN
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- LabelDomain ---
					labels en = Validity, de = Limit-Datum, fr = "Date de validité"
					domainAttribute = orderLimitD !
					for = orderLimitD
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					tid = 2406809932583356
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- CaldateField ---
					domainAttribute = orderLimitD !
					format = date
					horizontalAlignment = "${corporatehalign}"
					type = date
					bean-property = orderLimitD
					id = orderLimitD
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- LabelDomain ---
					labels en = Stop, de = Stop-Kurs
					domainAttribute = stopQuoteN !
					for = stopQuoteN
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					tid = 2406809933597497
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- TextField ---
					domainAttribute = stopQuoteN !
					columns = 21
					format = decimal.detailed
					horizontalAlignment = "${corporatehalign}"
					type = decimal
					allow = "\'1234567890,.\'"
					chars = 23
					bean-property = stopQuoteN
					id = stopQuoteN
			}
		}
		--- Include ---
			includeSrc = "" !
			resource:///default/extstrategyelement/orderallocation/CreateUpdateButton.fragment
	}
}