# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSOrderList:OrderListDetailedList"
	cssClass = nodeco
	bean-define = DSBean.AAADSOrderList.OrderListDetailedList
	bean-name = OrderListDetailedList
	id = AllDetailedListSelectable_i_3F_
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			id = Gn1_s
			table-column-count = 10 !
			table-columns-width = "10,10,10,10,10,10,10,10,10,10" !
		{
			--- TableColumn ---
				column-name = SELECT
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				id = Qz2GH
				table-column-width = 10
			{
				--- CheckBox ---
					column-checkbox-identifier = ORDER_CODE
					horizontalTextPosition = trail
					id = btn_R8g_7
			}
			--- TableColumn ---
				column-name = ORDER_CODE !
				column-type = domain !
				domainAttribute = ORDER_CODE !
				type = text
				id = Y_1_t
				table-column-width = 10
			{
				--- TableColumnItem ---
					item-column = ORDER_CODE
					previewValue = value
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = view ud
						code = "<udp:item column=\"ORDER_CODE\"/>" ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- TableColumn ---
				column-name = CREATION_DATE !
				column-type = domain !
				domainAttribute = CREATION_DATE !
				type = text
				id = CREATION_DATE
				table-column-width = 10
			{
				--- TableColumnItem ---
					item-column = CREATION_DATE
					format = datetime.date-only
					previewValue = value
			}
			--- TableColumn ---
				column-name = ORDER_DATE !
				column-type = domain !
				domainAttribute = ORDER_DATE !
				type = text
				id = u39__
				table-column-width = 10
			{
				--- TableColumnItem ---
					item-column = ORDER_DATE
					format = datetime.date-only
					previewValue = value
			}
			--- TableColumn ---
				column-name = PORTFOLIO_NAME !
				column-type = domain !
				domainAttribute = PORTFOLIO_NAME !
				type = text
				id = n_PAZ
				table-column-width = 10
			{
				--- TableColumnItem ---
					item-column = PORTFOLIO_NAME
					previewValue = value
			}
			--- TableColumn ---
				labels en = Category
				column-name = CATEGORY_LABEL !
				column-type = domain !
				domainAttribute = CATEGORY_LABEL !
				type = text
				id = CATEGORY_LABEL
				table-column-width = 10
				tid = 959265148196117
			{
				--- TableColumnItem ---
					item-column = CATEGORY_LABEL
					previewValue = value
			}
			--- TableColumn ---
				column-name = ORDER_SUMMARY !
				column-type = domain !
				domainAttribute = ORDER_SUMMARY !
				type = text
				id = ORDER_SUMMARY
				table-column-width = 10
			{
				--- TableColumnItem ---
					item-column = ORDER_SUMMARY
					previewValue = value
			}
			--- TableColumn ---
				column-name = VALUE_DATE !
				column-type = domain !
				domainAttribute = VALUE_DATE !
				type = text
				id = w1_F1
				table-column-width = 10
			{
				--- TableColumnItem ---
					item-column = VALUE_DATE
					format = date
					previewValue = value
			}
			--- TableColumn ---
				column-name = STATUS !
				column-type = domain !
				domainAttribute = STATUS !
				type = text
				id = Pt379
				table-column-width = 10
			{
				--- TableColumnItem ---
					item-column = STATUS
					previewValue = value
			}
			--- TableColumn ---
				column-name = order_id !
				column-type = domain !
				domainAttribute = order_id !
				type = text
				column-is-part-of-filter = false
				column-visibility = never-visible
				id = y_t7_
				table-column-width = 10
			{
				--- TableColumnItem ---
					item-column = order_id
					format = integer
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = PORTFOLIO_NAME
				sort-rank = 3
			--- TableExtra ---
				domainAttribute = status_id
			--- TableSort ---
				sort-column-name = CREATION_DATE
				sort-direction = descending
				sort-rank = 2
			--- TableSort ---
				sort-column-name = CATEGORY_LABEL
				sort-rank = 4
		}
	}
}