# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSOrderList:OrderListDetailedList"
	cssClass = nodeco
	bean-define = DSBean.AAADSOrderList.OrderListDetailedList
	bean-name = OrderListDetailedList
	id = AllDetailedList_l_f32
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			display-checkbox = true
			table-filter-layer = true
			id = Y_nN1
			table-column-count = 15 !
			table-columns-width = "6,6,6,6,6,6,6,6,6,6,6,6,6,6,6" !
			table-filterset-id = fs_yw3
		{
			--- TableColumn ---
				labels en = Validate, fr = Valider, de = Bestätigen
				column-name = Validate
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				id = h43_u
				table-column-width = 6
				tid = 105870686363988
			{
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "\"true\".equals(<udp:item column=\"ACTION_RIGHT_VALIDATE\"/>.toString())"
						technicalName = Condition
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips en = "Validate Order", fr = "Valider l\'ordre", de = Bestätigen
							horizontalAlignment = center
							icon = tick
							id = V_6_8
							tid = 16110303047282
						{
							Event OnClick (submit) S
							// "Execute selected Update Field TA Function"
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = validate ud
								modal = false
								only-changed = false
								prevalidate = false
								DSEntityCode = "<udp:item column=\"ORDER_CODE\"/>" ud
							}
						}
					}
				}
			}
			--- TableColumn ---
				labels en = Reject, fr = Rejeter, de = Ablehnen
				column-name = Reject
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				id = L8_R_
				table-column-width = 6
				tid = 105870702457153
			{
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "\"true\".equals(<udp:item column=\"ACTION_RIGHT_VALIDATE\"/>.toString())"
						technicalName = Condition
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips en = "Reject Order", fr = "Rejeter l\'ordre", de = Ablehnen
							horizontalAlignment = center
							icon = cross
							id = Q7e__
							tid = 16147246497419
						{
							Event OnClick (submit) S
							// "Execute selected Update Field TA Function"
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = reject ud
								modal = false
								only-changed = false
								prevalidate = false
								DSEntityCode = "<udp:item column=\"ORDER_CODE\"/>" ud
							}
						}
					}
				}
			}
			--- TableColumn ---
				labels en = Cancel, fr = Annuler, de = Streichen
				column-name = Cancel
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				id = kr___
				table-column-width = 6
				tid = 105870704233069
			{
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "\"true\".equals(<udp:item column=\"ACTION_RIGHT_CANCEL\"/>.toString())"
						technicalName = Condition
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips en = "Cancel Order", fr = "Annuler l\'ordre", de = Streichen
							horizontalAlignment = center
							icon = delete
							id = vjs77
							tid = 16158246265161
						{
							Event OnClick (submit) S
							// "Execute selected Update Field TA Function"
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = cancel ud
								modal = false
								only-changed = false
								prevalidate = false
								DSEntityCode = "<udp:item column=\"ORDER_CODE\"/>" ud
							}
						}
					}
				}
			}
			--- TableColumn ---
				labels en = View, fr = Voir, de = Ansehen
				column-name = View
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				id = OeHw9
				table-column-width = 6
				tid = 1066010454473683
			{
				--- Icon ---
					toolTips en = "View Order", fr = "Voir l’ordre", de = "Auftrag ansehen"
					horizontalAlignment = "${corporatehalign}"
					icon = application_form_magnify
					id = kSM4q
					tid = 1056071597976279
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = view ud
						code = "<udp:item column=\"ORDER_CODE\"/>" ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- TableColumn ---
				labels en = Select, fr = Selection, de = Select
				column-name = ORDER_SELECT
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				id = JD03A
				table-column-width = 6
				tid = 1042332711535963
			{
				--- CheckBox ---
					column-checkbox-action = orderSel
					column-checkbox-identifier = order_id
					checkbox-group-names = ORDER_HIER_STR
					horizontalTextPosition = trail
					id = btn_b8I_g
			}
			--- TableColumn ---
				labels en = "Order Hierarchy"
				column-display-grouping = true
				column-name = ORDER_HIER_STR
				column-type = placeholder !
				type = text
				column-sortable = false !
				id = J_3R1
				table-column-width = 6
				tid = 1042538231988981
			{
				--- TableGroup ---
					aggregateData = false
					group-column-name = ORDER_HIER_STR
					group-sorting-column-name = ORDER_HIER_STR
					group-sorting-direction = ascending
					hierarchy = true
					group-rank = 1
			}
			--- TableColumn ---
				column-name = CREATION_DATE !
				column-type = domain !
				domainAttribute = CREATION_DATE !
				type = text
				id = CREATION_DATE
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = CREATION_DATE
					format = datetime.date-only
					previewValue = value
			}
			--- TableColumn ---
				column-name = ORDER_DATE !
				column-type = domain !
				domainAttribute = ORDER_DATE !
				type = text
				id = u39__
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = ORDER_DATE
					format = datetime.date-only
					previewValue = value
			}
			--- TableColumn ---
				column-name = PORTFOLIO_NAME !
				column-type = domain !
				domainAttribute = PORTFOLIO_NAME !
				type = text
				id = n_PAZ
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = PORTFOLIO_NAME
					previewValue = value
			}
			--- TableColumn ---
				column-name = CATEGORY_LABEL !
				column-type = domain !
				domainAttribute = CATEGORY_LABEL !
				type = text
				id = CATEGORY_LABEL
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = CATEGORY_LABEL
					previewValue = value
			}
			--- TableColumn ---
				column-name = ORDER_SUMMARY !
				column-type = domain !
				domainAttribute = ORDER_SUMMARY !
				type = text
				id = ORDER_SUMMARY
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = ORDER_SUMMARY
					previewValue = value
			}
			--- TableColumn ---
				column-name = VALUE_DATE !
				column-type = domain !
				domainAttribute = VALUE_DATE !
				type = text
				id = w1_F1
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = VALUE_DATE
					format = date
					previewValue = value
			}
			--- TableColumn ---
				column-name = STATUS !
				column-type = domain !
				domainAttribute = STATUS !
				type = text
				id = Pt379
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = STATUS
					previewValue = value
			}
			--- TableColumn ---
				column-name = ORDER_CODE !
				column-type = domain !
				domainAttribute = ORDER_CODE !
				type = text
				column-visibility = never-visible
				id = ORDER_CODE
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = ORDER_CODE
					previewValue = value
			}
			--- TableColumn ---
				column-name = order_id !
				column-type = domain !
				domainAttribute = order_id !
				type = text
				column-is-part-of-filter = false
				column-visibility = never-visible
				id = y_t7_
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = order_id
					format = integer
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = PORTFOLIO_NAME
				sort-rank = 3
			--- TableExtra ---
				domainAttribute = status_id
			--- TableSort ---
				sort-column-name = CATEGORY_LABEL
				sort-rank = 4
			--- TableSort ---
				sort-column-name = CREATION_DATE
				sort-direction = descending
				sort-rank = 2
			--- TableExtra ---
				domainAttribute = ACTION_RIGHT_CANCEL
			--- TableExtra ---
				domainAttribute = ACTION_RIGHT_VALIDATE
			--- TableExtra ---
				domainAttribute = order_id
			--- TableExtra ---
				domainAttribute = ORDER_CODE
		}
	}
}