# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	containment = container
	cssClass = nodeco
	id = PortfolioNotepadView_F05__
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/portfolio/view/PortfolioIdentifierView.module
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/notepad/search/NotepadList.module
	}
}