# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSPortfolio:PortfolioAll"
	cssClass = nodeco
	bean-define = DSBean.AAADSPortfolio.PortfolioAll
	bean-name = PortfolioAll
	id = PortfolioDashboardView_N_KNm
{
	--- Box ---
		boxType = vertical
	{
		--- Box ---
			labels en = Valuation, de = Valorisierung, fr = Valorisation
			boxType = vertical
			widgetBorder = box
			tid = 99862583210597
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 6
				gridColumnsWidth = "16,16,16,16,16,16" !
				gridRowCount = 3
			{
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = extTdMktValPtfCurM !
						for = extTdMktValPtfCurM
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- TextField ---
						domainAttribute = extTdMktValPtfCurM !
						columns = 16
						format = decimal
						horizontalAlignment = "${corporatehalign}"
						type = amount
						chars = 18
						editable = false
						required = true
						bean-property = extTdMktValPtfCurM
						id = extTdMktValPtfCurM
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = extChangeMktValP !
						for = extChangeMktValP
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- TextField ---
						domainAttribute = extChangeMktValP !
						columns = 11
						format = percentTA
						horizontalAlignment = "${corporatehalign}"
						type = percent
						chars = 11
						editable = false
						required = true
						bean-property = extChangeMktValP
						id = extChangeMktValP
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = extPlPercent !
						for = extPlPercent
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- TextField ---
						domainAttribute = extPlPercent !
						columns = 11
						format = percentTA
						horizontalAlignment = "${corporatehalign}"
						type = percent
						chars = 11
						editable = false
						required = true
						bean-property = extPlPercent
						id = extPlPercent
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = extPoshistFromD !
						for = extPoshistFromD
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- CaldateField ---
						domainAttribute = extPoshistFromD !
						format = date
						horizontalAlignment = "${corporatehalign}"
						type = date
						editable = false
						required = true
						bean-property = extPoshistFromD
						id = extPoshistFromD
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = extPoshistTillD !
						for = extPoshistTillD
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- CaldateField ---
						domainAttribute = extPoshistTillD !
						format = date
						horizontalAlignment = "${corporatehalign}"
						type = date
						editable = false
						required = true
						bean-property = extPoshistTillD
						id = extPoshistTillD
				}
				--- GridCell ---
					gridColumnWidth = 16
				--- GridCell ---
					gridColumnWidth = 16
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = extMinBondRating !
						for = extMinBondRating
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- TextField ---
						domainAttribute = extMinBondRating !
						horizontalAlignment = "${corporatehalign}"
						type = text
						chars = 60
						editable = false
						required = true
						bean-property = extMinBondRating
						id = extMinBondRating
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						labels de = "Liquidität - Netto Kapital Ratio (Netto Sollsaldo)", fr = "Ratio liquidités - capital net (net soldes débiteurs)", en = "Liquidity - Net Capital Ratio (Net  Cash Debtor)"
						domainAttribute = extCashPercent !
						for = extCashPercent
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
						tid = 99862589347059
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- TextField ---
						domainAttribute = extCashPercent !
						columns = 11
						format = percentTA
						horizontalAlignment = "${corporatehalign}"
						type = percent
						chars = 11
						editable = false
						required = true
						bean-property = extCashPercent
						id = extCashPercent
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						labels en = "Fixed Income Next Redemption (in days)", fr = "Prochaine expiration de revenu (en jours)", de = "Festes Wertpapier Nächste Tilgung (in Tagen)"
						domainAttribute = extDaysToRedemp !
						for = extDaysToRedemp
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
						tid = 99862590718046
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- TextField ---
						domainAttribute = extDaysToRedemp !
						columns = 9
						format = integer
						horizontalAlignment = "${corporatehalign}"
						type = integer
						chars = 9
						editable = false
						required = true
						bean-property = extDaysToRedemp
						id = extDaysToRedemp
				}
			}
		}
		--- Box ---
			labels en = Compliance, de = Konformität, fr = Conformité
			boxType = vertical
			widgetBorder = box
			tid = 99862592670045
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 6
				gridColumnsWidth = "16,16,16,16,16,16" !
				gridRowCount = 2
			{
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = extObjCompliance !
						for = extObjCompliance
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- ComboBox ---
						domainAttribute = extObjCompliance !
						horizontalAlignment = "${corporatehalign}"
						editable = false
						required = true
						bean-property = extObjCompliance
						id = extObjCompliance
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = extCstCompliance !
						for = extCstCompliance
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- ComboBox ---
						domainAttribute = extCstCompliance !
						horizontalAlignment = "${corporatehalign}"
						editable = false
						required = true
						bean-property = extCstCompliance
						id = extCstCompliance
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = extObjMeanDiff !
						for = extObjMeanDiff
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- TextField ---
						domainAttribute = extObjMeanDiff !
						columns = 11
						format = percentTA
						horizontalAlignment = "${corporatehalign}"
						type = percent
						chars = 11
						editable = false
						required = true
						bean-property = extObjMeanDiff
						id = extObjMeanDiff
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						labels en = "Compliance Checking Date", fr = "Date de la vérification de conformité"
						domainAttribute = extCheckCalcD !
						for = extCheckCalcD
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
						tid = 99862594623514
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- CaldateField ---
						domainAttribute = extCheckCalcD !
						format = date
						horizontalAlignment = "${corporatehalign}"
						type = date
						editable = false
						required = true
						bean-property = extCheckCalcD
						id = extCheckCalcD
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = extIpName !
						for = extIpName
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- TextField ---
						domainAttribute = extIpName !
						horizontalAlignment = "${corporatehalign}"
						type = text
						chars = 60
						editable = false
						required = true
						bean-property = extIpName
						id = extIpName
				}
				--- GridCell ---
					gridColumnWidth = 16
				--- GridCell ---
					gridColumnWidth = 16
			}
		}
		--- Box ---
			labels en = Return, de = Rendite, fr = Rendement
			boxType = vertical
			widgetBorder = box
			tid = 99862596577913
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 6
				gridColumnsWidth = "16,16,16,16,16,16" !
				gridRowCount = 2
			{
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = extYtdPtfReturn !
						for = extYtdPtfReturn
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- TextField ---
						domainAttribute = extYtdPtfReturn !
						columns = 11
						format = percentTA
						horizontalAlignment = "${corporatehalign}"
						type = percent
						chars = 11
						editable = false
						required = true
						bean-property = extYtdPtfReturn
						id = extYtdPtfReturn
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = extYtdBenchRet !
						for = extYtdBenchRet
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- TextField ---
						domainAttribute = extYtdBenchRet !
						columns = 11
						format = percentTA
						horizontalAlignment = "${corporatehalign}"
						type = percent
						chars = 11
						editable = false
						required = true
						bean-property = extYtdBenchRet
						id = extYtdBenchRet
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						labels en = "Ptf/Bench Over/Under Performance", de = "Ptf/Bench über/unter Wertenwicklung"
						domainAttribute = extOverUnderPerf !
						for = extOverUnderPerf
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
						tid = 99862598529280
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- TextField ---
						domainAttribute = extOverUnderPerf !
						columns = 11
						format = percentTA
						horizontalAlignment = "${corporatehalign}"
						type = percent
						chars = 11
						editable = false
						required = true
						bean-property = extOverUnderPerf
						id = extOverUnderPerf
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = extReturnFromD !
						for = extReturnFromD
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- CaldateField ---
						domainAttribute = extReturnFromD !
						format = date
						horizontalAlignment = "${corporatehalign}"
						type = date
						editable = false
						required = true
						bean-property = extReturnFromD
						id = extReturnFromD
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = extReturnTillD !
						for = extReturnTillD
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- CaldateField ---
						domainAttribute = extReturnTillD !
						format = date
						horizontalAlignment = "${corporatehalign}"
						type = date
						editable = false
						required = true
						bean-property = extReturnTillD
						id = extReturnTillD
				}
				--- GridCell ---
					gridColumnWidth = 16
				--- GridCell ---
					gridColumnWidth = 16
			}
		}
		--- Box ---
			labels en = Activity, de = Aktivität, fr = Activité
			boxType = vertical
			widgetBorder = box
			tid = 99862600482690
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 6
				gridColumnsWidth = "16,16,16,16,16,16" !
				gridRowCount = 1
			{
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = extDateOperation !
						for = extDateOperation
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- CaldateField ---
						domainAttribute = extDateOperation !
						format = date
						horizontalAlignment = "${corporatehalign}"
						type = date
						editable = false
						required = true
						bean-property = extDateOperation
						id = extDateOperation
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = extDateFxOperat !
						for = extDateFxOperat
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- CaldateField ---
						domainAttribute = extDateFxOperat !
						format = date
						horizontalAlignment = "${corporatehalign}"
						type = date
						editable = false
						required = true
						bean-property = extDateFxOperat
						id = extDateFxOperat
				}
				--- GridCell ---
					gridColumnWidth = 16
				--- GridCell ---
					gridColumnWidth = 16
			}
		}
	}
}