# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Portfolio Identifier", fr = "Identifiant du portefeuille", de = "Portfolio Identifikator"
	domainEntity = "AAADSPortfolio:PortfolioAll"
	cssClass = nodeco
	bean-define = DSBean.AAADSPortfolio.PortfolioAll
	bean-name = PortfolioAll
	id = PortfolioIdentifierView_c0sZx
	tid = 99887912136754
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- Include ---
			includeSrc = "" !
			resource:///default/portfolio/portfolioall/PortfolioIdentifierView.fragment
	}
}