# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Portfolio Details", fr = "Détails du portefeuille", de = "Details des Portfolios"
	containment = container
	domainEntity = "AAADSPortfolio:PortfolioAdmin"
	bean-define = DSBean.AAADSPortfolio.PortfolioAdmin
	bean-name = PortfolioAdmin
	id = PortfolioAdministration_pK6tU
	documentation = "This module is used to have a global overview on the portfolio to administrate (details, strategy links, constraints, ...)"
	tid = 99858399626006
{
	--- Box ---
		boxType = vertical
	{
		--- Box ---
			labels en = Portfolio, fr = Portefeuille, de = Portfolio
			boxType = vertical
			tid = 99858401402254
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 4
				gridColumnsWidth = "25,25,25,25" !
				gridRowCount = 1
			{
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- LabelDomain ---
						labels en = "Portfolio Code", fr = "Code du portefeuille", de = "Code des Portfolios"
						domainAttribute = code !
						for = code
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
						id = code
						tid = 99858403356978
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- TextField ---
						domainAttribute = code !
						horizontalAlignment = "${corporatehalign}"
						type = text
						chars = 20
						editable = false
						required = true
						bean-property = code
						id = code
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- LabelDomain ---
						labels en = "Portfolio Name", fr = "Nom du portefeuille", de = "Name des Portfolios"
						domainAttribute = name !
						for = name
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
						id = name
						tid = 99858405319181
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- TextField ---
						domainAttribute = name !
						columns = 30
						horizontalAlignment = "${corporatehalign}"
						type = text
						chars = 20
						editable = false
						required = true
						bean-property = name
						id = name
				}
			}
		}
		--- TabbedPane ---
			id = L6__7
			indexOfSelectedChild = 1
		{
			--- Tab ---
				labels en = Constraints, fr = Contraintes, de = Beschränkungen toolTips en = "Click here to view related constraints", fr = "Cliquer ici pour voir les contraintes associées", de = "Klicken Sie hier um die zugehörige Beschränkungen zu ansehen "
				boxType = vertical
				id = tab_kUa03
				isWidgetVisible = false
				tid = 99858408357057
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 4
					gridColumnsWidth = "15,15,15,55" !
					gridRowCount = 1
				{
					--- GridCell ---
						gridColumnWidth = 15
					{
						--- RadioButton ---
							labels en = "All constraints", fr = "Toutes les contraintes", de = "Alle Beschränkungen" toolTips en = "Click here to view all existing constraints", fr = "Cliquer ici pour voir toutes les contraintes existantes", de = "Klicken Sie hier um all bestehende Beschränkungen zu ansehen"
							group = constraints
							id = allConstraints
							tid = 99858410195753
					}
					--- GridCell ---
						gridColumnWidth = 15
					{
						--- RadioButton ---
							labels en = "All active constraints", fr = "Toutes les contraintes actives", de = "All aktive Beschränkungen" toolTips en = "Click here to view all existing active constraints", fr = "Cliquer ici pour voir toutes les contraintes actives existantes", de = "Klicken Sie hier um all bestehende aktive Beschränkungen zu ansehen"
							selected = true
							group = constraints
							id = allActiveConstraints
							tid = 99858412143776
					}
					--- GridCell ---
						gridColumnWidth = 15
					{
						--- RadioButton ---
							labels en = "All inactive constraints", fr = "Toutes les contraintes inactives", de = "All inaktive Beschränkungen" toolTips en = "Click here to view all existing inactive constraints", fr = "Cliquer ici pour voir toutes les contraintes inactives existantes", de = "Klicken Sie hier um all bestehende inaktive Beschränkungen zu ansehen"
							group = constraints
							id = allInactiveConstraints
							tid = 99858414096250
					}
					--- GridCell ---
						gridColumnWidth = 55
				}
				--- Conditional ---
					indexOfSelectedChild = 2
				{
					--- ConditionalBody ---
						javaCode = "<nav:is-selected  group-id=\"constraints\" element-id=\"allActiveConstraints\" default-selected=\"true\" />"
						technicalName = "All Active Constraints"
						boxType = vertical
						isWidgetVisible = false
					{
						--- Box ---
							labels en = "Active Allocation Constraints", fr = "Contraintes d\'allocation actives", de = "Aktive Zuweisungsbeschränkungen"
							boxType = vertical
							tid = 99858416050922
						{
							--- Include ---
								includeSrc = "" !
								resource:///Default/module/aaa/administration/modellingconstraint/allocationconstraint/search/AllActiveAllocConstList.module
						}
						--- Box ---
							labels en = "Active Exclusion Constraints", fr = "Contraintes d\'exclusion actives", de = "Aktive Ausschlussbeschränkungen"
							boxType = vertical
							tid = 99858418003568
						{
							--- Include ---
								includeSrc = "" !
								resource:///Default/module/aaa/administration/modellingconstraint/securityoutconstraint/search/AllActiveSecOutConstList.module
							--- Include ---
								includeSrc = "" !
								resource:///default/portfolio/administration/ButtonNewSecurityOutConstraint.fragment
						}
					}
					--- ConditionalBody ---
						javaCode = "<nav:is-selected  group-id=\"constraints\" element-id=\"allConstraints\"/>"
						technicalName = "All Constraints"
						boxType = vertical
						isWidgetVisible = false
					{
						--- Box ---
							labels en = "Allocation Constraints", fr = "Contraintes d\'allocation", de = Zuweisungsbeschränkungen
							boxType = vertical
							tid = 99858419960363
						{
							--- Include ---
								includeSrc = "" !
								resource:///Default/module/aaa/administration/modellingconstraint/allocationconstraint/search/AllAllocationConstraintList.module
						}
						--- Box ---
							labels en = "Exclusion Constraints", fr = "Contraintes d\'exclusion", de = Ausschlussbeschränkungen
							boxType = vertical
							tid = 99858421910299
						{
							--- Include ---
								includeSrc = "" !
								resource:///Default/module/aaa/administration/modellingconstraint/securityoutconstraint/search/AllSecOutConstList.module
							--- Include ---
								includeSrc = "" !
								resource:///default/portfolio/administration/ButtonNewSecurityOutConstraint.fragment
						}
					}
					--- ConditionalBody ---
						javaCode = "<nav:is-selected  group-id=\"constraints\" element-id=\"allInactiveConstraints\"/>"
						technicalName = "All Inactive Constraints"
						boxType = vertical
						isWidgetSelected = true
					{
						--- Box ---
							labels en = "Inactive Allocation Constraints", fr = "Contraintes d\'allocation inactives", de = "Inaktive Zuweisungsbeschränkungen"
							boxType = vertical
							tid = 99858423875669
						{
							--- Include ---
								includeSrc = "" !
								resource:///Default/module/aaa/administration/modellingconstraint/allocationconstraint/search/AllInactiveAllocConstList.module
						}
						--- Box ---
							labels en = "Inactive Exclusion Constraints", fr = "Contraintes d\'exclusion inactives", de = "Inaktive Ausschlussbeschränkungen"
							boxType = vertical
							tid = 99858425816321
						{
							--- Include ---
								includeSrc = "" !
								resource:///Default/module/aaa/administration/modellingconstraint/securityoutconstraint/search/AllInactiveSecOutConstList.module
							--- Include ---
								includeSrc = "" !
								resource:///default/portfolio/administration/ButtonNewSecurityOutConstraint.fragment
						}
					}
				}
			}
			--- Tab ---
				labels en = "Strategy Links", fr = "Liens de stratégie", de = Strategieverknüpfungen toolTips en = "Click here to view related strategy links", fr = "Cliquer ici pour voir les liens de stratégie associés", de = "Klicken Sie hier um die zugehörige Strategieverknüpfungen zu ansehen "
				boxType = vertical
				id = tab_V_bmy
				isWidgetSelected = true
				tid = 99858427866247
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 4
					gridColumnsWidth = "15,15,15,55" !
					gridRowCount = 1
				{
					--- GridCell ---
						gridColumnWidth = 15
					{
						--- RadioButton ---
							labels en = "All strategy links", fr = "Tous les liens de stratégie", de = "Alle Strategieverknüpfungen" toolTips en = "Click here to view all existing strategy links", fr = "Cliquer ici pour voir toutes les liens de stratégie existants", de = "Klicken Sie hier um all bestehende Strategieverknüpfungen zu ansehen"
							group = strategyLinks
							id = allStrategyLinks
							tid = 99858429723089
					}
					--- GridCell ---
						gridColumnWidth = 15
					{
						--- RadioButton ---
							labels en = "All active strategy links", fr = "Tous les liens de stratégie actifs", de = "Alle aktive Strategieverknüpfungen" toolTips en = "Click here to view all existing active strategy links", fr = "Cliquer ici pour voir toutes les liens de stratégie actifs existants", de = "Klicken Sie hier um all bestehende aktive Strategieverknüpfungen zu ansehen"
							selected = true
							group = strategyLinks
							id = allActiveStrategyLinks
							tid = 99858431698564
					}
					--- GridCell ---
						gridColumnWidth = 15
					{
						--- RadioButton ---
							labels en = "All inactive strategy links", fr = "Tous les liens de stratégie inactifs", de = "Alle inaktive Strategieverknüpfungen" toolTips en = "Click here to view all existing inactive strategy links", fr = "Cliquer ici pour voir toutes les liens de stratégie inactifs existants", de = "Klicken Sie hier um all bestehende inaktive Strategieverknüpfungen zu ansehen"
							group = strategyLinks
							id = allInactiveStrategyLinks
							tid = 99858433629135
					}
					--- GridCell ---
						gridColumnWidth = 55
				}
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "<nav:is-selected  group-id=\"strategyLinks\" element-id=\"allActiveStrategyLinks\" default-selected=\"true\" />"
						technicalName = "All Active Strategy Links"
						boxType = vertical
						isWidgetSelected = true
					{
						--- Box ---
							labels en = "Active Strategy Links", fr = "Liens de stratégie actifs", de = "Aktive Strategieverknüpfungen"
							boxType = vertical
							tid = 99858435590767
						{
							--- Include ---
								includeSrc = "" !
								resource:///Default/module/aaa/administration/strategylink/search/ActiveStrategyLinkList.module
							--- Include ---
								includeSrc = "" !
								resource:///default/portfolio/administration/ButtonNewStrategyLink.fragment
						}
					}
					--- ConditionalBody ---
						javaCode = "<nav:is-selected  group-id=\"strategyLinks\" element-id=\"allStrategyLinks\"/>"
						technicalName = "All Strategy Links"
						boxType = vertical
						isWidgetVisible = false
					{
						--- Box ---
							labels en = "Strategy Links", fr = "Liens de stratégie", de = Strategieverknüpfungen
							boxType = vertical
							tid = 99858437538708
						{
							--- Include ---
								includeSrc = "" !
								resource:///Default/module/aaa/administration/strategylink/search/AllStrategyLinkList.module
							--- Include ---
								includeSrc = "" !
								resource:///default/portfolio/administration/ButtonNewStrategyLink.fragment
						}
					}
					--- ConditionalBody ---
						javaCode = "<nav:is-selected  group-id=\"strategyLinks\" element-id=\"allInactiveStrategyLinks\"/>"
						technicalName = "All Inactive Strategy Links"
						boxType = vertical
						isWidgetVisible = false
					{
						--- Box ---
							labels en = "Inactive Strategy Links", fr = "Liens de stratégie inactifs", de = "Inaktive Strategieverknüpfungen"
							boxType = vertical
							tid = 99858439497991
						{
							--- Include ---
								includeSrc = "" !
								resource:///Default/module/aaa/administration/strategylink/search/InactiveStrategyLinkList.module
							--- Include ---
								includeSrc = "" !
								resource:///default/portfolio/administration/ButtonNewStrategyLink.fragment
						}
					}
				}
			}
		}
	}
}