# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "View Portfolio", fr = "Voir le portefeuille", de = Portfolioübersicht
	containment = container
	domainEntity = "AAADSPortfolio:PortfolioAll"
	bean-define = DSBean.AAADSPortfolio.PortfolioAll
	bean-name = PortfolioAll
	id = PortfolioView_q2j5_
	tid = 99890521427321
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			id = P_5b9
			indexOfSelectedChild = 0
		{
			--- Tab ---
				labels en = Details, fr = Détails, de = Details
				id = tab_Q__7R
				isWidgetSelected = true
				tid = 99890523986202
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/portfolio/view/PortfolioDetailView.module
			}
			--- Tab ---
				labels en = Notepad, fr = Bloc-note, de = Notizblock
				boxType = vertical
				id = tab_qa_2Q
				isWidgetVisible = false
				tid = 99890526309757
			{
				Event OnClick (submit)
				{
					method = get
					call-URI = "<pageflow:continuation/>"
					param = "flow-action=notepadsearch"
					Query.Filter1.attribute = object ud
					Query.Filter1.operator = EQUAL ud
					Query.Filter1.value1 = "valueOf(form.id)" ud
					Query.DSQuery = "AAADSNotepad:NotepadSearchCriteria" ud
					Query.DSOutput = "AAADSNotepad:NotepadList" ud
					Query.Filter2.attribute = entityDict ud
					Query.Filter2.operator = EQUAL ud
					Query.Filter2.value1 = 800 ud
					modal = false
					only-changed = false
					prevalidate = false
				}
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/notepad/search/NotepadList.module
			}
		}
	}
}