# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = Portfolio, de = Portfolio, fr = Portefeuille
	containment = container
	domainEntity = "AAADSPortfolio:PortfolioAll"
	cssClass = nodeco
	bean-define = DSBean.AAADSPortfolio.PortfolioAll
	bean-name = PortfolioAll
	id = PortfolioView_DBG7Y
	tid = 6085189048483
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- Box ---
			labels en = Identification, de = Identifikation, fr = Identification
			boxType = vertical
			widgetBorder = box
			tid = 447960244958634
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 2
				gridColumnsWidth = "16,80" !
				gridRowCount = 3
			{
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = code !
						for = code
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
				}
				--- GridCell ---
					gridColumnWidth = 80
				{
					--- TextField ---
						domainAttribute = code !
						horizontalAlignment = "${corporatehalign}"
						type = text
						chars = 20
						editable = false
						required = true
						bean-property = code
						id = code
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = name !
						for = name
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
				}
				--- GridCell ---
					gridColumnWidth = 80
				{
					--- TextField ---
						domainAttribute = name !
						horizontalAlignment = "${corporatehalign}"
						type = text
						chars = 20
						editable = false
						required = true
						bean-property = name
						id = name
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = extDenomination !
						for = extDenomination
						horizontalAlignment = "${corporatehalign}"
						required = true
				}
				--- GridCell ---
					gridColumnWidth = 80
				{
					--- TextArea ---
						domainAttribute = extDenomination
						columns = 30
						rows = 3
						editable = false
						bean-property = extDenomination
						id = extDenomination
				}
			}
		}
		--- Box ---
			labels en = "Nature & Type", de = "Art & Typ", fr = "Nature et type"
			boxType = vertical
			widgetBorder = box
			tid = 447979143556043
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 6
				gridColumnsWidth = "16,16,16,16,16,16" !
				gridRowCount = 3
			{
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = natureE !
						for = natureE
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- ComboBox ---
						domainAttribute = natureE !
						horizontalAlignment = "${corporatehalign}"
						editable = false
						required = true
						bean-property = natureE
						id = natureE
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = type !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- Include ---
						domainAssociation = type
						includeSrc = "" !
						resource:///default/defaultFragments/TypeIdentifierDenomView.fragment
						bean-property-prefix = type.
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = currency !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- Include ---
						domainAssociation = currency
						includeSrc = "" !
						resource:///default/defaultFragments/CurrencyIdentifierView.fragment
						bean-property-prefix = currency.
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = serviceTypeE !
						for = serviceTypeE
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- ComboBox ---
						domainAttribute = serviceTypeE !
						horizontalAlignment = "${corporatehalign}"
						editable = false
						required = true
						bean-property = serviceTypeE
						id = serviceTypeE
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = managType !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- Include ---
						domainAssociation = managType
						includeSrc = "" !
						resource:///default/defaultFragments/TypeIdentifierDenomView.fragment
						bean-property-prefix = managType.
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = mgtBeginD !
						for = mgtBeginD
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- CaldateField ---
						domainAttribute = mgtBeginD !
						format = datetime.date-only
						horizontalAlignment = "${corporatehalign}"
						type = datetime
						editable = false
						bean-property = mgtBeginD
						id = mgtBeginD
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = statusE !
						for = statusE
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- ComboBox ---
						domainAttribute = statusE !
						horizontalAlignment = "${corporatehalign}"
						editable = false
						required = true
						bean-property = statusE
						id = statusE
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						labels en = Active, fr = Actif
						domainAttribute = activeF !
						for = activeF
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
						tid = 261735277363762
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- ComboBox ---
						domainAttribute = activeF !
						horizontalAlignment = "${corporatehalign}"
						editable = false
						required = true
						bean-property = activeF
						id = activeF
				}
				--- GridCell ---
					gridColumnWidth = 16
				--- GridCell ---
					gridColumnWidth = 16
			}
		}
		--- Box ---
			labels en = "Owner & Manager", de = "Eigentümer & Manager", fr = "Titulaire & gestionnaire"
			boxType = vertical
			widgetBorder = box
			tid = 448442462542954
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 6
				gridColumnsWidth = "16,16,16,16,16,16" !
				gridRowCount = 2
			{
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = third !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- Include ---
						domainAssociation = third
						includeSrc = "" !
						resource:///default/defaultFragments/ThirdPartyIdentifierView.fragment
						bean-property-prefix = third.
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = parentPort !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- Include ---
						domainAssociation = parentPort
						includeSrc = "" !
						resource:///default/defaultFragments/PortfolioIdentifierNameView.fragment
						bean-property-prefix = parentPort.
				}
				--- GridCell ---
					gridColumnWidth = 16
				--- GridCell ---
					gridColumnWidth = 16
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						labels en = Manager, de = Verwalter, fr = Gestionnaire
						domainAttribute = adminMgr !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						tid = 261799420711953
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- Include ---
						domainAssociation = adminMgr
						includeSrc = "" !
						resource:///default/defaultFragments/ManagerIdentifierView.fragment
						bean-property-prefix = adminMgr.
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						labels en = Advisor, fr = Conseiller, de = Berater
						domainAttribute = commMgr !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						tid = 261806236492330
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- Include ---
						domainAssociation = commMgr
						includeSrc = "" !
						resource:///default/defaultFragments/ManagerIdentifierView.fragment
						bean-property-prefix = commMgr.
				}
				--- GridCell ---
					gridColumnWidth = 16
				--- GridCell ---
					gridColumnWidth = 16
			}
		}
		--- TabbedPane ---
			id = t__v7
			indexOfSelectedChild = 0
		{
			--- Tab ---
				labels en = Details, fr = Détails, de = Details
				boxType = vertical
				id = tab_ICk0_
				isWidgetSelected = true
				tid = 448484237681771
			{
				--- Box ---
					labels en = Settings, de = Einstellungen, fr = Paramètres
					boxType = vertical
					widgetBorder = box
					tid = 518639388384222
				{
					--- Grid ---
						cssClass = blank
						gridColumnCount = 6
						gridColumnsWidth = "16,16,16,16,16,16" !
						gridRowCount = 3
					{
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = fusionRuleE !
								for = fusionRuleE
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- ComboBox ---
								domainAttribute = fusionRuleE !
								horizontalAlignment = "${corporatehalign}"
								editable = false
								required = true
								bean-property = fusionRuleE
								id = fusionRuleE
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = negativeCashE !
								for = negativeCashE
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- ComboBox ---
								domainAttribute = negativeCashE !
								horizontalAlignment = "${corporatehalign}"
								editable = false
								required = true
								bean-property = negativeCashE
								id = negativeCashE
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = language !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- Include ---
								domainAssociation = language
								includeSrc = "" !
								resource:///default/defaultFragments/DictLanguageIdentifierDenomView.fragment
								bean-property-prefix = language.
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = lastRebalancingD !
								for = lastRebalancingD
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- CaldateField ---
								domainAttribute = lastRebalancingD !
								format = datetime.date-only
								horizontalAlignment = "${corporatehalign}"
								type = datetime
								editable = false
								bean-property = lastRebalancingD
								id = lastRebalancingD
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = suitabilityToleranceD !
								for = suitabilityToleranceD
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- CaldateField ---
								domainAttribute = suitabilityToleranceD !
								format = datetime.date-only
								horizontalAlignment = "${corporatehalign}"
								type = datetime
								editable = false
								bean-property = suitabilityToleranceD
								id = suitabilityToleranceD
						}
						--- GridCell ---
							gridColumnWidth = 16
						--- GridCell ---
							gridColumnWidth = 16
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = taxStatusE !
								for = taxStatusE
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- ComboBox ---
								domainAttribute = taxStatusE !
								horizontalAlignment = "${corporatehalign}"
								editable = false
								required = true
								bean-property = taxStatusE
								id = taxStatusE
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- LabelDomain ---
								domainAttribute = taxConvention !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 16
						{
							--- Include ---
								domainAssociation = taxConvention
								includeSrc = "" !
								resource:///default/defaultFragments/FtConventionIdentifierView.fragment
								bean-property-prefix = taxConvention.
						}
						--- GridCell ---
							gridColumnWidth = 16
						--- GridCell ---
							gridColumnWidth = 16
					}
				}
			}
			--- Tab ---
				labels en = Dashboard, de = Überblick, fr = "Tableau de bord"
				boxType = vertical
				id = tab_k459U
				isWidgetVisible = false
				tid = 448505557683670
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/portfolio/view/PortfolioDashboardView.module
			}
			--- Tab ---
				labels en = Notepad, de = Notizblock, fr = Bloc-note
				id = tab_r76_J
				isWidgetVisible = false
				tid = 450564965079355
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/notepad/search/NotepadList.module
			}
		}
	}
}