# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels fr = "Liste de positions", en = "List of Positions", de = Bestandsliste
	containment = container
	domainEntity = "AAADSValuation:ValuationDetailledList"
	verticalAlignment = lead
	bean-define = DSBean.AAADSValuation.ValuationDetailledList
	bean-name = ValuationDetailledList
	id = DetailedList_hG_17
	tid = 504046285361407
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TabbedPane ---
			hide-empty-tabs = true
			tabs-filtered-attribute = ASSET_CLASS_RANK
			id = ASSET_CLASS_RANK
			indexOfSelectedChild = 8
		{
			--- Tab ---
				labels en = All, fr = Tous, de = Alle
				boxType = vertical
				id = tab_detail_all
				isWidgetVisible = false
				tid = 22978019239037
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/valuation/detailedlist/ByAssetClass/AllAccounting.module
				--- Include ---
					includeSrc = "" !
					resource:///default/initiateorder/NavigationInitiateOrderFromValuation.fragment
			}
			--- Tab ---
				labels fr = Actions, en = Stocks, de = Aktien
				hide-empty-tab = true
				tab-filter = 1
				boxType = vertical
				id = tab_detail_eqty
				isWidgetVisible = false
				tid = 6229739499266
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/valuation/detailedlist/ByAssetClass/StockAccounting.module
				--- Include ---
					includeSrc = "" !
					resource:///default/initiateorder/NavigationInitiateOrderFromValuation.fragment
			}
			--- Tab ---
				labels en = "Fixed Income", fr = "Titre à revenu fixe", de = Anleihen
				hide-empty-tab = true
				tab-filter = 2
				boxType = vertical
				id = tab_detail_fi
				isWidgetVisible = false
				tid = 80941078178733
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/valuation/detailedlist/ByAssetClass/FIAccounting.module
				--- Include ---
					includeSrc = "" !
					resource:///default/initiateorder/NavigationInitiateOrderFromValuation.fragment
			}
			--- Tab ---
				labels en = Funds, de = Fondsanteile, fr = Fonds
				hide-empty-tab = true
				tab-filter = 3
				boxType = vertical
				id = tab_Q_Z83
				isWidgetVisible = false
				tid = 22769298409155
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/valuation/detailedlist/ByAssetClass/FundAccounting.module
				--- Include ---
					includeSrc = "" !
					resource:///default/initiateorder/NavigationInitiateOrderFromValuation.fragment
			}
			--- Tab ---
				labels en = Derivatives, de = Derivate, fr = Dérivés
				hide-empty-tab = true
				tab-filter = 4
				boxType = vertical
				id = tab_J9O_S
				isWidgetVisible = false
				tid = 23062880740708
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/valuation/detailedlist/ByAssetClass/DerivativesAccounting.module
				--- Include ---
					includeSrc = "" !
					resource:///default/initiateorder/NavigationInitiateOrderFromValuation.fragment
			}
			--- Tab ---
				labels en = Liquidity, de = Liquidität, fr = Liquidité
				hide-empty-tab = true
				tab-filter = 5
				id = tab_S6_r_
				isWidgetVisible = false
				tid = 23104495198691
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/valuation/detailedlist/ByAssetClass/LiquidityAccounting.module
			}
			--- Tab ---
				labels en = "Money Market", fr = "Marché monétaire", de = Geldmarkt
				hide-empty-tab = true
				tab-filter = 6
				boxType = vertical
				id = tab_detail_mm
				isWidgetVisible = false
				tid = 81199185730305
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/valuation/detailedlist/ByAssetClass/MMAccounting.module
				--- Include ---
					includeSrc = "" !
					resource:///default/initiateorder/NavigationInitiateOrderFromValuation.fragment
			}
			--- Tab ---
				labels en = Forwards, de = Devisentermin, fr = "Contrats à terme"
				hide-empty-tab = true
				tab-filter = 7
				id = tab_T_424
				isWidgetVisible = false
				tid = 23144062167398
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/valuation/detailedlist/ByAssetClass/ForwardsAccounting.module
			}
			--- Tab ---
				labels en = Others, fr = Autres, de = "Übrige Anlagen"
				hide-empty-tab = true
				tab-filter = 99
				boxType = vertical
				id = tab_detail_alt
				isWidgetSelected = true
				tid = 81277817914895
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/valuation/detailedlist/ByAssetClass/OthersAccounting.module
				--- Include ---
					includeSrc = "" !
					resource:///default/initiateorder/NavigationInitiateOrderFromValuation.fragment
			}
		}
	}
}