# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels fr = "Liste de positions", en = "List of Positions", de = Bestandsliste
	containment = container
	domainEntity = "AAADSValuation:ValuationDetailledList"
	verticalAlignment = lead
	bean-define = DSBean.AAADSValuation.ValuationDetailledList
	bean-name = ValuationDetailledList
	id = DetailedListWithoutInitiateOrder_u5Or6
	tid = 92155878331687
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TabbedPane ---
			hide-empty-tabs = true
			tabs-filtered-attribute = ASSET_CLASS_RANK
			id = v4_Gg
			indexOfSelectedChild = 8
		{
			--- Tab ---
				labels en = All, fr = Tous, de = Alle
				boxType = vertical
				id = tab_J_5_i
				isWidgetVisible = false
				tid = 92155878827129
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/valuation/detailedlist/ByAssetClass/AllAccountingWithoutInitiateOrder.module
			}
			--- Tab ---
				labels fr = Actions, en = Stocks, de = Aktien
				hide-empty-tab = true
				tab-filter = 1
				boxType = vertical
				id = tab_w8__9
				isWidgetVisible = false
				tid = 92155881726392
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/valuation/detailedlist/ByAssetClass/StockAccountingWithoutInitiateOrder.module
			}
			--- Tab ---
				labels en = "Fixed Income", fr = "Titre à revenu fixe", de = Anleihen
				hide-empty-tab = true
				tab-filter = 2
				boxType = vertical
				id = tab_s__DS
				isWidgetVisible = false
				tid = 92155883666868
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/valuation/detailedlist/ByAssetClass/FIAccountingWithoutInitiateOrder.module
			}
			--- Tab ---
				labels en = Funds, de = Fondsanteile, fr = Fonds
				hide-empty-tab = true
				tab-filter = 3
				boxType = vertical
				id = tab_J6Q_D
				isWidgetVisible = false
				tid = 92155886014605
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/valuation/detailedlist/ByAssetClass/FundAccountingWithoutInitiateOrder.module
			}
			--- Tab ---
				labels en = Derivatives, de = Derivate, fr = Dérivés
				hide-empty-tab = true
				tab-filter = 4
				boxType = vertical
				id = tab_Xb3_Y
				isWidgetVisible = false
				tid = 92155887575025
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/valuation/detailedlist/ByAssetClass/DerivativesAccountingWithoutInitiateOrder.module
			}
			--- Tab ---
				labels en = Liquidity, de = Liquidität, fr = Liquidité
				hide-empty-tab = true
				tab-filter = 5
				id = tab_I0k80
				isWidgetVisible = false
				tid = 92155889530972
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/valuation/detailedlist/ByAssetClass/LiquidityAccounting.module
			}
			--- Tab ---
				labels en = "Money Market", fr = "Marché monétaire", de = Geldmarkt
				hide-empty-tab = true
				tab-filter = 6
				boxType = vertical
				id = tab_U3N_x
				isWidgetVisible = false
				tid = 92155891478392
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/valuation/detailedlist/ByAssetClass/MMAccountingWithoutInitiateOrder.module
			}
			--- Tab ---
				labels en = Forwards, de = Devisentermin, fr = "Contrats à terme"
				hide-empty-tab = true
				tab-filter = 7
				id = tab_u7_8_
				isWidgetVisible = false
				tid = 92155893432690
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/valuation/detailedlist/ByAssetClass/ForwardsAccounting.module
			}
			--- Tab ---
				labels en = Others, fr = Autres, de = "Übrige Anlagen"
				hide-empty-tab = true
				tab-filter = 99
				boxType = vertical
				id = tab_JWI_5
				isWidgetSelected = true
				tid = 92155900277392
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/valuation/detailedlist/ByAssetClass/OthersAccountingWithoutInitiateOrder.module
			}
		}
	}
}