# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = Context, fr = Contexte, de = Kontext
	containment = container
	domainEntity = "AAADSDomain:DomainContext"
	collapsed = true
	collapsible = true
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = ContextNotEditedHead_Q_j_2
	tid = 12333602815396
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TabbedPane ---
			id = vO__Q
			indexOfSelectedChild = 1
		{
			--- Tab ---
				labels fr = Base, en = Basic, de = Einfach
				id = perf_global_basic
				isWidgetVisible = false
				tid = 12333603256173
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/performance/global/context/ContextBasicNotEdited.module
			}
			--- Tab ---
				labels fr = Avancée, en = Advanced, de = Erweitert
				id = perf_global_advanced
				isWidgetSelected = true
				tid = 12333605206535
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/performance/global/context/ContextAdvancedNotEdited.module
			}
		}
		--- Grid ---
			cssClass = blank
			gridColumnCount = 4
			gridColumnsWidth = "25,25,25,25" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Button ---
					labels en = Execute, de = Ausführen, fr = Exécuter
					id = btn_la6_6
					tid = 12333607227852
				{
					Event OnClick (submit)
					{
						method = get
						call-URI = "<pageflow:continuation/>"
						widget-group-ref = form
						param = "flow-action=execute"
						only-changed = true
						prevalidate = false
						modal = false
					}
				}
				--- Button ---
					labels en = Refresh, de = Aktualisieren, fr = Actualiser
					id = btn_w_r1_
					tid = 12333609113754
				{
					Event OnClick (submit)
					{
						method = get
						call-URI = "<pageflow:continuation/>"
						widget-group-ref = form
						param = "flow-action=execute,DSAction=refresh"
						only-changed = true
						prevalidate = false
						modal = false
					}
				}
				--- Button ---
					labels en = "Default Settings", de = Standardeinstellung, fr = "Valeurs par défaut"
					id = btn_xx_Vi
					tid = 12333611084410
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = reset ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
		}
	}
}