# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSDomain:DomainContext"
	collapsible = true
	cssClass = nodeco
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = ContextAdvanced_l8_J_
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 4
			gridColumnsWidth = "12,12,12,54" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 12
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainPLMethod.fragment
			}
			--- GridCell ---
				gridColumnWidth = 12
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainDynamicWeight.fragment
			}
			--- GridCell ---
				gridColumnWidth = 12
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainPerformanceFrequency1.fragment
			}
			--- GridCell ---
				gridColumnWidth = 54
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainStrategyLink.fragment
			}
		}
	}
}