# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Portfolio Details", fr = "Détails du portefeuille", de = "Details des Portfolios"
	domainEntity = "AAADSDomain:DomainContextDetail"
	collapsed = true
	bean-define = DSActivityBean.AAADSDomain.DomainContextDetail
	bean-name = DomainContextDetail
	id = PortfolioCodeDetailHead_b64c_
	tid = 12350211772187
{
	--- Box ---
		boxType = vertical
		cssClass = nodeco
	{
		--- TabbedPane ---
			id = A78_7
			indexOfSelectedChild = 0
		{
			--- Tab ---
				labels en = Basic, fr = Base, de = Einfach
				id = perf_global_basic_details
				isWidgetSelected = true
				tid = 12350212279051
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 6
					gridColumnsWidth = "20,8,8,8,8,8" !
					gridRowCount = 1
					verticalAlignment = lead
				{
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainPortfolioCodeView.fragment
					}
					--- GridCell ---
						gridColumnWidth = 8
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainFromDateView.fragment
					}
					--- GridCell ---
						gridColumnWidth = 8
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainPivotDateTillView.fragment
					}
					--- GridCell ---
						gridColumnWidth = 8
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainRefCurrencyView.fragment
					}
					--- GridCell ---
						gridColumnWidth = 8
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainHierarchyIdentifierView.fragment
					}
					--- GridCell ---
						gridColumnWidth = 8
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainConsolidationIdentifierView.fragment
					}
				}
			}
			--- Tab ---
				labels en = Advanced, fr = Avancé, de = Erweitert
				id = perf_global_advanced_details
				isWidgetVisible = false
				tid = 12350214182778
			{
				--- Box ---
					boxType = vertical
				{
					--- Grid ---
						cssClass = blank
						gridColumnCount = 4
						gridColumnsWidth = "12,12,12,54" !
						gridRowCount = 1
					{
						--- GridCell ---
							gridColumnWidth = 12
						{
							--- Include ---
								includeSrc = "" !
								resource:///default/domain/basicelements/DomainPLMethodView.fragment
						}
						--- GridCell ---
							gridColumnWidth = 12
						{
							--- Include ---
								includeSrc = "" !
								resource:///default/domain/basicelements/DomainDynamicWeightView.fragment
						}
						--- GridCell ---
							gridColumnWidth = 12
						{
							--- Include ---
								includeSrc = "" !
								resource:///default/domain/basicelements/DomainPerformanceFrequency1View.fragment
						}
						--- GridCell ---
							gridColumnWidth = 54
						{
							--- Include ---
								includeSrc = "" !
								resource:///default/domain/basicelements/DomainPortfolioDetailsStrategyLinkView.fragment
						}
					}
				}
			}
		}
	}
}