# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Compliance Chrono List", fr = "Liste de la chronologie de conformité", de = "Zeitl. Ablauf Konformität"
	domainEntity = "AAADSComplianceChrono:ComplianceChronoList"
	bean-define = DSBean.AAADSComplianceChrono.ComplianceChronoList
	bean-name = ComplianceChronoList
	id = ComplianceChronoList_J60G_
	tid = 28558611810439
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			id = VkB97
			table-column-count = 9 !
			table-columns-width = "11,11,11,11,11,11,11,11,11" !
		{
			--- TableColumn ---
				labels de = Portfolio
				column-name = portfolioCode !
				column-type = domain !
				domainAttribute = portfolioCode !
				id = portfolioCode
				table-column-width = 11
				tid = 27119220489754
			{
				--- TableColumnItem ---
					item-column = portfolioCode
					previewValue = value
			}
			--- TableColumn ---
				labels de = Strategie, fr = Stratégie
				column-name = strategyCode !
				column-type = domain !
				domainAttribute = strategyCode !
				id = strategyCode
				table-column-width = 11
				tid = 27127092578246
			{
				--- TableColumnItem ---
					item-column = strategyCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = validityD !
				column-type = domain !
				domainAttribute = validityD !
				id = validityD
				table-column-width = 11
			{
				--- TableColumnItem ---
					item-column = validityD
					format = datetime.date-only
					previewValue = value
			}
			--- TableColumn ---
				column-name = natureE !
				column-type = domain !
				domainAttribute = natureE !
				id = natureE
				table-column-width = 11
			{
				--- TableColumnItem ---
					item-column = natureE
					previewValue = value
			}
			--- TableColumn ---
				column-name = complianceNatE !
				column-type = domain !
				domainAttribute = complianceNatE !
				id = complianceNatE
				table-column-width = 11
			{
				--- TableColumnItem ---
					item-column = complianceNatE
					previewValue = value
			}
			--- TableColumn ---
				column-name = valueN !
				column-type = domain !
				domainAttribute = valueN !
				id = valueN
				table-column-width = 11
			{
				--- TableColumnItem ---
					item-column = valueN
					format = amount.detailed
					previewValue = value
			}
			--- TableColumn ---
				column-name = currencyCode !
				column-type = domain !
				domainAttribute = currencyCode !
				id = currencyCode
				table-column-width = 11
			{
				--- TableColumnItem ---
					item-column = currencyCode
					previewValue = value
			}
			--- TableColumn ---
				labels de = Kunde
				column-name = thirdPartyCode !
				column-type = domain !
				domainAttribute = thirdPartyCode !
				id = thirdPartyCode
				table-column-width = 11
				tid = 27143004560076
			{
				--- TableColumnItem ---
					item-column = thirdPartyCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = subNatTypeCode !
				column-type = domain !
				domainAttribute = subNatTypeCode !
				id = subNatTypeCode
				table-column-width = 11
			{
				--- TableColumnItem ---
					item-column = subNatTypeCode
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = portfolioCode
				sort-rank = 1
			--- TableSort ---
				sort-column-name = strategyCode
				sort-rank = 2
			--- TableSort ---
				sort-column-name = validityD
				sort-direction = descending
				sort-rank = 3
			--- TableSort ---
				sort-column-name = natureE
				sort-rank = 4
			--- TableSort ---
				sort-column-name = complianceNatE
				sort-rank = 5
		}
	}
}