# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = Queries, de = Abfragen, fr = "Requêtes"
	containment = container
	id = ListQueries_Y__G5
	tid = 102831646860813
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			id = Fv75O
			indexOfSelectedChild = 1
		{
			--- Tab ---
				labels en = "My Queries", de = "Meine Abfragen", fr = "Mes requêtes"
				id = tab_private_query
				isWidgetVisible = false
				tid = 102881695726736
			{
				Event OnClick (setTabActive) Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = changeTab ud
					only-changed = false
					prevalidate = false
					modal = false
					Snippet FilterSet
					id = fs_4dk
					level = 2
					targetDataset = "AAADSList:ListList"
					{
						Snippet Filter
						attribute = userCode
						filterValue = "$CURRENT_USER_CODE"
						operator = EQUAL
					}
				}
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/list/queries/MyQueries.module
			}
			--- Tab ---
				labels en = "Public Queries", de = "Öffentliche Abfragen", fr = "Requêtes publique"
				id = tab_public_query
				isWidgetSelected = true
				tid = 102895652969290
			{
				Event OnClick (setTabActive) Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = changeTab ud
					only-changed = false
					prevalidate = false
					modal = false
					Snippet FilterSet
					id = fs_2YH
					level = 2
					targetDataset = "AAADSList:ListList"
					{
						Snippet Filter
						attribute = userCode
						operator = IS_NULL
					}
				}
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/list/queries/PublicQueries.module
			}
		}
	}
}