# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSList:ListList"
	cssClass = nodeco
	bean-define = DSBean.AAADSList.ListList
	bean-name = ListList
	id = MyQueries_t_7g9
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			id = s36k7
			table-column-count = 5 !
			table-columns-width = "20,20,20,20,20" !
		{
			--- TableColumn ---
				column-name = Delete
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				id = M2p__
				table-column-width = 20
			{
				--- Icon ---
					toolTips en = Delete, fr = Supprimer, de = Löschen
					horizontalAlignment = center
					icon = application_form_delete
					id = m__2b
					tid = 536034299634391
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = delete ud
						id = "<udp:item column=\"id\"/>" ud
						only-changed = false
						prevalidate = false
						modal = false
					}
				}
			}
			--- TableColumn ---
				column-name = name !
				column-type = domain !
				domainAttribute = name !
				type = text
				id = name
				table-column-width = 20
			{
				--- TableColumnItem ---
					item-column = name
					previewValue = value
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = selectQuery ud
						Query.dbId = "<udp:item column=\"id\"/>" ud
						only-changed = false
						prevalidate = false
						modal = false
						stabs = tab_all ud
					}
				}
			}
			--- TableColumn ---
				column-name = denom !
				column-type = domain !
				domainAttribute = denom !
				type = text
				id = denom
				table-column-width = 20
			{
				--- TableColumnItem ---
					item-column = denom
					previewValue = value
			}
			--- TableColumn ---
				column-name = userCode !
				column-type = domain !
				domainAttribute = userCode !
				type = text
				column-visibility = never-visible
				id = userCode
				table-column-width = 20
			{
				--- TableColumnItem ---
					item-column = userCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = id !
				column-type = domain !
				domainAttribute = id !
				type = text
				column-visibility = never-visible
				id = id
				table-column-width = 20
			{
				--- TableColumnItem ---
					item-column = id
					format = integer
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = name
				sort-rank = 1
		}
		--- Button ---
			labels en = Cancel, fr = Annuler, de = Abbrechen
			id = btn_n69v3
			tid = 373319962771022
		{
			Event OnClick (submit) S
			{
				method = post
				call-URI = "<pageflow:continuation/>"
				target = self
				flow-action = cancel ud
				only-changed = false
				prevalidate = false
				modal = false
			}
		}
	}
}