# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Save Query", de = "Anfrage speichern", fr = "Sauver la requête"
	domainEntity = "AAADSList:Query"
	bean-define = DSBean.AAADSList.Query
	bean-name = Query
	id = SaveQuery_e3bo_
	tid = 13132790510590
{
	--- Box ---
		boxType = vertical
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 2
			gridColumnsWidth = "25,75" !
			gridRowCount = 3
		{
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- LabelDomain ---
					domainAttribute = name !
					for = name
					cssClass = grey
					required = true
			}
			--- GridCell ---
				gridColumnWidth = 75
			{
				--- Conditional ---
					indexOfSelectedChild = 1
				{
					--- ConditionalBody ---
						javaCode = "<bean:get-property bean=\"Query\" property=\"id\"/> == null"
						technicalName = Editable
						boxType = vertical
						isWidgetVisible = false
					{
						--- TextField ---
							domainAttribute = name !
							horizontalAlignment = "${corporatehalign}"
							type = text
							chars = 20
							required = true
							bean-property = name
							id = name
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = NoEditable
						boxType = vertical
						isWidgetSelected = true
					{
						--- TextField ---
							domainAttribute = name !
							horizontalAlignment = "${corporatehalign}"
							type = text
							chars = 20
							editable = false
							required = true
							bean-property = name
							id = name
					}
				}
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- LabelDomain ---
					domainAttribute = denom !
					for = denom
					cssClass = grey
			}
			--- GridCell ---
				gridColumnWidth = 75
			{
				--- TextField ---
					domainAttribute = denom !
					columns = 80
					horizontalAlignment = "${corporatehalign}"
					type = text
					chars = 80
					bean-property = denom
					id = denom
			}
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 75
			{
				--- Conditional ---
					indexOfSelectedChild = 1
				{
					--- ConditionalBody ---
						javaCode = "<bean:get-property bean=\"Query\" property=\"id\"/> == null"
						technicalName = Editable
						boxType = vertical
						isWidgetVisible = false
					{
						--- CheckBox ---
							labels de = Öffentlich, fr = Public, en = Public
							domainAttribute = isPublic !
							horizontalAlignment = "${corporatehalign}"
							horizontalTextPosition = trail
							bean-property = isPublic
							id = isPublic
							tid = 23276979855260
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = NoEditable
						boxType = vertical
						isWidgetSelected = true
					{
						--- CheckBox ---
							labels de = Öffentlich, en = Public, fr = Public
							domainAttribute = isPublic !
							horizontalAlignment = "${corporatehalign}"
							horizontalTextPosition = trail
							enabled = false
							bean-property = isPublic
							id = isPublic
							tid = 358246976751462
					}
				}
			}
		}
		--- Box ---
		{
			--- Button ---
				labels en = Save, de = Speichern, fr = Sauver
				id = btn_I1_1q
				tid = 13065575971678
			{
				Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					widget-group-ref = "*"
					target = self
					flow-action = save ud
					only-changed = false
					prevalidate = false
					modal = false
				}
			}
			--- Button ---
				labels en = Cancel, de = Abbrechen, fr = Annuler
				id = btn_X9BGR
				tid = 13071610516199
			{
				Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = cancel ud
					only-changed = false
					prevalidate = false
					modal = false
				}
			}
			--- Glue ---
		}
	}
}