package com.odcgroup.edge.t24.generation.enquiry.model.ecproject.constants.presentation;

import com.odcgroup.edge.t24.generation.enquiry.BasicEnquiryProject;
import com.odcgroup.edge.t24.generation.enquiry.model.Appliable;


/**
 * <code>EnquiryStyleStrings</code> is the central point-of-definition for CSS style strings used to control presentational aspects in the edgeConnect project files generated by
 * {@link BasicEnquiryProject}.<p>
 * 
 * In terms of logical abstraction level, the strings defined here (barely) one level higher up than those defined in {@link EnquiryInlineStyleBlocks}.<p>
 * 
 * For this reason, they are not intended for direct reference in high-level classes such as {@link BasicEnquiryProject}.<p>
 * 
 * Rather, the idea is they are referenced within higher-level type-safe classes/enums (e.g. {@link ResultsTableRowColouringOption}), each representing a configurable presentation
 * attribute and providing "intelligent" constants (e.g. {@link ResultsTableRowColouringOption#HUMBUG_ROW_COLOURING}) that "know" how to {@link Appliable#applyTo(Object) apply}
 * themselves to any target presentation object wrapper of the appropriate type.<p>  
 *
 * @see		EnquiryInlineStyleBlocks
 * @author	Simon Hayes
 */
public interface EnquiryStyleStrings
{
    String COLLAPSIBLE_RESULTS_TABLE_QUESTION = "collapsibleEnqResultsQuestion";
    String COLLAPSIBLE_TABLE = "collapsibleTable";
    
    String DISPLAY_END_RESULTS_AS_MAIN_RESULTS_FOOTER_ROW = "displayEndResultsAsMainResultsFooterRow";
    String GRAPHABLE_AS_BAR = "graphableAsBar";
    
    String HEADER_ENQUIRY_RESULTS_TABLE = "headerEnquiryResultsTable";
    String HEADER_ENQUIRY_RESULTS_TABLE_QUESTION_WITH_LEFT_PADDING = "leftPaddedEnquiryHeaderColumn";
    
    String NAVIGATION_CONTROL_STYLE = "pagination-item";
    String NAVIGATION_ROW_STYLE = "resultTableNavigator";
    
    String NOT_DISPLAYED = "NotDisplayed";
    
    String PRIMPABLE_ENQUIRY_RESULTS_TABLE = "primpableEnqResultsTable";
    String PRIMPABLE_HEADER_RESULTS_TABLE = "primpableHeaderResultsTable";
    
    String QUESTION_ANSWER = "QAns";
    String QUESTION_HELP = "QHelp";
    String QUESTION_MANDATORY = "ErrorColor QMand";
    String QUESTION_POSTFIX = "QPost";
    String QUESTION_PREFIX = "QPref";
    
    String RESULTS_TABLE = "resultTable";
    String RESULTS_TABLE_HEADER = "resultTableHeader";
    String RESULTS_TABLE_ODD_ROWS = "resultTableOddRows";
    String RESULTS_TABLE_QUESTION_ANSWER_CONTROL = "FontDarkGrey";
    String RESULTS_TABLE_QUESTION_COLUMN_HEADING = "FontGrey QQues";
    String RESULTS_TABLE_QUESTION_ROW = "QRow";
    String RESULTS_TABLE_ROW_ROLLOVER = "BgColor5";
    String RESULTS_TABLE_SELECTED_ROW = RESULTS_TABLE_ROW_ROLLOVER;    
}
