package com.odcgroup.edge.t24.generation.enquiry.model.ecproject.constants.presentation;

import com.odcgroup.edge.t24.generation.enquiry.BasicEnquiryProject;

/**
 * The <code>EnquiryInlineStyleBlocks</code> interface is the central point-of-definition for the various inline CSS style blocks used to control presentational aspects in the edgeConnect project files generated by
 * {@link BasicEnquiryProject}.   
 *
 * @author Simon Hayes
 */
public interface EnquiryInlineStyleBlocks
{
	String COLOR_WHITE = "{color: white}";
	String DISPLAY_NONE = "{display: none}";
	String WIDTH_AUTO = "{width: auto}";
}
