package com.odcgroup.edge.t24.generation.enquiry.model.ecproject.constants.presentation;

import gen.com.acquire.intelligentforms.entities.presentation.html.waihtml.richhtml.RichHTMLPresentationTableWrapper;

import com.acquire.util.AssertionUtils;
import com.odcgroup.edge.t24.generation.enquiry.BasicEnquiryProject;

/**
 * <code>ResultsTableRowColouringOption</code> defines constants for the high-level results-table row-colouring schemes that may be applied to an Enquiry results table in the edgeConnect project files
 * generated by {@link BasicEnquiryProject}.<p>
 * 
 * Each such constant "knows" how to {@link #applyTo(RichHTMLPresentationTableWrapper) apply} itself to a supplied {@link RichHTMLPresentationTableWrapper} instance.
 *
 * @author Simon Hayes
 */
public enum ResultsTableRowColouringOption implements TablePresentationOption
{
	HUMBUG_ROW_COLOURING(EnquiryStyleStrings.RESULTS_TABLE_ODD_ROWS, null),
	NO_ROW_COLOURING(null, null),
	SINGLE_BACKGROUND_COLOUR(EnquiryStyleStrings.RESULTS_TABLE_ODD_ROWS, EnquiryStyleStrings.RESULTS_TABLE_ODD_ROWS);
	
	@Override
	public void applyTo(RichHTMLPresentationTableWrapper p_presTable)
	{
		AssertionUtils.requireNonNull(p_presTable, "p_presTable");
		
		p_presTable.setOddRowsStyle(m_oddRowsStyleText);
		p_presTable.setEvenRowsStyle(m_evenRowsStyleText);
	}

	private final String m_oddRowsStyleText;
	private final String m_evenRowsStyleText;

	private ResultsTableRowColouringOption(String p_oddRowsStyleText, String p_evenRowsStyleText)
	{
		m_oddRowsStyleText = p_oddRowsStyleText;
		m_evenRowsStyleText = p_evenRowsStyleText;
	}
}
