# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Sector List", fr = "Liste de secteur", de = "Liste der Branchen"
	domainEntity = "AAADSSector:SectorList"
	bean-define = DSBean.AAADSSector.SectorList
	bean-name = SectorList
	id = SectorList_P6_1_
	tid = 25830093397065
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			id = S_1_t
			table-column-count = 6 !
			table-columns-width = "16,16,16,16,16,16" !
		{
			--- TableColumn ---
				labels de = Kodifizierung
				column-name = codificationCode !
				column-type = domain !
				domainAttribute = codificationCode !
				id = codificationCode
				table-column-width = 16
				tid = 20343689263020
			{
				--- TableColumnItem ---
					item-column = codificationCode
					previewValue = value
			}
			--- TableColumn ---
				labels de = "überg. Branche"
				column-name = parentSectorCode !
				column-type = domain !
				domainAttribute = parentSectorCode !
				id = parentSectorCode
				table-column-width = 16
				tid = 20355961273290
			{
				--- TableColumnItem ---
					item-column = parentSectorCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = parentSectorExtDenomination !
				column-type = domain !
				domainAttribute = parentSectorExtDenomination !
				type = text
				id = parentSectorExtDenomination
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = parentSectorExtDenomination
					previewValue = value
			}
			--- TableColumn ---
				labels de = Code
				column-name = code !
				column-type = domain !
				domainAttribute = code !
				id = code
				table-column-width = 16
				tid = 20360441249656
			{
				--- TableColumnItem ---
					item-column = code
					previewValue = value
			}
			--- TableColumn ---
				column-name = name !
				column-type = domain !
				domainAttribute = name !
				id = name
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = name
					previewValue = value
			}
			--- TableColumn ---
				column-name = extDenomination !
				column-type = domain !
				domainAttribute = extDenomination !
				type = text
				id = extDenomination
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = extDenomination
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = codificationCode
				sort-rank = 1
			--- TableSort ---
				sort-column-name = parentSectorCode
				sort-rank = 2
			--- TableSort ---
				sort-column-name = code
				sort-rank = 3
		}
	}
}