# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Create List", de = "Liste erstellen", fr = "Créer une Liste"
	domainEntity = "AAADSList:ListAll"
	bean-define = DSBean.AAADSList.ListAll
	bean-name = ListAll
	id = ListCreate_AV2__
	tid = 113244872545812
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///default/list/listall/ListIdentifierCreate.fragment
		--- Include ---
			includeSrc = "" !
			resource:///default/list/listall/ListDetailCreate.fragment
	}
}