# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Search Results", de = Suchergebnisse, fr = "Résultats de la recherche"
	domainEntity = "AAADSFunctionResult:FunctionResultList"
	search = output !
	bean-define = DSBean.AAADSFunctionResult.FunctionResultList
	bean-name = FunctionResultList
	id = FunctionResultList_R4371
	tid = 252392336109146
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			id = z1u_4
			table-model-reference = DSTableModel.AAADSFunctionResult.FunctionResultList
			table-column-count = 15 !
			table-columns-width = "6,6,6,6,6,6,6,6,6,6,6,6,6,6,6" !
		{
			--- TableColumn ---
				labels en = View, de = Ansicht, fr = Voir
				column-name = VIEW
				column-type = placeholder !
				type = boolean
				column-locked = true
				column-sortable = false !
				id = j_MPC
				table-column-width = 6
				tid = 354532740499698
			{
				--- Icon ---
					toolTips en = "View Proposal", de = "Vorschlag ansehen", fr = "Voir la proposition"
					horizontalAlignment = center
					icon = application_form_magnify
					id = VAE_y
					tid = 537896687068154
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = viewProposal ud
						Query.propertyValue = "<udp:item column=\"funcResultCode\"/>" ud
						funcResultCode = "<udp:item column=\"funcResultCode\"/>" ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- TableColumn ---
				labels en = Modify, fr = Modifier, de = Aktualisieren
				column-name = updateRightF !
				column-type = domain !
				domainAttribute = updateRightF !
				type = text
				id = updateRightF
				table-column-width = 6
				tid = 24522603107378
			{
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "\"true\".equals(<udp:item column=\"updateRightF\"/>.toString())"
						technicalName = Update_Right
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips en = "Modify Proposal", de = "Vorschlag ändern", fr = "Modifier la proposition"
							horizontalAlignment = center
							icon = application_form_edit
							id = NZ__5
							tid = 459448728259235
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = editProposal ud
								Query.propertyValue = "<udp:item column=\"funcResultCode\"/>" ud
								funcResultCode = "<udp:item column=\"funcResultCode\"/>" ud
								modal = false
								only-changed = false
								prevalidate = false
							}
						}
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetVisible = false
				}
			}
			--- TableColumn ---
				labels en = Copy, de = Kopieren, fr = Copier
				column-name = COPY
				column-type = placeholder !
				type = boolean
				column-locked = true
				column-sortable = false !
				id = DU___
				table-column-width = 6
				tid = 354532741773329
			{
				--- Icon ---
					toolTips en = "Copy Proposal", de = "Vorschlag kopieren", fr = "Copier la proposition"
					horizontalAlignment = center
					icon = application_double
					id = O_5p1
					tid = 459448728586263
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						DSSessionCode = "<udp:item column=\"funcResultCode\"/>" ud
						modal = false
						only-changed = false
						prevalidate = false
						flow-action = copyproposal ud
						funcResultCode = "<udp:item column=\"funcResultCode\"/>" ud
					}
				}
			}
			--- TableColumn ---
				labels en = Report, de = Report, fr = Rapport
				column-name = GenerateReport
				column-type = placeholder !
				type = boolean
				column-locked = true
				column-sortable = false !
				id = OT2_5
				table-column-width = 6
				tid = 200993952988533
			{
				--- Icon ---
					toolTips en = "Generate Report", de = "Report erstellen", fr = "Générer le rapport"
					horizontalAlignment = center
					icon = report
					id = dj2S_
					tid = 200519838827606
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = report ud
						funcResultCode = "<udp:item column=\"funcResultCode\"/>" ud
						origin = search ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- TableColumn ---
				labels en = Delete, fr = Supprimer, de = Löschen
				column-name = deleteRightF !
				column-type = domain !
				domainAttribute = deleteRightF !
				type = text
				id = deleteRightF
				table-column-width = 6
				tid = 24569698935758
			{
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "\"true\".equals(<udp:item column=\"deleteRightF\"/>.toString())"
						technicalName = DELETE_RIGHT
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips en = "Remove Proposal", de = "Vorschlag entfernen", fr = "Supprimer la proposition"
							horizontalAlignment = center
							icon = application_form_delete
							id = kyZ1V
							tid = 200419199924377
						{
							Event OnClick (submit)
							tid = 270861980559819
							messages en = "Do you really want to delete this proposal?", de = "Wollen Sie diesen Vorschlag wirklich löschen?", fr = "Voulez-vous vraiment supprimer la proposition ?"
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								widget-group-ref = form
								target = self
								param = "flow-action=remove"
								only-changed = true
								funcResultCode = "<udp:item column=\"funcResultCode\"/>" ud
								modal = false
								prevalidate = false
								DSSessionCode = "<udp:item column=\"funcResultCode\"/>" ud
							}
						}
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetVisible = false
				}
			}
			--- TableColumn ---
				column-name = funcResultCode !
				column-type = domain !
				domainAttribute = funcResultCode !
				type = text
				column-is-part-of-filter = false
				id = funcResultCode
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = funcResultCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = sessionDescriptionC !
				column-type = domain !
				domainAttribute = sessionDescriptionC !
				type = text
				column-is-part-of-filter = false
				id = sessionDescriptionC
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = sessionDescriptionC
					previewValue = value
			}
			--- TableColumn ---
				column-name = portfolioDimPortfolioCode !
				column-type = domain !
				domainAttribute = portfolioDimPortfolioCode !
				type = text
				id = portfolioDimPortfolioCode
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = portfolioDimPortfolioCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = defaultStrategyCode !
				column-type = domain !
				domainAttribute = defaultStrategyCode !
				type = text
				column-visibility = not-visible
				id = defaultStrategyCode
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = defaultStrategyCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = strategyDimStrategyCode !
				column-type = domain !
				domainAttribute = strategyDimStrategyCode !
				type = text
				column-visibility = not-visible
				id = strategyDimStrategyCode
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = strategyDimStrategyCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = sessionCreationD !
				column-type = domain !
				domainAttribute = sessionCreationD !
				type = text
				id = sessionCreationD
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = sessionCreationD
					format = datetime.date-only
					previewValue = value
			}
			--- TableColumn ---
				column-name = sessionCreationUserCode !
				column-type = domain !
				domainAttribute = sessionCreationUserCode !
				type = text
				id = sessionCreationUserCode
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = sessionCreationUserCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = lastModifD !
				column-type = domain !
				domainAttribute = lastModifD !
				type = text
				id = lastModifD
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = lastModifD
					format = datetime.with-seconds
					previewValue = value
			}
			--- TableColumn ---
				column-name = lastUserCode !
				column-type = domain !
				domainAttribute = lastUserCode !
				type = text
				id = lastUserCode
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = lastUserCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = parentSessionFuncResultCode !
				column-type = domain !
				domainAttribute = parentSessionFuncResultCode !
				type = text
				id = parentSessionFuncResultCode
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = parentSessionFuncResultCode
					previewValue = value
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = viewProposal ud
						Query.propertyValue = "<udp:item column=\"parentSessionFuncResultCode\"/>" ud
						funcResultCode = "<udp:item column=\"parentSessionFuncResultCode\"/>" ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- TableSort ---
				sort-column-name = lastModifD
				sort-direction = descending
				sort-rank = 1
			--- TableExtra ---
				domainAttribute = id
		}
	}
}