# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Search Results", fr = "Résultats de la recherche", de = Suchergebnisse
	domainEntity = "AAADSFunctionResult:FunctionResultList"
	search = output !
	bean-define = DSBean.AAADSFunctionResult.FunctionResultList
	bean-name = FunctionResultList
	id = FunctionResultRejectedList_gQ___
	tid = 3441671786861738
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			id = yHvQ2
			table-model-reference = DSTableModel.AAADSFunctionResult.FunctionResultList
			table-column-count = 12 !
			table-columns-width = "8,8,8,8,8,8,8,8,8,8,8,8" !
		{
			--- TableColumn ---
				labels en = View, fr = Voir, de = Ansehen
				column-name = VIEW
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				id = p_At1
				table-column-width = 8
				tid = 3441671788423947
			{
				--- Icon ---
					toolTips en = "View Session", fr = "Voir la session", de = "Sitzung ansehen"
					horizontalAlignment = center
					icon = application_form_magnify
					id = R669e
					tid = 3441671790361624
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						flow-action = viewSession ud
						Query.propertyValue = "<udp:item column=\"funcResultCode\"/>" ud
						funcResultCode = "<udp:item column=\"funcResultCode\"/>" ud
						modal = false
						only-changed = false
						prevalidate = false
						target = self
					}
				}
			}
			--- TableColumn ---
				labels en = Modify, fr = Modifier, de = Aktualisieren
				column-name = updateRightF !
				column-type = domain !
				domainAttribute = updateRightF !
				type = text
				id = updateRightF
				table-column-width = 8
				tid = 353442284664391
			{
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "\"true\".equals(<udp:item column=\"updateRightF\"/>.toString())"
						technicalName = Condition
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips en = "Modify Session", fr = "Modifier la session", de = "Sitzung aktualisieren"
							horizontalAlignment = center
							icon = application_form_edit
							id = M27_2
							tid = 353494724058504
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								flow-action = updateSession ud
								Query.propertyValue = "<udp:item column=\"funcResultCode\"/>" ud
								funcResultCode = "<udp:item column=\"funcResultCode\"/>" ud
								modal = false
								only-changed = false
								prevalidate = false
								target = self
							}
						}
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetVisible = false
				}
			}
			--- TableColumn ---
				labels en = Delete, fr = Supprimer, de = Löschen
				column-name = deleteRightF !
				column-type = domain !
				domainAttribute = deleteRightF !
				type = text
				id = deleteRightF
				table-column-width = 8
				tid = 267078892065891
			{
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "\"true\".equals(<udp:item column=\"deleteRightF\"/>.toString())"
						technicalName = Condition
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips en = "Delete Session", de = "Sitzung löschen", fr = "Supprimer la session"
							horizontalAlignment = center
							icon = application_form_delete
							id = Sq2G_
							tid = 3441840801095670
						{
							Event OnClick (submit)
							tid = 268583743018365
							messages en = "Are you sure to delete this session ?", de = "Wollen Sie diese Sitzung wirklich löschen?", fr = "Etes-vous sûr de vouloir supprimer cette session?"
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								widget-group-ref = form
								target = self
								param = "flow-action=deletesession"
								funcResultCode = "<udp:item column=\"funcResultCode\"/>" ud
								modal = false
								only-changed = false
								prevalidate = false
							}
						}
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetVisible = false
				}
			}
			--- TableColumn ---
				column-name = sessionDescriptionC !
				column-type = domain !
				domainAttribute = sessionDescriptionC !
				type = text
				id = sessionDescriptionC
				table-column-width = 8
			{
				--- TableColumnItem ---
					item-column = sessionDescriptionC
					previewValue = value
			}
			--- TableColumn ---
				column-name = funcResultCode !
				column-type = domain !
				domainAttribute = funcResultCode !
				type = text
				id = funcResultCode
				table-column-width = 8
			{
				--- TableColumnItem ---
					item-column = funcResultCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = sessionCreationD !
				column-type = domain !
				domainAttribute = sessionCreationD !
				type = text
				id = sessionCreationD
				table-column-width = 8
			{
				--- TableColumnItem ---
					item-column = sessionCreationD
					format = datetime
					previewValue = value
			}
			--- TableColumn ---
				column-name = sessionCreationUserCode !
				column-type = domain !
				domainAttribute = sessionCreationUserCode !
				type = text
				id = sessionCreationUserCode
				table-column-width = 8
			{
				--- TableColumnItem ---
					item-column = sessionCreationUserCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = validationD !
				column-type = domain !
				domainAttribute = validationD !
				type = text
				id = validationD
				table-column-width = 8
			{
				--- TableColumnItem ---
					item-column = validationD
					format = datetime
					previewValue = value
			}
			--- TableColumn ---
				column-name = validationUserCode !
				column-type = domain !
				domainAttribute = validationUserCode !
				type = text
				id = validationUserCode
				table-column-width = 8
			{
				--- TableColumnItem ---
					item-column = validationUserCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = lastModifD !
				column-type = domain !
				domainAttribute = lastModifD !
				type = text
				id = lastModifD
				table-column-width = 8
			{
				--- TableColumnItem ---
					item-column = lastModifD
					format = datetime
					previewValue = value
			}
			--- TableColumn ---
				column-name = lastUserCode !
				column-type = domain !
				domainAttribute = lastUserCode !
				type = text
				id = lastUserCode
				table-column-width = 8
			{
				--- TableColumnItem ---
					item-column = lastUserCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = parentSessionFuncResultCode !
				column-type = domain !
				domainAttribute = parentSessionFuncResultCode !
				type = text
				id = parentSessionFuncResultCode
				table-column-width = 8
			{
				--- TableColumnItem ---
					item-column = parentSessionFuncResultCode
					previewValue = value
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						flow-action = viewProposal ud
						Query.propertyValue = "<udp:item column=\"parentSessionFuncResultCode\"/>" ud
						funcResultCode = "<udp:item column=\"parentSessionFuncResultCode\"/>" ud
						modal = false
						only-changed = false
						prevalidate = false
						target = self
					}
				}
			}
			--- TableSort ---
				sort-column-name = lastModifD
				sort-direction = descending
				sort-rank = 1
			--- TableExtra ---
				domainAttribute = id
		}
	}
}