# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Order Session Search Criteria", fr = "Critères de recherche sur session d\'ordre", de = "Auftragsession Suchbegriffe"
	containment = container
	domainEntity = "AAADSFunctionResult:FunctionResultSearchCriteria"
	search = input !
	bean-define = DSBean.AAADSFunctionResult.FunctionResultSearchCriteria
	bean-name = FunctionResultSearchCriteria
	id = FunctionResultSearchInput_MK60_
	tid = 1254716689101182
{
	--- Box ---
		boxType = vertical
	{
		--- FilterCriteria ---
			includedFile = "resource:/com/module/search/QueryBuilder.xsp"
		--- Include ---
			includeSrc = "" !
			resource:///default/search/NavigationFunctionResultSearch.fragment
	}
}