# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Search Results", fr = "Résultats de la recherche", de = Suchergebnisse
	domainEntity = "AAADSFunctionResult:FunctionResultList"
	search = output !
	bean-define = DSBean.AAADSFunctionResult.FunctionResultList
	bean-name = FunctionResultList
	id = FunctionResultRunningList_thr_7
	tid = 3644150114676865
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			id = Eq0L4
			table-model-reference = DSTableModel.AAADSFunctionResult.FunctionResultList
			table-column-count = 10 !
			table-columns-width = "10,10,10,10,10,10,10,10,10,10" !
		{
			--- TableColumn ---
				labels de = Status
				column-name = sessionStatusE !
				column-type = domain !
				domainAttribute = sessionStatusE !
				type = text
				id = sessionStatusE
				table-column-width = 10
				tid = 17963929868740
			{
				--- TableColumnItem ---
					item-column = sessionStatusE
					previewValue = value
			}
			--- TableColumn ---
				column-name = sessionDescriptionC !
				column-type = domain !
				domainAttribute = sessionDescriptionC !
				type = text
				id = sessionDescriptionC
				table-column-width = 10
			{
				--- TableColumnItem ---
					item-column = sessionDescriptionC
					previewValue = value
			}
			--- TableColumn ---
				column-name = funcResultCode !
				column-type = domain !
				domainAttribute = funcResultCode !
				type = text
				id = funcResultCode
				table-column-width = 10
			{
				--- TableColumnItem ---
					item-column = funcResultCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = sessionCreationD !
				column-type = domain !
				domainAttribute = sessionCreationD !
				type = text
				id = sessionCreationD
				table-column-width = 10
			{
				--- TableColumnItem ---
					item-column = sessionCreationD
					format = datetime
					previewValue = value
			}
			--- TableColumn ---
				column-name = sessionCreationUserCode !
				column-type = domain !
				domainAttribute = sessionCreationUserCode !
				type = text
				id = sessionCreationUserCode
				table-column-width = 10
			{
				--- TableColumnItem ---
					item-column = sessionCreationUserCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = validationD !
				column-type = domain !
				domainAttribute = validationD !
				type = text
				id = validationD
				table-column-width = 10
			{
				--- TableColumnItem ---
					item-column = validationD
					format = datetime
					previewValue = value
			}
			--- TableColumn ---
				column-name = validationUserCode !
				column-type = domain !
				domainAttribute = validationUserCode !
				type = text
				id = validationUserCode
				table-column-width = 10
			{
				--- TableColumnItem ---
					item-column = validationUserCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = lastModifD !
				column-type = domain !
				domainAttribute = lastModifD !
				type = text
				id = lastModifD
				table-column-width = 10
			{
				--- TableColumnItem ---
					item-column = lastModifD
					format = datetime
					previewValue = value
			}
			--- TableColumn ---
				column-name = lastUserCode !
				column-type = domain !
				domainAttribute = lastUserCode !
				type = text
				id = lastUserCode
				table-column-width = 10
			{
				--- TableColumnItem ---
					item-column = lastUserCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = parentSessionFuncResultCode !
				column-type = domain !
				domainAttribute = parentSessionFuncResultCode !
				type = text
				id = parentSessionFuncResultCode
				table-column-width = 10
			{
				--- TableColumnItem ---
					item-column = parentSessionFuncResultCode
					previewValue = value
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						flow-action = viewProposal ud
						Query.propertyValue = "<udp:item column=\"parentSessionFuncResultCode\"/>" ud
						funcResultCode = "<udp:item column=\"parentSessionFuncResultCode\"/>" ud
						modal = false
						only-changed = false
						prevalidate = false
						target = self
					}
				}
			}
			--- TableSort ---
				sort-column-name = lastModifD
				sort-direction = descending
				sort-rank = 1
			--- TableExtra ---
				domainAttribute = id
		}
	}
}