# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Search Investment Proposal", de = "Anlagevorschlag Suche", fr = "Recherche de proposition d\'investissement"
	containment = container
	search = container !
	cssClass = nodeco
	id = FunctionResultSearch_s22zq
	tid = 251387813038294
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TabbedPane ---
			id = y__8Y
			indexOfSelectedChild = 5
		{
			--- Tab ---
				labels en = All, de = Alle, fr = Tous
				tab-name = All
				boxType = vertical
				id = tab_all
				isWidgetVisible = false
				tid = 21205002280890
			{
				Event OnClick (setTabActive) Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = changeTab ud
					Query.fs_Oyo.cancel = false ud
					modal = false
					only-changed = false
					prevalidate = false
					Snippet Query
					queryAttributes = "containsInstr,sessionDescriptionC,strategyDimStrategySearchName,funcResultCode,portfolioDimPortfolioSearchCode,defaultStrategySearchName,sessionCreationD,parentSessionFuncResultCode,sessionCreationUserSearchCode,lastUserSearchCode,lastModifD"
					queryOutputModule = "" !
					resource:///Default/module/aaa/administration/functionresult/FunctionResultPGSearch.module
					Snippet FilterSet
					id = fs_Oyo
					level = 2
					targetDataset = "AAADSFunctionResult:FunctionResultPGSearchCriteria"
					{
						Snippet Filter
						attribute = sessionStatusE
						filterValue = "Validated,Working,SentForValidation,Rejected,ReleasedForTrading"
						operator = IN
						Snippet Filter
						attribute = sessionNatureE
						filterValue = InvestmentProposal
						operator = EQUAL
					}
				}
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/functionresult/FunctionResultPGSearchInput.module
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/functionresult/FunctionResultPGAllList.module
			}
			--- Tab ---
				labels en = Working, de = "In Bearbeitung", fr = "En cours"
				tab-name = Working
				boxType = vertical
				id = tab_working
				isWidgetVisible = false
				tid = 251387813833324
			{
				Event OnClick (setTabActive) Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = changeTab ud
					Query.fs_66j.cancel = false ud
					modal = false
					only-changed = false
					prevalidate = false
					Snippet Query
					queryAttributes = "sessionDescriptionC,containsInstr,strategyDimStrategySearchName,funcResultCode,portfolioDimPortfolioSearchCode,defaultStrategySearchName,sessionCreationD,sessionCreationUserSearchCode,lastUserSearchCode,parentSessionFuncResultCode,lastModifD"
					queryOutputModule = "" !
					resource:///Default/module/aaa/administration/functionresult/FunctionResultPGSearch.module
					Snippet FilterSet
					id = fs_66j
					level = 2
					targetDataset = "AAADSFunctionResult:FunctionResultPGSearchCriteria"
					{
						Snippet Filter
						attribute = sessionStatusE
						filterValue = Working
						operator = EQUAL
					}
				}
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/functionresult/FunctionResultPGSearchInput.module
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/functionresult/FunctionResultPGDraftList.module
			}
			--- Tab ---
				labels en = "Sent for Validation", de = "zum Validieren", fr = "Envoyé pour validation"
				tab-name = SentToClient
				boxType = vertical
				id = tab_sent_to_client
				isWidgetVisible = false
				tid = 625802690803317
			{
				Event OnClick (setTabActive) Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = changeTab ud
					Query.fs_7WV.cancel = false ud
					modal = false
					only-changed = false
					prevalidate = false
					Snippet Query
					queryAttributes = "sessionDescriptionC,funcResultCode,portfolioDimPortfolioSearchCode,sessionCreationUserSearchCode,lastModifD,containsInstr,strategyDimStrategySearchName,defaultStrategySearchName,sessionCreationD,parentSessionFuncResultCode,lastUserSearchCode"
					queryOutputModule = "" !
					resource:///Default/module/aaa/administration/functionresult/FunctionResultPGSearch.module
					Snippet FilterSet
					id = fs_7WV
					level = 2
					targetDataset = "AAADSFunctionResult:FunctionResultPGSearchCriteria"
					{
						Snippet Filter
						attribute = sessionStatusE
						filterValue = SentForValidation
						operator = EQUAL
					}
				}
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/functionresult/FunctionResultPGSearchInput.module
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/functionresult/FunctionResultPGSentToClientList.module
			}
			--- Tab ---
				labels en = Validated, de = Überprüft, fr = Validé
				tab-name = ValidatedByClient
				boxType = vertical
				id = tab_validate_by_client
				isWidgetVisible = false
				tid = 251387814394097
			{
				Event OnClick (setTabActive) Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = changeTab ud
					Query.fs_Dsy.cancel = false ud
					modal = false
					only-changed = false
					prevalidate = false
					Snippet Query
					queryAttributes = "sessionDescriptionC,funcResultCode,portfolioDimPortfolioSearchCode,sessionCreationUserSearchCode,lastModifD,containsInstr,strategyDimStrategySearchName,defaultStrategySearchName,sessionCreationD,parentSessionFuncResultCode,lastUserSearchCode"
					queryOutputModule = "" !
					resource:///Default/module/aaa/administration/functionresult/FunctionResultPGSearch.module
					Snippet FilterSet
					id = fs_Dsy
					level = 2
					targetDataset = "AAADSFunctionResult:FunctionResultPGSearchCriteria"
					{
						Snippet Filter
						attribute = sessionStatusE
						filterValue = Validated
						operator = EQUAL
					}
				}
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/functionresult/FunctionResultPGSearchInput.module
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/functionresult/FunctionResultPGValidatedByClientList.module
			}
			--- Tab ---
				labels en = Rejected, de = Abgelehnt, fr = Rejeté
				tab-name = RejectedByClient
				boxType = vertical
				id = tab_rejected_by_client
				isWidgetVisible = false
				tid = 251387814956785
			{
				Event OnClick (setTabActive) Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = changeTab ud
					Query.fs_7O8.cancel = false ud
					modal = false
					only-changed = false
					prevalidate = false
					Snippet Query
					queryAttributes = "sessionDescriptionC,funcResultCode,portfolioDimPortfolioSearchCode,sessionCreationUserSearchCode,lastModifD,containsInstr,strategyDimStrategySearchName,defaultStrategySearchName,sessionCreationD,parentSessionFuncResultCode,lastUserSearchCode"
					queryOutputModule = "" !
					resource:///Default/module/aaa/administration/functionresult/FunctionResultPGSearch.module
					Snippet FilterSet
					id = fs_7O8
					level = 2
					targetDataset = "AAADSFunctionResult:FunctionResultPGSearchCriteria"
					{
						Snippet Filter
						attribute = sessionStatusE
						filterValue = Rejected
						operator = EQUAL
					}
				}
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/functionresult/FunctionResultPGSearchInput.module
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/functionresult/FunctionResultPGRejectedByClientList.module
			}
			--- Tab ---
				labels en = "Released for trading", de = Handelsfreigabe, fr = "Envoyé vers le marché"
				tab-name = SentForTrading
				boxType = vertical
				id = tab_trading
				isWidgetSelected = true
				tid = 251387815241185
			{
				Event OnClick (setTabActive) Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = changeTab ud
					Query.fs_781.cancel = false ud
					modal = false
					only-changed = false
					prevalidate = false
					Snippet Query
					queryAttributes = "sessionDescriptionC,funcResultCode,portfolioDimPortfolioSearchCode,sessionCreationUserSearchCode,lastModifD,containsInstr,strategyDimStrategySearchName,defaultStrategySearchName,sessionCreationD,parentSessionFuncResultCode,lastUserSearchCode"
					queryOutputModule = "" !
					resource:///Default/module/aaa/administration/functionresult/FunctionResultPGSearch.module
					Snippet FilterSet
					id = fs_781
					level = 2
					targetDataset = "AAADSFunctionResult:FunctionResultPGSearchCriteria"
					{
						Snippet Filter
						attribute = sessionStatusE
						filterValue = ReleasedForTrading
						operator = EQUAL
					}
				}
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/functionresult/FunctionResultPGSearchInput.module
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/functionresult/FunctionResultPGReleasedForTradingList.module
			}
		}
	}
}