# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Search Order Session", fr = "Recherche de session d\'ordre", de = "Auftragsession Suche"
	containment = container
	search = container !
	cssClass = nodeco
	id = FunctionResultSearch_s22zq
	tid = 26758025401831
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TabbedPane ---
			id = y__8Y
			indexOfSelectedChild = 8
		{
			--- Tab ---
				labels en = All, fr = Tous, de = Alle
				tab-name = All
				boxType = vertical
				id = tab_all
				isWidgetVisible = false
				tid = 376251724727863
			{
				Event OnClick (setTabActive) Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = changeTab ud
					modal = false
					only-changed = false
					prevalidate = false
					Snippet Query
					queryAttributes = "sessionDescriptionC,sessionNatureE,funcResultCode,sessionStatusE,validationD,sessionCreationD,initialFunctionName,lastUserSearchCode,parentSessionFuncResultCode,sessionCreationUserSearchCode,lastModifD,validationUserSearchCode"
					queryOutputModule = "" !
					resource:///Default/module/aaa/administration/functionresult/FunctionResultSearch.module
					Snippet FilterSet
					id = fs_15e
					cancel = false
					level = 2
					targetDataset = "AAADSFunctionResult:FunctionResultSearchCriteria"
					{
						Snippet Filter
						attribute = sessionStatusE
						filterValue = None
						operator = DIFFERENT
					}
					Snippet FilterSet
					id = fs_t0i
					level = 4
					targetDataset = "AAADSFunctionResult:FunctionResultSearchCriteria"
					{
						Snippet Filter
						attribute = sessionCreationUserSearchCode
						editMode = editable
						filterValue = "$CURRENT_USER_CODE"
						operator = EQUAL
					}
				}
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/functionresult/FunctionResultSearchInput.module
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/functionresult/FunctionResultAllList.module
			}
			--- Tab ---
				labels en = Working, de = "In Bearbeitung", fr = "En cours"
				tab-name = Working
				boxType = vertical
				id = tab_draft
				isWidgetVisible = false
				tid = 387320342453580
			{
				Event OnClick (setTabActive) Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = changeTab ud
					modal = false
					only-changed = false
					prevalidate = false
					Query.fs_15e.cancel = false ud
					Snippet Query
					queryAttributes = "sessionDescriptionC,sessionNatureE,funcResultCode,sessionStatusE,validationD,sessionCreationD,sessionCreationUserSearchCode,parentSessionFuncResultCode,lastUserSearchCode,initialFunctionName,validationUserSearchCode,lastModifD"
					queryOutputModule = "" !
					resource:///Default/module/aaa/administration/functionresult/FunctionResultSearch.module
					Snippet FilterSet
					id = fs_15e
					cancel = false
					level = 2
					targetDataset = "AAADSFunctionResult:FunctionResultSearchCriteria"
					{
						Snippet Filter
						attribute = sessionStatusE
						filterValue = Working
						operator = EQUAL
					}
					Snippet FilterSet
					id = fs_dL8
					level = 4
					targetDataset = "AAADSFunctionResult:FunctionResultSearchCriteria"
					{
						Snippet Filter
						attribute = sessionCreationUserSearchCode
						editMode = editable
						filterValue = "$CURRENT_USER_CODE"
						operator = EQUAL
					}
				}
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/functionresult/FunctionResultSearchInput.module
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/functionresult/FunctionResultDraftList.module
			}
			--- Tab ---
				labels en = Checked, de = Geprüft, fr = Vérifié
				tab-name = Checked
				boxType = vertical
				id = tab_checked
				isWidgetVisible = false
				tid = 387372013164242
			{
				Event OnClick (setTabActive) Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = changeTab ud
					modal = false
					only-changed = false
					prevalidate = false
					Snippet Query
					queryAttributes = "sessionDescriptionC,sessionNatureE,funcResultCode,sessionStatusE,validationD,sessionCreationD,sessionCreationUserSearchCode,parentSessionFuncResultCode,lastUserSearchCode,initialFunctionName,validationUserSearchCode,lastModifD"
					queryOutputModule = "" !
					resource:///Default/module/aaa/administration/functionresult/FunctionResultSearch.module
					Snippet FilterSet
					id = fs_3Br
					cancel = false
					level = 2
					targetDataset = "AAADSFunctionResult:FunctionResultSearchCriteria"
					{
						Snippet Filter
						attribute = sessionStatusE
						filterValue = Checked
						operator = EQUAL
					}
					Snippet FilterSet
					id = fs_LSV
					level = 4
					targetDataset = "AAADSFunctionResult:FunctionResultSearchCriteria"
					{
						Snippet Filter
						attribute = sessionCreationUserSearchCode
						editMode = editable
						filterValue = "$CURRENT_USER_CODE"
						operator = EQUAL
					}
				}
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/functionresult/FunctionResultSearchInput.module
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/functionresult/FunctionResultDraftList.module
			}
			--- Tab ---
				labels en = "Sent for Validation", de = "Zur Bestätigung gesendet", fr = "Envoyé pour validation"
				tab-name = SentForValidation
				boxType = vertical
				id = tab_to_validate_mine
				isWidgetVisible = false
				tid = 137070614616382
			{
				Event OnClick (setTabActive) Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = changeTab ud
					modal = false
					only-changed = false
					prevalidate = false
					Snippet Query
					queryAttributes = "sessionDescriptionC,sessionNatureE,funcResultCode,sessionStatusE,validationD,sessionCreationD,initialFunctionName,lastUserSearchCode,parentSessionFuncResultCode,sessionCreationUserSearchCode,lastModifD,validationUserSearchCode"
					queryOutputModule = "" !
					resource:///Default/module/aaa/administration/functionresult/FunctionResultSearch.module
					Snippet FilterSet
					id = fs_3Br
					cancel = false
					level = 2
					targetDataset = "AAADSFunctionResult:FunctionResultSearchCriteria"
					{
						Snippet Filter
						attribute = sessionStatusE
						filterValue = SentForValidation
						operator = EQUAL
					}
					Snippet FilterSet
					id = fs_K7U
					level = 4
					targetDataset = "AAADSFunctionResult:FunctionResultSearchCriteria"
					{
						Snippet Filter
						attribute = sessionCreationUserSearchCode
						editMode = editable
						filterValue = "$CURRENT_USER_CODE"
						operator = EQUAL
					}
				}
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/functionresult/FunctionResultSearchInput.module
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/functionresult/FunctionResultList.module
			}
			--- Tab ---
				labels en = "To validate (others)", de = "Zu bestätigen (andere)", fr = "A valider (autres)"
				tab-name = "To validate other"
				boxType = vertical
				id = tab_to_validate_other
				isWidgetVisible = false
				tid = 137269509471175
			{
				Event OnClick (setTabActive) Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = changeTab ud
					modal = false
					only-changed = false
					prevalidate = false
					Snippet Query
					queryAttributes = "sessionDescriptionC,sessionNatureE,funcResultCode,sessionStatusE,validationD,sessionCreationD,sessionCreationUserSearchCode,parentSessionFuncResultCode,lastUserSearchCode,initialFunctionName,validationUserSearchCode,lastModifD"
					queryOutputModule = "" !
					resource:///Default/module/aaa/administration/functionresult/FunctionResultSearch.module
					Snippet FilterSet
					id = fs_3Br
					cancel = false
					level = 2
					targetDataset = "AAADSFunctionResult:FunctionResultSearchCriteria"
					{
						Snippet Filter
						attribute = sessionStatusE
						filterValue = SentForValidation
						operator = EQUAL
					}
					Snippet FilterSet
					id = fs_3HZ
					level = 4
					targetDataset = "AAADSFunctionResult:FunctionResultSearchCriteria"
					{
						Snippet Filter
						attribute = lastUserSearchCode
						editMode = editable
						filterValue = "$CURRENT_USER_CODE"
						operator = DIFFERENT
					}
				}
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/functionresult/FunctionResultSearchInput.module
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/functionresult/FunctionResultSentForValidationtList.module
			}
			--- Tab ---
				labels en = Rejected, de = Abgelehnt, fr = Rejeté
				tab-name = Rejected
				boxType = vertical
				id = tab_rejected
				isWidgetVisible = false
				tid = 137097214305170
			{
				Event OnClick (setTabActive) Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = changeTab ud
					modal = false
					only-changed = false
					prevalidate = false
					Snippet Query
					queryAttributes = "sessionDescriptionC,sessionNatureE,funcResultCode,sessionStatusE,validationD,sessionCreationD,sessionCreationUserSearchCode,parentSessionFuncResultCode,lastUserSearchCode,initialFunctionName,validationUserSearchCode,lastModifD"
					queryOutputModule = "" !
					resource:///Default/module/aaa/administration/functionresult/FunctionResultSearch.module
					Snippet FilterSet
					id = fs_3Br
					cancel = false
					level = 2
					targetDataset = "AAADSFunctionResult:FunctionResultSearchCriteria"
					{
						Snippet Filter
						attribute = sessionStatusE
						filterValue = Rejected
						operator = EQUAL
					}
					Snippet FilterSet
					id = fs_8Dt
					level = 4
					targetDataset = "AAADSFunctionResult:FunctionResultSearchCriteria"
					{
						Snippet Filter
						attribute = sessionCreationUserSearchCode
						editMode = editable
						filterValue = "$CURRENT_USER_CODE"
						operator = EQUAL
					}
				}
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/functionresult/FunctionResultSearchInput.module
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/functionresult/FunctionResultRejectedList.module
			}
			--- Tab ---
				labels en = "Released for Trading", de = "Zum Handel freigegeben", fr = "Envoyée pour exécution"
				tab-name = ReleasedForTrading
				boxType = vertical
				id = tab_final
				isWidgetVisible = false
				tid = 547631328706516
			{
				Event OnClick (setTabActive) Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = changeTab ud
					modal = false
					only-changed = false
					prevalidate = false
					Snippet Query
					queryAttributes = "sessionDescriptionC,sessionNatureE,funcResultCode,sessionStatusE,validationD,sessionCreationD,sessionCreationUserSearchCode,parentSessionFuncResultCode,lastUserSearchCode,initialFunctionName,validationUserSearchCode,lastModifD"
					queryOutputModule = "" !
					resource:///Default/module/aaa/administration/functionresult/FunctionResultSearch.module
					Snippet FilterSet
					id = fs_3Br
					cancel = false
					level = 2
					targetDataset = "AAADSFunctionResult:FunctionResultSearchCriteria"
					{
						Snippet Filter
						attribute = sessionStatusE
						filterValue = ReleasedForTrading
						operator = EQUAL
					}
					Snippet FilterSet
					id = fs_KP6
					level = 4
					targetDataset = "AAADSFunctionResult:FunctionResultSearchCriteria"
					{
						Snippet Filter
						attribute = sessionCreationUserSearchCode
						editMode = editable
						filterValue = "$CURRENT_USER_CODE"
						operator = EQUAL
					}
				}
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/functionresult/FunctionResultSearchInput.module
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/functionresult/FunctionResultList.module
			}
			--- Tab ---
				labels en = "Processes Running", de = "Verarbeitung läuft", fr = "Traitements en cours d\'exécution"
				tab-name = ProcessesRunning
				boxType = vertical
				id = tab_F__07
				isWidgetVisible = false
				tid = 3378815482040036
			{
				Event OnClick (setTabActive) Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = changeTab ud
					modal = false
					only-changed = false
					prevalidate = false
					Query.fs_15e.cancel = false ud
					Snippet Query
					queryAttributes = "sessionDescriptionC,sessionNatureE,funcResultCode,sessionStatusE,validationD,sessionCreationD,sessionCreationUserSearchCode,parentSessionFuncResultCode,lastUserSearchCode,initialFunctionName,validationUserSearchCode,lastModifD"
					queryOutputModule = "" !
					resource:///Default/module/aaa/administration/functionresult/FunctionResultSearch.module
					Snippet FilterSet
					id = fs_15e
					cancel = false
					level = 2
					targetDataset = "AAADSFunctionResult:FunctionResultSearchCriteria"
					{
						Snippet Filter
						attribute = sessionStatusE
						filterValue = "GenerationRunning,ReleasedForTradingRunning,CheckRunning"
						operator = IN
					}
					Snippet FilterSet
					id = fs_0lr
					level = 4
					targetDataset = "AAADSFunctionResult:FunctionResultSearchCriteria"
					{
						Snippet Filter
						attribute = sessionCreationUserSearchCode
						editMode = editable
						filterValue = "$CURRENT_USER_CODE"
						operator = EQUAL
					}
				}
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/functionresult/FunctionResultSearchInput.module
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/functionresult/FunctionResultRunningList.module
			}
			--- Tab ---
				labels en = "Processes Failed", de = "Verarbeitung fehlgeschlagen", fr = "Traitements ayant échoués"
				tab-name = ProcessesFailed
				boxType = vertical
				id = tab_m_7Tp
				isWidgetSelected = true
				tid = 3378964312434401
			{
				Event OnClick (setTabActive) Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = changeTab ud
					modal = false
					only-changed = false
					prevalidate = false
					Query.fs_15e.cancel = false ud
					Snippet Query
					queryAttributes = "sessionDescriptionC,sessionNatureE,funcResultCode,sessionStatusE,validationD,sessionCreationD,sessionCreationUserSearchCode,parentSessionFuncResultCode,lastUserSearchCode,initialFunctionName,validationUserSearchCode,lastModifD"
					queryOutputModule = "" !
					resource:///Default/module/aaa/administration/functionresult/FunctionResultSearch.module
					Snippet FilterSet
					id = fs_15e
					cancel = false
					level = 2
					targetDataset = "AAADSFunctionResult:FunctionResultSearchCriteria"
					{
						Snippet Filter
						attribute = sessionStatusE
						filterValue = "CheckFailed,GenerationFailed,ReleasedForTradingFailed"
						operator = IN
					}
					Snippet FilterSet
					id = fs_Ilz
					level = 4
					targetDataset = "AAADSFunctionResult:FunctionResultSearchCriteria"
					{
						Snippet Filter
						attribute = sessionCreationUserSearchCode
						editMode = editable
						filterValue = "$CURRENT_USER_CODE"
						operator = EQUAL
					}
				}
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/functionresult/FunctionResultSearchInput.module
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/functionresult/FunctionResultRunningList.module
			}
		}
	}
}