# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Search Results", fr = "Résultats de la recherche", de = Suchergebnisse
	domainEntity = "AAADSFunctionResult:FunctionResultList"
	search = output !
	bean-define = DSBean.AAADSFunctionResult.FunctionResultList
	bean-name = FunctionResultList
	id = FunctionResultList_R4371
	tid = 194923636163581
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			id = z1u_4
			table-model-reference = DSTableModel.AAADSFunctionResult.FunctionResultList
			table-column-count = 13 !
			table-columns-width = "7,7,7,7,7,7,7,7,7,7,7,7,7" !
		{
			--- TableColumn ---
				labels en = View, de = Ansicht, fr = Voir
				column-name = VIEW
				column-type = placeholder !
				type = boolean
				column-locked = true
				column-sortable = false !
				id = d5iw3
				table-column-width = 7
				tid = 356044039660226
			{
				--- Icon ---
					toolTips en = "View Proposal", de = "Vorschlag ansehen", fr = "Voir la proposition"
					horizontalAlignment = center
					icon = application_form_magnify
					id = e5b4_
					tid = 4637223262769
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = viewProposal ud
						Query.propertyValue = "<udp:item column=\"funcResultCode\"/>" ud
						funcResultCode = "<udp:item column=\"funcResultCode\"/>" ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- TableColumn ---
				labels en = Copy, de = Kopieren, fr = Copier
				column-name = COPY
				column-type = placeholder !
				type = boolean
				column-locked = true
				column-sortable = false !
				id = I518V
				table-column-width = 7
				tid = 356044040234567
			{
				--- Icon ---
					toolTips en = "Copy Proposal", de = "Vorschlag kopieren", fr = "Copier la proposition"
					horizontalAlignment = center
					icon = application_double
					id = b___7
					tid = 4735205311058
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						DSSessionCode = "<udp:item column=\"funcResultCode\"/>" ud
						modal = false
						only-changed = false
						prevalidate = false
						flow-action = copyproposal ud
						funcResultCode = "<udp:item column=\"funcResultCode\"/>" ud
					}
				}
			}
			--- TableColumn ---
				column-name = funcResultCode !
				column-type = domain !
				domainAttribute = funcResultCode !
				type = text
				column-is-part-of-filter = false
				id = funcResultCode
				table-column-width = 7
			{
				--- TableColumnItem ---
					item-column = funcResultCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = sessionDescriptionC !
				column-type = domain !
				domainAttribute = sessionDescriptionC !
				type = text
				column-is-part-of-filter = false
				id = sessionDescriptionC
				table-column-width = 7
			{
				--- TableColumnItem ---
					item-column = sessionDescriptionC
					previewValue = value
			}
			--- TableColumn ---
				column-name = portfolioDimPortfolioCode !
				column-type = domain !
				domainAttribute = portfolioDimPortfolioCode !
				type = text
				id = portfolioDimPortfolioCode
				table-column-width = 7
			{
				--- TableColumnItem ---
					item-column = portfolioDimPortfolioCode
					previewValue = value
			}
			--- TableColumn ---
				labels de = Status
				column-name = sessionStatusE !
				column-type = domain !
				domainAttribute = sessionStatusE !
				type = text
				id = sessionStatusE
				table-column-width = 7
				tid = 17901634123331
			{
				--- TableColumnItem ---
					item-column = sessionStatusE
					previewValue = value
			}
			--- TableColumn ---
				column-name = defaultStrategyCode !
				column-type = domain !
				domainAttribute = defaultStrategyCode !
				type = text
				column-visibility = not-visible
				id = defaultStrategyCode
				table-column-width = 7
			{
				--- TableColumnItem ---
					item-column = defaultStrategyCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = strategyDimStrategyCode !
				column-type = domain !
				domainAttribute = strategyDimStrategyCode !
				type = text
				column-visibility = not-visible
				id = strategyDimStrategyCode
				table-column-width = 7
			{
				--- TableColumnItem ---
					item-column = strategyDimStrategyCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = sessionCreationD !
				column-type = domain !
				domainAttribute = sessionCreationD !
				type = text
				id = sessionCreationD
				table-column-width = 7
			{
				--- TableColumnItem ---
					item-column = sessionCreationD
					format = datetime.date-only
					previewValue = value
			}
			--- TableColumn ---
				column-name = sessionCreationUserCode !
				column-type = domain !
				domainAttribute = sessionCreationUserCode !
				type = text
				id = sessionCreationUserCode
				table-column-width = 7
			{
				--- TableColumnItem ---
					item-column = sessionCreationUserCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = lastModifD !
				column-type = domain !
				domainAttribute = lastModifD !
				type = text
				id = lastModifD
				table-column-width = 7
			{
				--- TableColumnItem ---
					item-column = lastModifD
					format = datetime.with-seconds
					previewValue = value
			}
			--- TableColumn ---
				column-name = lastUserCode !
				column-type = domain !
				domainAttribute = lastUserCode !
				type = text
				id = lastUserCode
				table-column-width = 7
			{
				--- TableColumnItem ---
					item-column = lastUserCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = parentSessionFuncResultCode !
				column-type = domain !
				domainAttribute = parentSessionFuncResultCode !
				type = text
				id = parentSessionFuncResultCode
				table-column-width = 7
			{
				--- TableColumnItem ---
					item-column = parentSessionFuncResultCode
					previewValue = value
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = viewProposal ud
						Query.propertyValue = "<udp:item column=\"parentSessionFuncResultCode\"/>" ud
						funcResultCode = "<udp:item column=\"parentSessionFuncResultCode\"/>" ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- TableSort ---
				sort-column-name = lastModifD
				sort-direction = descending
				sort-rank = 1
			--- TableExtra ---
				domainAttribute = id
		}
	}
}