# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Search Results", fr = "Résultats de la recherche", de = Suchergebnisse
	domainEntity = "AAADSFunctionResult:FunctionResultList"
	search = output !
	bean-define = DSBean.AAADSFunctionResult.FunctionResultList
	bean-name = FunctionResultList
	id = FunctionResultList_R4371
	tid = 376685192809700
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			id = z1u_4
			table-model-reference = DSTableModel.AAADSFunctionResult.FunctionResultList
			table-column-count = 11 !
			table-columns-width = "9,9,9,9,9,9,9,9,9,9,9" !
		{
			--- TableColumn ---
				labels en = View, fr = Voir, de = Ansehen
				column-name = VIEW
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				id = d1___
				table-column-width = 9
				tid = 3440134684499566
			{
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "null!=<udp:item column=\"sessionStatusE\"/>\r\n&amp;&amp;!Integer.toString(com.odcgroup.aaa.DomainAAASessionStatusE.GenerationRunning).equals(<udp:item column=\"sessionStatusE\"/>.toString())\r\n&amp;&amp;!Integer.toString(com.odcgroup.aaa.DomainAAASessionStatusE.GenerationFailed).equals(<udp:item column=\"sessionStatusE\"/>.toString())\r\n&amp;&amp;!Integer.toString(com.odcgroup.aaa.DomainAAASessionStatusE.CheckRunning).equals(<udp:item column=\"sessionStatusE\"/>.toString())\r\n&amp;&amp;!Integer.toString(com.odcgroup.aaa.DomainAAASessionStatusE.CheckFailed).equals(<udp:item column=\"sessionStatusE\"/>.toString())\r\n&amp;&amp;!Integer.toString(com.odcgroup.aaa.DomainAAASessionStatusE.ReleasedForTradingRunning).equals(<udp:item column=\"sessionStatusE\"/>.toString())\r\n&amp;&amp;!Integer.toString(com.odcgroup.aaa.DomainAAASessionStatusE.ReleasedForTradingFailed).equals(<udp:item column=\"sessionStatusE\"/>.toString())"
						technicalName = Displayed
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips en = "View Session", fr = "Voir la session", de = "Sitzung ansehen"
							horizontalAlignment = center
							icon = application_form_magnify
							id = v9r_7
							tid = 429502084970855
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								flow-action = viewSession ud
								Query.propertyValue = "<udp:item column=\"funcResultCode\"/>" ud
								funcResultCode = "<udp:item column=\"funcResultCode\"/>" ud
								modal = false
								only-changed = false
								prevalidate = false
								target = self
							}
						}
					}
				}
			}
			--- TableColumn ---
				column-name = sessionStatusE !
				column-type = domain !
				domainAttribute = sessionStatusE !
				type = text
				id = sessionStatusE
				table-column-width = 9
			{
				--- TableColumnItem ---
					item-column = sessionStatusE
					previewValue = value
			}
			--- TableColumn ---
				column-name = sessionDescriptionC !
				column-type = domain !
				domainAttribute = sessionDescriptionC !
				type = text
				id = sessionDescriptionC
				table-column-width = 9
			{
				--- TableColumnItem ---
					item-column = sessionDescriptionC
					previewValue = value
			}
			--- TableColumn ---
				column-name = funcResultCode !
				column-type = domain !
				domainAttribute = funcResultCode !
				type = text
				id = funcResultCode
				table-column-width = 9
			{
				--- TableColumnItem ---
					item-column = funcResultCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = sessionCreationD !
				column-type = domain !
				domainAttribute = sessionCreationD !
				type = text
				id = sessionCreationD
				table-column-width = 9
			{
				--- TableColumnItem ---
					item-column = sessionCreationD
					format = datetime
					previewValue = value
			}
			--- TableColumn ---
				column-name = sessionCreationUserCode !
				column-type = domain !
				domainAttribute = sessionCreationUserCode !
				type = text
				id = sessionCreationUserCode
				table-column-width = 9
			{
				--- TableColumnItem ---
					item-column = sessionCreationUserCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = validationD !
				column-type = domain !
				domainAttribute = validationD !
				type = text
				id = validationD
				table-column-width = 9
			{
				--- TableColumnItem ---
					item-column = validationD
					format = datetime
					previewValue = value
			}
			--- TableColumn ---
				column-name = validationUserCode !
				column-type = domain !
				domainAttribute = validationUserCode !
				type = text
				id = validationUserCode
				table-column-width = 9
			{
				--- TableColumnItem ---
					item-column = validationUserCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = lastModifD !
				column-type = domain !
				domainAttribute = lastModifD !
				type = text
				id = lastModifD
				table-column-width = 9
			{
				--- TableColumnItem ---
					item-column = lastModifD
					format = datetime
					previewValue = value
			}
			--- TableColumn ---
				column-name = lastUserCode !
				column-type = domain !
				domainAttribute = lastUserCode !
				type = text
				id = lastUserCode
				table-column-width = 9
			{
				--- TableColumnItem ---
					item-column = lastUserCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = parentSessionFuncResultCode !
				column-type = domain !
				domainAttribute = parentSessionFuncResultCode !
				type = text
				id = parentSessionFuncResultCode
				table-column-width = 9
			{
				--- TableColumnItem ---
					item-column = parentSessionFuncResultCode
					previewValue = value
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						flow-action = viewProposal ud
						Query.propertyValue = "<udp:item column=\"parentSessionFuncResultCode\"/>" ud
						funcResultCode = "<udp:item column=\"parentSessionFuncResultCode\"/>" ud
						modal = false
						only-changed = false
						prevalidate = false
						target = self
					}
				}
			}
			--- TableSort ---
				sort-column-name = lastModifD
				sort-direction = descending
				sort-rank = 1
			--- TableExtra ---
				domainAttribute = id
		}
	}
}