# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Proposal Search Criteria", de = "Vorschlag Suchbegriffe", fr = "Critères de recherche sur proposition"
	containment = container
	domainEntity = "AAADSFunctionResult:FunctionResultPGSearchCriteria"
	search = input !
	bean-define = DSBean.AAADSFunctionResult.FunctionResultPGSearchCriteria
	bean-name = FunctionResultPGSearchCriteria
	id = FunctionResultSearchInput_MK60_
	tid = 251833161113841
{
	--- Box ---
		boxType = vertical
	{
		--- FilterCriteria ---
			includedFile = "resource:/com/module/search/QueryBuilder.xsp"
		--- Include ---
			includeSrc = "" !
			resource:///default/search/NavigationFunctionResultPGSearch.fragment
	}
}