# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "View Notepad", de = "Notiz ansehen", fr = "Voir bloc-note"
	domainEntity = "AAADSNotepad:NotepadAll"
	bean-define = DSBean.AAADSNotepad.NotepadAll
	bean-name = NotepadAll
	id = NotepadView_Sn1_y
	tid = 7048968397659
{
	--- Box ---
		boxType = vertical
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 6
			gridColumnsWidth = "16,17,16,17,16,18" !
			gridRowCount = 2
		{
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- LabelDomain ---
					domainAttribute = noteD !
					for = noteD
					cssClass = gray
					horizontalAlignment = "${corporatehalign}"
					required = true
			}
			--- GridCell ---
				gridColumnWidth = 17
			{
				--- CaldateField ---
					domainAttribute = noteD !
					format = datetime.date-only
					horizontalAlignment = "${corporatehalign}"
					type = datetime
					editable = false
					required = true
					bean-property = noteD
					id = noteD
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- LabelDomain ---
					domainAttribute = user !
					cssClass = gray
					horizontalAlignment = "${corporatehalign}"
					required = true
			}
			--- GridCell ---
				gridColumnWidth = 17
			{
				--- Include ---
					domainAssociation = user
					includeSrc = "" !
					resource:///default/defaultFragments/ApplUserIdentifierNameView.fragment
					bean-property-prefix = user.
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- LabelDomain ---
					domainAttribute = type !
					cssClass = gray
					horizontalAlignment = "${corporatehalign}"
			}
			--- GridCell ---
				gridColumnWidth = 18
			{
				--- Include ---
					domainAssociation = type
					includeSrc = "" !
					resource:///default/defaultFragments/TypeIdentifierDenomView.fragment
					bean-property-prefix = type.
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- LabelDomain ---
					domainAttribute = titleC !
					for = titleC
					cssClass = gray
					horizontalAlignment = "${corporatehalign}"
			}
			--- GridCell ---
				gridColumnWidth = 17
			{
				--- TextField ---
					domainAttribute = titleC !
					horizontalAlignment = "${corporatehalign}"
					type = text
					chars = 20
					editable = false
					bean-property = titleC
					id = titleC
			}
			--- GridCell ---
				gridColumnWidth = 16
			--- GridCell ---
				gridColumnWidth = 17
			--- GridCell ---
				gridColumnWidth = 16
			--- GridCell ---
				gridColumnWidth = 18
		}
		--- Grid ---
			cssClass = blank
			gridColumnCount = 2
			gridColumnsWidth = "16,84" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- LabelDomain ---
					domainAttribute = noteC !
					for = noteC
					cssClass = gray
					horizontalAlignment = "${corporatehalign}"
			}
			--- GridCell ---
				gridColumnWidth = 84
			{
				--- TextArea ---
					domainAttribute = noteC !
					columns = 100
					cssClass = "bold readonly"
					horizontalAlignment = "${corporatehalign}"
					rows = 3
					type = text
					editable = false
					bean-property = noteC
					id = noteC
			}
		}
	}
}