# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSPortPosSet:PortPosSetList"
	bean-define = DSBean.AAADSPortPosSet.PortPosSetList
	bean-name = PortPosSetList
	id = PortPosSetList_Yrtrw
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			id = NzTV1
			table-column-count = 4 !
			table-columns-width = "25,25,25,25" !
		{
			--- TableColumn ---
				column-name = portfolioCode !
				column-type = domain !
				domainAttribute = portfolioCode !
				id = portfolioCode
				table-column-width = 25
			{
				--- TableColumnItem ---
					item-column = portfolioCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = currencyCode !
				column-type = domain !
				domainAttribute = currencyCode !
				id = currencyCode
				table-column-width = 25
			{
				--- TableColumnItem ---
					item-column = currencyCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = typeCode !
				column-type = domain !
				domainAttribute = typeCode !
				id = typeCode
				table-column-width = 25
			{
				--- TableColumnItem ---
					item-column = typeCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = consPortfolioCode !
				column-type = domain !
				domainAttribute = consPortfolioCode !
				id = consPortfolioCode
				table-column-width = 25
			{
				--- TableColumnItem ---
					item-column = consPortfolioCode
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = portfolioCode
				sort-rank = 1
			--- TableSort ---
				sort-column-name = currencyCode
				sort-rank = 2
			--- TableSort ---
				sort-column-name = typeCode
				sort-rank = 3
			--- TableSort ---
				sort-column-name = consPortfolioCode
				sort-rank = 4
		}
	}
}