# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "DS2844:Ds2844Dataset"
	bean-define = DSBean.DS2844.Ds2844Dataset
	bean-name = Ds2844Dataset
	id = DS2844TreeWithShowNumItems_P1_d7
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			showNumItems = true
			id = B7Rl6
			table-column-count = 1 !
			table-columns-width = 100 !
		{
			--- TableColumn ---
				column-display-grouping = true
				column-name = placeholder_A_z87
				column-type = placeholder !
				type = text
				column-sortable = false !
				id = A_z87
				table-column-width = 100
			{
				--- TableGroup ---
					aggregateData = false
					group-column-name = ds2844Attribute
					group-sorting-column-name = ds2844Attribute
					group-sorting-direction = ascending
					group-rank = 1
			}
			--- TableSort ---
				sort-column-name = ds2844Attribute
				sort-rank = 1
		}
	}
}