# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "DS3557:DS3557Dataset"
	bean-define = DSBean.DS3557.DS3557Dataset
	bean-name = DS3557Dataset
	id = DS3557_tx_J_
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			id = N9Zz_
			table-column-count = 2 !
			table-columns-width = "50,50" !
		{
			--- TableColumn ---
				column-name = attr1 !
				column-type = domain !
				domainAttribute = attr1 !
				type = text
				id = attr1
				table-column-width = 50
			{
				--- TableColumnItem ---
					item-column = attr1
					item-css = test
					previewValue = value
			}
			--- TableColumn ---
				column-name = attr2 !
				column-type = domain !
				domainAttribute = attr2 !
				type = text
				id = attr2
				table-column-width = 50
			{
				--- TableColumnItem ---
					item-column = attr2
					previewValue = value
			}
		}
	}
}