# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "DS3458Domain:DS3458Dataset"
	search = output !
	bean-define = DSBean.DS3458Domain.DS3458Dataset
	bean-name = DS3458Dataset
	id = DS4166_ip__y
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			display-checkbox = true
			make-checkbox-exclusive = true
			table-filter-layer = true
			id = Y5bbg
			table-column-count = 3 !
			table-columns-width = "33,33,33" !
		{
			--- TableColumn ---
				column-display-grouping = true
				column-name = placeholder_n_t56
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				id = n_t56
				table-column-width = 33
			{
				--- CheckBox ---
					column-checkbox-identifier = PERIOD
					checkbox-group-names = DURATION
					horizontalAlignment = column
					horizontalTextPosition = trail
					id = btn_q_m5_
				--- TableGroup ---
					aggregateData = false
					group-column-name = DURATION
					group-sorting-column-name = DURATION
					group-sorting-direction = ascending
					group-rank = 1
			}
			--- TableColumn ---
				column-name = placeholder_U_5_X
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				id = U_5_X
				table-column-width = 33
			{
				--- CheckBox ---
					checkbox-group-names = DURATION
					horizontalAlignment = column
					horizontalTextPosition = trail
					id = btn_b9743
			}
			--- TableColumn ---
				column-name = MKT_VAL !
				column-type = domain !
				domainAttribute = MKT_VAL !
				type = text
				id = MKT_VAL
				table-column-width = 33
			{
				--- TableColumnItem ---
					item-column = MKT_VAL
					format = decimal
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = MKT_VAL
				sort-rank = 1
		}
	}
}