# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "DS4287Domain:DS4287Dataset"
	bean-define = DSBean.DS4287Domain.DS4287Dataset
	bean-name = DS4287Dataset
	id = DS4287_z_H_E
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			id = u5__9
			table-column-count = 2 !
			table-columns-width = "50,50" !
		{
			--- TableColumn ---
				column-name = MKT_VAL !
				column-type = domain !
				domainAttribute = MKT_VAL !
				format = decimal
				type = text
				id = MKT_VAL
				table-column-width = 50
			{
				--- TableColumnText ---
					item-column = MKT_VAL
					format = decimal.6-digits
					previewValue = value
					type = percent
			}
			--- TableColumn ---
				column-name = comp_L3D0w
				type = text
				id = L3D0w
				column-computation = same
				column-computation-parameters = PERIOD
				table-column-width = 50
			{
				--- TableColumnItem ---
					item-column = comp_L3D0w
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = comp_L3D0w
				sort-rank = 1
			--- TableSort ---
				sort-column-name = MKT_VAL
				sort-direction = descending
				sort-rank = 2
		}
	}
}