# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "DS4228:DS4228Dataset"
	bean-define = DSBean.DS4228.DS4228Dataset
	bean-name = DS4228Dataset
	id = DS4406_A6a4x
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			id = l_L7s
			table-column-count = 1 !
			table-columns-width = 100 !
		{
			--- TableColumn ---
				column-name = id !
				column-type = domain !
				domainAttribute = id !
				type = text
				id = id
				table-column-width = 100
			{
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = true
						technicalName = Condition
						boxType = vertical
						isWidgetSelected = true
					{
						--- Conditional ---
							indexOfSelectedChild = 0
						{
							--- ConditionalBody ---
								javaCode = true
								technicalName = Condition
								boxType = vertical
								isWidgetSelected = true
							{
								--- TableColumnItem ---
									item-column = id
									previewValue = value
							}
							--- ConditionalBody ---
								javaCode = true
								technicalName = Default
								boxType = vertical
								isWidgetVisible = false
						}
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetVisible = false
				}
			}
			--- TableSort ---
				sort-column-name = id
				sort-rank = 1
		}
	}
}