# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "DS3458Domain:DS3458Dataset"
	bean-define = DSBean.DS3458Domain.DS3458Dataset
	bean-name = DS3458Dataset
	id = DS4428_UWz9B
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			id = kNB__
			table-column-count = 2 !
			table-columns-width = "50,50" !
		{
			--- TableColumn ---
				column-name = MKT_VAL !
				column-type = domain !
				domainAttribute = MKT_VAL !
				format = decimal
				type = text
				id = MKT_VAL
				table-column-width = 50
			{
				--- TableColumnItem ---
					item-column = MKT_VAL
					format = decimal
					previewValue = value
				--- TableColumnItem ---
					item-column = MKT_VAL
					item-halign = center
					newLine = true
					previewValue = value
				--- TableColumnItem ---
					item-column = MKT_VAL
					previewValue = value
			}
			--- TableColumn ---
				column-name = placeholder_gN8D_
				column-type = placeholder !
				type = text
				column-sortable = false !
				id = gN8D_
				table-column-width = 50
			--- TableSort ---
				sort-column-name = MKT_VAL
				sort-rank = 1
			--- TableAggregate ---
				aggregate-column-name = MKT_VAL
				aggregate-computation = sum
		}
	}
}