# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "DS3458Domain:DS3458Dataset"
	bean-define = DSBean.DS3458Domain.DS3458Dataset
	bean-name = DS3458Dataset
	id = DS4505_X__H_
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			table-select-all = true
			id = g____
			table-column-count = 1 !
			table-columns-width = 100 !
		{
			--- TableColumn ---
				column-name = placeholder_H8___
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				id = H8___
				table-column-width = 100
			{
				--- CheckBox ---
					column-checkbox-action = ""
					column-checkbox-identifier = ASSET_CLASS_RANK
					horizontalTextPosition = trail
					id = btn_XLc_1
			}
			--- TableSort ---
				sort-column-name = ASSET_CLASS_RANK
				sort-rank = 1
		}
	}
}