# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "DS3813:DS"
	bean-define = DSBean.DS3813.DS
	bean-name = DS
	id = MyModule_A39n5
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			id = J9__0
			table-column-count = 1 !
			table-columns-width = 100 !
		{
			--- TableColumn ---
				column-name = placeholder_o89_4
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				id = o89_4
				table-column-width = 100
			{
				--- CheckBox ---
					column-checkbox-action = ""
					column-checkbox-identifier = a1
					horizontalTextPosition = trail
					id = btn_k44_8
			}
			--- TableSort ---
				sort-column-name = a1
				sort-rank = 1
		}
	}
}