# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "DS3813:DS"
	bean-define = DSBean.DS3813.DS
	bean-name = DS
	id = DS4708_P__32
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			id = h423Y
			table-column-count = 2 !
			table-columns-width = "50,50" !
		{
			--- TableColumn ---
				column-display-grouping = true
				column-name = placeholder_l_kn7
				column-type = placeholder !
				type = text
				column-sortable = false !
				id = c_M_6
				table-column-width = 50
			{
				--- TableGroup ---
					aggregateData = false
					group-column-name = a1
					group-sorting-column-name = a2
					group-sorting-direction = ascending
					hierarchy = true
					group-rank = 1
			}
			--- TableColumn ---
				column-name = a3 !
				column-type = domain !
				domainAttribute = a3 !
				type = text
				id = a3
				table-column-width = 50
			{
				--- TableColumnItem ---
					item-column = a3
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = a3
				sort-rank = 1
			--- TableExtra ---
				domainAttribute = a2
		}
	}
}