# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Dynamic Columns With Aggregation"
	domainEntity = "DS5365Domain:DS5365Dataset"
	bean-define = DSBean.DS5365Domain.DS5365Dataset
	bean-name = DS5365Dataset
	id = DynamicTableWithAggregation_q__5U
	tid = 341676259512961
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			id = Y___1
			table-column-count = 2 !
			table-columns-width = "50,50" !
		{
			--- TableColumn ---
				column-display-grouping = true
				column-name = REF_CURRENCY
				column-type = placeholder !
				type = text
				column-sortable = false !
				id = T__8q
				table-column-width = 50
			{
				--- TableGroup ---
					aggregateData = false
					group-column-name = ASSET_CLASS_RANK
					group-sorting-column-name = ASSET_CLASS_DENOM
					group-sorting-direction = ascending
					hierarchy = true
					group-rank = 1
			}
			--- TableColumn ---
				column-name = ASSET_CLASS_DENOM
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				id = k360_
				table-column-width = 50
			{
				--- CheckBox ---
					column-checkbox-action = Select
					column-checkbox-identifier = MKT_VAL
					column-checkbox-security = REF_CURRENCY
					checkbox-group-names = ASSET_CLASS_RANK
					horizontalTextPosition = trail
					id = btn_p0L_2
			}
			--- TableSort ---
				sort-column-name = ASSET_CLASS_DENOM
				sort-rank = 1
		}
	}
}