# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "DS3458Domain:DS3458Dataset"
	search = output !
	bean-define = DSBean.DS3458Domain.DS3458Dataset
	bean-name = DS3458Dataset
	id = DS4166_ip__y
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			show-column-selector = false
			table-expand-all = false
			table-filter-layer = true
			id = Y5bbg
			table-column-count = 1 !
			table-columns-width = 100 !
			table-filterset-id = fs_sf4
		{
			--- TableColumn ---
				column-display-grouping = true
				column-name = placeholder_hm4_Z
				column-type = placeholder !
				type = text
				column-sortable = false !
				id = hm4_Z
				table-column-width = 100
			{
				--- TableGroup ---
					aggregateData = false
					group-column-name = DURATION
					group-sorting-column-name = DURATION
					group-sorting-direction = ascending
					group-rank = 1
			}
			--- TableSort ---
				sort-column-name = MKT_VAL
				sort-rank = 1
		}
	}
}