# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Dynamic Columns With Aggregation"
	domainEntity = "DS5365Domain:DS5365Dataset"
	bean-define = DSBean.DS5365Domain.DS5365Dataset
	bean-name = DS5365Dataset
	id = DS5299TableGrpFormat_as__y
	tid = 69188976542165
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			id = Q0___
			table-column-count = 2 !
			table-columns-width = "50,50" !
		{
			--- TableColumn ---
				column-display-grouping = true
				column-name = REF_CURRENCY
				column-type = placeholder !
				type = text
				column-sortable = false !
				id = oZ__J
				table-column-width = 50
			{
				--- TableGroup ---
					aggregateData = false
					group-column-name = mydate
					group-sorting-column-name = ASSET_CLASS_DENOM
					group-sorting-direction = ascending
					hierarchy = true
					format = datetime.time-only
					group-rank = 1
			}
			--- TableColumn ---
				column-name = ASSET_CLASS_DENOM
				column-type = placeholder !
				type = text
				column-sortable = false !
				id = N_Ep_
				table-column-width = 50
			--- TableSort ---
				sort-column-name = ASSET_CLASS_DENOM
				sort-rank = 1
		}
	}
}