# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "DS5339:DS5339Dataset"
	bean-define = DSBean.DS5339.DS5339Dataset
	bean-name = DS5339Dataset
	id = DS5339_CB_8_
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			id = K_15z
			table-column-count = 2 !
			table-columns-width = "50,50" !
		{
			--- TableColumn ---
				column-name = attrEnum !
				column-type = domain !
				domainAttribute = attrEnum !
				type = text
				id = attrEnum
				table-column-width = 50
			{
				--- TableColumnItem ---
					item-column = attrEnum
					previewValue = value
				--- TableColumnItem ---
					item-column = otherAttr
					previewValue = value
			}
			--- TableColumn ---
				column-name = otherAttr !
				column-type = domain !
				domainAttribute = otherAttr !
				type = text
				id = otherAttr
				table-column-width = 50
			{
				--- TableColumnItem ---
					item-column = otherAttr
					previewValue = value
				--- TableColumnItem ---
					item-column = attrEnum
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = anEnum
				sort-rank = 1
		}
	}
}