# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "DS3813:DS"
	bean-define = DSBean.DS3813.DS
	bean-name = DS
	id = DS5354_Ft___
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			display-checkbox = true
			id = B6v5h
			table-column-count = 2 !
			table-columns-width = "50,50" !
		{
			--- TableColumn ---
				column-display-grouping = true
				column-name = placeholder_r8_7E
				column-type = placeholder !
				type = text
				column-sortable = false !
				id = r8_7E
				table-column-width = 50
			{
				--- TableGroup ---
					aggregateData = false
					group-column-name = id
					group-sorting-column-name = id
					hierarchy = true
					group-rank = 1
			}
			--- TableColumn ---
				column-name = placeholder_o89_4
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				id = O___Y
				table-column-width = 50
			{
				--- CheckBox ---
					column-checkbox-action = ""
					column-checkbox-identifier = a1
					checkbox-group-names = id
					horizontalTextPosition = trail
					id = btn_q2Kl4
			}
			--- TableSort ---
				sort-column-name = a1
				sort-rank = 1
		}
	}
}