# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Dynamic Columns With Aggregation"
	domainEntity = "DS3458Domain:DS3458Dataset"
	bean-define = DSBean.DS3458Domain.DS3458Dataset
	bean-name = DS3458Dataset
	id = DynamicTableWithAggregation_q__5U
	tid = 341676259512961
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			table-rendering-mode = summary-delegated
			id = Y___1
			table-column-count = 4 !
			table-columns-width = "25,25,25,25" !
		{
			--- TableColumn ---
				column-display-grouping = true
				column-name = placeholder_T__8q
				column-type = placeholder !
				type = text
				column-sortable = false !
				id = T__8q
				table-column-width = 25
			{
				--- TableGroup ---
					group-column-name = PTF_HIER_STR
					group-sorting-column-name = PTF_HIER_STR
					group-sorting-direction = ascending
					hierarchy = true
					group-rank = 1
				--- TableGroup ---
					group-column-name = CURR_CLASS_CODE
					group-dynamic-column = true
					group-sorting-column-name = CURR_CLASS_CODE
					group-sorting-direction = ascending
					group-rank = 2
			}
			--- TableColumn ---
				column-name = MarketValue
				type = decimal
				id = I8_99
				column-computation = same
				column-computation-parameters = MKT_VAL
				table-column-width = 25
			{
				--- TableColumnItem ---
					item-column = MKT_VAL
					previewValue = value
			}
			--- TableColumn ---
				column-name = MakeAmount
				type = amount
				id = G_1e7
				column-computation = make-amount
				column-computation-parameters = "MKT_VAL,REF_CURRENCY"
				table-column-width = 25
			{
				--- TableColumnItem ---
					item-column = MakeAmount
					previewValue = value
			}
			--- TableColumn ---
				column-name = dynamic_currency
				column-type = dynamic !
				type = text
				id = t5i62
				table-column-width = 25
			{
				--- TableColumnItem ---
					item-column = MarketValue
					previewValue = value
				--- Spacer ---
					height = 4
					width = 10
				--- TableColumnItem ---
					item-column = MakeAmount
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = PTF_HIER_STR
				sort-rank = 1
			--- TableAggregate ---
				aggregate-column-name = MKT_VAL
				aggregate-computation = sum
				aggregate-group-names = PTF_HIER_STR
			--- TableAggregate ---
				aggregate-column-name = MarketValue
				aggregate-computation = sum
				aggregate-group-names = PTF_HIER_STR
			--- TableAggregate ---
				aggregate-column-name = REF_CURRENCY
				aggregate-computation = max
				aggregate-group-names = PTF_HIER_STR
			--- TableAggregate ---
				aggregate-column-name = MakeAmount
				aggregate-computation = sum
				aggregate-group-names = PTF_HIER_STR
			--- TableAggregate ---
				aggregate-column-name = dynamic_currency
				aggregate-computation = sum
				aggregate-group-names = PTF_HIER_STR
			--- TableAggregate ---
				aggregate-column-name = CURR_CLASS_CODE
				aggregate-computation = max
				aggregate-group-names = PTF_HIER_STR
		}
	}
}