# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Dynamic Column Without Aggregation"
	domainEntity = "DS3458Domain:DS3458Dataset"
	bean-define = DSBean.DS3458Domain.DS3458Dataset
	bean-name = DS3458Dataset
	id = MyModule2_s5ucZ
	tid = 178106590990781
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			table-rendering-mode = summary-delegated
			cssClass = nodeco
			highlightRow = true
			table-fixed-size = true
			table-width = 600
			dumpModel = true
			id = V_L0i
			table-column-count = 4 !
			table-columns-width = "25,25,25,25" !
		{
			--- TableColumn ---
				column-display-grouping = true
				column-name = placeholder_sFQ_3
				column-type = placeholder !
				type = text
				column-sortable = false !
				id = R_4F3
				table-column-width = 25
			{
				--- TableGroup ---
					group-column-name = PERIOD
					group-dynamic-column = true
					group-sorting-column-name = PERIOD
					group-sorting-direction = ascending
					group-rank = 3
				--- TableGroup ---
					group-column-name = PTF_HIER_STR
					group-sorting-column-name = PTF_HIER_STR
					group-sorting-direction = ascending
					hierarchy = true
					group-rank = 1
			}
			--- TableColumn ---
				column-name = MarketValue
				table-column-halign = lead
				type = decimal
				id = bp1__
				column-computation = same
				column-computation-parameters = MKT_VAL
				table-column-width = 25
			{
				--- TableColumnItem ---
					item-column = MarketValue
					item-halign = lead
					previewValue = value
			}
			--- TableColumn ---
				column-name = MakeAmount2
				type = amount
				id = E__pz
				column-computation = make-amount
				column-computation-parameters = "MKT_VAL,REF_CURRENCY"
				table-column-width = 25
			{
				--- TableColumnItem ---
					item-column = MakeAmount2
					previewValue = value
			}
			--- TableColumn ---
				column-name = dynamic_period
				column-type = dynamic !
				table-column-halign = lead
				type = text
				id = k0llQ
				table-column-width = 25
			{
				--- TableColumnItem ---
					item-column = MarketValue
					item-halign = lead
					previewValue = value
				--- Spacer ---
					height = 4
					width = 20
				--- TableColumnItem ---
					item-column = MakeAmount2
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = PTF_HIER_STR
				sort-rank = 1
			--- TableAggregate ---
				aggregate-column-name = MarketValue
				aggregate-computation = sum
				aggregate-group-names = PTF_HIER_STR
			--- TableAggregate ---
				aggregate-column-name = MakeAmount2
				aggregate-computation = sum
				aggregate-group-names = PTF_HIER_STR
			--- TableAggregate ---
				aggregate-column-name = REF_CURRENCY
				aggregate-computation = max
				aggregate-group-names = PTF_HIER_STR
			--- TableAggregate ---
				aggregate-column-name = MKT_VAL
				aggregate-computation = sum
				aggregate-group-names = PTF_HIER_STR
			--- TableAggregate ---
				aggregate-column-name = dynamic_period
				aggregate-computation = max
				aggregate-group-names = PTF_HIER_STR
		}
	}
}