# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "DS3847Domain:DS3847Dataset"
	bean-define = DSBean.DS3847Domain.DS3847Dataset
	bean-name = DS3847Dataset
	id = TableSorting_U86C_
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			id = w7_65
			table-column-count = 1 !
			table-columns-width = 100 !
		{
			--- TableColumn ---
				column-name = ACCT_FILTER !
				column-type = domain !
				domainAttribute = ACCT_FILTER !
				type = text
				id = ACCT_FILTER
				table-column-width = 100
			{
				--- TableColumnItem ---
					item-column = ACCT_FILTER
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = PERIOD
				sort-rank = 1
		}
	}
}