/*
     This module was generated automatically from /vobs/ose5/core_ext/dbgserver/private/dbgserverinterface.stl.
                DO NOT EDIT THIS FILE
*/



package com.ose.dbgserver.protocol;
import java.io.*;

public class DBGCatchSendReceiveNotify extends Message implements dbgserverinterfaceConstants{
   public short state;
   public byte eventType;
   public byte notUsed;
   public int tick;
   public int utick;
   public int abstime;
   public int abstick;
   public int fromPid;
   public int toPid;
   public int signalNo;
   public int signalId;
   public String fromName;
   public String toName;


   public DBGCatchSendReceiveNotify(short _state, byte _eventType, byte _notUsed, int _tick, int _utick, int _abstime, int _abstick, int _fromPid, int _toPid, int _signalNo, int _signalId, String _fromName, String _toName) {
      state = _state;
      eventType = _eventType;
      notUsed = _notUsed;
      tick = _tick;
      utick = _utick;
      abstime = _abstime;
      abstick = _abstick;
      fromPid = _fromPid;
      toPid = _toPid;
      signalNo = _signalNo;
      signalId = _signalId;
      fromName = _fromName;
      toName = _toName;
   }

   public DBGCatchSendReceiveNotify(DataInputStream _s) throws IOException { signalNo = 32944; read(_s);}
   public final void sendMessage(DataOutputStream _s) throws IOException { write(_s, this.state, this.eventType, this.notUsed, this.tick, this.utick, this.abstime, this.abstick, this.fromPid, this.toPid, this.signalNo, this.signalId, this.fromName, this.toName);}
   public final static void write(DataOutputStream _s, short _state, byte _eventType, byte _notUsed, int _tick, int _utick, int _abstime, int _abstick, int _fromPid, int _toPid, int _signalNo, int _signalId, String _fromName, String _toName   ) throws IOException {
         int _i;
         int _fromNameSize=_fromName.length()+1;
         int _toNameSize=_toName.length()+1;
         _s.writeInt(DBGCATCHSENDRECEIVENOTIFY);
         int _size=44
            +4+((_fromNameSize & 3) == 0 ? _fromNameSize : (_fromNameSize + 4 - (_fromNameSize&3)))
            +4+_toNameSize
            ;
         _s.writeInt(_size);
         _s.writeShort(_state);
         _s.writeByte(_eventType);
         _s.writeByte(_notUsed);
         _s.writeInt(_tick);
         _s.writeInt(_utick);
         _s.writeInt(_abstime);
         _s.writeInt(_abstick);
         _s.writeInt(_fromPid);
         _s.writeInt(_toPid);
         _s.writeInt(_signalNo);
         _s.writeInt(_signalId);
         int _dynSize=44;
         int _bytes2Skip;

         // write fromName
         _bytes2Skip=4-_dynSize&3;
         for(_i=0;_i<_bytes2Skip;_i++) _s.writeByte(0);
         _dynSize+=_bytes2Skip;
         _s.writeInt(_fromNameSize);
         _dynSize+=_fromNameSize;
         _s.writeBytes(_fromName);
         _s.writeByte(0);

         // write toName
         _bytes2Skip=4-_dynSize&3;
         for(_i=0;_i<_bytes2Skip;_i++) _s.writeByte(0);
         _dynSize+=_bytes2Skip;
         _s.writeInt(_toNameSize);
         _dynSize+=_toNameSize;
         _s.writeBytes(_toName);
         _s.writeByte(0);
   }
   public final void read(DataInputStream _s) throws IOException {
         int _i;
         int _size=_s.readInt();
         state=_s.readShort();
         eventType=_s.readByte();
         notUsed=_s.readByte();
         tick=_s.readInt();
         utick=_s.readInt();
         abstime=_s.readInt();
         abstick=_s.readInt();
         fromPid=_s.readInt();
         toPid=_s.readInt();
         signalNo=_s.readInt();
         signalId=_s.readInt();
         int _dynSize=44;
         int _bytes2Skip;

         // read fromName
         _bytes2Skip=4-_dynSize&3;
         if(_bytes2Skip!=0) {_s.skipBytes(_bytes2Skip);_dynSize+=_bytes2Skip;}
         _size=_s.readInt();
         _dynSize+=_size;
         byte _fromName[] = new byte[_size];
         _s.readFully(_fromName, 0, _size);
         fromName=new String(_fromName, 0,0, _fromName.length-1);

         // read toName
         _bytes2Skip=4-_dynSize&3;
         if(_bytes2Skip!=0) {_s.skipBytes(_bytes2Skip);_dynSize+=_bytes2Skip;}
         _size=_s.readInt();
         _dynSize+=_size;
         byte _toName[] = new byte[_size];
         _s.readFully(_toName, 0, _size);
         toName=new String(_toName, 0,0, _toName.length-1);
   }
}
