/*
     This module was generated automatically from /vobs/ose5/core_ext/dbgserver/private/dbgserverinterface.stl.
                DO NOT EDIT THIS FILE
*/



package com.ose.dbgserver.protocol;
import java.io.*;

public class DBGCatchErrorNotify extends Message implements dbgserverinterfaceConstants{
   public short state;
   public byte eventType;
   public byte notUsed;
   public int tick;
   public int utick;
   public int abstime;
   public int abstick;
   public int error;
   public int extra;
   public int pid;
   public String name;
   public String miscInfo;


   public DBGCatchErrorNotify(short _state, byte _eventType, byte _notUsed, int _tick, int _utick, int _abstime, int _abstick, int _error, int _extra, int _pid, String _name, String _miscInfo) {
      state = _state;
      eventType = _eventType;
      notUsed = _notUsed;
      tick = _tick;
      utick = _utick;
      abstime = _abstime;
      abstick = _abstick;
      error = _error;
      extra = _extra;
      pid = _pid;
      name = _name;
      miscInfo = _miscInfo;
   }

   public DBGCatchErrorNotify(DataInputStream _s) throws IOException { signalNo = 32947; read(_s);}
   public final void sendMessage(DataOutputStream _s) throws IOException { write(_s, this.state, this.eventType, this.notUsed, this.tick, this.utick, this.abstime, this.abstick, this.error, this.extra, this.pid, this.name, this.miscInfo);}
   public final static void write(DataOutputStream _s, short _state, byte _eventType, byte _notUsed, int _tick, int _utick, int _abstime, int _abstick, int _error, int _extra, int _pid, String _name, String _miscInfo   ) throws IOException {
         int _i;
         int _nameSize=_name.length()+1;
         int _miscInfoSize=_miscInfo.length()+1;
         _s.writeInt(DBGCATCHERRORNOTIFY);
         int _size=40
            +4+((_nameSize & 3) == 0 ? _nameSize : (_nameSize + 4 - (_nameSize&3)))
            +4+_miscInfoSize
            ;
         _s.writeInt(_size);
         _s.writeShort(_state);
         _s.writeByte(_eventType);
         _s.writeByte(_notUsed);
         _s.writeInt(_tick);
         _s.writeInt(_utick);
         _s.writeInt(_abstime);
         _s.writeInt(_abstick);
         _s.writeInt(_error);
         _s.writeInt(_extra);
         _s.writeInt(_pid);
         int _dynSize=40;
         int _bytes2Skip;

         // write name
         _bytes2Skip=4-_dynSize&3;
         for(_i=0;_i<_bytes2Skip;_i++) _s.writeByte(0);
         _dynSize+=_bytes2Skip;
         _s.writeInt(_nameSize);
         _dynSize+=_nameSize;
         _s.writeBytes(_name);
         _s.writeByte(0);

         // write miscInfo
         _bytes2Skip=4-_dynSize&3;
         for(_i=0;_i<_bytes2Skip;_i++) _s.writeByte(0);
         _dynSize+=_bytes2Skip;
         _s.writeInt(_miscInfoSize);
         _dynSize+=_miscInfoSize;
         _s.writeBytes(_miscInfo);
         _s.writeByte(0);
   }
   public final void read(DataInputStream _s) throws IOException {
         int _i;
         int _size=_s.readInt();
         state=_s.readShort();
         eventType=_s.readByte();
         notUsed=_s.readByte();
         tick=_s.readInt();
         utick=_s.readInt();
         abstime=_s.readInt();
         abstick=_s.readInt();
         error=_s.readInt();
         extra=_s.readInt();
         pid=_s.readInt();
         int _dynSize=40;
         int _bytes2Skip;

         // read name
         _bytes2Skip=4-_dynSize&3;
         if(_bytes2Skip!=0) {_s.skipBytes(_bytes2Skip);_dynSize+=_bytes2Skip;}
         _size=_s.readInt();
         _dynSize+=_size;
         byte _name[] = new byte[_size];
         _s.readFully(_name, 0, _size);
         name=new String(_name, 0,0, _name.length-1);

         // read miscInfo
         _bytes2Skip=4-_dynSize&3;
         if(_bytes2Skip!=0) {_s.skipBytes(_bytes2Skip);_dynSize+=_bytes2Skip;}
         _size=_s.readInt();
         _dynSize+=_size;
         byte _miscInfo[] = new byte[_size];
         _s.readFully(_miscInfo, 0, _size);
         miscInfo=new String(_miscInfo, 0,0, _miscInfo.length-1);
   }
}
