/*
     This module was generated automatically from /vobs/ose5/core_ext/dbgserver/private/dbgserverinterface.stl.
                DO NOT EDIT THIS FILE
*/



package com.ose.dbgserver.protocol;
import java.io.*;

public class DBGEvactReply extends Message implements dbgserverinterfaceConstants{
   public int success;
   public int evactId;
   public int evactMemoryUsed;


   public DBGEvactReply(int _success, int _evactId, int _evactMemoryUsed) {
      success = _success;
      evactId = _evactId;
      evactMemoryUsed = _evactMemoryUsed;
   }

   public DBGEvactReply(DataInputStream _s) throws IOException { signalNo = 32926; read(_s);}
   public final void sendMessage(DataOutputStream _s) throws IOException { write(_s, this.success, this.evactId, this.evactMemoryUsed);}
   public final static void write(DataOutputStream _s, int _success, int _evactId, int _evactMemoryUsed   ) throws IOException {
         int _i;
         _s.writeInt(DBGEVACTREPLY);
         int _size=20;
         _s.writeInt(_size);
         _s.writeInt(_success);
         _s.writeInt(_evactId);
         _s.writeInt(_evactMemoryUsed);
   }
   public final void read(DataInputStream _s) throws IOException {
         int _i;
         int _size=_s.readInt();
         success=_s.readInt();
         evactId=_s.readInt();
         evactMemoryUsed=_s.readInt();
   }
}
