/*
     This module was generated automatically from /vobs/ose5/core_ext/dbgserver/private/dbgserverinterface.stl.
                DO NOT EDIT THIS FILE
*/



package com.ose.dbgserver.protocol;
import java.io.*;

public class DBGFlowControlReply extends Message implements dbgserverinterfaceConstants{
   public int lossCount;
   public byte async;


   public DBGFlowControlReply(int _lossCount, byte _async) {
      lossCount = _lossCount;
      async = _async;
   }

   public DBGFlowControlReply(DataInputStream _s) throws IOException { signalNo = 32908; read(_s);}
   public final void sendMessage(DataOutputStream _s) throws IOException { write(_s, this.lossCount, this.async);}
   public final static void write(DataOutputStream _s, int _lossCount, byte _async   ) throws IOException {
         int _i;
         _s.writeInt(DBGFLOWCONTROLREPLY);
         int _size=13;
         _s.writeInt(_size);
         _s.writeInt(_lossCount);
         _s.writeByte(_async);
   }
   public final void read(DataInputStream _s) throws IOException {
         int _i;
         int _size=_s.readInt();
         lossCount=_s.readInt();
         async=_s.readByte();
   }
}
