/*
     This module was generated automatically from /vobs/ose5/core_ext/dbgserver/private/dbgserverinterface.stl.
                DO NOT EDIT THIS FILE
*/



package com.ose.dbgserver.protocol;
import java.io.*;

public class DBGGetPoolSignalsReply extends Message implements dbgserverinterfaceConstants{
   public int pid;
   public int data[];


   public DBGGetPoolSignalsReply(int _pid, int _data[]) {
      pid = _pid;
      data = _data;
   }

   public DBGGetPoolSignalsReply(DataInputStream _s) throws IOException { signalNo = 32955; read(_s);}
   public final void sendMessage(DataOutputStream _s) throws IOException { write(_s, this.pid, this.data);}
   public final static void write(DataOutputStream _s, int _pid, int _data[]   ) throws IOException {
         int _i;
         _s.writeInt(DBGGETPOOLSIGNALSREPLY);
         int _size=12
            +4+(_data.length*4)
            ;
         _s.writeInt(_size);
         _s.writeInt(_pid);
         int _dynSize=12;
         int _bytes2Skip;

         // write data
         _bytes2Skip=4-_dynSize&3;
         for(_i=0;_i<_bytes2Skip;_i++) _s.writeByte(0);
         _dynSize+=_bytes2Skip;
         _s.writeInt((_data.length*4));
         _dynSize+=(_data.length*4);
         for(_i = 0 ; _i < _data.length ; _i++) 
            _s.writeInt(_data[_i]);
   }
   public final void read(DataInputStream _s) throws IOException {
         int _i;
         int _size=_s.readInt();
         pid=_s.readInt();
         int _dynSize=12;
         int _bytes2Skip;

         // read data
         _bytes2Skip=4-_dynSize&3;
         if(_bytes2Skip!=0) {_s.skipBytes(_bytes2Skip);_dynSize+=_bytes2Skip;}
         _size=_s.readInt();
         _dynSize+=_size;
         _size/=4;
         data=new int[_size];
         for(_i = 0 ; _i < _size ; _i++) 
            data[_i]=_s.readInt();
   }
}
