/*
     This module was generated automatically from /vobs/ose5/core_ext/dbgserver/private/dbgserverinterface.stl.
                DO NOT EDIT THIS FILE
*/



package com.ose.dbgserver.protocol;
import java.io.*;

public class DBGGotoNotify extends Message implements dbgserverinterfaceConstants{
   public int state;


   public DBGGotoNotify(int _state) {
      state = _state;
   }

   public DBGGotoNotify(DataInputStream _s) throws IOException { signalNo = 32948; read(_s);}
   public final void sendMessage(DataOutputStream _s) throws IOException { write(_s, this.state);}
   public final static void write(DataOutputStream _s, int _state   ) throws IOException {
         int _i;
         _s.writeInt(DBGGOTONOTIFY);
         int _size=12;
         _s.writeInt(_size);
         _s.writeInt(_state);
   }
   public final void read(DataInputStream _s) throws IOException {
         int _i;
         int _size=_s.readInt();
         state=_s.readInt();
   }
}
