/*
     This module was generated automatically from /vobs/ose5/core_ext/dbgserver/private/dbgserverinterface.stl.
                DO NOT EDIT THIS FILE
*/



package com.ose.dbgserver.protocol;
import java.io.*;

public class DBGGetBlockProcInfo extends Message implements dbgserverinterfaceConstants{
   public int bid;
   public int fullInfo;


   public DBGGetBlockProcInfo(int _bid, int _fullInfo) {
      bid = _bid;
      fullInfo = _fullInfo;
   }

   public DBGGetBlockProcInfo(DataInputStream _s) throws IOException { signalNo = 32960; read(_s);}
   public final void sendMessage(DataOutputStream _s) throws IOException { write(_s, this.bid, this.fullInfo);}
   public final static void write(DataOutputStream _s, int _bid, int _fullInfo   ) throws IOException {
         int _i;
         _s.writeInt(DBGGETBLOCKPROCINFO);
         int _size=16;
         _s.writeInt(_size);
         _s.writeInt(_bid);
         _s.writeInt(_fullInfo);
   }
   public final void read(DataInputStream _s) throws IOException {
         int _i;
         int _size=_s.readInt();
         bid=_s.readInt();
         fullInfo=_s.readInt();
   }
}
