/*
     This module was generated automatically from /vobs/ose5/core_ext/dbgserver/private/dbgserverinterface.stl.
                DO NOT EDIT THIS FILE
*/



package com.ose.dbgserver.protocol;
import java.io.*;

public class DBGGetBlockInfo extends Message implements dbgserverinterfaceConstants{
   public int bid;


   public DBGGetBlockInfo(int _bid) {
      bid = _bid;
   }

   public DBGGetBlockInfo(DataInputStream _s) throws IOException { signalNo = 32963; read(_s);}
   public final void sendMessage(DataOutputStream _s) throws IOException { write(_s, this.bid);}
   public final static void write(DataOutputStream _s, int _bid   ) throws IOException {
         int _i;
         _s.writeInt(DBGGETBLOCKINFO);
         int _size=12;
         _s.writeInt(_size);
         _s.writeInt(_bid);
   }
   public final void read(DataInputStream _s) throws IOException {
         int _i;
         int _size=_s.readInt();
         bid=_s.readInt();
   }
}
