/*
     This module was generated automatically from /vobs/ose5/core_ext/dbgserver/private/dbgserverinterface.stl.
                DO NOT EDIT THIS FILE
*/



package com.ose.dbgserver.protocol;
import java.io.*;

public class DBGGetSignalQueueReply extends Message implements dbgserverinterfaceConstants{
   public int pid;
   public int from;
   public int addressee;
   public int signalSize;
   public int signalNumber;
   public int entry;


   public DBGGetSignalQueueReply(int _pid, int _from, int _addressee, int _signalSize, int _signalNumber, int _entry) {
      pid = _pid;
      from = _from;
      addressee = _addressee;
      signalSize = _signalSize;
      signalNumber = _signalNumber;
      entry = _entry;
   }

   public DBGGetSignalQueueReply(DataInputStream _s) throws IOException { signalNo = 32983; read(_s);}
   public final void sendMessage(DataOutputStream _s) throws IOException { write(_s, this.pid, this.from, this.addressee, this.signalSize, this.signalNumber, this.entry);}
   public final static void write(DataOutputStream _s, int _pid, int _from, int _addressee, int _signalSize, int _signalNumber, int _entry   ) throws IOException {
         int _i;
         _s.writeInt(DBGGETSIGNALQUEUEREPLY);
         int _size=32;
         _s.writeInt(_size);
         _s.writeInt(_pid);
         _s.writeInt(_from);
         _s.writeInt(_addressee);
         _s.writeInt(_signalSize);
         _s.writeInt(_signalNumber);
         _s.writeInt(_entry);
   }
   public final void read(DataInputStream _s) throws IOException {
         int _i;
         int _size=_s.readInt();
         pid=_s.readInt();
         from=_s.readInt();
         addressee=_s.readInt();
         signalSize=_s.readInt();
         signalNumber=_s.readInt();
         entry=_s.readInt();
   }
}
