/*
     This module was generated automatically from /vobs/ose5/core_ext/dbgserver/private/dbgserverinterface.stl.
                DO NOT EDIT THIS FILE
*/



package com.ose.dbgserver.protocol;
import java.io.*;

public class DBGGetCatchScopeStatusReply extends Message implements dbgserverinterfaceConstants{
   public byte status;


   public DBGGetCatchScopeStatusReply(byte _status) {
      status = _status;
   }

   public DBGGetCatchScopeStatusReply(DataInputStream _s) throws IOException { signalNo = 32950; read(_s);}
   public final void sendMessage(DataOutputStream _s) throws IOException { write(_s, this.status);}
   public final static void write(DataOutputStream _s, byte _status   ) throws IOException {
         int _i;
         _s.writeInt(DBGGETCATCHSCOPESTATUSREPLY);
         int _size=9;
         _s.writeInt(_size);
         _s.writeByte(_status);
   }
   public final void read(DataInputStream _s) throws IOException {
         int _i;
         int _size=_s.readInt();
         status=_s.readByte();
   }
}
