/*
     This module was generated automatically from /vobs/ose5/core_ext/dbgserver/private/dbgserverinterface.stl.
                DO NOT EDIT THIS FILE
*/



package com.ose.dbgserver.protocol;
import java.io.*;

public class DBGIOPCSessionTerminate extends Message implements dbgserverinterfaceConstants{
   public int sessionHandle;


   public DBGIOPCSessionTerminate(int _sessionHandle) {
      sessionHandle = _sessionHandle;
   }

   public DBGIOPCSessionTerminate(DataInputStream _s) throws IOException { signalNo = 33019; read(_s);}
   public final void sendMessage(DataOutputStream _s) throws IOException { write(_s, this.sessionHandle);}
   public final static void write(DataOutputStream _s, int _sessionHandle   ) throws IOException {
         int _i;
         _s.writeInt(DBGIOPCSESSIONTERMINATE);
         int _size=12;
         _s.writeInt(_size);
         _s.writeInt(_sessionHandle);
   }
   public final void read(DataInputStream _s) throws IOException {
         int _i;
         int _size=_s.readInt();
         sessionHandle=_s.readInt();
   }
}
