/*
     This module was generated automatically from /vobs/ose5/core_ext/dbgserver/private/dbgserverinterface.stl.
                DO NOT EDIT THIS FILE
*/



package com.ose.dbgserver.protocol;
import java.io.*;

public class DBGNotifyResult extends Message implements dbgserverinterfaceConstants{
   public int cookie;


   public DBGNotifyResult(int _cookie) {
      cookie = _cookie;
   }

   public DBGNotifyResult(DataInputStream _s) throws IOException { signalNo = 33045; read(_s);}
   public final void sendMessage(DataOutputStream _s) throws IOException { write(_s, this.cookie);}
   public final static void write(DataOutputStream _s, int _cookie   ) throws IOException {
         int _i;
         _s.writeInt(DBGNOTIFYRESULT);
         int _size=12;
         _s.writeInt(_size);
         _s.writeInt(_cookie);
   }
   public final void read(DataInputStream _s) throws IOException {
         int _i;
         int _size=_s.readInt();
         cookie=_s.readInt();
   }
}
