/*
     This module was generated automatically from /vobs/ose5/core_ext/dbgserver/private/dbgserverinterface.stl.
                DO NOT EDIT THIS FILE
*/



package com.ose.dbgserver.protocol;
import java.io.*;

public class DBGResumeScope extends Message implements dbgserverinterfaceConstants{
   public byte scope[];


   public DBGResumeScope(byte _scope[]) {
      scope = _scope;
   }

   public DBGResumeScope(DataInputStream _s) throws IOException { signalNo = 33040; read(_s);}
   public final void sendMessage(DataOutputStream _s) throws IOException { write(_s, this.scope);}
   public final static void write(DataOutputStream _s, byte _scope[]   ) throws IOException {
         int _i;
         _s.writeInt(DBGRESUMESCOPE);
         int _size=8
            +4+_scope.length
            ;
         _s.writeInt(_size);
         int _dynSize=8;
         int _bytes2Skip;

         // write scope
         _bytes2Skip=4-_dynSize&3;
         for(_i=0;_i<_bytes2Skip;_i++) _s.writeByte(0);
         _dynSize+=_bytes2Skip;
         _s.writeInt(_scope.length);
         _dynSize+=_scope.length;
         _s.write(_scope);
   }
   public final void read(DataInputStream _s) throws IOException {
         int _i;
         int _size=_s.readInt();
         int _dynSize=8;
         int _bytes2Skip;

         // read scope
         _bytes2Skip=4-_dynSize&3;
         if(_bytes2Skip!=0) {_s.skipBytes(_bytes2Skip);_dynSize+=_bytes2Skip;}
         _size=_s.readInt();
         _dynSize+=_size;
         scope=new byte[_size];
         _s.readFully(scope,0,_size);
   }
}
