/*
     This module was generated automatically from /vobs/ose5/core_ext/dbgserver/private/dbgserverinterface.stl.
                DO NOT EDIT THIS FILE
*/



package com.ose.dbgserver.protocol;
import java.io.*;

public class DBGReadTraceEndMark extends Message implements dbgserverinterfaceConstants{
   public int entrys;


   public DBGReadTraceEndMark(int _entrys) {
      entrys = _entrys;
   }

   public DBGReadTraceEndMark(DataInputStream _s) throws IOException { signalNo = 32938; read(_s);}
   public final void sendMessage(DataOutputStream _s) throws IOException { write(_s, this.entrys);}
   public final static void write(DataOutputStream _s, int _entrys   ) throws IOException {
         int _i;
         _s.writeInt(DBGREADTRACEENDMARK);
         int _size=12;
         _s.writeInt(_size);
         _s.writeInt(_entrys);
   }
   public final void read(DataInputStream _s) throws IOException {
         int _i;
         int _size=_s.readInt();
         entrys=_s.readInt();
   }
}
