/*
     This module was generated automatically from /vobs/ose5/core_ext/dbgserver/private/dbgserverinterface.stl.
                DO NOT EDIT THIS FILE
*/



package com.ose.dbgserver.protocol;
import java.io.*;

public class DBGRegisterConsole extends Message implements dbgserverinterfaceConstants{
   public byte input;
   public byte notUsed1;
   public byte notUsed2;
   public byte notUsed3;
   public String terminalName;


   public DBGRegisterConsole(byte _input, byte _notUsed1, byte _notUsed2, byte _notUsed3, String _terminalName) {
      input = _input;
      notUsed1 = _notUsed1;
      notUsed2 = _notUsed2;
      notUsed3 = _notUsed3;
      terminalName = _terminalName;
   }

   public DBGRegisterConsole(DataInputStream _s) throws IOException { signalNo = 33053; read(_s);}
   public final void sendMessage(DataOutputStream _s) throws IOException { write(_s, this.input, this.notUsed1, this.notUsed2, this.notUsed3, this.terminalName);}
   public final static void write(DataOutputStream _s, byte _input, byte _notUsed1, byte _notUsed2, byte _notUsed3, String _terminalName   ) throws IOException {
         int _i;
         int _terminalNameSize=_terminalName.length()+1;
         _s.writeInt(DBGREGISTERCONSOLE);
         int _size=12
            +4+_terminalNameSize
            ;
         _s.writeInt(_size);
         _s.writeByte(_input);
         _s.writeByte(_notUsed1);
         _s.writeByte(_notUsed2);
         _s.writeByte(_notUsed3);
         int _dynSize=12;
         int _bytes2Skip;

         // write terminalName
         _bytes2Skip=4-_dynSize&3;
         for(_i=0;_i<_bytes2Skip;_i++) _s.writeByte(0);
         _dynSize+=_bytes2Skip;
         _s.writeInt(_terminalNameSize);
         _dynSize+=_terminalNameSize;
         _s.writeBytes(_terminalName);
         _s.writeByte(0);
   }
   public final void read(DataInputStream _s) throws IOException {
         int _i;
         int _size=_s.readInt();
         input=_s.readByte();
         notUsed1=_s.readByte();
         notUsed2=_s.readByte();
         notUsed3=_s.readByte();
         int _dynSize=12;
         int _bytes2Skip;

         // read terminalName
         _bytes2Skip=4-_dynSize&3;
         if(_bytes2Skip!=0) {_s.skipBytes(_bytes2Skip);_dynSize+=_bytes2Skip;}
         _size=_s.readInt();
         _dynSize+=_size;
         byte _terminalName[] = new byte[_size];
         _s.readFully(_terminalName, 0, _size);
         terminalName=new String(_terminalName, 0,0, _terminalName.length-1);
   }
}
