/*
     This module was generated automatically from /vobs/ose5/core_ext/dbgserver/private/dbgserverinterface.stl.
                DO NOT EDIT THIS FILE
*/



package com.ose.dbgserver.protocol;
import java.io.*;

public class DBGSetCreateEvact extends Message implements dbgserverinterfaceConstants{
   public int action;
   public int countNumber;
   public int state;
   public int nextState;
   public byte name[];


   public DBGSetCreateEvact(int _action, int _countNumber, int _state, int _nextState, byte _name[]) {
      action = _action;
      countNumber = _countNumber;
      state = _state;
      nextState = _nextState;
      name = _name;
   }

   public DBGSetCreateEvact(DataInputStream _s) throws IOException { signalNo = 32922; read(_s);}
   public final void sendMessage(DataOutputStream _s) throws IOException { write(_s, this.action, this.countNumber, this.state, this.nextState, this.name);}
   public final static void write(DataOutputStream _s, int _action, int _countNumber, int _state, int _nextState, byte _name[]   ) throws IOException {
         int _i;
         _s.writeInt(DBGSETCREATEEVACT);
         int _size=24
            +4+_name.length
            ;
         _s.writeInt(_size);
         _s.writeInt(_action);
         _s.writeInt(_countNumber);
         _s.writeInt(_state);
         _s.writeInt(_nextState);
         int _dynSize=24;
         int _bytes2Skip;

         // write name
         _bytes2Skip=4-_dynSize&3;
         for(_i=0;_i<_bytes2Skip;_i++) _s.writeByte(0);
         _dynSize+=_bytes2Skip;
         _s.writeInt(_name.length);
         _dynSize+=_name.length;
         _s.write(_name);
   }
   public final void read(DataInputStream _s) throws IOException {
         int _i;
         int _size=_s.readInt();
         action=_s.readInt();
         countNumber=_s.readInt();
         state=_s.readInt();
         nextState=_s.readInt();
         int _dynSize=24;
         int _bytes2Skip;

         // read name
         _bytes2Skip=4-_dynSize&3;
         if(_bytes2Skip!=0) {_s.skipBytes(_bytes2Skip);_dynSize+=_bytes2Skip;}
         _size=_s.readInt();
         _dynSize+=_size;
         name=new byte[_size];
         _s.readFully(name,0,_size);
   }
}
