/*
     This module was generated automatically from /vobs/ose5/core_ext/dbgserver/private/dbgserverinterface.stl.
                DO NOT EDIT THIS FILE
*/



package com.ose.dbgserver.protocol;
import java.io.*;

public class DBGWriteLdmVars extends Message implements dbgserverinterfaceConstants{
   public int count;
   public byte vars[];


   public DBGWriteLdmVars(int _count, byte _vars[]) {
      count = _count;
      vars = _vars;
   }

   public DBGWriteLdmVars(DataInputStream _s) throws IOException { signalNo = 33058; read(_s);}
   public final void sendMessage(DataOutputStream _s) throws IOException { write(_s, this.count, this.vars);}
   public final static void write(DataOutputStream _s, int _count, byte _vars[]   ) throws IOException {
         int _i;
         _s.writeInt(DBGWRITELDMVARS);
         int _size=12
            +4+_vars.length
            ;
         _s.writeInt(_size);
         _s.writeInt(_count);
         int _dynSize=12;
         int _bytes2Skip;

         // write vars
         _bytes2Skip=4-_dynSize&3;
         for(_i=0;_i<_bytes2Skip;_i++) _s.writeByte(0);
         _dynSize+=_bytes2Skip;
         _s.writeInt(_vars.length);
         _dynSize+=_vars.length;
         _s.write(_vars);
   }
   public final void read(DataInputStream _s) throws IOException {
         int _i;
         int _size=_s.readInt();
         count=_s.readInt();
         int _dynSize=12;
         int _bytes2Skip;

         // read vars
         _bytes2Skip=4-_dynSize&3;
         if(_bytes2Skip!=0) {_s.skipBytes(_bytes2Skip);_dynSize+=_bytes2Skip;}
         _size=_s.readInt();
         _dynSize+=_size;
         vars=new byte[_size];
         _s.readFully(vars,0,_size);
   }
}
