/*
     This module was generated automatically from /vobs/ose5/core_ext/dbgserver/private/dbgserverinterface.stl.
                DO NOT EDIT THIS FILE
*/



package com.ose.dbgserver.protocol;
import java.io.*;

public class DBGWriteMemory extends Message implements dbgserverinterfaceConstants{
   public int blockid;
   public int address;
   public byte bytes[];


   public DBGWriteMemory(int _blockid, int _address, byte _bytes[]) {
      blockid = _blockid;
      address = _address;
      bytes = _bytes;
   }

   public DBGWriteMemory(DataInputStream _s) throws IOException { signalNo = 33022; read(_s);}
   public final void sendMessage(DataOutputStream _s) throws IOException { write(_s, this.blockid, this.address, this.bytes);}
   public final static void write(DataOutputStream _s, int _blockid, int _address, byte _bytes[]   ) throws IOException {
         int _i;
         _s.writeInt(DBGWRITEMEMORY);
         int _size=16
            +4+_bytes.length
            ;
         _s.writeInt(_size);
         _s.writeInt(_blockid);
         _s.writeInt(_address);
         int _dynSize=16;
         int _bytes2Skip;

         // write bytes
         _bytes2Skip=4-_dynSize&3;
         for(_i=0;_i<_bytes2Skip;_i++) _s.writeByte(0);
         _dynSize+=_bytes2Skip;
         _s.writeInt(_bytes.length);
         _dynSize+=_bytes.length;
         _s.write(_bytes);
   }
   public final void read(DataInputStream _s) throws IOException {
         int _i;
         int _size=_s.readInt();
         blockid=_s.readInt();
         address=_s.readInt();
         int _dynSize=16;
         int _bytes2Skip;

         // read bytes
         _bytes2Skip=4-_dynSize&3;
         if(_bytes2Skip!=0) {_s.skipBytes(_bytes2Skip);_dynSize+=_bytes2Skip;}
         _size=_s.readInt();
         _dynSize+=_size;
         bytes=new byte[_size];
         _s.readFully(bytes,0,_size);
   }
}
