/*
     This module was generated automatically from /vobs/ose5/core_ext/dbgserver/private/dbgserverinterface.stl.
                DO NOT EDIT THIS FILE
*/



package com.ose.dbgserver.protocol;

import java.io.DataOutputStream;
import java.io.IOException;

public abstract class Message{
   public abstract void sendMessage(DataOutputStream _s) throws IOException;
   public int signalNo;
}
