# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSTermEvent:TermEventList"
	cssClass = nodeco
	bean-define = DSBean.AAADSTermEvent.TermEventList
	bean-name = TermEventList
	id = TermEventList_M_b_B
{
	--- Box ---
		labels en = "Term Events", de = Termin-Ereignis, fr = "Evénements à terme"
		boxType = vertical
		width = 0
		tid = 2337954850109162
	{
		--- TableTree ---
			table-filter-layer = true
			id = yPG3_
			table-column-count = 21 !
			table-columns-width = "4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4" !
		{
			--- TableColumn ---
				column-name = validityD !
				column-type = domain !
				domainAttribute = validityD !
				column-locked = true
				id = validityD
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = validityD
					format = date
					previewValue = value
			}
			--- TableColumn ---
				column-name = beginD !
				column-type = domain !
				domainAttribute = beginD !
				type = text
				id = beginD
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = beginD
					format = date
					previewValue = value
			}
			--- TableColumn ---
				column-name = code !
				column-type = domain !
				domainAttribute = code !
				type = text
				id = code
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = code
					previewValue = value
			}
			--- TableColumn ---
				column-name = underlyInstrCode !
				column-type = domain !
				domainAttribute = underlyInstrCode !
				type = text
				id = underlyInstrCode
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = underlyInstrCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = underlyQtyN !
				column-type = domain !
				domainAttribute = underlyQtyN !
				format = decimal.detailed
				type = text
				id = underlyQtyN
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = underlyQtyN
					previewValue = value
			}
			--- TableColumn ---
				column-name = currencyCode !
				column-type = domain !
				domainAttribute = currencyCode !
				type = text
				id = currencyCode
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = currencyCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = physicalF !
				column-type = domain !
				domainAttribute = physicalF !
				type = text
				id = physicalF
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = physicalF
					previewValue = value
			}
			--- TableColumn ---
				column-name = endD !
				column-type = domain !
				domainAttribute = endD !
				format = date
				type = text
				id = endD
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = endD
					format = date
					previewValue = value
			}
			--- TableColumn ---
				column-name = exerQuoteN !
				column-type = domain !
				domainAttribute = exerQuoteN !
				format = decimal.detailed
				type = text
				id = exerQuoteN
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = exerQuoteN
					previewValue = value
			}
			--- TableColumn ---
				column-name = endValidityD !
				column-type = domain !
				domainAttribute = endValidityD !
				format = date
				type = text
				id = endValidityD
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = endValidityD
					format = date
					previewValue = value
			}
			--- TableColumn ---
				column-name = settleDaysN !
				column-type = domain !
				domainAttribute = settleDaysN !
				format = integer
				type = text
				id = settleDaysN
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = settleDaysN
					previewValue = value
			}
			--- TableColumn ---
				column-name = freqN !
				column-type = domain !
				domainAttribute = freqN !
				format = integer
				type = text
				id = freqN
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = freqN
					previewValue = value
			}
			--- TableColumn ---
				column-name = freqUnitE !
				column-type = domain !
				domainAttribute = freqUnitE !
				type = text
				id = freqUnitE
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = freqUnitE
					previewValue = value
			}
			--- TableColumn ---
				column-name = fixedExchRate !
				column-type = domain !
				domainAttribute = fixedExchRate !
				format = decimal.detailed
				type = text
				id = fixedExchRate
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = fixedExchRate
					previewValue = value
			}
			--- TableColumn ---
				column-name = barrierN !
				column-type = domain !
				domainAttribute = barrierN !
				format = decimal.detailed
				type = text
				column-visibility = not-visible
				id = barrierN
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = barrierN
					previewValue = value
			}
			--- TableColumn ---
				column-name = barrierNatE !
				column-type = domain !
				domainAttribute = barrierNatE !
				type = text
				column-visibility = not-visible
				id = barrierNatE
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = barrierNatE
					previewValue = value
			}
			--- TableColumn ---
				column-name = premiumPmtE !
				column-type = domain !
				domainAttribute = premiumPmtE !
				type = text
				column-visibility = not-visible
				id = premiumPmtE
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = premiumPmtE
					previewValue = value
			}
			--- TableColumn ---
				column-name = optionClassE !
				column-type = domain !
				domainAttribute = optionClassE !
				type = text
				column-visibility = not-visible
				id = optionClassE
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = optionClassE
					previewValue = value
			}
			--- TableColumn ---
				column-name = optStyleE !
				column-type = domain !
				domainAttribute = optStyleE !
				type = text
				column-visibility = not-visible
				id = optStyleE
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = optStyleE
					previewValue = value
			}
			--- TableColumn ---
				column-name = payOffNatE !
				column-type = domain !
				domainAttribute = payOffNatE !
				type = text
				column-visibility = not-visible
				id = payOffNatE
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = payOffNatE
					previewValue = value
			}
			--- TableColumn ---
				column-name = instrCode !
				column-type = domain !
				domainAttribute = instrCode !
				column-is-part-of-filter = false
				column-visibility = never-visible
				id = instrCode
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = instrCode
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = validityD
				sort-direction = descending
				sort-rank = 2
			--- TableSort ---
				sort-column-name = endValidityD
				sort-direction = descending
				sort-rank = 3
			--- TableSort ---
				sort-column-name = beginD
				sort-direction = descending
				sort-rank = 4
			--- TableSort ---
				sort-column-name = endD
				sort-direction = descending
				sort-rank = 5
			--- TableSort ---
				sort-column-name = underlyInstrCode
				sort-rank = 6
		}
	}
}