/*
* generated by Xtext
*/
package com.odcgroup.menu.model;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class MenuUiInjectorProvider implements IInjectorProvider {

	public Injector getInjector() {
		return com.odcgroup.menu.model.ui.internal.MenuActivator.getInstance().getInjector("com.odcgroup.menu.model.Menu");
	}

}
