# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "List of Proposed Orders", de = Anlagevorschlagliste, fr = "Liste des propositions d\'ordres"
	domainEntity = "AAADSOrderSession:OrderProposalBuyDetailedList"
	bean-define = DSBean.AAADSOrderSession.OrderProposalBuyDetailedList
	bean-name = OrderProposalBuyDetailedList
	id = ByCategorySecurity_u__fE
	tid = 7746886598559
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			table-filter-layer = true
			table-fixed-size = true
			table-height = 150
			table-page-size = 15
			id = j_10x
			table-column-count = 15 !
			table-columns-width = "6,6,6,6,6,6,6,6,6,6,6,6,6,6,6" !
		{
			--- TableColumn ---
				column-display-grouping = true
				column-name = INSTR_NAME_ISIN !
				column-type = domain !
				domainAttribute = INSTR_NAME_ISIN !
				type = text
				column-is-part-of-filter = false
				column-locked = true
				id = INSTR_NAME_ISIN
				table-column-width = 6
			{
				--- Icon ---
					toolTips de = "Details des Instruments ansehen", fr = "Voir les détails de l\'instrument", en = "View Instrument Details"
					horizontalAlignment = "${corporatehalign}"
					icon = application_form_magnify
					id = qn_A_
					tid = 113920936486620
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "resource:///administration/instrument/InstrumentQuickView.pageflow"
						target = popup
						code = "<udp:item column=\"INSTR_CODE\"/>" ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
				--- Spacer ---
					height = 4
					width = 10
				--- TableColumnItem ---
					item-column = INSTR_NAME_ISIN
					previewValue = value
				--- TableGroup ---
					group-column-name = HIERARCHY
					group-sorting-column-name = ORDER_NATURE
					group-sorting-direction = ascending
					hierarchy = true
					group-rank = 1
			}
			--- TableColumn ---
				column-name = ORDER_NATURE !
				column-type = domain !
				domainAttribute = ORDER_NATURE !
				type = text
				column-is-part-of-filter = false
				column-visibility = never-visible
				id = ORDER_NATURE
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = ORDER_NATURE
					previewValue = value
			}
			--- TableColumn ---
				column-name = UPDATE_RIGHT !
				column-type = domain !
				domainAttribute = UPDATE_RIGHT !
				type = text
				id = UPDATE_RIGHT
				table-column-width = 6
			{
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "\"true\".equals(<udp:item column=\"UPDATE_RIGHT\"/>.toString())"
						technicalName = Condition
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips en = "View/Update Order", de = "Auftrag anzeigen/ändern", fr = "Voir/Mettre à jour un ordre"
							horizontalAlignment = center
							icon = application_form_edit
							id = F_M_R
							tid = 7746887865922
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = getorder ud
								toupdate-id = "<udp:item column=\"order_id\"/>" ud
								modal = false
								only-changed = false
								prevalidate = false
							}
						}
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetVisible = false
				}
			}
			--- TableColumn ---
				column-name = DELETE_RIGHT !
				column-type = domain !
				domainAttribute = DELETE_RIGHT !
				type = text
				id = DELETE_RIGHT
				table-column-width = 6
			{
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "\"true\".equals(<udp:item column=\"DELETE_RIGHT\"/>.toString())"
						technicalName = Condition
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips en = "Delete Order", de = "Auftrag löschen", fr = "Supprimer un ordre"
							horizontalAlignment = center
							icon = application_form_delete
							id = U6398
							tid = 7746888220098
						{
							Event OnClick (submit)
							tid = 268532399760302
							messages en = "Are you sure to delete this order ?", de = "Wollen Sie diesen Auftrag wirklich löschen?", fr = "Etes-vous sûr de vouloir supprimer cet ordre?"
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								param = "flow-action=deleteorder"
								todelete-id = "<udp:item column=\"order_id\"/>" ud
								modal = false
								only-changed = false
								prevalidate = false
							}
						}
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetVisible = false
				}
			}
			--- TableColumn ---
				column-name = FACTSHEET !
				column-type = domain !
				domainAttribute = FACTSHEET !
				type = text
				id = FACTSHEET
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = FACTSHEET
					previewValue = value
			}
			--- TableColumn ---
				labels de = Anlagekategorie
				column-name = ASSET_CLASS_NAME !
				column-type = domain !
				domainAttribute = ASSET_CLASS_NAME !
				type = text
				id = ASSET_CLASS_NAME
				table-column-width = 6
				tid = 21329955548819
			{
				--- TableColumnItem ---
					item-column = ASSET_CLASS_NAME
					previewValue = value
			}
			--- TableColumn ---
				column-name = QUANTITY !
				column-type = domain !
				domainAttribute = QUANTITY !
				id = QUANTITY
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = QUANTITY
					format = decimal
					previewValue = value
			}
			--- TableColumn ---
				column-name = PRICE !
				column-type = domain !
				domainAttribute = PRICE !
				id = PRICE
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = PRICE
					format = decimal.detailed
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Net Amount", de = Nettobetrag, fr = "Montant net"
				column-name = ORDER_NET_AMT
				type = amount
				id = t1V_w
				column-computation = make-amount
				column-computation-parameters = "ORDER_NET_AMOUNT,ORDER_CURRENCY"
				table-column-width = 6
				tid = 7746889000354
			{
				--- TableColumnItem ---
					item-column = ORDER_NET_AMT
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Accrued Interests", de = Stückzinsen, fr = "Intérêt couru"
				column-name = ACCRUED_INTEREST
				type = amount
				column-visibility = not-visible
				id = rC6M8
				column-computation = make-amount
				column-computation-parameters = "ACCR_INTERESTS,ORDER_CURRENCY"
				table-column-width = 6
				tid = 183450830674317
			{
				--- TableColumnItem ---
					item-column = ACCRUED_INTEREST
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Gross Amount", de = Bruttobetrag, fr = "Montant brut"
				column-name = GROSS_AMOUNT
				type = amount
				column-visibility = not-visible
				id = jg_56
				column-computation = make-amount
				column-computation-parameters = "ORDER_GROSS_AMOUNT,ORDER_CURRENCY"
				table-column-width = 6
				tid = 183554567943023
			{
				--- TableColumnItem ---
					item-column = GROSS_AMOUNT
					previewValue = value
			}
			--- TableColumn ---
				column-name = PERC_PORTFOLIO !
				column-type = domain !
				domainAttribute = PERC_PORTFOLIO !
				type = text
				id = PERC_PORTFOLIO
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = PERC_PORTFOLIO
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = PERC_MKT_SEG_OBJ !
				column-type = domain !
				domainAttribute = PERC_MKT_SEG_OBJ !
				type = text
				id = PERC_MKT_SEG_OBJ
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = PERC_MKT_SEG_OBJ
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = TARGET_TYPE !
				column-type = domain !
				domainAttribute = TARGET_TYPE !
				type = text
				id = TARGET_TYPE
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = TARGET_TYPE
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Net Amount in Portfolio Currency", de = "Nettobetrag in Porfoliowährung", fr = "Montant net en devise du portefeuille"
				column-name = AMOUNT_PTF_CCY
				type = amount
				id = t____
				column-computation = make-amount
				column-computation-parameters = "ORDER_PTF_AMOUNT,PTF_CURRENCY"
				table-column-width = 6
				tid = 22537309341833
			{
				--- TableColumnItem ---
					item-column = AMOUNT_PTF_CCY
					previewValue = value
			}
			--- TableKeepFilter ---
				keep-filter-column-name = ORDER_NATURE
				keep-filter-operand = 3
				keep-filter-operator = less-than
			--- TableSort ---
				sort-column-name = ORDER_NATURE
				sort-rank = 1
			--- TableSort ---
				sort-column-name = ORDER_PTF_AMOUNT
				sort-direction = descending
				sort-rank = 2
			--- TableAggregate ---
				aggregate-column-name = AMOUNT_PTF_CCY
				aggregate-computation = sum
				aggregate-group-names = HIERARCHY
			--- TableExtra ---
				domainAttribute = INSTR_CODE
			--- TableExtra ---
				domainAttribute = order_id
			--- TableExtra ---
				domainAttribute = DELETE_RIGHT
			--- TableExtra ---
				domainAttribute = UPDATE_RIGHT
		}
		--- Grid ---
			cssClass = blank
			gridColumnCount = 2
			gridColumnsWidth = "25,25" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Button ---
					labels en = "Create Buy Order", de = "Kaufauftrag erstellen", fr = "Créer un ordre d\'achat"
					id = btn_jA_Zz
					tid = 7746887297016
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = newOrder ud
						functionResult.id = "valueOf(form.id)" ud
						portfolio.code = "valueOf(form.portfolioDimPortfolio.code)" ud
						natureE = 1 ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
				--- Button ---
					labels en = "Create Sell Order", de = "Verkaufsauftrag erstellen", fr = "Création d\'un ordre de vente"
					id = btn_lq__2
					tid = 23983642231025
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = newOrder ud
						functionResult.id = "valueOf(form.id)" ud
						portfolio.code = "valueOf(form.portfolioDimPortfolio.code)" ud
						natureE = 2 ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- GridCell ---
				gridColumnWidth = 25
		}
	}
}