# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "List of Proposed Orders", de = Anlagevorschlagliste, fr = "Liste des propositions d\'ordres"
	domainEntity = "AAADSOrderSession:OrderProposalBuyDetailedList"
	bean-define = DSBean.AAADSOrderSession.OrderProposalBuyDetailedList
	bean-name = OrderProposalBuyDetailedList
	id = ByCategorySecurity_u__fE
	tid = 110363831485820
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			table-filter-layer = true
			table-page-size = 15
			id = j_10x
			table-column-count = 13 !
			table-columns-width = "7,7,7,7,7,7,7,7,7,7,7,7,7" !
		{
			--- TableColumn ---
				column-display-grouping = true
				column-name = INSTR_NAME_ISIN !
				column-type = domain !
				domainAttribute = INSTR_NAME_ISIN !
				type = text
				column-is-part-of-filter = false
				column-locked = true
				id = INSTR_NAME_ISIN
				table-column-width = 7
			{
				--- Icon ---
					toolTips en = "View Instrument Details", fr = "Voir les détails de l\'instrument", de = "Details des Instruments ansehen"
					horizontalAlignment = "${corporatehalign}"
					icon = application_form_magnify
					id = t_L_Z
					tid = 113871145276564
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "resource:///administration/instrument/InstrumentQuickView.pageflow"
						target = popup
						code = "<udp:item column=\"INSTR_CODE\"/>" ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
				--- Spacer ---
					height = 4
					width = 10
				--- TableColumnItem ---
					item-column = INSTR_NAME_ISIN
					previewValue = value
				--- TableGroup ---
					group-column-name = HIERARCHY
					group-sorting-column-name = ORDER_NATURE
					group-sorting-direction = ascending
					hierarchy = true
					group-rank = 1
			}
			--- TableColumn ---
				column-name = ORDER_NATURE !
				column-type = domain !
				domainAttribute = ORDER_NATURE !
				type = text
				column-is-part-of-filter = false
				column-visibility = not-visible
				id = ORDER_NATURE
				table-column-width = 7
			{
				--- TableColumnItem ---
					item-column = ORDER_NATURE
					previewValue = value
			}
			--- TableColumn ---
				column-name = FACTSHEET !
				column-type = domain !
				domainAttribute = FACTSHEET !
				type = text
				id = FACTSHEET
				table-column-width = 7
			{
				--- TableColumnItem ---
					item-column = FACTSHEET
					previewValue = value
			}
			--- TableColumn ---
				labels de = Anlagekategorie
				column-name = ASSET_CLASS_NAME !
				column-type = domain !
				domainAttribute = ASSET_CLASS_NAME !
				type = text
				id = ASSET_CLASS_NAME
				table-column-width = 7
				tid = 21292491629243
			{
				--- TableColumnItem ---
					item-column = ASSET_CLASS_NAME
					previewValue = value
			}
			--- TableColumn ---
				column-name = QUANTITY !
				column-type = domain !
				domainAttribute = QUANTITY !
				id = QUANTITY
				table-column-width = 7
			{
				--- TableColumnItem ---
					item-column = QUANTITY
					format = decimal
					previewValue = value
			}
			--- TableColumn ---
				column-name = PRICE !
				column-type = domain !
				domainAttribute = PRICE !
				id = PRICE
				table-column-width = 7
			{
				--- TableColumnItem ---
					item-column = PRICE
					format = decimal.detailed
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Net Amount", de = Nettobetrag, fr = "Montant net"
				column-name = ORDER_NET_AMT
				type = amount
				id = t1V_w
				column-computation = make-amount
				column-computation-parameters = "ORDER_NET_AMOUNT,ORDER_CURRENCY"
				table-column-width = 7
				tid = 110363836234477
			{
				--- TableColumnItem ---
					item-column = ORDER_NET_AMT
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Accrued Interests", de = Stückzinsen, fr = "Intérêt couru"
				column-name = ACCRUED_INTEREST
				type = amount
				column-visibility = not-visible
				id = rC6M8
				column-computation = make-amount
				column-computation-parameters = "ACCR_INTERESTS,ORDER_CURRENCY"
				table-column-width = 7
				tid = 110363836759765
			{
				--- TableColumnItem ---
					item-column = ACCRUED_INTEREST
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Gross Amount", de = Bruttobetrag, fr = "Montant brut"
				column-name = GROSS_AMOUNT
				type = amount
				column-visibility = not-visible
				id = jg_56
				column-computation = make-amount
				column-computation-parameters = "ORDER_GROSS_AMOUNT,ORDER_CURRENCY"
				table-column-width = 7
				tid = 110363837208261
			{
				--- TableColumnItem ---
					item-column = GROSS_AMOUNT
					previewValue = value
			}
			--- TableColumn ---
				column-name = PERC_PORTFOLIO !
				column-type = domain !
				domainAttribute = PERC_PORTFOLIO !
				type = text
				id = PERC_PORTFOLIO
				table-column-width = 7
			{
				--- TableColumnItem ---
					item-column = PERC_PORTFOLIO
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = PERC_MKT_SEG_OBJ !
				column-type = domain !
				domainAttribute = PERC_MKT_SEG_OBJ !
				type = text
				id = PERC_MKT_SEG_OBJ
				table-column-width = 7
			{
				--- TableColumnItem ---
					item-column = PERC_MKT_SEG_OBJ
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = TARGET_TYPE !
				column-type = domain !
				domainAttribute = TARGET_TYPE !
				type = text
				id = TARGET_TYPE
				table-column-width = 7
			{
				--- TableColumnItem ---
					item-column = TARGET_TYPE
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Net Amount in Portfolio Currency", de = "Nettobetrag in Porfoliowährung", fr = "Montant net en devise du portefeuille"
				column-name = AMOUNT_PTF_CCY
				type = amount
				id = t____
				column-computation = make-amount
				column-computation-parameters = "ORDER_PTF_AMOUNT,PTF_CURRENCY"
				table-column-width = 7
				tid = 110363841227348
			{
				--- TableColumnItem ---
					item-column = AMOUNT_PTF_CCY
					previewValue = value
			}
			--- TableKeepFilter ---
				keep-filter-column-name = ORDER_NATURE
				keep-filter-operand = 3
				keep-filter-operator = less-than
			--- TableSort ---
				sort-column-name = ORDER_NATURE
				sort-rank = 1
			--- TableSort ---
				sort-column-name = ORDER_PTF_AMOUNT
				sort-direction = descending
				sort-rank = 2
			--- TableAggregate ---
				aggregate-column-name = AMOUNT_PTF_CCY
				aggregate-computation = sum
				aggregate-group-names = HIERARCHY
			--- TableExtra ---
				domainAttribute = INSTR_CODE
			--- TableExtra ---
				domainAttribute = order_id
			--- TableExtra ---
				domainAttribute = DELETE_RIGHT
			--- TableExtra ---
				domainAttribute = UPDATE_RIGHT
		}
	}
}