# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "List of External Positions", de = "Liste der Externen Positionen", fr = "Liste des positions externes"
	domainEntity = "AAADSOrderSession:OrderProposalExternalPosition"
	bean-define = DSBean.AAADSOrderSession.OrderProposalExternalPosition
	bean-name = OrderProposalExternalPosition
	id = ExternalPositionView_G_50X
	tid = 5275060140406
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			table-filter-layer = true
			id = d2_D5
			table-column-count = 6 !
			table-columns-width = "16,16,16,16,16,16" !
		{
			--- TableColumn ---
				labels de = Menge
				column-name = QUANTITY !
				column-type = domain !
				domainAttribute = QUANTITY !
				type = text
				id = QUANTITY
				table-column-width = 16
				tid = 1604016787845567
			{
				--- TableColumnItem ---
					item-column = QUANTITY
					format = decimal
					previewValue = value
			}
			--- TableColumn ---
				labels de = "Art des Instruments"
				column-name = INSTR_NATURE !
				column-type = domain !
				domainAttribute = INSTR_NATURE !
				type = text
				id = INSTR_NATURE
				table-column-width = 16
				tid = 1604016788089373
			{
				--- TableColumnItem ---
					item-column = INSTR_NATURE
					previewValue = value
			}
			--- TableColumn ---
				labels de = "Instrument Name/ISIN"
				column-name = INSTR_NAME_ISIN !
				column-type = domain !
				domainAttribute = INSTR_NAME_ISIN !
				type = text
				id = INSTR_NAME_ISIN
				table-column-width = 16
				tid = 1604016788297677
			{
				--- Icon ---
					icon = application_form_magnify
					id = Yu8X7
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "resource:///administration/instrument/InstrumentQuickView.pageflow"
						target = popup
						code = "<udp:item column=\"INSTR_CODE\"/>" ud
						only-changed = false
						prevalidate = false
						modal = false
					}
				}
				--- Spacer ---
					height = 4
					width = 10
				--- TableColumnItem ---
					item-column = INSTR_NAME_ISIN
					previewValue = value
			}
			--- TableColumn ---
				labels en = Price, de = Preis, fr = Prix
				column-name = PRICE_CCY
				type = amount
				id = Jl5_5
				column-computation = make-amount
				column-computation-parameters = "PRICE,ORDER_CURRENCY"
				table-column-width = 16
				tid = 5857866474559
			{
				--- TableColumnItem ---
					item-column = PRICE_CCY
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Market Value", de = Marktwert, fr = "Valeur de marché"
				column-name = NET_AMOUT
				type = amount
				id = p_7_2
				column-computation = make-amount
				column-computation-parameters = "ORDER_NET_AMOUNT,ORDER_CURRENCY"
				table-column-width = 16
				tid = 5865239926019
			{
				--- TableColumnItem ---
					item-column = NET_AMOUT
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Market Value in Ptf Ccy", de = "Marktwert in Ptf Währ.", fr = "Valeur de marche dans la devise portefeuille"
				column-name = MARKET_VALUE_PTC_CCY
				type = amount
				id = c____
				column-computation = make-amount
				column-computation-parameters = "ORDER_PTF_AMOUNT,PTF_CURRENCY"
				table-column-width = 16
				tid = 5870986360578
			{
				--- TableColumnItem ---
					item-column = MARKET_VALUE_PTC_CCY
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = ORDER_PTF_AMOUNT
				sort-direction = descending
				sort-rank = 1
			--- TableExtra ---
				domainAttribute = INSTR_CODE
		}
	}
}