# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "List of External Positions", de = "Liste der Externen Positionen", fr = "Liste des positions externes"
	domainEntity = "AAADSOrderSession:OrderProposalExternalPosition"
	bean-define = DSBean.AAADSOrderSession.OrderProposalExternalPosition
	bean-name = OrderProposalExternalPosition
	id = ByCategorySecurity_u__fE
	tid = 89504279173332
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			table-filter-layer = true
			table-page-size = 15
			id = j_10x
			table-column-count = 8 !
			table-columns-width = "12,12,12,12,12,12,12,12" !
		{
			--- TableColumn ---
				column-name = UPDATE_RIGHT !
				column-type = domain !
				domainAttribute = UPDATE_RIGHT !
				type = text
				id = UPDATE_RIGHT
				table-column-width = 12
			{
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "\"true\".equals(<udp:item column=\"UPDATE_RIGHT\"/>.toString())"
						technicalName = Condition
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips en = "View/Update External Position", de = "Externe Position anzeigen/ändern", fr = "Voir/Mettre à jour la position externe"
							horizontalAlignment = center
							icon = application_form_edit
							id = UD_Os
							tid = 89504281368120
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = getorder ud
								modal = false
								only-changed = false
								prevalidate = false
								code = "<udp:item column=\"OPER_CODE\"/>" ud
							}
						}
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetVisible = false
				}
			}
			--- TableColumn ---
				column-name = DELETE_RIGHT !
				column-type = domain !
				domainAttribute = DELETE_RIGHT !
				type = text
				id = DELETE_RIGHT
				table-column-width = 12
			{
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "\"true\".equals(<udp:item column=\"DELETE_RIGHT\"/>.toString())"
						technicalName = Condition
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips en = "Delete External Position", de = "Externe Position löschen", fr = "Supprimer la position externe"
							horizontalAlignment = center
							icon = application_form_delete
							id = D_UiL
							tid = 89504281838767
						{
							Event OnClick (submit)
							tid = 268288794360447
							messages en = "Are you sure to delete this external position ?", de = "Wollen Sie diese externe Position wirklich löschen?", fr = "Etes-vous sûr de vouloir supprimer cette position externe?"
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								widget-group-ref = form
								target = self
								param = "flow-action=deleteorder"
								modal = false
								only-changed = false
								prevalidate = false
								code = "<udp:item column=\"OPER_CODE\"/>" ud
							}
						}
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetVisible = false
				}
			}
			--- TableColumn ---
				column-name = QUANTITY !
				column-type = domain !
				domainAttribute = QUANTITY !
				id = QUANTITY
				table-column-width = 12
			{
				--- TableColumnItem ---
					item-column = QUANTITY
					format = decimal
					previewValue = value
			}
			--- TableColumn ---
				column-name = INSTR_NATURE !
				column-type = domain !
				domainAttribute = INSTR_NATURE !
				type = text
				id = INSTR_NATURE
				table-column-width = 12
			{
				--- TableColumnItem ---
					item-column = INSTR_NATURE
					previewValue = value
			}
			--- TableColumn ---
				column-name = INSTR_NAME_ISIN !
				column-type = domain !
				domainAttribute = INSTR_NAME_ISIN !
				type = text
				id = INSTR_NAME_ISIN
				table-column-width = 12
			{
				--- Icon ---
					icon = application_form_magnify
					id = w__63
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "resource:///administration/instrument/InstrumentQuickView.pageflow"
						target = popup
						code = "<udp:item column=\"INSTR_CODE\"/>" ud
						only-changed = false
						prevalidate = false
						modal = false
					}
				}
				--- Spacer ---
					height = 4
					width = 10
				--- TableColumnItem ---
					item-column = INSTR_NAME_ISIN
					previewValue = value
			}
			--- TableColumn ---
				labels en = Price, de = Preis, fr = Prix
				column-name = PRICE_CCY
				type = amount
				id = D2R__
				column-computation = make-amount
				column-computation-parameters = "PRICE,ORDER_CURRENCY"
				table-column-width = 12
				tid = 115597082119421
			{
				--- TableColumnItem ---
					item-column = PRICE_CCY
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Market Value", de = Marktwert, fr = "Valeur de marché"
				column-name = NET_AMOUNT
				type = amount
				id = t1V_w
				column-computation = make-amount
				column-computation-parameters = "ORDER_NET_AMOUNT,ORDER_CURRENCY"
				table-column-width = 12
				tid = 89504282822113
			{
				--- TableColumnItem ---
					item-column = NET_AMOUNT
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Market Value in Ptf Ccy", de = "Marktwert in Ptf Währ.", fr = "Valeur de marche exprimée en devise portefeuille"
				column-name = MARKET_VALUE_PTF_CCY
				type = amount
				id = z_nMx
				column-computation = make-amount
				column-computation-parameters = "ORDER_PTF_AMOUNT,PTF_CURRENCY"
				table-column-width = 12
				tid = 30064057298449
			{
				--- TableColumnItem ---
					item-column = MARKET_VALUE_PTF_CCY
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = ORDER_PTF_AMOUNT
				sort-direction = descending
				sort-rank = 1
			--- TableExtra ---
				domainAttribute = INSTR_CODE
			--- TableExtra ---
				domainAttribute = OPER_CODE
		}
		--- Grid ---
			cssClass = blank
			gridColumnCount = 2
			gridColumnsWidth = "25,25" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Button ---
					labels en = "Create Cash Position", de = "Geldposition erstellen", fr = "Créer une position cash"
					id = btn_jA_Zz
					tid = 89504280604673
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = neworder ud
						functionResult.id = "valueOf(form.functionResult.id)" ud
						portfolio.code = "valueOf(form.portfolio.code)" ud
						orderType.code = PCK_DS_EXT_POS_CASH ud
						externalPositionCreator = 1 ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
				--- Button ---
					labels en = "Create Security Position", de = "Wertpapierposition erstellen", fr = "Créer une position titre"
					id = btn_h_d06
					tid = 91184129953101
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = neworder ud
						functionResult.id = "valueOf(form.functionResult.id)" ud
						portfolio.code = "valueOf(form.portfolio.code)" ud
						externalPositionCreator = 1 ud
						orderType.code = PCK_DS_EXT_POS_SEC ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- GridCell ---
				gridColumnWidth = 25
		}
	}
}