# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Classification List", fr = "Liste de classification", de = Klassifizierungsliste
	domainEntity = "AAADSClassification:ClassificationList"
	bean-define = DSBean.AAADSClassification.ClassificationList
	bean-name = ClassificationList
	id = ClassificationList_k07Ff
	tid = 132678336891979
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			id = GR330
			table-column-count = 4 !
			table-columns-width = "25,25,25,25" !
		{
			--- TableColumn ---
				column-name = dictEntityName !
				column-type = domain !
				domainAttribute = dictEntityName !
				id = dictEntityName
				table-column-width = 25
			{
				--- TableColumnItem ---
					item-column = dictEntityName
					previewValue = value
			}
			--- TableColumn ---
				column-name = code !
				column-type = domain !
				domainAttribute = code !
				id = code
				table-column-width = 25
			{
				--- TableColumnItem ---
					item-column = code
					previewValue = value
			}
			--- TableColumn ---
				column-name = name !
				column-type = domain !
				domainAttribute = name !
				id = name
				table-column-width = 25
			{
				--- TableColumnItem ---
					item-column = name
					previewValue = value
			}
			--- TableColumn ---
				column-name = denom !
				column-type = domain !
				domainAttribute = denom !
				id = denom
				table-column-width = 25
			{
				--- TableColumnItem ---
					item-column = denom
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = dictEntityName
				sort-rank = 1
			--- TableSort ---
				sort-column-name = code
				sort-rank = 2
		}
	}
}