/*
 * generated by Xtext
 */
package com.odcgroup.t24.version.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

import com.google.inject.Binder;

/**
 * Use this class to register components to be used within the IDE.
 */
public class VersionDSLUiModule extends com.odcgroup.t24.version.ui.AbstractVersionDSLUiModule {
	public VersionDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	// contributed by org.eclipse.xtext.generator.builder.BuilderIntegrationFragment
	@Override
	public Class<? extends org.eclipse.xtext.ui.editor.IXtextEditorCallback> bindIXtextEditorCallback() {
		//DS-5701 suppressed the xtext nature popup
		return com.odcgroup.t24.version.ui.nature.VersionDSLNatureAddingEditorCallback.class;
	}
	
	@Override
	public void configureMarkOccurrencesAction(Binder binder) {
	}
}
