/**
 */
package com.odcgroup.t24.enquiry.enquiry.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;
import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import com.odcgroup.t24.enquiry.enquiry.util.EnquiryAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class EnquiryItemProviderAdapterFactory extends EnquiryAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EnquiryItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.Enquiry} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EnquiryItemProvider enquiryItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.Enquiry}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEnquiryAdapter() {
		if (enquiryItemProvider == null) {
			enquiryItemProvider = new EnquiryItemProvider(this);
		}

		return enquiryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.Companies} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CompaniesItemProvider companiesItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.Companies}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCompaniesAdapter() {
		if (companiesItemProvider == null) {
			companiesItemProvider = new CompaniesItemProvider(this);
		}

		return companiesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.EnquiryHeader} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EnquiryHeaderItemProvider enquiryHeaderItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.EnquiryHeader}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEnquiryHeaderAdapter() {
		if (enquiryHeaderItemProvider == null) {
			enquiryHeaderItemProvider = new EnquiryHeaderItemProvider(this);
		}

		return enquiryHeaderItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.Target} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TargetItemProvider targetItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.Target}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTargetAdapter() {
		if (targetItemProvider == null) {
			targetItemProvider = new TargetItemProvider(this);
		}

		return targetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.TargetMapping} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TargetMappingItemProvider targetMappingItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.TargetMapping}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTargetMappingAdapter() {
		if (targetMappingItemProvider == null) {
			targetMappingItemProvider = new TargetMappingItemProvider(this);
		}

		return targetMappingItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.Parameters} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ParametersItemProvider parametersItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.Parameters}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createParametersAdapter() {
		if (parametersItemProvider == null) {
			parametersItemProvider = new ParametersItemProvider(this);
		}

		return parametersItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.DrillDown} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DrillDownItemProvider drillDownItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.DrillDown}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDrillDownAdapter() {
		if (drillDownItemProvider == null) {
			drillDownItemProvider = new DrillDownItemProvider(this);
		}

		return drillDownItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.DrillDownType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DrillDownTypeItemProvider drillDownTypeItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.DrillDownType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDrillDownTypeAdapter() {
		if (drillDownTypeItemProvider == null) {
			drillDownTypeItemProvider = new DrillDownTypeItemProvider(this);
		}

		return drillDownTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.DrillDownStringType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DrillDownStringTypeItemProvider drillDownStringTypeItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.DrillDownStringType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDrillDownStringTypeAdapter() {
		if (drillDownStringTypeItemProvider == null) {
			drillDownStringTypeItemProvider = new DrillDownStringTypeItemProvider(this);
		}

		return drillDownStringTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.ApplicationType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ApplicationTypeItemProvider applicationTypeItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.ApplicationType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createApplicationTypeAdapter() {
		if (applicationTypeItemProvider == null) {
			applicationTypeItemProvider = new ApplicationTypeItemProvider(this);
		}

		return applicationTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.ScreenType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ScreenTypeItemProvider screenTypeItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.ScreenType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createScreenTypeAdapter() {
		if (screenTypeItemProvider == null) {
			screenTypeItemProvider = new ScreenTypeItemProvider(this);
		}

		return screenTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.EnquiryType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EnquiryTypeItemProvider enquiryTypeItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.EnquiryType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEnquiryTypeAdapter() {
		if (enquiryTypeItemProvider == null) {
			enquiryTypeItemProvider = new EnquiryTypeItemProvider(this);
		}

		return enquiryTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.FromFieldType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FromFieldTypeItemProvider fromFieldTypeItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.FromFieldType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFromFieldTypeAdapter() {
		if (fromFieldTypeItemProvider == null) {
			fromFieldTypeItemProvider = new FromFieldTypeItemProvider(this);
		}

		return fromFieldTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.CompositeScreenType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CompositeScreenTypeItemProvider compositeScreenTypeItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.CompositeScreenType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCompositeScreenTypeAdapter() {
		if (compositeScreenTypeItemProvider == null) {
			compositeScreenTypeItemProvider = new CompositeScreenTypeItemProvider(this);
		}

		return compositeScreenTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.TabbedScreenType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TabbedScreenTypeItemProvider tabbedScreenTypeItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.TabbedScreenType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTabbedScreenTypeAdapter() {
		if (tabbedScreenTypeItemProvider == null) {
			tabbedScreenTypeItemProvider = new TabbedScreenTypeItemProvider(this);
		}

		return tabbedScreenTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.ViewType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ViewTypeItemProvider viewTypeItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.ViewType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createViewTypeAdapter() {
		if (viewTypeItemProvider == null) {
			viewTypeItemProvider = new ViewTypeItemProvider(this);
		}

		return viewTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.QuitSEEType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected QuitSEETypeItemProvider quitSEETypeItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.QuitSEEType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createQuitSEETypeAdapter() {
		if (quitSEETypeItemProvider == null) {
			quitSEETypeItemProvider = new QuitSEETypeItemProvider(this);
		}

		return quitSEETypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.BlankType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BlankTypeItemProvider blankTypeItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.BlankType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBlankTypeAdapter() {
		if (blankTypeItemProvider == null) {
			blankTypeItemProvider = new BlankTypeItemProvider(this);
		}

		return blankTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.PWProcessType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PWProcessTypeItemProvider pwProcessTypeItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.PWProcessType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPWProcessTypeAdapter() {
		if (pwProcessTypeItemProvider == null) {
			pwProcessTypeItemProvider = new PWProcessTypeItemProvider(this);
		}

		return pwProcessTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.DownloadType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DownloadTypeItemProvider downloadTypeItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.DownloadType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDownloadTypeAdapter() {
		if (downloadTypeItemProvider == null) {
			downloadTypeItemProvider = new DownloadTypeItemProvider(this);
		}

		return downloadTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.RunType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RunTypeItemProvider runTypeItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.RunType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRunTypeAdapter() {
		if (runTypeItemProvider == null) {
			runTypeItemProvider = new RunTypeItemProvider(this);
		}

		return runTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.UtilType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UtilTypeItemProvider utilTypeItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.UtilType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUtilTypeAdapter() {
		if (utilTypeItemProvider == null) {
			utilTypeItemProvider = new UtilTypeItemProvider(this);
		}

		return utilTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.JavaScriptType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected JavaScriptTypeItemProvider javaScriptTypeItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.JavaScriptType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createJavaScriptTypeAdapter() {
		if (javaScriptTypeItemProvider == null) {
			javaScriptTypeItemProvider = new JavaScriptTypeItemProvider(this);
		}

		return javaScriptTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.ShouldBeChangedType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ShouldBeChangedTypeItemProvider shouldBeChangedTypeItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.ShouldBeChangedType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createShouldBeChangedTypeAdapter() {
		if (shouldBeChangedTypeItemProvider == null) {
			shouldBeChangedTypeItemProvider = new ShouldBeChangedTypeItemProvider(this);
		}

		return shouldBeChangedTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.DrillDownOption} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DrillDownOptionItemProvider drillDownOptionItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.DrillDownOption}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDrillDownOptionAdapter() {
		if (drillDownOptionItemProvider == null) {
			drillDownOptionItemProvider = new DrillDownOptionItemProvider(this);
		}

		return drillDownOptionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.CompositeScreenOption} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CompositeScreenOptionItemProvider compositeScreenOptionItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.CompositeScreenOption}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCompositeScreenOptionAdapter() {
		if (compositeScreenOptionItemProvider == null) {
			compositeScreenOptionItemProvider = new CompositeScreenOptionItemProvider(this);
		}

		return compositeScreenOptionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.TabOption} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TabOptionItemProvider tabOptionItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.TabOption}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTabOptionAdapter() {
		if (tabOptionItemProvider == null) {
			tabOptionItemProvider = new TabOptionItemProvider(this);
		}

		return tabOptionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.ViewOption} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ViewOptionItemProvider viewOptionItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.ViewOption}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createViewOptionAdapter() {
		if (viewOptionItemProvider == null) {
			viewOptionItemProvider = new ViewOptionItemProvider(this);
		}

		return viewOptionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.QuitSEEOption} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected QuitSEEOptionItemProvider quitSEEOptionItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.QuitSEEOption}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createQuitSEEOptionAdapter() {
		if (quitSEEOptionItemProvider == null) {
			quitSEEOptionItemProvider = new QuitSEEOptionItemProvider(this);
		}

		return quitSEEOptionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.Reference} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReferenceItemProvider referenceItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.Reference}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReferenceAdapter() {
		if (referenceItemProvider == null) {
			referenceItemProvider = new ReferenceItemProvider(this);
		}

		return referenceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.Parameter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ParameterItemProvider parameterItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.Parameter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createParameterAdapter() {
		if (parameterItemProvider == null) {
			parameterItemProvider = new ParameterItemProvider(this);
		}

		return parameterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.SelectionCriteria} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SelectionCriteriaItemProvider selectionCriteriaItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.SelectionCriteria}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSelectionCriteriaAdapter() {
		if (selectionCriteriaItemProvider == null) {
			selectionCriteriaItemProvider = new SelectionCriteriaItemProvider(this);
		}

		return selectionCriteriaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.Security} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SecurityItemProvider securityItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.Security}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSecurityAdapter() {
		if (securityItemProvider == null) {
			securityItemProvider = new SecurityItemProvider(this);
		}

		return securityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.Graph} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GraphItemProvider graphItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.Graph}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGraphAdapter() {
		if (graphItemProvider == null) {
			graphItemProvider = new GraphItemProvider(this);
		}

		return graphItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.Axis} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AxisItemProvider axisItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.Axis}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAxisAdapter() {
		if (axisItemProvider == null) {
			axisItemProvider = new AxisItemProvider(this);
		}

		return axisItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.Dimension} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DimensionItemProvider dimensionItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.Dimension}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDimensionAdapter() {
		if (dimensionItemProvider == null) {
			dimensionItemProvider = new DimensionItemProvider(this);
		}

		return dimensionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.Label} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LabelItemProvider labelItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.Label}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLabelAdapter() {
		if (labelItemProvider == null) {
			labelItemProvider = new LabelItemProvider(this);
		}

		return labelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.Position} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PositionItemProvider positionItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.Position}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPositionAdapter() {
		if (positionItemProvider == null) {
			positionItemProvider = new PositionItemProvider(this);
		}

		return positionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.Legend} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LegendItemProvider legendItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.Legend}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLegendAdapter() {
		if (legendItemProvider == null) {
			legendItemProvider = new LegendItemProvider(this);
		}

		return legendItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.Margins} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MarginsItemProvider marginsItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.Margins}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMarginsAdapter() {
		if (marginsItemProvider == null) {
			marginsItemProvider = new MarginsItemProvider(this);
		}

		return marginsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.Scale} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ScaleItemProvider scaleItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.Scale}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createScaleAdapter() {
		if (scaleItemProvider == null) {
			scaleItemProvider = new ScaleItemProvider(this);
		}

		return scaleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.Routine} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RoutineItemProvider routineItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.Routine}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRoutineAdapter() {
		if (routineItemProvider == null) {
			routineItemProvider = new RoutineItemProvider(this);
		}

		return routineItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.JBCRoutine} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected JBCRoutineItemProvider jbcRoutineItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.JBCRoutine}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createJBCRoutineAdapter() {
		if (jbcRoutineItemProvider == null) {
			jbcRoutineItemProvider = new JBCRoutineItemProvider(this);
		}

		return jbcRoutineItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.JavaRoutine} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected JavaRoutineItemProvider javaRoutineItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.JavaRoutine}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createJavaRoutineAdapter() {
		if (javaRoutineItemProvider == null) {
			javaRoutineItemProvider = new JavaRoutineItemProvider(this);
		}

		return javaRoutineItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.FixedSelection} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FixedSelectionItemProvider fixedSelectionItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.FixedSelection}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFixedSelectionAdapter() {
		if (fixedSelectionItemProvider == null) {
			fixedSelectionItemProvider = new FixedSelectionItemProvider(this);
		}

		return fixedSelectionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.FixedSort} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FixedSortItemProvider fixedSortItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.FixedSort}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFixedSortAdapter() {
		if (fixedSortItemProvider == null) {
			fixedSortItemProvider = new FixedSortItemProvider(this);
		}

		return fixedSortItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.SelectionExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SelectionExpressionItemProvider selectionExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.SelectionExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSelectionExpressionAdapter() {
		if (selectionExpressionItemProvider == null) {
			selectionExpressionItemProvider = new SelectionExpressionItemProvider(this);
		}

		return selectionExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.Selection} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SelectionItemProvider selectionItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.Selection}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSelectionAdapter() {
		if (selectionItemProvider == null) {
			selectionItemProvider = new SelectionItemProvider(this);
		}

		return selectionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.FileVersion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FileVersionItemProvider fileVersionItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.FileVersion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFileVersionAdapter() {
		if (fileVersionItemProvider == null) {
			fileVersionItemProvider = new FileVersionItemProvider(this);
		}

		return fileVersionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.Operation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OperationItemProvider operationItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.Operation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOperationAdapter() {
		if (operationItemProvider == null) {
			operationItemProvider = new OperationItemProvider(this);
		}

		return operationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.BreakOperation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BreakOperationItemProvider breakOperationItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.BreakOperation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBreakOperationAdapter() {
		if (breakOperationItemProvider == null) {
			breakOperationItemProvider = new BreakOperationItemProvider(this);
		}

		return breakOperationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.BreakOnChangeOperation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BreakOnChangeOperationItemProvider breakOnChangeOperationItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.BreakOnChangeOperation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBreakOnChangeOperationAdapter() {
		if (breakOnChangeOperationItemProvider == null) {
			breakOnChangeOperationItemProvider = new BreakOnChangeOperationItemProvider(this);
		}

		return breakOnChangeOperationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.BreakLineOperation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BreakLineOperationItemProvider breakLineOperationItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.BreakLineOperation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBreakLineOperationAdapter() {
		if (breakLineOperationItemProvider == null) {
			breakLineOperationItemProvider = new BreakLineOperationItemProvider(this);
		}

		return breakLineOperationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.CalcOperation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CalcOperationItemProvider calcOperationItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.CalcOperation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCalcOperationAdapter() {
		if (calcOperationItemProvider == null) {
			calcOperationItemProvider = new CalcOperationItemProvider(this);
		}

		return calcOperationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.ConstantOperation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConstantOperationItemProvider constantOperationItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.ConstantOperation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConstantOperationAdapter() {
		if (constantOperationItemProvider == null) {
			constantOperationItemProvider = new ConstantOperationItemProvider(this);
		}

		return constantOperationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.LabelOperation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LabelOperationItemProvider labelOperationItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.LabelOperation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLabelOperationAdapter() {
		if (labelOperationItemProvider == null) {
			labelOperationItemProvider = new LabelOperationItemProvider(this);
		}

		return labelOperationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.DateOperation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DateOperationItemProvider dateOperationItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.DateOperation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDateOperationAdapter() {
		if (dateOperationItemProvider == null) {
			dateOperationItemProvider = new DateOperationItemProvider(this);
		}

		return dateOperationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.DecisionOperation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DecisionOperationItemProvider decisionOperationItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.DecisionOperation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDecisionOperationAdapter() {
		if (decisionOperationItemProvider == null) {
			decisionOperationItemProvider = new DecisionOperationItemProvider(this);
		}

		return decisionOperationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.DescriptorOperation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DescriptorOperationItemProvider descriptorOperationItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.DescriptorOperation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDescriptorOperationAdapter() {
		if (descriptorOperationItemProvider == null) {
			descriptorOperationItemProvider = new DescriptorOperationItemProvider(this);
		}

		return descriptorOperationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.TodayOperation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TodayOperationItemProvider todayOperationItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.TodayOperation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTodayOperationAdapter() {
		if (todayOperationItemProvider == null) {
			todayOperationItemProvider = new TodayOperationItemProvider(this);
		}

		return todayOperationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.LWDOperation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LWDOperationItemProvider lwdOperationItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.LWDOperation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLWDOperationAdapter() {
		if (lwdOperationItemProvider == null) {
			lwdOperationItemProvider = new LWDOperationItemProvider(this);
		}

		return lwdOperationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.NWDOperation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NWDOperationItemProvider nwdOperationItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.NWDOperation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNWDOperationAdapter() {
		if (nwdOperationItemProvider == null) {
			nwdOperationItemProvider = new NWDOperationItemProvider(this);
		}

		return nwdOperationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.FieldOperation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FieldOperationItemProvider fieldOperationItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.FieldOperation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFieldOperationAdapter() {
		if (fieldOperationItemProvider == null) {
			fieldOperationItemProvider = new FieldOperationItemProvider(this);
		}

		return fieldOperationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.ApplicationFieldNameOperation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ApplicationFieldNameOperationItemProvider applicationFieldNameOperationItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.ApplicationFieldNameOperation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createApplicationFieldNameOperationAdapter() {
		if (applicationFieldNameOperationItemProvider == null) {
			applicationFieldNameOperationItemProvider = new ApplicationFieldNameOperationItemProvider(this);
		}

		return applicationFieldNameOperationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.FieldNumberOperation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FieldNumberOperationItemProvider fieldNumberOperationItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.FieldNumberOperation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFieldNumberOperationAdapter() {
		if (fieldNumberOperationItemProvider == null) {
			fieldNumberOperationItemProvider = new FieldNumberOperationItemProvider(this);
		}

		return fieldNumberOperationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.FieldExtractOperation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FieldExtractOperationItemProvider fieldExtractOperationItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.FieldExtractOperation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFieldExtractOperationAdapter() {
		if (fieldExtractOperationItemProvider == null) {
			fieldExtractOperationItemProvider = new FieldExtractOperationItemProvider(this);
		}

		return fieldExtractOperationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.SelectionOperation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SelectionOperationItemProvider selectionOperationItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.SelectionOperation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSelectionOperationAdapter() {
		if (selectionOperationItemProvider == null) {
			selectionOperationItemProvider = new SelectionOperationItemProvider(this);
		}

		return selectionOperationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.SystemOperation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SystemOperationItemProvider systemOperationItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.SystemOperation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSystemOperationAdapter() {
		if (systemOperationItemProvider == null) {
			systemOperationItemProvider = new SystemOperationItemProvider(this);
		}

		return systemOperationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.UserOperation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UserOperationItemProvider userOperationItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.UserOperation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUserOperationAdapter() {
		if (userOperationItemProvider == null) {
			userOperationItemProvider = new UserOperationItemProvider(this);
		}

		return userOperationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.CompanyOperation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CompanyOperationItemProvider companyOperationItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.CompanyOperation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCompanyOperationAdapter() {
		if (companyOperationItemProvider == null) {
			companyOperationItemProvider = new CompanyOperationItemProvider(this);
		}

		return companyOperationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.LanguageOperation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LanguageOperationItemProvider languageOperationItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.LanguageOperation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLanguageOperationAdapter() {
		if (languageOperationItemProvider == null) {
			languageOperationItemProvider = new LanguageOperationItemProvider(this);
		}

		return languageOperationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.LocalCurrencyOperation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LocalCurrencyOperationItemProvider localCurrencyOperationItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.LocalCurrencyOperation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLocalCurrencyOperationAdapter() {
		if (localCurrencyOperationItemProvider == null) {
			localCurrencyOperationItemProvider = new LocalCurrencyOperationItemProvider(this);
		}

		return localCurrencyOperationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.TotalOperation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TotalOperationItemProvider totalOperationItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.TotalOperation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTotalOperationAdapter() {
		if (totalOperationItemProvider == null) {
			totalOperationItemProvider = new TotalOperationItemProvider(this);
		}

		return totalOperationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.Conversion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConversionItemProvider conversionItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.Conversion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConversionAdapter() {
		if (conversionItemProvider == null) {
			conversionItemProvider = new ConversionItemProvider(this);
		}

		return conversionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.ExtractConversion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExtractConversionItemProvider extractConversionItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.ExtractConversion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExtractConversionAdapter() {
		if (extractConversionItemProvider == null) {
			extractConversionItemProvider = new ExtractConversionItemProvider(this);
		}

		return extractConversionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.DecryptConversion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DecryptConversionItemProvider decryptConversionItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.DecryptConversion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDecryptConversionAdapter() {
		if (decryptConversionItemProvider == null) {
			decryptConversionItemProvider = new DecryptConversionItemProvider(this);
		}

		return decryptConversionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.ReplaceConversion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReplaceConversionItemProvider replaceConversionItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.ReplaceConversion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReplaceConversionAdapter() {
		if (replaceConversionItemProvider == null) {
			replaceConversionItemProvider = new ReplaceConversionItemProvider(this);
		}

		return replaceConversionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.ConvertConversion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConvertConversionItemProvider convertConversionItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.ConvertConversion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConvertConversionAdapter() {
		if (convertConversionItemProvider == null) {
			convertConversionItemProvider = new ConvertConversionItemProvider(this);
		}

		return convertConversionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.ValueConversion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ValueConversionItemProvider valueConversionItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.ValueConversion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createValueConversionAdapter() {
		if (valueConversionItemProvider == null) {
			valueConversionItemProvider = new ValueConversionItemProvider(this);
		}

		return valueConversionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.JulianConversion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected JulianConversionItemProvider julianConversionItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.JulianConversion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createJulianConversionAdapter() {
		if (julianConversionItemProvider == null) {
			julianConversionItemProvider = new JulianConversionItemProvider(this);
		}

		return julianConversionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.BasicConversion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BasicConversionItemProvider basicConversionItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.BasicConversion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBasicConversionAdapter() {
		if (basicConversionItemProvider == null) {
			basicConversionItemProvider = new BasicConversionItemProvider(this);
		}

		return basicConversionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.BasicOConversion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BasicOConversionItemProvider basicOConversionItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.BasicOConversion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBasicOConversionAdapter() {
		if (basicOConversionItemProvider == null) {
			basicOConversionItemProvider = new BasicOConversionItemProvider(this);
		}

		return basicOConversionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.BasicIConversion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BasicIConversionItemProvider basicIConversionItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.BasicIConversion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBasicIConversionAdapter() {
		if (basicIConversionItemProvider == null) {
			basicIConversionItemProvider = new BasicIConversionItemProvider(this);
		}

		return basicIConversionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.GetFromConversion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GetFromConversionItemProvider getFromConversionItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.GetFromConversion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGetFromConversionAdapter() {
		if (getFromConversionItemProvider == null) {
			getFromConversionItemProvider = new GetFromConversionItemProvider(this);
		}

		return getFromConversionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.RateConversion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RateConversionItemProvider rateConversionItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.RateConversion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRateConversionAdapter() {
		if (rateConversionItemProvider == null) {
			rateConversionItemProvider = new RateConversionItemProvider(this);
		}

		return rateConversionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.CalcFixedRateConversion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CalcFixedRateConversionItemProvider calcFixedRateConversionItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.CalcFixedRateConversion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCalcFixedRateConversionAdapter() {
		if (calcFixedRateConversionItemProvider == null) {
			calcFixedRateConversionItemProvider = new CalcFixedRateConversionItemProvider(this);
		}

		return calcFixedRateConversionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.GetFixedRateConversion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GetFixedRateConversionItemProvider getFixedRateConversionItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.GetFixedRateConversion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGetFixedRateConversionAdapter() {
		if (getFixedRateConversionItemProvider == null) {
			getFixedRateConversionItemProvider = new GetFixedRateConversionItemProvider(this);
		}

		return getFixedRateConversionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.GetFixedCurrencyConversion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GetFixedCurrencyConversionItemProvider getFixedCurrencyConversionItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.GetFixedCurrencyConversion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGetFixedCurrencyConversionAdapter() {
		if (getFixedCurrencyConversionItemProvider == null) {
			getFixedCurrencyConversionItemProvider = new GetFixedCurrencyConversionItemProvider(this);
		}

		return getFixedCurrencyConversionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.AbsConversion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AbsConversionItemProvider absConversionItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.AbsConversion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAbsConversionAdapter() {
		if (absConversionItemProvider == null) {
			absConversionItemProvider = new AbsConversionItemProvider(this);
		}

		return absConversionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.MatchField} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MatchFieldItemProvider matchFieldItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.MatchField}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMatchFieldAdapter() {
		if (matchFieldItemProvider == null) {
			matchFieldItemProvider = new MatchFieldItemProvider(this);
		}

		return matchFieldItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.CallRoutine} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CallRoutineItemProvider callRoutineItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.CallRoutine}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCallRoutineAdapter() {
		if (callRoutineItemProvider == null) {
			callRoutineItemProvider = new CallRoutineItemProvider(this);
		}

		return callRoutineItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.RepeatConversion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RepeatConversionItemProvider repeatConversionItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.RepeatConversion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRepeatConversionAdapter() {
		if (repeatConversionItemProvider == null) {
			repeatConversionItemProvider = new RepeatConversionItemProvider(this);
		}

		return repeatConversionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.RepeatOnNullConversion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RepeatOnNullConversionItemProvider repeatOnNullConversionItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.RepeatOnNullConversion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRepeatOnNullConversionAdapter() {
		if (repeatOnNullConversionItemProvider == null) {
			repeatOnNullConversionItemProvider = new RepeatOnNullConversionItemProvider(this);
		}

		return repeatOnNullConversionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.RepeatEveryConversion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RepeatEveryConversionItemProvider repeatEveryConversionItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.RepeatEveryConversion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRepeatEveryConversionAdapter() {
		if (repeatEveryConversionItemProvider == null) {
			repeatEveryConversionItemProvider = new RepeatEveryConversionItemProvider(this);
		}

		return repeatEveryConversionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.RepeatSubConversion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RepeatSubConversionItemProvider repeatSubConversionItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.RepeatSubConversion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRepeatSubConversionAdapter() {
		if (repeatSubConversionItemProvider == null) {
			repeatSubConversionItemProvider = new RepeatSubConversionItemProvider(this);
		}

		return repeatSubConversionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.Field} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FieldItemProvider fieldItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.Field}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFieldAdapter() {
		if (fieldItemProvider == null) {
			fieldItemProvider = new FieldItemProvider(this);
		}

		return fieldItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.BreakCondition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BreakConditionItemProvider breakConditionItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.BreakCondition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBreakConditionAdapter() {
		if (breakConditionItemProvider == null) {
			breakConditionItemProvider = new BreakConditionItemProvider(this);
		}

		return breakConditionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.FieldPosition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FieldPositionItemProvider fieldPositionItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.FieldPosition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFieldPositionAdapter() {
		if (fieldPositionItemProvider == null) {
			fieldPositionItemProvider = new FieldPositionItemProvider(this);
		}

		return fieldPositionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.Format} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FormatItemProvider formatItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.Format}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFormatAdapter() {
		if (formatItemProvider == null) {
			formatItemProvider = new FormatItemProvider(this);
		}

		return formatItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.Tool} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ToolItemProvider toolItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.Tool}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createToolAdapter() {
		if (toolItemProvider == null) {
			toolItemProvider = new ToolItemProvider(this);
		}

		return toolItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.odcgroup.t24.enquiry.enquiry.WebService} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WebServiceItemProvider webServiceItemProvider;

	/**
	 * This creates an adapter for a {@link com.odcgroup.t24.enquiry.enquiry.WebService}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWebServiceAdapter() {
		if (webServiceItemProvider == null) {
			webServiceItemProvider = new WebServiceItemProvider(this);
		}

		return webServiceItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (enquiryItemProvider != null) enquiryItemProvider.dispose();
		if (companiesItemProvider != null) companiesItemProvider.dispose();
		if (enquiryHeaderItemProvider != null) enquiryHeaderItemProvider.dispose();
		if (targetItemProvider != null) targetItemProvider.dispose();
		if (targetMappingItemProvider != null) targetMappingItemProvider.dispose();
		if (parametersItemProvider != null) parametersItemProvider.dispose();
		if (drillDownItemProvider != null) drillDownItemProvider.dispose();
		if (drillDownTypeItemProvider != null) drillDownTypeItemProvider.dispose();
		if (drillDownStringTypeItemProvider != null) drillDownStringTypeItemProvider.dispose();
		if (applicationTypeItemProvider != null) applicationTypeItemProvider.dispose();
		if (screenTypeItemProvider != null) screenTypeItemProvider.dispose();
		if (enquiryTypeItemProvider != null) enquiryTypeItemProvider.dispose();
		if (fromFieldTypeItemProvider != null) fromFieldTypeItemProvider.dispose();
		if (compositeScreenTypeItemProvider != null) compositeScreenTypeItemProvider.dispose();
		if (tabbedScreenTypeItemProvider != null) tabbedScreenTypeItemProvider.dispose();
		if (viewTypeItemProvider != null) viewTypeItemProvider.dispose();
		if (quitSEETypeItemProvider != null) quitSEETypeItemProvider.dispose();
		if (blankTypeItemProvider != null) blankTypeItemProvider.dispose();
		if (pwProcessTypeItemProvider != null) pwProcessTypeItemProvider.dispose();
		if (downloadTypeItemProvider != null) downloadTypeItemProvider.dispose();
		if (runTypeItemProvider != null) runTypeItemProvider.dispose();
		if (utilTypeItemProvider != null) utilTypeItemProvider.dispose();
		if (javaScriptTypeItemProvider != null) javaScriptTypeItemProvider.dispose();
		if (shouldBeChangedTypeItemProvider != null) shouldBeChangedTypeItemProvider.dispose();
		if (drillDownOptionItemProvider != null) drillDownOptionItemProvider.dispose();
		if (compositeScreenOptionItemProvider != null) compositeScreenOptionItemProvider.dispose();
		if (tabOptionItemProvider != null) tabOptionItemProvider.dispose();
		if (viewOptionItemProvider != null) viewOptionItemProvider.dispose();
		if (quitSEEOptionItemProvider != null) quitSEEOptionItemProvider.dispose();
		if (referenceItemProvider != null) referenceItemProvider.dispose();
		if (parameterItemProvider != null) parameterItemProvider.dispose();
		if (selectionCriteriaItemProvider != null) selectionCriteriaItemProvider.dispose();
		if (securityItemProvider != null) securityItemProvider.dispose();
		if (graphItemProvider != null) graphItemProvider.dispose();
		if (axisItemProvider != null) axisItemProvider.dispose();
		if (dimensionItemProvider != null) dimensionItemProvider.dispose();
		if (labelItemProvider != null) labelItemProvider.dispose();
		if (positionItemProvider != null) positionItemProvider.dispose();
		if (legendItemProvider != null) legendItemProvider.dispose();
		if (marginsItemProvider != null) marginsItemProvider.dispose();
		if (scaleItemProvider != null) scaleItemProvider.dispose();
		if (routineItemProvider != null) routineItemProvider.dispose();
		if (jbcRoutineItemProvider != null) jbcRoutineItemProvider.dispose();
		if (javaRoutineItemProvider != null) javaRoutineItemProvider.dispose();
		if (fixedSelectionItemProvider != null) fixedSelectionItemProvider.dispose();
		if (fixedSortItemProvider != null) fixedSortItemProvider.dispose();
		if (selectionExpressionItemProvider != null) selectionExpressionItemProvider.dispose();
		if (selectionItemProvider != null) selectionItemProvider.dispose();
		if (fileVersionItemProvider != null) fileVersionItemProvider.dispose();
		if (operationItemProvider != null) operationItemProvider.dispose();
		if (breakOperationItemProvider != null) breakOperationItemProvider.dispose();
		if (breakOnChangeOperationItemProvider != null) breakOnChangeOperationItemProvider.dispose();
		if (breakLineOperationItemProvider != null) breakLineOperationItemProvider.dispose();
		if (calcOperationItemProvider != null) calcOperationItemProvider.dispose();
		if (constantOperationItemProvider != null) constantOperationItemProvider.dispose();
		if (labelOperationItemProvider != null) labelOperationItemProvider.dispose();
		if (dateOperationItemProvider != null) dateOperationItemProvider.dispose();
		if (decisionOperationItemProvider != null) decisionOperationItemProvider.dispose();
		if (descriptorOperationItemProvider != null) descriptorOperationItemProvider.dispose();
		if (todayOperationItemProvider != null) todayOperationItemProvider.dispose();
		if (lwdOperationItemProvider != null) lwdOperationItemProvider.dispose();
		if (nwdOperationItemProvider != null) nwdOperationItemProvider.dispose();
		if (fieldOperationItemProvider != null) fieldOperationItemProvider.dispose();
		if (applicationFieldNameOperationItemProvider != null) applicationFieldNameOperationItemProvider.dispose();
		if (fieldNumberOperationItemProvider != null) fieldNumberOperationItemProvider.dispose();
		if (fieldExtractOperationItemProvider != null) fieldExtractOperationItemProvider.dispose();
		if (selectionOperationItemProvider != null) selectionOperationItemProvider.dispose();
		if (systemOperationItemProvider != null) systemOperationItemProvider.dispose();
		if (userOperationItemProvider != null) userOperationItemProvider.dispose();
		if (companyOperationItemProvider != null) companyOperationItemProvider.dispose();
		if (languageOperationItemProvider != null) languageOperationItemProvider.dispose();
		if (localCurrencyOperationItemProvider != null) localCurrencyOperationItemProvider.dispose();
		if (totalOperationItemProvider != null) totalOperationItemProvider.dispose();
		if (conversionItemProvider != null) conversionItemProvider.dispose();
		if (extractConversionItemProvider != null) extractConversionItemProvider.dispose();
		if (decryptConversionItemProvider != null) decryptConversionItemProvider.dispose();
		if (replaceConversionItemProvider != null) replaceConversionItemProvider.dispose();
		if (convertConversionItemProvider != null) convertConversionItemProvider.dispose();
		if (valueConversionItemProvider != null) valueConversionItemProvider.dispose();
		if (julianConversionItemProvider != null) julianConversionItemProvider.dispose();
		if (basicConversionItemProvider != null) basicConversionItemProvider.dispose();
		if (basicOConversionItemProvider != null) basicOConversionItemProvider.dispose();
		if (basicIConversionItemProvider != null) basicIConversionItemProvider.dispose();
		if (getFromConversionItemProvider != null) getFromConversionItemProvider.dispose();
		if (rateConversionItemProvider != null) rateConversionItemProvider.dispose();
		if (calcFixedRateConversionItemProvider != null) calcFixedRateConversionItemProvider.dispose();
		if (getFixedRateConversionItemProvider != null) getFixedRateConversionItemProvider.dispose();
		if (getFixedCurrencyConversionItemProvider != null) getFixedCurrencyConversionItemProvider.dispose();
		if (absConversionItemProvider != null) absConversionItemProvider.dispose();
		if (matchFieldItemProvider != null) matchFieldItemProvider.dispose();
		if (callRoutineItemProvider != null) callRoutineItemProvider.dispose();
		if (repeatConversionItemProvider != null) repeatConversionItemProvider.dispose();
		if (repeatOnNullConversionItemProvider != null) repeatOnNullConversionItemProvider.dispose();
		if (repeatEveryConversionItemProvider != null) repeatEveryConversionItemProvider.dispose();
		if (repeatSubConversionItemProvider != null) repeatSubConversionItemProvider.dispose();
		if (fieldItemProvider != null) fieldItemProvider.dispose();
		if (breakConditionItemProvider != null) breakConditionItemProvider.dispose();
		if (fieldPositionItemProvider != null) fieldPositionItemProvider.dispose();
		if (formatItemProvider != null) formatItemProvider.dispose();
		if (toolItemProvider != null) toolItemProvider.dispose();
		if (webServiceItemProvider != null) webServiceItemProvider.dispose();
	}

}
