# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSIncomeEvent:IncomeEventList"
	cssClass = nodeco
	bean-define = DSBean.AAADSIncomeEvent.IncomeEventList
	bean-name = IncomeEventList
	id = IncomeEventDividendsList_h9Ti_
{
	--- Box ---
		labels en = Dividends, de = Dividenden, fr = Dividendes
		boxType = vertical
		widgetBorder = box
		width = 0
		tid = 610367240074367
	{
		--- TableTree ---
			table-filter-layer = true
			id = n1ku_
			table-column-count = 13 !
			table-columns-width = "7,7,7,7,7,7,7,7,7,7,7,7,7" !
		{
			--- TableColumn ---
				column-name = validityD !
				column-type = domain !
				domainAttribute = validityD !
				column-locked = true
				id = validityD
				table-column-width = 7
			{
				--- TableColumnItem ---
					item-column = validityD
					format = date
					previewValue = value
			}
			--- TableColumn ---
				column-name = beginD !
				column-type = domain !
				domainAttribute = beginD !
				id = beginD
				table-column-width = 7
			{
				--- TableColumnItem ---
					item-column = beginD
					format = date
					previewValue = value
			}
			--- TableColumn ---
				column-name = natureE !
				column-type = domain !
				domainAttribute = natureE !
				id = natureE
				table-column-width = 7
			{
				--- TableColumnItem ---
					item-column = natureE
					previewValue = value
			}
			--- TableColumn ---
				column-name = dividendN !
				column-type = domain !
				domainAttribute = dividendN !
				type = text
				id = dividendN
				table-column-width = 7
			{
				--- TableColumnItem ---
					item-column = dividendN
					format = decimal.detailed
					previewValue = value
			}
			--- TableColumn ---
				column-name = currencyCode !
				column-type = domain !
				domainAttribute = currencyCode !
				type = text
				id = currencyCode
				table-column-width = 7
			{
				--- TableColumnItem ---
					item-column = currencyCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = fixedExchRate !
				column-type = domain !
				domainAttribute = fixedExchRate !
				type = text
				id = fixedExchRate
				table-column-width = 7
			{
				--- TableColumnItem ---
					item-column = fixedExchRate
					format = decimal.detailed
					previewValue = value
			}
			--- TableColumn ---
				column-name = endValidityD !
				column-type = domain !
				domainAttribute = endValidityD !
				type = text
				id = endValidityD
				table-column-width = 7
			{
				--- TableColumnItem ---
					item-column = endValidityD
					format = date
					previewValue = value
			}
			--- TableColumn ---
				column-name = payFreqN !
				column-type = domain !
				domainAttribute = payFreqN !
				type = text
				column-visibility = not-visible
				id = payFreqN
				table-column-width = 7
			{
				--- TableColumnItem ---
					item-column = payFreqN
					format = integer
					previewValue = value
			}
			--- TableColumn ---
				column-name = payFreqUnitE !
				column-type = domain !
				domainAttribute = payFreqUnitE !
				type = text
				column-visibility = not-visible
				id = payFreqUnitE
				table-column-width = 7
			{
				--- TableColumnItem ---
					item-column = payFreqUnitE
					previewValue = value
			}
			--- TableColumn ---
				column-name = lastPayD !
				column-type = domain !
				domainAttribute = lastPayD !
				type = text
				column-visibility = not-visible
				id = lastPayD
				table-column-width = 7
			{
				--- TableColumnItem ---
					item-column = lastPayD
					format = date
					previewValue = value
			}
			--- TableColumn ---
				column-name = firstExD !
				column-type = domain !
				domainAttribute = firstExD !
				type = text
				column-visibility = not-visible
				id = firstExD
				table-column-width = 7
			{
				--- TableColumnItem ---
					item-column = firstExD
					format = date
					previewValue = value
			}
			--- TableColumn ---
				column-name = firstCoupD !
				column-type = domain !
				domainAttribute = firstCoupD !
				format = datetime.date-only
				type = text
				column-visibility = not-visible
				id = firstCoupD
				table-column-width = 7
			{
				--- TableColumnItem ---
					item-column = firstCoupD
					previewValue = value
			}
			--- TableColumn ---
				column-name = divProjectionF !
				column-type = domain !
				domainAttribute = divProjectionF !
				column-visibility = not-visible
				id = divProjectionF
				table-column-width = 7
			{
				--- TableColumnItem ---
					item-column = divProjectionF
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = beginD
				sort-direction = descending
				sort-rank = 4
			--- TableSort ---
				sort-column-name = validityD
				sort-direction = descending
				sort-rank = 2
			--- TableSort ---
				sort-column-name = endValidityD
				sort-direction = descending
				sort-rank = 5
			--- TableSort ---
				sort-column-name = natureE
				sort-rank = 3
		}
	}
}