# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels fr = "Liste des dividendes", de = Dividenden-Liste, en = "Dividends List"
	domainEntity = "AAADSIncomeEvent:IncomeEventList"
	cssClass = nodeco
	bean-define = DSBean.AAADSIncomeEvent.IncomeEventList
	bean-name = IncomeEventList
	id = IncomeEventList_ex1_1
	tid = 263459488198718
{
	--- Box ---
		labels en = Dividend, de = Dividenden, fr = Dividende
		boxType = vertical
		widgetBorder = box
		width = 0
		tid = 713001236514138
	{
		--- TableTree ---
			id = AP2__
			table-model-reference = DSTableModel.AAADSIncomeEvent.IncomeEventList
			table-column-count = 4 !
			table-columns-width = "25,25,25,25" !
		{
			--- TableColumn ---
				column-name = beginD !
				column-type = domain !
				domainAttribute = beginD !
				id = beginD
				table-column-width = 25
			{
				--- TableColumnItem ---
					item-column = beginD
					format = date
					previewValue = value
			}
			--- TableColumn ---
				column-name = validityD !
				column-type = domain !
				domainAttribute = validityD !
				id = validityD
				table-column-width = 25
			{
				--- TableColumnItem ---
					item-column = validityD
					format = date
					previewValue = value
			}
			--- TableColumn ---
				column-name = divProjectionF !
				column-type = domain !
				domainAttribute = divProjectionF !
				id = divProjectionF
				table-column-width = 25
			{
				--- TableColumnItem ---
					item-column = divProjectionF
					previewValue = value
			}
			--- TableColumn ---
				labels en = Value, fr = Valeur, de = Wert
				column-name = comp_c_k_d
				type = amount
				id = c_k_d
				column-computation = make-amount
				column-computation-parameters = "dividendN,currencyName"
				table-column-width = 25
				tid = 263459547439850
			{
				--- TableColumnItem ---
					item-column = comp_c_k_d
					format = amount.5-digits
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = beginD
				sort-direction = descending
				sort-rank = 2
			--- TableSort ---
				sort-column-name = instrCode
				sort-rank = 1
		}
	}
}