# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSDictFunction:DictFunctionList"
	bean-define = DSBean.AAADSDictFunction.DictFunctionList
	bean-name = DictFunctionList
	id = DictFunctionList_ArxS_
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			id = D___5
			table-column-count = 3 !
			table-columns-width = "33,33,33" !
		{
			--- TableColumn ---
				column-name = name !
				column-type = domain !
				domainAttribute = name !
				id = name
				table-column-width = 33
			{
				--- TableColumnItem ---
					item-column = name
					previewValue = value
			}
			--- TableColumn ---
				column-name = procName !
				column-type = domain !
				domainAttribute = procName !
				id = procName
				table-column-width = 33
			{
				--- TableColumnItem ---
					item-column = procName
					previewValue = value
			}
			--- TableColumn ---
				column-name = parentFunctionName !
				column-type = domain !
				domainAttribute = parentFunctionName !
				id = parentFunctionName
				table-column-width = 33
			{
				--- TableColumnItem ---
					item-column = parentFunctionName
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = name
				sort-rank = 1
		}
	}
}