# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Manager / Advisor Search Criteria", fr = "Critères de recherche sur gestionnaire / conseiller", de = "Verwalter / Berater Suchbegriffe"
	containment = container
	domainEntity = "AAADSManager:ManagerSearchCriteria"
	search = input !
	bean-define = DSBean.AAADSManager.ManagerSearchCriteria
	bean-name = ManagerSearchCriteria
	id = ManagerSearchInput_G1435
	tid = 30865212779153
{
	--- Box ---
		boxType = vertical
	{
		--- FilterCriteria ---
			includedFile = "resource:/com/module/search/QueryBuilder.xsp"
		--- Include ---
			includeSrc = "" !
			resource:///default/search/NavigationSearch.fragment
	}
}