# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Search Results", fr = "Résultats de la recherche", de = Suchergebnisse
	domainEntity = "AAADSManager:ManagerList"
	search = output !
	bean-define = DSBean.AAADSManager.ManagerList
	bean-name = ManagerList
	id = ManagerList_c2_z_
	tid = 30840588587314
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			id = S_6_4
			table-model-reference = DSTableModel.AAADSManager.ManagerList
			table-column-count = 4 !
			table-columns-width = "25,25,25,25" !
		{
			--- TableColumn ---
				labels de = Code
				column-name = code !
				column-type = domain !
				domainAttribute = code !
				column-locked = true
				id = code
				table-column-width = 25
				tid = 18053689094843
			{
				--- Conditional ---
					indexOfSelectedChild = 1
				{
					--- ConditionalBody ---
						javaCode = "com.odcgroup.tsl.wui.search.form.SearchFormHelper.isLookup(objectModel) == false"
						technicalName = NotLookup
						boxType = vertical
						isWidgetVisible = false
					{
						--- TableColumnItem ---
							toolTips en = "Select Manager/Advisor", fr = "Sélectionner le gestionnaire/conseiller", de = "Verwalter/Berater auswählen"
							item-column = code
							previewValue = value
							tid = 30840590538413
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = select ud
								Query.beanValue1 = "<udp:item column=\"code\"/>" ud
								Query.beanValue2 = "<udp:item column=\"name\"/>" ud
								modal = false
								only-changed = false
								prevalidate = false
							}
						}
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetSelected = true
					{
						--- TableColumnItem ---
							toolTips en = "Select Manager/Advisor", fr = "Sélectionner le gestionnaire/conseiller", de = "Verwalter/Berater auswählen"
							item-column = code
							previewValue = value
							tid = 30840592491669
						{
							Event OnClick (setWidgetValue)
							{
								widget-group-id = "<xsp:expr>com.odcgroup.tsl.wui.search.form.SearchFormHelper.getParentWidgetValue1Id(objectModel)</xsp:expr>"
								value = "<udp:item column=\"code\"/>"
								target = WUI_main
							}
							Event OnClick (winClose)
							{
								target = self
							}
						}
					}
				}
			}
			--- TableColumn ---
				column-name = name !
				column-type = domain !
				domainAttribute = name !
				id = name
				table-column-width = 25
			{
				--- TableColumnItem ---
					item-column = name
					previewValue = value
			}
			--- TableColumn ---
				column-name = extDenomination !
				column-type = domain !
				domainAttribute = extDenomination !
				type = text
				id = extDenomination
				table-column-width = 25
			{
				--- TableColumnItem ---
					item-column = extDenomination
					previewValue = value
			}
			--- TableColumn ---
				labels de = "Code der Geschäftseinheit"
				column-name = dataProfileCode !
				column-type = domain !
				domainAttribute = dataProfileCode !
				type = text
				id = dataProfileCode
				table-column-width = 25
				tid = 18069001108800
			{
				--- TableColumnItem ---
					item-column = dataProfileCode
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = code
				sort-rank = 1
			--- TableSort ---
				sort-column-name = name
				sort-rank = 2
		}
	}
}