# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Search Manager / Advisor", fr = "Recherche de gestionnaire / conseiller", de = "Verwalter / Berater Suche"
	containment = container
	search = container !
	cssClass = nodeco
	id = ManagerSearch_b__3_
	tid = 30852079451781
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/manager/search/ManagerSearchInput.module
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/manager/search/ManagerList.module
	}
}