# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "List Of Allocation Rules", de = "Liste Verteilungs-Regeln", fr = "Liste des règles d\'allocation"
	domainEntity = "AAADSExtStrategyElement:ExtStrategyElementDomainList"
	bean-define = DSTableModel.AAADSExtStrategyElement.ExtStrategyElementDomainList
	bean-name = ExtStrategyElementDomainList
	id = InstrOrderPercentOfPtfList_O___U
	tid = 1292317600925430
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			id = e_a_1
			table-column-count = 17 !
			table-columns-width = "5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5" !
		{
			--- TableColumn ---
				column-name = UPDATE
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				column-width = 2%
				id = T8b__
				table-column-width = 5
			{
				--- Icon ---
					toolTips en = "Update Instruction", de = "Instruktion aktualisieren", fr = "Mettre à jour les instructions"
					horizontalAlignment = center
					icon = application_form_edit
					id = D8W80
					tid = 1813575318086571
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = edit-instruction ud
						id = "<udp:item column=\"id\"/>" ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- TableColumn ---
				column-name = DELETE
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				column-width = 2%
				id = k3__6
				table-column-width = 5
			{
				--- Icon ---
					toolTips en = "Delete Instruction", de = "Instruktion löschen", fr = "Supprimer l\'Instruction"
					horizontalAlignment = center
					icon = application_form_delete
					id = c2Lx2
					tid = 1813575318980948
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = delete-instruction ud
						id = "<udp:item column=\"id\"/>" ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- TableColumn ---
				column-name = instrCode !
				column-type = domain !
				domainAttribute = instrCode !
				type = text
				id = instrCode
				table-column-width = 5
			{
				--- Icon ---
					toolTips fr = "Voir les détails de l\'instrument", en = "View Instrument Details", de = "Details des Instruments ansehen"
					icon = application_form_magnify
					id = IzX_M
					tid = 1227959219554414
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "resource:///administration/instrument/InstrumentQuickView.pageflow"
						target = popup
						code = "<udp:item column=\"instrCode\"/>" ud
						only-changed = false
						prevalidate = false
						modal = false
					}
				}
				--- Spacer ---
					height = 4
					width = 10
				--- TableColumnItem ---
					item-column = instrCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = opNatE !
				column-type = domain !
				domainAttribute = opNatE !
				type = text
				id = opNatE
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = opNatE
					previewValue = value
			}
			--- TableColumn ---
				column-name = recomNatE !
				column-type = domain !
				domainAttribute = recomNatE !
				type = text
				id = recomNatE
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = recomNatE
					previewValue = value
			}
			--- TableColumn ---
				column-name = objWeightN !
				column-type = domain !
				domainAttribute = objWeightN !
				type = text
				id = objWeightN
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = objWeightN
					format = decimal.detailed
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Last Quote", fr = "Cours courant", de = "Aktueller Kurs"
				column-name = Last_Quote
				type = amount
				id = o615h
				column-computation = make-amount
				column-computation-parameters = "currentQuoteN,currQuoteCurrCode"
				table-column-width = 5
				tid = 83858575802344
			{
				--- TableColumnItem ---
					item-column = Last_Quote
					previewValue = value
			}
			--- TableColumn ---
				column-name = actualOrderNatE !
				column-type = domain !
				domainAttribute = actualOrderNatE !
				type = text
				id = actualOrderNatE
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = actualOrderNatE
					previewValue = value
			}
			--- TableColumn ---
				labels en = Limit, fr = Limite, de = Limit-Kurs
				column-name = Limit_Quote
				type = amount
				id = e9__1
				column-computation = make-amount
				column-computation-parameters = "orderQuoteN,orderQuoteCurrCode"
				table-column-width = 5
				tid = 83878170793894
			{
				--- TableColumnItem ---
					item-column = Limit_Quote
					previewValue = value
			}
			--- TableColumn ---
				labels en = Stop, fr = Stop, de = Stop-Kurs
				column-name = Stop_Quote
				type = amount
				id = dZLq8
				column-computation = make-amount
				column-computation-parameters = "stopQuoteN,orderQuoteCurrCode"
				table-column-width = 5
				tid = 83890363244991
			{
				--- TableColumnItem ---
					item-column = Stop_Quote
					previewValue = value
			}
			--- TableColumn ---
				column-name = orderLimitD !
				column-type = domain !
				domainAttribute = orderLimitD !
				type = text
				id = orderLimitD
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = orderLimitD
					format = date
					previewValue = value
			}
			--- TableColumn ---
				column-name = id !
				column-type = domain !
				domainAttribute = id !
				type = text
				column-visibility = never-visible
				id = id
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = id
					format = integer
					previewValue = value
			}
			--- TableColumn ---
				column-name = currentQuoteN !
				column-type = domain !
				domainAttribute = currentQuoteN !
				format = decimal.detailed
				type = text
				column-visibility = never-visible
				id = currentQuoteN
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = currentQuoteN
					previewValue = value
			}
			--- TableColumn ---
				column-name = currQuoteCurrCode !
				column-type = domain !
				domainAttribute = currQuoteCurrCode !
				type = text
				column-visibility = never-visible
				id = currQuoteCurrCode
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = currQuoteCurrCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = orderQuoteN !
				column-type = domain !
				domainAttribute = orderQuoteN !
				type = text
				column-visibility = never-visible
				id = orderQuoteN
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = orderQuoteN
					format = decimal.detailed
					previewValue = value
			}
			--- TableColumn ---
				column-name = orderQuoteCurrCode !
				column-type = domain !
				domainAttribute = orderQuoteCurrCode !
				type = text
				column-visibility = never-visible
				id = orderQuoteCurrCode
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = orderQuoteCurrCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = stopQuoteN !
				column-type = domain !
				domainAttribute = stopQuoteN !
				type = text
				column-visibility = never-visible
				id = stopQuoteN
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = stopQuoteN
					format = decimal.detailed
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = id
				sort-direction = descending
				sort-rank = 1
		}
	}
}