# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Search List", de = "Liste Suche", fr = "Recherche de liste"
	containment = container
	domainEntity = "AAADSList:ListList"
	bean-define = DSBean.AAADSList.ListList
	bean-name = ListList
	id = ListSearchEdit_eH6__
	tid = 110454524360498
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///default/search/NavigationSearch.fragment
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/list/search/ListListEdit.module
	}
}