# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "List Search Criteria", fr = "Critères de recherche sur liste", de = "Liste Suchbegriffe"
	containment = container
	domainEntity = "AAADSList:ListSearchCriteria"
	search = input !
	bean-define = DSBean.AAADSList.ListSearchCriteria
	bean-name = ListSearchCriteria
	id = ListSearchInput_f____
	tid = 1253923300830136
{
	--- Box ---
		boxType = vertical
	{
		--- FilterCriteria ---
			includedFile = "resource:/com/module/search/QueryBuilder.xsp"
		--- Include ---
			includeSrc = "" !
			resource:///default/search/NavigationSearchWithoutQueries.fragment
	}
}