# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Search Results", fr = "Résultats de la recherche", de = Suchergebnisse
	domainEntity = "AAADSList:ListList"
	search = output !
	bean-define = DSBean.AAADSList.ListList
	bean-name = ListList
	id = ListList_yR_05
	tid = 108577822092472
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			id = c66__
			table-model-reference = DSTableModel.AAADSList.ListList
			table-column-count = 5 !
			table-columns-width = "20,20,20,20,20" !
		{
			--- TableColumn ---
				labels de = Code
				column-name = code !
				column-type = domain !
				domainAttribute = code !
				type = text
				column-locked = true
				id = code
				table-column-width = 20
				tid = 26577311175582
			{
				--- TableColumnItem ---
					toolTips en = "Select List", fr = "Sélectionner la liste", de = "Liste auswählen"
					item-column = code
					previewValue = value
					tid = 109634815562871
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = select ud
						Query.beanValue0 = "<udp:item column=\"id\"/>" ud
						Query.beanValue1 = "<udp:item column=\"code\"/>" ud
						only-changed = false
						prevalidate = false
						modal = false
					}
				}
			}
			--- TableColumn ---
				column-name = name !
				column-type = domain !
				domainAttribute = name !
				type = text
				id = name
				table-column-width = 20
			{
				--- TableColumnItem ---
					item-column = name
					previewValue = value
			}
			--- TableColumn ---
				column-name = extDenomination !
				column-type = domain !
				domainAttribute = extDenomination !
				type = text
				id = extDenomination
				table-column-width = 20
			{
				--- TableColumnItem ---
					item-column = extDenomination
					previewValue = value
			}
			--- TableColumn ---
				column-name = currencyExtDenomination !
				column-type = domain !
				domainAttribute = currencyExtDenomination !
				type = text
				id = currencyExtDenomination
				table-column-width = 20
			{
				--- TableColumnItem ---
					item-column = currencyExtDenomination
					previewValue = value
			}
			--- TableColumn ---
				column-name = natureE !
				column-type = domain !
				domainAttribute = natureE !
				type = text
				id = natureE
				table-column-width = 20
			{
				--- TableColumnItem ---
					item-column = natureE
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = code
				sort-rank = 1
			--- TableExtra ---
				domainAttribute = id
			--- TableSort ---
				sort-column-name = extDenomination
				sort-rank = 3
		}
	}
}