# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Search List", fr = "Recherche de liste", de = "Liste Suche"
	containment = container
	search = container !
	cssClass = nodeco
	id = ListSearch_V5_2_
	tid = 11828324039787
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/list/search/ListSearchInput.module
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/list/search/ListList.module
	}
}