# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Search Result", de = Suchergebnis, fr = "Résultat de recherche"
	domainEntity = "AAADSList:ListList"
	bean-define = DSBean.AAADSList.ListList
	bean-name = ListList
	id = ListList_yR_05
	tid = 5571865221138
{
	--- Box ---
		boxType = vertical
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 4
			gridColumnsWidth = "25,25,25,25" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Button ---
					labels en = "Create List", de = "Liste erstellen", fr = "Créer une Liste"
					id = btn_D_2C_
					tid = 113510047576158
			}
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
		}
		--- TableTree ---
			id = c66__
			table-column-count = 12 !
			table-columns-width = "8,8,8,8,8,8,8,8,8,8,8,8" !
		{
			--- TableColumn ---
				column-name = UPDATE
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				id = t__82
				table-column-width = 8
			{
				--- Icon ---
					toolTips en = "Update List", de = "Liste ändern", fr = "Mettre à jour la liste"
					horizontalAlignment = center
					icon = application_form_edit
					id = k0__F
					tid = 109787311178376
			}
			--- TableColumn ---
				column-name = COPY
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				id = Z436_
				table-column-width = 8
			{
				--- Icon ---
					toolTips en = "Copy List", de = "Liste kopieren", fr = "Copier la liste"
					horizontalAlignment = center
					icon = application_double
					id = Z_z3E
					tid = 109890921788663
			}
			--- TableColumn ---
				column-name = DELETE
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				id = jf70_
				table-column-width = 8
			{
				--- Icon ---
					toolTips en = "Delete Portfolio", de = "Portfolio löschen", fr = "Supprimer le portefeuille"
					horizontalAlignment = center
					icon = application_form_delete
					id = o1_4_
					tid = 82603584968760
			}
			--- TableColumn ---
				column-name = natureE !
				column-type = domain !
				domainAttribute = natureE !
				type = text
				id = natureE
				table-column-width = 8
			{
				--- TableColumnItem ---
					item-column = natureE
					previewValue = value
			}
			--- TableColumn ---
				labels de = Code
				column-name = code !
				column-type = domain !
				domainAttribute = code !
				type = text
				id = code
				table-column-width = 8
				tid = 20283745206443
			{
				--- TableColumnItem ---
					toolTips en = "View List", de = "Liste ansehen", fr = "Voir la liste"
					item-column = code
					previewValue = value
					tid = 109717519404281
			}
			--- TableColumn ---
				column-name = name !
				column-type = domain !
				domainAttribute = name !
				type = text
				id = name
				table-column-width = 8
			{
				--- TableColumnItem ---
					item-column = name
					previewValue = value
			}
			--- TableColumn ---
				column-name = extDenomination !
				column-type = domain !
				domainAttribute = extDenomination !
				type = text
				id = extDenomination
				table-column-width = 8
			{
				--- TableColumnItem ---
					item-column = extDenomination
					previewValue = value
			}
			--- TableColumn ---
				column-name = currencyExtDenomination !
				column-type = domain !
				domainAttribute = currencyExtDenomination !
				type = text
				id = currencyExtDenomination
				table-column-width = 8
			{
				--- TableColumnItem ---
					item-column = currencyExtDenomination
					previewValue = value
			}
			--- TableColumn ---
				column-name = typeExtDenomination !
				column-type = domain !
				domainAttribute = typeExtDenomination !
				type = text
				id = typeExtDenomination
				table-column-width = 8
			{
				--- TableColumnItem ---
					item-column = typeExtDenomination
					previewValue = value
			}
			--- TableColumn ---
				column-name = id !
				column-type = domain !
				domainAttribute = id !
				type = text
				column-visibility = never-visible
				id = id
				table-column-width = 8
			{
				--- TableColumnItem ---
					item-column = id
					format = integer
					previewValue = value
			}
			--- TableColumn ---
				column-name = updateRightF !
				column-type = domain !
				domainAttribute = updateRightF !
				type = text
				column-visibility = never-visible
				id = updateRightF
				table-column-width = 8
			{
				--- TableColumnItem ---
					item-column = updateRightF
					previewValue = value
			}
			--- TableColumn ---
				column-name = deleteRightF !
				column-type = domain !
				domainAttribute = deleteRightF !
				type = text
				column-visibility = never-visible
				id = deleteRightF
				table-column-width = 8
			{
				--- TableColumnItem ---
					item-column = deleteRightF
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = code
				sort-rank = 1
		}
	}
}