# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSValRuleCoeff:ValRuleCoeffList"
	bean-define = DSBean.AAADSValRuleCoeff.ValRuleCoeffList
	bean-name = ValRuleCoeffList
	id = ValRuleCoeffList_O073_
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			id = T__dB
			table-column-count = 2 !
			table-columns-width = "50,50" !
		{
			--- TableColumn ---
				column-name = natureE !
				column-type = domain !
				domainAttribute = natureE !
				id = natureE
				table-column-width = 50
			{
				--- TableColumnItem ---
					item-column = natureE
					previewValue = value
			}
			--- TableColumn ---
				column-name = valueN !
				column-type = domain !
				domainAttribute = valueN !
				id = valueN
				table-column-width = 50
			{
				--- TableColumnItem ---
					item-column = valueN
					format = decimal.detailed
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = natureE
				sort-rank = 1
		}
	}
}