# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSValRuleCoeff:ValRuleCoeffAll"
	bean-define = DSBean.AAADSValRuleCoeff.ValRuleCoeffAll
	bean-name = ValRuleCoeffAll
	id = ValRuleCoeffDetail_S_8_1
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 6
			gridColumnsWidth = "16,16,16,16,16,16" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- LabelDomain ---
					domainAttribute = natureE !
					for = natureE
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					width = 0
					required = true
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- ComboBox ---
					domainAttribute = natureE !
					horizontalAlignment = "${corporatehalign}"
					required = true
					bean-property = natureE
					id = natureE
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- LabelDomain ---
					domainAttribute = valueN !
					for = valueN
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					width = 0
					required = true
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- TextField ---
					domainAttribute = valueN !
					horizontalAlignment = "${corporatehalign}"
					type = decimal
					required = true
					bean-property = valueN
					id = valueN
			}
			--- GridCell ---
				gridColumnWidth = 16
			--- GridCell ---
				gridColumnWidth = 16
		}
	}
}