/*
 * generated by Xtext
 */
package com.odcgroup.domain.ui.contentassist;

import org.eclipse.xtext.ui.editor.contentassist.ContentAssistContext;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class DomainProposalProvider extends AbstractDomainProposalProvider {


    protected boolean isValidProposal(String proposal, String prefix,
	    ContentAssistContext context) {
	if(proposal.equals("\n")){
	    return false;
	}
	return super.isValidProposal(proposal, prefix, context);
    }

}
