# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "External Positions", de = "Externe Positionen", fr = "Positions externes"
	containment = container
	domainEntity = "AAADSDomain:DomainContext"
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = ExternalPositionContainer_a_9__
	tid = 91508788484966
{
	--- Box ---
		boxType = vertical
	{
		--- Conditional ---
			technicalName = AddSecurityPosition
			indexOfSelectedChild = 0
		{
			--- ConditionalBody ---
				javaCode = "null != <bean:get-property bean=\"DomainContext\" property=\"externalPositionCreator\"/> &amp;&amp; \r\n\"1\".equals(<bean:get-property bean=\"DomainContext\" property=\"externalPositionCreator\"/>.toString())"
				technicalName = AddPosition
				boxType = vertical
				isWidgetSelected = true
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/orderproposal/order/AddExternalPosition.module
			}
			--- ConditionalBody ---
				javaCode = "null != <bean:get-property bean=\"DomainContext\" property=\"externalPositionCreator\"/> &amp;&amp; \r\n\"2\".equals(<bean:get-property bean=\"DomainContext\" property=\"externalPositionCreator\"/>.toString())"
				technicalName = UpdatePosition
				boxType = vertical
				isWidgetVisible = false
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/orderproposal/order/UpdateExternalPosition.module
			}
			--- ConditionalBody ---
				javaCode = true
				technicalName = Default
				boxType = vertical
				isWidgetVisible = false
		}
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/orderproposal/detailedlist/ExternalPosition.module
		--- Grid ---
			cssClass = blank
			gridColumnCount = 4
			gridColumnsWidth = "25,25,25,25" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Button ---
					labels en = Back, de = Zurück, fr = Retour
					id = btn_P_2_b
					tid = 109279557182324
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = back ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
		}
	}
}