# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Order Proposal View", de = "Anlagevorschlag ansehen", fr = "Visualisation de la proposition d\'ordre"
	containment = container
	domainEntity = "AAADSDomain:DomainContext"
	cssClass = nodeco
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = OrderProposal_N7ck0
	tid = 86925437374948
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/orderproposal/context/ContextView.module
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/orderproposal/compliance/PTCCObjectivesCompliancePG.module
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/orderproposal/detailedlist/BuySellSecurityPGView.module
	}
}