# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Portfolio Selection", fr = "Sélection de portefeuille", de = Portfolioauswahl
	domainEntity = "AAADSPortfolio:PortfolioList"
	bean-define = DSBean.AAADSPortfolio.PortfolioList
	bean-name = PortfolioList
	id = PortfolioSelection_i594_
	tid = 181062550684539
{
	--- Box ---
		boxType = vertical
	{
		--- Button ---
			labels en = "Select Another Portfolio", fr = "Sélectionner un autre portefeuille", de = "Anderes Portfolio auswählen"
			id = btn_J150_
			tid = 181191472272347
		{
			Event OnClick (submit) S
			{
				method = post
				call-URI = "<pageflow:continuation/>"
				target = self
				flow-action = otherPortfolio ud
				modal = false
				only-changed = false
				prevalidate = false
			}
		}
		--- TableTree ---
			id = Z8_X6
			table-column-count = 30 !
			table-columns-width = "3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3" !
		{
			--- TableColumn ---
				labels de = Code
				column-name = code !
				column-type = domain !
				domainAttribute = code !
				type = text
				id = code
				table-column-width = 3
				tid = 17525777076416
			{
				--- TableColumnItem ---
					item-column = code
					previewValue = value
					enabled = conditional
					enabledIsBasedOn = updateRightF
					enabledIsBasedOn-simplified = "AAADSPortfolio:PortfolioList#updateRightF"
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = select ud
						portfolioDimPortfolio.code = "<udp:item column=\"code\"/>" ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- TableColumn ---
				column-name = extDenomination !
				column-type = domain !
				domainAttribute = extDenomination !
				type = text
				id = extDenomination
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = extDenomination
					previewValue = value
			}
			--- TableColumn ---
				column-name = currencyExtDenomination !
				column-type = domain !
				domainAttribute = currencyExtDenomination !
				type = text
				id = currencyExtDenomination
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = currencyExtDenomination
					previewValue = value
			}
			--- TableColumn ---
				column-name = thirdCode !
				column-type = domain !
				domainAttribute = thirdCode !
				type = text
				id = thirdCode
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = thirdCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = thirdName !
				column-type = domain !
				domainAttribute = thirdName !
				type = text
				id = thirdName
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = thirdName
					previewValue = value
			}
			--- TableColumn ---
				column-name = commMgrName !
				column-type = domain !
				domainAttribute = commMgrName !
				type = text
				id = commMgrName
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = commMgrName
					previewValue = value
			}
			--- TableColumn ---
				column-name = adminMgrName !
				column-type = domain !
				domainAttribute = adminMgrName !
				type = text
				id = adminMgrName
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = adminMgrName
					previewValue = value
			}
			--- TableColumn ---
				column-name = serviceTypeE !
				column-type = domain !
				domainAttribute = serviceTypeE !
				type = text
				id = serviceTypeE
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = serviceTypeE
					previewValue = value
			}
			--- TableColumn ---
				column-name = managTypeExtDenomination !
				column-type = domain !
				domainAttribute = managTypeExtDenomination !
				type = text
				id = managTypeExtDenomination
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = managTypeExtDenomination
					previewValue = value
			}
			--- TableColumn ---
				column-name = activeF !
				column-type = domain !
				domainAttribute = activeF !
				type = text
				id = activeF
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = activeF
					previewValue = value
			}
			--- TableColumn ---
				column-name = statusE !
				column-type = domain !
				domainAttribute = statusE !
				type = text
				id = statusE
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = statusE
					previewValue = value
			}
			--- TableColumn ---
				column-name = extCashPercent !
				column-type = domain !
				domainAttribute = extCashPercent !
				type = text
				column-visibility = not-visible
				id = extCashPercent
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = extCashPercent
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = extChangeMktValP !
				column-type = domain !
				domainAttribute = extChangeMktValP !
				type = text
				column-visibility = not-visible
				id = extChangeMktValP
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = extChangeMktValP
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = extCstCompliance !
				column-type = domain !
				domainAttribute = extCstCompliance !
				type = text
				column-visibility = not-visible
				id = extCstCompliance
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = extCstCompliance
					previewValue = value
			}
			--- TableColumn ---
				column-name = extDateOperation !
				column-type = domain !
				domainAttribute = extDateOperation !
				type = text
				column-visibility = not-visible
				id = extDateOperation
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = extDateOperation
					format = date
					previewValue = value
			}
			--- TableColumn ---
				column-name = extDaysOperation !
				column-type = domain !
				domainAttribute = extDaysOperation !
				type = text
				column-visibility = not-visible
				id = extDaysOperation
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = extDaysOperation
					format = integer
					previewValue = value
			}
			--- TableColumn ---
				column-name = extDaysToRedemp !
				column-type = domain !
				domainAttribute = extDaysToRedemp !
				format = integer
				type = text
				column-visibility = not-visible
				id = extDaysToRedemp
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = extDaysToRedemp
					previewValue = value
			}
			--- TableColumn ---
				column-name = extDaysToRedemp2 !
				column-type = domain !
				domainAttribute = extDaysToRedemp2 !
				format = integer
				type = text
				column-visibility = not-visible
				id = extDaysToRedemp2
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = extDaysToRedemp2
					previewValue = value
			}
			--- TableColumn ---
				column-name = extNextExpLimitOrder !
				column-type = domain !
				domainAttribute = extNextExpLimitOrder !
				format = integer
				type = text
				column-visibility = not-visible
				id = extNextExpLimitOrder
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = extNextExpLimitOrder
					previewValue = value
			}
			--- TableColumn ---
				column-name = extExecLimitOrder !
				column-type = domain !
				domainAttribute = extExecLimitOrder !
				type = text
				column-visibility = not-visible
				id = extExecLimitOrder
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = extExecLimitOrder
					format = integer
					previewValue = value
			}
			--- TableColumn ---
				column-name = extExpLimitOrder !
				column-type = domain !
				domainAttribute = extExpLimitOrder !
				type = text
				column-visibility = not-visible
				id = extExpLimitOrder
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = extExpLimitOrder
					format = integer
					previewValue = value
			}
			--- TableColumn ---
				column-name = extMinBondRating !
				column-type = domain !
				domainAttribute = extMinBondRating !
				type = text
				column-visibility = not-visible
				id = extMinBondRating
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = extMinBondRating
					previewValue = value
			}
			--- TableColumn ---
				column-name = extObjCompliance !
				column-type = domain !
				domainAttribute = extObjCompliance !
				type = text
				column-visibility = not-visible
				id = extObjCompliance
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = extObjCompliance
					previewValue = value
			}
			--- TableColumn ---
				column-name = extObjMeanDiff !
				column-type = domain !
				domainAttribute = extObjMeanDiff !
				type = text
				column-visibility = not-visible
				id = extObjMeanDiff
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = extObjMeanDiff
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				labels de = "Über-/Unterrendite ", en = "Ptf/Bench Over/Under Performance"
				column-name = extOverUnderPerf !
				column-type = domain !
				domainAttribute = extOverUnderPerf !
				type = text
				column-visibility = not-visible
				id = extOverUnderPerf
				table-column-width = 3
				tid = 17694384906740
			{
				--- TableColumnItem ---
					item-column = extOverUnderPerf
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = extPlPercent !
				column-type = domain !
				domainAttribute = extPlPercent !
				type = text
				column-visibility = not-visible
				id = extPlPercent
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = extPlPercent
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = extTdCostValM !
				column-type = domain !
				domainAttribute = extTdCostValM !
				type = text
				column-visibility = not-visible
				id = extTdCostValM
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = extTdCostValM
					format = decimal
					previewValue = value
			}
			--- TableColumn ---
				column-name = extTdMktValM !
				column-type = domain !
				domainAttribute = extTdMktValM !
				type = text
				column-visibility = not-visible
				id = extTdMktValM
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = extTdMktValM
					format = decimal
					previewValue = value
			}
			--- TableColumn ---
				labels de = "Rendite der Benchmarks"
				column-name = extYtdBenchRet !
				column-type = domain !
				domainAttribute = extYtdBenchRet !
				type = text
				column-visibility = not-visible
				id = extYtdBenchRet
				table-column-width = 3
				tid = 17568280959172
			{
				--- TableColumnItem ---
					item-column = extYtdBenchRet
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = extYtdPtfReturn !
				column-type = domain !
				domainAttribute = extYtdPtfReturn !
				type = text
				column-visibility = not-visible
				id = extYtdPtfReturn
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = extYtdPtfReturn
					format = percentTA
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = code
				sort-rank = 1
			--- TableExtra ---
				domainAttribute = updateRightF
		}
	}
}