# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Proposal Creation", de = "Vorschlag erstellen", fr = "Création de proposition"
	containment = container
	domainEntity = "AAADSDomain:DomainContext"
	bean-define = DSBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = ProposalCreationContainer_l01_5
	tid = 541436525176831
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/orderproposal/context/ProposalCreate.module
		--- Grid ---
			cssClass = blank
			gridColumnCount = 3
			gridColumnsWidth = "25,25,25" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Button ---
					labels en = "Create Empty Proposal", de = "Neuer Anlagevorschlag erstellen", fr = "Créer une proposition vide"
					id = btn_Sg68_
					tid = 541737309401660
				{
					Event OnClick (submit)
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						widget-group-ref = form
						target = self
						param = "flow-action=create"
						only-changed = true
						modal = false
						prevalidate = false
					}
				}
				--- Button ---
					labels en = "Create Proposal With Rebalancing", de = "Vorschlag mittels Rebalancing erstellen", fr = "Créer une proposition avec rééquilibrage"
					id = btn_Nje_z
					tid = 541770372730536
				{
					Event OnClick (submit)
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						widget-group-ref = form
						target = self
						param = "flow-action=rebalancing"
						only-changed = true
						modal = false
						prevalidate = false
					}
				}
			}
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
		}
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/compliancechecking/detailedlist/ObjectivesCompliance.module
	}
}