# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Create Deposit Order", de = "Anlage-Auftrag erstellen", fr = "Créer un ordre de dépôt"
	containment = container
	domainEntity = "AAADSExtOperation:ExtOperationAll"
	bean-define = DSBean.AAADSExtOperation.ExtOperationAll
	bean-name = ExtOperationAll
	id = SingleOrderPtccDepositCreate_n_L_1
	tid = 699328596223542
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/extoperation/order/create/MMDepositNoButtonCreate.module
		--- Grid ---
			cssClass = blank
			gridColumnCount = 4
			gridColumnsWidth = "25,25,25,25" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "null != <bean:get-property bean=\"ExtOperationAll\" property=\"instr.code\"/> &amp;&amp;\r\nnull != <bean:get-property bean=\"ExtOperationAll\" property=\"portfolio.code\"/>"
						technicalName = instrPtfSelected
						boxType = vertical
						isWidgetSelected = true
					{
						--- Button ---
							labels en = Check, de = Prüfen, fr = Vérifier
							horizontalTextPosition = lead
							id = btn_L_S7w
							tid = 699328613809855
						{
							Event OnClick (submit)
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								widget-group-ref = form
								param = "flow-action=check"
								only-changed = true
								modal = false
								prevalidate = false
							}
						}
					}
				}
				--- Button ---
					labels en = Cancel, fr = Annuler, de = Abbrechen
					horizontalTextPosition = lead
					verticalAlignment = lead
					id = btn_y__fW
					tid = 699328615628522
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = newOrder ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
		}
	}
}