# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Create Loan Order", de = "Kredit-Auftrag erstellen", fr = "Créer un ordre de prêt"
	containment = container
	domainEntity = "AAADSExtOperation:ExtOperationAll"
	bean-define = DSBean.AAADSExtOperation.ExtOperationAll
	bean-name = ExtOperationAll
	id = SingleOrderPtccLoanCreate_h5T_5
	tid = 5622450357796
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/extoperation/order/create/MMLoanNoButtonCreate.module
		--- Grid ---
			cssClass = blank
			gridColumnCount = 4
			gridColumnsWidth = "25,25,25,25" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "null != <bean:get-property bean=\"ExtOperationAll\" property=\"instr.code\"/> &amp;&amp;\r\nnull != <bean:get-property bean=\"ExtOperationAll\" property=\"portfolio.code\"/>"
						technicalName = instrPtfSelected
						boxType = vertical
						isWidgetSelected = true
					{
						--- Button ---
							labels en = Check, de = Prüfen, fr = Vérifier
							horizontalTextPosition = lead
							id = btn_i5292
							tid = 5622451209581
						{
							Event OnClick (submit)
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								widget-group-ref = form
								param = "flow-action=check"
								only-changed = true
								modal = false
								prevalidate = false
							}
						}
					}
				}
				--- Button ---
					labels en = Cancel, fr = Annuler, de = Abbrechen
					horizontalTextPosition = lead
					verticalAlignment = lead
					id = btn_l_g__
					tid = 5622453148095
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = newOrder ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
		}
	}
}