# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Check Deposit Order", de = "Anlage-Auftrag prüfen", fr = "Vérifier un ordre de dépôt"
	containment = container
	domainEntity = "AAADSExtOperation:ExtOperationAll"
	bean-define = DSBean.AAADSExtOperation.ExtOperationAll
	bean-name = ExtOperationAll
	id = SingleOrderDepositCheck_d1__k
	tid = 699997214203481
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/ordersession/context/SingleOrderClarificationConditional.module
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/ordersession/compliance/summary/ByPortfolio.module
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/extoperation/order/view/MMDepositView.module
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/ordersession/context/SingleOrderClarificationAction.module
	}
}