# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Security Order Check", de = "Prüfung Wertpapier-Auftrag", fr = "Vérification de l’ordre sur titre"
	containment = container
	domainEntity = "AAADSExtOperation:ExtOperationAll"
	bean-define = DSBean.AAADSExtOperation.ExtOperationAll
	bean-name = ExtOperationAll
	id = SingleOrderSecurityView_d49Nw
	tid = 372537880019657
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/ordersession/context/SingleOrderClarificationConditional.module
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/ordersession/compliance/summary/ByPortfolio.module
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/extoperation/order/view/SecurityView.module
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/ordersession/context/SingleOrderClarificationAction.module
	}
}