# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Check Forex Order", de = "Devisenkassa-Auftrag prüfen", fr = "Vérifier ordre de change"
	containment = container
	domainEntity = "AAADSExtOperation:ExtOperationAll"
	bean-define = DSBean.AAADSExtOperation.ExtOperationAll
	bean-name = ExtOperationAll
	id = SingleOrderForexCheck_G9__u
	tid = 194082689610830
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/ordersession/context/SingleOrderClarificationConditional.module
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/ordersession/compliance/summary/ByPortfolio.module
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/extoperation/order/view/ForexNoButtonView.module
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/ordersession/context/SingleOrderClarificationAction.module
	}
}