# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Check Loan Order", de = "Kredit-Auftrag prüfen", fr = "Vérifier un ordre de prêt"
	containment = container
	domainEntity = "AAADSExtOperation:ExtOperationAll"
	bean-define = DSBean.AAADSExtOperation.ExtOperationAll
	bean-name = ExtOperationAll
	id = SingleOrderLoanCheck_gs_fi
	tid = 6123001030019
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/ordersession/context/SingleOrderClarificationConditional.module
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/ordersession/compliance/summary/ByPortfolio.module
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/extoperation/order/view/MMLoanView.module
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/ordersession/context/SingleOrderClarificationAction.module
	}
}