# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Create Security Order", de = "Wertpapier-Auftrag erstellen", fr = "Créer un ordre sur titre"
	containment = container
	domainEntity = "AAADSExtOperation:ExtOperationAll"
	bean-define = DSBean.AAADSExtOperation.ExtOperationAll
	bean-name = ExtOperationAll
	id = SingleOrderSecurityCreate_E53_a
	tid = 373264468944678
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/extoperation/order/create/SecurityCreate.module
		--- Grid ---
			cssClass = blank
			gridColumnCount = 4
			gridColumnsWidth = "25,25,25,25" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "null != <bean:get-property bean=\"ExtOperationAll\" property=\"instr.code\"/> &amp;&amp;\r\nnull != <bean:get-property bean=\"ExtOperationAll\" property=\"portfolio.code\"/>"
						technicalName = instrPtfSelected
						boxType = vertical
						isWidgetSelected = true
					{
						--- Button ---
							labels en = Check, de = Prüfen, fr = Vérifier
							horizontalTextPosition = lead
							id = btn_E_55o
							tid = 373264469183648
						{
							Event OnClick (submit)
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								widget-group-ref = form
								param = "flow-action=check"
								only-changed = true
								modal = false
								prevalidate = false
							}
						}
					}
				}
				--- Button ---
					labels en = Cancel, fr = Annuler, de = Abbrechen
					horizontalTextPosition = lead
					verticalAlignment = lead
					id = btn_Y__30
					tid = 373264469583569
				{
					Event OnClick (submit) S
					tid = 624847824771025
					messages en = "Are you sure to cancel this order?", fr = "Etes-vous sûr d\'annuler cet ordre?", de = "Wollen Sie diesen Auftrag wirklich streichen?"
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = newOrder ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
		}
	}
}