# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = Context, fr = Contexte, de = Kontext
	domainEntity = "AAADSDomain:DomainContext"
	collapsed = true
	collapsible = true
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = Context_XxYh5
	tid = 95561422083436
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TabbedPane ---
			id = a0Xbg
			indexOfSelectedChild = 0
		{
			--- Tab ---
				labels fr = Base, en = Basic, de = Einfach
				id = tab_k_s_8
				isWidgetSelected = true
				tid = 6230609330543
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 7
					gridColumnsWidth = "23,14,10,10,14,10,10" !
					gridRowCount = 1
				{
					--- GridCell ---
						gridColumnWidth = 23
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainPortfolioDimensionNotEdited.fragment
					}
					--- GridCell ---
						gridColumnWidth = 14
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainInstrumentDimensionNotEdited.fragment
					}
					--- GridCell ---
						gridColumnWidth = 10
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainPivotDateFromNotEdited.fragment
					}
					--- GridCell ---
						gridColumnWidth = 10
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainTillDateView.fragment
					}
					--- GridCell ---
						gridColumnWidth = 14
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainRefCurrencyNotEdited.fragment
					}
					--- GridCell ---
						gridColumnWidth = 10
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainHierarchyIdentifierNotEdited.fragment
					}
					--- GridCell ---
						gridColumnWidth = 10
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainConsolidationIdentifierNotEdited.fragment
					}
				}
			}
			--- Tab ---
				labels fr = Avancée, en = Advanced, de = Erweitert
				id = tab_gi__2
				isWidgetVisible = false
				tid = 6230606833032
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 5
					gridColumnsWidth = "16,16,16,16,16" !
					gridRowCount = 1
				{
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainMinStatusNotEdited.fragment
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainMaxStatusNotEdited.fragment
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainStatusFusNotEdited.fragment
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainPosLogicalENotEdited.fragment
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainClosePosFNotEdited.fragment
					}
				}
			}
		}
		--- Grid ---
			cssClass = blank
			gridColumnCount = 4
			gridColumnsWidth = "25,25,25,25" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Button ---
					labels en = Refresh, fr = Actualiser, de = Aktualisieren
					id = btn_refresh_in_domaincontext
					tid = 95561423856868
				{
					Event OnClick (submit)
					{
						method = get
						call-URI = "<pageflow:continuation/>"
						widget-group-ref = form
						param = "flow-action=execute,DSAction=refresh"
						only-changed = true
						prevalidate = false
						modal = false
					}
				}
				--- Button ---
					labels en = "Default Settings", fr = "Valeurs par défaut", de = Standardeinstellung
					id = btn_S8_9_
					tid = 95561424352159
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = reset ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
		}
	}
}