# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = Context, fr = Contexte, de = Kontext
	domainEntity = "AAADSDomain:DomainContext"
	collapsible = true
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = Context_XxYh5
	tid = 6229749980545
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TabbedPane ---
			id = a0Xbg
			indexOfSelectedChild = 0
		{
			--- Tab ---
				labels fr = Base, en = Basic, de = Einfach
				id = tab_k_s_8
				isWidgetSelected = true
				tid = 144898588275604
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 7
					gridColumnsWidth = "23,14,10,10,14,10,10" !
					gridRowCount = 1
				{
					--- GridCell ---
						gridColumnWidth = 23
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainPortfolioDimension.fragment
					}
					--- GridCell ---
						gridColumnWidth = 14
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainInstrumentDimension.fragment
					}
					--- GridCell ---
						gridColumnWidth = 10
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainPivotDateFrom.fragment
					}
					--- GridCell ---
						gridColumnWidth = 10
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainTillDateView.fragment
					}
					--- GridCell ---
						gridColumnWidth = 14
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainRefCurrency.fragment
					}
					--- GridCell ---
						gridColumnWidth = 10
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainHierarchyIdentifier.fragment
					}
					--- GridCell ---
						gridColumnWidth = 10
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainConsolidationIdentifier.fragment
					}
				}
			}
			--- Tab ---
				labels fr = Avancée, en = Advanced, de = Erweitert
				id = tab_gi__2
				isWidgetVisible = false
				tid = 144960412064382
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 5
					gridColumnsWidth = "16,16,16,16,16" !
					gridRowCount = 1
				{
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainMinStatus.fragment
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainMaxStatus.fragment
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainStatusFus.fragment
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainPosLogicalE.fragment
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainClosePosF.fragment
					}
				}
			}
		}
		--- Grid ---
			cssClass = blank
			gridColumnCount = 4
			gridColumnsWidth = "25,25,25,25" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Button ---
					labels en = Execute, de = Ausführen, fr = Exécuter
					id = btn_execute_in_domaincontext
					tid = 6230607971531
				{
					Event OnClick (submit)
					{
						method = get
						call-URI = "<pageflow:continuation/>"
						widget-group-ref = form
						param = "flow-action=execute"
						only-changed = true
						prevalidate = false
						modal = false
					}
				}
				--- Button ---
					labels en = Refresh, de = Aktualisieren, fr = Actualiser
					id = btn_refresh_in_domaincontext
					tid = 6230608687350
				{
					Event OnClick (submit)
					{
						method = get
						call-URI = "<pageflow:continuation/>"
						widget-group-ref = form
						param = "flow-action=execute,action=refresh"
						only-changed = true
						prevalidate = false
						modal = false
					}
				}
				--- Button ---
					labels en = "Default Settings", de = Standardeinstellung, fr = "Valeurs par défaut"
					id = btn_S8_9_
					tid = 473508972389507
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = reset ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
		}
	}
}