# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Portfolio Details", fr = "Détails du portefeuille", de = "Details des Portfolios"
	containment = container
	domainEntity = "AAADSDomain:DomainContext"
	cssClass = nodeco
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = PortfolioDetail_a2_0E
	tid = 6229753001417
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/futurecashflow/context/PortfolioCodeDetailHead.module
		--- Grid ---
			cssClass = blank
			gridColumnCount = 4
			gridColumnsWidth = "25,25,25,25" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Button ---
					labels en = "Back to Summary", fr = "Retour au résumé", de = "Zurück zur Ansicht"
					id = btn_l202_
					tid = 6229753727329
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = back ud
						Query.fs_1.TargetDS = "AAADSFutureCashFlow:FutureCashFlowSummaryList" ud
						Query.fs_1.cancel = true ud
						Query.fs_1.level = 0 ud
						only-changed = false
						prevalidate = false
						modal = false
					}
				}
				--- Button ---
					labels en = Refresh, fr = Actualiser, de = Aktualisieren
					id = btn_o_762
					tid = 3796428646085745
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = refresh ud
						only-changed = false
						prevalidate = false
						modal = false
					}
				}
			}
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
		}
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/identification/identification/PortfolioBanner.module
	}
}