# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSStandingInstruction:StandingInstructionList"
	bean-define = DSBean.AAADSStandingInstruction.StandingInstructionList
	bean-name = StandingInstructionList
	id = StandingInstructionList_G___6
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			id = aVp1_
			table-column-count = 4 !
			table-columns-width = "25,25,25,25" !
		{
			--- TableColumn ---
				column-name = portfolioCode !
				column-type = domain !
				domainAttribute = portfolioCode !
				id = portfolioCode
				table-column-width = 25
			{
				--- TableColumnItem ---
					item-column = portfolioCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = code !
				column-type = domain !
				domainAttribute = code !
				id = code
				table-column-width = 25
			{
				--- TableColumnItem ---
					item-column = code
					previewValue = value
			}
			--- TableColumn ---
				column-name = beginD !
				column-type = domain !
				domainAttribute = beginD !
				id = beginD
				table-column-width = 25
			{
				--- TableColumnItem ---
					item-column = beginD
					format = datetime.date-only
					previewValue = value
			}
			--- TableColumn ---
				column-name = statusE !
				column-type = domain !
				domainAttribute = statusE !
				id = statusE
				table-column-width = 25
			{
				--- TableColumnItem ---
					item-column = statusE
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = portfolioCode
				sort-rank = 1
			--- TableSort ---
				sort-column-name = code
				sort-rank = 2
			--- TableSort ---
				sort-column-name = beginD
				sort-direction = descending
				sort-rank = 3
			--- TableSort ---
				sort-column-name = statusE
				sort-rank = 4
		}
	}
}