# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Rating Codification List", fr = "Liste de codification de notation", de = "Liste der Bonitätscodes"
	domainEntity = "AAADSCodification:CodificationList"
	bean-define = DSBean.AAADSCodification.CodificationList
	bean-name = CodificationList
	id = CodificationRatingList_R_8_i
	tid = 134042179248479
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			id = f6___
			table-model-reference = CodificationList
			table-column-count = 4 !
			table-columns-width = "25,25,25,25" !
		{
			--- TableColumn ---
				column-name = dictEntityName !
				column-type = domain !
				domainAttribute = dictEntityName !
				id = dictEntityName
				table-column-width = 25
			{
				--- TableColumnItem ---
					item-column = dictEntityName
					previewValue = value
			}
			--- TableColumn ---
				column-name = code !
				column-type = domain !
				domainAttribute = code !
				id = code
				table-column-width = 25
			{
				--- TableColumnItem ---
					item-column = code
					previewValue = value
			}
			--- TableColumn ---
				column-name = name !
				column-type = domain !
				domainAttribute = name !
				id = name
				table-column-width = 25
			{
				--- TableColumnItem ---
					item-column = name
					previewValue = value
			}
			--- TableColumn ---
				column-name = denom !
				column-type = domain !
				domainAttribute = denom !
				id = denom
				table-column-width = 25
			{
				--- TableColumnItem ---
					item-column = denom
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = dictEntityName
				sort-rank = 1
			--- TableSort ---
				sort-column-name = code
				sort-rank = 2
		}
	}
}