# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Synonym Codification List", fr = "Liste de codification de synonyme", de = "Liste der Synonym-Codes"
	domainEntity = "AAADSCodification:CodificationList"
	bean-define = DSBean.AAADSCodification.CodificationList
	bean-name = CodificationList
	id = CodificationSynonymList_Oa3W_
	tid = 80116719167938
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			id = N_j7u
			table-column-count = 6 !
			table-columns-width = "16,16,16,16,16,16" !
		{
			--- TableColumn ---
				column-name = dictEntityName !
				column-type = domain !
				domainAttribute = dictEntityName !
				id = dictEntityName
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = dictEntityName
					previewValue = value
			}
			--- TableColumn ---
				column-name = synEntityName !
				column-type = domain !
				domainAttribute = synEntityName !
				id = synEntityName
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = synEntityName
					previewValue = value
			}
			--- TableColumn ---
				column-name = code !
				column-type = domain !
				domainAttribute = code !
				id = code
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = code
					previewValue = value
			}
			--- TableColumn ---
				column-name = name !
				column-type = domain !
				domainAttribute = name !
				id = name
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = name
					previewValue = value
			}
			--- TableColumn ---
				column-name = denom !
				column-type = domain !
				domainAttribute = denom !
				id = denom
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = denom
					previewValue = value
			}
			--- TableColumn ---
				column-name = internalCodifF !
				column-type = domain !
				domainAttribute = internalCodifF !
				id = internalCodifF
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = internalCodifF
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = dictEntityName
				sort-rank = 1
			--- TableSort ---
				sort-column-name = synEntityName
				sort-rank = 2
			--- TableSort ---
				sort-column-name = code
				sort-rank = 3
		}
	}
}