# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Balance Position Type List", fr = "Liste de type de position équilibrée", de = "Liste Balance Position Typ"
	domainEntity = "AAADSBalancePosType:BalancePosTypeList"
	bean-define = DSBean.AAADSBalancePosType.BalancePosTypeList
	bean-name = BalancePosTypeList
	id = BalancePosTypeList_O_mf7
	tid = 25149839331255
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			id = P5__Z
			table-column-count = 5 !
			table-columns-width = "20,20,20,20,20" !
		{
			--- TableColumn ---
				column-name = natureE !
				column-type = domain !
				domainAttribute = natureE !
				id = natureE
				table-column-width = 20
			{
				--- TableColumnItem ---
					item-column = natureE
					previewValue = value
			}
			--- TableColumn ---
				column-name = code !
				column-type = domain !
				domainAttribute = code !
				id = code
				table-column-width = 20
			{
				--- TableColumnItem ---
					item-column = code
					previewValue = value
			}
			--- TableColumn ---
				column-name = name !
				column-type = domain !
				domainAttribute = name !
				id = name
				table-column-width = 20
			{
				--- TableColumnItem ---
					item-column = name
					previewValue = value
			}
			--- TableColumn ---
				column-name = denom !
				column-type = domain !
				domainAttribute = denom !
				id = denom
				table-column-width = 20
			{
				--- TableColumnItem ---
					item-column = denom
					previewValue = value
			}
			--- TableColumn ---
				column-name = rankN !
				column-type = domain !
				domainAttribute = rankN !
				id = rankN
				table-column-width = 20
			{
				--- TableColumnItem ---
					item-column = rankN
					format = integer
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = natureE
				sort-rank = 1
			--- TableSort ---
				sort-column-name = code
				sort-rank = 2
		}
	}
}