# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSBalancePosType:BalancePosTypeAll"
	bean-define = DSBean.AAADSBalancePosType.BalancePosTypeAll
	bean-name = BalancePosTypeAll
	id = BalancePosTypeDetail_Y78U5
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 6
			gridColumnsWidth = "16,16,16,16,16,16" !
			gridRowCount = 2
		{
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- LabelDomain ---
					domainAttribute = code !
					for = code
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					width = 0
					required = true
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- TextField ---
					domainAttribute = code !
					horizontalAlignment = "${corporatehalign}"
					type = text
					required = true
					bean-property = code
					id = code
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- LabelDomain ---
					domainAttribute = name !
					for = name
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					width = 0
					required = true
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- TextField ---
					domainAttribute = name !
					horizontalAlignment = "${corporatehalign}"
					type = text
					required = true
					bean-property = name
					id = name
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- LabelDomain ---
					domainAttribute = denom !
					for = denom
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					width = 0
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- TextField ---
					domainAttribute = denom !
					horizontalAlignment = "${corporatehalign}"
					type = text
					bean-property = denom
					id = denom
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- LabelDomain ---
					domainAttribute = natureE !
					for = natureE
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					width = 0
					required = true
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- ComboBox ---
					domainAttribute = natureE !
					horizontalAlignment = "${corporatehalign}"
					required = true
					bean-property = natureE
					id = natureE
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- LabelDomain ---
					domainAttribute = rankN !
					for = rankN
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					width = 0
					required = true
			}
			--- GridCell ---
				gridColumnWidth = 16
			{
				--- TextField ---
					domainAttribute = rankN !
					horizontalAlignment = "${corporatehalign}"
					type = integer
					required = true
					bean-property = rankN
					id = rankN
			}
			--- GridCell ---
				gridColumnWidth = 16
			--- GridCell ---
				gridColumnWidth = 16
		}
	}
}