# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "List Of Allocation Rules", fr = "Liste des règles d\'allocation", de = "Liste der Verteilungs-Regeln"
	domainEntity = "AAADSExtStrategyElement:ExtStrategyElementDomainList"
	bean-define = DSBean.AAADSExtStrategyElement.ExtStrategyElementDomainList
	bean-name = ExtStrategyElementDomainList
	id = InstrResultPercentOfStratMktSegList_yP__1
	tid = 85355318947239
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			id = gZ_t_
			table-column-count = 16 !
			table-columns-width = "6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6" !
		{
			--- TableColumn ---
				column-name = UPDATE
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				column-width = 2%
				id = MI_3_
				table-column-width = 6
			{
				--- Icon ---
					toolTips en = "Update Instruction", de = "Instruktion aktualisieren", fr = "Mettre à jour les instructions"
					horizontalAlignment = center
					icon = application_form_edit
					id = f3g4s
					tid = 68078145712722
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = edit-instruction ud
						id = "<udp:item column=\"id\"/>" ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- TableColumn ---
				column-name = DELETE
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				column-width = 2%
				id = WB1d7
				table-column-width = 6
			{
				--- Icon ---
					toolTips en = "Delete Instruction", de = "Instruktion löschen", fr = "Supprimer l\'Instruction"
					horizontalAlignment = center
					icon = application_form_delete
					id = Q_923
					tid = 68078146707192
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = delete-instruction ud
						id = "<udp:item column=\"id\"/>" ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- TableColumn ---
				column-name = instrCode !
				column-type = domain !
				domainAttribute = instrCode !
				type = text
				id = instrCode
				table-column-width = 6
			{
				--- Icon ---
					toolTips de = "Details des Instruments ansehen", fr = "Voir les détails de l\'instrument", en = "View Instrument Details"
					icon = application_form_magnify
					id = z15xo
					tid = 1228143379775000
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "resource:///administration/instrument/InstrumentQuickView.pageflow"
						target = popup
						code = "<udp:item column=\"instrCode\"/>" ud
						only-changed = false
						prevalidate = false
						modal = false
					}
				}
				--- Spacer ---
					height = 4
					width = 10
				--- TableColumnItem ---
					item-column = instrCode
					previewValue = value
			}
			--- TableColumn ---
				labels en = Buy/Sell
				column-name = opNatE !
				column-type = domain !
				domainAttribute = opNatE !
				type = text
				id = opNatE
				table-column-width = 6
				tid = 68078147706795
			{
				--- TableColumnItem ---
					item-column = opNatE
					previewValue = value
			}
			--- TableColumn ---
				column-name = objWeightN !
				column-type = domain !
				domainAttribute = objWeightN !
				format = decimal.detailed
				type = text
				id = objWeightN
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = objWeightN
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Last Quote", fr = "Cours courant", de = "Aktueller Kurs"
				column-name = Last_Quote
				type = amount
				id = I__1p
				column-computation = make-amount
				column-computation-parameters = "currentQuoteN,currQuoteCurrCode"
				table-column-width = 6
				tid = 85388664295622
			{
				--- TableColumnItem ---
					item-column = Last_Quote
					previewValue = value
			}
			--- TableColumn ---
				column-name = actualOrderNatE !
				column-type = domain !
				domainAttribute = actualOrderNatE !
				type = text
				id = actualOrderNatE
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = actualOrderNatE
					previewValue = value
			}
			--- TableColumn ---
				labels en = Limit, fr = Limite, de = Limit-Kurs
				column-name = Limit_Quote
				type = amount
				id = Ie39U
				column-computation = make-amount
				column-computation-parameters = "orderQuoteN,orderQuoteCurrCode"
				table-column-width = 6
				tid = 85412513769237
			{
				--- TableColumnItem ---
					item-column = Limit_Quote
					previewValue = value
			}
			--- TableColumn ---
				labels en = Stop, fr = Stop, de = Stop-Kurs
				column-name = Stop_Quote
				type = amount
				id = jmcz5
				column-computation = make-amount
				column-computation-parameters = "stopQuoteN,orderQuoteCurrCode"
				table-column-width = 6
				tid = 85423078739773
			{
				--- TableColumnItem ---
					item-column = Stop_Quote
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Limit Date"
				column-name = orderLimitD !
				column-type = domain !
				domainAttribute = orderLimitD !
				type = text
				id = orderLimitD
				table-column-width = 6
				tid = 68078150713729
			{
				--- TableColumnItem ---
					item-column = orderLimitD
					format = date
					previewValue = value
			}
			--- TableColumn ---
				column-name = id !
				column-type = domain !
				domainAttribute = id !
				type = text
				column-visibility = never-visible
				id = id
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = id
					format = integer
					previewValue = value
			}
			--- TableColumn ---
				column-name = currentQuoteN !
				column-type = domain !
				domainAttribute = currentQuoteN !
				format = decimal.detailed
				type = text
				column-visibility = never-visible
				id = currentQuoteN
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = currentQuoteN
					previewValue = value
			}
			--- TableColumn ---
				column-name = currQuoteCurrCode !
				column-type = domain !
				domainAttribute = currQuoteCurrCode !
				type = text
				column-visibility = never-visible
				id = currQuoteCurrCode
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = currQuoteCurrCode
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Limit Price"
				column-name = orderQuoteN !
				column-type = domain !
				domainAttribute = orderQuoteN !
				type = text
				column-visibility = never-visible
				id = orderQuoteN
				table-column-width = 6
				tid = 68078149649540
			{
				--- TableColumnItem ---
					item-column = orderQuoteN
					format = decimal.detailed
					previewValue = value
				--- TableColumnItem ---
					item-column = orderQuoteCurrCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = orderQuoteCurrCode !
				column-type = domain !
				domainAttribute = orderQuoteCurrCode !
				type = text
				column-visibility = never-visible
				id = orderQuoteCurrCode
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = orderQuoteCurrCode
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Stop Price"
				column-name = stopQuoteN !
				column-type = domain !
				domainAttribute = stopQuoteN !
				type = text
				column-visibility = never-visible
				id = stopQuoteN
				table-column-width = 6
				tid = 68078149710277
			{
				--- TableColumnItem ---
					item-column = stopQuoteN
					format = decimal.detailed
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = id
				sort-direction = descending
				sort-rank = 1
		}
	}
}