# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	containment = container
	domainEntity = "DS3705:DS3705Dataset"
	bean-define = DSBean.DS3705.DS3705Dataset
	bean-name = DS3705Dataset
	id = DS3705_x___X
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			hide-empty-tabs = true
			loading-mode = async
			tabs-filtered-attribute = attr1
			id = attr1
			indexOfSelectedChild = 1
		{
			--- Tab ---
				id = tab_J_e_4
				isWidgetVisible = false
			--- Tab ---
				hide-empty-tab = true
				tab-filter = test
				id = tab_b__6_
				isWidgetSelected = true
		}
	}
}