# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Ensure the tag <udp:udp> is generated only once"
	containment = container
	domainEntity = "DS4021Domain:DS4021Dataset"
	bean-define = DSBean.DS4021Domain.DS4021Dataset
	bean-name = DS4021Dataset
	id = DS4021_QksSz
	tid = 91129709979234
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			hide-empty-tabs = true
			tabs-filtered-attribute = filter1
			id = filter1
			indexOfSelectedChild = 0
		{
			--- Tab ---
				id = tab_fF5y_
				isWidgetSelected = true
			{
				--- TabbedPane ---
					hide-empty-tabs = true
					tabs-filtered-attribute = filter2
					id = filter2
					indexOfSelectedChild = 0
				{
					--- Tab ---
						id = tab_oLE0_
						isWidgetSelected = true
					{
						--- Button ---
							id = btn_l___C
					}
				}
			}
		}
	}
}