# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	id = DS4328_xq6m_
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			id = f9hO5
			indexOfSelectedChild = 0
		{
			--- Tab ---
				id = tab_u_7Z0
				isWidgetSelected = true
			{
				Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = outgoingTransition ud
					only-changed = false
					prevalidate = false
					modal = false
					Snippet FilterSet
					id = fs_zor
					cancel = false
					level = 1
					targetDataset = "DS4328:DS4328Entity"
					{
						Snippet Filter
						attribute = id
						filterValue = %
						operator = EQUAL
					}
				}
			}
		}
	}
}