# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	containment = container
	domainEntity = "DS4021Domain:DS4021Dataset"
	bean-define = DSBean.DS4021Domain.DS4021Dataset
	bean-name = DS4021Dataset
	id = DS5529_JP1g_
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			hide-empty-tabs = true
			tabs-filtered-attribute = filter1
			id = filter1
			indexOfSelectedChild = 1
		{
			--- Tab ---
				labels en = Test
				tab-name = Test
				id = tab_fz_Ai
				isWidgetVisible = false
				tid = 629983526808483
			--- Tab ---
				labels en = Tab2
				hide-empty-tab = true
				tab-filter = test
				id = tab_V97U5
				isWidgetSelected = true
				tid = 629988596967537
			{
				Event OnClick (submit)
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = module
					only-changed = true
					param = "flow-action=test"
					prevalidate = false
					modal = false
					flow-action = loadAgain ud
				}
			}
		}
	}
}