# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	containment = container
	domainEntity = "DS8423:Dataset"
	bean-define = DSBean.DS8423.Dataset
	bean-name = Dataset
	id = DS8423_Wob_9
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			hide-empty-tabs = true
			tabs-filtered-attribute = valA
			filter-level = 55
			id = valA
			indexOfSelectedChild = 2
		{
			--- Tab ---
				labels en = All
				id = tab_K6zH_
				isWidgetVisible = false
				tid = 346615149562816
			--- Tab ---
				labels en = One
				hide-empty-tab = true
				tab-filter = one
				id = tab_G_K_R
				isWidgetVisible = false
				tid = 346644529370538
			--- Tab ---
				labels en = Two
				hide-empty-tab = true
				tab-filter = two
				id = tab_V2V8_
				isWidgetSelected = true
				tid = 346648536041141
		}
	}
}