/*
* generated by Xtext
*/
package com.odcgroup.t24.enquiry;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class EnquiryUiInjectorProvider implements IInjectorProvider {

	public Injector getInjector() {
		return com.odcgroup.t24.enquiry.ui.internal.EnquiryActivator.getInstance().getInjector("com.odcgroup.t24.enquiry.Enquiry");
	}

}
