# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSAllocationConstraintAdmin:AllocationConstraintObjectives"
	cssClass = nodeco
	bean-define = DSBean.AAADSAllocationConstraintAdmin.AllocationConstraintObjectives
	bean-name = AllocationConstraintObjectives
	id = AllocationConstraintObjectivesView_D7g86
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			table-filter-layer = true
			id = f0_S_
			table-column-count = 8 !
			table-columns-width = "12,12,12,12,12,12,12,12" !
		{
			--- TableColumn ---
				labels en = "Market Segment", fr = "Segment de marché", de = Marktsegment
				column-display-grouping = true
				column-name = MarketSegment
				column-type = placeholder !
				type = text
				column-locked = true
				column-sortable = false !
				id = P_6__
				table-column-width = 12
				tid = 100085274679607
			{
				--- TableGroup ---
					aggregateData = false
					group-column-name = MARKET_STRUCTURE
					group-sorting-column-name = MKT_STRUCTURE_SORT
					group-sorting-direction = ascending
					hierarchy = true
					group-rank = 1
			}
			--- TableColumn ---
				column-name = minWeightN !
				column-type = domain !
				domainAttribute = minWeightN !
				format = decimal.detailed
				type = text
				id = minWeightN
				table-column-width = 12
			{
				--- TableColumnItem ---
					item-column = minWeightN
					format = percentTA
			}
			--- TableColumn ---
				column-name = OBJECTIVE_WEIGHT !
				column-type = domain !
				domainAttribute = OBJECTIVE_WEIGHT !
				type = text
				column-is-part-of-filter = false
				column-sortable = false
				id = OBJECTIVE_WEIGHT
				table-column-width = 12
			{
				--- TableColumnItem ---
					item-column = OBJECTIVE_WEIGHT
					previewValue = "40.00% +/- 0.20%"
			}
			--- TableColumn ---
				column-name = maxWeightN !
				column-type = domain !
				domainAttribute = maxWeightN !
				format = decimal.detailed
				type = text
				id = maxWeightN
				table-column-width = 12
			{
				--- TableColumnItem ---
					item-column = maxWeightN
					format = percentTA
					previewValue = 43.00%
			}
			--- TableColumn ---
				labels en = "Fixed Objective", fr = "Objectif fixé", de = "Festgelegtes Ziel"
				column-name = FixedObjective
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				id = m_28w
				table-column-width = 12
				tid = 100085276632253
			{
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "\"0\".equals(<udp:item column=\"fixedCellF\"/>)"
						technicalName = "Fixed Objective"
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							horizontalAlignment = center
							icon = tick
							id = YV__V
					}
				}
			}
			--- TableColumn ---
				column-name = fixedCellF !
				column-type = domain !
				domainAttribute = fixedCellF !
				type = text
				column-sortable = false
				column-visibility = never-visible
				id = fixedCellF
				table-column-width = 12
			{
				--- TableColumnItem ---
					item-column = fixedCellF
					previewValue = Fixed
			}
			--- TableColumn ---
				column-name = criticalnessELabel !
				column-type = domain !
				domainAttribute = criticalnessELabel !
				type = text
				column-is-part-of-filter = false
				id = criticalnessELabel
				table-column-width = 12
			{
				--- TableColumnItem ---
					item-column = criticalnessELabel
					previewValue = Low
			}
			--- TableColumn ---
				column-name = criticalnessE !
				column-type = domain !
				domainAttribute = criticalnessE !
				type = text
				column-sortable = false
				column-visibility = never-visible
				id = criticalnessE
				table-column-width = 12
			{
				--- TableColumnItem ---
					item-column = criticalnessE
					previewValue = Low
			}
			--- TableSort ---
				sort-column-name = MKT_STRUCTURE_SORT
				sort-rank = 1
			--- TableExtra ---
				domainAttribute = id
			--- TableExtra ---
				domainAttribute = row_id
		}
	}
}