# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSAllocationConstraintAdmin:AllocationConstraintObjectives"
	cssClass = nodeco
	bean-define = DSBean.AAADSAllocationConstraintAdmin.AllocationConstraintObjectives
	bean-name = AllocationConstraintObjectives
	id = AllocationConstraintObjectivesEdit_l_v1m
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			table-editable-dataset = "AAADSModelConstrElt:AllocationConstraintElement"
			table-format-identifier = id
			table-row-identifier = id
			id = V__KQ
			table-column-count = 6 !
			table-columns-width = "16,16,16,16,16,16" !
		{
			--- TableColumn ---
				labels en = "Market Segment", fr = "Segment de marché", de = Marktsegment
				column-display-grouping = true
				column-name = MarketSegment
				column-type = placeholder !
				type = text
				column-locked = true
				column-sortable = false !
				id = b_8_9
				table-column-width = 16
				tid = 100083985660679
			{
				--- TableGroup ---
					aggregateData = false
					group-column-name = MARKET_STRUCTURE
					group-sorting-column-name = MKT_STRUCTURE_SORT
					group-sorting-direction = ascending
					hierarchy = true
					group-rank = 1
			}
			--- TableColumn ---
				column-name = minWeightN !
				column-type = domain !
				domainAttribute = minWeightN !
				format = decimal.detailed
				type = text
				id = minWeightN
				table-column-width = 16
			{
				--- TableColumnText ---
					item-column = minWeightN
					table-column-item-dataset-attribute = minWeightN
					columns = 22
					format = percentTA
					type = decimal
					chars = 22
					enabled = conditional
					enabledIsBasedOn = fixedCellF
					enabledIsBasedOn-simplified = "AAADSAllocationConstraintAdmin:AllocationConstraintObjectives#fixedCellF"
				{
					Event OnChange (submit)
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						widget-group-ref = form
						param = "flow-action=reload"
						only-changed = true
						modal = false
						prevalidate = false
					}
				}
			}
			--- TableColumn ---
				column-name = OBJECTIVE_WEIGHT !
				column-type = domain !
				domainAttribute = OBJECTIVE_WEIGHT !
				type = text
				column-is-part-of-filter = false
				column-sortable = false
				id = OBJECTIVE_WEIGHT
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = OBJECTIVE_WEIGHT
					previewValue = "40.00% +/- 0.20%"
			}
			--- TableColumn ---
				column-name = maxWeightN !
				column-type = domain !
				domainAttribute = maxWeightN !
				format = decimal.detailed
				type = text
				id = maxWeightN
				table-column-width = 16
			{
				--- TableColumnText ---
					item-column = maxWeightN
					table-column-item-dataset-attribute = maxWeightN
					columns = 22
					format = percentTA
					previewValue = 43.00%
					type = decimal
					chars = 22
					enabled = conditional
					enabledIsBasedOn = fixedCellF
					enabledIsBasedOn-simplified = "AAADSAllocationConstraintAdmin:AllocationConstraintObjectives#fixedCellF"
				{
					Event OnChange (submit)
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						widget-group-ref = form
						param = "flow-action=reload"
						only-changed = true
						modal = false
						prevalidate = false
					}
				}
			}
			--- TableColumn ---
				column-name = fixedCellF !
				column-type = domain !
				domainAttribute = fixedCellF !
				type = text
				id = fixedCellF
				table-column-width = 16
			{
				--- TableColumnCombobox ---
					item-column = fixedCellF
					table-column-item-dataset-attribute = fixedCellF
					previewValue = Variable
				{
					Event OnChange (submit)
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						widget-group-ref = form
						param = "flow-action=reload"
						only-changed = true
						modal = false
						prevalidate = false
					}
				}
			}
			--- TableColumn ---
				column-name = criticalnessE !
				column-type = domain !
				domainAttribute = criticalnessE !
				type = text
				id = criticalnessE
				table-column-width = 16
			{
				--- TableColumnCombobox ---
					item-column = criticalnessE
					table-column-item-dataset-attribute = criticalnessE
					previewValue = Low
			}
			--- TableSort ---
				sort-column-name = MKT_STRUCTURE_SORT
				sort-rank = 1
			--- TableExtra ---
				domainAttribute = id
			--- TableExtra ---
				domainAttribute = row_id
		}
	}
}