# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels fr = "Liste de positions", en = "List of Positions", de = Bestandsliste
	containment = container
	domainEntity = "AAADSValuation:ValuationDetailledList"
	verticalAlignment = lead
	bean-define = DSBean.AAADSValuation.ValuationDetailledList
	bean-name = ValuationDetailledList
	id = CopyOfDetailedList_f85_z
	tid = 88431011767961
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TabbedPane ---
			hide-empty-tabs = true
			tabs-filtered-attribute = ASSET_CLASS_RANK
			id = HT1v9
			indexOfSelectedChild = 0
		{
			--- Tab ---
				labels en = All, fr = Tous, de = Alle
				boxType = vertical
				id = tab_A0__r
				isWidgetSelected = true
				tid = 88431027403400
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/heldasset/detailedlist/ByAssetClass/AllAccounting.module
				--- Include ---
					includeSrc = "" !
					resource:///default/initiateorder/NavigationInitiateOrderFromHeldAsset.fragment
			}
			--- Tab ---
				labels fr = Action, en = Stocks, de = Aktien
				hide-empty-tab = true
				tab-filter = 1
				boxType = vertical
				id = tab_ztz_5
				isWidgetVisible = false
				tid = 88431028387592
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/heldasset/detailedlist/ByAssetClass/StockAccounting.module
				--- Include ---
					includeSrc = "" !
					resource:///default/initiateorder/NavigationInitiateOrderFromHeldAsset.fragment
			}
			--- Tab ---
				labels en = "Fixed Income", fr = "Titre à revenu fixe", de = Anleihen
				hide-empty-tab = true
				tab-filter = 2
				boxType = vertical
				id = tab_L1___
				isWidgetVisible = false
				tid = 88431029386755
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/heldasset/detailedlist/ByAssetClass/FIAccounting.module
				--- Include ---
					includeSrc = "" !
					resource:///default/initiateorder/NavigationInitiateOrderFromHeldAsset.fragment
			}
			--- Tab ---
				labels en = Funds, de = Fondsanteile, fr = Fonds
				hide-empty-tab = true
				tab-filter = 3
				boxType = vertical
				id = tab_W8_45
				isWidgetVisible = false
				tid = 88431030386345
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/heldasset/detailedlist/ByAssetClass/FundAccounting.module
				--- Include ---
					includeSrc = "" !
					resource:///default/initiateorder/NavigationInitiateOrderFromHeldAsset.fragment
			}
			--- Tab ---
				labels en = Derivatives, de = Derivate, fr = Dérivés
				hide-empty-tab = true
				tab-filter = 4
				boxType = vertical
				id = tab_qrH03
				isWidgetVisible = false
				tid = 88431032323078
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/heldasset/detailedlist/ByAssetClass/DerivativesAccounting.module
				--- Include ---
					includeSrc = "" !
					resource:///default/initiateorder/NavigationInitiateOrderFromHeldAsset.fragment
			}
			--- Tab ---
				labels en = Liquidity, de = Liquidität, fr = Liquidité
				hide-empty-tab = true
				tab-filter = 5
				id = tab_vdKI8
				isWidgetVisible = false
				tid = 88431032386809
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/heldasset/detailedlist/ByAssetClass/LiquidityAccounting.module
			}
			--- Tab ---
				labels en = "Money Market", fr = "Marché monétaire", de = Geldmarkt
				hide-empty-tab = true
				tab-filter = 6
				boxType = vertical
				id = tab_vrr1_
				isWidgetVisible = false
				tid = 88431033388110
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/heldasset/detailedlist/ByAssetClass/MMAccounting.module
				--- Include ---
					includeSrc = "" !
					resource:///default/initiateorder/NavigationInitiateOrderFromHeldAsset.fragment
			}
			--- Tab ---
				labels en = Forwards, de = Devisentermin
				hide-empty-tab = true
				tab-filter = 7
				id = tab_Q7R1_
				isWidgetVisible = false
				tid = 88431034391550
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/heldasset/detailedlist/ByAssetClass/ForwardsAccounting.module
			}
			--- Tab ---
				labels en = Others, fr = Alternatifs, de = "Übrige Anlagen"
				hide-empty-tab = true
				tab-filter = 99
				boxType = vertical
				id = tab_ro_35
				isWidgetVisible = false
				tid = 88431035388574
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/heldasset/detailedlist/ByAssetClass/OthersAccounting.module
				--- Include ---
					includeSrc = "" !
					resource:///default/initiateorder/NavigationInitiateOrderFromHeldAsset.fragment
			}
		}
	}
}