# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSExtOperation:ExtOperationAll"
	cssClass = nodeco
	bean-define = DSBean.AAADSExtOperation.ExtOperationAll
	bean-name = ExtOperationAll
	id = AdditionalDataView_A_3_B
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			id = j4___
			indexOfSelectedChild = 3
		{
			--- Tab ---
				labels en = Communication, fr = Communication, de = Kommunikation
				id = tab_WF_1n
				isWidgetVisible = false
				tid = 668323476706955
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/extoperation/order/CommunicationView.fragment
			}
			--- Tab ---
				labels de = Handel, fr = Marché, en = Trading
				id = tab_z_24t
				isWidgetVisible = false
				tid = 668323493030818
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/extoperation/order/TradingView.fragment
			}
			--- Tab ---
				labels en = Booking, fr = Réservation, de = Verbuchung
				id = tab_bf___
				isWidgetVisible = false
				tid = 668323494883008
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/extoperation/order/BookingView.fragment
			}
			--- Tab ---
				labels en = "Fees & Taxes", fr = "Fees & Taxes", de = "Fees & Taxes"
				id = tab_t1_Ak
				isWidgetSelected = true
				tid = 668323496873764
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/extoperation/order/FeesAndTaxesView.fragment
			}
		}
	}
}