# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "View Call Amendment Order", de = "Änderungsauftrag Kündigungsgeld ansehen", fr = "Voir les appels d\'ordres en modification"
	containment = container
	domainEntity = "AAADSExtOperation:ExtOperationAll"
	bean-define = DSBean.AAADSExtOperation.ExtOperationAll
	bean-name = ExtOperationAll
	id = CallAmendmentView_v_2_2
	tid = 69057823193729
{
	--- Box ---
		boxType = vertical
	{
		--- TextArea ---
			domainAttribute = summaryC !
			columns = 200
			horizontalAlignment = "${corporatehalign}"
			rows = 1
			type = text
			bean-property = summaryC
			id = summaryC
		--- Include ---
			includeSrc = "" !
			resource:///default/extoperation/basicelements/OrderHeadView.fragment
		--- Box ---
			labels en = Identification, de = Identifikation, fr = Identification
			boxType = vertical
			tid = 5571900576076
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 4
				gridColumnsWidth = "25,25,25,25" !
				gridRowCount = 2
			{
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- LabelDomain ---
						labels en = Contract
						domainAttribute = sourceCode !
						for = sourceCode
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						tid = 161201969010307
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- TextField ---
						domainAttribute = sourceCode !
						horizontalAlignment = "${corporatehalign}"
						type = text
						chars = 20
						editable = false
						bean-property = sourceCode
						id = sourceCode
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- LabelDomain ---
						domainAttribute = valueD !
						for = valueD
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- CaldateField ---
						domainAttribute = valueD !
						format = datetime.date-only
						horizontalAlignment = "${corporatehalign}"
						type = datetime
						editable = false
						required = true
						bean-property = valueD
						id = valueD
					{
						Event OnChange (submit)
						{
							method = post
							call-URI = "<pageflow:continuation/>"
							widget-group-ref = form
							param = "flow-action=reload"
							only-changed = true
							modal = false
							prevalidate = false
						}
					}
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- LabelDomain ---
						domainAttribute = portfolio !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- Include ---
						domainAssociation = portfolio
						includeSrc = "" !
						resource:///default/defaultFragments/PortfolioIdentifierView.fragment
						bean-property-prefix = portfolio.
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- LabelDomain ---
						labels en = "Portfolio Name", fr = "Nom du portefeuille"
						domainAttribute = portfolio !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						tid = 3303654636980957
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- Include ---
						domainAssociation = portfolio
						includeSrc = "" !
						resource:///default/extoperation/basicelements/PortfolioNameIdentifier.fragment
						bean-property-prefix = portfolio.
				}
			}
		}
		--- Box ---
			labels en = Instruction, de = Instruktion, fr = Instruction
			boxType = vertical
			tid = 13558526932892
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 4
				gridColumnsWidth = "25,25,25,25" !
				gridRowCount = 2
			{
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- LabelDomain ---
						labels en = Amount, fr = Montant, de = Betrag
						domainAttribute = quantityN !
						for = quantityN
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						tid = 5571914785282
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- Box ---
					{
						--- TextField ---
							domainAttribute = quantityN !
							columns = 21
							format = decimal.detailed
							horizontalAlignment = "${corporatehalign}"
							type = decimal
							allow = "\'0123456789.,\'"
							chars = 23
							editable = false
							required = true
							bean-property = quantityN
							id = quantityN
						{
							Event OnChange (submit)
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								widget-group-ref = form
								param = "flow-action=reload"
								only-changed = true
								modal = false
								prevalidate = false
							}
						}
						--- Include ---
							domainAssociation = account
							includeSrc = "" !
							resource:///default/defaultFragments/InstrumentIdentifierView.fragment
							bean-property-prefix = account.
						--- Include ---
							domainAssociation = accCurrency
							includeSrc = "" !
							resource:///default/defaultFragments/CurrencyIdentifierView.fragment
							bean-property-prefix = accCurrency.
					}
				}
				--- GridCell ---
					gridColumnWidth = 25
				--- GridCell ---
					gridColumnWidth = 25
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- LabelDomain ---
						domainAttribute = rateP !
						for = rateP
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- TextField ---
						domainAttribute = rateP !
						columns = 11
						format = decimal.5-digits
						horizontalAlignment = "${corporatehalign}"
						type = percent
						allow = "\'0123456789.,\'"
						chars = 11
						editable = false
						bean-property = rateP
						id = rateP
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- LabelDomain ---
						domainAttribute = counterpartyThird !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- Include ---
						domainAssociation = counterpartyThird
						includeSrc = "" !
						resource:///default/defaultFragments/ThirdPartyIdentifierView.fragment
						bean-property-prefix = counterpartyThird.
				}
			}
		}
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/extoperation/order/view/SingleOrderSecurityCommunicationView.module
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/extoperation/order/view/OrderTradingView.module
		--- Include ---
			includeSrc = "" !
			resource:///default/extoperation/basicelements/OrderHeadView.fragment
		--- Grid ---
			cssClass = blank
			gridColumnCount = 4
			gridColumnsWidth = "25,25,25,25" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Button ---
					labels en = Back, de = Zurück, fr = Retour
					id = btn_H0_o_
					tid = 116386435846533
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						widget-group-ref = form
						target = self
						flow-action = end ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
		}
	}
}