# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = Buy, de = "Devisenkassa-Auftrag ansehen"
	containment = container
	domainEntity = "AAADSExtOperation:ExtOperationAll"
	cssClass = nodeco
	bean-define = DSBean.AAADSExtOperation.ExtOperationAll
	bean-name = ExtOperationAll
	id = SingleOrderForexSpotView_Tt_95
	tid = 881053298563364
{
	--- Box ---
		boxType = vertical
	{
		--- TextArea ---
			domainAttribute = summaryC !
			columns = 200
			horizontalAlignment = "${corporatehalign}"
			rows = 1
			type = text
			editable = false
			bean-property = summaryC
			id = summaryC
		--- Box ---
			labels en = Identification, de = Identifikation, fr = Identification
			boxType = vertical
			tid = 881053299303961
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 4
				gridColumnsWidth = "25,25,25,25" !
				gridRowCount = 2
			{
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- LabelDomain ---
						domainAttribute = natureE !
						for = natureE
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- Conditional ---
						indexOfSelectedChild = 0
					{
						--- ConditionalBody ---
							javaCode = "null != <bean:get-property bean=\"ExtOperationAll\" property=\"orderType\"/> &amp;&amp; \r\n(\"PCK_DS_ACCT_SAME_CCY\".equals(<bean:get-property bean=\"ExtOperationAll\" property=\"orderType.code\"/>.toString()))"
							technicalName = Condition
							boxType = vertical
							isWidgetSelected = true
						{
							--- Code ---
								code = "<xgui:combobox editable=\"false\" id=\"natureE\" required=\"true\" widget-group=\"form\">\r\n  <xgui:selected-value>\r\n\t<bean:get-property bean=\"ExtOperationAll\" property=\"natureE\"/>\r\n  </xgui:selected-value>\r\n  <xgui:item>\r\n\t<xgui:value>1</xgui:value>\r\n\t<xgui:text>\r\n\t  <i18n:text>forex.ACCT_SAME_CCY.buy.text</i18n:text>\r\n\t</xgui:text>\r\n  </xgui:item>\r\n  <xgui:item>\r\n\t<xgui:value>2</xgui:value>\r\n\t<xgui:text>\r\n\t  <i18n:text>forex.ACCT_SAME_CCY.sell.text</i18n:text>\r\n\t</xgui:text>\r\n  </xgui:item>\r\n</xgui:combobox>"
						}
						--- ConditionalBody ---
							javaCode = true
							technicalName = Default
							boxType = vertical
							isWidgetVisible = false
						{
							--- ComboBox ---
								domainAttribute = natureE !
								horizontalAlignment = "${corporatehalign}"
								editable = false
								required = true
								bean-property = natureE
								id = natureE
						}
					}
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- LabelDomain ---
						labels en = Type
						domainAttribute = orderType !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						tid = 451710885905331
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- Include ---
						domainAssociation = orderType
						includeSrc = "" !
						resource:///default/defaultFragments/TypeIdentifierDenomView.fragment
						bean-property-prefix = orderType.
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- LabelDomain ---
						domainAttribute = portfolio !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- Include ---
						domainAssociation = portfolio
						includeSrc = "" !
						resource:///default/defaultFragments/PortfolioIdentifierView.fragment
						bean-property-prefix = portfolio.
					--- Include ---
						domainAssociation = functionResult
						includeSrc = "" !
						resource:///default/domain/basicelements/DomainId.fragment
						bean-property-prefix = functionResult.
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- LabelDomain ---
						labels en = "Portfolio Name", de = "Portfolio Name", fr = "Nom du portefeuille"
						domainAttribute = portfolio !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						tid = 881053301238285
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- Include ---
						domainAssociation = portfolio
						includeSrc = "" !
						resource:///default/extoperation/basicelements/PortfolioNameIdentifier.fragment
						bean-property-prefix = portfolio.
				}
			}
		}
		--- Conditional ---
			indexOfSelectedChild = 0
		{
			--- ConditionalBody ---
				javaCode = "null != <bean:get-property bean=\"ExtOperationAll\" property=\"portfolio.code\"/> &amp;&amp; null != <bean:get-property bean=\"ExtOperationAll\" property=\"portfolio.code\"/>"
				technicalName = IsPtfSelected
				boxType = vertical
				isWidgetSelected = true
			{
				--- Conditional ---
					technicalName = "Transfer From"
					indexOfSelectedChild = 1
				{
					--- ConditionalBody ---
						javaCode = "Integer.toString(com.odcgroup.aaa.OperationNatureE.Sell).equals(<bean:get-property bean=\"ExtOperationAll\" property=\"natureE\"/>.toString()) &amp;&amp; \r\nnull != <bean:get-property bean=\"ExtOperationAll\" property=\"orderType\"/> &amp;&amp; \r\n(\"PCK_DS_FXSPOT_NEGO\".equals(<bean:get-property bean=\"ExtOperationAll\" property=\"orderType.code\"/>.toString()) ||\r\n\"PCK_DS_FXSPOT_CONV\".equals(<bean:get-property bean=\"ExtOperationAll\" property=\"orderType.code\"/>.toString()))"
						technicalName = IsSellFxSpot
						boxType = vertical
						isWidgetVisible = false
					{
						--- Box ---
							labels en = Instruction, de = Instruktion, fr = Instruction
							boxType = vertical
							tid = 881053303190489
						{
							--- Grid ---
								cssClass = blank
								gridColumnCount = 4
								gridColumnsWidth = "25,25,25,25" !
								gridRowCount = 3
							{
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = Sell
										domainAttribute = opCurrency !
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 538808997355809
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- Include ---
											domainAssociation = opCurrency
											includeSrc = "" !
											resource:///default/defaultFragments/CurrencyIdentifierView.fragment
											bean-property-prefix = opCurrency.
										--- TextField ---
											domainAttribute = quantityN !
											columns = 21
											format = decimal
											horizontalAlignment = "${corporatehalign}"
											type = decimal
											allow = "\'0123456789.,\'"
											chars = 23
											editable = false
											required = true
											bean-property = quantityN
											id = quantityN
										{
											Event OnChange (submit)
											{
												method = post
												call-URI = "<pageflow:continuation/>"
												widget-group-ref = form
												param = "flow-action=reload"
												only-changed = true
												modal = false
												prevalidate = false
											}
										}
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = Buy
										domainAttribute = accCurrency !
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 539054777736555
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- Include ---
											domainAssociation = accCurrency
											includeSrc = "" !
											resource:///default/defaultFragments/CurrencyIdentifierView.fragment
											bean-property-prefix = accCurrency.
										--- TextField ---
											domainAttribute = accNetAmountM !
											columns = 21
											format = decimal
											horizontalAlignment = "${corporatehalign}"
											type = amount
											chars = 18
											editable = false
											bean-property = accNetAmountM
											id = accNetAmountM
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = "Debited Account", de = "Belastetes Konto", fr = "Compte débité"
										domainAttribute = instr !
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										required = true
										tid = 881053305143810
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- Include ---
											domainAssociation = instr
											includeSrc = "" !
											resource:///default/defaultFragments/InstrumentIdentifierView.fragment
											bean-property-prefix = instr.
										--- Include ---
											domainAssociation = opCurrency
											includeSrc = "" !
											resource:///default/defaultFragments/CurrencyIdentifierView.fragment
											bean-property-prefix = opCurrency.
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = "Credited Account"
										domainAttribute = account !
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 539017121738377
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- Include ---
											domainAssociation = account
											includeSrc = "" !
											resource:///default/defaultFragments/InstrumentIdentifierView.fragment
											bean-property-prefix = account.
										--- Include ---
											domainAssociation = accCurrency
											includeSrc = "" !
											resource:///default/defaultFragments/CurrencyIdentifierView.fragment
											bean-property-prefix = accCurrency.
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								--- GridCell ---
									gridColumnWidth = 25
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										domainAttribute = valueD !
										for = valueD
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- CaldateField ---
										domainAttribute = valueD !
										format = datetime.date-only
										horizontalAlignment = "${corporatehalign}"
										type = datetime
										editable = false
										bean-property = valueD
										id = valueD
								}
							}
						}
					}
					--- ConditionalBody ---
						javaCode = "Integer.toString(com.odcgroup.aaa.OperationNatureE.Buy).equals(<bean:get-property bean=\"ExtOperationAll\" property=\"natureE\"/>.toString()) &amp;&amp; \r\nnull != <bean:get-property bean=\"ExtOperationAll\" property=\"orderType\"/> &amp;&amp; \r\n(\"PCK_DS_FXSPOT_NEGO\".equals(<bean:get-property bean=\"ExtOperationAll\" property=\"orderType.code\"/>.toString()) ||\r\n\"PCK_DS_FXSPOT_CONV\".equals(<bean:get-property bean=\"ExtOperationAll\" property=\"orderType.code\"/>.toString()))"
						technicalName = IsBuyFxSpot
						boxType = vertical
						isWidgetSelected = true
					{
						--- Box ---
							labels en = Instruction, de = Instruktion, fr = Instruction
							boxType = vertical
							tid = 881053312956814
						{
							--- Grid ---
								cssClass = blank
								gridColumnCount = 4
								gridColumnsWidth = "25,25,25,25" !
								gridRowCount = 3
							{
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = Buy
										domainAttribute = opCurrency !
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 539379746759993
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- Include ---
											domainAssociation = opCurrency
											includeSrc = "" !
											resource:///default/defaultFragments/CurrencyIdentifierView.fragment
											bean-property-prefix = opCurrency.
										--- TextField ---
											domainAttribute = quantityN !
											columns = 21
											format = decimal
											horizontalAlignment = "${corporatehalign}"
											type = decimal
											allow = "\'0123456789.,\'"
											chars = 23
											editable = false
											required = true
											bean-property = quantityN
											id = quantityN
										{
											Event OnChange (submit)
											{
												method = post
												call-URI = "<pageflow:continuation/>"
												widget-group-ref = form
												param = "flow-action=reload"
												only-changed = true
												modal = false
												prevalidate = false
											}
										}
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = Sell
										domainAttribute = accCurrency !
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 539427105803391
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- Include ---
											domainAssociation = accCurrency
											includeSrc = "" !
											resource:///default/defaultFragments/CurrencyIdentifierView.fragment
											bean-property-prefix = accCurrency.
										--- TextField ---
											domainAttribute = accNetAmountM !
											columns = 21
											format = decimal
											horizontalAlignment = "${corporatehalign}"
											type = amount
											chars = 23
											editable = false
											required = true
											bean-property = accNetAmountM
											id = accNetAmountM
										{
											Event OnChange (submit)
											{
												method = post
												call-URI = "<pageflow:continuation/>"
												widget-group-ref = form
												param = "flow-action=reload"
												only-changed = true
												modal = false
												prevalidate = false
											}
										}
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = "Credited Account", de = "Erkanntes Konto", fr = "Compte crédité"
										domainAttribute = instr !
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										required = true
										tid = 881053314909297
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- Include ---
											domainAssociation = instr
											includeSrc = "" !
											resource:///default/defaultFragments/InstrumentIdentifierView.fragment
											bean-property-prefix = instr.
										--- Include ---
											domainAssociation = opCurrency
											includeSrc = "" !
											resource:///default/defaultFragments/CurrencyIdentifierView.fragment
											bean-property-prefix = opCurrency.
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = "Debited Account", de = "Belastetes Konto", fr = "Compte débité"
										domainAttribute = account !
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										required = true
										tid = 881053316940840
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- Include ---
											domainAssociation = account
											includeSrc = "" !
											resource:///default/defaultFragments/InstrumentIdentifierView.fragment
											bean-property-prefix = account.
										--- Include ---
											domainAssociation = accCurrency
											includeSrc = "" !
											resource:///default/defaultFragments/CurrencyIdentifierView.fragment
											bean-property-prefix = accCurrency.
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								--- GridCell ---
									gridColumnWidth = 25
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										domainAttribute = valueD !
										for = valueD
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- CaldateField ---
										domainAttribute = valueD !
										format = datetime.date-only
										horizontalAlignment = "${corporatehalign}"
										type = datetime
										editable = false
										bean-property = valueD
										id = valueD
								}
							}
						}
					}
					--- ConditionalBody ---
						javaCode = "Integer.toString(com.odcgroup.aaa.OperationNatureE.Buy).equals(<bean:get-property bean=\"ExtOperationAll\" property=\"natureE\"/>.toString()) &amp;&amp; \r\nnull != <bean:get-property bean=\"ExtOperationAll\" property=\"orderType\"/> &amp;&amp; \r\n(\"PCK_DS_FXFWD_NEGO\".equals(<bean:get-property bean=\"ExtOperationAll\" property=\"orderType.code\"/>.toString()) ||\r\n\"PCK_DS_FXFWD_CONV\".equals(<bean:get-property bean=\"ExtOperationAll\" property=\"orderType.code\"/>.toString()))"
						technicalName = IsBuyFxForward
						boxType = vertical
						isWidgetVisible = false
					{
						--- Box ---
							labels en = Instruction, fr = Instruction, de = Instruktion
							boxType = vertical
							tid = 441148865221976
						{
							--- Grid ---
								cssClass = blank
								gridColumnCount = 4
								gridColumnsWidth = "25,25,25,25" !
								gridRowCount = 3
							{
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = Buy
										domainAttribute = acc2Currency !
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 262765241163890
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- Include ---
											domainAssociation = acc2Currency
											includeSrc = "" !
											resource:///default/defaultFragments/CurrencyIdentifierView.fragment
											bean-property-prefix = acc2Currency.
										--- TextField ---
											domainAttribute = quantityN !
											columns = 21
											format = decimal
											horizontalAlignment = "${corporatehalign}"
											type = decimal
											allow = "\'0123456789.,\'"
											chars = 23
											editable = false
											required = true
											bean-property = quantityN
											id = quantityN
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = Sell
										domainAttribute = opCurrency !
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 262890051867485
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- Include ---
											domainAssociation = opCurrency
											includeSrc = "" !
											resource:///default/defaultFragments/CurrencyIdentifierView.fragment
											bean-property-prefix = opCurrency.
										--- TextField ---
											domainAttribute = accNetAmountM !
											columns = 16
											format = decimal
											horizontalAlignment = "${corporatehalign}"
											type = amount
											chars = 18
											editable = false
											bean-property = accNetAmountM
											id = accNetAmountM
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = "Credited Account"
										domainAttribute = account2 !
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 262804926171622
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- Include ---
											domainAssociation = account2
											includeSrc = "" !
											resource:///default/defaultFragments/InstrumentIdentifierView.fragment
											bean-property-prefix = account2.
										--- Include ---
											domainAssociation = acc2Currency
											includeSrc = "" !
											resource:///default/defaultFragments/CurrencyIdentifierView.fragment
											bean-property-prefix = acc2Currency.
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = "Debited Account", de = "Belastetes Konto", fr = "Compte débité"
										domainAttribute = account !
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										required = true
										tid = 441148867901088
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- Include ---
											domainAssociation = account
											includeSrc = "" !
											resource:///default/defaultFragments/InstrumentIdentifierView.fragment
											bean-property-prefix = account.
										--- Include ---
											domainAssociation = accCurrency
											includeSrc = "" !
											resource:///default/defaultFragments/CurrencyIdentifierView.fragment
											bean-property-prefix = accCurrency.
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = Length
										domainAttribute = contractLengthN !
										for = contractLengthN
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 441148873757139
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- TextField ---
										domainAttribute = contractLengthN !
										columns = 9
										format = integer
										horizontalAlignment = "${corporatehalign}"
										type = integer
										chars = 9
										editable = false
										bean-property = contractLengthN
										id = contractLengthN
									--- ComboBox ---
										domainAttribute = contractLengthUnitE !
										horizontalAlignment = "${corporatehalign}"
										editable = false
										required = true
										bean-property = contractLengthUnitE
										id = contractLengthUnitE
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										domainAttribute = valueD !
										for = valueD
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- CaldateField ---
										domainAttribute = valueD !
										format = datetime.date-only
										horizontalAlignment = "${corporatehalign}"
										type = datetime
										editable = false
										required = true
										bean-property = valueD
										id = valueD
									{
										Event OnChange (submit)
										{
											method = post
											call-URI = "<pageflow:continuation/>"
											widget-group-ref = form
											param = "flow-action=reload"
											only-changed = true
											modal = false
											prevalidate = false
										}
									}
								}
							}
						}
					}
					--- ConditionalBody ---
						javaCode = "Integer.toString(com.odcgroup.aaa.OperationNatureE.Sell).equals(<bean:get-property bean=\"ExtOperationAll\" property=\"natureE\"/>.toString()) &amp;&amp; \r\nnull != <bean:get-property bean=\"ExtOperationAll\" property=\"orderType\"/> &amp;&amp; \r\n(\"PCK_DS_FXFWD_NEGO\".equals(<bean:get-property bean=\"ExtOperationAll\" property=\"orderType.code\"/>.toString()) ||\r\n\"PCK_DS_FXFWD_CONV\".equals(<bean:get-property bean=\"ExtOperationAll\" property=\"orderType.code\"/>.toString()))"
						technicalName = isSellFxForward
						boxType = vertical
						isWidgetVisible = false
					{
						--- Box ---
							labels en = Instruction, de = Instruktion, fr = Instruction
							boxType = vertical
							tid = 441170749794457
						{
							--- Grid ---
								cssClass = blank
								gridColumnCount = 4
								gridColumnsWidth = "25,25,25,25" !
								gridRowCount = 3
							{
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = Sell
										domainAttribute = acc2Currency !
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 263304910910744
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- Include ---
											domainAssociation = acc2Currency
											includeSrc = "" !
											resource:///default/defaultFragments/CurrencyIdentifierView.fragment
											bean-property-prefix = acc2Currency.
										--- TextField ---
											domainAttribute = quantityN !
											columns = 21
											format = decimal
											horizontalAlignment = "${corporatehalign}"
											type = decimal
											allow = "\'0123456789.,\'"
											chars = 23
											editable = false
											required = true
											bean-property = quantityN
											id = quantityN
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = Buy
										domainAttribute = opCurrency !
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 263304911943277
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- Include ---
											domainAssociation = opCurrency
											includeSrc = "" !
											resource:///default/defaultFragments/CurrencyIdentifierView.fragment
											bean-property-prefix = opCurrency.
										--- TextField ---
											domainAttribute = accNetAmountM !
											columns = 16
											format = decimal
											horizontalAlignment = "${corporatehalign}"
											type = amount
											chars = 18
											editable = false
											bean-property = accNetAmountM
											id = accNetAmountM
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = "Debited Account"
										domainAttribute = account2 !
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 263304921560142
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- Include ---
											domainAssociation = account2
											includeSrc = "" !
											resource:///default/defaultFragments/InstrumentIdentifierView.fragment
											bean-property-prefix = account2.
										--- Include ---
											domainAssociation = acc2Currency
											includeSrc = "" !
											resource:///default/defaultFragments/CurrencyIdentifierView.fragment
											bean-property-prefix = acc2Currency.
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = "Credited Account", de = "Belastetes Konto", fr = "Compte débité"
										domainAttribute = account !
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										required = true
										tid = 263304923464295
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- Include ---
											domainAssociation = account
											includeSrc = "" !
											resource:///default/defaultFragments/InstrumentIdentifierView.fragment
											bean-property-prefix = account.
										--- Include ---
											domainAssociation = accCurrency
											includeSrc = "" !
											resource:///default/defaultFragments/CurrencyIdentifierView.fragment
											bean-property-prefix = accCurrency.
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = Length
										domainAttribute = contractLengthN !
										for = contractLengthN
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 263304925398898
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- TextField ---
										domainAttribute = contractLengthN !
										columns = 9
										format = integer
										horizontalAlignment = "${corporatehalign}"
										type = integer
										chars = 9
										editable = false
										bean-property = contractLengthN
										id = contractLengthN
									--- ComboBox ---
										domainAttribute = contractLengthUnitE !
										horizontalAlignment = "${corporatehalign}"
										editable = false
										required = true
										bean-property = contractLengthUnitE
										id = contractLengthUnitE
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										domainAttribute = valueD !
										for = valueD
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- CaldateField ---
										domainAttribute = valueD !
										format = datetime.date-only
										horizontalAlignment = "${corporatehalign}"
										type = datetime
										editable = false
										required = true
										bean-property = valueD
										id = valueD
									{
										Event OnChange (submit)
										{
											method = post
											call-URI = "<pageflow:continuation/>"
											widget-group-ref = form
											param = "flow-action=reload"
											only-changed = true
											modal = false
											prevalidate = false
										}
									}
								}
							}
						}
					}
					--- ConditionalBody ---
						javaCode = "Integer.toString(com.odcgroup.aaa.OperationNatureE.Sell).equals(<bean:get-property bean=\"ExtOperationAll\" property=\"natureE\"/>.toString()) &amp;&amp; \r\nnull != <bean:get-property bean=\"ExtOperationAll\" property=\"orderType\"/> &amp;&amp; \r\n(\"PCK_DS_ACCT_SAME_CCY\".equals(<bean:get-property bean=\"ExtOperationAll\" property=\"orderType.code\"/>.toString()))"
						technicalName = "Transfer From"
						boxType = vertical
						isWidgetVisible = false
					{
						--- Box ---
							labels en = Instruction, de = Instruktion, fr = Instruction
							boxType = vertical
							tid = 921835704043949
						{
							--- Grid ---
								cssClass = blank
								gridColumnCount = 4
								gridColumnsWidth = "25,25,25,25" !
								gridRowCount = 3
							{
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = "Amount to Debit"
										domainAttribute = opCurrency !
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 921835704949651
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- Include ---
											domainAssociation = opCurrency
											includeSrc = "" !
											resource:///default/defaultFragments/CurrencyIdentifierView.fragment
											bean-property-prefix = opCurrency.
										--- TextField ---
											domainAttribute = quantityN !
											columns = 21
											format = decimal
											horizontalAlignment = "${corporatehalign}"
											type = decimal
											allow = "\'0123456789.,\'"
											chars = 23
											editable = false
											required = true
											bean-property = quantityN
											id = quantityN
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = "Received Amount"
										domainAttribute = accCurrency !
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 921835706897664
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- Include ---
											domainAssociation = accCurrency
											includeSrc = "" !
											resource:///default/defaultFragments/CurrencyIdentifierView.fragment
											bean-property-prefix = accCurrency.
										--- TextField ---
											domainAttribute = accNetAmountM !
											columns = 21
											format = decimal
											type = amount
											chars = 18
											editable = false
											bean-property = accNetAmountM
											id = accNetAmountM
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = "Debited Account"
										domainAttribute = instr !
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 921835708847074
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- Include ---
											domainAssociation = instr
											includeSrc = "" !
											resource:///default/defaultFragments/InstrumentIdentifierView.fragment
											bean-property-prefix = instr.
										--- Include ---
											domainAssociation = opCurrency
											includeSrc = "" !
											resource:///default/defaultFragments/CurrencyIdentifierView.fragment
											bean-property-prefix = opCurrency.
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = "Credited Account"
										domainAttribute = account !
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 921835710800953
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- Include ---
											domainAssociation = account
											includeSrc = "" !
											resource:///default/defaultFragments/InstrumentIdentifierView.fragment
											bean-property-prefix = account.
										--- Include ---
											domainAssociation = accCurrency
											includeSrc = "" !
											resource:///default/defaultFragments/CurrencyIdentifierView.fragment
											bean-property-prefix = accCurrency.
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								--- GridCell ---
									gridColumnWidth = 25
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										domainAttribute = valueD !
										for = valueD
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- CaldateField ---
										domainAttribute = valueD !
										format = datetime.date-only
										horizontalAlignment = "${corporatehalign}"
										type = datetime
										editable = false
										bean-property = valueD
										id = valueD
								}
							}
						}
					}
					--- ConditionalBody ---
						javaCode = "Integer.toString(com.odcgroup.aaa.OperationNatureE.Buy).equals(<bean:get-property bean=\"ExtOperationAll\" property=\"natureE\"/>.toString()) &amp;&amp; \r\nnull != <bean:get-property bean=\"ExtOperationAll\" property=\"orderType\"/> &amp;&amp; \r\n(\"PCK_DS_ACCT_SAME_CCY\".equals(<bean:get-property bean=\"ExtOperationAll\" property=\"orderType.code\"/>.toString()))"
						technicalName = "Transfer To"
						boxType = vertical
						isWidgetVisible = false
					{
						--- Box ---
							labels en = Instruction, fr = Instruction, de = Instruktion
							boxType = vertical
							tid = 921897727520955
						{
							--- Grid ---
								cssClass = blank
								gridColumnCount = 4
								gridColumnsWidth = "25,25,25,25" !
								gridRowCount = 3
							{
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = "Amount to Credit"
										domainAttribute = opCurrency !
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 921897728420790
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- Include ---
											domainAssociation = opCurrency
											includeSrc = "" !
											resource:///default/defaultFragments/CurrencyIdentifierView.fragment
											bean-property-prefix = opCurrency.
										--- TextField ---
											domainAttribute = quantityN !
											columns = 21
											format = decimal
											horizontalAlignment = "${corporatehalign}"
											type = decimal
											allow = "\'0123456789.,\'"
											chars = 23
											editable = false
											required = true
											bean-property = quantityN
											id = quantityN
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = "Debited Amount"
										domainAttribute = accCurrency !
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 921897730338911
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- Include ---
											domainAssociation = accCurrency
											includeSrc = "" !
											resource:///default/defaultFragments/CurrencyIdentifierView.fragment
											bean-property-prefix = accCurrency.
										--- TextField ---
											domainAttribute = accNetAmountM !
											columns = 21
											format = decimal
											type = amount
											chars = 23
											editable = false
											required = true
											bean-property = accNetAmountM
											id = accNetAmountM
										{
											Event OnChange (submit)
											{
												method = post
												call-URI = "<pageflow:continuation/>"
												widget-group-ref = form
												param = "flow-action=reload"
												only-changed = true
												modal = false
												prevalidate = false
											}
										}
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = "Credited Account"
										domainAttribute = instr !
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 921897732288600
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- Include ---
											domainAssociation = instr
											includeSrc = "" !
											resource:///default/defaultFragments/InstrumentIdentifierView.fragment
											bean-property-prefix = instr.
										--- Include ---
											domainAssociation = opCurrency
											includeSrc = "" !
											resource:///default/defaultFragments/CurrencyIdentifierView.fragment
											bean-property-prefix = opCurrency.
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = "Debited Account", de = "Belastetes Konto", fr = "Compte débité"
										domainAttribute = account !
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										required = true
										tid = 921897734231585
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- Include ---
											domainAssociation = account
											includeSrc = "" !
											resource:///default/defaultFragments/InstrumentIdentifierView.fragment
											bean-property-prefix = account.
										--- Include ---
											domainAssociation = accCurrency
											includeSrc = "" !
											resource:///default/defaultFragments/CurrencyIdentifierView.fragment
											bean-property-prefix = accCurrency.
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								--- GridCell ---
									gridColumnWidth = 25
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										domainAttribute = valueD !
										for = valueD
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- CaldateField ---
										domainAttribute = valueD !
										format = datetime.date-only
										horizontalAlignment = "${corporatehalign}"
										type = datetime
										editable = false
										bean-property = valueD
										id = valueD
								}
							}
						}
					}
				}
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "null != <bean:get-property bean=\"ExtOperationAll\" property=\"orderType\"/> &amp;&amp; \r\n(\"PCK_DS_FXSPOT_NEGO\".equals(<bean:get-property bean=\"ExtOperationAll\" property=\"orderType.code\"/>.toString()) || \r\n\"PCK_DS_FXFWD_NEGO\".equals(<bean:get-property bean=\"ExtOperationAll\" property=\"orderType.code\"/>.toString()))"
						technicalName = IsFxNego
						boxType = vertical
						documentation = "It defines the fx rate conditions for Fx Spot order.\r\nIt requires having to buy or sell an amount into a currency against another currency."
						isWidgetSelected = true
					{
						--- Box ---
							labels en = Rate, fr = Taux
							boxType = vertical
							widgetBorder = box
							tid = 540428187353979
						{
							--- Grid ---
								cssClass = blank
								gridColumnCount = 4
								gridColumnsWidth = "25,25,25,25" !
								gridRowCount = 3
							{
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = "Client Rate", de = Kunden-Kurs, fr = "Taux client"
										domainAttribute = fxClientRateN !
										for = fxClientRateN
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 540428188499096
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- TextField ---
											domainAttribute = fxClientRateN !
											columns = 21
											format = decimal.detailed
											type = decimal
											allow = "\'0123456789.,\'"
											chars = 23
											editable = false
											bean-property = fxClientRateN
											id = fxClientRateN
										{
											Event OnChange (submit)
											{
												method = post
												call-URI = "<pageflow:continuation/>"
												widget-group-ref = form
												param = "flow-action=reload"
												only-changed = true
												stabs = "<xsp-request:get-parameter name=\"stabs\"/>" ud
												modal = false
												prevalidate = false
											}
										}
										--- ComboBox ---
											domainAttribute = fxRateDirectionF !
											horizontalAlignment = "${corporatehalign}"
											editable = false
											required = true
											bean-property = fxRateDirectionF
											id = fxRateDirectionF
										{
											Event OnChange (submit)
											{
												method = post
												call-URI = "<pageflow:continuation/>"
												widget-group-ref = form
												param = "flow-action=reload"
												only-changed = true
												stabs = "<xsp-request:get-parameter name=\"stabs\"/>" ud
												modal = false
												prevalidate = false
											}
										}
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = "Margin %"
										domainAttribute = fxMarginP !
										for = fxMarginP
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 540428190276417
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- TextField ---
											domainAttribute = fxMarginP !
											columns = 11
											format = percentTA
											horizontalAlignment = "${corporatehalign}"
											type = percent
											chars = 11
											editable = false
											bean-property = fxMarginP
											id = fxMarginP
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = "Margin pips"
										domainAttribute = fxMarginN !
										for = fxMarginN
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 540428192221916
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- TextField ---
										domainAttribute = fxMarginN !
										columns = 21
										format = decimal.detailed
										horizontalAlignment = "${corporatehalign}"
										type = decimal
										chars = 23
										editable = false
										bean-property = fxMarginN
										id = fxMarginN
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = "Margin Amount"
										domainAttribute = fxMarginM !
										for = fxMarginM
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 540428194159034
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- TextField ---
											domainAttribute = fxMarginM !
											columns = 21
											format = decimal
											horizontalAlignment = trail
											type = amount
											chars = 18
											editable = false
											bean-property = fxMarginM
											id = fxMarginM
										--- Include ---
											domainAssociation = opCurrency
											includeSrc = "" !
											resource:///default/defaultFragments/CurrencyIdentifierView.fragment
											bean-property-prefix = opCurrency.
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = "Market Rate", de = Basis-Kurs, fr = "Taux de base"
										domainAttribute = fxMarketRateN !
										for = fxMarketRateN
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 540428196119618
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- TextField ---
										domainAttribute = fxMarketRateN !
										columns = 21
										format = decimal.detailed
										horizontalAlignment = "${corporatehalign}"
										type = decimal
										chars = 23
										editable = false
										required = true
										bean-property = fxMarketRateN
										id = fxMarketRateN
									{
										Event OnChange (submit)
										{
											method = post
											call-URI = "<pageflow:continuation/>"
											widget-group-ref = form
											param = "flow-action=reload"
											only-changed = true
											stabs = "<xsp-request:get-parameter name=\"stabs\"/>" ud
											modal = false
											prevalidate = false
										}
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								--- GridCell ---
									gridColumnWidth = 25
							}
						}
					}
					--- ConditionalBody ---
						javaCode = "null != <bean:get-property bean=\"ExtOperationAll\" property=\"orderType\"/> &amp;&amp; \r\n(\"PCK_DS_FXSPOT_CONV\".equals(<bean:get-property bean=\"ExtOperationAll\" property=\"orderType.code\"/>.toString()) || \r\n\"PCK_DS_FXFWD_CONV\".equals(<bean:get-property bean=\"ExtOperationAll\" property=\"orderType.code\"/>.toString()))"
						technicalName = IsFxConv
						boxType = vertical
						isWidgetVisible = false
					{
						--- Box ---
							labels en = Rate, fr = Taux
							boxType = vertical
							widgetBorder = box
							tid = 540428198070145
						{
							--- Grid ---
								cssClass = blank
								gridColumnCount = 4
								gridColumnsWidth = "25,25,25,25" !
								gridRowCount = 3
							{
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = "Client Rate"
										domainAttribute = fxClientRateN !
										for = fxClientRateN
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 540428200029892
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- TextField ---
											domainAttribute = fxClientRateN !
											columns = 21
											format = decimal.detailed
											horizontalAlignment = "${corporatehalign}"
											type = decimal
											chars = 23
											editable = false
											bean-property = fxClientRateN
											id = fxClientRateN
										--- ComboBox ---
											domainAttribute = fxRateDirectionF !
											horizontalAlignment = "${corporatehalign}"
											editable = false
											required = true
											bean-property = fxRateDirectionF
											id = fxRateDirectionF
										{
											Event OnChange (submit)
											{
												method = post
												call-URI = "<pageflow:continuation/>"
												widget-group-ref = form
												param = "flow-action=reload"
												only-changed = true
												stabs = "<xsp-request:get-parameter name=\"stabs\"/>" ud
												modal = false
												prevalidate = false
											}
										}
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = "Margin %"
										domainAttribute = fxMarginP !
										for = fxMarginP
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 540428201988241
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- TextField ---
											domainAttribute = fxMarginP !
											columns = 11
											format = percentTA
											horizontalAlignment = "${corporatehalign}"
											type = percent
											chars = 11
											editable = false
											bean-property = fxMarginP
											id = fxMarginP
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = "Margin pips", fr = Marge, de = Marge
										domainAttribute = fxMarginN !
										for = fxMarginN
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 540428203933181
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- TextField ---
										domainAttribute = fxMarginN !
										columns = 21
										format = decimal.detailed
										type = decimal
										chars = 23
										editable = false
										bean-property = fxMarginN
										id = fxMarginN
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = "Margin Amount"
										domainAttribute = fxMarginM !
										for = fxMarginM
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 540428205894045
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- TextField ---
											domainAttribute = fxMarginM !
											columns = 21
											format = decimal
											horizontalAlignment = trail
											type = amount
											chars = 18
											editable = false
											bean-property = fxMarginM
											id = fxMarginM
										--- Include ---
											domainAssociation = opCurrency
											includeSrc = "" !
											resource:///default/defaultFragments/CurrencyIdentifierView.fragment
											bean-property-prefix = opCurrency.
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = "Market Rate", de = Basis-Kurs, fr = "Taux de base"
										domainAttribute = fxMarketRateN !
										for = fxMarketRateN
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 540428207863569
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- TextField ---
										domainAttribute = fxMarketRateN !
										columns = 21
										format = decimal.detailed
										horizontalAlignment = "${corporatehalign}"
										type = decimal
										chars = 23
										editable = false
										bean-property = fxMarketRateN
										id = fxMarketRateN
								}
								--- GridCell ---
									gridColumnWidth = 25
								--- GridCell ---
									gridColumnWidth = 25
							}
						}
					}
				}
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/extoperation/order/view/AdditionalDataOtherView.module
			}
		}
	}
}