# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "View Forex Order", de = "Devisen-auftrag ansehen", fr = "Voir l\'ordre de change"
	containment = container
	domainEntity = "AAADSExtOperation:ExtOperationAll"
	bean-define = DSBean.AAADSExtOperation.ExtOperationAll
	bean-name = ExtOperationAll
	id = ForexViewOnly_IqU_Z
	tid = 24104082055959
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/extoperation/order/view/ForexNoButtonView.module
		--- Include ---
			includeSrc = "" !
			resource:///default/extoperation/basicelements/OrderHeadView.fragment
		--- Grid ---
			cssClass = blank
			gridColumnCount = 4
			gridColumnsWidth = "25,25,25,25" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Button ---
					labels en = Back, de = Zurück, fr = Retour
					id = btn_jMQ9w
					tid = 24104083697788
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = end ud
						stabs = "<xsp-request:get-parameter name=\"stabs\"/>" ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
		}
	}
}