# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "View Forex Order", de = "Devisen-auftrag ansehen", fr = "Voir l\'ordre de change"
	containment = container
	domainEntity = "AAADSExtOperation:ExtOperationAll"
	bean-define = DSBean.AAADSExtOperation.ExtOperationAll
	bean-name = ExtOperationAll
	id = ForexView_jU8_K
	tid = 195081784228163
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/extoperation/order/view/ForexNoButtonView.module
		--- Include ---
			includeSrc = "" !
			resource:///default/extoperation/basicelements/OrderHeadView.fragment
		--- Grid ---
			cssClass = blank
			gridColumnCount = 4
			gridColumnsWidth = "25,25,25,25" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Button ---
					labels en = New, de = Neu, fr = Nouveau
					id = btn_w_e_1
					tid = 195081785009547
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						flow-action = new ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
				--- Button ---
					labels en = Copy, de = Kopieren, fr = Copie
					id = btn_B__zk
					tid = 195081842046684
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = copy ud
						modal = false
						only-changed = false
						prevalidate = false
						Snippet FilterSet
						id = fs_2Bw
						Snippet FilterSet
						id = fs_v50
						Snippet FilterSet
						id = fs_1M4
						Snippet FilterSet
						id = fs_P98
						Snippet FilterSet
						id = fs_PRQ
					}
				}
				--- Button ---
					labels en = "Order List", de = Auftragsliste, fr = "Carnets d\'ordre"
					id = btn_NM8__
					tid = 195081843599116
				{
					Event OnClick (submit)
					{
						method = get
						call-URI = "<pageflow:continuation/>"
						param = "flow-action=orderlist"
						only-changed = false
						portfolioDimensionE = 1 ud
						portfolioDimPortfolio.code = "valueOf(form.portfolio.code)" ud
						modal = false
						prevalidate = false
					}
				}
			}
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
		}
	}
}