# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	containment = container
	domainEntity = "AAADSExtOperation:ExtOperationAll"
	cssClass = nodeco
	bean-define = DSBean.AAADSExtOperation.ExtOperationAll
	bean-name = ExtOperationAll
	id = MMDepositView_g__f3
{
	--- Box ---
		boxType = vertical
	{
		--- TextArea ---
			domainAttribute = summaryC !
			columns = 200
			horizontalAlignment = "${corporatehalign}"
			rows = 1
			type = text
			editable = false
			bean-property = summaryC
			id = summaryC
		--- Box ---
			labels en = Identification, de = Identifikation, fr = Identification
			boxType = vertical
			tid = 5571976721566
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 4
				gridColumnsWidth = "25,25,25,25" !
				gridRowCount = 2
			{
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- LabelDomain ---
						labels en = "Contract Type", de = Vertragsart, fr = "Type de contrat"
						domainAttribute = orderType !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						tid = 1828590104948254
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- Include ---
						domainAssociation = orderType
						includeSrc = "" !
						resource:///default/defaultFragments/TypeIdentifierNameView.fragment
						bean-property-prefix = orderType.
				}
				--- GridCell ---
					gridColumnWidth = 25
				--- GridCell ---
					gridColumnWidth = 25
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- LabelDomain ---
						domainAttribute = portfolio !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- Include ---
						domainAssociation = portfolio
						includeSrc = "" !
						resource:///default/defaultFragments/PortfolioIdentifierView.fragment
						bean-property-prefix = portfolio.
					--- Include ---
						domainAssociation = functionResult
						includeSrc = "" !
						resource:///default/domain/basicelements/DomainId.fragment
						bean-property-prefix = functionResult.
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- LabelDomain ---
						labels en = "Portfolio Name", fr = "Nom du portefeuille"
						domainAttribute = portfolio !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						tid = 1828777600959619
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- Include ---
						domainAssociation = portfolio
						includeSrc = "" !
						resource:///default/defaultFragments/PortfolioIdentifierNameView.fragment
						bean-property-prefix = portfolio.
				}
			}
		}
		--- Conditional ---
			indexOfSelectedChild = 0
		{
			--- ConditionalBody ---
				javaCode = "null != <bean:get-property bean=\"ExtOperationAll\" property=\"orderType\"/> &amp;&amp; \r\n\"PCK_DS_CALL_DEP_NEW\".equals(<bean:get-property bean=\"ExtOperationAll\" property=\"orderType.code\"/>.toString())"
				technicalName = IsFiduCall
				boxType = vertical
				isWidgetSelected = true
			{
				--- Box ---
					labels en = Instruction, de = Instruktion, fr = Instruction
					boxType = vertical
					tid = 5571976786350
				{
					--- Grid ---
						cssClass = blank
						gridColumnCount = 4
						gridColumnsWidth = "25,25,25,25" !
						gridRowCount = 3
					{
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								labels en = Amount, fr = Montant, de = Betrag
								domainAttribute = quantityN !
								for = quantityN
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 5571914823596
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- Box ---
							{
								--- TextField ---
									domainAttribute = quantityN !
									columns = 21
									format = decimal.detailed
									horizontalAlignment = "${corporatehalign}"
									type = decimal
									chars = 23
									editable = false
									bean-property = quantityN
									id = quantityN
								--- Include ---
									domainAssociation = accCurrency
									includeSrc = "" !
									resource:///default/defaultFragments/CurrencyIdentifierView.fragment
									bean-property-prefix = accCurrency.
							}
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								domainAttribute = account !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- Include ---
								domainAssociation = account
								includeSrc = "" !
								resource:///default/defaultFragments/InstrumentIdentifierView.fragment
								bean-property-prefix = account.
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								labels en = "Client Rate"
								domainAttribute = rateP !
								for = rateP
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 175248241693567
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- TextField ---
								domainAttribute = rateP !
								columns = 11
								format = percentTA
								horizontalAlignment = "${corporatehalign}"
								type = percent
								chars = 11
								editable = false
								bean-property = rateP
								id = rateP
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								labels en = "Market Rate"
								domainAttribute = interestMarketRateN !
								for = interestMarketRateN
								horizontalAlignment = "${corporatehalign}"
								tid = 175529404155835
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- TextField ---
								domainAttribute = interestMarketRateN !
								columns = 11
								format = percentTA
								horizontalAlignment = "${corporatehalign}"
								type = percent
								chars = 11
								editable = false
								bean-property = interestMarketRateN
								id = interestMarketRateN
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								domainAttribute = counterpartyThird !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- Include ---
								domainAssociation = counterpartyThird
								includeSrc = "" !
								resource:///default/defaultFragments/ThirdPartyIdentifierView.fragment
								bean-property-prefix = counterpartyThird.
						}
						--- GridCell ---
							gridColumnWidth = 25
						--- GridCell ---
							gridColumnWidth = 25
					}
				}
			}
			--- ConditionalBody ---
				javaCode = "null != <bean:get-property bean=\"ExtOperationAll\" property=\"orderType\"/> &amp;&amp; \r\n\"PCK_DS_TERM_DEP_NEW\".equals(<bean:get-property bean=\"ExtOperationAll\" property=\"orderType.code\"/>.toString())"
				technicalName = IsFiduTerm
				boxType = vertical
				isWidgetVisible = false
			{
				--- Box ---
					labels en = Instruction, de = Instruktion, fr = Instruction
					boxType = vertical
					tid = 40599266178830
				{
					--- Grid ---
						cssClass = blank
						gridColumnCount = 4
						gridColumnsWidth = "25,25,25,25" !
						gridRowCount = 5
					{
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								labels en = Amount, fr = Montant, de = Betrag
								domainAttribute = quantityN !
								for = quantityN
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 177513169426561
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- Box ---
							{
								--- TextField ---
									domainAttribute = quantityN !
									columns = 21
									format = decimal.detailed
									horizontalAlignment = "${corporatehalign}"
									type = decimal
									chars = 23
									editable = false
									bean-property = quantityN
									id = quantityN
								--- Include ---
									domainAssociation = accCurrency
									includeSrc = "" !
									resource:///default/defaultFragments/CurrencyIdentifierView.fragment
									bean-property-prefix = accCurrency.
							}
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								domainAttribute = account !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- Include ---
								domainAssociation = account
								includeSrc = "" !
								resource:///default/defaultFragments/InstrumentIdentifierView.fragment
								bean-property-prefix = account.
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								labels de = Laufzeit, fr = "Durée du contrat"
								domainAttribute = contractLengthN !
								for = contractLengthN
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 14342736569871
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- Box ---
							{
								--- TextField ---
									domainAttribute = contractLengthN !
									columns = 11
									format = integer
									horizontalAlignment = "${corporatehalign}"
									type = integer
									chars = 9
									editable = false
									bean-property = contractLengthN
									id = contractLengthN
								--- ComboBox ---
									domainAttribute = contractLengthUnitE !
									horizontalAlignment = "${corporatehalign}"
									editable = false
									required = true
									bean-property = contractLengthUnitE
									id = contractLengthUnitE
							}
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								labels en = "Maturity Date", fr = "Date d\'échéance"
								domainAttribute = expirationD !
								for = expirationD
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 1829225985134423
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- CaldateField ---
								domainAttribute = expirationD !
								format = datetime.date-only
								horizontalAlignment = "${corporatehalign}"
								type = datetime
								editable = false
								bean-property = expirationD
								id = expirationD
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								labels en = "Client Rate"
								domainAttribute = rateP !
								for = rateP
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 174428929848346
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- TextField ---
								domainAttribute = rateP !
								columns = 11
								format = percentTA
								horizontalAlignment = "${corporatehalign}"
								type = percent
								chars = 11
								editable = false
								bean-property = rateP
								id = rateP
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								labels en = "Market Rate"
								domainAttribute = interestMarketRateN !
								for = interestMarketRateN
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 174491312144141
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- TextField ---
								domainAttribute = interestMarketRateN !
								columns = 11
								format = percentTA
								horizontalAlignment = "${corporatehalign}"
								type = percent
								chars = 11
								editable = false
								bean-property = interestMarketRateN
								id = interestMarketRateN
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								domainAttribute = counterpartyThird !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- Include ---
								domainAssociation = counterpartyThird
								includeSrc = "" !
								resource:///default/defaultFragments/ThirdPartyIdentifierView.fragment
								bean-property-prefix = counterpartyThird.
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								labels en = "Interest At Maturity"
								domainAttribute = mmInterestAmountM !
								for = mmInterestAmountM
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 174806943301453
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- TextField ---
								domainAttribute = mmInterestAmountM !
								columns = 16
								format = decimal
								horizontalAlignment = "${corporatehalign}"
								type = amount
								chars = 18
								editable = false
								bean-property = mmInterestAmountM
								id = mmInterestAmountM
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								labels en = Renewal, de = Erneuerung
								domainAttribute = autoRenewalE !
								for = autoRenewalE
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
								tid = 20548114556608
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- ComboBox ---
								domainAttribute = autoRenewalE !
								horizontalAlignment = "${corporatehalign}"
								editable = false
								required = true
								bean-property = autoRenewalE
								id = autoRenewalE
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								labels en = "Margin Amount"
								domainAttribute = fxMarginM !
								for = fxMarginM
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 174902657552845
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- TextField ---
								domainAttribute = fxMarginM !
								columns = 16
								format = decimal
								horizontalAlignment = "${corporatehalign}"
								type = amount
								chars = 18
								editable = false
								bean-property = fxMarginM
								id = fxMarginM
						}
					}
				}
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "null != <bean:get-property bean=\"ExtOperationAll\" property=\"autoRenewalE\"/> &amp;&amp; Integer.toString(com.odcgroup.aaa.OperationAutoRenewalE.Automatic).equals(<bean:get-property bean=\"ExtOperationAll\" property=\"autoRenewalE\"/>.toString())"
						technicalName = IsRenewable
						boxType = vertical
						isWidgetSelected = true
					{
						--- Box ---
							labels en = "Automatic Renewal", de = "Automatische Verlängerung", fr = "Renouvellement automatique"
							boxType = vertical
							tid = 5571976850952
						{
							--- Grid ---
								cssClass = blank
								gridColumnCount = 4
								gridColumnsWidth = "25,25,25,25" !
								gridRowCount = 2
							{
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										labels en = Treatment, de = Behandlung, fr = Traitement
										domainAttribute = renewalTreatmentE !
										for = renewalTreatmentE
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										required = true
										tid = 20548129033335
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- ComboBox ---
										domainAttribute = renewalTreatmentE !
										horizontalAlignment = "${corporatehalign}"
										editable = false
										required = true
										bean-property = renewalTreatmentE
										id = renewalTreatmentE
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										domainAttribute = renewalEndValD !
										for = renewalEndValD
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- CaldateField ---
										domainAttribute = renewalEndValD !
										format = datetime.date-only
										horizontalAlignment = "${corporatehalign}"
										type = datetime
										editable = false
										bean-property = renewalEndValD
										id = renewalEndValD
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- LabelDomain ---
										domainAttribute = renewalLengthN !
										for = renewalLengthN
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
								}
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Box ---
									{
										--- TextField ---
											domainAttribute = renewalLengthN !
											columns = 9
											format = integer
											horizontalAlignment = "${corporatehalign}"
											type = decimal
											chars = 23
											editable = false
											bean-property = renewalLengthN
											id = renewalLengthN
										--- ComboBox ---
											domainAttribute = renewalLengthUnitE !
											horizontalAlignment = "${corporatehalign}"
											editable = false
											required = true
											bean-property = renewalLengthUnitE
											id = renewalLengthUnitE
									}
								}
								--- GridCell ---
									gridColumnWidth = 25
								--- GridCell ---
									gridColumnWidth = 25
							}
						}
					}
				}
			}
		}
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/extoperation/order/view/AdditionalDataOtherView.module
	}
}