# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSExtOperation:ExtOperationAll"
	cssClass = nodeco
	bean-define = DSBean.AAADSExtOperation.ExtOperationAll
	bean-name = ExtOperationAll
	id = FxSpotCommunicationCreate_tJ_c4
{
	--- Box ---
		labels en = Trading, de = Handel, fr = Marché
		boxType = vertical
		tid = 23369698610651
	{
		--- Conditional ---
			indexOfSelectedChild = 0
		{
			--- ConditionalBody ---
				javaCode = "null != <bean:get-property bean=\"ExtOperationAll\" property=\"orderModeType\"/> &amp;&amp; \r\n\"PCK_DS_NORMAL\".equals(<bean:get-property bean=\"ExtOperationAll\" property=\"orderModeType.code\"/>.toString())"
				technicalName = PCK_DS_NORMAL
				boxType = vertical
				isWidgetSelected = true
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 4
					gridColumnsWidth = "25,25,25,25" !
					gridRowCount = 2
				{
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- LabelDomain ---
							labels en = "Order Mode", fr = "Modalité de l\'ordre"
							domainAttribute = orderModeType !
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							tid = 1910148140677097
					}
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- Include ---
							domainAssociation = orderModeType
							includeSrc = "" !
							resource:///default/defaultFragments/TypeIdentifierNameView.fragment
							bean-property-prefix = orderModeType.
					}
					--- GridCell ---
						gridColumnWidth = 25
					--- GridCell ---
						gridColumnWidth = 25
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- LabelDomain ---
							labels en = "Trader Instruction", fr = "Instruction de l\'opérateur boursier", de = Bemerkung
							domainAttribute = remark3C !
							for = remark3C
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							tid = 373783711721741
					}
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- TextArea ---
							domainAttribute = remark3C !
							columns = 30
							horizontalAlignment = "${corporatehalign}"
							rows = 3
							type = text
							editable = false
							bean-property = remark3C
							id = remark3C
					}
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- LabelDomain ---
							labels en = Trader, fr = "Opérateur boursier"
							domainAttribute = traderManager !
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							tid = 1910148143535840
					}
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- Include ---
							domainAssociation = traderManager
							includeSrc = "" !
							resource:///default/defaultFragments/ManagerIdentifierView.fragment
							bean-property-prefix = traderManager.
					}
				}
			}
			--- ConditionalBody ---
				javaCode = true
				technicalName = Default
				boxType = vertical
				isWidgetVisible = false
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 4
					gridColumnsWidth = "25,25,25,25" !
					gridRowCount = 3
				{
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- LabelDomain ---
							labels en = "Order Mode", fr = "Modalité de l\'ordre"
							domainAttribute = orderModeType !
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							tid = 23293662139039
					}
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- Include ---
							domainAssociation = orderModeType
							includeSrc = "" !
							resource:///default/defaultFragments/TypeIdentifierNameView.fragment
							bean-property-prefix = orderModeType.
					}
					--- GridCell ---
						gridColumnWidth = 25
					--- GridCell ---
						gridColumnWidth = 25
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- LabelDomain ---
							labels en = "Trader Instruction", fr = "Instruction de l\'opérateur boursier", de = Bemerkung
							domainAttribute = remark3C !
							for = remark3C
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							tid = 373918290243313
					}
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- TextArea ---
							domainAttribute = remark3C !
							columns = 30
							horizontalAlignment = "${corporatehalign}"
							rows = 3
							type = text
							editable = false
							bean-property = remark3C
							id = remark3C
					}
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- LabelDomain ---
							labels en = Trader, fr = "Opérateur boursier"
							domainAttribute = traderManager !
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							tid = 1835271766963678
					}
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- Include ---
							domainAssociation = traderManager
							includeSrc = "" !
							resource:///default/defaultFragments/ManagerIdentifierView.fragment
							bean-property-prefix = traderManager.
					}
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- LabelDomain ---
							domainAttribute = transmissionType !
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
					}
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- Include ---
							domainAssociation = transmissionType
							includeSrc = "" !
							resource:///default/defaultFragments/TypeIdentifierNameView.fragment
							bean-property-prefix = transmissionType.
					}
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- LabelDomain ---
							domainAttribute = transmissionD !
							for = transmissionD
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
					}
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- CaldateField ---
							domainAttribute = transmissionD !
							format = datetime
							horizontalAlignment = "${corporatehalign}"
							type = datetime
							editable = false
							bean-property = transmissionD
							id = transmissionD
					}
				}
			}
		}
	}
}