# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "View Order Notepad", de = "Auftragsnotizen ansehen", fr = "Voir le bloc-note de l\'ordre"
	containment = container
	cssClass = nodeco
	id = OrderNotepadView_u4T7_
	tid = 44150710253398
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/extoperation/order/view/OrderIdentifierView.module
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/notepad/search/NotepadList.module
	}
}