# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAAIdentifierDatasets:ExtOperationIdentifier"
	cssClass = nodeco
	bean-define = DSBean.AAAIdentifierDatasets.ExtOperationIdentifier
	bean-name = ExtOperationIdentifier
	id = ExtOperationOrderIdentifierView_w_g__
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///default/extoperation/basicelements/OrderHeadView.fragment
	}
}