# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "View Forex Order", de = "Devisen-auftrag ansehen", fr = "Voir l\'ordre de change"
	containment = container
	domainEntity = "AAADSExtOperation:ExtOperationAll"
	bean-define = DSBean.AAADSExtOperation.ExtOperationAll
	bean-name = ExtOperationAll
	id = QuickOrderForexView_l12__
	tid = 755039476650803
{
	--- Box ---
		boxType = vertical
	{
		--- Box ---
			labels en = "Quick / Detailed"
			boxType = vertical
			widgetBorder = box
			tid = 755039477550638
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 4
				gridColumnsWidth = "25,25,25,25" !
				gridRowCount = 1
			{
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- RadioButton ---
						labels en = Quick
						selected = true
						group = detailedView
						id = Short
						tid = 755039479466803
					--- RadioButton ---
						labels en = Detailed
						group = detailedView
						id = Full
						tid = 755039481421800
				}
				--- GridCell ---
					gridColumnWidth = 25
				--- GridCell ---
					gridColumnWidth = 25
				--- GridCell ---
					gridColumnWidth = 25
			}
		}
		--- Conditional ---
			indexOfSelectedChild = 0
		{
			--- ConditionalBody ---
				javaCode = "<nav:is-selected  group-id=\"detailedView\" element-id=\"Short\" default-selected=\"true\"/>"
				technicalName = Quick
				boxType = vertical
				isWidgetSelected = true
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/extoperation/order/view/QuickForexView.module
			}
			--- ConditionalBody ---
				javaCode = true
				technicalName = Default
				boxType = vertical
				isWidgetVisible = false
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/extoperation/order/view/ForexNoButtonView.module
			}
		}
		--- Grid ---
			cssClass = blank
			gridColumnCount = 4
			gridColumnsWidth = "25,25,25,25" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Button ---
					labels en = New, de = Neu, fr = Nouveau
					id = btn_w__m_
					tid = 755039483373724
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = new ud
						functionResult.id = "valueOf(form.functionResult.id)" ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
				--- Button ---
					labels en = "Back to Session", de = "Zurück zur Sitzung", fr = "Retour à la session"
					id = btn_r6_c_
					tid = 755039485327883
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = WUI_main
						flow-action = back ud
						only-changed = false
						prevalidate = false
						modal = false
					}
					Event OnClick (closeLayer)
				}
			}
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
		}
	}
}