# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Order Details", de = Auftragdetails, fr = "Détails de l\'ordre"
	domainEntity = "AAADSExtOperation:ExtOperationAll"
	collapsible = true
	bean-define = DSBean.AAADSExtOperation.ExtOperationAll
	bean-name = ExtOperationAll
	id = QuickOrderPGView_u5__p
	tid = 198030681389933
{
	--- Box ---
		boxType = vertical
		widgetBorder = horizontal
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 4
			gridColumnsWidth = "25,25,25,5" !
			gridRowCount = 3
		{
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- ComboBox ---
					domainAttribute = natureE !
					horizontalAlignment = "${corporatehalign}"
					editable = false
					required = true
					bean-property = natureE
					id = natureE
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- LabelDomain ---
					domainAttribute = instr !
					horizontalAlignment = "${corporatehalign}"
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Include ---
					domainAssociation = instr
					includeSrc = "" !
					resource:///default/defaultFragments/InstrumentIdentifierView.fragment
					bean-property-prefix = instr.
			}
			--- GridCell ---
				gridColumnWidth = 5
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- LabelDomain ---
					domainAttribute = quantityN !
					for = quantityN
					horizontalAlignment = "${corporatehalign}"
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- TextField ---
					domainAttribute = quantityN !
					columns = 21
					format = decimal.detailed
					horizontalAlignment = "${corporatehalign}"
					type = decimal
					chars = 23
					editable = false
					bean-property = quantityN
					id = quantityN
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- LabelDomain ---
					domainAttribute = opNetAmountM !
					for = opNetAmountM
					horizontalAlignment = "${corporatehalign}"
			}
			--- GridCell ---
				gridColumnWidth = 5
			{
				--- TextField ---
					domainAttribute = opNetAmountM !
					columns = 16
					format = decimal
					horizontalAlignment = "${corporatehalign}"
					type = amount
					chars = 18
					editable = false
					bean-property = opNetAmountM
					id = opNetAmountM
			}
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 5
		}
	}
}