# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	containment = container
	domainEntity = "AAADSExtOperation:ExtOperationAll"
	cssClass = nodeco
	bean-define = DSBean.AAADSExtOperation.ExtOperationAll
	bean-name = ExtOperationAll
	id = QuickMMLoanView_I4__9
{
	--- Box ---
		boxType = vertical
	{
		--- TextArea ---
			domainAttribute = summaryC !
			columns = 200
			horizontalAlignment = "${corporatehalign}"
			rows = 1
			type = text
			editable = false
			bean-property = summaryC
			id = summaryC
		--- Box ---
			labels en = Identification, de = Identifikation, fr = Identification
			boxType = vertical
			tid = 769674624559266
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 4
				gridColumnsWidth = "25,25,25,25" !
				gridRowCount = 2
			{
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- LabelDomain ---
						labels en = "Contract Type", de = Vertragsart, fr = "Type de contrat"
						domainAttribute = orderType !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						tid = 769674625576435
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- Include ---
						domainAssociation = orderType
						includeSrc = "" !
						resource:///default/defaultFragments/TypeIdentifierNameView.fragment
						bean-property-prefix = orderType.
				}
				--- GridCell ---
					gridColumnWidth = 25
				--- GridCell ---
					gridColumnWidth = 25
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- LabelDomain ---
						domainAttribute = portfolio !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- Include ---
						domainAssociation = portfolio
						includeSrc = "" !
						resource:///default/defaultFragments/PortfolioIdentifierView.fragment
						bean-property-prefix = portfolio.
					--- Include ---
						domainAssociation = functionResult
						includeSrc = "" !
						resource:///default/domain/basicelements/DomainId.fragment
						bean-property-prefix = functionResult.
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- LabelDomain ---
						labels fr = "Nom du portefeuille", en = "Portfolio Name", de = "Portfolio Name"
						domainAttribute = portfolio !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						tid = 769674627472765
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- Include ---
						domainAssociation = portfolio
						includeSrc = "" !
						resource:///default/extoperation/basicelements/PortfolioNameIdentifier.fragment
						bean-property-prefix = portfolio.
				}
			}
		}
		--- Box ---
			labels en = Instruction, de = Instruktion, fr = Instruction
			boxType = vertical
			tid = 769674683422055
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 4
				gridColumnsWidth = "25,25,25,25" !
				gridRowCount = 3
			{
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- LabelDomain ---
						labels en = Amount, fr = Montant, de = Betrag
						domainAttribute = quantityN !
						for = quantityN
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						tid = 769674685091820
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- Box ---
					{
						--- TextField ---
							domainAttribute = quantityN !
							columns = 21
							format = decimal.detailed
							horizontalAlignment = "${corporatehalign}"
							type = decimal
							chars = 23
							editable = false
							bean-property = quantityN
							id = quantityN
						--- Include ---
							domainAssociation = account
							includeSrc = "" !
							resource:///default/defaultFragments/InstrumentIdentifierView.fragment
							bean-property-prefix = account.
						--- Include ---
							domainAssociation = accCurrency
							includeSrc = "" !
							resource:///default/defaultFragments/CurrencyIdentifierView.fragment
							bean-property-prefix = accCurrency.
					}
				}
				--- GridCell ---
					gridColumnWidth = 25
				--- GridCell ---
					gridColumnWidth = 25
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- LabelDomain ---
						labels de = Laufzeit, fr = Durée, en = Length
						domainAttribute = contractLengthN !
						for = contractLengthN
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						tid = 769674687076430
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- Box ---
					{
						--- TextField ---
							domainAttribute = contractLengthN !
							columns = 9
							format = integer
							horizontalAlignment = "${corporatehalign}"
							type = integer
							chars = 9
							editable = false
							bean-property = contractLengthN
							id = contractLengthN
						--- ComboBox ---
							domainAttribute = contractLengthUnitE !
							horizontalAlignment = "${corporatehalign}"
							editable = false
							required = true
							bean-property = contractLengthUnitE
							id = contractLengthUnitE
					}
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- LabelDomain ---
						labels en = "Maturity Date", fr = "Date d\'échéance"
						domainAttribute = expirationD !
						for = expirationD
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						tid = 769674688997065
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- CaldateField ---
						domainAttribute = expirationD !
						format = datetime.date-only
						horizontalAlignment = "${corporatehalign}"
						type = datetime
						editable = false
						bean-property = expirationD
						id = expirationD
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- LabelDomain ---
						labels en = "Client Rate", fr = "Taux Client", de = Kunden-Zinssatz
						domainAttribute = rateP !
						for = rateP
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						tid = 769674690950665
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- TextField ---
						domainAttribute = rateP !
						columns = 11
						format = decimal.5-digits
						horizontalAlignment = "${corporatehalign}"
						precision = "21 (BT)"
						scale = "9 (BT)"
						type = percent
						chars = 11
						editable = false
						bean-property = rateP
						id = rateP
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- LabelDomain ---
						labels en = "Market Rate", de = Marktzins, fr = "Taux du marché"
						domainAttribute = interestMarketRateN !
						for = interestMarketRateN
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						tid = 769674692934996
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- TextField ---
						domainAttribute = interestMarketRateN !
						columns = 11
						format = percentTA
						horizontalAlignment = "${corporatehalign}"
						precision = "21 (BT)"
						scale = "9 (BT)"
						type = percent
						chars = 11
						editable = false
						bean-property = interestMarketRateN
						id = interestMarketRateN
				}
			}
		}
	}
}