# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = Buy, de = "Devisenkassa-Auftrag ansehen"
	containment = container
	domainEntity = "AAADSExtOperation:ExtOperationAll"
	cssClass = nodeco
	bean-define = DSBean.AAADSExtOperation.ExtOperationAll
	bean-name = ExtOperationAll
	id = QuickForexView_pe19_
	tid = 755252892666805
{
	--- Box ---
		boxType = vertical
	{
		--- TextArea ---
			domainAttribute = summaryC !
			columns = 200
			horizontalAlignment = "${corporatehalign}"
			rows = 1
			type = text
			editable = false
			bean-property = summaryC
			id = summaryC
		--- Box ---
			labels en = Identification, de = Identifikation, fr = Identification
			boxType = vertical
			tid = 755252896288494
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 4
				gridColumnsWidth = "25,25,25,25" !
				gridRowCount = 2
			{
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- LabelDomain ---
						domainAttribute = natureE !
						for = natureE
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- Conditional ---
						indexOfSelectedChild = 0
					{
						--- ConditionalBody ---
							javaCode = "null != <bean:get-property bean=\"ExtOperationAll\" property=\"orderType\"/> &amp;&amp; \r\n(\"PCK_DS_ACCT_SAME_CCY\".equals(<bean:get-property bean=\"ExtOperationAll\" property=\"orderType.code\"/>.toString()))"
							technicalName = Condition
							boxType = vertical
							isWidgetSelected = true
						{
							--- Code ---
								code = "<xgui:combobox editable=\"false\" id=\"natureE\" required=\"true\" widget-group=\"form\">\r\n  <xgui:selected-value>\r\n\t<bean:get-property bean=\"ExtOperationAll\" property=\"natureE\"/>\r\n  </xgui:selected-value>\r\n  <xgui:item>\r\n\t<xgui:value>1</xgui:value>\r\n\t<xgui:text>\r\n\t  <i18n:text>forex.ACCT_SAME_CCY.buy.text</i18n:text>\r\n\t</xgui:text>\r\n  </xgui:item>\r\n  <xgui:item>\r\n\t<xgui:value>2</xgui:value>\r\n\t<xgui:text>\r\n\t  <i18n:text>forex.ACCT_SAME_CCY.sell.text</i18n:text>\r\n\t</xgui:text>\r\n  </xgui:item>\r\n</xgui:combobox>"
						}
						--- ConditionalBody ---
							javaCode = true
							technicalName = Default
							boxType = vertical
							isWidgetVisible = false
						{
							--- ComboBox ---
								domainAttribute = natureE !
								horizontalAlignment = "${corporatehalign}"
								editable = false
								required = true
								bean-property = natureE
								id = natureE
						}
					}
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- LabelDomain ---
						labels en = Type
						domainAttribute = orderType !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						tid = 755252897428583
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- Include ---
						domainAssociation = orderType
						includeSrc = "" !
						resource:///default/defaultFragments/TypeIdentifierDenomView.fragment
						bean-property-prefix = orderType.
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- LabelDomain ---
						domainAttribute = portfolio !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- Include ---
						domainAssociation = portfolio
						includeSrc = "" !
						resource:///default/defaultFragments/PortfolioIdentifierView.fragment
						bean-property-prefix = portfolio.
					--- Include ---
						domainAssociation = functionResult
						includeSrc = "" !
						resource:///default/domain/basicelements/DomainId.fragment
						bean-property-prefix = functionResult.
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- LabelDomain ---
						labels en = "Portfolio Name", de = "Portfolio Name", fr = "Nom du portefeuille"
						domainAttribute = portfolio !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						tid = 755252899456774
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- Include ---
						domainAssociation = portfolio
						includeSrc = "" !
						resource:///default/extoperation/basicelements/PortfolioNameIdentifier.fragment
						bean-property-prefix = portfolio.
				}
			}
		}
		--- Conditional ---
			technicalName = "Transfer From"
			indexOfSelectedChild = 1
		{
			--- ConditionalBody ---
				javaCode = "Integer.toString(com.odcgroup.aaa.OperationNatureE.Sell).equals(<bean:get-property bean=\"ExtOperationAll\" property=\"natureE\"/>.toString()) &amp;&amp; \r\nnull != <bean:get-property bean=\"ExtOperationAll\" property=\"orderType\"/> &amp;&amp; \r\n(\"PCK_DS_FXSPOT_NEGO\".equals(<bean:get-property bean=\"ExtOperationAll\" property=\"orderType.code\"/>.toString()) ||\r\n\"PCK_DS_FXSPOT_CONV\".equals(<bean:get-property bean=\"ExtOperationAll\" property=\"orderType.code\"/>.toString()))"
				technicalName = IsSellFxSpot
				boxType = vertical
				isWidgetVisible = false
			{
				--- Box ---
					labels en = Instruction, de = Instruktion, fr = Instruction
					boxType = vertical
					tid = 755252901647555
				{
					--- Grid ---
						cssClass = blank
						gridColumnCount = 4
						gridColumnsWidth = "25,25,25,25" !
						gridRowCount = 3
					{
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								labels en = Sell
								domainAttribute = opCurrency !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 755252903623225
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- Box ---
							{
								--- Include ---
									domainAssociation = opCurrency
									includeSrc = "" !
									resource:///default/defaultFragments/CurrencyIdentifierView.fragment
									bean-property-prefix = opCurrency.
								--- TextField ---
									domainAttribute = quantityN !
									columns = 21
									format = decimal
									horizontalAlignment = "${corporatehalign}"
									type = decimal
									allow = "\'0123456789.,\'"
									chars = 23
									editable = false
									required = true
									bean-property = quantityN
									id = quantityN
								{
									Event OnChange (submit)
									{
										method = post
										call-URI = "<pageflow:continuation/>"
										widget-group-ref = form
										param = "flow-action=reload"
										only-changed = true
										modal = false
										prevalidate = false
									}
								}
							}
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								labels en = Buy
								domainAttribute = accCurrency !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 755252905528775
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- Box ---
							{
								--- Include ---
									domainAssociation = accCurrency
									includeSrc = "" !
									resource:///default/defaultFragments/CurrencyIdentifierView.fragment
									bean-property-prefix = accCurrency.
								--- TextField ---
									domainAttribute = accNetAmountM !
									columns = 21
									format = decimal
									horizontalAlignment = "${corporatehalign}"
									type = amount
									chars = 18
									editable = false
									bean-property = accNetAmountM
									id = accNetAmountM
							}
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								labels en = "Debited Account", de = "Belastetes Konto", fr = "Compte débité"
								domainAttribute = instr !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
								tid = 755252907182616
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- Box ---
							{
								--- Include ---
									domainAssociation = instr
									includeSrc = "" !
									resource:///default/defaultFragments/InstrumentIdentifierView.fragment
									bean-property-prefix = instr.
								--- Include ---
									domainAssociation = opCurrency
									includeSrc = "" !
									resource:///default/defaultFragments/CurrencyIdentifierView.fragment
									bean-property-prefix = opCurrency.
							}
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								labels en = "Credited Account"
								domainAttribute = account !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 755252909154096
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- Box ---
							{
								--- Include ---
									domainAssociation = account
									includeSrc = "" !
									resource:///default/defaultFragments/InstrumentIdentifierView.fragment
									bean-property-prefix = account.
								--- Include ---
									domainAssociation = accCurrency
									includeSrc = "" !
									resource:///default/defaultFragments/CurrencyIdentifierView.fragment
									bean-property-prefix = accCurrency.
							}
						}
						--- GridCell ---
							gridColumnWidth = 25
						--- GridCell ---
							gridColumnWidth = 25
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								domainAttribute = valueD !
								for = valueD
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- CaldateField ---
								domainAttribute = valueD !
								format = datetime.date-only
								horizontalAlignment = "${corporatehalign}"
								type = datetime
								editable = false
								bean-property = valueD
								id = valueD
						}
					}
				}
			}
			--- ConditionalBody ---
				javaCode = "Integer.toString(com.odcgroup.aaa.OperationNatureE.Buy).equals(<bean:get-property bean=\"ExtOperationAll\" property=\"natureE\"/>.toString()) &amp;&amp; \r\nnull != <bean:get-property bean=\"ExtOperationAll\" property=\"orderType\"/> &amp;&amp; \r\n(\"PCK_DS_FXSPOT_NEGO\".equals(<bean:get-property bean=\"ExtOperationAll\" property=\"orderType.code\"/>.toString()) ||\r\n\"PCK_DS_FXSPOT_CONV\".equals(<bean:get-property bean=\"ExtOperationAll\" property=\"orderType.code\"/>.toString()))"
				technicalName = IsBuyFxSpot
				boxType = vertical
				isWidgetSelected = true
			{
				--- Box ---
					labels en = Instruction, de = Instruktion, fr = Instruction
					boxType = vertical
					tid = 755252911089258
				{
					--- Grid ---
						cssClass = blank
						gridColumnCount = 4
						gridColumnsWidth = "25,25,25,25" !
						gridRowCount = 3
					{
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								labels en = Buy
								domainAttribute = opCurrency !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 755252913046769
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- Box ---
							{
								--- Include ---
									domainAssociation = opCurrency
									includeSrc = "" !
									resource:///default/defaultFragments/CurrencyIdentifierView.fragment
									bean-property-prefix = opCurrency.
								--- TextField ---
									domainAttribute = quantityN !
									columns = 21
									format = decimal
									horizontalAlignment = "${corporatehalign}"
									type = decimal
									allow = "\'0123456789.,\'"
									chars = 23
									editable = false
									required = true
									bean-property = quantityN
									id = quantityN
								{
									Event OnChange (submit)
									{
										method = post
										call-URI = "<pageflow:continuation/>"
										widget-group-ref = form
										param = "flow-action=reload"
										only-changed = true
										modal = false
										prevalidate = false
									}
								}
							}
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								labels en = Sell
								domainAttribute = accCurrency !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 755252915067138
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- Box ---
							{
								--- Include ---
									domainAssociation = accCurrency
									includeSrc = "" !
									resource:///default/defaultFragments/CurrencyIdentifierView.fragment
									bean-property-prefix = accCurrency.
								--- TextField ---
									domainAttribute = accNetAmountM !
									columns = 21
									format = decimal
									horizontalAlignment = "${corporatehalign}"
									type = amount
									chars = 23
									editable = false
									required = true
									bean-property = accNetAmountM
									id = accNetAmountM
								{
									Event OnChange (submit)
									{
										method = post
										call-URI = "<pageflow:continuation/>"
										widget-group-ref = form
										param = "flow-action=reload"
										only-changed = true
										modal = false
										prevalidate = false
									}
								}
							}
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								labels en = "Credited Account", de = "Erkanntes Konto", fr = "Compte crédité"
								domainAttribute = instr !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
								tid = 755252916949221
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- Box ---
							{
								--- Include ---
									domainAssociation = instr
									includeSrc = "" !
									resource:///default/defaultFragments/InstrumentIdentifierView.fragment
									bean-property-prefix = instr.
								--- Include ---
									domainAssociation = opCurrency
									includeSrc = "" !
									resource:///default/defaultFragments/CurrencyIdentifierView.fragment
									bean-property-prefix = opCurrency.
							}
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								labels en = "Debited Account", de = "Belastetes Konto", fr = "Compte débité"
								domainAttribute = account !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
								tid = 755252918900586
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- Box ---
							{
								--- Include ---
									domainAssociation = account
									includeSrc = "" !
									resource:///default/defaultFragments/InstrumentIdentifierView.fragment
									bean-property-prefix = account.
								--- Include ---
									domainAssociation = accCurrency
									includeSrc = "" !
									resource:///default/defaultFragments/CurrencyIdentifierView.fragment
									bean-property-prefix = accCurrency.
							}
						}
						--- GridCell ---
							gridColumnWidth = 25
						--- GridCell ---
							gridColumnWidth = 25
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								domainAttribute = valueD !
								for = valueD
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- CaldateField ---
								domainAttribute = valueD !
								format = datetime.date-only
								horizontalAlignment = "${corporatehalign}"
								type = datetime
								editable = false
								bean-property = valueD
								id = valueD
						}
					}
				}
			}
			--- ConditionalBody ---
				javaCode = "Integer.toString(com.odcgroup.aaa.OperationNatureE.Buy).equals(<bean:get-property bean=\"ExtOperationAll\" property=\"natureE\"/>.toString()) &amp;&amp; \r\nnull != <bean:get-property bean=\"ExtOperationAll\" property=\"orderType\"/> &amp;&amp; \r\n(\"PCK_DS_FXFWD_NEGO\".equals(<bean:get-property bean=\"ExtOperationAll\" property=\"orderType.code\"/>.toString()) ||\r\n\"PCK_DS_FXFWD_CONV\".equals(<bean:get-property bean=\"ExtOperationAll\" property=\"orderType.code\"/>.toString()))"
				technicalName = IsBuyFxForward
				boxType = vertical
				isWidgetVisible = false
			{
				--- Box ---
					labels en = Instruction, fr = Instruction, de = Instruktion
					boxType = vertical
					tid = 755252920853907
				{
					--- Grid ---
						cssClass = blank
						gridColumnCount = 4
						gridColumnsWidth = "25,25,25,25" !
						gridRowCount = 3
					{
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								labels en = Buy
								domainAttribute = acc2Currency !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 755252922804155
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- Box ---
							{
								--- Include ---
									domainAssociation = acc2Currency
									includeSrc = "" !
									resource:///default/defaultFragments/CurrencyIdentifierView.fragment
									bean-property-prefix = acc2Currency.
								--- TextField ---
									domainAttribute = quantityN !
									columns = 21
									format = decimal
									horizontalAlignment = "${corporatehalign}"
									type = decimal
									allow = "\'0123456789.,\'"
									chars = 23
									editable = false
									required = true
									bean-property = quantityN
									id = quantityN
							}
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								labels en = Sell
								domainAttribute = opCurrency !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 755252924758034
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- Box ---
							{
								--- Include ---
									domainAssociation = opCurrency
									includeSrc = "" !
									resource:///default/defaultFragments/CurrencyIdentifierView.fragment
									bean-property-prefix = opCurrency.
								--- TextField ---
									domainAttribute = accNetAmountM !
									columns = 16
									format = decimal
									horizontalAlignment = "${corporatehalign}"
									type = amount
									chars = 18
									editable = false
									bean-property = accNetAmountM
									id = accNetAmountM
							}
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								labels en = "Credited Account"
								domainAttribute = account2 !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 755252926713870
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- Box ---
							{
								--- Include ---
									domainAssociation = account2
									includeSrc = "" !
									resource:///default/defaultFragments/InstrumentIdentifierView.fragment
									bean-property-prefix = account2.
								--- Include ---
									domainAssociation = acc2Currency
									includeSrc = "" !
									resource:///default/defaultFragments/CurrencyIdentifierView.fragment
									bean-property-prefix = acc2Currency.
							}
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								labels en = "Debited Account", de = "Belastetes Konto", fr = "Compte débité"
								domainAttribute = account !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
								tid = 755252928666632
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- Box ---
							{
								--- Include ---
									domainAssociation = account
									includeSrc = "" !
									resource:///default/defaultFragments/InstrumentIdentifierView.fragment
									bean-property-prefix = account.
								--- Include ---
									domainAssociation = accCurrency
									includeSrc = "" !
									resource:///default/defaultFragments/CurrencyIdentifierView.fragment
									bean-property-prefix = accCurrency.
							}
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								labels en = Length
								domainAttribute = contractLengthN !
								for = contractLengthN
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 755252949114761
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- TextField ---
								domainAttribute = contractLengthN !
								columns = 9
								format = integer
								horizontalAlignment = "${corporatehalign}"
								type = integer
								chars = 9
								editable = false
								bean-property = contractLengthN
								id = contractLengthN
							--- ComboBox ---
								domainAttribute = contractLengthUnitE !
								horizontalAlignment = "${corporatehalign}"
								editable = false
								required = true
								bean-property = contractLengthUnitE
								id = contractLengthUnitE
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								domainAttribute = valueD !
								for = valueD
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- CaldateField ---
								domainAttribute = valueD !
								format = datetime.date-only
								horizontalAlignment = "${corporatehalign}"
								type = datetime
								editable = false
								required = true
								bean-property = valueD
								id = valueD
							{
								Event OnChange (submit)
								{
									method = post
									call-URI = "<pageflow:continuation/>"
									widget-group-ref = form
									param = "flow-action=reload"
									only-changed = true
									modal = false
									prevalidate = false
								}
							}
						}
					}
				}
			}
			--- ConditionalBody ---
				javaCode = "Integer.toString(com.odcgroup.aaa.OperationNatureE.Sell).equals(<bean:get-property bean=\"ExtOperationAll\" property=\"natureE\"/>.toString()) &amp;&amp; \r\nnull != <bean:get-property bean=\"ExtOperationAll\" property=\"orderType\"/> &amp;&amp; \r\n(\"PCK_DS_FXFWD_NEGO\".equals(<bean:get-property bean=\"ExtOperationAll\" property=\"orderType.code\"/>.toString()) ||\r\n\"PCK_DS_FXFWD_CONV\".equals(<bean:get-property bean=\"ExtOperationAll\" property=\"orderType.code\"/>.toString()))"
				technicalName = isSellFxForward
				boxType = vertical
				isWidgetVisible = false
			{
				--- Box ---
					labels en = Instruction, de = Instruktion, fr = Instruction
					boxType = vertical
					tid = 755252966059652
				{
					--- Grid ---
						cssClass = blank
						gridColumnCount = 4
						gridColumnsWidth = "25,25,25,25" !
						gridRowCount = 3
					{
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								labels en = Sell
								domainAttribute = acc2Currency !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 755252967729976
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- Box ---
							{
								--- Include ---
									domainAssociation = acc2Currency
									includeSrc = "" !
									resource:///default/defaultFragments/CurrencyIdentifierView.fragment
									bean-property-prefix = acc2Currency.
								--- TextField ---
									domainAttribute = quantityN !
									columns = 21
									format = decimal
									horizontalAlignment = "${corporatehalign}"
									type = decimal
									allow = "\'0123456789.,\'"
									chars = 23
									editable = false
									required = true
									bean-property = quantityN
									id = quantityN
							}
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								labels en = Buy
								domainAttribute = opCurrency !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 755252969680224
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- Box ---
							{
								--- Include ---
									domainAssociation = opCurrency
									includeSrc = "" !
									resource:///default/defaultFragments/CurrencyIdentifierView.fragment
									bean-property-prefix = opCurrency.
								--- TextField ---
									domainAttribute = accNetAmountM !
									columns = 16
									format = decimal
									horizontalAlignment = "${corporatehalign}"
									type = amount
									chars = 18
									editable = false
									bean-property = accNetAmountM
									id = accNetAmountM
							}
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								labels en = "Debited Account"
								domainAttribute = account2 !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 755252971632986
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- Box ---
							{
								--- Include ---
									domainAssociation = account2
									includeSrc = "" !
									resource:///default/defaultFragments/InstrumentIdentifierView.fragment
									bean-property-prefix = account2.
								--- Include ---
									domainAssociation = acc2Currency
									includeSrc = "" !
									resource:///default/defaultFragments/CurrencyIdentifierView.fragment
									bean-property-prefix = acc2Currency.
							}
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								labels en = "Credited Account", de = "Belastetes Konto", fr = "Compte débité"
								domainAttribute = account !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
								tid = 755252973594688
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- Box ---
							{
								--- Include ---
									domainAssociation = account
									includeSrc = "" !
									resource:///default/defaultFragments/InstrumentIdentifierView.fragment
									bean-property-prefix = account.
								--- Include ---
									domainAssociation = accCurrency
									includeSrc = "" !
									resource:///default/defaultFragments/CurrencyIdentifierView.fragment
									bean-property-prefix = accCurrency.
							}
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								labels en = Length
								domainAttribute = contractLengthN !
								for = contractLengthN
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 755252975543819
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- TextField ---
								domainAttribute = contractLengthN !
								columns = 9
								format = integer
								horizontalAlignment = "${corporatehalign}"
								type = integer
								chars = 9
								editable = false
								bean-property = contractLengthN
								id = contractLengthN
							--- ComboBox ---
								domainAttribute = contractLengthUnitE !
								horizontalAlignment = "${corporatehalign}"
								editable = false
								required = true
								bean-property = contractLengthUnitE
								id = contractLengthUnitE
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								domainAttribute = valueD !
								for = valueD
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- CaldateField ---
								domainAttribute = valueD !
								format = datetime.date-only
								horizontalAlignment = "${corporatehalign}"
								type = datetime
								editable = false
								required = true
								bean-property = valueD
								id = valueD
							{
								Event OnChange (submit)
								{
									method = post
									call-URI = "<pageflow:continuation/>"
									widget-group-ref = form
									param = "flow-action=reload"
									only-changed = true
									modal = false
									prevalidate = false
								}
							}
						}
					}
				}
			}
			--- ConditionalBody ---
				javaCode = "Integer.toString(com.odcgroup.aaa.OperationNatureE.Sell).equals(<bean:get-property bean=\"ExtOperationAll\" property=\"natureE\"/>.toString()) &amp;&amp; \r\nnull != <bean:get-property bean=\"ExtOperationAll\" property=\"orderType\"/> &amp;&amp; \r\n(\"PCK_DS_ACCT_SAME_CCY\".equals(<bean:get-property bean=\"ExtOperationAll\" property=\"orderType.code\"/>.toString()))"
				technicalName = "Transfer From"
				boxType = vertical
				isWidgetVisible = false
			{
				--- Box ---
					labels en = Instruction, de = Instruktion, fr = Instruction
					boxType = vertical
					tid = 755252977494625
				{
					--- Grid ---
						cssClass = blank
						gridColumnCount = 4
						gridColumnsWidth = "25,25,25,25" !
						gridRowCount = 3
					{
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								labels en = "Amount to Debit"
								domainAttribute = opCurrency !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 755252979447108
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- Box ---
							{
								--- Include ---
									domainAssociation = opCurrency
									includeSrc = "" !
									resource:///default/defaultFragments/CurrencyIdentifierView.fragment
									bean-property-prefix = opCurrency.
								--- TextField ---
									domainAttribute = quantityN !
									columns = 21
									format = decimal
									horizontalAlignment = "${corporatehalign}"
									type = decimal
									allow = "\'0123456789.,\'"
									chars = 23
									editable = false
									required = true
									bean-property = quantityN
									id = quantityN
							}
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								labels en = "Received Amount"
								domainAttribute = accCurrency !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 755252981400429
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- Box ---
							{
								--- Include ---
									domainAssociation = accCurrency
									includeSrc = "" !
									resource:///default/defaultFragments/CurrencyIdentifierView.fragment
									bean-property-prefix = accCurrency.
								--- TextField ---
									domainAttribute = accNetAmountM !
									columns = 21
									format = decimal
									type = amount
									chars = 18
									editable = false
									bean-property = accNetAmountM
									id = accNetAmountM
							}
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								labels en = "Debited Account"
								domainAttribute = instr !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 755252983351515
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- Box ---
							{
								--- Include ---
									domainAssociation = instr
									includeSrc = "" !
									resource:///default/defaultFragments/InstrumentIdentifierView.fragment
									bean-property-prefix = instr.
								--- Include ---
									domainAssociation = opCurrency
									includeSrc = "" !
									resource:///default/defaultFragments/CurrencyIdentifierView.fragment
									bean-property-prefix = opCurrency.
							}
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								labels en = "Credited Account"
								domainAttribute = account !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 755252985305674
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- Box ---
							{
								--- Include ---
									domainAssociation = account
									includeSrc = "" !
									resource:///default/defaultFragments/InstrumentIdentifierView.fragment
									bean-property-prefix = account.
								--- Include ---
									domainAssociation = accCurrency
									includeSrc = "" !
									resource:///default/defaultFragments/CurrencyIdentifierView.fragment
									bean-property-prefix = accCurrency.
							}
						}
						--- GridCell ---
							gridColumnWidth = 25
						--- GridCell ---
							gridColumnWidth = 25
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								domainAttribute = valueD !
								for = valueD
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- CaldateField ---
								domainAttribute = valueD !
								format = datetime.date-only
								horizontalAlignment = "${corporatehalign}"
								type = datetime
								editable = false
								bean-property = valueD
								id = valueD
						}
					}
				}
			}
			--- ConditionalBody ---
				javaCode = "Integer.toString(com.odcgroup.aaa.OperationNatureE.Buy).equals(<bean:get-property bean=\"ExtOperationAll\" property=\"natureE\"/>.toString()) &amp;&amp; \r\nnull != <bean:get-property bean=\"ExtOperationAll\" property=\"orderType\"/> &amp;&amp; \r\n(\"PCK_DS_ACCT_SAME_CCY\".equals(<bean:get-property bean=\"ExtOperationAll\" property=\"orderType.code\"/>.toString()))"
				technicalName = "Transfer To"
				boxType = vertical
				isWidgetVisible = false
			{
				--- Box ---
					labels en = Instruction, fr = Instruction, de = Instruktion
					boxType = vertical
					tid = 755252987261509
				{
					--- Grid ---
						cssClass = blank
						gridColumnCount = 4
						gridColumnsWidth = "25,25,25,25" !
						gridRowCount = 3
					{
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								labels en = "Amount to Credit"
								domainAttribute = opCurrency !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 755252989212036
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- Box ---
							{
								--- Include ---
									domainAssociation = opCurrency
									includeSrc = "" !
									resource:///default/defaultFragments/CurrencyIdentifierView.fragment
									bean-property-prefix = opCurrency.
								--- TextField ---
									domainAttribute = quantityN !
									columns = 21
									format = decimal
									horizontalAlignment = "${corporatehalign}"
									type = decimal
									allow = "\'0123456789.,\'"
									chars = 23
									editable = false
									required = true
									bean-property = quantityN
									id = quantityN
							}
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								labels en = "Debited Amount"
								domainAttribute = accCurrency !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 755252991168151
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- Box ---
							{
								--- Include ---
									domainAssociation = accCurrency
									includeSrc = "" !
									resource:///default/defaultFragments/CurrencyIdentifierView.fragment
									bean-property-prefix = accCurrency.
								--- TextField ---
									domainAttribute = accNetAmountM !
									columns = 21
									format = decimal
									type = amount
									chars = 23
									editable = false
									required = true
									bean-property = accNetAmountM
									id = accNetAmountM
								{
									Event OnChange (submit)
									{
										method = post
										call-URI = "<pageflow:continuation/>"
										widget-group-ref = form
										param = "flow-action=reload"
										only-changed = true
										modal = false
										prevalidate = false
									}
								}
							}
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								labels en = "Credited Account"
								domainAttribute = instr !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 755252993117840
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- Box ---
							{
								--- Include ---
									domainAssociation = instr
									includeSrc = "" !
									resource:///default/defaultFragments/InstrumentIdentifierView.fragment
									bean-property-prefix = instr.
								--- Include ---
									domainAssociation = opCurrency
									includeSrc = "" !
									resource:///default/defaultFragments/CurrencyIdentifierView.fragment
									bean-property-prefix = opCurrency.
							}
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								labels en = "Debited Account", de = "Belastetes Konto", fr = "Compte débité"
								domainAttribute = account !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
								tid = 755252995071161
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- Box ---
							{
								--- Include ---
									domainAssociation = account
									includeSrc = "" !
									resource:///default/defaultFragments/InstrumentIdentifierView.fragment
									bean-property-prefix = account.
								--- Include ---
									domainAssociation = accCurrency
									includeSrc = "" !
									resource:///default/defaultFragments/CurrencyIdentifierView.fragment
									bean-property-prefix = accCurrency.
							}
						}
						--- GridCell ---
							gridColumnWidth = 25
						--- GridCell ---
							gridColumnWidth = 25
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								domainAttribute = valueD !
								for = valueD
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- CaldateField ---
								domainAttribute = valueD !
								format = datetime.date-only
								horizontalAlignment = "${corporatehalign}"
								type = datetime
								editable = false
								bean-property = valueD
								id = valueD
						}
					}
				}
			}
		}
		--- Conditional ---
			indexOfSelectedChild = 0
		{
			--- ConditionalBody ---
				javaCode = "null != <bean:get-property bean=\"ExtOperationAll\" property=\"orderType\"/> &amp;&amp; \r\n(\"PCK_DS_FXSPOT_NEGO\".equals(<bean:get-property bean=\"ExtOperationAll\" property=\"orderType.code\"/>.toString()) || \r\n\"PCK_DS_FXFWD_NEGO\".equals(<bean:get-property bean=\"ExtOperationAll\" property=\"orderType.code\"/>.toString()))"
				technicalName = IsFxNego
				boxType = vertical
				documentation = "It defines the fx rate conditions for Fx Spot order.\r\nIt requires having to buy or sell an amount into a currency against another currency."
				isWidgetSelected = true
			{
				--- Box ---
					labels en = Rate, fr = Taux
					boxType = vertical
					widgetBorder = box
					tid = 611379914529081
				{
					--- Grid ---
						cssClass = blank
						gridColumnCount = 4
						gridColumnsWidth = "25,25,25,25" !
						gridRowCount = 3
					{
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								labels en = "Client Rate", de = Kunden-Kurs, fr = "Taux client"
								domainAttribute = fxClientRateN !
								for = fxClientRateN
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 611379915482554
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- Box ---
							{
								--- TextField ---
									domainAttribute = fxClientRateN !
									columns = 21
									format = decimal.detailed
									type = decimal
									allow = "\'0123456789.,\'"
									chars = 23
									editable = false
									bean-property = fxClientRateN
									id = fxClientRateN
								{
									Event OnChange (submit)
									{
										method = post
										call-URI = "<pageflow:continuation/>"
										widget-group-ref = form
										param = "flow-action=reload"
										only-changed = true
										stabs = "<xsp-request:get-parameter name=\"stabs\"/>" ud
										modal = false
										prevalidate = false
									}
								}
								--- ComboBox ---
									domainAttribute = fxRateDirectionF !
									horizontalAlignment = "${corporatehalign}"
									editable = false
									required = true
									bean-property = fxRateDirectionF
									id = fxRateDirectionF
								{
									Event OnChange (submit)
									{
										method = post
										call-URI = "<pageflow:continuation/>"
										widget-group-ref = form
										param = "flow-action=reload"
										only-changed = true
										stabs = "<xsp-request:get-parameter name=\"stabs\"/>" ud
										modal = false
										prevalidate = false
									}
								}
							}
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								labels en = "Margin %"
								domainAttribute = fxMarginP !
								for = fxMarginP
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 611379917194503
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- Box ---
							{
								--- TextField ---
									domainAttribute = fxMarginP !
									columns = 11
									format = percentTA
									horizontalAlignment = "${corporatehalign}"
									type = percent
									chars = 11
									editable = false
									bean-property = fxMarginP
									id = fxMarginP
							}
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								labels en = "Margin pips"
								domainAttribute = fxMarginN !
								for = fxMarginN
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 611379919126034
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- TextField ---
								domainAttribute = fxMarginN !
								columns = 21
								format = decimal.detailed
								horizontalAlignment = "${corporatehalign}"
								type = decimal
								chars = 23
								editable = false
								bean-property = fxMarginN
								id = fxMarginN
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								labels en = "Margin Amount"
								domainAttribute = fxMarginM !
								for = fxMarginM
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 611379921079355
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- Box ---
							{
								--- TextField ---
									domainAttribute = fxMarginM !
									columns = 21
									format = decimal
									horizontalAlignment = trail
									type = amount
									chars = 18
									editable = false
									bean-property = fxMarginM
									id = fxMarginM
								--- Include ---
									domainAssociation = opCurrency
									includeSrc = "" !
									resource:///default/defaultFragments/CurrencyIdentifierView.fragment
									bean-property-prefix = opCurrency.
							}
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								labels en = "Market Rate", de = Basis-Kurs, fr = "Taux de base"
								domainAttribute = fxMarketRateN !
								for = fxMarketRateN
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 611379923033514
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- TextField ---
								domainAttribute = fxMarketRateN !
								columns = 21
								format = decimal.detailed
								horizontalAlignment = "${corporatehalign}"
								type = decimal
								chars = 23
								editable = false
								required = true
								bean-property = fxMarketRateN
								id = fxMarketRateN
							{
								Event OnChange (submit)
								{
									method = post
									call-URI = "<pageflow:continuation/>"
									widget-group-ref = form
									param = "flow-action=reload"
									only-changed = true
									stabs = "<xsp-request:get-parameter name=\"stabs\"/>" ud
									modal = false
									prevalidate = false
								}
							}
						}
						--- GridCell ---
							gridColumnWidth = 25
						--- GridCell ---
							gridColumnWidth = 25
					}
				}
			}
			--- ConditionalBody ---
				javaCode = "null != <bean:get-property bean=\"ExtOperationAll\" property=\"orderType\"/> &amp;&amp; \r\n(\"PCK_DS_FXSPOT_CONV\".equals(<bean:get-property bean=\"ExtOperationAll\" property=\"orderType.code\"/>.toString()) || \r\n\"PCK_DS_FXFWD_CONV\".equals(<bean:get-property bean=\"ExtOperationAll\" property=\"orderType.code\"/>.toString()))"
				technicalName = IsFxConv
				boxType = vertical
				isWidgetVisible = false
			{
				--- Box ---
					labels en = Rate, fr = Taux
					boxType = vertical
					widgetBorder = box
					tid = 611379925008904
				{
					--- Grid ---
						cssClass = blank
						gridColumnCount = 4
						gridColumnsWidth = "25,25,25,25" !
						gridRowCount = 3
					{
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								labels en = "Client Rate"
								domainAttribute = fxClientRateN !
								for = fxClientRateN
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 611379926965019
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- Box ---
							{
								--- TextField ---
									domainAttribute = fxClientRateN !
									columns = 21
									format = decimal.detailed
									horizontalAlignment = "${corporatehalign}"
									type = decimal
									chars = 23
									editable = false
									bean-property = fxClientRateN
									id = fxClientRateN
								--- ComboBox ---
									domainAttribute = fxRateDirectionF !
									horizontalAlignment = "${corporatehalign}"
									editable = false
									required = true
									bean-property = fxRateDirectionF
									id = fxRateDirectionF
								{
									Event OnChange (submit)
									{
										method = post
										call-URI = "<pageflow:continuation/>"
										widget-group-ref = form
										param = "flow-action=reload"
										only-changed = true
										stabs = "<xsp-request:get-parameter name=\"stabs\"/>" ud
										modal = false
										prevalidate = false
									}
								}
							}
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								labels en = "Margin %"
								domainAttribute = fxMarginP !
								for = fxMarginP
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 611379928909400
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- Box ---
							{
								--- TextField ---
									domainAttribute = fxMarginP !
									columns = 11
									format = percentTA
									horizontalAlignment = "${corporatehalign}"
									type = percent
									chars = 11
									editable = false
									bean-property = fxMarginP
									id = fxMarginP
							}
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								labels en = "Margin pips", fr = Marge, de = Marge
								domainAttribute = fxMarginN !
								for = fxMarginN
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 611379930869705
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- TextField ---
								domainAttribute = fxMarginN !
								columns = 21
								format = decimal.detailed
								type = decimal
								chars = 23
								editable = false
								bean-property = fxMarginN
								id = fxMarginN
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								labels en = "Margin Amount"
								domainAttribute = fxMarginM !
								for = fxMarginM
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 611379932826099
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- Box ---
							{
								--- TextField ---
									domainAttribute = fxMarginM !
									columns = 21
									format = decimal
									horizontalAlignment = trail
									type = amount
									chars = 18
									editable = false
									bean-property = fxMarginM
									id = fxMarginM
								--- Include ---
									domainAssociation = opCurrency
									includeSrc = "" !
									resource:///default/defaultFragments/CurrencyIdentifierView.fragment
									bean-property-prefix = opCurrency.
							}
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								labels en = "Market Rate", de = Basis-Kurs, fr = "Taux de base"
								domainAttribute = fxMarketRateN !
								for = fxMarketRateN
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 611379934790036
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- TextField ---
								domainAttribute = fxMarketRateN !
								columns = 21
								format = decimal.detailed
								horizontalAlignment = "${corporatehalign}"
								type = decimal
								chars = 23
								editable = false
								bean-property = fxMarketRateN
								id = fxMarketRateN
						}
						--- GridCell ---
							gridColumnWidth = 25
						--- GridCell ---
							gridColumnWidth = 25
					}
				}
			}
		}
	}
}