# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "View Advances Order", de = "Geldeinlagen ansehen", fr = "Voir les avances d\'ordre"
	containment = container
	domainEntity = "AAADSExtOperation:ExtOperationAll"
	bean-define = DSBean.AAADSExtOperation.ExtOperationAll
	bean-name = ExtOperationAll
	id = QuickOrderMMLoanView_C2Au4
	tid = 768783443163027
{
	--- Box ---
		boxType = vertical
	{
		--- Box ---
			labels en = "Quick / Detailed"
			boxType = vertical
			widgetBorder = box
			tid = 768783444306748
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 4
				gridColumnsWidth = "25,25,25,25" !
				gridRowCount = 1
			{
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- RadioButton ---
						labels en = Quick
						selected = true
						group = detailedView
						id = Short
						tid = 768783445917009
					--- RadioButton ---
						labels en = Detailed
						group = detailedView
						id = Full
						tid = 768783447871726
				}
				--- GridCell ---
					gridColumnWidth = 25
				--- GridCell ---
					gridColumnWidth = 25
				--- GridCell ---
					gridColumnWidth = 25
			}
		}
		--- Conditional ---
			indexOfSelectedChild = 0
		{
			--- ConditionalBody ---
				javaCode = "<nav:is-selected  group-id=\"detailedView\" element-id=\"Short\" default-selected=\"true\"/>"
				technicalName = Quick
				boxType = vertical
				isWidgetSelected = true
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/extoperation/order/view/QuickMMLoanView.module
			}
			--- ConditionalBody ---
				javaCode = true
				technicalName = Default
				boxType = vertical
				isWidgetVisible = false
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/extoperation/order/view/MMLoanView.module
			}
		}
		--- Grid ---
			cssClass = blank
			gridColumnCount = 4
			gridColumnsWidth = "25,25,25,25" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Button ---
					labels en = New, de = Neu, fr = Nouveau
					id = btn_l1___
					tid = 768783449824768
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = new ud
						functionResult.id = "valueOf(form.functionResult.id)" ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
				--- Button ---
					labels en = "Back to Session", de = "Zurück zur Sitzung", fr = "Retour à la session"
					id = btn_P_W05
					tid = 768783451778368
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = WUI_main
						flow-action = back ud
						only-changed = false
						prevalidate = false
						modal = false
					}
					Event OnClick (closeLayer)
				}
			}
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
		}
	}
}