# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSExtOperation:ExtOperationAll"
	cssClass = nodeco
	bean-define = DSBean.AAADSExtOperation.ExtOperationAll
	bean-name = ExtOperationAll
	id = SecurityModeCreate_hQ__a
{
	--- Box ---
		labels en = Mode, de = Art, fr = Mode
		boxType = vertical
		tid = 11909020892878
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 2
			gridColumnsWidth = "50,50" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 50
			{
				--- Box ---
					boxType = vertical
				{
					--- Grid ---
						cssClass = blank
						gridColumnCount = 2
						gridColumnsWidth = "50,50" !
						gridRowCount = 2
					{
						--- GridCell ---
							gridColumnWidth = 50
						{
							--- LabelDomain ---
								labels en = "Order Type"
								domainAttribute = orderNatE !
								for = orderNatE
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
								tid = 5576486959096
						}
						--- GridCell ---
							gridColumnWidth = 50
						{
							--- ComboBox ---
								domainAttribute = orderNatE !
								horizontalAlignment = "${corporatehalign}"
								editable = false
								required = true
								bean-property = orderNatE
								id = orderNatE
						}
						--- GridCell ---
							gridColumnWidth = 50
						{
							--- LabelDomain ---
								labels en = Validity
								domainAttribute = orderLimitD !
								for = orderLimitD
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								required = true
								tid = 5576504394552
						}
						--- GridCell ---
							gridColumnWidth = 50
						{
							--- CaldateField ---
								domainAttribute = orderLimitD !
								format = datetime.date-only
								horizontalAlignment = "${corporatehalign}"
								type = datetime
								editable = false
								required = true
								bean-property = orderLimitD
								id = orderLimitD
						}
					}
				}
			}
			--- GridCell ---
				gridColumnWidth = 50
			{
				--- Box ---
					boxType = vertical
				{
					--- Conditional ---
						indexOfSelectedChild = 0
					{
						--- ConditionalBody ---
							javaCode = "Integer.toString(com.odcgroup.aaa.OperationOrderNatE.StopLimit).equals(<bean:get-property bean=\"ExtOperationAll\" property=\"orderNatE\"/>.toString())"
							technicalName = Limit-Stop
							boxType = vertical
							isWidgetSelected = true
						{
							--- Grid ---
								cssClass = blank
								gridColumnCount = 2
								gridColumnsWidth = "50,50" !
								gridRowCount = 2
							{
								--- GridCell ---
									gridColumnWidth = 50
								{
									--- LabelDomain ---
										labels en = Limit
										domainAttribute = limitQuoteN !
										for = limitQuoteN
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										required = true
										tid = 5576520608904
								}
								--- GridCell ---
									gridColumnWidth = 50
								{
									--- TextField ---
										domainAttribute = limitQuoteN !
										columns = 21
										format = decimal.detailed
										horizontalAlignment = "${corporatehalign}"
										type = decimal
										chars = 23
										editable = false
										required = true
										bean-property = limitQuoteN
										id = limitQuoteN
								}
								--- GridCell ---
									gridColumnWidth = 50
								{
									--- LabelDomain ---
										labels en = Stop
										domainAttribute = stopQuoteN !
										for = stopQuoteN
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										required = true
										tid = 5571969128066
								}
								--- GridCell ---
									gridColumnWidth = 50
								{
									--- TextField ---
										domainAttribute = stopQuoteN !
										columns = 21
										format = decimal.detailed
										horizontalAlignment = "${corporatehalign}"
										type = decimal
										chars = 23
										editable = false
										required = true
										bean-property = stopQuoteN
										id = stopQuoteN
								}
							}
						}
						--- ConditionalBody ---
							javaCode = "Integer.toString(com.odcgroup.aaa.OperationOrderNatE.Stop).equals(<bean:get-property bean=\"ExtOperationAll\" property=\"orderNatE\"/>.toString())"
							technicalName = Stop
							boxType = vertical
							isWidgetVisible = false
						{
							--- Grid ---
								cssClass = blank
								gridColumnCount = 2
								gridColumnsWidth = "50,50" !
								gridRowCount = 2
							{
								--- GridCell ---
									gridColumnWidth = 50
								--- GridCell ---
									gridColumnWidth = 50
								--- GridCell ---
									gridColumnWidth = 50
								{
									--- LabelDomain ---
										labels en = Stop, fr = Stop
										domainAttribute = stopQuoteN !
										for = stopQuoteN
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										tid = 5571976493695
								}
								--- GridCell ---
									gridColumnWidth = 50
								{
									--- TextField ---
										domainAttribute = stopQuoteN !
										columns = 21
										format = decimal.detailed
										horizontalAlignment = "${corporatehalign}"
										type = decimal
										chars = 23
										editable = false
										bean-property = stopQuoteN
										id = stopQuoteN
								}
							}
						}
						--- ConditionalBody ---
							javaCode = "Integer.toString(com.odcgroup.aaa.OperationOrderNatE.Limit).equals(<bean:get-property bean=\"ExtOperationAll\" property=\"orderNatE\"/>.toString())"
							technicalName = Limit
							boxType = vertical
							isWidgetVisible = false
						{
							--- Grid ---
								cssClass = blank
								gridColumnCount = 2
								gridColumnsWidth = "50,50" !
								gridRowCount = 2
							{
								--- GridCell ---
									gridColumnWidth = 50
								--- GridCell ---
									gridColumnWidth = 50
								--- GridCell ---
									gridColumnWidth = 50
								{
									--- LabelDomain ---
										labels en = Limit
										domainAttribute = limitQuoteN !
										for = limitQuoteN
										cssClass = grey
										horizontalAlignment = "${corporatehalign}"
										required = true
										tid = 5571969351434
								}
								--- GridCell ---
									gridColumnWidth = 50
								{
									--- TextField ---
										domainAttribute = limitQuoteN !
										columns = 21
										format = decimal.detailed
										horizontalAlignment = "${corporatehalign}"
										type = decimal
										chars = 23
										editable = false
										required = true
										bean-property = limitQuoteN
										id = limitQuoteN
								}
							}
						}
					}
				}
			}
		}
	}
}