# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSExtOperation:ExtOperationAll"
	cssClass = nodeco
	bean-define = DSBean.AAADSExtOperation.ExtOperationAll
	bean-name = ExtOperationAll
	id = SecurityCreateBooking_L__S8
{
	--- Box ---
		labels en = Booking, de = Verbuchung, fr = Réservation
		boxType = vertical
		tid = 11432954559867
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 4
			gridColumnsWidth = "25,25,25,25" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- LabelDomain ---
					labels en = "BO instruction", de = "BO Instruktion", fr = "BO instruction"
					domainAttribute = remark2C !
					for = remark2C
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					tid = 869778969578535
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- TextArea ---
					domainAttribute = remark2C !
					columns = 50
					horizontalAlignment = "${corporatehalign}"
					rows = 3
					type = text
					editable = false
					bean-property = remark2C
					id = remark2C
			}
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
		}
	}
}