<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="menu" nsURI="http://www.odcgroup.com/t24/menu/Menu" nsPrefix="menu">
  <eClassifiers xsi:type="ecore:EClass" name="MenuRoot">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metamodelVersion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rootItem" eType="#//MenuItem"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MenuItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabled" eType="#//Enabled"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayTabs" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="securityRole" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shortcut" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="labels" upperBound="-1"
        eType="#//Translation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="version" eType="ecore:EClass platform:/resource/com.odcgroup.t24.version.model/model/generated/VersionDSL.ecore#//Version"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enquiry" eType="ecore:EClass platform:/resource/com.odcgroup.t24.enquiry.model/model/generated/Enquiry.ecore#//Enquiry"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="compositeScreen" eType="ecore:EClass platform:/resource/com.odcgroup.edge.t24ui.model/model/t24ui.ecore#//CompositeScreen"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="includedMenu" eType="#//MenuRoot"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="application" eType="ecore:EClass platform:/resource/com.odcgroup.mdf.ecore/src/main/model/mdf.ecore#//MdfClass"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameters" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="submenus" upperBound="-1"
        eType="#//MenuItem" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Translation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Enabled">
    <eLiterals name="true" literal="true"/>
    <eLiterals name="false" value="1" literal="false"/>
    <eLiterals name="conditional" value="2" literal="conditional"/>
  </eClassifiers>
</ecore:EPackage>
