# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels fr = "Liste des opérations sur titres", de = "Liste der Kapitalmassnahmen"
	domainEntity = "AAADSCorporateAction:CorporateActionList"
	cssClass = nodeco
	bean-define = DSBean.AAADSCorporateAction.CorporateActionList
	bean-name = CorporateActionList
	id = CorporateActionList_Q___9
	tid = 29271284834245
{
	--- Box ---
		labels en = "Corporate Action ", fr = "Opération sur titres", de = Kapitalmassnahme
		boxType = vertical
		widgetBorder = box
		width = 0
		tid = 712971923470441
	{
		--- TableTree ---
			table-filter-layer = true
			id = e84Y5
			table-column-count = 8 !
			table-columns-width = "12,12,12,12,12,12,12,12" !
		{
			--- TableColumn ---
				column-name = code !
				column-type = domain !
				domainAttribute = code !
				column-locked = true
				id = code
				table-column-width = 12
			{
				--- TableColumnItem ---
					item-column = code
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Event Type", fr = "Type d\'événement", de = Ereignistyp
				column-name = eventTypeExtDenomination !
				column-type = domain !
				domainAttribute = eventTypeExtDenomination !
				type = text
				column-locked = true
				id = eventTypeExtDenomination
				table-column-width = 12
				tid = 439341176352301
			{
				--- TableColumnItem ---
					toolTips en = "Event Type"
					item-column = eventTypeExtDenomination
					previewValue = value
					tid = 369930565852627
			}
			--- TableColumn ---
				labels en = "Sub-Event Type", fr = "Sous-type d\'événement", de = "Unterart des Ereignisses"
				column-name = subEventTypeExtDenomination !
				column-type = domain !
				domainAttribute = subEventTypeExtDenomination !
				type = text
				id = subEventTypeExtDenomination
				table-column-width = 12
				tid = 369006519028753
			{
				--- TableColumnItem ---
					toolTips en = "Sub_Event Type"
					item-column = subEventTypeExtDenomination
					previewValue = value
					tid = 369943109985410
			}
			--- TableColumn ---
				column-name = announcementD !
				column-type = domain !
				domainAttribute = announcementD !
				id = announcementD
				table-column-width = 12
			{
				--- TableColumnItem ---
					item-column = announcementD
					format = datetime.date-only
					previewValue = value
			}
			--- TableColumn ---
				column-name = effectiveD !
				column-type = domain !
				domainAttribute = effectiveD !
				id = effectiveD
				table-column-width = 12
			{
				--- TableColumnItem ---
					item-column = effectiveD
					format = datetime.date-only
					previewValue = value
			}
			--- TableColumn ---
				column-name = processingStatusE !
				column-type = domain !
				domainAttribute = processingStatusE !
				type = text
				column-is-part-of-filter = false
				column-locked = true
				id = processingStatusE
				table-column-width = 12
			{
				--- TableColumnItem ---
					item-column = processingStatusE
					previewValue = value
			}
			--- TableColumn ---
				column-name = providerExtDenomination !
				column-type = domain !
				domainAttribute = providerExtDenomination !
				type = text
				id = providerExtDenomination
				table-column-width = 12
			{
				--- TableColumnItem ---
					item-column = providerExtDenomination
					previewValue = value
			}
			--- TableColumn ---
				column-name = shortDescriptionC !
				column-type = domain !
				domainAttribute = shortDescriptionC !
				type = text
				column-is-part-of-filter = false
				column-visibility = not-visible
				id = shortDescriptionC
				table-column-width = 12
			{
				--- TableColumnItem ---
					item-column = shortDescriptionC
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = effectiveD
				sort-direction = descending
				sort-rank = 4
			--- TableSort ---
				sort-column-name = announcementD
				sort-direction = descending
				sort-rank = 3
			--- TableSort ---
				sort-column-name = eventTypeExtDenomination
				sort-direction = descending
				sort-rank = 6
			--- TableSort ---
				sort-column-name = subEventTypeExtDenomination
				sort-direction = descending
				sort-rank = 8
		}
	}
}