# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSOrderList:OrderListDetailedList"
	cssClass = nodeco
	bean-define = DSBean.AAADSOrderList.OrderListDetailedList
	bean-name = OrderListDetailedList
	id = DepositDetailedList_w___w
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			display-checkbox = true
			table-filter-layer = true
			id = s_z__
			table-column-count = 20 !
			table-columns-width = "5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5" !
			table-filterset-id = fs_OUS
		{
			--- TableColumn ---
				labels en = Validate, fr = Valider, de = Bestätigen
				column-name = VALIDATE
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				id = L5_6_
				table-column-width = 5
				tid = 110879161182301
			{
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "\"true\".equals(<udp:item column=\"ACTION_RIGHT_VALIDATE\"/>.toString())"
						technicalName = Condition
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips en = "Validate Order", fr = "Valider l\'ordre", de = Bestätigen
							horizontalAlignment = center
							icon = tick
							id = y11qE
							tid = 16219301671272
						{
							Event OnClick (submit) S
							// "Execute selected Update Field TA Function"
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = validate ud
								modal = false
								only-changed = false
								prevalidate = false
								DSEntityCode = "<udp:item column=\"ORDER_CODE\"/>" ud
							}
						}
					}
				}
			}
			--- TableColumn ---
				labels en = Reject, fr = Rejeter, de = Ablehnen
				column-name = REJECT
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				id = Y7__f
				table-column-width = 5
				tid = 110882537135754
			{
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "\"true\".equals(<udp:item column=\"ACTION_RIGHT_VALIDATE\"/>.toString())"
						technicalName = Condition
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips en = "Reject Order", fr = "Rejeter l\'ordre", de = Ablehnen
							horizontalAlignment = center
							icon = cross
							id = y57__
							tid = 16230061420861
						{
							Event OnClick (submit) S
							// "Execute selected Update Field TA Function"
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = reject ud
								modal = false
								only-changed = false
								prevalidate = false
								DSEntityCode = "<udp:item column=\"ORDER_CODE\"/>" ud
							}
						}
					}
				}
			}
			--- TableColumn ---
				labels en = Cancel, de = Streichen, fr = Annuler
				column-name = CANCEL
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				id = p_wN_
				table-column-width = 5
				tid = 110886272903301
			{
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "\"true\".equals(<udp:item column=\"ACTION_RIGHT_CANCEL\"/>.toString())"
						technicalName = Condition
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips en = "Cancel Order", fr = "Annuler l\'ordre", de = Streichen
							horizontalAlignment = center
							icon = delete
							id = ypU__
							tid = 16240669410702
						{
							Event OnClick (submit) S
							// "Execute selected Update Field TA Function"
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = cancel ud
								modal = false
								only-changed = false
								prevalidate = false
								DSEntityCode = "<udp:item column=\"ORDER_CODE\"/>" ud
							}
						}
					}
				}
			}
			--- TableColumn ---
				labels de = Ansehen, fr = Voir, en = View
				column-name = VIEW
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				id = W_1__
				table-column-width = 5
				tid = 1056269977347959
			{
				--- Icon ---
					toolTips de = "Auftrag ansehen", fr = "Voir l’ordre", en = "View Order"
					horizontalAlignment = "${corporatehalign}"
					icon = application_form_magnify
					id = X1_vB
					tid = 1056355752576933
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = view ud
						code = "<udp:item column=\"ORDER_CODE\"/>" ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- TableColumn ---
				labels en = Select, de = Select, fr = Selection
				column-name = ORDER_SELECT
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				id = m_0T_
				table-column-width = 5
				tid = 1043282598276876
			{
				--- CheckBox ---
					column-checkbox-action = orderSel
					column-checkbox-identifier = order_id
					checkbox-group-names = ORDER_HIER_STR
					horizontalTextPosition = trail
					id = btn_Qu58X
			}
			--- TableColumn ---
				labels en = "Order Hierarchy"
				column-display-grouping = true
				column-name = ORDER_HIER_STR
				column-type = placeholder !
				type = text
				column-sortable = false !
				id = D30Ah
				table-column-width = 5
				tid = 1043465409533893
			{
				--- TableGroup ---
					aggregateData = false
					group-column-name = ORDER_HIER_STR
					group-sorting-column-name = ORDER_HIER_STR
					group-sorting-direction = ascending
					hierarchy = true
					group-rank = 1
			}
			--- TableColumn ---
				column-name = CREATION_DATE !
				column-type = domain !
				domainAttribute = CREATION_DATE !
				type = text
				id = CREATION_DATE
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = CREATION_DATE
					format = datetime.date-only
					previewValue = value
			}
			--- TableColumn ---
				column-name = ORDER_DATE !
				column-type = domain !
				domainAttribute = ORDER_DATE !
				type = text
				id = qJ_2h
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = ORDER_DATE
					format = datetime.date-only
					previewValue = value
			}
			--- TableColumn ---
				column-name = PORTFOLIO_NAME !
				column-type = domain !
				domainAttribute = PORTFOLIO_NAME !
				type = text
				id = wsD_v
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = PORTFOLIO_NAME
					previewValue = value
			}
			--- TableColumn ---
				column-name = CONTRACT_TYPE !
				column-type = domain !
				domainAttribute = CONTRACT_TYPE !
				type = text
				id = C_J3h
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = CONTRACT_TYPE
					previewValue = value
			}
			--- TableColumn ---
				labels en = Amount, fr = Montant, de = Betrag
				column-name = AMOUNT
				type = amount
				id = B51_W
				column-computation = make-amount
				column-computation-parameters = "QUANTITY,ORDER_CURRENCY"
				table-column-width = 5
				tid = 110837968168253
			{
				--- TableColumnItem ---
					item-column = AMOUNT
					previewValue = value
			}
			--- TableColumn ---
				column-name = RATE !
				column-type = domain !
				domainAttribute = RATE !
				type = text
				id = H2_59
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = RATE
					previewValue = value
			}
			--- TableColumn ---
				column-name = CONTRACT_REF !
				column-type = domain !
				domainAttribute = CONTRACT_REF !
				type = text
				id = M7s32
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = CONTRACT_REF
					previewValue = value
			}
			--- TableColumn ---
				column-name = EXPIRATION_DATE !
				column-type = domain !
				domainAttribute = EXPIRATION_DATE !
				type = text
				id = V__36
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = EXPIRATION_DATE
					format = date
					previewValue = value
			}
			--- TableColumn ---
				column-name = VALUE_DATE !
				column-type = domain !
				domainAttribute = VALUE_DATE !
				type = text
				id = KS5_n
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = VALUE_DATE
					format = date
					previewValue = value
			}
			--- TableColumn ---
				column-name = STATUS !
				column-type = domain !
				domainAttribute = STATUS !
				type = text
				id = b_84o
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = STATUS
					previewValue = value
			}
			--- TableColumn ---
				column-name = ORDER_CODE !
				column-type = domain !
				domainAttribute = ORDER_CODE !
				type = text
				column-visibility = never-visible
				id = ORDER_CODE
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = ORDER_CODE
					previewValue = value
			}
			--- TableColumn ---
				column-name = order_id !
				column-type = domain !
				domainAttribute = order_id !
				type = text
				column-is-part-of-filter = false
				column-visibility = never-visible
				id = s8o__
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = order_id
					format = integer
					previewValue = value
			}
			--- TableColumn ---
				column-name = QUANTITY !
				column-type = domain !
				domainAttribute = QUANTITY !
				type = text
				column-visibility = never-visible
				id = x7g5J
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = QUANTITY
					format = decimal
					previewValue = value
			}
			--- TableColumn ---
				column-name = ORDER_CURRENCY !
				column-type = domain !
				domainAttribute = ORDER_CURRENCY !
				type = text
				column-visibility = never-visible
				id = T5377
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = ORDER_CURRENCY
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = PORTFOLIO_NAME
				sort-rank = 3
			--- TableSort ---
				sort-column-name = CONTRACT_TYPE_ID
				sort-rank = 4
			--- TableSort ---
				sort-column-name = CREATION_DATE
				sort-direction = descending
				sort-rank = 2
			--- TableExtra ---
				domainAttribute = ACTION_RIGHT_CANCEL
			--- TableExtra ---
				domainAttribute = ACTION_RIGHT_VALIDATE
		}
	}
}