# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSOrderList:OrderListDetailedList"
	cssClass = nodeco
	bean-define = DSBean.AAADSOrderList.OrderListDetailedList
	bean-name = OrderListDetailedList
	id = DepositDetailedListSelectable_L_a_6
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			id = F42v_
			table-column-count = 15 !
			table-columns-width = "6,6,6,6,6,6,6,6,6,6,6,6,6,6,6" !
		{
			--- TableColumn ---
				column-name = SELECT
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				id = fg18C
				table-column-width = 6
			{
				--- CheckBox ---
					column-checkbox-identifier = ORDER_CODE
					horizontalTextPosition = trail
					id = btn_z9J1q
			}
			--- TableColumn ---
				column-name = ORDER_CODE !
				column-type = domain !
				domainAttribute = ORDER_CODE !
				type = text
				id = s_i_v
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = ORDER_CODE
					previewValue = value
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = view ud
						code = "<udp:item column=\"ORDER_CODE\"/>" ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- TableColumn ---
				column-name = CREATION_DATE !
				column-type = domain !
				domainAttribute = CREATION_DATE !
				type = text
				id = CREATION_DATE
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = CREATION_DATE
					format = datetime.date-only
					previewValue = value
			}
			--- TableColumn ---
				column-name = ORDER_DATE !
				column-type = domain !
				domainAttribute = ORDER_DATE !
				type = text
				id = qJ_2h
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = ORDER_DATE
					format = datetime.date-only
					previewValue = value
			}
			--- TableColumn ---
				column-name = PORTFOLIO_NAME !
				column-type = domain !
				domainAttribute = PORTFOLIO_NAME !
				type = text
				id = wsD_v
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = PORTFOLIO_NAME
					previewValue = value
			}
			--- TableColumn ---
				column-name = CONTRACT_TYPE !
				column-type = domain !
				domainAttribute = CONTRACT_TYPE !
				type = text
				id = C_J3h
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = CONTRACT_TYPE
					previewValue = value
			}
			--- TableColumn ---
				labels en = Amount, de = Betrag, fr = Montant
				column-name = AMOUNT
				type = amount
				id = x_Uta
				column-computation = make-amount
				column-computation-parameters = "QUANTITY,ORDER_CURRENCY"
				table-column-width = 6
				tid = 110811057739925
			{
				--- TableColumnItem ---
					item-column = AMOUNT
					previewValue = value
			}
			--- TableColumn ---
				column-name = RATE !
				column-type = domain !
				domainAttribute = RATE !
				type = text
				id = H2_59
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = RATE
					previewValue = value
			}
			--- TableColumn ---
				column-name = CONTRACT_REF !
				column-type = domain !
				domainAttribute = CONTRACT_REF !
				type = text
				id = M7s32
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = CONTRACT_REF
					previewValue = value
			}
			--- TableColumn ---
				column-name = EXPIRATION_DATE !
				column-type = domain !
				domainAttribute = EXPIRATION_DATE !
				type = text
				id = V__36
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = EXPIRATION_DATE
					format = date
					previewValue = value
			}
			--- TableColumn ---
				column-name = VALUE_DATE !
				column-type = domain !
				domainAttribute = VALUE_DATE !
				type = text
				id = KS5_n
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = VALUE_DATE
					format = date
					previewValue = value
			}
			--- TableColumn ---
				column-name = STATUS !
				column-type = domain !
				domainAttribute = STATUS !
				type = text
				id = b_84o
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = STATUS
					previewValue = value
			}
			--- TableColumn ---
				column-name = order_id !
				column-type = domain !
				domainAttribute = order_id !
				type = text
				column-is-part-of-filter = false
				column-visibility = never-visible
				id = s8o__
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = order_id
					format = integer
					previewValue = value
			}
			--- TableColumn ---
				column-name = QUANTITY !
				column-type = domain !
				domainAttribute = QUANTITY !
				type = text
				column-visibility = never-visible
				id = x7g5J
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = QUANTITY
					format = decimal
					previewValue = value
			}
			--- TableColumn ---
				column-name = ORDER_CURRENCY !
				column-type = domain !
				domainAttribute = ORDER_CURRENCY !
				type = text
				column-visibility = never-visible
				id = T5377
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = ORDER_CURRENCY
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = PORTFOLIO_NAME
				sort-rank = 3
			--- TableSort ---
				sort-column-name = CONTRACT_TYPE_ID
				sort-rank = 4
			--- TableSort ---
				sort-column-name = CREATION_DATE
				sort-direction = descending
				sort-rank = 2
		}
	}
}