<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="localref" nsURI="http://www.odcgroup.com/t24/application/localref/model/LocalRef"
    nsPrefix="localref">
  <eClassifiers xsi:type="ecore:EClass" name="LocalRef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="localRefID" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumChars" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minimumChars" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mandatory" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="charType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="overridePossible" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="noInputChange" eType="#//NoInputChange"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultPossible" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="applicationEnrich" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="shortName" lowerBound="1"
        upperBound="-1" eType="ecore:EClass ../../../../../../../../../../com.odcgroup.translation.dsl/src-gen/com/odcgroup/translation/TranslationDsl.ecore#//Translations"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vettingTable" upperBound="-1"
        eType="#//VettingTable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="virtualTable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="applicationVET" eType="ecore:EClass ../../../../../../../../../../com.odcgroup.mdf.ecore/src/main/model/mdf.ecore#//MdfClass"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="NoInputChange">
    <eLiterals name="NONE" literal="NONE"/>
    <eLiterals name="NOINPUT" value="1" literal="NOINPUT"/>
    <eLiterals name="NOCHANGE" value="2" literal="NOCHANGE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VettingTable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vettingTable" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="remarks" upperBound="-1"
        eType="ecore:EClass ../../../../../../../../../../com.odcgroup.translation.dsl/src-gen/com/odcgroup/translation/TranslationDsl.ecore#//Translations"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
