# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = Context, fr = Contexte, de = Kontext
	domainEntity = "AAADSDomain:DomainContext"
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = Context_pD5K8
	tid = 1947041697577632
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			id = cC__8
			indexOfSelectedChild = 0
		{
			--- Tab ---
				labels en = Basic, fr = Base, de = Einfach
				id = tab_L_2_a
				isWidgetSelected = true
				tid = 1947180502463515
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 4
					gridColumnsWidth = "25,25,25,25" !
					gridRowCount = 1
				{
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainPortfolioDimension.fragment
					}
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainPivotDate.fragment
					}
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainRefCurrency.fragment
					}
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainHierarchyIdentifier.fragment
					}
				}
			}
			--- Tab ---
				labels en = Advanced, de = Erweitert, fr = Avancé
				id = tab_q7736
				isWidgetVisible = false
				tid = 1947223313341480
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 2
					gridColumnsWidth = "25,25" !
					gridRowCount = 1
				{
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainMinStatus.fragment
					}
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainMaxStatus.fragment
					}
				}
			}
		}
		--- Grid ---
			cssClass = blank
			gridColumnCount = 4
			gridColumnsWidth = "25,25,25,25" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Code ---
					code = "<xsp:logic>\r\nList errors = ValidationHelper.getErrorReporter(objectModel,\"DSActivityBean.AAADSDomain.DomainContext.reporter\").getErrors();\r\nif(errors.isEmpty()){\r\n//button accessible\r\n<xgui:button id=\"btn_T___S\">\r\n\t<xgui:text>\r\n    \t<i18n:text>1947884751567098.text</i18n:text>\r\n    </xgui:text>\r\n    <xgui:onevent type=\"click\">\r\n    \t<xgui:submit only-changed=\"true\" param=\"flow-action=execute\" target=\"popup\" widget-group-ref=\"form\">\r\n        \t<xsp:attribute name=\"call-URI\"><pageflow:continuation/></xsp:attribute>\r\n\t\t\t<xsp:attribute name=\"enabled\">true</xsp:attribute>\t\t            \t\t\t\r\n\t\t\t<xgui:param name=\"cocoon-view\">inline</xgui:param>\r\n        </xgui:submit>\r\n\t</xgui:onevent>\r\n</xgui:button>\r\n}\r\n</xsp:logic>"
				--- Button ---
					labels en = Execute, fr = Exécuter, de = Ausführen
					cssClass = hidden
					id = btn_T___S
					tid = 1947884751567098
				{
					Event OnClick (submit)
					{
						method = get
						call-URI = "<pageflow:continuation/>"
						widget-group-ref = form
						param = "flow-action=execute"
						only-changed = true
						prevalidate = false
						modal = false
						target = popup
						cocoon-view = inline ud
					}
				}
				--- Button ---
					labels en = "Default Settings", de = Standardeinstellung, fr = "Valeurs par défaut"
					id = btn_hq3S7
					tid = 1948004935912236
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = reset ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
		}
	}
}