# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = Xante, fr = Xante, de = Xante
	domainEntity = "AAADSDomain:DomainContext"
	collapsible = true
	cssClass = nodeco
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = PortfolioRisk_VM93_
	tid = 2099078597602397
{
	--- Box ---
		boxType = vertical
	{
		--- Code ---
			code = "<xsp:logic>\r\nString url = <bean:get-property bean=\"DomainContext\" property=\"externalDefinitionC\"/>.toString();\r\nurl = url.substring(url.indexOf(\"http\"));\r\n</xsp:logic>\r\n\r\n<xgui:external>\r\n\t<xsp:attribute name=\"src\"><xsp:expr>url</xsp:expr></xsp:attribute>\r\n \t<xsp:attribute name=\"grab\">chartouterwrapper</xsp:attribute>\r\n\t<xsp:attribute name=\"id\">XANTE</xsp:attribute>\r\n\t<xsp:attribute name=\"height\">500</xsp:attribute>\r\n</xgui:external>"
	}
}