# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Search Market Segment", fr = "Recherche de segment de marché", de = "Marktsegment Suche"
	containment = container
	search = container !
	cssClass = nodeco
	id = MarketSegmentSearch_yRV8o
	tid = 30355271073374
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/marketsegment/search/MarketSegmentSearchInput.module
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/marketsegment/search/MarketSegmentList.module
	}
}