# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels de = "Marktsegment Suchbegriffe", en = "Market Segment Search Criteria", fr = "Critères de recherche sur segment de marché"
	containment = container
	domainEntity = "AAADSMarketSegment:MarketSegmentSearchCriteria"
	search = input !
	bean-define = DSBean.AAADSMarketSegment.MarketSegmentSearchCriteria
	bean-name = MarketSegmentSearchCriteria
	id = MarketSegmentSearchInput_s2_Zt
	tid = 30375346043881
{
	--- Box ---
		boxType = vertical
	{
		--- FilterCriteria ---
			includedFile = "resource:/com/module/search/QueryBuilder.xsp"
		--- Include ---
			includeSrc = "" !
			resource:///default/search/NavigationSearch.fragment
	}
}