# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Search Results", fr = "Résultats de la recherche", de = Suchergebnisse
	domainEntity = "AAADSMarketSegment:MarketSegmentList"
	search = output !
	bean-define = DSBean.AAADSMarketSegment.MarketSegmentList
	bean-name = MarketSegmentList
	id = MarketSegmentList_YWHyj
	tid = 30344738647843
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			id = jR__9
			table-column-count = 2 !
			table-columns-width = "50,50" !
		{
			--- TableColumn ---
				column-display-grouping = true
				column-name = name !
				column-type = domain !
				domainAttribute = name !
				type = text
				column-locked = true
				id = name
				table-column-width = 50
			{
				--- Conditional ---
					indexOfSelectedChild = 1
				{
					--- ConditionalBody ---
						javaCode = "com.odcgroup.tsl.wui.search.form.SearchFormHelper.isLookup(objectModel) == false"
						technicalName = NotLookup
						boxType = vertical
						isWidgetVisible = false
					{
						--- TableColumnItem ---
							toolTips en = "Select Market Segment", fr = "Sélectionner le segment de marché", de = "Marktsegment auswählen"
							item-column = name
							previewValue = value
							tid = 30344740602002
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = select ud
								Query.beanValue2 = "<udp:item column=\"name\"/>" ud
								modal = false
								only-changed = false
								prevalidate = false
								Query.beanValue1 = "<udp:item column=\"id\"/>" ud
							}
						}
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetSelected = true
					{
						--- TableColumnItem ---
							toolTips en = "Select Market Segment", fr = "Sélectionner le segment de marché", de = "Marktsegment auswählen"
							item-column = name
							previewValue = value
							tid = 30344742553649
						{
							Event OnClick (setWidgetValue)
							{
								widget-group-id = "<xsp:expr>com.odcgroup.tsl.wui.search.form.SearchFormHelper.getParentWidgetValue1Id(objectModel)</xsp:expr>"
								value = "<udp:item column=\"name\"/>"
								target = WUI_main
							}
							Event OnClick (winClose)
							{
								target = self
							}
						}
					}
				}
				--- TableGroup ---
					aggregateData = false !
					group-column-name = gridCode
					group-sorting-column-name = mktStructParentMktSgtExtDenomination
					group-sorting-direction = ascending
					group-rank = 1
				--- TableGroup ---
					group-column-name = mktStructParentMktSgtExtDenomination
					group-sorting-column-name = name
					group-sorting-direction = ascending
					group-rank = 2
			}
			--- TableColumn ---
				column-name = extDenomination !
				column-type = domain !
				domainAttribute = extDenomination !
				type = text
				id = extDenomination
				table-column-width = 50
			{
				--- TableColumnItem ---
					item-column = extDenomination
					previewValue = value
			}
			--- TableExtra ---
				domainAttribute = id
			--- TableSort ---
				sort-column-name = name
				sort-rank = 1
		}
	}
}