# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Update Forex Order", de = "Devisenkassa-Auftrag aktualisieren", fr = "Mettre à jour ordre de change"
	containment = container
	domainEntity = "AAADSExtOperation:ExtOperationAll"
	bean-define = DSBean.AAADSExtOperation.ExtOperationAll
	bean-name = ExtOperationAll
	id = ForexUpdate_nq__c
	tid = 2155423301218730
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/extoperation/order/create/ForexNoButtonCreate.module
		--- Grid ---
			cssClass = blank
			gridColumnCount = 4
			gridColumnsWidth = "25,25,25,25" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Button ---
					labels en = Save, de = Speichern, fr = Sauver
					id = btn_U_8__
					tid = 2155423345165097
				{
					Event OnClick (submit)
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						widget-group-ref = form
						param = "flow-action=save"
						only-changed = true
						modal = false
						prevalidate = false
					}
				}
				--- Button ---
					labels en = Cancel, de = Abbrechen, fr = Annuler
					id = btn_L__H_
					tid = 2155423347118698
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						flow-action = cancel ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
		}
	}
}