# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Modify Call Deposit Amendment", de = "Kündigungsgeldanlage ändern", fr = "Modifier amendement de dépôt à vue"
	containment = container
	domainEntity = "AAADSExtOperation:ExtOperationAll"
	bean-define = DSBean.AAADSExtOperation.ExtOperationAll
	bean-name = ExtOperationAll
	id = MMDepositAmdUpdate_b6dC_
	tid = 350315184385445
{
	--- Box ---
		boxType = vertical
	{
		--- TextArea ---
			domainAttribute = summaryC !
			columns = 200
			horizontalAlignment = "${corporatehalign}"
			rows = 1
			type = text
			editable = false
			bean-property = summaryC
			id = summaryC
		--- Box ---
			labels en = Identification, de = Identifikation, fr = Identification
			boxType = vertical
			tid = 350315185314055
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 4
				gridColumnsWidth = "25,25,25,25" !
				gridRowCount = 2
			{
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- LabelDomain ---
						labels en = Contract, fr = Contrat
						domainAttribute = sourceCode !
						for = sourceCode
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						tid = 6480780652010
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- TextField ---
						domainAttribute = sourceCode !
						horizontalAlignment = "${corporatehalign}"
						type = text
						chars = 20
						editable = false
						bean-property = sourceCode
						id = sourceCode
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- LabelDomain ---
						domainAttribute = valueD !
						for = valueD
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- CaldateField ---
						domainAttribute = valueD !
						format = datetime.date-only
						horizontalAlignment = "${corporatehalign}"
						type = datetime
						required = true
						bean-property = valueD
						id = valueD
					{
						Event OnChange (submit)
						{
							method = post
							call-URI = "<pageflow:continuation/>"
							widget-group-ref = form
							param = "flow-action=reload"
							only-changed = true
							modal = false
							prevalidate = false
						}
					}
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- LabelDomain ---
						domainAttribute = portfolio !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- Include ---
						domainAssociation = portfolio
						includeSrc = "" !
						resource:///default/defaultFragments/PortfolioIdentifierView.fragment
						bean-property-prefix = portfolio.
					--- Include ---
						domainAssociation = functionResult
						includeSrc = "" !
						resource:///default/domain/basicelements/DomainId.fragment
						bean-property-prefix = functionResult.
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- LabelDomain ---
						labels en = "Portfolio Name", de = "Portfolio Name", fr = "Nom du portefeuille"
						domainAttribute = portfolio !
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						tid = 350315189194157
				}
				--- GridCell ---
					gridColumnWidth = 25
				{
					--- Include ---
						domainAssociation = portfolio
						includeSrc = "" !
						resource:///default/extoperation/basicelements/PortfolioNameIdentifier.fragment
						bean-property-prefix = portfolio.
				}
			}
		}
		--- Conditional ---
			indexOfSelectedChild = 0
		{
			--- ConditionalBody ---
				javaCode = "null != <bean:get-property bean=\"ExtOperationAll\" property=\"portfolio\"/> &amp;&amp; null != <bean:get-property bean=\"ExtOperationAll\" property=\"portfolio.code\"/>"
				technicalName = IsPtfSelected
				boxType = vertical
				isWidgetSelected = true
			{
				--- Box ---
					labels en = Instruction, fr = Instruction, de = Instruktion
					boxType = vertical
					tid = 350315191145522
				{
					--- Grid ---
						cssClass = blank
						gridColumnCount = 4
						gridColumnsWidth = "25,25,25,25" !
						gridRowCount = 2
					{
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								labels en = Amount, fr = Montant, de = Betrag
								domainAttribute = quantityN !
								for = quantityN
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
								tid = 350315193099402
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- Box ---
							{
								--- TextField ---
									domainAttribute = quantityN !
									columns = 21
									format = decimal.detailed
									horizontalAlignment = "${corporatehalign}"
									type = decimal
									allow = "\'0123456789.,\'"
									chars = 23
									required = true
									bean-property = quantityN
									id = quantityN
								--- Include ---
									domainAssociation = account
									includeSrc = "" !
									resource:///default/defaultFragments/InstrumentIdentifierView.fragment
									bean-property-prefix = account.
								--- Include ---
									domainAssociation = accCurrency
									includeSrc = "" !
									resource:///default/defaultFragments/CurrencyIdentifierView.fragment
									bean-property-prefix = accCurrency.
							}
						}
						--- GridCell ---
							gridColumnWidth = 25
						--- GridCell ---
							gridColumnWidth = 25
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								domainAttribute = rateP !
								for = rateP
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- TextField ---
								domainAttribute = rateP !
								columns = 11
								format = percentTA
								horizontalAlignment = "${corporatehalign}"
								type = percent
								allow = "\'0123456789.,\'"
								chars = 11
								editable = false
								bean-property = rateP
								id = rateP
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- LabelDomain ---
								domainAttribute = counterpartyThird !
								cssClass = grey
								horizontalAlignment = "${corporatehalign}"
						}
						--- GridCell ---
							gridColumnWidth = 25
						{
							--- Include ---
								domainAssociation = counterpartyThird
								includeSrc = "" !
								resource:///default/defaultFragments/ThirdPartyIdentifierView.fragment
								bean-property-prefix = counterpartyThird.
						}
					}
				}
			}
		}
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/extoperation/order/create/AdditionalDataOther.module
		--- Grid ---
			cssClass = blank
			gridColumnCount = 4
			gridColumnsWidth = "25,25,25,25" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Button ---
					labels en = Save, de = Speichern, fr = Sauver
					id = btn_y3i4_
					tid = 350315237289376
				{
					Event OnClick (submit)
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						widget-group-ref = form
						param = "flow-action=save"
						only-changed = true
						modal = false
						prevalidate = false
					}
				}
				--- Button ---
					labels en = Cancel, de = Abbrechen, fr = Annuler
					id = btn_hF0_o
					tid = 350315240951294
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						flow-action = cancel ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
		}
	}
}