# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSDeposit:DepositList"
	cssClass = nodeco
	bean-define = DSBean.AAADSDeposit.DepositList
	bean-name = DepositList
	id = DepositList_G1__V
{
	--- Box ---
		labels en = Deposit, de = Lagerstelle, fr = Dépositaire
		boxType = vertical
		width = 0
		tid = 713259048677136
	{
		--- TableTree ---
			table-filter-layer = true
			id = i9_73
			table-column-count = 3 !
			table-columns-width = "33,33,33" !
		{
			--- TableColumn ---
				labels de = Code
				column-name = code !
				column-type = domain !
				domainAttribute = code !
				id = code
				table-column-width = 33
				tid = 24368981387578
			{
				--- TableColumnItem ---
					item-column = code
					previewValue = value
			}
			--- TableColumn ---
				column-name = name !
				column-type = domain !
				domainAttribute = name !
				id = name
				table-column-width = 33
			{
				--- TableColumnItem ---
					item-column = name
					previewValue = value
			}
			--- TableColumn ---
				column-name = thirdCode !
				column-type = domain !
				domainAttribute = thirdCode !
				id = thirdCode
				table-column-width = 33
			{
				--- TableColumnItem ---
					item-column = thirdCode
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = code
				sort-rank = 1
		}
	}
}