# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSFtConvention:FtConventionList"
	bean-define = DSBean.AAADSFtConvention.FtConventionList
	bean-name = FtConventionList
	id = FtConventionList_zh_u_
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			id = u_0q_
			table-column-count = 6 !
			table-columns-width = "16,16,16,16,16,16" !
		{
			--- TableColumn ---
				column-name = natureE !
				column-type = domain !
				domainAttribute = natureE !
				id = natureE
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = natureE
					previewValue = value
			}
			--- TableColumn ---
				column-name = code !
				column-type = domain !
				domainAttribute = code !
				id = code
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = code
					previewValue = value
			}
			--- TableColumn ---
				column-name = taxGeoCode !
				column-type = domain !
				domainAttribute = taxGeoCode !
				id = taxGeoCode
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = taxGeoCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = taxStatusE !
				column-type = domain !
				domainAttribute = taxStatusE !
				id = taxStatusE
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = taxStatusE
					previewValue = value
			}
			--- TableColumn ---
				column-name = name !
				column-type = domain !
				domainAttribute = name !
				id = name
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = name
					previewValue = value
			}
			--- TableColumn ---
				column-name = denom !
				column-type = domain !
				domainAttribute = denom !
				id = denom
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = denom
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = natureE
				sort-rank = 1
			--- TableSort ---
				sort-column-name = code
				sort-rank = 2
		}
	}
}