# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Add Order", de = "Auftrag hinzufügen", fr = "Ajouter un ordre"
	containment = container
	domainEntity = "AAADSExtOperation:ExtOperationAll"
	bean-define = DSBean.AAADSExtOperation.ExtOperationAll
	bean-name = ExtOperationAll
	id = AddOrder_W_K__
	tid = 454531291231684
{
	--- Box ---
		boxType = vertical
	{
		--- Conditional ---
			indexOfSelectedChild = 0
		{
			--- ConditionalBody ---
				javaCode = "null != <bean:get-property bean=\"ExtOperationAll\" property=\"natureE\"/> &amp;&amp; Integer.toString(com.odcgroup.aaa.OperationNatureE.Buy).equals(<bean:get-property bean=\"ExtOperationAll\" property=\"natureE\"/>.toString())"
				technicalName = Buy
				boxType = vertical
				isWidgetSelected = true
			{
				--- Box ---
					boxType = vertical
					cssClass = lightblue
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/extoperation/order/orderproposal/QuickOrderPG.module
				}
			}
			--- ConditionalBody ---
				javaCode = true
				technicalName = Sell
				boxType = vertical
				isWidgetVisible = false
			{
				--- Box ---
					boxType = vertical
					cssClass = lightred
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/extoperation/order/orderproposal/QuickOrderPG.module
				}
			}
		}
		--- Spacer ---
			height = 5
			width = 4
		--- Grid ---
			cssClass = blank
			gridColumnCount = 2
			gridColumnsWidth = "25,25" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Button ---
					labels en = Save, de = Speichern, fr = Sauver
					id = btn_I__V7
					tid = 627752954557217
				{
					Event OnClick (submit)
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						widget-group-ref = form
						target = self
						param = "flow-action=createorder"
						only-changed = true
						functionResult.id = "valueOf(form.functionResult.id)" ud
						portfolio.code = "valueOf(form.portfolio.code)" ud
						modal = false
						prevalidate = false
					}
				}
				--- Button ---
					labels en = Cancel, de = Abbrechen, fr = Annuler
					id = btn_eB38j
					tid = 181650314598950
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = cancelorder ud
						functionResult.id = "valueOf(form.functionResult.id)" ud
						portfolio.code = "valueOf(form.portfolio.code)" ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- GridCell ---
				gridColumnWidth = 25
		}
	}
}