# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Add Security External Position", de = "Externe Wertpapierposition hinzufügen", fr = "Ajouter une position externe titre"
	containment = container
	domainEntity = "AAADSExtOperation:ExtOperationAll"
	bean-define = DSBean.AAADSExtOperation.ExtOperationAll
	bean-name = ExtOperationAll
	id = AddOrder_W_K__
	tid = 94240951655269
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/extoperation/order/orderproposal/SecurityExternalPosition.module
	}
}