# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Modify Security External Position", de = "Externe Wertpapier-Positionen aktualisieren", fr = "Modifier une position externe titre"
	containment = container
	domainEntity = "AAADSExtOperation:ExtOperationAll"
	bean-define = DSBean.AAADSExtOperation.ExtOperationAll
	bean-name = ExtOperationAll
	id = AddOrder_W_K__
	tid = 96843233978077
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/extoperation/order/orderproposal/SecurityExternalPosition.module
	}
}