# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Update Cash External Position", de = "Externe Kontokorrent-Positionen aktualisieren", fr = "Mettre à jour une position externe en liquidité"
	containment = container
	domainEntity = "AAADSExtOperation:ExtOperationAll"
	bean-define = DSBean.AAADSExtOperation.ExtOperationAll
	bean-name = ExtOperationAll
	id = AddOrder_W_K__
	tid = 97101029808722
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/extoperation/order/orderproposal/CashExternalPosition.module
	}
}