# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSInstrChrono:InstrChronoList"
	cssClass = nodeco
	bean-define = DSBean.AAADSInstrChrono.InstrChronoList
	bean-name = InstrChronoList
	id = InstrChronoList_U_I__
{
	--- Box ---
		labels en = Chronology, de = "Zeitliche Abfolge", fr = Chronologie
		boxType = vertical
		widgetBorder = box
		width = 0
		tid = 1142529709604991
	{
		--- TableTree ---
			table-filter-layer = true
			id = Xz5G_
			table-model-reference = DSTableModel.AAADSInstrChrono.InstrChronoList
			table-column-count = 6 !
			table-columns-width = "16,16,16,16,16,16" !
		{
			--- TableColumn ---
				column-name = natureE !
				column-type = domain !
				domainAttribute = natureE !
				column-locked = true
				id = natureE
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = natureE
					previewValue = value
			}
			--- TableColumn ---
				column-name = subNatTypeExtDenomination !
				column-type = domain !
				domainAttribute = subNatTypeExtDenomination !
				type = text
				id = subNatTypeExtDenomination
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = subNatTypeExtDenomination
					previewValue = value
			}
			--- TableColumn ---
				column-name = validityD !
				column-type = domain !
				domainAttribute = validityD !
				column-locked = true
				id = validityD
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = validityD
					format = datetime.date-only
					previewValue = value
			}
			--- TableColumn ---
				column-name = valueN !
				column-type = domain !
				domainAttribute = valueN !
				type = text
				column-locked = true
				id = valueN
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = valueN
					format = decimal
					previewValue = value
			}
			--- TableColumn ---
				column-name = currencyCode !
				column-type = domain !
				domainAttribute = currencyCode !
				type = text
				id = currencyCode
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = currencyCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = thirdPartyExtDenomination !
				column-type = domain !
				domainAttribute = thirdPartyExtDenomination !
				type = text
				id = thirdPartyExtDenomination
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = thirdPartyExtDenomination
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = validityD
				sort-direction = descending
				sort-rank = 1
			--- TableSort ---
				sort-column-name = natureE
				sort-direction = descending
				sort-rank = 2
			--- TableSort ---
				sort-column-name = subNatTypeExtDenomination
				sort-direction = descending
				sort-rank = 4
		}
	}
}