# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Yield To Maturity List", fr = "Taux actuariel brut", de = Rückzahlungsrendite
	domainEntity = "AAADSInstrChrono:InstrChronoList"
	bean-define = DSBean.AAADSInstrChrono.InstrChronoList
	bean-name = InstrChronoList
	id = InstrChronoDividendList_t78p1
	documentation = "List of instrument chrono to be used when the nature is dividends"
	tid = 182998044295019
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			id = W_J1f
			table-model-reference = DSTableModel.AAADSInstrChrono.InstrChronoList
			table-column-count = 2 !
			table-columns-width = "50,50" !
		{
			--- TableColumn ---
				column-name = validityD !
				column-type = domain !
				domainAttribute = validityD !
				type = text
				id = validityD
				table-column-width = 50
			{
				--- TableColumnItem ---
					item-column = validityD
					format = datetime.date-only
					previewValue = value
			}
			--- TableColumn ---
				labels en = Value, fr = Valeur, de = Wert
				column-name = Value
				type = amount
				id = S_2_e
				column-computation = make-amount
				column-computation-parameters = "valueN,currencyName"
				table-column-width = 50
				tid = 182998044842228
			{
				--- TableColumnItem ---
					item-column = Value
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = validityD
				sort-rank = 1
		}
	}
}