# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSFtRateHistory:FtRateHistoryList"
	bean-define = DSBean.AAADSFtRateHistory.FtRateHistoryList
	bean-name = FtRateHistoryList
	id = FtRateHistoryList_VEl__
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			id = g9_D_
			table-column-count = 2 !
			table-columns-width = "50,50" !
		{
			--- TableColumn ---
				column-name = ftConventionCode !
				column-type = domain !
				domainAttribute = ftConventionCode !
				id = ftConventionCode
				table-column-width = 50
			{
				--- TableColumnItem ---
					item-column = ftConventionCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = beginD !
				column-type = domain !
				domainAttribute = beginD !
				id = beginD
				table-column-width = 50
			{
				--- TableColumnItem ---
					item-column = beginD
					format = datetime.date-only
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = ftConventionCode
				sort-rank = 1
			--- TableSort ---
				sort-column-name = beginD
				sort-direction = descending
				sort-rank = 2
		}
	}
}