# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "DS3561:DSDS3561"
	bean-define = DSBean.DS3561.DSDS3561
	bean-name = DSDS3561
	id = DS3561_x7_9i
{
	--- Box ---
		boxType = vertical
	{
		--- Box ---
		{
			--- RadioButton ---
				domainAttribute = renewal
				enumValue = None !
				horizontalTextPosition = trail
				bean-name = DSDS3561
				bean-property = renewal
				group = renewal
				id = btn_H___8
			--- RadioButton ---
				domainAttribute = renewal
				enumValue = Automatic !
				displayLabel = false
				horizontalTextPosition = trail
				bean-name = DSDS3561
				bean-property = renewal
				group = renewal
				id = btn_v1_2_
			--- RadioButton ---
				domainAttribute = renewal
				enumValue = Manual !
				horizontalTextPosition = trail
				bean-name = DSDS3561
				bean-property = renewal
				group = renewal
				id = btn_BQL39
		}
	}
}