# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "NewDomain:DSFlat"
	bean-define = DSBean.NewDomain.DSFlat
	bean-name = DSFlat
	id = DS3553_yo7_9
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			id = wO__h
			indexOfSelectedChild = 1
		{
			--- Tab ---
				labels en = aaa
				id = tab_AE__c
				isWidgetVisible = false
				tid = 93428403206832
			--- Tab ---
				labels en = bbb
				id = tab_d_9O0
				isWidgetSelected = true
				tid = 93428405154845
			{
				Event OnClick (submit)
				{
					call-URI = callURIxxxx
					flow-action = xxxxx ud
					only-changed = false
					method = get
					prevalidate = false
					modal = false
					Snippet FilterSet
					id = fs_012
					level = 1
					targetDataset = "NewDomain:DSFlat"
					{
						Snippet Filter
						attribute = newAttribute333dfdfd
						editMode = readOnly
						filterValue = "NEW_VALUE2,NEW_VALUE"
						operator = IN
					}
				}
			}
		}
	}
}