# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "SimpleDomain:SimpleClassDS"
	bean-define = DSBean.SimpleDomain.SimpleClassDS
	bean-name = SimpleClassDS
	id = DS3760_xHE_9
{
	--- Box ---
		boxType = vertical
	{
		--- Matrix ---
			id = ID_05
			matrix-model-reference = DSBean.SimpleDomain.SimpleClassDS
		{
			--- MatrixAxis ---
				domainAttribute = asset_class !
				group-sorting-column-name = asset_rank
				group-sorting-direction = descending
				maxColumns = 10
				matrixAxis = x-axis !
			--- MatrixAxis ---
				domainAttribute = currency !
				maxRows = 5
				matrixAxis = y-axis !
			--- MatrixContentCell ---
				matrixCellType = content-cell !
			{
				Snippet CssClass --- MatrixContentCellItem ---
					domainAttribute = mkt_val !
					matrixCellItemType = domain !
					id = o_I0u
					aggregationItems = "a_9_I,U2JNS,dX_Y9"
			}
			--- MatrixCell ---
				matrixCellType = last-cell !
			{
				--- MatrixCellItem ---
					domainAttribute = mkt_val !
					matrixCellItemType = domain !
					id = dX_Y9 !
			}
			--- MatrixCell ---
				matrixCellType = last-row !
			{
				--- MatrixCellItem ---
					domainAttribute = mkt_val !
					matrixCellItemType = domain !
					id = U2JNS !
			}
			--- MatrixCell ---
				matrixCellType = last-column !
			{
				--- MatrixCellItem ---
					domainAttribute = mkt_val !
					matrixCellItemType = domain !
					id = a_9_I !
			}
			--- MatrixExtraColumn ---
				matrixCellType = extra-column !
		}
	}
}