# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "NewDomain:DSFlat"
	bean-define = DSBean.NewDomain.DSFlat
	bean-name = DSFlat
	id = DS3731_L_8gu
{
	--- Box ---
		labels en = test
		boxType = vertical
		tid = 336750065276173
	{
		--- TableTree ---
			cssClass = test
			highlightRow = true
			id = qu49_
			table-model-reference = informationModel
			table-column-count = 4 !
			table-columns-width = "25,25,25,25" !
		{
			--- TableColumn ---
				column-display-grouping = true
				column-name = placeholder_C3RRX
				column-type = placeholder !
				type = text
				column-sortable = false !
				id = dyb_9
				table-column-width = 25
			{
				--- TableGroup ---
					aggregateData = false
					eventLevel = onlyLeaf
					group-column-name = Portfolio
					group-sorting-column-name = AmountDecimal
					group-sorting-direction = ascending
					group-rank = 1
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = testtesttest ud
						only-changed = false
						prevalidate = false
						modal = false
					}
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = xxxxxxxxxxx ud
						only-changed = false
						prevalidate = false
						modal = false
					}
				}
			}
			--- TableColumn ---
				column-name = AssetType !
				column-type = domain !
				domainAttribute = AssetType !
				id = s___6
				table-column-width = 25
			{
				--- TableColumnItem ---
					item-column = AssetType
					previewValue = value
			}
			--- TableColumn ---
				column-name = Currency !
				column-type = domain !
				domainAttribute = Currency !
				id = V2n9_
				table-column-width = 25
			{
				--- TableColumnItem ---
					item-column = Currency
					previewValue = value
			}
			--- TableColumn ---
				column-name = isNode !
				column-type = domain !
				domainAttribute = isNode !
				id = b__7_
				table-column-width = 25
			{
				--- TableColumnItem ---
					item-column = isNode
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = Currency
				sort-rank = 1
		}
	}
}