# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "DS3717:DS3717"
	bean-define = DSBean.DS3717.DS3717
	bean-name = DS3717
	id = DS3717_qi_5_
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			table-rendering-mode = in-memory
			id = h_Q_E
			table-column-count = 1 !
			table-columns-width = 100 !
		{
			--- TableColumn ---
				column-name = attr1 !
				column-type = domain !
				domainAttribute = attr1 !
				type = text
				id = attr1
				table-column-width = 100
			{
				--- TableColumnItem ---
					item-column = attr1
					previewValue = value
			}
		}
	}
}