# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "SimpleDomain:SimpleClassDS"
	bean-define = DSBean.SimpleDomain.SimpleClassDS
	bean-name = SimpleClassDS
	id = DS3792_cay__
{
	--- Box ---
		boxType = vertical
	{
		--- Matrix ---
			id = h7CRd
		{
			--- MatrixAxis ---
				domainAttribute = asset_class !
				matrixAxis = x-axis !
			--- MatrixAxis ---
				domainAttribute = my_return !
				group-sorting-column-name = asset_rank
				group-sorting-direction = descending
				matrixAxis = y-axis !
			--- MatrixContentCell ---
				matrixCellType = content-cell !
			{
				--- MatrixContentCellItem ---
					domainAttribute = mkt_val !
					matrixCellItemType = domain !
					id = L7_rA
					aggregationItems = "H5H11,wj7r8,S7p_9"
				--- MatrixContentCellItem ---
					domainAttribute = asset_rank !
					matrixCellItemType = domain !
					id = W2U4_
					aggregationItems = "e4f3F,m_Z98,S23_2"
			}
			--- MatrixCell ---
				matrixCellType = last-cell !
			{
				--- MatrixCellItem ---
					domainAttribute = mkt_val !
					matrixCellItemType = domain !
					id = S7p_9
				--- MatrixCellItem ---
					domainAttribute = asset_rank !
					matrixCellItemType = domain !
					id = S23_2
			}
			--- MatrixCell ---
				matrixCellType = last-row !
			{
				--- MatrixCellItem ---
					domainAttribute = mkt_val !
					matrixCellItemType = domain !
					id = wj7r8
				--- MatrixCellItem ---
					domainAttribute = asset_rank !
					matrixCellItemType = domain !
					id = m_Z98
			}
			--- MatrixCell ---
				matrixCellType = last-column !
			{
				--- MatrixCellItem ---
					domainAttribute = mkt_val !
					matrixCellItemType = domain !
					id = H5H11
				--- MatrixCellItem ---
					domainAttribute = asset_rank !
					matrixCellItemType = domain !
					id = e4f3F
			}
			--- MatrixExtraColumn ---
				matrixCellType = extra-column !
		}
	}
}