# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "SimpleDomain:SimpleClassDS"
	bean-define = DSBean.SimpleDomain.SimpleClassDS
	bean-name = SimpleClassDS
	id = MatrixGenerationTest_K__WG
{
	--- Box ---
		boxType = vertical
	{
		--- Matrix ---
			id = g_lp_
			matrix-model-reference = DSBean.SimpleDomain.SimpleClassDS
		{
			--- MatrixAxis ---
				domainAttribute = asset_class !
				matrixAxis = x-axis !
			--- MatrixAxis ---
				domainAttribute = currency !
				matrixAxis = y-axis !
			--- MatrixContentCell ---
				matrixCellType = content-cell !
			{
				Snippet CssClass
				specificClass = test
				{
					Snippet ConditionalCssClass
					name = test
					condition = "if(1>0)"
					result = "tab AM"
				}
				--- MatrixContentCellItem ---
					column-name = comp_t_20J
					matrixCellItemType = computed !
					format = amount
					id = t_20J
					aggregationItems = "Y8L_5,XY_vI,Sc4Y_"
					column-computation = make-amount
					column-computation-parameters = "asset_class,currency"
			}
			--- MatrixCell ---
				matrixCellType = last-cell !
			{
				--- MatrixCellItem ---
					column-name = comp_Sc4Y_
					matrixCellItemType = computed !
					id = Sc4Y_ !
			}
			--- MatrixCell ---
				matrixCellType = last-row !
			{
				--- MatrixCellItem ---
					column-name = comp_XY_vI
					matrixCellItemType = computed !
					id = XY_vI !
			}
			--- MatrixCell ---
				matrixCellType = last-column !
			{
				--- MatrixCellItem ---
					column-name = comp_Y8L_5
					matrixCellItemType = computed !
					id = Y8L_5 !
			}
			--- MatrixExtraColumn ---
				matrixCellType = extra-column !
			{
				--- MatrixExtraColumnItem ---
					labels en = "My Return"
					displayInLastRow = true
					domainAttribute = my_return !
					matrixCellItemType = domain !
					id = CkJ_6
					tid = 959190827087241
			}
		}
	}
}