# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "SimpleDomain:SimpleClassDS"
	bean-define = DSBean.SimpleDomain.SimpleClassDS
	bean-name = SimpleClassDS
	id = DS3772_fB_rZ
{
	--- Box ---
		boxType = vertical
	{
		--- Matrix ---
			id = a82lA
		{
			--- MatrixAxis ---
				domainAttribute = asset_class !
				matrixAxis = x-axis !
			--- MatrixAxis ---
				domainAttribute = currency !
				matrixAxis = y-axis !
			--- MatrixContentCell ---
				matrixCellType = content-cell !
			{
				Snippet CssClass --- MatrixContentCellItem ---
					column-name = comp_P1b_N
					matrixCellItemType = computed !
					format = percent
					id = P1b_N
					aggregationItems = "a4119,Z7b6_,P_9m6"
					column-computation = compute-percentage
					column-computation-parameters = currency
			}
			--- MatrixCell ---
				matrixCellType = last-cell !
			{
				--- MatrixCellItem ---
					column-name = comp_P_9m6
					matrixCellItemType = computed !
					id = P_9m6 !
			}
			--- MatrixCell ---
				matrixCellType = last-row !
			{
				--- MatrixCellItem ---
					column-name = comp_Z7b6_
					matrixCellItemType = computed !
					id = Z7b6_ !
			}
			--- MatrixCell ---
				matrixCellType = last-column !
			{
				--- MatrixCellItem ---
					column-name = comp_a4119
					matrixCellItemType = computed !
					id = a4119 !
			}
			--- MatrixExtraColumn ---
				matrixCellType = extra-column !
		}
	}
}