# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "SimpleDomain:SimpleClassDS"
	bean-define = DSBean.SimpleDomain.SimpleClassDS
	bean-name = SimpleClassDS
	id = DS3790_bP__a
{
	--- Box ---
		boxType = vertical
	{
		--- Matrix ---
			displayLastRow = false
			id = F_564
		{
			--- MatrixAxis ---
				domainAttribute = asset_class !
				matrixAxis = x-axis !
			--- MatrixAxis ---
				domainAttribute = currency !
				matrixAxis = y-axis !
			--- MatrixContentCell ---
				matrixCellType = content-cell !
			{
				--- MatrixContentCellItem ---
					domainAttribute = mkt_val !
					matrixCellItemType = domain !
					id = KB22a
					aggregationItems = "Gxm_6,UsVx6,h_neC"
			}
			--- MatrixCell ---
				matrixCellType = last-cell !
			{
				--- MatrixCellItem ---
					domainAttribute = mkt_val !
					matrixCellItemType = domain !
					id = h_neC
			}
			--- MatrixCell ---
				matrixCellType = last-row !
			{
				--- MatrixCellItem ---
					domainAttribute = mkt_val !
					matrixCellItemType = domain !
					id = UsVx6
			}
			--- MatrixCell ---
				matrixCellType = last-column !
			{
				--- MatrixCellItem ---
					domainAttribute = mkt_val !
					matrixCellItemType = domain !
					id = Gxm_6
			}
			--- MatrixExtraColumn ---
				matrixCellType = extra-column !
			{
				--- MatrixExtraColumnItem ---
					labels en = TEST
					toolTips en = TESTTEST
					domainAttribute = keep !
					matrixCellItemType = domain !
					horizontalAlignment = trail
					verticalAlignment = lead
					id = c__o8
					tid = 268108838557135
			}
		}
	}
}