# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "SimpleDomain:SimpleClassDS"
	bean-define = DSBean.SimpleDomain.SimpleClassDS
	bean-name = SimpleClassDS
	id = MatrixGenerationTest_K__WG
{
	--- Box ---
		boxType = vertical
	{
		--- Matrix ---
			id = g_lp_
			matrix-model-reference = DSBean.SimpleDomain.SimpleClassDS
		{
			--- MatrixAxis ---
				domainAttribute = asset_class !
				matrixAxis = x-axis !
			--- MatrixAxis ---
				domainAttribute = currency !
				matrixAxis = y-axis !
			--- MatrixContentCell ---
				matrixCellType = content-cell !
			{
				Snippet CssClass
				specificClass = test
				{
					Snippet ConditionalCssClass
					name = test
					condition = "if(1>0)"
					result = "tab AM"
				}
				--- Box ---
				{
					--- MatrixContentCellItem ---
						domainAttribute = mkt_val !
						matrixCellItemType = domain !
						id = hBc_f
						aggregationItems = ",,"
					--- Box ---
						boxType = vertical
					{
						--- MatrixContentCellItem ---
							column-name = comp_MMd_4
							matrixCellItemType = computed !
							format = percent
							id = MMd_4
							aggregationItems = "eQ_8m,G8_g_,j__2Y"
							column-computation = compute-percentage
							column-computation-parameters = mkt_val
						--- MatrixContentCellItem ---
							domainAttribute = my_return !
							matrixCellItemType = domain !
							id = C49S_
							aggregationItems = "Rf_q3,QOt_Z,Dyn7_"
					}
					--- Box ---
						boxType = vertical
					{
						--- MatrixContentCellItem ---
							matrixCellItemType = computed !
							id = MMd_4
							aggregationItems = "eQ_8m,G8_g_,j__2Y"
							column-computation = compute-percentage
							column-computation-parameters = mkt_val
						--- MatrixContentCellItem ---
							domainAttribute = my_return !
							matrixCellItemType = domain !
							id = C49S_
							aggregationItems = "Rf_q3,QOt_Z,Dyn7_"
					}
				}
			}
			--- MatrixCell ---
				matrixCellType = last-cell !
			{
				--- MatrixCellItem ---
					domainAttribute = mkt_val !
					matrixCellItemType = domain !
					id = B1_CV !
				--- MatrixCellItem ---
					column-name = comp_j__2Y
					matrixCellItemType = computed !
					id = j__2Y !
				--- MatrixCellItem ---
					domainAttribute = my_return !
					matrixCellItemType = domain !
					id = Dyn7_ !
			}
			--- MatrixCell ---
				matrixCellType = last-row !
			{
				--- MatrixCellItem ---
					domainAttribute = mkt_val !
					matrixCellItemType = domain !
					id = c__52 !
				--- MatrixCellItem ---
					column-name = comp_G8_g_
					matrixCellItemType = computed !
					id = G8_g_ !
				--- MatrixCellItem ---
					domainAttribute = my_return !
					matrixCellItemType = domain !
					id = QOt_Z !
			}
			--- MatrixCell ---
				matrixCellType = last-column !
			{
				--- MatrixCellItem ---
					domainAttribute = mkt_val !
					matrixCellItemType = domain !
					id = U0_1j !
				--- MatrixCellItem ---
					column-name = comp_eQ_8m
					matrixCellItemType = computed !
					id = eQ_8m !
				--- MatrixCellItem ---
					domainAttribute = my_return !
					matrixCellItemType = domain !
					id = Rf_q3 !
			}
			--- MatrixExtraColumn ---
				matrixCellType = extra-column !
			{
				--- MatrixExtraColumnItem ---
					labels en = "My Return"
					displayInLastRow = true
					domainAttribute = my_return !
					matrixCellItemType = domain !
					id = CkJ_6
					tid = 959190827087241
				--- MatrixExtraColumnItem ---
					domainAttribute = mkt_val !
					matrixCellItemType = domain !
					id = YA3sX
			}
		}
	}
}