# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "SimpleDomain:SimpleClassDS"
	bean-define = DSBean.SimpleDomain.SimpleClassDS
	bean-name = SimpleClassDS
	id = MyModule_rZ_DO
{
	--- Box ---
		boxType = vertical
	{
		--- Matrix ---
			id = Z5_kW
		{
			--- MatrixAxis ---
				domainAttribute = asset_class !
				group-sorting-column-name = asset_rank
				group-sorting-direction = descending
				matrixAxis = x-axis !
			--- MatrixAxis ---
				domainAttribute = currency !
				matrixAxis = y-axis !
			--- MatrixContentCell ---
				matrixCellType = content-cell !
			{
				Snippet CssClass --- MatrixContentCellItem ---
					domainAttribute = mkt_val !
					matrixCellItemType = domain !
					id = o____
					aggregationItems = "QPu__,c_M_w,Ju__q"
				--- MatrixContentCellItem ---
					aggregationType = max
					column-name = comp_B9_16
					matrixCellItemType = computed !
					format = amount
					id = B9_16
					aggregationItems = "Dw10_,GB_4_,er_7_"
					column-computation = make-amount
					column-computation-parameters = "mkt_val,currency"
			}
			--- MatrixCell ---
				matrixCellType = last-cell !
			{
				--- MatrixCellItem ---
					domainAttribute = mkt_val !
					matrixCellItemType = domain !
					id = Ju__q
				--- MatrixCellItem ---
					column-name = comp_er_7_
					matrixCellItemType = computed !
					id = er_7_
			}
			--- MatrixCell ---
				matrixCellType = last-row !
			{
				--- MatrixCellItem ---
					domainAttribute = mkt_val !
					matrixCellItemType = domain !
					id = c_M_w
				--- MatrixCellItem ---
					column-name = comp_GB_4_
					matrixCellItemType = computed !
					id = GB_4_
			}
			--- MatrixCell ---
				matrixCellType = last-column !
			{
				--- MatrixCellItem ---
					domainAttribute = mkt_val !
					matrixCellItemType = domain !
					id = QPu__
				--- MatrixCellItem ---
					column-name = comp_Dw10_
					matrixCellItemType = computed !
					id = Dw10_
			}
			--- MatrixExtraColumn ---
				matrixCellType = extra-column !
		}
	}
}