# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "SimpleDomain:SimpleClassDS"
	bean-define = DSBean.SimpleDomain.SimpleClassDS
	bean-name = SimpleClassDS
	id = MatrixMakeAmountComp_v_e_D
{
	--- Box ---
		boxType = vertical
	{
		--- Matrix ---
			id = Jo_A_
			matrix-model-reference = DSBean.SimpleDomain.SimpleClassDS
		{
			--- MatrixAxis ---
				domainAttribute = currency !
				matrixAxis = x-axis !
			--- MatrixAxis ---
				domainAttribute = asset_class !
				matrixAxis = y-axis !
			--- MatrixContentCell ---
				matrixCellType = content-cell !
			{
				Snippet CssClass --- MatrixContentCellItem ---
					toolTips en = "tooltip for first computation item"
					column-name = comp_mnN__
					matrixCellItemType = computed !
					format = amount
					id = mnN__
					aggregationItems = "g7nyM,z_eX_,r_yRk"
					column-computation = make-amount
					column-computation-parameters = "mkt_val,currency"
					tid = 9616111356052
			}
			--- MatrixCell ---
				matrixCellType = last-cell !
			{
				--- MatrixCellItem ---
					toolTips en = "last cell item tooltip"
					column-name = comp_r_yRk
					matrixCellItemType = computed !
					id = r_yRk !
					tid = 15400324438161
			}
			--- MatrixCell ---
				matrixCellType = last-row !
			{
				--- MatrixCellItem ---
					toolTips en = "last row item tooltip"
					column-name = comp_z_eX_
					matrixCellItemType = computed !
					id = z_eX_ !
					tid = 15392804151365
			}
			--- MatrixCell ---
				matrixCellType = last-column !
			{
				--- MatrixCellItem ---
					toolTips en = "last column item tooltip"
					column-name = comp_g7nyM
					matrixCellItemType = computed !
					id = g7nyM !
					tid = 15422412254071
			}
			--- MatrixExtraColumn ---
				matrixCellType = extra-column !
		}
	}
}