# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	containment = container
	domainEntity = "DS3173:DefaultDS"
	bean-define = DSBean.DS3173.DefaultDS
	bean-name = DefaultDS
	id = DS3811_Table_sBe_8
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			id = s_Lm8
			table-column-count = 1 !
			table-columns-width = 100 !
		{
			--- TableColumn ---
				column-name = AmountDecimal !
				column-type = domain !
				domainAttribute = AmountDecimal !
				type = text
				id = AmountDecimal
				table-column-width = 100
			{
				--- TableColumnItem ---
					item-column = AmountDecimal
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = AmountDecimal
				sort-direction = descending
				sort-rank = 1
			--- TableKeepFilter ---
				keep-filter-column-name = AmountDecimal
				keep-filter-operand = 10000
		}
	}
}