# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	containment = container
	domainEntity = "DS3173:DefaultDS"
	bean-define = DSBean.DS3173.DefaultDS
	bean-name = DefaultDS
	id = DS3811_q2__1
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			hide-empty-tabs = true
			tabs-filtered-attribute = AmountDecimal
			id = AmountDecimal
			indexOfSelectedChild = 1
		{
			--- Tab ---
				labels en = first
				id = tab_Nl_Sl
				isWidgetVisible = false
				tid = 515047065285671
			--- Tab ---
				labels en = second
				hide-empty-tab = true
				tab-filter = 10000
				id = tab_O8_1a
				isWidgetSelected = true
				tid = 515051725092155
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/DS3811_Table.module
			}
		}
	}
}