# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "SimpleDomain:SimpleClassDS"
	bean-define = DSBean.SimpleDomain.SimpleClassDS
	bean-name = SimpleClassDS
	id = DS3804_Nkk_u
{
	--- Box ---
		boxType = vertical
	{
		--- Matrix ---
			id = J8T2_
			documentation = test
		{
			--- MatrixAxis ---
				domainAttribute = asset_class !
				matrixAxis = x-axis !
			--- MatrixAxis ---
				domainAttribute = currency !
				matrixAxis = y-axis !
			--- MatrixContentCell ---
				matrixCellType = content-cell !
			{
				--- MatrixContentCellItem ---
					domainAttribute = mkt_val !
					matrixCellItemType = domain !
					enabled = conditional
					enabledIsBasedOn = instrument
					id = r5__6
					documentation = test
					aggregationItems = "tI3yd,ut3__,BY__7"
					enabledIsBasedOn-advanced = test
					enabledIsBasedOn-simplified = "SimpleDomain:SimpleClassDS#instrument"
			}
			--- MatrixCell ---
				matrixCellType = last-cell !
			{
				--- MatrixCellItem ---
					domainAttribute = mkt_val !
					matrixCellItemType = domain !
					id = BY__7
			}
			--- MatrixCell ---
				matrixCellType = last-row !
			{
				--- MatrixCellItem ---
					domainAttribute = mkt_val !
					matrixCellItemType = domain !
					id = ut3__
			}
			--- MatrixCell ---
				matrixCellType = last-column !
			{
				--- MatrixCellItem ---
					domainAttribute = mkt_val !
					matrixCellItemType = domain !
					id = tI3yd
			}
			--- MatrixExtraColumn ---
				matrixCellType = extra-column !
		}
	}
}