# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "SimpleDomain:SimpleClassDS"
	bean-define = DSBean.SimpleDomain.SimpleClassDS
	bean-name = SimpleClassDS
	id = MatrixMakeAmountComp_v_e_D
{
	--- Box ---
		boxType = vertical
	{
		--- Matrix ---
			id = Jo_A_
			matrix-model-reference = DSBean.SimpleDomain.SimpleClassDS
		{
			--- MatrixAxis ---
				domainAttribute = currency !
				matrixAxis = x-axis !
			--- MatrixAxis ---
				domainAttribute = asset_class !
				matrixAxis = y-axis !
			--- MatrixContentCell ---
				matrixCellType = content-cell !
			{
				Snippet CssClass --- MatrixContentCellItem ---
					toolTips en = "tooltip for first computation item"
					column-name = comp_mnN__
					matrixCellItemType = computed !
					id = mnN__
					aggregationItems = "g7nyM,z_eX_,r_yRk"
					column-computation = make-amount
					column-computation-parameters = "mkt_val,currency"
					tid = 9616111356052
				--- MatrixContentCellItem ---
					column-name = comp_j__31
					matrixCellItemType = computed !
					format = percent
					id = j__31
					aggregationItems = "e_48N,rpR9w,c7gs4"
					column-computation = compute-percentage
					column-computation-parameters = my_return
			}
			--- MatrixCell ---
				matrixCellType = last-cell !
			{
				--- MatrixCellItem ---
					column-name = comp_r_yRk
					matrixCellItemType = computed !
					id = r_yRk !
				--- MatrixCellItem ---
					column-name = comp_c7gs4
					matrixCellItemType = computed !
					id = c7gs4 !
			}
			--- MatrixCell ---
				matrixCellType = last-row !
			{
				--- MatrixCellItem ---
					column-name = comp_z_eX_
					matrixCellItemType = computed !
					id = z_eX_ !
				--- MatrixCellItem ---
					column-name = comp_rpR9w
					matrixCellItemType = computed !
					id = rpR9w !
			}
			--- MatrixCell ---
				matrixCellType = last-column !
			{
				--- MatrixCellItem ---
					column-name = comp_g7nyM
					matrixCellItemType = computed !
					id = g7nyM !
				--- MatrixCellItem ---
					column-name = comp_e_48N
					matrixCellItemType = computed !
					id = e_48N !
			}
			--- MatrixExtraColumn ---
				matrixCellType = extra-column !
		}
	}
}