# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "SimpleDomain:SimpleClassDS"
	bean-define = DSBean.SimpleDomain.SimpleClassDS
	bean-name = SimpleClassDS
	id = DS3922_U6Rb_
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			table-rendering-mode = summary-delegated
			id = R685_
			table-column-count = 3 !
			table-columns-width = "33,33,33" !
		{
			--- TableColumn ---
				column-display-grouping = true
				column-name = placeholder_LJh9l
				column-type = placeholder !
				type = text
				column-sortable = false !
				id = LJh9l
				table-column-width = 33
			{
				--- TableGroup ---
					aggregateData = false
					group-column-name = currency
					group-dynamic-column = true
					group-sorting-column-name = asset_rank
					group-sorting-direction = ascending
					group-rank = 3
				--- TableGroup ---
					group-column-name = asset_rank
					group-sorting-column-name = asset_class
					group-sorting-direction = ascending
					group-rank = 2
			}
			--- TableColumn ---
				column-name = mkt_val !
				column-type = domain !
				domainAttribute = mkt_val !
				type = text
				id = mkt_val
				table-column-width = 33
			{
				--- TableColumnItem ---
					item-column = mkt_val
					previewValue = value
			}
			--- TableColumn ---
				column-name = dynamic_qR__3
				column-type = dynamic !
				type = text
				id = qR__3
				table-column-width = 33
			{
				--- TableColumnItem ---
					item-column = dynamic_qR__3
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = asset_rank
				sort-rank = 1
			--- TableAggregate ---
				aggregate-column-name = dynamic_qR__3
				aggregate-computation = max
			--- TableAggregate ---
				aggregate-column-name = mkt_val
				aggregate-computation = max
		}
	}
}