# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "SimpleDomain:SimpleClassDS"
	bean-define = DSBean.SimpleDomain.SimpleClassDS
	bean-name = SimpleClassDS
	id = DS3905_L5__5
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			table-rendering-mode = summary-delegated
			id = O_i_E
			table-column-count = 3 !
			table-columns-width = "33,33,33" !
		{
			--- TableColumn ---
				column-display-grouping = true
				column-name = placeholder_o_t__
				column-type = placeholder !
				type = text
				column-sortable = false !
				id = o_t__
				table-column-width = 33
			{
				--- TableGroup ---
					aggregateData = false
					group-column-name = instrument
					group-dynamic-column = true
					group-sorting-column-name = mkt_val
					group-sorting-direction = ascending
					group-rank = 3
				--- TableGroup ---
					group-column-name = currency
					group-sorting-column-name = instrument
					group-sorting-direction = ascending
					group-rank = 2
			}
			--- TableColumn ---
				column-name = mkt_val !
				column-type = domain !
				domainAttribute = mkt_val !
				type = text
				id = mkt_val
				table-column-width = 33
			{
				--- TableColumnItem ---
					item-column = mkt_val
					previewValue = value
			}
			--- TableColumn ---
				column-name = dynamic_sj_E_
				column-type = dynamic !
				type = text
				id = sj_E_
				column-computation = make-amount
				table-column-width = 33
			{
				--- TableColumnItem ---
					item-column = mkt_val
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = mkt_val
				sort-rank = 1
			--- TableAggregate ---
				aggregate-column-name = mkt_val
				aggregate-computation = max
			--- TableAggregate ---
				aggregate-column-name = dynamic_sj_E_
				aggregate-computation = sum
		}
	}
}