# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "SimpleDomain:SimpleClassDS"
	bean-define = DSBean.SimpleDomain.SimpleClassDS
	bean-name = SimpleClassDS
	id = DS3931_N99S8
{
	--- Box ---
		boxType = vertical
	{
		--- Matrix ---
			id = x56v_
		{
			--- MatrixAxis ---
				domainAttribute = asset_class !
				matrixAxis = x-axis !
			--- MatrixAxis ---
				domainAttribute = currency !
				matrixAxis = y-axis !
			--- MatrixContentCell ---
				matrixCellType = content-cell !
			{
				--- MatrixContentCellItem ---
					domainAttribute = mkt_val !
					matrixCellItemType = domain !
					id = Fr709
					aggregationItems = "n_zy1,A0_23,C_b1c"
			}
			--- MatrixCell ---
				matrixCellType = last-cell !
			{
				--- MatrixCellItem ---
					domainAttribute = mkt_val !
					matrixCellItemType = domain !
					id = C_b1c
				{
					Snippet CssClass
					cssClassType = specific
					specificClass = red
				}
			}
			--- MatrixCell ---
				matrixCellType = last-row !
			{
				--- MatrixCellItem ---
					domainAttribute = mkt_val !
					matrixCellItemType = domain !
					id = A0_23
				{
					Snippet CssClass
					cssClassType = specific
					specificClass = green
				}
			}
			--- MatrixCell ---
				matrixCellType = last-column !
			{
				--- MatrixCellItem ---
					domainAttribute = mkt_val !
					matrixCellItemType = domain !
					id = n_zy1
				{
					Snippet CssClass
					specificClass = yellow
				}
			}
			--- MatrixExtraColumn ---
				matrixCellType = extra-column !
		}
	}
}