# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "SimpleDomain:SimpleClassDS"
	bean-define = DSBean.SimpleDomain.SimpleClassDS
	bean-name = SimpleClassDS
	id = DS3911_D_0r3
{
	--- Box ---
		boxType = vertical
	{
		--- Matrix ---
			id = f50_1
		{
			--- MatrixAxis ---
				domainAttribute = asset_class !
				matrixAxis = x-axis !
			--- MatrixAxis ---
				domainAttribute = currency !
				matrixAxis = y-axis !
			--- MatrixContentCell ---
				matrixCellType = content-cell !
			{
				Snippet CssClass --- Box ---
				{
					--- Conditional ---
						indexOfSelectedChild = 1
					{
						--- ConditionalBody ---
							javaCode = true
							technicalName = Default
							boxType = vertical
							isWidgetVisible = false
						--- ConditionalBody ---
							javaCode = "\"true\".equals(<udp:item column=\"ONE_PTF_OCCUR\"/>)"
							technicalName = Condition
							boxType = vertical
							isWidgetSelected = true
						{
							--- MatrixContentCellItem ---
								column-name = comp_W_J__
								matrixCellItemType = computed !
								format = percentTA
								id = W_J__
								column-computation = compute-percentage
								column-computation-parameters = my_return
						}
					}
				}
			}
			--- MatrixCell ---
				matrixCellType = last-cell !
			--- MatrixCell ---
				matrixCellType = last-row !
			--- MatrixCell ---
				matrixCellType = last-column !
			--- MatrixExtraColumn ---
				matrixCellType = extra-column !
		}
	}
}