# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "DS3458Domain:DS3458Dataset"
	bean-define = DSBean.DS3458Domain.DS3458Dataset
	bean-name = DS3458Dataset
	id = DS3917_pbJvq
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			table-rendering-mode = summary-delegated
			id = x_Bn4
			table-column-count = 5 !
			table-columns-width = "20,20,20,20,20" !
		{
			--- TableColumn ---
				column-display-grouping = true
				column-name = placeholder_T__8q
				column-type = placeholder !
				type = text
				column-sortable = false !
				id = K1s9L
				table-column-width = 20
			{
				--- TableGroup ---
					group-column-name = PTF_HIER_STR
					group-sorting-column-name = PTF_HIER_STR
					group-sorting-direction = ascending
					group-rank = 1
				--- TableGroup ---
					group-column-name = CURR_CLASS_CODE
					group-dynamic-column = true
					group-sorting-column-name = CURR_CLASS_CODE
					group-sorting-direction = ascending
					group-rank = 2
			}
			--- TableColumn ---
				column-name = MarketValue
				type = decimal
				id = Z_3D_
				column-computation = same
				column-computation-parameters = MKT_VAL
				table-column-width = 20
			{
				--- TableColumnItem ---
					item-column = MKT_VAL
					previewValue = value
			}
			--- TableColumn ---
				column-name = MakeAmount
				type = amount
				id = CJ_9_
				column-computation = make-amount
				column-computation-parameters = "MKT_VAL,REF_CURRENCY"
				table-column-width = 20
			{
				--- TableColumnItem ---
					item-column = MakeAmount
					previewValue = value
			}
			--- TableColumn ---
				column-name = dynamic_currency
				column-type = dynamic !
				type = text
				id = I___7
				table-column-width = 20
			{
				--- TableColumnItem ---
					item-column = MarketValue
					previewValue = value
				--- Spacer ---
					height = 4
					width = 10
				--- TableColumnItem ---
					item-column = MakeAmount
					previewValue = value
			}
			--- TableColumn ---
				column-name = dynamic_s_CBO
				column-type = dynamic !
				type = text
				id = s_CBO
				table-column-width = 20
			{
				--- TableColumnItem ---
					item-column = dynamic_s_CBO
					previewValue = value
			}
			--- TableAggregate ---
				aggregate-column-name = MKT_VAL
				aggregate-computation = sum
				aggregate-group-names = PTF_HIER_STR
			--- TableAggregate ---
				aggregate-column-name = MarketValue
				aggregate-computation = sum
				aggregate-group-names = PTF_HIER_STR
			--- TableAggregate ---
				aggregate-column-name = REF_CURRENCY
				aggregate-computation = max
				aggregate-group-names = PTF_HIER_STR
			--- TableAggregate ---
				aggregate-column-name = CURR_CLASS_CODE
				aggregate-computation = max
				aggregate-group-names = PTF_HIER_STR
			--- TableAggregate ---
				aggregate-column-name = MakeAmount
				aggregate-computation = sum
				aggregate-group-names = PTF_HIER_STR
			--- TableAggregate ---
				aggregate-column-name = dynamic_currency
				aggregate-computation = max
				aggregate-group-names = PTF_HIER_STR
			--- TableAggregate ---
				aggregate-column-name = PTF_HIER_STR
				aggregate-computation = sum
		}
	}
}