# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "DS4059:DS4059DS"
	bean-define = DSBean.DS4059.DS4059DS
	bean-name = DS4059DS
	id = DS4059_b_Dc_
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			table-rendering-mode = summary-delegated
			id = O_f_I
			table-column-count = 3 !
			table-columns-width = "33,33,33" !
		{
			--- TableColumn ---
				column-display-grouping = true
				column-name = placeholder_fZ_2_
				column-type = placeholder !
				type = text
				column-sortable = false !
				id = fZ_2_
				table-column-width = 33
			{
				--- TableGroup ---
					group-column-name = Portfolio
					group-sorting-column-name = Portfolio
					group-sorting-direction = ascending
					hierarchy = true
					group-rank = 1
				--- TableGroup ---
					group-column-name = AssetType
					group-dynamic-column = true
					group-rank = 2
			}
			--- TableColumn ---
				column-name = AssetType
				type = text
				id = x5_r3
				column-computation = same
				column-computation-parameters = AmountDecimal
				table-column-width = 33
			{
				--- TableColumnItem ---
					item-column = comp_x5_r3
					previewValue = value
			}
			--- TableColumn ---
				column-name = dynamic_pM9T1
				column-type = dynamic !
				type = text
				id = pM9T1
				table-column-width = 33
			{
				--- TableColumnItem ---
					item-column = AssetType
					previewValue = value
				--- Spacer ---
					height = 4
					width = 4
				--- TableColumnItem ---
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = comp_x5_r3
				sort-rank = 1
			--- TableAggregate ---
				aggregate-column-name = comp_x5_r3
				aggregate-computation = sum
			--- TableAggregate ---
				aggregate-column-name = AmountDecimal
				aggregate-computation = sum
			--- TableAggregate ---
				aggregate-column-name = dynamic_pM9T1
				aggregate-computation = max
				aggregate-group-names = Portfolio
		}
	}
}