# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "DS4035:DS4035DS"
	bean-define = DSBean.DS4035.DS4035DS
	bean-name = DS4035DS
	id = DS4035_S3_V_
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			id = k6JZ5
			table-column-count = 3 !
			table-columns-width = "33,33,33" !
		{
			--- TableColumn ---
				column-name = placeholder_g_a20
				column-type = placeholder !
				type = text
				column-sortable = false !
				id = g_a20
				table-column-width = 33
			--- TableColumn ---
				column-name = TEST_DURATION !
				column-type = domain !
				domainAttribute = TEST_DURATION !
				type = text
				id = TEST_DURATION
				table-column-width = 33
			{
				--- TableColumnItem ---
					item-column = TEST_DURATION
					previewValue = value
			}
			--- TableColumn ---
				column-name = MKT_VAL !
				column-type = domain !
				domainAttribute = MKT_VAL !
				format = decimal
				type = text
				id = MKT_VAL
				table-column-width = 33
			{
				--- TableColumnItem ---
					item-column = MKT_VAL
					format = decimal
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = MKT_VAL
				sort-rank = 1
		}
	}
}