# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "DS4204:DS4204Dataset"
	bean-define = DSBean.DS4204.DS4204Dataset
	bean-name = DS4204Dataset
	id = DS4204_ModifiableIdFormat_D_ou_
{
	--- Box ---
		boxType = vertical
	{
		--- CheckBox ---
			domainAttribute = DS4204_Checkbox
			horizontalTextPosition = trail
			bean-property = DS4204_Checkbox
			id = DS4204_Checkbox
		--- List ---
			domainAttribute = DS4204_List
			size = 5
			bean-property = DS4204_List
			id = DS4204_List
		--- ComboBox ---
			domainAttribute = DS4204_ComboBox
			bean-property = DS4204_ComboBox
			id = DS4204_ComboBox
		--- RadioButton ---
			id = btn_R_8f_
	}
}