# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "DS4204:DS4204Dataset"
	bean-define = DSBean.DS4204.DS4204Dataset
	bean-name = DS4204Dataset
	id = DS4204_EditableIdFormat_Z_Xc_
{
	--- Box ---
		boxType = vertical
	{
		--- AutoComplete ---
			domainAttribute = DS4204_AutoComplete
			columns = 30
			bean-property = DS4204_AutoComplete
			id = DS4204_AutoComplete
		--- CaldateField ---
			domainAttribute = DS4204_CalDate
			bean-property = DS4204_CalDate
			id = DS4204_CalDate
		--- FileChooser ---
			domainAttribute = DS4204_FileChooser
			columns = 30
			bean-property = DS4204_FileChooser
			id = DS4204_FileChooser
		--- PasswordField ---
			domainAttribute = DS4204_PasswordField
			columns = 30
			previewValue = "****************"
			bean-property = DS4204_PasswordField
			id = DS4204_PasswordField
		--- SearchField ---
			domainAttribute = DS4204_SearchArea
			searchType = searchOnly
			columns = 30
			bean-property = DS4204_SearchArea
			id = DS4204_SearchArea
		--- TextArea ---
			domainAttribute = DS4204_TextArea
			columns = 30
			rows = 3
			bean-property = DS4204_TextArea
			id = DS4204_TextArea
		--- TextField ---
			domainAttribute = DS4204_TextField
			columns = 30
			bean-property = DS4204_TextField
			id = DS4204_TextField
	}
}