# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "DS3813:DS"
	bean-define = DSBean.DS3813.DS
	bean-name = DS
	id = DS4453_s4s__
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			id = fZ_0b
			table-column-count = 3 !
			table-columns-width = "33,33,33" !
		{
			--- TableColumn ---
				column-display-grouping = true
				column-name = placeholder_K_6_f
				column-type = placeholder !
				type = text
				column-sortable = false !
				id = U4_2b
				table-column-width = 33
			{
				--- TableGroup ---
					aggregateData = false
					group-column-name = a1
					group-sorting-column-name = a1
					group-sorting-direction = descending
					group-rank = 1
			}
			--- TableColumn ---
				column-name = placeholder_z12_u
				column-type = placeholder !
				type = text
				column-sortable = false !
				id = z12_u
				table-column-width = 33
			{
				--- Icon ---
					horizontalAlignment = column
					icon = add_red
					id = zU7eE
			}
			--- TableColumn ---
				column-name = a2 !
				column-type = domain !
				domainAttribute = a2 !
				type = text
				id = a2
				table-column-width = 33
			{
				--- TableColumnItem ---
					item-column = a2
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = a1
				sort-rank = 1
		}
	}
}