# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "SimpleDomain:SimpleClassDS"
	bean-define = DSBean.SimpleDomain.SimpleClassDS
	bean-name = SimpleClassDS
	id = cDS4422_upLad
{
	--- Box ---
		boxType = vertical
	{
		--- Matrix ---
			id = DM5__
		{
			--- MatrixAxis ---
				domainAttribute = currency !
				matrixAxis = x-axis !
			--- MatrixAxis ---
				domainAttribute = asset_class !
				matrixAxis = y-axis !
			--- MatrixContentCell ---
				matrixCellType = content-cell !
			{
				Snippet CssClass --- MatrixContentCellItem ---
					aggregationType = weighted-mean
					domainAttribute = asset_rank !
					matrixCellItemType = domain !
					matrixMeanWeight = mkt_val
					id = k0F7_
					aggregationItems = "Y0_a6,qS19_,p_25Q"
			}
			--- MatrixCell ---
				matrixCellType = last-cell !
			{
				--- MatrixCellItem ---
					domainAttribute = asset_rank !
					matrixCellItemType = domain !
					id = p_25Q
			}
			--- MatrixCell ---
				matrixCellType = last-row !
			{
				--- MatrixCellItem ---
					domainAttribute = asset_rank !
					matrixCellItemType = domain !
					id = qS19_
			}
			--- MatrixCell ---
				matrixCellType = last-column !
			{
				--- MatrixCellItem ---
					domainAttribute = asset_rank !
					matrixCellItemType = domain !
					id = Y0_a6
			}
			--- MatrixExtraColumn ---
				matrixCellType = extra-column !
		}
	}
}