# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "DS3813:DS"
	bean-define = DSBean.DS3813.DS
	bean-name = DS
	id = DS4467_DpRYM
{
	--- Box ---
		boxType = vertical
	{
		--- SearchField ---
			domainAttribute = a1
			columns = 30
			bean-property = a1
			id = a1
			nb-chars = 2
			outputDesign = "" !
			resource:///Default/module/DS4467Auto.module
		{
			Event Search (submit)
			{
				method = post
				call-URI = "<pageflow:continuation/>"
				target = self
				only-changed = false
				prevalidate = false
				modal = false
				widget-group-ref = form
				param = "flow-action=search"
				Query.alwaysDisplayResult = true ud
				Query.exactMatching = false ud
			}
		}
	}
}