# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "DS3813:DS"
	bean-define = DSBean.DS3813.DS
	bean-name = DS
	id = DS4438_NJho3
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			table-rendering-mode = summary-delegated
			id = jJ_K9
			table-column-count = 2 !
			table-columns-width = "50,50" !
		{
			--- TableColumn ---
				column-display-grouping = true
				column-name = placeholder_wZkD0
				column-type = placeholder !
				type = text
				column-sortable = false !
				id = wZkD0
				table-column-width = 50
			{
				--- TableGroup ---
					aggregateData = false
					group-column-name = a1
					group-sorting-column-name = a2
					group-sorting-direction = ascending
					group-rank = 1
			}
			--- TableColumn ---
				column-name = a2 !
				column-type = domain !
				domainAttribute = a2 !
				type = text
				id = a2
				table-column-width = 50
			{
				--- TableColumnItem ---
					item-column = a2
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = a3
				sort-rank = 1
			--- TableAggregate ---
				aggregate-column-name = a2
				aggregate-computation = weighted-mean
				aggregate-other-column-name = a2
		}
	}
}