# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "PrecisionAndScale:PsDataSet"
	bean-define = DSBean.PrecisionAndScale.PsDataSet
	bean-name = PsDataSet
	id = DS4558PrecisionScale_W_v55
{
	--- Box ---
		boxType = vertical
	{
		--- LabelDomain ---
			domainAttribute = doubAttr !
			for = doubAttr
			horizontalAlignment = "${corporatehalign}"
			id = doubAttr
		--- TextField ---
			domainAttribute = doubAttr !
			columns = 30
			horizontalAlignment = "${corporatehalign}"
			precision = 2
			scale = 3
			type = decimal
			bean-property = doubAttr
			id = doubAttr
	}
}