# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "DS3813:DS"
	bean-define = DSBean.DS3813.DS
	bean-name = DS
	id = DS3113_sj0_f
	documentation = "Test the reverse flag is generated on grouping with a descending sorting."
	tid = 331046569761550
{
	--- Box ---
		boxType = vertical
	{
		--- Box ---
			boxType = vertical
			tid = 330833067511033
		{
			--- TableTree ---
				table-rendering-mode = summary-delegated
				id = q_398
				table-column-count = 2 !
				table-columns-width = "50,50" !
			{
				--- TableColumn ---
					column-display-grouping = true
					column-name = placeholder_K_6_f
					column-type = placeholder !
					type = text
					column-sortable = false !
					id = E7u6k
					table-column-width = 50
				{
					--- TableGroup ---
						aggregateData = false
						group-column-name = a1
						group-sorting-column-name = a1
						group-sorting-direction = descending
						group-rank = 1
				}
				--- TableColumn ---
					column-name = a2 !
					column-type = domain !
					domainAttribute = a2 !
					type = text
					id = BmpA_
					table-column-width = 50
				{
					--- TableColumnItem ---
						item-column = a2
						previewValue = value
					--- CheckBox ---
						labels en = "<rt><s ts=\"b\">English Rich Text Check Box</s></rt>", fr = "<rt><s ts=\"i\">French Rich Text Check Box</s></rt>", de = "<rt><s ts=\"u\">German Rich Text Check Box</s></rt>"
						column-checkbox-action = ""
						domainAttribute = a1
						horizontalTextPosition = trail
						bean-property = a1
						id = a1
						tid = 36390171729148
				}
				--- TableSort ---
					sort-column-name = a1
					sort-rank = 1
				--- TableAggregate ---
					aggregate-column-name = a2
					aggregate-computation = sum
			}
		}
		--- Box ---
			boxType = vertical
			tid = 330853356960919
		{
			--- TableTree ---
				id = E7_4_
				table-column-count = 2 !
				table-columns-width = "50,50" !
			{
				--- TableColumn ---
					column-display-grouping = true
					column-name = placeholder_K_6_f
					column-type = placeholder !
					type = text
					column-sortable = false !
					id = K_6_f
					table-column-width = 50
				{
					--- TableGroup ---
						aggregateData = false
						group-column-name = a1
						group-sorting-column-name = a1
						group-sorting-direction = descending
						group-rank = 1
				}
				--- TableColumn ---
					column-name = a2 !
					column-type = domain !
					domainAttribute = a2 !
					type = text
					id = a2
					table-column-width = 50
				{
					--- TableColumnItem ---
						item-column = a2
						previewValue = value
				}
				--- TableSort ---
					sort-column-name = a1
					sort-rank = 1
			}
		}
	}
}