# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "Ds4884:DS4884_DSOrderList"
	bean-define = DSBean.Ds4884.DS4884_DSOrderList
	bean-name = DS4884_DSOrderList
	id = DS4884_TableColumnSearchField_V4zvI
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			table-editable-dataset = "Ds4884:DS4884_DSExtOperation"
			table-format-identifier = id
			table-row-identifier = id
			table-row-permission = permission
			id = f_m9_
			table-column-count = 1 !
			table-columns-width = 100 !
		{
			--- TableColumn ---
				column-name = code !
				column-type = domain !
				domainAttribute = code !
				type = text
				id = code
				table-column-width = 100
			{
				--- TableColumnSearch ---
					item-column = code
					table-column-item-dataset-attribute = instr.code
					previewValue = value
					type = text
					chars = 10
					required = true
					widgetGroup = formSearch
					auto-delay = 700
					nb-chars = 1
					outputDesign = "" !
					resource:///Default/module/DS4467Auto.module
				{
					Event Search (submit)
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = popup
						only-changed = false
						prevalidate = false
						modal = false
						Query.parentWidgetValue1Id = "formSearch.<bean:get-property bean=\"ExtOperationAll\" property=\"id\"/>.instr.code" ud
					}
				}
			}
			--- TableSort ---
				sort-column-name = code
				sort-rank = 1
		}
	}
}