# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "Ds4884:DS4884_DSOrderList"
	bean-define = DSBean.Ds4884.DS4884_DSOrderList
	bean-name = DS4884_DSOrderList
	id = DS4884_TableColumnCombobox_u__6G
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			table-editable-dataset = "Ds4884:DS4884_DSExtOperation"
			table-format-identifier = id
			table-row-identifier = id
			table-row-permission = permission
			id = F621_
			table-column-count = 2 !
			table-columns-width = "50,50" !
		{
			--- TableColumn ---
				column-name = statut !
				column-type = domain !
				domainAttribute = statut !
				type = text
				id = statut
				table-column-width = 50
			{
				--- TableColumnCombobox ---
					item-column = statut
					table-column-item-dataset-attribute = statut2
					previewValue = value
			}
			--- TableColumn ---
				column-name = code !
				column-type = domain !
				domainAttribute = code !
				type = text
				id = code
				table-column-width = 50
			{
				--- TableColumnCombobox ---
					item-column = code
					table-column-item-dataset-attribute = statut2
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = code
				sort-rank = 1
		}
	}
}