# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "Ds4884:DS4884_DSExtOperation"
	bean-define = DSBean.Ds4884.DS4884_DSExtOperation
	bean-name = DS4884_DSExtOperation
	id = DS4884_Z2_55
{
	--- Box ---
		boxType = vertical
	{
		--- TextField ---
			domainAttribute = id
			columns = 30
			bean-property = id
			id = id
		--- CaldateField ---
			domainAttribute = date2
			bean-property = date2
			id = date2
		--- CheckBox ---
			column-checkbox-action = ""
			horizontalTextPosition = trail
			id = btn_xLq95
		--- ComboBox ---
			id = l780_
		--- SearchField ---
			searchType = autoCompleteOnly
			columns = 30
			id = d0_43
	}
}