# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "Ds4884:DS4884_DSOrderList"
	bean-define = DSBean.Ds4884.DS4884_DSOrderList
	bean-name = DS4884_DSOrderList
	id = DS4884_TableColumnCalendar_AmLp_
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			table-editable-dataset = "Ds4884:DS4884_DSExtOperation"
			table-format-identifier = id
			table-row-identifier = id
			table-row-permission = permission
			id = Jz4__
			table-column-count = 1 !
			table-columns-width = 100 !
		{
			--- TableColumn ---
				column-name = code !
				column-type = domain !
				domainAttribute = code !
				type = text
				id = code
				table-column-width = 100
			{
				--- TableColumnCalendar ---
					item-column = code
					table-column-item-dataset-attribute = date2
					format = datetime.date-only
					previewValue = value
					type = date
					editable = false
			}
			--- TableSort ---
				sort-column-name = code
				sort-rank = 1
		}
	}
}