# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "RadioButtonEnum:DS4877"
	bean-define = DSBean.RadioButtonEnum.DS4877
	bean-name = DS4877
	id = DS4877_e8V__
{
	--- Box ---
		boxType = vertical
	{
		--- RadioButton ---
			domainAttribute = newAttribute !
			enumValue = NEW_VALUE !
			horizontalTextPosition = trail
			bean-name = DS4877
			bean-property = newAttribute
			group = newAttribute
			id = btn_D7_YX
	}
}