# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "DS4405:TestDomainDS"
	bean-define = DSBean.DS4405.TestDomainDS
	bean-name = TestDomainDS
	id = DS4925_Z4_89
{
	--- Box ---
		boxType = vertical
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 2
			gridColumnsWidth = "25,25" !
			gridRowCount = 2
		{
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Include ---
					domainAssociation = money
					includeSrc = "" !
					resource:///ds4925/DS4925Search.fragment
			}
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Include ---
					domainAssociation = money
					includeSrc = "" !
					resource:///ds4925/DS4925Text.fragment
			}
		}
	}
}