# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "DS4989:NewDataset"
	bean-define = DSBean.DS4989.NewDataset
	bean-name = NewDataset
	id = DS4989_tk422
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			table-editable-dataset = "DS4989:NewDataset"
			id = F__3H
			table-column-count = 3 !
			table-columns-width = "33,33,33" !
		{
			--- TableColumn ---
				column-name = placeholder_p_D__
				column-type = placeholder !
				type = text
				column-sortable = false !
				id = p_D__
				table-column-width = 33
			--- TableColumn ---
				column-display-grouping = true
				column-name = placeholder_BJ_I_
				column-type = placeholder !
				type = text
				column-sortable = false !
				id = BJ_I_
				table-column-width = 33
			{
				--- TableGroup ---
					group-rank = 1
				--- TableGroup ---
					group-rank = 2
			}
			--- TableColumn ---
				column-name = placeholder_v97vm
				column-type = placeholder !
				type = text
				column-sortable = false !
				id = v97vm
				table-column-width = 33
		}
	}
}