# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "DS4405:MoneyIdentifierDS"
	bean-define = DSBean.DS4405.MoneyIdentifierDS
	bean-name = MoneyIdentifierDS
	id = DS4957_Cpe_s
{
	--- Box ---
		boxType = vertical
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 2
			gridColumnsWidth = "25,25" !
			gridRowCount = 2
		{
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- LabelDomain ---
					domainAttribute = denom !
					for = denom
					horizontalAlignment = "${corporatehalign}"
					id = denom
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- TextField ---
					domainAttribute = denom !
					columns = 30
					horizontalAlignment = "${corporatehalign}"
					type = text
					editable = conditional
					editableIsBasedOn = advanced
					bean-property = denom
					id = denom
					editableIsBasedOn-advanced = "conditionVal=false;\r\nif ((\"true\").equals(<bean:get-property bean=\"DomainContext\" property=\"simulationF\"/>.toString())) {\r\n   conditionVal=true;\r\n  }"
			}
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
		}
	}
}