# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "DS4405:TestDomainDS"
	bean-define = DSBean.DS4405.TestDomainDS
	bean-name = TestDomainDS
	id = DS4949ConditionCheckbox_U_1__
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			id = CK1c6
			table-column-count = 1 !
			table-columns-width = 100 !
		{
			--- TableColumn ---
				column-name = placeholder_rQ4__
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				id = rQ4__
				table-column-width = 100
			{
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = test
						technicalName = Condition
						boxType = vertical
						isWidgetSelected = true
					{
						--- CheckBox ---
							column-checkbox-action = ""
							column-checkbox-identifier = id
							horizontalTextPosition = trail
							id = btn_O0__P
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetVisible = false
				}
			}
			--- TableSort ---
				sort-column-name = id
				sort-rank = 1
		}
	}
}