# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "DS4405:TestDomainDS"
	bean-define = DSBean.DS4405.TestDomainDS
	bean-name = TestDomainDS
	id = DS4949_P__KQ
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			id = E____
			table-column-count = 1 !
			table-columns-width = 100 !
		{
			--- TableColumn ---
				column-name = placeholder_Z_6c_
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				id = Z_6c_
				table-column-width = 100
			{
				--- CheckBox ---
					column-checkbox-action = ""
					horizontalTextPosition = trail
					id = btn_A25_v
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = test
						technicalName = Condition
						boxType = vertical
						isWidgetSelected = true
					{
						--- CheckBox ---
							column-checkbox-action = ""
							horizontalTextPosition = trail
							id = btn_x9M__
						--- Conditional ---
							indexOfSelectedChild = 0
						{
							--- ConditionalBody ---
								javaCode = test
								technicalName = Condition
								boxType = vertical
								isWidgetSelected = true
							{
								--- CheckBox ---
									column-checkbox-action = ""
									horizontalTextPosition = trail
									id = btn_az_qX
							}
							--- ConditionalBody ---
								javaCode = true
								technicalName = Default
								boxType = vertical
								isWidgetVisible = false
						}
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetVisible = false
				}
			}
			--- TableSort ---
				sort-column-name = id
				sort-rank = 1
		}
	}
}