# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "DS5132Domain:DS5132"
	bean-define = DSBean.DS5132Domain.DS5132
	bean-name = DS5132
	id = DS5132_W9Pyr
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			table-page-size = 0
			id = W08_7
			table-column-count = 1 !
			table-columns-width = 100 !
		{
			--- TableColumn ---
				column-name = data !
				column-type = domain !
				domainAttribute = data !
				type = text
				id = data
				table-column-width = 100
			{
				--- TableColumnItem ---
					item-column = data
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = data
				sort-rank = 1
		}
	}
}