# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "Ds4884:DS4884_DSOrderList"
	search = container
	bean-define = DSBean.Ds4884.DS4884_DSOrderList
	bean-name = DS4884_DSOrderList
	id = DS5124_EditableWidgetValidation_Y3IH2
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			table-editable-dataset = "Ds4884:DS4884_DSExtOperation"
			table-row-identifier = id
			table-row-permission = permission
			id = G_H_1
			table-column-count = 1 !
			table-columns-width = 100 !
		{
			--- TableColumn ---
				column-name = code !
				column-type = domain !
				domainAttribute = code !
				type = text
				id = code
				table-column-width = 100
			{
				--- TableColumnText ---
					item-column = code
					previewValue = value
					type = text
			}
			--- TableSort ---
				sort-column-name = code
				sort-rank = 1
		}
	}
}