# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "SimpleDomain:SimpleClassDS"
	bean-define = DSBean.SimpleDomain.SimpleClassDS
	bean-name = SimpleClassDS
	id = DS3804_Nkk_u
{
	--- Box ---
		boxType = vertical
	{
		--- Matrix ---
			id = J8T2_
			documentation = test
		{
			--- MatrixAxis ---
				domainAttribute = asset_class !
				matrixAxis = x-axis !
			--- MatrixAxis ---
				domainAttribute = currency !
				matrixAxis = y-axis !
			--- MatrixContentCell ---
				matrixCellType = content-cell !
			{
				Snippet CssClass --- MatrixContentCellItem ---
					domainAttribute = mkt_val !
					matrixCellItemType = domain !
					enabled = conditional
					enabledIsBasedOn = instrument
					id = r5__6
					documentation = test
					aggregationItems = "tI3yd,ut3__,BY__7"
					enabledIsBasedOn-advanced = test
					enabledIsBasedOn-simplified = "SimpleDomain:SimpleClassDS#instrument"
				--- MatrixContentCellItem ---
					column-name = ds5142
					matrixCellItemType = computed !
					id = uG47j
					aggregationItems = "Q40c_,W_v_3,z_1__"
			}
			--- MatrixCell ---
				matrixCellType = last-cell !
			{
				--- MatrixCellItem ---
					domainAttribute = mkt_val !
					matrixCellItemType = domain !
					id = BY__7
				--- MatrixCellItem ---
					column-name = comp_z_1__
					matrixCellItemType = computed !
					id = z_1__
			}
			--- MatrixCell ---
				matrixCellType = last-row !
			{
				--- MatrixCellItem ---
					domainAttribute = mkt_val !
					matrixCellItemType = domain !
					id = ut3__
				--- MatrixCellItem ---
					column-name = comp_W_v_3
					matrixCellItemType = computed !
					id = W_v_3
			}
			--- MatrixCell ---
				matrixCellType = last-column !
			{
				--- MatrixCellItem ---
					domainAttribute = mkt_val !
					matrixCellItemType = domain !
					id = tI3yd
				--- MatrixCellItem ---
					column-name = comp_Q40c_
					matrixCellItemType = computed !
					id = Q40c_
			}
			--- MatrixExtraColumn ---
				matrixCellType = extra-column !
		}
	}
}