# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "DS5275:TestDomainDS5275"
	bean-define = DSBean.DS5275.TestDomainDS5275
	bean-name = TestDomainDS5275
	bean-property-prefix = moduleref
	id = DS5275_IdGen_p_1__
{
	--- Box ---
		boxType = vertical
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 2
			gridColumnsWidth = "50,50" !
			gridRowCount = 2
		{
			--- GridCell ---
				gridColumnWidth = 50
			--- GridCell ---
				gridColumnWidth = 50
			{
				--- Include ---
					domainAssociation = money
					includeSrc = "" !
					resource:///ds5275/DS5275Search.fragment
					bean-property-prefix = money.
			}
			--- GridCell ---
				gridColumnWidth = 50
			--- GridCell ---
				gridColumnWidth = 50
			{
				--- Include ---
					domainAssociation = money
					includeSrc = "" !
					resource:///ds5275/DS5275Text.fragment
					bean-property-prefix = money1.
			}
		}
	}
}