# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "Ds4884:DS4884_DSOrderList"
	bean-define = DSBean.Ds4884.DS4884_DSOrderList
	bean-name = DS4884_DSOrderList
	id = DS5377_ExtendedToolTip_WIVZ_
{
	--- Box ---
		boxType = vertical
	{
		--- Label ---
			horizontalAlignment = "${corporatehalign}"
			includeXtooltipFragment = "" !
			resource:///ds5377/MyFragment.fragment
		--- TableTree ---
			table-editable-dataset = "Ds4884:DS4884_DSExtOperation"
			table-format-identifier = id
			table-row-identifier = id
			table-row-permission = permission
			id = XA_2_
			table-column-count = 2 !
			table-columns-width = "50,50" !
		{
			--- TableColumn ---
				column-name = data !
				column-type = domain !
				domainAttribute = data !
				type = text
				id = data
				table-column-width = 50
			{
				--- Icon ---
					horizontalAlignment = "${corporatehalign}"
					icon = application_form
					id = F9103
					includeXtooltipFragment = "" !
					resource:///ds5377/MyFragment.fragment
			}
			--- TableColumn ---
				column-name = code !
				column-type = domain !
				domainAttribute = code !
				type = text
				id = code
				table-column-width = 50
			{
				--- TableColumnItem ---
					item-column = code
					previewValue = value
					includeXtooltipFragment = "" !
					resource:///ds5377/MyFragment.fragment
			}
			--- TableSort ---
				sort-column-name = code
				sort-rank = 1
		}
	}
}