# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "DS5312Domain:OrderSessionDetailedList"
	bean-define = DSBean.DS5312Domain.OrderSessionDetailedList
	bean-name = OrderSessionDetailedList
	id = DS5312_V_W_0
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			show-column-selector = false
			table-editable-dataset = "DS5312Domain:ExtOperationAll"
			table-expand-all = false
			table-format-identifier = order_id
			table-row-identifier = id
			id = A1_Cg
			table-column-count = 1 !
			table-columns-width = 100 !
			table-filterset-id = fs_p3l
		{
			--- TableColumn ---
				column-name = ORDER_CURRENCY !
				column-type = domain !
				domainAttribute = ORDER_CURRENCY !
				type = text
				id = ORDER_CURRENCY
				table-column-width = 100
			{
				--- TableColumnCombobox ---
					item-column = ORDER_CURRENCY
					table-column-item-dataset-attribute = tradeCurrency.code
					previewValue = value
					type = text
				{
					Event OnChange (submit)
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						widget-group-ref = form
						target = self
						param = "flow-action=t2"
						prevalidate = false
						modal = false
						only-changed = false
					}
				}
			}
			--- TableSort ---
				sort-column-name = order_id
				sort-rank = 1
		}
	}
}