# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "Ds4884:DS4884_DSOrderList"
	bean-define = DSBean.Ds4884.DS4884_DSOrderList
	bean-name = DS4884_DSOrderList
	id = DS5349_TableColumnTextFieldInConditional_b42__
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			table-editable-dataset = "Ds4884:DS4884_DSExtOperation"
			table-format-identifier = id
			table-row-identifier = id
			table-row-permission = permission
			id = r_p_C
			table-column-count = 1 !
			table-columns-width = 100 !
		{
			--- TableColumn ---
				column-name = code !
				column-type = domain !
				domainAttribute = code !
				type = text
				id = code
				table-column-width = 100
			{
				--- Conditional ---
					indexOfSelectedChild = 1
				{
					--- ConditionalBody ---
						javaCode = true
						technicalName = Condition
						boxType = vertical
						isWidgetVisible = false
					{
						--- TableColumnText ---
							item-column = code
							table-column-item-dataset-attribute = quantity
							previewValue = value
							type = text
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetSelected = true
				}
			}
			--- TableSort ---
				sort-column-name = code
				sort-rank = 1
		}
	}
}