# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "DS5315Domain:OrderSessionDetailedList5315"
	cssClass = nodeco
	bean-define = DSBean.DS5315Domain.OrderSessionDetailedList5315
	bean-name = OrderSessionDetailedList5315
	id = ByCategoryAllEdit_gl_K8
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			table-editable-dataset = "DS5315Domain:ExtOperationAll5315"
			table-filter-layer = true
			table-format-identifier = order_id
			table-row-identifier = id
			table-row-permission = UPDATE_RIGHT
			table-page-size = 15
			id = i0710
			table-column-count = 16 !
			table-columns-width = "6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6" !
			table-filterset-id = fs_578
		{
			--- TableColumn ---
				labels en = Modify, fr = Modifier, de = Aktualisieren
				column-name = MODIFY
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				id = C_D1m
				table-column-width = 6
				tid = 89852910940356
			{
				--- Icon ---
					toolTips en = "Modify Order", fr = "Modifier l’ordre", de = "Auftrag aktualisieren"
					icon = application_form_edit
					enabled = conditional
					enabledIsBasedOn = advanced
					id = y_sB_
					enabledIsBasedOn-advanced = "conditionVal=!<bean:is-true key=\"DSBean.DS5315Domain.OrderSessionDetailedList.updateMode\"/>\r\n&amp;&amp; \"true\".equals(<udp:item column=\"UPDATE_RIGHT\"/>.toString());"
					enabledIsBasedOn-simplified = "DS5315Domain:OrderSessionDetailedList#UPDATE_RIGHT"
					tid = 159638881438004
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = updateorder ud
						toinit-id = "<udp:item column=\"order_id\"/>" ud
						modal = false
						only-changed = false
						prevalidate = false
						toinit-functionResult.id = "valueOf(form.id)" ud
					}
				}
			}
			--- TableColumn ---
				labels en = Copy, fr = Copier, de = Kopieren
				column-name = COPY
				column-type = placeholder !
				type = boolean
				column-locked = true
				column-sortable = false !
				id = J0_C8
				table-column-width = 6
				tid = 1294576231513502
			{
				--- Icon ---
					toolTips de = "Auftrag Kopieren", fr = "Copier l\'ordre", en = "Copy order"
					icon = application_double
					enabled = conditional
					enabledIsBasedOn = advanced
					id = h009_
					enabledIsBasedOn-advanced = "conditionVal=!<bean:is-true key=\"DSBean.DS5315Domain.OrderSessionDetailedList.updateMode\"/>\r\n&amp;&amp; \"true\".equals(<udp:item column=\"UPDATE_RIGHT\"/>.toString());"
					enabledIsBasedOn-simplified = "DS5315Domain:OrderSessionDetailedList#UPDATE_RIGHT"
					tid = 91300635714874
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = copyOrder ud
						toinit-id = "<udp:item column=\"order_id\"/>" ud
						modal = false
						only-changed = false
						prevalidate = false
						toinit-functionResult.id = "valueOf(form.id)" ud
					}
				}
			}
			--- TableColumn ---
				labels en = View, fr = Voir, de = Ansehen
				column-name = SELECT
				column-type = placeholder !
				type = boolean
				column-locked = true
				column-sortable = false !
				id = T8E_E
				table-column-width = 6
				tid = 21206052233174
			{
				--- Icon ---
					toolTips en = "View Order", fr = "Voir l’ordre", de = "Auftrag ansehen"
					icon = application_form_magnify
					enabled = conditional
					enabledIsBasedOn = advanced
					id = O7_h_
					enabledIsBasedOn-advanced = "conditionVal=!<bean:is-true key=\"DSBean.DS5315Domain.OrderSessionDetailedList.updateMode\"/>;"
					tid = 118793130408194
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = vieworder ud
						toinit-id = "<udp:item column=\"order_id\"/>" ud
						modal = false
						only-changed = false
						prevalidate = false
						toinit-functionResult.id = "valueOf(form.id)" ud
					}
				}
			}
			--- TableColumn ---
				labels en = Select, fr = Selection, de = Select
				column-name = ORDER_SELECT
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				id = rG__1
				table-column-width = 6
				tid = 1272245021345450
			{
				--- CheckBox ---
					column-checkbox-action = orderSel
					column-checkbox-identifier = order_id
					horizontalTextPosition = trail
					enabled = conditional
					enabledIsBasedOn = advanced
					id = btn_jBnXW
					enabledIsBasedOn-advanced = "conditionVal=!<bean:is-true key=\"DSBean.DS5315Domain.OrderSessionDetailedList.updateMode\"/>\r\n&amp;&amp; \"true\".equals(<udp:item column=\"UPDATE_RIGHT\"/>.toString());"
			}
			--- TableColumn ---
				labels en = Order
				column-display-grouping = true
				column-name = ORDER_HIER_STR
				column-type = placeholder !
				type = text
				column-sortable = false !
				id = tF6__
				table-column-width = 6
				tid = 1290069031151445
			{
				--- TableGroup ---
					aggregateData = false
					group-column-name = ORDER_HIER_STR
					group-sorting-column-name = ORDER_HIER_STR
					group-sorting-direction = ascending
					hierarchy = true
					group-rank = 1
			}
			--- TableColumn ---
				column-name = CREATION_DATE !
				column-type = domain !
				domainAttribute = CREATION_DATE !
				type = text
				id = CREATION_DATE
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = CREATION_DATE
					format = datetime
					previewValue = value
			}
			--- TableColumn ---
				column-name = ORDER_NATURE !
				column-type = domain !
				domainAttribute = ORDER_NATURE !
				type = text
				id = ORDER_NATURE
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = ORDER_NATURE
					previewValue = value
			}
			--- TableColumn ---
				column-name = PORTFOLIO_NAME !
				column-type = domain !
				domainAttribute = PORTFOLIO_NAME !
				type = text
				id = PORTFOLIO_NAME
				table-column-width = 6
			{
				--- TableColumnText ---
					item-column = PORTFOLIO_NAME
					table-column-item-dataset-attribute = summaryC
					previewValue = value
					type = text
			}
			--- TableColumn ---
				column-name = INSTR_NAME !
				column-type = domain !
				domainAttribute = INSTR_NAME !
				type = text
				id = INSTR_NAME
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = INSTR_NAME
					previewValue = value
			}
			--- TableColumn ---
				column-name = QUANTITY !
				column-type = domain !
				domainAttribute = QUANTITY !
				format = decimal
				type = text
				id = QUANTITY
				table-column-width = 6
			{
				--- TableColumnText ---
					editable-levels = false
					item-column = QUANTITY
					table-column-item-dataset-attribute = quantityN
					columns = 22
					format = decimal.detailed
					previewValue = value
					type = decimal
					chars = 22
			}
			--- TableColumn ---
				labels en = "No Grouping"
				column-name = PARENT_OPER_NATURE !
				column-type = domain !
				domainAttribute = PARENT_OPER_NATURE !
				type = text
				id = PARENT_OPER_NATURE
				table-column-width = 6
				tid = 1290408688007833
			{
				--- TableColumnCombobox ---
					editable-levels = false
					item-column = PARENT_OPER_NATURE
					table-column-item-dataset-attribute = parentOperNatE
					previewValue = value
			}
			--- TableColumn ---
				column-name = CATEGORY_LABEL !
				column-type = domain !
				domainAttribute = CATEGORY_LABEL !
				type = text
				id = CATEGORY_LABEL
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = CATEGORY_LABEL
					previewValue = value
			}
			--- TableColumn ---
				column-name = VALUE_DATE !
				column-type = domain !
				domainAttribute = VALUE_DATE !
				type = text
				id = VALUE_DATE
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = VALUE_DATE
					format = datetime
					previewValue = value
			}
			--- TableColumn ---
				column-name = ORDER_SUMMARY !
				column-type = domain !
				domainAttribute = ORDER_SUMMARY !
				type = text
				id = ORDER_SUMMARY
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = ORDER_SUMMARY
					previewValue = value
			}
			--- TableColumn ---
				column-name = ORDER_DATE !
				column-type = domain !
				domainAttribute = ORDER_DATE !
				type = text
				id = ORDER_DATE
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = ORDER_DATE
					format = datetime.date-only
					previewValue = value
			}
			--- TableColumn ---
				column-name = order_id !
				column-type = domain !
				domainAttribute = order_id !
				type = text
				column-is-part-of-filter = false
				column-visibility = never-visible
				id = order_id
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = order_id
					format = integer
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = PORTFOLIO_NAME
				sort-rank = 3
			--- TableSort ---
				sort-column-name = CATEGORY_LABEL
				sort-rank = 4
			--- TableSort ---
				sort-column-name = CREATION_DATE
				sort-direction = descending
				sort-rank = 2
			--- TableExtra ---
				domainAttribute = UPDATE_RIGHT
		}
	}
}