# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "DS5442:StrategyAdmin"
	bean-define = DSBean.DS5442.StrategyAdmin
	bean-name = StrategyAdmin
	id = DS5442_ConditionEL_f97__
{
	--- Box ---
		boxType = vertical
	{
		--- Conditional ---
			indexOfSelectedChild = 1
		{
			--- ConditionalBody ---
				conditionLang = DSEL
				javaCode = "NOT(StrategyAdmin.grid == null)"
				technicalName = Grid
				boxType = vertical
				isWidgetVisible = false
			{
				--- Label ---
					labels en = "Grid Only"
					horizontalAlignment = "${corporatehalign}"
					tid = 182237873483290
			}
			--- ConditionalBody ---
				conditionLang = DSEL
				javaCode = "StrategyAdmin.list != null"
				technicalName = "Grid List"
				boxType = vertical
				isWidgetSelected = true
			{
				--- Label ---
					labels en = "Grid List"
					horizontalAlignment = "${corporatehalign}"
					tid = 182246864160427
			}
			--- ConditionalBody ---
				conditionLang = DSEL
				javaCode = "StrategyAdmin.code == null"
				technicalName = Code
				boxType = vertical
				isWidgetVisible = false
			--- ConditionalBody ---
				conditionLang = DSEL
				javaCode = "StrategyAdmin.amount == 500"
				technicalName = Amount
				boxType = vertical
				isWidgetVisible = false
			--- ConditionalBody ---
				conditionLang = DSEL
				javaCode = "StrategyAdmin.subNatureE==DS5442::StrategySubNatureE::None"
				technicalName = Enumeration
				boxType = vertical
				isWidgetVisible = false
			--- ConditionalBody ---
				javaCode = true
				technicalName = Default
				boxType = vertical
				isWidgetVisible = false
		}
	}
}