# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	bean-define = DSBean..
	id = DS5596Module_MOS12
{
	--- Box ---
		boxType = vertical
		id = red
	{
		--- Conditional ---
			technicalName = TestConditionalDialog
			indexOfSelectedChild = 1
		{
			--- ConditionalBody ---
				javaCode = false
				technicalName = Condition
				boxType = vertical
				isWidgetVisible = false
			--- ConditionalBody ---
				conditionLang = DSEL
				javaCode = true
				technicalName = Default
				boxType = vertical
				isWidgetSelected = true
		}
	}
}