# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "SimpleDomain:SimpleClassDS"
	bean-define = DSBean.SimpleDomain.SimpleClassDS
	bean-name = SimpleClassDS
	id = DS3911_D_0r3
{
	--- Box ---
		boxType = vertical
	{
		--- Matrix ---
			id = f50_1
		{
			--- MatrixAxis ---
				domainAttribute = asset_class !
				matrixAxis = x-axis !
			--- MatrixAxis ---
				domainAttribute = currency !
				matrixAxis = y-axis !
			--- MatrixContentCell ---
				matrixCellType = content-cell !
			{
				Snippet CssClass --- MatrixContentCellItem ---
					domainAttribute = mkt_val !
					matrixCellItemType = domain !
					id = e_7__
					aggregationItems = "Cf_20,u__1_,Sp_q4"
				--- Conditional ---
					technicalName = TestCondition1
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = true
						technicalName = Condition
						boxType = vertical
						isWidgetSelected = true
					{
						--- MatrixContentCellItem ---
							domainAttribute = asset_rank !
							matrixCellItemType = domain !
							id = XD4__
							aggregationItems = "A__3_,l_6_0,A661P"
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetVisible = false
				}
				--- Box ---
				{
					--- Conditional ---
						technicalName = TestCondition2
						indexOfSelectedChild = 0
					{
						--- ConditionalBody ---
							javaCode = false
							technicalName = Condition
							boxType = vertical
							isWidgetSelected = true
						{
							--- MatrixContentCellItem ---
								domainAttribute = instrument !
								matrixCellItemType = domain !
								id = R1_t_
								aggregationItems = "yO__U,Ue1__,sRk5p"
						}
						--- ConditionalBody ---
							javaCode = true
							technicalName = Default
							boxType = vertical
							isWidgetVisible = false
					}
				}
			}
			--- MatrixCell ---
				matrixCellType = last-cell !
			{
				--- MatrixCellItem ---
					domainAttribute = instrument !
					matrixCellItemType = domain !
					id = sRk5p
				--- MatrixCellItem ---
					domainAttribute = asset_rank !
					matrixCellItemType = domain !
					id = A661P
				--- MatrixCellItem ---
					domainAttribute = mkt_val !
					matrixCellItemType = domain !
					id = Sp_q4
			}
			--- MatrixCell ---
				matrixCellType = last-row !
			{
				--- MatrixCellItem ---
					domainAttribute = instrument !
					matrixCellItemType = domain !
					id = Ue1__
				--- MatrixCellItem ---
					domainAttribute = asset_rank !
					matrixCellItemType = domain !
					id = l_6_0
				--- MatrixCellItem ---
					domainAttribute = mkt_val !
					matrixCellItemType = domain !
					id = u__1_
			}
			--- MatrixCell ---
				matrixCellType = last-column !
			{
				--- MatrixCellItem ---
					domainAttribute = instrument !
					matrixCellItemType = domain !
					id = yO__U
				--- MatrixCellItem ---
					domainAttribute = asset_rank !
					matrixCellItemType = domain !
					id = A__3_
				--- MatrixCellItem ---
					domainAttribute = mkt_val !
					matrixCellItemType = domain !
					id = Cf_20
			}
			--- MatrixExtraColumn ---
				matrixCellType = extra-column !
		}
	}
}