# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "SimpleDomain:SimpleClassDS"
	bean-define = DSBean.SimpleDomain.SimpleClassDS
	bean-name = SimpleClassDS
	id = DS5666MatrixAggregations_GW2z0
{
	--- Box ---
		boxType = vertical
	{
		--- Matrix ---
			displayLastRow = false
			id = XDTQ_
		{
			--- MatrixAxis ---
				domainAttribute = currency !
				group-sorting-column-name = MKT_VAL
				group-sorting-direction = descending
				matrixAxis = x-axis !
			--- MatrixAxis ---
				domainAttribute = asset_rank !
				group-sorting-column-name = MKT_VAL
				group-sorting-direction = descending
				matrixAxis = y-axis !
			--- MatrixContentCell ---
				matrixCellType = content-cell !
			{
				Snippet CssClass --- MatrixContentCellItem ---
					domainAttribute = mkt_val !
					matrixCellItemType = domain !
					id = GT4c3
					aggregationItems = "p_8m8,kRH61,fR_9X"
				--- MatrixContentCellItem ---
					domainAttribute = instrument !
					matrixCellItemType = domain !
					id = C_3X1
					aggregationItems = "wH3j_,pnj09,N8_p9"
			}
			--- MatrixCell ---
				matrixCellType = last-cell !
			{
				--- MatrixCellItem ---
					domainAttribute = mkt_val !
					matrixCellItemType = domain !
					id = fR_9X
				--- MatrixCellItem ---
					domainAttribute = instrument !
					matrixCellItemType = domain !
					id = N8_p9
			}
			--- MatrixCell ---
				matrixCellType = last-row !
			{
				--- MatrixCellItem ---
					domainAttribute = mkt_val !
					matrixCellItemType = domain !
					id = V7__9
				--- MatrixCellItem ---
					domainAttribute = instrument !
					matrixCellItemType = domain !
					id = pnj09
			}
			--- MatrixCell ---
				matrixCellType = last-column !
			{
				--- MatrixCellItem ---
					domainAttribute = mkt_val !
					matrixCellItemType = domain !
					id = k__V_
				--- MatrixCellItem ---
					domainAttribute = instrument !
					matrixCellItemType = domain !
					id = wH3j_
			}
			--- MatrixExtraColumn ---
				matrixCellType = extra-column !
		}
	}
}