# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSExtOperation:ExtOperationAll"
	cssClass = nodeco
	bean-define = DSBean.AAADSExtOperation.ExtOperationAll
	bean-name = ExtOperationAll
	id = MMDepositIdentifierCreate_GHq7C
{
	--- Box ---
		labels en = Identification, fr = Identification, de = Identification
		boxType = vertical
		tid = 492694602405054
	{
		--- Conditional ---
			indexOfSelectedChild = 0
		{
			--- ConditionalBody ---
				conditionLang = DSEL
				javaCode = "ExtOperationAll.isProposalOrder==1"
				technicalName = Proposal
				boxType = vertical
				isWidgetSelected = true
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 4
					gridColumnsWidth = "25,25,25,25" !
					gridRowCount = 2
				{
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- LabelDomain ---
							labels en = "Contract Type", de = Vertragsart, fr = "Type de contrat"
							domainAttribute = orderType !
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							tid = 492425918584903
					}
					--- GridCell ---
						gridColumnWidth = 25
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- LabelDomain ---
							domainAttribute = valueD !
							for = valueD
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
					}
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- CaldateField ---
							domainAttribute = valueD !
							format = datetime.date-only
							horizontalAlignment = "${corporatehalign}"
							type = datetime
							required = true
							bean-property = valueD
							id = valueD
						{
							Event OnChange (submit)
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								widget-group-ref = form
								param = "flow-action=reload"
								only-changed = true
								modal = false
								prevalidate = false
							}
						}
					}
					--- GridCell ---
						gridColumnWidth = 25
					--- GridCell ---
						gridColumnWidth = 25
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- Label ---
							labels en = "Market Segment", fr = Type, de = Typ
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							tid = 492425919330250
					}
					--- GridCell ---
						gridColumnWidth = 25
				}
			}
			--- ConditionalBody ---
				javaCode = true
				technicalName = Default
				boxType = vertical
				isWidgetVisible = false
			{
				--- TextArea ---
					domainAttribute = summaryC !
					columns = 200
					horizontalAlignment = "${corporatehalign}"
					rows = 1
					type = text
					editable = false
					bean-property = summaryC
					id = summaryC
				--- Grid ---
					cssClass = blank
					gridColumnCount = 4
					gridColumnsWidth = "25,25,25,25" !
					gridRowCount = 2
				{
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- LabelDomain ---
							labels en = "Contract Type", de = Vertragsart, fr = "Type de contrat"
							domainAttribute = orderType !
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							tid = 492425923249183
					}
					--- GridCell ---
						gridColumnWidth = 25
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- LabelDomain ---
							domainAttribute = valueD !
							for = valueD
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
					}
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- CaldateField ---
							domainAttribute = valueD !
							format = datetime.date-only
							horizontalAlignment = "${corporatehalign}"
							type = datetime
							required = true
							bean-property = valueD
							id = valueD
						{
							Event OnChange (submit)
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								widget-group-ref = form
								param = "flow-action=reload"
								only-changed = true
								modal = false
								prevalidate = false
							}
						}
					}
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- LabelDomain ---
							domainAttribute = portfolio !
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
					}
					--- GridCell ---
						gridColumnWidth = 25
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- LabelDomain ---
							labels en = "Portfolio Name", fr = "Nom du portefeuille"
							domainAttribute = portfolio !
							cssClass = grey
							horizontalAlignment = "${corporatehalign}"
							tid = 492425925201108
					}
					--- GridCell ---
						gridColumnWidth = 25
				}
			}
		}
	}
}