# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "DS5705:DS5705"
	bean-define = DSBean.DS5705.DS5705
	bean-name = DS5705
	id = DS5705_dc9DM
{
	--- Box ---
		boxType = vertical
	{
		--- Box ---
		{
			--- RadioButton ---
				domainAttribute = renewal
				enumValue = None !
				horizontalTextPosition = trail
				bean-name = DS5705
				bean-property = renewal
				group = renewal
				id = btn_H___8
			--- RadioButton ---
				domainAttribute = renewal
				enumValue = Automatic !
				displayLabel = false
				horizontalTextPosition = trail
				bean-name = DS5705
				bean-property = renewal
				group = renewal
				id = btn_v1_2_
			--- RadioButton ---
				domainAttribute = renewal
				enumValue = Manual !
				horizontalTextPosition = trail
				bean-name = DS5705
				bean-property = renewal
				group = renewal
				id = btn_BQL39
		}
		--- Grid ---
			cssClass = blank
			gridColumnCount = 2
			gridColumnsWidth = "50,50" !
			gridRowCount = 2
		{
			--- GridCell ---
				gridColumnWidth = 50
			{
				--- LabelDomain ---
					domainAttribute = keepRemark !
					for = keepRemark
					horizontalAlignment = "${corporatehalign}"
					id = keepRemark
			}
			--- GridCell ---
				gridColumnWidth = 50
			{
				--- CheckBox ---
					column-checkbox-action = ""
					domainAttribute = keepRemark !
					horizontalAlignment = "${corporatehalign}"
					horizontalTextPosition = trail
					bean-property = keepRemark
					id = keepRemark
			}
			--- GridCell ---
				gridColumnWidth = 50
			{
				--- LabelDomain ---
					domainAttribute = radioButtonCalcAttr !
					for = radioButtonCalcAttr
					horizontalAlignment = "${corporatehalign}"
					id = radioButtonCalcAttr
			}
			--- GridCell ---
				gridColumnWidth = 50
			{
				--- RadioButton ---
					domainAttribute = radioButtonCalcAttr !
					enumValue = Selected !
					horizontalTextPosition = trail
					bean-property = radioButtonCalcAttr
					group = radioButtonCalcAttr
					id = btn_V_rS6
				--- RadioButton ---
					domainAttribute = radioButtonCalcAttr !
					enumValue = Deselected !
					horizontalTextPosition = trail
					bean-property = radioButtonCalcAttr
					group = radioButtonCalcAttr
					id = btn_n__34
			}
		}
	}
}