# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "SimpleDomain:SimpleClassDS"
	bean-define = DSBean.SimpleDomain.SimpleClassDS
	bean-name = SimpleClassDS
	id = DS5931_c1hSN
{
	--- Box ---
		boxType = vertical
	{
		--- Matrix ---
			id = lGo_r
			matrix-model-reference = DSBean.SimpleDomain.SimpleClassDS
		{
			--- MatrixAxis ---
				domainAttribute = currency !
				matrixAxis = x-axis !
			--- MatrixAxis ---
				domainAttribute = asset_class !
				matrixAxis = y-axis !
			--- MatrixContentCell ---
				matrixCellType = content-cell !
			{
				Snippet CssClass --- MatrixContentCellItem ---
					toolTips en = "tooltip for first computation item"
					column-name = comp_mnN__
					matrixCellItemType = computed !
					format = exchangerate
					id = f9_P_
					aggregationItems = "s0O9_,h_9Lf,F9_j9"
					column-computation = compute-percentage
					column-computation-parameters = mkt_val
					tid = 11338195219036
			}
			--- MatrixCell ---
				matrixCellType = last-cell !
			{
				--- MatrixCellItem ---
					column-name = comp_F9_j9
					matrixCellItemType = computed !
					id = F9_j9 !
			}
			--- MatrixCell ---
				matrixCellType = last-row !
			{
				--- MatrixCellItem ---
					column-name = comp_h_9Lf
					matrixCellItemType = computed !
					id = h_9Lf !
			}
			--- MatrixCell ---
				matrixCellType = last-column !
			{
				--- MatrixCellItem ---
					column-name = comp_s0O9_
					matrixCellItemType = computed !
					id = s0O9_ !
			}
			--- MatrixExtraColumn ---
				matrixCellType = extra-column !
		}
	}
}