# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSPortfolio:PortfolioAll"
	bean-define = DSBean.AAADSPortfolio.PortfolioAll
	bean-name = PortfolioAll
	bean-property-prefix = MyPrefix
	id = ModulePrefixSample_h6_J_
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///default/portfolio/portfolioall/PortfolioIdentifierView.fragment
		--- Grid ---
			cssClass = blank
			gridColumnCount = 2
			gridColumnsWidth = "50,50" !
			gridRowCount = 10
		{
			--- GridCell ---
				gridColumnWidth = 50
			{
				--- LabelDomain ---
					domainAttribute = code !
					for = code
					horizontalAlignment = "${corporatehalign}"
					required = true
					id = code
			}
			--- GridCell ---
				gridColumnWidth = 50
			{
				--- TextField ---
					domainAttribute = code !
					horizontalAlignment = "${corporatehalign}"
					type = text
					chars = 20
					required = true
					bean-property = code
					id = code
			}
			--- GridCell ---
				gridColumnWidth = 50
			{
				--- LabelDomain ---
					domainAttribute = currConvD !
					for = currConvD
					horizontalAlignment = "${corporatehalign}"
					id = currConvD
			}
			--- GridCell ---
				gridColumnWidth = 50
			{
				--- CaldateField ---
					domainAttribute = currConvD !
					format = datetime.date-only
					horizontalAlignment = "${corporatehalign}"
					type = datetime
					bean-property = currConvD
					id = currConvD
			}
			--- GridCell ---
				gridColumnWidth = 50
			{
				--- LabelDomain ---
					domainAttribute = activeF !
					for = activeF
					horizontalAlignment = "${corporatehalign}"
					required = true
					id = activeF
			}
			--- GridCell ---
				gridColumnWidth = 50
			{
				--- ComboBox ---
					domainAttribute = activeF !
					horizontalAlignment = "${corporatehalign}"
					required = true
					bean-property = activeF
					id = activeF
			}
			--- GridCell ---
				gridColumnWidth = 50
			{
				--- LabelDomain ---
					domainAttribute = defaultRecomE !
					for = defaultRecomE
					horizontalAlignment = "${corporatehalign}"
					required = true
					id = defaultRecomE
			}
			--- GridCell ---
				gridColumnWidth = 50
			{
				--- ComboBox ---
					domainAttribute = defaultRecomE !
					horizontalAlignment = "${corporatehalign}"
					required = true
					bean-property = defaultRecomE
					id = defaultRecomE
			}
			--- GridCell ---
				gridColumnWidth = 50
			{
				--- LabelDomain ---
					domainAttribute = deleteRightF !
					for = deleteRightF
					horizontalAlignment = "${corporatehalign}"
					required = true
					id = deleteRightF
			}
			--- GridCell ---
				gridColumnWidth = 50
			{
				--- CheckBox ---
					column-checkbox-action = ""
					domainAttribute = deleteRightF
					horizontalTextPosition = trail
					bean-property = deleteRightF
					id = deleteRightF
			}
			--- GridCell ---
				gridColumnWidth = 50
			{
				--- LabelDomain ---
					domainAttribute = dividendAccrualE !
					for = dividendAccrualE
					horizontalAlignment = "${corporatehalign}"
					required = true
					id = dividendAccrualE
			}
			--- GridCell ---
				gridColumnWidth = 50
			{
				--- RadioButton ---
					domainAttribute = dividendAccrualE !
					enumValue = None !
					horizontalTextPosition = trail
					bean-property = dividendAccrualE
					group = dividendAccrualE
					id = btn_F06Hd
				--- RadioButton ---
					domainAttribute = dividendAccrualE !
					enumValue = All !
					horizontalTextPosition = trail
					bean-property = dividendAccrualE
					group = dividendAccrualE
					id = btn_fCw_S
				--- RadioButton ---
					domainAttribute = dividendAccrualE !
					enumValue = Default !
					horizontalTextPosition = trail
					bean-property = dividendAccrualE
					group = dividendAccrualE
					id = btn_GP___
				--- RadioButton ---
					domainAttribute = dividendAccrualE !
					enumValue = Stocks !
					horizontalTextPosition = trail
					bean-property = dividendAccrualE
					group = dividendAccrualE
					id = btn_o___0
				--- RadioButton ---
					domainAttribute = dividendAccrualE !
					enumValue = FundShares !
					horizontalTextPosition = trail
					bean-property = dividendAccrualE
					group = dividendAccrualE
					id = btn_u3_9_
			}
			--- GridCell ---
				gridColumnWidth = 50
			{
				--- LabelDomain ---
					domainAttribute = denom !
					for = denom
					horizontalAlignment = "${corporatehalign}"
					id = denom
			}
			--- GridCell ---
				gridColumnWidth = 50
			{
				--- TextArea ---
					domainAttribute = denom
					columns = 30
					rows = 3
					bean-property = denom
					id = denom
			}
			--- GridCell ---
				gridColumnWidth = 50
			{
				--- LabelDomain ---
					domainAttribute = third !
					horizontalAlignment = "${corporatehalign}"
			}
			--- GridCell ---
				gridColumnWidth = 50
			{
				--- Include ---
					domainAssociation = third
					includeSrc = "" !
					resource:///default/defaultFragments/ThirdPartyIdentifier.fragment
					bean-property-prefix = third.
			}
			--- GridCell ---
				gridColumnWidth = 50
			{
				--- LabelDomain ---
					domainAttribute = sysCurrency !
					horizontalAlignment = "${corporatehalign}"
			}
			--- GridCell ---
				gridColumnWidth = 50
			{
				--- Include ---
					domainAssociation = sysCurrency
					includeSrc = "" !
					resource:///default/defaultFragments/CurrencyIdentifier.fragment
					bean-property-prefix = sysCurrency.
			}
			--- GridCell ---
				gridColumnWidth = 50
			{
				--- LabelDomain ---
					domainAttribute = parentPort !
					horizontalAlignment = "${corporatehalign}"
			}
			--- GridCell ---
				gridColumnWidth = 50
			{
				--- Include ---
					domainAssociation = parentPort
					includeSrc = "" !
					resource:///default/defaultFragments/PortfolioIdentifier.fragment
					bean-property-prefix = parentPort.
			}
		}
	}
}