# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = History, fr = Historique, de = Historische
	domainEntity = "AAADSStrategyHistory:StrategyHistoryList"
	bean-define = DSBean.AAADSStrategyHistory.StrategyHistoryList
	bean-name = StrategyHistoryList
	id = HistoryUpdate_dwo24
	tid = 272183846869750
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			table-page-size = 5
			id = pDlRL
			table-column-count = 6 !
			table-columns-width = "16,16,16,16,16,16" !
		{
			--- TableColumn ---
				labels en = Modify, de = Aktualisieren, fr = Modifier
				column-name = Update
				column-type = placeholder !
				type = text
				column-sortable = false !
				id = l__83
				table-column-width = 16
				tid = 272183847392288
			{
				--- Icon ---
					toolTips en = "Modify History", fr = "Modifier l\'historique", de = "Geschichte ändern"
					horizontalAlignment = center
					icon = application_form_edit
					id = J65a_
					tid = 272183849301595
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = selectHistory ud
						id = "<udp:item column=\"id\"/>" ud
						modal = false
						only-changed = false
						prevalidate = false
						histMode = update ud
						strategyDimStrategy.code = "<udp:item column=\"strategyCode\"/>" ud
						calcFromD = "<udp:item column=\"beginD\"/>" ud
					}
				}
			}
			--- TableColumn ---
				labels en = View, fr = Voir, de = Ansehen
				column-name = View
				column-type = placeholder !
				type = text
				column-sortable = false !
				id = uA_I_
				table-column-width = 16
				tid = 272183851251470
			{
				--- Icon ---
					toolTips en = "View History", de = "Siehe Geschichte", fr = "Voir l\'historique"
					horizontalAlignment = center
					icon = application_form_magnify
					id = N___8
					tid = 272183853205364
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = selectHistory ud
						id = "<udp:item column=\"id\"/>" ud
						modal = false
						only-changed = false
						prevalidate = false
						histMode = view ud
						strategyDimStrategy.code = "<udp:item column=\"strategyCode\"/>" ud
						calcFromD = "<udp:item column=\"beginD\"/>" ud
					}
				}
			}
			--- TableColumn ---
				labels en = "Begin on", fr = "Commence le", de = "Anfängt am"
				column-name = beginD !
				column-type = domain !
				domainAttribute = beginD !
				format = date
				type = text
				column-visibility = never-visible
				id = beginD
				table-column-width = 16
				tid = 89088777522747
			{
				--- TableColumnItem ---
					item-column = beginD
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Begin on", fr = "Commence le", de = "Anfängt am"
				column-name = BeginDate
				type = date
				id = r9oRf
				column-computation = same
				column-computation-parameters = beginD
				table-column-width = 16
				tid = 107003391205984
			{
				--- TableColumnItem ---
					item-column = BeginDate
					format = datetime.date-only
					previewValue = value
			}
			--- TableColumn ---
				labels en = "End on", fr = "Finit le", de = "Endet am"
				column-name = endD !
				column-type = domain !
				domainAttribute = endD !
				format = date
				type = text
				id = endD
				table-column-width = 16
				tid = 89121710114258
			{
				--- TableColumnItem ---
					item-column = endD
					format = datetime.date-only
					previewValue = value
			}
			--- TableColumn ---
				column-name = extDenomination !
				column-type = domain !
				domainAttribute = extDenomination !
				type = text
				id = extDenomination
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = extDenomination
					previewValue = value
			}
			--- TableExtra ---
				domainAttribute = strategyCode
			--- TableExtra ---
				domainAttribute = id
			--- TableSort ---
				sort-column-name = BeginDate
				sort-direction = descending
				sort-rank = 2
		}
	}
}