# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	containment = container
	domainEntity = "AAADSStrategy:StrategyAdmin"
	cssClass = nodeco
	bean-define = DSBean.AAADSStrategy.StrategyAdmin
	bean-name = StrategyAdmin
	id = HistoryWithObjectives_tA1__
{
	--- Box ---
		boxType = vertical
	{
		--- Conditional ---
			indexOfSelectedChild = 0
		{
			--- ConditionalBody ---
				javaCode = "(Integer.toString(com.odcgroup.aaa.StrategyNatureE.AssetAllocation).equals(<bean:get-property bean=\"StrategyAdmin\" property=\"natureE\"/>.toString()))\r\n &amp;&amp;\r\n(\"update\".equals(<bean:get-property bean=\"StrategyAdmin\" property=\"mode\"/>.toString()))"
				technicalName = "Allocation Edit"
				boxType = vertical
				isWidgetSelected = true
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/strategy/common/history/HistoryUpdate.module
			}
			--- ConditionalBody ---
				javaCode = "(Integer.toString(com.odcgroup.aaa.StrategyNatureE.AssetAllocation).equals(<bean:get-property bean=\"StrategyAdmin\" property=\"natureE\"/>.toString()))\r\n &amp;&amp;\r\n(\"view\".equals(<bean:get-property bean=\"StrategyAdmin\" property=\"mode\"/>.toString()))"
				technicalName = "Allocation View"
				boxType = vertical
				isWidgetVisible = false
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/strategy/common/history/HistoryView.module
			}
		}
	}
}