# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = History, fr = Historique, de = Historische
	domainEntity = "AAADSStrategyHistory:StrategyHistoryList"
	bean-define = DSBean.AAADSStrategyHistory.StrategyHistoryList
	bean-name = StrategyHistoryList
	id = HistoryView_P9_6Q
	tid = 272187675009434
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			table-page-size = 5
			id = DcBSD
			table-column-count = 5 !
			table-columns-width = "20,20,20,20,20" !
		{
			--- TableColumn ---
				labels en = View, fr = Voir, de = Ansehen
				column-name = View
				column-type = placeholder !
				type = text
				column-sortable = false !
				id = P_w_k
				table-column-width = 20
				tid = 272187675500573
			{
				--- Icon ---
					toolTips en = "View History", de = "Siehe Geschichte", fr = "Voir l\'historique"
					horizontalAlignment = center
					icon = application_form_magnify
					id = ZGCb_
					tid = 272187729735918
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = selectHistory ud
						id = "<udp:item column=\"id\"/>" ud
						modal = false
						only-changed = false
						prevalidate = false
						histMode = view ud
						strategyDimStrategy.code = "<udp:item column=\"strategyCode\"/>" ud
						calcFromD = "<udp:item column=\"beginD\"/>" ud
					}
				}
			}
			--- TableColumn ---
				labels en = "Begin on", fr = "Commence le", de = "Anfängt am"
				column-name = beginD !
				column-type = domain !
				domainAttribute = beginD !
				format = date
				type = text
				column-visibility = never-visible
				id = beginD
				table-column-width = 20
				tid = 89215444319436
			{
				--- TableColumnItem ---
					item-column = beginD
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Begin on", fr = "Commence le", de = "Anfängt am"
				column-name = BeginDate
				type = date
				id = C8049
				column-computation = same
				column-computation-parameters = beginD
				table-column-width = 20
				tid = 107875424904830
			{
				--- TableColumnItem ---
					item-column = BeginDate
					format = datetime.date-only
					previewValue = value
			}
			--- TableColumn ---
				labels en = "End on", fr = "Finit le", de = "Endet am"
				column-name = endD !
				column-type = domain !
				domainAttribute = endD !
				format = date
				type = text
				id = endD
				table-column-width = 20
				tid = 89243611742945
			{
				--- TableColumnItem ---
					item-column = endD
					previewValue = value
			}
			--- TableColumn ---
				column-name = extDenomination !
				column-type = domain !
				domainAttribute = extDenomination !
				type = text
				id = extDenomination
				table-column-width = 20
			{
				--- TableColumnItem ---
					item-column = extDenomination
					previewValue = value
			}
			--- TableExtra ---
				domainAttribute = strategyCode
			--- TableExtra ---
				domainAttribute = id
			--- TableSort ---
				sort-column-name = BeginDate
				sort-direction = descending
				sort-rank = 2
		}
	}
}