# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = Objectives, fr = Objectifs, de = Ziele
	containment = container
	domainEntity = "AAADSStrategyHistory:StrategyHistoryAdmin"
	bean-define = DSBean.AAADSStrategyHistory.StrategyHistoryAdmin
	bean-name = StrategyHistoryAdmin
	id = SelectedHistoryHead_R__i6
	tid = 274846870078851
{
	--- Box ---
		boxType = vertical
	{
		--- Conditional ---
			indexOfSelectedChild = 0
		{
			--- ConditionalBody ---
				conditionLang = DSEL
				javaCode = "StrategyHistoryAdmin.histMode==\"edit\""
				technicalName = Edit
				boxType = vertical
				isWidgetSelected = true
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/strategy/common/history/SelectedHistoryUpdate.module
			}
			--- ConditionalBody ---
				conditionLang = DSEL
				javaCode = "StrategyHistoryAdmin.histMode==\"create\""
				technicalName = Create
				boxType = vertical
				isWidgetVisible = false
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/strategy/common/history/SelectedHistoryCreate.module
			}
			--- ConditionalBody ---
				javaCode = true
				technicalName = View
				boxType = vertical
				isWidgetVisible = false
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/strategy/common/history/SelectedHistoryView.module
			}
		}
	}
}