# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	containment = container
	domainEntity = "AAADSStrategyHistory:StrategyHistoryAdmin"
	cssClass = nodeco
	bean-define = DSBean.AAADSStrategyHistory.StrategyHistoryAdmin
	bean-name = StrategyHistoryAdmin
	id = SelectedHistoryUpdate_Kr65b
{
	--- Box ---
		boxType = vertical
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 6
			gridColumnsWidth = "10,10,10,10,30,30" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 10
			{
				--- LabelDomain ---
					domainAttribute = beginD !
					for = beginD
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					required = true
					id = beginD
			}
			--- GridCell ---
				gridColumnWidth = 10
			{
				--- CaldateField ---
					domainAttribute = beginD !
					format = date
					horizontalAlignment = "${corporatehalign}"
					type = date
					editable = false
					required = true
					bean-property = beginD
					id = beginD
			}
			--- GridCell ---
				gridColumnWidth = 10
			{
				--- LabelDomain ---
					domainAttribute = endD !
					for = endD
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					id = endD
			}
			--- GridCell ---
				gridColumnWidth = 10
			{
				--- CaldateField ---
					domainAttribute = endD !
					format = date
					horizontalAlignment = "${corporatehalign}"
					type = date
					nillable = true
					bean-property = endD
					id = endD
			}
			--- GridCell ---
				gridColumnWidth = 30
			{
				--- Button ---
					labels en = Save, fr = Sauvegarde toolTips en = "Click here to edit the selected history"
					id = btn_D3_y2
					enabledIsBasedOn-advanced = "if(\"update\".equals(<bean:get-property bean=\"StrategyHistoryAll\" property=\"histMode\"/>.toString()))\r\n\tconditionVal=true;\r\nelse\r\n\tconditionVal=false;"
					enabledIsBasedOn-simplified = "AAADSStrategyHistory:StrategyHistoryAll#histModeF"
					tid = 272246191338555
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = saveObjectives ud
						modal = false
						only-changed = false
						prevalidate = false
						widget-group-ref = form
					}
				}
			}
			--- GridCell ---
				gridColumnWidth = 30
		}
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/strategy/common/objectives/ObjectivesView.module
	}
}