# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	containment = container
	domainEntity = "AAADSStrategyHistory:StrategyHistoryAdmin"
	cssClass = nodeco
	bean-define = DSBean.AAADSStrategyHistory.StrategyHistoryAdmin
	bean-name = StrategyHistoryAdmin
	id = SelectedHistoryView_S_0X_
{
	--- Box ---
		boxType = vertical
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 8
			gridColumnsWidth = "10,10,10,10,30,10,5,5" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 10
			{
				--- LabelDomain ---
					domainAttribute = beginD !
					for = beginD
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					required = true
					id = beginD
			}
			--- GridCell ---
				gridColumnWidth = 10
			{
				--- CaldateField ---
					domainAttribute = beginD !
					format = date
					horizontalAlignment = "${corporatehalign}"
					type = date
					editable = false
					required = true
					bean-property = beginD
					id = beginD
			}
			--- GridCell ---
				gridColumnWidth = 10
			{
				--- LabelDomain ---
					domainAttribute = endD !
					for = endD
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					id = endD
			}
			--- GridCell ---
				gridColumnWidth = 10
			{
				--- CaldateField ---
					domainAttribute = endD !
					format = date
					horizontalAlignment = "${corporatehalign}"
					type = date
					editable = false
					bean-property = endD
					id = endD
			}
			--- GridCell ---
				gridColumnWidth = 30
			{
				--- Button ---
					labels en = "Edit objectives", fr = "Modier les objectifs" toolTips en = "Click here to edit the selected history"
					enabled = conditional
					enabledIsBasedOn = advanced
					id = btn_Ml_m_
					enabledIsBasedOn-advanced = "if(\"update\".equals(<bean:get-property bean=\"StrategyHistoryAdmin\" property=\"histMode\"/>.toString()))\r\n\tconditionVal=true;\r\nelse\r\n\tconditionVal=false;"
					enabledIsBasedOn-simplified = "AAADSStrategyHistory:StrategyHistoryAll#histModeF"
					tid = 12854333569865
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = editObjectives ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- GridCell ---
				gridColumnWidth = 10
			{
				--- Button ---
					labels en = "Create History", fr = "Créer un historique" toolTips en = "Click here to create a new history"
					horizontalAlignment = trail
					enabled = conditional
					enabledIsBasedOn = advanced
					id = btn_e78Uk
					enabledIsBasedOn-advanced = "if(\"update\".equals(<bean:get-property bean=\"StrategyHistoryAdmin\" property=\"histMode\"/>.toString()))\r\n\tconditionVal=true;\r\nelse\r\n\tconditionVal=false;"
					enabledIsBasedOn-simplified = "AAADSStrategyHistory:StrategyHistoryAll#histModeF"
					tid = 12854349296696
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = createHistory ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- GridCell ---
				gridColumnWidth = 5
			--- GridCell ---
				gridColumnWidth = 5
		}
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/strategy/common/objectives/ObjectivesView.module
	}
}