# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSExchRate:ExchRateList"
	bean-define = DSBean.AAADSExchRate.ExchRateList
	bean-name = ExchRateList
	id = ExchRateList_f_m_7
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			id = fx_oc
			table-column-count = 7 !
			table-columns-width = "14,14,14,14,14,14,14" !
		{
			--- TableColumn ---
				column-name = currencyCode !
				column-type = domain !
				domainAttribute = currencyCode !
				id = currencyCode
				table-column-width = 14
			{
				--- TableColumnItem ---
					item-column = currencyCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = exchD !
				column-type = domain !
				domainAttribute = exchD !
				id = exchD
				table-column-width = 14
			{
				--- TableColumnItem ---
					item-column = exchD
					format = datetime.date-only
					previewValue = value
			}
			--- TableColumn ---
				column-name = exchRate !
				column-type = domain !
				domainAttribute = exchRate !
				id = exchRate
				table-column-width = 14
			{
				--- TableColumnItem ---
					item-column = exchRate
					format = decimal.detailed
					previewValue = value
			}
			--- TableColumn ---
				column-name = underlyCurrencyCode !
				column-type = domain !
				domainAttribute = underlyCurrencyCode !
				id = underlyCurrencyCode
				table-column-width = 14
			{
				--- TableColumnItem ---
					item-column = underlyCurrencyCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = typecode !
				column-type = domain !
				domainAttribute = typecode !
				id = typecode
				table-column-width = 14
			{
				--- TableColumnItem ---
					item-column = typecode
					previewValue = value
			}
			--- TableColumn ---
				column-name = thirdCode !
				column-type = domain !
				domainAttribute = thirdCode !
				id = thirdCode
				table-column-width = 14
			{
				--- TableColumnItem ---
					item-column = thirdCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = marketThirdCode !
				column-type = domain !
				domainAttribute = marketThirdCode !
				id = marketThirdCode
				table-column-width = 14
			{
				--- TableColumnItem ---
					item-column = marketThirdCode
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = currencyCode
				sort-rank = 1
			--- TableSort ---
				sort-column-name = exchD
				sort-rank = 2
			--- TableSort ---
				sort-column-name = underlyCurrencyCode
				sort-rank = 3
			--- TableSort ---
				sort-column-name = typecode
				sort-rank = 4
			--- TableSort ---
				sort-column-name = thirdCode
				sort-rank = 5
		}
	}
}