# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	containment = container
	domainEntity = "AAADSStrategyAdmin:StrategyAdminEditObjectivesList"
	cssClass = nodeco
	bean-define = DSBean.AAADSStrategyAdmin.StrategyAdminEditObjectivesList
	bean-name = StrategyAdminEditObjectivesList
	id = ObjectivesView_o_x_0
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			table-editable-dataset = "AAADSStrategyElement:StrategyElementAdmin"
			table-format-identifier = id
			table-row-identifier = id
			id = id
			table-column-count = 10 !
			table-columns-width = "10,10,10,10,10,10,10,10,10,10" !
		{
			--- TableColumn ---
				labels en = "Market Segment", fr = "Segment de marché", de = Marktsegment
				column-display-grouping = true
				column-name = GROUPING
				column-type = placeholder !
				type = text
				column-locked = true
				column-sortable = false !
				id = k_WeY
				table-column-width = 10
				tid = 270535851138826
			{
				--- TableGroup ---
					aggregateData = false
					group-column-name = MARKET_STRUCTURE
					group-sorting-column-name = recomNatE
					group-sorting-direction = ascending
					hierarchy = true
					group-rank = 1
			}
			--- TableColumn ---
				column-name = priorityN !
				column-type = domain !
				domainAttribute = priorityN !
				format = integer
				type = text
				column-sortable = false
				id = priorityN
				table-column-width = 10
			{
				--- TableColumnText ---
					item-column = priorityN
					table-column-item-dataset-attribute = priorityN
					columns = 5
					format = integer
					previewValue = value
					type = integer
					chars = 5
			}
			--- TableColumn ---
				column-name = valueN !
				column-type = domain !
				domainAttribute = valueN !
				format = decimal.detailed
				type = text
				column-sortable = false
				id = valueN
				table-column-width = 10
			{
				--- TableColumnText ---
					item-column = valueN
					table-column-item-dataset-attribute = valueN
					columns = 22
					format = decimal.2-digits
					previewValue = value
					scale = 2
					type = decimal
					chars = 22
					enabled = conditional
					enabledIsBasedOn = advanced
					enabledIsBasedOn-advanced = "conditionVal = _e.getState() == 2;"
				{
					Event OnChange (sumTreeCol)
				}
			}
			--- TableColumn ---
				column-name = fluctMarginN !
				column-type = domain !
				domainAttribute = fluctMarginN !
				format = decimal.detailed
				type = text
				column-sortable = false
				id = fluctMarginN
				table-column-width = 10
			{
				--- TableColumnText ---
					item-column = fluctMarginN
					table-column-item-dataset-attribute = fluctMarginN
					columns = 22
					format = decimal.2-digits
					previewValue = value
					type = decimal
					chars = 22
			}
			--- TableColumn ---
				column-name = criticalnessELabel !
				column-type = domain !
				domainAttribute = criticalnessELabel !
				type = text
				id = criticalnessELabel
				table-column-width = 10
			{
				--- TableColumnCombobox ---
					item-column = criticalnessELabel
					table-column-item-dataset-attribute = criticalnessE
					previewValue = value
			}
			--- TableColumn ---
				column-name = benchDimensionELabel !
				column-type = domain !
				domainAttribute = benchDimensionELabel !
				type = text
				id = benchDimensionELabel
				table-column-width = 10
			{
				--- TableColumnCombobox ---
					item-column = benchDimensionELabel
					table-column-item-dataset-attribute = benchDimensionE
					previewValue = value
				{
					Event OnChange (submit)
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						widget-group-ref = form
						target = self
						param = "flow-action=benchReload"
						only-changed = true
						modal = false
						prevalidate = false
					}
				}
			}
			--- TableColumn ---
				column-name = BENCH_OBJECT_CODE !
				column-type = domain !
				domainAttribute = BENCH_OBJECT_CODE !
				type = text
				id = BENCH_OBJECT_CODE
				table-column-width = 10
			{
				--- TableColumnSearch ---
					item-column = BENCH_OBJECT_CODE
					table-column-item-dataset-attribute = benchStrategy
					previewValue = value
					enabled = conditional
					enabledIsBasedOn = advanced
					widgetGroup = formSearch
					enabledIsBasedOn-advanced = "if(<bean:get-property bean=\"StrategyAdminEditObjectivesList\" property=\"benchDimensionE\"/> != null &amp;&amp; \"3\".equals(<bean:get-property bean=\"StrategyAdminEditObjectivesList\" property=\"benchDimensionE\"/>.toString()))\r\n\tconditionVal=true;\r\nelse\r\n\tconditionVal=false;"
					auto-delay = 4
					nb-chars = 1
					outputDesign = "" !
					resource:///Default/autocompleteoutput/Strategy.module
				{
					Event Search (submit)
					{
						method = post
						call-URI = /wui/activity/aaa/pageflow/search-pageflow-Lookup/Lookup
						widget-group-ref = form
						target = popup
						param = "flow-action=search"
						only-changed = true
						modal = false
						prevalidate = false
						Query.parentWidgetValue1Id = "formSearch.<bean:get-property bean=\"StrategyElementAdmin\" property=\"id\"/>.bench_object_code" ud
						Snippet Query
						queryAttributes = "extDenomination,name,code,natureE"
						queryMappings = id
						queryOutputModule = "" !
						resource:///Default/module/aaa/administration/strategy/search/StrategySearch.module
						Snippet FilterSet
						id = fs_ebr
						level = 1
						targetDataset = "AAADSStrategy:StrategySearchCriteria"
						{
							Snippet Filter
							attribute = searchCode
							editMode = editable
							filterValue = "valueOf(formSearch.<bean:get-property bean=\"StrategyElementAdmin\" property=\"id\"/>.bench_object_code)"
							operator = LIKE
						}
					}
				}
				--- TableColumnSearch ---
					item-column = BENCH_OBJECT_CODE
					table-column-item-dataset-attribute = benchInstr
					previewValue = value
					enabled = conditional
					enabledIsBasedOn = advanced
					widgetGroup = formSearch
					enabledIsBasedOn-advanced = "if(<bean:get-property bean=\"StrategyAdminEditObjectivesList\" property=\"benchDimensionE\"/> != null &amp;&amp; \"2\".equals(<bean:get-property bean=\"StrategyAdminEditObjectivesList\" property=\"benchDimensionE\"/>.toString()))\r\n\tconditionVal=true;\r\nelse\r\n\tconditionVal=false;"
					auto-delay = 4
					nb-chars = 1
					outputDesign = "" !
					resource:///Default/autocompleteoutput/Instrument.module
				{
					Event Search (submit)
					{
						method = post
						call-URI = /wui/activity/aaa/pageflow/search-pageflow-Lookup/Lookup
						widget-group-ref = form
						target = popup
						param = "flow-action=search"
						only-changed = true
						modal = false
						prevalidate = false
						Query.parentWidgetValue1Id = "formSearch.<bean:get-property bean=\"StrategyElementAdmin\" property=\"id\"/>.bench_object_code" ud
						Snippet Query
						queryAttributes = "extDenomination,name,code,natureE"
						queryMappings = id
						queryOutputModule = "" !
						resource:///Default/module/aaa/administration/instrument/search/InstrumentSearch.module
						Snippet FilterSet
						id = fs_1WE
						level = 1
						targetDataset = "AAADSInstrument:InstrumentSearchCriteriaAll"
						{
							Snippet Filter
							attribute = searchCode
							editMode = editable
							filterValue = "valueOf(formSearch.<bean:get-property bean=\"StrategyElementAdmin\" property=\"id\"/>.bench_object_code)"
							operator = LIKE
						}
					}
				}
			}
			--- TableColumn ---
				column-name = benchDimensionE !
				column-type = domain !
				domainAttribute = benchDimensionE !
				type = text
				column-visibility = never-visible
				id = benchDimensionE
				table-column-width = 10
			{
				--- TableColumnItem ---
					item-column = benchDimensionE
					previewValue = value
			}
			--- TableColumn ---
				column-name = id !
				column-type = domain !
				domainAttribute = id !
				format = integer
				type = text
				column-visibility = never-visible
				id = id
				table-column-width = 10
			{
				--- TableColumnItem ---
					item-column = id
					previewValue = value
			}
			--- TableColumn ---
				column-name = rankN !
				column-type = domain !
				domainAttribute = rankN !
				format = integer
				type = text
				column-is-part-of-filter = false
				id = rankN
				table-column-width = 10
			{
				--- TableColumnItem ---
					item-column = rankN
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = rankN
				sort-rank = 1
		}
	}
}