# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Strategy Link Definition", fr = "Définition du lien de stratégie", de = "Strategieverknüpfung Bestimmung"
	containment = container
	domainEntity = "AAADSStrategyLink:StrategyLinkDetails"
	bean-define = DSBean.AAADSStrategyLink.StrategyLinkDetails
	bean-name = StrategyLinkDetails
	id = StrategyLinkCreate_R_8XF
	tid = 100315762206381
{
	--- Box ---
		boxType = vertical
	{
		--- Box ---
			labels en = Definition, fr = Définition, de = Bestimmung
			tid = 100315764054459
		{
			--- Include ---
				includeSrc = "" !
				resource:///Default/module/aaa/administration/strategylink/StrategyLinkDefinition.module
		}
		--- Conditional ---
			indexOfSelectedChild = 0
		{
			--- ConditionalBody ---
				conditionLang = DSEL
				javaCode = "StrategyLinkDetails.strategy!=null"
				technicalName = "Associated Strategy Selected"
				boxType = vertical
				isWidgetSelected = true
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/strategylink/AssociatedStrategyDetails.module
			}
		}
		--- Include ---
			includeSrc = "" !
			resource:///default/portfolio/administration/ButtonCreateStrategyLink.fragment
	}
}