# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSRating:RatingList"
	bean-define = DSBean.AAADSRating.RatingList
	bean-name = RatingList
	id = RatingList_T_J7G
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			id = a_2L9
			table-column-count = 3 !
			table-columns-width = "33,33,33" !
		{
			--- TableColumn ---
				labels de = Kodifizierung
				column-name = codificationCode !
				column-type = domain !
				domainAttribute = codificationCode !
				id = codificationCode
				table-column-width = 33
				tid = 20603977409419
			{
				--- TableColumnItem ---
					item-column = codificationCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = rankN !
				column-type = domain !
				domainAttribute = rankN !
				id = rankN
				table-column-width = 33
			{
				--- TableColumnItem ---
					item-column = rankN
					format = integer
					previewValue = value
			}
			--- TableColumn ---
				column-name = code !
				column-type = domain !
				domainAttribute = code !
				id = code
				table-column-width = 33
			{
				--- TableColumnItem ---
					item-column = code
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = codificationCode
				sort-rank = 1
			--- TableSort ---
				sort-column-name = rankN
				sort-rank = 2
			--- TableSort ---
				sort-column-name = code
				sort-rank = 3
		}
	}
}