# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSDictAttribute:DictAttributeList"
	bean-define = DSBean.AAADSDictAttribute.DictAttributeList
	bean-name = DictAttributeList
	id = DictAttributeList_i13O3
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			id = Re__8
			table-column-count = 2 !
			table-columns-width = "50,50" !
		{
			--- TableColumn ---
				column-name = dictEntityName !
				column-type = domain !
				domainAttribute = dictEntityName !
				id = dictEntityName
				table-column-width = 50
			{
				--- TableColumnItem ---
					item-column = dictEntityName
					previewValue = value
			}
			--- TableColumn ---
				column-name = name !
				column-type = domain !
				domainAttribute = name !
				id = name
				table-column-width = 50
			{
				--- TableColumnItem ---
					item-column = name
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = dictEntityName
				sort-rank = 1
			--- TableSort ---
				sort-column-name = name
				sort-rank = 2
		}
	}
}