# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Intermediate Benchmark Attribution Performance Effect 5 Details", fr = "Détails de l\'effet 5 de l\'attribution de performance (benchmarks intermédiaires)", de = "Mehrstufige Performance Attribution mit Details des Effekts 5"
	domainEntity = "AAADSPerformance:PerformanceIBPAEffectFocusDetails"
	bean-define = DSBean.AAADSPerformance.PerformanceIBPAEffectFocusDetails
	bean-name = PerformanceIBPAEffectFocusDetails
	id = PerformanceIBPAFocusOnEffect5PerMktSeg_lS_dD
	tid = 24803557910366
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			table-page-size = 100
			id = WS_OP
			table-column-count = 21 !
			table-columns-width = "4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4" !
		{
			--- TableColumn ---
				labels en = "Market Segment / Period", fr = "Segment de marché / période", de = "Marktsegment / Periode"
				column-display-grouping = true
				column-name = GROUPING
				column-type = placeholder !
				type = text
				column-locked = true
				column-sortable = false !
				id = cJ8G_
				table-column-width = 4
				tid = 24460738516817
			{
				--- TableGroup ---
					aggregateData = false
					group-column-name = PERIOD
					group-sorting-column-name = PERIOD_SORT
					group-sorting-direction = ascending
					hierarchy = true
					group-rank = 1
			}
			--- TableColumn ---
				labels en = "Initial Market Value", fr = "Valeur d\'inventaire initiale", de = Anfangs-Marktwert
				column-name = IntialMarketValue
				type = amount
				column-sortable = false
				id = P_873
				column-computation = make-amount
				column-computation-parameters = "INITIAL_MARKET_VALUE,REF_CURRENCY"
				table-column-width = 4
				tid = 24460738971408
			{
				--- TableColumnItem ---
					item-column = IntialMarketValue
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Final Market Value", fr = "Valeur d\'inventaire finale", de = End-Marktwert
				column-name = FinalMarketValue
				type = amount
				column-sortable = false
				id = s8n_7
				column-computation = make-amount
				column-computation-parameters = "FINAL_MARKET_VALUE,REF_CURRENCY"
				table-column-width = 4
				tid = 24460740911727
			{
				--- TableColumnItem ---
					item-column = FinalMarketValue
					previewValue = value
			}
			--- TableColumn ---
				column-name = WEIGHT !
				column-type = domain !
				domainAttribute = WEIGHT !
				type = text
				column-sortable = false
				id = WEIGHT
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = WEIGHT
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = PTF_RETURN !
				column-type = domain !
				domainAttribute = PTF_RETURN !
				type = text
				column-sortable = false
				id = PTF_RETURN
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = PTF_RETURN
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = PTF_RETURN_CONTRIBUTION !
				column-type = domain !
				domainAttribute = PTF_RETURN_CONTRIBUTION !
				type = text
				column-sortable = false
				id = PTF_RETURN_CONTRIBUTION
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = PTF_RETURN_CONTRIBUTION
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = PTF_DURATION !
				column-type = domain !
				domainAttribute = PTF_DURATION !
				type = text
				column-sortable = false
				id = PTF_DURATION
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = PTF_DURATION
					previewValue = value
			}
			--- TableColumn ---
				column-name = PTF_DURATION_CONTRIBUTION !
				column-type = domain !
				domainAttribute = PTF_DURATION_CONTRIBUTION !
				type = text
				column-sortable = false
				id = PTF_DURATION_CONTRIBUTION
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = PTF_DURATION_CONTRIBUTION
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_WEIGHT !
				column-type = domain !
				domainAttribute = B1_WEIGHT !
				type = text
				column-sortable = false
				id = B1_WEIGHT
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = B1_WEIGHT
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_RETURN !
				column-type = domain !
				domainAttribute = B1_RETURN !
				type = text
				column-sortable = false
				id = B1_RETURN
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = B1_RETURN
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_RETURN_CONTRIBUTION !
				column-type = domain !
				domainAttribute = B1_RETURN_CONTRIBUTION !
				type = text
				column-sortable = false
				id = B1_RETURN_CONTRIBUTION
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = B1_RETURN_CONTRIBUTION
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_DURATION !
				column-type = domain !
				domainAttribute = B1_DURATION !
				format = percentTA
				type = text
				column-sortable = false
				id = B1_DURATION
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = B1_DURATION
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_DURATION_CONTRIBUTION !
				column-type = domain !
				domainAttribute = B1_DURATION_CONTRIBUTION !
				format = percentTA
				type = text
				column-sortable = false
				id = B1_DURATION_CONTRIBUTION
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = B1_DURATION_CONTRIBUTION
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_BENCHMARK_FACTOR !
				column-type = domain !
				domainAttribute = B1_BENCHMARK_FACTOR !
				type = text
				column-sortable = false
				id = B1_BENCHMARK_FACTOR
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = B1_BENCHMARK_FACTOR
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = IB5_EFFECT_FOCUS_DENOM !
				column-type = domain !
				domainAttribute = IB5_EFFECT_FOCUS_DENOM !
				type = text
				column-sortable = false
				id = IB5_EFFECT_FOCUS_DENOM
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = IB5_EFFECT_FOCUS_DENOM
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_IB5_WEIGHT !
				column-type = domain !
				domainAttribute = B1_IB5_WEIGHT !
				type = text
				column-sortable = false
				id = B1_IB5_WEIGHT
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = B1_IB5_WEIGHT
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_IB5_RETURN !
				column-type = domain !
				domainAttribute = B1_IB5_RETURN !
				type = text
				column-sortable = false
				id = B1_IB5_RETURN
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = B1_IB5_RETURN
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_IB5_CONTRIBUTION !
				column-type = domain !
				domainAttribute = B1_IB5_CONTRIBUTION !
				type = text
				column-sortable = false
				id = B1_IB5_CONTRIBUTION
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = B1_IB5_CONTRIBUTION
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_IB5_DURATION !
				column-type = domain !
				domainAttribute = B1_IB5_DURATION !
				type = text
				column-sortable = false
				id = B1_IB5_DURATION
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = B1_IB5_DURATION
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_IB5_DURATION_CONTRIBUTION !
				column-type = domain !
				domainAttribute = B1_IB5_DURATION_CONTRIBUTION !
				type = text
				column-sortable = false
				id = B1_IB5_DURATION_CONTRIBUTION
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = B1_IB5_DURATION_CONTRIBUTION
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_IB5_EFFECT !
				column-type = domain !
				domainAttribute = B1_IB5_EFFECT !
				type = text
				column-sortable = false
				id = B1_IB5_EFFECT
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = B1_IB5_EFFECT
					format = percentTA
					previewValue = value
			}
			--- TableKeepFilter ---
				keep-filter-column-name = PERIOD_FILTER
				keep-filter-operand = 1
			--- TableSort ---
				sort-column-name = PERIOD_SORT
				sort-rank = 2
			--- TableSort ---
				sort-column-name = INITIAL_DATE
				sort-rank = 3
		}
	}
}