# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels de = "Mehrstufige Performance Attribution mit Details des Effekts 4", fr = "Détails de l\'effet 4 de l\'attribution de performance (benchmarks intermédiaires)", en = "Intermediate Benchmark Attribution Performance Effect 4 Details"
	domainEntity = "AAADSPerformance:PerformanceIBPAEffectFocusDetails"
	bean-define = DSBean.AAADSPerformance.PerformanceIBPAEffectFocusDetails
	bean-name = PerformanceIBPAEffectFocusDetails
	id = PerformanceIBPAFocusOnEffect4PerPeriod_L_Sp_
	tid = 24773064969988
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			table-page-size = 100
			id = L___9
			table-column-count = 21 !
			table-columns-width = "4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4" !
		{
			--- TableColumn ---
				labels en = "Period / Market Segment", fr = "Période / segment de marché", de = "Periode / Marktsegment"
				column-display-grouping = true
				column-name = GROUPING
				column-type = placeholder !
				type = text
				column-locked = true
				column-sortable = false !
				id = Fm6__
				table-column-width = 4
				tid = 24458769859690
			{
				--- TableGroup ---
					aggregateData = false
					group-column-name = MARKET_SEGMENT
					group-sorting-column-name = MARKET_SEGMENT_SORT
					group-sorting-direction = ascending
					hierarchy = true
					group-rank = 1
			}
			--- TableColumn ---
				labels en = "Initial Market Value", fr = "Valeur d\'inventaire initiale", de = Anfangs-Marktwert
				column-name = IntialMarketValue
				type = amount
				column-sortable = false
				id = p2RG_
				column-computation = make-amount
				column-computation-parameters = "INITIAL_MARKET_VALUE,REF_CURRENCY"
				table-column-width = 4
				tid = 24458770288158
			{
				--- TableColumnItem ---
					item-column = IntialMarketValue
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Final Market Value", fr = "Valeur d\'inventaire finale", de = End-Marktwert
				column-name = FinalMarketValue
				type = amount
				column-sortable = false
				id = a_99q
				column-computation = make-amount
				column-computation-parameters = "FINAL_MARKET_VALUE,REF_CURRENCY"
				table-column-width = 4
				tid = 24458772211494
			{
				--- TableColumnItem ---
					item-column = FinalMarketValue
					previewValue = value
			}
			--- TableColumn ---
				column-name = WEIGHT !
				column-type = domain !
				domainAttribute = WEIGHT !
				type = text
				column-sortable = false
				id = WEIGHT
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = WEIGHT
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = PTF_RETURN !
				column-type = domain !
				domainAttribute = PTF_RETURN !
				type = text
				column-sortable = false
				id = PTF_RETURN
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = PTF_RETURN
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = PTF_RETURN_CONTRIBUTION !
				column-type = domain !
				domainAttribute = PTF_RETURN_CONTRIBUTION !
				type = text
				column-sortable = false
				id = PTF_RETURN_CONTRIBUTION
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = PTF_RETURN_CONTRIBUTION
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = PTF_DURATION !
				column-type = domain !
				domainAttribute = PTF_DURATION !
				type = text
				column-sortable = false
				id = PTF_DURATION
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = PTF_DURATION
					previewValue = value
			}
			--- TableColumn ---
				column-name = PTF_DURATION_CONTRIBUTION !
				column-type = domain !
				domainAttribute = PTF_DURATION_CONTRIBUTION !
				type = text
				column-sortable = false
				id = PTF_DURATION_CONTRIBUTION
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = PTF_DURATION_CONTRIBUTION
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_WEIGHT !
				column-type = domain !
				domainAttribute = B1_WEIGHT !
				type = text
				column-sortable = false
				id = B1_WEIGHT
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = B1_WEIGHT
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_RETURN !
				column-type = domain !
				domainAttribute = B1_RETURN !
				type = text
				column-sortable = false
				id = B1_RETURN
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = B1_RETURN
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_RETURN_CONTRIBUTION !
				column-type = domain !
				domainAttribute = B1_RETURN_CONTRIBUTION !
				type = text
				column-sortable = false
				id = B1_RETURN_CONTRIBUTION
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = B1_RETURN_CONTRIBUTION
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_DURATION !
				column-type = domain !
				domainAttribute = B1_DURATION !
				format = percentTA
				type = text
				column-sortable = false
				id = B1_DURATION
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = B1_DURATION
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_DURATION_CONTRIBUTION !
				column-type = domain !
				domainAttribute = B1_DURATION_CONTRIBUTION !
				format = percentTA
				type = text
				column-sortable = false
				id = B1_DURATION_CONTRIBUTION
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = B1_DURATION_CONTRIBUTION
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_BENCHMARK_FACTOR !
				column-type = domain !
				domainAttribute = B1_BENCHMARK_FACTOR !
				type = text
				column-sortable = false
				id = B1_BENCHMARK_FACTOR
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = B1_BENCHMARK_FACTOR
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = IB4_EFFECT_FOCUS_DENOM !
				column-type = domain !
				domainAttribute = IB4_EFFECT_FOCUS_DENOM !
				type = text
				column-sortable = false
				id = IB4_EFFECT_FOCUS_DENOM
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = IB4_EFFECT_FOCUS_DENOM
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_IB4_WEIGHT !
				column-type = domain !
				domainAttribute = B1_IB4_WEIGHT !
				type = text
				column-sortable = false
				id = B1_IB4_WEIGHT
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = B1_IB4_WEIGHT
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_IB4_RETURN !
				column-type = domain !
				domainAttribute = B1_IB4_RETURN !
				type = text
				column-sortable = false
				id = B1_IB4_RETURN
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = B1_IB4_RETURN
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_IB4_CONTRIBUTION !
				column-type = domain !
				domainAttribute = B1_IB4_CONTRIBUTION !
				type = text
				column-sortable = false
				id = B1_IB4_CONTRIBUTION
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = B1_IB4_CONTRIBUTION
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_IB4_DURATION !
				column-type = domain !
				domainAttribute = B1_IB4_DURATION !
				type = text
				column-sortable = false
				id = B1_IB4_DURATION
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = B1_IB4_DURATION
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_IB4_DURATION_CONTRIBUTION !
				column-type = domain !
				domainAttribute = B1_IB4_DURATION_CONTRIBUTION !
				type = text
				column-sortable = false
				id = B1_IB4_DURATION_CONTRIBUTION
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = B1_IB4_DURATION_CONTRIBUTION
					previewValue = value
			}
			--- TableColumn ---
				column-name = B1_IB4_EFFECT !
				column-type = domain !
				domainAttribute = B1_IB4_EFFECT !
				type = text
				column-sortable = false
				id = B1_IB4_EFFECT
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = B1_IB4_EFFECT
					format = percentTA
					previewValue = value
			}
			--- TableKeepFilter ---
				keep-filter-column-name = GLOBAL_FILTER
				keep-filter-operand = 0
			--- TableSort ---
				sort-column-name = MARKET_SEGMENT_SORT
				sort-rank = 3
			--- TableSort ---
				sort-column-name = INITIAL_DATE
				sort-rank = 2
		}
	}
}