# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "View Portfolio Details", fr = "Voir les détails du portefeuille", de = "Details des Portfolios ansehen"
	domainEntity = "AAADSPortfolio:PortfolioAll"
	cssClass = nodeco
	bean-define = DSBean.AAADSPortfolio.PortfolioAll
	bean-name = PortfolioAll
	id = PortfolioView_DBG7Y
	tid = 5571970622179
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- Include ---
			includeSrc = "" !
			resource:///default/portfolio/portfolioall/PortfolioIdentifierView.fragment
		--- Include ---
			includeSrc = "" !
			resource:///default/portfolio/portfolioall/PortfolioDetailSimplifiedView.fragment
	}
}