# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "View List Notepad", de = Notizen, fr = "Voir le bloc-note de la liste"
	containment = container
	domainEntity = "AAADSList:ListAll"
	cssClass = nodeco
	bean-define = DSBean.AAADSList.ListAll
	bean-name = ListAll
	id = ListNotepadView_Q_L_3
	tid = 115419380168987
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///default/list/listidentifier/ListIdentifierView.fragment
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/notepad/search/NotepadList.module
	}
}