# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "View List Identifier", de = "Listenidentifikator ansehen", fr = "Voir l\'identifiant de la liste"
	domainEntity = "AAAIdentifierDatasets:ListAAAIdentifier"
	cssClass = nodeco
	bean-define = DSBean.AAAIdentifierDatasets.ListAAAIdentifier
	bean-name = ListAAAIdentifier
	id = ListIdentifierView_nx731
	tid = 110191057591677
{
	--- Box ---
		boxType = vertical
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 6
			gridColumnsWidth = "10,10,10,10,10,50" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 10
			{
				--- LabelDomain ---
					domainAttribute = code !
					for = code
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					required = true
			}
			--- GridCell ---
				gridColumnWidth = 10
			{
				--- TextField ---
					domainAttribute = code !
					horizontalAlignment = "${corporatehalign}"
					type = text
					chars = 20
					editable = false
					required = true
					bean-property = code
					id = code
			}
			--- GridCell ---
				gridColumnWidth = 10
			{
				--- LabelDomain ---
					domainAttribute = name !
					for = name
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					required = true
			}
			--- GridCell ---
				gridColumnWidth = 10
			{
				--- TextField ---
					domainAttribute = name !
					horizontalAlignment = "${corporatehalign}"
					type = text
					chars = 20
					editable = false
					required = true
					bean-property = name
					id = name
			}
			--- GridCell ---
				gridColumnWidth = 10
			{
				--- LabelDomain ---
					domainAttribute = denom !
					for = denom
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
			}
			--- GridCell ---
				gridColumnWidth = 50
			{
				--- TextField ---
					domainAttribute = denom !
					columns = 180
					horizontalAlignment = "${corporatehalign}"
					type = text
					chars = 80
					editable = false
					bean-property = denom
					id = denom
			}
		}
	}
}