# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "View List", de = "Liste ansehen", fr = "Voir la liste"
	containment = container
	domainEntity = "AAADSList:ListAll"
	bean-define = DSBean.AAADSList.ListAll
	bean-name = ListAll
	id = ListView_gro_8
	tid = 110088508888699
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			id = eS32Z
			indexOfSelectedChild = 2
		{
			--- Tab ---
				labels en = Detail, de = Detail, fr = Détail
				boxType = vertical
				id = tab_T7Ku_
				isWidgetVisible = false
				tid = 110310622093869
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/list/listall/ListIdentifierView.fragment
				--- Include ---
					includeSrc = "" !
					resource:///default/list/listall/ListDetailView.fragment
			}
			--- Tab ---
				labels en = Composition, de = Zusammensetzung, fr = Composition
				id = tab_Y_x_h
				isWidgetVisible = false
				tid = 110322177383717
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/list/view/ListCompoView.module
			}
			--- Tab ---
				labels en = Notepad, de = Notiz, fr = Bloc-note
				id = tab_Hya6K
				isWidgetSelected = true
				tid = 110334398867733
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/list/view/ListNotepadView.module
			}
		}
	}
}