# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "View List Detail", de = "Listendetails ansehen", fr = "Voir le détail de la liste"
	domainEntity = "AAADSList:ListAll"
	cssClass = nodeco
	bean-define = DSBean.AAADSList.ListAll
	bean-name = ListAll
	id = ListDetailView_cap_9
	tid = 110065261648337
{
	--- Box ---
		boxType = vertical
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 6
			gridColumnsWidth = "16,16,16,16,16,16" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 16
			--- GridCell ---
				gridColumnWidth = 16
			--- GridCell ---
				gridColumnWidth = 16
			--- GridCell ---
				gridColumnWidth = 16
			--- GridCell ---
				gridColumnWidth = 16
			--- GridCell ---
				gridColumnWidth = 16
		}
	}
}