# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "View List Composition", de = "Listenzusammensetzung ansehen", fr = "Voir la composition de la liste"
	containment = container
	domainEntity = "AAADSList:ListAll"
	cssClass = nodeco
	bean-define = DSBean.AAADSList.ListAll
	bean-name = ListAll
	id = ListCompoView_G_6s9
	tid = 110380905536038
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///default/list/listidentifier/ListIdentifierView.fragment
	}
}