# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = Context, fr = Contexte, de = Kontext
	containment = container
	domainEntity = "AAADSDomain:DomainContext"
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = Context_B_340
	documentation = "Domain Context"
	tid = 591578814859926
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TabbedPane ---
			id = Xo8_7
			indexOfSelectedChild = 0
		{
			--- Tab ---
				labels fr = Base, en = Basic, de = Basis
				boxType = vertical
				id = tab_moy1w
				isWidgetSelected = true
				tid = 6230606677809
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 3
					gridColumnsWidth = "25,20,55" !
					gridRowCount = 1
					verticalAlignment = lead
				{
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainPortfolioDimensionView.fragment
					}
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainOrderAllocationMethodView.fragment
					}
					--- GridCell ---
						gridColumnWidth = 55
					{
						--- Conditional ---
							indexOfSelectedChild = 0
						{
							--- ConditionalBody ---
								conditionLang = DSEL
								javaCode = "DomainContext.orderAllocNatE == AAAEnumerations::DomainAAAOrderAllocNatE::ResultingCashPercentOfPort\r\n||\r\nDomainContext.orderAllocNatE == AAAEnumerations::DomainAAAOrderAllocNatE::InstrResultingOfMktSgt\r\n||\r\nDomainContext.orderAllocNatE == AAAEnumerations::DomainAAAOrderAllocNatE::ResultingMktSegPercentOfPort"
								technicalName = "CashRes%Ptf, InstrRes%MS, MSRes%Ptf"
								boxType = vertical
								isWidgetSelected = true
							{
								--- Include ---
									includeSrc = "" !
									resource:///default/domain/basicelements/DomainObjectiveWeight.fragment
							}
						}
					}
				}
				--- Grid ---
					cssClass = blank
					gridColumnCount = 2
					gridColumnsWidth = "45,55" !
					gridRowCount = 1
				{
					--- GridCell ---
						gridColumnWidth = 45
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainSessionDescription.fragment
					}
					--- GridCell ---
						gridColumnWidth = 55
					{
						--- Conditional ---
							indexOfSelectedChild = 1
						{
							--- ConditionalBody ---
								conditionLang = DSEL
								javaCode = "DomainContext.orderAllocNatE == AAAEnumerations::DomainAAAOrderAllocNatE::InstrResultingOfMktSgt\r\n||\r\nDomainContext.orderAllocNatE == AAAEnumerations::DomainAAAOrderAllocNatE::InstrResPercentOfStratMktSgt\r\n||\r\nDomainContext.orderAllocNatE == AAAEnumerations::DomainAAAOrderAllocNatE::ResultingMktSegPercentOfPort"
								technicalName = "InstrRes%MS, InstrRes%StratMS, MSRes%Ptf"
								isWidgetVisible = false
							{
								--- Box ---
									labels en = "Market Segment", fr = "Segment de marché", de = Marktsegment
									boxType = vertical
									tid = 967316700332084
								{
									--- Include ---
										domainAssociation = marketSegment
										includeSrc = "" !
										resource:///default/defaultFragments/MarketSegmentIdentifier.fragment
										bean-property-prefix = marketSegment.
								}
								--- Conditional ---
									indexOfSelectedChild = 0
								{
									--- ConditionalBody ---
										conditionLang = DSEL
										javaCode = "DomainContext.marketSegment != NULL"
										technicalName = "MktSgt not empty"
										boxType = vertical
										isWidgetSelected = true
									{
										--- Box ---
											labels en = "Recommendation List", fr = "Liste de recommandation", de = Empfehlungsliste
											tid = 967316701323120
										{
											--- Include ---
												domainAssociation = strategyDimStrategy
												includeSrc = "" !
												resource:///default/defaultFragments/RecommendationListBasedOnMktSgtIdentifier.fragment
												bean-property-prefix = strategyDimStrategy.
											--- Button ---
												labels en = Load, de = Laden, fr = Charger toolTips en = "Load Selected Recommendation List", fr = "Charger la liste de recommandation sélectionnée", de = "Empfehlungsliste laden"
												enabled = conditional
												enabledIsBasedOn = advanced
												id = btn_Oo9_W
												enabledIsBasedOn-advanced = "if (null!=<bean:get-property bean=\"DomainContext\" property=\"strategyDimStrategy\"/>) {\r\n\tconditionVal = true;\r\n} else {\r\n\tconditionVal = false;\r\n}"
												tid = 628392412502705
											{
												Event OnClick (submit)
												{
													method = post
													call-URI = "<pageflow:continuation/>"
													widget-group-ref = form
													target = self
													modal = false
													only-changed = true
													prevalidate = false
													param = "flow-action=loadrecomlist"
												}
											}
											--- Glue ---
										}
									}
								}
							}
							--- ConditionalBody ---
								conditionLang = DSEL
								javaCode = "DomainContext.orderAllocNatE != AAAEnumerations::DomainAAAOrderAllocNatE::Arbitrage\r\nAND\r\nDomainContext.orderAllocNatE != AAAEnumerations::DomainAAAOrderAllocNatE::Conversion"
								technicalName = "Other (except arbitrage & conversion)"
								boxType = vertical
								isWidgetSelected = true
							{
								--- Box ---
									labels en = "Recommendation List", fr = "Liste de recommandation", de = Empfehlungsliste
									tid = 967316702351368
								{
									--- Include ---
										domainAssociation = strategyDimStrategy
										includeSrc = "" !
										resource:///default/defaultFragments/RecommendationListIdentifier.fragment
										bean-property-prefix = strategyDimStrategy.
									--- Button ---
										labels en = Load, de = Laden, fr = Charger toolTips en = "Load Selected Recommendation List", fr = "Charger la liste de recommandation sélectionnée", de = "Empfehlungsliste laden"
										enabled = conditional
										enabledIsBasedOn = advanced
										id = btn_um4_3
										enabledIsBasedOn-advanced = "if (null!=<bean:get-property bean=\"DomainContext\" property=\"strategyDimStrategy\"/>) {\r\n\tconditionVal = true;\r\n} else {\r\n\tconditionVal = false;\r\n}"
										tid = 1217406443612331
									{
										Event OnClick (submit)
										{
											method = post
											call-URI = "<pageflow:continuation/>"
											widget-group-ref = form
											target = self
											modal = false
											only-changed = true
											prevalidate = false
											param = "flow-action=loadrecomlist"
										}
									}
									--- Glue ---
								}
							}
						}
					}
				}
			}
			--- Tab ---
				labels fr = Avancé, en = Advanced, de = Erweitert
				id = tab_F__8Y
				isWidgetVisible = false
				tid = 6230609051780
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 4
					gridColumnsWidth = "20,20,20,40" !
					gridRowCount = 1
				{
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainMinStatus.fragment
					}
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainMaxStatus.fragment
					}
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainGenGlobalOrder.fragment
					}
					--- GridCell ---
						gridColumnWidth = 40
					{
						--- Conditional ---
							indexOfSelectedChild = 0
						{
							--- ConditionalBody ---
								conditionLang = DSEL
								javaCode = "DomainContext.orderAllocNatE!=AAAEnumerations::DomainAAAOrderAllocNatE::GlobalOrderQuantity"
								technicalName = "Not Global Order Qty"
								isWidgetSelected = true
							{
								--- Grid ---
									cssClass = blank
									gridColumnCount = 2
									gridColumnsWidth = "25,25" !
									gridRowCount = 1
									verticalAlignment = lead
								{
									--- GridCell ---
										gridColumnWidth = 25
									{
										--- Include ---
											includeSrc = "" !
											resource:///default/domain/basicelements/DomainMinOrderAmount.fragment
									}
									--- GridCell ---
										gridColumnWidth = 25
									{
										--- Include ---
											includeSrc = "" !
											resource:///default/domain/basicelements/DomainMinOrderPercent.fragment
									}
								}
							}
						}
					}
				}
			}
		}
		--- Box ---
		{
			--- Button ---
				labels en = Execute, de = Ausführen, fr = Exécuter toolTips en = "Execute Allocate Order Function", fr = "Exécuter la fonction d\'allocation d\'ordres"
				id = btn_c91_X
				tid = 575151884304081
			{
				Event OnClick (submit)
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					widget-group-ref = form
					target = self
					flow-action = allocateorder ud
					modal = false
					only-changed = true
					prevalidate = false
				}
			}
			--- Glue ---
		}
	}
}