# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels fr = "Paramètres aditionnels", en = "Additional Parameters"
	containment = container
	domainEntity = "AAADSDomain:DomainContext"
	cssClass = nodeco
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = Context_B_340
	documentation = "Domain Context"
	tid = 6230607260723
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- Conditional ---
			indexOfSelectedChild = 0
		{
			--- ConditionalBody ---
				conditionLang = DSEL
				javaCode = "DomainContext.orderAllocNatE!=AAAEnumerations::DomainAAAOrderAllocNatE::GlobalOrderQuantity"
				technicalName = "Not Global Order Qty"
				isWidgetSelected = true
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 2
					gridColumnsWidth = "25,25" !
					gridRowCount = 1
					verticalAlignment = lead
				{
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainMinOrderAmount.fragment
					}
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainMinOrderPercent.fragment
					}
				}
			}
		}
	}
}