# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels fr = Contexte, en = Context, de = Kontext
	containment = container
	domainEntity = "AAADSDomain:DomainContext"
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = Context_B_340
	documentation = "Domain Context"
	tid = 6230607260723
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TabbedPane ---
			id = Xo8_7
			indexOfSelectedChild = 0
		{
			--- Tab ---
				labels fr = Base, en = Basic, de = Basis
				boxType = vertical
				id = tab_moy1w
				isWidgetSelected = true
				tid = 6230606587041
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 3
					gridColumnsWidth = "25,20,55" !
					gridRowCount = 1
					verticalAlignment = lead
				{
					--- GridCell ---
						gridColumnWidth = 25
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainPortfolioWithUpdateRightDimension.fragment
					}
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainOrderAllocationMethod.fragment
					}
					--- GridCell ---
						gridColumnWidth = 55
					{
						--- Conditional ---
							indexOfSelectedChild = 0
						{
							--- ConditionalBody ---
								conditionLang = DSEL
								javaCode = "DomainContext.orderAllocNatE == AAAEnumerations::DomainAAAOrderAllocNatE::ResultingCashPercentOfPort\r\n||\r\nDomainContext.orderAllocNatE == AAAEnumerations::DomainAAAOrderAllocNatE::InstrResultingOfMktSgt\r\n||\r\nDomainContext.orderAllocNatE == AAAEnumerations::DomainAAAOrderAllocNatE::ResultingMktSegPercentOfPort"
								technicalName = "CashRes%Ptf, InstrRes%MS, MSRes%Ptf"
								boxType = vertical
								isWidgetSelected = true
							{
								--- Include ---
									includeSrc = "" !
									resource:///default/domain/basicelements/DomainObjectiveWeight.fragment
							}
						}
					}
				}
				--- Grid ---
					cssClass = blank
					gridColumnCount = 2
					gridColumnsWidth = "45,55" !
					gridRowCount = 1
				{
					--- GridCell ---
						gridColumnWidth = 45
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainSessionDescription.fragment
					}
					--- GridCell ---
						gridColumnWidth = 55
					{
						--- Conditional ---
							indexOfSelectedChild = 1
						{
							--- ConditionalBody ---
								conditionLang = DSEL
								javaCode = "DomainContext.orderAllocNatE == AAAEnumerations::DomainAAAOrderAllocNatE::InstrResultingOfMktSgt\r\n||\r\nDomainContext.orderAllocNatE == AAAEnumerations::DomainAAAOrderAllocNatE::InstrResPercentOfStratMktSgt\r\n||\r\nDomainContext.orderAllocNatE == AAAEnumerations::DomainAAAOrderAllocNatE::ResultingMktSegPercentOfPort"
								technicalName = "InstrRes%MS, InstrRes%StratMS, MSRes%Ptf"
								isWidgetVisible = false
							{
								--- Box ---
									labels en = "Market Segment", fr = "Segment de marché", de = Marktsegment
									boxType = vertical
									tid = 2151556571270679
								{
									--- Include ---
										domainAssociation = marketSegment
										includeSrc = "" !
										resource:///default/defaultFragments/MarketSegmentIdentifier.fragment
										bean-property-prefix = marketSegment.
								}
								--- Conditional ---
									indexOfSelectedChild = 0
								{
									--- ConditionalBody ---
										conditionLang = DSEL
										javaCode = "DomainContext.marketSegment != NULL"
										technicalName = "MktSgt not empty"
										boxType = vertical
										isWidgetSelected = true
									{
										--- Box ---
											labels en = "Recommendation List", fr = "Liste de recommandation", de = Empfehlungsliste
											tid = 711826993699630
										{
											--- Include ---
												domainAssociation = strategyDimStrategy
												includeSrc = "" !
												resource:///default/defaultFragments/RecommendationListBasedOnMktSgtIdentifier.fragment
												bean-property-prefix = strategyDimStrategy.
											--- Glue ---
										}
									}
								}
							}
							--- ConditionalBody ---
								conditionLang = DSEL
								javaCode = "DomainContext.orderAllocNatE != AAAEnumerations::DomainAAAOrderAllocNatE::Arbitrage\r\nAND\r\nDomainContext.orderAllocNatE != AAAEnumerations::DomainAAAOrderAllocNatE::Conversion"
								technicalName = "Other (except arbitrage & conversion)"
								boxType = vertical
								isWidgetSelected = true
							{
								--- Box ---
									labels en = "Recommendation List", fr = "Liste de recommandation", de = Empfehlungsliste
									tid = 452311055617337
								{
									--- Include ---
										domainAssociation = strategyDimStrategy
										includeSrc = "" !
										resource:///default/defaultFragments/RecommendationListIdentifier.fragment
										bean-property-prefix = strategyDimStrategy.
									--- Glue ---
								}
							}
						}
					}
				}
			}
			--- Tab ---
				labels fr = Avancé, en = Advanced, de = Erweitert
				id = tab_F__8Y
				isWidgetVisible = false
				tid = 6230609097654
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 4
					gridColumnsWidth = "20,20,20,40" !
					gridRowCount = 1
				{
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainMinStatus.fragment
					}
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainMaxStatus.fragment
					}
					--- GridCell ---
						gridColumnWidth = 20
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainGenGlobalOrder.fragment
					}
					--- GridCell ---
						gridColumnWidth = 40
					{
						--- Conditional ---
							indexOfSelectedChild = 0
						{
							--- ConditionalBody ---
								conditionLang = DSEL
								javaCode = "DomainContext.orderAllocNatE!=AAAEnumerations::DomainAAAOrderAllocNatE::GlobalOrderQuantity"
								technicalName = "Not Global Order Qty"
								isWidgetSelected = true
							{
								--- Grid ---
									cssClass = blank
									gridColumnCount = 2
									gridColumnsWidth = "25,25" !
									gridRowCount = 1
									verticalAlignment = lead
								{
									--- GridCell ---
										gridColumnWidth = 25
									{
										--- Include ---
											includeSrc = "" !
											resource:///default/domain/basicelements/DomainMinOrderAmount.fragment
									}
									--- GridCell ---
										gridColumnWidth = 25
									{
										--- Include ---
											includeSrc = "" !
											resource:///default/domain/basicelements/DomainMinOrderPercent.fragment
									}
								}
							}
						}
					}
				}
			}
		}
		--- Box ---
		{
			--- Button ---
				labels en = Apply, de = Anwenden, fr = Appliquer toolTips de = "Domänen – Parameter anwenden", fr = "Appliquer les paramètres du domaine", en = "Apply domain parameters"
				id = btn_u7_hu
				tid = 341969491363119
			{
				Event OnClick (submit)
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					widget-group-ref = form
					target = self
					modal = false
					only-changed = true
					prevalidate = false
					param = "flow-action=create-instruction"
				}
			}
			--- Glue ---
		}
	}
}