# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels fr = "Vues résumées", en = "Summary Views", de = Zusammenfassung
	containment = container
	domainEntity = "AAADSValuation:ValuationSummaryList"
	bean-define = DSBean.AAADSValuation.ValuationSummaryList
	bean-name = ValuationSummaryList
	id = Summary_fr4__
	tid = 6229723488797
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TabbedPane ---
			id = d8x__
			indexOfSelectedChild = 1
		{
			--- Tab ---
				labels en = Portfolio, de = Portfolio, fr = Portefeuille
				boxType = vertical
				id = tab_summary_portfolio
				isWidgetVisible = false
				tid = 14603062195893
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/valuation/summary/ByPortfolio/ByPortfolioD.module
			}
			--- Tab ---
				labels en = Instrument, fr = Instrument, de = Instrument
				id = tab_summary_instrument
				isWidgetSelected = true
				tid = 13151930951280
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/valuation/summary/ByInstrument/InstrumentAccounting.module
			}
			--- Tab ---
				labels en = "Asset Class", de = Anlagekategorie, fr = "Catégorie d\'actif"
				boxType = vertical
				id = tab_summary_assetclass
				isWidgetVisible = false
				tid = 27175723336625
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/valuation/summary/DynamicByAssetClassCurrency/AssetClassCurrencyMatrix.module
				--- Code ---
					code = "<cinclude:include src=\"cocoon://module/aaa/corda/valuation/ByAssetClassCurrencyGraph\" />"
			}
			--- Tab ---
				labels en = Rating, de = Bonität, fr = Notation
				boxType = vertical
				id = tab_summary_rating
				isWidgetVisible = false
				tid = 28254193973535
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/valuation/summary/DynamicByRatingCurrency/RatingCurrencyMatrix.module
				--- Code ---
					code = "<cinclude:include src=\"cocoon://module/aaa/corda/valuation/ByRatingGraph\" />"
			}
			--- Tab ---
				labels en = Sector, de = Branche, fr = Secteur
				boxType = vertical
				id = tab_summary_sector
				isWidgetVisible = false
				tid = 28374667532046
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/valuation/summary/DynamicBySectorCurrency/SectorCurrencyMatrix.module
				--- Code ---
					code = "<cinclude:include src=\"cocoon://module/aaa/corda/valuation/BySectorGraph\" />"
			}
			--- Tab ---
				labels en = Region, de = Region, fr = Région
				boxType = vertical
				id = tab_summary_region
				isWidgetVisible = false
				tid = 11965698529841
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/valuation/summary/DynamicByRegionCurrency/RegionCurrencyMatrix.module
				--- Code ---
					code = "<cinclude:include src=\"cocoon://module/aaa/corda/valuation/ByRegionGraph\" />"
			}
			--- Tab ---
				labels en = Duration, de = Duration, fr = Duration
				boxType = vertical
				id = tab_summary_duration
				isWidgetVisible = false
				tid = 2393434441528
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/valuation/summary/DynamicByDurationCurrency/DurationCurrencyMatrix.module
				--- Code ---
					code = "<cinclude:include src=\"cocoon://module/aaa/corda/valuation/ByDurationGraph\" />"
			}
			--- Tab ---
				labels en = Maturity, de = Fälligkeit, fr = Echéance
				boxType = vertical
				id = tab_summary_maturity
				isWidgetVisible = false
				tid = 12100043252424
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/valuation/summary/DynamicByMaturityCurrency/MaturityCurrencyMatrix.module
				--- Code ---
					code = "<cinclude:include src=\"cocoon://module/aaa/corda/valuation/ByMaturityGraph\" />"
			}
		}
		--- Button ---
			labels en = "Exchange rates", fr = "Taux de change", de = Devisenkurs
			id = btn_ACa__
			tid = 63517561338577
		{
			Event OnClick (submit) S
			{
				method = post
				call-URI = "resource:///valuation/ValuationExchangeRate.pageflow"
				target = popup
				modal = false
				only-changed = false
				prevalidate = false
			}
		}
	}
}