# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels fr = "Vues résumées", en = "Summary Views", de = Zusammenfassung
	containment = container
	domainEntity = "AAADSValuation:ValuationSummaryList"
	bean-define = DSBean.AAADSValuation.ValuationSummaryList
	bean-name = ValuationSummaryList
	id = Summary_fr4__
	tid = 305256579326143
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TabbedPane ---
			id = d8x__
			indexOfSelectedChild = 1
		{
			--- Tab ---
				labels en = Portfolio, de = Portfolio, fr = Portefeuille
				boxType = vertical
				id = tab_summary_portfolio
				isWidgetVisible = false
				tid = 26675648209479
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/valuation/summary/ByPortfolio/ByPortfolioDList.module
			}
			--- Tab ---
				labels en = Instrument, fr = Instrument, de = Instrument
				id = tab_summary_instrument
				isWidgetSelected = true
				tid = 13026902371949
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/valuation/summary/ByInstrument/InstrumentAccountingList.module
			}
			--- Tab ---
				labels en = "Asset Class", de = Anlagekategorie, fr = "Catégorie d\'actif"
				boxType = vertical
				id = tab_summary_assetclass
				isWidgetVisible = false
				tid = 25254569208656
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/valuation/summary/DynamicByAssetClassCurrency/AssetClassCurrencyMatrix.module
				--- Code ---
					code = "<cinclude:include src=\"cocoon://module/aaa/corda/valuation/ByAssetClassCurrencyGraph\" />"
			}
			--- Tab ---
				labels en = Rating, de = Bonität, fr = Notation
				boxType = vertical
				id = tab_summary_rating
				isWidgetVisible = false
				tid = 25877511607760
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/valuation/summary/DynamicByRatingCurrency/RatingCurrencyMatrix.module
				--- Code ---
					code = "<cinclude:include src=\"cocoon://module/aaa/corda/valuation/ByRatingGraph\" />"
			}
			--- Tab ---
				labels en = Sector, de = Branche, fr = Secteur
				boxType = vertical
				id = tab_summary_sector
				isWidgetVisible = false
				tid = 26101913896877
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/valuation/summary/DynamicBySectorCurrency/SectorCurrencyMatrix.module
				--- Code ---
					code = "<cinclude:include src=\"cocoon://module/aaa/corda/valuation/BySectorGraph\" />"
			}
			--- Tab ---
				labels en = Region, de = Region, fr = Région
				boxType = vertical
				id = tab_summary_region
				isWidgetVisible = false
				tid = 26254139638697
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/valuation/summary/DynamicByRegionCurrency/RegionCurrencyMatrix.module
				--- Code ---
					code = "<cinclude:include src=\"cocoon://module/aaa/corda/valuation/ByRegionGraph\" />"
			}
			--- Tab ---
				labels en = Duration, de = Duration, fr = Duration
				boxType = vertical
				id = tab_summary_duration
				isWidgetVisible = false
				tid = 2101304595137
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/valuation/summary/DynamicByDurationCurrency/DurationCurrencyMatrix.module
				--- Code ---
					code = "<cinclude:include src=\"cocoon://module/aaa/corda/valuation/ByDurationGraph\" />"
			}
			--- Tab ---
				labels en = Maturity, de = Fälligkeit, fr = Echéance
				boxType = vertical
				id = tab_summary_maturity
				isWidgetVisible = false
				tid = 26406033990912
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/valuation/summary/DynamicByMaturityCurrency/MaturityCurrencyMatrix.module
				--- Code ---
					code = "<cinclude:include src=\"cocoon://module/aaa/corda/valuation/ByMaturityGraph\" />"
			}
		}
		--- Button ---
			labels de = Devisenkurs, fr = "Taux de change", en = "Exchange rates"
			id = btn_T_50x
			tid = 10063677164609
		{
			Event OnClick (submit) S
			{
				method = post
				call-URI = "resource:///valuation/ValuationExchangeRate.pageflow"
				target = popup
				modal = false
				only-changed = false
				prevalidate = false
			}
		}
	}
}