# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels fr = "Vues résumées", en = "Summary Views", de = Zusammenfassung
	containment = container
	domainEntity = "AAADSValuation:ValuationSummaryList"
	bean-define = DSBean.AAADSValuation.ValuationSummaryList
	bean-name = ValuationSummaryList
	id = SummaryInstrumentDetail_nc__8
	tid = 549025355865340
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TabbedPane ---
			id = ZQ___
			indexOfSelectedChild = 0
		{
			--- Tab ---
				labels en = Portfolio, de = Portfolio, fr = Portefeuille
				boxType = vertical
				id = tab_Jrl_q
				isWidgetSelected = true
				tid = 549025357153493
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/valuation/summary/ByPortfolio/InstrumentByPortfolioD.module
			}
			--- Tab ---
				labels en = Instrument, fr = Instrument, de = Instrument
				id = tab_AcsE8
				isWidgetVisible = false
				tid = 549025359117429
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/valuation/summary/ByInstrument/InstrumentAccounting.module
			}
			--- Tab ---
				labels en = "Asset Class", de = Anlagekategorie, fr = "Catégorie d\'actif"
				boxType = vertical
				id = tab_nB_DO
				isWidgetVisible = false
				tid = 549025361060414
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/valuation/summary/DynamicByAssetClassCurrency/AssetClassCurrencyMatrix.module
				--- Code ---
					code = "<cinclude:include src=\"cocoon://module/aaa/corda/valuation/ByAssetClassCurrencyGraph\" />"
			}
			--- Tab ---
				labels en = Rating, de = Bonität, fr = Notation
				boxType = vertical
				id = tab_c_15_
				isWidgetVisible = false
				tid = 549025363012338
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/valuation/summary/DynamicByRatingCurrency/RatingCurrencyMatrix.module
				--- Code ---
					code = "<cinclude:include src=\"cocoon://module/aaa/corda/valuation/ByRatingGraph\" />"
			}
			--- Tab ---
				labels en = Sector, de = Branche, fr = Secteur
				boxType = vertical
				id = tab_q2__w
				isWidgetVisible = false
				tid = 549025364971805
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/valuation/summary/DynamicBySectorCurrency/SectorCurrencyMatrix.module
				--- Code ---
					code = "<cinclude:include src=\"cocoon://module/aaa/corda/valuation/BySectorGraph\" />"
			}
			--- Tab ---
				labels en = Region, de = Region, fr = Région
				boxType = vertical
				id = tab_J_d_7
				isWidgetVisible = false
				tid = 549025368070243
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/valuation/summary/DynamicByRegionCurrency/RegionCurrencyMatrix.module
				--- Code ---
					code = "<cinclude:include src=\"cocoon://module/aaa/corda/valuation/ByRegionGraph\" />"
			}
			--- Tab ---
				labels en = Duration, de = Duration, fr = Duration
				boxType = vertical
				id = tab_h72_y
				isWidgetVisible = false
				tid = 549025402080990
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/valuation/summary/DynamicByDurationCurrency/DurationCurrencyMatrix.module
				--- Code ---
					code = "<cinclude:include src=\"cocoon://module/aaa/corda/valuation/ByDurationGraph\" />"
			}
			--- Tab ---
				labels en = Maturity, de = Fälligkeit, fr = Echéance
				boxType = vertical
				id = tab_PO_N8
				isWidgetVisible = false
				tid = 549025404027048
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/valuation/summary/DynamicByMaturityCurrency/MaturityCurrencyMatrix.module
				--- Code ---
					code = "<cinclude:include src=\"cocoon://module/aaa/corda/valuation/ByMaturityGraph\" />"
			}
		}
		--- Button ---
			labels en = "Exchange rates", fr = "Taux de change", de = Devisenkurs
			id = btn_S3wN1
			tid = 549025405980368
		{
			Event OnClick (submit) S
			{
				method = post
				call-URI = "resource:///valuation/ValuationExchangeRate.pageflow"
				target = popup
				modal = false
				only-changed = false
				prevalidate = false
			}
		}
	}
}