# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	containment = container
	domainEntity = "AAADSStrategyLink:StrategyLinkDetails"
	cssClass = nodeco
	bean-define = DSBean.AAADSStrategyLink.StrategyLinkDetails
	bean-name = StrategyLinkDetails
	id = AssociatedStrategyDetails_I_62_
{
	--- Box ---
		labels en = "Associated Strategy", fr = "Stratégie associée", de = "Verknüpfte Strategie"
		boxType = vertical
		tid = 100275801544468
	{
		--- Conditional ---
			indexOfSelectedChild = 0
		{
			--- ConditionalBody ---
				javaCode = "\"true\".equals(<bean:get-property bean=\"StrategyLinkDetails\" property=\"rightsOnAssociatedStrategyF\"/>.toString())"
				technicalName = "Access Rights On Associated Strategy"
				boxType = vertical
				isWidgetSelected = true
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/strategy/common/definition/DefinitionCommon.module
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/strategylink/AssociatedStrategyCurrentObjectivesView.module
			}
			--- ConditionalBody ---
				javaCode = true
				technicalName = "No Access Rights On Associated Strategy"
				boxType = vertical
				isWidgetVisible = false
			{
				--- Label ---
					labels en = "No access rights on the associated strategy", fr = "Pas de droit d\'accès sur la stratégie associée", de = "Kein Zugriffsrecht auf der verknüpften Strategie"
					tid = 100275803465376
			}
		}
	}
}