# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSStrategyLink:StrategyLinkDetails"
	cssClass = nodeco
	bean-define = DSBean.AAADSStrategyLink.StrategyLinkDetails
	bean-name = StrategyLinkDetails
	id = StrategyLinkDefinition_V_N_9
{
	--- Box ---
		boxType = vertical
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 4
			gridColumnsWidth = "25,25,25,25" !
			gridRowCount = 4
		{
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- LabelDomain ---
					domainAttribute = portfolio !
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Include ---
					domainAssociation = portfolio
					includeSrc = "" !
					resource:///default/portfolio/administration/PortfolioIdentifierView.fragment
					bean-property-prefix = portfolio.
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- LabelDomain ---
					domainAttribute = strategy !
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					required = true
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Conditional ---
					indexOfSelectedChild = 1
				{
					--- ConditionalBody ---
						javaCode = "\"true\".equals(<bean:get-property bean=\"StrategyLinkDetails\" property=\"createF\"/>.toString())"
						technicalName = Creation
						boxType = vertical
						isWidgetVisible = false
					{
						--- Include ---
							domainAssociation = strategy
							includeSrc = "" !
							resource:///default/portfolio/administration/StrategyIdentifier.fragment
							bean-property-prefix = strategy.
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetSelected = true
					{
						--- Include ---
							domainAssociation = strategy
							includeSrc = "" !
							resource:///default/portfolio/administration/StrategyIdentifierView.fragment
							bean-property-prefix = strategy.
					}
				}
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- LabelDomain ---
					labels en = Nature, fr = Nature, de = Art
					domainAttribute = linkNatE !
					for = linkNatE
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					required = true
					id = linkNatE
					tid = 100277993709470
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- ComboBox ---
					domainAttribute = linkNatE !
					horizontalAlignment = "${corporatehalign}"
					editable = conditional
					editableIsBasedOn = createF
					required = true
					bean-property = linkNatE
					id = linkNatE
					widgetGroup = formCreate
					editableIsBasedOn-simplified = "AAADSStrategyLink:StrategyLinkDetails#createF"
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- LabelDomain ---
					domainAttribute = priorityN !
					for = priorityN
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					id = priorityN
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- TextField ---
					domainAttribute = priorityN !
					columns = 5
					format = integer
					horizontalAlignment = "${corporatehalign}"
					type = integer
					chars = 5
					editable = conditional
					editableIsBasedOn = editF
					bean-property = priorityN
					id = priorityN
					editableIsBasedOn-simplified = "AAADSStrategyLink:StrategyLinkDetails#editF"
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- LabelDomain ---
					domainAttribute = beginD !
					for = beginD
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					required = true
					id = beginD
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- CaldateField ---
					domainAttribute = beginD !
					format = date
					horizontalAlignment = "${corporatehalign}"
					type = date
					editable = conditional
					editableIsBasedOn = createF
					required = true
					bean-property = beginD
					id = beginD
					widgetGroup = formCreate
					editableIsBasedOn-simplified = "AAADSStrategyLink:StrategyLinkDetails#createF"
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- LabelDomain ---
					domainAttribute = endD !
					for = endD
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					id = endD
					enabledIsBasedOn-simplified = "AAADSStrategyLink:StrategyLinkDetails#notCreateF"
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- CaldateField ---
					domainAttribute = endD !
					format = date
					horizontalAlignment = "${corporatehalign}"
					type = date
					editable = conditional
					editableIsBasedOn = editF
					nillable = true
					bean-property = endD
					id = endD
					editableIsBasedOn-simplified = "AAADSStrategyLink:StrategyLinkDetails#editF"
					enabledIsBasedOn-simplified = "AAADSStrategyLink:StrategyLinkDetails#notCreateF"
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- LabelDomain ---
					labels en = "Third Party Access", fr = "Accès tierce personne", de = "Dritte Person Zugriff"
					domainAttribute = dataSecuProf2 !
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					tid = 100277994801275
			}
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "\"true\".equals(<bean:get-property bean=\"StrategyLinkDetails\" property=\"editF\"/>.toString())"
						technicalName = Edition
						isWidgetSelected = true
					{
						--- Include ---
							domainAssociation = dataSecuProf2
							includeSrc = "" !
							resource:///default/defaultFragments/DataSecuProf2Identifier.fragment
							bean-property-prefix = dataSecuProf2.
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetVisible = false
					{
						--- Include ---
							domainAssociation = dataSecuProf2
							includeSrc = "" !
							resource:///default/defaultFragments/DataSecuProf2IdentifierView.fragment
							bean-property-prefix = dataSecuProf2.
					}
				}
			}
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
		}
	}
}