package com.odcgroup.iris.rim.generation.mappers;

import com.odcgroup.iris.generator.Application;
import com.odcgroup.iris.rim.generation.mappers.T24VersionMapper;
import com.odcgroup.t24.version.versionDSL.Version;
import com.odcgroup.workbench.generation.cartridge.ng.ModelLoader;

/**
 * TODO: Document me!
 * 
 * @author sjunejo
 */
@SuppressWarnings("all")
public class Version2ResourceMapperForLiveNauHist extends T24VersionMapper {
  public Version2ResourceMapperForLiveNauHist(final ModelLoader _loader, final /* MdfClass */Object _mdfClass, final Application _application, final Version _version, final /* ResourceInteractionModel */Object _rim) {
    super(_loader, _mdfClass, _application, _version, _rim);
  }
  
  public void generate() {
    throw new Error("Unresolved compilation problems:"
      + "\nState cannot be resolved to a type."
      + "\nState cannot be resolved to a type."
      + "\nState cannot be resolved to a type."
      + "\nThe method createGET is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createGET is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createGET is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPUT is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createDELETE is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPUT is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createGET is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPUT is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createDELETE is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPUT is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createGET is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPUT is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createGET is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createGET is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPUT is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createDELETE is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPUT is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPUT is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createGET is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createGET is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createGET is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPUT is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createDELETE is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createGET is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPUT is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createGET is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createGET is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createGET is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createGET is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createGET is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createGET is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createGET is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createGET is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createGET is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createGET is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createGET is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createGET is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createGET is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createDELETE is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPUT is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForLiveNauHist"
      + "\nstates cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nstates cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nstates cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nstates cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nstates cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nstates cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nstates cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nstates cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nstates cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nstates cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nstates cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nstates cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nstates cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nstates cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nstates cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nstates cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nstates cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nstates cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nstates cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nstates cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nstates cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nstates cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nstates cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nstates cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nstates cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nstates cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nstates cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nstates cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nstates cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nstates cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\n!= cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nerrorState cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nerrorState cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nerrorState cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\n!= cannot be resolved"
      + "\nerrorState cannot be resolved"
      + "\nerrorState cannot be resolved"
      + "\nerrorState cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved");
  }
}
