package com.odcgroup.iris.rim.generation.mappers;

import com.odcgroup.iris.generator.Application;
import com.odcgroup.iris.rim.generation.mappers.T24VersionMapper;
import com.odcgroup.t24.version.versionDSL.Version;
import com.odcgroup.workbench.generation.cartridge.ng.ModelLoader;

/**
 * This class is responsible for generating a RIM model for versions supports VERIFY operation in T24.
 * These type of APPLICATION do not have any NAU and HIST files hence can only be INPUT/VERIFY/DELETE
 * 
 * @author sjunejo
 */
@SuppressWarnings("all")
public class Version2ResourceMapperForVerifyOnly extends T24VersionMapper {
  public Version2ResourceMapperForVerifyOnly(final ModelLoader _loader, final /* MdfClass */Object _mdfClass, final Application _application, final Version _version, final /* ResourceInteractionModel */Object _rim) {
    super(_loader, _mdfClass, _application, _version, _rim);
  }
  
  public void generate() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method createGET is undefined for the type Version2ResourceMapperForVerifyOnly"
      + "\nThe method createGET is undefined for the type Version2ResourceMapperForVerifyOnly"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForVerifyOnly"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForVerifyOnly"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForVerifyOnly"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForVerifyOnly"
      + "\nThe method createPUT is undefined for the type Version2ResourceMapperForVerifyOnly"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForVerifyOnly"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForVerifyOnly"
      + "\nThe method createPUT is undefined for the type Version2ResourceMapperForVerifyOnly"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForVerifyOnly"
      + "\nThe method createPUT is undefined for the type Version2ResourceMapperForVerifyOnly"
      + "\nThe method createPUT is undefined for the type Version2ResourceMapperForVerifyOnly"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForVerifyOnly"
      + "\nThe method createPUT is undefined for the type Version2ResourceMapperForVerifyOnly"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForVerifyOnly"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForVerifyOnly"
      + "\nThe method createPUT is undefined for the type Version2ResourceMapperForVerifyOnly"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForVerifyOnly"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForVerifyOnly"
      + "\nThe method createPUT is undefined for the type Version2ResourceMapperForVerifyOnly"
      + "\nThe method createGET is undefined for the type Version2ResourceMapperForVerifyOnly"
      + "\nThe method createPUT is undefined for the type Version2ResourceMapperForVerifyOnly"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForVerifyOnly"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForVerifyOnly"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForVerifyOnly"
      + "\nThe method createGET is undefined for the type Version2ResourceMapperForVerifyOnly"
      + "\nThe method createGET is undefined for the type Version2ResourceMapperForVerifyOnly"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForVerifyOnly"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForVerifyOnly"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForVerifyOnly"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForVerifyOnly"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForVerifyOnly"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForVerifyOnly"
      + "\nThe method createPUT is undefined for the type Version2ResourceMapperForVerifyOnly"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForVerifyOnly"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForVerifyOnly"
      + "\nThe method createPUT is undefined for the type Version2ResourceMapperForVerifyOnly"
      + "\nThe method createPOST is undefined for the type Version2ResourceMapperForVerifyOnly"
      + "\nstates cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nstates cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nstates cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nstates cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nstates cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nstates cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nstates cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nstates cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nstates cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nstates cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nstates cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nstates cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nstates cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nstates cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nstates cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nstates cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nstates cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nerrorState cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nerrorState cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ntransitions cannot be resolved"
      + "\nadd cannot be resolved");
  }
}
