/*
 * generated by Xtext
 */
package com.odcgroup.page.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.formatting.IWhitespaceInformationProvider;

import com.odcgroup.page.ui.formatting.DS_8733_PreferenceStoreWhitespaceInformationProvider;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PageUiModule extends com.odcgroup.page.ui.AbstractPageUiModule {
	public PageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	@Override
	public Class<? extends IWhitespaceInformationProvider> bindIWhitespaceInformationProvider() {
		return DS_8733_PreferenceStoreWhitespaceInformationProvider.class;
	}

}
