# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSValuation:ValuationCashBalance"
	cssClass = nodeco
	bean-define = DSBean.AAADSValuation.ValuationCashBalance
	bean-name = ValuationCashBalance
	id = CashBalancePortfolio_i5_61
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			id = AC___
			table-column-count = 7 !
			table-columns-width = "14,14,14,14,14,14,14" !
		{
			--- TableColumn ---
				column-name = PORTFOLIO_NAME !
				column-type = domain !
				domainAttribute = PORTFOLIO_NAME !
				type = text
				column-locked = true
				id = PORTFOLIO_NAME
				table-column-width = 14
			{
				--- TableColumnItem ---
					item-column = PORTFOLIO_NAME
					previewValue = value
			}
			--- TableColumn ---
				column-name = POS_CURRENCY_CODE !
				column-type = domain !
				domainAttribute = POS_CURRENCY_CODE !
				type = text
				id = POS_CURRENCY_CODE
				table-column-width = 14
			{
				--- TableColumnItem ---
					item-column = POS_CURRENCY_CODE
					previewValue = value
			}
			--- TableColumn ---
				column-name = INSTR_NAME !
				column-type = domain !
				domainAttribute = INSTR_NAME !
				type = text
				id = INSTR_NAME
				table-column-width = 14
			{
				--- TableColumnItem ---
					item-column = INSTR_NAME
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Cash Balance", fr = "Solde de compte", de = Saldo
				column-name = PosNetAmount
				type = amount
				id = Tf8_W
				documentation = "Position Net Amount"
				column-computation = make-amount
				column-computation-parameters = "POS_NET_AMOUNT,POS_CURRENCY_CODE"
				table-column-width = 14
				tid = 136761237367197
			{
				--- TableColumnItem ---
					item-column = PosNetAmount
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Balance (Ref)", fr = "Solde de compte (Réf)", de = "Saldo (Ref)"
				column-name = RefNetAmount
				type = amount
				id = d9FX_
				documentation = "Ref. net amount"
				column-computation = make-amount
				column-computation-parameters = "REF_NET_AMOUNT,REF_CURRENCY"
				table-column-width = 14
				tid = 137034783690673
			{
				--- TableColumnItem ---
					item-column = RefNetAmount
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Balance (Sys)", fr = "Solde de compte (Sys)", de = "Saldo (Sys)"
				column-name = SysNetAmount
				type = amount
				column-visibility = not-visible
				id = M1X1_
				documentation = "Sys. net amount"
				column-computation = make-amount
				column-computation-parameters = "SYS_NET_AMOUNT,SYS_CURRENCY"
				table-column-width = 14
				tid = 373235839735529
			{
				--- TableColumnItem ---
					item-column = SysNetAmount
					previewValue = value
			}
			--- TableColumn ---
				column-name = TOT_MKT_PERC !
				column-type = domain !
				domainAttribute = TOT_MKT_PERC !
				type = text
				id = TOT_MKT_PERC
				table-column-width = 14
			{
				--- TableColumnItem ---
					item-column = TOT_MKT_PERC
					format = percentTA
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = PORTFOLIO_NAME
				sort-rank = 1
			--- TableSort ---
				sort-column-name = POS_CURRENCY_CODE
				sort-rank = 2
			--- TableSort ---
				sort-column-name = INSTR_NAME
				sort-rank = 3
		}
	}
}