# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSValuation:ValuationCashBalance"
	cssClass = nodeco
	bean-define = DSBean.AAADSValuation.ValuationCashBalance
	bean-name = ValuationCashBalance
	id = CashBalancePortfolio_i5_61
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			id = AC___
			table-column-count = 6 !
			table-columns-width = "16,16,16,16,16,16" !
		{
			--- TableColumn ---
				column-name = POS_CURRENCY_CODE !
				column-type = domain !
				domainAttribute = POS_CURRENCY_CODE !
				type = text
				column-locked = true
				id = POS_CURRENCY_CODE
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = POS_CURRENCY_CODE
					previewValue = value
			}
			--- TableColumn ---
				column-name = INSTR_NAME !
				column-type = domain !
				domainAttribute = INSTR_NAME !
				type = text
				id = INSTR_NAME
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = INSTR_NAME
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Cash Balance", fr = "Solde de compte", de = Saldo
				column-name = PosNetAmount
				type = amount
				id = Y7P_v
				documentation = "Position Net Amount"
				column-computation = make-amount
				column-computation-parameters = "POS_NET_AMOUNT,POS_CURRENCY_CODE"
				table-column-width = 16
				tid = 135754651112867
			{
				--- TableColumnItem ---
					item-column = PosNetAmount
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Cash Balance (Ref)", de = "Saldo (Ref)", fr = "Solde de compte (Réf)"
				column-name = RefNetAmount
				type = amount
				id = D2_k_
				documentation = "Ref. net amount"
				column-computation = make-amount
				column-computation-parameters = "REF_NET_AMOUNT,REF_CURRENCY"
				table-column-width = 16
				tid = 136074126013412
			{
				--- TableColumnItem ---
					item-column = RefNetAmount
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Balance (Sys)", fr = "Solde de compte (Sys)", de = "Saldo (Sys)"
				column-name = SysNetAmount
				type = amount
				column-visibility = not-visible
				id = I_9_C
				documentation = "Sys. net amount"
				column-computation = make-amount
				column-computation-parameters = "SYS_NET_AMOUNT,SYS_CURRENCY"
				table-column-width = 16
				tid = 373485640039168
			{
				--- TableColumnItem ---
					item-column = SysNetAmount
					previewValue = value
			}
			--- TableColumn ---
				column-name = TOT_MKT_PERC !
				column-type = domain !
				domainAttribute = TOT_MKT_PERC !
				type = text
				id = TOT_MKT_PERC
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = TOT_MKT_PERC
					format = percentTA
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = POS_CURRENCY_CODE
				sort-rank = 1
		}
	}
}