# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Country Search Criteria", fr = "Critères de recherche sur pays", de = "Land Suchbegriffe"
	containment = container
	domainEntity = "AAADSGeographic:GeographicSearchCriteria"
	search = input !
	bean-define = DSBean.AAADSGeographic.GeographicSearchCriteria
	bean-name = GeographicSearchCriteria
	id = GeographicSearchInput_M__8q
	tid = 30566685475562
{
	--- Box ---
		boxType = vertical
	{
		--- FilterCriteria ---
			includedFile = "resource:/com/module/search/QueryBuilder.xsp"
		--- Include ---
			includeSrc = "" !
			resource:///default/search/NavigationSearch.fragment
	}
}