# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Country Search", fr = "Recherche de pays", de = "Land Suche"
	containment = container
	search = container !
	cssClass = nodeco
	id = GeographicSearch_x60wT
	tid = 30551394956899
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/geographic/search/GeographicSearchInput.module
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/geographic/search/GeographicList.module
	}
}