# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSValuation:ValuationDetailledList"
	cssClass = nodeco
	bean-define = DSBean.AAADSValuation.ValuationDetailledList
	bean-name = ValuationDetailledList
	id = CopyOfLiquidityAccounting_P2b__
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			table-filter-layer = true
			table-fixed-size = true
			table-height = 700
			id = F_5_m
			table-column-count = 17 !
			table-columns-width = "5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5" !
		{
			--- TableColumn ---
				column-display-grouping = true
				column-name = PORTFOLIO_CODE !
				column-type = domain !
				domainAttribute = PORTFOLIO_CODE !
				type = text
				column-is-part-of-filter = false
				id = PORTFOLIO_CODE
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = PORTFOLIO_CODE
					previewValue = value
				--- TableGroup ---
					group-column-name = INSTR_TYPE_DENOM
					group-sorting-column-name = INSTR_TYPE_DENOM
					group-sorting-direction = ascending
					group-rank = 1
				--- TableGroup ---
					aggregateData = false
					group-column-name = INSTR_CODE
					group-sorting-column-name = INSTR_CODE
					group-sorting-direction = ascending
					collapsed = true
					group-rank = 2
			}
			--- TableColumn ---
				column-name = INSTR_DENOM !
				column-type = domain !
				domainAttribute = INSTR_DENOM !
				column-locked = true
				id = INSTR_DENOM
				table-column-width = 5
			{
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "<udp:item column=\"INSTR_CODE\"/>!=null &amp;&amp; \r\n<udp:item column=\"PORTFOLIO_CODE\"/>==null"
						technicalName = Instrument
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips en = "View Instrument Details", fr = "Voir détails de l\'instrument", de = "Details des Instruments ansehen"
							icon = application_form_magnify
							id = n_i8w
							tid = 88551281962721
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "resource:///administration/instrument/InstrumentQuickView.pageflow"
								target = popup
								code = "<udp:item column=\"INSTR_CODE\"/>" ud
								modal = false
								only-changed = false
								prevalidate = false
							}
						}
						--- TableColumnItem ---
							item-column = INSTR_DENOM
							item-halign = lead
							previewValue = value
					}
				}
			}
			--- TableColumn ---
				labels en = Quantity
				column-name = QUANTITY !
				column-type = domain !
				domainAttribute = QUANTITY !
				id = QUANTITY
				table-column-width = 5
				tid = 88551282929804
			{
				--- TableColumnItem ---
					item-column = QUANTITY
					format = decimal.2-digits
					previewValue = value
				--- Spacer ---
					height = 4
					width = 4
				--- TableColumnItem ---
					item-column = QUANTITY_CURR
					previewValue = value
				--- Spacer ---
					height = 4
					width = 10
				--- Conditional ---
					indexOfSelectedChild = 1
				{
					--- ConditionalBody ---
						javaCode = "<udp:item column=\"PORTFOLIO_CODE\"/>!=null &amp;&amp; \r\n<udp:item column=\"INSTR_CODE\"/>!=null"
						technicalName = PortAndInstr
						boxType = vertical
						isWidgetVisible = false
					{
						--- Icon ---
							toolTips en = "View Position Details", fr = "Voir détails de la position", de = "Details der Position ansehen"
							horizontalAlignment = trail
							icon = application_form_magnify
							id = OI_2Q
							tid = 80851302892406
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = popup
								modal = false
								only-changed = false
								prevalidate = false
								flow-action = positiondetails ud
								pos_instrumentDimInstrument.code = "<udp:item column=\"INSTR_CODE\"/>" ud
								pos_instrumentDimensionE = 1 ud
								pos_portfolioDimPortfolio.code = "<udp:item column=\"PORTFOLIO_CODE\"/>" ud
								pos_portfolioDimensionE = 1 ud
								inputFieldPrefix = pos_ ud
								Snippet FilterSet
								id = fs_HX2
								level = 1
								targetDataset = "AAADSPositionDetails:PositionDetailsFromValuation"
								{
									Snippet Filter
									attribute = id
									filterValue = "<udp:item column=\"id\"/>"
									operator = EQUAL
								}
							}
						}
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetSelected = true
				}
			}
			--- TableColumn ---
				column-name = POS_CURRENCY !
				column-type = domain !
				domainAttribute = POS_CURRENCY !
				type = text
				id = POS_CURRENCY
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = POS_CURRENCY
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Market Value", fr = "Valeur d\'inventaire", de = Marktwert
				column-name = MktVal
				type = amount
				id = PW_U_
				documentation = "Market Value in Reference Currency by Money Markets\'s position."
				column-computation = make-amount
				column-computation-parameters = "MKT_VAL,REF_CURRENCY"
				table-column-width = 5
				tid = 88551284925990
			{
				--- TableColumnItem ---
					item-column = MktVal
					previewValue = value
			}
			--- TableColumn ---
				column-name = MKT_VAL_PERC_REL !
				column-type = domain !
				domainAttribute = MKT_VAL_PERC_REL !
				type = text
				id = MKT_VAL_PERC_REL
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = MKT_VAL_PERC_REL
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = MKT_VAL_PERC !
				column-type = domain !
				domainAttribute = MKT_VAL_PERC !
				type = text
				column-visibility = not-visible
				id = MKT_VAL_PERC
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = MKT_VAL_PERC
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Net Cost Value", de = "Einstandswert Netto", fr = "Coût d\'achat"
				column-name = NetCostVal
				type = amount
				id = G2___
				documentation = "Net Cost Value in Reference Currency by Money Markets\'s position."
				column-computation = make-amount
				column-computation-parameters = "NET_COST_VAL,REF_CURRENCY"
				table-column-width = 5
				tid = 88551286865717
			{
				--- TableColumnItem ---
					item-column = NetCostVal
					previewValue = value
			}
			--- TableColumn ---
				column-name = CURR_PL_PERC !
				column-type = domain !
				domainAttribute = CURR_PL_PERC !
				type = text
				id = CURR_PL_PERC
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = CURR_PL_PERC
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Cur P&L", de = "Dev G/V"
				column-name = CurrPl
				type = amount
				column-visibility = not-visible
				id = ZtNB_
				column-computation = make-amount
				column-computation-parameters = "CURR_PL,REF_CURRENCY"
				table-column-width = 5
				tid = 88551287930322
			{
				--- TableColumnItem ---
					item-column = CurrPl
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Interest Rate", de = Zinssatz
				column-name = RATE !
				column-type = domain !
				domainAttribute = RATE !
				type = text
				column-visibility = not-visible
				id = RATE
				table-column-width = 5
				tid = 88551304537121
			{
				--- TableColumnItem ---
					item-column = RATE
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Accrued Interest", fr = "Intérêts courus", de = Stückzinsen
				column-name = AccruedInterest
				type = amount
				column-visibility = not-visible
				id = y__pS
				documentation = "Accrued Interest Value in Reference Currency by Money Market\'s position."
				column-computation = make-amount
				column-computation-parameters = "ACCRUED_INTEREST,REF_CURRENCY"
				table-column-width = 5
				tid = 88551305525591
			{
				--- TableColumnItem ---
					item-column = AccruedInterest
					previewValue = value
			}
			--- TableColumn ---
				column-name = STATUS !
				column-type = domain !
				domainAttribute = STATUS !
				id = STATUS
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = STATUS
					previewValue = value
			}
			--- TableColumn ---
				column-name = MKT_VAL !
				column-type = domain !
				domainAttribute = MKT_VAL !
				type = text
				column-sortable = false
				column-visibility = never-visible
				id = MKT_VAL
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = MKT_VAL
					format = decimal
					previewValue = value
			}
			--- TableColumn ---
				column-name = NET_COST_VAL !
				column-type = domain !
				domainAttribute = NET_COST_VAL !
				type = text
				column-sortable = false
				column-visibility = never-visible
				id = NET_COST_VAL
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = NET_COST_VAL
					format = decimal
					previewValue = value
			}
			--- TableColumn ---
				column-name = CURR_PL !
				column-type = domain !
				domainAttribute = CURR_PL !
				type = text
				column-sortable = false
				column-visibility = never-visible
				id = CURR_PL
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = CURR_PL
					format = decimal
					previewValue = value
			}
			--- TableColumn ---
				column-name = ACCRUED_INTEREST !
				column-type = domain !
				domainAttribute = ACCRUED_INTEREST !
				type = text
				column-sortable = false
				column-visibility = never-visible
				id = ACCRUED_INTEREST
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = ACCRUED_INTEREST
					format = decimal
					previewValue = value
			}
			--- TableExtra ---
				domainAttribute = INSTR_PRICE_CURRENCY
			--- TableExtra ---
				domainAttribute = INSTR_PRICE_PERCENTAGE
			--- TableExtra ---
				domainAttribute = COST_PRICE_CURRENCY
			--- TableExtra ---
				domainAttribute = COST_PRICE_PERCENTAGE
			--- TableExtra ---
				domainAttribute = QUANTITY_CURR
			--- TableSort ---
				sort-column-name = MKT_VAL
				sort-direction = descending
				sort-rank = 1
			--- TableExtra ---
				domainAttribute = CURR_CLASS_RANK
			--- TableExtra ---
				domainAttribute = seqno
			--- TableAggregate ---
				aggregate-column-name = NET_COST_VAL
				aggregate-computation = sum
				aggregate-group-names = INSTR_CODE
			--- TableAggregate ---
				aggregate-column-name = MKT_VAL_PERC
				aggregate-computation = sum
				aggregate-group-names = INSTR_CODE
			--- TableAggregate ---
				aggregate-column-name = CAP_PL
				aggregate-computation = sum
				aggregate-group-names = INSTR_CODE
			--- TableAggregate ---
				aggregate-column-name = CURR_PL
				aggregate-computation = sum
				aggregate-group-names = INSTR_CODE
			--- TableAggregate ---
				aggregate-column-name = PL
				aggregate-computation = sum
				aggregate-group-names = INSTR_CODE
			--- TableAggregate ---
				aggregate-column-name = CurrPl
				aggregate-computation = sum
				aggregate-group-names = INSTR_CODE
			--- TableAggregate ---
				aggregate-column-name = AccruedInterest
				aggregate-computation = sum
				aggregate-group-names = INSTR_CODE
			--- TableAggregate ---
				aggregate-column-name = ACCRUED_INTEREST
				aggregate-computation = sum
				aggregate-group-names = INSTR_CODE
			--- TableAggregate ---
				aggregate-column-name = MKT_VAL
				aggregate-computation = sum
				aggregate-group-names = INSTR_CODE
			--- TableAggregate ---
				aggregate-column-name = REF_CURRENCY
				aggregate-computation = max
				aggregate-group-names = INSTR_CODE
			--- TableAggregate ---
				aggregate-column-name = INSTR_DENOM
				aggregate-computation = max
				aggregate-group-names = INSTR_CODE
			--- TableAggregate ---
				aggregate-column-name = QUANTITY
				aggregate-computation = sum
				aggregate-group-names = INSTR_CODE
			--- TableAggregate ---
				aggregate-column-name = POS_CURRENCY
				aggregate-computation = max
				aggregate-group-names = INSTR_CODE
			--- TableExtra ---
				domainAttribute = id
			--- TableAggregate ---
				aggregate-column-name = MktVal
				aggregate-computation = sum
				aggregate-group-names = "INSTR_CODE,INSTR_TYPE_DENOM"
			--- TableAggregate ---
				aggregate-column-name = MKT_VAL_PERC_REL
				aggregate-computation = sum
				aggregate-group-names = "INSTR_CODE,INSTR_TYPE_DENOM"
			--- TableAggregate ---
				aggregate-column-name = NetCostVal
				aggregate-computation = sum
				aggregate-group-names = "INSTR_CODE,INSTR_TYPE_DENOM"
			--- TableSort ---
				sort-column-name = PORTFOLIO_CODE
				sort-rank = 2
		}
	}
}