# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSValRuleElement:ValRuleElementList"
	bean-define = DSBean.AAADSValRuleElement.ValRuleElementList
	bean-name = ValRuleElementList
	id = ValRuleElementList_G92R_
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			id = V__34
			table-column-count = 2 !
			table-columns-width = "50,50" !
		{
			--- TableColumn ---
				column-name = code !
				column-type = domain !
				domainAttribute = code !
				id = code
				table-column-width = 50
			{
				--- TableColumnItem ---
					item-column = code
					previewValue = value
			}
			--- TableColumn ---
				column-name = ruleNatureE !
				column-type = domain !
				domainAttribute = ruleNatureE !
				id = ruleNatureE
				table-column-width = 50
			{
				--- TableColumnItem ---
					item-column = ruleNatureE
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = code
				sort-rank = 1
		}
	}
}