# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Price List", fr = "Liste de Prix", de = Preisliste
	domainEntity = "AAADSInstrPrice:InstrPriceList"
	bean-define = DSBean.AAADSInstrPrice.InstrPriceList
	bean-name = InstrPriceList
	id = InstrPriceList_l_Nb2_
	tid = 97165119089282
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			id = Z4tk_
			table-model-reference = aaa-search.instrPriceList
			table-column-count = 7 !
			table-columns-width = "14,14,14,14,14,14,14" !
		{
			--- TableColumn ---
				labels en = "NAV Date", fr = "NAV date"
				column-name = quoteD !
				column-type = domain !
				domainAttribute = quoteD !
				id = quoteD
				table-column-width = 14
				tid = 97167975158195
			{
				--- TableColumnItem ---
					item-column = quoteD
					format = datetime.date-only
					previewValue = value
			}
			--- TableColumn ---
				labels en = NAV, fr = NAV, de = NAV
				column-name = comp_O36k_
				type = amount
				id = O36k_
				column-computation = make-amount
				column-computation-parameters = "quoteN,currencyName"
				table-column-width = 14
				tid = 97165120169538
			{
				--- TableColumnItem ---
					item-column = comp_O36k_
					format = amount.5-digits
					previewValue = value
			}
			--- TableColumn ---
				column-name = typeCode !
				column-type = domain !
				domainAttribute = typeCode !
				id = typeCode
				table-column-width = 14
			{
				--- TableColumnItem ---
					item-column = typeCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = thirdCode !
				column-type = domain !
				domainAttribute = thirdCode !
				id = thirdCode
				table-column-width = 14
			{
				--- TableColumnItem ---
					item-column = thirdCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = marketThirdName !
				column-type = domain !
				domainAttribute = marketThirdName !
				type = text
				id = marketThirdName
				table-column-width = 14
			{
				--- TableColumnItem ---
					item-column = marketThirdName
					previewValue = value
			}
			--- TableColumn ---
				column-name = marketThirdCode !
				column-type = domain !
				domainAttribute = marketThirdCode !
				column-visibility = never-visible
				id = marketThirdCode
				table-column-width = 14
			{
				--- TableColumnItem ---
					item-column = marketThirdCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = termTypeCode !
				column-type = domain !
				domainAttribute = termTypeCode !
				id = termTypeCode
				table-column-width = 14
			{
				--- TableColumnItem ---
					item-column = termTypeCode
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = instrCode
				sort-rank = 1
			--- TableSort ---
				sort-column-name = quoteD
				sort-direction = descending
				sort-rank = 2
			--- TableSort ---
				sort-column-name = currencyCode
				sort-rank = 3
			--- TableSort ---
				sort-column-name = typeCode
				sort-rank = 4
			--- TableSort ---
				sort-column-name = thirdCode
				sort-rank = 5
			--- TableSort ---
				sort-column-name = marketThirdCode
				sort-rank = 7
			--- TableSort ---
				sort-column-name = termTypeCode
				sort-rank = 8
			--- TableSort ---
				sort-column-name = marketThirdName
				sort-rank = 6
		}
	}
}