# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSInstrPrice:InstrPriceList"
	cssClass = nodeco
	bean-define = DSBean.AAADSInstrPrice.InstrPriceList
	bean-name = InstrPriceList
	id = InstrPriceList_l_Nb_
{
	--- Box ---
		labels en = Price, de = Preisliste, fr = Prix
		boxType = vertical
		widgetBorder = box
		width = 0
		tid = 712935794063491
	{
		--- TableTree ---
			table-filter-layer = true
			id = Z4tk_
			table-model-reference = DSTableModel.AAADSInstrPrice.InstrPriceList
			table-column-count = 8 !
			table-columns-width = "12,12,12,12,12,12,12,12" !
		{
			--- TableColumn ---
				column-name = quoteD !
				column-type = domain !
				domainAttribute = quoteD !
				id = quoteD
				table-column-width = 12
			{
				--- TableColumnItem ---
					item-column = quoteD
					format = datetime.date-only
					previewValue = value
			}
			--- TableColumn ---
				labels en = Type, fr = Type, de = Typ
				column-name = typeExtDenomination !
				column-type = domain !
				domainAttribute = typeExtDenomination !
				type = text
				id = typeExtDenomination
				table-column-width = 12
				tid = 1381993663112211
			{
				--- TableColumnItem ---
					item-column = typeExtDenomination
					previewValue = value
			}
			--- TableColumn ---
				column-name = thirdExtDenomination !
				column-type = domain !
				domainAttribute = thirdExtDenomination !
				type = text
				id = thirdExtDenomination
				table-column-width = 12
			{
				--- TableColumnItem ---
					item-column = thirdExtDenomination
					previewValue = value
			}
			--- TableColumn ---
				column-name = marketThirdCode !
				column-type = domain !
				domainAttribute = marketThirdCode !
				id = marketThirdCode
				table-column-width = 12
			{
				--- TableColumnItem ---
					item-column = marketThirdCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = termTypeExtDenomination !
				column-type = domain !
				domainAttribute = termTypeExtDenomination !
				type = text
				column-visibility = not-visible
				id = termTypeExtDenomination
				table-column-width = 12
			{
				--- TableColumnItem ---
					item-column = termTypeExtDenomination
					previewValue = value
			}
			--- TableColumn ---
				column-name = quoteN !
				column-type = domain !
				domainAttribute = quoteN !
				type = text
				column-locked = true
				id = quoteN
				table-column-width = 12
			{
				--- TableColumnItem ---
					item-column = quoteN
					format = decimal.detailed
					previewValue = value
			}
			--- TableColumn ---
				column-name = currencyCode !
				column-type = domain !
				domainAttribute = currencyCode !
				type = text
				id = currencyCode
				table-column-width = 12
			{
				--- TableColumnItem ---
					item-column = currencyCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = dailyDfltF !
				column-type = domain !
				domainAttribute = dailyDfltF !
				type = text
				column-visibility = never-visible
				id = dailyDfltF
				table-column-width = 12
			{
				--- TableColumnItem ---
					item-column = dailyDfltF
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = quoteD
				sort-direction = descending
				sort-rank = 1
			--- TableSort ---
				sort-column-name = termTypeExtDenomination
				sort-rank = 11
			--- TableSort ---
				sort-column-name = marketThirdExtDenomination
				sort-rank = 10
			--- TableSort ---
				sort-column-name = thirdExtDenomination
				sort-rank = 9
			--- TableSort ---
				sort-column-name = typeExtDenomination
				sort-rank = 8
		}
	}
}