# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = Context, fr = Contexte, de = Kontext
	containment = container
	domainEntity = "AAADSDomain:DomainContext"
	collapsed = true
	collapsible = true
	cssClass = nodeco
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = Context_nXc1_
	tid = 6229750161651
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/returnanalysis/context/ContextNotEditedHead.module
		--- Conditional ---
			indexOfSelectedChild = 2
		{
			--- ConditionalBody ---
				javaCode = "Integer.toString(com.odcgroup.aaa.DomainAAAPortfolioDimensionE.Portfolio).equals(<bean:get-property bean=\"DomainContext\" property=\"portfolioDimensionE\"/>.toString())"
				technicalName = Portfolio
				boxType = vertical
				isWidgetVisible = false
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/identification/identification/PortfolioBanner.module
			}
			--- ConditionalBody ---
				javaCode = "Integer.toString(com.odcgroup.aaa.DomainAAAPortfolioDimensionE.PortfolioThirdParty).equals(<bean:get-property bean=\"DomainContext\" property=\"portfolioDimensionE\"/>.toString())"
				technicalName = Client
				boxType = vertical
				isWidgetVisible = false
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/identification/identification/ClientBanner.module
			}
			--- ConditionalBody ---
				javaCode = true
				technicalName = Default
				boxType = vertical
				isWidgetSelected = true
		}
	}
}