# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = Context, fr = Contexte, de = Kontext
	containment = container
	domainEntity = "AAADSDomain:DomainContext"
	collapsible = true
	cssClass = nodeco
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = Context_nXc1_
	tid = 6229750087605
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/returnanalysis/context/PortfolioCodeDetailHead.module
		--- Grid ---
			cssClass = blank
			gridColumnCount = 4
			gridColumnsWidth = "25,25,25,25" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Button ---
					labels en = "Back To Summary", fr = "Retour au résumé", de = "Zurück zur Zusammenfassung"
					id = btn_o__7o
					tid = 275159848161238
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = back ud
						Query.fs_1.TargetDS = "AAADSReturn:ReturnAnalysis" ud
						Query.fs_1.cancel = nofilter ud
						Query.fs_1.level = 0 ud
						Query.fs_2.TargetDS = "AAADSReturn:SummaryReturnAnalysis" ud
						Query.fs_2.cancel = nofilter ud
						Query.fs_2.level = 0 ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
				--- Button ---
					labels en = Refresh, fr = Actualiser, de = Aktualisieren
					id = btn_H__n6
					tid = 3794081637539966
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = refresh ud
						only-changed = false
						prevalidate = false
						modal = false
					}
				}
			}
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
		}
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/identification/identification/PortfolioBanner.module
	}
}