# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Search Result", de = Suchergebnis, fr = "Résultat de recherche"
	domainEntity = "AAADSType:TypeList"
	bean-define = DSBean.AAADSType.TypeList
	bean-name = TypeList
	id = TypeList_c_i99
	tid = 4686770547653
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			id = Tz_U1
			table-column-count = 7 !
			table-columns-width = "14,14,14,14,14,14,14" !
		{
			--- TableColumn ---
				column-name = SELECT
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				id = A_O1f
				table-column-width = 14
			{
				--- CheckBox ---
					column-checkbox-identifier = id
					horizontalTextPosition = trail
					id = btn_D_C20
			}
			--- TableColumn ---
				column-name = UPDATE
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				id = nK_y_
				table-column-width = 14
			{
				--- Icon ---
					toolTips en = "Update Type", de = "Typ ändern", fr = "Mettre à jour le type"
					horizontalAlignment = center
					icon = application_double
					id = N32su
					tid = 39243594633954
			}
			--- TableColumn ---
				labels de = Code
				column-name = code !
				column-type = domain !
				domainAttribute = code !
				id = code
				table-column-width = 14
				tid = 24220949807028
			{
				--- TableColumnItem ---
					toolTips en = "View Type", de = "Typ ansehen", fr = "Voir le type"
					item-column = code
					previewValue = value
					tid = 4686798560990
			}
			--- TableColumn ---
				column-name = name !
				column-type = domain !
				domainAttribute = name !
				id = name
				table-column-width = 14
			{
				--- TableColumnItem ---
					item-column = name
					previewValue = value
			}
			--- TableColumn ---
				column-name = extDenomination !
				column-type = domain !
				domainAttribute = extDenomination !
				type = text
				id = extDenomination
				table-column-width = 14
			{
				--- TableColumnItem ---
					item-column = extDenomination
					previewValue = value
			}
			--- TableColumn ---
				column-name = parentTypeExtDenomination !
				column-type = domain !
				domainAttribute = parentTypeExtDenomination !
				type = text
				id = parentTypeExtDenomination
				table-column-width = 14
			{
				--- TableColumnItem ---
					item-column = parentTypeExtDenomination
					previewValue = value
			}
			--- TableColumn ---
				column-name = id !
				column-type = domain !
				domainAttribute = id !
				type = text
				column-visibility = never-visible
				id = id
				table-column-width = 14
			{
				--- TableColumnItem ---
					item-column = id
					format = integer
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = attributeEntityName
				sort-rank = 1
			--- TableSort ---
				sort-column-name = attributeName
				sort-rank = 2
			--- TableSort ---
				sort-column-name = code
				sort-rank = 3
		}
	}
}