# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Search Results", de = Suchergebnisse, fr = "Résultats de la recherche"
	domainEntity = "AAADSType:TypeList"
	search = output !
	bean-define = DSBean.AAADSType.TypeList
	bean-name = TypeList
	id = TypeList_c_i99
	tid = 4685261592464
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			id = Tz_U1
			table-column-count = 3 !
			table-columns-width = "33,33,33" !
		{
			--- TableColumn ---
				labels de = Code
				column-name = code !
				column-type = domain !
				domainAttribute = code !
				column-locked = true
				id = code
				table-column-width = 33
				tid = 19795446835561
			{
				--- Conditional ---
					indexOfSelectedChild = 1
				{
					--- ConditionalBody ---
						javaCode = "com.odcgroup.tsl.wui.search.form.SearchFormHelper.isLookup(objectModel) == false"
						technicalName = NotLookup
						boxType = vertical
						isWidgetVisible = false
					{
						--- TableColumnItem ---
							toolTips en = "Select Type", fr = "Sélectionner le type", de = "Typ auswählen"
							item-column = code
							previewValue = value
							tid = 115103300907401
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = select ud
								Query.beanValue1 = "<udp:item column=\"code\"/>" ud
								Query.beanValue2 = "<udp:item column=\"name\"/>" ud
								modal = false
								only-changed = false
								prevalidate = false
							}
						}
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetSelected = true
					{
						--- TableColumnItem ---
							toolTips en = "Select Type", fr = "Sélectionner le type", de = "Typ auswählen"
							item-column = code
							previewValue = value
							tid = 115103315367850
						{
							Event OnClick (setWidgetValue)
							{
								widget-group-id = "<xsp:expr>com.odcgroup.tsl.wui.search.form.SearchFormHelper.getParentWidgetValue1Id(objectModel)</xsp:expr>"
								value = "<udp:item column=\"code\"/>"
								target = WUI_main
							}
							Event OnClick (winClose)
							{
								target = self
							}
						}
					}
				}
			}
			--- TableColumn ---
				column-name = name !
				column-type = domain !
				domainAttribute = name !
				id = name
				table-column-width = 33
			{
				--- TableColumnItem ---
					item-column = name
					previewValue = value
			}
			--- TableColumn ---
				column-name = extDenomination !
				column-type = domain !
				domainAttribute = extDenomination !
				type = text
				id = extDenomination
				table-column-width = 33
			{
				--- TableColumnItem ---
					item-column = extDenomination
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = attributeEntityName
				sort-rank = 1
			--- TableSort ---
				sort-column-name = attributeName
				sort-rank = 2
			--- TableSort ---
				sort-column-name = code
				sort-rank = 3
			--- TableExtra ---
				domainAttribute = id
		}
	}
}