# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Type Search Criteria", fr = "Critères de recherche sur type", de = "Typ Suchbegriffe"
	containment = container
	domainEntity = "AAADSType:TypeSearchCriteria"
	search = input !
	bean-define = DSBean.AAADSType.TypeSearchCriteria
	bean-name = TypeSearchCriteria
	id = TypeSearchInput_IB3_8
	tid = 116145993655774
{
	--- Box ---
		boxType = vertical
	{
		--- FilterCriteria ---
			includedFile = "resource:/com/module/search/QueryBuilder.xsp"
		--- Include ---
			includeSrc = "" !
			resource:///default/search/NavigationSearchWithoutQueries.fragment
	}
}