# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Search Type", de = "Typ Suche", fr = "Recherche de type"
	containment = container
	search = container !
	cssClass = nodeco
	id = TypeSearch_Sde_9
	tid = 4565313668357
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/type/search/TypeSearchInput.module
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/type/search/TypeList.module
	}
}