# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Filter(s)", de = Filter, fr = "Filtre(s)"
	containment = container
	search = input !
	id = FilterLayer_t_H02
	tid = 261736863079246
{
	--- Box ---
		boxType = vertical
	{
		--- FilterCriteria ---
			includedFile = "resource:/com/module/search/QueryBuilder.xsp"
		--- Include ---
			includeSrc = "" !
			resource:///default/filter/FilterNavigation.fragment
	}
}