# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	containment = container
	domainEntity = "AAADSStrategy:StrategyAdmin"
	cssClass = nodeco
	bean-define = DSBean.AAADSStrategy.StrategyAdmin
	bean-name = StrategyAdmin
	id = CurrentObjectivesView_v_7W8
{
	--- Box ---
		boxType = vertical
	{
		--- Conditional ---
			indexOfSelectedChild = 0
		{
			--- ConditionalBody ---
				javaCode = "Integer.toString(com.odcgroup.aaa.StrategyNatureE.AssetAllocation).equals(<bean:get-property bean=\"StrategyAdmin\" property=\"natureE\"/>.toString())"
				technicalName = Allocation
				boxType = vertical
				isWidgetSelected = true
			{
				--- Box ---
					labels en = "Current Objectives", fr = "Objectifs actuels", de = "Aktuelle Ziele"
					boxType = vertical
					tid = 17324226570428
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/strategy/common/history/SelectedHistoryView.module
				}
			}
			--- ConditionalBody ---
				javaCode = true
				technicalName = "Other Natures"
				boxType = vertical
				isWidgetVisible = false
		}
	}
}