# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Classification Composition", fr = "Composition de la classification", de = "Zusammensetzung der Klassifizierung"
	domainEntity = "AAADSClassifCompo:ClassifCompoList"
	bean-define = DSBean.AAADSClassifCompo.ClassifCompoList
	bean-name = ClassifCompoList
	id = ClassifCompoList_E7_jG
	tid = 79556734686950
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			id = c__47
			table-column-count = 4 !
			table-columns-width = "25,25,25,25" !
		{
			--- TableColumn ---
				column-name = classificationCode !
				column-type = domain !
				domainAttribute = classificationCode !
				id = classificationCode
				table-column-width = 25
			{
				--- TableColumnItem ---
					item-column = classificationCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = listCode !
				column-type = domain !
				domainAttribute = listCode !
				id = listCode
				table-column-width = 25
			{
				--- TableColumnItem ---
					item-column = listCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = priorityN !
				column-type = domain !
				domainAttribute = priorityN !
				id = priorityN
				table-column-width = 25
			{
				--- TableColumnItem ---
					item-column = priorityN
					format = integer
					previewValue = value
			}
			--- TableColumn ---
				column-name = rankN !
				column-type = domain !
				domainAttribute = rankN !
				id = rankN
				table-column-width = 25
			{
				--- TableColumnItem ---
					item-column = rankN
					format = integer
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = classificationCode
				sort-rank = 1
			--- TableSort ---
				sort-column-name = listCode
				sort-rank = 2
		}
	}
}