# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = Notifications, fr = Notifications, de = Nachrichten
	domainEntity = "AAADSNotification:NotificationList"
	bean-define = DSBean.AAADSNotification.NotificationList
	bean-name = NotificationList
	id = NotificationList_Y8y_A
	tid = 1015396614659963
{
	--- Box ---
		boxType = vertical
	{
		--- Box ---
		{
			--- Button ---
				labels en = Delete, fr = Effaçer, de = Löschen
				id = btn_q6__D
				tid = 1015396616541487
			{
				Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = deleteNotifications ud
					only-changed = false
					prevalidate = false
					modal = false
				}
			}
			--- Button ---
				labels en = "Mark As Read", de = "Als gelesen markieren", fr = "Marquer comme lu"
				id = btn_Cw1_C
				tid = 1015396618492853
			{
				Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = toggleNotificationsRead ud
					only-changed = false
					prevalidate = false
					modal = false
				}
			}
			--- Button ---
				labels en = "Mark As Unread", fr = "Marquer comme non-lu", de = "Als ungelesen markieren"
				id = btn_BhL8_
				tid = 1015396620763253
			{
				Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = toggleNotificationsUnread ud
					only-changed = false
					prevalidate = false
					modal = false
				}
			}
			--- Glue ---
		}
		--- TableTree ---
			table-filter-layer = true
			id = Y6___
			table-column-count = 12 !
			table-columns-width = "8,8,8,8,8,8,8,8,8,8,8,8" !
		{
			--- TableColumn ---
				column-name = placeholder_IE262
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				id = i2436
				table-column-width = 8
			{
				--- CheckBox ---
					column-checkbox-action = selectednotifications
					column-checkbox-identifier = id
					horizontalTextPosition = trail
					id = btn_f_27O
			}
			--- TableColumn ---
				labels en = Delete, fr = Supprimer, de = Entfernen
				column-name = placeholder_QH0_k
				column-type = placeholder !
				type = text
				column-sortable = false !
				column-width = 10
				id = QH0_k
				table-column-width = 8
				tid = 1270473386240988
			{
				--- Icon ---
					toolTips en = Delete, fr = Supprimer, de = Entfernen
					horizontalAlignment = center
					icon = application_form_delete
					id = M_t6D
					tid = 1268880509703887
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = deleteNotification ud
						id = "<udp:item column=\"id\"/>" ud
						only-changed = false
						prevalidate = false
						modal = false
					}
				}
			}
			--- TableColumn ---
				labels en = View, fr = Voir, de = Ansicht
				column-name = placeholder_K_6X_
				column-type = placeholder !
				type = text
				column-sortable = false !
				column-width = 10
				id = K_6X_
				table-column-width = 8
				tid = 1270854071958866
			{
				--- Icon ---
					toolTips en = View, fr = Voir, de = Ansicht
					horizontalAlignment = center
					icon = application_form_magnify
					id = s60jY
					tid = 1270740031823039
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "resource:///monitoring/notification/NotificationDetails.pageflow"
						target = layer
						notifInstanceId = "<udp:item column=\"notifInstanceId\"/>" ud
						only-changed = false
						prevalidate = false
						modal = false
						notifRecipientId = "<udp:item column=\"id\"/>" ud
						notifInstanceNotifNatureE = "<udp:item column=\"notifInstanceNotifNatureE\"/>" ud
					}
				}
			}
			--- TableColumn ---
				labels en = Read, fr = Lu, de = Gelesen
				column-name = placeholder_G85N7
				column-type = placeholder !
				type = text
				column-sortable = false !
				column-width = 30
				id = Q64A_
				table-column-width = 8
				tid = 1015396622422961
			{
				--- Conditional ---
					indexOfSelectedChild = 1
				{
					--- ConditionalBody ---
						conditionLang = DSEL
						javaCode = "NotificationList.isReadF = \"1\""
						technicalName = isReadF
						boxType = vertical
						isWidgetVisible = false
					{
						--- Icon ---
							toolTips en = "Read Notification", fr = "Notification lue", de = "Gelesener Betreff"
							horizontalAlignment = center
							icon = email_open
							id = R_5_y
							tid = 1015396624356726
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = toggleNotificationUnread ud
								id = "<udp:item column=\"id\"/>" ud
								only-changed = false
								prevalidate = false
								modal = false
							}
						}
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips en = "Unread notification", fr = "Notification non-lue", de = "Nicht gelesener Betreff"
							horizontalAlignment = center
							icon = email
							id = m_Ys_
							tid = 1015396626424308
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = toggleNotificationRead ud
								id = "<udp:item column=\"id\"/>" ud
								only-changed = false
								prevalidate = false
								modal = false
							}
						}
					}
				}
			}
			--- TableColumn ---
				labels en = Importance, fr = Importance, de = Wichtigkeit toolTips en = Importance, fr = Importance, de = Wichtigkeit
				column-name = notifInstanceNotifImportanceE !
				column-type = domain !
				domainAttribute = notifInstanceNotifImportanceE !
				type = text
				id = notifInstanceNotifImportanceE
				table-column-width = 8
				tid = 1015396628269794
			{
				--- Conditional ---
					indexOfSelectedChild = 5
				{
					--- ConditionalBody ---
						conditionLang = DSEL
						javaCode = "NotificationList.notifInstanceNotifImportanceE == \"1\""
						technicalName = Success
						boxType = vertical
						isWidgetVisible = false
					{
						--- Icon ---
							toolTips en = Success, fr = Succès, de = "Erfolgreich abgeschlossen"
							horizontalAlignment = center
							icon = tick
							id = F_h_5
							tid = 1015396630216969
					}
					--- ConditionalBody ---
						conditionLang = DSEL
						javaCode = "NotificationList.notifInstanceNotifImportanceE == \"3\""
						technicalName = Failure
						boxType = vertical
						isWidgetVisible = false
					{
						--- Icon ---
							toolTips en = Failure, fr = Echec, de = "Fehlerhaft abgeschlossen"
							horizontalAlignment = center
							icon = exclamation
							id = o_4N9
							tid = 1015396632172524
					}
					--- ConditionalBody ---
						conditionLang = DSEL
						javaCode = "NotificationList.notifInstanceNotifImportanceE == \"4\""
						technicalName = Info
						boxType = vertical
						isWidgetVisible = false
					{
						--- Icon ---
							toolTips en = "For your information", fr = "A titre d\'information", de = "Zur Kenntnisnahme"
							horizontalAlignment = center
							icon = information
							id = v98R2
							tid = 1015396634133388
					}
					--- ConditionalBody ---
						conditionLang = DSEL
						javaCode = "NotificationList.notifInstanceNotifImportanceE == \"5\""
						technicalName = Warning
						boxType = vertical
						isWidgetVisible = false
					{
						--- Icon ---
							toolTips en = Warning, fr = Avertissement, de = Warnung
							horizontalAlignment = center
							icon = error
							id = W92__
							tid = 1015396636072741
					}
					--- ConditionalBody ---
						conditionLang = DSEL
						javaCode = "NotificationList.notifInstanceNotifImportanceE == \"6\""
						technicalName = Error
						boxType = vertical
						isWidgetVisible = false
					{
						--- Icon ---
							toolTips en = Error, fr = Erreur, de = "Fehler aufgetreten"
							horizontalAlignment = center
							icon = cross
							id = M__58
							tid = 1015396638033604
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetSelected = true
				}
			}
			--- TableColumn ---
				labels en = "Follow up", de = Behandeln, fr = Suivi
				column-name = notifInstanceUrlC !
				column-type = domain !
				domainAttribute = notifInstanceUrlC !
				type = text
				column-width = 40
				id = notifInstanceUrlC
				table-column-width = 8
				tid = 1015396643897199
			{
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						conditionLang = DSEL
						javaCode = "NotificationList.notifInstanceUrlC != null"
						technicalName = Condition
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							horizontalAlignment = center
							icon = bullet_go
							id = r15z_
						{
							Event OnClick (submit)
							{
								method = get
								call-URI = "<udp:item column=\"notifInstanceUrlC\"/>"
								target = self
								only-changed = false
								prevalidate = false
								modal = false
							}
						}
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetVisible = false
				}
			}
			--- TableColumn ---
				column-name = isReadF !
				column-type = domain !
				domainAttribute = isReadF !
				type = text
				column-visibility = never-visible
				id = isReadF
				table-column-width = 8
			--- TableColumn ---
				column-name = notifInstanceNotifNatureE !
				column-type = domain !
				domainAttribute = notifInstanceNotifNatureE !
				type = text
				id = notifInstanceNotifNatureE
				table-column-width = 8
			{
				--- TableColumnItem ---
					item-column = notifInstanceNotifNatureE
					previewValue = value
			}
			--- TableColumn ---
				labels en = Sender, fr = Expéditeur, de = Absender
				column-name = notifInstanceCreationUserCode !
				column-type = domain !
				domainAttribute = notifInstanceCreationUserCode !
				type = text
				column-width = 50
				id = notifInstanceCreationUserCode
				table-column-width = 8
				tid = 1110604086524404
			{
				--- TableColumnItem ---
					item-column = notifInstanceCreationUserCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = notifInstanceNotifPriorityE !
				column-type = domain !
				domainAttribute = notifInstanceNotifPriorityE !
				type = text
				id = notifInstanceNotifPriorityE
				table-column-width = 8
			{
				--- TableColumnItem ---
					item-column = notifInstanceNotifPriorityE
					previewValue = value
			}
			--- TableColumn ---
				column-name = subject !
				column-type = domain !
				domainAttribute = subject !
				type = text
				column-locked = true
				id = subject
				table-column-width = 8
			{
				--- TableColumnItem ---
					item-column = subject
					previewValue = value
			}
			--- TableColumn ---
				column-name = sentOnD !
				column-type = domain !
				domainAttribute = sentOnD !
				format = datetime.date-only
				type = text
				column-width = 100
				id = sentOnD
				table-column-width = 8
			{
				--- TableColumnItem ---
					item-column = sentOnD
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = sentOnD
				sort-direction = descending
				sort-rank = 1
			--- TableSort ---
				sort-column-name = notifInstanceNotifPriorityE
				sort-rank = 2
			--- TableExtra ---
				domainAttribute = notifInstanceId
			--- TableExtra ---
				domainAttribute = userId
			--- TableExtra ---
				domainAttribute = id
		}
	}
}