# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = Notifications, fr = Notifications, de = Nachrichten
	domainEntity = "AAADSNotification:NotificationList"
	bean-define = DSBean.AAADSNotification.NotificationList
	bean-name = NotificationList
	id = NotificationListNoMulti_a_4su
	documentation = "A notification list that does not expose the multi operation (multi delete, read/unread).\r\nThis version has been created because the multi operations expose some problems if the notification list is used under CDM."
	tid = 953166712406744
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			id = D_k_6
			table-column-count = 11 !
			table-columns-width = "9,9,9,9,9,9,9,9,9,9,9" !
		{
			--- TableColumn ---
				labels en = View, fr = Voir, de = Ansicht
				column-name = placeholder_K_6X_
				column-type = placeholder !
				type = text
				column-sortable = false !
				column-width = 10
				id = A_0_7
				table-column-width = 9
				tid = 953166720197958
			{
				--- Icon ---
					toolTips en = View, fr = Voir, de = Ansicht
					horizontalAlignment = "${corporatehalign}"
					icon = application_form_magnify
					id = n3ADz
					tid = 953166722146250
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "resource:///monitoring/notification/NotificationDetails.pageflow"
						target = layer
						notifInstanceId = "<udp:item column=\"notifInstanceId\"/>" ud
						only-changed = false
						prevalidate = false
						modal = false
						notifRecipientId = "<udp:item column=\"id\"/>" ud
						notifInstanceNotifNatureE = "<udp:item column=\"notifInstanceNotifNatureE\"/>" ud
					}
				}
			}
			--- TableColumn ---
				labels en = Delete, fr = Supprimer, de = Entfernen
				column-name = placeholder_QH0_k
				column-type = placeholder !
				type = text
				column-sortable = false !
				column-width = 10
				id = Z7Qb5
				table-column-width = 9
				tid = 953166724116612
			{
				--- Icon ---
					toolTips en = Delete, fr = Supprimer, de = Entfernen
					horizontalAlignment = center
					icon = application_form_delete
					id = E8iAf
					tid = 953166726027470
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = deleteNotification ud
						id = "<udp:item column=\"id\"/>" ud
						only-changed = false
						prevalidate = false
						modal = false
					}
				}
			}
			--- TableColumn ---
				labels en = Read, fr = Lu, de = Gelesen
				column-name = placeholder_G85N7
				column-type = placeholder !
				type = text
				column-sortable = false !
				column-width = 30
				id = X5t27
				table-column-width = 9
				tid = 953166728011800
			{
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						conditionLang = DSEL
						javaCode = "NotificationList.isReadF = \"1\""
						technicalName = isReadF
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips en = "Read Notification", fr = "Notification lue", de = "Gelesener Betreff"
							horizontalAlignment = "${corporatehalign}"
							icon = email_open
							id = h_RS_
							tid = 953166730041667
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = toggleNotificationUnread ud
								id = "<udp:item column=\"id\"/>" ud
								only-changed = false
								prevalidate = false
								modal = false
							}
						}
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetVisible = false
					{
						--- Icon ---
							toolTips en = "Unread notification", fr = "Notification non-lue", de = "Nicht gelesener Betreff"
							horizontalAlignment = "${corporatehalign}"
							icon = email
							id = Z__1_
							tid = 953166731908385
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = toggleNotificationRead ud
								id = "<udp:item column=\"id\"/>" ud
								only-changed = false
								prevalidate = false
								modal = false
							}
						}
					}
				}
			}
			--- TableColumn ---
				labels en = Importance, fr = Importance, de = Wichtigkeit toolTips en = Importance, fr = Importance, de = Wichtigkeit
				column-name = notifInstanceNotifImportanceE !
				column-type = domain !
				domainAttribute = notifInstanceNotifImportanceE !
				type = text
				id = notifInstanceNotifImportanceE
				table-column-width = 9
				tid = 953166733843826
			{
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						conditionLang = DSEL
						javaCode = "NotificationList.notifInstanceNotifImportanceE == \"1\""
						technicalName = Success
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips en = Success, fr = Succès, de = "Erfolgreich abgeschlossen"
							horizontalAlignment = center
							icon = tick
							id = T_4z_
							tid = 953166735811953
					}
					--- ConditionalBody ---
						conditionLang = DSEL
						javaCode = "NotificationList.notifInstanceNotifImportanceE == \"3\""
						technicalName = Failure
						boxType = vertical
						isWidgetVisible = false
					{
						--- Icon ---
							toolTips en = Failure, fr = Echec, de = "Fehlerhaft abgeschlossen"
							horizontalAlignment = center
							icon = lightning
							id = Fs_q_
							tid = 953166737757452
					}
					--- ConditionalBody ---
						conditionLang = DSEL
						javaCode = "NotificationList.notifInstanceNotifImportanceE == \"4\""
						technicalName = Info
						boxType = vertical
						isWidgetVisible = false
					{
						--- Icon ---
							toolTips en = "For your information", fr = "A titre d\'information", de = "Zur Kenntnisnahme"
							horizontalAlignment = center
							icon = m_info
							id = f_8r6
							tid = 953166739726697
					}
					--- ConditionalBody ---
						conditionLang = DSEL
						javaCode = "NotificationList.notifInstanceNotifImportanceE == \"5\""
						technicalName = Warning
						boxType = vertical
						isWidgetVisible = false
					{
						--- Icon ---
							toolTips en = Warning, fr = Avertissement, de = Warnung
							horizontalAlignment = center
							icon = m_warn
							id = ebV4_
							tid = 953166741653757
					}
					--- ConditionalBody ---
						conditionLang = DSEL
						javaCode = "NotificationList.notifInstanceNotifImportanceE == \"6\""
						technicalName = Error
						boxType = vertical
						isWidgetVisible = false
					{
						--- Icon ---
							toolTips en = Error, fr = Erreur, de = "Fehler aufgetreten"
							horizontalAlignment = center
							icon = cross
							id = hR_64
							tid = 953166743604564
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetVisible = false
				}
			}
			--- TableColumn ---
				column-name = isReadF !
				column-type = domain !
				domainAttribute = isReadF !
				type = text
				column-visibility = never-visible
				id = isReadF
				table-column-width = 9
			--- TableColumn ---
				column-name = notifInstanceNotifNatureE !
				column-type = domain !
				domainAttribute = notifInstanceNotifNatureE !
				type = text
				id = notifInstanceNotifNatureE
				table-column-width = 9
			{
				--- TableColumnItem ---
					item-column = notifInstanceNotifNatureE
					previewValue = value
			}
			--- TableColumn ---
				labels en = Sender, fr = Expéditeur, de = Absender
				column-name = notifInstanceCreationUserCode !
				column-type = domain !
				domainAttribute = notifInstanceCreationUserCode !
				type = text
				column-width = 50
				id = notifInstanceCreationUserCode
				table-column-width = 9
				tid = 953166745559282
			{
				--- TableColumnItem ---
					item-column = notifInstanceCreationUserCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = notifInstanceNotifPriorityE !
				column-type = domain !
				domainAttribute = notifInstanceNotifPriorityE !
				type = text
				id = notifInstanceNotifPriorityE
				table-column-width = 9
			{
				--- TableColumnItem ---
					item-column = notifInstanceNotifPriorityE
					previewValue = value
			}
			--- TableColumn ---
				column-name = subject !
				column-type = domain !
				domainAttribute = subject !
				type = text
				id = subject
				table-column-width = 9
			{
				--- TableColumnItem ---
					item-column = subject
					previewValue = value
			}
			--- TableColumn ---
				column-name = sentOnD !
				column-type = domain !
				domainAttribute = sentOnD !
				format = datetime.date-only
				type = text
				column-width = 100
				id = sentOnD
				table-column-width = 9
			{
				--- TableColumnItem ---
					item-column = sentOnD
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Follow up", de = Behandeln, fr = Suivi
				column-name = notifInstanceUrlC !
				column-type = domain !
				domainAttribute = notifInstanceUrlC !
				type = text
				column-width = 40
				id = notifInstanceUrlC
				table-column-width = 9
				tid = 953166747804260
			{
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						conditionLang = DSEL
						javaCode = "NotificationList.notifInstanceUrlC != null"
						technicalName = Condition
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							horizontalAlignment = "${corporatehalign}"
							icon = bullet_go
							id = I__7_
						{
							Event OnClick (submit)
							{
								method = get
								call-URI = "<udp:item column=\"notifInstanceUrlC\"/>"
								target = self
								only-changed = false
								prevalidate = false
								modal = false
							}
						}
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetVisible = false
				}
			}
			--- TableSort ---
				sort-column-name = isReadF
				sort-direction = descending
				sort-rank = 1
			--- TableSort ---
				sort-column-name = sentOnD
				sort-direction = descending
				sort-rank = 2
			--- TableSort ---
				sort-column-name = notifInstanceNotifPriorityE
				sort-rank = 3
			--- TableExtra ---
				domainAttribute = notifInstanceId
			--- TableExtra ---
				domainAttribute = userId
			--- TableExtra ---
				domainAttribute = id
		}
	}
}