# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Alert Notifications"
	containment = container
	domainEntity = "AlertDef:AlertDefAll"
	bean-define = DSBean.AlertDef.AlertDefAll
	bean-name = AlertDefAll
	id = NotificationAlertDetails_ow7__
	tid = 983801520460437
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/monitoring/notification/NotificationDetails.module
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/alerts/view/AlertDefView.module
		--- Conditional ---
			indexOfSelectedChild = 2
		{
			--- ConditionalBody ---
				javaCode = "\"portfolio\".equals(<bean:get-property bean=\"AlertDefAll\" property=\"entity.sqlnameC\"/>)"
				technicalName = Portfolio
				boxType = vertical
				isWidgetVisible = false
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/alerts/view/AlertPortfolioQueryView.module
			}
			--- ConditionalBody ---
				javaCode = "\"third_party\".equals(<bean:get-property bean=\"AlertDefAll\" property=\"entity.sqlnameC\"/>)"
				technicalName = ThirdParty
				boxType = vertical
				isWidgetVisible = false
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/alerts/view/AlertClientQueryView.module
			}
			--- ConditionalBody ---
				javaCode = "\"instrument\".equals(<bean:get-property bean=\"AlertDefAll\" property=\"entity.sqlnameC\"/>)"
				technicalName = Instrument
				boxType = vertical
				isWidgetSelected = true
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/alerts/view/AlertInstrumentQueryView.module
			}
		}
	}
}