# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Notification Details", fr = "Détails de notification", de = Nachrichtendetails
	domainEntity = "AAADSNotification:NotificationInstanceDetails"
	bean-define = DSBean.AAADSNotification.NotificationInstanceDetails
	bean-name = NotificationInstanceDetails
	id = NotificationDetails_e6___
	tid = 522825502153765
{
	--- Box ---
		boxType = vertical
		horizontalAlignment = center
	{
		--- Box ---
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 6
				gridColumnsWidth = "16,16,16,16,16,16" !
				gridRowCount = 1
			{
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = notifImportanceE !
						for = notifImportanceE
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
						id = notifImportanceE
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- ComboBox ---
						domainAttribute = notifImportanceE !
						horizontalAlignment = "${corporatehalign}"
						editable = false
						required = true
						bean-property = notifImportanceE
						id = notifImportanceE
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = notifPriorityE !
						for = notifPriorityE
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
						id = notifPriorityE
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- ComboBox ---
						domainAttribute = notifPriorityE !
						horizontalAlignment = "${corporatehalign}"
						editable = false
						required = true
						bean-property = notifPriorityE
						id = notifPriorityE
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- LabelDomain ---
						domainAttribute = notifNatureE !
						for = notifNatureE
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
						id = notifNatureE
				}
				--- GridCell ---
					gridColumnWidth = 16
				{
					--- ComboBox ---
						domainAttribute = notifNatureE !
						horizontalAlignment = "${corporatehalign}"
						editable = false
						required = true
						bean-property = notifNatureE
						id = notifNatureE
				}
			}
		}
		--- Spacer ---
			height = 20
			width = 4
		--- Grid ---
			cssClass = blank
			gridColumnCount = 2
			gridColumnsWidth = "30,70" !
			gridRowCount = 2
		{
			--- GridCell ---
				gridColumnWidth = 30
			{
				--- LabelDomain ---
					domainAttribute = subject !
					for = subject
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					id = subject
			}
			--- GridCell ---
				gridColumnWidth = 70
			{
				--- TextField ---
					domainAttribute = subject !
					columns = 60
					horizontalAlignment = "${corporatehalign}"
					type = text
					editable = false
					bean-property = subject
					id = subject
			}
			--- GridCell ---
				gridColumnWidth = 30
			{
				--- LabelDomain ---
					domainAttribute = body !
					for = body
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					id = body
			}
			--- GridCell ---
				gridColumnWidth = 70
			{
				--- TextArea ---
					domainAttribute = body
					columns = 60
					richText = true
					rows = 4
					editable = false
					bean-property = body
					id = body
			}
		}
		--- Spacer ---
			height = 20
			width = 4
		--- Conditional ---
			indexOfSelectedChild = 0
		{
			--- ConditionalBody ---
				conditionLang = DSEL
				javaCode = "NotificationInstanceDetails.urlC != NULL"
				technicalName = Condition
				isWidgetSelected = true
			{
				--- Box ---
					boxType = vertical
					horizontalAlignment = center
				{
					--- Button ---
						labels en = "Follow up", fr = Suivi, de = Weiterverfolgen
						horizontalAlignment = center
						horizontalTextPosition = center
						id = btn_A_W_6
						tid = 522951174356238
					{
						Event OnClick (submit)
						{
							method = get
							call-URI = "<bean:get-property bean=\"NotificationInstanceDetails\" property=\"url\"/>"
							target = WUI_main
							only-changed = false
							prevalidate = false
							modal = false
						}
					}
				}
			}
			--- ConditionalBody ---
				javaCode = true
				technicalName = Default
				boxType = vertical
				isWidgetVisible = false
		}
	}
}