# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSPerformance:PerformanceGlobalDetails"
	cssClass = nodeco
	bean-define = DSBean.AAADSPerformance.PerformanceGlobalDetails
	bean-name = PerformanceGlobalDetails
	id = PerformanceGlobalEffects_o55_w
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			table-page-size = 50
			id = E1l1F
			table-column-count = 17 !
			table-columns-width = "5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5" !
		{
			--- TableColumn ---
				column-name = PERIOD_DISPLAY !
				column-type = domain !
				domainAttribute = PERIOD_DISPLAY !
				type = text
				column-locked = true
				column-sortable = false
				id = PERIOD_DISPLAY
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = PERIOD_DISPLAY
					previewValue = value
			}
			--- TableColumn ---
				column-name = PERIOD_RET_TWR !
				column-type = domain !
				domainAttribute = PERIOD_RET_TWR !
				type = text
				column-sortable = false
				id = PERIOD_RET_TWR
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = PERIOD_RET_TWR
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = CUMUL_TOT_RET !
				column-type = domain !
				domainAttribute = CUMUL_TOT_RET !
				type = text
				column-sortable = false
				id = CUMUL_TOT_RET
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = CUMUL_TOT_RET
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = PERIOD_TOT_RET_BENCH !
				column-type = domain !
				domainAttribute = PERIOD_TOT_RET_BENCH !
				type = text
				column-sortable = false
				id = PERIOD_TOT_RET_BENCH
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = PERIOD_TOT_RET_BENCH
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = CUMUL_TOT_RET_BENCH !
				column-type = domain !
				domainAttribute = CUMUL_TOT_RET_BENCH !
				type = text
				column-sortable = false
				id = CUMUL_TOT_RET_BENCH
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = CUMUL_TOT_RET_BENCH
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = OVER_UNDER_PERFORMANCE !
				column-type = domain !
				domainAttribute = OVER_UNDER_PERFORMANCE !
				type = text
				column-sortable = false
				id = OVER_UNDER_PERFORMANCE
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = OVER_UNDER_PERFORMANCE
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = CUMUL_OVER_PERF !
				column-type = domain !
				domainAttribute = CUMUL_OVER_PERF !
				type = text
				column-sortable = false
				id = CUMUL_OVER_PERF
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = CUMUL_OVER_PERF
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = PERIOD_CAP_EFFECT !
				column-type = domain !
				domainAttribute = PERIOD_CAP_EFFECT !
				type = text
				column-sortable = false
				id = PERIOD_CAP_EFFECT
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = PERIOD_CAP_EFFECT
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = CUMUL_CAP_EFFECT !
				column-type = domain !
				domainAttribute = CUMUL_CAP_EFFECT !
				type = text
				column-sortable = false
				id = CUMUL_CAP_EFFECT
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = CUMUL_CAP_EFFECT
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = PERIOD_CURR_EFFECT !
				column-type = domain !
				domainAttribute = PERIOD_CURR_EFFECT !
				type = text
				column-sortable = false
				id = PERIOD_CURR_EFFECT
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = PERIOD_CURR_EFFECT
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = CUMUL_CURR_EFFECT !
				column-type = domain !
				domainAttribute = CUMUL_CURR_EFFECT !
				type = text
				column-sortable = false
				id = CUMUL_CURR_EFFECT
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = CUMUL_CURR_EFFECT
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = PERIOD_INCOME_EFFECT !
				column-type = domain !
				domainAttribute = PERIOD_INCOME_EFFECT !
				type = text
				column-sortable = false
				id = PERIOD_INCOME_EFFECT
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = PERIOD_INCOME_EFFECT
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = CUMUL_INCOME_EFFECT !
				column-type = domain !
				domainAttribute = CUMUL_INCOME_EFFECT !
				type = text
				column-sortable = false
				id = CUMUL_INCOME_EFFECT
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = CUMUL_INCOME_EFFECT
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = PERIOD_F_T_EFFECT !
				column-type = domain !
				domainAttribute = PERIOD_F_T_EFFECT !
				type = text
				column-sortable = false
				id = PERIOD_F_T_EFFECT
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = PERIOD_F_T_EFFECT
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = CUMUL_F_T_EFFECT !
				column-type = domain !
				domainAttribute = CUMUL_F_T_EFFECT !
				type = text
				column-sortable = false
				id = CUMUL_F_T_EFFECT
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = CUMUL_F_T_EFFECT
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = PERIOD_CROSS_EFFECT !
				column-type = domain !
				domainAttribute = PERIOD_CROSS_EFFECT !
				type = text
				column-sortable = false
				id = PERIOD_CROSS_EFFECT
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = PERIOD_CROSS_EFFECT
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = CUMUL_CROSS_EFFECT !
				column-type = domain !
				domainAttribute = CUMUL_CROSS_EFFECT !
				type = text
				column-sortable = false
				id = CUMUL_CROSS_EFFECT
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = CUMUL_CROSS_EFFECT
					format = percentTA
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = PERIOD_FINAL_DATE
				sort-rank = 1
			--- TableKeepFilter ---
				keep-filter-column-name = PORTFOLIO_LEVEL_FILTER
				keep-filter-operand = 1
			--- TableKeepFilter ---
				keep-filter-column-name = GLOBAL_FILTER
				keep-filter-operand = 0
		}
	}
}