# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSPerformance:PerformanceGlobalDetails"
	cssClass = nodeco
	bean-define = DSBean.AAADSPerformance.PerformanceGlobalDetails
	bean-name = PerformanceGlobalDetails
	id = PerformanceGlobalReturn_z2R_8
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			table-page-size = 50
			id = z1Ty3
			table-column-count = 28 !
			table-columns-width = "3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3" !
		{
			--- TableColumn ---
				column-name = PERIOD_DISPLAY !
				column-type = domain !
				domainAttribute = PERIOD_DISPLAY !
				type = text
				column-locked = true
				column-sortable = false
				id = PERIOD_DISPLAY
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = PERIOD_DISPLAY
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Initial Market Value", fr = "Valeur d\'inventaire initiale", de = Anfangs-Marktwert
				column-name = InitialMarketValue
				type = amount
				column-sortable = false
				id = Rg_CD
				column-computation = make-amount
				column-computation-parameters = "PERIOD_INITIAL_MKT_VAL,REF_CURRENCY"
				table-column-width = 3
				tid = 14569221275945
			{
				--- TableColumnItem ---
					item-column = InitialMarketValue
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Final Market Value", fr = "Valeur d\'inventaire finale", de = End-Marktwert
				column-name = FinalMarketValue
				type = amount
				column-sortable = false
				id = fv02_
				column-computation = make-amount
				column-computation-parameters = "PERIOD_FINAL_MKT_VAL,REF_CURRENCY"
				table-column-width = 3
				tid = 14569223002575
			{
				--- TableColumnItem ---
					item-column = FinalMarketValue
					previewValue = value
			}
			--- TableColumn ---
				labels de = Zuflüsse/Abflüsse, fr = Apport/retrait, en = Investment/Withdrawal
				column-name = InvestmentWithdrawal
				type = amount
				column-sortable = false
				id = M968g
				column-computation = make-amount
				column-computation-parameters = "PERIOD_INVEST_WITHDRAWAL,REF_CURRENCY"
				table-column-width = 3
				tid = 14569224956521
			{
				--- TableColumnItem ---
					item-column = InvestmentWithdrawal
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Profit & Loss", fr = "Profits & pertes", de = "Gewinn & Verlust"
				column-name = ProfitLoss
				type = amount
				column-sortable = false
				id = e_2_f
				column-computation = make-amount
				column-computation-parameters = "PERIOD_GAIN_LOSS,REF_CURRENCY"
				table-column-width = 3
				tid = 14569226910092
			{
				--- TableColumnItem ---
					item-column = ProfitLoss
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Gain & Loss Cumul", fr = "Profits & pertes cumulés", de = "Kum. Gewinn & Verlust"
				column-name = CummulativeGainLoss
				type = amount
				column-sortable = false
				column-visibility = not-visible
				id = y8Gl0
				column-computation = make-amount
				column-computation-parameters = "CUMULATED_GAIN_LOSS,REF_CURRENCY"
				table-column-width = 3
				tid = 14569228868694
			{
				--- TableColumnItem ---
					item-column = CummulativeGainLoss
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Mean Capital", fr = "Capital moyen", de = "Durchschnittl. Kapital"
				column-name = MeanCap
				type = amount
				column-sortable = false
				column-visibility = not-visible
				id = Ll_p4
				column-computation = make-amount
				column-computation-parameters = "MEAN_CAP,REF_CURRENCY"
				table-column-width = 3
				tid = 14569230823458
			{
				--- TableColumnItem ---
					item-column = MeanCap
					previewValue = value
			}
			--- TableColumn ---
				column-name = PERIOD_RET_MWR !
				column-type = domain !
				domainAttribute = PERIOD_RET_MWR !
				type = text
				column-sortable = false
				column-visibility = not-visible
				id = PERIOD_RET_MWR
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = PERIOD_RET_MWR
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = PERIOD_RET_TWR !
				column-type = domain !
				domainAttribute = PERIOD_RET_TWR !
				type = text
				column-sortable = false
				id = PERIOD_RET_TWR
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = PERIOD_RET_TWR
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Cumul Return", de = "Kum. Rendite", fr = "Rendement cumulé"
				column-name = CUMUL_TOT_RET !
				column-type = domain !
				domainAttribute = CUMUL_TOT_RET !
				type = text
				column-sortable = false
				column-visibility = not-visible
				id = CUMUL_TOT_RET
				table-column-width = 3
				tid = 14569232776776
			{
				--- TableColumnItem ---
					item-column = CUMUL_TOT_RET
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Capital P&L", fr = "G&P sur capital", de = Kapital-G/V
				column-name = PeriodCapitalProfitLoss
				type = amount
				column-sortable = false
				id = S_11_
				column-computation = make-amount
				column-computation-parameters = "PERIOD_CAP_PL,REF_CURRENCY"
				table-column-width = 3
				tid = 14569234719183
			{
				--- TableColumnItem ---
					item-column = PeriodCapitalProfitLoss
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Capital P&L Cumul", fr = "G&P sur capital cumulés", de = "Kum. Kapital-G/V"
				column-name = CummulativeCapitalProfitLoss
				type = amount
				column-sortable = false
				column-visibility = not-visible
				id = d___9
				column-computation = make-amount
				column-computation-parameters = "CUMUL_CAP_PL,REF_CURRENCY"
				table-column-width = 3
				tid = 14569236671358
			{
				--- TableColumnItem ---
					item-column = CummulativeCapitalProfitLoss
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Real. Capital P&L", fr = "G&P sur capital réalisés", de = "Real. Kapital-G/V"
				column-name = PeriodRealCapitalProfitLoss
				type = amount
				column-sortable = false
				column-visibility = not-visible
				id = ZZ9__
				column-computation = make-amount
				column-computation-parameters = "PERIOD_REAL_CAP_PL,REF_CURRENCY"
				table-column-width = 3
				tid = 14569238623166
			{
				--- TableColumnItem ---
					item-column = PeriodRealCapitalProfitLoss
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Cumul Real. Capital P&L", fr = "G&P sur capital réalisés cumulés", de = "Kum. Real. Kapital-G/V" toolTips en = "Cumulated Realized Capital Profit & Loss", fr = "Gains & pertes cumulés en capital réalisés", de = "Kumul. Realisierter Kapital Gewinn & Verlust"
				column-name = CummulativeRealCapitalProfitLoss
				type = amount
				column-sortable = false
				column-visibility = not-visible
				id = C2__1
				column-computation = make-amount
				column-computation-parameters = "CUMUL_REAL_CAP_PL,REF_CURRENCY"
				table-column-width = 3
				tid = 14569240575423
			{
				--- TableColumnItem ---
					item-column = CummulativeRealCapitalProfitLoss
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Unreal. Capital P&L", fr = "G&P sur capital non réalisés", de = "Unreal. Kapital-G/V"
				column-name = PeriodUnrealizedCapitalProfitLoss
				type = amount
				column-sortable = false
				column-visibility = not-visible
				id = YL6_2
				column-computation = make-amount
				column-computation-parameters = "CUMUL_UNREAL_CAP_PL,REF_CURRENCY"
				table-column-width = 3
				tid = 14569242535658
			{
				--- TableColumnItem ---
					item-column = PeriodUnrealizedCapitalProfitLoss
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Unreal. Capital P&L Cumul", fr = "G&P  sur capital non réalisés et cumulés", de = "Kum. Unreal. Kapital-G/V"
				column-name = CummulativeUnrealizedProfitLoss
				type = amount
				column-sortable = false
				column-visibility = not-visible
				id = f8_R_
				column-computation = make-amount
				column-computation-parameters = "CUMUL_UNREAL_CAP_PL,REF_CURRENCY"
				table-column-width = 3
				tid = 14569244484416
			{
				--- TableColumnItem ---
					item-column = CummulativeUnrealizedProfitLoss
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Currency P&L", fr = "G&P sur devise", de = Währungs-G/V toolTips en = "Period Currency Profit & Loss", fr = "Gains & pertes sur devise par période", de = "Währungs- Gewinn & Verlust der Periode"
				column-name = PeriodCurrencyProfitLoss
				type = amount
				column-sortable = false
				id = DZ_5_
				column-computation = make-amount
				column-computation-parameters = "PERIOD_CURR_PL,REF_CURRENCY"
				table-column-width = 3
				tid = 14569246448206
			{
				--- TableColumnItem ---
					item-column = PeriodCurrencyProfitLoss
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Currency P&L Cumul", fr = "G&P sur devise cumulé", de = "Kum. Währungs-G/V" toolTips en = "Cumulated Currency Profit & Loss", fr = "Gains & pertes cumulés sur devise", de = "Kumul. Währungs- Gewinn & Verlust"
				column-name = CummulativeCurrencyProfitLoss
				type = amount
				column-sortable = false
				column-visibility = not-visible
				id = K7__7
				column-computation = make-amount
				column-computation-parameters = "CUMUL_CURR_PL,REF_CURRENCY"
				table-column-width = 3
				tid = 14569248388261
			{
				--- TableColumnItem ---
					item-column = CummulativeCurrencyProfitLoss
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Real. Currency P&L", fr = "G&P sur devise réalisés", de = "Real. Währungs-G/V"
				column-name = PeroidRealCurrencyPriofitLoss
				type = amount
				column-sortable = false
				column-visibility = not-visible
				id = yL_6J
				column-computation = make-amount
				column-computation-parameters = "PERIOD_REAL_CURR_PL,REF_CURRENCY"
				table-column-width = 3
				tid = 14569250351751
			{
				--- TableColumnItem ---
					item-column = PeroidRealCurrencyPriofitLoss
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Real. Currency P&L Cumul", fr = "G&P sur devise réalisés et cumulés", de = "Kum. Real. Währungs-G/V" toolTips en = "Period Realized Currency Profit & Loss", fr = "Gains & pertes sur devise réalisés par Période", de = "Realisierter Währungs- Gewinn & Verlust der Periode"
				column-name = CummulativeRealCurrencyProfitLoss
				type = amount
				column-sortable = false
				column-visibility = not-visible
				id = LKRI_
				column-computation = make-amount
				column-computation-parameters = "CUMUL_REAL_CURR_PL,REF_CURRENCY"
				table-column-width = 3
				tid = 14569252302632
			{
				--- TableColumnItem ---
					item-column = CummulativeRealCurrencyProfitLoss
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Unreal. Currency P&L", fr = "G&P sur devise non réalisés", de = "Unreal. Währungs-G/V" toolTips en = "Period Unrealized Currency Profit & Loss", fr = "Gains & pertes sur devise non réalisés par période", de = "Unrealisierter Währungs- Gewinn & Verlust der Periode"
				column-name = PeriodUnrealizedCurrencyProfitLoss
				type = amount
				column-sortable = false
				column-visibility = not-visible
				id = B_B_c
				column-computation = make-amount
				column-computation-parameters = "PERIOD_UNREAL_CURR_PL,REF_CURRENCY"
				table-column-width = 3
				tid = 14569254253962
			{
				--- TableColumnItem ---
					item-column = PeriodUnrealizedCurrencyProfitLoss
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Unreal. Currency P&L Cumul", fr = "G&P sur devise non réalisés et cumulés", de = "Kum. Unreal. Währungs-G/V" toolTips en = "Cumulated Unrealized Currency Profit & Loss", fr = "Gains & pertes cumulés sur devise non réalisés", de = "Kumul. Unrealisierter Währungs- Gewinn & Verlust"
				column-name = CummulativeUnrealizedCurrencyProfitLoss
				type = amount
				column-sortable = false
				column-visibility = not-visible
				id = S69N_
				column-computation = make-amount
				column-computation-parameters = "CUMUL_UNREAL_CURR_PL,REF_CURRENCY"
				table-column-width = 3
				tid = 14569256201569
			{
				--- TableColumnItem ---
					item-column = CummulativeUnrealizedCurrencyProfitLoss
					previewValue = value
			}
			--- TableColumn ---
				labels en = Income, fr = Revenu, de = Ertrag toolTips en = "Period Income", fr = "Revenu par période", de = "Ertrag der Periode"
				column-name = PeriodIncome
				type = amount
				column-sortable = false
				id = au90Y
				column-computation = make-amount
				column-computation-parameters = "PERIOD_INCOME,REF_CURRENCY"
				table-column-width = 3
				tid = 14569258154499
			{
				--- TableColumnItem ---
					item-column = PeriodIncome
					previewValue = value
			}
			--- TableColumn ---
				labels fr = "Revenu cumulé", en = "Cumul Income", de = "Kum. Ertrag" toolTips en = "Cumulated Income", fr = "Revenu cumulé", de = "Kum. Ertrag"
				column-name = CummulativeIncome
				type = amount
				column-sortable = false
				column-visibility = not-visible
				id = J0Q95
				column-computation = make-amount
				column-computation-parameters = "CUMUL_INCOME,REF_CURRENCY"
				table-column-width = 3
				tid = 14569260108722
			{
				--- TableColumnItem ---
					item-column = CummulativeIncome
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Fees & Taxes", fr = "Frais & taxes", de = Gebühren/Steuern toolTips en = "Period Fees & Taxes", fr = "Frais & taxes par période", de = "Gebühren & Steuern der Periode"
				column-name = PeriodFeeTax
				type = amount
				column-sortable = false
				id = asHY_
				column-computation = make-amount
				column-computation-parameters = "PERIOD_FEE_TAX,REF_CURRENCY"
				table-column-width = 3
				tid = 14569262060281
			{
				--- TableColumnItem ---
					item-column = PeriodFeeTax
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Fees & Taxes Cumul", fr = "Frais & taxes cumulé", de = "Kum. Gebühren/Steuern"
				column-name = CummulativeFeesTax
				type = amount
				column-sortable = false
				column-visibility = not-visible
				id = q_q_6
				column-computation = make-amount
				column-computation-parameters = "CUMUL_FEE_TAX,REF_CURRENCY"
				table-column-width = 3
				tid = 14569264017063
			{
				--- TableColumnItem ---
					item-column = CummulativeFeesTax
					previewValue = value
			}
			--- TableColumn ---
				column-name = PERIOD_TOT_RET_BENCH !
				column-type = domain !
				domainAttribute = PERIOD_TOT_RET_BENCH !
				type = text
				column-sortable = false
				id = PERIOD_TOT_RET_BENCH
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = PERIOD_TOT_RET_BENCH
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				column-name = CUMUL_TOT_RET_BENCH !
				column-type = domain !
				domainAttribute = CUMUL_TOT_RET_BENCH !
				type = text
				column-sortable = false
				column-visibility = not-visible
				id = CUMUL_TOT_RET_BENCH
				table-column-width = 3
			{
				--- TableColumnItem ---
					item-column = CUMUL_TOT_RET_BENCH
					format = percentTA
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = PERIOD_FINAL_DATE
				sort-rank = 1
			--- TableKeepFilter ---
				keep-filter-column-name = PORTFOLIO_LEVEL_FILTER
				keep-filter-operand = 1
			--- TableKeepFilter ---
				keep-filter-column-name = GLOBAL_FILTER
				keep-filter-operand = 0
		}
	}
}