# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Strategy Link Details", fr = "Détails du lien de stratégie", de = "Strategieverknüpfung Details"
	containment = container
	domainEntity = "AAADSStrategyLink:StrategyLinkDetails"
	bean-define = DSBean.AAADSStrategyLink.StrategyLinkDetails
	bean-name = StrategyLinkDetails
	id = StrategyLinkDetails_Ik_3g
	documentation = "This module is used to display the strategy link\'s attributes and details of associated strategy"
	tid = 100353664150655
{
	--- Box ---
		boxType = vertical
	{
		--- Box ---
			labels en = Details, fr = Détails, de = Details
			boxType = vertical
			tid = 100353666096753
		{
			--- Include ---
				includeSrc = "" !
				resource:///Default/module/aaa/administration/strategylink/StrategyLinkDefinition.module
		}
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/strategylink/AssociatedStrategyDetails.module
	}
}