# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = Scorecard, fr = "Tableau de bord", de = Cockpit
	domainEntity = "AAADSThirdParty:ThirdPartyListDashboardSC"
	bean-define = DSBean.AAADSThirdParty.ThirdPartyListDashboardSC
	bean-name = ThirdPartyListDashboardSC
	id = ClientScorecard_i29__
	tid = 1746788707275645
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			table-rendering-mode = summary-delegated
			id = Lr___
			table-column-count = 8 !
			table-columns-width = "12,12,12,12,12,12,12,12" !
		{
			--- TableColumn ---
				labels en = Category, fr = Catégorie, de = Kategorie
				column-display-grouping = true
				column-name = placeholder_z_7_o
				column-type = placeholder !
				type = text
				column-sortable = false !
				column-width = 50
				id = z_7_o
				table-column-width = 12
				tid = 1815283797953930
			{
				--- TableGroup ---
					aggregateData = false
					group-column-name = extBiCategory
					group-sorting-column-name = extBiCategory
					group-sorting-direction = ascending
					group-rank = 1
			}
			--- TableColumn ---
				labels en = "Market Value Drop", fr = "Chute valeur de marché", de = Marktwertsverlust toolTips en = "Market Value of one or more of the client\'s portfolios has fallen > 2 %", fr = "Valeur de marché d\'un ou plusieurs des portefeuilles du client a chuté > 2 %", de = "Marktwert eines oder mehreren der Kundendepots ist um mehr als 2 % gefallen"
				column-name = extBiMktValDrop !
				column-type = domain !
				domainAttribute = extBiMktValDrop !
				type = text
				column-sortable = false
				id = extBiMktValDrop
				table-column-width = 12
				tid = 202305775920403
			{
				--- TableColumnItem ---
					item-column = extBiMktValDrop
					format = integer
					previewValue = value
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = displayDashboardDetailsClient ud
						Query.fs_E8Q.f2.attribute = extBiCategory ud
						Query.fs_E8Q.f2.Op = EQUAL ud
						Query.fs_E8Q.f2.value1 = "<udp:item column=\"extBiCategory\" />" ud
						Query.fs_E8Q.f2.mode = HIDDEN ud
						only-changed = false
						prevalidate = false
						modal = false
						Query.fs_E8Q.f3.attribute = activeF ud
						Query.fs_E8Q.f3.Op = EQUAL ud
						Query.fs_E8Q.f3.value1 = 1 ud
						Query.fs_E8Q.f3.mode = HIDDEN ud
						Snippet FilterSet
						id = fs_E8Q
						level = 1
						targetDataset = "AAADSThirdParty:ThirdPartyListDashboardDetails"
						{
							Snippet Filter
							attribute = extBiMktValDrop
							filterValue = 1
							operator = EQUAL
						}
					}
				}
			}
			--- TableColumn ---
				labels fr = "Dernière proposition"
				toolTips en = "Last Proposal is longer than 180 days ago", fr = "La dernière proposition a été soumise depuis plus que 180 jours", de = "Letzter Vorschlag wurde vor mehr als 180 Tagen gemacht"
				column-name = extBiDaysProposal !
				column-type = domain !
				domainAttribute = extBiDaysProposal !
				type = text
				column-sortable = false
				id = extBiDaysProposal
				table-column-width = 12
				tid = 202945685543833
			{
				--- TableColumnItem ---
					item-column = extBiDaysProposal
					format = integer
					previewValue = value
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = displayDashboardDetailsClient ud
						Query.fs_E8Q.f2.attribute = extBiCategory ud
						Query.fs_E8Q.f2.Op = EQUAL ud
						Query.fs_E8Q.f2.value1 = "<udp:item column=\"extBiCategory\" />" ud
						Query.fs_E8Q.f2.mode = HIDDEN ud
						only-changed = false
						prevalidate = false
						modal = false
						Query.fs_E8Q.f3.attribute = activeF ud
						Query.fs_E8Q.f3.Op = EQUAL ud
						Query.fs_E8Q.f3.value1 = 1 ud
						Query.fs_E8Q.f3.mode = HIDDEN ud
						Snippet FilterSet
						id = fs_E8Q
						level = 1
						targetDataset = "AAADSThirdParty:ThirdPartyListDashboardDetails"
						{
							Snippet Filter
							attribute = extBiDaysProposal
							filterValue = 1
							operator = EQUAL
						}
					}
				}
			}
			--- TableColumn ---
				toolTips en = "Last operation on one or more of the client\'s portfolios is longer than 180 days ago", fr = "La dernière opération date d\'il y a plus que 180 jours sur un ou plusieurs des portefeuilles du client ", de = "Die letzte Transaktion auf einem oder mehreren Kundendepots liegt mehr als 180 Tage zurück"
				column-name = extBiDaysOperation !
				column-type = domain !
				domainAttribute = extBiDaysOperation !
				type = text
				column-sortable = false
				id = extBiDaysOperation
				table-column-width = 12
				tid = 203006296426501
			{
				--- TableColumnItem ---
					item-column = extBiDaysOperation
					format = integer
					previewValue = value
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = displayDashboardDetailsClient ud
						Query.fs_E8Q.f2.attribute = extBiCategory ud
						Query.fs_E8Q.f2.Op = EQUAL ud
						Query.fs_E8Q.f2.value1 = "<udp:item column=\"extBiCategory\" />" ud
						Query.fs_E8Q.f2.mode = HIDDEN ud
						only-changed = false
						prevalidate = false
						modal = false
						Query.fs_E8Q.f3.attribute = activeF ud
						Query.fs_E8Q.f3.Op = EQUAL ud
						Query.fs_E8Q.f3.value1 = 1 ud
						Query.fs_E8Q.f3.mode = HIDDEN ud
						Snippet FilterSet
						id = fs_E8Q
						level = 1
						targetDataset = "AAADSThirdParty:ThirdPartyListDashboardDetails"
						{
							Snippet Filter
							attribute = extBiDaysOperation
							filterValue = 1
							operator = EQUAL
						}
					}
				}
			}
			--- TableColumn ---
				toolTips en = "The objectives on one or more of the client\'s portfolios are not compliant", fr = "Les objectifs ne sont pas conformes sur un ou plusieurs portefeuilles du client", de = "Die Zielvereinbarungen sind auf einem oder mehreren Kundendepots nicht konform"
				column-name = extBiObjCompliance !
				column-type = domain !
				domainAttribute = extBiObjCompliance !
				type = text
				column-sortable = false
				id = extBiObjCompliance
				table-column-width = 12
				tid = 273729735442912
			{
				--- TableColumnItem ---
					item-column = extBiObjCompliance
					format = integer
					previewValue = value
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = displayDashboardDetailsClient ud
						Query.fs_E8Q.f2.attribute = extBiCategory ud
						Query.fs_E8Q.f2.Op = EQUAL ud
						Query.fs_E8Q.f2.value1 = "<udp:item column=\"extBiCategory\" />" ud
						Query.fs_E8Q.f2.mode = HIDDEN ud
						only-changed = false
						prevalidate = false
						modal = false
						Query.fs_E8Q.f3.attribute = activeF ud
						Query.fs_E8Q.f3.Op = EQUAL ud
						Query.fs_E8Q.f3.value1 = 1 ud
						Query.fs_E8Q.f3.mode = HIDDEN ud
						Snippet FilterSet
						id = fs_E8Q
						level = 1
						targetDataset = "AAADSThirdParty:ThirdPartyListDashboardDetails"
						{
							Snippet Filter
							attribute = extBiObjCompliance
							filterValue = 1
							operator = EQUAL
						}
					}
				}
			}
			--- TableColumn ---
				toolTips en = "The constraints are not compliant on one or more of the client\'s portfolios", fr = "Les contraintes ne sont pas conformes sur un ou plusieurs portefeuilles du client", de = "Die Einschränkungen sind auf einem oder mehreren Depots des Kunden nicht konform"
				column-name = extBiCstCompliance !
				column-type = domain !
				domainAttribute = extBiCstCompliance !
				type = text
				column-sortable = false
				id = extBiCstCompliance
				table-column-width = 12
				tid = 273811076125876
			{
				--- TableColumnItem ---
					item-column = extBiCstCompliance
					format = integer
					previewValue = value
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = displayDashboardDetailsClient ud
						Query.fs_E8Q.f2.attribute = extBiCategory ud
						Query.fs_E8Q.f2.Op = EQUAL ud
						Query.fs_E8Q.f2.value1 = "<udp:item column=\"extBiCategory\" />" ud
						Query.fs_E8Q.f2.mode = HIDDEN ud
						only-changed = false
						prevalidate = false
						modal = false
						Query.fs_E8Q.f3.attribute = activeF ud
						Query.fs_E8Q.f3.Op = EQUAL ud
						Query.fs_E8Q.f3.value1 = 1 ud
						Query.fs_E8Q.f3.mode = HIDDEN ud
						Snippet FilterSet
						id = fs_E8Q
						level = 1
						targetDataset = "AAADSThirdParty:ThirdPartyListDashboardDetails"
						{
							Snippet Filter
							attribute = extBiCstCompliance
							filterValue = 1
							operator = EQUAL
						}
					}
				}
			}
			--- TableColumn ---
				labels en = "Max. Liquidity - Net Capital Ratio", fr = "Max. ratio liquidité - net capital", de = "Max. Liquidität - Netto Kapital Ratio" toolTips en = "The Liquidity - Net Capital Ratio (Net  Cash Debtor) of one or more of the client\'s portfolios is >30 %", fr = "Le ratio liquidités - capital net (net soldes débiteurs) d\'un ou plusieurs des portefeuilles du client est de > 30 %", de = "Liquidität - Netto Kapital Ratio (Netto Sollsaldo) eines oder mehreren der Kundendepots ist >30 %"
				column-name = extBiCashPercent !
				column-type = domain !
				domainAttribute = extBiCashPercent !
				type = text
				column-sortable = false
				id = extBiCashPercent
				table-column-width = 12
				tid = 274110536354480
			{
				--- TableColumnItem ---
					item-column = extBiCashPercent
					format = integer
					previewValue = value
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = displayDashboardDetailsClient ud
						Query.fs_E8Q.f2.attribute = extBiCategory ud
						Query.fs_E8Q.f2.Op = EQUAL ud
						Query.fs_E8Q.f2.value1 = "<udp:item column=\"extBiCategory\" />" ud
						Query.fs_E8Q.f2.mode = HIDDEN ud
						only-changed = false
						prevalidate = false
						modal = false
						Query.fs_E8Q.f3.attribute = activeF ud
						Query.fs_E8Q.f3.Op = EQUAL ud
						Query.fs_E8Q.f3.value1 = 1 ud
						Query.fs_E8Q.f3.mode = HIDDEN ud
						Snippet FilterSet
						id = fs_E8Q
						level = 1
						targetDataset = "AAADSThirdParty:ThirdPartyListDashboardDetails"
						{
							Snippet Filter
							attribute = extBiCashPercent
							filterValue = 1
							operator = EQUAL
						}
					}
				}
			}
			--- TableColumn ---
				column-name = extBiTotal !
				column-type = domain !
				domainAttribute = extBiTotal !
				type = text
				column-sortable = false
				id = extBiTotal
				table-column-width = 12
			{
				--- TableColumnItem ---
					item-column = extBiTotal
					format = integer
					previewValue = value
			}
			--- TableAggregate ---
				aggregate-column-name = extBiCashPercent
				aggregate-computation = sum
				aggregate-group-names = extBiCategory
			--- TableAggregate ---
				aggregate-column-name = extBiCstCompliance
				aggregate-computation = sum
				aggregate-group-names = extBiCategory
			--- TableAggregate ---
				aggregate-column-name = extBiDaysOperation
				aggregate-computation = sum
				aggregate-group-names = extBiCategory
			--- TableAggregate ---
				aggregate-column-name = extBiDaysProposal
				aggregate-computation = sum
				aggregate-group-names = extBiCategory
			--- TableAggregate ---
				aggregate-column-name = extBiMktValDrop
				aggregate-computation = sum
				aggregate-group-names = extBiCategory
			--- TableAggregate ---
				aggregate-column-name = extBiObjCompliance
				aggregate-computation = sum
				aggregate-group-names = extBiCategory
			--- TableAggregate ---
				aggregate-column-name = extBiTotal
				aggregate-computation = sum
				aggregate-group-names = extBiCategory
			--- TableAggregate ---
				aggregate-column-name = extBiCategory
				aggregate-computation = max
				aggregate-group-names = extBiCategory
		}
	}
}