# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = Details, fr = Détails, de = Details
	domainEntity = "AAADSThirdParty:ThirdPartyListDashboardDetails"
	bean-define = DSBean.AAADSThirdParty.ThirdPartyListDashboardDetails
	bean-name = ThirdPartyListDashboardDetails
	id = ClientDetails_nM_68
	tid = 1748101453354546
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			id = t4Uq_
			table-column-count = 16 !
			table-columns-width = "6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6" !
		{
			--- TableColumn ---
				column-name = name !
				column-type = domain !
				domainAttribute = name !
				type = text
				id = name
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = name
					previewValue = value
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = useSelectedClientFromDashboardInContext ud
						portfolioDimThirdParty.code = "<udp:item column=\"code\" />" ud
						only-changed = false
						prevalidate = false
						modal = false
					}
				}
			}
			--- TableColumn ---
				column-name = code !
				column-type = domain !
				domainAttribute = code !
				type = text
				column-visibility = never-visible
				id = code
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = code
					previewValue = value
			}
			--- TableColumn ---
				labels en = Language, fr = Langue, de = Sprache
				column-name = languageName !
				column-type = domain !
				domainAttribute = languageName !
				type = text
				id = languageName
				table-column-width = 6
				tid = 1829913210846350
			{
				--- TableColumnItem ---
					item-column = languageName
					previewValue = value
			}
			--- TableColumn ---
				labels en = Country, fr = Pays, de = Wohnort
				column-name = residGeoName !
				column-type = domain !
				domainAttribute = residGeoName !
				type = text
				id = residGeoName
				table-column-width = 6
				tid = 1829949098566996
			{
				--- TableColumnItem ---
					item-column = residGeoName
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Market Value", fr = "Valeur de marché", de = Marktwert toolTips en = "Market Value in System Currency", fr = "Valeur de marché exprimée en devise système", de = "Marktwert, in Systemwährung ausgedrückt"
				column-name = extTdMktValM !
				column-type = domain !
				domainAttribute = extTdMktValM !
				type = text
				id = extTdMktValM
				table-column-width = 6
				tid = 1830552063178420
			{
				--- TableColumnItem ---
					item-column = extTdMktValM
					format = decimal
					previewValue = value
			}
			--- TableColumn ---
				labels en = Currency, fr = Devise, de = Währung
				column-name = currencyName !
				column-type = domain !
				domainAttribute = currencyName !
				type = text
				id = currencyName
				table-column-width = 6
				tid = 1829932493931491
			{
				--- TableColumnItem ---
					item-column = currencyName
					previewValue = value
			}
			--- TableColumn ---
				column-name = extChangeMktValP !
				column-type = domain !
				domainAttribute = extChangeMktValP !
				type = text
				id = extChangeMktValP
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = extChangeMktValP
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Market Value", fr = "Valeur de marché", de = Marktwert toolTips en = "Market Value of one or more of the client\'s portfolios has fallen > 2 %", fr = "Valeur de marché d\'un ou plusieurs des portefeuilles du client a chuté > 2 %", de = "Marktwert eines oder mehreren der Kundendepots ist um mehr als 2 % gefallen"
				column-name = BI_MKT_VALUE_DROP
				column-type = placeholder !
				type = text
				column-sortable = false !
				id = L_X_2
				table-column-width = 6
				tid = 274353818599291
			{
				--- Conditional ---
					indexOfSelectedChild = 2
				{
					--- ConditionalBody ---
						javaCode = "\"1\".equals(<udp:item column=\"extBiMktValDrop\"/>)"
						technicalName = VIOL
						boxType = vertical
						isWidgetVisible = false
					{
						--- Icon ---
							toolTips en = "Launch Valuation", fr = "Exécuter la valorisation", de = "Valorisierung starten"
							horizontalAlignment = "${corporatehalign}"
							icon = cross
							id = xsttZ
							tid = 272265802526578
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = launchClientValuationFromDashboard ud
								portfolioDimThirdParty.code = "<udp:item column=\"code\" />" ud
								only-changed = false
								prevalidate = false
								modal = false
							}
						}
					}
					--- ConditionalBody ---
						javaCode = "\"0\".equals(<udp:item column=\"extBiMktValDrop\"/>)"
						technicalName = NOVIOL
						boxType = vertical
						isWidgetVisible = false
					{
						--- Icon ---
							toolTips en = "Launch Valuation", fr = "Exécuter la valorisation", de = "Valorisierung starten"
							horizontalAlignment = "${corporatehalign}"
							icon = tick
							id = UI_a_
							tid = 272313973514510
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = launchClientValuationFromDashboard ud
								portfolioDimThirdParty.code = "<udp:item column=\"code\" />" ud
								only-changed = false
								prevalidate = false
								modal = false
							}
						}
					}
					--- ConditionalBody ---
						javaCode = "<udp:item column=\"extBiMktValDrop\"/> == null"
						technicalName = NULL
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips en = "Launch Valuation", fr = "Exécuter la valorisation", de = "Valorisierung starten"
							horizontalAlignment = "${corporatehalign}"
							icon = information
							id = qjHJ1
							tid = 272339411427709
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = launchClientValuationFromDashboard ud
								portfolioDimThirdParty.code = "<udp:item column=\"code\" />" ud
								only-changed = false
								prevalidate = false
								modal = false
							}
						}
					}
				}
			}
			--- TableColumn ---
				column-name = extCashPercent !
				column-type = domain !
				domainAttribute = extCashPercent !
				type = text
				id = extCashPercent
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = extCashPercent
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Max. Liquidity - Net Capital Ratio ", fr = "Max. Ratio liquidités - capital net ", de = "Max. Liquidität - Netto Kapital Ratio " toolTips en = "The Liquidity - Net Capital Ratio (Net  Cash Debtor) of one or more of the client\'s portfolios is >30 %", fr = "Le ratio liquidités - capital net (net soldes débiteurs) d\'un ou plusieurs des portefeuilles du client est de > 30 %", de = "Liquidität - Netto Kapital Ratio (Netto Sollsaldo) eines oder mehreren der Kundendepots ist >30 %"
				column-name = BI_CASH_PERCENT
				column-type = placeholder !
				type = text
				column-sortable = false !
				id = W7__B
				table-column-width = 6
				tid = 274488451210139
			{
				--- Conditional ---
					indexOfSelectedChild = 2
				{
					--- ConditionalBody ---
						javaCode = "\"1\".equals(<udp:item column=\"extBiCashPercent\"/>)"
						technicalName = VIOL
						boxType = vertical
						isWidgetVisible = false
					{
						--- Icon ---
							toolTips en = "Launch Valuation", fr = "Exécuter la valorisation", de = "Valorisierung starten"
							horizontalAlignment = "${corporatehalign}"
							icon = cross
							id = YD7oX
							tid = 272410487898042
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = launchClientValuationFromDashboard ud
								portfolioDimThirdParty.code = "<udp:item column=\"code\" />" ud
								only-changed = false
								prevalidate = false
								modal = false
							}
						}
					}
					--- ConditionalBody ---
						javaCode = "\"0\".equals(<udp:item column=\"extBiCashPercent\"/>)"
						technicalName = NOVIOL
						boxType = vertical
						isWidgetVisible = false
					{
						--- Icon ---
							toolTips en = "Launch Valuation", fr = "Exécuter la valorisation", de = "Valorisierung starten"
							horizontalAlignment = "${corporatehalign}"
							icon = tick
							id = aOW__
							tid = 272418613829411
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = launchClientValuationFromDashboard ud
								portfolioDimThirdParty.code = "<udp:item column=\"code\" />" ud
								only-changed = false
								prevalidate = false
								modal = false
							}
						}
					}
					--- ConditionalBody ---
						javaCode = "<udp:item column=\"extBiCashPercent\"/> == null"
						technicalName = NULL
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips en = "Launch Valuation", fr = "Exécuter la valorisation", de = "Valorisierung starten"
							horizontalAlignment = "${corporatehalign}"
							icon = information
							id = W_L__
							tid = 272428177434282
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = launchClientValuationFromDashboard ud
								portfolioDimThirdParty.code = "<udp:item column=\"code\" />" ud
								only-changed = false
								prevalidate = false
								modal = false
							}
						}
					}
				}
			}
			--- TableColumn ---
				column-name = extDateOperation !
				column-type = domain !
				domainAttribute = extDateOperation !
				type = text
				id = extDateOperation
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = extDateOperation
					format = date
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Last Operation", fr = "Dernière opération", de = "Letzte Transaktion" toolTips en = "Last operation on one or more of the client\'s portfolios is longer than 180 days ago", fr = "La dernière opération date d\'il y a plus que 180 jours sur un ou plusieurs des portefeuilles du client ", de = "Die letzte Transaktion auf einem oder mehreren Kundendepots liegt mehr als 180 Tage zurück"
				column-name = BI_DAYS_OPERATION
				column-type = placeholder !
				type = text
				column-sortable = false !
				id = cZ__6
				table-column-width = 6
				tid = 274670087876531
			{
				--- Conditional ---
					indexOfSelectedChild = 2
				{
					--- ConditionalBody ---
						javaCode = "\"1\".equals(<udp:item column=\"extBiDaysOperation\"/>)"
						technicalName = VIOL
						boxType = vertical
						isWidgetVisible = false
					{
						--- Icon ---
							toolTips en = "View Client\'s Portfolios Activity", fr = "Voir l\'activité des portefeuilles client", de = "Aktivität der Kundenportfolios anschauen"
							horizontalAlignment = "${corporatehalign}"
							icon = cross
							id = zn0A9
							tid = 273536178768251
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = launchClientActivityFromDashboard ud
								portfolioDimThirdParty.code = "<udp:item column=\"code\" />" ud
								only-changed = false
								prevalidate = false
								modal = false
							}
						}
					}
					--- ConditionalBody ---
						javaCode = "\"0\".equals(<udp:item column=\"extBiDaysOperation\"/>)"
						technicalName = NOVIOL
						boxType = vertical
						isWidgetVisible = false
					{
						--- Icon ---
							toolTips de = "Aktivität der Kundenportfolios anschauen", fr = "Voir l\'activité des portefeuilles client", en = "View Client\'s Portfolios Activity"
							horizontalAlignment = "${corporatehalign}"
							icon = tick
							id = s__3n
							tid = 273605577419476
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = launchClientActivityFromDashboard ud
								portfolioDimThirdParty.code = "<udp:item column=\"code\" />" ud
								only-changed = false
								prevalidate = false
								modal = false
							}
						}
					}
					--- ConditionalBody ---
						javaCode = "<udp:item column=\"extBiDaysOperation\"/> == null"
						technicalName = NULL
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							horizontalAlignment = "${corporatehalign}"
							icon = information
							id = i8_dD
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = launchClientActivityFromDashboard ud
								portfolioDimThirdParty.code = "<udp:item column=\"code\" />" ud
								only-changed = false
								prevalidate = false
								modal = false
							}
						}
					}
				}
			}
			--- TableColumn ---
				labels en = Objectives, fr = Objectifs, de = Zielvereinbarungen toolTips en = "The objectives on one or more of the client\'s portfolios are not compliant", fr = "Les objectifs ne sont pas conformes sur un ou plusieurs portefeuilles du client", de = "Die Zielvereinbarungen sind auf einem oder mehreren Kundendepots nicht konform"
				column-name = BI_OBJ_COMPLIANCE
				column-type = placeholder !
				type = text
				column-sortable = false !
				id = C__9_
				table-column-width = 6
				tid = 274838932117629
			{
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "\"1\".equals(<udp:item column=\"extBiObjCompliance\"/>)"
						technicalName = VIOL
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips en = "Launch Compliance Checking", fr = "Exécuter la vérification de conformité", de = "Prüfung der Befolgung starten"
							horizontalAlignment = "${corporatehalign}"
							icon = cross
							id = izO4c
							tid = 277655629644270
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = launchClientComplianceCheckingFromDashboard ud
								portfolioDimThirdParty.code = "<udp:item column=\"code\" />" ud
								only-changed = false
								prevalidate = false
								modal = false
							}
						}
					}
					--- ConditionalBody ---
						javaCode = "\"0\".equals(<udp:item column=\"extBiObjCompliance\"/>)"
						technicalName = NOVIOL
						boxType = vertical
						isWidgetVisible = false
					{
						--- Icon ---
							toolTips en = "Launch Compliance Checking", fr = "Exécuter la vérification de conformité", de = "Prüfung der Befolgung starten"
							horizontalAlignment = "${corporatehalign}"
							icon = tick
							id = g43q5
							tid = 277701965026560
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = launchClientComplianceCheckingFromDashboard ud
								portfolioDimThirdParty.code = "<udp:item column=\"code\" />" ud
								only-changed = false
								prevalidate = false
								modal = false
							}
						}
					}
					--- ConditionalBody ---
						javaCode = "<udp:item column=\"extBiObjCompliance\"/> == null"
						technicalName = NULL
						boxType = vertical
						isWidgetVisible = false
					{
						--- Icon ---
							toolTips en = "Launch Compliance Checking", fr = "Exécuter la vérification de conformité", de = "Prüfung der Befolgung starten"
							horizontalAlignment = "${corporatehalign}"
							icon = information
							id = u_8_l
							tid = 277706042793707
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = launchClientComplianceCheckingFromDashboard ud
								portfolioDimThirdParty.code = "<udp:item column=\"code\" />" ud
								only-changed = false
								prevalidate = false
								modal = false
							}
						}
					}
				}
			}
			--- TableColumn ---
				labels en = Constraints, fr = Contraintes, de = Einschränkungen toolTips en = "The constraints are not compliant on one or more of the client\'s portfolios", fr = "Les contraintes ne sont pas conformes sur un ou plusieurs portefeuilles du client", de = "Die Einschränkungen sind auf einem oder mehreren Depots des Kunden nicht konform"
				column-name = BI_CST_COMPLIANCE
				column-type = placeholder !
				type = text
				column-sortable = false !
				id = wK723
				table-column-width = 6
				tid = 274998716432675
			{
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "\"1\".equals(<udp:item column=\"extBiCstCompliance\"/>)"
						technicalName = VIOL
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips en = "Launch Compliance Checking", fr = "Exécuter la vérification de conformité", de = "Prüfung der Befolgung starten"
							horizontalAlignment = "${corporatehalign}"
							icon = cross
							id = h98_7
							tid = 277825683674042
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = launchClientComplianceCheckingFromDashboard ud
								portfolioDimThirdParty.code = "<udp:item column=\"code\" />" ud
								only-changed = false
								prevalidate = false
								modal = false
							}
						}
					}
					--- ConditionalBody ---
						javaCode = "\"0\".equals(<udp:item column=\"extBiCstCompliance\"/>)"
						technicalName = NOVIOL
						boxType = vertical
						isWidgetVisible = false
					{
						--- Icon ---
							toolTips en = "Launch Compliance Checking", fr = "Exécuter la vérification de conformité", de = "Prüfung der Befolgung starten"
							horizontalAlignment = "${corporatehalign}"
							icon = tick
							id = W49__
							tid = 277813838911928
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = launchClientComplianceCheckingFromDashboard ud
								portfolioDimThirdParty.code = "<udp:item column=\"code\" />" ud
								only-changed = false
								prevalidate = false
								modal = false
							}
						}
					}
					--- ConditionalBody ---
						javaCode = "<udp:item column=\"extBiCstCompliance\"/> == null"
						technicalName = NULL
						boxType = vertical
						isWidgetVisible = false
					{
						--- Icon ---
							toolTips en = "Launch Compliance Checking", fr = "Exécuter la vérification de conformité", de = "Prüfung der Befolgung starten"
							horizontalAlignment = "${corporatehalign}"
							icon = information
							id = Qw7g3
							tid = 277805400455365
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = launchClientComplianceCheckingFromDashboard ud
								portfolioDimThirdParty.code = "<udp:item column=\"code\" />" ud
								only-changed = false
								prevalidate = false
								modal = false
							}
						}
					}
				}
			}
			--- TableColumn ---
				column-name = extDateProposal !
				column-type = domain !
				domainAttribute = extDateProposal !
				type = text
				id = extDateProposal
				table-column-width = 6
			{
				--- TableColumnItem ---
					item-column = extDateProposal
					format = date
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Last Proposal", fr = "Dernière proposition", de = "Letzter Vorschlag" toolTips en = "Last Proposal is longer than 180 days ago", fr = "La dernière proposition a été soumise depuis plus que 180 jours", de = "Letzter Vorschlag wurde vor mehr als 180 Tagen gemacht"
				column-name = BI_DAYS_PROPOSAL
				column-type = placeholder !
				type = text
				column-sortable = false !
				id = p_7K_
				table-column-width = 6
				tid = 275178438497909
			{
				--- Conditional ---
					indexOfSelectedChild = 2
				{
					--- ConditionalBody ---
						javaCode = "\"1\".equals(<udp:item column=\"extBiDaysProposal\"/>)"
						technicalName = VIOL
						boxType = vertical
						isWidgetVisible = false
					{
						--- Icon ---
							toolTips en = "View Client\'s Portfolios Activity", fr = "Voir l\'activité des portefeuilles client", de = "Aktivität der Kundenportfolios anschauen"
							horizontalAlignment = "${corporatehalign}"
							icon = cross
							id = i_4__
							tid = 273938279717673
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = launchClientActivityFromDashboard ud
								portfolioDimThirdParty.code = "<udp:item column=\"code\" />" ud
								only-changed = false
								prevalidate = false
								modal = false
							}
						}
					}
					--- ConditionalBody ---
						javaCode = "\"0\".equals(<udp:item column=\"extBiDaysProposal\"/>)"
						technicalName = NOVIOL
						boxType = vertical
						isWidgetVisible = false
					{
						--- Icon ---
							toolTips de = "Aktivität der Kundenportfolios anschauen", fr = "Voir l\'activité des portefeuilles client", en = "View Client\'s Portfolios Activity"
							horizontalAlignment = "${corporatehalign}"
							icon = tick
							id = e888q
							tid = 273925028718733
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = launchClientActivityFromDashboard ud
								portfolioDimThirdParty.code = "<udp:item column=\"code\" />" ud
								only-changed = false
								prevalidate = false
								modal = false
							}
						}
					}
					--- ConditionalBody ---
						javaCode = "<udp:item column=\"extBiDaysProposal\"/> == null"
						technicalName = NULL
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							horizontalAlignment = "${corporatehalign}"
							icon = information
							id = b___y
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = launchClientActivityFromDashboard ud
								portfolioDimThirdParty.code = "<udp:item column=\"code\" />" ud
								only-changed = false
								prevalidate = false
								modal = false
							}
						}
					}
				}
			}
			--- TableSort ---
				sort-column-name = name
				sort-rank = 1
			--- TableExtra ---
				domainAttribute = extBiCashPercent
			--- TableExtra ---
				domainAttribute = extBiCstCompliance
			--- TableExtra ---
				domainAttribute = extBiDaysOperation
			--- TableExtra ---
				domainAttribute = extBiDaysProposal
			--- TableExtra ---
				domainAttribute = extBiMktValDrop
			--- TableExtra ---
				domainAttribute = extBiObjCompliance
		}
	}
}