# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = Dashboard, fr = "Tableau de bord", de = Überblick
	containment = container
	id = Dashboard_I__Q_
	tid = 20803820868294
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			id = T5cB_
			indexOfSelectedChild = 1
		{
			--- Tab ---
				labels en = Portfolios, fr = Portefeuilles, de = Portfolios
				id = tab_iX101
				isWidgetVisible = false
				tid = 20785321604002
			{
				--- Box ---
					boxType = vertical
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/dashboard/PortfolioScorecard.module
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/dashboard/PortfolioDetails.module
				}
			}
			--- Tab ---
				labels en = Clients, fr = Clients, de = Kunden
				id = clientTab
				isWidgetSelected = true
				tid = 20785323564587
			{
				Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = selectClientDashboard ud
					only-changed = false
					prevalidate = false
					modal = false
					stabs = clientTab ud
				}
				--- Box ---
					boxType = vertical
				{
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/dashboard/ClientScorecard.module
					--- Include ---
						includeSrc = "" !
						resource:///Default/module/aaa/administration/dashboard/ClientDetails.module
				}
			}
		}
	}
}