# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = Scorecard, fr = "Tableau de bord", de = Cockpit
	domainEntity = "AAADSPortfolio:PortfolioListDashboardSC"
	bean-define = DSBean.AAADSPortfolio.PortfolioListDashboardSC
	bean-name = PortfolioListDashboardSC
	id = DashboardPortfolioList_A_4xr
	tid = 4069301396406
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			table-rendering-mode = summary-delegated
			id = j_j23
			table-column-count = 8 !
			table-columns-width = "12,12,12,12,12,12,12,12" !
		{
			--- TableColumn ---
				labels en = Category, fr = Catégorie, de = Kategorie
				column-display-grouping = true
				column-name = placeholder_A_429
				column-type = placeholder !
				type = text
				column-sortable = false !
				column-width = 50
				id = A_429
				table-column-width = 12
				tid = 433698806950045
			{
				--- TableGroup ---
					aggregateData = false
					group-column-name = serviceTypeE
					group-max = 1
					group-sorting-column-name = serviceTypeE
					group-sorting-direction = ascending
					group-rank = 1
			}
			--- TableColumn ---
				labels fr = "Valeur de marché"
				toolTips en = "Market Value has fallen > 2 %", fr = "Valeur de marché a chuté > 2 %", de = "Marktwert ist um mehr als 2 % gefallen"
				column-name = extBiMktValDrop !
				column-type = domain !
				domainAttribute = extBiMktValDrop !
				type = text
				column-sortable = false
				id = extBiMktValDrop
				table-column-width = 12
				tid = 272387800186336
			{
				--- TableColumnItem ---
					item-column = extBiMktValDrop
					format = integer
					previewValue = value
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = displayDashboardDetailsPtf ud
						only-changed = false
						prevalidate = false
						modal = false
						Query.fs_m8h.f2.attribute = serviceTypeE ud
						Query.fs_m8h.f2.Op = EQUAL ud
						Query.fs_m8h.f2.mode = HIDDEN ud
						Query.fs_m8h.f2.value1 = "<udp:item column=\"serviceTypeE\"/>" ud
						Query.fs_m8h.f3.attribute = activeF ud
						Query.fs_m8h.f3.Op = EQUAL ud
						Query.fs_m8h.f3.mode = HIDDEN ud
						Query.fs_m8h.f3.value1 = 1 ud
						Snippet FilterSet
						id = fs_m8h
						level = 1
						targetDataset = "AAADSPortfolio:PortfolioListDashboardDetails"
						{
							Snippet Filter
							attribute = extBiMktValDrop
							filterValue = 1
							operator = EQUAL
						}
					}
				}
			}
			--- TableColumn ---
				toolTips en = "Return over last year is < 6% (Discretionary) or 12% (Advisory)", fr = "Rendement annuel <  6% (Discretionnaire) ou 12% (Conseil)", de = "Jahresrendite < 6% (Verwaltet) oder 12% (Nicht Verwaltet)"
				column-name = extBiReturn !
				column-type = domain !
				domainAttribute = extBiReturn !
				type = text
				column-sortable = false
				id = extBiReturn
				table-column-width = 12
				tid = 272446212632611
			{
				--- TableColumnItem ---
					item-column = extBiReturn
					format = integer
					previewValue = value
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = displayDashboardDetailsPtf ud
						only-changed = false
						prevalidate = false
						modal = false
						Query.fs_m8h.f10.attribute = serviceTypeE ud
						Query.fs_m8h.f10.Op = EQUAL ud
						Query.fs_m8h.f10.value1 = "<udp:item column=\"serviceTypeE\" />" ud
						Query.fs_m8h.f10.mode = HIDDEN ud
						Query.fs_m8h.f11.attribute = activeF ud
						Query.fs_m8h.f11.Op = EQUAL ud
						Query.fs_m8h.f11.mode = HIDDEN ud
						Query.fs_m8h.f11.value1 = 1 ud
						Snippet FilterSet
						id = fs_m8h
						level = 1
						targetDataset = "AAADSPortfolio:PortfolioListDashboardDetails"
						{
							Snippet Filter
							attribute = extBiReturn
							filterValue = 1
							operator = EQUAL
						}
					}
				}
			}
			--- TableColumn ---
				toolTips en = "Last operation is longer than 180 days ago", fr = "La dernière opération date d\'il y a plus que 180 jours", de = "Die letzte Transaktion liegt mehr als 180 Tage zurück"
				column-name = extBiDaysOperation !
				column-type = domain !
				domainAttribute = extBiDaysOperation !
				type = text
				column-sortable = false
				id = extBiDaysOperation
				table-column-width = 12
				tid = 272482422104206
			{
				--- TableColumnItem ---
					item-column = extBiDaysOperation
					format = integer
					previewValue = value
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = displayDashboardDetailsPtf ud
						only-changed = false
						prevalidate = false
						modal = false
						Query.fs_m8h.f10.attribute = serviceTypeE ud
						Query.fs_m8h.f10.Op = EQUAL ud
						Query.fs_m8h.f10.value1 = "<udp:item column=\"serviceTypeE\" />" ud
						Query.fs_m8h.f10.mode = HIDDEN ud
						Query.fs_m8h.f11.attribute = activeF ud
						Query.fs_m8h.f11.Op = EQUAL ud
						Query.fs_m8h.f11.value1 = 1 ud
						Query.fs_m8h.f11.mode = HIDDEN ud
						Snippet FilterSet
						id = fs_m8h
						level = 1
						targetDataset = "AAADSPortfolio:PortfolioListDashboardDetails"
						{
							Snippet Filter
							attribute = extBiDaysOperation
							filterValue = 1
							operator = EQUAL
						}
					}
				}
			}
			--- TableColumn ---
				toolTips en = "The constraints are not compliant", fr = "Les contraintes ne sont pas conformes", de = "Die Einschränkungen sind nicht konform"
				column-name = extBiCstCompliance !
				column-type = domain !
				domainAttribute = extBiCstCompliance !
				type = text
				column-sortable = false
				id = extBiCstCompliance
				table-column-width = 12
				tid = 272527565610992
			{
				--- TableColumnItem ---
					item-column = extBiCstCompliance
					format = integer
					previewValue = value
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = displayDashboardDetailsPtf ud
						only-changed = false
						prevalidate = false
						modal = false
						Query.fs_m8h.f10.attribute = serviceTypeE ud
						Query.fs_m8h.f10.Op = EQUAL ud
						Query.fs_m8h.f10.value1 = "<udp:item column=\"serviceTypeE\" />" ud
						Query.fs_m8h.f10.Mode = HIDDEN ud
						Query.fs_m8h.f11.attribute = activeF ud
						Query.fs_m8h.f11.Op = EQUAL ud
						Query.fs_m8h.f11.value1 = 1 ud
						Query.fs_m8h.f11.Mode = HIDDEN ud
						Snippet FilterSet
						id = fs_m8h
						level = 1
						targetDataset = "AAADSPortfolio:PortfolioListDashboardDetails"
						{
							Snippet Filter
							attribute = extBiCstCompliance
							filterValue = 1
							operator = EQUAL
						}
					}
				}
			}
			--- TableColumn ---
				toolTips en = "The objectives are not compliant", fr = "Les objectifs ne sont pas conformes", de = "Die Zielvereinbarungen sind nicht konform"
				column-name = extBiObjCompliance !
				column-type = domain !
				domainAttribute = extBiObjCompliance !
				type = text
				column-sortable = false
				id = extBiObjCompliance
				table-column-width = 12
				tid = 272560426455597
			{
				--- TableColumnItem ---
					item-column = extBiObjCompliance
					format = integer
					previewValue = value
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = displayDashboardDetailsPtf ud
						only-changed = false
						prevalidate = false
						modal = false
						Query.fs_m8h.f10.attribute = serviceTypeE ud
						Query.fs_m8h.f10.Op = EQUAL ud
						Query.fs_m8h.f10.value1 = "<udp:item column=\"serviceTypeE\" />" ud
						Query.fs_m8h.f10.mode = HIDDEN ud
						Query.fs_m8h.f11.attribute = activeF ud
						Query.fs_m8h.f11.Op = EQUAL ud
						Query.fs_m8h.f11.value1 = 1 ud
						Query.fs_m8h.f11.mode = HIDDEN ud
						Snippet FilterSet
						id = fs_m8h
						level = 1
						targetDataset = "AAADSPortfolio:PortfolioListDashboardDetails"
						{
							Snippet Filter
							attribute = extBiObjCompliance
							filterValue = 1
							operator = EQUAL
						}
					}
				}
			}
			--- TableColumn ---
				labels de = "Liquidität - Netto Kapital Ratio", fr = "Ratio liquidités - capital net", en = "Liquidity - Net Capital Ratio" toolTips en = "Liquidity - Net Capital Ratio (Net  Cash Debtor) is > 30 %", fr = "Ratio liquidités - capital net (net soldes débiteurs) est de > 30 %", de = "Liquidität - Netto Kapital Ratio (Netto Sollsaldo) ist > 30 %"
				column-name = extBiCashPercent !
				column-type = domain !
				domainAttribute = extBiCashPercent !
				type = text
				column-sortable = false
				id = extBiCashPercent
				table-column-width = 12
				tid = 272598849541771
			{
				--- TableColumnItem ---
					item-column = extBiCashPercent
					format = integer
					previewValue = value
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = displayDashboardDetailsPtf ud
						only-changed = false
						prevalidate = false
						modal = false
						Query.fs_m8h.f10.attribute = serviceTypeE ud
						Query.fs_m8h.f10.Op = EQUAL ud
						Query.fs_m8h.f10.value1 = "<udp:item column=\"serviceTypeE\" />" ud
						Query.fs_m8h.f10.mode = HIDDEN ud
						Query.fs_m8h.f11.attribute = activeF ud
						Query.fs_m8h.f11.Op = EQUAL ud
						Query.fs_m8h.f11.value1 = 1 ud
						Query.fs_m8h.f11.mode = HIDDEN ud
						Snippet FilterSet
						id = fs_m8h
						level = 1
						targetDataset = "AAADSPortfolio:PortfolioListDashboardDetails"
						{
							Snippet Filter
							attribute = extBiCashPercent
							filterValue = 1
							operator = EQUAL
						}
					}
				}
			}
			--- TableColumn ---
				toolTips en = "Total number of records for this business category violating a business indicator", fr = "Nombre total d\'enregistrements pour cette catégorie violant un indicateur métier", de = "Gesamtzahl der Depots, welche für diese Kategorie Indikatoren verletzen"
				column-name = extBiTotal !
				column-type = domain !
				domainAttribute = extBiTotal !
				type = text
				column-sortable = false
				id = extBiTotal
				table-column-width = 12
				tid = 272669217214199
			{
				--- TableColumnItem ---
					item-column = extBiTotal
					format = integer
					previewValue = value
			}
			--- TableAggregate ---
				aggregate-column-name = extBiCstCompliance
				aggregate-computation = sum
				aggregate-group-names = serviceTypeE
			--- TableAggregate ---
				aggregate-column-name = extBiReturn
				aggregate-computation = sum
				aggregate-group-names = serviceTypeE
			--- TableAggregate ---
				aggregate-column-name = extBiObjCompliance
				aggregate-computation = sum
				aggregate-group-names = serviceTypeE
			--- TableAggregate ---
				aggregate-column-name = extBiMktValDrop
				aggregate-computation = sum
				aggregate-group-names = serviceTypeE
			--- TableAggregate ---
				aggregate-column-name = extBiDaysOperation
				aggregate-computation = sum
				aggregate-group-names = serviceTypeE
			--- TableAggregate ---
				aggregate-column-name = extBiCashPercent
				aggregate-computation = sum
				aggregate-group-names = serviceTypeE
			--- TableAggregate ---
				aggregate-column-name = extBiTotal
				aggregate-computation = sum
				aggregate-group-names = serviceTypeE
			--- TableAggregate ---
				aggregate-column-name = serviceTypeE
				aggregate-computation = max
				aggregate-group-names = serviceTypeE
		}
	}
}