# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = Details, fr = Détails, de = Details
	domainEntity = "AAADSPortfolio:PortfolioListDashboardDetails"
	bean-define = DSBean.AAADSPortfolio.PortfolioListDashboardDetails
	bean-name = PortfolioListDashboardDetails
	id = dPortfolioDetails_O5_d4
	tid = 1307446238872817
{
	--- Box ---
		boxType = vertical
	{
		--- Box ---
		{
			--- Button ---
				labels en = "Use in Context", fr = "Utiliser dans le contexte", de = "Benutzen im Kontext"
				id = btn_R___3
				tid = 1307446240758532
			{
				Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = useInContext ud
					modal = false
					only-changed = false
					prevalidate = false
					queryPortfolioLabel = Search ud
				}
			}
			--- Glue ---
		}
		--- TableTree ---
			table-select-all = true
			id = Tz8_0
			table-column-count = 17 !
			table-columns-width = "5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5" !
		{
			--- TableColumn ---
				column-name = SELECT
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				id = SELECT
				table-column-width = 5
			{
				--- CheckBox ---
					column-checkbox-identifier = id
					horizontalTextPosition = trail
					id = btn_tR_l9
			}
			--- TableColumn ---
				column-name = id !
				column-type = domain !
				domainAttribute = id !
				type = text
				column-visibility = never-visible
				id = id
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = id
					format = integer
					previewValue = value
			}
			--- TableColumn ---
				labels de = Code
				column-name = code !
				column-type = domain !
				domainAttribute = code !
				type = text
				id = code
				table-column-width = 5
				tid = 24122813459531
			{
				--- TableColumnItem ---
					item-column = code
					previewValue = value
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = useSelectedPtfFromDashboardInContext ud
						portfolioDimPortfolio.code = "<udp:item column=\"code\" />" ud
						only-changed = false
						prevalidate = false
						modal = false
					}
				}
			}
			--- TableColumn ---
				labels de = "Code der Währung"
				column-name = currencyCode !
				column-type = domain !
				domainAttribute = currencyCode !
				type = text
				id = currencyCode
				table-column-width = 5
				tid = 29510468636656
			{
				--- TableColumnItem ---
					item-column = currencyCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = thirdName !
				column-type = domain !
				domainAttribute = thirdName !
				type = text
				id = thirdName
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = thirdName
					previewValue = value
			}
			--- TableColumn ---
				column-name = serviceTypeE !
				column-type = domain !
				domainAttribute = serviceTypeE !
				type = text
				id = serviceTypeE
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = serviceTypeE
					previewValue = value
			}
			--- TableColumn ---
				column-name = extTdMktValPtfCurM !
				column-type = domain !
				domainAttribute = extTdMktValPtfCurM !
				format = decimal
				type = text
				id = extTdMktValPtfCurM
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = extTdMktValPtfCurM
					previewValue = value
			}
			--- TableColumn ---
				column-name = extChangeMktValP !
				column-type = domain !
				domainAttribute = extChangeMktValP !
				type = text
				id = extChangeMktValP
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = extChangeMktValP
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Market Value", fr = "Valeur de marché", de = Marktwert toolTips en = "Market Value has fallen > 2 %", fr = "Valeur de marché a chuté > 2 %", de = "Marktwert ist um mehr als 2 % gefallen"
				column-name = BI_MARKET_VALUE_DROP
				column-type = placeholder !
				type = text
				column-sortable = false !
				id = h2L_r
				table-column-width = 5
				tid = 259459002918247
			{
				--- Conditional ---
					indexOfSelectedChild = 2
				{
					--- ConditionalBody ---
						javaCode = "\"1\".equals(<udp:item column=\"extBiMktValDrop\"/>)"
						technicalName = VIOL
						boxType = vertical
						isWidgetVisible = false
					{
						--- Icon ---
							toolTips en = "Launch Valuation", fr = "Exécuter la valorisation", de = "Valorisierung starten"
							horizontalAlignment = "${corporatehalign}"
							icon = cross
							id = AZIq_
							tid = 193561543323243
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = launchPtfValuationFromDashboard ud
								portfolioDimPortfolio.code = "<udp:item column=\"code\" />" ud
								only-changed = false
								prevalidate = false
								modal = false
							}
						}
					}
					--- ConditionalBody ---
						javaCode = "\"0\".equals(<udp:item column=\"extBiMktValDrop\"/>)"
						technicalName = NOVIOL
						boxType = vertical
						isWidgetVisible = false
					{
						--- Icon ---
							toolTips en = "Launch Valuation", fr = "Exécuter la valorisation", de = "Valorisierung starten"
							horizontalAlignment = "${corporatehalign}"
							icon = tick
							id = UMi_3
							tid = 193652301711809
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = launchPtfValuationFromDashboard ud
								portfolioDimPortfolio.code = "<udp:item column=\"code\" />" ud
								only-changed = false
								prevalidate = false
								modal = false
							}
						}
					}
					--- ConditionalBody ---
						javaCode = "<udp:item column=\"extBiMktValDrop\"/> == null"
						technicalName = NULL
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips en = "Launch valuation", fr = "Exécuter la valorisation", de = "Valorisierung starten"
							horizontalAlignment = "${corporatehalign}"
							icon = help
							id = b495E
							tid = 193690676654993
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = launchPtfValuationFromDashboard ud
								portfolioDimPortfolio.code = "<udp:item column=\"code\" />" ud
								only-changed = false
								prevalidate = false
								modal = false
							}
						}
					}
				}
			}
			--- TableColumn ---
				labels en = "Liquidity - Net Capital Ratio "
				column-name = extCashPercent !
				column-type = domain !
				domainAttribute = extCashPercent !
				type = text
				id = extCashPercent
				table-column-width = 5
				tid = 424803228206004
			{
				--- TableColumnItem ---
					item-column = extCashPercent
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				labels fr = "Liquidité - net capital ratio", de = "Liquidität - Netto Kapital Ratio", en = "Liquidity - Net Capital Ratio" toolTips en = "Liquidity - Net Capital Ratio (Net  Cash Debtor) is > 30 %", fr = "Le ratio liquidités - capital net (net soldes débiteurs) est de > 30 %", de = "Liquidität - Netto Kapital Ratio (Netto Sollsaldo) ist > 30 %"
				column-name = BI_CASH_PERCENT
				column-type = placeholder !
				type = text
				column-sortable = false !
				id = i_2__
				table-column-width = 5
				tid = 260370668395005
			{
				--- Conditional ---
					indexOfSelectedChild = 1
				{
					--- ConditionalBody ---
						javaCode = "\"1\".equals(<udp:item column=\"extBiCashPercent\"/>)"
						technicalName = VIOL
						boxType = vertical
						isWidgetVisible = false
					{
						--- Icon ---
							toolTips en = "Launch Valuation", fr = "Exécuter la valorisation", de = "Valorisierung starten"
							horizontalAlignment = "${corporatehalign}"
							icon = cross
							id = vUd_l
							tid = 193757973927412
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = launchPtfValuationFromDashboard ud
								portfolioDimPortfolio.code = "<udp:item column=\"code\" />" ud
								only-changed = false
								prevalidate = false
								modal = false
							}
						}
					}
					--- ConditionalBody ---
						javaCode = "\"0\".equals(<udp:item column=\"extBiCashPercent\"/>)"
						technicalName = NOVIOL
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips en = "Launch Valuation", fr = "Exécuter la valorisation", de = "Valorisierung starten"
							horizontalAlignment = "${corporatehalign}"
							icon = tick
							id = Z__j_
							tid = 193743113635950
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = launchPtfValuationFromDashboard ud
								portfolioDimPortfolio.code = "<udp:item column=\"code\" />" ud
								only-changed = false
								prevalidate = false
								modal = false
							}
						}
					}
					--- ConditionalBody ---
						javaCode = "<udp:item column=\"extBiCashPercent\"/> == null"
						technicalName = NULL
						boxType = vertical
						isWidgetVisible = false
					{
						--- Icon ---
							toolTips en = "Launch valuation", fr = "Exécuter la valorisation", de = "Valorisierung starten"
							horizontalAlignment = "${corporatehalign}"
							icon = help
							id = h_e__
							tid = 193730128280829
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = launchPtfValuationFromDashboard ud
								portfolioDimPortfolio.code = "<udp:item column=\"code\" />" ud
								only-changed = false
								prevalidate = false
								modal = false
							}
						}
					}
				}
			}
			--- TableColumn ---
				column-name = extDateOperation !
				column-type = domain !
				domainAttribute = extDateOperation !
				type = text
				id = extDateOperation
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = extDateOperation
					format = date
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Last Operation", fr = "Dernière opération", de = "Letzte Transaktion" toolTips en = "Last operation is longer than 180 days ago", fr = "La dernière opération date d\'il y a plus que 180 jours", de = "Die letzte Transaktion liegt mehr als 180 Tage zurück"
				column-name = BI_DAYS_OPERATION
				column-type = placeholder !
				type = text
				column-sortable = false !
				id = mv7_6
				table-column-width = 5
				tid = 260470831436397
			{
				--- Conditional ---
					indexOfSelectedChild = 1
				{
					--- ConditionalBody ---
						javaCode = "\"1\".equals(<udp:item column=\"extBiDaysOperation\"/>)"
						technicalName = VIOL
						boxType = vertical
						isWidgetVisible = false
					{
						--- Icon ---
							toolTips en = "View Portfolio Activity", fr = "Voir l\'activité du portefeuille", de = "Aktivität des Portfolios anschauen"
							horizontalAlignment = "${corporatehalign}"
							icon = cross
							id = k_VMi
							tid = 196318320370326
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = launchPtfActivityFromDashboard ud
								portfolioDimPortfolio.code = "<udp:item column=\"code\" />" ud
								only-changed = false
								prevalidate = false
								modal = false
							}
						}
					}
					--- ConditionalBody ---
						javaCode = "\"0\".equals(<udp:item column=\"extBiDaysOperation\"/>)"
						technicalName = NOVIOL
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips en = "View Portfolio Activity", fr = "Voir l\'activité du portefeuille", de = "Aktivität des Portfolios anschauen"
							horizontalAlignment = "${corporatehalign}"
							icon = tick
							id = O_L_w
							tid = 196737729078695
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = launchPtfActivityFromDashboard ud
								portfolioDimPortfolio.code = "<udp:item column=\"code\" />" ud
								only-changed = false
								prevalidate = false
								modal = false
							}
						}
					}
					--- ConditionalBody ---
						javaCode = "<udp:item column=\"extBiDaysOperation\"/> == null"
						technicalName = NULL
						boxType = vertical
						isWidgetVisible = false
					{
						--- Icon ---
							toolTips en = "View Portfolio Activity", fr = "Voir l\'activité du portefeuille", de = "Aktivität des Portfolios anschauen"
							horizontalAlignment = "${corporatehalign}"
							icon = help
							id = xvk_O
							tid = 196771870051361
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = launchPtfActivityFromDashboard ud
								portfolioDimPortfolio.code = "<udp:item column=\"code\" />" ud
								only-changed = false
								prevalidate = false
								modal = false
							}
						}
					}
				}
			}
			--- TableColumn ---
				labels en = Objectives, fr = Objectifs, de = Zielvereinbarungen toolTips en = "The objectives are not compliant", fr = "Les objectifs ne sont pas conformes", de = "Die Zielvereinbarungen sind nicht konform"
				column-name = BI_OBJ_COMPLIANCE
				column-type = placeholder !
				type = text
				column-sortable = false !
				id = K_4C9
				table-column-width = 5
				tid = 260823019255799
			{
				--- Conditional ---
					indexOfSelectedChild = 2
				{
					--- ConditionalBody ---
						javaCode = "\"1\".equals(<udp:item column=\"extBiObjCompliance\"/>)"
						technicalName = VIOL
						boxType = vertical
						isWidgetVisible = false
					{
						--- Icon ---
							toolTips en = "Launch Compliance Checking", fr = "Exécuter la vérification de conformité", de = "Prüfung der Befolgung starten"
							horizontalAlignment = "${corporatehalign}"
							icon = cross
							id = C___3
							tid = 196821947724361
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = launchPtfCompCheckingFromDashboard ud
								portfolioDimPortfolio.code = "<udp:item column=\"code\" />" ud
								only-changed = false
								prevalidate = false
								modal = false
							}
						}
					}
					--- ConditionalBody ---
						javaCode = "\"0\".equals(<udp:item column=\"extBiObjCompliance\"/>)"
						technicalName = NOVIOL
						boxType = vertical
						isWidgetVisible = false
					{
						--- Icon ---
							toolTips en = "Launch Compliance Checking", fr = "Exécuter la vérification de conformité", de = "Prüfung der Befolgung starten"
							horizontalAlignment = "${corporatehalign}"
							icon = tick
							id = z____
							tid = 196902089704138
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = launchPtfCompCheckingFromDashboard ud
								portfolioDimPortfolio.code = "<udp:item column=\"code\" />" ud
								only-changed = false
								prevalidate = false
								modal = false
							}
						}
					}
					--- ConditionalBody ---
						javaCode = "<udp:item column=\"extBiObjCompliance\"/> == null"
						technicalName = NULL
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips en = "Launch Compliance Checking", fr = "Exécuter la vérification de conformité", de = "Prüfung der Befolgung starten"
							horizontalAlignment = "${corporatehalign}"
							icon = help
							id = qW2eR
							tid = 196956199141511
					}
				}
			}
			--- TableColumn ---
				labels en = Constraints, fr = Contraintes, de = Einschränkungen toolTips en = "The constraints are not compliant", fr = "Les contraintes ne sont pas conformes", de = "Die Einschränkungen sind nicht konform"
				column-name = BI_CST_COMPLIANCE
				column-type = placeholder !
				type = text
				column-sortable = false !
				id = M__8L
				table-column-width = 5
				tid = 261476561864706
			{
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "\"1\".equals(<udp:item column=\"extBiCstCompliance\"/>)"
						technicalName = VIOL
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips en = "Launch Compliance Checking", fr = "Exécuter la vérification de conformité", de = "Prüfung der Befolgung starten"
							horizontalAlignment = "${corporatehalign}"
							icon = cross
							id = g3q8T
							tid = 196863633862683
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = launchPtfCompCheckingFromDashboard ud
								portfolioDimPortfolio.code = "<udp:item column=\"code\" />" ud
								only-changed = false
								prevalidate = false
								modal = false
							}
						}
					}
					--- ConditionalBody ---
						javaCode = "\"0\".equals(<udp:item column=\"extBiCstCompliance\"/>)"
						technicalName = NOVIOL
						boxType = vertical
						isWidgetVisible = false
					{
						--- Icon ---
							toolTips en = "Launch Compliance Checking", fr = "Exécuter la vérification de conformité", de = "Prüfung der Befolgung starten"
							horizontalAlignment = "${corporatehalign}"
							icon = tick
							id = ea03_
							tid = 197002651415193
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = launchPtfCompCheckingFromDashboard ud
								portfolioDimPortfolio.code = "<udp:item column=\"code\" />" ud
								only-changed = false
								prevalidate = false
								modal = false
							}
						}
					}
					--- ConditionalBody ---
						javaCode = "<udp:item column=\"extBiCstCompliance\"/> == null"
						technicalName = NULL
						boxType = vertical
						isWidgetVisible = false
					{
						--- Icon ---
							toolTips en = "Launch Compliance Checking", fr = "Exécuter la vérification de conformité", de = "Prüfung der Befolgung starten"
							horizontalAlignment = "${corporatehalign}"
							icon = help
							id = l_O23
							tid = 196993603547936
					}
				}
			}
			--- TableColumn ---
				column-name = extYtdPtfReturn !
				column-type = domain !
				domainAttribute = extYtdPtfReturn !
				type = text
				id = extYtdPtfReturn
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = extYtdPtfReturn
					format = percentTA
					previewValue = value
			}
			--- TableColumn ---
				labels en = Return, fr = Rendement, de = Rendite toolTips en = "Return over last year is < 6% (Discretionary) or 12% (Advisory)", fr = "Rendement annuel < 6 % (Discretionnaire) ou 12% (", de = "Jahresrendite < 6% (Verwaltet) oder 12% (Nicht Verwaltet)"
				column-name = BI_RETURN
				column-type = placeholder !
				type = text
				column-sortable = false !
				id = b__p_
				table-column-width = 5
				tid = 269013439217274
			{
				--- Conditional ---
					indexOfSelectedChild = 2
				{
					--- ConditionalBody ---
						javaCode = "\"1\".equals(<udp:item column=\"extBiReturn\"/>)"
						technicalName = VIOL
						boxType = vertical
						isWidgetVisible = false
					{
						--- Icon ---
							toolTips en = "Launch Return Calculation", fr = "Exécuter le calcul de rendement", de = "Ertragsberechnung starten"
							horizontalAlignment = "${corporatehalign}"
							icon = cross
							id = t6r__
							tid = 197038997873472
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = launchPtfReturnFromDashboard ud
								portfolioDimPortfolio.code = "<udp:item column=\"code\" />" ud
								only-changed = false
								prevalidate = false
								modal = false
							}
						}
					}
					--- ConditionalBody ---
						javaCode = "\"0\".equals(<udp:item column=\"extBiReturn\"/>)"
						technicalName = NOVIOL
						boxType = vertical
						isWidgetVisible = false
					{
						--- Icon ---
							toolTips en = "Launch Return Calculation", fr = "Exécuter le calcul de rendement", de = "Ertragsberechnung starten"
							horizontalAlignment = "${corporatehalign}"
							icon = tick
							id = Av8__
							tid = 197110513267468
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = launchPtfReturnFromDashboard ud
								portfolioDimPortfolio.code = "<udp:item column=\"code\" />" ud
								only-changed = false
								prevalidate = false
								modal = false
							}
						}
					}
					--- ConditionalBody ---
						javaCode = "<udp:item column=\"extBiReturn\"/> == null"
						technicalName = NULL
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips en = "Launch Return Calculation", fr = "Exécuter le calcul de rendement", de = "Ertragsberechnung starten"
							horizontalAlignment = "${corporatehalign}"
							icon = help
							id = d_v_4
							tid = 197144997623440
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = launchPtfReturnFromDashboard ud
								portfolioDimPortfolio.code = "<udp:item column=\"code\" />" ud
								only-changed = false
								prevalidate = false
								modal = false
							}
						}
					}
				}
			}
			--- TableSort ---
				sort-column-name = code
				sort-rank = 1
			--- TableExtra ---
				domainAttribute = extBiMktValDrop
			--- TableExtra ---
				domainAttribute = extBiCashPercent
			--- TableExtra ---
				domainAttribute = extBiCstCompliance
			--- TableExtra ---
				domainAttribute = extBiObjCompliance
			--- TableExtra ---
				domainAttribute = extBiDaysOperation
			--- TableExtra ---
				domainAttribute = extBiReturn
		}
	}
}