/*
* generated by Xtext
*/
package com.odcgroup.page.validation;
 
import java.util.ArrayList;
import java.util.List;

import org.eclipse.emf.ecore.EPackage;

public class AbstractPageJavaValidator extends com.odcgroup.workbench.dsl.validation.CommonJavaValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.odcgroup.com/page/model"));
		return result;
	}

}
