# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSPspPositionData:PspPositionDataList"
	bean-define = DSBean.AAADSPspPositionData.PspPositionDataList
	bean-name = PspPositionDataList
	id = PspPositionDataList_W____
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			id = b__w3
			table-column-count = 1 !
			table-columns-width = 100 !
		{
			--- TableColumn ---
				column-name = code !
				column-type = domain !
				domainAttribute = code !
				id = code
				table-column-width = 100
			{
				--- TableColumnItem ---
					item-column = code
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = code
				sort-rank = 1
		}
	}
}