# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSDomain:DomainContext"
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = ContextAdvanced_Z99_6
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			id = oF_8A
			indexOfSelectedChild = 1
		{
			--- Tab ---
				id = tab_Dv9_m
				isWidgetVisible = false
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/DomainContextDataLoadingNotEdited.fragment
			}
			--- Tab ---
				id = tab_ue4o_
				isWidgetSelected = true
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/DomainContextComplianceNotEdited.fragment
			}
		}
	}
}