# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSDomain:DomainContext"
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = ContextAdvanced_Z99_6
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			id = oF_8A
			indexOfSelectedChild = 1
		{
			--- Tab ---
				labels en = "Data Loading", de = "Laden der Daten", fr = "Chargement de données"
				id = tab_Dv9_m
				isWidgetVisible = false
				tid = 28166593476545
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/DomainContextDataLoading.fragment
			}
			--- Tab ---
				labels en = Compliance, de = Konformität, fr = Conformité
				id = tab_ue4o_
				isWidgetSelected = true
				tid = 28175464503170
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/DomainContextCompliance.fragment
			}
		}
	}
}