# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Portfolio Details", fr = "Détails du portefeuille", de = "Details des Portfolios"
	domainEntity = "AAADSDomain:DomainContext"
	collapsed = true
	collapsible = true
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = PortfolioCodeDetailHead_I___V
	tid = 585518072261315
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			id = N8Y0D
			indexOfSelectedChild = 0
		{
			--- Tab ---
				labels en = Basic, fr = Base, de = Einfach
				id = tab_P28m6
				isWidgetSelected = true
				tid = 175016166797073
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 3
					gridColumnsWidth = "16,16,16" !
					gridRowCount = 1
					verticalAlignment = lead
				{
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainPortfolioCodeView.fragment
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainInstrumentDimensionView.fragment
					}
					--- GridCell ---
						gridColumnWidth = 16
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainHierarchyIdentifierView.fragment
					}
				}
			}
			--- Tab ---
				labels en = Advanced, fr = Avancé, de = Erweitert
				id = tab_vj57_
				isWidgetVisible = false
				tid = 175053668623699
			{
				--- Grid ---
					cssClass = blank
					gridColumnCount = 6
					gridColumnsWidth = "14,14,14,14,14,14" !
					gridRowCount = 1
				{
					--- GridCell ---
						gridColumnWidth = 14
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainMinStatusView.fragment
					}
					--- GridCell ---
						gridColumnWidth = 14
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainMaxStatusView.fragment
					}
					--- GridCell ---
						gridColumnWidth = 14
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainStatusFusView.fragment
					}
					--- GridCell ---
						gridColumnWidth = 14
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainPosLogicalEView.fragment
					}
					--- GridCell ---
						gridColumnWidth = 14
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainClosePosFView.fragment
					}
					--- GridCell ---
						gridColumnWidth = 14
					{
						--- Include ---
							includeSrc = "" !
							resource:///default/domain/basicelements/DomainDerivationView.fragment
					}
				}
			}
		}
	}
}