# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Alert Recipients"
	domainEntity = "AlertDef:AlertRecipientList"
	bean-define = DSBean.AlertDef.AlertRecipientList
	bean-name = AlertRecipientList
	id = AlertRecipientView_Z_0_1
	tid = 503347885195464
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			id = N_7Gq
			table-column-count = 4 !
			table-columns-width = "25,25,25,25" !
		{
			--- TableColumn ---
				column-name = managerCode !
				column-type = domain !
				domainAttribute = managerCode !
				type = text
				id = managerCode
				table-column-width = 25
			{
				--- TableColumnItem ---
					item-column = managerCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = thirdPartyCode !
				column-type = domain !
				domainAttribute = thirdPartyCode !
				type = text
				id = thirdPartyCode
				table-column-width = 25
			{
				--- TableColumnItem ---
					item-column = thirdPartyCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = listCode !
				column-type = domain !
				domainAttribute = listCode !
				type = text
				id = listCode
				table-column-width = 25
			{
				--- TableColumnItem ---
					item-column = listCode
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Entity List Name"
				column-name = listEntityName !
				column-type = domain !
				domainAttribute = listEntityName !
				type = text
				id = listEntityName
				table-column-width = 25
				tid = 865998248700684
			{
				--- TableColumnItem ---
					item-column = listEntityName
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = managerCode
				sort-rank = 1
		}
	}
}