# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Private Alerts"
	domainEntity = "AlertDef:AlertDefList"
	bean-define = DSBean.AlertDef.AlertDefList
	bean-name = AlertDefList
	id = PrivateAlertsList_w_4n_
	tid = 326552627018901
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			table-filter-layer = true
			id = a0r__
			table-column-count = 8 !
			table-columns-width = "12,12,12,12,12,12,12,12" !
		{
			--- TableColumn ---
				labels en = Modify, fr = Modifier, de = Aktualisieren
				column-name = edit
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				id = X5BDH
				table-column-width = 12
				tid = 332900792123182
			{
				--- Icon ---
					horizontalAlignment = center
					icon = application_form_edit
					id = K___8
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = edit ud
						id = "<udp:item column=\"id\"/>" ud
						only-changed = false
						prevalidate = false
						modal = false
					}
				}
			}
			--- TableColumn ---
				labels en = Delete
				column-name = delete
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				id = Bh8_8
				table-column-width = 12
				tid = 356697729055931
			{
				--- Icon ---
					horizontalAlignment = center
					icon = application_form_delete
					id = k108_
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = layer
						flow-action = delete ud
						id = "<udp:item column=\"id\"/>" ud
						only-changed = false
						prevalidate = false
						modal = false
					}
				}
			}
			--- TableColumn ---
				labels en = View
				column-name = view
				column-type = placeholder !
				type = text
				column-sortable = false !
				column-width = 20
				id = D75_x
				table-column-width = 12
				tid = 275134341350925
			{
				--- Icon ---
					horizontalAlignment = center
					icon = application_form_magnify
					id = T_0_7
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = view ud
						id = "<udp:item column=\"id\"/>" ud
						only-changed = false
						prevalidate = false
						modal = false
					}
				}
			}
			--- TableColumn ---
				labels en = "Run Query"
				column-name = runQuery
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				id = F__2_
				table-column-width = 12
				tid = 333058719522763
			{
				--- Icon ---
					toolTips en = "Run Query"
					horizontalAlignment = center
					icon = resultset_next
					id = s3g_U
					tid = 333195787941280
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = executeQuery ud
						id = "<udp:item column=\"id\"/>" ud
						only-changed = false
						prevalidate = false
						modal = false
					}
				}
			}
			--- TableColumn ---
				column-name = name !
				column-type = domain !
				domainAttribute = name !
				type = text
				column-locked = true
				id = name
				table-column-width = 12
			{
				--- TableColumnItem ---
					item-column = name
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Entity Name"
				column-name = entityDictName !
				column-type = domain !
				domainAttribute = entityDictName !
				type = text
				id = entityDictName
				table-column-width = 12
				tid = 344702951529793
			{
				--- TableColumnItem ---
					item-column = entityDictName
					previewValue = value
			}
			--- TableColumn ---
				column-name = activeE !
				column-type = domain !
				domainAttribute = activeE !
				type = text
				id = activeE
				table-column-width = 12
			{
				--- TableColumnItem ---
					item-column = activeE
					previewValue = value
			}
			--- TableColumn ---
				column-name = lastExecutionD !
				column-type = domain !
				domainAttribute = lastExecutionD !
				format = datetime.date-only
				type = text
				id = lastExecutionD
				table-column-width = 12
			{
				--- TableColumnItem ---
					item-column = lastExecutionD
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = name
				sort-rank = 1
			--- TableExtra ---
				domainAttribute = id
		}
		--- Button ---
			labels en = "Create Alert"
			id = btn_uKW2_
			tid = 238759239711171
		{
			Event OnClick (submit) S
			{
				method = post
				call-URI = "<pageflow:continuation/>"
				target = self
				flow-action = create ud
				only-changed = false
				prevalidate = false
				modal = false
			}
		}
	}
}