# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AlertDef:AlertDefAccess"
	cssClass = nodeco
	bean-define = DSBean.AlertDef.AlertDefAccess
	bean-name = AlertDefAccess
	id = PublicAlertAddButton_k_p2_
{
	--- Box ---
		boxType = vertical
	{
		--- Button ---
			labels en = "Create Alert"
			enabled = conditional
			enabledIsBasedOn = createRightF
			id = btn_q___z
			enabledIsBasedOn-simplified = "AlertDef:AlertDefAccess#createRightF"
			tid = 863674610626490
		{
			Event OnClick (submit) S
			{
				method = post
				call-URI = "<pageflow:continuation/>"
				target = self
				flow-action = create ud
				only-changed = false
				prevalidate = false
				modal = false
			}
		}
	}
}