# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Public Alerts"
	containment = container
	domainEntity = "AlertDef:AlertDefList"
	bean-define = DSBean.AlertDef.AlertDefList
	bean-name = AlertDefList
	id = PublicAlertsList_i39Q_
	tid = 95229941905465
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			table-filter-layer = true
			id = E____
			table-column-count = 11 !
			table-columns-width = "9,9,9,9,9,9,9,9,9,9,9" !
		{
			--- TableColumn ---
				labels en = Modify
				column-name = edit
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				id = jd___
				table-column-width = 9
				tid = 353406482852424
			{
				--- Icon ---
					horizontalAlignment = center
					icon = application_form_edit
					enabled = conditional
					enabledIsBasedOn = updateRightF
					id = U0n46
					enabledIsBasedOn-simplified = "AlertDef:AlertDefList#updateRightF"
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = edit ud
						id = "<udp:item column=\"id\"/>" ud
						only-changed = false
						prevalidate = false
						modal = false
					}
				}
			}
			--- TableColumn ---
				labels en = Delete
				column-name = delete
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				id = Pa1_5
				table-column-width = 9
				tid = 883603988280893
			{
				--- Icon ---
					horizontalAlignment = center
					icon = application_form_delete
					enabled = conditional
					enabledIsBasedOn = deleteRightF
					id = YWyKC
					enabledIsBasedOn-simplified = "AlertDef:AlertDefList#deleteRightF"
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = layer
						flow-action = delete ud
						id = "<udp:item column=\"id\"/>" ud
						only-changed = false
						prevalidate = false
						modal = false
					}
				}
			}
			--- TableColumn ---
				column-name = deleteRightF !
				column-type = domain !
				domainAttribute = deleteRightF !
				type = text
				column-visibility = never-visible
				id = deleteRightF
				table-column-width = 9
			{
				--- TableColumnItem ---
					item-column = deleteRightF
					previewValue = value
			}
			--- TableColumn ---
				column-name = updateRightF !
				column-type = domain !
				domainAttribute = updateRightF !
				type = text
				column-visibility = never-visible
				id = updateRightF
				table-column-width = 9
			{
				--- TableColumnItem ---
					item-column = updateRightF
					previewValue = value
			}
			--- TableColumn ---
				labels en = View
				column-name = view
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				id = w_D_n
				table-column-width = 9
				tid = 883553204183195
			{
				--- Icon ---
					horizontalAlignment = center
					icon = application_form_magnify
					id = U_l7F
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = view ud
						id = "<udp:item column=\"id\"/>" ud
						only-changed = false
						prevalidate = false
						modal = false
					}
				}
			}
			--- TableColumn ---
				labels en = "Run Query"
				column-name = runQuery
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				id = h___3
				table-column-width = 9
				tid = 353406499287387
			{
				--- Icon ---
					toolTips en = "Run Query"
					horizontalAlignment = center
					icon = resultset_next
					id = g_pz9
					tid = 353406500350041
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = executeQuery ud
						id = "<udp:item column=\"id\"/>" ud
						only-changed = false
						prevalidate = false
						modal = false
					}
				}
			}
			--- TableColumn ---
				labels en = Subscribe
				column-name = subscriberIdForCurrentUser !
				column-type = domain !
				domainAttribute = subscriberIdForCurrentUser !
				format = integer
				type = text
				id = subscriberIdForCurrentUser
				table-column-width = 9
				tid = 101513305419264
			{
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "<udp:item column=\"subscriberIdForCurrentUser\"/> != null"
						technicalName = UnSubcribe
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips en = Unsubscribe
							horizontalAlignment = center
							icon = plugin_delete
							id = A66V0
							tid = 101440372104555
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = unsubscribe ud
								id = "<udp:item column=\"subscriberIdForCurrentUser\"/>" ud
								only-changed = false
								prevalidate = false
								modal = false
							}
						}
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Subscribe
						boxType = vertical
						isWidgetVisible = false
					{
						--- Icon ---
							toolTips en = Subscribe
							horizontalAlignment = center
							icon = plugin_add
							id = Q6o43
							tid = 101447315818909
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = subscribe ud
								alertDef.id = "<udp:item column=\"id\"/>" ud
								only-changed = false
								prevalidate = false
								modal = false
							}
						}
					}
				}
			}
			--- TableColumn ---
				column-name = name !
				column-type = domain !
				domainAttribute = name !
				type = text
				column-locked = true
				id = name
				table-column-width = 9
			{
				--- TableColumnItem ---
					item-column = name
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Entity Name"
				column-name = entityDictName !
				column-type = domain !
				domainAttribute = entityDictName !
				type = text
				id = entityDictName
				table-column-width = 9
				tid = 353406498419963
			{
				--- TableColumnItem ---
					item-column = entityDictName
					previewValue = value
			}
			--- TableColumn ---
				column-name = activeE !
				column-type = domain !
				domainAttribute = activeE !
				type = text
				id = activeE
				table-column-width = 9
			{
				--- TableColumnItem ---
					item-column = activeE
					previewValue = value
			}
			--- TableColumn ---
				column-name = lastExecutionD !
				column-type = domain !
				domainAttribute = lastExecutionD !
				format = datetime.date-only
				type = text
				id = lastExecutionD
				table-column-width = 9
			{
				--- TableColumnItem ---
					item-column = lastExecutionD
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = name
				sort-rank = 1
			--- TableExtra ---
				domainAttribute = id
		}
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/alerts/PublicAlertsAddButton.module
	}
}