# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Create Type", de = "Typ erstellen", fr = "Créer un type"
	id = TypeCreate_H___n
	tid = 3855274641888
{
	--- Box ---
		boxType = vertical
	{
		--- Conditional ---
			indexOfSelectedChild = 2
		{
			--- ConditionalBody ---
				javaCode = true
				technicalName = Type
				boxType = vertical
				isWidgetVisible = false
			--- ConditionalBody ---
				javaCode = false
				technicalName = InstrumentType
				boxType = vertical
				isWidgetVisible = false
			--- ConditionalBody ---
				javaCode = false
				technicalName = OperationType
				boxType = vertical
				isWidgetSelected = true
		}
	}
}