<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="uimodel"
    nsURI="http://www.odcgroup.com/page/uimodel" nsPrefix="com.odcgroup.page.uimodel">
  <eClassifiers xsi:type="ecore:EClass" name="UIModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="palette" upperBound="-1"
        eType="#//Palette" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="renderers" eType="#//Renderers"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="paletteGroupItems" upperBound="-1"
        eType="#//PaletteGroupItem" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultPalette" eType="#//Palette"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="menus" eType="#//Menus"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actionGroups" eType="#//ActionGroups"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//Actions" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Palette">
    <eStructuralFeatures xsi:type="ecore:EReference" name="groups" upperBound="-1"
        eType="#//PaletteGroup" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="widgetType" eType="ecore:EClass ../../page-metamodel/model/PageMetaModel.ecore#//WidgetType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertyType" eType="ecore:EClass ../../page-metamodel/model/PageMetaModel.ecore#//PropertyType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="propertyValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PaletteGroup">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1"
        eType="#//PaletteGroupItem"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expanded" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PaletteGroupItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="smallImage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="largeImage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tooltip" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="widgetTemplate" eType="ecore:EClass ../../page-metamodel/model/PageMetaModel.ecore#//WidgetTemplate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Renderers">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rendererInfos" upperBound="-1"
        eType="#//RendererInfo" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RendererInfo">
    <eStructuralFeatures xsi:type="ecore:EReference" name="widgetType" eType="ecore:EClass ../../page-metamodel/model/PageMetaModel.ecore#//WidgetType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="figure" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="editPart" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="designWidgetSpacing" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="8"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="previewWidgetSpacing" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="4"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requestHandler" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="directEditMode" eType="#//EditorMode"
        defaultValueLiteral="None"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" upperBound="-1"
        eType="#//EditPolicyRole" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="directEditManager" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deleteCommand" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dragTracker" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MenuType">
    <eLiterals name="Contextual"/>
    <eLiterals name="Toolbar" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Menus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="menus" upperBound="-1"
        eType="#//WidgetMenu" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WidgetMenu" eSuperTypes="../../page-metamodel/model/PageMetaModel.ecore#//NamedType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//MenuType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="propertyValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//WidgetMenu"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertyType" eType="ecore:EClass ../../page-metamodel/model/PageMetaModel.ecore#//PropertyType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="widgetTypes" upperBound="-1"
        eType="ecore:EClass ../../page-metamodel/model/PageMetaModel.ecore#//WidgetType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="menuItems" upperBound="-1"
        eType="#//MenuItem" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EditorMode">
    <eLiterals name="All"/>
    <eLiterals name="DesignMode" value="1"/>
    <eLiterals name="PreviewMode" value="2"/>
    <eLiterals name="None" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActionGroups">
    <eStructuralFeatures xsi:type="ecore:EReference" name="groups" upperBound="-1"
        eType="#//ActionGroup" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actions">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//Action" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActionGroup" eSuperTypes="../../page-metamodel/model/PageMetaModel.ecore#//NamedType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//Action"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action" eSuperTypes="../../page-metamodel/model/PageMetaModel.ecore#//NamedType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="provider" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" eType="ecore:EClass ../../page-metamodel/model/PageMetaModel.ecore#//PropertyType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mode" eType="#//EditorMode"
        defaultValueLiteral="DesignMode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="propertyValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="templateName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="delegate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="accelerator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertyType" eType="ecore:EClass ../../page-metamodel/model/PageMetaModel.ecore#//PropertyType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EditPolicyRoleType">
    <eLiterals name="DirectEditPolicy" literal="DirectEditPolicy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EditPolicyRole">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mode" eType="#//EditorMode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="role" eType="#//EditPolicyRoleType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="implementationClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MenuItem" eSuperTypes="../../page-metamodel/model/PageMetaModel.ecore#//NamedType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//MenuItem"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="groups" upperBound="-1"
        eType="#//ActionGroup"/>
  </eClassifiers>
</ecore:EPackage>
