# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Intermediate Benchmark Attribution Performance Effect 1 Details", fr = "Détails de l\'effet 1 de l\'attribution de performance (benchmarks intermédiaires)", de = "Mehrstufige Performance Attribution mit Details des Effekts 1"
	containment = container
	id = PerformanceIBPAFocusOnEffect1_g2W6_
	tid = 274259708216726
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			id = u7M_0
			indexOfSelectedChild = 1
		{
			--- Tab ---
				labels en = "By Period", fr = "Par période", de = "Per Periode"
				id = tab_S1yg7
				isWidgetVisible = false
				tid = 274352855749124
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/effectfocus/PerformanceIBPAFocusOnEffect1PerPeriod.module
			}
			--- Tab ---
				labels en = "By Market Segment", fr = "Par segment de marché", de = "Per Marktsegment"
				id = tab_x7h__
				isWidgetSelected = true
				tid = 274372583337028
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/effectfocus/PerformanceIBPAFocusOnEffect1PerMktSeg.module
			}
		}
	}
}