# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Intermediate Benchmark Attribution Performance Effect 5 Details", fr = "Détails de l\'effet 5 de l\'attribution de performance (benchmarks intermédiaires)", de = "Mehrstufige Performance Attribution mit Details des Effekts 5"
	containment = container
	id = PerformanceIBPAFocusOnEffect5_KY290
	tid = 274847466311200
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			id = m3_5_
			indexOfSelectedChild = 0
		{
			--- Tab ---
				labels en = "By Period", fr = "Par période", de = "Per Periode"
				id = tab_V__6_
				isWidgetSelected = true
				tid = 274847468261762
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/effectfocus/PerformanceIBPAFocusOnEffect5PerPeriod.module
			}
			--- Tab ---
				labels en = "By Market Segment", fr = "Par segment de marché", de = "Per Marktsegment"
				id = tab_AD4_9
				isWidgetVisible = false
				tid = 274847470226843
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/effectfocus/PerformanceIBPAFocusOnEffect5PerMktSeg.module
			}
		}
	}
}