# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Intermediate Benchmark Attribution Performance Effect 3 Details", fr = "Détails de l\'effet 3 de l\'attribution de performance (benchmarks intermédiaires)", de = "Mehrstufige Performance Attribution mit Details des Effekts 3"
	containment = container
	id = PerformanceIBPAFocusOnEffect3_eXr77
	tid = 274591729133472
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			id = pU__j
			indexOfSelectedChild = 0
		{
			--- Tab ---
				labels en = "By Period", fr = "Par période", de = "Per Periode"
				id = tab_hpOO_
				isWidgetSelected = true
				tid = 274591750591409
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/effectfocus/PerformanceIBPAFocusOnEffect3PerPeriod.module
			}
			--- Tab ---
				labels en = "By Market Segment", fr = "Par segment de marché", de = "Per Marktsegment"
				id = tab_c_J_s
				isWidgetVisible = false
				tid = 274591752538623
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/effectfocus/PerformanceIBPAFocusOnEffect3PerMktSeg.module
			}
		}
	}
}