# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Intermediate Benchmark Attribution Performance Effect 2 Details", fr = "Détails de l\'effet 2 de l\'attribution de performance (benchmarks intermédiaires)", de = "Mehrstufige Performance Attribution mit Details des Effekts 2"
	containment = container
	id = PerformanceIBPAFocusOnEffect2_xTXIH
	tid = 274449526236663
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			id = G1Y9J
			indexOfSelectedChild = 0
		{
			--- Tab ---
				labels en = "By Period", fr = "Par période", de = "Per Periode"
				id = tab_ud__3
				isWidgetSelected = true
				tid = 274449528138894
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/effectfocus/PerformanceIBPAFocusOnEffect2PerPeriod.module
			}
			--- Tab ---
				labels en = "By Market Segment", fr = "Par segment de marché", de = "Per Marktsegment"
				id = tab_J_G__
				isWidgetVisible = false
				tid = 274449529944552
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/effectfocus/PerformanceIBPAFocusOnEffect2PerMktSeg.module
			}
		}
	}
}