# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Intermediate Benchmark Attribution Performance Effect 4 Details", fr = "Détails de l\'effet 4 de l\'attribution de performance (benchmarks intermédiaires)", de = "Mehrstufige Performance Attribution mit Details des Effekts 4"
	containment = container
	id = PerformanceIBPAFocusOnEffect4_s_3_K
	tid = 274805411154248
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			id = TsZ_m
			indexOfSelectedChild = 0
		{
			--- Tab ---
				labels en = "By Period", fr = "Par période", de = "Per Periode"
				id = tab_o_v0W
				isWidgetSelected = true
				tid = 274805413083805
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/effectfocus/PerformanceIBPAFocusOnEffect4PerPeriod.module
			}
			--- Tab ---
				labels en = "By Market Segment", fr = "Par segment de marché", de = "Per Marktsegment"
				id = tab_hf_v1
				isWidgetVisible = false
				tid = 274805415036288
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/effectfocus/PerformanceIBPAFocusOnEffect4PerMktSeg.module
			}
		}
	}
}