# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "User Search Criteria", fr = "Critères de recherche sur utilisateur", de = "Benutzer Suchbegriffe"
	containment = container
	domainEntity = "AAADSApplUser:ApplUserSearchCriteria"
	search = input !
	bean-define = DSBean.AAADSApplUser.ApplUserSearchCriteria
	bean-name = ApplUserSearchCriteria
	id = ApplUserSearchInput_gsV_w
	tid = 4819805406255
{
	--- Box ---
		boxType = vertical
	{
		--- FilterCriteria ---
			includedFile = "resource:/com/module/search/QueryBuilder.xsp"
		--- Include ---
			includeSrc = "" !
			resource:///default/search/NavigationSearchWithoutQueries.fragment
	}
}