# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Search User", fr = "Recherche d\'utilisateur", de = "Benutzer Suche"
	containment = container
	search = container !
	cssClass = nodeco
	id = ApplUserSearch_RIq_z
	tid = 4993242104384
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/appluser/search/ApplUserSearchInput.module
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/appluser/search/ApplUserList.module
	}
}