# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Search Results", fr = "Résultats de la recherche", de = Suchergebnisse
	domainEntity = "AAADSDataProfile:DataProfileList"
	search = output !
	bean-define = DSBean.AAADSDataProfile.DataProfileList
	bean-name = DataProfileList
	id = DataProfileList_r_j97
	tid = 367148613060949
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			id = E____
			table-column-count = 1 !
			table-columns-width = 100 !
		{
			--- TableColumn ---
				labels de = Code
				column-name = code !
				column-type = domain !
				domainAttribute = code !
				column-locked = true
				id = code
				table-column-width = 100
				tid = 19755313194554
			{
				--- Conditional ---
					indexOfSelectedChild = 1
				{
					--- ConditionalBody ---
						javaCode = "com.odcgroup.tsl.wui.search.form.SearchFormHelper.isLookup(objectModel) == false"
						technicalName = NotLookup
						boxType = vertical
						isWidgetVisible = false
					{
						--- TableColumnItem ---
							toolTips en = "Select Business Unit", fr = "Sélectionner l\'unité business", de = "Geschäftseinheit auswählen"
							item-column = code
							previewValue = value
							tid = 366733839157227
						{
							Event OnClick (submit) S
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = select ud
								Query.beanValue1 = "<udp:item column=\"code\"/>" ud
								modal = false
								only-changed = false
								prevalidate = false
							}
						}
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Default
						boxType = vertical
						isWidgetSelected = true
					{
						--- TableColumnItem ---
							toolTips en = "Select Business Unit", fr = "Sélectionner l\'unité business", de = "Geschäftseinheit auswählen"
							item-column = code
							previewValue = value
							tid = 366733841108530
						{
							Event OnClick (setWidgetValue)
							{
								widget-group-id = "<xsp:expr>com.odcgroup.tsl.wui.search.form.SearchFormHelper.getParentWidgetValue1Id(objectModel)</xsp:expr>"
								value = "<udp:item column=\"code\"/>"
								target = WUI_main
							}
							Event OnClick (winClose)
							{
								target = self
							}
						}
					}
				}
			}
			--- TableSort ---
				sort-column-name = code
				sort-rank = 1
		}
	}
}