# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Search Business Unit", fr = "Recherche d\'unité business", de = "Geschäftseinheit Suche"
	containment = container
	search = container !
	cssClass = nodeco
	id = DataProfileSearch_W__a_
	tid = 367045728935613
{
	--- Box ---
		boxType = vertical
	{
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/dataprofile/search/DataProfileSearchInput.module
		--- Include ---
			includeSrc = "" !
			resource:///Default/module/aaa/administration/dataprofile/search/DataProfileList.module
	}
}