# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Business Unit Search Criteria", fr = "Critères de recherche sur unité business", de = "Geschäftseinheit Suchbegriffe"
	containment = container
	domainEntity = "AAADSDataProfile:DataProfileSearchCriteria"
	search = input !
	bean-define = DSBean.AAADSDataProfile.DataProfileSearchCriteria
	bean-name = DataProfileSearchCriteria
	id = DataProfileSearchInput_l69_0
	tid = 366892945477276
{
	--- Box ---
		boxType = vertical
	{
		--- FilterCriteria ---
			includedFile = "resource:/com/module/search/QueryBuilder.xsp"
		--- Include ---
			includeSrc = "" !
			resource:///default/search/NavigationSearchWithoutQueries.fragment
	}
}