# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "List Of Allocation Rules", de = "Liste Verteilungs-Regeln", fr = "Liste des règles d\'allocation"
	domainEntity = "AAADSExtStrategyElement:ExtStrategyElementDomainList"
	bean-define = DSTableModel.AAADSExtStrategyElement.ExtStrategyElementDomainList
	bean-name = ExtStrategyElementDomainList
	id = InstrOrderPercentOfPtfList_W97c7
	tid = 1270203569463531
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			id = y243_
			table-column-count = 17 !
			table-columns-width = "5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5" !
		{
			--- TableColumn ---
				column-name = UPDATE
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				column-width = 2%
				id = E0S9_
				table-column-width = 5
			{
				--- Icon ---
					toolTips en = "Update Allocation Rule", de = "Instruktion aktualisieren", fr = "Mettre à jour les instructions"
					horizontalAlignment = center
					icon = application_form_edit
					id = J___9
					tid = 1813630067966272
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = edit-instruction ud
						id = "<udp:item column=\"id\"/>" ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- TableColumn ---
				column-name = DELETE
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				column-width = 2%
				id = b6_ek
				table-column-width = 5
			{
				--- Icon ---
					toolTips en = "Delete Allocation Rule", de = "Instruktion löschen", fr = "Supprimer l\'Instruction"
					horizontalAlignment = center
					icon = application_form_delete
					id = mk_9u
					tid = 1813630068963732
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = delete-instruction ud
						id = "<udp:item column=\"id\"/>" ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- TableColumn ---
				column-name = instrCode !
				column-type = domain !
				domainAttribute = instrCode !
				type = text
				id = instrCode
				table-column-width = 5
			{
				--- Icon ---
					toolTips de = "Details des Instruments ansehen", fr = "Voir les détails de l\'instrument", en = "View Instrument Details"
					icon = application_form_magnify
					id = C_G13
					tid = 1228079965685867
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "resource:///administration/instrument/InstrumentQuickView.pageflow"
						target = popup
						code = "<udp:item column=\"instrCode\"/>" ud
						only-changed = false
						prevalidate = false
						modal = false
					}
				}
				--- Spacer ---
					height = 4
					width = 10
				--- TableColumnItem ---
					item-column = instrCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = opNatE !
				column-type = domain !
				domainAttribute = opNatE !
				type = text
				id = opNatE
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = opNatE
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Weight %", fr = Objectif, de = Zielgewicht
				column-name = objWeightContN !
				column-type = domain !
				domainAttribute = objWeightContN !
				type = text
				id = objWeightContN
				table-column-width = 5
				tid = 1813630071280730
			{
				--- TableColumnItem ---
					item-column = objWeightContN
					format = decimal.detailed
					previewValue = value
			}
			--- TableColumn ---
				column-name = objWeightContMargN !
				column-type = domain !
				domainAttribute = objWeightContMargN !
				format = decimal.detailed
				type = text
				id = objWeightContMargN
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = objWeightContMargN
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Last Quote", fr = "Cours courant", de = "Aktueller Kurs"
				column-name = Last_Quote
				type = amount
				id = n3iJ7
				column-computation = make-amount
				column-computation-parameters = "currentQuoteN,currQuoteCurrCode"
				table-column-width = 5
				tid = 81349248793269
			{
				--- TableColumnItem ---
					item-column = Last_Quote
					previewValue = value
			}
			--- TableColumn ---
				labels fr = "Nature de l\'ordre"
				column-name = actualOrderNatE !
				column-type = domain !
				domainAttribute = actualOrderNatE !
				type = text
				id = actualOrderNatE
				table-column-width = 5
				tid = 1813630071979636
			{
				--- TableColumnItem ---
					item-column = actualOrderNatE
					previewValue = value
			}
			--- TableColumn ---
				labels en = Limit, fr = Limite, de = Limit-Kurs
				column-name = Limit_Quote
				type = amount
				id = A641_
				column-computation = make-amount
				column-computation-parameters = "orderQuoteN,orderQuoteCurrCode"
				table-column-width = 5
				tid = 81361067552094
			{
				--- TableColumnItem ---
					item-column = Limit_Quote
					previewValue = value
			}
			--- TableColumn ---
				labels en = Stop, fr = Stop, de = Stop-Kurs
				column-name = Stop_Quote
				type = amount
				id = d_540
				column-computation = make-amount
				column-computation-parameters = "stopQuoteN,orderQuoteCurrCode"
				table-column-width = 5
				tid = 81409033780752
			{
				--- TableColumnItem ---
					item-column = Stop_Quote
					previewValue = value
			}
			--- TableColumn ---
				labels en = Validity, fr = "Date de validité", de = Limit-Datum
				column-name = orderLimitD !
				column-type = domain !
				domainAttribute = orderLimitD !
				type = text
				id = orderLimitD
				table-column-width = 5
				tid = 1813630074960467
			{
				--- TableColumnItem ---
					item-column = orderLimitD
					format = date
					previewValue = value
			}
			--- TableColumn ---
				column-name = id !
				column-type = domain !
				domainAttribute = id !
				type = text
				column-visibility = never-visible
				id = id
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = id
					format = integer
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Last Quote"
				column-name = currentQuoteN !
				column-type = domain !
				domainAttribute = currentQuoteN !
				format = decimal.detailed
				type = text
				column-visibility = never-visible
				id = currentQuoteN
				table-column-width = 5
				tid = 1813630069968891
			{
				--- TableColumnItem ---
					item-column = currentQuoteN
					previewValue = value
			}
			--- TableColumn ---
				column-name = currQuoteCurrCode !
				column-type = domain !
				domainAttribute = currQuoteCurrCode !
				type = text
				column-visibility = never-visible
				id = currQuoteCurrCode
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = currQuoteCurrCode
					previewValue = value
			}
			--- TableColumn ---
				labels fr = Limite, en = Limit, de = Limit-Kurs
				column-name = orderQuoteN !
				column-type = domain !
				domainAttribute = orderQuoteN !
				type = text
				column-visibility = never-visible
				id = orderQuoteN
				table-column-width = 5
				tid = 1813630073901842
			{
				--- TableColumnItem ---
					item-column = orderQuoteN
					format = decimal.detailed
					previewValue = value
			}
			--- TableColumn ---
				labels en = Stop, de = Stop-Kurs
				column-name = stopQuoteN !
				column-type = domain !
				domainAttribute = stopQuoteN !
				format = decimal.detailed
				type = text
				column-visibility = never-visible
				id = stopQuoteN
				table-column-width = 5
				tid = 1813630073985677
			{
				--- TableColumnItem ---
					item-column = stopQuoteN
					previewValue = value
			}
			--- TableColumn ---
				column-name = orderQuoteCurrCode !
				column-type = domain !
				domainAttribute = orderQuoteCurrCode !
				type = text
				column-visibility = never-visible
				id = orderQuoteCurrCode
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = orderQuoteCurrCode
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = id
				sort-direction = descending
				sort-rank = 1
		}
	}
}