# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels fr = Contexte, en = Context, de = Kontext
	containment = container
	domainEntity = "AAADSDomain:DomainContext"
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = Context_J30_3
	tid = 448894894522911
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TabbedPane ---
			id = FEN_4
			indexOfSelectedChild = 0
		{
			--- Tab ---
				labels en = Basic, fr = Base, de = Einfach
				boxType = vertical
				id = tab_N__9s
				isWidgetSelected = true
				tid = 448894895521226
			{
				Event OnClick (submit)
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					widget-group-ref = form
					target = self
					only-changed = true
					flow-action = reload ud
					prevalidate = false
					modal = false
				}
				--- Grid ---
					cssClass = blank
					gridColumnCount = 3
					gridColumnsWidth = "33,33,33" !
					gridRowCount = 1
				{
					--- GridCell ---
						gridColumnWidth = 33
					{
						--- Box ---
							boxType = vertical
						{
							--- Grid ---
								cssClass = blank
								gridColumnCount = 2
								gridColumnsWidth = "25,25" !
								gridRowCount = 1
							{
								--- GridCell ---
									gridColumnWidth = 25
								{
									--- Include ---
										includeSrc = "" !
										resource:///default/domain/basicelements/DomainReport.fragment
								}
								--- GridCell ---
									gridColumnWidth = 25
							}
						}
					}
					--- GridCell ---
						gridColumnWidth = 33
					--- GridCell ---
						gridColumnWidth = 33
				}
				--- Box ---
					boxType = vertical
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "(<bean:get-property bean=\"DomainContext\" property=\"report.code\"/>)==null"
						technicalName = Empty
						boxType = vertical
						isWidgetSelected = true
					--- ConditionalBody ---
						javaCode = "\"Master_PBR\".equals(<bean:get-property bean=\"DomainContext\" property=\"report.code\"/>)"
						technicalName = PBR
						boxType = vertical
						isWidgetVisible = false
					{
						--- Box ---
							boxType = vertical
						{
							--- Include ---
								includeSrc = "" !
								resource:///Default/module/aaa/reporting/context/FinancialParametersPBR.module
							--- Box ---
								boxType = vertical
							--- Include ---
								includeSrc = "" !
								resource:///Default/module/aaa/reporting/context/ReportOptions.module
							--- Box ---
								boxType = vertical
							--- Include ---
								includeSrc = "" !
								resource:///Default/module/aaa/reporting/context/ReportBlocksPBR.module
						}
					}
					--- ConditionalBody ---
						javaCode = true
						technicalName = Others
						boxType = vertical
						isWidgetVisible = false
					{
						--- Include ---
							includeSrc = "" !
							resource:///Default/module/aaa/reporting/context/FinancialParametersOthers.module
					}
				}
			}
			--- Tab ---
				labels en = Advanced, fr = Avancé, de = Erweitert
				boxType = vertical
				id = tab_E__va
				isWidgetVisible = false
				tid = 448894896525529
			{
				Event OnClick (submit)
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					widget-group-ref = form
					target = self
					only-changed = true
					flow-action = reload ud
					prevalidate = false
					modal = false
				}
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/reporting/context/OutputSetup.module
			}
		}
		--- Box ---
		{
			--- Button ---
				labels fr = "Exécuter et notifier", en = "Run and Notify", de = "Starten und "
				id = btn_tM_M_
				tid = 448894897541381
			{
				Event OnClick (submit) // "Launches the report in a separate pageflow in order to be able to continue working while the report is generating"
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					only-changed = true
					prevalidate = false
					modal = false
					flow-action = execute ud
					widget-group-ref = form
				}
			}
			--- Button ---
				labels en = "Run and Display", fr = "Exécuter et afficher", de = "Starten und Vorschau"
				id = btn_launch_report
				documentation = "Launches the report in a separate pageflow in order to be able to continue working while the report is generating.\r\nA popup with the resulting PDF is opened and the report is not stored in the repository"
				tid = 448990114256616
			{
				Event OnClick (submit)
				{
					method = post
					call-URI = "resource:///reporting/ReportPreviewExecution.pageflow"
					target = popreport
					width = 1200
					height = 850
					only-changed = true
					prevalidate = false
					modal = false
					widget-group-ref = form
				}
			}
			--- Button ---
				labels en = "Default Settings", de = Standardeinstellung, fr = "Valeurs par défaut"
				id = btn_x__58
				tid = 448894898516171
			{
				Event OnClick (submit) S
				{
					method = post
					call-URI = "<pageflow:continuation/>"
					target = self
					flow-action = reload ud
					DSEntityReset = true ud
					function.dict = 6 ud
					modal = false
					only-changed = false
					prevalidate = false
				}
			}
			--- Glue ---
		}
	}
}