# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	containment = container
	domainEntity = "AAADSDomain:DomainContext"
	cssClass = nodeco
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = ContextAdvanced_l9_6_
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			id = B_2Pq
			indexOfSelectedChild = 2
		{
			--- Tab ---
				labels en = "Data Loading", de = "Laden der Daten", fr = "Chargement de données"
				id = tab_A67_6
				isWidgetVisible = false
				tid = 184938780015057
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/DomainContextDataLoading.fragment
			}
			--- Tab ---
				labels en = Compliance, de = Konformität, fr = Conformité
				id = tab_j1_p4
				isWidgetVisible = false
				tid = 184945907223124
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/DomainContextCompliance.fragment
			}
			--- Tab ---
				labels en = Performance, de = Performance, fr = Performance
				id = tab_JO_1R
				isWidgetSelected = true
				tid = 184955390226970
		}
	}
}