# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSDomain:DomainContext"
	cssClass = nodeco
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = DebugOptions_g352S
	documentation = "Debug Options"
{
	--- Box ---
		labels en = "Debug Options", fr = "Options de débogage", de = Debug-Einstellungen
		boxType = vertical
		tid = 181261700921623
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 5
			gridColumnsWidth = "12,12,12,12,52" !
			gridRowCount = 3
		{
			--- GridCell ---
				gridColumnWidth = 12
			{
				--- LabelDomain ---
					domainAttribute = repGlobalTraceF !
					for = repGlobalTraceF
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					required = true
			}
			--- GridCell ---
				gridColumnWidth = 12
			{
				--- CheckBox ---
					domainAttribute = repGlobalTraceF
					displayLabel = false
					horizontalTextPosition = trail
					bean-property = repGlobalTraceF
					id = repGlobalTraceF
			}
			--- GridCell ---
				gridColumnWidth = 12
			{
				--- LabelDomain ---
					domainAttribute = repDeleteDataF !
					for = repDeleteDataF
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					required = true
			}
			--- GridCell ---
				gridColumnWidth = 12
			{
				--- CheckBox ---
					domainAttribute = repDeleteDataF
					displayLabel = false
					horizontalTextPosition = trail
					bean-property = repDeleteDataF
					id = repDeleteDataF
			}
			--- GridCell ---
				gridColumnWidth = 52
			--- GridCell ---
				gridColumnWidth = 12
			{
				--- LabelDomain ---
					domainAttribute = repModuleTraceF !
					for = repModuleTraceF
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					required = true
			}
			--- GridCell ---
				gridColumnWidth = 12
			{
				--- CheckBox ---
					domainAttribute = repModuleTraceF
					displayLabel = false
					horizontalTextPosition = trail
					bean-property = repModuleTraceF
					id = repModuleTraceF
			}
			--- GridCell ---
				gridColumnWidth = 12
			--- GridCell ---
				gridColumnWidth = 12
			--- GridCell ---
				gridColumnWidth = 52
			--- GridCell ---
				gridColumnWidth = 12
			{
				--- LabelDomain ---
					domainAttribute = repStyleTraceF !
					for = repStyleTraceF
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					required = true
			}
			--- GridCell ---
				gridColumnWidth = 12
			{
				--- CheckBox ---
					domainAttribute = repStyleTraceF
					displayLabel = false
					horizontalTextPosition = trail
					bean-property = repStyleTraceF
					id = repStyleTraceF
			}
			--- GridCell ---
				gridColumnWidth = 12
			--- GridCell ---
				gridColumnWidth = 12
			--- GridCell ---
				gridColumnWidth = 52
		}
	}
}