# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSDomain:DomainContext"
	cssClass = nodeco
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = FinancialParametersPBR_Jss6k
	documentation = "Specific Context parameters for the Private Banking Report (PBR)"
{
	--- Box ---
		labels en = "Financial Parameters", fr = "Paramètres financiers", de = Finanz-Parameter
		boxType = vertical
		tid = 177368797439539
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 5
			gridColumnsWidth = "25,15,15,15,30" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainPortfolioDimension.fragment
			}
			--- GridCell ---
				gridColumnWidth = 15
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainHierarchyIdentifier.fragment
			}
			--- GridCell ---
				gridColumnWidth = 15
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainConsolidationIdentifier.fragment
			}
			--- GridCell ---
				gridColumnWidth = 15
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainFundSplit.fragment
			}
			--- GridCell ---
				gridColumnWidth = 30
		}
		--- Grid ---
			cssClass = blank
			gridColumnCount = 5
			gridColumnsWidth = "15,15,20,20,30" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 15
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainFromDate.fragment
			}
			--- GridCell ---
				gridColumnWidth = 15
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainTillDate.fragment
			}
			--- GridCell ---
				gridColumnWidth = 20
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainRefCurrencyReport.fragment
			}
			--- GridCell ---
				gridColumnWidth = 20
			{
				--- Include ---
					includeSrc = "" !
					resource:///default/domain/basicelements/DomainLanguageReport.fragment
			}
			--- GridCell ---
				gridColumnWidth = 30
		}
	}
}