# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSDomain:DomainContext"
	cssClass = nodeco
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = OutputSetup_Kw9Xp
	documentation = "Output options"
{
	--- Box ---
		labels fr = "Configuration de sortie", en = "Output Setup", de = Ausgabe-Konfiguration
		boxType = vertical
		cssClass = nodeco
		tid = 180696663488226
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 3
			gridColumnsWidth = "24,24,52" !
			gridRowCount = 2
		{
			--- GridCell ---
				gridColumnWidth = 24
			{
				--- LabelDomain ---
					labels de = Ausgabe-Dateityp, fr = "Type de fichier de sortie"
					domainAttribute = repFileOutputNatureE !
					for = repFileOutputNatureE
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					required = true
					tid = 15574901403111
			}
			--- GridCell ---
				gridColumnWidth = 24
			{
				--- ComboBox ---
					domainAttribute = repFileOutputNatureE !
					horizontalAlignment = "${corporatehalign}"
					required = true
					bean-property = repFileOutputNatureE
					id = repFileOutputNatureE
			}
			--- GridCell ---
				gridColumnWidth = 52
			--- GridCell ---
				gridColumnWidth = 24
			{
				--- LabelDomain ---
					labels de = Ausgabe-Name, fr = "Nom de sortie"
					domainAttribute = repFileOutputName !
					for = repFileOutputName
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					tid = 15582196413790
			}
			--- GridCell ---
				gridColumnWidth = 24
			{
				--- TextField ---
					domainAttribute = repFileOutputName !
					columns = 60
					horizontalAlignment = "${corporatehalign}"
					type = text
					chars = 60
					bean-property = repFileOutputName
					id = repFileOutputName
			}
			--- GridCell ---
				gridColumnWidth = 52
		}
	}
}