# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSDomain:DomainContext"
	cssClass = nodeco
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = ReportBlocksPBR_j_3AS
	documentation = "Report Blocks Selection for the Private Banking Report (PBR)"
{
	--- Box ---
		labels en = "Report Blocks Selection", fr = "Sélection des sections de rapport", de = "Auswahl Berichts-Abschnitte"
		boxType = vertical
		tid = 171412829577675
	{
		--- Box ---
			labels en = General, fr = Général, de = General
			boxType = vertical
			tid = 94843282518342
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 5
				gridColumnsWidth = "15,15,15,15,40" !
				gridRowCount = 4
			{
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						domainAttribute = repConfigNatureE !
						for = repConfigNatureE
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
				}
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- ComboBox ---
						domainAttribute = repConfigNatureE !
						horizontalAlignment = "${corporatehalign}"
						bean-property = repConfigNatureE
						id = repConfigNatureE
					{
						Event OnChange (submit)
						{
							method = post
							call-URI = "<pageflow:continuation/>"
							widget-group-ref = form
							target = self
							param = "flow-action=reload"
							only-changed = true
							modal = false
							prevalidate = false
						}
					}
				}
				--- GridCell ---
					gridColumnWidth = 15
				--- GridCell ---
					gridColumnWidth = 15
				--- GridCell ---
					gridColumnWidth = 40
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						domainAttribute = repTocE !
						for = repTocE
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
				}
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- CheckBox ---
						domainAttribute = repTocE
						displayLabel = false
						horizontalTextPosition = trail
						bean-property = repTocE
						id = repTocE
				}
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						domainAttribute = repOperationHistoryE !
						for = repOperationHistoryE
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
				}
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- CheckBox ---
						domainAttribute = repOperationHistoryE
						displayLabel = false
						horizontalTextPosition = trail
						bean-property = repOperationHistoryE
						id = repOperationHistoryE
				}
				--- GridCell ---
					gridColumnWidth = 40
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						domainAttribute = repIntroductionE !
						for = repIntroductionE
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
				}
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- CheckBox ---
						domainAttribute = repIntroductionE
						displayLabel = false
						horizontalTextPosition = trail
						bean-property = repIntroductionE
						id = repIntroductionE
				}
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						domainAttribute = repPerformanceE !
						for = repPerformanceE
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
				}
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- ComboBox ---
						domainAttribute = repPerformanceE !
						horizontalAlignment = "${corporatehalign}"
						bean-property = repPerformanceE
						id = repPerformanceE
				}
				--- GridCell ---
					gridColumnWidth = 40
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						domainAttribute = repOverviewE !
						for = repOverviewE
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
				}
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- CheckBox ---
						domainAttribute = repOverviewE
						displayLabel = false
						horizontalTextPosition = trail
						bean-property = repOverviewE
						id = repOverviewE
				}
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						labels de = Konformität, fr = Conformité
						domainAttribute = repComplianceE !
						for = repComplianceE
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
						tid = 26615620359012
				}
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- ComboBox ---
						domainAttribute = repComplianceE !
						horizontalAlignment = "${corporatehalign}"
						bean-property = repComplianceE
						id = repComplianceE
				}
				--- GridCell ---
					gridColumnWidth = 40
			}
		}
		--- Box ---
			labels en = Valuation, fr = Valorisation, de = Bewertung
			boxType = vertical
			tid = 172950355195323
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 6
				gridColumnsWidth = "15,15,15,15,30,10" !
				gridRowCount = 2
			{
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						labels en = "Display Type", fr = "Type d\'affichage", de = Darstellungs-Art
						domainAttribute = repValuationE !
						for = repValuationE
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
						tid = 178539004510382
				}
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- ComboBox ---
						domainAttribute = repValuationE !
						horizontalAlignment = "${corporatehalign}"
						bean-property = repValuationE
						id = repValuationE
					{
						Event OnChange (submit)
						{
							method = post
							call-URI = "<pageflow:continuation/>"
							widget-group-ref = form
							target = self
							param = "flow-action=reload"
							only-changed = true
							modal = false
							prevalidate = false
						}
					}
				}
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						domainAttribute = repStockChartE !
						for = repStockChartE
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
				}
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- CheckBox ---
						domainAttribute = repStockChartE
						displayLabel = false
						horizontalTextPosition = trail
						enabled = conditional
						enabledIsBasedOn = advanced
						bean-property = repStockChartE
						id = repStockChartE
						enabledIsBasedOn-advanced = "conditionVal = (Integer.valueOf(<bean:get-property bean=\"DomainContext\" property=\"repValuationE\"/>.toString()) > 0);"
				}
				--- GridCell ---
					gridColumnWidth = 30
				{
					--- Include ---
						includeSrc = "" !
						resource:///default/domain/basicelements/DomainStockGroupingReport.fragment
				}
				--- GridCell ---
					gridColumnWidth = 10
				--- GridCell ---
					gridColumnWidth = 15
				--- GridCell ---
					gridColumnWidth = 15
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						domainAttribute = repBondChartE !
						for = repBondChartE
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
				}
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- CheckBox ---
						domainAttribute = repBondChartE
						displayLabel = false
						horizontalTextPosition = trail
						enabled = conditional
						enabledIsBasedOn = advanced
						bean-property = repBondChartE
						id = repBondChartE
						enabledIsBasedOn-advanced = "conditionVal = (Integer.valueOf(<bean:get-property bean=\"DomainContext\" property=\"repValuationE\"/>.toString()) > 0);"
				}
				--- GridCell ---
					gridColumnWidth = 30
				{
					--- Include ---
						includeSrc = "" !
						resource:///default/domain/basicelements/DomainFundGroupingReport.fragment
				}
				--- GridCell ---
					gridColumnWidth = 10
			}
		}
		--- Box ---
			labels en = "Cash Flow", fr = "Cash flow", de = Geldfluss
			boxType = vertical
			tid = 178207267922730
		{
			--- Grid ---
				cssClass = blank
				gridColumnCount = 5
				gridColumnsWidth = "15,15,15,15,40" !
				gridRowCount = 2
			{
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						labels en = "Display Type", fr = "Type d\'affichage", de = Darstellungs-Art
						domainAttribute = repCashflowE !
						for = repCashflowE
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
						tid = 178578053269140
				}
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- ComboBox ---
						domainAttribute = repCashflowE !
						horizontalAlignment = "${corporatehalign}"
						bean-property = repCashflowE
						id = repCashflowE
					{
						Event OnChange (submit)
						{
							method = post
							call-URI = "<pageflow:continuation/>"
							widget-group-ref = form
							target = self
							param = "flow-action=reload"
							only-changed = true
							modal = false
							prevalidate = false
						}
					}
				}
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						domainAttribute = repMaturityChartE !
						for = repMaturityChartE
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
				}
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- CheckBox ---
						domainAttribute = repMaturityChartE
						displayLabel = false
						horizontalTextPosition = trail
						enabled = conditional
						enabledIsBasedOn = advanced
						bean-property = repMaturityChartE
						id = repMaturityChartE
						enabledIsBasedOn-advanced = "conditionVal = (Integer.valueOf(<bean:get-property bean=\"DomainContext\" property=\"repCashflowE\"/>.toString()) > 0);"
				}
				--- GridCell ---
					gridColumnWidth = 40
				--- GridCell ---
					gridColumnWidth = 15
				--- GridCell ---
					gridColumnWidth = 15
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- LabelDomain ---
						domainAttribute = repCurrencyChartE !
						for = repCurrencyChartE
						cssClass = grey
						horizontalAlignment = "${corporatehalign}"
						required = true
				}
				--- GridCell ---
					gridColumnWidth = 15
				{
					--- CheckBox ---
						domainAttribute = repCurrencyChartE
						displayLabel = false
						horizontalTextPosition = trail
						enabled = conditional
						enabledIsBasedOn = advanced
						bean-property = repCurrencyChartE
						id = repCurrencyChartE
						enabledIsBasedOn-advanced = "conditionVal = (Integer.valueOf(<bean:get-property bean=\"DomainContext\" property=\"repCashflowE\"/>.toString()) > 0);"
				}
				--- GridCell ---
					gridColumnWidth = 40
			}
		}
	}
}