# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSDomain:DomainContext"
	cssClass = nodeco
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = ReportOptions_D__39
	documentation = "Common Report Options for new reports"
{
	--- Box ---
		labels en = "Report Options", fr = "Options de rapport", de = Berichts-Optionen
		boxType = vertical
		tid = 105652649595220
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 7
			gridColumnsWidth = "15,15,15,15,15,15,10" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 15
			{
				--- LabelDomain ---
					domainAttribute = repColorE !
					for = repColorE
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					required = true
			}
			--- GridCell ---
				gridColumnWidth = 15
			{
				--- CheckBox ---
					domainAttribute = repColorE
					displayLabel = false
					horizontalTextPosition = trail
					bean-property = repColorE
					id = repColorE
			}
			--- GridCell ---
				gridColumnWidth = 15
			{
				--- LabelDomain ---
					domainAttribute = repAnonymousE !
					for = repAnonymousE
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					required = true
			}
			--- GridCell ---
				gridColumnWidth = 15
			{
				--- CheckBox ---
					domainAttribute = repAnonymousE
					displayLabel = false
					horizontalTextPosition = trail
					bean-property = repAnonymousE
					id = repAnonymousE
			}
			--- GridCell ---
				gridColumnWidth = 15
			{
				--- LabelDomain ---
					domainAttribute = repStyleSheetE !
					for = repStyleSheetE
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					required = true
			}
			--- GridCell ---
				gridColumnWidth = 15
			{
				--- ComboBox ---
					domainAttribute = repStyleSheetE !
					horizontalAlignment = "${corporatehalign}"
					bean-property = repStyleSheetE
					id = repStyleSheetE
			}
			--- GridCell ---
				gridColumnWidth = 10
		}
	}
}