# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "View Client", fr = "Voir le client", de = "Kunde ansehen"
	containment = container
	id = ClientView_NK3_1
	tid = 409829207981461
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			id = S__39
			indexOfSelectedChild = 2
		{
			--- Tab ---
				labels en = Details, fr = Détails, de = Details
				id = tab_N_rF8
				isWidgetVisible = false
				tid = 409838683488264
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/thirdparty/simplified/view/ThirdPartyDetailView.module
			}
			--- Tab ---
				labels en = "Cash Accounts", fr = "Comptes de liquidités", de = Konten
				id = tab_J64tk
				isWidgetVisible = false
				tid = 409871508391988
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/valuation/detailedlist/ByCashAccount/CashBalanceClient.module
			}
			--- Tab ---
				labels en = Notepads, de = Notizen, fr = Bloc-notes
				id = tab_Ou9C0
				isWidgetSelected = true
				tid = 409853572386713
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/thirdparty/full/view/ThirdPartyNotepadView.module
			}
		}
	}
}