# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = Client, fr = Client, de = Kunde
	domainEntity = "AAADSThirdParty:ThirdPartyAll"
	collapsible = true
	bean-define = DSBean.AAADSThirdParty.ThirdPartyAll
	bean-name = ThirdPartyAll
	id = ClientBanner_z__61
	tid = 368800965977575
{
	--- Box ---
		boxType = vertical
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 8
			gridColumnsWidth = "12,13,12,13,12,13,12,13" !
			gridRowCount = 2
		{
			--- GridCell ---
				gridColumnWidth = 12
			{
				--- LabelDomain ---
					domainAttribute = code !
					for = code
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					required = true
			}
			--- GridCell ---
				gridColumnWidth = 13
			{
				--- TextField ---
					domainAttribute = code !
					horizontalAlignment = "${corporatehalign}"
					type = text
					chars = 20
					editable = false
					required = true
					bean-property = code
					id = code
			}
			--- GridCell ---
				gridColumnWidth = 12
			{
				--- LabelDomain ---
					domainAttribute = residGeo !
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
			}
			--- GridCell ---
				gridColumnWidth = 13
			{
				--- Include ---
					domainAssociation = residGeo
					includeSrc = "" !
					resource:///default/defaultFragments/GeographicIdentifierView.fragment
					bean-property-prefix = residGeo.
			}
			--- GridCell ---
				gridColumnWidth = 12
			{
				--- LabelDomain ---
					domainAttribute = taxGeo !
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
			}
			--- GridCell ---
				gridColumnWidth = 13
			{
				--- Include ---
					domainAssociation = taxGeo
					includeSrc = "" !
					resource:///default/defaultFragments/GeographicIdentifierView.fragment
					bean-property-prefix = taxGeo.
			}
			--- GridCell ---
				gridColumnWidth = 12
			{
				--- LabelDomain ---
					domainAttribute = riskGeo !
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
			}
			--- GridCell ---
				gridColumnWidth = 13
			{
				--- Include ---
					domainAssociation = riskGeo
					includeSrc = "" !
					resource:///default/defaultFragments/GeographicIdentifierView.fragment
					bean-property-prefix = riskGeo.
			}
			--- GridCell ---
				gridColumnWidth = 12
			{
				--- LabelDomain ---
					domainAttribute = name !
					for = name
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					required = true
			}
			--- GridCell ---
				gridColumnWidth = 13
			{
				--- TextField ---
					domainAttribute = name !
					horizontalAlignment = "${corporatehalign}"
					type = text
					chars = 20
					editable = false
					required = true
					bean-property = name
					id = name
			}
			--- GridCell ---
				gridColumnWidth = 12
			{
				--- LabelDomain ---
					domainAttribute = statusE !
					for = statusE
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					required = true
			}
			--- GridCell ---
				gridColumnWidth = 13
			{
				--- ComboBox ---
					domainAttribute = statusE !
					horizontalAlignment = "${corporatehalign}"
					editable = false
					required = true
					bean-property = statusE
					id = statusE
			}
			--- GridCell ---
				gridColumnWidth = 12
			{
				--- LabelDomain ---
					domainAttribute = currency !
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					required = true
			}
			--- GridCell ---
				gridColumnWidth = 13
			{
				--- Include ---
					domainAssociation = currency
					includeSrc = "" !
					resource:///default/defaultFragments/CurrencyIdentifierView.fragment
					bean-property-prefix = currency.
			}
			--- GridCell ---
				gridColumnWidth = 12
			{
				--- LabelDomain ---
					domainAttribute = language !
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					required = true
			}
			--- GridCell ---
				gridColumnWidth = 13
			{
				--- Include ---
					domainAssociation = language
					includeSrc = "" !
					resource:///default/defaultFragments/DictLanguageIdentifierView.fragment
					bean-property-prefix = language.
			}
		}
	}
}