# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "View Portfolio", fr = "Voir le portefeuille", de = Portfolioübersicht
	containment = container
	id = PortfolioView_F_6_e
	tid = 409789793270373
{
	--- Box ---
		boxType = vertical
	{
		--- TabbedPane ---
			id = U_P__
			indexOfSelectedChild = 2
		{
			--- Tab ---
				labels en = Details, fr = Détails, de = Details
				id = tab_n5M88
				isWidgetVisible = false
				tid = 409903061402776
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/portfolio/simplified/view/PortfolioDetailView.module
			}
			--- Tab ---
				labels en = "Cash Accounts", fr = "Comptes de liquidités", de = Konten
				id = tab_Y__y6
				isWidgetVisible = false
				tid = 409933098807809
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/valuation/detailedlist/ByCashAccount/CashBalancePortfolio.module
			}
			--- Tab ---
				labels en = Notepads, de = Notizen, fr = Bloc-notes
				id = tab_Y_0g_
				isWidgetSelected = true
				tid = 409915682965572
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/portfolio/view/PortfolioNotepadView.module
			}
		}
	}
}