# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = Portfolio, fr = Portefeuille, de = Portfolio
	containment = container
	domainEntity = "AAADSPortfolio:PortfolioAll"
	bean-define = DSBean.AAADSPortfolio.PortfolioAll
	bean-name = PortfolioAll
	id = PortfolioBanner_oo4Iq
	tid = 133753670721558
{
	--- Box ---
		boxType = vertical
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 8
			gridColumnsWidth = "12,13,12,13,12,13,12,13" !
			gridRowCount = 3
		{
			--- GridCell ---
				gridColumnWidth = 12
			{
				--- LabelDomain ---
					labels en = Code, fr = Code, de = Code
					domainAttribute = code !
					for = code
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					required = true
					tid = 362131127120760
			}
			--- GridCell ---
				gridColumnWidth = 13
			{
				--- TextField ---
					domainAttribute = code !
					horizontalAlignment = "${corporatehalign}"
					type = text
					chars = 20
					editable = false
					required = true
					bean-property = code
					id = code
			}
			--- GridCell ---
				gridColumnWidth = 12
			{
				--- LabelDomain ---
					domainAttribute = third !
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
			}
			--- GridCell ---
				gridColumnWidth = 13
			{
				--- Include ---
					domainAssociation = third
					includeSrc = "" !
					resource:///default/defaultFragments/ThirdPartyIdentifierView.fragment
					bean-property-prefix = third.
			}
			--- GridCell ---
				gridColumnWidth = 12
			{
				--- LabelDomain ---
					domainAttribute = type !
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
			}
			--- GridCell ---
				gridColumnWidth = 13
			{
				--- Include ---
					domainAssociation = type
					includeSrc = "" !
					resource:///default/defaultFragments/TypeIdentifierView.fragment
					bean-property-prefix = type.
			}
			--- GridCell ---
				gridColumnWidth = 12
			{
				--- LabelDomain ---
					domainAttribute = currency !
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					required = true
			}
			--- GridCell ---
				gridColumnWidth = 13
			{
				--- Include ---
					domainAssociation = currency
					includeSrc = "" !
					resource:///default/defaultFragments/CurrencyIdentifierView.fragment
					bean-property-prefix = currency.
			}
			--- GridCell ---
				gridColumnWidth = 12
			{
				--- LabelDomain ---
					labels en = Name, fr = Nom, de = Name
					domainAttribute = name !
					for = name
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					required = true
					tid = 362131129104543
			}
			--- GridCell ---
				gridColumnWidth = 13
			{
				--- TextField ---
					domainAttribute = name !
					horizontalAlignment = "${corporatehalign}"
					type = text
					chars = 20
					editable = false
					required = true
					bean-property = name
					id = name
			}
			--- GridCell ---
				gridColumnWidth = 12
			{
				--- LabelDomain ---
					labels en = Advisor, fr = Conseiller, de = Berater
					domainAttribute = commMgr !
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					verticalTextPosition = lead
					required = true
					tid = 362131128104953
			}
			--- GridCell ---
				gridColumnWidth = 13
			{
				--- Include ---
					domainAssociation = commMgr
					includeSrc = "" !
					resource:///default/defaultFragments/ManagerIdentifierView.fragment
					bean-property-prefix = commMgr.
			}
			--- GridCell ---
				gridColumnWidth = 12
			{
				--- LabelDomain ---
					domainAttribute = serviceTypeE !
					for = serviceTypeE
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					required = true
			}
			--- GridCell ---
				gridColumnWidth = 13
			{
				--- ComboBox ---
					domainAttribute = serviceTypeE !
					horizontalAlignment = "${corporatehalign}"
					editable = false
					required = true
					bean-property = serviceTypeE
					id = serviceTypeE
			}
			--- GridCell ---
				gridColumnWidth = 12
			{
				--- LabelDomain ---
					domainAttribute = parentPort !
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
			}
			--- GridCell ---
				gridColumnWidth = 13
			{
				--- Include ---
					domainAssociation = parentPort
					includeSrc = "" !
					resource:///default/defaultFragments/PortfolioIdentifierNameView.fragment
					bean-property-prefix = parentPort.
			}
			--- GridCell ---
				gridColumnWidth = 12
			{
				--- LabelDomain ---
					domainAttribute = statusE !
					for = statusE
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					required = true
			}
			--- GridCell ---
				gridColumnWidth = 13
			{
				--- ComboBox ---
					domainAttribute = statusE !
					horizontalAlignment = "${corporatehalign}"
					editable = false
					required = true
					bean-property = statusE
					id = statusE
			}
			--- GridCell ---
				gridColumnWidth = 12
			{
				--- LabelDomain ---
					labels en = Manager, fr = Gestionnaire, de = Verwalter
					domainAttribute = adminMgr !
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					required = true
					tid = 362131130075903
			}
			--- GridCell ---
				gridColumnWidth = 13
			{
				--- Include ---
					domainAssociation = adminMgr
					includeSrc = "" !
					resource:///default/defaultFragments/ManagerIdentifierView.fragment
					bean-property-prefix = adminMgr.
			}
			--- GridCell ---
				gridColumnWidth = 12
			{
				--- LabelDomain ---
					domainAttribute = managType !
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
			}
			--- GridCell ---
				gridColumnWidth = 13
			{
				--- Include ---
					domainAssociation = managType
					includeSrc = "" !
					resource:///default/defaultFragments/TypeIdentifierView.fragment
					bean-property-prefix = managType.
			}
			--- GridCell ---
				gridColumnWidth = 12
			{
				--- LabelDomain ---
					domainAttribute = activeF !
					for = activeF
					cssClass = grey
					horizontalAlignment = "${corporatehalign}"
					required = true
			}
			--- GridCell ---
				gridColumnWidth = 13
			{
				--- ComboBox ---
					domainAttribute = activeF !
					horizontalAlignment = "${corporatehalign}"
					editable = false
					required = true
					bean-property = activeF
					id = activeF
			}
		}
	}
}