# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSOrderList:OrderListDetailedList"
	cssClass = nodeco
	bean-define = DSBean.AAADSOrderList.OrderListDetailedList
	bean-name = OrderListDetailedList
	id = FxSpotDetailedListSelectable_J_C_7
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			id = d_686
			table-column-count = 19 !
			table-columns-width = "5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5" !
		{
			--- TableColumn ---
				column-name = SELECT
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				id = VX_x_
				table-column-width = 5
			{
				--- CheckBox ---
					column-checkbox-identifier = ORDER_CODE
					horizontalTextPosition = trail
					id = btn_i54CU
			}
			--- TableColumn ---
				column-name = ORDER_CODE !
				column-type = domain !
				domainAttribute = ORDER_CODE !
				type = text
				id = pc_6b
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = ORDER_CODE
					previewValue = value
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = view ud
						code = "<udp:item column=\"ORDER_CODE\"/>" ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- TableColumn ---
				column-name = CREATION_DATE !
				column-type = domain !
				domainAttribute = CREATION_DATE !
				type = text
				id = CREATION_DATE
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = CREATION_DATE
					format = datetime.date-only
					previewValue = value
			}
			--- TableColumn ---
				column-name = ORDER_DATE !
				column-type = domain !
				domainAttribute = ORDER_DATE !
				type = text
				id = Rb74_
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = ORDER_DATE
					format = datetime.date-only
					previewValue = value
			}
			--- TableColumn ---
				column-name = PORTFOLIO_NAME !
				column-type = domain !
				domainAttribute = PORTFOLIO_NAME !
				type = text
				id = i_00_
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = PORTFOLIO_NAME
					previewValue = value
			}
			--- TableColumn ---
				column-name = ORDER_NATURE !
				column-type = domain !
				domainAttribute = ORDER_NATURE !
				type = text
				id = ej_yP
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = ORDER_NATURE
					previewValue = value
			}
			--- TableColumn ---
				column-name = CREDITED_ACCOUNT !
				column-type = domain !
				domainAttribute = CREDITED_ACCOUNT !
				type = text
				id = Rp_44
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = CREDITED_ACCOUNT
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Credited Amount", fr = "Montant crédité", de = Gutschriftsbetrag
				column-name = CREDITED_AMT
				type = amount
				id = c_361
				column-computation = make-amount
				column-computation-parameters = "CREDITED_AMOUNT,CREDITED_CURR"
				table-column-width = 5
				tid = 110313611642512
			{
				--- TableColumnItem ---
					item-column = CREDITED_AMT
					previewValue = value
			}
			--- TableColumn ---
				column-name = DEBITED_ACCOUNT !
				column-type = domain !
				domainAttribute = DEBITED_ACCOUNT !
				type = text
				id = bW_T_
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = DEBITED_ACCOUNT
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Debited Amount", fr = "Montant débité", de = "Belasteter Betrag"
				column-name = DEBITED_AMT
				type = amount
				id = x4__j
				column-computation = make-amount
				column-computation-parameters = "DEBITED_AMOUNT,DEBITED_CURR"
				table-column-width = 5
				tid = 110313627171508
			{
				--- TableColumnItem ---
					item-column = DEBITED_AMT
					previewValue = value
			}
			--- TableColumn ---
				column-name = EXCH_RATE !
				column-type = domain !
				domainAttribute = EXCH_RATE !
				type = text
				id = DT2_x
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = EXCH_RATE
					format = decimal.5-digits
					previewValue = value
			}
			--- TableColumn ---
				column-name = CURR_PAIR !
				column-type = domain !
				domainAttribute = CURR_PAIR !
				type = text
				id = Hw888
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = CURR_PAIR
					previewValue = value
			}
			--- TableColumn ---
				column-name = VALUE_DATE !
				column-type = domain !
				domainAttribute = VALUE_DATE !
				type = text
				id = z4U__
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = VALUE_DATE
					format = date
					previewValue = value
			}
			--- TableColumn ---
				column-name = STATUS !
				column-type = domain !
				domainAttribute = STATUS !
				type = text
				id = h_CJ_
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = STATUS
					previewValue = value
			}
			--- TableColumn ---
				column-name = order_id !
				column-type = domain !
				domainAttribute = order_id !
				type = text
				column-is-part-of-filter = false
				column-visibility = never-visible
				id = M04_5
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = order_id
					format = integer
					previewValue = value
			}
			--- TableColumn ---
				column-name = CREDITED_AMOUNT !
				column-type = domain !
				domainAttribute = CREDITED_AMOUNT !
				type = text
				column-visibility = never-visible
				id = jI__1
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = CREDITED_AMOUNT
					format = decimal
					previewValue = value
			}
			--- TableColumn ---
				column-name = CREDITED_CURR !
				column-type = domain !
				domainAttribute = CREDITED_CURR !
				type = text
				column-visibility = never-visible
				id = O__73
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = CREDITED_CURR
					previewValue = value
			}
			--- TableColumn ---
				column-name = DEBITED_AMOUNT !
				column-type = domain !
				domainAttribute = DEBITED_AMOUNT !
				type = text
				column-visibility = never-visible
				id = A_o_U
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = DEBITED_AMOUNT
					format = decimal
					previewValue = value
			}
			--- TableColumn ---
				column-name = DEBITED_CURR !
				column-type = domain !
				domainAttribute = DEBITED_CURR !
				type = text
				column-visibility = never-visible
				id = GG_R3
				table-column-width = 5
			{
				--- TableColumnItem ---
					item-column = DEBITED_CURR
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = PORTFOLIO_NAME
				sort-rank = 3
			--- TableSort ---
				sort-column-name = CURR_PAIR
				sort-rank = 4
			--- TableSort ---
				sort-column-name = CREATION_DATE
				sort-direction = descending
				sort-rank = 2
		}
	}
}