# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSOrderList:OrderListDetailedList"
	cssClass = nodeco
	bean-define = DSBean.AAADSOrderList.OrderListDetailedList
	bean-name = OrderListDetailedList
	id = FxSpotDetailedList_Z1_ha
{
	--- Box ---
		boxType = vertical
	{
		--- TableTree ---
			display-checkbox = true
			table-filter-layer = true
			id = tv_03
			table-column-count = 24 !
			table-columns-width = "4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4" !
		{
			--- TableColumn ---
				labels en = Validate, fr = Valider, de = Bestätigen
				column-name = VALIDATE
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				id = of1k1
				table-column-width = 4
				tid = 15395757028365
			{
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "\"true\".equals(<udp:item column=\"ACTION_RIGHT_VALIDATE\"/>.toString())"
						technicalName = Condition
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips en = "Validate Order", fr = "Valider l\'ordre", de = Bestätigen
							horizontalAlignment = center
							icon = tick
							id = d2N3_
							tid = 16255180944677
						{
							Event OnClick (submit) S
							// "Execute selected Update Field TA Function"
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = validate ud
								modal = false
								only-changed = false
								prevalidate = false
								DSEntityCode = "<udp:item column=\"ORDER_CODE\"/>" ud
							}
						}
					}
				}
			}
			--- TableColumn ---
				labels en = Reject, fr = Rejeter, de = Ablehnen
				column-name = REJECT
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				id = Z_3_m
				table-column-width = 4
				tid = 15395772702989
			{
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "\"true\".equals(<udp:item column=\"ACTION_RIGHT_VALIDATE\"/>.toString())"
						technicalName = Condition
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips en = "Reject Order", fr = "Rejeter l\'ordre", de = Ablehnen
							horizontalAlignment = center
							icon = cross
							id = y_12_
							tid = 16265236929936
						{
							Event OnClick (submit) S
							// "Execute selected Update Field TA Function"
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = reject ud
								modal = false
								only-changed = false
								prevalidate = false
								DSEntityCode = "<udp:item column=\"ORDER_CODE\"/>" ud
							}
						}
					}
				}
			}
			--- TableColumn ---
				labels en = Cancel, fr = Annuler, de = Streichen
				column-name = CANCEL
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				id = Z88_b
				table-column-width = 4
				tid = 15395774360446
			{
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "\"true\".equals(<udp:item column=\"ACTION_RIGHT_CANCEL\"/>.toString())"
						technicalName = Condition
						boxType = vertical
						isWidgetSelected = true
					{
						--- Icon ---
							toolTips en = "Cancel Order", fr = "Annuler l\'ordre", de = Streichen
							horizontalAlignment = center
							icon = delete
							id = j9t_s
							tid = 16278221953797
						{
							Event OnClick (submit) S
							// "Execute selected Update Field TA Function"
							{
								method = post
								call-URI = "<pageflow:continuation/>"
								target = self
								flow-action = cancel ud
								modal = false
								only-changed = false
								prevalidate = false
								DSEntityCode = "<udp:item column=\"ORDER_CODE\"/>" ud
							}
						}
					}
				}
			}
			--- TableColumn ---
				labels en = View, fr = Voir, de = Ansehen
				column-name = VIEW
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				id = x30tA
				table-column-width = 4
				tid = 1056186571741659
			{
				--- Icon ---
					toolTips de = "Auftrag ansehen", fr = "Voir l’ordre", en = "View Order"
					horizontalAlignment = "${corporatehalign}"
					icon = application_form_magnify
					id = AXQ_2
					tid = 1056164126771419
				{
					Event OnClick (submit) S
					{
						method = post
						call-URI = "<pageflow:continuation/>"
						target = self
						flow-action = view ud
						code = "<udp:item column=\"ORDER_CODE\"/>" ud
						modal = false
						only-changed = false
						prevalidate = false
					}
				}
			}
			--- TableColumn ---
				labels en = Select, de = Select, fr = Selection
				column-name = ORDER_SELECT
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				id = V91D_
				table-column-width = 4
				tid = 1043097322546301
			{
				--- CheckBox ---
					column-checkbox-action = orderSel
					column-checkbox-identifier = order_id
					checkbox-group-names = ORDER_HIER_STR
					horizontalTextPosition = trail
					id = btn_V_5N_
			}
			--- TableColumn ---
				labels en = "Order Hierarchy"
				column-display-grouping = true
				column-name = ORDER_HIER_STR
				column-type = placeholder !
				type = text
				column-sortable = false !
				id = G_8yt
				table-column-width = 4
				tid = 1066073734465972
			{
				--- TableGroup ---
					toolTips en = "Order Hierarchy"
					aggregateData = false
					group-column-name = ORDER_HIER_STR
					group-sorting-column-name = ORDER_HIER_STR
					group-sorting-direction = ascending
					hierarchy = true
					group-rank = 1
					tid = 1043085931981019
			}
			--- TableColumn ---
				column-name = CREATION_DATE !
				column-type = domain !
				domainAttribute = CREATION_DATE !
				type = text
				id = CREATION_DATE
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = CREATION_DATE
					format = datetime.date-only
					previewValue = value
			}
			--- TableColumn ---
				column-name = ORDER_DATE !
				column-type = domain !
				domainAttribute = ORDER_DATE !
				type = text
				id = Rb74_
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = ORDER_DATE
					format = datetime.date-only
					previewValue = value
			}
			--- TableColumn ---
				column-name = PORTFOLIO_NAME !
				column-type = domain !
				domainAttribute = PORTFOLIO_NAME !
				type = text
				id = i_00_
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = PORTFOLIO_NAME
					previewValue = value
			}
			--- TableColumn ---
				column-name = ORDER_NATURE !
				column-type = domain !
				domainAttribute = ORDER_NATURE !
				type = text
				id = ej_yP
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = ORDER_NATURE
					previewValue = value
			}
			--- TableColumn ---
				column-name = CREDITED_ACCOUNT !
				column-type = domain !
				domainAttribute = CREDITED_ACCOUNT !
				type = text
				id = Rp_44
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = CREDITED_ACCOUNT
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Credited Amount", fr = "Montant crédité", de = Gutschriftsbetrag
				column-name = CREDITED_AMT
				type = amount
				id = iI_B4
				column-computation = make-amount
				column-computation-parameters = "CREDITED_AMOUNT,CREDITED_CURR"
				table-column-width = 4
				tid = 15395774631199
			{
				--- TableColumnItem ---
					item-column = CREDITED_AMT
					previewValue = value
			}
			--- TableColumn ---
				column-name = DEBITED_ACCOUNT !
				column-type = domain !
				domainAttribute = DEBITED_ACCOUNT !
				type = text
				id = bW_T_
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = DEBITED_ACCOUNT
					previewValue = value
			}
			--- TableColumn ---
				labels en = "Debited Amount", fr = "Montant débité", de = "Belasteter Betrag"
				column-name = DEBITED_AMT
				type = amount
				id = C_0L_
				column-computation = make-amount
				column-computation-parameters = "DEBITED_AMOUNT,DEBITED_CURR"
				table-column-width = 4
				tid = 15395775643638
			{
				--- TableColumnItem ---
					item-column = DEBITED_AMT
					previewValue = value
			}
			--- TableColumn ---
				column-name = EXCH_RATE !
				column-type = domain !
				domainAttribute = EXCH_RATE !
				type = text
				id = DT2_x
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = EXCH_RATE
					format = decimal.5-digits
					previewValue = value
			}
			--- TableColumn ---
				column-name = CURR_PAIR !
				column-type = domain !
				domainAttribute = CURR_PAIR !
				type = text
				id = Hw888
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = CURR_PAIR
					previewValue = value
			}
			--- TableColumn ---
				column-name = VALUE_DATE !
				column-type = domain !
				domainAttribute = VALUE_DATE !
				type = text
				id = z4U__
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = VALUE_DATE
					format = date
					previewValue = value
			}
			--- TableColumn ---
				column-name = STATUS !
				column-type = domain !
				domainAttribute = STATUS !
				type = text
				id = h_CJ_
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = STATUS
					previewValue = value
			}
			--- TableColumn ---
				column-name = ORDER_CODE !
				column-type = domain !
				domainAttribute = ORDER_CODE !
				type = text
				column-visibility = never-visible
				id = ORDER_CODE
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = ORDER_CODE
					previewValue = value
			}
			--- TableColumn ---
				column-name = order_id !
				column-type = domain !
				domainAttribute = order_id !
				type = text
				column-is-part-of-filter = false
				column-visibility = never-visible
				id = M04_5
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = order_id
					format = integer
					previewValue = value
			}
			--- TableColumn ---
				column-name = CREDITED_AMOUNT !
				column-type = domain !
				domainAttribute = CREDITED_AMOUNT !
				type = text
				column-visibility = never-visible
				id = jI__1
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = CREDITED_AMOUNT
					format = decimal
					previewValue = value
			}
			--- TableColumn ---
				column-name = CREDITED_CURR !
				column-type = domain !
				domainAttribute = CREDITED_CURR !
				type = text
				column-visibility = never-visible
				id = O__73
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = CREDITED_CURR
					previewValue = value
			}
			--- TableColumn ---
				column-name = DEBITED_AMOUNT !
				column-type = domain !
				domainAttribute = DEBITED_AMOUNT !
				type = text
				column-visibility = never-visible
				id = A_o_U
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = DEBITED_AMOUNT
					format = decimal
					previewValue = value
			}
			--- TableColumn ---
				column-name = DEBITED_CURR !
				column-type = domain !
				domainAttribute = DEBITED_CURR !
				type = text
				column-visibility = never-visible
				id = GG_R3
				table-column-width = 4
			{
				--- TableColumnItem ---
					item-column = DEBITED_CURR
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = PORTFOLIO_NAME
				sort-rank = 3
			--- TableSort ---
				sort-column-name = CURR_PAIR
				sort-rank = 4
			--- TableSort ---
				sort-column-name = CREATION_DATE
				sort-direction = descending
				sort-rank = 2
			--- TableExtra ---
				domainAttribute = ACTION_RIGHT_VALIDATE
			--- TableExtra ---
				domainAttribute = ACTION_RIGHT_CANCEL
		}
	}
}