# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	containment = container
	domainEntity = "AAADSDomain:DomainContext"
	cssClass = nodeco
	bean-define = DSActivityBean.AAADSDomain.DomainContext
	bean-name = DomainContext
	id = AllocationRuleCreate_jev_u
{
	--- Box ---
		boxType = vertical
	{
		--- Conditional ---
			indexOfSelectedChild = 10
		{
			--- ConditionalBody ---
				conditionLang = DSEL
				javaCode = "DomainContext.orderAllocNatE ==AAAEnumerations::DomainAAAOrderAllocNatE::GlobalOrderQuantity"
				technicalName = "Global Ord Qty"
				boxType = vertical
				isWidgetVisible = false
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/extstrategyelement/orderallocation/globalOrderQuantity/GlobalOrderQuantityCreate.module
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/extstrategyelement/orderallocation/globalOrderQuantity/GlobalOrderQuantityList.module
			}
			--- ConditionalBody ---
				conditionLang = DSEL
				javaCode = "DomainContext.orderAllocNatE == AAAEnumerations::DomainAAAOrderAllocNatE::IndividualOrderQuantity"
				technicalName = "Instr Order Qty"
				boxType = vertical
				isWidgetVisible = false
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/extstrategyelement/orderallocation/instrOrderQuantity/InstrOrderQuantityCreate.module
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/extstrategyelement/orderallocation/instrOrderQuantity/InstrOrderQuantityList.module
			}
			--- ConditionalBody ---
				conditionLang = DSEL
				javaCode = "DomainContext.orderAllocNatE == AAAEnumerations::DomainAAAOrderAllocNatE::ResultingInstrumentQuantity"
				technicalName = "Instr Result Qty"
				boxType = vertical
				isWidgetVisible = false
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/extstrategyelement/orderallocation/instrResultQuantity/InstrResultQuantityCreate.module
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/extstrategyelement/orderallocation/instrResultQuantity/InstrResultQuantityList.module
			}
			--- ConditionalBody ---
				conditionLang = DSEL
				javaCode = "DomainContext.orderAllocNatE == AAAEnumerations::DomainAAAOrderAllocNatE::IndividOrderPercentOfPort"
				technicalName = "Instr Order % ptf"
				boxType = vertical
				isWidgetVisible = false
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/instrOrderPercentOfPtf/InstrOrderPercentOfPtfCreate.module
				--- Include ---
					includeSrc = "" !
					resource:///Default/instrOrderPercentOfPtf/InstrOrderPercentOfPtfList.module
			}
			--- ConditionalBody ---
				conditionLang = DSEL
				javaCode = "DomainContext.orderAllocNatE ==AAAEnumerations::DomainAAAOrderAllocNatE::ResultingInstrPercentOfPort"
				technicalName = "Instr Res % ptf"
				boxType = vertical
				isWidgetVisible = false
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/instrResultPercentOfPtf/InstrResultPercentOfPtfCreate.module
				--- Include ---
					includeSrc = "" !
					resource:///Default/instrResultPercentOfPtf/InstrResultPercentOfPtfList.module
			}
			--- ConditionalBody ---
				conditionLang = DSEL
				javaCode = "DomainContext.orderAllocNatE == AAAEnumerations::DomainAAAOrderAllocNatE::ResultingMktSegPercentOfPort"
				technicalName = "Mkt Sgt Result % of ptf"
				boxType = vertical
				isWidgetVisible = false
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/mktSegResultPercentOfPtf/MktSegResultPercentOfPtfCreate.module
				--- Include ---
					includeSrc = "" !
					resource:///Default/mktSegResultPercentOfPtf/MktSegResultPercentOfPtfList.module
			}
			--- ConditionalBody ---
				conditionLang = DSEL
				javaCode = "DomainContext.orderAllocNatE == AAAEnumerations::DomainAAAOrderAllocNatE::SwitchInstruments"
				technicalName = "Switch instr"
				boxType = vertical
				isWidgetVisible = false
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/extstrategyelement/orderallocation/switchInstr/SwitchInstrCreate.module
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/extstrategyelement/orderallocation/switchInstr/SwitchInstrList.module
			}
			--- ConditionalBody ---
				conditionLang = DSEL
				javaCode = "DomainContext.orderAllocNatE == AAAEnumerations::DomainAAAOrderAllocNatE::ResultingCashPercentOfPort"
				technicalName = "Cash Res % ptf"
				boxType = vertical
				isWidgetVisible = false
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/cashResultPercentOfPtf/CashResultPercentOfPtfCreate.module
				--- Include ---
					includeSrc = "" !
					resource:///Default/cashResultPercentOfPtf/CashResultPercentOfPtfList.module
			}
			--- ConditionalBody ---
				conditionLang = DSEL
				javaCode = "DomainContext.orderAllocNatE == AAAEnumerations::DomainAAAOrderAllocNatE::PortfolioOrderQuantity"
				technicalName = "Ptf Order Quantity"
				boxType = vertical
				isWidgetVisible = false
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/extstrategyelement/orderallocation/ptfOrderQuantity/PtfOrderQuantityCreate.module
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/extstrategyelement/orderallocation/ptfOrderQuantity/PtfOrderQuantityList.module
			}
			--- ConditionalBody ---
				conditionLang = DSEL
				javaCode = "DomainContext.orderAllocNatE == AAAEnumerations::DomainAAAOrderAllocNatE::PortfolioResultingQuantity"
				technicalName = "Ptf Result Quantity"
				boxType = vertical
				isWidgetVisible = false
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/extstrategyelement/orderallocation/ptfResultQuantity/PtfResultQuantityCreate.module
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/extstrategyelement/orderallocation/ptfResultQuantity/PtfResultQuantityList.module
			}
			--- ConditionalBody ---
				conditionLang = DSEL
				javaCode = "DomainContext.orderAllocNatE == AAAEnumerations::DomainAAAOrderAllocNatE::Conversion\r\n||\r\nDomainContext.orderAllocNatE == AAAEnumerations::DomainAAAOrderAllocNatE::Arbitrage"
				technicalName = ConversionOrArbitrage
				boxType = vertical
				isWidgetSelected = true
			{
				--- Spacer ---
					height = 15
					width = 4
				--- Box ---
					widgetBorder = box
				{
					--- Icon ---
						icon = information
						id = m_K20
					--- Label ---
						labels en = "Please note that for Conversion or Arbitrage allocation method, you can enter only one sell rule and one buy rule.", fr = "Veuillez noter que pour les méthodes d\'allocation Converion ou Arbitrage, vous ne pouvez saisir qu\'une règle de vente et qu\'une règle d\'achat.", de = "Bitte beachten Sie, dass Sie für die Verteilungsregeln Umwandlung und Arbitrage nur eine Verkaufs- und eine Kaufregel definieren können."
						nowrap = false
						tid = 1033314215903409
					--- Glue ---
				}
				--- Conditional ---
					indexOfSelectedChild = 0
				{
					--- ConditionalBody ---
						javaCode = "null!=<xsp-request:get-parameter name=\"test\"/>\r\n&amp;&amp;\r\n\"true\".equals(<xsp-request:get-parameter name=\"test\"/>.toString())"
						technicalName = Display
						boxType = vertical
						isWidgetSelected = true
					{
						--- Include ---
							includeSrc = "" !
							resource:///Default/module/aaa/administration/extstrategyelement/orderallocation/arbitrageOrConversion/RuleDefinition.module
					}
				}
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/extstrategyelement/orderallocation/arbitrageOrConversion/RuleList.module
			}
			--- ConditionalBody ---
				conditionLang = DSEL
				javaCode = "DomainContext.orderAllocNatE == AAAEnumerations::DomainAAAOrderAllocNatE::CombinedSellBuy"
				technicalName = Combined
				boxType = vertical
				isWidgetVisible = false
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/extstrategyelement/orderallocation/combinedSellBuy/CombinedBuySellCreate.module
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/extstrategyelement/orderallocation/combinedSellBuy/CombinedBuySellList.module
			}
			--- ConditionalBody ---
				conditionLang = DSEL
				javaCode = "DomainContext.orderAllocNatE == AAAEnumerations::DomainAAAOrderAllocNatE::InstrResultingOfMktSgt"
				technicalName = "Instr Result of Mkt Sgt"
				boxType = vertical
				isWidgetVisible = false
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/extstrategyelement/orderallocation/instrResultMktSeg/InstrResultMktSgtCreate.module
				--- Include ---
					includeSrc = "" !
					resource:///Default/module/aaa/administration/extstrategyelement/orderallocation/instrResultMktSeg/InstrResultMktSgtList.module
			}
			--- ConditionalBody ---
				conditionLang = DSEL
				javaCode = "DomainContext.orderAllocNatE == AAAEnumerations::DomainAAAOrderAllocNatE::InstrResPercentOfStratMktSgt"
				technicalName = "Instr Result % of Strategy Mkt Seg"
				boxType = vertical
				isWidgetVisible = false
			{
				--- Include ---
					includeSrc = "" !
					resource:///Default/instrResPercOfStratMktSeg/InstrResultPercentOfStratMktSegCreate.module
				--- Include ---
					includeSrc = "" !
					resource:///Default/instrResPercOfStratMktSeg/InstrResultPercentOfStratMktSegList.module
			}
		}
	}
}