<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="localReferenceApplication" nsURI="http://www.odcgroup.com/t24/application/localRefApplication/model/LocalReferenceApplication"
    nsPrefix="localReferenceApplication">
  <eClassifiers xsi:type="ecore:EClass" name="LocalReferenceApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="localField" lowerBound="1"
        upperBound="-1" eType="#//LocalField" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="forApplication" eType="ecore:EClass ../../../../../../../../../../com.odcgroup.mdf.ecore/src/main/model/mdf.ecore#//MdfClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocalField">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="groupName" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="groupName"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="localRefID" lowerBound="1"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        defaultValueLiteral="">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="localRefID"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="label" eType="ecore:EClass ../../../../../../../../../../com.odcgroup.translation.dsl/src-gen/com/odcgroup/translation/TranslationDsl.ecore#//Translations"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toolTip" eType="ecore:EClass ../../../../../../../../../../com.odcgroup.translation.dsl/src-gen/com/odcgroup/translation/TranslationDsl.ecore#//Translations"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
