# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	labels en = "Third Chrono List", de = "Liste zum zeitl. Ablauf der Drittpartei ", fr = "Liste de chronologie de tierce partie"
	domainEntity = "AAADSThirdChrono:ThirdChronoList"
	bean-define = DSBean.AAADSThirdChrono.ThirdChronoList
	bean-name = ThirdChronoList
	id = ThirdChronoListEdit_qy_c_
	tid = 40170582664556
{
	--- Box ---
		boxType = vertical
	{
		--- Grid ---
			cssClass = blank
			gridColumnCount = 4
			gridColumnsWidth = "25,25,25,25" !
			gridRowCount = 1
		{
			--- GridCell ---
				gridColumnWidth = 25
			{
				--- Button ---
					labels en = "Create Third Chrono", de = "Zeitl. Ablauf der Drittpartei erstellen", fr = "Créer la chronologie d\'une tierce partie"
					id = btn_T_Q__
					tid = 40217572344250
			}
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
			--- GridCell ---
				gridColumnWidth = 25
		}
		--- TableTree ---
			id = jK_5o
			table-column-count = 9 !
			table-columns-width = "11,11,11,11,11,11,11,11,11" !
		{
			--- TableColumn ---
				column-name = UPDATE
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				column-width = 3%
				id = au___
				table-column-width = 11
			{
				--- Icon ---
					toolTips en = "Update Third Chrono", de = "Zeitl. Ablauf Drittpartei ändern", fr = "Mettre à jour la chronologie de tierce partie"
					horizontalAlignment = center
					icon = application_edit
					id = h0pED
					tid = 40373411755404
			}
			--- TableColumn ---
				column-name = COPY
				column-type = placeholder !
				type = boolean
				column-sortable = false !
				column-width = 3%
				id = hy__W
				table-column-width = 11
			{
				--- Icon ---
					toolTips en = "Copy Third Chrono", de = "Zeitl. Ablauf der Drittpartei kopieren", fr = "Copier la chronologie Tiers"
					horizontalAlignment = center
					icon = application_double
					id = I91__
					tid = 40434379085889
			}
			--- TableColumn ---
				column-name = DELETE
				column-type = placeholder !
				type = text
				column-sortable = false !
				column-width = 3%
				id = pt__j
				table-column-width = 11
			{
				--- Icon ---
					toolTips en = "Delete Third Chrono", de = "Zeitl. Ablauf der Drittpartei löschen", fr = "Supprimer la chronologie d\'une tierce partie"
					horizontalAlignment = center
					icon = application_form_delete
					id = q___0
					tid = 40482258504642
			}
			--- TableColumn ---
				column-name = validityD !
				column-type = domain !
				domainAttribute = validityD !
				type = text
				id = validityD
				table-column-width = 11
			{
				--- TableColumnItem ---
					toolTips en = "View Third Chrono", de = "Zeitl. Ablauf Drittpartei ansehen", fr = "Voir la tierce partie"
					item-column = validityD
					format = datetime.date-only
					previewValue = value
					tid = 40246927235444
			}
			--- TableColumn ---
				column-name = natureE !
				column-type = domain !
				domainAttribute = natureE !
				type = text
				id = natureE
				table-column-width = 11
			{
				--- TableColumnItem ---
					item-column = natureE
					previewValue = value
			}
			--- TableColumn ---
				column-name = valueN !
				column-type = domain !
				domainAttribute = valueN !
				type = text
				id = valueN
				table-column-width = 11
			{
				--- TableColumnItem ---
					item-column = valueN
					format = decimal.detailed
					previewValue = value
			}
			--- TableColumn ---
				column-name = currencyCode !
				column-type = domain !
				domainAttribute = currencyCode !
				type = text
				id = currencyCode
				table-column-width = 11
			{
				--- TableColumnItem ---
					item-column = currencyCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = currencyId !
				column-type = domain !
				domainAttribute = currencyId !
				type = text
				column-visibility = never-visible
				id = currencyId
				table-column-width = 11
			{
				--- TableColumnItem ---
					item-column = currencyId
					format = integer
					previewValue = value
			}
			--- TableColumn ---
				column-name = thirdId !
				column-type = domain !
				domainAttribute = thirdId !
				type = text
				column-visibility = never-visible
				id = thirdId
				table-column-width = 11
			{
				--- TableColumnItem ---
					item-column = thirdId
					format = integer
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = validityD
				sort-direction = descending
				sort-rank = 1
			--- TableSort ---
				sort-column-name = natureE
				sort-rank = 2
		}
	}
}