# UTF-8
metamodelVersion = 8.0.0.20130123

--- Module ---
	domainEntity = "AAADSThirdChrono:ThirdChronoList"
	bean-define = DSBean.AAADSThirdChrono.ThirdChronoList
	bean-name = ThirdChronoList
	id = ThirdChronoList_so_11
{
	--- Box ---
		boxType = vertical
		width = 0
	{
		--- TableTree ---
			id = jsqd_
			table-column-count = 6 !
			table-columns-width = "16,16,16,16,16,16" !
		{
			--- TableColumn ---
				column-name = validityD !
				column-type = domain !
				domainAttribute = validityD !
				id = validityD
				table-column-width = 16
			{
				--- TableColumnItem ---
					toolTips en = "View Third Chrono", de = "Zeitl. Ablauf Drittpartei ansehen", fr = "Voir la chronologie de tierce partie"
					item-column = validityD
					format = datetime.date-only
					previewValue = value
					tid = 41806265304389
			}
			--- TableColumn ---
				column-name = natureE !
				column-type = domain !
				domainAttribute = natureE !
				id = natureE
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = natureE
					previewValue = value
			}
			--- TableColumn ---
				column-name = valueN !
				column-type = domain !
				domainAttribute = valueN !
				id = valueN
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = valueN
					format = decimal.detailed
					previewValue = value
			}
			--- TableColumn ---
				column-name = currencyCode !
				column-type = domain !
				domainAttribute = currencyCode !
				id = currencyCode
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = currencyCode
					previewValue = value
			}
			--- TableColumn ---
				column-name = thirdId !
				column-type = domain !
				domainAttribute = thirdId !
				type = text
				column-visibility = never-visible
				id = thirdId
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = thirdId
					format = integer
					previewValue = value
			}
			--- TableColumn ---
				column-name = currencyId !
				column-type = domain !
				domainAttribute = currencyId !
				type = text
				column-visibility = never-visible
				id = currencyId
				table-column-width = 16
			{
				--- TableColumnItem ---
					item-column = currencyId
					format = integer
					previewValue = value
			}
			--- TableSort ---
				sort-column-name = thirdCode
				sort-rank = 1
			--- TableSort ---
				sort-column-name = validityD
				sort-direction = descending
				sort-rank = 2
			--- TableSort ---
				sort-column-name = natureE
				sort-rank = 3
		}
	}
}